<?php
// This is file installs the map data for the YoungstownWWII variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Venetia', 'Coast', 'No', 3, 197, 269, 201, 273),
	array('Milan', 'Land', 'Yes', 3, 179, 256, 180, 260),
	array('Piedmont', 'Coast', 'No', 3, 161, 266, 161, 266),
	array('Rome', 'Coast', 'Yes', 3, 187, 277, 188, 279),
	array('Apulia', 'Coast', 'No', 3, 224, 295, 231, 294),
	array('Naples', 'Coast', 'Yes', 3, 241, 321, 233, 332),
	array('Tirane', 'Coast', 'Yes', 3, 270, 298, 267, 294),
	array('Tripoli', 'Coast', 'Yes', 3, 226, 390, 233, 395),
	array('Cyrene', 'Coast', 'No', 3, 264, 379, 261, 392),
	array('Fezzan', 'Land', 'No', 3, 255, 430, 263, 433),
	array('Addis Adaba', 'Coast', 'Yes', 3, 390, 490, 389, 491),
	array('Mogadishu', 'Coast', 'Yes', 3, 464, 506, 458, 528),
	array('Akito', 'Coast', 'No', 4, 933, 237, 937, 246),
	array('Tokyo', 'Coast', 'Yes', 4, 944, 278, 948, 273),
	array('Kyoto', 'Coast', 'Yes', 4, 923, 277, 926, 272),
	array('Shizuoko', 'Coast', 'No', 4, 941, 288, 938, 290),
	array('Osaka', 'Coast', 'Yes', 4, 912, 301, 911, 296),
	array('Kagoshima Prefecture', 'Coast', 'No', 4, 891, 302, 890, 305),
	array('Seoul', 'Coast', 'Yes', 4, 855, 229, 857, 236),
	array('Manchuria', 'Coast', 'No', 4, 844, 190, 831, 177),
	array('Shendong', 'Coast', 'Yes', 4, 831, 214, 812, 213),
	array('Shanghai', 'Coast', 'Yes', 4, 847, 324, 845, 327),
	array('Kiel', 'Coast', 'Yes', 5, 164, 166, 168, 168),
	array('Berlin', 'Coast', 'Yes', 5, 184, 176, 182, 180),
	array('Prussia', 'Coast', 'No', 5, 216, 172, 220, 177),
	array('East Prussia (EPr)', 'Coast', 'No', 5, 253, 154, 252, 154),
	array('Cologne', 'Land', 'Yes', 5, 153, 205, 154, 210),
	array('Saxony', 'Land', 'No', 5, 187, 194, 184, 201),
	array('Swabia', 'Land', 'No', 5, 163, 219, 166, 216),
	array('Munich', 'Land', 'Yes', 5, 180, 225, 181, 231),
	array('Tyrolia', 'Land', 'No', 5, 207, 232, 208, 229),
	array('Vienna', 'Land', 'Yes', 5, 224, 229, 227, 232),
	array('Prague', 'Land', 'Yes', 5, 230, 210, 229, 215),
	array('Slovakia', 'Land', 'No', 5, 253, 214, 265, 213),
	array('Breslau', 'Land', 'Yes', 5, 229, 196, 237, 197),
	array('Clyde', 'Coast', 'No', 1, 67, 113, 67, 117),
	array('Edinburgh', 'Coast', 'Yes', 1, 85, 110, 83, 120),
	array('Yorkshire', 'Coast', 'No', 1, 89, 143, 89, 149),
	array('Liverpool', 'Coast', 'Yes', 1, 68, 139, 74, 139),
	array('Wales', 'Coast', 'No', 1, 76, 190, 74, 193),
	array('London', 'Coast', 'Yes', 1, 95, 186, 95, 189),
	array('Cairo', 'Coast', 'Yes', 1, 323, 394, 319, 402),
	array('Bayuda', 'Coast', 'No', 1, 343, 425, 315, 429),
	array('Kenya', 'Coast', 'No', 1, 394, 584, 389, 573),
	array('Puntland', 'Coast', 'No', 1, 445, 501, 442, 508),
	array('Aden', 'Coast', 'Yes', 1, 432, 461, 434, 467),
	array('Palestine', 'Coast', 'No', 1, 370, 355, 364, 358),
	array('Sindh', 'Coast', 'No', 1, 537, 343, 537, 356),
	array('Kashmir', 'Land', 'No', 1, 563, 293, 565, 299),
	array('Delhi', 'Land', 'Yes', 1, 589, 325, 598, 337),
	array('Deccan Plateau', 'Land', 'No', 1, 609, 390, 612, 382),
	array('Calcutta', 'Coast', 'Yes', 1, 645, 394, 663, 361),
	array('Madras', 'Coast', 'Yes', 1, 616, 471, 617, 468),
	array('Bombay Presidency', 'Coast', 'No', 1, 578, 390, 573, 382),
	array('Singapore', 'Coast', 'Yes', 1, 772, 506, 769, 500),
	array('Burgundy', 'Land', 'No', 2, 138, 236, 137, 242),
	array('Marseille', 'Coast', 'Yes', 2, 120, 285, 141, 275),
	array('Picardy', 'Coast', 'No', 2, 110, 219, 110, 216),
	array('Paris', 'Land', 'Yes', 2, 104, 240, 107, 243),
	array('Brest', 'Coast', 'Yes', 2, 75, 238, 77, 241),
	array('Tunisia', 'Coast', 'No', 2, 177, 350, 176, 360),
	array('Sahara', 'Land', 'No', 2, 140, 408, 123, 453),
	array('Central Africa', 'Land', 'No', 2, 253, 483, 244, 487),
	array('Mali', 'Coast', 'No', 2, 32, 470, 53, 491),
	array('Algiers', 'Coast', 'Yes', 2, 154, 346, 138, 362),
	array('Laos', 'Land', 'No', 2, 755, 390, 755, 388),
	array('Phnom Penh', 'Coast', 'Yes', 2, 779, 445, 786, 444),
	array('Saigon', 'Coast', 'Yes', 2, 809, 456, 810, 453),
	array('Annam', 'Coast', 'No', 2, 805, 415, 814, 427),
	array('Bielorussia', 'Land', 'No', 6, 317, 130, 313, 132),
	array('Ukraine', 'Land', 'No', 6, 362, 199, 334, 184),
	array('Sevastopol', 'Coast', 'Yes', 6, 380, 252, 384, 249),
	array('Stalingrad', 'Coast', 'Yes', 6, 409, 254, 415, 242),
	array('Caucasus', 'Coast', 'No', 6, 427, 285, 433, 281),
	array('Kazakhstan', 'Land', 'No', 6, 442, 222, 443, 223),
	array('Moscow', 'Land', 'Yes', 6, 389, 134, 395, 124),
	array('Omsk', 'Land', 'Yes', 6, 499, 180, 501, 182),
	array('Siberia', 'Coast', 'No', 6, 705, 94, 692, 76),
	array('Irkutsk', 'Land', 'Yes', 6, 584, 169, 574, 179),
	array('Turkmenistan', 'Land', 'No', 6, 494, 278, 492, 281),
	array('Kamchatka', 'Coast', 'No', 6, 910, 41, 813, 69),
	array('Vladivostok', 'Coast', 'Yes', 6, 874, 177, 864, 154),
	array('Sakhalin', 'Coast', 'No', 6, 891, 136, 890, 134),
	array('Leningrad', 'Coast', 'Yes', 6, 352, 81, 347, 75),
	array('Leningrad (North Coast)', 'Coast', 'No', 6, 385, 34, 391, 37),
	array('Leningrad (South Coast)', 'Coast', 'No', 6, 308, 109, 314, 107),
	array('Ireland', 'Coast', 'Yes', 0, 26, 163, 25, 159),
	array('Norway', 'Coast', 'Yes', 0, 140, 105, 143, 108),
	array('Sweden', 'Coast', 'Yes', 0, 202, 70, 199, 76),
	array('Finland', 'Coast', 'No', 0, 260, 62, 267, 62),
	array('Estonia', 'Coast', 'No', 0, 271, 111, 282, 111),
	array('Lithuania', 'Coast', 'No', 0, 274, 139, 276, 139),
	array('Latvia', 'Coast', 'Yes', 0, 285, 127, 285, 127),
	array('Denmark', 'Coast', 'Yes', 0, 159, 147, 158, 148),
	array('Holland', 'Coast', 'Yes', 0, 129, 191, 130, 195),
	array('Belgium', 'Coast', 'Yes', 0, 128, 208, 135, 215),
	array('Navarra', 'Coast', 'No', 0, 81, 293, 86, 295),
	array('Portugal', 'Coast', 'Yes', 0, 53, 315, 54, 316),
	array('Spain', 'Coast', 'Yes', 0, 90, 329, 86, 332),
	array('Hungary', 'Land', 'No', 0, 261, 227, 262, 231),
	array('Croatia', 'Coast', 'No', 0, 232, 263, 232, 263),
	array('Bosnia', 'Coast', 'No', 0, 248, 269, 249, 273),
	array('Serbia', 'Land', 'Yes', 0, 270, 263, 273, 263),
	array('Macedonia', 'Land', 'No', 0, 279, 283, 280, 284),
	array('Greece', 'Coast', 'Yes', 0, 290, 329, 288, 301),
	array('Bulgaria', 'Coast', 'Yes', 0, 294, 273, 296, 275),
	array('Rumania', 'Coast', 'Yes', 0, 304, 250, 303, 252),
	array('Bessarabia', 'Coast', 'No', 0, 315, 226, 321, 231),
	array('Danzig', 'Coast', 'No', 0, 244, 179, 246, 181),
	array('Warsaw', 'Land', 'Yes', 0, 268, 166, 267, 168),
	array('Pinsk', 'Land', 'Yes', 0, 286, 193, 289, 193),
	array('Sudan', 'Coast', 'Yes', 0, 312, 481, 312, 484),
	array('South Sudan', 'Coast', 'No', 0, 348, 511, 348, 511),
	array('Istanbul', 'Coast', 'Yes', 0, 333, 297, 338, 304),
	array('Ankara', 'Coast', 'Yes', 0, 367, 291, 369, 291),
	array('Konya', 'Coast', 'No', 0, 338, 320, 341, 318),
	array('Armenia', 'Coast', 'No', 0, 402, 290, 399, 289),
	array('Baghdad', 'Coast', 'Yes', 0, 413, 323, 420, 338),
	array('Arabia', 'Coast', 'No', 0, 435, 416, 454, 416),
	array('Arabia (South Coast)', 'Coast', 'No', 0, 397, 418, 407, 419),
	array('Arabia (North Coast)', 'Coast', 'No', 0, 438, 369, 428, 372),
	array('Yemen', 'Coast', 'No', 0, 484, 440, 458, 458),
	array('Oman', 'Coast', 'No', 0, 502, 422, 503, 421),
	array('Persia', 'Coast', 'Yes', 0, 471, 351, 469, 351),
	array('Afghanistan', 'Land', 'Yes', 0, 512, 325, 512, 330),
	array('Ceylon', 'Coast', 'Yes', 0, 636, 506, 642, 510),
	array('Burma', 'Coast', 'Yes', 0, 707, 396, 706, 366),
	array('Thailand', 'Coast', 'Yes', 0, 734, 401, 735, 401),
	array('Thailand (West Coast)', 'Coast', 'No', 0, 740, 467, 745, 471),
	array('Thailand (East Coast)', 'Coast', 'No', 0, 760, 441, 762, 442),
	array('Yunnan', 'Land', 'No', 0, 727, 331, 731, 329),
	array('Tibet', 'Land', 'No', 0, 663, 292, 665, 285),
	array('Xinjiang', 'Land', 'Yes', 0, 626, 226, 618, 229),
	array('Mongolia', 'Land', 'Yes', 0, 714, 200, 669, 180),
	array('Inner Mongolia', 'Coast', 'No', 4, 754, 209, 756, 209),
	array('Qinghai', 'Land', 'No', 0, 696, 267, 729, 258),
	array('Peking', 'Coast', 'Yes', 4, 765, 236, 762, 237),
	array('Hebei', 'Coast', 'No', 4, 813, 260, 812, 260),
	array('Guangzhou', 'Coast', 'Yes', 0, 798, 353, 796, 354),
	array('Sumatra', 'Coast', 'No', 0, 749, 526, 750, 525),
	array('Borneo', 'Coast', 'Yes', 0, 863, 504, 860, 498),
	array('Java', 'Coast', 'Yes', 0, 818, 573, 819, 576),
	array('Formosa', 'Coast', 'Yes', 0, 863, 356, 863, 362),
	array('Philippines', 'Coast', 'Yes', 0, 925, 463, 924, 463),
	array('Karafuto', 'Coast', 'Yes', 0, 913, 168, 912, 170),
	array('North Atlantic Ocean', 'Sea', 'No', 0, 33, 81, 26, 83),
	array('Irish Sea', 'Sea', 'No', 0, 55, 159, 52, 167),
	array('English Channel', 'Sea', 'No', 0, 85, 214, 86, 211),
	array('Heligoland Bight', 'Sea', 'No', 0, 141, 159, 141, 160),
	array('Skagerrak', 'Sea', 'No', 0, 160, 123, 160, 124),
	array('Baltic Sea', 'Sea', 'No', 0, 236, 141, 235, 140),
	array('Gulf of Bothnia', 'Sea', 'No', 0, 235, 104, 238, 107),
	array('North Sea', 'Sea', 'No', 0, 113, 116, 112, 117),
	array('Norwegian Sea', 'Sea', 'No', 0, 136, 53, 135, 52),
	array('Barents Sea', 'Sea', 'No', 0, 371, 13, 377, 11),
	array('Black Sea', 'Sea', 'No', 0, 337, 277, 338, 265),
	array('Aegean Sea', 'Sea', 'No', 0, 308, 309, 306, 310),
	array('Eastern Mediterranean Sea', 'Sea', 'No', 0, 340, 339, 332, 338),
	array('Ionian Sea', 'Sea', 'No', 0, 260, 319, 261, 321),
	array('Adriatic Sea', 'Sea', 'No', 0, 242, 287, 242, 287),
	array('Gulf of Sirte', 'Sea', 'No', 0, 229, 363, 233, 364),
	array('Tyrrhenian Sea', 'Sea', 'No', 0, 191, 306, 196, 315),
	array('Gulf of Lyons', 'Sea', 'No', 0, 151, 303, 164, 303),
	array('Western Mediterranean Sea', 'Sea', 'No', 0, 153, 331, 156, 327),
	array('Mid Atlantic Ocean', 'Sea', 'No', 0, 18, 284, 23, 292),
	array('South Atlantic Ocean', 'Sea', 'No', 0, 18, 581, 27, 585),
	array('Red Sea', 'Sea', 'No', 0, 366, 410, 368, 411),
	array('Persian Gulf', 'Sea', 'No', 0, 469, 380, 483, 383),
	array('Gulf of Aden', 'Sea', 'No', 0, 467, 477, 460, 482),
	array('Arabian Sea', 'Sea', 'No', 0, 538, 396, 526, 440),
	array('Western Indian Ocean', 'Sea', 'No', 0, 574, 567, 583, 561),
	array('Horn of Africa', 'Sea', 'No', 0, 486, 527, 444, 589),
	array('Eastern Indian Ocean', 'Sea', 'No', 0, 704, 571, 709, 572),
	array('Bay of Bengal', 'Sea', 'No', 0, 673, 399, 644, 444),
	array('Andaman Sea', 'Sea', 'No', 0, 723, 480, 726, 480),
	array('Gulf of Thailand', 'Sea', 'No', 0, 827, 479, 826, 476),
	array('Java Sea', 'Sea', 'No', 0, 796, 530, 796, 532),
	array('Celebes Sea', 'Sea', 'No', 0, 930, 522, 930, 520),
	array('Timor Sea', 'Sea', 'No', 0, 957, 572, 959, 576),
	array('Gulf of Tonkin', 'Sea', 'No', 0, 802, 382, 801, 381),
	array('Vietnam', 'Coast', 'Yes', 0, 778, 372, 774, 363),
	array('South China Sea', 'Sea', 'No', 0, 853, 387, 871, 450),
	array('East China Sea', 'Sea', 'No', 0, 918, 337, 916, 337),
	array('Yellow Sea', 'Sea', 'No', 0, 855, 260, 854, 261),
	array('Sea of Japan', 'Sea', 'No', 0, 898, 198, 906, 250),
	array('South Pacific Ocean', 'Sea', 'No', 0, 957, 386, 950, 380),
	array('North Pacific Ocean', 'Sea', 'No', 0, 964, 88, 965, 83),
	array('Sea of Okhotsk', 'Sea', 'No', 0, 912, 118, 912, 117),
	array('Hubei', 'Land', 'No', 0, 764, 310, 782, 295),
	array('Lyons', 'Coast', 'Yes', 2, 115, 269, 115, 269),
	array('Hokkaido', 'Coast', 'No', 4, 927, 202, 930, 206),
	array('Morocco', 'Coast', 'Yes', 0, 94, 373, 91, 374),
	array('Bordeaux', 'Coast', 'Yes', 2, 95, 277, 92, 277),
	array('Syria', 'Coast', 'No', 2, 374, 332, 375, 331)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Venetia','Milan','No','Yes'),
	array('Venetia','Rome','No','Yes'),
	array('Venetia','Apulia','Yes','Yes'),
	array('Venetia','Tyrolia','No','Yes'),
	array('Venetia','Croatia','Yes','Yes'),
	array('Venetia','Adriatic Sea','Yes','No'),
	array('Milan','Piedmont','No','Yes'),
	array('Milan','Rome','No','Yes'),
	array('Milan','Tyrolia','No','Yes'),
	array('Piedmont','Rome','Yes','Yes'),
	array('Piedmont','Marseille','Yes','Yes'),
	array('Piedmont','Gulf of Lyons','Yes','No'),
	array('Rome','Apulia','No','Yes'),
	array('Rome','Naples','Yes','Yes'),
	array('Rome','Tyrrhenian Sea','Yes','No'),
	array('Rome','Gulf of Lyons','Yes','No'),
	array('Apulia','Naples','Yes','Yes'),
	array('Apulia','Ionian Sea','Yes','No'),
	array('Apulia','Adriatic Sea','Yes','No'),
	array('Naples','Ionian Sea','Yes','No'),
	array('Naples','Gulf of Sirte','Yes','No'),
	array('Naples','Tyrrhenian Sea','Yes','No'),
	array('Tirane','Bosnia','Yes','Yes'),
	array('Tirane','Macedonia','No','Yes'),
	array('Tirane','Greece','Yes','Yes'),
	array('Tirane','Adriatic Sea','Yes','No'),
	array('Tripoli','Cyrene','Yes','Yes'),
	array('Tripoli','Fezzan','No','Yes'),
	array('Tripoli','Tunisia','Yes','Yes'),
	array('Tripoli','Sahara','No','Yes'),
	array('Tripoli','Gulf of Sirte','Yes','No'),
	array('Cyrene','Fezzan','No','Yes'),
	array('Cyrene','Cairo','Yes','Yes'),
	array('Cyrene','Bayuda','No','Yes'),
	array('Cyrene','Eastern Mediterranean Sea','Yes','No'),
	array('Cyrene','Ionian Sea','Yes','No'),
	array('Cyrene','Gulf of Sirte','Yes','No'),
	array('Fezzan','Bayuda','No','Yes'),
	array('Fezzan','Sahara','No','Yes'),
	array('Fezzan','Central Africa','No','Yes'),
	array('Fezzan','Sudan','No','Yes'),
	array('Addis Adaba','Mogadishu','No','Yes'),
	array('Addis Adaba','Kenya','No','Yes'),
	array('Addis Adaba','Puntland','Yes','Yes'),
	array('Addis Adaba','South Sudan','Yes','Yes'),
	array('Addis Adaba','Red Sea','Yes','No'),
	array('Addis Adaba','Gulf of Aden','Yes','No'),
	array('Mogadishu','Kenya','Yes','Yes'),
	array('Mogadishu','Puntland','Yes','Yes'),
	array('Mogadishu','Gulf of Aden','Yes','No'),
	array('Mogadishu','Horn of Africa','Yes','No'),
	array('Akito','Tokyo','Yes','Yes'),
	array('Akito','Kyoto','Yes','Yes'),
	array('Akito','Sea of Japan','Yes','No'),
	array('Tokyo','Kyoto','No','Yes'),
	array('Tokyo','Shizuoko','Yes','Yes'),
	array('Tokyo','South Pacific Ocean','Yes','No'),
	array('Tokyo','North Pacific Ocean','Yes','No'),
	array('Kyoto','Shizuoko','No','Yes'),
	array('Kyoto','Osaka','No','Yes'),
	array('Kyoto','Kagoshima Prefecture','Yes','Yes'),
	array('Kyoto','Sea of Japan','Yes','No'),
	array('Shizuoko','Osaka','Yes','Yes'),
	array('Shizuoko','South Pacific Ocean','Yes','No'),
	array('Osaka','Kagoshima Prefecture','Yes','Yes'),
	array('Osaka','East China Sea','Yes','No'),
	array('Osaka','South Pacific Ocean','Yes','No'),
	array('Kagoshima Prefecture','East China Sea','Yes','No'),
	array('Seoul','Manchuria','Yes','Yes'),
	array('Seoul','Shendong','Yes','Yes'),
	array('Seoul','East China Sea','Yes','No'),
	array('Seoul','Yellow Sea','Yes','No'),
	array('Seoul','Sea of Japan','Yes','No'),
	array('Manchuria','Shendong','No','Yes'),
	array('Manchuria','Siberia','No','Yes'),
	array('Manchuria','Vladivostok','Yes','Yes'),
	array('Manchuria','Sea of Japan','Yes','No'),
	array('Shendong','Siberia','No','Yes'),
	array('Shendong','Mongolia','No','Yes'),
	array('Shendong','Inner Mongolia','Yes','Yes'),
	array('Shendong','Yellow Sea','Yes','No'),
	array('Shanghai','Hebei','Yes','Yes'),
	array('Shanghai','Guangzhou','Yes','Yes'),
	array('Shanghai','South China Sea','Yes','No'),
	array('Shanghai','East China Sea','Yes','No'),
	array('Shanghai','Hubei','No','Yes'),
	array('Kiel','Berlin','Yes','Yes'),
	array('Kiel','Cologne','No','Yes'),
	array('Kiel','Saxony','No','Yes'),
	array('Kiel','Denmark','Yes','Yes'),
	array('Kiel','Holland','Yes','Yes'),
	array('Kiel','Heligoland Bight','Yes','No'),
	array('Kiel','Baltic Sea','Yes','No'),
	array('Berlin','Prussia','Yes','Yes'),
	array('Berlin','Saxony','No','Yes'),
	array('Berlin','Breslau','No','Yes'),
	array('Berlin','Baltic Sea','Yes','No'),
	array('Prussia','Breslau','No','Yes'),
	array('Prussia','Danzig','Yes','Yes'),
	array('Prussia','Baltic Sea','Yes','No'),
	array('East Prussia (EPr)','Lithuania','Yes','Yes'),
	array('East Prussia (EPr)','Danzig','Yes','Yes'),
	array('East Prussia (EPr)','Warsaw','No','Yes'),
	array('East Prussia (EPr)','Baltic Sea','Yes','No'),
	array('Cologne','Saxony','No','Yes'),
	array('Cologne','Swabia','No','Yes'),
	array('Cologne','Munich','No','Yes'),
	array('Cologne','Burgundy','No','Yes'),
	array('Cologne','Holland','No','Yes'),
	array('Cologne','Belgium','No','Yes'),
	array('Saxony','Munich','No','Yes'),
	array('Saxony','Prague','No','Yes'),
	array('Saxony','Breslau','No','Yes'),
	array('Swabia','Munich','No','Yes'),
	array('Swabia','Burgundy','No','Yes'),
	array('Munich','Tyrolia','No','Yes'),
	array('Munich','Prague','No','Yes'),
	array('Tyrolia','Vienna','No','Yes'),
	array('Tyrolia','Prague','No','Yes'),
	array('Tyrolia','Croatia','No','Yes'),
	array('Vienna','Prague','No','Yes'),
	array('Vienna','Hungary','No','Yes'),
	array('Vienna','Croatia','No','Yes'),
	array('Prague','Slovakia','No','Yes'),
	array('Prague','Breslau','No','Yes'),
	array('Prague','Hungary','No','Yes'),
	array('Slovakia','Breslau','No','Yes'),
	array('Slovakia','Hungary','No','Yes'),
	array('Slovakia','Bessarabia','No','Yes'),
	array('Slovakia','Danzig','No','Yes'),
	array('Slovakia','Warsaw','No','Yes'),
	array('Breslau','Danzig','No','Yes'),
	array('Clyde','Edinburgh','Yes','Yes'),
	array('Clyde','Liverpool','Yes','Yes'),
	array('Clyde','North Atlantic Ocean','Yes','No'),
	array('Clyde','Norwegian Sea','Yes','No'),
	array('Edinburgh','Yorkshire','Yes','Yes'),
	array('Edinburgh','Liverpool','No','Yes'),
	array('Edinburgh','North Sea','Yes','No'),
	array('Edinburgh','Norwegian Sea','Yes','No'),
	array('Yorkshire','Liverpool','No','Yes'),
	array('Yorkshire','Wales','No','Yes'),
	array('Yorkshire','London','Yes','Yes'),
	array('Yorkshire','North Sea','Yes','No'),
	array('Liverpool','Wales','Yes','Yes'),
	array('Liverpool','North Atlantic Ocean','Yes','No'),
	array('Liverpool','Irish Sea','Yes','No'),
	array('Wales','London','Yes','Yes'),
	array('Wales','Irish Sea','Yes','No'),
	array('Wales','English Channel','Yes','No'),
	array('London','English Channel','Yes','No'),
	array('London','North Sea','Yes','No'),
	array('Cairo','Bayuda','Yes','Yes'),
	array('Cairo','Palestine','Yes','Yes'),
	array('Cairo','Arabia','No','Yes'),
	array('Cairo','Arabia (South Coast)','Yes','No'),
	array('Cairo','Eastern Mediterranean Sea','Yes','No'),
	array('Cairo','Red Sea','Yes','No'),
	array('Bayuda','Sudan','Yes','Yes'),
	array('Bayuda','Red Sea','Yes','No'),
	array('Kenya','South Sudan','No','Yes'),
	array('Kenya','Horn of Africa','Yes','No'),
	array('Puntland','Gulf of Aden','Yes','No'),
	array('Aden','Arabia','No','Yes'),
	array('Aden','Arabia (South Coast)','Yes','No'),
	array('Aden','Yemen','Yes','Yes'),
	array('Aden','Red Sea','Yes','No'),
	array('Aden','Gulf of Aden','Yes','No'),
	array('Palestine','Baghdad','No','Yes'),
	array('Palestine','Arabia','No','Yes'),
	array('Palestine','Eastern Mediterranean Sea','Yes','No'),
	array('Palestine','Syria','Yes','Yes'),
	array('Sindh','Kashmir','No','Yes'),
	array('Sindh','Delhi','No','Yes'),
	array('Sindh','Bombay Presidency','Yes','Yes'),
	array('Sindh','Persia','Yes','Yes'),
	array('Sindh','Afghanistan','No','Yes'),
	array('Sindh','Arabian Sea','Yes','No'),
	array('Kashmir','Delhi','No','Yes'),
	array('Kashmir','Afghanistan','No','Yes'),
	array('Kashmir','Tibet','No','Yes'),
	array('Delhi','Deccan Plateau','No','Yes'),
	array('Delhi','Calcutta','No','Yes'),
	array('Delhi','Bombay Presidency','No','Yes'),
	array('Delhi','Tibet','No','Yes'),
	array('Deccan Plateau','Calcutta','No','Yes'),
	array('Deccan Plateau','Madras','No','Yes'),
	array('Deccan Plateau','Bombay Presidency','No','Yes'),
	array('Calcutta','Madras','Yes','Yes'),
	array('Calcutta','Burma','Yes','Yes'),
	array('Calcutta','Tibet','No','Yes'),
	array('Calcutta','Bay of Bengal','Yes','No'),
	array('Madras','Bombay Presidency','Yes','Yes'),
	array('Madras','Western Indian Ocean','Yes','No'),
	array('Madras','Eastern Indian Ocean','Yes','No'),
	array('Madras','Bay of Bengal','Yes','No'),
	array('Bombay Presidency','Arabian Sea','Yes','No'),
	array('Bombay Presidency','Western Indian Ocean','Yes','No'),
	array('Singapore','Thailand','No','Yes'),
	array('Singapore','Thailand (West Coast)','Yes','No'),
	array('Singapore','Thailand (East Coast)','Yes','No'),
	array('Singapore','Andaman Sea','Yes','No'),
	array('Singapore','Gulf of Thailand','Yes','No'),
	array('Singapore','Java Sea','Yes','No'),
	array('Burgundy','Marseille','No','Yes'),
	array('Burgundy','Picardy','No','Yes'),
	array('Burgundy','Paris','No','Yes'),
	array('Burgundy','Belgium','No','Yes'),
	array('Burgundy','Lyons','No','Yes'),
	array('Marseille','Navarra','No','Yes'),
	array('Marseille','Spain','Yes','Yes'),
	array('Marseille','Gulf of Lyons','Yes','No'),
	array('Marseille','Lyons','No','Yes'),
	array('Marseille','Bordeaux','No','Yes'),
	array('Picardy','Paris','No','Yes'),
	array('Picardy','Brest','Yes','Yes'),
	array('Picardy','Belgium','Yes','Yes'),
	array('Picardy','English Channel','Yes','No'),
	array('Paris','Brest','No','Yes'),
	array('Paris','Lyons','No','Yes'),
	array('Brest','English Channel','Yes','No'),
	array('Brest','Mid Atlantic Ocean','Yes','No'),
	array('Brest','Lyons','Yes','Yes'),
	array('Tunisia','Sahara','No','Yes'),
	array('Tunisia','Algiers','Yes','Yes'),
	array('Tunisia','Gulf of Sirte','Yes','No'),
	array('Tunisia','Tyrrhenian Sea','Yes','No'),
	array('Sahara','Central Africa','No','Yes'),
	array('Sahara','Mali','No','Yes'),
	array('Sahara','Algiers','No','Yes'),
	array('Sahara','Morocco','No','Yes'),
	array('Central Africa','Sudan','No','Yes'),
	array('Mali','South Atlantic Ocean','Yes','No'),
	array('Mali','Morocco','Yes','Yes'),
	array('Algiers','Tyrrhenian Sea','Yes','No'),
	array('Algiers','Western Mediterranean Sea','Yes','No'),
	array('Algiers','Morocco','Yes','Yes'),
	array('Laos','Phnom Penh','No','Yes'),
	array('Laos','Annam','No','Yes'),
	array('Laos','Burma','No','Yes'),
	array('Laos','Thailand','No','Yes'),
	array('Laos','Yunnan','No','Yes'),
	array('Laos','Vietnam','No','Yes'),
	array('Phnom Penh','Saigon','Yes','Yes'),
	array('Phnom Penh','Annam','No','Yes'),
	array('Phnom Penh','Thailand','No','Yes'),
	array('Phnom Penh','Thailand (East Coast)','Yes','No'),
	array('Phnom Penh','Gulf of Thailand','Yes','No'),
	array('Saigon','Annam','Yes','Yes'),
	array('Saigon','Gulf of Thailand','Yes','No'),
	array('Saigon','South China Sea','Yes','No'),
	array('Annam','Gulf of Tonkin','Yes','No'),
	array('Annam','Vietnam','Yes','Yes'),
	array('Annam','South China Sea','Yes','No'),
	array('Bielorussia','Ukraine','No','Yes'),
	array('Bielorussia','Moscow','No','Yes'),
	array('Bielorussia','Leningrad','No','Yes'),
	array('Bielorussia','Latvia','No','Yes'),
	array('Bielorussia','Pinsk','No','Yes'),
	array('Ukraine','Sevastopol','No','Yes'),
	array('Ukraine','Moscow','No','Yes'),
	array('Ukraine','Bessarabia','No','Yes'),
	array('Ukraine','Pinsk','No','Yes'),
	array('Sevastopol','Stalingrad','Yes','Yes'),
	array('Sevastopol','Moscow','No','Yes'),
	array('Sevastopol','Bessarabia','Yes','Yes'),
	array('Sevastopol','Black Sea','Yes','No'),
	array('Stalingrad','Caucasus','Yes','Yes'),
	array('Stalingrad','Kazakhstan','No','Yes'),
	array('Stalingrad','Moscow','No','Yes'),
	array('Stalingrad','Black Sea','Yes','No'),
	array('Caucasus','Armenia','Yes','Yes'),
	array('Caucasus','Persia','No','Yes'),
	array('Caucasus','Black Sea','Yes','No'),
	array('Kazakhstan','Moscow','No','Yes'),
	array('Kazakhstan','Omsk','No','Yes'),
	array('Moscow','Omsk','No','Yes'),
	array('Moscow','Leningrad','No','Yes'),
	array('Omsk','Siberia','No','Yes'),
	array('Omsk','Irkutsk','No','Yes'),
	array('Omsk','Turkmenistan','No','Yes'),
	array('Omsk','Leningrad','No','Yes'),
	array('Siberia','Irkutsk','No','Yes'),
	array('Siberia','Kamchatka','Yes','Yes'),
	array('Siberia','Vladivostok','No','Yes'),
	array('Siberia','Leningrad','No','Yes'),
	array('Siberia','Leningrad (North Coast)','Yes','No'),
	array('Siberia','Mongolia','No','Yes'),
	array('Siberia','Barents Sea','Yes','No'),
	array('Siberia','North Pacific Ocean','Yes','No'),
	array('Irkutsk','Turkmenistan','No','Yes'),
	array('Irkutsk','Xinjiang','No','Yes'),
	array('Irkutsk','Mongolia','No','Yes'),
	array('Turkmenistan','Persia','No','Yes'),
	array('Turkmenistan','Afghanistan','No','Yes'),
	array('Turkmenistan','Tibet','No','Yes'),
	array('Turkmenistan','Xinjiang','No','Yes'),
	array('Kamchatka','Vladivostok','Yes','Yes'),
	array('Kamchatka','North Pacific Ocean','Yes','No'),
	array('Kamchatka','Sea of Okhotsk','Yes','No'),
	array('Vladivostok','Sea of Japan','Yes','No'),
	array('Vladivostok','Sea of Okhotsk','Yes','No'),
	array('Sakhalin','Karafuto','Yes','Yes'),
	array('Sakhalin','Sea of Japan','Yes','No'),
	array('Sakhalin','Sea of Okhotsk','Yes','No'),
	array('Leningrad','Norway','No','Yes'),
	array('Leningrad','Finland','No','Yes'),
	array('Leningrad','Estonia','No','Yes'),
	array('Leningrad','Latvia','No','Yes'),
	array('Leningrad (North Coast)','Norway','Yes','No'),
	array('Leningrad (North Coast)','Barents Sea','Yes','No'),
	array('Leningrad (South Coast)','Finland','Yes','No'),
	array('Leningrad (South Coast)','Estonia','Yes','No'),
	array('Leningrad (South Coast)','Gulf of Bothnia','Yes','No'),
	array('Ireland','North Atlantic Ocean','Yes','No'),
	array('Ireland','Irish Sea','Yes','No'),
	array('Ireland','Mid Atlantic Ocean','Yes','No'),
	array('Norway','Sweden','Yes','Yes'),
	array('Norway','Finland','No','Yes'),
	array('Norway','Skagerrak','Yes','No'),
	array('Norway','North Sea','Yes','No'),
	array('Norway','Norwegian Sea','Yes','No'),
	array('Norway','Barents Sea','Yes','No'),
	array('Sweden','Finland','Yes','Yes'),
	array('Sweden','Denmark','Yes','Yes'),
	array('Sweden','Skagerrak','Yes','No'),
	array('Sweden','Baltic Sea','Yes','No'),
	array('Sweden','Gulf of Bothnia','Yes','No'),
	array('Finland','Gulf of Bothnia','Yes','No'),
	array('Estonia','Latvia','Yes','Yes'),
	array('Estonia','Gulf of Bothnia','Yes','No'),
	array('Lithuania','Latvia','Yes','Yes'),
	array('Lithuania','Warsaw','No','Yes'),
	array('Lithuania','Pinsk','No','Yes'),
	array('Lithuania','Baltic Sea','Yes','No'),
	array('Latvia','Pinsk','No','Yes'),
	array('Latvia','Baltic Sea','Yes','No'),
	array('Latvia','Gulf of Bothnia','Yes','No'),
	array('Denmark','Heligoland Bight','Yes','No'),
	array('Denmark','Skagerrak','Yes','No'),
	array('Denmark','Baltic Sea','Yes','No'),
	array('Denmark','North Sea','Yes','No'),
	array('Holland','Belgium','Yes','Yes'),
	array('Holland','Heligoland Bight','Yes','No'),
	array('Holland','North Sea','Yes','No'),
	array('Belgium','English Channel','Yes','No'),
	array('Belgium','North Sea','Yes','No'),
	array('Navarra','Portugal','Yes','Yes'),
	array('Navarra','Spain','No','Yes'),
	array('Navarra','Mid Atlantic Ocean','Yes','No'),
	array('Navarra','Bordeaux','Yes','Yes'),
	array('Portugal','Spain','Yes','Yes'),
	array('Portugal','Mid Atlantic Ocean','Yes','No'),
	array('Spain','Gulf of Lyons','Yes','No'),
	array('Spain','Western Mediterranean Sea','Yes','No'),
	array('Spain','Mid Atlantic Ocean','Yes','No'),
	array('Hungary','Croatia','No','Yes'),
	array('Hungary','Serbia','No','Yes'),
	array('Hungary','Rumania','No','Yes'),
	array('Hungary','Bessarabia','No','Yes'),
	array('Croatia','Bosnia','Yes','Yes'),
	array('Croatia','Serbia','No','Yes'),
	array('Croatia','Adriatic Sea','Yes','No'),
	array('Bosnia','Serbia','No','Yes'),
	array('Bosnia','Macedonia','No','Yes'),
	array('Bosnia','Adriatic Sea','Yes','No'),
	array('Serbia','Macedonia','No','Yes'),
	array('Serbia','Bulgaria','No','Yes'),
	array('Serbia','Rumania','No','Yes'),
	array('Macedonia','Greece','No','Yes'),
	array('Macedonia','Bulgaria','No','Yes'),
	array('Greece','Bulgaria','No','Yes'),
	array('Greece','Istanbul','Yes','Yes'),
	array('Greece','Aegean Sea','Yes','No'),
	array('Greece','Ionian Sea','Yes','No'),
	array('Bulgaria','Rumania','Yes','Yes'),
	array('Bulgaria','Istanbul','Yes','Yes'),
	array('Bulgaria','Black Sea','Yes','No'),
	array('Rumania','Bessarabia','Yes','Yes'),
	array('Rumania','Black Sea','Yes','No'),
	array('Bessarabia','Warsaw','No','Yes'),
	array('Bessarabia','Pinsk','No','Yes'),
	array('Bessarabia','Black Sea','Yes','No'),
	array('Danzig','Warsaw','No','Yes'),
	array('Danzig','Baltic Sea','Yes','No'),
	array('Warsaw','Pinsk','No','Yes'),
	array('Sudan','South Sudan','Yes','Yes'),
	array('Sudan','Red Sea','Yes','No'),
	array('South Sudan','Red Sea','Yes','No'),
	array('Istanbul','Ankara','Yes','Yes'),
	array('Istanbul','Konya','Yes','Yes'),
	array('Istanbul','Black Sea','Yes','No'),
	array('Istanbul','Aegean Sea','Yes','No'),
	array('Ankara','Konya','No','Yes'),
	array('Ankara','Armenia','Yes','Yes'),
	array('Ankara','Black Sea','Yes','No'),
	array('Konya','Armenia','No','Yes'),
	array('Konya','Aegean Sea','Yes','No'),
	array('Konya','Eastern Mediterranean Sea','Yes','No'),
	array('Konya','Syria','Yes','Yes'),
	array('Armenia','Baghdad','No','Yes'),
	array('Armenia','Persia','No','Yes'),
	array('Armenia','Black Sea','Yes','No'),
	array('Armenia','Syria','No','Yes'),
	array('Baghdad','Arabia','No','Yes'),
	array('Baghdad','Arabia (North Coast)','Yes','No'),
	array('Baghdad','Persia','Yes','Yes'),
	array('Baghdad','Persian Gulf','Yes','No'),
	array('Baghdad','Syria','No','Yes'),
	array('Arabia','Yemen','No','Yes'),
	array('Arabia','Oman','No','Yes'),
	array('Arabia (South Coast)','Red Sea','Yes','No'),
	array('Arabia (North Coast)','Oman','Yes','No'),
	array('Arabia (North Coast)','Persian Gulf','Yes','No'),
	array('Yemen','Oman','Yes','Yes'),
	array('Yemen','Gulf of Aden','Yes','No'),
	array('Yemen','Arabian Sea','Yes','No'),
	array('Oman','Persian Gulf','Yes','No'),
	array('Oman','Arabian Sea','Yes','No'),
	array('Persia','Afghanistan','No','Yes'),
	array('Persia','Persian Gulf','Yes','No'),
	array('Persia','Arabian Sea','Yes','No'),
	array('Afghanistan','Tibet','No','Yes'),
	array('Ceylon','Western Indian Ocean','Yes','No'),
	array('Ceylon','Eastern Indian Ocean','Yes','No'),
	array('Burma','Thailand','No','Yes'),
	array('Burma','Thailand (West Coast)','Yes','No'),
	array('Burma','Yunnan','No','Yes'),
	array('Burma','Tibet','No','Yes'),
	array('Burma','Bay of Bengal','Yes','No'),
	array('Burma','Andaman Sea','Yes','No'),
	array('Thailand (West Coast)','Andaman Sea','Yes','No'),
	array('Thailand (East Coast)','Gulf of Thailand','Yes','No'),
	array('Yunnan','Tibet','No','Yes'),
	array('Yunnan','Qinghai','No','Yes'),
	array('Yunnan','Guangzhou','No','Yes'),
	array('Yunnan','Vietnam','No','Yes'),
	array('Yunnan','Hubei','No','Yes'),
	array('Tibet','Xinjiang','No','Yes'),
	array('Tibet','Qinghai','No','Yes'),
	array('Xinjiang','Mongolia','No','Yes'),
	array('Xinjiang','Inner Mongolia','No','Yes'),
	array('Xinjiang','Qinghai','No','Yes'),
	array('Mongolia','Inner Mongolia','No','Yes'),
	array('Inner Mongolia','Qinghai','No','Yes'),
	array('Inner Mongolia','Peking','Yes','Yes'),
	array('Inner Mongolia','Yellow Sea','Yes','No'),
	array('Qinghai','Peking','No','Yes'),
	array('Qinghai','Hebei','No','Yes'),
	array('Qinghai','Hubei','No','Yes'),
	array('Peking','Hebei','Yes','Yes'),
	array('Peking','Yellow Sea','Yes','No'),
	array('Hebei','East China Sea','Yes','No'),
	array('Hebei','Yellow Sea','Yes','No'),
	array('Hebei','Hubei','No','Yes'),
	array('Guangzhou','Gulf of Tonkin','Yes','No'),
	array('Guangzhou','Vietnam','Yes','Yes'),
	array('Guangzhou','South China Sea','Yes','No'),
	array('Guangzhou','Hubei','No','Yes'),
	array('Sumatra','Eastern Indian Ocean','Yes','No'),
	array('Sumatra','Andaman Sea','Yes','No'),
	array('Sumatra','Java Sea','Yes','No'),
	array('Borneo','Gulf of Thailand','Yes','No'),
	array('Borneo','Java Sea','Yes','No'),
	array('Borneo','Celebes Sea','Yes','No'),
	array('Borneo','South China Sea','Yes','No'),
	array('Java','Eastern Indian Ocean','Yes','No'),
	array('Java','Java Sea','Yes','No'),
	array('Java','Celebes Sea','Yes','No'),
	array('Java','Timor Sea','Yes','No'),
	array('Formosa','South China Sea','Yes','No'),
	array('Formosa','East China Sea','Yes','No'),
	array('Philippines','Celebes Sea','Yes','No'),
	array('Philippines','South China Sea','Yes','No'),
	array('Philippines','East China Sea','Yes','No'),
	array('Philippines','South Pacific Ocean','Yes','No'),
	array('Karafuto','Sea of Japan','Yes','No'),
	array('Karafuto','North Pacific Ocean','Yes','No'),
	array('Karafuto','Sea of Okhotsk','Yes','No'),
	array('North Atlantic Ocean','Irish Sea','Yes','No'),
	array('North Atlantic Ocean','Norwegian Sea','Yes','No'),
	array('North Atlantic Ocean','Mid Atlantic Ocean','Yes','No'),
	array('Irish Sea','English Channel','Yes','No'),
	array('Irish Sea','Mid Atlantic Ocean','Yes','No'),
	array('English Channel','North Sea','Yes','No'),
	array('English Channel','Mid Atlantic Ocean','Yes','No'),
	array('Heligoland Bight','Baltic Sea','Yes','No'),
	array('Heligoland Bight','North Sea','Yes','No'),
	array('Skagerrak','North Sea','Yes','No'),
	array('Baltic Sea','Gulf of Bothnia','Yes','No'),
	array('North Sea','Norwegian Sea','Yes','No'),
	array('Norwegian Sea','Barents Sea','Yes','No'),
	array('Barents Sea','North Pacific Ocean','Yes','No'),
	array('Black Sea','Aegean Sea','Yes','No'),
	array('Aegean Sea','Eastern Mediterranean Sea','Yes','No'),
	array('Aegean Sea','Ionian Sea','Yes','No'),
	array('Eastern Mediterranean Sea','Ionian Sea','Yes','No'),
	array('Eastern Mediterranean Sea','Red Sea','Yes','No'),
	array('Eastern Mediterranean Sea','Syria','Yes','No'),
	array('Ionian Sea','Adriatic Sea','Yes','No'),
	array('Ionian Sea','Gulf of Sirte','Yes','No'),
	array('Gulf of Sirte','Tyrrhenian Sea','Yes','No'),
	array('Tyrrhenian Sea','Gulf of Lyons','Yes','No'),
	array('Tyrrhenian Sea','Western Mediterranean Sea','Yes','No'),
	array('Gulf of Lyons','Western Mediterranean Sea','Yes','No'),
	array('Western Mediterranean Sea','Mid Atlantic Ocean','Yes','No'),
	array('Western Mediterranean Sea','Morocco','Yes','No'),
	array('Mid Atlantic Ocean','South Atlantic Ocean','Yes','No'),
	array('Mid Atlantic Ocean','Lyons','Yes','No'),
	array('Mid Atlantic Ocean','Morocco','Yes','No'),
	array('Mid Atlantic Ocean','Bordeaux','Yes','No'),
	array('South Atlantic Ocean','Horn of Africa','Yes','No'),
	array('South Atlantic Ocean','Morocco','Yes','No'),
	array('Red Sea','Gulf of Aden','Yes','No'),
	array('Persian Gulf','Arabian Sea','Yes','No'),
	array('Gulf of Aden','Arabian Sea','Yes','No'),
	array('Gulf of Aden','Western Indian Ocean','Yes','No'),
	array('Gulf of Aden','Horn of Africa','Yes','No'),
	array('Arabian Sea','Western Indian Ocean','Yes','No'),
	array('Western Indian Ocean','Horn of Africa','Yes','No'),
	array('Western Indian Ocean','Eastern Indian Ocean','Yes','No'),
	array('Eastern Indian Ocean','Bay of Bengal','Yes','No'),
	array('Eastern Indian Ocean','Andaman Sea','Yes','No'),
	array('Eastern Indian Ocean','Java Sea','Yes','No'),
	array('Eastern Indian Ocean','Timor Sea','Yes','No'),
	array('Bay of Bengal','Andaman Sea','Yes','No'),
	array('Andaman Sea','Java Sea','Yes','No'),
	array('Gulf of Thailand','Java Sea','Yes','No'),
	array('Gulf of Thailand','South China Sea','Yes','No'),
	array('Java Sea','Celebes Sea','Yes','No'),
	array('Celebes Sea','Timor Sea','Yes','No'),
	array('Celebes Sea','South China Sea','Yes','No'),
	array('Celebes Sea','South Pacific Ocean','Yes','No'),
	array('Timor Sea','South Pacific Ocean','Yes','No'),
	array('Gulf of Tonkin','Vietnam','Yes','No'),
	array('Gulf of Tonkin','South China Sea','Yes','No'),
	array('South China Sea','East China Sea','Yes','No'),
	array('East China Sea','Yellow Sea','Yes','No'),
	array('East China Sea','Sea of Japan','Yes','No'),
	array('East China Sea','South Pacific Ocean','Yes','No'),
	array('Sea of Japan','North Pacific Ocean','Yes','No'),
	array('Sea of Japan','Sea of Okhotsk','Yes','No'),
	array('Sea of Japan','Hokkaido','Yes','No'),
	array('South Pacific Ocean','North Pacific Ocean','Yes','No'),
	array('North Pacific Ocean','Sea of Okhotsk','Yes','No'),
	array('North Pacific Ocean','Hokkaido','Yes','No'),
	array('Lyons','Bordeaux','Yes','Yes')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

// Custom footer not changed by edit tool

// Just create the database as usual:
InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);

// Copy the smallmap-sample to the cache-directory to avoid a screwed variantpage (there is no smallmap available)
if (!file_exists('variants/'.$this->name.'/cache/sampleMap.png'))
	copy ('variants/'.$this->name.'/resources/sampleMap.png','variants/'.$this->name.'/cache/sampleMap.png');

?>


