<?php
// This is file installs the map data for the DutchRevolt variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Upper North Sea', 'Sea', 'No', 0, 394, 120, 145, 42),
	array('Norwich', 'Coast', 'Yes', 1, 80, 212, 39, 116),
	array('Thurrock', 'Coast', 'Yes', 1, 60, 398, 25, 183),
	array('North English Coast', 'Sea', 'No', 0, 264, 338, 122, 185),
	array('South English Coast', 'Sea', 'No', 0, 169, 520, 93, 255),
	array('Thames', 'Sea', 'No', 0, 21, 555, 10, 302),
	array('Cantia', 'Coast', 'Yes', 1, 15, 684, 6, 356),
	array('Pas de Calais', 'Sea', 'No', 0, 108, 829, 51, 420),
	array('Spain', 'Coast', 'Yes', 3, 27, 851, 6, 431),
	array('Channel', 'Sea', 'No', 0, 33, 1107, 10, 532),
	array('Valery sur Somme', 'Coast', 'Yes', 2, 22, 1294, 15, 652),
	array('Coast of Flanders', 'Sea', 'No', 0, 284, 743, 123, 332),
	array('Calais', 'Coast', 'Yes', 0, 93, 961, 34, 485),
	array('Artois', 'Coast', 'No', 2, 104, 1104, 47, 550),
	array('Picardie', 'Coast', 'No', 2, 89, 1240, 54, 635),
	array('West Flanders', 'Coast', 'No', 0, 232, 921, 114, 463),
	array('Arras', 'Coast', 'Yes', 2, 265, 1119, 124, 593),
	array('Central North Sea', 'Sea', 'No', 0, 570, 252, 265, 118),
	array('Coast of Holland', 'Sea', 'No', 0, 576, 474, 254, 222),
	array('Coast of Zeeland', 'Sea', 'No', 0, 430, 607, 193, 276),
	array('Bruges', 'Coast', 'Yes', 0, 357, 852, 198, 438),
	array('Ghent', 'Coast', 'Yes', 0, 402, 1018, 198, 486),
	array('Tournaisis', 'Coast', 'No', 0, 363, 1123, 179, 563),
	array('Cambrai', 'Coast', 'Yes', 0, 381, 1231, 180, 625),
	array('Thierache', 'Land', 'Yes', 2, 463, 1315, 254, 654),
	array('South Hainaut', 'Coast', 'No', 0, 442, 1180, 222, 592),
	array('North Hainaut', 'Coast', 'No', 0, 472, 1069, 238, 541),
	array('East Flanders', 'Coast', 'No', 0, 516, 943, 271, 454),
	array('Goes', 'Coast', 'Yes', 0, 526, 777, 269, 392),
	array('Middelburg', 'Coast', 'Yes', 0, 443, 753, 223, 384),
	array('South Zeeland', 'Sea', 'No', 0, 552, 739, 271, 365),
	array('North Zeeland', 'Sea', 'No', 0, 627, 682, 309, 343),
	array('Biesbosch', 'Coast', 'No', 0, 719, 694, 342, 347),
	array('North Brabant', 'Coast', 'No', 0, 745, 763, 378, 412),
	array('Antwerp', 'Coast', 'Yes', 0, 633, 880, 311, 442),
	array('South Brabant', 'Coast', 'No', 0, 720, 937, 360, 473),
	array('Brussels', 'Coast', 'Yes', 0, 619, 966, 311, 484),
	array('Namur', 'Coast', 'Yes', 0, 676, 1138, 340, 568),
	array('West Ardennes', 'Land', 'No', 0, 751, 1239, 376, 622),
	array('Liege', 'Coast', 'Yes', 0, 817, 1078, 410, 538),
	array('Loon', 'Coast', 'No', 0, 885, 924, 441, 466),
	array('s Hertogenbosch', 'Coast', 'Yes', 0, 883, 714, 453, 364),
	array('Cleves', 'Coast', 'Yes', 0, 973, 699, 491, 351),
	array('Venlo', 'Coast', 'Yes', 0, 1023, 791, 483, 401),
	array('Maastricht', 'Coast', 'Yes', 0, 954, 921, 478, 458),
	array('Limburg', 'Coast', 'No', 0, 925, 1104, 461, 555),
	array('High Fens', 'Coast', 'No', 3, 963, 1215, 444, 594),
	array('Luxembourg', 'Land', 'Yes', 3, 1053, 1281, 526, 640),
	array('East Ardennes', 'Land', 'No', 0, 1054, 1132, 527, 564),
	array('South Julich', 'Land', 'No', 0, 1044, 984, 535, 504),
	array('North Julich', 'Coast', 'No', 0, 1102, 900, 549, 447),
	array('South Borken', 'Coast', 'No', 0, 1081, 711, 542, 356),
	array('Westmark', 'Land', 'No', 0, 1246, 760, 631, 386),
	array('Dusseldorf', 'Coast', 'Yes', 0, 1162, 866, 584, 446),
	array('Berg', 'Coast', 'No', 0, 1212, 963, 603, 485),
	array('Cologne', 'Coast', 'Yes', 0, 1190, 1066, 596, 530),
	array('Siegerland', 'Coast', 'No', 0, 1277, 1127, 633, 544),
	array('Eifel', 'Land', 'No', 0, 1136, 1092, 564, 544),
	array('Trier', 'Land', 'Yes', 3, 1212, 1290, 602, 632),
	array('Munsterland', 'Land', 'Yes', 4, 1266, 640, 637, 306),
	array('Bocholt', 'Land', 'Yes', 4, 1153, 650, 597, 324),
	array('North Borken', 'Land', 'No', 4, 1159, 590, 604, 279),
	array('Emsland', 'Coast', 'No', 4, 1214, 404, 609, 206),
	array('Lingen', 'Coast', 'Yes', 4, 1279, 452, 639, 202),
	array('Ammerland', 'Coast', 'No', 0, 1262, 258, 611, 143),
	array('Emden', 'Coast', 'Yes', 0, 1204, 176, 625, 74),
	array('East Wadden', 'Sea', 'No', 0, 1104, 80, 553, 33),
	array('Groningen', 'Coast', 'Yes', 0, 1068, 157, 539, 78),
	array('Oldambt', 'Coast', 'No', 0, 1152, 194, 574, 96),
	array('Noordenveld', 'Land', 'No', 0, 1122, 324, 554, 151),
	array('Bentheim', 'Coast', 'Yes', 0, 1205, 460, 595, 232),
	array('Twenthe', 'Land', 'No', 0, 1112, 500, 557, 264),
	array('Coevoorden', 'Coast', 'Yes', 0, 1062, 400, 541, 202),
	array('Salland', 'Coast', 'No', 0, 1015, 502, 518, 236),
	array('Achterhoek', 'Coast', 'No', 0, 1039, 568, 525, 312),
	array('Nymegen', 'Coast', 'Yes', 0, 971, 626, 491, 316),
	array('Veluwe', 'Coast', 'No', 0, 927, 517, 461, 250),
	array('Kampen', 'Coast', 'Yes', 0, 988, 402, 490, 206),
	array('Eastergoa', 'Coast', 'No', 0, 966, 190, 484, 86),
	array('West Wadden', 'Coast', 'No', 0, 878, 163, 409, 73),
	array('Frysian Sea', 'Sea', 'No', 0, 831, 96, 426, 46),
	array('Leeuwarden', 'Coast', 'Yes', 0, 870, 223, 434, 108),
	array('Urk', 'Coast', 'Yes', 0, 874, 386, 439, 191),
	array('South Zuiderzee', 'Sea', 'No', 0, 851, 444, 434, 227),
	array('Texel', 'Coast', 'Yes', 0, 732, 239, 376, 101),
	array('Marsdiep', 'Sea', 'No', 0, 771, 292, 379, 141),
	array('Kennemerland', 'Coast', 'No', 5, 697, 397, 349, 193),
	array('Waterland', 'Coast', 'No', 5, 760, 421, 376, 203),
	array('Rynland', 'Coast', 'No', 5, 675, 541, 342, 275),
	array('Amsterdam', 'Coast', 'Yes', 5, 724, 488, 378, 250),
	array('s Gravenhage', 'Coast', 'Yes', 5, 646, 597, 333, 311),
	array('Utrecht', 'Coast', 'Yes', 5, 741, 557, 381, 295),
	array('Gelder Valley', 'Coast', 'No', 5, 839, 582, 414, 301),
	array('Betuwe', 'Coast', 'No', 0, 780, 661, 400, 325),
	array('Cleves (East Coast)', 'Coast', 'No', 0, 1037, 714, 520, 358),
	array('Cleves (West Coast)', 'Coast', 'No', 0, 968, 712, 474, 347),
	array('Veluwe (West Coast)', 'Coast', 'No', 0, 896, 502, 447, 253),
	array('Veluwe (East Coast)', 'Coast', 'No', 0, 966, 505, 479, 255),
	array('Bohain', 'Coast', 'No', 2, 246, 1300, 157, 652),
	array('Schelde', 'Sea', 'No', 0, 461, 805, 257, 408),
	array('North Zuiderzee', 'Sea', 'No', 0, 842, 373, 419, 189),
	array('East Flanders (North Coast)', 'Coast', 'No', 0, 511, 866, 255, 435),
	array('East Flanders (South Coast)', 'Coast', 'No', 0, 506, 998, 255, 497)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Upper North Sea','Norwich','Yes','No'),
	array('Upper North Sea','North English Coast','Yes','No'),
	array('Upper North Sea','Central North Sea','Yes','No'),
	array('Upper North Sea','East Wadden','Yes','No'),
	array('Upper North Sea','Frysian Sea','Yes','No'),
	array('Norwich','Thurrock','Yes','Yes'),
	array('Norwich','North English Coast','Yes','No'),
	array('Thurrock','North English Coast','Yes','No'),
	array('Thurrock','South English Coast','Yes','No'),
	array('Thurrock','Thames','Yes','No'),
	array('North English Coast','South English Coast','Yes','No'),
	array('North English Coast','Central North Sea','Yes','No'),
	array('North English Coast','Coast of Zeeland','Yes','No'),
	array('South English Coast','Thames','Yes','No'),
	array('South English Coast','Cantia','Yes','No'),
	array('South English Coast','Pas de Calais','Yes','No'),
	array('South English Coast','Coast of Flanders','Yes','No'),
	array('South English Coast','Coast of Zeeland','Yes','No'),
	array('Thames','Cantia','Yes','No'),
	array('Cantia','Pas de Calais','Yes','No'),
	array('Pas de Calais','Channel','Yes','No'),
	array('Pas de Calais','Coast of Flanders','Yes','No'),
	array('Pas de Calais','Calais','Yes','No'),
	array('Pas de Calais','West Flanders','Yes','No'),
	array('Spain','Pas de Calais','Yes','No'),
	array('Spain','Channel','Yes','No'),
	array('Channel','Valery sur Somme','Yes','No'),
	array('Channel','Calais','Yes','No'),
	array('Channel','Artois','Yes','No'),
	array('Channel','Picardie','Yes','No'),
	array('Valery sur Somme','Picardie','Yes','Yes'),
	array('Valery sur Somme','Bohain','Yes','No'),
	array('Coast of Flanders','West Flanders','Yes','No'),
	array('Coast of Flanders','Coast of Zeeland','Yes','No'),
	array('Coast of Flanders','Bruges','Yes','No'),
	array('Coast of Flanders','Middelburg','Yes','No'),
	array('Coast of Flanders','Schelde','Yes','No'),
	array('Calais','Artois','Yes','Yes'),
	array('Calais','West Flanders','Yes','Yes'),
	array('Artois','Picardie','Yes','Yes'),
	array('Artois','West Flanders','No','Yes'),
	array('Artois','Arras','No','Yes'),
	array('Picardie','Arras','No','Yes'),
	array('Picardie','Bohain','Yes','Yes'),
	array('West Flanders','Arras','No','Yes'),
	array('West Flanders','Bruges','Yes','Yes'),
	array('West Flanders','Ghent','No','Yes'),
	array('West Flanders','Tournaisis','No','Yes'),
	array('Arras','Tournaisis','Yes','Yes'),
	array('Arras','Cambrai','Yes','No'),
	array('Arras','Bohain','Yes','Yes'),
	array('Central North Sea','Coast of Holland','Yes','No'),
	array('Central North Sea','Coast of Zeeland','Yes','No'),
	array('Central North Sea','Frysian Sea','Yes','No'),
	array('Central North Sea','Texel','Yes','No'),
	array('Central North Sea','Marsdiep','Yes','No'),
	array('Central North Sea','Kennemerland','Yes','No'),
	array('Coast of Holland','Coast of Zeeland','Yes','No'),
	array('Coast of Holland','North Zeeland','Yes','No'),
	array('Coast of Holland','Kennemerland','Yes','No'),
	array('Coast of Holland','Rynland','Yes','No'),
	array('Coast of Holland','s Gravenhage','Yes','No'),
	array('Coast of Zeeland','Middelburg','Yes','No'),
	array('Coast of Zeeland','South Zeeland','Yes','No'),
	array('Coast of Zeeland','North Zeeland','Yes','No'),
	array('Bruges','Ghent','No','Yes'),
	array('Bruges','East Flanders','No','Yes'),
	array('Bruges','Schelde','Yes','No'),
	array('Bruges','East Flanders (North Coast)','Yes','No'),
	array('Ghent','Tournaisis','Yes','Yes'),
	array('Ghent','North Hainaut','Yes','Yes'),
	array('Ghent','East Flanders','No','Yes'),
	array('Ghent','East Flanders (South Coast)','Yes','No'),
	array('Tournaisis','Cambrai','Yes','Yes'),
	array('Tournaisis','South Hainaut','Yes','No'),
	array('Tournaisis','North Hainaut','Yes','No'),
	array('Cambrai','Thierache','No','Yes'),
	array('Cambrai','South Hainaut','Yes','Yes'),
	array('Cambrai','Bohain','Yes','Yes'),
	array('Thierache','South Hainaut','No','Yes'),
	array('Thierache','West Ardennes','No','Yes'),
	array('Thierache','Bohain','No','Yes'),
	array('South Hainaut','North Hainaut','Yes','Yes'),
	array('South Hainaut','Namur','No','Yes'),
	array('South Hainaut','West Ardennes','No','Yes'),
	array('North Hainaut','East Flanders','No','Yes'),
	array('North Hainaut','Brussels','No','Yes'),
	array('North Hainaut','Namur','No','Yes'),
	array('North Hainaut','East Flanders (South Coast)','Yes','No'),
	array('East Flanders','Antwerp','No','Yes'),
	array('East Flanders','Brussels','No','Yes'),
	array('Goes','Middelburg','Yes','No'),
	array('Goes','South Zeeland','Yes','No'),
	array('Goes','Antwerp','Yes','No'),
	array('Goes','Schelde','Yes','No'),
	array('Middelburg','South Zeeland','Yes','No'),
	array('Middelburg','Schelde','Yes','No'),
	array('South Zeeland','North Zeeland','Yes','No'),
	array('South Zeeland','Biesbosch','Yes','No'),
	array('South Zeeland','Antwerp','Yes','No'),
	array('South Zeeland','Schelde','Yes','No'),
	array('North Zeeland','Biesbosch','Yes','No'),
	array('North Zeeland','s Gravenhage','Yes','No'),
	array('North Zeeland','Betuwe','Yes','No'),
	array('Biesbosch','North Brabant','No','Yes'),
	array('Biesbosch','Antwerp','Yes','Yes'),
	array('Biesbosch','s Hertogenbosch','Yes','Yes'),
	array('Biesbosch','Betuwe','Yes','No'),
	array('North Brabant','Antwerp','Yes','Yes'),
	array('North Brabant','South Brabant','Yes','No'),
	array('North Brabant','Loon','Yes','Yes'),
	array('North Brabant','s Hertogenbosch','No','Yes'),
	array('Antwerp','South Brabant','Yes','Yes'),
	array('Antwerp','Brussels','Yes','Yes'),
	array('Antwerp','Schelde','Yes','No'),
	array('Antwerp','East Flanders (North Coast)','Yes','No'),
	array('Antwerp','East Flanders (South Coast)','Yes','No'),
	array('South Brabant','Brussels','No','Yes'),
	array('South Brabant','Namur','No','Yes'),
	array('South Brabant','Liege','No','Yes'),
	array('South Brabant','Loon','Yes','Yes'),
	array('Brussels','Namur','No','Yes'),
	array('Brussels','East Flanders (South Coast)','Yes','No'),
	array('Namur','West Ardennes','No','Yes'),
	array('Namur','Liege','Yes','Yes'),
	array('Namur','High Fens','Yes','Yes'),
	array('West Ardennes','High Fens','No','Yes'),
	array('Liege','Loon','Yes','Yes'),
	array('Liege','Maastricht','Yes','Yes'),
	array('Liege','Limburg','Yes','No'),
	array('Liege','High Fens','Yes','Yes'),
	array('Loon','s Hertogenbosch','No','Yes'),
	array('Loon','Venlo','Yes','Yes'),
	array('Loon','Maastricht','Yes','Yes'),
	array('s Hertogenbosch','Venlo','Yes','Yes'),
	array('s Hertogenbosch','Nymegen','Yes','Yes'),
	array('s Hertogenbosch','Betuwe','Yes','No'),
	array('s Hertogenbosch','Cleves (West Coast)','Yes','No'),
	array('Cleves','Venlo','No','Yes'),
	array('Cleves','North Julich','No','Yes'),
	array('Cleves','Nymegen','No','Yes'),
	array('Venlo','Maastricht','Yes','Yes'),
	array('Venlo','North Julich','No','Yes'),
	array('Venlo','Cleves (West Coast)','Yes','No'),
	array('Maastricht','Limburg','Yes','Yes'),
	array('Maastricht','South Julich','No','Yes'),
	array('Maastricht','North Julich','No','Yes'),
	array('Limburg','High Fens','Yes','Yes'),
	array('Limburg','East Ardennes','No','Yes'),
	array('Limburg','South Julich','No','Yes'),
	array('High Fens','Luxembourg','No','Yes'),
	array('High Fens','East Ardennes','No','Yes'),
	array('Luxembourg','East Ardennes','No','Yes'),
	array('Luxembourg','Trier','No','Yes'),
	array('East Ardennes','South Julich','No','Yes'),
	array('East Ardennes','Eifel','No','Yes'),
	array('East Ardennes','Trier','No','Yes'),
	array('South Julich','North Julich','No','Yes'),
	array('South Julich','Cologne','No','Yes'),
	array('South Julich','Eifel','No','Yes'),
	array('North Julich','South Borken','Yes','No'),
	array('North Julich','Dusseldorf','Yes','Yes'),
	array('North Julich','Cologne','Yes','Yes'),
	array('North Julich','Cleves (East Coast)','Yes','No'),
	array('South Borken','Westmark','No','Yes'),
	array('South Borken','Dusseldorf','Yes','Yes'),
	array('South Borken','Bocholt','No','Yes'),
	array('South Borken','Achterhoek','Yes','Yes'),
	array('South Borken','Cleves (East Coast)','Yes','No'),
	array('Westmark','Dusseldorf','No','Yes'),
	array('Westmark','Berg','No','Yes'),
	array('Westmark','Munsterland','No','Yes'),
	array('Westmark','Bocholt','No','Yes'),
	array('Dusseldorf','Berg','Yes','Yes'),
	array('Dusseldorf','Cologne','Yes','Yes'),
	array('Berg','Cologne','Yes','No'),
	array('Berg','Siegerland','Yes','Yes'),
	array('Cologne','Siegerland','Yes','No'),
	array('Cologne','Eifel','No','Yes'),
	array('Siegerland','Eifel','No','Yes'),
	array('Siegerland','Trier','No','Yes'),
	array('Eifel','Trier','No','Yes'),
	array('Munsterland','Bocholt','No','Yes'),
	array('Munsterland','North Borken','No','Yes'),
	array('Munsterland','Emsland','No','Yes'),
	array('Bocholt','North Borken','No','Yes'),
	array('Bocholt','Achterhoek','No','Yes'),
	array('North Borken','Emsland','No','Yes'),
	array('North Borken','Bentheim','No','Yes'),
	array('North Borken','Twenthe','No','Yes'),
	array('North Borken','Achterhoek','No','Yes'),
	array('Emsland','Lingen','Yes','Yes'),
	array('Emsland','Ammerland','Yes','Yes'),
	array('Emsland','Noordenveld','No','Yes'),
	array('Emsland','Bentheim','Yes','Yes'),
	array('Lingen','Ammerland','Yes','Yes'),
	array('Ammerland','Emden','Yes','Yes'),
	array('Ammerland','Oldambt','No','Yes'),
	array('Ammerland','Noordenveld','No','Yes'),
	array('Emden','East Wadden','Yes','No'),
	array('Emden','Oldambt','Yes','Yes'),
	array('East Wadden','Groningen','Yes','No'),
	array('East Wadden','Oldambt','Yes','No'),
	array('East Wadden','West Wadden','Yes','No'),
	array('East Wadden','Frysian Sea','Yes','No'),
	array('Groningen','Oldambt','Yes','Yes'),
	array('Groningen','Noordenveld','No','Yes'),
	array('Groningen','Eastergoa','Yes','Yes'),
	array('Groningen','West Wadden','Yes','Yes'),
	array('Oldambt','Noordenveld','No','Yes'),
	array('Noordenveld','Bentheim','No','Yes'),
	array('Noordenveld','Coevoorden','No','Yes'),
	array('Noordenveld','Kampen','No','Yes'),
	array('Noordenveld','Eastergoa','Yes','Yes'),
	array('Bentheim','Twenthe','No','Yes'),
	array('Bentheim','Coevoorden','Yes','Yes'),
	array('Bentheim','Salland','Yes','Yes'),
	array('Twenthe','Salland','No','Yes'),
	array('Twenthe','Achterhoek','No','Yes'),
	array('Coevoorden','Salland','Yes','Yes'),
	array('Coevoorden','Kampen','Yes','Yes'),
	array('Salland','Achterhoek','Yes','Yes'),
	array('Salland','Kampen','Yes','No'),
	array('Salland','Veluwe (East Coast)','Yes','No'),
	array('Achterhoek','Nymegen','Yes','Yes'),
	array('Achterhoek','Cleves (East Coast)','Yes','No'),
	array('Achterhoek','Veluwe (East Coast)','Yes','No'),
	array('Nymegen','Veluwe','No','Yes'),
	array('Nymegen','Gelder Valley','Yes','Yes'),
	array('Nymegen','Betuwe','Yes','Yes'),
	array('Nymegen','Cleves (East Coast)','Yes','No'),
	array('Nymegen','Cleves (West Coast)','Yes','No'),
	array('Nymegen','Veluwe (East Coast)','Yes','No'),
	array('Veluwe','Kampen','No','Yes'),
	array('Veluwe','Amsterdam','No','Yes'),
	array('Veluwe','Gelder Valley','No','Yes'),
	array('Kampen','Eastergoa','No','Yes'),
	array('Kampen','Leeuwarden','Yes','Yes'),
	array('Kampen','South Zuiderzee','Yes','No'),
	array('Kampen','Veluwe (West Coast)','Yes','No'),
	array('Kampen','Veluwe (East Coast)','Yes','No'),
	array('Kampen','North Zuiderzee','Yes','No'),
	array('Eastergoa','West Wadden','Yes','Yes'),
	array('Eastergoa','Leeuwarden','Yes','Yes'),
	array('West Wadden','Frysian Sea','Yes','No'),
	array('West Wadden','Leeuwarden','Yes','Yes'),
	array('West Wadden','Texel','Yes','Yes'),
	array('West Wadden','Marsdiep','Yes','No'),
	array('Frysian Sea','Texel','Yes','No'),
	array('Leeuwarden','Marsdiep','Yes','No'),
	array('Leeuwarden','North Zuiderzee','Yes','No'),
	array('Urk','South Zuiderzee','Yes','No'),
	array('Urk','North Zuiderzee','Yes','No'),
	array('South Zuiderzee','Waterland','Yes','No'),
	array('South Zuiderzee','Amsterdam','Yes','No'),
	array('South Zuiderzee','Veluwe (West Coast)','Yes','No'),
	array('South Zuiderzee','North Zuiderzee','Yes','No'),
	array('Texel','Marsdiep','Yes','No'),
	array('Marsdiep','Kennemerland','Yes','No'),
	array('Marsdiep','Waterland','Yes','No'),
	array('Marsdiep','North Zuiderzee','Yes','No'),
	array('Kennemerland','Waterland','Yes','Yes'),
	array('Kennemerland','Rynland','Yes','Yes'),
	array('Kennemerland','Amsterdam','No','Yes'),
	array('Waterland','Amsterdam','Yes','Yes'),
	array('Waterland','North Zuiderzee','Yes','No'),
	array('Rynland','Amsterdam','No','Yes'),
	array('Rynland','s Gravenhage','Yes','Yes'),
	array('Rynland','Utrecht','Yes','Yes'),
	array('Amsterdam','Utrecht','Yes','Yes'),
	array('Amsterdam','Gelder Valley','No','Yes'),
	array('Amsterdam','Veluwe (West Coast)','Yes','No'),
	array('s Gravenhage','Utrecht','Yes','Yes'),
	array('s Gravenhage','Betuwe','Yes','No'),
	array('Utrecht','Gelder Valley','Yes','Yes'),
	array('Utrecht','Betuwe','Yes','No'),
	array('Gelder Valley','Betuwe','Yes','Yes'),
	array('Schelde','East Flanders (North Coast)','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

// Custom footer not changed by edit tool
InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);

// Remove the links to Spain... (you can only leave Spain)
global $DB;
$DB->sql_put('DELETE FROM wD_Borders        WHERE mapID='.$this->mapID.' AND toTerrID=9');
$DB->sql_put('DELETE FROM wD_CoastalBorders WHERE mapID='.$this->mapID.' AND toTerrID=9');

?>


