<?php
// This is file installs the map data for the Octopus variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Clyde', 'Coast', 'No', 309, 337, 157, 120, 'England'),
	array('Edinburgh', 'Coast', 'Yes', 340, 350, 175, 109, 'England'),
	array('Liverpool', 'Coast', 'Yes', 315, 405, 166, 140, 'England'),
	array('Yorkshire', 'Coast', 'No', 355, 440, 184, 150, 'England'),
	array('Wales', 'Coast', 'No', 305, 480, 154, 179, 'England'),
	array('London', 'Coast', 'Yes', 358, 485, 176, 185, 'England'),
	array('Portugal', 'Coast', 'Yes', 100, 718, 65, 292, 'Neutral'),
	array('Spain', 'Coast', 'Yes', 205, 760, 110, 307, 'Neutral'),
	array('North Africa', 'Coast', 'No', 210, 923, 130, 380, 'Neutral'),
	array('Tunis', 'Coast', 'Yes', 420, 970, 204, 384, 'Neutral'),
	array('Naples', 'Coast', 'Yes', 570, 870, 298, 357, 'Italy'),
	array('Rome', 'Coast', 'Yes', 522, 800, 272, 330, 'Italy'),
	array('Tuscany', 'Coast', 'No', 485, 755, 256, 312, 'Italy'),
	array('Piedmont', 'Coast', 'No', 441, 694, 228, 276, 'Italy'),
	array('Venice', 'Coast', 'Yes', 490, 710, 258, 292, 'Italy'),
	array('Apulia', 'Coast', 'No', 575, 813, 295, 335, 'Italy'),
	array('Greece', 'Coast', 'Yes', 676, 851, 355, 361, 'Neutral'),
	array('Albania', 'Coast', 'No', 640, 820, 343, 341, 'Neutral'),
	array('Serbia', 'Land', 'Yes', 668, 766, 357, 324, 'Neutral'),
	array('Bulgaria', 'Coast', 'Yes', 730, 776, 394, 318, 'Neutral'),
	array('Rumania', 'Coast', 'Yes', 765, 717, 412, 272, 'Neutral'),
	array('Constantinople', 'Coast', 'Yes', 821, 840, 433, 345, 'Turkey'),
	array('Smyrna', 'Coast', 'Yes', 899, 890, 480, 363, 'Turkey'),
	array('Ankara', 'Coast', 'Yes', 970, 820, 485, 320, 'Turkey'),
	array('Armenia', 'Coast', 'No', 1130, 835, 572, 323, 'Turkey'),
	array('Syria', 'Coast', 'No', 1073, 940, 559, 370, 'Turkey'),
	array('Sevastopol', 'Coast', 'Yes', 920, 595, 485, 248, 'Russia'),
	array('Ukraine', 'Land', 'No', 779, 579, 418, 220, 'Russia'),
	array('Warsaw', 'Land', 'Yes', 680, 540, 358, 209, 'Russia'),
	array('Livonia', 'Coast', 'No', 719, 441, 374, 168, 'Russia'),
	array('Moscow', 'Land', 'Yes', 880, 440, 490, 160, 'Russia'),
	array('St. Petersburg', 'Coast', 'Yes', 837, 309, 445, 97, 'Russia'),
	array('Finland', 'Coast', 'No', 710, 263, 369, 109, 'Russia'),
	array('Sweden', 'Coast', 'Yes', 587, 285, 307, 103, 'Neutral'),
	array('Norway', 'Coast', 'Yes', 518, 270, 265, 113, 'Neutral'),
	array('Denmark', 'Coast', 'Yes', 501, 435, 264, 150, 'Neutral'),
	array('Kiel', 'Coast', 'Yes', 477, 504, 253, 193, 'Germany'),
	array('Berlin', 'Coast', 'Yes', 559, 493, 287, 189, 'Germany'),
	array('Prussia', 'Coast', 'No', 618, 482, 319, 202, 'Germany'),
	array('Silesia', 'Land', 'No', 589, 535, 315, 222, 'Germany'),
	array('Munich', 'Land', 'Yes', 489, 596, 252, 229, 'Germany'),
	array('Ruhr', 'Land', 'No', 450, 550, 227, 221, 'Germany'),
	array('Holland', 'Coast', 'Yes', 433, 510, 234, 185, 'Neutral'),
	array('Belgium', 'Coast', 'Yes', 410, 550, 215, 205, 'Neutral'),
	array('Picardy', 'Coast', 'No', 363, 559, 182, 213, 'France'),
	array('Brest', 'Coast', 'Yes', 298, 595, 153, 240, 'France'),
	array('Paris', 'Land', 'Yes', 336, 620, 176, 233, 'France'),
	array('Burgundy', 'Land', 'No', 393, 629, 204, 243, 'France'),
	array('Marseilles', 'Coast', 'Yes', 390, 689, 199, 275, 'France'),
	array('Gascony', 'Coast', 'No', 301, 676, 154, 265, 'France'),
	array('Barents Sea', 'Sea', 'No', 826, 37, 427, 15, 'Neutral'),
	array('Norwegian Sea', 'Sea', 'No', 437, 149, 240, 31, 'Neutral'),
	array('North Sea', 'Sea', 'No', 414, 378, 216, 125, 'Neutral'),
	array('Skagerrack', 'Sea', 'No', 518, 363, 284, 146, 'Neutral'),
	array('Heligoland Bight', 'Sea', 'No', 455, 439, 241, 159, 'Neutral'),
	array('Baltic Sea', 'Sea', 'No', 621, 431, 338, 177, 'Neutral'),
	array('Gulf of Bothnia', 'Sea', 'No', 653, 330, 345, 141, 'Neutral'),
	array('North Atlantic Ocean', 'Sea', 'No', 145, 250, 78, 92, 'Neutral'),
	array('Irish Sea', 'Sea', 'No', 208, 478, 118, 171, 'Neutral'),
	array('English Channel', 'Sea', 'No', 275, 526, 145, 205, 'Neutral'),
	array('Mid-Atlantic Ocean', 'Sea', 'No', 106, 587, 60, 251, 'Neutral'),
	array('Western Mediterranean', 'Sea', 'No', 327, 852, 186, 350, 'Neutral'),
	array('Gulf of Lyons', 'Sea', 'No', 366, 774, 208, 322, 'Neutral'),
	array('Tyrrhenian Sea', 'Sea', 'No', 480, 847, 248, 343, 'Neutral'),
	array('Ionian Sea', 'Sea', 'No', 610, 952, 325, 379, 'Neutral'),
	array('Adriatic Sea', 'Sea', 'No', 554, 761, 316, 329, 'Neutral'),
	array('Aegean Sea', 'Sea', 'No', 755, 930, 395, 363, 'Neutral'),
	array('Eastern Mediterranean', 'Sea', 'No', 860, 967, 465, 383, 'Neutral'),
	array('Black Sea', 'Sea', 'No', 915, 735, 457, 300, 'Neutral'),
	array('Tyrolia', 'Land', 'No', 542, 632, 282, 252, 'Austria'),
	array('Bohemia', 'Land', 'No', 567, 586, 298, 227, 'Austria'),
	array('Vienna', 'Land', 'Yes', 602, 637, 314, 246, 'Austria'),
	array('Trieste', 'Coast', 'Yes', 579, 710, 308, 288, 'Austria'),
	array('Budapest', 'Land', 'Yes', 661, 678, 350, 260, 'Austria'),
	array('Galicia', 'Land', 'No', 710, 610, 378, 240, 'Austria'),
	array('Spain (North Coast)', 'Coast', 'No', 193, 685, 90, 273, 'Neutral'),
	array('Spain (South Coast)', 'Coast', 'No', 191, 832, 106, 345, 'Neutral'),
	array('St. Petersburg (North Coast)', 'Coast', 'No', 828, 90, 448, 59, 'Russia'),
	array('St. Petersburg (South Coast)', 'Coast', 'No', 760, 335, 397, 130, 'Russia'),
	array('Bulgaria (North Coast)', 'Coast', 'No', 785, 762, 424, 304, 'Neutral'),
	array('Bulgaria (South Coast)', 'Coast', 'No', 749, 815, 397, 332, 'Neutral')
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $x, $y, $sx, $sy, $country)=$territoryRawRow;
	if( $country=='Neutral' )
		$countryID=0;
	else
		$countryID=$this->countryID($country);
		
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);
$bordersRawData=array(
	array('Clyde','Edinburgh','Yes','Yes'),
	array('Clyde','Liverpool','Yes','Yes'),
	array('Clyde','Yorkshire','Yes','Yes'),
	array('Clyde','Wales','Yes','Yes'),
	array('Clyde','Norway','Yes','No'),
	array('Clyde','Barents Sea','Yes','No'),
	array('Clyde','Norwegian Sea','Yes','No'),
	array('Clyde','North Sea','Yes','No'),
	array('Clyde','North Atlantic Ocean','Yes','No'),
	array('Clyde','Irish Sea','Yes','No'),
	array('Clyde','Mid-Atlantic Ocean','Yes','No'),
	array('Edinburgh','Clyde','Yes','Yes'),
	array('Edinburgh','Liverpool','Yes','Yes'),
	array('Edinburgh','Yorkshire','Yes','Yes'),
	array('Edinburgh','Wales','No','Yes'),
	array('Edinburgh','London','Yes','Yes'),
	array('Edinburgh','Norway','Yes','No'),
	array('Edinburgh','Denmark','Yes','No'),
	array('Edinburgh','Holland','Yes','No'),
	array('Edinburgh','Belgium','Yes','No'),
	array('Edinburgh','Barents Sea','Yes','No'),
	array('Edinburgh','Norwegian Sea','Yes','No'),
	array('Edinburgh','North Sea','Yes','No'),
	array('Edinburgh','Skagerrack','Yes','No'),
	array('Edinburgh','Heligoland Bight','Yes','No'),
	array('Edinburgh','North Atlantic Ocean','Yes','No'),
	array('Edinburgh','English Channel','Yes','No'),
	array('Liverpool','Clyde','Yes','Yes'),
	array('Liverpool','Edinburgh','Yes','Yes'),
	array('Liverpool','Yorkshire','No','Yes'),
	array('Liverpool','Wales','Yes','Yes'),
	array('Liverpool','London','Yes','Yes'),
	array('Liverpool','Norwegian Sea','Yes','No'),
	array('Liverpool','North Atlantic Ocean','Yes','No'),
	array('Liverpool','Irish Sea','Yes','No'),
	array('Liverpool','English Channel','Yes','No'),
	array('Liverpool','Mid-Atlantic Ocean','Yes','No'),
	array('Yorkshire','Clyde','Yes','Yes'),
	array('Yorkshire','Edinburgh','Yes','Yes'),
	array('Yorkshire','Liverpool','No','Yes'),
	array('Yorkshire','Wales','Yes','Yes'),
	array('Yorkshire','London','Yes','Yes'),
	array('Yorkshire','Norway','Yes','No'),
	array('Yorkshire','Denmark','Yes','No'),
	array('Yorkshire','Holland','Yes','No'),
	array('Yorkshire','Belgium','Yes','No'),
	array('Yorkshire','Norwegian Sea','Yes','No'),
	array('Yorkshire','North Sea','Yes','No'),
	array('Yorkshire','Skagerrack','Yes','No'),
	array('Yorkshire','Heligoland Bight','Yes','No'),
	array('Yorkshire','English Channel','Yes','No'),
	array('Wales','Clyde','Yes','Yes'),
	array('Wales','Edinburgh','No','Yes'),
	array('Wales','Liverpool','Yes','Yes'),
	array('Wales','Yorkshire','Yes','Yes'),
	array('Wales','London','Yes','Yes'),
	array('Wales','Belgium','Yes','No'),
	array('Wales','Picardy','Yes','No'),
	array('Wales','Brest','Yes','No'),
	array('Wales','North Sea','Yes','No'),
	array('Wales','North Atlantic Ocean','Yes','No'),
	array('Wales','Irish Sea','Yes','No'),
	array('Wales','English Channel','Yes','No'),
	array('Wales','Mid-Atlantic Ocean','Yes','No'),
	array('London','Edinburgh','Yes','Yes'),
	array('London','Liverpool','Yes','Yes'),
	array('London','Yorkshire','Yes','Yes'),
	array('London','Wales','Yes','Yes'),
	array('London','Norway','Yes','No'),
	array('London','Denmark','Yes','No'),
	array('London','Holland','Yes','No'),
	array('London','Belgium','Yes','No'),
	array('London','Picardy','Yes','No'),
	array('London','Brest','Yes','No'),
	array('London','Norwegian Sea','Yes','No'),
	array('London','North Sea','Yes','No'),
	array('London','Skagerrack','Yes','No'),
	array('London','Heligoland Bight','Yes','No'),
	array('London','North Atlantic Ocean','Yes','No'),
	array('London','Irish Sea','Yes','No'),
	array('London','English Channel','Yes','No'),
	array('London','Mid-Atlantic Ocean','Yes','No'),
	array('Portugal','Spain','No','Yes'),
	array('Portugal','North Africa','Yes','No'),
	array('Portugal','Brest','Yes','No'),
	array('Portugal','Marseilles','Yes','Yes'),
	array('Portugal','Gascony','Yes','Yes'),
	array('Portugal','North Atlantic Ocean','Yes','No'),
	array('Portugal','Irish Sea','Yes','No'),
	array('Portugal','English Channel','Yes','No'),
	array('Portugal','Mid-Atlantic Ocean','Yes','No'),
	array('Portugal','Western Mediterranean','Yes','No'),
	array('Portugal','Gulf of Lyons','Yes','No'),
	array('Portugal','Spain (North Coast)','Yes','No'),
	array('Portugal','Spain (South Coast)','Yes','No'),
	array('Spain','Portugal','No','Yes'),
	array('Spain','Piedmont','No','Yes'),
	array('Spain','Brest','No','Yes'),
	array('Spain','Paris','No','Yes'),
	array('Spain','Burgundy','No','Yes'),
	array('Spain','Marseilles','No','Yes'),
	array('Spain','Gascony','No','Yes'),
	array('North Africa','Portugal','Yes','No'),
	array('North Africa','Tunis','Yes','Yes'),
	array('North Africa','Brest','Yes','No'),
	array('North Africa','Gascony','Yes','No'),
	array('North Africa','North Atlantic Ocean','Yes','No'),
	array('North Africa','Irish Sea','Yes','No'),
	array('North Africa','English Channel','Yes','No'),
	array('North Africa','Mid-Atlantic Ocean','Yes','No'),
	array('North Africa','Western Mediterranean','Yes','No'),
	array('North Africa','Gulf of Lyons','Yes','No'),
	array('North Africa','Tyrrhenian Sea','Yes','No'),
	array('North Africa','Ionian Sea','Yes','No'),
	array('North Africa','Spain (North Coast)','Yes','No'),
	array('North Africa','Spain (South Coast)','Yes','No'),
	array('Tunis','North Africa','Yes','Yes'),
	array('Tunis','Naples','Yes','No'),
	array('Tunis','Rome','Yes','No'),
	array('Tunis','Tuscany','Yes','No'),
	array('Tunis','Apulia','Yes','No'),
	array('Tunis','Greece','Yes','No'),
	array('Tunis','Albania','Yes','No'),
	array('Tunis','Mid-Atlantic Ocean','Yes','No'),
	array('Tunis','Western Mediterranean','Yes','No'),
	array('Tunis','Gulf of Lyons','Yes','No'),
	array('Tunis','Tyrrhenian Sea','Yes','No'),
	array('Tunis','Ionian Sea','Yes','No'),
	array('Tunis','Adriatic Sea','Yes','No'),
	array('Tunis','Aegean Sea','Yes','No'),
	array('Tunis','Eastern Mediterranean','Yes','No'),
	array('Tunis','Spain (South Coast)','Yes','No'),
	array('Naples','Tunis','Yes','No'),
	array('Naples','Rome','Yes','Yes'),
	array('Naples','Tuscany','Yes','Yes'),
	array('Naples','Venice','Yes','Yes'),
	array('Naples','Apulia','Yes','Yes'),
	array('Naples','Greece','Yes','No'),
	array('Naples','Albania','Yes','No'),
	array('Naples','Western Mediterranean','Yes','No'),
	array('Naples','Gulf of Lyons','Yes','No'),
	array('Naples','Tyrrhenian Sea','Yes','No'),
	array('Naples','Ionian Sea','Yes','No'),
	array('Naples','Adriatic Sea','Yes','No'),
	array('Naples','Aegean Sea','Yes','No'),
	array('Naples','Eastern Mediterranean','Yes','No'),
	array('Rome','Tunis','Yes','No'),
	array('Rome','Naples','Yes','Yes'),
	array('Rome','Tuscany','Yes','Yes'),
	array('Rome','Piedmont','Yes','Yes'),
	array('Rome','Venice','No','Yes'),
	array('Rome','Apulia','Yes','Yes'),
	array('Rome','Western Mediterranean','Yes','No'),
	array('Rome','Gulf of Lyons','Yes','No'),
	array('Rome','Tyrrhenian Sea','Yes','No'),
	array('Rome','Ionian Sea','Yes','No'),
	array('Rome','Tyrolia','No','Yes'),
	array('Rome','Trieste','No','Yes'),
	array('Tuscany','Tunis','Yes','No'),
	array('Tuscany','Naples','Yes','Yes'),
	array('Tuscany','Rome','Yes','Yes'),
	array('Tuscany','Piedmont','Yes','Yes'),
	array('Tuscany','Venice','No','Yes'),
	array('Tuscany','Apulia','No','Yes'),
	array('Tuscany','Marseilles','Yes','Yes'),
	array('Tuscany','Western Mediterranean','Yes','No'),
	array('Tuscany','Gulf of Lyons','Yes','No'),
	array('Tuscany','Tyrrhenian Sea','Yes','No'),
	array('Tuscany','Ionian Sea','Yes','No'),
	array('Tuscany','Tyrolia','No','Yes'),
	array('Tuscany','Trieste','No','Yes'),
	array('Tuscany','Spain (South Coast)','Yes','No'),
	array('Piedmont','Spain','No','Yes'),
	array('Piedmont','Rome','Yes','Yes'),
	array('Piedmont','Tuscany','Yes','Yes'),
	array('Piedmont','Venice','No','Yes'),
	array('Piedmont','Apulia','No','Yes'),
	array('Piedmont','Munich','No','Yes'),
	array('Piedmont','Burgundy','No','Yes'),
	array('Piedmont','Marseilles','Yes','Yes'),
	array('Piedmont','Gascony','No','Yes'),
	array('Piedmont','Western Mediterranean','Yes','No'),
	array('Piedmont','Gulf of Lyons','Yes','No'),
	array('Piedmont','Tyrrhenian Sea','Yes','No'),
	array('Piedmont','Tyrolia','No','Yes'),
	array('Piedmont','Bohemia','No','Yes'),
	array('Piedmont','Vienna','No','Yes'),
	array('Piedmont','Trieste','No','Yes'),
	array('Piedmont','Spain (South Coast)','Yes','No'),
	array('Venice','Naples','Yes','Yes'),
	array('Venice','Rome','No','Yes'),
	array('Venice','Tuscany','No','Yes'),
	array('Venice','Piedmont','No','Yes'),
	array('Venice','Apulia','Yes','Yes'),
	array('Venice','Albania','Yes','Yes'),
	array('Venice','Serbia','No','Yes'),
	array('Venice','Munich','No','Yes'),
	array('Venice','Marseilles','No','Yes'),
	array('Venice','Ionian Sea','Yes','No'),
	array('Venice','Adriatic Sea','Yes','No'),
	array('Venice','Tyrolia','No','Yes'),
	array('Venice','Bohemia','No','Yes'),
	array('Venice','Vienna','No','Yes'),
	array('Venice','Trieste','Yes','Yes'),
	array('Venice','Budapest','No','Yes'),
	array('Apulia','Tunis','Yes','No'),
	array('Apulia','Naples','Yes','Yes'),
	array('Apulia','Rome','Yes','Yes'),
	array('Apulia','Tuscany','No','Yes'),
	array('Apulia','Piedmont','No','Yes'),
	array('Apulia','Venice','Yes','Yes'),
	array('Apulia','Greece','Yes','No'),
	array('Apulia','Albania','Yes','No'),
	array('Apulia','Tyrrhenian Sea','Yes','No'),
	array('Apulia','Ionian Sea','Yes','No'),
	array('Apulia','Adriatic Sea','Yes','No'),
	array('Apulia','Aegean Sea','Yes','No'),
	array('Apulia','Eastern Mediterranean','Yes','No'),
	array('Apulia','Trieste','Yes','Yes'),
	array('Greece','Tunis','Yes','No'),
	array('Greece','Naples','Yes','No'),
	array('Greece','Apulia','Yes','No'),
	array('Greece','Albania','Yes','Yes'),
	array('Greece','Serbia','No','Yes'),
	array('Greece','Bulgaria','No','Yes'),
	array('Greece','Rumania','No','Yes'),
	array('Greece','Constantinople','Yes','Yes'),
	array('Greece','Smyrna','Yes','No'),
	array('Greece','Tyrrhenian Sea','Yes','No'),
	array('Greece','Ionian Sea','Yes','No'),
	array('Greece','Adriatic Sea','Yes','No'),
	array('Greece','Aegean Sea','Yes','No'),
	array('Greece','Eastern Mediterranean','Yes','No'),
	array('Greece','Trieste','Yes','Yes'),
	array('Greece','Budapest','No','Yes'),
	array('Greece','Bulgaria (South Coast)','Yes','No'),
	array('Albania','Tunis','Yes','No'),
	array('Albania','Naples','Yes','No'),
	array('Albania','Venice','Yes','Yes'),
	array('Albania','Apulia','Yes','No'),
	array('Albania','Greece','Yes','Yes'),
	array('Albania','Serbia','No','Yes'),
	array('Albania','Bulgaria','No','Yes'),
	array('Albania','Rumania','No','Yes'),
	array('Albania','Tyrrhenian Sea','Yes','No'),
	array('Albania','Ionian Sea','Yes','No'),
	array('Albania','Adriatic Sea','Yes','No'),
	array('Albania','Aegean Sea','Yes','No'),
	array('Albania','Eastern Mediterranean','Yes','No'),
	array('Albania','Tyrolia','No','Yes'),
	array('Albania','Vienna','No','Yes'),
	array('Albania','Trieste','Yes','Yes'),
	array('Albania','Budapest','No','Yes'),
	array('Albania','Bulgaria (South Coast)','Yes','No'),
	array('Serbia','Venice','No','Yes'),
	array('Serbia','Greece','No','Yes'),
	array('Serbia','Albania','No','Yes'),
	array('Serbia','Bulgaria','No','Yes'),
	array('Serbia','Rumania','No','Yes'),
	array('Serbia','Constantinople','No','Yes'),
	array('Serbia','Sevastopol','No','Yes'),
	array('Serbia','Ukraine','No','Yes'),
	array('Serbia','Tyrolia','No','Yes'),
	array('Serbia','Vienna','No','Yes'),
	array('Serbia','Trieste','No','Yes'),
	array('Serbia','Budapest','No','Yes'),
	array('Serbia','Galicia','No','Yes'),
	array('Bulgaria','Greece','No','Yes'),
	array('Bulgaria','Albania','No','Yes'),
	array('Bulgaria','Serbia','No','Yes'),
	array('Bulgaria','Rumania','No','Yes'),
	array('Bulgaria','Constantinople','No','Yes'),
	array('Bulgaria','Smyrna','No','Yes'),
	array('Bulgaria','Ankara','No','Yes'),
	array('Bulgaria','Sevastopol','No','Yes'),
	array('Bulgaria','Ukraine','No','Yes'),
	array('Bulgaria','Trieste','No','Yes'),
	array('Bulgaria','Budapest','No','Yes'),
	array('Bulgaria','Galicia','No','Yes'),
	array('Rumania','Greece','No','Yes'),
	array('Rumania','Albania','No','Yes'),
	array('Rumania','Serbia','No','Yes'),
	array('Rumania','Bulgaria','No','Yes'),
	array('Rumania','Constantinople','Yes','Yes'),
	array('Rumania','Ankara','Yes','No'),
	array('Rumania','Armenia','Yes','Yes'),
	array('Rumania','Sevastopol','Yes','Yes'),
	array('Rumania','Ukraine','No','Yes'),
	array('Rumania','Warsaw','No','Yes'),
	array('Rumania','Moscow','No','Yes'),
	array('Rumania','Silesia','No','Yes'),
	array('Rumania','Black Sea','Yes','No'),
	array('Rumania','Bohemia','No','Yes'),
	array('Rumania','Vienna','No','Yes'),
	array('Rumania','Trieste','No','Yes'),
	array('Rumania','Budapest','No','Yes'),
	array('Rumania','Galicia','No','Yes'),
	array('Rumania','Bulgaria (North Coast)','Yes','No'),
	array('Constantinople','Greece','Yes','Yes'),
	array('Constantinople','Serbia','No','Yes'),
	array('Constantinople','Bulgaria','No','Yes'),
	array('Constantinople','Rumania','Yes','Yes'),
	array('Constantinople','Smyrna','Yes','Yes'),
	array('Constantinople','Ankara','Yes','Yes'),
	array('Constantinople','Armenia','Yes','Yes'),
	array('Constantinople','Syria','Yes','Yes'),
	array('Constantinople','Sevastopol','Yes','No'),
	array('Constantinople','Ionian Sea','Yes','No'),
	array('Constantinople','Aegean Sea','Yes','No'),
	array('Constantinople','Eastern Mediterranean','Yes','No'),
	array('Constantinople','Black Sea','Yes','No'),
	array('Constantinople','Bulgaria (North Coast)','Yes','No'),
	array('Constantinople','Bulgaria (South Coast)','Yes','No'),
	array('Smyrna','Greece','Yes','No'),
	array('Smyrna','Bulgaria','No','Yes'),
	array('Smyrna','Constantinople','Yes','Yes'),
	array('Smyrna','Ankara','Yes','Yes'),
	array('Smyrna','Armenia','No','Yes'),
	array('Smyrna','Syria','Yes','Yes'),
	array('Smyrna','Sevastopol','No','Yes'),
	array('Smyrna','Ionian Sea','Yes','No'),
	array('Smyrna','Aegean Sea','Yes','No'),
	array('Smyrna','Eastern Mediterranean','Yes','No'),
	array('Smyrna','Black Sea','Yes','No'),
	array('Smyrna','Bulgaria (North Coast)','Yes','No'),
	array('Smyrna','Bulgaria (South Coast)','Yes','No'),
	array('Ankara','Bulgaria','No','Yes'),
	array('Ankara','Rumania','Yes','No'),
	array('Ankara','Constantinople','Yes','Yes'),
	array('Ankara','Smyrna','Yes','Yes'),
	array('Ankara','Armenia','Yes','Yes'),
	array('Ankara','Syria','No','Yes'),
	array('Ankara','Sevastopol','Yes','Yes'),
	array('Ankara','Aegean Sea','Yes','No'),
	array('Ankara','Black Sea','Yes','No'),
	array('Ankara','Bulgaria (North Coast)','Yes','No'),
	array('Ankara','Bulgaria (South Coast)','Yes','No'),
	array('Armenia','Rumania','Yes','Yes'),
	array('Armenia','Constantinople','Yes','Yes'),
	array('Armenia','Smyrna','No','Yes'),
	array('Armenia','Ankara','Yes','Yes'),
	array('Armenia','Syria','No','Yes'),
	array('Armenia','Sevastopol','Yes','Yes'),
	array('Armenia','Ukraine','No','Yes'),
	array('Armenia','Moscow','No','Yes'),
	array('Armenia','Black Sea','Yes','No'),
	array('Armenia','Bulgaria (North Coast)','Yes','No'),
	array('Syria','Constantinople','Yes','Yes'),
	array('Syria','Smyrna','Yes','Yes'),
	array('Syria','Ankara','No','Yes'),
	array('Syria','Armenia','No','Yes'),
	array('Syria','Sevastopol','No','Yes'),
	array('Syria','Ionian Sea','Yes','No'),
	array('Syria','Aegean Sea','Yes','No'),
	array('Syria','Eastern Mediterranean','Yes','No'),
	array('Sevastopol','Serbia','No','Yes'),
	array('Sevastopol','Bulgaria','No','Yes'),
	array('Sevastopol','Rumania','Yes','Yes'),
	array('Sevastopol','Constantinople','Yes','No'),
	array('Sevastopol','Smyrna','No','Yes'),
	array('Sevastopol','Ankara','Yes','Yes'),
	array('Sevastopol','Armenia','Yes','Yes'),
	array('Sevastopol','Syria','No','Yes'),
	array('Sevastopol','Ukraine','No','Yes'),
	array('Sevastopol','Warsaw','No','Yes'),
	array('Sevastopol','Livonia','No','Yes'),
	array('Sevastopol','Moscow','No','Yes'),
	array('Sevastopol','St. Petersburg','No','Yes'),
	array('Sevastopol','Black Sea','Yes','No'),
	array('Sevastopol','Budapest','No','Yes'),
	array('Sevastopol','Galicia','No','Yes'),
	array('Sevastopol','Bulgaria (North Coast)','Yes','No'),
	array('Ukraine','Serbia','No','Yes'),
	array('Ukraine','Bulgaria','No','Yes'),
	array('Ukraine','Rumania','No','Yes'),
	array('Ukraine','Armenia','No','Yes'),
	array('Ukraine','Sevastopol','No','Yes'),
	array('Ukraine','Warsaw','No','Yes'),
	array('Ukraine','Livonia','No','Yes'),
	array('Ukraine','Moscow','No','Yes'),
	array('Ukraine','St. Petersburg','No','Yes'),
	array('Ukraine','Prussia','No','Yes'),
	array('Ukraine','Silesia','No','Yes'),
	array('Ukraine','Bohemia','No','Yes'),
	array('Ukraine','Vienna','No','Yes'),
	array('Ukraine','Budapest','No','Yes'),
	array('Ukraine','Galicia','No','Yes'),
	array('Warsaw','Rumania','No','Yes'),
	array('Warsaw','Sevastopol','No','Yes'),
	array('Warsaw','Ukraine','No','Yes'),
	array('Warsaw','Livonia','No','Yes'),
	array('Warsaw','Moscow','No','Yes'),
	array('Warsaw','St. Petersburg','No','Yes'),
	array('Warsaw','Berlin','No','Yes'),
	array('Warsaw','Prussia','No','Yes'),
	array('Warsaw','Silesia','No','Yes'),
	array('Warsaw','Munich','No','Yes'),
	array('Warsaw','Bohemia','No','Yes'),
	array('Warsaw','Vienna','No','Yes'),
	array('Warsaw','Budapest','No','Yes'),
	array('Warsaw','Galicia','No','Yes'),
	array('Livonia','Sevastopol','No','Yes'),
	array('Livonia','Ukraine','No','Yes'),
	array('Livonia','Warsaw','No','Yes'),
	array('Livonia','Moscow','No','Yes'),
	array('Livonia','St. Petersburg','No','Yes'),
	array('Livonia','Finland','Yes','Yes'),
	array('Livonia','Sweden','Yes','No'),
	array('Livonia','Norway','No','Yes'),
	array('Livonia','Denmark','Yes','No'),
	array('Livonia','Kiel','Yes','No'),
	array('Livonia','Berlin','Yes','Yes'),
	array('Livonia','Prussia','Yes','Yes'),
	array('Livonia','Silesia','No','Yes'),
	array('Livonia','Baltic Sea','Yes','No'),
	array('Livonia','Gulf of Bothnia','Yes','No'),
	array('Livonia','Galicia','No','Yes'),
	array('Livonia','St. Petersburg (South Coast)','Yes','No'),
	array('Moscow','Rumania','No','Yes'),
	array('Moscow','Armenia','No','Yes'),
	array('Moscow','Sevastopol','No','Yes'),
	array('Moscow','Ukraine','No','Yes'),
	array('Moscow','Warsaw','No','Yes'),
	array('Moscow','Livonia','No','Yes'),
	array('Moscow','St. Petersburg','No','Yes'),
	array('Moscow','Finland','No','Yes'),
	array('Moscow','Norway','No','Yes'),
	array('Moscow','Prussia','No','Yes'),
	array('Moscow','Silesia','No','Yes'),
	array('Moscow','Galicia','No','Yes'),
	array('St. Petersburg','Sevastopol','No','Yes'),
	array('St. Petersburg','Ukraine','No','Yes'),
	array('St. Petersburg','Warsaw','No','Yes'),
	array('St. Petersburg','Livonia','No','Yes'),
	array('St. Petersburg','Moscow','No','Yes'),
	array('St. Petersburg','Finland','No','Yes'),
	array('St. Petersburg','Sweden','No','Yes'),
	array('St. Petersburg','Norway','No','Yes'),
	array('St. Petersburg','Prussia','No','Yes'),
	array('Finland','Livonia','Yes','Yes'),
	array('Finland','Moscow','No','Yes'),
	array('Finland','St. Petersburg','No','Yes'),
	array('Finland','Sweden','Yes','Yes'),
	array('Finland','Norway','Yes','Yes'),
	array('Finland','Denmark','Yes','Yes'),
	array('Finland','Skagerrack','Yes','No'),
	array('Finland','Baltic Sea','Yes','No'),
	array('Finland','Gulf of Bothnia','Yes','No'),
	array('Finland','St. Petersburg (South Coast)','Yes','No'),
	array('Sweden','Livonia','Yes','No'),
	array('Sweden','St. Petersburg','No','Yes'),
	array('Sweden','Finland','Yes','Yes'),
	array('Sweden','Norway','Yes','Yes'),
	array('Sweden','Denmark','Yes','Yes'),
	array('Sweden','Kiel','Yes','Yes'),
	array('Sweden','Berlin','Yes','No'),
	array('Sweden','Prussia','Yes','No'),
	array('Sweden','Barents Sea','Yes','No'),
	array('Sweden','Norwegian Sea','Yes','No'),
	array('Sweden','North Sea','Yes','No'),
	array('Sweden','Skagerrack','Yes','No'),
	array('Sweden','Heligoland Bight','Yes','No'),
	array('Sweden','Baltic Sea','Yes','No'),
	array('Sweden','Gulf of Bothnia','Yes','No'),
	array('Sweden','St. Petersburg (North Coast)','Yes','No'),
	array('Sweden','St. Petersburg (South Coast)','Yes','No'),
	array('Norway','Clyde','Yes','No'),
	array('Norway','Edinburgh','Yes','No'),
	array('Norway','Yorkshire','Yes','No'),
	array('Norway','London','Yes','No'),
	array('Norway','Livonia','No','Yes'),
	array('Norway','Moscow','No','Yes'),
	array('Norway','St. Petersburg','No','Yes'),
	array('Norway','Finland','Yes','Yes'),
	array('Norway','Sweden','Yes','Yes'),
	array('Norway','Denmark','Yes','Yes'),
	array('Norway','Holland','Yes','No'),
	array('Norway','Belgium','Yes','No'),
	array('Norway','Barents Sea','Yes','No'),
	array('Norway','Norwegian Sea','Yes','No'),
	array('Norway','North Sea','Yes','No'),
	array('Norway','Skagerrack','Yes','No'),
	array('Norway','Heligoland Bight','Yes','No'),
	array('Norway','Baltic Sea','Yes','No'),
	array('Norway','Gulf of Bothnia','Yes','No'),
	array('Norway','North Atlantic Ocean','Yes','No'),
	array('Norway','English Channel','Yes','No'),
	array('Norway','St. Petersburg (North Coast)','Yes','No'),
	array('Denmark','Edinburgh','Yes','No'),
	array('Denmark','Yorkshire','Yes','No'),
	array('Denmark','London','Yes','No'),
	array('Denmark','Livonia','Yes','No'),
	array('Denmark','Finland','Yes','Yes'),
	array('Denmark','Sweden','Yes','Yes'),
	array('Denmark','Norway','Yes','Yes'),
	array('Denmark','Kiel','Yes','Yes'),
	array('Denmark','Berlin','Yes','Yes'),
	array('Denmark','Munich','No','Yes'),
	array('Denmark','Ruhr','No','Yes'),
	array('Denmark','Holland','Yes','Yes'),
	array('Denmark','Belgium','Yes','No'),
	array('Denmark','Norwegian Sea','Yes','No'),
	array('Denmark','North Sea','Yes','No'),
	array('Denmark','Skagerrack','Yes','No'),
	array('Denmark','Heligoland Bight','Yes','No'),
	array('Denmark','Baltic Sea','Yes','No'),
	array('Denmark','Gulf of Bothnia','Yes','No'),
	array('Denmark','English Channel','Yes','No'),
	array('Kiel','Livonia','Yes','No'),
	array('Kiel','Sweden','Yes','Yes'),
	array('Kiel','Denmark','Yes','Yes'),
	array('Kiel','Berlin','Yes','Yes'),
	array('Kiel','Prussia','Yes','Yes'),
	array('Kiel','Silesia','No','Yes'),
	array('Kiel','Munich','No','Yes'),
	array('Kiel','Ruhr','No','Yes'),
	array('Kiel','Holland','Yes','Yes'),
	array('Kiel','Belgium','Yes','Yes'),
	array('Kiel','Burgundy','No','Yes'),
	array('Kiel','North Sea','Yes','No'),
	array('Kiel','Skagerrack','Yes','No'),
	array('Kiel','Heligoland Bight','Yes','No'),
	array('Kiel','Baltic Sea','Yes','No'),
	array('Kiel','Gulf of Bothnia','Yes','No'),
	array('Kiel','Tyrolia','No','Yes'),
	array('Kiel','Bohemia','No','Yes'),
	array('Berlin','Warsaw','No','Yes'),
	array('Berlin','Livonia','Yes','Yes'),
	array('Berlin','Sweden','Yes','No'),
	array('Berlin','Denmark','Yes','Yes'),
	array('Berlin','Kiel','Yes','Yes'),
	array('Berlin','Prussia','Yes','Yes'),
	array('Berlin','Silesia','No','Yes'),
	array('Berlin','Munich','No','Yes'),
	array('Berlin','Ruhr','No','Yes'),
	array('Berlin','Holland','Yes','Yes'),
	array('Berlin','Burgundy','No','Yes'),
	array('Berlin','Heligoland Bight','Yes','No'),
	array('Berlin','Baltic Sea','Yes','No'),
	array('Berlin','Gulf of Bothnia','Yes','No'),
	array('Berlin','Tyrolia','No','Yes'),
	array('Berlin','Bohemia','No','Yes'),
	array('Berlin','Galicia','No','Yes'),
	array('Prussia','Ukraine','No','Yes'),
	array('Prussia','Warsaw','No','Yes'),
	array('Prussia','Livonia','Yes','Yes'),
	array('Prussia','Moscow','No','Yes'),
	array('Prussia','St. Petersburg','No','Yes'),
	array('Prussia','Sweden','Yes','No'),
	array('Prussia','Kiel','Yes','Yes'),
	array('Prussia','Berlin','Yes','Yes'),
	array('Prussia','Silesia','No','Yes'),
	array('Prussia','Munich','No','Yes'),
	array('Prussia','Baltic Sea','Yes','No'),
	array('Prussia','Gulf of Bothnia','Yes','No'),
	array('Prussia','Bohemia','No','Yes'),
	array('Prussia','Galicia','No','Yes'),
	array('Prussia','St. Petersburg (South Coast)','Yes','No'),
	array('Silesia','Rumania','No','Yes'),
	array('Silesia','Ukraine','No','Yes'),
	array('Silesia','Warsaw','No','Yes'),
	array('Silesia','Livonia','No','Yes'),
	array('Silesia','Moscow','No','Yes'),
	array('Silesia','Kiel','No','Yes'),
	array('Silesia','Berlin','No','Yes'),
	array('Silesia','Prussia','No','Yes'),
	array('Silesia','Munich','No','Yes'),
	array('Silesia','Ruhr','No','Yes'),
	array('Silesia','Burgundy','No','Yes'),
	array('Silesia','Tyrolia','No','Yes'),
	array('Silesia','Bohemia','No','Yes'),
	array('Silesia','Vienna','No','Yes'),
	array('Silesia','Budapest','No','Yes'),
	array('Silesia','Galicia','No','Yes'),
	array('Munich','Piedmont','No','Yes'),
	array('Munich','Venice','No','Yes'),
	array('Munich','Warsaw','No','Yes'),
	array('Munich','Denmark','No','Yes'),
	array('Munich','Kiel','No','Yes'),
	array('Munich','Berlin','No','Yes'),
	array('Munich','Prussia','No','Yes'),
	array('Munich','Silesia','No','Yes'),
	array('Munich','Ruhr','No','Yes'),
	array('Munich','Holland','No','Yes'),
	array('Munich','Belgium','No','Yes'),
	array('Munich','Picardy','No','Yes'),
	array('Munich','Paris','No','Yes'),
	array('Munich','Burgundy','No','Yes'),
	array('Munich','Marseilles','No','Yes'),
	array('Munich','Gascony','No','Yes'),
	array('Munich','Tyrolia','No','Yes'),
	array('Munich','Bohemia','No','Yes'),
	array('Munich','Vienna','No','Yes'),
	array('Munich','Trieste','No','Yes'),
	array('Munich','Galicia','No','Yes'),
	array('Ruhr','Denmark','No','Yes'),
	array('Ruhr','Kiel','No','Yes'),
	array('Ruhr','Berlin','No','Yes'),
	array('Ruhr','Silesia','No','Yes'),
	array('Ruhr','Munich','No','Yes'),
	array('Ruhr','Holland','No','Yes'),
	array('Ruhr','Belgium','No','Yes'),
	array('Ruhr','Picardy','No','Yes'),
	array('Ruhr','Paris','No','Yes'),
	array('Ruhr','Burgundy','No','Yes'),
	array('Ruhr','Marseilles','No','Yes'),
	array('Ruhr','Gascony','No','Yes'),
	array('Ruhr','Tyrolia','No','Yes'),
	array('Ruhr','Bohemia','No','Yes'),
	array('Holland','Edinburgh','Yes','No'),
	array('Holland','Yorkshire','Yes','No'),
	array('Holland','London','Yes','No'),
	array('Holland','Norway','Yes','No'),
	array('Holland','Denmark','Yes','Yes'),
	array('Holland','Kiel','Yes','Yes'),
	array('Holland','Berlin','Yes','Yes'),
	array('Holland','Munich','No','Yes'),
	array('Holland','Ruhr','No','Yes'),
	array('Holland','Belgium','Yes','Yes'),
	array('Holland','Picardy','Yes','Yes'),
	array('Holland','Burgundy','No','Yes'),
	array('Holland','Norwegian Sea','Yes','No'),
	array('Holland','North Sea','Yes','No'),
	array('Holland','Skagerrack','Yes','No'),
	array('Holland','Heligoland Bight','Yes','No'),
	array('Holland','Baltic Sea','Yes','No'),
	array('Holland','English Channel','Yes','No'),
	array('Belgium','Edinburgh','Yes','No'),
	array('Belgium','Yorkshire','Yes','No'),
	array('Belgium','Wales','Yes','No'),
	array('Belgium','London','Yes','No'),
	array('Belgium','Norway','Yes','No'),
	array('Belgium','Denmark','Yes','No'),
	array('Belgium','Kiel','Yes','Yes'),
	array('Belgium','Munich','No','Yes'),
	array('Belgium','Ruhr','No','Yes'),
	array('Belgium','Holland','Yes','Yes'),
	array('Belgium','Picardy','Yes','Yes'),
	array('Belgium','Brest','Yes','Yes'),
	array('Belgium','Paris','No','Yes'),
	array('Belgium','Burgundy','No','Yes'),
	array('Belgium','Marseilles','No','Yes'),
	array('Belgium','Gascony','No','Yes'),
	array('Belgium','Norwegian Sea','Yes','No'),
	array('Belgium','North Sea','Yes','No'),
	array('Belgium','Skagerrack','Yes','No'),
	array('Belgium','Heligoland Bight','Yes','No'),
	array('Belgium','Irish Sea','Yes','No'),
	array('Belgium','English Channel','Yes','No'),
	array('Belgium','Mid-Atlantic Ocean','Yes','No'),
	array('Picardy','Wales','Yes','No'),
	array('Picardy','London','Yes','No'),
	array('Picardy','Munich','No','Yes'),
	array('Picardy','Ruhr','No','Yes'),
	array('Picardy','Holland','Yes','Yes'),
	array('Picardy','Belgium','Yes','Yes'),
	array('Picardy','Brest','Yes','Yes'),
	array('Picardy','Paris','No','Yes'),
	array('Picardy','Burgundy','No','Yes'),
	array('Picardy','Marseilles','No','Yes'),
	array('Picardy','Gascony','Yes','Yes'),
	array('Picardy','North Sea','Yes','No'),
	array('Picardy','Irish Sea','Yes','No'),
	array('Picardy','English Channel','Yes','No'),
	array('Picardy','Mid-Atlantic Ocean','Yes','No'),
	array('Brest','Wales','Yes','No'),
	array('Brest','London','Yes','No'),
	array('Brest','Portugal','Yes','No'),
	array('Brest','Spain','No','Yes'),
	array('Brest','North Africa','Yes','No'),
	array('Brest','Belgium','Yes','Yes'),
	array('Brest','Picardy','Yes','Yes'),
	array('Brest','Paris','No','Yes'),
	array('Brest','Burgundy','No','Yes'),
	array('Brest','Marseilles','No','Yes'),
	array('Brest','Gascony','Yes','Yes'),
	array('Brest','North Sea','Yes','No'),
	array('Brest','North Atlantic Ocean','Yes','No'),
	array('Brest','Irish Sea','Yes','No'),
	array('Brest','English Channel','Yes','No'),
	array('Brest','Mid-Atlantic Ocean','Yes','No'),
	array('Brest','Western Mediterranean','Yes','No'),
	array('Brest','Spain (North Coast)','Yes','No'),
	array('Brest','Spain (South Coast)','Yes','No'),
	array('Paris','Spain','No','Yes'),
	array('Paris','Munich','No','Yes'),
	array('Paris','Ruhr','No','Yes'),
	array('Paris','Belgium','No','Yes'),
	array('Paris','Picardy','No','Yes'),
	array('Paris','Brest','No','Yes'),
	array('Paris','Burgundy','No','Yes'),
	array('Paris','Marseilles','No','Yes'),
	array('Paris','Gascony','No','Yes'),
	array('Burgundy','Spain','No','Yes'),
	array('Burgundy','Piedmont','No','Yes'),
	array('Burgundy','Kiel','No','Yes'),
	array('Burgundy','Berlin','No','Yes'),
	array('Burgundy','Silesia','No','Yes'),
	array('Burgundy','Munich','No','Yes'),
	array('Burgundy','Ruhr','No','Yes'),
	array('Burgundy','Holland','No','Yes'),
	array('Burgundy','Belgium','No','Yes'),
	array('Burgundy','Picardy','No','Yes'),
	array('Burgundy','Brest','No','Yes'),
	array('Burgundy','Paris','No','Yes'),
	array('Burgundy','Marseilles','No','Yes'),
	array('Burgundy','Gascony','No','Yes'),
	array('Burgundy','Tyrolia','No','Yes'),
	array('Burgundy','Bohemia','No','Yes'),
	array('Marseilles','Portugal','Yes','Yes'),
	array('Marseilles','Spain','No','Yes'),
	array('Marseilles','Tuscany','Yes','Yes'),
	array('Marseilles','Piedmont','Yes','Yes'),
	array('Marseilles','Venice','No','Yes'),
	array('Marseilles','Munich','No','Yes'),
	array('Marseilles','Ruhr','No','Yes'),
	array('Marseilles','Belgium','No','Yes'),
	array('Marseilles','Picardy','No','Yes'),
	array('Marseilles','Brest','No','Yes'),
	array('Marseilles','Paris','No','Yes'),
	array('Marseilles','Burgundy','No','Yes'),
	array('Marseilles','Gascony','No','Yes'),
	array('Marseilles','Mid-Atlantic Ocean','Yes','No'),
	array('Marseilles','Western Mediterranean','Yes','No'),
	array('Marseilles','Gulf of Lyons','Yes','No'),
	array('Marseilles','Tyrrhenian Sea','Yes','No'),
	array('Marseilles','Tyrolia','No','Yes'),
	array('Marseilles','Spain (South Coast)','Yes','No'),
	array('Gascony','Portugal','Yes','Yes'),
	array('Gascony','Spain','No','Yes'),
	array('Gascony','North Africa','Yes','No'),
	array('Gascony','Piedmont','No','Yes'),
	array('Gascony','Munich','No','Yes'),
	array('Gascony','Ruhr','No','Yes'),
	array('Gascony','Belgium','No','Yes'),
	array('Gascony','Picardy','Yes','Yes'),
	array('Gascony','Brest','Yes','Yes'),
	array('Gascony','Paris','No','Yes'),
	array('Gascony','Burgundy','No','Yes'),
	array('Gascony','Marseilles','No','Yes'),
	array('Gascony','North Atlantic Ocean','Yes','No'),
	array('Gascony','Irish Sea','Yes','No'),
	array('Gascony','English Channel','Yes','No'),
	array('Gascony','Mid-Atlantic Ocean','Yes','No'),
	array('Gascony','Western Mediterranean','Yes','No'),
	array('Gascony','Spain (North Coast)','Yes','No'),
	array('Gascony','Spain (South Coast)','Yes','No'),
	array('Barents Sea','Clyde','Yes','No'),
	array('Barents Sea','Edinburgh','Yes','No'),
	array('Barents Sea','Sweden','Yes','No'),
	array('Barents Sea','Norway','Yes','No'),
	array('Barents Sea','Norwegian Sea','Yes','No'),
	array('Barents Sea','North Sea','Yes','No'),
	array('Barents Sea','Skagerrack','Yes','No'),
	array('Barents Sea','North Atlantic Ocean','Yes','No'),
	array('Barents Sea','St. Petersburg (North Coast)','Yes','No'),
	array('Norwegian Sea','Clyde','Yes','No'),
	array('Norwegian Sea','Edinburgh','Yes','No'),
	array('Norwegian Sea','Liverpool','Yes','No'),
	array('Norwegian Sea','Yorkshire','Yes','No'),
	array('Norwegian Sea','London','Yes','No'),
	array('Norwegian Sea','Sweden','Yes','No'),
	array('Norwegian Sea','Norway','Yes','No'),
	array('Norwegian Sea','Denmark','Yes','No'),
	array('Norwegian Sea','Holland','Yes','No'),
	array('Norwegian Sea','Belgium','Yes','No'),
	array('Norwegian Sea','Barents Sea','Yes','No'),
	array('Norwegian Sea','North Sea','Yes','No'),
	array('Norwegian Sea','Skagerrack','Yes','No'),
	array('Norwegian Sea','Heligoland Bight','Yes','No'),
	array('Norwegian Sea','North Atlantic Ocean','Yes','No'),
	array('Norwegian Sea','Irish Sea','Yes','No'),
	array('Norwegian Sea','English Channel','Yes','No'),
	array('Norwegian Sea','Mid-Atlantic Ocean','Yes','No'),
	array('Norwegian Sea','St. Petersburg (North Coast)','Yes','No'),
	array('North Sea','Clyde','Yes','No'),
	array('North Sea','Edinburgh','Yes','No'),
	array('North Sea','Yorkshire','Yes','No'),
	array('North Sea','Wales','Yes','No'),
	array('North Sea','London','Yes','No'),
	array('North Sea','Sweden','Yes','No'),
	array('North Sea','Norway','Yes','No'),
	array('North Sea','Denmark','Yes','No'),
	array('North Sea','Kiel','Yes','No'),
	array('North Sea','Holland','Yes','No'),
	array('North Sea','Belgium','Yes','No'),
	array('North Sea','Picardy','Yes','No'),
	array('North Sea','Brest','Yes','No'),
	array('North Sea','Barents Sea','Yes','No'),
	array('North Sea','Norwegian Sea','Yes','No'),
	array('North Sea','Skagerrack','Yes','No'),
	array('North Sea','Heligoland Bight','Yes','No'),
	array('North Sea','Baltic Sea','Yes','No'),
	array('North Sea','North Atlantic Ocean','Yes','No'),
	array('North Sea','Irish Sea','Yes','No'),
	array('North Sea','English Channel','Yes','No'),
	array('North Sea','Mid-Atlantic Ocean','Yes','No'),
	array('North Sea','St. Petersburg (North Coast)','Yes','No'),
	array('Skagerrack','Edinburgh','Yes','No'),
	array('Skagerrack','Yorkshire','Yes','No'),
	array('Skagerrack','London','Yes','No'),
	array('Skagerrack','Finland','Yes','No'),
	array('Skagerrack','Sweden','Yes','No'),
	array('Skagerrack','Norway','Yes','No'),
	array('Skagerrack','Denmark','Yes','No'),
	array('Skagerrack','Kiel','Yes','No'),
	array('Skagerrack','Holland','Yes','No'),
	array('Skagerrack','Belgium','Yes','No'),
	array('Skagerrack','Barents Sea','Yes','No'),
	array('Skagerrack','Norwegian Sea','Yes','No'),
	array('Skagerrack','North Sea','Yes','No'),
	array('Skagerrack','Heligoland Bight','Yes','No'),
	array('Skagerrack','Baltic Sea','Yes','No'),
	array('Skagerrack','Gulf of Bothnia','Yes','No'),
	array('Skagerrack','English Channel','Yes','No'),
	array('Skagerrack','St. Petersburg (North Coast)','Yes','No'),
	array('Heligoland Bight','Edinburgh','Yes','No'),
	array('Heligoland Bight','Yorkshire','Yes','No'),
	array('Heligoland Bight','London','Yes','No'),
	array('Heligoland Bight','Sweden','Yes','No'),
	array('Heligoland Bight','Norway','Yes','No'),
	array('Heligoland Bight','Denmark','Yes','No'),
	array('Heligoland Bight','Kiel','Yes','No'),
	array('Heligoland Bight','Berlin','Yes','No'),
	array('Heligoland Bight','Holland','Yes','No'),
	array('Heligoland Bight','Belgium','Yes','No'),
	array('Heligoland Bight','Norwegian Sea','Yes','No'),
	array('Heligoland Bight','North Sea','Yes','No'),
	array('Heligoland Bight','Skagerrack','Yes','No'),
	array('Heligoland Bight','Baltic Sea','Yes','No'),
	array('Heligoland Bight','English Channel','Yes','No'),
	array('Baltic Sea','Livonia','Yes','No'),
	array('Baltic Sea','Finland','Yes','No'),
	array('Baltic Sea','Sweden','Yes','No'),
	array('Baltic Sea','Norway','Yes','No'),
	array('Baltic Sea','Denmark','Yes','No'),
	array('Baltic Sea','Kiel','Yes','No'),
	array('Baltic Sea','Berlin','Yes','No'),
	array('Baltic Sea','Prussia','Yes','No'),
	array('Baltic Sea','Holland','Yes','No'),
	array('Baltic Sea','North Sea','Yes','No'),
	array('Baltic Sea','Skagerrack','Yes','No'),
	array('Baltic Sea','Heligoland Bight','Yes','No'),
	array('Baltic Sea','Gulf of Bothnia','Yes','No'),
	array('Baltic Sea','St. Petersburg (South Coast)','Yes','No'),
	array('Gulf of Bothnia','Livonia','Yes','No'),
	array('Gulf of Bothnia','Finland','Yes','No'),
	array('Gulf of Bothnia','Sweden','Yes','No'),
	array('Gulf of Bothnia','Norway','Yes','No'),
	array('Gulf of Bothnia','Denmark','Yes','No'),
	array('Gulf of Bothnia','Kiel','Yes','No'),
	array('Gulf of Bothnia','Berlin','Yes','No'),
	array('Gulf of Bothnia','Prussia','Yes','No'),
	array('Gulf of Bothnia','Skagerrack','Yes','No'),
	array('Gulf of Bothnia','Baltic Sea','Yes','No'),
	array('Gulf of Bothnia','St. Petersburg (South Coast)','Yes','No'),
	array('North Atlantic Ocean','Clyde','Yes','No'),
	array('North Atlantic Ocean','Edinburgh','Yes','No'),
	array('North Atlantic Ocean','Liverpool','Yes','No'),
	array('North Atlantic Ocean','Wales','Yes','No'),
	array('North Atlantic Ocean','London','Yes','No'),
	array('North Atlantic Ocean','Portugal','Yes','No'),
	array('North Atlantic Ocean','North Africa','Yes','No'),
	array('North Atlantic Ocean','Norway','Yes','No'),
	array('North Atlantic Ocean','Brest','Yes','No'),
	array('North Atlantic Ocean','Gascony','Yes','No'),
	array('North Atlantic Ocean','Barents Sea','Yes','No'),
	array('North Atlantic Ocean','Norwegian Sea','Yes','No'),
	array('North Atlantic Ocean','North Sea','Yes','No'),
	array('North Atlantic Ocean','Irish Sea','Yes','No'),
	array('North Atlantic Ocean','English Channel','Yes','No'),
	array('North Atlantic Ocean','Mid-Atlantic Ocean','Yes','No'),
	array('North Atlantic Ocean','Western Mediterranean','Yes','No'),
	array('North Atlantic Ocean','Spain (North Coast)','Yes','No'),
	array('North Atlantic Ocean','Spain (South Coast)','Yes','No'),
	array('Irish Sea','Clyde','Yes','No'),
	array('Irish Sea','Liverpool','Yes','No'),
	array('Irish Sea','Wales','Yes','No'),
	array('Irish Sea','London','Yes','No'),
	array('Irish Sea','Portugal','Yes','No'),
	array('Irish Sea','North Africa','Yes','No'),
	array('Irish Sea','Belgium','Yes','No'),
	array('Irish Sea','Picardy','Yes','No'),
	array('Irish Sea','Brest','Yes','No'),
	array('Irish Sea','Gascony','Yes','No'),
	array('Irish Sea','Norwegian Sea','Yes','No'),
	array('Irish Sea','North Sea','Yes','No'),
	array('Irish Sea','North Atlantic Ocean','Yes','No'),
	array('Irish Sea','English Channel','Yes','No'),
	array('Irish Sea','Mid-Atlantic Ocean','Yes','No'),
	array('Irish Sea','Western Mediterranean','Yes','No'),
	array('Irish Sea','Spain (North Coast)','Yes','No'),
	array('Irish Sea','Spain (South Coast)','Yes','No'),
	array('English Channel','Edinburgh','Yes','No'),
	array('English Channel','Liverpool','Yes','No'),
	array('English Channel','Yorkshire','Yes','No'),
	array('English Channel','Wales','Yes','No'),
	array('English Channel','London','Yes','No'),
	array('English Channel','Portugal','Yes','No'),
	array('English Channel','North Africa','Yes','No'),
	array('English Channel','Norway','Yes','No'),
	array('English Channel','Denmark','Yes','No'),
	array('English Channel','Holland','Yes','No'),
	array('English Channel','Belgium','Yes','No'),
	array('English Channel','Picardy','Yes','No'),
	array('English Channel','Brest','Yes','No'),
	array('English Channel','Gascony','Yes','No'),
	array('English Channel','Norwegian Sea','Yes','No'),
	array('English Channel','North Sea','Yes','No'),
	array('English Channel','Skagerrack','Yes','No'),
	array('English Channel','Heligoland Bight','Yes','No'),
	array('English Channel','North Atlantic Ocean','Yes','No'),
	array('English Channel','Irish Sea','Yes','No'),
	array('English Channel','Mid-Atlantic Ocean','Yes','No'),
	array('English Channel','Western Mediterranean','Yes','No'),
	array('English Channel','Spain (North Coast)','Yes','No'),
	array('English Channel','Spain (South Coast)','Yes','No'),
	array('Mid-Atlantic Ocean','Clyde','Yes','No'),
	array('Mid-Atlantic Ocean','Liverpool','Yes','No'),
	array('Mid-Atlantic Ocean','Wales','Yes','No'),
	array('Mid-Atlantic Ocean','London','Yes','No'),
	array('Mid-Atlantic Ocean','Portugal','Yes','No'),
	array('Mid-Atlantic Ocean','North Africa','Yes','No'),
	array('Mid-Atlantic Ocean','Tunis','Yes','No'),
	array('Mid-Atlantic Ocean','Belgium','Yes','No'),
	array('Mid-Atlantic Ocean','Picardy','Yes','No'),
	array('Mid-Atlantic Ocean','Brest','Yes','No'),
	array('Mid-Atlantic Ocean','Marseilles','Yes','No'),
	array('Mid-Atlantic Ocean','Gascony','Yes','No'),
	array('Mid-Atlantic Ocean','Norwegian Sea','Yes','No'),
	array('Mid-Atlantic Ocean','North Sea','Yes','No'),
	array('Mid-Atlantic Ocean','North Atlantic Ocean','Yes','No'),
	array('Mid-Atlantic Ocean','Irish Sea','Yes','No'),
	array('Mid-Atlantic Ocean','English Channel','Yes','No'),
	array('Mid-Atlantic Ocean','Western Mediterranean','Yes','No'),
	array('Mid-Atlantic Ocean','Gulf of Lyons','Yes','No'),
	array('Mid-Atlantic Ocean','Tyrrhenian Sea','Yes','No'),
	array('Mid-Atlantic Ocean','Spain (North Coast)','Yes','No'),
	array('Mid-Atlantic Ocean','Spain (South Coast)','Yes','No'),
	array('Western Mediterranean','Portugal','Yes','No'),
	array('Western Mediterranean','North Africa','Yes','No'),
	array('Western Mediterranean','Tunis','Yes','No'),
	array('Western Mediterranean','Naples','Yes','No'),
	array('Western Mediterranean','Rome','Yes','No'),
	array('Western Mediterranean','Tuscany','Yes','No'),
	array('Western Mediterranean','Piedmont','Yes','No'),
	array('Western Mediterranean','Brest','Yes','No'),
	array('Western Mediterranean','Marseilles','Yes','No'),
	array('Western Mediterranean','Gascony','Yes','No'),
	array('Western Mediterranean','North Atlantic Ocean','Yes','No'),
	array('Western Mediterranean','Irish Sea','Yes','No'),
	array('Western Mediterranean','English Channel','Yes','No'),
	array('Western Mediterranean','Mid-Atlantic Ocean','Yes','No'),
	array('Western Mediterranean','Gulf of Lyons','Yes','No'),
	array('Western Mediterranean','Tyrrhenian Sea','Yes','No'),
	array('Western Mediterranean','Ionian Sea','Yes','No'),
	array('Western Mediterranean','Spain (North Coast)','Yes','No'),
	array('Western Mediterranean','Spain (South Coast)','Yes','No'),
	array('Gulf of Lyons','Portugal','Yes','No'),
	array('Gulf of Lyons','North Africa','Yes','No'),
	array('Gulf of Lyons','Tunis','Yes','No'),
	array('Gulf of Lyons','Naples','Yes','No'),
	array('Gulf of Lyons','Rome','Yes','No'),
	array('Gulf of Lyons','Tuscany','Yes','No'),
	array('Gulf of Lyons','Piedmont','Yes','No'),
	array('Gulf of Lyons','Marseilles','Yes','No'),
	array('Gulf of Lyons','Mid-Atlantic Ocean','Yes','No'),
	array('Gulf of Lyons','Western Mediterranean','Yes','No'),
	array('Gulf of Lyons','Tyrrhenian Sea','Yes','No'),
	array('Gulf of Lyons','Ionian Sea','Yes','No'),
	array('Gulf of Lyons','Spain (South Coast)','Yes','No'),
	array('Tyrrhenian Sea','North Africa','Yes','No'),
	array('Tyrrhenian Sea','Tunis','Yes','No'),
	array('Tyrrhenian Sea','Naples','Yes','No'),
	array('Tyrrhenian Sea','Rome','Yes','No'),
	array('Tyrrhenian Sea','Tuscany','Yes','No'),
	array('Tyrrhenian Sea','Piedmont','Yes','No'),
	array('Tyrrhenian Sea','Apulia','Yes','No'),
	array('Tyrrhenian Sea','Greece','Yes','No'),
	array('Tyrrhenian Sea','Albania','Yes','No'),
	array('Tyrrhenian Sea','Marseilles','Yes','No'),
	array('Tyrrhenian Sea','Mid-Atlantic Ocean','Yes','No'),
	array('Tyrrhenian Sea','Western Mediterranean','Yes','No'),
	array('Tyrrhenian Sea','Gulf of Lyons','Yes','No'),
	array('Tyrrhenian Sea','Ionian Sea','Yes','No'),
	array('Tyrrhenian Sea','Adriatic Sea','Yes','No'),
	array('Tyrrhenian Sea','Aegean Sea','Yes','No'),
	array('Tyrrhenian Sea','Eastern Mediterranean','Yes','No'),
	array('Tyrrhenian Sea','Spain (South Coast)','Yes','No'),
	array('Ionian Sea','North Africa','Yes','No'),
	array('Ionian Sea','Tunis','Yes','No'),
	array('Ionian Sea','Naples','Yes','No'),
	array('Ionian Sea','Rome','Yes','No'),
	array('Ionian Sea','Tuscany','Yes','No'),
	array('Ionian Sea','Venice','Yes','No'),
	array('Ionian Sea','Apulia','Yes','No'),
	array('Ionian Sea','Greece','Yes','No'),
	array('Ionian Sea','Albania','Yes','No'),
	array('Ionian Sea','Constantinople','Yes','No'),
	array('Ionian Sea','Smyrna','Yes','No'),
	array('Ionian Sea','Syria','Yes','No'),
	array('Ionian Sea','Western Mediterranean','Yes','No'),
	array('Ionian Sea','Gulf of Lyons','Yes','No'),
	array('Ionian Sea','Tyrrhenian Sea','Yes','No'),
	array('Ionian Sea','Adriatic Sea','Yes','No'),
	array('Ionian Sea','Aegean Sea','Yes','No'),
	array('Ionian Sea','Eastern Mediterranean','Yes','No'),
	array('Ionian Sea','Trieste','Yes','No'),
	array('Ionian Sea','Bulgaria (South Coast)','Yes','No'),
	array('Adriatic Sea','Tunis','Yes','No'),
	array('Adriatic Sea','Naples','Yes','No'),
	array('Adriatic Sea','Venice','Yes','No'),
	array('Adriatic Sea','Apulia','Yes','No'),
	array('Adriatic Sea','Greece','Yes','No'),
	array('Adriatic Sea','Albania','Yes','No'),
	array('Adriatic Sea','Tyrrhenian Sea','Yes','No'),
	array('Adriatic Sea','Ionian Sea','Yes','No'),
	array('Adriatic Sea','Aegean Sea','Yes','No'),
	array('Adriatic Sea','Eastern Mediterranean','Yes','No'),
	array('Adriatic Sea','Trieste','Yes','No'),
	array('Aegean Sea','Tunis','Yes','No'),
	array('Aegean Sea','Naples','Yes','No'),
	array('Aegean Sea','Apulia','Yes','No'),
	array('Aegean Sea','Greece','Yes','No'),
	array('Aegean Sea','Albania','Yes','No'),
	array('Aegean Sea','Constantinople','Yes','No'),
	array('Aegean Sea','Smyrna','Yes','No'),
	array('Aegean Sea','Ankara','Yes','No'),
	array('Aegean Sea','Syria','Yes','No'),
	array('Aegean Sea','Tyrrhenian Sea','Yes','No'),
	array('Aegean Sea','Ionian Sea','Yes','No'),
	array('Aegean Sea','Adriatic Sea','Yes','No'),
	array('Aegean Sea','Eastern Mediterranean','Yes','No'),
	array('Aegean Sea','Black Sea','Yes','No'),
	array('Aegean Sea','Bulgaria (North Coast)','Yes','No'),
	array('Aegean Sea','Bulgaria (South Coast)','Yes','No'),
	array('Eastern Mediterranean','Tunis','Yes','No'),
	array('Eastern Mediterranean','Naples','Yes','No'),
	array('Eastern Mediterranean','Apulia','Yes','No'),
	array('Eastern Mediterranean','Greece','Yes','No'),
	array('Eastern Mediterranean','Albania','Yes','No'),
	array('Eastern Mediterranean','Constantinople','Yes','No'),
	array('Eastern Mediterranean','Smyrna','Yes','No'),
	array('Eastern Mediterranean','Syria','Yes','No'),
	array('Eastern Mediterranean','Tyrrhenian Sea','Yes','No'),
	array('Eastern Mediterranean','Ionian Sea','Yes','No'),
	array('Eastern Mediterranean','Adriatic Sea','Yes','No'),
	array('Eastern Mediterranean','Aegean Sea','Yes','No'),
	array('Eastern Mediterranean','Bulgaria (South Coast)','Yes','No'),
	array('Black Sea','Rumania','Yes','No'),
	array('Black Sea','Constantinople','Yes','No'),
	array('Black Sea','Smyrna','Yes','No'),
	array('Black Sea','Ankara','Yes','No'),
	array('Black Sea','Armenia','Yes','No'),
	array('Black Sea','Sevastopol','Yes','No'),
	array('Black Sea','Aegean Sea','Yes','No'),
	array('Black Sea','Bulgaria (North Coast)','Yes','No'),
	array('Black Sea','Bulgaria (South Coast)','Yes','No'),
	array('Tyrolia','Rome','No','Yes'),
	array('Tyrolia','Tuscany','No','Yes'),
	array('Tyrolia','Piedmont','No','Yes'),
	array('Tyrolia','Venice','No','Yes'),
	array('Tyrolia','Albania','No','Yes'),
	array('Tyrolia','Serbia','No','Yes'),
	array('Tyrolia','Kiel','No','Yes'),
	array('Tyrolia','Berlin','No','Yes'),
	array('Tyrolia','Silesia','No','Yes'),
	array('Tyrolia','Munich','No','Yes'),
	array('Tyrolia','Ruhr','No','Yes'),
	array('Tyrolia','Burgundy','No','Yes'),
	array('Tyrolia','Marseilles','No','Yes'),
	array('Tyrolia','Bohemia','No','Yes'),
	array('Tyrolia','Vienna','No','Yes'),
	array('Tyrolia','Trieste','No','Yes'),
	array('Tyrolia','Budapest','No','Yes'),
	array('Tyrolia','Galicia','No','Yes'),
	array('Bohemia','Piedmont','No','Yes'),
	array('Bohemia','Venice','No','Yes'),
	array('Bohemia','Rumania','No','Yes'),
	array('Bohemia','Ukraine','No','Yes'),
	array('Bohemia','Warsaw','No','Yes'),
	array('Bohemia','Kiel','No','Yes'),
	array('Bohemia','Berlin','No','Yes'),
	array('Bohemia','Prussia','No','Yes'),
	array('Bohemia','Silesia','No','Yes'),
	array('Bohemia','Munich','No','Yes'),
	array('Bohemia','Ruhr','No','Yes'),
	array('Bohemia','Burgundy','No','Yes'),
	array('Bohemia','Tyrolia','No','Yes'),
	array('Bohemia','Vienna','No','Yes'),
	array('Bohemia','Trieste','No','Yes'),
	array('Bohemia','Budapest','No','Yes'),
	array('Bohemia','Galicia','No','Yes'),
	array('Vienna','Piedmont','No','Yes'),
	array('Vienna','Venice','No','Yes'),
	array('Vienna','Albania','No','Yes'),
	array('Vienna','Serbia','No','Yes'),
	array('Vienna','Rumania','No','Yes'),
	array('Vienna','Ukraine','No','Yes'),
	array('Vienna','Warsaw','No','Yes'),
	array('Vienna','Silesia','No','Yes'),
	array('Vienna','Munich','No','Yes'),
	array('Vienna','Tyrolia','No','Yes'),
	array('Vienna','Bohemia','No','Yes'),
	array('Vienna','Trieste','No','Yes'),
	array('Vienna','Budapest','No','Yes'),
	array('Vienna','Galicia','No','Yes'),
	array('Trieste','Rome','No','Yes'),
	array('Trieste','Tuscany','No','Yes'),
	array('Trieste','Piedmont','No','Yes'),
	array('Trieste','Venice','Yes','Yes'),
	array('Trieste','Apulia','Yes','Yes'),
	array('Trieste','Greece','Yes','Yes'),
	array('Trieste','Albania','Yes','Yes'),
	array('Trieste','Serbia','No','Yes'),
	array('Trieste','Bulgaria','No','Yes'),
	array('Trieste','Rumania','No','Yes'),
	array('Trieste','Munich','No','Yes'),
	array('Trieste','Ionian Sea','Yes','No'),
	array('Trieste','Adriatic Sea','Yes','No'),
	array('Trieste','Tyrolia','No','Yes'),
	array('Trieste','Bohemia','No','Yes'),
	array('Trieste','Vienna','No','Yes'),
	array('Trieste','Budapest','No','Yes'),
	array('Trieste','Galicia','No','Yes'),
	array('Budapest','Venice','No','Yes'),
	array('Budapest','Greece','No','Yes'),
	array('Budapest','Albania','No','Yes'),
	array('Budapest','Serbia','No','Yes'),
	array('Budapest','Bulgaria','No','Yes'),
	array('Budapest','Rumania','No','Yes'),
	array('Budapest','Sevastopol','No','Yes'),
	array('Budapest','Ukraine','No','Yes'),
	array('Budapest','Warsaw','No','Yes'),
	array('Budapest','Silesia','No','Yes'),
	array('Budapest','Tyrolia','No','Yes'),
	array('Budapest','Bohemia','No','Yes'),
	array('Budapest','Vienna','No','Yes'),
	array('Budapest','Trieste','No','Yes'),
	array('Budapest','Galicia','No','Yes'),
	array('Galicia','Serbia','No','Yes'),
	array('Galicia','Bulgaria','No','Yes'),
	array('Galicia','Rumania','No','Yes'),
	array('Galicia','Sevastopol','No','Yes'),
	array('Galicia','Ukraine','No','Yes'),
	array('Galicia','Warsaw','No','Yes'),
	array('Galicia','Livonia','No','Yes'),
	array('Galicia','Moscow','No','Yes'),
	array('Galicia','Berlin','No','Yes'),
	array('Galicia','Prussia','No','Yes'),
	array('Galicia','Silesia','No','Yes'),
	array('Galicia','Munich','No','Yes'),
	array('Galicia','Tyrolia','No','Yes'),
	array('Galicia','Bohemia','No','Yes'),
	array('Galicia','Vienna','No','Yes'),
	array('Galicia','Trieste','No','Yes'),
	array('Galicia','Budapest','No','Yes'),
	array('Spain (North Coast)','Portugal','Yes','No'),
	array('Spain (North Coast)','North Africa','Yes','No'),
	array('Spain (North Coast)','Brest','Yes','No'),
	array('Spain (North Coast)','Gascony','Yes','No'),
	array('Spain (North Coast)','North Atlantic Ocean','Yes','No'),
	array('Spain (North Coast)','Irish Sea','Yes','No'),
	array('Spain (North Coast)','English Channel','Yes','No'),
	array('Spain (North Coast)','Mid-Atlantic Ocean','Yes','No'),
	array('Spain (North Coast)','Western Mediterranean','Yes','No'),
	array('Spain (North Coast)','Spain (South Coast)','Yes','No'),
	array('Spain (South Coast)','Portugal','Yes','No'),
	array('Spain (South Coast)','North Africa','Yes','No'),
	array('Spain (South Coast)','Tunis','Yes','No'),
	array('Spain (South Coast)','Tuscany','Yes','No'),
	array('Spain (South Coast)','Piedmont','Yes','No'),
	array('Spain (South Coast)','Brest','Yes','No'),
	array('Spain (South Coast)','Marseilles','Yes','No'),
	array('Spain (South Coast)','Gascony','Yes','No'),
	array('Spain (South Coast)','North Atlantic Ocean','Yes','No'),
	array('Spain (South Coast)','Irish Sea','Yes','No'),
	array('Spain (South Coast)','English Channel','Yes','No'),
	array('Spain (South Coast)','Mid-Atlantic Ocean','Yes','No'),
	array('Spain (South Coast)','Western Mediterranean','Yes','No'),
	array('Spain (South Coast)','Gulf of Lyons','Yes','No'),
	array('Spain (South Coast)','Tyrrhenian Sea','Yes','No'),
	array('Spain (South Coast)','Spain (North Coast)','Yes','No'),
	array('St. Petersburg (North Coast)','Sweden','Yes','No'),
	array('St. Petersburg (North Coast)','Norway','Yes','No'),
	array('St. Petersburg (North Coast)','Barents Sea','Yes','No'),
	array('St. Petersburg (North Coast)','Norwegian Sea','Yes','No'),
	array('St. Petersburg (North Coast)','North Sea','Yes','No'),
	array('St. Petersburg (North Coast)','Skagerrack','Yes','No'),
	array('St. Petersburg (South Coast)','Livonia','Yes','No'),
	array('St. Petersburg (South Coast)','Finland','Yes','No'),
	array('St. Petersburg (South Coast)','Sweden','Yes','No'),
	array('St. Petersburg (South Coast)','Prussia','Yes','No'),
	array('St. Petersburg (South Coast)','Baltic Sea','Yes','No'),
	array('St. Petersburg (South Coast)','Gulf of Bothnia','Yes','No'),
	array('Bulgaria (North Coast)','Rumania','Yes','No'),
	array('Bulgaria (North Coast)','Constantinople','Yes','No'),
	array('Bulgaria (North Coast)','Smyrna','Yes','No'),
	array('Bulgaria (North Coast)','Ankara','Yes','No'),
	array('Bulgaria (North Coast)','Armenia','Yes','No'),
	array('Bulgaria (North Coast)','Sevastopol','Yes','No'),
	array('Bulgaria (North Coast)','Aegean Sea','Yes','No'),
	array('Bulgaria (North Coast)','Black Sea','Yes','No'),
	array('Bulgaria (North Coast)','Bulgaria (South Coast)','Yes','No'),
	array('Bulgaria (South Coast)','Greece','Yes','No'),
	array('Bulgaria (South Coast)','Albania','Yes','No'),
	array('Bulgaria (South Coast)','Constantinople','Yes','No'),
	array('Bulgaria (South Coast)','Smyrna','Yes','No'),
	array('Bulgaria (South Coast)','Ankara','Yes','No'),
	array('Bulgaria (South Coast)','Ionian Sea','Yes','No'),
	array('Bulgaria (South Coast)','Aegean Sea','Yes','No'),
	array('Bulgaria (South Coast)','Eastern Mediterranean','Yes','No'),
	array('Bulgaria (South Coast)','Black Sea','Yes','No'),
	array('Bulgaria (South Coast)','Bulgaria (North Coast)','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
