<?php
// This is file installs the map data for the USofA variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Clyde', 'Coast', 'No', 1, 493, 267, 264, 143),
	array('Edinburgh', 'Coast', 'Yes', 1, 519, 248, 278, 133),
	array('Liverpool', 'Coast', 'Yes', 1, 495, 291, 265, 156),
	array('Yorkshire', 'Coast', 'No', 1, 534, 317, 286, 170),
	array('Wales', 'Coast', 'No', 1, 465, 379, 249, 203),
	array('London', 'Coast', 'Yes', 1, 547, 357, 293, 191),
	array('Portugal', 'Coast', 'Yes', 0, 332, 611, 178, 327),
	array('Spain', 'Coast', 'Yes', 0, 407, 575, 218, 308),
	array('North Africa', 'Coast', 'No', 0, 343, 721, 184, 386),
	array('Tunis', 'Coast', 'Yes', 0, 594, 719, 318, 385),
	array('Naples', 'Coast', 'Yes', 3, 693, 708, 371, 379),
	array('Rome', 'Coast', 'Yes', 3, 670, 642, 359, 344),
	array('Tuscany', 'Coast', 'No', 3, 635, 583, 340, 312),
	array('Piedmont', 'Coast', 'No', 3, 601, 558, 322, 299),
	array('Venice', 'Coast', 'Yes', 3, 659, 571, 353, 306),
	array('Apulia', 'Coast', 'No', 3, 721, 655, 386, 351),
	array('Greece', 'Coast', 'Yes', 0, 816, 710, 437, 380),
	array('Asia', 'Coast', 'No', 0, 1253, 670, 671, 359),
	array('Serbia', 'Land', 'Yes', 0, 805, 624, 431, 334),
	array('Bulgaria', 'Coast', 'Yes', 0, 859, 590, 460, 316),
	array('Rumania', 'Coast', 'Yes', 0, 883, 519, 473, 278),
	array('Constantinople', 'Coast', 'Yes', 6, 917, 644, 491, 345),
	array('Smyrna', 'Coast', 'Yes', 6, 909, 697, 487, 373),
	array('Ankara', 'Coast', 'Yes', 6, 1012, 594, 542, 318),
	array('Armenia', 'Coast', 'No', 6, 1114, 637, 597, 341),
	array('Syria', 'Coast', 'No', 6, 1083, 691, 580, 370),
	array('Sevastopol', 'Coast', 'Yes', 7, 982, 497, 526, 266),
	array('Ukraine', 'Land', 'No', 7, 861, 444, 461, 238),
	array('Warsaw', 'Land', 'Yes', 7, 818, 416, 438, 223),
	array('Livonia', 'Coast', 'No', 7, 829, 370, 444, 198),
	array('Moscow', 'Land', 'Yes', 7, 920, 364, 493, 195),
	array('St. Petersburg', 'Coast', 'Yes', 7, 986, 189, 528, 101),
	array('Finland', 'Coast', 'No', 7, 814, 183, 436, 98),
	array('Sweden', 'Coast', 'Yes', 0, 735, 269, 394, 144),
	array('Norway', 'Coast', 'Yes', 0, 648, 218, 347, 117),
	array('Denmark', 'Coast', 'Yes', 0, 691, 344, 370, 184),
	array('Kiel', 'Coast', 'Yes', 4, 651, 407, 349, 218),
	array('Berlin', 'Coast', 'Yes', 4, 706, 390, 378, 209),
	array('Prussia', 'Coast', 'No', 4, 747, 415, 400, 222),
	array('Silesia', 'Land', 'No', 4, 707, 435, 379, 233),
	array('Munich', 'Land', 'Yes', 4, 646, 456, 346, 244),
	array('Ruhr', 'Land', 'No', 4, 603, 443, 323, 237),
	array('Holland', 'Coast', 'Yes', 0, 592, 379, 317, 203),
	array('Belgium', 'Coast', 'Yes', 0, 566, 402, 303, 215),
	array('Picardy', 'Coast', 'No', 2, 528, 418, 283, 224),
	array('Brest', 'Coast', 'Yes', 2, 480, 472, 257, 253),
	array('Paris', 'Land', 'Yes', 2, 549, 458, 294, 245),
	array('Burgundy', 'Land', 'No', 2, 575, 474, 308, 254),
	array('Marseilles', 'Coast', 'Yes', 2, 554, 534, 297, 286),
	array('Gascony', 'Coast', 'No', 2, 467, 545, 250, 292),
	array('Barents Sea', 'Sea', 'No', 0, 917, 90, 491, 48),
	array('Norwegian Sea', 'Sea', 'No', 0, 622, 144, 333, 77),
	array('North Sea', 'Sea', 'No', 0, 579, 334, 310, 179),
	array('Skagerrack', 'Sea', 'No', 0, 679, 299, 364, 160),
	array('Heligoland Bight', 'Sea', 'No', 0, 612, 351, 328, 188),
	array('Baltic Sea', 'Sea', 'No', 0, 734, 359, 393, 192),
	array('Gulf of Bothnia', 'Sea', 'No', 0, 773, 267, 414, 143),
	array('North Atlantic Ocean', 'Sea', 'No', 0, 386, 280, 207, 150),
	array('Irish Sea', 'Sea', 'No', 0, 433, 359, 232, 192),
	array('English Channel', 'Sea', 'No', 0, 467, 407, 250, 218),
	array('Mid-Atlantic Ocean', 'Sea', 'No', 0, 327, 508, 175, 272),
	array('Western Mediterranean', 'Sea', 'No', 0, 429, 687, 230, 368),
	array('Gulf of Lyons', 'Sea', 'No', 0, 569, 599, 305, 321),
	array('Tyrrhenian Sea', 'Sea', 'No', 0, 650, 684, 348, 366),
	array('Ionian Sea', 'Sea', 'No', 0, 756, 700, 405, 375),
	array('Adriatic Sea', 'Sea', 'No', 0, 747, 633, 400, 339),
	array('Aegean Sea', 'Sea', 'No', 0, 864, 682, 463, 365),
	array('Eastern Mediterranean', 'Sea', 'No', 0, 1029, 734, 551, 393),
	array('Black Sea', 'Sea', 'No', 0, 941, 585, 504, 313),
	array('Tyrolia', 'Land', 'No', 5, 687, 499, 368, 267),
	array('Bohemia', 'Land', 'No', 5, 711, 456, 381, 244),
	array('Vienna', 'Land', 'Yes', 5, 743, 486, 398, 260),
	array('Trieste', 'Coast', 'Yes', 5, 745, 596, 399, 319),
	array('Budapest', 'Land', 'Yes', 5, 782, 506, 419, 271),
	array('Galicia', 'Land', 'No', 5, 844, 487, 452, 261),
	array('Spain (North Coast)', 'Coast', 'No', 0, 407, 542, 218, 290),
	array('Spain (South Coast)', 'Coast', 'No', 0, 441, 641, 236, 343),
	array('St. Petersburg (North Coast)', 'Coast', 'No', 7, 945, 138, 506, 74),
	array('St. Petersburg (South Coast)', 'Coast', 'No', 7, 853, 289, 457, 155),
	array('Bulgaria (East Coast)', 'Coast', 'No', 0, 894, 594, 479, 318),
	array('Bulgaria (South Coast)', 'Coast', 'No', 0, 862, 631, 462, 338),
	array('Canada', 'Coast', 'Yes', 0, 133, 360, 71, 193),
	array('Arctic Ocean', 'Sea', 'No', 0, 730, 30, 391, 16),
	array('Pacific Ocean', 'Sea', 'No', 0, 1372, 514, 735, 275),
	array('Indian Ocean', 'Sea', 'No', 0, 1299, 732, 696, 392),
	array('Siberia', 'Coast', 'No', 7, 1253, 220, 671, 118),
	array('Albania', 'Coast', 'No', 0, 780, 652, 418, 349),
	array('Middle America', 'Land', 'No', 8, 149, 543, 80, 291),
	array('San Francisco', 'Coast', 'Yes', 8, 84, 431, 45, 231),
	array('New York City', 'Coast', 'Yes', 8, 202, 415, 108, 222),
	array('Washington', 'Coast', 'Yes', 8, 202, 588, 108, 315),
	array('West Atlantic Ocean', 'Sea', 'No', 0, 299, 176, 160, 94),
	array('South Atlantic Ocean', 'Sea', 'No', 0, 259, 646, 139, 346)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Clyde','Edinburgh','Yes','Yes'),
	array('Clyde','Liverpool','Yes','Yes'),
	array('Clyde','Norwegian Sea','Yes','No'),
	array('Clyde','North Atlantic Ocean','Yes','No'),
	array('Edinburgh','Liverpool','Yes','Yes'),
	array('Edinburgh','Yorkshire','Yes','Yes'),
	array('Edinburgh','Norwegian Sea','Yes','No'),
	array('Edinburgh','North Sea','Yes','No'),
	array('Liverpool','Yorkshire','No','Yes'),
	array('Liverpool','Wales','Yes','Yes'),
	array('Liverpool','North Atlantic Ocean','Yes','No'),
	array('Liverpool','Irish Sea','Yes','No'),
	array('Yorkshire','Wales','No','Yes'),
	array('Yorkshire','London','Yes','Yes'),
	array('Yorkshire','North Sea','Yes','No'),
	array('Wales','London','Yes','Yes'),
	array('Wales','Irish Sea','Yes','No'),
	array('Wales','English Channel','Yes','No'),
	array('London','North Sea','Yes','No'),
	array('London','English Channel','Yes','No'),
	array('Portugal','Spain','No','Yes'),
	array('Portugal','Mid-Atlantic Ocean','Yes','No'),
	array('Portugal','Spain (North Coast)','Yes','No'),
	array('Portugal','Spain (South Coast)','Yes','No'),
	array('Spain','Marseilles','No','Yes'),
	array('Spain','Gascony','No','Yes'),
	array('North Africa','Tunis','Yes','Yes'),
	array('North Africa','Mid-Atlantic Ocean','Yes','No'),
	array('North Africa','Western Mediterranean','Yes','No'),
	array('North Africa','South Atlantic Ocean','Yes','No'),
	array('Tunis','Western Mediterranean','Yes','No'),
	array('Tunis','Tyrrhenian Sea','Yes','No'),
	array('Tunis','Ionian Sea','Yes','No'),
	array('Naples','Rome','Yes','Yes'),
	array('Naples','Apulia','Yes','Yes'),
	array('Naples','Tyrrhenian Sea','Yes','No'),
	array('Naples','Ionian Sea','Yes','No'),
	array('Rome','Tuscany','Yes','Yes'),
	array('Rome','Venice','No','Yes'),
	array('Rome','Apulia','No','Yes'),
	array('Rome','Tyrrhenian Sea','Yes','No'),
	array('Tuscany','Piedmont','Yes','Yes'),
	array('Tuscany','Venice','No','Yes'),
	array('Tuscany','Gulf of Lyons','Yes','No'),
	array('Tuscany','Tyrrhenian Sea','Yes','No'),
	array('Piedmont','Venice','No','Yes'),
	array('Piedmont','Marseilles','Yes','Yes'),
	array('Piedmont','Gulf of Lyons','Yes','No'),
	array('Piedmont','Tyrolia','No','Yes'),
	array('Venice','Apulia','Yes','Yes'),
	array('Venice','Adriatic Sea','Yes','No'),
	array('Venice','Tyrolia','No','Yes'),
	array('Venice','Trieste','Yes','Yes'),
	array('Apulia','Ionian Sea','Yes','No'),
	array('Apulia','Adriatic Sea','Yes','No'),
	array('Greece','Serbia','No','Yes'),
	array('Greece','Bulgaria','No','Yes'),
	array('Greece','Ionian Sea','Yes','No'),
	array('Greece','Aegean Sea','Yes','No'),
	array('Greece','Bulgaria (South Coast)','Yes','No'),
	array('Greece','Albania','Yes','Yes'),
	array('Asia','Armenia','No','Yes'),
	array('Asia','Syria','Yes','Yes'),
	array('Asia','Sevastopol','No','Yes'),
	array('Asia','Pacific Ocean','Yes','No'),
	array('Asia','Indian Ocean','Yes','No'),
	array('Asia','Siberia','Yes','Yes'),
	array('Serbia','Bulgaria','No','Yes'),
	array('Serbia','Rumania','No','Yes'),
	array('Serbia','Trieste','No','Yes'),
	array('Serbia','Budapest','No','Yes'),
	array('Serbia','Albania','No','Yes'),
	array('Bulgaria','Rumania','No','Yes'),
	array('Bulgaria','Constantinople','No','Yes'),
	array('Rumania','Sevastopol','Yes','Yes'),
	array('Rumania','Ukraine','No','Yes'),
	array('Rumania','Black Sea','Yes','No'),
	array('Rumania','Budapest','No','Yes'),
	array('Rumania','Galicia','No','Yes'),
	array('Rumania','Bulgaria (East Coast)','Yes','No'),
	array('Constantinople','Smyrna','Yes','Yes'),
	array('Constantinople','Ankara','Yes','Yes'),
	array('Constantinople','Aegean Sea','Yes','No'),
	array('Constantinople','Black Sea','Yes','No'),
	array('Constantinople','Bulgaria (East Coast)','Yes','No'),
	array('Constantinople','Bulgaria (South Coast)','Yes','No'),
	array('Smyrna','Ankara','No','Yes'),
	array('Smyrna','Armenia','No','Yes'),
	array('Smyrna','Syria','Yes','Yes'),
	array('Smyrna','Aegean Sea','Yes','No'),
	array('Smyrna','Eastern Mediterranean','Yes','No'),
	array('Ankara','Armenia','Yes','Yes'),
	array('Ankara','Black Sea','Yes','No'),
	array('Armenia','Syria','No','Yes'),
	array('Armenia','Sevastopol','Yes','Yes'),
	array('Armenia','Black Sea','Yes','No'),
	array('Syria','Eastern Mediterranean','Yes','No'),
	array('Syria','Indian Ocean','Yes','No'),
	array('Sevastopol','Ukraine','No','Yes'),
	array('Sevastopol','Moscow','No','Yes'),
	array('Sevastopol','Black Sea','Yes','No'),
	array('Sevastopol','Siberia','No','Yes'),
	array('Ukraine','Warsaw','No','Yes'),
	array('Ukraine','Moscow','No','Yes'),
	array('Ukraine','Galicia','No','Yes'),
	array('Warsaw','Livonia','No','Yes'),
	array('Warsaw','Moscow','No','Yes'),
	array('Warsaw','Prussia','No','Yes'),
	array('Warsaw','Silesia','No','Yes'),
	array('Warsaw','Galicia','No','Yes'),
	array('Livonia','Moscow','No','Yes'),
	array('Livonia','St. Petersburg','No','Yes'),
	array('Livonia','Prussia','Yes','Yes'),
	array('Livonia','Baltic Sea','Yes','No'),
	array('Livonia','Gulf of Bothnia','Yes','No'),
	array('Livonia','St. Petersburg (South Coast)','Yes','No'),
	array('Moscow','St. Petersburg','No','Yes'),
	array('Moscow','Siberia','No','Yes'),
	array('St. Petersburg','Finland','No','Yes'),
	array('St. Petersburg','Norway','No','Yes'),
	array('St. Petersburg','Siberia','No','Yes'),
	array('Finland','Sweden','Yes','Yes'),
	array('Finland','Norway','No','Yes'),
	array('Finland','Gulf of Bothnia','Yes','No'),
	array('Finland','St. Petersburg (South Coast)','Yes','No'),
	array('Sweden','Norway','Yes','Yes'),
	array('Sweden','Denmark','Yes','Yes'),
	array('Sweden','Skagerrack','Yes','No'),
	array('Sweden','Baltic Sea','Yes','No'),
	array('Sweden','Gulf of Bothnia','Yes','No'),
	array('Norway','Barents Sea','Yes','No'),
	array('Norway','Norwegian Sea','Yes','No'),
	array('Norway','North Sea','Yes','No'),
	array('Norway','Skagerrack','Yes','No'),
	array('Norway','St. Petersburg (North Coast)','Yes','No'),
	array('Denmark','Kiel','Yes','Yes'),
	array('Denmark','Skagerrack','Yes','No'),
	array('Denmark','Heligoland Bight','Yes','No'),
	array('Denmark','Baltic Sea','Yes','No'),
	array('Kiel','Berlin','Yes','Yes'),
	array('Kiel','Munich','No','Yes'),
	array('Kiel','Ruhr','No','Yes'),
	array('Kiel','Holland','Yes','Yes'),
	array('Kiel','Heligoland Bight','Yes','No'),
	array('Berlin','Prussia','Yes','Yes'),
	array('Berlin','Silesia','No','Yes'),
	array('Berlin','Baltic Sea','Yes','No'),
	array('Prussia','Silesia','No','Yes'),
	array('Prussia','Baltic Sea','Yes','No'),
	array('Silesia','Munich','No','Yes'),
	array('Silesia','Bohemia','No','Yes'),
	array('Silesia','Galicia','No','Yes'),
	array('Munich','Ruhr','No','Yes'),
	array('Munich','Burgundy','No','Yes'),
	array('Munich','Tyrolia','No','Yes'),
	array('Munich','Bohemia','No','Yes'),
	array('Ruhr','Holland','No','Yes'),
	array('Ruhr','Belgium','No','Yes'),
	array('Ruhr','Burgundy','No','Yes'),
	array('Holland','Belgium','Yes','Yes'),
	array('Holland','North Sea','Yes','No'),
	array('Holland','Heligoland Bight','Yes','No'),
	array('Belgium','Picardy','Yes','Yes'),
	array('Belgium','Burgundy','No','Yes'),
	array('Belgium','North Sea','Yes','No'),
	array('Belgium','English Channel','Yes','No'),
	array('Picardy','Brest','Yes','Yes'),
	array('Picardy','Paris','No','Yes'),
	array('Picardy','Burgundy','No','Yes'),
	array('Picardy','English Channel','Yes','No'),
	array('Brest','Paris','No','Yes'),
	array('Brest','Gascony','Yes','Yes'),
	array('Brest','English Channel','Yes','No'),
	array('Brest','Mid-Atlantic Ocean','Yes','No'),
	array('Paris','Burgundy','No','Yes'),
	array('Paris','Gascony','No','Yes'),
	array('Burgundy','Marseilles','No','Yes'),
	array('Burgundy','Gascony','No','Yes'),
	array('Marseilles','Gascony','No','Yes'),
	array('Marseilles','Gulf of Lyons','Yes','No'),
	array('Marseilles','Spain (South Coast)','Yes','No'),
	array('Gascony','Mid-Atlantic Ocean','Yes','No'),
	array('Gascony','Spain (North Coast)','Yes','No'),
	array('Barents Sea','Norwegian Sea','Yes','No'),
	array('Barents Sea','St. Petersburg (North Coast)','Yes','No'),
	array('Barents Sea','Arctic Ocean','Yes','No'),
	array('Norwegian Sea','North Sea','Yes','No'),
	array('Norwegian Sea','North Atlantic Ocean','Yes','No'),
	array('Norwegian Sea','Arctic Ocean','Yes','No'),
	array('Norwegian Sea','West Atlantic Ocean','Yes','No'),
	array('North Sea','Skagerrack','Yes','No'),
	array('North Sea','Heligoland Bight','Yes','No'),
	array('North Sea','English Channel','Yes','No'),
	array('Baltic Sea','Gulf of Bothnia','Yes','No'),
	array('Gulf of Bothnia','St. Petersburg (South Coast)','Yes','No'),
	array('North Atlantic Ocean','Irish Sea','Yes','No'),
	array('North Atlantic Ocean','Mid-Atlantic Ocean','Yes','No'),
	array('North Atlantic Ocean','West Atlantic Ocean','Yes','No'),
	array('Irish Sea','English Channel','Yes','No'),
	array('Irish Sea','Mid-Atlantic Ocean','Yes','No'),
	array('English Channel','Mid-Atlantic Ocean','Yes','No'),
	array('Mid-Atlantic Ocean','Spain (North Coast)','Yes','No'),
	array('Mid-Atlantic Ocean','Spain (South Coast)','Yes','No'),
	array('Mid-Atlantic Ocean','West Atlantic Ocean','Yes','No'),
	array('Mid-Atlantic Ocean','South Atlantic Ocean','Yes','No'),
	array('Western Mediterranean','Gulf of Lyons','Yes','No'),
	array('Western Mediterranean','Tyrrhenian Sea','Yes','No'),
	array('Western Mediterranean','Spain (South Coast)','Yes','No'),
	array('Gulf of Lyons','Tyrrhenian Sea','Yes','No'),
	array('Gulf of Lyons','Spain (South Coast)','Yes','No'),
	array('Tyrrhenian Sea','Ionian Sea','Yes','No'),
	array('Ionian Sea','Adriatic Sea','Yes','No'),
	array('Ionian Sea','Aegean Sea','Yes','No'),
	array('Ionian Sea','Albania','Yes','No'),
	array('Adriatic Sea','Trieste','Yes','No'),
	array('Adriatic Sea','Albania','Yes','No'),
	array('Aegean Sea','Eastern Mediterranean','Yes','No'),
	array('Aegean Sea','Bulgaria (South Coast)','Yes','No'),
	array('Eastern Mediterranean','Indian Ocean','Yes','No'),
	array('Black Sea','Bulgaria (East Coast)','Yes','No'),
	array('Tyrolia','Bohemia','No','Yes'),
	array('Tyrolia','Vienna','No','Yes'),
	array('Tyrolia','Trieste','No','Yes'),
	array('Bohemia','Vienna','No','Yes'),
	array('Bohemia','Galicia','No','Yes'),
	array('Vienna','Trieste','No','Yes'),
	array('Vienna','Budapest','No','Yes'),
	array('Vienna','Galicia','No','Yes'),
	array('Trieste','Budapest','No','Yes'),
	array('Trieste','Albania','Yes','Yes'),
	array('Budapest','Galicia','No','Yes'),
	array('St. Petersburg (North Coast)','Arctic Ocean','Yes','No'),
	array('St. Petersburg (North Coast)','Siberia','Yes','No'),
	array('Canada','Arctic Ocean','Yes','No'),
	array('Canada','Pacific Ocean','Yes','No'),
	array('Canada','Middle America','No','Yes'),
	array('Canada','San Francisco','Yes','Yes'),
	array('Canada','New York City','Yes','Yes'),
	array('Canada','West Atlantic Ocean','Yes','No'),
	array('Arctic Ocean','Pacific Ocean','Yes','No'),
	array('Arctic Ocean','Siberia','Yes','No'),
	array('Arctic Ocean','West Atlantic Ocean','Yes','No'),
	array('Pacific Ocean','Indian Ocean','Yes','No'),
	array('Pacific Ocean','Siberia','Yes','No'),
	array('Pacific Ocean','San Francisco','Yes','No'),
	array('Middle America','San Francisco','No','Yes'),
	array('Middle America','New York City','No','Yes'),
	array('Middle America','Washington','No','Yes'),
	array('New York City','Washington','Yes','Yes'),
	array('New York City','West Atlantic Ocean','Yes','No'),
	array('Washington','West Atlantic Ocean','Yes','No'),
	array('Washington','South Atlantic Ocean','Yes','No'),
	array('West Atlantic Ocean','South Atlantic Ocean','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
