const territories = {
  1: {
    id: "1",
    name: "Clyde",
    type: "Coast",
    supply: "No",
    countryID: "1",
    coast: "No",
    coastParentID: "1",
    smallMapX: "160",
    smallMapY: "109",
    Borders: [
      { id: "2", a: true, f: true },
      { id: "3", a: true, f: true },
      { id: "52", a: false, f: true },
      { id: "58", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "2", a: true, f: true },
      { id: "3", a: true, f: true },
      { id: "52", a: false, f: true },
      { id: "58", a: false, f: true },
    ],
  },
  2: {
    id: "2",
    name: "Edinburgh",
    type: "Coast",
    supply: "Yes",
    countryID: "1",
    coast: "No",
    coastParentID: "2",
    smallMapX: "175",
    smallMapY: "112",
    Borders: [
      { id: "1", a: true, f: true },
      { id: "3", a: true, f: false },
      { id: "4", a: true, f: true },
      { id: "52", a: false, f: true },
      { id: "53", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "1", a: true, f: true },
      { id: "3", a: true, f: false },
      { id: "4", a: true, f: true },
      { id: "52", a: false, f: true },
      { id: "53", a: false, f: true },
    ],
  },
  3: {
    id: "3",
    name: "Liverpool",
    type: "Coast",
    supply: "Yes",
    countryID: "1",
    coast: "No",
    coastParentID: "3",
    smallMapX: "170",
    smallMapY: "144",
    Borders: [
      { id: "1", a: true, f: true },
      { id: "2", a: true, f: false },
      { id: "4", a: true, f: false },
      { id: "5", a: true, f: true },
      { id: "58", a: false, f: true },
      { id: "59", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "1", a: true, f: true },
      { id: "2", a: true, f: false },
      { id: "4", a: true, f: false },
      { id: "5", a: true, f: true },
      { id: "58", a: false, f: true },
      { id: "59", a: false, f: true },
    ],
  },
  4: {
    id: "4",
    name: "Yorkshire",
    type: "Coast",
    supply: "No",
    countryID: "1",
    coast: "No",
    coastParentID: "4",
    smallMapX: "184",
    smallMapY: "150",
    Borders: [
      { id: "2", a: true, f: true },
      { id: "3", a: true, f: false },
      { id: "5", a: true, f: false },
      { id: "6", a: true, f: true },
      { id: "53", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "2", a: true, f: true },
      { id: "3", a: true, f: false },
      { id: "5", a: true, f: false },
      { id: "6", a: true, f: true },
      { id: "53", a: false, f: true },
    ],
  },
  5: {
    id: "5",
    name: "Wales",
    type: "Coast",
    supply: "No",
    countryID: "1",
    coast: "No",
    coastParentID: "5",
    smallMapX: "154",
    smallMapY: "169",
    Borders: [
      { id: "3", a: true, f: true },
      { id: "4", a: true, f: false },
      { id: "6", a: true, f: true },
      { id: "59", a: false, f: true },
      { id: "60", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "3", a: true, f: true },
      { id: "4", a: true, f: false },
      { id: "6", a: true, f: true },
      { id: "59", a: false, f: true },
      { id: "60", a: false, f: true },
    ],
  },
  6: {
    id: "6",
    name: "London",
    type: "Coast",
    supply: "Yes",
    countryID: "1",
    coast: "No",
    coastParentID: "6",
    smallMapX: "186",
    smallMapY: "175",
    Borders: [
      { id: "4", a: true, f: true },
      { id: "5", a: true, f: true },
      { id: "53", a: false, f: true },
      { id: "60", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "4", a: true, f: true },
      { id: "5", a: true, f: true },
      { id: "53", a: false, f: true },
      { id: "60", a: false, f: true },
    ],
  },
  7: {
    id: "7",
    name: "Portugal",
    type: "Coast",
    supply: "Yes",
    countryID: "0",
    coast: "No",
    coastParentID: "7",
    smallMapX: "60",
    smallMapY: "305",
    Borders: [
      { id: "8", a: true, f: true },
      { id: "61", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "8", a: true, f: false },
      { id: "61", a: false, f: true },
      { id: "76", a: false, f: true },
      { id: "77", a: false, f: true },
    ],
  },
  8: {
    id: "8",
    name: "Spain",
    type: "Coast",
    supply: "Yes",
    countryID: "0",
    coast: "Parent",
    coastParentID: "8",
    smallMapX: "100",
    smallMapY: "324",
    Borders: [
      { id: "7", a: true, f: true },
      { id: "49", a: true, f: true },
      { id: "50", a: true, f: true },
      { id: "61", a: false, f: true },
      { id: "62", a: false, f: true },
      { id: "63", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "7", a: true, f: false },
      { id: "49", a: true, f: false },
      { id: "50", a: true, f: false },
    ],
  },
  9: {
    id: "9",
    name: "North Africa",
    type: "Coast",
    supply: "No",
    countryID: "0",
    coast: "No",
    coastParentID: "9",
    smallMapX: "118",
    smallMapY: "386",
    Borders: [
      { id: "10", a: true, f: true },
      { id: "61", a: false, f: true },
      { id: "62", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "10", a: true, f: true },
      { id: "61", a: false, f: true },
      { id: "62", a: false, f: true },
    ],
  },
  10: {
    id: "10",
    name: "Tunis",
    type: "Coast",
    supply: "Yes",
    countryID: "0",
    coast: "No",
    coastParentID: "10",
    smallMapX: "212",
    smallMapY: "390",
    Borders: [
      { id: "9", a: true, f: true },
      { id: "62", a: false, f: true },
      { id: "64", a: false, f: true },
      { id: "65", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "9", a: true, f: true },
      { id: "62", a: false, f: true },
      { id: "64", a: false, f: true },
      { id: "65", a: false, f: true },
    ],
  },
  11: {
    id: "11",
    name: "Naples",
    type: "Coast",
    supply: "Yes",
    countryID: "3",
    coast: "No",
    coastParentID: "11",
    smallMapX: "298",
    smallMapY: "362",
    Borders: [
      { id: "12", a: true, f: true },
      { id: "16", a: true, f: true },
      { id: "64", a: false, f: true },
      { id: "65", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "12", a: true, f: true },
      { id: "16", a: true, f: true },
      { id: "64", a: false, f: true },
      { id: "65", a: false, f: true },
    ],
  },
  12: {
    id: "12",
    name: "Rome",
    type: "Coast",
    supply: "Yes",
    countryID: "3",
    coast: "No",
    coastParentID: "12",
    smallMapX: "272",
    smallMapY: "332",
    Borders: [
      { id: "11", a: true, f: true },
      { id: "13", a: true, f: true },
      { id: "15", a: true, f: false },
      { id: "16", a: true, f: false },
      { id: "64", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "11", a: true, f: true },
      { id: "13", a: true, f: true },
      { id: "15", a: true, f: false },
      { id: "16", a: true, f: false },
      { id: "64", a: false, f: true },
    ],
  },
  13: {
    id: "13",
    name: "Tuscany",
    type: "Coast",
    supply: "No",
    countryID: "3",
    coast: "No",
    coastParentID: "13",
    smallMapX: "256",
    smallMapY: "309",
    Borders: [
      { id: "12", a: true, f: true },
      { id: "14", a: true, f: true },
      { id: "15", a: true, f: false },
      { id: "63", a: false, f: true },
      { id: "64", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "12", a: true, f: true },
      { id: "14", a: true, f: true },
      { id: "15", a: true, f: false },
      { id: "63", a: false, f: true },
      { id: "64", a: false, f: true },
    ],
  },
  14: {
    id: "14",
    name: "Piedmont",
    type: "Coast",
    supply: "No",
    countryID: "3",
    coast: "No",
    coastParentID: "14",
    smallMapX: "228",
    smallMapY: "279",
    Borders: [
      { id: "13", a: true, f: true },
      { id: "15", a: true, f: false },
      { id: "49", a: true, f: true },
      { id: "63", a: false, f: true },
      { id: "70", a: true, f: false },
    ],
    CoastalBorders: [
      { id: "13", a: true, f: true },
      { id: "15", a: true, f: false },
      { id: "49", a: true, f: true },
      { id: "63", a: false, f: true },
      { id: "70", a: true, f: false },
    ],
  },
  15: {
    id: "15",
    name: "Venice",
    type: "Coast",
    supply: "Yes",
    countryID: "3",
    coast: "No",
    coastParentID: "15",
    smallMapX: "261",
    smallMapY: "289",
    Borders: [
      { id: "12", a: true, f: false },
      { id: "13", a: true, f: false },
      { id: "14", a: true, f: false },
      { id: "16", a: true, f: true },
      { id: "66", a: false, f: true },
      { id: "70", a: true, f: false },
      { id: "73", a: true, f: true },
    ],
    CoastalBorders: [
      { id: "12", a: true, f: false },
      { id: "13", a: true, f: false },
      { id: "14", a: true, f: false },
      { id: "16", a: true, f: true },
      { id: "66", a: false, f: true },
      { id: "70", a: true, f: false },
      { id: "73", a: true, f: true },
    ],
  },
  16: {
    id: "16",
    name: "Apulia",
    type: "Coast",
    supply: "No",
    countryID: "3",
    coast: "No",
    coastParentID: "16",
    smallMapX: "305",
    smallMapY: "343",
    Borders: [
      { id: "11", a: true, f: true },
      { id: "12", a: true, f: false },
      { id: "15", a: true, f: true },
      { id: "65", a: false, f: true },
      { id: "66", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "11", a: true, f: true },
      { id: "12", a: true, f: false },
      { id: "15", a: true, f: true },
      { id: "65", a: false, f: true },
      { id: "66", a: false, f: true },
    ],
  },
  17: {
    id: "17",
    name: "Greece",
    type: "Coast",
    supply: "Yes",
    countryID: "0",
    coast: "No",
    coastParentID: "17",
    smallMapX: "358",
    smallMapY: "359",
    Borders: [
      { id: "18", a: true, f: true },
      { id: "19", a: true, f: false },
      { id: "20", a: true, f: true },
      { id: "65", a: false, f: true },
      { id: "67", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "18", a: true, f: true },
      { id: "19", a: true, f: false },
      { id: "20", a: true, f: false },
      { id: "65", a: false, f: true },
      { id: "67", a: false, f: true },
      { id: "81", a: false, f: true },
    ],
  },
  18: {
    id: "18",
    name: "Albania",
    type: "Coast",
    supply: "No",
    countryID: "0",
    coast: "No",
    coastParentID: "18",
    smallMapX: "344",
    smallMapY: "337",
    Borders: [
      { id: "17", a: true, f: true },
      { id: "19", a: true, f: false },
      { id: "65", a: false, f: true },
      { id: "66", a: false, f: true },
      { id: "73", a: true, f: true },
    ],
    CoastalBorders: [
      { id: "17", a: true, f: true },
      { id: "19", a: true, f: false },
      { id: "65", a: false, f: true },
      { id: "66", a: false, f: true },
      { id: "73", a: true, f: true },
    ],
  },
  19: {
    id: "19",
    name: "Serbia",
    type: "Land",
    supply: "Yes",
    countryID: "0",
    coast: "No",
    coastParentID: "19",
    smallMapX: "354",
    smallMapY: "315",
    Borders: [
      { id: "17", a: true, f: false },
      { id: "18", a: true, f: false },
      { id: "20", a: true, f: false },
      { id: "21", a: true, f: false },
      { id: "73", a: true, f: false },
      { id: "74", a: true, f: false },
    ],
    CoastalBorders: [
      { id: "17", a: true, f: false },
      { id: "18", a: true, f: false },
      { id: "20", a: true, f: false },
      { id: "21", a: true, f: false },
      { id: "73", a: true, f: false },
      { id: "74", a: true, f: false },
    ],
  },
  20: {
    id: "20",
    name: "Bulgaria",
    type: "Coast",
    supply: "Yes",
    countryID: "0",
    coast: "Parent",
    coastParentID: "20",
    smallMapX: "396",
    smallMapY: "311",
    Borders: [
      { id: "17", a: true, f: true },
      { id: "19", a: true, f: false },
      { id: "21", a: true, f: true },
      { id: "22", a: true, f: true },
      { id: "67", a: false, f: true },
      { id: "69", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "17", a: true, f: false },
      { id: "19", a: true, f: false },
      { id: "21", a: true, f: false },
      { id: "22", a: true, f: false },
    ],
  },
  21: {
    id: "21",
    name: "Rumania",
    type: "Coast",
    supply: "Yes",
    countryID: "0",
    coast: "No",
    coastParentID: "21",
    smallMapX: "422",
    smallMapY: "289",
    Borders: [
      { id: "19", a: true, f: false },
      { id: "20", a: true, f: true },
      { id: "27", a: true, f: true },
      { id: "28", a: true, f: false },
      { id: "69", a: false, f: true },
      { id: "74", a: true, f: false },
      { id: "75", a: true, f: false },
    ],
    CoastalBorders: [
      { id: "19", a: true, f: false },
      { id: "20", a: true, f: false },
      { id: "27", a: true, f: true },
      { id: "28", a: true, f: false },
      { id: "69", a: false, f: true },
      { id: "74", a: true, f: false },
      { id: "75", a: true, f: false },
      { id: "80", a: false, f: true },
    ],
  },
  22: {
    id: "22",
    name: "Constantinople",
    type: "Coast",
    supply: "Yes",
    countryID: "6",
    coast: "No",
    coastParentID: "22",
    smallMapX: "441",
    smallMapY: "341",
    Borders: [
      { id: "20", a: true, f: true },
      { id: "23", a: true, f: true },
      { id: "24", a: true, f: true },
      { id: "67", a: false, f: true },
      { id: "69", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "20", a: true, f: false },
      { id: "23", a: true, f: true },
      { id: "24", a: true, f: true },
      { id: "67", a: false, f: true },
      { id: "69", a: false, f: true },
      { id: "80", a: false, f: true },
      { id: "81", a: false, f: true },
    ],
  },
  23: {
    id: "23",
    name: "Smyrna",
    type: "Coast",
    supply: "Yes",
    countryID: "6",
    coast: "No",
    coastParentID: "23",
    smallMapX: "480",
    smallMapY: "360",
    Borders: [
      { id: "22", a: true, f: true },
      { id: "24", a: true, f: false },
      { id: "25", a: true, f: false },
      { id: "26", a: true, f: true },
      { id: "67", a: false, f: true },
      { id: "68", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "22", a: true, f: true },
      { id: "24", a: true, f: false },
      { id: "25", a: true, f: false },
      { id: "26", a: true, f: true },
      { id: "67", a: false, f: true },
      { id: "68", a: false, f: true },
    ],
  },
  24: {
    id: "24",
    name: "Ankara",
    type: "Coast",
    supply: "Yes",
    countryID: "6",
    coast: "No",
    coastParentID: "24",
    smallMapX: "498",
    smallMapY: "325",
    Borders: [
      { id: "22", a: true, f: true },
      { id: "23", a: true, f: false },
      { id: "25", a: true, f: true },
      { id: "69", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "22", a: true, f: true },
      { id: "23", a: true, f: false },
      { id: "25", a: true, f: true },
      { id: "69", a: false, f: true },
    ],
  },
  25: {
    id: "25",
    name: "Armenia",
    type: "Coast",
    supply: "No",
    countryID: "6",
    coast: "No",
    coastParentID: "25",
    smallMapX: "572",
    smallMapY: "323",
    Borders: [
      { id: "23", a: true, f: false },
      { id: "24", a: true, f: true },
      { id: "26", a: true, f: false },
      { id: "27", a: true, f: true },
      { id: "69", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "23", a: true, f: false },
      { id: "24", a: true, f: true },
      { id: "26", a: true, f: false },
      { id: "27", a: true, f: true },
      { id: "69", a: false, f: true },
    ],
  },
  26: {
    id: "26",
    name: "Syria",
    type: "Coast",
    supply: "No",
    countryID: "6",
    coast: "No",
    coastParentID: "26",
    smallMapX: "559",
    smallMapY: "381",
    Borders: [
      { id: "23", a: true, f: true },
      { id: "25", a: true, f: false },
      { id: "68", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "23", a: true, f: true },
      { id: "25", a: true, f: false },
      { id: "68", a: false, f: true },
    ],
  },
  27: {
    id: "27",
    name: "Sevastopol",
    type: "Coast",
    supply: "Yes",
    countryID: "7",
    coast: "No",
    coastParentID: "27",
    smallMapX: "500",
    smallMapY: "244",
    Borders: [
      { id: "21", a: true, f: true },
      { id: "25", a: true, f: true },
      { id: "28", a: true, f: false },
      { id: "31", a: true, f: false },
      { id: "69", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "21", a: true, f: true },
      { id: "25", a: true, f: true },
      { id: "28", a: true, f: false },
      { id: "31", a: true, f: false },
      { id: "69", a: false, f: true },
    ],
  },
  28: {
    id: "28",
    name: "Ukraine",
    type: "Land",
    supply: "No",
    countryID: "7",
    coast: "No",
    coastParentID: "28",
    smallMapX: "418",
    smallMapY: "223",
    Borders: [
      { id: "21", a: true, f: false },
      { id: "27", a: true, f: false },
      { id: "29", a: true, f: false },
      { id: "31", a: true, f: false },
      { id: "75", a: true, f: false },
    ],
    CoastalBorders: [
      { id: "21", a: true, f: false },
      { id: "27", a: true, f: false },
      { id: "29", a: true, f: false },
      { id: "31", a: true, f: false },
      { id: "75", a: true, f: false },
    ],
  },
  29: {
    id: "29",
    name: "Warsaw",
    type: "Land",
    supply: "Yes",
    countryID: "7",
    coast: "No",
    coastParentID: "29",
    smallMapX: "354",
    smallMapY: "212",
    Borders: [
      { id: "28", a: true, f: false },
      { id: "30", a: true, f: false },
      { id: "31", a: true, f: false },
      { id: "39", a: true, f: false },
      { id: "40", a: true, f: false },
      { id: "75", a: true, f: false },
    ],
    CoastalBorders: [
      { id: "28", a: true, f: false },
      { id: "30", a: true, f: false },
      { id: "31", a: true, f: false },
      { id: "39", a: true, f: false },
      { id: "40", a: true, f: false },
      { id: "75", a: true, f: false },
    ],
  },
  30: {
    id: "30",
    name: "Livonia",
    type: "Coast",
    supply: "No",
    countryID: "7",
    coast: "No",
    coastParentID: "30",
    smallMapX: "374",
    smallMapY: "168",
    Borders: [
      { id: "29", a: true, f: false },
      { id: "31", a: true, f: false },
      { id: "32", a: true, f: true },
      { id: "39", a: true, f: true },
      { id: "56", a: false, f: true },
      { id: "57", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "29", a: true, f: false },
      { id: "31", a: true, f: false },
      { id: "32", a: true, f: false },
      { id: "39", a: true, f: true },
      { id: "56", a: false, f: true },
      { id: "57", a: false, f: true },
      { id: "79", a: false, f: true },
    ],
  },
  31: {
    id: "31",
    name: "Moscow",
    type: "Land",
    supply: "Yes",
    countryID: "7",
    coast: "No",
    coastParentID: "31",
    smallMapX: "490",
    smallMapY: "155",
    Borders: [
      { id: "27", a: true, f: false },
      { id: "28", a: true, f: false },
      { id: "29", a: true, f: false },
      { id: "30", a: true, f: false },
      { id: "32", a: true, f: false },
    ],
    CoastalBorders: [
      { id: "27", a: true, f: false },
      { id: "28", a: true, f: false },
      { id: "29", a: true, f: false },
      { id: "30", a: true, f: false },
      { id: "32", a: true, f: false },
    ],
  },
  32: {
    id: "32",
    name: "St. Petersburg",
    type: "Coast",
    supply: "Yes",
    countryID: "7",
    coast: "Parent",
    coastParentID: "32",
    smallMapX: "445",
    smallMapY: "104",
    Borders: [
      { id: "30", a: true, f: true },
      { id: "31", a: true, f: false },
      { id: "33", a: true, f: true },
      { id: "35", a: true, f: true },
      { id: "51", a: false, f: true },
      { id: "57", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "30", a: true, f: false },
      { id: "31", a: true, f: false },
      { id: "33", a: true, f: false },
      { id: "35", a: true, f: false },
    ],
  },
  33: {
    id: "33",
    name: "Finland",
    type: "Coast",
    supply: "No",
    countryID: "7",
    coast: "No",
    coastParentID: "33",
    smallMapX: "367",
    smallMapY: "109",
    Borders: [
      { id: "32", a: true, f: true },
      { id: "34", a: true, f: true },
      { id: "35", a: true, f: false },
      { id: "57", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "32", a: true, f: false },
      { id: "34", a: true, f: true },
      { id: "35", a: true, f: false },
      { id: "57", a: false, f: true },
      { id: "79", a: false, f: true },
    ],
  },
  34: {
    id: "34",
    name: "Sweden",
    type: "Coast",
    supply: "Yes",
    countryID: "0",
    coast: "No",
    coastParentID: "34",
    smallMapX: "313",
    smallMapY: "87",
    Borders: [
      { id: "33", a: true, f: true },
      { id: "35", a: true, f: true },
      { id: "36", a: true, f: true },
      { id: "54", a: false, f: true },
      { id: "56", a: false, f: true },
      { id: "57", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "33", a: true, f: true },
      { id: "35", a: true, f: true },
      { id: "36", a: true, f: true },
      { id: "54", a: false, f: true },
      { id: "56", a: false, f: true },
      { id: "57", a: false, f: true },
    ],
  },
  35: {
    id: "35",
    name: "Norway",
    type: "Coast",
    supply: "Yes",
    countryID: "0",
    coast: "No",
    coastParentID: "35",
    smallMapX: "271",
    smallMapY: "100",
    Borders: [
      { id: "32", a: true, f: true },
      { id: "33", a: true, f: false },
      { id: "34", a: true, f: true },
      { id: "51", a: false, f: true },
      { id: "52", a: false, f: true },
      { id: "53", a: false, f: true },
      { id: "54", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "32", a: true, f: false },
      { id: "33", a: true, f: false },
      { id: "34", a: true, f: true },
      { id: "51", a: false, f: true },
      { id: "52", a: false, f: true },
      { id: "53", a: false, f: true },
      { id: "54", a: false, f: true },
      { id: "78", a: false, f: true },
    ],
  },
  36: {
    id: "36",
    name: "Denmark",
    type: "Coast",
    supply: "Yes",
    countryID: "0",
    coast: "No",
    coastParentID: "36",
    smallMapX: "264",
    smallMapY: "156",
    Borders: [
      { id: "34", a: true, f: true },
      { id: "37", a: true, f: true },
      { id: "53", a: false, f: true },
      { id: "54", a: false, f: true },
      { id: "55", a: false, f: true },
      { id: "56", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "34", a: true, f: true },
      { id: "37", a: true, f: true },
      { id: "53", a: false, f: true },
      { id: "54", a: false, f: true },
      { id: "55", a: false, f: true },
      { id: "56", a: false, f: true },
    ],
  },
  37: {
    id: "37",
    name: "Kiel",
    type: "Coast",
    supply: "Yes",
    countryID: "4",
    coast: "No",
    coastParentID: "37",
    smallMapX: "256",
    smallMapY: "200",
    Borders: [
      { id: "36", a: true, f: true },
      { id: "38", a: true, f: true },
      { id: "41", a: true, f: false },
      { id: "42", a: true, f: false },
      { id: "43", a: true, f: true },
      { id: "55", a: false, f: true },
      { id: "56", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "36", a: true, f: true },
      { id: "38", a: true, f: true },
      { id: "41", a: true, f: false },
      { id: "42", a: true, f: false },
      { id: "43", a: true, f: true },
      { id: "55", a: false, f: true },
      { id: "56", a: false, f: true },
    ],
  },
  38: {
    id: "38",
    name: "Berlin",
    type: "Coast",
    supply: "Yes",
    countryID: "4",
    coast: "No",
    coastParentID: "38",
    smallMapX: "292",
    smallMapY: "193",
    Borders: [
      { id: "37", a: true, f: true },
      { id: "39", a: true, f: true },
      { id: "40", a: true, f: false },
      { id: "41", a: true, f: false },
      { id: "56", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "37", a: true, f: true },
      { id: "39", a: true, f: true },
      { id: "40", a: true, f: false },
      { id: "41", a: true, f: false },
      { id: "56", a: false, f: true },
    ],
  },
  39: {
    id: "39",
    name: "Prussia",
    type: "Coast",
    supply: "No",
    countryID: "4",
    coast: "No",
    coastParentID: "39",
    smallMapX: "329",
    smallMapY: "192",
    Borders: [
      { id: "29", a: true, f: false },
      { id: "30", a: true, f: true },
      { id: "38", a: true, f: true },
      { id: "40", a: true, f: false },
      { id: "56", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "29", a: true, f: false },
      { id: "30", a: true, f: true },
      { id: "38", a: true, f: true },
      { id: "40", a: true, f: false },
      { id: "56", a: false, f: true },
    ],
  },
  40: {
    id: "40",
    name: "Silesia",
    type: "Land",
    supply: "No",
    countryID: "4",
    coast: "No",
    coastParentID: "40",
    smallMapX: "304",
    smallMapY: "217",
    Borders: [
      { id: "29", a: true, f: false },
      { id: "38", a: true, f: false },
      { id: "39", a: true, f: false },
      { id: "41", a: true, f: false },
      { id: "71", a: true, f: false },
      { id: "75", a: true, f: false },
    ],
    CoastalBorders: [
      { id: "29", a: true, f: false },
      { id: "38", a: true, f: false },
      { id: "39", a: true, f: false },
      { id: "41", a: true, f: false },
      { id: "71", a: true, f: false },
      { id: "75", a: true, f: false },
    ],
  },
  41: {
    id: "41",
    name: "Munich",
    type: "Land",
    supply: "Yes",
    countryID: "4",
    coast: "No",
    coastParentID: "41",
    smallMapX: "248",
    smallMapY: "232",
    Borders: [
      { id: "37", a: true, f: false },
      { id: "38", a: true, f: false },
      { id: "40", a: true, f: false },
      { id: "42", a: true, f: false },
      { id: "48", a: true, f: false },
      { id: "70", a: true, f: false },
      { id: "71", a: true, f: false },
    ],
    CoastalBorders: [
      { id: "37", a: true, f: false },
      { id: "38", a: true, f: false },
      { id: "40", a: true, f: false },
      { id: "42", a: true, f: false },
      { id: "48", a: true, f: false },
      { id: "70", a: true, f: false },
      { id: "71", a: true, f: false },
    ],
  },
  42: {
    id: "42",
    name: "Ruhr",
    type: "Land",
    supply: "No",
    countryID: "4",
    coast: "No",
    coastParentID: "42",
    smallMapX: "234",
    smallMapY: "214",
    Borders: [
      { id: "37", a: true, f: false },
      { id: "41", a: true, f: false },
      { id: "43", a: true, f: false },
      { id: "44", a: true, f: false },
      { id: "48", a: true, f: false },
    ],
    CoastalBorders: [
      { id: "37", a: true, f: false },
      { id: "41", a: true, f: false },
      { id: "43", a: true, f: false },
      { id: "44", a: true, f: false },
      { id: "48", a: true, f: false },
    ],
  },
  43: {
    id: "43",
    name: "Holland",
    type: "Coast",
    supply: "Yes",
    countryID: "0",
    coast: "No",
    coastParentID: "43",
    smallMapX: "234",
    smallMapY: "186",
    Borders: [
      { id: "37", a: true, f: true },
      { id: "42", a: true, f: false },
      { id: "44", a: true, f: true },
      { id: "53", a: false, f: true },
      { id: "55", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "37", a: true, f: true },
      { id: "42", a: true, f: false },
      { id: "44", a: true, f: true },
      { id: "53", a: false, f: true },
      { id: "55", a: false, f: true },
    ],
  },
  44: {
    id: "44",
    name: "Belgium",
    type: "Coast",
    supply: "Yes",
    countryID: "0",
    coast: "No",
    coastParentID: "44",
    smallMapX: "215",
    smallMapY: "205",
    Borders: [
      { id: "42", a: true, f: false },
      { id: "43", a: true, f: true },
      { id: "45", a: true, f: true },
      { id: "48", a: true, f: false },
      { id: "53", a: false, f: true },
      { id: "60", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "42", a: true, f: false },
      { id: "43", a: true, f: true },
      { id: "45", a: true, f: true },
      { id: "48", a: true, f: false },
      { id: "53", a: false, f: true },
      { id: "60", a: false, f: true },
    ],
  },
  45: {
    id: "45",
    name: "Picardy",
    type: "Coast",
    supply: "No",
    countryID: "2",
    coast: "No",
    coastParentID: "45",
    smallMapX: "189",
    smallMapY: "214",
    Borders: [
      { id: "44", a: true, f: true },
      { id: "46", a: true, f: true },
      { id: "47", a: true, f: false },
      { id: "48", a: true, f: false },
      { id: "60", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "44", a: true, f: true },
      { id: "46", a: true, f: true },
      { id: "47", a: true, f: false },
      { id: "48", a: true, f: false },
      { id: "60", a: false, f: true },
    ],
  },
  46: {
    id: "46",
    name: "Brest",
    type: "Coast",
    supply: "Yes",
    countryID: "2",
    coast: "No",
    coastParentID: "46",
    smallMapX: "146",
    smallMapY: "223",
    Borders: [
      { id: "45", a: true, f: true },
      { id: "47", a: true, f: false },
      { id: "50", a: true, f: true },
      { id: "60", a: false, f: true },
      { id: "61", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "45", a: true, f: true },
      { id: "47", a: true, f: false },
      { id: "50", a: true, f: true },
      { id: "60", a: false, f: true },
      { id: "61", a: false, f: true },
    ],
  },
  47: {
    id: "47",
    name: "Paris",
    type: "Land",
    supply: "Yes",
    countryID: "2",
    coast: "No",
    coastParentID: "47",
    smallMapX: "179",
    smallMapY: "238",
    Borders: [
      { id: "45", a: true, f: false },
      { id: "46", a: true, f: false },
      { id: "48", a: true, f: false },
      { id: "50", a: true, f: false },
    ],
    CoastalBorders: [
      { id: "45", a: true, f: false },
      { id: "46", a: true, f: false },
      { id: "48", a: true, f: false },
      { id: "50", a: true, f: false },
    ],
  },
  48: {
    id: "48",
    name: "Burgundy",
    type: "Land",
    supply: "No",
    countryID: "2",
    coast: "No",
    coastParentID: "48",
    smallMapX: "206",
    smallMapY: "248",
    Borders: [
      { id: "41", a: true, f: false },
      { id: "42", a: true, f: false },
      { id: "44", a: true, f: false },
      { id: "45", a: true, f: false },
      { id: "47", a: true, f: false },
      { id: "49", a: true, f: false },
      { id: "50", a: true, f: false },
    ],
    CoastalBorders: [
      { id: "41", a: true, f: false },
      { id: "42", a: true, f: false },
      { id: "44", a: true, f: false },
      { id: "45", a: true, f: false },
      { id: "47", a: true, f: false },
      { id: "49", a: true, f: false },
      { id: "50", a: true, f: false },
    ],
  },
  49: {
    id: "49",
    name: "Marseilles",
    type: "Coast",
    supply: "Yes",
    countryID: "2",
    coast: "No",
    coastParentID: "49",
    smallMapX: "183",
    smallMapY: "286",
    Borders: [
      { id: "8", a: true, f: true },
      { id: "14", a: true, f: true },
      { id: "48", a: true, f: false },
      { id: "50", a: true, f: false },
      { id: "63", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "8", a: true, f: false },
      { id: "14", a: true, f: true },
      { id: "48", a: true, f: false },
      { id: "50", a: true, f: false },
      { id: "63", a: false, f: true },
      { id: "77", a: false, f: true },
    ],
  },
  50: {
    id: "50",
    name: "Gascony",
    type: "Coast",
    supply: "No",
    countryID: "2",
    coast: "No",
    coastParentID: "50",
    smallMapX: "150",
    smallMapY: "274",
    Borders: [
      { id: "8", a: true, f: true },
      { id: "46", a: true, f: true },
      { id: "47", a: true, f: false },
      { id: "48", a: true, f: false },
      { id: "49", a: true, f: false },
      { id: "61", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "8", a: true, f: false },
      { id: "46", a: true, f: true },
      { id: "47", a: true, f: false },
      { id: "48", a: true, f: false },
      { id: "49", a: true, f: false },
      { id: "61", a: false, f: true },
      { id: "76", a: false, f: true },
    ],
  },
  51: {
    id: "51",
    name: "Barents Sea",
    type: "Sea",
    supply: "No",
    countryID: "0",
    coast: "No",
    coastParentID: "51",
    smallMapX: "420",
    smallMapY: "20",
    Borders: [
      { id: "32", a: false, f: true },
      { id: "35", a: false, f: true },
      { id: "52", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "35", a: false, f: true },
      { id: "52", a: false, f: true },
      { id: "78", a: false, f: true },
    ],
  },
  52: {
    id: "52",
    name: "Norwegian Sea",
    type: "Sea",
    supply: "No",
    countryID: "0",
    coast: "No",
    coastParentID: "52",
    smallMapX: "268",
    smallMapY: "35",
    Borders: [
      { id: "1", a: false, f: true },
      { id: "2", a: false, f: true },
      { id: "35", a: false, f: true },
      { id: "51", a: false, f: true },
      { id: "53", a: false, f: true },
      { id: "58", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "1", a: false, f: true },
      { id: "2", a: false, f: true },
      { id: "35", a: false, f: true },
      { id: "51", a: false, f: true },
      { id: "53", a: false, f: true },
      { id: "58", a: false, f: true },
    ],
  },
  53: {
    id: "53",
    name: "North Sea",
    type: "Sea",
    supply: "No",
    countryID: "0",
    coast: "No",
    coastParentID: "53",
    smallMapX: "216",
    smallMapY: "136",
    Borders: [
      { id: "2", a: false, f: true },
      { id: "4", a: false, f: true },
      { id: "6", a: false, f: true },
      { id: "35", a: false, f: true },
      { id: "36", a: false, f: true },
      { id: "43", a: false, f: true },
      { id: "44", a: false, f: true },
      { id: "52", a: false, f: true },
      { id: "54", a: false, f: true },
      { id: "55", a: false, f: true },
      { id: "60", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "2", a: false, f: true },
      { id: "4", a: false, f: true },
      { id: "6", a: false, f: true },
      { id: "35", a: false, f: true },
      { id: "36", a: false, f: true },
      { id: "43", a: false, f: true },
      { id: "44", a: false, f: true },
      { id: "52", a: false, f: true },
      { id: "54", a: false, f: true },
      { id: "55", a: false, f: true },
      { id: "60", a: false, f: true },
    ],
  },
  54: {
    id: "54",
    name: "Skagerrack",
    type: "Sea",
    supply: "No",
    countryID: "0",
    coast: "No",
    coastParentID: "54",
    smallMapX: "279",
    smallMapY: "133",
    Borders: [
      { id: "34", a: false, f: true },
      { id: "35", a: false, f: true },
      { id: "36", a: false, f: true },
      { id: "53", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "34", a: false, f: true },
      { id: "35", a: false, f: true },
      { id: "36", a: false, f: true },
      { id: "53", a: false, f: true },
    ],
  },
  55: {
    id: "55",
    name: "Heligoland Bight",
    type: "Sea",
    supply: "No",
    countryID: "0",
    coast: "No",
    coastParentID: "55",
    smallMapX: "250",
    smallMapY: "167",
    Borders: [
      { id: "36", a: false, f: true },
      { id: "37", a: false, f: true },
      { id: "43", a: false, f: true },
      { id: "53", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "36", a: false, f: true },
      { id: "37", a: false, f: true },
      { id: "43", a: false, f: true },
      { id: "53", a: false, f: true },
    ],
  },
  56: {
    id: "56",
    name: "Baltic Sea",
    type: "Sea",
    supply: "No",
    countryID: "0",
    coast: "No",
    coastParentID: "56",
    smallMapX: "338",
    smallMapY: "175",
    Borders: [
      { id: "30", a: false, f: true },
      { id: "34", a: false, f: true },
      { id: "36", a: false, f: true },
      { id: "37", a: false, f: true },
      { id: "38", a: false, f: true },
      { id: "39", a: false, f: true },
      { id: "57", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "30", a: false, f: true },
      { id: "34", a: false, f: true },
      { id: "36", a: false, f: true },
      { id: "37", a: false, f: true },
      { id: "38", a: false, f: true },
      { id: "39", a: false, f: true },
      { id: "57", a: false, f: true },
    ],
  },
  57: {
    id: "57",
    name: "Gulf of Bothnia",
    type: "Sea",
    supply: "No",
    countryID: "0",
    coast: "No",
    coastParentID: "57",
    smallMapX: "362",
    smallMapY: "131",
    Borders: [
      { id: "30", a: false, f: true },
      { id: "32", a: false, f: true },
      { id: "33", a: false, f: true },
      { id: "34", a: false, f: true },
      { id: "56", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "30", a: false, f: true },
      { id: "33", a: false, f: true },
      { id: "34", a: false, f: true },
      { id: "56", a: false, f: true },
      { id: "79", a: false, f: true },
    ],
  },
  58: {
    id: "58",
    name: "North Atlantic Ocean",
    type: "Sea",
    supply: "No",
    countryID: "0",
    coast: "No",
    coastParentID: "58",
    smallMapX: "78",
    smallMapY: "87",
    Borders: [
      { id: "1", a: false, f: true },
      { id: "3", a: false, f: true },
      { id: "52", a: false, f: true },
      { id: "59", a: false, f: true },
      { id: "61", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "1", a: false, f: true },
      { id: "3", a: false, f: true },
      { id: "52", a: false, f: true },
      { id: "59", a: false, f: true },
      { id: "61", a: false, f: true },
    ],
  },
  59: {
    id: "59",
    name: "Irish Sea",
    type: "Sea",
    supply: "No",
    countryID: "0",
    coast: "No",
    coastParentID: "59",
    smallMapX: "110",
    smallMapY: "178",
    Borders: [
      { id: "3", a: false, f: true },
      { id: "5", a: false, f: true },
      { id: "58", a: false, f: true },
      { id: "60", a: false, f: true },
      { id: "61", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "3", a: false, f: true },
      { id: "5", a: false, f: true },
      { id: "58", a: false, f: true },
      { id: "60", a: false, f: true },
      { id: "61", a: false, f: true },
    ],
  },
  60: {
    id: "60",
    name: "English Channel",
    type: "Sea",
    supply: "No",
    countryID: "0",
    coast: "No",
    coastParentID: "60",
    smallMapX: "153",
    smallMapY: "198",
    Borders: [
      { id: "5", a: false, f: true },
      { id: "6", a: false, f: true },
      { id: "44", a: false, f: true },
      { id: "45", a: false, f: true },
      { id: "46", a: false, f: true },
      { id: "53", a: false, f: true },
      { id: "59", a: false, f: true },
      { id: "61", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "5", a: false, f: true },
      { id: "6", a: false, f: true },
      { id: "44", a: false, f: true },
      { id: "45", a: false, f: true },
      { id: "46", a: false, f: true },
      { id: "53", a: false, f: true },
      { id: "59", a: false, f: true },
      { id: "61", a: false, f: true },
    ],
  },
  61: {
    id: "61",
    name: "Mid-Atlantic Ocean",
    type: "Sea",
    supply: "No",
    countryID: "0",
    coast: "No",
    coastParentID: "61",
    smallMapX: "81",
    smallMapY: "247",
    Borders: [
      { id: "7", a: false, f: true },
      { id: "8", a: false, f: true },
      { id: "9", a: false, f: true },
      { id: "46", a: false, f: true },
      { id: "50", a: false, f: true },
      { id: "58", a: false, f: true },
      { id: "59", a: false, f: true },
      { id: "60", a: false, f: true },
      { id: "62", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "7", a: false, f: true },
      { id: "9", a: false, f: true },
      { id: "46", a: false, f: true },
      { id: "50", a: false, f: true },
      { id: "58", a: false, f: true },
      { id: "59", a: false, f: true },
      { id: "60", a: false, f: true },
      { id: "62", a: false, f: true },
      { id: "76", a: false, f: true },
      { id: "77", a: false, f: true },
    ],
  },
  62: {
    id: "62",
    name: "Western Mediterranean",
    type: "Sea",
    supply: "No",
    countryID: "0",
    coast: "No",
    coastParentID: "62",
    smallMapX: "186",
    smallMapY: "363",
    Borders: [
      { id: "8", a: false, f: true },
      { id: "9", a: false, f: true },
      { id: "10", a: false, f: true },
      { id: "61", a: false, f: true },
      { id: "63", a: false, f: true },
      { id: "64", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "9", a: false, f: true },
      { id: "10", a: false, f: true },
      { id: "61", a: false, f: true },
      { id: "63", a: false, f: true },
      { id: "64", a: false, f: true },
      { id: "77", a: false, f: true },
    ],
  },
  63: {
    id: "63",
    name: "Gulf of Lyons",
    type: "Sea",
    supply: "No",
    countryID: "0",
    coast: "No",
    coastParentID: "63",
    smallMapX: "205",
    smallMapY: "323",
    Borders: [
      { id: "8", a: false, f: true },
      { id: "13", a: false, f: true },
      { id: "14", a: false, f: true },
      { id: "49", a: false, f: true },
      { id: "62", a: false, f: true },
      { id: "64", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "13", a: false, f: true },
      { id: "14", a: false, f: true },
      { id: "49", a: false, f: true },
      { id: "62", a: false, f: true },
      { id: "64", a: false, f: true },
      { id: "77", a: false, f: true },
    ],
  },
  64: {
    id: "64",
    name: "Tyrrhenian Sea",
    type: "Sea",
    supply: "No",
    countryID: "0",
    coast: "No",
    coastParentID: "64",
    smallMapX: "250",
    smallMapY: "348",
    Borders: [
      { id: "10", a: false, f: true },
      { id: "11", a: false, f: true },
      { id: "12", a: false, f: true },
      { id: "13", a: false, f: true },
      { id: "62", a: false, f: true },
      { id: "63", a: false, f: true },
      { id: "65", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "10", a: false, f: true },
      { id: "11", a: false, f: true },
      { id: "12", a: false, f: true },
      { id: "13", a: false, f: true },
      { id: "62", a: false, f: true },
      { id: "63", a: false, f: true },
      { id: "65", a: false, f: true },
    ],
  },
  65: {
    id: "65",
    name: "Ionian Sea",
    type: "Sea",
    supply: "No",
    countryID: "0",
    coast: "No",
    coastParentID: "65",
    smallMapX: "325",
    smallMapY: "384",
    Borders: [
      { id: "10", a: false, f: true },
      { id: "11", a: false, f: true },
      { id: "16", a: false, f: true },
      { id: "17", a: false, f: true },
      { id: "18", a: false, f: true },
      { id: "64", a: false, f: true },
      { id: "66", a: false, f: true },
      { id: "67", a: false, f: true },
      { id: "68", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "10", a: false, f: true },
      { id: "11", a: false, f: true },
      { id: "16", a: false, f: true },
      { id: "17", a: false, f: true },
      { id: "18", a: false, f: true },
      { id: "64", a: false, f: true },
      { id: "66", a: false, f: true },
      { id: "67", a: false, f: true },
      { id: "68", a: false, f: true },
    ],
  },
  66: {
    id: "66",
    name: "Adriatic Sea",
    type: "Sea",
    supply: "No",
    countryID: "0",
    coast: "No",
    coastParentID: "66",
    smallMapX: "311",
    smallMapY: "319",
    Borders: [
      { id: "15", a: false, f: true },
      { id: "16", a: false, f: true },
      { id: "18", a: false, f: true },
      { id: "65", a: false, f: true },
      { id: "73", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "15", a: false, f: true },
      { id: "16", a: false, f: true },
      { id: "18", a: false, f: true },
      { id: "65", a: false, f: true },
      { id: "73", a: false, f: true },
    ],
  },
  67: {
    id: "67",
    name: "Aegean Sea",
    type: "Sea",
    supply: "No",
    countryID: "0",
    coast: "No",
    coastParentID: "67",
    smallMapX: "400",
    smallMapY: "378",
    Borders: [
      { id: "17", a: false, f: true },
      { id: "20", a: false, f: true },
      { id: "22", a: false, f: true },
      { id: "23", a: false, f: true },
      { id: "65", a: false, f: true },
      { id: "68", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "17", a: false, f: true },
      { id: "22", a: false, f: true },
      { id: "23", a: false, f: true },
      { id: "65", a: false, f: true },
      { id: "68", a: false, f: true },
      { id: "81", a: false, f: true },
    ],
  },
  68: {
    id: "68",
    name: "Eastern Mediterranean",
    type: "Sea",
    supply: "No",
    countryID: "0",
    coast: "No",
    coastParentID: "68",
    smallMapX: "454",
    smallMapY: "391",
    Borders: [
      { id: "23", a: false, f: true },
      { id: "26", a: false, f: true },
      { id: "65", a: false, f: true },
      { id: "67", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "23", a: false, f: true },
      { id: "26", a: false, f: true },
      { id: "65", a: false, f: true },
      { id: "67", a: false, f: true },
    ],
  },
  69: {
    id: "69",
    name: "Black Sea",
    type: "Sea",
    supply: "No",
    countryID: "0",
    coast: "No",
    coastParentID: "69",
    smallMapX: "469",
    smallMapY: "300",
    Borders: [
      { id: "20", a: false, f: true },
      { id: "21", a: false, f: true },
      { id: "22", a: false, f: true },
      { id: "24", a: false, f: true },
      { id: "25", a: false, f: true },
      { id: "27", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "21", a: false, f: true },
      { id: "22", a: false, f: true },
      { id: "24", a: false, f: true },
      { id: "25", a: false, f: true },
      { id: "27", a: false, f: true },
      { id: "80", a: false, f: true },
    ],
  },
  70: {
    id: "70",
    name: "Tyrolia",
    type: "Land",
    supply: "No",
    countryID: "5",
    coast: "No",
    coastParentID: "70",
    smallMapX: "273",
    smallMapY: "260",
    Borders: [
      { id: "14", a: true, f: false },
      { id: "15", a: true, f: false },
      { id: "41", a: true, f: false },
      { id: "71", a: true, f: false },
      { id: "72", a: true, f: false },
      { id: "73", a: true, f: false },
    ],
    CoastalBorders: [
      { id: "14", a: true, f: false },
      { id: "15", a: true, f: false },
      { id: "41", a: true, f: false },
      { id: "71", a: true, f: false },
      { id: "72", a: true, f: false },
      { id: "73", a: true, f: false },
    ],
  },
  71: {
    id: "71",
    name: "Bohemia",
    type: "Land",
    supply: "No",
    countryID: "5",
    coast: "No",
    coastParentID: "71",
    smallMapX: "292",
    smallMapY: "232",
    Borders: [
      { id: "40", a: true, f: false },
      { id: "41", a: true, f: false },
      { id: "70", a: true, f: false },
      { id: "72", a: true, f: false },
      { id: "75", a: true, f: false },
    ],
    CoastalBorders: [
      { id: "40", a: true, f: false },
      { id: "41", a: true, f: false },
      { id: "70", a: true, f: false },
      { id: "72", a: true, f: false },
      { id: "75", a: true, f: false },
    ],
  },
  72: {
    id: "72",
    name: "Vienna",
    type: "Land",
    supply: "Yes",
    countryID: "5",
    coast: "No",
    coastParentID: "72",
    smallMapX: "319",
    smallMapY: "246",
    Borders: [
      { id: "70", a: true, f: false },
      { id: "71", a: true, f: false },
      { id: "73", a: true, f: false },
      { id: "74", a: true, f: false },
      { id: "75", a: true, f: false },
    ],
    CoastalBorders: [
      { id: "70", a: true, f: false },
      { id: "71", a: true, f: false },
      { id: "73", a: true, f: false },
      { id: "74", a: true, f: false },
      { id: "75", a: true, f: false },
    ],
  },
  73: {
    id: "73",
    name: "Trieste",
    type: "Coast",
    supply: "Yes",
    countryID: "5",
    coast: "No",
    coastParentID: "73",
    smallMapX: "311",
    smallMapY: "291",
    Borders: [
      { id: "15", a: true, f: true },
      { id: "18", a: true, f: true },
      { id: "19", a: true, f: false },
      { id: "66", a: false, f: true },
      { id: "70", a: true, f: false },
      { id: "72", a: true, f: false },
      { id: "74", a: true, f: false },
    ],
    CoastalBorders: [
      { id: "15", a: true, f: true },
      { id: "18", a: true, f: true },
      { id: "19", a: true, f: false },
      { id: "66", a: false, f: true },
      { id: "70", a: true, f: false },
      { id: "72", a: true, f: false },
      { id: "74", a: true, f: false },
    ],
  },
  74: {
    id: "74",
    name: "Budapest",
    type: "Land",
    supply: "Yes",
    countryID: "5",
    coast: "No",
    coastParentID: "74",
    smallMapX: "354",
    smallMapY: "271",
    Borders: [
      { id: "19", a: true, f: false },
      { id: "21", a: true, f: false },
      { id: "72", a: true, f: false },
      { id: "73", a: true, f: false },
      { id: "75", a: true, f: false },
    ],
    CoastalBorders: [
      { id: "19", a: true, f: false },
      { id: "21", a: true, f: false },
      { id: "72", a: true, f: false },
      { id: "73", a: true, f: false },
      { id: "75", a: true, f: false },
    ],
  },
  75: {
    id: "75",
    name: "Galicia",
    type: "Land",
    supply: "No",
    countryID: "5",
    coast: "No",
    coastParentID: "75",
    smallMapX: "365",
    smallMapY: "237",
    Borders: [
      { id: "21", a: true, f: false },
      { id: "28", a: true, f: false },
      { id: "29", a: true, f: false },
      { id: "40", a: true, f: false },
      { id: "71", a: true, f: false },
      { id: "72", a: true, f: false },
      { id: "74", a: true, f: false },
    ],
    CoastalBorders: [
      { id: "21", a: true, f: false },
      { id: "28", a: true, f: false },
      { id: "29", a: true, f: false },
      { id: "40", a: true, f: false },
      { id: "71", a: true, f: false },
      { id: "72", a: true, f: false },
      { id: "74", a: true, f: false },
    ],
  },
  76: {
    id: "76",
    name: "Spain (North Coast)",
    type: "Coast",
    supply: "No",
    countryID: "0",
    coast: "Child",
    coastParentID: "8",
    smallMapX: "94",
    smallMapY: "277",
    Borders: [
      { id: "7", a: false, f: true },
      { id: "50", a: false, f: true },
      { id: "61", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "7", a: false, f: true },
      { id: "50", a: false, f: true },
      { id: "61", a: false, f: true },
    ],
  },
  77: {
    id: "77",
    name: "Spain (South Coast)",
    type: "Coast",
    supply: "No",
    countryID: "0",
    coast: "Child",
    coastParentID: "8",
    smallMapX: "106",
    smallMapY: "345",
    Borders: [
      { id: "7", a: false, f: true },
      { id: "49", a: false, f: true },
      { id: "61", a: false, f: true },
      { id: "62", a: false, f: true },
      { id: "63", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "7", a: false, f: true },
      { id: "49", a: false, f: true },
      { id: "61", a: false, f: true },
      { id: "62", a: false, f: true },
      { id: "63", a: false, f: true },
    ],
  },
  78: {
    id: "78",
    name: "St. Petersburg (North Coast)",
    type: "Coast",
    supply: "No",
    countryID: "7",
    coast: "Child",
    coastParentID: "32",
    smallMapX: "448",
    smallMapY: "59",
    Borders: [
      { id: "35", a: false, f: true },
      { id: "51", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "35", a: false, f: true },
      { id: "51", a: false, f: true },
    ],
  },
  79: {
    id: "79",
    name: "St. Petersburg (South Coast)",
    type: "Coast",
    supply: "No",
    countryID: "7",
    coast: "Child",
    coastParentID: "32",
    smallMapX: "398",
    smallMapY: "133",
    Borders: [
      { id: "30", a: false, f: true },
      { id: "33", a: false, f: true },
      { id: "57", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "30", a: false, f: true },
      { id: "33", a: false, f: true },
      { id: "57", a: false, f: true },
    ],
  },
  80: {
    id: "80",
    name: "Bulgaria (North Coast)",
    type: "Coast",
    supply: "No",
    countryID: "0",
    coast: "Child",
    coastParentID: "20",
    smallMapX: "420",
    smallMapY: "304",
    Borders: [
      { id: "21", a: false, f: true },
      { id: "22", a: false, f: true },
      { id: "69", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "21", a: false, f: true },
      { id: "22", a: false, f: true },
      { id: "69", a: false, f: true },
    ],
  },
  81: {
    id: "81",
    name: "Bulgaria (South Coast)",
    type: "Coast",
    supply: "No",
    countryID: "0",
    coast: "Child",
    coastParentID: "20",
    smallMapX: "397",
    smallMapY: "329",
    Borders: [
      { id: "17", a: false, f: true },
      { id: "22", a: false, f: true },
      { id: "67", a: false, f: true },
    ],
    CoastalBorders: [
      { id: "17", a: false, f: true },
      { id: "22", a: false, f: true },
      { id: "67", a: false, f: true },
    ],
  },
};

const units = {
  "845": { id: "845", terrID: "53", countryID: "1", type: "Fleet" },
  "846": { id: "846", terrID: "4", countryID: "1", type: "Army" },
  "847": { id: "847", terrID: "60", countryID: "1", type: "Fleet" },
  "848": { id: "848", terrID: "61", countryID: "2", type: "Fleet" },
  "849": { id: "849", terrID: "46", countryID: "2", type: "Army" },
  "850": { id: "850", terrID: "14", countryID: "2", type: "Army" },
  "851": { id: "851", terrID: "13", countryID: "3", type: "Army" },
  "852": { id: "852", terrID: "16", countryID: "3", type: "Army" },
  "853": { id: "853", terrID: "64", countryID: "3", type: "Fleet" },
  "854": { id: "854", terrID: "55", countryID: "4", type: "Fleet" },
  "855": { id: "855", terrID: "37", countryID: "4", type: "Army" },
  "856": { id: "856", terrID: "38", countryID: "4", type: "Army" },
  "857": { id: "857", terrID: "72", countryID: "5", type: "Army" },
  "858": { id: "858", terrID: "18", countryID: "5", type: "Fleet" },
  "859": { id: "859", terrID: "74", countryID: "5", type: "Army" },
  "860": { id: "860", terrID: "24", countryID: "6", type: "Army" },
  "861": { id: "861", terrID: "69", countryID: "6", type: "Fleet" },
  "862": { id: "862", terrID: "22", countryID: "6", type: "Army" },
  "863": { id: "863", terrID: "31", countryID: "7", type: "Army" },
  "864": { id: "864", terrID: "57", countryID: "7", type: "Fleet" },
  "865": { id: "865", terrID: "29", countryID: "7", type: "Army" },
  "866": { id: "866", terrID: "27", countryID: "7", type: "Fleet" },
};

const terrStatus = [
  {
    id: "1",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: null,
    ownerCountryID: "1",
  },
  {
    id: "2",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: null,
    ownerCountryID: "1",
  },
  {
    id: "3",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: null,
    ownerCountryID: "1",
  },
  {
    id: "4",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: "846",
    ownerCountryID: "1",
  },
  {
    id: "5",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: null,
    ownerCountryID: "1",
  },
  {
    id: "6",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: null,
    ownerCountryID: "1",
  },
  {
    id: "11",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: null,
    ownerCountryID: "3",
  },
  {
    id: "12",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: null,
    ownerCountryID: "3",
  },
  {
    id: "13",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: "851",
    ownerCountryID: "3",
  },
  {
    id: "14",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: "850",
    ownerCountryID: "2",
  },
  {
    id: "15",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: null,
    ownerCountryID: "3",
  },
  {
    id: "16",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: "852",
    ownerCountryID: "3",
  },
  {
    id: "22",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: "862",
    ownerCountryID: "6",
  },
  {
    id: "23",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: null,
    ownerCountryID: "6",
  },
  {
    id: "24",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: "860",
    ownerCountryID: "6",
  },
  {
    id: "25",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: null,
    ownerCountryID: "6",
  },
  {
    id: "26",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: null,
    ownerCountryID: "6",
  },
  {
    id: "27",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: "866",
    ownerCountryID: "7",
  },
  {
    id: "28",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: null,
    ownerCountryID: "7",
  },
  {
    id: "29",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: "865",
    ownerCountryID: "7",
  },
  {
    id: "30",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: null,
    ownerCountryID: "7",
  },
  {
    id: "31",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: "863",
    ownerCountryID: "7",
  },
  {
    id: "32",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: null,
    ownerCountryID: "7",
  },
  {
    id: "33",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: null,
    ownerCountryID: "7",
  },
  {
    id: "37",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: "855",
    ownerCountryID: "4",
  },
  {
    id: "38",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: "856",
    ownerCountryID: "4",
  },
  {
    id: "39",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: null,
    ownerCountryID: "4",
  },
  {
    id: "40",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: null,
    ownerCountryID: "4",
  },
  {
    id: "41",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: null,
    ownerCountryID: "4",
  },
  {
    id: "42",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: null,
    ownerCountryID: "4",
  },
  {
    id: "45",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: null,
    ownerCountryID: "2",
  },
  {
    id: "46",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: "849",
    ownerCountryID: "2",
  },
  {
    id: "47",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: null,
    ownerCountryID: "2",
  },
  {
    id: "48",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: null,
    ownerCountryID: "2",
  },
  {
    id: "49",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: null,
    ownerCountryID: "2",
  },
  {
    id: "50",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: null,
    ownerCountryID: "2",
  },
  {
    id: "70",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: null,
    ownerCountryID: "5",
  },
  {
    id: "71",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: null,
    ownerCountryID: "5",
  },
  {
    id: "72",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: "857",
    ownerCountryID: "5",
  },
  {
    id: "73",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: null,
    ownerCountryID: "5",
  },
  {
    id: "74",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: "859",
    ownerCountryID: "5",
  },
  {
    id: "75",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: null,
    ownerCountryID: "5",
  },
  {
    id: "18",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: "858",
    ownerCountryID: "5",
  },
  {
    id: "64",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: "853",
    ownerCountryID: "3",
  },
  {
    id: "57",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: "864",
    ownerCountryID: "7",
  },
  {
    id: "69",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: "861",
    ownerCountryID: "6",
  },
  {
    id: "55",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: "854",
    ownerCountryID: "4",
  },
  {
    id: "61",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: "848",
    ownerCountryID: "2",
  },
  {
    id: "60",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: "847",
    ownerCountryID: "1",
  },
  {
    id: "53",
    standoff: false,
    occupiedFromTerrID: null,
    unitID: "845",
    ownerCountryID: "1",
  },
];

const context = {
  countryID: "7",
  gameID: 8,
  maxOrderID: "910",
  memberID: 866,
  orderStatus: "",
  phase: "Diplomacy",
  tokenExpireTime: 1645599334,
  turn: 2,
  userID: 10,
  variantID: 1,
};

const ordersData = [
  {
    error: null,
    fixed: ["unitID"],
    fromTerrID: "4",
    id: "892",
    status: "Loading",
    toTerrID: "50",
    type: "Convoy",
    unitID: "848",
    viaConvoy: null,
    countryID: 2,
  },
  {
    error: null,
    fixed: ["unitID"],
    fromTerrID: null,
    id: "893",
    status: "Loading",
    toTerrID: null,
    type: "Hold",
    unitID: "849",
    viaConvoy: null,
    countryID: 2,
  },
  {
    error: null,
    fixed: ["unitID"],
    fromTerrID: null,
    id: "894",
    status: "Loading",
    toTerrID: null,
    type: "Hold",
    unitID: "850",
    viaConvoy: null,
    countryID: 2,
  },
];

export { territories, units, context, terrStatus, ordersData };
