<?php
// This is file installs the map data for the Sengoku5 variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Aki', 'Coast', 'No', 378, 694, 171, 316, 'Neutral'),
	array('Ariake Bay', 'Sea', 'No', 240, 1005, 96, 472, 'Neutral'),
	array('Awa', 'Coast', 'No', 524, 792, 237, 360, 'Neutral'),
	array('Bingo', 'Coast', 'Yes', 437, 691, 200, 308, 'Neutral'),
	array('Bitchu (2)', 'Coast', 'No', 496, 689, 229, 306, 'Neutral'),
	array('Bizen', 'Coast', 'Yes', 553, 661, 251, 301, 'Neutral units'),
	array('Bungo', 'Coast', 'Yes', 268, 812, 120, 368, 'Neutral units'),
	array('Bungo Strait (1)', 'Sea', 'No', 314, 847, 145, 385, 'Neutral'),
	array('Chikuzen', 'Coast', 'No', 183, 740, 84, 333, 'Neutral'),
	array('Dewa', 'Coast', 'No', 1089, 267, 504, 119, 'Neutral'),
	array('East China Sea', 'Sea', 'No', 34, 923, 18, 433, 'Neutral'),
	array('Echigo', 'Coast', 'Yes', 956, 418, 441, 195, 'Uesugi'),
	array('Echizen (7)', 'Coast', 'Yes', 721, 579, 324, 258, 'Asakura'),
	array('Etchu', 'Coast', 'No', 818, 482, 383, 217, 'Neutral'),
	array('Harima', 'Coast', 'No', 605, 675, 279, 308, 'Neutral'),
	array('Hida', 'Land', 'No', 802, 548, 369, 258, 'Neutral'),
	array('Higo', 'Coast', 'Yes', 126, 861, 63, 389, 'Neutral'),
	array('Hitachi', 'Coast', 'Yes', 1119, 485, 523, 221, 'Neutral'),
	array('Hizen', 'Coast', 'Yes', 95, 775, 47, 354, 'Neutral units'),
	array('Hoki', 'Coast', 'No', 518, 588, 237, 266, 'Neutral'),
	array('Hyuga', 'Coast', 'No', 213, 904, 90, 423, 'Neutral'),
	array('Hyuga Coast', 'Sea', 'No', 316, 913, 143, 413, 'Neutral'),
	array('Inaba', 'Coast', 'Yes', 568, 584, 263, 262, 'Neutral'),
	array('Inland Sea', 'Sea', 'No', 365, 737, 211, 324, 'Neutral'),
	array('Ise', 'Coast', 'Yes', 727, 705, 339, 320, 'Neutral'),
	array('Iwami', 'Coast', 'Yes', 356, 618, 162, 279, 'Mori'),
	array('Iwami Coast', 'Sea', 'No', 315, 578, 158, 254, 'Neutral'),
	array('Iyo', 'Coast', 'Yes', 443, 763, 189, 346, 'Chosokabe'),
	array('Izu', 'Coast', 'Yes', 949, 705, 437, 326, 'Hojo'),
	array('Izumo', 'Coast', 'Yes', 423, 591, 212, 268, 'Neutral units'),
	array('Kaga', 'Coast', 'No', 754, 511, 344, 236, 'Neutral'),
	array('Kai', 'Land', 'Yes', 946, 565, 433, 281, 'Takeda'),
	array('Kanmon Strait', 'Sea', 'No', 156, 663, 80, 293, 'Neutral'),
	array('Kawachi (3)', 'Coast', 'No', 618, 712, 285, 328, 'Neutral'),
	array('Kazusa', 'Coast', 'Yes', 1049, 674, 499, 299, 'Neutral'),
	array('Kii', 'Coast', 'Yes', 626, 789, 283, 361, 'Neutral'),
	array('Kii Straits', 'Sea', 'No', 585, 846, 269, 389, 'Neutral'),
	array('Kozuke', 'Land', 'Yes', 1008, 452, 472, 202, 'Uesugi'),
	array('Kumano Sea', 'Sea', 'No', 814, 873, 374, 398, 'Neutral'),
	array('Mikawa', 'Coast', 'Yes', 829, 703, 371, 320, 'Oda'),
	array('Mino', 'Land', 'Yes', 811, 621, 377, 280, 'Neutral units'),
	array('Musashi', 'Land', 'Yes', 1018, 578, 465, 256, 'Neutral units'),
	array('Mutsu', 'Coast', 'Yes', 1216, 208, 555, 88, 'Neutral'),
	array('Nagato', 'Coast', 'Yes', 270, 669, 125, 297, 'Mori'),
	array('North Pacific Ocean', 'Sea', 'No', 1229, 463, 564, 212, 'Neutral'),
	array('North Sea of Japan', 'Sea', 'No', 916, 209, 420, 100, 'Neutral'),
	array('North Shinano', 'Land', 'Yes', 933, 522, 420, 240, 'Neutral'),
	array('Noto (8)', 'Coast', 'Yes', 790, 453, 360, 194, 'Neutral'),
	array('Omi', 'Land', 'Yes', 705, 632, 322, 298, 'Asakura'),
	array('Osaka Bay', 'Sea', 'No', 576, 717, 264, 336, 'Neutral'),
	array('Osumi', 'Coast', 'Yes', 154, 1001, 69, 447, 'Shimazu'),
	array('Owari', 'Coast', 'Yes', 772, 654, 352, 298, 'Oda'),
	array('Pacific Ocean', 'Sea', 'No', 1119, 794, 522, 394, 'Neutral'),
	array('Sagami', 'Coast', 'Yes', 984, 652, 455, 295, 'Hojo'),
	array('Sagami Bay', 'Sea', 'No', 992, 728, 457, 329, 'Neutral'),
	array('Sanin Coast', 'Sea', 'No', 549, 529, 263, 234, 'Neutral'),
	array('Sanuki', 'Coast', 'Yes', 519, 725, 246, 339, 'Neutral'),
	array('Satsuma', 'Coast', 'Yes', 116, 965, 52, 433, 'Shimazu'),
	array('Sea of Japan', 'Sea', 'No', 586, 424, 255, 178, 'Neutral'),
	array('Settsu (4)', 'Coast', 'Yes', 625, 693, 290, 314, 'Neutral'),
	array('Shima', 'Coast', 'No', 712, 753, 342, 333, 'Neutral'),
	array('Shimosa', 'Coast', 'No', 1115, 608, 497, 269, 'Neutral'),
	array('Shimotsuke (11)', 'Land', 'No', 1079, 439, 500, 188, 'Neutral'),
	array('Shuri Straits', 'Sea', 'No', 169, 1081, 31, 480, 'Neutral'),
	array('South Pacific Ocean', 'Sea', 'No', 643, 1015, 261, 456, 'Neutral'),
	array('South Sea of Japan', 'Sea', 'No', 139, 508, 61, 229, 'Neutral'),
	array('South Shinano', 'Land', 'Yes', 875, 620, 403, 281, 'Takeda'),
	array('Suo', 'Coast', 'No', 328, 725, 153, 330, 'Neutral'),
	array('Suo Sea', 'Sea', 'No', 307, 767, 121, 333, 'Neutral'),
	array('Suruga (10)', 'Coast', 'No', 901, 647, 420, 305, 'Neutral'),
	array('Tango', 'Coast', 'No', 638, 594, 290, 266, 'Neutral'),
	array('Tosa', 'Coast', 'Yes', 425, 799, 176, 385, 'Chosokabe'),
	array('Tosa Bay', 'Sea', 'No', 452, 863, 205, 393, 'Neutral'),
	array('Totomi (9)', 'Coast', 'Yes', 881, 707, 410, 318, 'Neutral'),
	array('Totomi Sea', 'Sea', 'No', 811, 754, 372, 344, 'Neutral'),
	array('Toyama Bay', 'Sea', 'No', 874, 415, 394, 195, 'Neutral'),
	array('Tsugaru Strait', 'Sea', 'No', 1049, 31, 490, 13, 'Neutral'),
	array('Tsushima Strait', 'Sea', 'No', 44, 690, 17, 343, 'Neutral'),
	array('Wakasa Bay', 'Sea', 'No', 662, 550, 317, 222, 'Neutral'),
	array('Yamashiro (6)', 'Land', 'Yes', 678, 686, 311, 320, 'Neutral units'),
	array('Yamato (5)', 'Land', 'Yes', 650, 768, 306, 338, 'Neutral')
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $x, $y, $sx, $sy, $country)=$territoryRawRow;
	if( $country=='Neutral' )
		$countryID=0;
	else
		$countryID=$this->countryID($country);
		
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);
$bordersRawData=array(
	array('Aki','Bingo','Yes','Yes'),
	array('Aki','Inland Sea','Yes','No'),
	array('Aki','Iwami','No','Yes'),
	array('Aki','Izumo','No','Yes'),
	array('Aki','Suo','Yes','Yes'),
	array('Ariake Bay','East China Sea','Yes','No'),
	array('Ariake Bay','Hyuga','Yes','No'),
	array('Ariake Bay','Hyuga Coast','Yes','No'),
	array('Ariake Bay','Osumi','Yes','No'),
	array('Ariake Bay','Shuri Straits','Yes','No'),
	array('Ariake Bay','South Pacific Ocean','Yes','No'),
	array('Awa','Iyo','No','Yes'),
	array('Awa','Kii Straits','Yes','No'),
	array('Awa','Osaka Bay','Yes','No'),
	array('Awa','Sanuki','Yes','Yes'),
	array('Awa','Tosa','Yes','Yes'),
	array('Bingo','Aki','Yes','Yes'),
	array('Bingo','Bitchu (2)','Yes','Yes'),
	array('Bingo','Hoki','No','Yes'),
	array('Bingo','Inland Sea','Yes','No'),
	array('Bingo','Izumo','No','Yes'),
	array('Bitchu (2)','Bingo','Yes','Yes'),
	array('Bitchu (2)','Bizen','Yes','Yes'),
	array('Bitchu (2)','Hoki','No','Yes'),
	array('Bitchu (2)','Inland Sea','Yes','No'),
	array('Bitchu (2)','Osaka Bay','Yes','No'),
	array('Bitchu (2)','Sanuki','Yes','Yes'),
	array('Bizen','Bitchu (2)','Yes','Yes'),
	array('Bizen','Harima','Yes','Yes'),
	array('Bizen','Hoki','No','Yes'),
	array('Bizen','Inaba','No','Yes'),
	array('Bizen','Osaka Bay','Yes','No'),
	array('Bizen','Tango','No','Yes'),
	array('Bungo','Bungo Strait (1)','Yes','No'),
	array('Bungo','Chikuzen','Yes','Yes'),
	array('Bungo','Higo','No','Yes'),
	array('Bungo','Hizen','No','Yes'),
	array('Bungo','Hyuga','Yes','Yes'),
	array('Bungo','Hyuga Coast','Yes','No'),
	array('Bungo','Iyo','Yes','Yes'),
	array('Bungo','Suo Sea','Yes','No'),
	array('Bungo Strait (1)','Bungo','Yes','No'),
	array('Bungo Strait (1)','Hyuga','Yes','No'),
	array('Bungo Strait (1)','Hyuga Coast','Yes','No'),
	array('Bungo Strait (1)','Iyo','Yes','No'),
	array('Bungo Strait (1)','Suo Sea','Yes','No'),
	array('Bungo Strait (1)','Tosa','Yes','No'),
	array('Chikuzen','Bungo','Yes','Yes'),
	array('Chikuzen','Hizen','Yes','Yes'),
	array('Chikuzen','Kanmon Strait','Yes','No'),
	array('Chikuzen','Nagato','Yes','Yes'),
	array('Chikuzen','Suo Sea','Yes','No'),
	array('Dewa','Echigo','Yes','Yes'),
	array('Dewa','Kozuke','No','Yes'),
	array('Dewa','Mutsu','Yes','Yes'),
	array('Dewa','North Sea of Japan','Yes','No'),
	array('Dewa','Shimotsuke (11)','No','Yes'),
	array('East China Sea','Ariake Bay','Yes','No'),
	array('East China Sea','Higo','Yes','No'),
	array('East China Sea','Hizen','Yes','No'),
	array('East China Sea','Osumi','Yes','No'),
	array('East China Sea','Satsuma','Yes','No'),
	array('East China Sea','Shuri Straits','Yes','No'),
	array('East China Sea','Tsushima Strait','Yes','No'),
	array('Echigo','Dewa','Yes','Yes'),
	array('Echigo','Etchu','Yes','Yes'),
	array('Echigo','Kozuke','No','Yes'),
	array('Echigo','Musashi','No','Yes'),
	array('Echigo','North Sea of Japan','Yes','No'),
	array('Echigo','North Shinano','No','Yes'),
	array('Echigo','Toyama Bay','Yes','No'),
	array('Echizen (7)','Hida','No','Yes'),
	array('Echizen (7)','Kaga','Yes','Yes'),
	array('Echizen (7)','Mino','No','Yes'),
	array('Echizen (7)','Omi','No','Yes'),
	array('Echizen (7)','Tango','Yes','Yes'),
	array('Echizen (7)','Wakasa Bay','Yes','No'),
	array('Etchu','Echigo','Yes','Yes'),
	array('Etchu','Hida','No','Yes'),
	array('Etchu','Kaga','No','Yes'),
	array('Etchu','North Shinano','No','Yes'),
	array('Etchu','Noto (8)','Yes','Yes'),
	array('Etchu','Toyama Bay','Yes','No'),
	array('Harima','Bizen','Yes','Yes'),
	array('Harima','Omi','No','Yes'),
	array('Harima','Osaka Bay','Yes','No'),
	array('Harima','Settsu (4)','Yes','Yes'),
	array('Harima','Tango','No','Yes'),
	array('Harima','Yamashiro (6)','No','Yes'),
	array('Hida','Echizen (7)','No','Yes'),
	array('Hida','Etchu','No','Yes'),
	array('Hida','Kaga','No','Yes'),
	array('Hida','Mino','No','Yes'),
	array('Hida','North Shinano','No','Yes'),
	array('Hida','South Shinano','No','Yes'),
	array('Higo','Bungo','No','Yes'),
	array('Higo','East China Sea','Yes','No'),
	array('Higo','Hizen','Yes','Yes'),
	array('Higo','Hyuga','No','Yes'),
	array('Higo','Satsuma','Yes','Yes'),
	array('Hitachi','Musashi','No','Yes'),
	array('Hitachi','Mutsu','Yes','Yes'),
	array('Hitachi','North Pacific Ocean','Yes','No'),
	array('Hitachi','Shimosa','Yes','Yes'),
	array('Hitachi','Shimotsuke (11)','No','Yes'),
	array('Hizen','Bungo','No','Yes'),
	array('Hizen','Chikuzen','Yes','Yes'),
	array('Hizen','East China Sea','Yes','No'),
	array('Hizen','Higo','Yes','Yes'),
	array('Hizen','Kanmon Strait','Yes','No'),
	array('Hizen','Tsushima Strait','Yes','No'),
	array('Hoki','Bingo','No','Yes'),
	array('Hoki','Bitchu (2)','No','Yes'),
	array('Hoki','Bizen','No','Yes'),
	array('Hoki','Inaba','Yes','Yes'),
	array('Hoki','Izumo','Yes','Yes'),
	array('Hoki','Sanin Coast','Yes','No'),
	array('Hyuga','Ariake Bay','Yes','No'),
	array('Hyuga','Bungo','Yes','Yes'),
	array('Hyuga','Bungo Strait (1)','Yes','No'),
	array('Hyuga','Higo','No','Yes'),
	array('Hyuga','Hyuga Coast','Yes','No'),
	array('Hyuga','Osumi','Yes','Yes'),
	array('Hyuga','Satsuma','No','Yes'),
	array('Hyuga Coast','Ariake Bay','Yes','No'),
	array('Hyuga Coast','Bungo','Yes','No'),
	array('Hyuga Coast','Bungo Strait (1)','Yes','No'),
	array('Hyuga Coast','Hyuga','Yes','No'),
	array('Hyuga Coast','South Pacific Ocean','Yes','No'),
	array('Hyuga Coast','Tosa','Yes','No'),
	array('Hyuga Coast','Tosa Bay','Yes','No'),
	array('Inaba','Bizen','No','Yes'),
	array('Inaba','Hoki','Yes','Yes'),
	array('Inaba','Sanin Coast','Yes','No'),
	array('Inaba','Tango','Yes','Yes'),
	array('Inland Sea','Aki','Yes','No'),
	array('Inland Sea','Bingo','Yes','No'),
	array('Inland Sea','Bitchu (2)','Yes','No'),
	array('Inland Sea','Iyo','Yes','No'),
	array('Inland Sea','Osaka Bay','Yes','No'),
	array('Inland Sea','Sanuki','Yes','No'),
	array('Inland Sea','Suo','Yes','No'),
	array('Inland Sea','Suo Sea','Yes','No'),
	array('Ise','Mino','No','Yes'),
	array('Ise','Omi','No','Yes'),
	array('Ise','Owari','Yes','Yes'),
	array('Ise','Shima','Yes','Yes'),
	array('Ise','Totomi Sea','Yes','No'),
	array('Ise','Yamashiro (6)','No','Yes'),
	array('Ise','Yamato (5)','No','Yes'),
	array('Iwami','Aki','No','Yes'),
	array('Iwami','Iwami Coast','Yes','No'),
	array('Iwami','Izumo','Yes','Yes'),
	array('Iwami','Nagato','Yes','Yes'),
	array('Iwami','Suo','No','Yes'),
	array('Iwami Coast','Iwami','Yes','No'),
	array('Iwami Coast','Izumo','Yes','No'),
	array('Iwami Coast','Kanmon Strait','Yes','No'),
	array('Iwami Coast','Nagato','Yes','No'),
	array('Iwami Coast','Sanin Coast','Yes','No'),
	array('Iwami Coast','Sea of Japan','Yes','No'),
	array('Iwami Coast','South Sea of Japan','Yes','No'),
	array('Iyo','Awa','No','Yes'),
	array('Iyo','Bungo','Yes','Yes'),
	array('Iyo','Bungo Strait (1)','Yes','No'),
	array('Iyo','Inland Sea','Yes','No'),
	array('Iyo','Sanuki','Yes','Yes'),
	array('Iyo','Suo Sea','Yes','No'),
	array('Iyo','Tosa','Yes','Yes'),
	array('Izu','Sagami','Yes','Yes'),
	array('Izu','Sagami Bay','Yes','No'),
	array('Izu','Suruga (10)','Yes','Yes'),
	array('Izumo','Aki','No','Yes'),
	array('Izumo','Bingo','No','Yes'),
	array('Izumo','Hoki','Yes','Yes'),
	array('Izumo','Iwami','Yes','Yes'),
	array('Izumo','Iwami Coast','Yes','No'),
	array('Izumo','Sanin Coast','Yes','No'),
	array('Kaga','Echizen (7)','Yes','Yes'),
	array('Kaga','Etchu','No','Yes'),
	array('Kaga','Hida','No','Yes'),
	array('Kaga','Noto (8)','Yes','Yes'),
	array('Kaga','Wakasa Bay','Yes','No'),
	array('Kai','Musashi','No','Yes'),
	array('Kai','North Shinano','No','Yes'),
	array('Kai','Sagami','No','Yes'),
	array('Kai','South Shinano','No','Yes'),
	array('Kai','Suruga (10)','No','Yes'),
	array('Kanmon Strait','Chikuzen','Yes','No'),
	array('Kanmon Strait','Hizen','Yes','No'),
	array('Kanmon Strait','Iwami Coast','Yes','No'),
	array('Kanmon Strait','Nagato','Yes','No'),
	array('Kanmon Strait','South Sea of Japan','Yes','No'),
	array('Kanmon Strait','Suo Sea','Yes','No'),
	array('Kanmon Strait','Tsushima Strait','Yes','No'),
	array('Kawachi (3)','Kii','Yes','Yes'),
	array('Kawachi (3)','Osaka Bay','Yes','No'),
	array('Kawachi (3)','Settsu (4)','Yes','Yes'),
	array('Kawachi (3)','Yamashiro (6)','No','Yes'),
	array('Kawachi (3)','Yamato (5)','No','Yes'),
	array('Kazusa','North Pacific Ocean','Yes','No'),
	array('Kazusa','Pacific Ocean','Yes','No'),
	array('Kazusa','Sagami','Yes','Yes'),
	array('Kazusa','Sagami Bay','Yes','No'),
	array('Kazusa','Shimosa','Yes','Yes'),
	array('Kii','Kawachi (3)','Yes','Yes'),
	array('Kii','Kii Straits','Yes','No'),
	array('Kii','Kumano Sea','Yes','No'),
	array('Kii','Osaka Bay','Yes','No'),
	array('Kii','Shima','Yes','Yes'),
	array('Kii','Totomi Sea','Yes','No'),
	array('Kii','Yamato (5)','No','Yes'),
	array('Kii Straits','Awa','Yes','No'),
	array('Kii Straits','Kii','Yes','No'),
	array('Kii Straits','Kumano Sea','Yes','No'),
	array('Kii Straits','Osaka Bay','Yes','No'),
	array('Kii Straits','South Pacific Ocean','Yes','No'),
	array('Kii Straits','Tosa','Yes','No'),
	array('Kii Straits','Tosa Bay','Yes','No'),
	array('Kozuke','Dewa','No','Yes'),
	array('Kozuke','Echigo','No','Yes'),
	array('Kozuke','Musashi','No','Yes'),
	array('Kozuke','Shimotsuke (11)','No','Yes'),
	array('Kumano Sea','Kii','Yes','No'),
	array('Kumano Sea','Kii Straits','Yes','No'),
	array('Kumano Sea','Pacific Ocean','Yes','No'),
	array('Kumano Sea','Sagami Bay','Yes','No'),
	array('Kumano Sea','South Pacific Ocean','Yes','No'),
	array('Kumano Sea','Totomi Sea','Yes','No'),
	array('Mikawa','Mino','No','Yes'),
	array('Mikawa','Owari','Yes','Yes'),
	array('Mikawa','Shima','No','Yes'),
	array('Mikawa','Totomi (9)','Yes','Yes'),
	array('Mikawa','Totomi Sea','Yes','No'),
	array('Mino','Echizen (7)','No','Yes'),
	array('Mino','Hida','No','Yes'),
	array('Mino','Ise','No','Yes'),
	array('Mino','Mikawa','No','Yes'),
	array('Mino','Omi','No','Yes'),
	array('Mino','Owari','No','Yes'),
	array('Mino','South Shinano','No','Yes'),
	array('Mino','Totomi (9)','No','Yes'),
	array('Musashi','Echigo','No','Yes'),
	array('Musashi','Hitachi','No','Yes'),
	array('Musashi','Kai','No','Yes'),
	array('Musashi','Kozuke','No','Yes'),
	array('Musashi','North Shinano','No','Yes'),
	array('Musashi','Sagami','No','Yes'),
	array('Musashi','Shimosa','No','Yes'),
	array('Musashi','Shimotsuke (11)','No','Yes'),
	array('Mutsu','Dewa','Yes','Yes'),
	array('Mutsu','Hitachi','Yes','Yes'),
	array('Mutsu','North Pacific Ocean','Yes','No'),
	array('Mutsu','North Sea of Japan','Yes','No'),
	array('Mutsu','Shimotsuke (11)','No','Yes'),
	array('Mutsu','Tsugaru Strait','Yes','No'),
	array('Nagato','Chikuzen','Yes','Yes'),
	array('Nagato','Iwami','Yes','Yes'),
	array('Nagato','Iwami Coast','Yes','No'),
	array('Nagato','Kanmon Strait','Yes','No'),
	array('Nagato','Suo','Yes','Yes'),
	array('Nagato','Suo Sea','Yes','No'),
	array('North Pacific Ocean','Hitachi','Yes','No'),
	array('North Pacific Ocean','Kazusa','Yes','No'),
	array('North Pacific Ocean','Mutsu','Yes','No'),
	array('North Pacific Ocean','Pacific Ocean','Yes','No'),
	array('North Pacific Ocean','Shimosa','Yes','No'),
	array('North Pacific Ocean','Tsugaru Strait','Yes','No'),
	array('North Sea of Japan','Dewa','Yes','No'),
	array('North Sea of Japan','Echigo','Yes','No'),
	array('North Sea of Japan','Mutsu','Yes','No'),
	array('North Sea of Japan','Noto (8)','Yes','No'),
	array('North Sea of Japan','Sea of Japan','Yes','No'),
	array('North Sea of Japan','Toyama Bay','Yes','No'),
	array('North Sea of Japan','Tsugaru Strait','Yes','No'),
	array('North Shinano','Echigo','No','Yes'),
	array('North Shinano','Etchu','No','Yes'),
	array('North Shinano','Hida','No','Yes'),
	array('North Shinano','Kai','No','Yes'),
	array('North Shinano','Musashi','No','Yes'),
	array('North Shinano','South Shinano','No','Yes'),
	array('Noto (8)','Etchu','Yes','Yes'),
	array('Noto (8)','Kaga','Yes','Yes'),
	array('Noto (8)','North Sea of Japan','Yes','No'),
	array('Noto (8)','Sea of Japan','Yes','No'),
	array('Noto (8)','Toyama Bay','Yes','No'),
	array('Noto (8)','Wakasa Bay','Yes','No'),
	array('Omi','Echizen (7)','No','Yes'),
	array('Omi','Harima','No','Yes'),
	array('Omi','Ise','No','Yes'),
	array('Omi','Mino','No','Yes'),
	array('Omi','Tango','No','Yes'),
	array('Omi','Yamashiro (6)','No','Yes'),
	array('Osaka Bay','Awa','Yes','No'),
	array('Osaka Bay','Bitchu (2)','Yes','No'),
	array('Osaka Bay','Bizen','Yes','No'),
	array('Osaka Bay','Harima','Yes','No'),
	array('Osaka Bay','Inland Sea','Yes','No'),
	array('Osaka Bay','Kawachi (3)','Yes','No'),
	array('Osaka Bay','Kii','Yes','No'),
	array('Osaka Bay','Kii Straits','Yes','No'),
	array('Osaka Bay','Sanuki','Yes','No'),
	array('Osaka Bay','Settsu (4)','Yes','No'),
	array('Osumi','Ariake Bay','Yes','No'),
	array('Osumi','East China Sea','Yes','No'),
	array('Osumi','Hyuga','Yes','Yes'),
	array('Osumi','Satsuma','Yes','Yes'),
	array('Owari','Ise','Yes','Yes'),
	array('Owari','Mikawa','Yes','Yes'),
	array('Owari','Mino','No','Yes'),
	array('Owari','Totomi Sea','Yes','No'),
	array('Pacific Ocean','Kazusa','Yes','No'),
	array('Pacific Ocean','Kumano Sea','Yes','No'),
	array('Pacific Ocean','North Pacific Ocean','Yes','No'),
	array('Pacific Ocean','Sagami Bay','Yes','No'),
	array('Pacific Ocean','South Pacific Ocean','Yes','No'),
	array('Sagami','Izu','Yes','Yes'),
	array('Sagami','Kai','No','Yes'),
	array('Sagami','Kazusa','Yes','Yes'),
	array('Sagami','Musashi','No','Yes'),
	array('Sagami','Sagami Bay','Yes','No'),
	array('Sagami','Shimosa','No','Yes'),
	array('Sagami','Suruga (10)','No','Yes'),
	array('Sagami Bay','Izu','Yes','No'),
	array('Sagami Bay','Kazusa','Yes','No'),
	array('Sagami Bay','Kumano Sea','Yes','No'),
	array('Sagami Bay','Pacific Ocean','Yes','No'),
	array('Sagami Bay','Sagami','Yes','No'),
	array('Sagami Bay','Suruga (10)','Yes','No'),
	array('Sagami Bay','Totomi (9)','Yes','No'),
	array('Sagami Bay','Totomi Sea','Yes','No'),
	array('Sanin Coast','Hoki','Yes','No'),
	array('Sanin Coast','Inaba','Yes','No'),
	array('Sanin Coast','Iwami Coast','Yes','No'),
	array('Sanin Coast','Izumo','Yes','No'),
	array('Sanin Coast','Sea of Japan','Yes','No'),
	array('Sanin Coast','Tango','Yes','No'),
	array('Sanin Coast','Wakasa Bay','Yes','No'),
	array('Sanuki','Awa','Yes','Yes'),
	array('Sanuki','Bitchu (2)','Yes','Yes'),
	array('Sanuki','Inland Sea','Yes','No'),
	array('Sanuki','Iyo','Yes','Yes'),
	array('Sanuki','Osaka Bay','Yes','No'),
	array('Satsuma','East China Sea','Yes','No'),
	array('Satsuma','Higo','Yes','Yes'),
	array('Satsuma','Hyuga','No','Yes'),
	array('Satsuma','Osumi','Yes','Yes'),
	array('Sea of Japan','Iwami Coast','Yes','No'),
	array('Sea of Japan','North Sea of Japan','Yes','No'),
	array('Sea of Japan','Noto (8)','Yes','No'),
	array('Sea of Japan','Sanin Coast','Yes','No'),
	array('Sea of Japan','South Sea of Japan','Yes','No'),
	array('Sea of Japan','Wakasa Bay','Yes','No'),
	array('Settsu (4)','Harima','Yes','Yes'),
	array('Settsu (4)','Kawachi (3)','Yes','Yes'),
	array('Settsu (4)','Osaka Bay','Yes','No'),
	array('Settsu (4)','Yamashiro (6)','No','Yes'),
	array('Shima','Ise','Yes','Yes'),
	array('Shima','Kii','Yes','Yes'),
	array('Shima','Mikawa','No','Yes'),
	array('Shima','Totomi Sea','Yes','No'),
	array('Shima','Yamato (5)','No','Yes'),
	array('Shimosa','Hitachi','Yes','Yes'),
	array('Shimosa','Kazusa','Yes','Yes'),
	array('Shimosa','Musashi','No','Yes'),
	array('Shimosa','North Pacific Ocean','Yes','No'),
	array('Shimosa','Sagami','No','Yes'),
	array('Shimotsuke (11)','Dewa','No','Yes'),
	array('Shimotsuke (11)','Hitachi','No','Yes'),
	array('Shimotsuke (11)','Kozuke','No','Yes'),
	array('Shimotsuke (11)','Musashi','No','Yes'),
	array('Shimotsuke (11)','Mutsu','No','Yes'),
	array('Shuri Straits','Ariake Bay','Yes','No'),
	array('Shuri Straits','East China Sea','Yes','No'),
	array('Shuri Straits','South Pacific Ocean','Yes','No'),
	array('South Pacific Ocean','Ariake Bay','Yes','No'),
	array('South Pacific Ocean','Hyuga Coast','Yes','No'),
	array('South Pacific Ocean','Kii Straits','Yes','No'),
	array('South Pacific Ocean','Kumano Sea','Yes','No'),
	array('South Pacific Ocean','Pacific Ocean','Yes','No'),
	array('South Pacific Ocean','Shuri Straits','Yes','No'),
	array('South Pacific Ocean','Tosa Bay','Yes','No'),
	array('South Sea of Japan','Iwami Coast','Yes','No'),
	array('South Sea of Japan','Kanmon Strait','Yes','No'),
	array('South Sea of Japan','Sea of Japan','Yes','No'),
	array('South Sea of Japan','Tsushima Strait','Yes','No'),
	array('South Shinano','Hida','No','Yes'),
	array('South Shinano','Kai','No','Yes'),
	array('South Shinano','Mino','No','Yes'),
	array('South Shinano','North Shinano','No','Yes'),
	array('South Shinano','Suruga (10)','No','Yes'),
	array('South Shinano','Totomi (9)','No','Yes'),
	array('Suo','Aki','Yes','Yes'),
	array('Suo','Inland Sea','Yes','No'),
	array('Suo','Iwami','No','Yes'),
	array('Suo','Nagato','Yes','Yes'),
	array('Suo','Suo Sea','Yes','No'),
	array('Suo Sea','Bungo','Yes','No'),
	array('Suo Sea','Bungo Strait (1)','Yes','No'),
	array('Suo Sea','Chikuzen','Yes','No'),
	array('Suo Sea','Inland Sea','Yes','No'),
	array('Suo Sea','Iyo','Yes','No'),
	array('Suo Sea','Kanmon Strait','Yes','No'),
	array('Suo Sea','Nagato','Yes','No'),
	array('Suo Sea','Suo','Yes','No'),
	array('Suruga (10)','Izu','Yes','Yes'),
	array('Suruga (10)','Kai','No','Yes'),
	array('Suruga (10)','Sagami','No','Yes'),
	array('Suruga (10)','Sagami Bay','Yes','No'),
	array('Suruga (10)','South Shinano','No','Yes'),
	array('Suruga (10)','Totomi (9)','Yes','Yes'),
	array('Tango','Bizen','No','Yes'),
	array('Tango','Echizen (7)','Yes','Yes'),
	array('Tango','Harima','No','Yes'),
	array('Tango','Inaba','Yes','Yes'),
	array('Tango','Omi','No','Yes'),
	array('Tango','Sanin Coast','Yes','No'),
	array('Tango','Wakasa Bay','Yes','No'),
	array('Tosa','Awa','Yes','Yes'),
	array('Tosa','Bungo Strait (1)','Yes','No'),
	array('Tosa','Hyuga Coast','Yes','No'),
	array('Tosa','Iyo','Yes','Yes'),
	array('Tosa','Kii Straits','Yes','No'),
	array('Tosa','Tosa Bay','Yes','No'),
	array('Tosa Bay','Hyuga Coast','Yes','No'),
	array('Tosa Bay','Kii Straits','Yes','No'),
	array('Tosa Bay','South Pacific Ocean','Yes','No'),
	array('Tosa Bay','Tosa','Yes','No'),
	array('Totomi (9)','Mikawa','Yes','Yes'),
	array('Totomi (9)','Mino','No','Yes'),
	array('Totomi (9)','Sagami Bay','Yes','No'),
	array('Totomi (9)','South Shinano','No','Yes'),
	array('Totomi (9)','Suruga (10)','Yes','Yes'),
	array('Totomi (9)','Totomi Sea','Yes','No'),
	array('Totomi Sea','Ise','Yes','No'),
	array('Totomi Sea','Kii','Yes','No'),
	array('Totomi Sea','Kumano Sea','Yes','No'),
	array('Totomi Sea','Mikawa','Yes','No'),
	array('Totomi Sea','Owari','Yes','No'),
	array('Totomi Sea','Sagami Bay','Yes','No'),
	array('Totomi Sea','Shima','Yes','No'),
	array('Totomi Sea','Totomi (9)','Yes','No'),
	array('Toyama Bay','Echigo','Yes','No'),
	array('Toyama Bay','Etchu','Yes','No'),
	array('Toyama Bay','North Sea of Japan','Yes','No'),
	array('Toyama Bay','Noto (8)','Yes','No'),
	array('Tsugaru Strait','Mutsu','Yes','No'),
	array('Tsugaru Strait','North Pacific Ocean','Yes','No'),
	array('Tsugaru Strait','North Sea of Japan','Yes','No'),
	array('Tsushima Strait','East China Sea','Yes','No'),
	array('Tsushima Strait','Hizen','Yes','No'),
	array('Tsushima Strait','Kanmon Strait','Yes','No'),
	array('Tsushima Strait','South Sea of Japan','Yes','No'),
	array('Wakasa Bay','Echizen (7)','Yes','No'),
	array('Wakasa Bay','Kaga','Yes','No'),
	array('Wakasa Bay','Noto (8)','Yes','No'),
	array('Wakasa Bay','Sanin Coast','Yes','No'),
	array('Wakasa Bay','Sea of Japan','Yes','No'),
	array('Wakasa Bay','Tango','Yes','No'),
	array('Yamashiro (6)','Harima','No','Yes'),
	array('Yamashiro (6)','Ise','No','Yes'),
	array('Yamashiro (6)','Kawachi (3)','No','Yes'),
	array('Yamashiro (6)','Omi','No','Yes'),
	array('Yamashiro (6)','Settsu (4)','No','Yes'),
	array('Yamashiro (6)','Yamato (5)','No','Yes'),
	array('Yamato (5)','Ise','No','Yes'),
	array('Yamato (5)','Kawachi (3)','No','Yes'),
	array('Yamato (5)','Kii','No','Yes'),
	array('Yamato (5)','Shima','No','Yes'),
	array('Yamato (5)','Yamashiro (6)','No','Yes')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
