<?php
// This is file installs the map data for the Sengoku5 variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Aki', 'Coast', 'No', 0, 378, 694, 171, 316),
	array('Ariake Bay', 'Sea', 'No', 0, 240, 1005, 96, 472),
	array('Awa', 'Coast', 'No', 0, 524, 792, 237, 360),
	array('Bingo', 'Coast', 'Yes', 0, 437, 691, 200, 308),
	array('Bitchu (2)', 'Coast', 'No', 0, 496, 689, 229, 306),
	array('Bizen', 'Coast', 'Yes', 9, 553, 661, 251, 301),
	array('Bungo', 'Coast', 'Yes', 9, 268, 812, 120, 368),
	array('Bungo Strait (1)', 'Sea', 'No', 0, 314, 847, 145, 385),
	array('Chikuzen', 'Coast', 'No', 0, 183, 740, 84, 333),
	array('Dewa', 'Coast', 'No', 0, 1089, 267, 504, 119),
	array('East China Sea', 'Sea', 'No', 0, 34, 923, 18, 433),
	array('Echigo', 'Coast', 'Yes', 6, 956, 418, 441, 195),
	array('Echizen (7)', 'Coast', 'Yes', 4, 721, 579, 324, 258),
	array('Etchu', 'Coast', 'No', 0, 818, 482, 383, 217),
	array('Harima', 'Coast', 'No', 0, 605, 675, 279, 308),
	array('Hida', 'Land', 'No', 0, 802, 548, 369, 258),
	array('Higo', 'Coast', 'Yes', 0, 126, 861, 63, 389),
	array('Hitachi', 'Coast', 'Yes', 0, 1119, 485, 523, 221),
	array('Hizen', 'Coast', 'Yes', 9, 95, 775, 47, 354),
	array('Hoki', 'Coast', 'No', 0, 518, 588, 237, 266),
	array('Hyuga', 'Coast', 'No', 0, 213, 904, 90, 423),
	array('Hyuga Coast', 'Sea', 'No', 0, 316, 913, 143, 413),
	array('Inaba', 'Coast', 'Yes', 0, 568, 584, 263, 262),
	array('Inland Sea', 'Sea', 'No', 0, 365, 737, 211, 324),
	array('Ise', 'Coast', 'Yes', 0, 727, 705, 339, 320),
	array('Iwami', 'Coast', 'Yes', 2, 356, 618, 162, 279),
	array('Iwami Coast', 'Sea', 'No', 0, 315, 578, 158, 254),
	array('Iyo', 'Coast', 'Yes', 3, 443, 763, 189, 346),
	array('Izu', 'Coast', 'Yes', 8, 949, 705, 437, 326),
	array('Izumo', 'Coast', 'Yes', 9, 423, 591, 212, 268),
	array('Kaga', 'Coast', 'No', 0, 754, 511, 344, 236),
	array('Kai', 'Land', 'Yes', 7, 946, 565, 433, 281),
	array('Kanmon Strait', 'Sea', 'No', 0, 156, 663, 80, 293),
	array('Kawachi (3)', 'Coast', 'No', 0, 618, 712, 285, 328),
	array('Kazusa', 'Coast', 'Yes', 0, 1049, 674, 499, 299),
	array('Kii', 'Coast', 'Yes', 0, 626, 789, 283, 361),
	array('Kii Straits', 'Sea', 'No', 0, 585, 846, 269, 389),
	array('Kozuke', 'Land', 'Yes', 6, 1008, 452, 472, 202),
	array('Kumano Sea', 'Sea', 'No', 0, 814, 873, 374, 398),
	array('Mikawa', 'Coast', 'Yes', 5, 829, 703, 371, 320),
	array('Mino', 'Land', 'Yes', 9, 811, 621, 377, 280),
	array('Musashi', 'Land', 'Yes', 9, 1018, 578, 465, 256),
	array('Mutsu', 'Coast', 'Yes', 0, 1216, 208, 555, 88),
	array('Nagato', 'Coast', 'Yes', 2, 270, 669, 125, 297),
	array('North Pacific Ocean', 'Sea', 'No', 0, 1229, 463, 564, 212),
	array('North Sea of Japan', 'Sea', 'No', 0, 916, 209, 420, 100),
	array('North Shinano', 'Land', 'Yes', 0, 933, 522, 420, 240),
	array('Noto (8)', 'Coast', 'Yes', 0, 790, 453, 360, 194),
	array('Omi', 'Land', 'Yes', 4, 705, 632, 322, 298),
	array('Osaka Bay', 'Sea', 'No', 0, 576, 717, 264, 336),
	array('Osumi', 'Coast', 'Yes', 1, 154, 1001, 69, 447),
	array('Owari', 'Coast', 'Yes', 5, 772, 654, 352, 298),
	array('Pacific Ocean', 'Sea', 'No', 0, 1119, 794, 522, 394),
	array('Sagami', 'Coast', 'Yes', 8, 984, 652, 455, 295),
	array('Sagami Bay', 'Sea', 'No', 0, 992, 728, 457, 329),
	array('Sanin Coast', 'Sea', 'No', 0, 549, 529, 263, 234),
	array('Sanuki', 'Coast', 'Yes', 0, 519, 725, 246, 339),
	array('Satsuma', 'Coast', 'Yes', 1, 116, 965, 52, 433),
	array('Sea of Japan', 'Sea', 'No', 0, 586, 424, 255, 178),
	array('Settsu (4)', 'Coast', 'Yes', 0, 625, 693, 290, 314),
	array('Shima', 'Coast', 'No', 0, 712, 753, 342, 333),
	array('Shimosa', 'Coast', 'No', 0, 1115, 608, 497, 269),
	array('Shimotsuke (11)', 'Land', 'No', 0, 1079, 439, 500, 188),
	array('Shuri Straits', 'Sea', 'No', 0, 169, 1081, 31, 480),
	array('South Pacific Ocean', 'Sea', 'No', 0, 643, 1015, 261, 456),
	array('South Sea of Japan', 'Sea', 'No', 0, 139, 508, 61, 229),
	array('South Shinano', 'Land', 'Yes', 7, 875, 620, 403, 281),
	array('Suo', 'Coast', 'No', 0, 328, 725, 153, 330),
	array('Suo Sea', 'Sea', 'No', 0, 307, 767, 121, 333),
	array('Suruga (10)', 'Coast', 'No', 0, 901, 647, 420, 305),
	array('Tango', 'Coast', 'No', 0, 638, 594, 290, 266),
	array('Tosa', 'Coast', 'Yes', 3, 425, 799, 176, 385),
	array('Tosa Bay', 'Sea', 'No', 0, 452, 863, 205, 393),
	array('Totomi (9)', 'Coast', 'Yes', 0, 881, 707, 410, 318),
	array('Totomi Sea', 'Sea', 'No', 0, 811, 754, 372, 344),
	array('Toyama Bay', 'Sea', 'No', 0, 874, 415, 394, 195),
	array('Tsugaru Strait', 'Sea', 'No', 0, 1049, 31, 490, 13),
	array('Tsushima Strait', 'Sea', 'No', 0, 44, 690, 17, 343),
	array('Wakasa Bay', 'Sea', 'No', 0, 662, 550, 317, 222),
	array('Yamashiro (6)', 'Land', 'Yes', 9, 678, 686, 311, 320),
	array('Yamato (5)', 'Land', 'Yes', 0, 650, 768, 306, 338)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Aki','Bingo','Yes','Yes'),
	array('Aki','Inland Sea','Yes','No'),
	array('Aki','Iwami','No','Yes'),
	array('Aki','Izumo','No','Yes'),
	array('Aki','Suo','Yes','Yes'),
	array('Ariake Bay','East China Sea','Yes','No'),
	array('Ariake Bay','Hyuga','Yes','No'),
	array('Ariake Bay','Hyuga Coast','Yes','No'),
	array('Ariake Bay','Osumi','Yes','No'),
	array('Ariake Bay','Shuri Straits','Yes','No'),
	array('Ariake Bay','South Pacific Ocean','Yes','No'),
	array('Awa','Iyo','No','Yes'),
	array('Awa','Kii Straits','Yes','No'),
	array('Awa','Osaka Bay','Yes','No'),
	array('Awa','Sanuki','Yes','Yes'),
	array('Awa','Tosa','Yes','Yes'),
	array('Bingo','Bitchu (2)','Yes','Yes'),
	array('Bingo','Hoki','No','Yes'),
	array('Bingo','Inland Sea','Yes','No'),
	array('Bingo','Izumo','No','Yes'),
	array('Bitchu (2)','Bizen','Yes','Yes'),
	array('Bitchu (2)','Hoki','No','Yes'),
	array('Bitchu (2)','Inland Sea','Yes','No'),
	array('Bitchu (2)','Osaka Bay','Yes','No'),
	array('Bitchu (2)','Sanuki','Yes','Yes'),
	array('Bizen','Harima','Yes','Yes'),
	array('Bizen','Hoki','No','Yes'),
	array('Bizen','Inaba','No','Yes'),
	array('Bizen','Osaka Bay','Yes','No'),
	array('Bizen','Tango','No','Yes'),
	array('Bungo','Bungo Strait (1)','Yes','No'),
	array('Bungo','Chikuzen','Yes','Yes'),
	array('Bungo','Higo','No','Yes'),
	array('Bungo','Hizen','No','Yes'),
	array('Bungo','Hyuga','Yes','Yes'),
	array('Bungo','Iyo','Yes','Yes'),
	array('Bungo','Suo Sea','Yes','No'),
	array('Bungo Strait (1)','Hyuga','Yes','No'),
	array('Bungo Strait (1)','Hyuga Coast','Yes','No'),
	array('Bungo Strait (1)','Iyo','Yes','No'),
	array('Bungo Strait (1)','Suo Sea','Yes','No'),
	array('Bungo Strait (1)','Tosa','Yes','No'),
	array('Chikuzen','Hizen','Yes','Yes'),
	array('Chikuzen','Kanmon Strait','Yes','No'),
	array('Chikuzen','Nagato','Yes','Yes'),
	array('Chikuzen','Suo Sea','Yes','No'),
	array('Dewa','Echigo','Yes','Yes'),
	array('Dewa','Kozuke','No','Yes'),
	array('Dewa','Mutsu','Yes','Yes'),
	array('Dewa','North Sea of Japan','Yes','No'),
	array('Dewa','Shimotsuke (11)','No','Yes'),
	array('East China Sea','Higo','Yes','No'),
	array('East China Sea','Hizen','Yes','No'),
	array('East China Sea','Osumi','Yes','No'),
	array('East China Sea','Satsuma','Yes','No'),
	array('East China Sea','Shuri Straits','Yes','No'),
	array('East China Sea','Tsushima Strait','Yes','No'),
	array('Echigo','Etchu','Yes','Yes'),
	array('Echigo','Kozuke','No','Yes'),
	array('Echigo','Musashi','No','Yes'),
	array('Echigo','North Sea of Japan','Yes','No'),
	array('Echigo','North Shinano','No','Yes'),
	array('Echigo','Toyama Bay','Yes','No'),
	array('Echizen (7)','Hida','No','Yes'),
	array('Echizen (7)','Kaga','Yes','Yes'),
	array('Echizen (7)','Mino','No','Yes'),
	array('Echizen (7)','Omi','No','Yes'),
	array('Echizen (7)','Tango','Yes','Yes'),
	array('Echizen (7)','Wakasa Bay','Yes','No'),
	array('Etchu','Hida','No','Yes'),
	array('Etchu','Kaga','No','Yes'),
	array('Etchu','North Shinano','No','Yes'),
	array('Etchu','Noto (8)','Yes','Yes'),
	array('Etchu','Toyama Bay','Yes','No'),
	array('Harima','Omi','No','Yes'),
	array('Harima','Osaka Bay','Yes','No'),
	array('Harima','Settsu (4)','Yes','Yes'),
	array('Harima','Tango','No','Yes'),
	array('Harima','Yamashiro (6)','No','Yes'),
	array('Hida','Kaga','No','Yes'),
	array('Hida','Mino','No','Yes'),
	array('Hida','North Shinano','No','Yes'),
	array('Hida','South Shinano','No','Yes'),
	array('Higo','Hizen','Yes','Yes'),
	array('Higo','Hyuga','No','Yes'),
	array('Higo','Satsuma','Yes','Yes'),
	array('Hitachi','Musashi','No','Yes'),
	array('Hitachi','Mutsu','Yes','Yes'),
	array('Hitachi','North Pacific Ocean','Yes','No'),
	array('Hitachi','Shimosa','Yes','Yes'),
	array('Hitachi','Shimotsuke (11)','No','Yes'),
	array('Hizen','Kanmon Strait','Yes','No'),
	array('Hizen','Tsushima Strait','Yes','No'),
	array('Hoki','Inaba','Yes','Yes'),
	array('Hoki','Izumo','Yes','Yes'),
	array('Hoki','Sanin Coast','Yes','No'),
	array('Hyuga','Hyuga Coast','Yes','No'),
	array('Hyuga','Osumi','Yes','Yes'),
	array('Hyuga','Satsuma','No','Yes'),
	array('Hyuga Coast','South Pacific Ocean','Yes','No'),
	array('Hyuga Coast','Tosa','Yes','No'),
	array('Hyuga Coast','Tosa Bay','Yes','No'),
	array('Inaba','Sanin Coast','Yes','No'),
	array('Inaba','Tango','Yes','Yes'),
	array('Inland Sea','Iyo','Yes','No'),
	array('Inland Sea','Osaka Bay','Yes','No'),
	array('Inland Sea','Sanuki','Yes','No'),
	array('Inland Sea','Suo','Yes','No'),
	array('Inland Sea','Suo Sea','Yes','No'),
	array('Ise','Mino','No','Yes'),
	array('Ise','Omi','No','Yes'),
	array('Ise','Owari','Yes','Yes'),
	array('Ise','Shima','Yes','Yes'),
	array('Ise','Totomi Sea','Yes','No'),
	array('Ise','Yamashiro (6)','No','Yes'),
	array('Ise','Yamato (5)','No','Yes'),
	array('Iwami','Iwami Coast','Yes','No'),
	array('Iwami','Izumo','Yes','Yes'),
	array('Iwami','Nagato','Yes','Yes'),
	array('Iwami','Suo','No','Yes'),
	array('Iwami Coast','Izumo','Yes','No'),
	array('Iwami Coast','Kanmon Strait','Yes','No'),
	array('Iwami Coast','Nagato','Yes','No'),
	array('Iwami Coast','Sanin Coast','Yes','No'),
	array('Iwami Coast','Sea of Japan','Yes','No'),
	array('Iwami Coast','South Sea of Japan','Yes','No'),
	array('Iyo','Sanuki','Yes','Yes'),
	array('Iyo','Suo Sea','Yes','No'),
	array('Iyo','Tosa','Yes','Yes'),
	array('Izu','Sagami','Yes','Yes'),
	array('Izu','Sagami Bay','Yes','No'),
	array('Izu','Suruga (10)','Yes','Yes'),
	array('Izumo','Sanin Coast','Yes','No'),
	array('Kaga','Noto (8)','Yes','Yes'),
	array('Kaga','Wakasa Bay','Yes','No'),
	array('Kai','Musashi','No','Yes'),
	array('Kai','North Shinano','No','Yes'),
	array('Kai','Sagami','No','Yes'),
	array('Kai','South Shinano','No','Yes'),
	array('Kai','Suruga (10)','No','Yes'),
	array('Kanmon Strait','Nagato','Yes','No'),
	array('Kanmon Strait','South Sea of Japan','Yes','No'),
	array('Kanmon Strait','Suo Sea','Yes','No'),
	array('Kanmon Strait','Tsushima Strait','Yes','No'),
	array('Kawachi (3)','Kii','Yes','Yes'),
	array('Kawachi (3)','Osaka Bay','Yes','No'),
	array('Kawachi (3)','Settsu (4)','Yes','Yes'),
	array('Kawachi (3)','Yamashiro (6)','No','Yes'),
	array('Kawachi (3)','Yamato (5)','No','Yes'),
	array('Kazusa','North Pacific Ocean','Yes','No'),
	array('Kazusa','Pacific Ocean','Yes','No'),
	array('Kazusa','Sagami','Yes','Yes'),
	array('Kazusa','Sagami Bay','Yes','No'),
	array('Kazusa','Shimosa','Yes','Yes'),
	array('Kii','Kii Straits','Yes','No'),
	array('Kii','Kumano Sea','Yes','No'),
	array('Kii','Osaka Bay','Yes','No'),
	array('Kii','Shima','Yes','Yes'),
	array('Kii','Totomi Sea','Yes','No'),
	array('Kii','Yamato (5)','No','Yes'),
	array('Kii Straits','Kumano Sea','Yes','No'),
	array('Kii Straits','Osaka Bay','Yes','No'),
	array('Kii Straits','South Pacific Ocean','Yes','No'),
	array('Kii Straits','Tosa','Yes','No'),
	array('Kii Straits','Tosa Bay','Yes','No'),
	array('Kozuke','Musashi','No','Yes'),
	array('Kozuke','Shimotsuke (11)','No','Yes'),
	array('Kumano Sea','Pacific Ocean','Yes','No'),
	array('Kumano Sea','Sagami Bay','Yes','No'),
	array('Kumano Sea','South Pacific Ocean','Yes','No'),
	array('Kumano Sea','Totomi Sea','Yes','No'),
	array('Mikawa','Mino','No','Yes'),
	array('Mikawa','Owari','Yes','Yes'),
	array('Mikawa','Shima','No','Yes'),
	array('Mikawa','Totomi (9)','Yes','Yes'),
	array('Mikawa','Totomi Sea','Yes','No'),
	array('Mino','Omi','No','Yes'),
	array('Mino','Owari','No','Yes'),
	array('Mino','South Shinano','No','Yes'),
	array('Mino','Totomi (9)','No','Yes'),
	array('Musashi','North Shinano','No','Yes'),
	array('Musashi','Sagami','No','Yes'),
	array('Musashi','Shimosa','No','Yes'),
	array('Musashi','Shimotsuke (11)','No','Yes'),
	array('Mutsu','North Pacific Ocean','Yes','No'),
	array('Mutsu','North Sea of Japan','Yes','No'),
	array('Mutsu','Shimotsuke (11)','No','Yes'),
	array('Mutsu','Tsugaru Strait','Yes','No'),
	array('Nagato','Suo','Yes','Yes'),
	array('Nagato','Suo Sea','Yes','No'),
	array('North Pacific Ocean','Pacific Ocean','Yes','No'),
	array('North Pacific Ocean','Shimosa','Yes','No'),
	array('North Pacific Ocean','Tsugaru Strait','Yes','No'),
	array('North Sea of Japan','Noto (8)','Yes','No'),
	array('North Sea of Japan','Sea of Japan','Yes','No'),
	array('North Sea of Japan','Toyama Bay','Yes','No'),
	array('North Sea of Japan','Tsugaru Strait','Yes','No'),
	array('North Shinano','South Shinano','No','Yes'),
	array('Noto (8)','Sea of Japan','Yes','No'),
	array('Noto (8)','Toyama Bay','Yes','No'),
	array('Noto (8)','Wakasa Bay','Yes','No'),
	array('Omi','Tango','No','Yes'),
	array('Omi','Yamashiro (6)','No','Yes'),
	array('Osaka Bay','Sanuki','Yes','No'),
	array('Osaka Bay','Settsu (4)','Yes','No'),
	array('Osumi','Satsuma','Yes','Yes'),
	array('Owari','Totomi Sea','Yes','No'),
	array('Pacific Ocean','Sagami Bay','Yes','No'),
	array('Pacific Ocean','South Pacific Ocean','Yes','No'),
	array('Sagami','Sagami Bay','Yes','No'),
	array('Sagami','Shimosa','No','Yes'),
	array('Sagami','Suruga (10)','No','Yes'),
	array('Sagami Bay','Suruga (10)','Yes','No'),
	array('Sagami Bay','Totomi (9)','Yes','No'),
	array('Sagami Bay','Totomi Sea','Yes','No'),
	array('Sanin Coast','Sea of Japan','Yes','No'),
	array('Sanin Coast','Tango','Yes','No'),
	array('Sanin Coast','Wakasa Bay','Yes','No'),
	array('Sea of Japan','South Sea of Japan','Yes','No'),
	array('Sea of Japan','Wakasa Bay','Yes','No'),
	array('Settsu (4)','Yamashiro (6)','No','Yes'),
	array('Shima','Totomi Sea','Yes','No'),
	array('Shima','Yamato (5)','No','Yes'),
	array('Shuri Straits','South Pacific Ocean','Yes','No'),
	array('South Pacific Ocean','Tosa Bay','Yes','No'),
	array('South Sea of Japan','Tsushima Strait','Yes','No'),
	array('South Shinano','Suruga (10)','No','Yes'),
	array('South Shinano','Totomi (9)','No','Yes'),
	array('Suo','Suo Sea','Yes','No'),
	array('Suruga (10)','Totomi (9)','Yes','Yes'),
	array('Tango','Wakasa Bay','Yes','No'),
	array('Tosa','Tosa Bay','Yes','No'),
	array('Totomi (9)','Totomi Sea','Yes','No'),
	array('Yamashiro (6)','Yamato (5)','No','Yes')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
