<?php
// This is file installs the map data for the GreekDip variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Achaia', 'Coast', 'No', 0, 382, 639, 186, 315),
	array('Aegaean Sea', 'Sea', 'No', 0, 837, 529, 420, 261),
	array('Anactorium Gulf', 'Sea', 'No', 0, 94, 523, 52, 260),
	array('Apollonia', 'Coast', 'Yes', 0, 83, 174, 50, 85),
	array('Argos', 'Coast', 'Yes', 0, 531, 724, 270, 363),
	array('Athens', 'Coast', 'Yes', 1, 667, 663, 332, 340),
	array('Black Sea', 'Sea', 'No', 0, 1335, 23, 666, 14),
	array('Boeotia', 'Coast', 'No', 0, 570, 581, 280, 290),
	array('Boeotia (North Coast)', 'Coast', 'No', 0, 589, 556, 283, 279),
	array('Boeotia (South Coast)', 'Coast', 'No', 0, 536, 609, 271, 308),
	array('Byzantinum', 'Coast', 'Yes', 2, 1301, 68, 647, 33),
	array('Caria', 'Land', 'No', 0, 1367, 730, 687, 342),
	array('Carian Sea', 'Sea', 'No', 0, 1062, 806, 536, 406),
	array('Chalies', 'Coast', 'Yes', 0, 697, 571, 348, 286),
	array('Chicos', 'Coast', 'Yes', 0, 961, 561, 482, 279),
	array('Concyra', 'Coast', 'Yes', 0, 32, 381, 14, 192),
	array('Corinth', 'Coast', 'Yes', 0, 547, 650, 277, 321),
	array('Corinth (East Coast)', 'Coast', 'No', 0, 590, 654, 279, 327),
	array('Corinth (West Coast)', 'Coast', 'No', 0, 529, 637, 265, 318),
	array('Cretan Sea', 'Sea', 'No', 0, 833, 976, 418, 487),
	array('Cydonia', 'Coast', 'Yes', 0, 674, 1110, 329, 554),
	array('Cydonian Sea', 'Sea', 'No', 0, 531, 1200, 246, 594),
	array('Delos', 'Coast', 'Yes', 0, 879, 659, 439, 328),
	array('Delphi', 'Coast', 'Yes', 0, 288, 525, 147, 260),
	array('Egyptian Sea', 'Sea', 'No', 0, 1122, 1162, 555, 579),
	array('Ephesus', 'Coast', 'Yes', 0, 1134, 589, 550, 295),
	array('Epirus', 'Coast', 'No', 0, 176, 365, 112, 179),
	array('Euboea', 'Coast', 'No', 0, 599, 510, 291, 247),
	array('Gulf of Corinth', 'Sea', 'No', 0, 263, 627, 134, 314),
	array('Gulf of Ephesus', 'Sea', 'No', 0, 962, 694, 488, 341),
	array('Gulf of Knossos', 'Sea', 'No', 0, 1025, 970, 508, 487),
	array('Gulf of Laconia', 'Sea', 'No', 0, 467, 1015, 226, 504),
	array('Gulf of Macedonia', 'Sea', 'No', 0, 531, 284, 267, 146),
	array('Gulf of Salamis', 'Sea', 'No', 0, 621, 801, 301, 397),
	array('Halicarnassus', 'Coast', 'Yes', 0, 1249, 793, 620, 395),
	array('Ilium', 'Coast', 'Yes', 0, 1031, 271, 500, 167),
	array('Imbros', 'Coast', 'Yes', 0, 819, 311, 410, 154),
	array('Ionian Sea', 'Sea', 'No', 0, 68, 794, 32, 393),
	array('Ithaca', 'Coast', 'Yes', 0, 202, 586, 99, 289),
	array('Knossos', 'Coast', 'Yes', 0, 905, 1146, 456, 573),
	array('Laodicoa', 'Land', 'Yes', 0, 1256, 602, 650, 297),
	array('Larissa', 'Coast', 'Yes', 0, 469, 384, 244, 195),
	array('Lesbos', 'Coast', 'Yes', 0, 982, 427, 487, 211),
	array('Lycian Sea', 'Sea', 'No', 0, 1347, 1079, 667, 538),
	array('Macedonia', 'Land', 'No', 0, 469, 74, 217, 31),
	array('Mediterranean Sea', 'Sea', 'No', 0, 74, 1050, 37, 515),
	array('Melos', 'Coast', 'Yes', 0, 696, 871, 346, 434),
	array('Messenia', 'Coast', 'Yes', 0, 369, 785, 186, 387),
	array('Messenian Sea', 'Sea', 'No', 0, 257, 979, 127, 488),
	array('Miletus', 'Coast', 'Yes', 0, 1177, 707, 587, 353),
	array('Mount Ida', 'Coast', 'No', 0, 812, 1162, 384, 564),
	array('Mount Ida (North Coast)', 'Coast', 'No', 0, 770, 1115, 381, 559),
	array('Mount Ida (South Coast)', 'Coast', 'No', 0, 839, 1195, 423, 593),
	array('Myrtoan Sea', 'Sea', 'No', 0, 656, 974, 321, 482),
	array('Mysia', 'Land', 'No', 0, 1338, 337, 676, 168),
	array('Naxos', 'Coast', 'Yes', 0, 870, 813, 433, 405),
	array('Olympia', 'Coast', 'Yes', 0, 330, 700, 163, 350),
	array('Olympian Sea', 'Sea', 'No', 0, 244, 731, 120, 363),
	array('Paeonia', 'Coast', 'No', 0, 685, 133, 338, 62),
	array('Panon', 'Coast', 'No', 0, 484, 780, 242, 383),
	array('Pella', 'Coast', 'Yes', 3, 451, 206, 227, 101),
	array('Pergamum', 'Coast', 'Yes', 0, 1102, 434, 553, 217),
	array('Phrygia', 'Coast', 'No', 0, 1269, 240, 628, 116),
	array('Propontis', 'Sea', 'No', 0, 1253, 148, 619, 66),
	array('Rhodes', 'Coast', 'Yes', 5, 1263, 962, 630, 479),
	array('Samos', 'Coast', 'Yes', 0, 1065, 695, 530, 345),
	array('Sardis', 'Land', 'Yes', 4, 1248, 488, 633, 247),
	array('Sea of Athens', 'Sea', 'No', 0, 775, 734, 390, 372),
	array('Sea of Komos', 'Sea', 'No', 0, 859, 1237, 367, 598),
	array('Sea of Pergamum', 'Sea', 'No', 0, 1050, 490, 524, 234),
	array('Sea of Syracuse', 'Sea', 'No', 0, 239, 1198, 119, 597),
	array('Skithos Sea', 'Sea', 'No', 0, 679, 437, 332, 228),
	array('Sparta', 'Coast', 'Yes', 6, 446, 816, 222, 407),
	array('Straits of Corcya', 'Sea', 'No', 0, 80, 349, 36, 177),
	array('Straits of Euboea', 'Sea', 'No', 0, 546, 459, 315, 285),
	array('Thassos', 'Coast', 'Yes', 0, 808, 115, 404, 56),
	array('Thebes', 'Coast', 'Yes', 0, 489, 556, 249, 278),
	array('Thebes (North Coast)', 'Coast', 'No', 0, 499, 510, 262, 262),
	array('Thebes (South Coast)', 'Coast', 'No', 0, 466, 582, 233, 294),
	array('Therma', 'Coast', 'Yes', 0, 584, 218, 300, 111),
	array('Thermopylae', 'Coast', 'No', 0, 474, 474, 242, 236),
	array('Thessaly', 'Coast', 'No', 0, 444, 305, 228, 151),
	array('Thrace', 'Coast', 'No', 0, 973, 152, 511, 47),
	array('Thracian Sea', 'Sea', 'No', 0, 845, 230, 427, 114),
	array('Coin Stack 11', 'Land', 'No', 1, 0, 0, 0, 0),
	array('Coin Stack 12', 'Land', 'No', 1, 0, 0, 0, 0),
	array('Coin Stack 13', 'Land', 'No', 1, 0, 0, 0, 0),
	array('Coin Stack 14', 'Land', 'No', 1, 0, 0, 0, 0),
	array('Coin Stack 21', 'Land', 'No', 2, 0, 0, 0, 0),
	array('Coin Stack 22', 'Land', 'No', 2, 0, 0, 0, 0),
	array('Coin Stack 23', 'Land', 'No', 2, 0, 0, 0, 0),
	array('Coin Stack 24', 'Land', 'No', 2, 0, 0, 0, 0),
	array('Coin Stack 31', 'Land', 'No', 3, 0, 0, 0, 0),
	array('Coin Stack 32', 'Land', 'No', 3, 0, 0, 0, 0),
	array('Coin Stack 33', 'Land', 'No', 3, 0, 0, 0, 0),
	array('Coin Stack 34', 'Land', 'No', 3, 0, 0, 0, 0),
	array('Coin Stack 41', 'Land', 'No', 4, 0, 0, 0, 0),
	array('Coin Stack 42', 'Land', 'No', 4, 0, 0, 0, 0),
	array('Coin Stack 43', 'Land', 'No', 4, 0, 0, 0, 0),
	array('Coin Stack 44', 'Land', 'No', 4, 0, 0, 0, 0),
	array('Coin Stack 51', 'Land', 'No', 5, 0, 0, 0, 0),
	array('Coin Stack 52', 'Land', 'No', 5, 0, 0, 0, 0),
	array('Coin Stack 53', 'Land', 'No', 5, 0, 0, 0, 0),
	array('Coin Stack 54', 'Land', 'No', 5, 0, 0, 0, 0),
	array('Coin Stack 61', 'Land', 'No', 6, 0, 0, 0, 0),
	array('Coin Stack 62', 'Land', 'No', 6, 0, 0, 0, 0),
	array('Coin Stack 63', 'Land', 'No', 6, 0, 0, 0, 0),
	array('Coin Stack 64', 'Land', 'No', 6, 0, 0, 0, 0),
	array('Thrace (East Coast)', 'Coast', 'No', 0, 1131, 126, 567, 59),
	array('Thrace (West Coast)', 'Coast', 'No', 0, 988, 168, 494, 82)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Achaia','Argos','No','Yes'),
	array('Achaia','Corinth','No','Yes'),
	array('Achaia','Corinth (West Coast)','Yes','No'),
	array('Achaia','Gulf of Corinth','Yes','No'),
	array('Achaia','Olympia','Yes','Yes'),
	array('Achaia','Olympian Sea','Yes','No'),
	array('Aegaean Sea','Chalies','Yes','No'),
	array('Aegaean Sea','Chicos','Yes','No'),
	array('Aegaean Sea','Delos','Yes','No'),
	array('Aegaean Sea','Gulf of Ephesus','Yes','No'),
	array('Aegaean Sea','Ilium','Yes','No'),
	array('Aegaean Sea','Imbros','Yes','No'),
	array('Aegaean Sea','Lesbos','Yes','No'),
	array('Aegaean Sea','Sea of Athens','Yes','No'),
	array('Aegaean Sea','Sea of Pergamum','Yes','No'),
	array('Aegaean Sea','Skithos Sea','Yes','No'),
	array('Aegaean Sea','Thracian Sea','Yes','No'),
	array('Anactorium Gulf','Concyra','Yes','No'),
	array('Anactorium Gulf','Delphi','Yes','No'),
	array('Anactorium Gulf','Epirus','Yes','No'),
	array('Anactorium Gulf','Gulf of Corinth','Yes','No'),
	array('Anactorium Gulf','Ionian Sea','Yes','No'),
	array('Anactorium Gulf','Ithaca','Yes','No'),
	array('Anactorium Gulf','Straits of Corcya','Yes','No'),
	array('Apollonia','Epirus','Yes','Yes'),
	array('Apollonia','Straits of Corcya','Yes','No'),
	array('Argos','Corinth','No','Yes'),
	array('Argos','Corinth (East Coast)','Yes','No'),
	array('Argos','Gulf of Salamis','Yes','No'),
	array('Argos','Olympia','No','Yes'),
	array('Argos','Panon','Yes','Yes'),
	array('Athens','Boeotia','No','Yes'),
	array('Athens','Boeotia (North Coast)','Yes','No'),
	array('Athens','Corinth','No','Yes'),
	array('Athens','Corinth (East Coast)','Yes','No'),
	array('Athens','Gulf of Salamis','Yes','No'),
	array('Athens','Sea of Athens','Yes','No'),
	array('Athens','Straits of Euboea','Yes','No'),
	array('Black Sea','Byzantinum','Yes','No'),
	array('Boeotia','Corinth','No','Yes'),
	array('Boeotia','Thebes','No','Yes'),
	array('Boeotia (North Coast)','Straits of Euboea','Yes','No'),
	array('Boeotia (North Coast)','Thebes (North Coast)','Yes','No'),
	array('Boeotia (South Coast)','Corinth (West Coast)','Yes','No'),
	array('Boeotia (South Coast)','Gulf of Corinth','Yes','No'),
	array('Boeotia (South Coast)','Thebes (South Coast)','Yes','No'),
	array('Byzantinum','Phrygia','Yes','Yes'),
	array('Byzantinum','Propontis','Yes','No'),
	array('Byzantinum','Thrace','No','Yes'),
	array('Byzantinum','Thrace (East Coast)','Yes','No'),
	array('Caria','Halicarnassus','No','Yes'),
	array('Caria','Laodicoa','No','Yes'),
	array('Caria','Miletus','No','Yes'),
	array('Carian Sea','Gulf of Ephesus','Yes','No'),
	array('Carian Sea','Gulf of Knossos','Yes','No'),
	array('Carian Sea','Halicarnassus','Yes','No'),
	array('Carian Sea','Lycian Sea','Yes','No'),
	array('Carian Sea','Miletus','Yes','No'),
	array('Carian Sea','Naxos','Yes','No'),
	array('Carian Sea','Rhodes','Yes','No'),
	array('Carian Sea','Samos','Yes','No'),
	array('Chalies','Euboea','Yes','Yes'),
	array('Chalies','Sea of Athens','Yes','No'),
	array('Chalies','Skithos Sea','Yes','No'),
	array('Chalies','Straits of Euboea','Yes','No'),
	array('Chicos','Gulf of Ephesus','Yes','No'),
	array('Chicos','Sea of Pergamum','Yes','No'),
	array('Concyra','Straits of Corcya','Yes','No'),
	array('Corinth (East Coast)','Gulf of Salamis','Yes','No'),
	array('Corinth (West Coast)','Gulf of Corinth','Yes','No'),
	array('Cretan Sea','Gulf of Knossos','Yes','No'),
	array('Cretan Sea','Knossos','Yes','No'),
	array('Cretan Sea','Melos','Yes','No'),
	array('Cretan Sea','Mount Ida (North Coast)','Yes','No'),
	array('Cretan Sea','Myrtoan Sea','Yes','No'),
	array('Cretan Sea','Naxos','Yes','No'),
	array('Cretan Sea','Sea of Athens','Yes','No'),
	array('Cydonia','Cydonian Sea','Yes','No'),
	array('Cydonia','Gulf of Laconia','Yes','No'),
	array('Cydonia','Mount Ida','No','Yes'),
	array('Cydonia','Mount Ida (North Coast)','Yes','No'),
	array('Cydonia','Mount Ida (South Coast)','Yes','No'),
	array('Cydonia','Myrtoan Sea','Yes','No'),
	array('Cydonia','Sea of Komos','Yes','No'),
	array('Cydonian Sea','Gulf of Laconia','Yes','No'),
	array('Cydonian Sea','Sea of Komos','Yes','No'),
	array('Cydonian Sea','Sea of Syracuse','Yes','No'),
	array('Delos','Gulf of Ephesus','Yes','No'),
	array('Delos','Sea of Athens','Yes','No'),
	array('Delphi','Epirus','Yes','Yes'),
	array('Delphi','Gulf of Corinth','Yes','No'),
	array('Delphi','Larissa','No','Yes'),
	array('Delphi','Thebes','No','Yes'),
	array('Delphi','Thebes (South Coast)','Yes','No'),
	array('Egyptian Sea','Gulf of Knossos','Yes','No'),
	array('Egyptian Sea','Knossos','Yes','No'),
	array('Egyptian Sea','Lycian Sea','Yes','No'),
	array('Egyptian Sea','Rhodes','Yes','No'),
	array('Egyptian Sea','Sea of Komos','Yes','No'),
	array('Ephesus','Gulf of Ephesus','Yes','No'),
	array('Ephesus','Laodicoa','No','Yes'),
	array('Ephesus','Miletus','Yes','Yes'),
	array('Ephesus','Pergamum','Yes','Yes'),
	array('Ephesus','Sardis','No','Yes'),
	array('Ephesus','Sea of Pergamum','Yes','No'),
	array('Epirus','Larissa','No','Yes'),
	array('Epirus','Pella','No','Yes'),
	array('Epirus','Straits of Corcya','Yes','No'),
	array('Epirus','Thessaly','No','Yes'),
	array('Euboea','Skithos Sea','Yes','No'),
	array('Euboea','Straits of Euboea','Yes','No'),
	array('Gulf of Corinth','Ithaca','Yes','No'),
	array('Gulf of Corinth','Olympian Sea','Yes','No'),
	array('Gulf of Corinth','Thebes (South Coast)','Yes','No'),
	array('Gulf of Ephesus','Miletus','Yes','No'),
	array('Gulf of Ephesus','Naxos','Yes','No'),
	array('Gulf of Ephesus','Samos','Yes','No'),
	array('Gulf of Ephesus','Sea of Athens','Yes','No'),
	array('Gulf of Ephesus','Sea of Pergamum','Yes','No'),
	array('Gulf of Knossos','Knossos','Yes','No'),
	array('Gulf of Knossos','Naxos','Yes','No'),
	array('Gulf of Knossos','Rhodes','Yes','No'),
	array('Gulf of Laconia','Messenia','Yes','No'),
	array('Gulf of Laconia','Messenian Sea','Yes','No'),
	array('Gulf of Laconia','Myrtoan Sea','Yes','No'),
	array('Gulf of Laconia','Sea of Syracuse','Yes','No'),
	array('Gulf of Laconia','Sparta','Yes','No'),
	array('Gulf of Macedonia','Imbros','Yes','No'),
	array('Gulf of Macedonia','Larissa','Yes','No'),
	array('Gulf of Macedonia','Pella','Yes','No'),
	array('Gulf of Macedonia','Skithos Sea','Yes','No'),
	array('Gulf of Macedonia','Therma','Yes','No'),
	array('Gulf of Macedonia','Thessaly','Yes','No'),
	array('Gulf of Macedonia','Thracian Sea','Yes','No'),
	array('Gulf of Salamis','Melos','Yes','No'),
	array('Gulf of Salamis','Myrtoan Sea','Yes','No'),
	array('Gulf of Salamis','Panon','Yes','No'),
	array('Gulf of Salamis','Sea of Athens','Yes','No'),
	array('Gulf of Salamis','Sparta','Yes','No'),
	array('Halicarnassus','Lycian Sea','Yes','No'),
	array('Halicarnassus','Miletus','Yes','Yes'),
	array('Ilium','Pergamum','Yes','Yes'),
	array('Ilium','Phrygia','Yes','Yes'),
	array('Ilium','Propontis','Yes','No'),
	array('Ilium','Sea of Pergamum','Yes','No'),
	array('Ilium','Thrace','No','Yes'),
	array('Ilium','Thracian Sea','Yes','No'),
	array('Ilium','Thrace (East Coast)','Yes','No'),
	array('Ilium','Thrace (West Coast)','Yes','No'),
	array('Imbros','Skithos Sea','Yes','No'),
	array('Imbros','Thracian Sea','Yes','No'),
	array('Ionian Sea','Ithaca','Yes','No'),
	array('Ionian Sea','Mediterranean Sea','Yes','No'),
	array('Ionian Sea','Messenian Sea','Yes','No'),
	array('Ionian Sea','Olympian Sea','Yes','No'),
	array('Ithaca','Olympian Sea','Yes','No'),
	array('Knossos','Mount Ida','No','Yes'),
	array('Knossos','Mount Ida (North Coast)','Yes','No'),
	array('Knossos','Mount Ida (South Coast)','Yes','No'),
	array('Knossos','Sea of Komos','Yes','No'),
	array('Laodicoa','Miletus','No','Yes'),
	array('Laodicoa','Sardis','No','Yes'),
	array('Larissa','Skithos Sea','Yes','No'),
	array('Larissa','Straits of Euboea','Yes','No'),
	array('Larissa','Thermopylae','Yes','Yes'),
	array('Larissa','Thessaly','Yes','Yes'),
	array('Lesbos','Sea of Pergamum','Yes','No'),
	array('Lycian Sea','Rhodes','Yes','No'),
	array('Macedonia','Paeonia','No','Yes'),
	array('Macedonia','Pella','No','Yes'),
	array('Macedonia','Therma','No','Yes'),
	array('Mediterranean Sea','Messenian Sea','Yes','No'),
	array('Mediterranean Sea','Sea of Syracuse','Yes','No'),
	array('Melos','Myrtoan Sea','Yes','No'),
	array('Melos','Sea of Athens','Yes','No'),
	array('Messenia','Messenian Sea','Yes','No'),
	array('Messenia','Olympia','Yes','Yes'),
	array('Messenia','Olympian Sea','Yes','No'),
	array('Messenia','Sparta','Yes','Yes'),
	array('Messenian Sea','Olympian Sea','Yes','No'),
	array('Messenian Sea','Sea of Syracuse','Yes','No'),
	array('Mount Ida (North Coast)','Myrtoan Sea','Yes','No'),
	array('Mount Ida (South Coast)','Sea of Komos','Yes','No'),
	array('Myrtoan Sea','Sparta','Yes','No'),
	array('Mysia','Pergamum','No','Yes'),
	array('Mysia','Phrygia','No','Yes'),
	array('Mysia','Sardis','No','Yes'),
	array('Naxos','Sea of Athens','Yes','No'),
	array('Olympia','Olympian Sea','Yes','No'),
	array('Olympia','Panon','No','Yes'),
	array('Olympia','Sparta','No','Yes'),
	array('Paeonia','Thassos','Yes','Yes'),
	array('Paeonia','Therma','Yes','Yes'),
	array('Paeonia','Thrace','No','Yes'),
	array('Paeonia','Thracian Sea','Yes','No'),
	array('Panon','Sparta','Yes','Yes'),
	array('Pella','Therma','Yes','Yes'),
	array('Pella','Thessaly','Yes','Yes'),
	array('Pergamum','Phrygia','No','Yes'),
	array('Pergamum','Sardis','No','Yes'),
	array('Pergamum','Sea of Pergamum','Yes','No'),
	array('Phrygia','Propontis','Yes','No'),
	array('Propontis','Thrace (East Coast)','Yes','No'),
	array('Sea of Athens','Straits of Euboea','Yes','No'),
	array('Skithos Sea','Straits of Euboea','Yes','No'),
	array('Straits of Euboea','Thebes (North Coast)','Yes','No'),
	array('Straits of Euboea','Thermopylae','Yes','No'),
	array('Thassos','Thrace','No','Yes'),
	array('Thassos','Thracian Sea','Yes','No'),
	array('Thassos','Thrace (West Coast)','Yes','No'),
	array('Thebes','Thermopylae','No','Yes'),
	array('Thebes (North Coast)','Thermopylae','Yes','No'),
	array('Therma','Thracian Sea','Yes','No'),
	array('Thracian Sea','Thrace (West Coast)','Yes','No'),
	array('Coin Stack 11','Apollonia','No','Yes'),
	array('Coin Stack 11','Argos','No','Yes'),
	array('Coin Stack 11','Chalies','No','Yes'),
	array('Coin Stack 11','Chicos','No','Yes'),
	array('Coin Stack 11','Concyra','No','Yes'),
	array('Coin Stack 11','Corinth','No','Yes'),
	array('Coin Stack 11','Cydonia','No','Yes'),
	array('Coin Stack 11','Delos','No','Yes'),
	array('Coin Stack 11','Delphi','No','Yes'),
	array('Coin Stack 11','Ephesus','No','Yes'),
	array('Coin Stack 11','Epirus','Yes','Yes'),
	array('Coin Stack 11','Halicarnassus','No','Yes'),
	array('Coin Stack 11','Ilium','No','Yes'),
	array('Coin Stack 11','Imbros','No','Yes'),
	array('Coin Stack 11','Ithaca','No','Yes'),
	array('Coin Stack 11','Knossos','No','Yes'),
	array('Coin Stack 11','Laodicoa','No','Yes'),
	array('Coin Stack 11','Larissa','No','Yes'),
	array('Coin Stack 11','Lesbos','No','Yes'),
	array('Coin Stack 11','Melos','No','Yes'),
	array('Coin Stack 11','Messenia','No','Yes'),
	array('Coin Stack 11','Miletus','No','Yes'),
	array('Coin Stack 11','Naxos','No','Yes'),
	array('Coin Stack 11','Olympia','No','Yes'),
	array('Coin Stack 11','Pergamum','No','Yes'),
	array('Coin Stack 11','Samos','No','Yes'),
	array('Coin Stack 11','Thassos','No','Yes'),
	array('Coin Stack 11','Thebes','No','Yes'),
	array('Coin Stack 11','Therma','No','Yes'),
	array('Coin Stack 12','Apollonia','No','Yes'),
	array('Coin Stack 12','Argos','No','Yes'),
	array('Coin Stack 12','Chalies','No','Yes'),
	array('Coin Stack 12','Chicos','No','Yes'),
	array('Coin Stack 12','Concyra','No','Yes'),
	array('Coin Stack 12','Corinth','No','Yes'),
	array('Coin Stack 12','Cydonia','No','Yes'),
	array('Coin Stack 12','Delos','No','Yes'),
	array('Coin Stack 12','Delphi','No','Yes'),
	array('Coin Stack 12','Ephesus','No','Yes'),
	array('Coin Stack 12','Halicarnassus','No','Yes'),
	array('Coin Stack 12','Ilium','No','Yes'),
	array('Coin Stack 12','Imbros','No','Yes'),
	array('Coin Stack 12','Ithaca','No','Yes'),
	array('Coin Stack 12','Knossos','No','Yes'),
	array('Coin Stack 12','Laodicoa','No','Yes'),
	array('Coin Stack 12','Larissa','No','Yes'),
	array('Coin Stack 12','Lesbos','No','Yes'),
	array('Coin Stack 12','Melos','No','Yes'),
	array('Coin Stack 12','Messenia','No','Yes'),
	array('Coin Stack 12','Miletus','No','Yes'),
	array('Coin Stack 12','Naxos','No','Yes'),
	array('Coin Stack 12','Olympia','No','Yes'),
	array('Coin Stack 12','Pergamum','No','Yes'),
	array('Coin Stack 12','Samos','No','Yes'),
	array('Coin Stack 12','Thassos','No','Yes'),
	array('Coin Stack 12','Thebes','No','Yes'),
	array('Coin Stack 12','Therma','No','Yes'),
	array('Coin Stack 13','Apollonia','No','Yes'),
	array('Coin Stack 13','Argos','No','Yes'),
	array('Coin Stack 13','Chalies','No','Yes'),
	array('Coin Stack 13','Chicos','No','Yes'),
	array('Coin Stack 13','Concyra','No','Yes'),
	array('Coin Stack 13','Corinth','No','Yes'),
	array('Coin Stack 13','Cydonia','No','Yes'),
	array('Coin Stack 13','Delos','No','Yes'),
	array('Coin Stack 13','Delphi','No','Yes'),
	array('Coin Stack 13','Ephesus','No','Yes'),
	array('Coin Stack 13','Halicarnassus','No','Yes'),
	array('Coin Stack 13','Ilium','No','Yes'),
	array('Coin Stack 13','Imbros','No','Yes'),
	array('Coin Stack 13','Ithaca','No','Yes'),
	array('Coin Stack 13','Knossos','No','Yes'),
	array('Coin Stack 13','Laodicoa','No','Yes'),
	array('Coin Stack 13','Larissa','No','Yes'),
	array('Coin Stack 13','Lesbos','No','Yes'),
	array('Coin Stack 13','Melos','No','Yes'),
	array('Coin Stack 13','Messenia','No','Yes'),
	array('Coin Stack 13','Miletus','No','Yes'),
	array('Coin Stack 13','Naxos','No','Yes'),
	array('Coin Stack 13','Olympia','No','Yes'),
	array('Coin Stack 13','Pergamum','No','Yes'),
	array('Coin Stack 13','Samos','No','Yes'),
	array('Coin Stack 13','Thassos','No','Yes'),
	array('Coin Stack 13','Thebes','No','Yes'),
	array('Coin Stack 13','Therma','No','Yes'),
	array('Coin Stack 14','Apollonia','No','Yes'),
	array('Coin Stack 14','Argos','No','Yes'),
	array('Coin Stack 14','Chalies','No','Yes'),
	array('Coin Stack 14','Chicos','No','Yes'),
	array('Coin Stack 14','Concyra','No','Yes'),
	array('Coin Stack 14','Corinth','No','Yes'),
	array('Coin Stack 14','Cydonia','No','Yes'),
	array('Coin Stack 14','Delos','No','Yes'),
	array('Coin Stack 14','Delphi','No','Yes'),
	array('Coin Stack 14','Ephesus','No','Yes'),
	array('Coin Stack 14','Halicarnassus','No','Yes'),
	array('Coin Stack 14','Ilium','No','Yes'),
	array('Coin Stack 14','Imbros','No','Yes'),
	array('Coin Stack 14','Ithaca','No','Yes'),
	array('Coin Stack 14','Knossos','No','Yes'),
	array('Coin Stack 14','Laodicoa','No','Yes'),
	array('Coin Stack 14','Larissa','No','Yes'),
	array('Coin Stack 14','Lesbos','No','Yes'),
	array('Coin Stack 14','Melos','No','Yes'),
	array('Coin Stack 14','Messenia','No','Yes'),
	array('Coin Stack 14','Miletus','No','Yes'),
	array('Coin Stack 14','Naxos','No','Yes'),
	array('Coin Stack 14','Olympia','No','Yes'),
	array('Coin Stack 14','Pergamum','No','Yes'),
	array('Coin Stack 14','Samos','No','Yes'),
	array('Coin Stack 14','Thassos','No','Yes'),
	array('Coin Stack 14','Thebes','No','Yes'),
	array('Coin Stack 14','Therma','No','Yes'),
	array('Coin Stack 21','Apollonia','No','Yes'),
	array('Coin Stack 21','Argos','No','Yes'),
	array('Coin Stack 21','Chalies','No','Yes'),
	array('Coin Stack 21','Chicos','No','Yes'),
	array('Coin Stack 21','Concyra','No','Yes'),
	array('Coin Stack 21','Corinth','No','Yes'),
	array('Coin Stack 21','Cydonia','No','Yes'),
	array('Coin Stack 21','Delos','No','Yes'),
	array('Coin Stack 21','Delphi','No','Yes'),
	array('Coin Stack 21','Ephesus','No','Yes'),
	array('Coin Stack 21','Halicarnassus','No','Yes'),
	array('Coin Stack 21','Ilium','No','Yes'),
	array('Coin Stack 21','Imbros','No','Yes'),
	array('Coin Stack 21','Ithaca','No','Yes'),
	array('Coin Stack 21','Knossos','No','Yes'),
	array('Coin Stack 21','Laodicoa','No','Yes'),
	array('Coin Stack 21','Larissa','No','Yes'),
	array('Coin Stack 21','Lesbos','No','Yes'),
	array('Coin Stack 21','Melos','No','Yes'),
	array('Coin Stack 21','Messenia','No','Yes'),
	array('Coin Stack 21','Miletus','No','Yes'),
	array('Coin Stack 21','Naxos','No','Yes'),
	array('Coin Stack 21','Olympia','No','Yes'),
	array('Coin Stack 21','Pergamum','No','Yes'),
	array('Coin Stack 21','Samos','No','Yes'),
	array('Coin Stack 21','Thassos','No','Yes'),
	array('Coin Stack 21','Thebes','No','Yes'),
	array('Coin Stack 21','Therma','No','Yes'),
	array('Coin Stack 22','Apollonia','No','Yes'),
	array('Coin Stack 22','Argos','No','Yes'),
	array('Coin Stack 22','Chalies','No','Yes'),
	array('Coin Stack 22','Chicos','No','Yes'),
	array('Coin Stack 22','Concyra','No','Yes'),
	array('Coin Stack 22','Corinth','No','Yes'),
	array('Coin Stack 22','Cydonia','No','Yes'),
	array('Coin Stack 22','Delos','No','Yes'),
	array('Coin Stack 22','Delphi','No','Yes'),
	array('Coin Stack 22','Ephesus','No','Yes'),
	array('Coin Stack 22','Halicarnassus','No','Yes'),
	array('Coin Stack 22','Ilium','No','Yes'),
	array('Coin Stack 22','Imbros','No','Yes'),
	array('Coin Stack 22','Ithaca','No','Yes'),
	array('Coin Stack 22','Knossos','No','Yes'),
	array('Coin Stack 22','Laodicoa','No','Yes'),
	array('Coin Stack 22','Larissa','No','Yes'),
	array('Coin Stack 22','Lesbos','No','Yes'),
	array('Coin Stack 22','Melos','No','Yes'),
	array('Coin Stack 22','Messenia','No','Yes'),
	array('Coin Stack 22','Miletus','No','Yes'),
	array('Coin Stack 22','Naxos','No','Yes'),
	array('Coin Stack 22','Olympia','No','Yes'),
	array('Coin Stack 22','Pergamum','No','Yes'),
	array('Coin Stack 22','Samos','No','Yes'),
	array('Coin Stack 22','Thassos','No','Yes'),
	array('Coin Stack 22','Thebes','No','Yes'),
	array('Coin Stack 22','Therma','No','Yes'),
	array('Coin Stack 23','Apollonia','No','Yes'),
	array('Coin Stack 23','Argos','No','Yes'),
	array('Coin Stack 23','Chalies','No','Yes'),
	array('Coin Stack 23','Chicos','No','Yes'),
	array('Coin Stack 23','Concyra','No','Yes'),
	array('Coin Stack 23','Corinth','No','Yes'),
	array('Coin Stack 23','Cydonia','No','Yes'),
	array('Coin Stack 23','Delos','No','Yes'),
	array('Coin Stack 23','Delphi','No','Yes'),
	array('Coin Stack 23','Ephesus','No','Yes'),
	array('Coin Stack 23','Halicarnassus','No','Yes'),
	array('Coin Stack 23','Ilium','No','Yes'),
	array('Coin Stack 23','Imbros','No','Yes'),
	array('Coin Stack 23','Ithaca','No','Yes'),
	array('Coin Stack 23','Knossos','No','Yes'),
	array('Coin Stack 23','Laodicoa','No','Yes'),
	array('Coin Stack 23','Larissa','No','Yes'),
	array('Coin Stack 23','Lesbos','No','Yes'),
	array('Coin Stack 23','Melos','No','Yes'),
	array('Coin Stack 23','Messenia','No','Yes'),
	array('Coin Stack 23','Miletus','No','Yes'),
	array('Coin Stack 23','Naxos','No','Yes'),
	array('Coin Stack 23','Olympia','No','Yes'),
	array('Coin Stack 23','Pergamum','No','Yes'),
	array('Coin Stack 23','Samos','No','Yes'),
	array('Coin Stack 23','Thassos','No','Yes'),
	array('Coin Stack 23','Thebes','No','Yes'),
	array('Coin Stack 23','Therma','No','Yes'),
	array('Coin Stack 24','Apollonia','No','Yes'),
	array('Coin Stack 24','Argos','No','Yes'),
	array('Coin Stack 24','Chalies','No','Yes'),
	array('Coin Stack 24','Chicos','No','Yes'),
	array('Coin Stack 24','Concyra','No','Yes'),
	array('Coin Stack 24','Corinth','No','Yes'),
	array('Coin Stack 24','Cydonia','No','Yes'),
	array('Coin Stack 24','Delos','No','Yes'),
	array('Coin Stack 24','Delphi','No','Yes'),
	array('Coin Stack 24','Ephesus','No','Yes'),
	array('Coin Stack 24','Halicarnassus','No','Yes'),
	array('Coin Stack 24','Ilium','No','Yes'),
	array('Coin Stack 24','Imbros','No','Yes'),
	array('Coin Stack 24','Ithaca','No','Yes'),
	array('Coin Stack 24','Knossos','No','Yes'),
	array('Coin Stack 24','Laodicoa','No','Yes'),
	array('Coin Stack 24','Larissa','No','Yes'),
	array('Coin Stack 24','Lesbos','No','Yes'),
	array('Coin Stack 24','Melos','No','Yes'),
	array('Coin Stack 24','Messenia','No','Yes'),
	array('Coin Stack 24','Miletus','No','Yes'),
	array('Coin Stack 24','Naxos','No','Yes'),
	array('Coin Stack 24','Olympia','No','Yes'),
	array('Coin Stack 24','Pergamum','No','Yes'),
	array('Coin Stack 24','Samos','No','Yes'),
	array('Coin Stack 24','Thassos','No','Yes'),
	array('Coin Stack 24','Thebes','No','Yes'),
	array('Coin Stack 24','Therma','No','Yes'),
	array('Coin Stack 31','Apollonia','No','Yes'),
	array('Coin Stack 31','Argos','No','Yes'),
	array('Coin Stack 31','Chalies','No','Yes'),
	array('Coin Stack 31','Chicos','No','Yes'),
	array('Coin Stack 31','Concyra','No','Yes'),
	array('Coin Stack 31','Corinth','No','Yes'),
	array('Coin Stack 31','Cydonia','No','Yes'),
	array('Coin Stack 31','Delos','No','Yes'),
	array('Coin Stack 31','Delphi','No','Yes'),
	array('Coin Stack 31','Ephesus','No','Yes'),
	array('Coin Stack 31','Halicarnassus','No','Yes'),
	array('Coin Stack 31','Ilium','No','Yes'),
	array('Coin Stack 31','Imbros','No','Yes'),
	array('Coin Stack 31','Ithaca','No','Yes'),
	array('Coin Stack 31','Knossos','No','Yes'),
	array('Coin Stack 31','Laodicoa','No','Yes'),
	array('Coin Stack 31','Larissa','No','Yes'),
	array('Coin Stack 31','Lesbos','No','Yes'),
	array('Coin Stack 31','Melos','No','Yes'),
	array('Coin Stack 31','Messenia','No','Yes'),
	array('Coin Stack 31','Miletus','No','Yes'),
	array('Coin Stack 31','Naxos','No','Yes'),
	array('Coin Stack 31','Olympia','No','Yes'),
	array('Coin Stack 31','Pergamum','No','Yes'),
	array('Coin Stack 31','Samos','No','Yes'),
	array('Coin Stack 31','Thassos','No','Yes'),
	array('Coin Stack 31','Thebes','No','Yes'),
	array('Coin Stack 31','Therma','No','Yes'),
	array('Coin Stack 32','Apollonia','No','Yes'),
	array('Coin Stack 32','Argos','No','Yes'),
	array('Coin Stack 32','Chalies','No','Yes'),
	array('Coin Stack 32','Chicos','No','Yes'),
	array('Coin Stack 32','Concyra','No','Yes'),
	array('Coin Stack 32','Corinth','No','Yes'),
	array('Coin Stack 32','Cydonia','No','Yes'),
	array('Coin Stack 32','Delos','No','Yes'),
	array('Coin Stack 32','Delphi','No','Yes'),
	array('Coin Stack 32','Ephesus','No','Yes'),
	array('Coin Stack 32','Halicarnassus','No','Yes'),
	array('Coin Stack 32','Ilium','No','Yes'),
	array('Coin Stack 32','Imbros','No','Yes'),
	array('Coin Stack 32','Ithaca','No','Yes'),
	array('Coin Stack 32','Knossos','No','Yes'),
	array('Coin Stack 32','Laodicoa','No','Yes'),
	array('Coin Stack 32','Larissa','No','Yes'),
	array('Coin Stack 32','Lesbos','No','Yes'),
	array('Coin Stack 32','Melos','No','Yes'),
	array('Coin Stack 32','Messenia','No','Yes'),
	array('Coin Stack 32','Miletus','No','Yes'),
	array('Coin Stack 32','Naxos','No','Yes'),
	array('Coin Stack 32','Olympia','No','Yes'),
	array('Coin Stack 32','Pergamum','No','Yes'),
	array('Coin Stack 32','Samos','No','Yes'),
	array('Coin Stack 32','Thassos','No','Yes'),
	array('Coin Stack 32','Thebes','No','Yes'),
	array('Coin Stack 32','Therma','No','Yes'),
	array('Coin Stack 33','Apollonia','No','Yes'),
	array('Coin Stack 33','Argos','No','Yes'),
	array('Coin Stack 33','Chalies','No','Yes'),
	array('Coin Stack 33','Chicos','No','Yes'),
	array('Coin Stack 33','Concyra','No','Yes'),
	array('Coin Stack 33','Corinth','No','Yes'),
	array('Coin Stack 33','Cydonia','No','Yes'),
	array('Coin Stack 33','Delos','No','Yes'),
	array('Coin Stack 33','Delphi','No','Yes'),
	array('Coin Stack 33','Ephesus','No','Yes'),
	array('Coin Stack 33','Halicarnassus','No','Yes'),
	array('Coin Stack 33','Ilium','No','Yes'),
	array('Coin Stack 33','Imbros','No','Yes'),
	array('Coin Stack 33','Ithaca','No','Yes'),
	array('Coin Stack 33','Knossos','No','Yes'),
	array('Coin Stack 33','Laodicoa','No','Yes'),
	array('Coin Stack 33','Larissa','No','Yes'),
	array('Coin Stack 33','Lesbos','No','Yes'),
	array('Coin Stack 33','Melos','No','Yes'),
	array('Coin Stack 33','Messenia','No','Yes'),
	array('Coin Stack 33','Miletus','No','Yes'),
	array('Coin Stack 33','Naxos','No','Yes'),
	array('Coin Stack 33','Olympia','No','Yes'),
	array('Coin Stack 33','Pergamum','No','Yes'),
	array('Coin Stack 33','Samos','No','Yes'),
	array('Coin Stack 33','Thassos','No','Yes'),
	array('Coin Stack 33','Thebes','No','Yes'),
	array('Coin Stack 33','Therma','No','Yes'),
	array('Coin Stack 34','Apollonia','No','Yes'),
	array('Coin Stack 34','Argos','No','Yes'),
	array('Coin Stack 34','Chalies','No','Yes'),
	array('Coin Stack 34','Chicos','No','Yes'),
	array('Coin Stack 34','Concyra','No','Yes'),
	array('Coin Stack 34','Corinth','No','Yes'),
	array('Coin Stack 34','Cydonia','No','Yes'),
	array('Coin Stack 34','Delos','No','Yes'),
	array('Coin Stack 34','Delphi','No','Yes'),
	array('Coin Stack 34','Ephesus','No','Yes'),
	array('Coin Stack 34','Halicarnassus','No','Yes'),
	array('Coin Stack 34','Ilium','No','Yes'),
	array('Coin Stack 34','Imbros','No','Yes'),
	array('Coin Stack 34','Ithaca','No','Yes'),
	array('Coin Stack 34','Knossos','No','Yes'),
	array('Coin Stack 34','Laodicoa','No','Yes'),
	array('Coin Stack 34','Larissa','No','Yes'),
	array('Coin Stack 34','Lesbos','No','Yes'),
	array('Coin Stack 34','Melos','No','Yes'),
	array('Coin Stack 34','Messenia','No','Yes'),
	array('Coin Stack 34','Miletus','No','Yes'),
	array('Coin Stack 34','Naxos','No','Yes'),
	array('Coin Stack 34','Olympia','No','Yes'),
	array('Coin Stack 34','Pergamum','No','Yes'),
	array('Coin Stack 34','Samos','No','Yes'),
	array('Coin Stack 34','Thassos','No','Yes'),
	array('Coin Stack 34','Thebes','No','Yes'),
	array('Coin Stack 34','Therma','No','Yes'),
	array('Coin Stack 41','Apollonia','No','Yes'),
	array('Coin Stack 41','Argos','No','Yes'),
	array('Coin Stack 41','Chalies','No','Yes'),
	array('Coin Stack 41','Chicos','No','Yes'),
	array('Coin Stack 41','Concyra','No','Yes'),
	array('Coin Stack 41','Corinth','No','Yes'),
	array('Coin Stack 41','Cydonia','No','Yes'),
	array('Coin Stack 41','Delos','No','Yes'),
	array('Coin Stack 41','Delphi','No','Yes'),
	array('Coin Stack 41','Ephesus','No','Yes'),
	array('Coin Stack 41','Halicarnassus','No','Yes'),
	array('Coin Stack 41','Ilium','No','Yes'),
	array('Coin Stack 41','Imbros','No','Yes'),
	array('Coin Stack 41','Ithaca','No','Yes'),
	array('Coin Stack 41','Knossos','No','Yes'),
	array('Coin Stack 41','Laodicoa','No','Yes'),
	array('Coin Stack 41','Larissa','No','Yes'),
	array('Coin Stack 41','Lesbos','No','Yes'),
	array('Coin Stack 41','Melos','No','Yes'),
	array('Coin Stack 41','Messenia','No','Yes'),
	array('Coin Stack 41','Miletus','No','Yes'),
	array('Coin Stack 41','Naxos','No','Yes'),
	array('Coin Stack 41','Olympia','No','Yes'),
	array('Coin Stack 41','Pergamum','No','Yes'),
	array('Coin Stack 41','Samos','No','Yes'),
	array('Coin Stack 41','Thassos','No','Yes'),
	array('Coin Stack 41','Thebes','No','Yes'),
	array('Coin Stack 41','Therma','No','Yes'),
	array('Coin Stack 42','Apollonia','No','Yes'),
	array('Coin Stack 42','Argos','No','Yes'),
	array('Coin Stack 42','Chalies','No','Yes'),
	array('Coin Stack 42','Chicos','No','Yes'),
	array('Coin Stack 42','Concyra','No','Yes'),
	array('Coin Stack 42','Corinth','No','Yes'),
	array('Coin Stack 42','Cydonia','No','Yes'),
	array('Coin Stack 42','Delos','No','Yes'),
	array('Coin Stack 42','Delphi','No','Yes'),
	array('Coin Stack 42','Ephesus','No','Yes'),
	array('Coin Stack 42','Halicarnassus','No','Yes'),
	array('Coin Stack 42','Ilium','No','Yes'),
	array('Coin Stack 42','Imbros','No','Yes'),
	array('Coin Stack 42','Ithaca','No','Yes'),
	array('Coin Stack 42','Knossos','No','Yes'),
	array('Coin Stack 42','Laodicoa','No','Yes'),
	array('Coin Stack 42','Larissa','No','Yes'),
	array('Coin Stack 42','Lesbos','No','Yes'),
	array('Coin Stack 42','Melos','No','Yes'),
	array('Coin Stack 42','Messenia','No','Yes'),
	array('Coin Stack 42','Miletus','No','Yes'),
	array('Coin Stack 42','Naxos','No','Yes'),
	array('Coin Stack 42','Olympia','No','Yes'),
	array('Coin Stack 42','Pergamum','No','Yes'),
	array('Coin Stack 42','Samos','No','Yes'),
	array('Coin Stack 42','Thassos','No','Yes'),
	array('Coin Stack 42','Thebes','No','Yes'),
	array('Coin Stack 42','Therma','No','Yes'),
	array('Coin Stack 43','Apollonia','No','Yes'),
	array('Coin Stack 43','Argos','No','Yes'),
	array('Coin Stack 43','Chalies','No','Yes'),
	array('Coin Stack 43','Chicos','No','Yes'),
	array('Coin Stack 43','Concyra','No','Yes'),
	array('Coin Stack 43','Corinth','No','Yes'),
	array('Coin Stack 43','Cydonia','No','Yes'),
	array('Coin Stack 43','Delos','No','Yes'),
	array('Coin Stack 43','Delphi','No','Yes'),
	array('Coin Stack 43','Ephesus','No','Yes'),
	array('Coin Stack 43','Halicarnassus','No','Yes'),
	array('Coin Stack 43','Ilium','No','Yes'),
	array('Coin Stack 43','Imbros','No','Yes'),
	array('Coin Stack 43','Ithaca','No','Yes'),
	array('Coin Stack 43','Knossos','No','Yes'),
	array('Coin Stack 43','Laodicoa','No','Yes'),
	array('Coin Stack 43','Larissa','No','Yes'),
	array('Coin Stack 43','Lesbos','No','Yes'),
	array('Coin Stack 43','Melos','No','Yes'),
	array('Coin Stack 43','Messenia','No','Yes'),
	array('Coin Stack 43','Miletus','No','Yes'),
	array('Coin Stack 43','Naxos','No','Yes'),
	array('Coin Stack 43','Olympia','No','Yes'),
	array('Coin Stack 43','Pergamum','No','Yes'),
	array('Coin Stack 43','Samos','No','Yes'),
	array('Coin Stack 43','Thassos','No','Yes'),
	array('Coin Stack 43','Thebes','No','Yes'),
	array('Coin Stack 43','Therma','No','Yes'),
	array('Coin Stack 44','Apollonia','No','Yes'),
	array('Coin Stack 44','Argos','No','Yes'),
	array('Coin Stack 44','Chalies','No','Yes'),
	array('Coin Stack 44','Chicos','No','Yes'),
	array('Coin Stack 44','Concyra','No','Yes'),
	array('Coin Stack 44','Corinth','No','Yes'),
	array('Coin Stack 44','Cydonia','No','Yes'),
	array('Coin Stack 44','Delos','No','Yes'),
	array('Coin Stack 44','Delphi','No','Yes'),
	array('Coin Stack 44','Ephesus','No','Yes'),
	array('Coin Stack 44','Halicarnassus','No','Yes'),
	array('Coin Stack 44','Ilium','No','Yes'),
	array('Coin Stack 44','Imbros','No','Yes'),
	array('Coin Stack 44','Ithaca','No','Yes'),
	array('Coin Stack 44','Knossos','No','Yes'),
	array('Coin Stack 44','Laodicoa','No','Yes'),
	array('Coin Stack 44','Larissa','No','Yes'),
	array('Coin Stack 44','Lesbos','No','Yes'),
	array('Coin Stack 44','Melos','No','Yes'),
	array('Coin Stack 44','Messenia','No','Yes'),
	array('Coin Stack 44','Miletus','No','Yes'),
	array('Coin Stack 44','Naxos','No','Yes'),
	array('Coin Stack 44','Olympia','No','Yes'),
	array('Coin Stack 44','Pergamum','No','Yes'),
	array('Coin Stack 44','Samos','No','Yes'),
	array('Coin Stack 44','Thassos','No','Yes'),
	array('Coin Stack 44','Thebes','No','Yes'),
	array('Coin Stack 44','Therma','No','Yes'),
	array('Coin Stack 51','Apollonia','No','Yes'),
	array('Coin Stack 51','Argos','No','Yes'),
	array('Coin Stack 51','Chalies','No','Yes'),
	array('Coin Stack 51','Chicos','No','Yes'),
	array('Coin Stack 51','Concyra','No','Yes'),
	array('Coin Stack 51','Corinth','No','Yes'),
	array('Coin Stack 51','Cydonia','No','Yes'),
	array('Coin Stack 51','Delos','No','Yes'),
	array('Coin Stack 51','Delphi','No','Yes'),
	array('Coin Stack 51','Ephesus','No','Yes'),
	array('Coin Stack 51','Halicarnassus','No','Yes'),
	array('Coin Stack 51','Ilium','No','Yes'),
	array('Coin Stack 51','Imbros','No','Yes'),
	array('Coin Stack 51','Ithaca','No','Yes'),
	array('Coin Stack 51','Knossos','No','Yes'),
	array('Coin Stack 51','Laodicoa','No','Yes'),
	array('Coin Stack 51','Larissa','No','Yes'),
	array('Coin Stack 51','Lesbos','No','Yes'),
	array('Coin Stack 51','Melos','No','Yes'),
	array('Coin Stack 51','Messenia','No','Yes'),
	array('Coin Stack 51','Miletus','No','Yes'),
	array('Coin Stack 51','Naxos','No','Yes'),
	array('Coin Stack 51','Olympia','No','Yes'),
	array('Coin Stack 51','Pergamum','No','Yes'),
	array('Coin Stack 51','Samos','No','Yes'),
	array('Coin Stack 51','Thassos','No','Yes'),
	array('Coin Stack 51','Thebes','No','Yes'),
	array('Coin Stack 51','Therma','No','Yes'),
	array('Coin Stack 52','Apollonia','No','Yes'),
	array('Coin Stack 52','Argos','No','Yes'),
	array('Coin Stack 52','Chalies','No','Yes'),
	array('Coin Stack 52','Chicos','No','Yes'),
	array('Coin Stack 52','Concyra','No','Yes'),
	array('Coin Stack 52','Corinth','No','Yes'),
	array('Coin Stack 52','Cydonia','No','Yes'),
	array('Coin Stack 52','Delos','No','Yes'),
	array('Coin Stack 52','Delphi','No','Yes'),
	array('Coin Stack 52','Ephesus','No','Yes'),
	array('Coin Stack 52','Halicarnassus','No','Yes'),
	array('Coin Stack 52','Ilium','No','Yes'),
	array('Coin Stack 52','Imbros','No','Yes'),
	array('Coin Stack 52','Ithaca','No','Yes'),
	array('Coin Stack 52','Knossos','No','Yes'),
	array('Coin Stack 52','Laodicoa','No','Yes'),
	array('Coin Stack 52','Larissa','No','Yes'),
	array('Coin Stack 52','Lesbos','No','Yes'),
	array('Coin Stack 52','Melos','No','Yes'),
	array('Coin Stack 52','Messenia','No','Yes'),
	array('Coin Stack 52','Miletus','No','Yes'),
	array('Coin Stack 52','Naxos','No','Yes'),
	array('Coin Stack 52','Olympia','No','Yes'),
	array('Coin Stack 52','Pergamum','No','Yes'),
	array('Coin Stack 52','Samos','No','Yes'),
	array('Coin Stack 52','Thassos','No','Yes'),
	array('Coin Stack 52','Thebes','No','Yes'),
	array('Coin Stack 52','Therma','No','Yes'),
	array('Coin Stack 53','Apollonia','No','Yes'),
	array('Coin Stack 53','Argos','No','Yes'),
	array('Coin Stack 53','Chalies','No','Yes'),
	array('Coin Stack 53','Chicos','No','Yes'),
	array('Coin Stack 53','Concyra','No','Yes'),
	array('Coin Stack 53','Corinth','No','Yes'),
	array('Coin Stack 53','Cydonia','No','Yes'),
	array('Coin Stack 53','Delos','No','Yes'),
	array('Coin Stack 53','Delphi','No','Yes'),
	array('Coin Stack 53','Ephesus','No','Yes'),
	array('Coin Stack 53','Halicarnassus','No','Yes'),
	array('Coin Stack 53','Ilium','No','Yes'),
	array('Coin Stack 53','Imbros','No','Yes'),
	array('Coin Stack 53','Ithaca','No','Yes'),
	array('Coin Stack 53','Knossos','No','Yes'),
	array('Coin Stack 53','Laodicoa','No','Yes'),
	array('Coin Stack 53','Larissa','No','Yes'),
	array('Coin Stack 53','Lesbos','No','Yes'),
	array('Coin Stack 53','Melos','No','Yes'),
	array('Coin Stack 53','Messenia','No','Yes'),
	array('Coin Stack 53','Miletus','No','Yes'),
	array('Coin Stack 53','Naxos','No','Yes'),
	array('Coin Stack 53','Olympia','No','Yes'),
	array('Coin Stack 53','Pergamum','No','Yes'),
	array('Coin Stack 53','Samos','No','Yes'),
	array('Coin Stack 53','Thassos','No','Yes'),
	array('Coin Stack 53','Thebes','No','Yes'),
	array('Coin Stack 53','Therma','No','Yes'),
	array('Coin Stack 54','Apollonia','No','Yes'),
	array('Coin Stack 54','Argos','No','Yes'),
	array('Coin Stack 54','Chalies','No','Yes'),
	array('Coin Stack 54','Chicos','No','Yes'),
	array('Coin Stack 54','Concyra','No','Yes'),
	array('Coin Stack 54','Corinth','No','Yes'),
	array('Coin Stack 54','Cydonia','No','Yes'),
	array('Coin Stack 54','Delos','No','Yes'),
	array('Coin Stack 54','Delphi','No','Yes'),
	array('Coin Stack 54','Ephesus','No','Yes'),
	array('Coin Stack 54','Halicarnassus','No','Yes'),
	array('Coin Stack 54','Ilium','No','Yes'),
	array('Coin Stack 54','Imbros','No','Yes'),
	array('Coin Stack 54','Ithaca','No','Yes'),
	array('Coin Stack 54','Knossos','No','Yes'),
	array('Coin Stack 54','Laodicoa','No','Yes'),
	array('Coin Stack 54','Larissa','No','Yes'),
	array('Coin Stack 54','Lesbos','No','Yes'),
	array('Coin Stack 54','Melos','No','Yes'),
	array('Coin Stack 54','Messenia','No','Yes'),
	array('Coin Stack 54','Miletus','No','Yes'),
	array('Coin Stack 54','Naxos','No','Yes'),
	array('Coin Stack 54','Olympia','No','Yes'),
	array('Coin Stack 54','Pergamum','No','Yes'),
	array('Coin Stack 54','Samos','No','Yes'),
	array('Coin Stack 54','Thassos','No','Yes'),
	array('Coin Stack 54','Thebes','No','Yes'),
	array('Coin Stack 54','Therma','No','Yes'),
	array('Coin Stack 61','Apollonia','No','Yes'),
	array('Coin Stack 61','Argos','No','Yes'),
	array('Coin Stack 61','Chalies','No','Yes'),
	array('Coin Stack 61','Chicos','No','Yes'),
	array('Coin Stack 61','Concyra','No','Yes'),
	array('Coin Stack 61','Corinth','No','Yes'),
	array('Coin Stack 61','Cydonia','No','Yes'),
	array('Coin Stack 61','Delos','No','Yes'),
	array('Coin Stack 61','Delphi','No','Yes'),
	array('Coin Stack 61','Ephesus','No','Yes'),
	array('Coin Stack 61','Halicarnassus','No','Yes'),
	array('Coin Stack 61','Ilium','No','Yes'),
	array('Coin Stack 61','Imbros','No','Yes'),
	array('Coin Stack 61','Ithaca','No','Yes'),
	array('Coin Stack 61','Knossos','No','Yes'),
	array('Coin Stack 61','Laodicoa','No','Yes'),
	array('Coin Stack 61','Larissa','No','Yes'),
	array('Coin Stack 61','Lesbos','No','Yes'),
	array('Coin Stack 61','Melos','No','Yes'),
	array('Coin Stack 61','Messenia','No','Yes'),
	array('Coin Stack 61','Miletus','No','Yes'),
	array('Coin Stack 61','Naxos','No','Yes'),
	array('Coin Stack 61','Olympia','No','Yes'),
	array('Coin Stack 61','Pergamum','No','Yes'),
	array('Coin Stack 61','Samos','No','Yes'),
	array('Coin Stack 61','Thassos','No','Yes'),
	array('Coin Stack 61','Thebes','No','Yes'),
	array('Coin Stack 61','Therma','No','Yes'),
	array('Coin Stack 62','Apollonia','No','Yes'),
	array('Coin Stack 62','Argos','No','Yes'),
	array('Coin Stack 62','Chalies','No','Yes'),
	array('Coin Stack 62','Chicos','No','Yes'),
	array('Coin Stack 62','Concyra','No','Yes'),
	array('Coin Stack 62','Corinth','No','Yes'),
	array('Coin Stack 62','Cydonia','No','Yes'),
	array('Coin Stack 62','Delos','No','Yes'),
	array('Coin Stack 62','Delphi','No','Yes'),
	array('Coin Stack 62','Ephesus','No','Yes'),
	array('Coin Stack 62','Halicarnassus','No','Yes'),
	array('Coin Stack 62','Ilium','No','Yes'),
	array('Coin Stack 62','Imbros','No','Yes'),
	array('Coin Stack 62','Ithaca','No','Yes'),
	array('Coin Stack 62','Knossos','No','Yes'),
	array('Coin Stack 62','Laodicoa','No','Yes'),
	array('Coin Stack 62','Larissa','No','Yes'),
	array('Coin Stack 62','Lesbos','No','Yes'),
	array('Coin Stack 62','Melos','No','Yes'),
	array('Coin Stack 62','Messenia','No','Yes'),
	array('Coin Stack 62','Miletus','No','Yes'),
	array('Coin Stack 62','Naxos','No','Yes'),
	array('Coin Stack 62','Olympia','No','Yes'),
	array('Coin Stack 62','Pergamum','No','Yes'),
	array('Coin Stack 62','Samos','No','Yes'),
	array('Coin Stack 62','Thassos','No','Yes'),
	array('Coin Stack 62','Thebes','No','Yes'),
	array('Coin Stack 62','Therma','No','Yes'),
	array('Coin Stack 63','Apollonia','No','Yes'),
	array('Coin Stack 63','Argos','No','Yes'),
	array('Coin Stack 63','Chalies','No','Yes'),
	array('Coin Stack 63','Chicos','No','Yes'),
	array('Coin Stack 63','Concyra','No','Yes'),
	array('Coin Stack 63','Corinth','No','Yes'),
	array('Coin Stack 63','Cydonia','No','Yes'),
	array('Coin Stack 63','Delos','No','Yes'),
	array('Coin Stack 63','Delphi','No','Yes'),
	array('Coin Stack 63','Ephesus','No','Yes'),
	array('Coin Stack 63','Halicarnassus','No','Yes'),
	array('Coin Stack 63','Ilium','No','Yes'),
	array('Coin Stack 63','Imbros','No','Yes'),
	array('Coin Stack 63','Ithaca','No','Yes'),
	array('Coin Stack 63','Knossos','No','Yes'),
	array('Coin Stack 63','Laodicoa','No','Yes'),
	array('Coin Stack 63','Larissa','No','Yes'),
	array('Coin Stack 63','Lesbos','No','Yes'),
	array('Coin Stack 63','Melos','No','Yes'),
	array('Coin Stack 63','Messenia','No','Yes'),
	array('Coin Stack 63','Miletus','No','Yes'),
	array('Coin Stack 63','Naxos','No','Yes'),
	array('Coin Stack 63','Olympia','No','Yes'),
	array('Coin Stack 63','Pergamum','No','Yes'),
	array('Coin Stack 63','Samos','No','Yes'),
	array('Coin Stack 63','Thassos','No','Yes'),
	array('Coin Stack 63','Thebes','No','Yes'),
	array('Coin Stack 63','Therma','No','Yes'),
	array('Coin Stack 64','Apollonia','No','Yes'),
	array('Coin Stack 64','Argos','No','Yes'),
	array('Coin Stack 64','Chalies','No','Yes'),
	array('Coin Stack 64','Chicos','No','Yes'),
	array('Coin Stack 64','Concyra','No','Yes'),
	array('Coin Stack 64','Corinth','No','Yes'),
	array('Coin Stack 64','Cydonia','No','Yes'),
	array('Coin Stack 64','Delos','No','Yes'),
	array('Coin Stack 64','Delphi','No','Yes'),
	array('Coin Stack 64','Ephesus','No','Yes'),
	array('Coin Stack 64','Halicarnassus','No','Yes'),
	array('Coin Stack 64','Ilium','No','Yes'),
	array('Coin Stack 64','Imbros','No','Yes'),
	array('Coin Stack 64','Ithaca','No','Yes'),
	array('Coin Stack 64','Knossos','No','Yes'),
	array('Coin Stack 64','Laodicoa','No','Yes'),
	array('Coin Stack 64','Larissa','No','Yes'),
	array('Coin Stack 64','Lesbos','No','Yes'),
	array('Coin Stack 64','Melos','No','Yes'),
	array('Coin Stack 64','Messenia','No','Yes'),
	array('Coin Stack 64','Miletus','No','Yes'),
	array('Coin Stack 64','Naxos','No','Yes'),
	array('Coin Stack 64','Olympia','No','Yes'),
	array('Coin Stack 64','Pergamum','No','Yes'),
	array('Coin Stack 64','Samos','No','Yes'),
	array('Coin Stack 64','Thassos','No','Yes'),
	array('Coin Stack 64','Thebes','No','Yes'),
	array('Coin Stack 64','Therma','No','Yes')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

// Custom footer not changed by edit tool
InstallTerritory::runSQL($this->mapID);

// Remove the links to The Coin Stacks ... (you can only leave them)
global $DB;
$DB->sql_put('DELETE b FROM wD_Borders b
		INNER JOIN wD_Territories t ON (t.mapID=b.mapID AND b.toTerrID = t.id)
		WHERE t.mapID='.$this->mapID.' AND t.name LIKE "Coin Stack %"');

$DB->sql_put('DELETE b FROM wD_CoastalBorders b
		INNER JOIN wD_Territories t ON (t.mapID=b.mapID AND b.toTerrID = t.id)
		WHERE t.mapID='.$this->mapID.' AND t.name LIKE "Coin Stack %"');

InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>









