<?php
// This is file installs the map data for the TenSixtySix_V2 variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Lincolnshire', 'Coast', 'No', 1, 416, 569, 207, 286),
	array('York', 'Coast', 'Yes', 1, 412, 493, 206, 249),
	array('The Dales', 'Land', 'No', 1, 373, 489, 187, 234),
	array('Heart of England', 'Land', 'No', 1, 361, 593, 180, 296),
	array('Hadrian s Wall', 'Land', 'No', 3, 398, 436, 196, 217),
	array('Gwynedd and Lakes District', 'Coast', 'Yes', 4, 334, 483, 161, 248),
	array('Wales', 'Coast', 'No', 0, 252, 540, 129, 271),
	array('Norfolk', 'Coast', 'Yes', 1, 418, 645, 223, 303),
	array('London', 'Coast', 'Yes', 1, 383, 667, 183, 321),
	array('Hastings', 'Coast', 'No', 1, 344, 696, 171, 348),
	array('Winchester', 'Coast', 'Yes', 1, 221, 628, 114, 318),
	array('Winchester (South Coast)', 'Coast', 'No', 1, 273, 671, 116, 326),
	array('Winchester (West Coast)', 'Coast', 'No', 1, 222, 612, 125, 314),
	array('Cornwall', 'Coast', 'No', 0, 168, 635, 76, 322),
	array('Edinburgh', 'Coast', 'Yes', 4, 413, 398, 205, 190),
	array('Glasgow', 'Coast', 'Yes', 4, 313, 370, 154, 189),
	array('Highlands and Islands', 'Coast', 'No', 0, 408, 210, 204, 105),
	array('Oxford', 'Coast', 'Yes', 1, 300, 616, 150, 308),
	array('Dublin', 'Coast', 'Yes', 4, 216, 396, 107, 170),
	array('Waterford', 'Coast', 'No', 0, 140, 488, 41, 242),
	array('Firth of Clyde', 'Sea', 'No', 0, 292, 348, 147, 174),
	array('Irish Sea', 'Sea', 'No', 0, 236, 484, 114, 242),
	array('Mid Atlantic Ocean', 'Sea', 'No', 0, 58, 612, 29, 306),
	array('North Atlantic Ocean', 'Sea', 'No', 0, 138, 285, 26, 172),
	array('Bristol Channel', 'Sea', 'No', 0, 209, 584, 106, 295),
	array('North English Channel', 'Sea', 'No', 0, 294, 714, 149, 356),
	array('South English Channel', 'Sea', 'No', 0, 364, 745, 155, 384),
	array('Strait of Dover', 'Sea', 'No', 0, 398, 723, 197, 363),
	array('Thames Estuary', 'Sea', 'No', 0, 425, 678, 218, 338),
	array('Southwest North Sea', 'Sea', 'No', 0, 552, 590, 265, 306),
	array('Northwest North Sea', 'Sea', 'No', 0, 472, 431, 241, 228),
	array('Shetland and Orkneys', 'Sea', 'No', 0, 531, 276, 256, 145),
	array('Norwegian Sea', 'Sea', 'No', 0, 576, 67, 301, 36),
	array('Northeast North Sea', 'Sea', 'No', 0, 643, 285, 329, 92),
	array('Southeast North Sea', 'Sea', 'No', 0, 650, 472, 335, 232),
	array('Heligoland Bight', 'Sea', 'No', 0, 702, 564, 356, 278),
	array('Channel Islands', 'Sea', 'No', 0, 200, 767, 105, 379),
	array('Skagerrak', 'Sea', 'No', 0, 826, 378, 426, 183),
	array('Baltic Sea', 'Sea', 'No', 0, 953, 631, 503, 290),
	array('Denmark', 'Coast', 'Yes', 4, 804, 478, 405, 239),
	array('Danish Islands', 'Coast', 'No', 0, 863, 559, 432, 280),
	array('Götaland', 'Coast', 'No', 0, 956, 534, 475, 260),
	array('Sweden', 'Coast', 'Yes', 4, 1044, 417, 529, 196),
	array('Finnland', 'Coast', 'No', 0, 1133, 348, 565, 177),
	array('Oslo', 'Coast', 'Yes', 3, 898, 320, 450, 171),
	array('Bergen', 'Coast', 'No', 3, 731, 222, 367, 110),
	array('Trondheim', 'Coast', 'Yes', 3, 798, 98, 402, 49),
	array('Kaupang', 'Coast', 'Yes', 3, 812, 337, 408, 168),
	array('Free Cities Passage', 'Coast', 'No', 0, 768, 626, 386, 312),
	array('County of Flanders', 'Coast', 'Yes', 4, 519, 733, 256, 366),
	array('Duchy of Brittany', 'Coast', 'Yes', 4, 143, 757, 74, 382),
	array('Ecclesiastes', 'Coast', 'No', 0, 430, 740, 216, 371),
	array('Rouen', 'Coast', 'Yes', 2, 398, 765, 200, 382),
	array('Caen', 'Coast', 'Yes', 2, 366, 788, 180, 390),
	array('Bayeux', 'Coast', 'Yes', 2, 262, 772, 131, 386),
	array('Mont Saint-Michel', 'Coast', 'No', 2, 221, 799, 112, 401),
	array('Maine', 'Coast', 'No', 0, 310, 853, 141, 426),
	array('Central North Sea', 'Sea', 'No', 0, 543, 450, 275, 216),
	array('Free Cities Passage (West Coast)', 'Coast', 'No', 0, 629, 635, 315, 318),
	array('Free Cities Passage (East Coast)', 'Coast', 'No', 0, 808, 614, 402, 308),
	array('Oxford (Atlantic Coast)', 'Coast', 'No', 1, 281, 613, 141, 306),
	array('Oxford (Thames Coast)', 'Coast', 'No', 1, 325, 636, 163, 319),
	array('Danish Islands (fake)', 'Land', 'No', 0, 840, 520, 420, 260),
	array('Sweden (fake)', 'Coast', 'No', 0, 964, 360, 482, 180),
	array('Dublin (fake)', 'Coast', 'No', 0, 242, 372, 121, 186),
	array('Oxford (fake)', 'Coast', 'No', 0, 330, 640, 165, 320),
	array('London (fake)', 'Coast', 'No', 0, 334, 652, 167, 326),
	array('Caen (fake)', 'Coast', 'No', 0, 332, 788, 166, 394),
	array('Maine (fake)', 'Coast', 'No', 0, 388, 856, 194, 428),
	array('Trondheim (fake)', 'Coast', 'No', 0, 1030, 98, 515, 49)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Lincolnshire','York','Yes','Yes'),
	array('Lincolnshire','Heart of England','No','Yes'),
	array('Lincolnshire','Norfolk','Yes','Yes'),
	array('Lincolnshire','Southwest North Sea','Yes','No'),
	array('Lincolnshire','Northwest North Sea','Yes','No'),
	array('York','The Dales','No','Yes'),
	array('York','Heart of England','No','Yes'),
	array('York','Hadrian s Wall','No','Yes'),
	array('York','Northwest North Sea','Yes','No'),
	array('The Dales','Heart of England','No','Yes'),
	array('The Dales','Hadrian s Wall','No','Yes'),
	array('The Dales','Gwynedd and Lakes District','No','Yes'),
	array('Heart of England','Gwynedd and Lakes District','No','Yes'),
	array('Heart of England','Wales','No','Yes'),
	array('Heart of England','Norfolk','No','Yes'),
	array('Heart of England','London','No','Yes'),
	array('Heart of England','Oxford','No','Yes'),
	array('Hadrian s Wall','Gwynedd and Lakes District','No','Yes'),
	array('Hadrian s Wall','Edinburgh','No','Yes'),
	array('Hadrian s Wall','Glasgow','No','Yes'),
	array('Gwynedd and Lakes District','Wales','Yes','Yes'),
	array('Gwynedd and Lakes District','Irish Sea','Yes','No'),
	array('Wales','Oxford','No','Yes'),
	array('Wales','Irish Sea','Yes','No'),
	array('Wales','Mid Atlantic Ocean','Yes','No'),
	array('Wales','Bristol Channel','Yes','No'),
	array('Wales','Oxford (Atlantic Coast)','Yes','No'),
	array('Norfolk','London','Yes','Yes'),
	array('Norfolk','Thames Estuary','Yes','No'),
	array('Norfolk','Southwest North Sea','Yes','No'),
	array('London','Hastings','Yes','Yes'),
	array('London','Winchester','No','Yes'),
	array('London','Oxford','No','Yes'),
	array('London','Thames Estuary','Yes','No'),
	array('London','Oxford (Thames Coast)','Yes','No'),
	array('Hastings','Winchester','No','Yes'),
	array('Hastings','Winchester (South Coast)','Yes','No'),
	array('Hastings','North English Channel','Yes','No'),
	array('Hastings','Strait of Dover','Yes','No'),
	array('Hastings','Thames Estuary','Yes','No'),
	array('Winchester','Cornwall','No','Yes'),
	array('Winchester','Oxford','No','Yes'),
	array('Winchester (South Coast)','Cornwall','Yes','No'),
	array('Winchester (South Coast)','North English Channel','Yes','No'),
	array('Winchester (West Coast)','Cornwall','Yes','No'),
	array('Winchester (West Coast)','Bristol Channel','Yes','No'),
	array('Winchester (West Coast)','Oxford (Atlantic Coast)','Yes','No'),
	array('Cornwall','Mid Atlantic Ocean','Yes','No'),
	array('Cornwall','Bristol Channel','Yes','No'),
	array('Cornwall','North English Channel','Yes','No'),
	array('Edinburgh','Glasgow','No','Yes'),
	array('Edinburgh','Highlands and Islands','Yes','Yes'),
	array('Edinburgh','Northwest North Sea','Yes','No'),
	array('Edinburgh','Shetland and Orkneys','Yes','No'),
	array('Glasgow','Highlands and Islands','Yes','Yes'),
	array('Glasgow','Firth of Clyde','Yes','No'),
	array('Glasgow','Irish Sea','Yes','No'),
	array('Highlands and Islands','Firth of Clyde','Yes','No'),
	array('Highlands and Islands','North Atlantic Ocean','Yes','No'),
	array('Highlands and Islands','Shetland and Orkneys','Yes','No'),
	array('Dublin','Waterford','Yes','Yes'),
	array('Dublin','Firth of Clyde','Yes','No'),
	array('Dublin','Irish Sea','Yes','No'),
	array('Dublin','North Atlantic Ocean','Yes','No'),
	array('Waterford','Irish Sea','Yes','No'),
	array('Waterford','Mid Atlantic Ocean','Yes','No'),
	array('Waterford','North Atlantic Ocean','Yes','No'),
	array('Firth of Clyde','Irish Sea','Yes','No'),
	array('Firth of Clyde','North Atlantic Ocean','Yes','No'),
	array('Irish Sea','Mid Atlantic Ocean','Yes','No'),
	array('Mid Atlantic Ocean','North Atlantic Ocean','Yes','No'),
	array('Mid Atlantic Ocean','Bristol Channel','Yes','No'),
	array('Mid Atlantic Ocean','North English Channel','Yes','No'),
	array('Mid Atlantic Ocean','Channel Islands','Yes','No'),
	array('Mid Atlantic Ocean','Duchy of Brittany','Yes','No'),
	array('North Atlantic Ocean','Shetland and Orkneys','Yes','No'),
	array('North Atlantic Ocean','Norwegian Sea','Yes','No'),
	array('Bristol Channel','Oxford (Atlantic Coast)','Yes','No'),
	array('North English Channel','South English Channel','Yes','No'),
	array('North English Channel','Strait of Dover','Yes','No'),
	array('North English Channel','Channel Islands','Yes','No'),
	array('South English Channel','Strait of Dover','Yes','No'),
	array('South English Channel','Channel Islands','Yes','No'),
	array('South English Channel','Rouen','Yes','No'),
	array('South English Channel','Caen','Yes','No'),
	array('South English Channel','Bayeux','Yes','No'),
	array('Strait of Dover','Thames Estuary','Yes','No'),
	array('Strait of Dover','Southwest North Sea','Yes','No'),
	array('Strait of Dover','County of Flanders','Yes','No'),
	array('Strait of Dover','Ecclesiastes','Yes','No'),
	array('Strait of Dover','Rouen','Yes','No'),
	array('Thames Estuary','Southwest North Sea','Yes','No'),
	array('Southwest North Sea','Northwest North Sea','Yes','No'),
	array('Southwest North Sea','Southeast North Sea','Yes','No'),
	array('Southwest North Sea','Heligoland Bight','Yes','No'),
	array('Southwest North Sea','County of Flanders','Yes','No'),
	array('Southwest North Sea','Central North Sea','Yes','No'),
	array('Southwest North Sea','Free Cities Passage (West Coast)','Yes','No'),
	array('Northwest North Sea','Shetland and Orkneys','Yes','No'),
	array('Northwest North Sea','Northeast North Sea','Yes','No'),
	array('Northwest North Sea','Central North Sea','Yes','No'),
	array('Shetland and Orkneys','Norwegian Sea','Yes','No'),
	array('Shetland and Orkneys','Northeast North Sea','Yes','No'),
	array('Norwegian Sea','Northeast North Sea','Yes','No'),
	array('Norwegian Sea','Trondheim','Yes','No'),
	array('Northeast North Sea','Southeast North Sea','Yes','No'),
	array('Northeast North Sea','Skagerrak','Yes','No'),
	array('Northeast North Sea','Bergen','Yes','No'),
	array('Northeast North Sea','Trondheim','Yes','No'),
	array('Northeast North Sea','Kaupang','Yes','No'),
	array('Northeast North Sea','Central North Sea','Yes','No'),
	array('Southeast North Sea','Heligoland Bight','Yes','No'),
	array('Southeast North Sea','Skagerrak','Yes','No'),
	array('Southeast North Sea','Denmark','Yes','No'),
	array('Southeast North Sea','Central North Sea','Yes','No'),
	array('Heligoland Bight','Denmark','Yes','No'),
	array('Heligoland Bight','Free Cities Passage (West Coast)','Yes','No'),
	array('Channel Islands','Duchy of Brittany','Yes','No'),
	array('Channel Islands','Bayeux','Yes','No'),
	array('Channel Islands','Mont Saint-Michel','Yes','No'),
	array('Skagerrak','Denmark','Yes','No'),
	array('Skagerrak','Danish Islands','Yes','No'),
	array('Skagerrak','Götaland','Yes','No'),
	array('Skagerrak','Oslo','Yes','No'),
	array('Skagerrak','Kaupang','Yes','No'),
	array('Baltic Sea','Denmark','Yes','No'),
	array('Baltic Sea','Danish Islands','Yes','No'),
	array('Baltic Sea','Götaland','Yes','No'),
	array('Baltic Sea','Sweden','Yes','No'),
	array('Baltic Sea','Finnland','Yes','No'),
	array('Baltic Sea','Free Cities Passage (East Coast)','Yes','No'),
	array('Denmark','Danish Islands','Yes','Yes'),
	array('Denmark','Free Cities Passage','No','Yes'),
	array('Denmark','Free Cities Passage (West Coast)','Yes','No'),
	array('Denmark','Free Cities Passage (East Coast)','Yes','No'),
	array('Danish Islands','Götaland','Yes','Yes'),
	array('Götaland','Sweden','Yes','Yes'),
	array('Götaland','Oslo','Yes','Yes'),
	array('Sweden','Finnland','Yes','Yes'),
	array('Sweden','Oslo','No','Yes'),
	array('Sweden','Trondheim','No','Yes'),
	array('Finnland','Trondheim','No','Yes'),
	array('Oslo','Trondheim','No','Yes'),
	array('Oslo','Kaupang','Yes','Yes'),
	array('Bergen','Trondheim','Yes','Yes'),
	array('Bergen','Kaupang','Yes','Yes'),
	array('Trondheim','Kaupang','No','Yes'),
	array('Free Cities Passage','County of Flanders','No','Yes'),
	array('County of Flanders','Ecclesiastes','Yes','Yes'),
	array('County of Flanders','Free Cities Passage (West Coast)','Yes','No'),
	array('Duchy of Brittany','Mont Saint-Michel','Yes','Yes'),
	array('Duchy of Brittany','Maine','No','Yes'),
	array('Ecclesiastes','Rouen','Yes','Yes'),
	array('Ecclesiastes','Caen','No','Yes'),
	array('Rouen','Caen','Yes','Yes'),
	array('Caen','Bayeux','Yes','Yes'),
	array('Caen','Maine','Yes','Yes'),
	array('Bayeux','Mont Saint-Michel','Yes','Yes'),
	array('Bayeux','Maine','No','Yes'),
	array('Mont Saint-Michel','Maine','No','Yes')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
