<?php
// This is file installs the map data for the FantasyWorld variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Ameland', 'Coast', 'Yes', 248, 35, 127, 16, 'Neutral'),
	array('Suomi', 'Coast', 'Yes', 661, 48, 367, 25, 'Neutral'),
	array('Frostisen', 'Coast', 'No', 458, 141, 249, 61, 'Jylland'),
	array('Thisted', 'Coast', 'Yes', 422, 172, 212, 84, 'Jylland'),
	array('Farberg', 'Coast', 'Yes', 487, 166, 244, 82, 'Jylland'),
	array('Kassel', 'Coast', 'Yes', 454, 237, 221, 117, 'Jylland'),
	array('Ulm', 'Land', 'No', 392, 271, 195, 134, 'Jylland'),
	array('Dramm', 'Coast', 'No', 370, 246, 184, 121, 'Jylland'),
	array('Rennes', 'Coast', 'Yes', 324, 294, 162, 143, 'Orleans'),
	array('Labrador', 'Coast', 'No', 275, 227, 136, 113, 'Orleans'),
	array('Charente', 'Coast', 'Yes', 237, 246, 113, 129, 'Orleans'),
	array('Segre', 'Coast', 'No', 231, 314, 121, 154, 'Orleans'),
	array('Amiens', 'Coast', 'Yes', 281, 311, 142, 155, 'Orleans'),
	array('Isere', 'Coast', 'No', 301, 348, 154, 171, 'Orleans'),
	array('Menin', 'Coast', 'Yes', 372, 355, 186, 178, 'Neutral'),
	array('Opole', 'Coast', 'Yes', 428, 360, 220, 164, 'Neutral'),
	array('Kootenay', 'Coast', 'No', 334, 440, 168, 234, 'New Foundland'),
	array('Kootenay (East Coast)', 'Coast', 'No', 360, 401, 175, 198, 'Neutral'),
	array('Kootenay (West Coast)', 'Coast', 'No', 309, 476, 160, 235, 'Neutral'),
	array('Albany', 'Coast', 'Yes', 334, 579, 167, 287, 'New Foundland'),
	array('Wallowa', 'Coast', 'No', 235, 560, 117, 278, 'New Foundland'),
	array('Pahau', 'Coast', 'Yes', 75, 640, 39, 318, 'Neutral'),
	array('Washington', 'Coast', 'Yes', 214, 662, 109, 335, 'New Foundland'),
	array('Hiawatha', 'Coast', 'No', 366, 671, 188, 333, 'New Foundland'),
	array('Columbus', 'Coast', 'Yes', 418, 583, 216, 313, 'New Foundland'),
	array('Inagua', 'Coast', 'Yes', 455, 657, 232, 327, 'Neutral'),
	array('Arizona', 'Coast', 'No', 371, 744, 207, 363, 'Valparaiso'),
	array('Merida', 'Coast', 'No', 495, 715, 250, 360, 'Valparaiso'),
	array('Veracruz', 'Coast', 'Yes', 459, 746, 228, 371, 'Valparaiso'),
	array('Cordoba', 'Coast', 'Yes', 413, 861, 207, 426, 'Valparaiso'),
	array('Coracoes', 'Coast', 'Yes', 410, 1010, 203, 504, 'Neutral'),
	array('Imataca', 'Coast', 'No', 463, 854, 230, 423, 'Valparaiso'),
	array('Cartagena', 'Coast', 'Yes', 495, 822, 249, 403, 'Valparaiso'),
	array('Cabot', 'Coast', 'Yes', 497, 493, 249, 245, 'Neutral'),
	array('Hierro', 'Coast', 'Yes', 629, 666, 318, 338, 'Neutral'),
	array('Usovo', 'Coast', 'Yes', 662, 283, 329, 150, 'Sakhalin'),
	array('Ibresi', 'Coast', 'No', 729, 244, 370, 116, 'Sakhalin'),
	array('Star', 'Coast', 'Yes', 703, 301, 357, 148, 'Sakhalin'),
	array('Sozh', 'Coast', 'No', 664, 361, 332, 181, 'Sakhalin'),
	array('Sudzha', 'Coast', 'Yes', 720, 362, 354, 180, 'Sakhalin'),
	array('Pena', 'Coast', 'No', 745, 313, 373, 157, 'Sakhalin'),
	array('Nemuro', 'Coast', 'Yes', 1055, 213, 529, 106, 'Kyushu'),
	array('Osumi', 'Coast', 'No', 973, 224, 487, 111, 'Kyushu'),
	array('Aldan', 'Coast', 'Yes', 912, 290, 455, 141, 'Neutral'),
	array('Jaipur', 'Coast', 'Yes', 851, 368, 416, 183, 'Rajasthan'),
	array('Takada', 'Coast', 'Yes', 995, 264, 501, 126, 'Kyushu'),
	array('Sakai', 'Coast', 'No', 1072, 272, 536, 135, 'Kyushu'),
	array('Taichun', 'Coast', 'Yes', 1111, 292, 556, 145, 'Neutral'),
	array('Shibata', 'Land', 'Yes', 954, 285, 474, 142, 'Kyushu'),
	array('Honavar', 'Land', 'No', 930, 340, 465, 169, 'Rajasthan'),
	array('Yum', 'Land', 'Yes', 994, 372, 497, 184, 'Neutral'),
	array('Yoshida', 'Land', 'No', 1018, 315, 510, 155, 'Kyushu'),
	array('Tsinan', 'Land', 'No', 1066, 372, 533, 187, 'Ming-tao'),
	array('Pinkiang', 'Coast', 'No', 1183, 357, 593, 172, 'Ming-tao'),
	array('Mingshui', 'Coast', 'Yes', 1147, 430, 575, 217, 'Ming-tao'),
	array('Shahpur', 'Coast', 'Yes', 926, 439, 465, 222, 'Rajasthan'),
	array('Hissar', 'Land', 'No', 1001, 468, 500, 233, 'Rajasthan'),
	array('Pegu', 'Coast', 'Yes', 1047, 517, 524, 268, 'Neutral'),
	array('Hanyin', 'Land', 'Yes', 1097, 478, 542, 235, 'Ming-tao'),
	array('Lintao', 'Coast', 'Yes', 1199, 518, 585, 234, 'Ming-tao'),
	array('Anking', 'Coast', 'No', 1142, 531, 567, 265, 'Ming-tao'),
	array('Tanjor', 'Coast', 'Yes', 913, 526, 457, 268, 'Rajasthan'),
	array('Nizamri', 'Land', 'Yes', 958, 540, 477, 266, 'Rajasthan'),
	array('Jothar', 'Land', 'No', 997, 536, 498, 267, 'Rajasthan'),
	array('Romang', 'Coast', 'No', 1047, 573, 526, 291, 'Arafura'),
	array('Shibam', 'Coast', 'No', 896, 587, 446, 292, 'Neutral'),
	array('Makalu', 'Land', 'No', 994, 583, 495, 291, 'Neutral'),
	array('Ifni', 'Coast', 'Yes', 850, 622, 421, 310, 'Neutral'),
	array('Matara', 'Land', 'Yes', 961, 646, 476, 340, 'Neutral'),
	array('Culion', 'Land', 'No', 1009, 657, 509, 343, 'Neutral'),
	array('Babar', 'Coast', 'Yes', 1072, 664, 536, 334, 'Arafura'),
	array('Serang', 'Coast', 'Yes', 1111, 615, 554, 305, 'Arafura'),
	array('Serang (North Coast)', 'Coast', 'No', 1108, 579, 564, 301, 'Neutral'),
	array('Serang (South Coast)', 'Coast', 'No', 1111, 655, 556, 329, 'Neutral'),
	array('Surabaya', 'Coast', 'No', 1152, 651, 577, 325, 'Arafura'),
	array('Surabaya (North Coast)', 'Coast', 'No', 1162, 640, 584, 323, 'Neutral'),
	array('Surabaya (South Coast)', 'Coast', 'No', 1156, 681, 583, 340, 'Neutral'),
	array('Davao', 'Coast', 'Yes', 1245, 658, 625, 327, 'Arafura'),
	array('Vinh', 'Coast', 'Yes', 1334, 565, 667, 284, 'Neutral'),
	array('Karet', 'Coast', 'Yes', 800, 669, 401, 334, 'Hamra'),
	array('Jazirah', 'Land', 'No', 870, 678, 443, 355, 'Hamra'),
	array('Khali', 'Land', 'No', 921, 698, 460, 347, 'Hamra'),
	array('Ubon', 'Land', 'Yes', 998, 719, 499, 360, 'Neutral'),
	array('Jolo', 'Coast', 'No', 1076, 704, 531, 350, 'Arafura'),
	array('Aouker', 'Coast', 'No', 775, 720, 383, 358, 'Hamra'),
	array('Marzuq', 'Land', 'Yes', 850, 742, 423, 370, 'Hamra'),
	array('Summan', 'Land', 'Yes', 934, 758, 452, 376, 'Hamra'),
	array('Tabou', 'Coast', 'Yes', 755, 758, 379, 383, 'Neutral'),
	array('Bambari', 'Coast', 'No', 760, 809, 377, 404, 'Lugulu'),
	array('Pagalu', 'Coast', 'Yes', 772, 862, 380, 435, 'Lugulu'),
	array('Gamba', 'Coast', 'No', 725, 883, 361, 440, 'Lugulu'),
	array('Eshowe', 'Coast', 'Yes', 804, 990, 400, 494, 'Lugulu'),
	array('Pebane', 'Coast', 'Yes', 804, 901, 395, 450, 'Lugulu'),
	array('Bukoba', 'Coast', 'No', 834, 855, 415, 416, 'Lugulu'),
	array('Ginir', 'Coast', 'Yes', 889, 830, 446, 417, 'Neutral'),
	array('Oron', 'Coast', 'Yes', 946, 856, 473, 428, 'Neutral'),
	array('Arak', 'Land', 'No', 986, 777, 491, 385, 'Ishfahan'),
	array('Shurab', 'Land', 'No', 1038, 755, 519, 376, 'Ishfahan'),
	array('Zarand', 'Land', 'Yes', 1022, 834, 505, 417, 'Ishfahan'),
	array('Zahedan', 'Coast', 'Yes', 1092, 788, 548, 395, 'Ishfahan'),
	array('Jahrom', 'Coast', 'No', 1052, 874, 530, 437, 'Ishfahan'),
	array('Dezful', 'Coast', 'Yes', 1019, 903, 512, 456, 'Ishfahan'),
	array('Kadmat', 'Coast', 'Yes', 1253, 807, 625, 404, 'Neutral'),
	array('North-West Ocean', 'Sea', 'No', 101, 124, 77, 92, 'Neutral'),
	array('North-North-West Ocean', 'Sea', 'No', 360, 108, 172, 54, 'Neutral'),
	array('Western Ocean', 'Sea', 'No', 105, 430, 62, 215, 'Neutral'),
	array('Gulf of Gasco', 'Sea', 'No', 268, 410, 137, 255, 'Neutral'),
	array('Empty Ocean', 'Sea', 'No', 130, 867, 134, 456, 'Neutral'),
	array('Gulf of Pahute', 'Sea', 'No', 334, 728, 152, 371, 'Neutral'),
	array('Gulf San Meties', 'Sea', 'No', 386, 831, 191, 416, 'Neutral'),
	array('Southern Ocean', 'Sea', 'No', 575, 975, 295, 483, 'Neutral'),
	array('South Sea', 'Sea', 'No', 589, 813, 295, 384, 'Neutral'),
	array('South-West Sea', 'Sea', 'No', 487, 585, 248, 294, 'Neutral'),
	array('Gulf of Boothia', 'Sea', 'No', 415, 444, 210, 218, 'Neutral'),
	array('Western Sea', 'Sea', 'No', 529, 355, 265, 169, 'Neutral'),
	array('North-West Sea', 'Sea', 'No', 599, 201, 301, 98, 'Neutral'),
	array('North-East Sea', 'Sea', 'No', 852, 189, 418, 92, 'Neutral'),
	array('East Central Sea', 'Sea', 'No', 749, 484, 372, 244, 'Neutral'),
	array('West Central Sea', 'Sea', 'No', 600, 463, 299, 256, 'Neutral'),
	array('Gulf of Mahanadi', 'Sea', 'No', 860, 481, 424, 239, 'Neutral'),
	array('South-East Sea', 'Sea', 'No', 697, 760, 347, 376, 'Neutral'),
	array('North-North-East Ocean', 'Sea', 'No', 940, 77, 476, 47, 'Neutral'),
	array('North-East Ocean', 'Sea', 'No', 1187, 161, 589, 94, 'Neutral'),
	array('Gulf of Toyama', 'Sea', 'No', 1060, 241, 529, 119, 'Neutral'),
	array('Eastern Ocean', 'Sea', 'No', 1286, 426, 636, 212, 'Neutral'),
	array('Gulf of Amboy', 'Sea', 'No', 1184, 579, 584, 289, 'Neutral'),
	array('Eastern Sea', 'Sea', 'No', 1321, 723, 661, 355, 'Neutral'),
	array('Gulf of Sunda', 'Sea', 'No', 1172, 733, 572, 363, 'Neutral'),
	array('South-East Ocean', 'Sea', 'No', 1229, 938, 609, 463, 'Neutral'),
	array('South-South-East Sea', 'Sea', 'No', 963, 1015, 479, 503, 'Neutral'),
	array('Gulf of Pembra', 'Sea', 'No', 861, 892, 426, 449, 'Neutral')
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $x, $y, $sx, $sy, $country)=$territoryRawRow;
	if( $country=='Neutral' )
		$countryID=0;
	else
		$countryID=$this->countryID($country);
		
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);
$bordersRawData=array(
	array('Ameland','North-West Ocean','Yes','No'),
	array('Ameland','North-North-West Ocean','Yes','No'),
	array('Suomi','North-North-West Ocean','Yes','No'),
	array('Suomi','North-West Sea','Yes','No'),
	array('Suomi','North-East Sea','Yes','No'),
	array('Suomi','North-North-East Ocean','Yes','No'),
	array('Frostisen','Thisted','Yes','Yes'),
	array('Frostisen','Farberg','Yes','Yes'),
	array('Frostisen','North-North-West Ocean','Yes','No'),
	array('Thisted','Frostisen','Yes','Yes'),
	array('Thisted','Farberg','No','Yes'),
	array('Thisted','Kassel','No','Yes'),
	array('Thisted','Dramm','Yes','Yes'),
	array('Thisted','North-North-West Ocean','Yes','No'),
	array('Farberg','Frostisen','Yes','Yes'),
	array('Farberg','Thisted','No','Yes'),
	array('Farberg','Kassel','Yes','Yes'),
	array('Farberg','North-North-West Ocean','Yes','No'),
	array('Farberg','North-West Sea','Yes','No'),
	array('Kassel','Thisted','No','Yes'),
	array('Kassel','Farberg','Yes','Yes'),
	array('Kassel','Ulm','No','Yes'),
	array('Kassel','Dramm','No','Yes'),
	array('Kassel','Opole','Yes','Yes'),
	array('Kassel','Western Sea','Yes','No'),
	array('Kassel','North-West Sea','Yes','No'),
	array('Ulm','Kassel','No','Yes'),
	array('Ulm','Dramm','No','Yes'),
	array('Ulm','Menin','No','Yes'),
	array('Ulm','Opole','No','Yes'),
	array('Dramm','Thisted','Yes','Yes'),
	array('Dramm','Kassel','No','Yes'),
	array('Dramm','Ulm','No','Yes'),
	array('Dramm','Rennes','Yes','Yes'),
	array('Dramm','Menin','No','Yes'),
	array('Dramm','North-North-West Ocean','Yes','No'),
	array('Rennes','Dramm','Yes','Yes'),
	array('Rennes','Labrador','Yes','Yes'),
	array('Rennes','Amiens','No','Yes'),
	array('Rennes','Isere','No','Yes'),
	array('Rennes','Menin','No','Yes'),
	array('Rennes','North-North-West Ocean','Yes','No'),
	array('Labrador','Rennes','Yes','Yes'),
	array('Labrador','Charente','Yes','Yes'),
	array('Labrador','Amiens','No','Yes'),
	array('Labrador','North-West Ocean','Yes','No'),
	array('Labrador','North-North-West Ocean','Yes','No'),
	array('Charente','Labrador','Yes','Yes'),
	array('Charente','Segre','Yes','Yes'),
	array('Charente','Amiens','No','Yes'),
	array('Charente','North-West Ocean','Yes','No'),
	array('Charente','Western Ocean','Yes','No'),
	array('Segre','Charente','Yes','Yes'),
	array('Segre','Amiens','Yes','Yes'),
	array('Segre','Western Ocean','Yes','No'),
	array('Segre','Gulf of Gasco','Yes','No'),
	array('Amiens','Rennes','No','Yes'),
	array('Amiens','Labrador','No','Yes'),
	array('Amiens','Charente','No','Yes'),
	array('Amiens','Segre','Yes','Yes'),
	array('Amiens','Isere','Yes','Yes'),
	array('Amiens','Gulf of Gasco','Yes','No'),
	array('Isere','Rennes','No','Yes'),
	array('Isere','Amiens','Yes','Yes'),
	array('Isere','Menin','No','Yes'),
	array('Isere','Kootenay','No','Yes'),
	array('Isere','Kootenay (West Coast)','Yes','No'),
	array('Isere','Gulf of Gasco','Yes','No'),
	array('Menin','Ulm','No','Yes'),
	array('Menin','Dramm','No','Yes'),
	array('Menin','Rennes','No','Yes'),
	array('Menin','Isere','No','Yes'),
	array('Menin','Opole','Yes','Yes'),
	array('Menin','Kootenay','No','Yes'),
	array('Menin','Kootenay (East Coast)','Yes','No'),
	array('Menin','Gulf of Boothia','Yes','No'),
	array('Opole','Kassel','Yes','Yes'),
	array('Opole','Ulm','No','Yes'),
	array('Opole','Menin','Yes','Yes'),
	array('Opole','Gulf of Boothia','Yes','No'),
	array('Opole','Western Sea','Yes','No'),
	array('Kootenay','Isere','No','Yes'),
	array('Kootenay','Menin','No','Yes'),
	array('Kootenay','Albany','No','Yes'),
	array('Kootenay','Columbus','No','Yes'),
	array('Kootenay (East Coast)','Menin','Yes','No'),
	array('Kootenay (East Coast)','Columbus','Yes','No'),
	array('Kootenay (East Coast)','Gulf of Boothia','Yes','No'),
	array('Kootenay (West Coast)','Isere','Yes','No'),
	array('Kootenay (West Coast)','Albany','Yes','No'),
	array('Kootenay (West Coast)','Gulf of Gasco','Yes','No'),
	array('Albany','Kootenay','No','Yes'),
	array('Albany','Kootenay (West Coast)','Yes','No'),
	array('Albany','Wallowa','Yes','Yes'),
	array('Albany','Washington','No','Yes'),
	array('Albany','Hiawatha','No','Yes'),
	array('Albany','Columbus','No','Yes'),
	array('Albany','Gulf of Gasco','Yes','No'),
	array('Wallowa','Albany','Yes','Yes'),
	array('Wallowa','Washington','Yes','Yes'),
	array('Wallowa','Western Ocean','Yes','No'),
	array('Wallowa','Gulf of Gasco','Yes','No'),
	array('Pahau','Western Ocean','Yes','No'),
	array('Pahau','Empty Ocean','Yes','No'),
	array('Washington','Albany','No','Yes'),
	array('Washington','Wallowa','Yes','Yes'),
	array('Washington','Hiawatha','Yes','Yes'),
	array('Washington','Western Ocean','Yes','No'),
	array('Washington','Empty Ocean','Yes','No'),
	array('Washington','Gulf of Pahute','Yes','No'),
	array('Hiawatha','Albany','No','Yes'),
	array('Hiawatha','Washington','Yes','Yes'),
	array('Hiawatha','Columbus','No','Yes'),
	array('Hiawatha','Inagua','No','Yes'),
	array('Hiawatha','Arizona','Yes','Yes'),
	array('Hiawatha','Merida','No','Yes'),
	array('Hiawatha','Gulf of Pahute','Yes','No'),
	array('Columbus','Kootenay','No','Yes'),
	array('Columbus','Kootenay (East Coast)','Yes','No'),
	array('Columbus','Albany','No','Yes'),
	array('Columbus','Hiawatha','No','Yes'),
	array('Columbus','Inagua','Yes','Yes'),
	array('Columbus','South-West Sea','Yes','No'),
	array('Columbus','Gulf of Boothia','Yes','No'),
	array('Inagua','Hiawatha','No','Yes'),
	array('Inagua','Columbus','Yes','Yes'),
	array('Inagua','Merida','Yes','Yes'),
	array('Inagua','South-West Sea','Yes','No'),
	array('Arizona','Hiawatha','Yes','Yes'),
	array('Arizona','Merida','No','Yes'),
	array('Arizona','Veracruz','Yes','Yes'),
	array('Arizona','Gulf of Pahute','Yes','No'),
	array('Arizona','Gulf San Meties','Yes','No'),
	array('Merida','Hiawatha','No','Yes'),
	array('Merida','Inagua','Yes','Yes'),
	array('Merida','Arizona','No','Yes'),
	array('Merida','Veracruz','No','Yes'),
	array('Merida','Cartagena','Yes','Yes'),
	array('Merida','South Sea','Yes','No'),
	array('Merida','South-West Sea','Yes','No'),
	array('Veracruz','Arizona','Yes','Yes'),
	array('Veracruz','Merida','No','Yes'),
	array('Veracruz','Cordoba','Yes','Yes'),
	array('Veracruz','Imataca','No','Yes'),
	array('Veracruz','Cartagena','No','Yes'),
	array('Veracruz','Gulf San Meties','Yes','No'),
	array('Cordoba','Veracruz','Yes','Yes'),
	array('Cordoba','Imataca','Yes','Yes'),
	array('Cordoba','Empty Ocean','Yes','No'),
	array('Cordoba','Gulf San Meties','Yes','No'),
	array('Cordoba','Southern Ocean','Yes','No'),
	array('Coracoes','Empty Ocean','Yes','No'),
	array('Coracoes','Southern Ocean','Yes','No'),
	array('Imataca','Veracruz','No','Yes'),
	array('Imataca','Cordoba','Yes','Yes'),
	array('Imataca','Cartagena','Yes','Yes'),
	array('Imataca','Southern Ocean','Yes','No'),
	array('Cartagena','Merida','Yes','Yes'),
	array('Cartagena','Veracruz','No','Yes'),
	array('Cartagena','Imataca','Yes','Yes'),
	array('Cartagena','Southern Ocean','Yes','No'),
	array('Cartagena','South Sea','Yes','No'),
	array('Cabot','South-West Sea','Yes','No'),
	array('Cabot','Gulf of Boothia','Yes','No'),
	array('Cabot','Western Sea','Yes','No'),
	array('Cabot','West Central Sea','Yes','No'),
	array('Hierro','South Sea','Yes','No'),
	array('Hierro','South-West Sea','Yes','No'),
	array('Hierro','East Central Sea','Yes','No'),
	array('Hierro','West Central Sea','Yes','No'),
	array('Hierro','South-East Sea','Yes','No'),
	array('Usovo','Ibresi','Yes','Yes'),
	array('Usovo','Star','No','Yes'),
	array('Usovo','Sozh','Yes','Yes'),
	array('Usovo','Western Sea','Yes','No'),
	array('Usovo','North-West Sea','Yes','No'),
	array('Ibresi','Usovo','Yes','Yes'),
	array('Ibresi','Star','Yes','Yes'),
	array('Ibresi','North-West Sea','Yes','No'),
	array('Ibresi','North-East Sea','Yes','No'),
	array('Star','Usovo','No','Yes'),
	array('Star','Ibresi','Yes','Yes'),
	array('Star','Sozh','No','Yes'),
	array('Star','Sudzha','No','Yes'),
	array('Star','Pena','Yes','Yes'),
	array('Star','North-East Sea','Yes','No'),
	array('Sozh','Usovo','Yes','Yes'),
	array('Sozh','Star','No','Yes'),
	array('Sozh','Sudzha','Yes','Yes'),
	array('Sozh','Western Sea','Yes','No'),
	array('Sozh','West Central Sea','Yes','No'),
	array('Sudzha','Star','No','Yes'),
	array('Sudzha','Sozh','Yes','Yes'),
	array('Sudzha','Pena','Yes','Yes'),
	array('Sudzha','East Central Sea','Yes','No'),
	array('Sudzha','West Central Sea','Yes','No'),
	array('Pena','Star','Yes','Yes'),
	array('Pena','Sudzha','Yes','Yes'),
	array('Pena','North-East Sea','Yes','No'),
	array('Pena','East Central Sea','Yes','No'),
	array('Nemuro','Osumi','Yes','Yes'),
	array('Nemuro','Takada','Yes','Yes'),
	array('Nemuro','North-East Sea','Yes','No'),
	array('Nemuro','North-North-East Ocean','Yes','No'),
	array('Nemuro','North-East Ocean','Yes','No'),
	array('Nemuro','Gulf of Toyama','Yes','No'),
	array('Osumi','Nemuro','Yes','Yes'),
	array('Osumi','Aldan','Yes','Yes'),
	array('Osumi','Takada','No','Yes'),
	array('Osumi','Shibata','No','Yes'),
	array('Osumi','North-East Sea','Yes','No'),
	array('Aldan','Osumi','Yes','Yes'),
	array('Aldan','Jaipur','Yes','Yes'),
	array('Aldan','Shibata','No','Yes'),
	array('Aldan','Honavar','No','Yes'),
	array('Aldan','North-East Sea','Yes','No'),
	array('Jaipur','Aldan','Yes','Yes'),
	array('Jaipur','Honavar','No','Yes'),
	array('Jaipur','Shahpur','Yes','Yes'),
	array('Jaipur','North-East Sea','Yes','No'),
	array('Jaipur','East Central Sea','Yes','No'),
	array('Jaipur','Gulf of Mahanadi','Yes','No'),
	array('Takada','Nemuro','Yes','Yes'),
	array('Takada','Osumi','No','Yes'),
	array('Takada','Sakai','Yes','Yes'),
	array('Takada','Shibata','No','Yes'),
	array('Takada','Yoshida','No','Yes'),
	array('Takada','Gulf of Toyama','Yes','No'),
	array('Sakai','Takada','Yes','Yes'),
	array('Sakai','Taichun','Yes','Yes'),
	array('Sakai','Yoshida','No','Yes'),
	array('Sakai','North-East Ocean','Yes','No'),
	array('Sakai','Gulf of Toyama','Yes','No'),
	array('Taichun','Sakai','Yes','Yes'),
	array('Taichun','Yoshida','No','Yes'),
	array('Taichun','Tsinan','No','Yes'),
	array('Taichun','Pinkiang','Yes','Yes'),
	array('Taichun','North-East Ocean','Yes','No'),
	array('Shibata','Osumi','No','Yes'),
	array('Shibata','Aldan','No','Yes'),
	array('Shibata','Takada','No','Yes'),
	array('Shibata','Honavar','No','Yes'),
	array('Shibata','Yoshida','No','Yes'),
	array('Honavar','Aldan','No','Yes'),
	array('Honavar','Jaipur','No','Yes'),
	array('Honavar','Shibata','No','Yes'),
	array('Honavar','Yum','No','Yes'),
	array('Honavar','Yoshida','No','Yes'),
	array('Honavar','Shahpur','No','Yes'),
	array('Yum','Honavar','No','Yes'),
	array('Yum','Yoshida','No','Yes'),
	array('Yum','Tsinan','No','Yes'),
	array('Yum','Shahpur','No','Yes'),
	array('Yum','Hissar','No','Yes'),
	array('Yoshida','Takada','No','Yes'),
	array('Yoshida','Sakai','No','Yes'),
	array('Yoshida','Taichun','No','Yes'),
	array('Yoshida','Shibata','No','Yes'),
	array('Yoshida','Honavar','No','Yes'),
	array('Yoshida','Yum','No','Yes'),
	array('Yoshida','Tsinan','No','Yes'),
	array('Tsinan','Taichun','No','Yes'),
	array('Tsinan','Yum','No','Yes'),
	array('Tsinan','Yoshida','No','Yes'),
	array('Tsinan','Pinkiang','No','Yes'),
	array('Tsinan','Mingshui','No','Yes'),
	array('Tsinan','Hissar','No','Yes'),
	array('Tsinan','Pegu','No','Yes'),
	array('Tsinan','Hanyin','No','Yes'),
	array('Pinkiang','Taichun','Yes','Yes'),
	array('Pinkiang','Tsinan','No','Yes'),
	array('Pinkiang','Mingshui','Yes','Yes'),
	array('Pinkiang','North-East Ocean','Yes','No'),
	array('Pinkiang','Eastern Ocean','Yes','No'),
	array('Mingshui','Tsinan','No','Yes'),
	array('Mingshui','Pinkiang','Yes','Yes'),
	array('Mingshui','Hanyin','No','Yes'),
	array('Mingshui','Lintao','Yes','Yes'),
	array('Mingshui','Eastern Ocean','Yes','No'),
	array('Shahpur','Jaipur','Yes','Yes'),
	array('Shahpur','Honavar','No','Yes'),
	array('Shahpur','Yum','No','Yes'),
	array('Shahpur','Hissar','No','Yes'),
	array('Shahpur','Tanjor','Yes','Yes'),
	array('Shahpur','Nizamri','No','Yes'),
	array('Shahpur','Gulf of Mahanadi','Yes','No'),
	array('Hissar','Yum','No','Yes'),
	array('Hissar','Tsinan','No','Yes'),
	array('Hissar','Shahpur','No','Yes'),
	array('Hissar','Pegu','No','Yes'),
	array('Hissar','Nizamri','No','Yes'),
	array('Hissar','Jothar','No','Yes'),
	array('Pegu','Tsinan','No','Yes'),
	array('Pegu','Hissar','No','Yes'),
	array('Pegu','Hanyin','No','Yes'),
	array('Pegu','Anking','Yes','Yes'),
	array('Pegu','Jothar','No','Yes'),
	array('Pegu','Romang','Yes','Yes'),
	array('Pegu','Gulf of Amboy','Yes','No'),
	array('Hanyin','Tsinan','No','Yes'),
	array('Hanyin','Mingshui','No','Yes'),
	array('Hanyin','Pegu','No','Yes'),
	array('Hanyin','Lintao','No','Yes'),
	array('Hanyin','Anking','No','Yes'),
	array('Lintao','Mingshui','Yes','Yes'),
	array('Lintao','Hanyin','No','Yes'),
	array('Lintao','Anking','Yes','Yes'),
	array('Lintao','Eastern Ocean','Yes','No'),
	array('Lintao','Gulf of Amboy','Yes','No'),
	array('Anking','Pegu','Yes','Yes'),
	array('Anking','Hanyin','No','Yes'),
	array('Anking','Lintao','Yes','Yes'),
	array('Anking','Gulf of Amboy','Yes','No'),
	array('Tanjor','Shahpur','Yes','Yes'),
	array('Tanjor','Nizamri','No','Yes'),
	array('Tanjor','Shibam','Yes','Yes'),
	array('Tanjor','Gulf of Mahanadi','Yes','No'),
	array('Nizamri','Shahpur','No','Yes'),
	array('Nizamri','Hissar','No','Yes'),
	array('Nizamri','Tanjor','No','Yes'),
	array('Nizamri','Jothar','No','Yes'),
	array('Nizamri','Shibam','No','Yes'),
	array('Nizamri','Makalu','No','Yes'),
	array('Jothar','Hissar','No','Yes'),
	array('Jothar','Pegu','No','Yes'),
	array('Jothar','Nizamri','No','Yes'),
	array('Jothar','Romang','No','Yes'),
	array('Jothar','Makalu','No','Yes'),
	array('Romang','Pegu','Yes','Yes'),
	array('Romang','Jothar','No','Yes'),
	array('Romang','Makalu','No','Yes'),
	array('Romang','Babar','No','Yes'),
	array('Romang','Serang','No','Yes'),
	array('Romang','Serang (North Coast)','Yes','No'),
	array('Romang','Gulf of Amboy','Yes','No'),
	array('Shibam','Tanjor','Yes','Yes'),
	array('Shibam','Nizamri','No','Yes'),
	array('Shibam','Makalu','No','Yes'),
	array('Shibam','Ifni','Yes','Yes'),
	array('Shibam','Matara','No','Yes'),
	array('Shibam','Gulf of Mahanadi','Yes','No'),
	array('Makalu','Nizamri','No','Yes'),
	array('Makalu','Jothar','No','Yes'),
	array('Makalu','Romang','No','Yes'),
	array('Makalu','Shibam','No','Yes'),
	array('Makalu','Matara','No','Yes'),
	array('Makalu','Culion','No','Yes'),
	array('Makalu','Babar','No','Yes'),
	array('Ifni','Shibam','Yes','Yes'),
	array('Ifni','Matara','No','Yes'),
	array('Ifni','Karet','Yes','Yes'),
	array('Ifni','Jazirah','No','Yes'),
	array('Ifni','Khali','No','Yes'),
	array('Ifni','East Central Sea','Yes','No'),
	array('Ifni','Gulf of Mahanadi','Yes','No'),
	array('Matara','Shibam','No','Yes'),
	array('Matara','Makalu','No','Yes'),
	array('Matara','Ifni','No','Yes'),
	array('Matara','Culion','No','Yes'),
	array('Matara','Khali','No','Yes'),
	array('Matara','Ubon','No','Yes'),
	array('Culion','Makalu','No','Yes'),
	array('Culion','Matara','No','Yes'),
	array('Culion','Babar','No','Yes'),
	array('Culion','Ubon','No','Yes'),
	array('Culion','Jolo','No','Yes'),
	array('Babar','Romang','No','Yes'),
	array('Babar','Makalu','No','Yes'),
	array('Babar','Culion','No','Yes'),
	array('Babar','Serang','No','Yes'),
	array('Babar','Serang (South Coast)','Yes','No'),
	array('Babar','Jolo','Yes','Yes'),
	array('Babar','Gulf of Sunda','Yes','No'),
	array('Serang','Romang','No','Yes'),
	array('Serang','Babar','No','Yes'),
	array('Serang','Surabaya','No','Yes'),
	array('Serang (North Coast)','Romang','Yes','No'),
	array('Serang (North Coast)','Surabaya (North Coast)','Yes','No'),
	array('Serang (North Coast)','Gulf of Amboy','Yes','No'),
	array('Serang (South Coast)','Babar','Yes','No'),
	array('Serang (South Coast)','Surabaya (South Coast)','Yes','No'),
	array('Serang (South Coast)','Gulf of Sunda','Yes','No'),
	array('Surabaya','Serang','No','Yes'),
	array('Surabaya','Davao','No','Yes'),
	array('Surabaya (North Coast)','Serang (North Coast)','Yes','No'),
	array('Surabaya (North Coast)','Davao','Yes','No'),
	array('Surabaya (North Coast)','Gulf of Amboy','Yes','No'),
	array('Surabaya (South Coast)','Serang (South Coast)','Yes','No'),
	array('Surabaya (South Coast)','Davao','Yes','No'),
	array('Surabaya (South Coast)','Gulf of Sunda','Yes','No'),
	array('Davao','Surabaya','No','Yes'),
	array('Davao','Surabaya (North Coast)','Yes','No'),
	array('Davao','Surabaya (South Coast)','Yes','No'),
	array('Davao','Gulf of Amboy','Yes','No'),
	array('Davao','Eastern Sea','Yes','No'),
	array('Davao','Gulf of Sunda','Yes','No'),
	array('Vinh','Eastern Ocean','Yes','No'),
	array('Vinh','Gulf of Amboy','Yes','No'),
	array('Vinh','Eastern Sea','Yes','No'),
	array('Karet','Ifni','Yes','Yes'),
	array('Karet','Jazirah','No','Yes'),
	array('Karet','Aouker','Yes','Yes'),
	array('Karet','Marzuq','No','Yes'),
	array('Karet','East Central Sea','Yes','No'),
	array('Karet','South-East Sea','Yes','No'),
	array('Jazirah','Ifni','No','Yes'),
	array('Jazirah','Karet','No','Yes'),
	array('Jazirah','Khali','No','Yes'),
	array('Jazirah','Marzuq','No','Yes'),
	array('Jazirah','Summan','No','Yes'),
	array('Khali','Ifni','No','Yes'),
	array('Khali','Matara','No','Yes'),
	array('Khali','Jazirah','No','Yes'),
	array('Khali','Ubon','No','Yes'),
	array('Khali','Summan','No','Yes'),
	array('Ubon','Matara','No','Yes'),
	array('Ubon','Culion','No','Yes'),
	array('Ubon','Khali','No','Yes'),
	array('Ubon','Jolo','No','Yes'),
	array('Ubon','Summan','No','Yes'),
	array('Ubon','Arak','No','Yes'),
	array('Ubon','Shurab','No','Yes'),
	array('Jolo','Culion','No','Yes'),
	array('Jolo','Babar','Yes','Yes'),
	array('Jolo','Ubon','No','Yes'),
	array('Jolo','Shurab','No','Yes'),
	array('Jolo','Zahedan','Yes','Yes'),
	array('Jolo','Gulf of Sunda','Yes','No'),
	array('Aouker','Karet','Yes','Yes'),
	array('Aouker','Marzuq','No','Yes'),
	array('Aouker','Tabou','Yes','Yes'),
	array('Aouker','Bambari','No','Yes'),
	array('Aouker','South-East Sea','Yes','No'),
	array('Marzuq','Karet','No','Yes'),
	array('Marzuq','Jazirah','No','Yes'),
	array('Marzuq','Aouker','No','Yes'),
	array('Marzuq','Summan','No','Yes'),
	array('Marzuq','Bambari','No','Yes'),
	array('Marzuq','Bukoba','No','Yes'),
	array('Marzuq','Ginir','No','Yes'),
	array('Summan','Jazirah','No','Yes'),
	array('Summan','Khali','No','Yes'),
	array('Summan','Ubon','No','Yes'),
	array('Summan','Marzuq','No','Yes'),
	array('Summan','Ginir','No','Yes'),
	array('Summan','Oron','No','Yes'),
	array('Summan','Arak','No','Yes'),
	array('Tabou','Aouker','Yes','Yes'),
	array('Tabou','Bambari','Yes','Yes'),
	array('Tabou','South-East Sea','Yes','No'),
	array('Bambari','Aouker','No','Yes'),
	array('Bambari','Marzuq','No','Yes'),
	array('Bambari','Tabou','Yes','Yes'),
	array('Bambari','Pagalu','Yes','Yes'),
	array('Bambari','Bukoba','No','Yes'),
	array('Bambari','South-East Sea','Yes','No'),
	array('Pagalu','Bambari','Yes','Yes'),
	array('Pagalu','Gamba','Yes','Yes'),
	array('Pagalu','Pebane','No','Yes'),
	array('Pagalu','Bukoba','No','Yes'),
	array('Pagalu','South-East Sea','Yes','No'),
	array('Gamba','Pagalu','Yes','Yes'),
	array('Gamba','Eshowe','Yes','Yes'),
	array('Gamba','Pebane','No','Yes'),
	array('Gamba','Southern Ocean','Yes','No'),
	array('Gamba','South Sea','Yes','No'),
	array('Gamba','South-East Sea','Yes','No'),
	array('Eshowe','Gamba','Yes','Yes'),
	array('Eshowe','Pebane','Yes','Yes'),
	array('Eshowe','Southern Ocean','Yes','No'),
	array('Eshowe','South-South-East Sea','Yes','No'),
	array('Eshowe','Gulf of Pembra','Yes','No'),
	array('Pebane','Pagalu','No','Yes'),
	array('Pebane','Gamba','No','Yes'),
	array('Pebane','Eshowe','Yes','Yes'),
	array('Pebane','Bukoba','Yes','Yes'),
	array('Pebane','Gulf of Pembra','Yes','No'),
	array('Bukoba','Marzuq','No','Yes'),
	array('Bukoba','Bambari','No','Yes'),
	array('Bukoba','Pagalu','No','Yes'),
	array('Bukoba','Pebane','Yes','Yes'),
	array('Bukoba','Ginir','Yes','Yes'),
	array('Bukoba','Gulf of Pembra','Yes','No'),
	array('Ginir','Marzuq','No','Yes'),
	array('Ginir','Summan','No','Yes'),
	array('Ginir','Bukoba','Yes','Yes'),
	array('Ginir','Oron','Yes','Yes'),
	array('Ginir','Gulf of Pembra','Yes','No'),
	array('Oron','Summan','No','Yes'),
	array('Oron','Ginir','Yes','Yes'),
	array('Oron','Arak','No','Yes'),
	array('Oron','Dezful','Yes','Yes'),
	array('Oron','Gulf of Pembra','Yes','No'),
	array('Arak','Ubon','No','Yes'),
	array('Arak','Summan','No','Yes'),
	array('Arak','Oron','No','Yes'),
	array('Arak','Shurab','No','Yes'),
	array('Arak','Zarand','No','Yes'),
	array('Arak','Dezful','No','Yes'),
	array('Shurab','Ubon','No','Yes'),
	array('Shurab','Jolo','No','Yes'),
	array('Shurab','Arak','No','Yes'),
	array('Shurab','Zarand','No','Yes'),
	array('Shurab','Zahedan','No','Yes'),
	array('Zarand','Arak','No','Yes'),
	array('Zarand','Shurab','No','Yes'),
	array('Zarand','Zahedan','No','Yes'),
	array('Zarand','Jahrom','No','Yes'),
	array('Zarand','Dezful','No','Yes'),
	array('Zahedan','Jolo','Yes','Yes'),
	array('Zahedan','Shurab','No','Yes'),
	array('Zahedan','Zarand','No','Yes'),
	array('Zahedan','Jahrom','Yes','Yes'),
	array('Zahedan','Gulf of Sunda','Yes','No'),
	array('Zahedan','South-East Ocean','Yes','No'),
	array('Jahrom','Zarand','No','Yes'),
	array('Jahrom','Zahedan','Yes','Yes'),
	array('Jahrom','Dezful','Yes','Yes'),
	array('Jahrom','South-East Ocean','Yes','No'),
	array('Dezful','Oron','Yes','Yes'),
	array('Dezful','Arak','No','Yes'),
	array('Dezful','Zarand','No','Yes'),
	array('Dezful','Jahrom','Yes','Yes'),
	array('Dezful','South-East Ocean','Yes','No'),
	array('Dezful','South-South-East Sea','Yes','No'),
	array('Dezful','Gulf of Pembra','Yes','No'),
	array('Kadmat','Eastern Sea','Yes','No'),
	array('Kadmat','Gulf of Sunda','Yes','No'),
	array('Kadmat','South-East Ocean','Yes','No'),
	array('North-West Ocean','Ameland','Yes','No'),
	array('North-West Ocean','Labrador','Yes','No'),
	array('North-West Ocean','Charente','Yes','No'),
	array('North-West Ocean','North-North-West Ocean','Yes','No'),
	array('North-West Ocean','Western Ocean','Yes','No'),
	array('North-North-West Ocean','Ameland','Yes','No'),
	array('North-North-West Ocean','Suomi','Yes','No'),
	array('North-North-West Ocean','Frostisen','Yes','No'),
	array('North-North-West Ocean','Thisted','Yes','No'),
	array('North-North-West Ocean','Farberg','Yes','No'),
	array('North-North-West Ocean','Dramm','Yes','No'),
	array('North-North-West Ocean','Rennes','Yes','No'),
	array('North-North-West Ocean','Labrador','Yes','No'),
	array('North-North-West Ocean','North-West Ocean','Yes','No'),
	array('North-North-West Ocean','North-West Sea','Yes','No'),
	array('North-North-West Ocean','North-North-East Ocean','Yes','No'),
	array('Western Ocean','Charente','Yes','No'),
	array('Western Ocean','Segre','Yes','No'),
	array('Western Ocean','Wallowa','Yes','No'),
	array('Western Ocean','Pahau','Yes','No'),
	array('Western Ocean','Washington','Yes','No'),
	array('Western Ocean','North-West Ocean','Yes','No'),
	array('Western Ocean','Gulf of Gasco','Yes','No'),
	array('Western Ocean','Empty Ocean','Yes','No'),
	array('Gulf of Gasco','Segre','Yes','No'),
	array('Gulf of Gasco','Amiens','Yes','No'),
	array('Gulf of Gasco','Isere','Yes','No'),
	array('Gulf of Gasco','Kootenay (West Coast)','Yes','No'),
	array('Gulf of Gasco','Albany','Yes','No'),
	array('Gulf of Gasco','Wallowa','Yes','No'),
	array('Gulf of Gasco','Western Ocean','Yes','No'),
	array('Empty Ocean','Pahau','Yes','No'),
	array('Empty Ocean','Washington','Yes','No'),
	array('Empty Ocean','Cordoba','Yes','No'),
	array('Empty Ocean','Coracoes','Yes','No'),
	array('Empty Ocean','Western Ocean','Yes','No'),
	array('Empty Ocean','Gulf of Pahute','Yes','No'),
	array('Empty Ocean','Gulf San Meties','Yes','No'),
	array('Empty Ocean','Southern Ocean','Yes','No'),
	array('Gulf of Pahute','Washington','Yes','No'),
	array('Gulf of Pahute','Hiawatha','Yes','No'),
	array('Gulf of Pahute','Arizona','Yes','No'),
	array('Gulf of Pahute','Empty Ocean','Yes','No'),
	array('Gulf of Pahute','Gulf San Meties','Yes','No'),
	array('Gulf San Meties','Arizona','Yes','No'),
	array('Gulf San Meties','Veracruz','Yes','No'),
	array('Gulf San Meties','Cordoba','Yes','No'),
	array('Gulf San Meties','Empty Ocean','Yes','No'),
	array('Gulf San Meties','Gulf of Pahute','Yes','No'),
	array('Southern Ocean','Cordoba','Yes','No'),
	array('Southern Ocean','Coracoes','Yes','No'),
	array('Southern Ocean','Imataca','Yes','No'),
	array('Southern Ocean','Cartagena','Yes','No'),
	array('Southern Ocean','Gamba','Yes','No'),
	array('Southern Ocean','Eshowe','Yes','No'),
	array('Southern Ocean','Empty Ocean','Yes','No'),
	array('Southern Ocean','South Sea','Yes','No'),
	array('Southern Ocean','South-South-East Sea','Yes','No'),
	array('South Sea','Merida','Yes','No'),
	array('South Sea','Cartagena','Yes','No'),
	array('South Sea','Hierro','Yes','No'),
	array('South Sea','Gamba','Yes','No'),
	array('South Sea','Southern Ocean','Yes','No'),
	array('South Sea','South-West Sea','Yes','No'),
	array('South Sea','South-East Sea','Yes','No'),
	array('South-West Sea','Columbus','Yes','No'),
	array('South-West Sea','Inagua','Yes','No'),
	array('South-West Sea','Merida','Yes','No'),
	array('South-West Sea','Cabot','Yes','No'),
	array('South-West Sea','Hierro','Yes','No'),
	array('South-West Sea','South Sea','Yes','No'),
	array('South-West Sea','Gulf of Boothia','Yes','No'),
	array('South-West Sea','West Central Sea','Yes','No'),
	array('Gulf of Boothia','Menin','Yes','No'),
	array('Gulf of Boothia','Opole','Yes','No'),
	array('Gulf of Boothia','Kootenay (East Coast)','Yes','No'),
	array('Gulf of Boothia','Columbus','Yes','No'),
	array('Gulf of Boothia','Cabot','Yes','No'),
	array('Gulf of Boothia','South-West Sea','Yes','No'),
	array('Gulf of Boothia','Western Sea','Yes','No'),
	array('Western Sea','Kassel','Yes','No'),
	array('Western Sea','Opole','Yes','No'),
	array('Western Sea','Cabot','Yes','No'),
	array('Western Sea','Usovo','Yes','No'),
	array('Western Sea','Sozh','Yes','No'),
	array('Western Sea','Gulf of Boothia','Yes','No'),
	array('Western Sea','North-West Sea','Yes','No'),
	array('Western Sea','West Central Sea','Yes','No'),
	array('North-West Sea','Suomi','Yes','No'),
	array('North-West Sea','Farberg','Yes','No'),
	array('North-West Sea','Kassel','Yes','No'),
	array('North-West Sea','Usovo','Yes','No'),
	array('North-West Sea','Ibresi','Yes','No'),
	array('North-West Sea','North-North-West Ocean','Yes','No'),
	array('North-West Sea','Western Sea','Yes','No'),
	array('North-West Sea','North-East Sea','Yes','No'),
	array('North-East Sea','Suomi','Yes','No'),
	array('North-East Sea','Ibresi','Yes','No'),
	array('North-East Sea','Star','Yes','No'),
	array('North-East Sea','Pena','Yes','No'),
	array('North-East Sea','Nemuro','Yes','No'),
	array('North-East Sea','Osumi','Yes','No'),
	array('North-East Sea','Aldan','Yes','No'),
	array('North-East Sea','Jaipur','Yes','No'),
	array('North-East Sea','North-West Sea','Yes','No'),
	array('North-East Sea','East Central Sea','Yes','No'),
	array('North-East Sea','North-North-East Ocean','Yes','No'),
	array('East Central Sea','Hierro','Yes','No'),
	array('East Central Sea','Sudzha','Yes','No'),
	array('East Central Sea','Pena','Yes','No'),
	array('East Central Sea','Jaipur','Yes','No'),
	array('East Central Sea','Ifni','Yes','No'),
	array('East Central Sea','Karet','Yes','No'),
	array('East Central Sea','North-East Sea','Yes','No'),
	array('East Central Sea','West Central Sea','Yes','No'),
	array('East Central Sea','Gulf of Mahanadi','Yes','No'),
	array('East Central Sea','South-East Sea','Yes','No'),
	array('West Central Sea','Cabot','Yes','No'),
	array('West Central Sea','Hierro','Yes','No'),
	array('West Central Sea','Sozh','Yes','No'),
	array('West Central Sea','Sudzha','Yes','No'),
	array('West Central Sea','South-West Sea','Yes','No'),
	array('West Central Sea','Western Sea','Yes','No'),
	array('West Central Sea','East Central Sea','Yes','No'),
	array('Gulf of Mahanadi','Jaipur','Yes','No'),
	array('Gulf of Mahanadi','Shahpur','Yes','No'),
	array('Gulf of Mahanadi','Tanjor','Yes','No'),
	array('Gulf of Mahanadi','Shibam','Yes','No'),
	array('Gulf of Mahanadi','Ifni','Yes','No'),
	array('Gulf of Mahanadi','East Central Sea','Yes','No'),
	array('South-East Sea','Hierro','Yes','No'),
	array('South-East Sea','Karet','Yes','No'),
	array('South-East Sea','Aouker','Yes','No'),
	array('South-East Sea','Tabou','Yes','No'),
	array('South-East Sea','Bambari','Yes','No'),
	array('South-East Sea','Pagalu','Yes','No'),
	array('South-East Sea','Gamba','Yes','No'),
	array('South-East Sea','South Sea','Yes','No'),
	array('South-East Sea','East Central Sea','Yes','No'),
	array('North-North-East Ocean','Suomi','Yes','No'),
	array('North-North-East Ocean','Nemuro','Yes','No'),
	array('North-North-East Ocean','North-North-West Ocean','Yes','No'),
	array('North-North-East Ocean','North-East Sea','Yes','No'),
	array('North-North-East Ocean','North-East Ocean','Yes','No'),
	array('North-East Ocean','Nemuro','Yes','No'),
	array('North-East Ocean','Sakai','Yes','No'),
	array('North-East Ocean','Taichun','Yes','No'),
	array('North-East Ocean','Pinkiang','Yes','No'),
	array('North-East Ocean','North-North-East Ocean','Yes','No'),
	array('North-East Ocean','Gulf of Toyama','Yes','No'),
	array('North-East Ocean','Eastern Ocean','Yes','No'),
	array('Gulf of Toyama','Nemuro','Yes','No'),
	array('Gulf of Toyama','Takada','Yes','No'),
	array('Gulf of Toyama','Sakai','Yes','No'),
	array('Gulf of Toyama','North-East Ocean','Yes','No'),
	array('Eastern Ocean','Pinkiang','Yes','No'),
	array('Eastern Ocean','Mingshui','Yes','No'),
	array('Eastern Ocean','Lintao','Yes','No'),
	array('Eastern Ocean','Vinh','Yes','No'),
	array('Eastern Ocean','North-East Ocean','Yes','No'),
	array('Eastern Ocean','Gulf of Amboy','Yes','No'),
	array('Eastern Ocean','Eastern Sea','Yes','No'),
	array('Gulf of Amboy','Pegu','Yes','No'),
	array('Gulf of Amboy','Lintao','Yes','No'),
	array('Gulf of Amboy','Anking','Yes','No'),
	array('Gulf of Amboy','Romang','Yes','No'),
	array('Gulf of Amboy','Serang (North Coast)','Yes','No'),
	array('Gulf of Amboy','Surabaya (North Coast)','Yes','No'),
	array('Gulf of Amboy','Davao','Yes','No'),
	array('Gulf of Amboy','Vinh','Yes','No'),
	array('Gulf of Amboy','Eastern Ocean','Yes','No'),
	array('Gulf of Amboy','Eastern Sea','Yes','No'),
	array('Eastern Sea','Davao','Yes','No'),
	array('Eastern Sea','Vinh','Yes','No'),
	array('Eastern Sea','Kadmat','Yes','No'),
	array('Eastern Sea','Eastern Ocean','Yes','No'),
	array('Eastern Sea','Gulf of Amboy','Yes','No'),
	array('Eastern Sea','Gulf of Sunda','Yes','No'),
	array('Eastern Sea','South-East Ocean','Yes','No'),
	array('Gulf of Sunda','Babar','Yes','No'),
	array('Gulf of Sunda','Serang (South Coast)','Yes','No'),
	array('Gulf of Sunda','Surabaya (South Coast)','Yes','No'),
	array('Gulf of Sunda','Davao','Yes','No'),
	array('Gulf of Sunda','Jolo','Yes','No'),
	array('Gulf of Sunda','Zahedan','Yes','No'),
	array('Gulf of Sunda','Kadmat','Yes','No'),
	array('Gulf of Sunda','Eastern Sea','Yes','No'),
	array('Gulf of Sunda','South-East Ocean','Yes','No'),
	array('South-East Ocean','Zahedan','Yes','No'),
	array('South-East Ocean','Jahrom','Yes','No'),
	array('South-East Ocean','Dezful','Yes','No'),
	array('South-East Ocean','Kadmat','Yes','No'),
	array('South-East Ocean','Eastern Sea','Yes','No'),
	array('South-East Ocean','Gulf of Sunda','Yes','No'),
	array('South-East Ocean','South-South-East Sea','Yes','No'),
	array('South-South-East Sea','Eshowe','Yes','No'),
	array('South-South-East Sea','Dezful','Yes','No'),
	array('South-South-East Sea','Southern Ocean','Yes','No'),
	array('South-South-East Sea','South-East Ocean','Yes','No'),
	array('South-South-East Sea','Gulf of Pembra','Yes','No'),
	array('Gulf of Pembra','Eshowe','Yes','No'),
	array('Gulf of Pembra','Pebane','Yes','No'),
	array('Gulf of Pembra','Bukoba','Yes','No'),
	array('Gulf of Pembra','Ginir','Yes','No'),
	array('Gulf of Pembra','Oron','Yes','No'),
	array('Gulf of Pembra','Dezful','Yes','No'),
	array('Gulf of Pembra','South-South-East Sea','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
