<?php
// This is file installs the map data for the AmericanConflict variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Anchorage', 'Coast', 'Yes', 1, 202, 349, 100, 125),
	array('Yukon', 'Coast', 'No', 4, 303, 275, 152, 185),
	array('Calgary', 'Land', 'Yes', 0, 495, 610, 264, 352),
	array('Northern BC', 'Land', 'No', 4, 349, 522, 171, 272),
	array('Vancouver', 'Coast', 'Yes', 4, 282, 596, 180, 332),
	array('Eastern Rupert\\\'s Land', 'Coast', 'No', 4, 837, 444, 447, 303),
	array('Cote-Nord', 'Coast', 'No', 4, 948, 539, 496, 295),
	array('Quebec', 'Coast', 'Yes', 0, 877, 638, 475, 341),
	array('Montreal', 'Coast', 'Yes', 4, 832, 671, 469, 357),
	array('Beauce', 'Coast', 'No', 4, 932, 641, 498, 355),
	array('Gaspesie', 'Coast', 'No', 4, 958, 582, 513, 315),
	array('San Francisco', 'Coast', 'Yes', 3, 244, 790, 140, 442),
	array('Los Angeles', 'Coast', 'Yes', 0, 261, 884, 160, 474),
	array('Dallas', 'Land', 'Yes', 0, 649, 970, 328, 526),
	array('Houston', 'Coast', 'Yes', 0, 669, 1021, 363, 545),
	array('West Texas', 'Coast', 'No', 2, 612, 1041, 297, 533),
	array('Minneapolis', 'Coast', 'Yes', 0, 664, 707, 346, 411),
	array('Iowa', 'Land', 'No', 3, 680, 785, 355, 436),
	array('Indiana', 'Coast', 'No', 3, 773, 807, 415, 435),
	array('Chicago', 'Coast', 'Yes', 3, 723, 812, 396, 452),
	array('Milwaukee', 'Coast', 'Yes', 0, 710, 761, 374, 410),
	array('Milwaukee (North Coast)', 'Coast', 'No', 0, 685, 720, 369, 388),
	array('Milwaukee (East Coast)', 'Coast', 'No', 0, 729, 766, 394, 412),
	array('West Pennsylvania', 'Coast', 'No', 3, 855, 769, 469, 415),
	array('New York State', 'Coast', 'No', 3, 884, 730, 480, 392),
	array('New York City', 'Coast', 'Yes', 0, 953, 731, 503, 393),
	array('New Jersey', 'Coast', 'Yes', 0, 937, 775, 501, 408),
	array('Philadelphia', 'Land', 'Yes', 0, 887, 760, 474, 407),
	array('Florida', 'Coast', 'Yes', 0, 903, 1004, 471, 527),
	array('Havana', 'Coast', 'Yes', 0, 888, 1102, 492, 582),
	array('Holguin', 'Coast', 'Yes', 6, 1067, 1073, 552, 579),
	array('Kingston', 'Coast', 'Yes', 4, 1017, 1126, 557, 602),
	array('Camaguey', 'Coast', 'No', 6, 962, 1081, 525, 579),
	array('Camaguey (North Coast)', 'Coast', 'No', 6, 965, 1073, 531, 572),
	array('Camaguey (South Coast)', 'Coast', 'No', 6, 963, 1085, 529, 584),
	array('Guadalajara', 'Coast', 'Yes', 5, 502, 1179, 270, 631),
	array('Potosi', 'Coast', 'No', 5, 621, 1149, 304, 608),
	array('Veracruz', 'Coast', 'Yes', 5, 655, 1195, 354, 639),
	array('Mexico', 'Land', 'Yes', 0, 608, 1201, 326, 646),
	array('Guerrero', 'Coast', 'No', 5, 543, 1211, 300, 649),
	array('Oaxaca', 'Coast', 'No', 5, 601, 1232, 335, 660),
	array('North West Territory', 'Coast', 'No', 4, 466, 359, 251, 196),
	array('North West Territory Islands', 'Coast', 'No', 4, 611, 171, 331, 108),
	array('Manitoba', 'Coast', 'Yes', 0, 612, 608, 319, 345),
	array('Western Rupert\\\'s Land', 'Coast', 'No', 4, 602, 462, 405, 330),
	array('Western Ontario', 'Coast', 'No', 4, 726, 656, 363, 362),
	array('Ontario', 'Coast', 'Yes', 0, 869, 684, 425, 369),
	array('Labrador', 'Coast', 'No', 4, 967, 443, 519, 255),
	array('Nova Scotia', 'Coast', 'Yes', 0, 1050, 590, 549, 327),
	array('Newfoundland', 'Coast', 'No', 4, 1064, 521, 571, 278),
	array('Washington Territory', 'Coast', 'No', 3, 300, 682, 166, 358),
	array('Oregon', 'Coast', 'Yes', 0, 257, 748, 173, 394),
	array('Arizona Territory', 'Land', 'No', 3, 391, 937, 231, 489),
	array('Utah Territory', 'Land', 'No', 3, 404, 826, 221, 441),
	array('Nevada Territory', 'Land', 'No', 3, 438, 900, 183, 462),
	array('Colorado Territory', 'Land', 'Yes', 0, 472, 840, 282, 477),
	array('Indian Territory', 'Land', 'No', 3, 584, 912, 350, 503),
	array('Kansas', 'Land', 'Yes', 0, 601, 859, 342, 462),
	array('Nebraska Territory', 'Land', 'No', 3, 583, 831, 312, 447),
	array('Dakota Territory', 'Land', 'No', 3, 506, 711, 279, 409),
	array('Missouri', 'Coast', 'Yes', 0, 679, 851, 368, 462),
	array('Arkansas', 'Coast', 'No', 2, 697, 924, 375, 491),
	array('Louisiana', 'Coast', 'Yes', 2, 764, 1007, 379, 525),
	array('Lake Ontario', 'Sea', 'No', 0, 860, 719, 469, 388),
	array('Upper Peninsula', 'Coast', 'No', 3, 743, 716, 397, 382),
	array('Michigan', 'Coast', 'Yes', 0, 772, 775, 418, 400),
	array('Lake Michigan', 'Sea', 'No', 0, 748, 747, 403, 406),
	array('Lake Superior', 'Sea', 'No', 0, 703, 699, 397, 370),
	array('Lake Huron', 'Sea', 'No', 0, 809, 731, 429, 384),
	array('Lake Erie', 'Sea', 'No', 0, 847, 754, 452, 405),
	array('Ohio', 'Coast', 'Yes', 0, 820, 787, 447, 436),
	array('Maine', 'Coast', 'No', 3, 962, 670, 520, 348),
	array('Vermont', 'Coast', 'No', 3, 960, 693, 500, 366),
	array('Massachusetts', 'Coast', 'Yes', 3, 969, 717, 513, 383),
	array('Washington DC', 'Coast', 'Yes', 3, 937, 805, 500, 429),
	array('Richmond', 'Coast', 'Yes', 2, 898, 817, 484, 440),
	array('West Virginia', 'Land', 'No', 3, 870, 810, 458, 447),
	array('Kentucky', 'Coast', 'Yes', 0, 755, 871, 435, 464),
	array('Tennessee', 'Coast', 'Yes', 2, 770, 895, 433, 477),
	array('Deep South', 'Coast', 'Yes', 0, 734, 950, 433, 512),
	array('Georgia', 'Coast', 'Yes', 0, 884, 935, 462, 499),
	array('South Carolina', 'Coast', 'Yes', 0, 910, 891, 485, 480),
	array('North Carolina', 'Coast', 'Yes', 0, 929, 865, 495, 463),
	array('Haiti', 'Coast', 'No', 0, 1114, 1081, 595, 571),
	array('Dominica', 'Coast', 'Yes', 0, 1184, 1043, 630, 563),
	array('Baja California', 'Coast', 'No', 5, 345, 1025, 187, 558),
	array('Chihuahua', 'Coast', 'Yes', 0, 453, 1010, 233, 567),
	array('Coahuila', 'Land', 'No', 5, 544, 1080, 294, 578),
	array('Nuevo Leon', 'Coast', 'Yes', 0, 628, 1113, 334, 590),
	array('Durango', 'Coast', 'Yes', 0, 468, 1117, 258, 607),
	array('Chiapas', 'Coast', 'No', 5, 732, 1246, 379, 661),
	array('Tabasco', 'Coast', 'No', 5, 750, 1196, 399, 643),
	array('Yucatan', 'Coast', 'Yes', 0, 784, 1149, 427, 634),
	array('El Salvador', 'Coast', 'No', 0, 826, 1259, 444, 674),
	array('Panama', 'Coast', 'Yes', 0, 1025, 1278, 542, 693),
	array('Hawaii', 'Coast', 'Yes', 0, 134, 1233, 53, 654),
	array('Greenland', 'Coast', 'No', 0, 914, 146, 491, 75),
	array('Bering Sea', 'Sea', 'No', 0, 32, 230, 15, 137),
	array('West Arctic Sea', 'Sea', 'No', 0, 175, 70, 114, 19),
	array('Beaufort Sea', 'Sea', 'No', 0, 396, 185, 196, 105),
	array('Hudson Bay', 'Sea', 'No', 0, 693, 450, 377, 245),
	array('Baffin Bay', 'Sea', 'No', 0, 766, 165, 400, 95),
	array('Sea of Labrador', 'Sea', 'No', 0, 946, 311, 514, 175),
	array('North Atlantic Ocean', 'Sea', 'No', 0, 1203, 360, 610, 200),
	array('Gulf of St-Lawrence', 'Sea', 'No', 0, 1032, 531, 555, 291),
	array('Massachusetts Bay', 'Sea', 'No', 0, 1069, 660, 570, 363),
	array('North Central Atlantic Ocean', 'Sea', 'No', 0, 1217, 717, 647, 380),
	array('Chesapeake Bay', 'Sea', 'No', 0, 974, 841, 550, 453),
	array('Cape May', 'Sea', 'No', 0, 1019, 751, 557, 410),
	array('Mid Atlantic Ocean', 'Sea', 'No', 0, 1227, 854, 635, 457),
	array('Bermuda Triangle', 'Sea', 'No', 0, 1100, 939, 590, 515),
	array('East Coast', 'Sea', 'No', 0, 980, 893, 531, 485),
	array('Straits of Florida', 'Sea', 'No', 0, 958, 1038, 515, 558),
	array('East Caribbean Sea', 'Sea', 'No', 0, 1079, 1148, 595, 597),
	array('South Central Atlantic Ocean', 'Sea', 'No', 0, 1305, 1121, 652, 597),
	array('Apalachee Bay', 'Sea', 'No', 0, 785, 1037, 448, 555),
	array('Gulf of Mexico', 'Sea', 'No', 0, 774, 1091, 390, 573),
	array('Gulf of Campeche', 'Sea', 'No', 0, 653, 1143, 360, 618),
	array('Straits of Yucatan', 'Sea', 'No', 0, 856, 1096, 465, 584),
	array('Gulf of Honduras', 'Sea', 'No', 0, 851, 1164, 460, 641),
	array('Cayman Trench', 'Sea', 'No', 0, 1073, 1090, 571, 590),
	array('West Caribbean Sea', 'Sea', 'No', 0, 932, 1139, 523, 640),
	array('South Caribbean Sea', 'Sea', 'No', 0, 1161, 1181, 611, 649),
	array('Gulf of Mosquitos', 'Sea', 'No', 0, 960, 1232, 532, 665),
	array('North Pacific Ocean', 'Sea', 'No', 0, 87, 904, 25, 460),
	array('Gulf of Alaska', 'Sea', 'No', 0, 88, 389, 38, 241),
	array('Queen Charlotte Sound', 'Sea', 'No', 0, 180, 496, 95, 300),
	array('Straits of Juan de Fuca', 'Sea', 'No', 0, 197, 611, 117, 330),
	array('West Coast', 'Sea', 'No', 0, 167, 738, 100, 435),
	array('Mid Pacific Ocean', 'Sea', 'No', 0, 293, 1163, 160, 625),
	array('Gulf of Santa Catalina', 'Sea', 'No', 0, 215, 944, 139, 499),
	array('Central West Pacific Ocean', 'Sea', 'No', 0, 113, 1367, 10, 710),
	array('Coast of Mexico', 'Sea', 'No', 0, 523, 1253, 300, 680),
	array('Gulf of California', 'Sea', 'No', 0, 433, 1188, 230, 603),
	array('Gulf of Tehuantepec', 'Sea', 'No', 0, 701, 1258, 385, 686),
	array('Central Pacific Ocean', 'Sea', 'No', 0, 450, 1395, 240, 740),
	array('Galapagos', 'Sea', 'No', 0, 893, 1415, 465, 760),
	array('Gulf of Panama', 'Sea', 'No', 0, 1050, 1307, 567, 697),
	array('Coronado Bay', 'Sea', 'No', 0, 887, 1303, 496, 717),
	array('Gulf of Fonseca', 'Sea', 'No', 0, 854, 1349, 449, 690),
	array('New Brunswick', 'Coast', 'No', 4, 986, 624, 525, 324),
	array('New Brunswick (North Coast)', 'Coast', 'No', 4, 984, 592, 531, 318),
	array('New Brunswick (South Coast)', 'Coast', 'No', 4, 988, 629, 534, 338),
	array('Honduras', 'Coast', 'No', 0, 900, 1212, 471, 656),
	array('Honduras (North Coast)', 'Coast', 'No', 0, 905, 1208, 480, 645),
	array('Honduras (South Coast)', 'Coast', 'No', 0, 853, 1252, 458, 674),
	array('Nicaragua', 'Coast', 'Yes', 0, 914, 1234, 490, 662),
	array('Nicaragua (East Coast)', 'Coast', 'No', 0, 925, 1228, 500, 661),
	array('Nicaragua (West Coast)', 'Coast', 'No', 0, 882, 1271, 470, 681),
	array('Costa Rica', 'Coast', 'No', 0, 941, 1278, 505, 691),
	array('Costa Rica (North Coast)', 'Coast', 'No', 0, 943, 1275, 509, 682),
	array('Costa Rica (South Coast)', 'Coast', 'No', 0, 961, 1305, 491, 697),
	array('Guatemala', 'Coast', 'Yes', 0, 762, 1246, 430, 650),
	array('Guatemala (South Coast)', 'Coast', 'No', 0, 763, 1254, 423, 675),
	array('Guatemala (East Coast)', 'Coast', 'No', 0, 831, 1220, 448, 654),
	array('East Arctic Sea', 'Sea', 'No', 0, 526, 50, 279, 34),
	array('Archangelsk', 'Coast', 'Yes', 1, 391, 34, 194, 22),
	array('Siberia', 'Coast', 'No', 1, 12, 184, 9, 92),
	array('Vladivostok', 'Coast', 'Yes', 1, 31, 558, 14, 314),
	array('South West Pacific Ocean', 'Sea', 'No', 0, 232, 1555, 155, 850),
	array('Southern Pacific Ocean', 'Sea', 'No', 0, 636, 1564, 344, 840),
	array('South East Pacific Ocean', 'Sea', 'No', 0, 913, 1521, 563, 826),
	array('Cape Horn', 'Sea', 'No', 0, 1112, 1666, 601, 896),
	array('Falklands', 'Coast', 'No', 4, 1201, 1662, 644, 891),
	array('South West Atlantic Ocean', 'Sea', 'No', 0, 1309, 1471, 693, 805),
	array('South Atlantic Ocean', 'Sea', 'No', 0, 1346, 1604, 739, 849),
	array('Cadiz', 'Coast', 'Yes', 6, 1362, 986, 730, 528),
	array('La Rochelle', 'Coast', 'Yes', 5, 1361, 729, 723, 402),
	array('Portsmouth', 'Coast', 'Yes', 4, 1355, 498, 724, 268),
	array('Belize', 'Coast', 'No', 4, 828, 1188, 443, 639),
	array('Puerto Rico', 'Coast', 'Yes', 6, 1248, 1013, 669, 544),
	array('Panama (North Coast)', 'Coast', 'No', 0, 1016, 1280, 545, 687),
	array('Panama (South Coast)', 'Coast', 'No', 0, 1018, 1305, 546, 699)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Anchorage','Yukon','Yes','Yes'),
	array('Anchorage','Northern BC','No','Yes'),
	array('Anchorage','Vancouver','Yes','Yes'),
	array('Anchorage','Bering Sea','Yes','No'),
	array('Anchorage','West Arctic Sea','Yes','No'),
	array('Anchorage','Beaufort Sea','Yes','No'),
	array('Anchorage','Gulf of Alaska','Yes','No'),
	array('Anchorage','Queen Charlotte Sound','Yes','No'),
	array('Yukon','Northern BC','No','Yes'),
	array('Yukon','North West Territory','Yes','Yes'),
	array('Yukon','Beaufort Sea','Yes','No'),
	array('Calgary','Vancouver','No','Yes'),
	array('Calgary','North West Territory','No','Yes'),
	array('Calgary','Manitoba','No','Yes'),
	array('Calgary','Dakota Territory','No','Yes'),
	array('Northern BC','Vancouver','No','Yes'),
	array('Northern BC','North West Territory','No','Yes'),
	array('Vancouver','North West Territory','No','Yes'),
	array('Vancouver','Washington Territory','Yes','Yes'),
	array('Vancouver','Dakota Territory','No','Yes'),
	array('Vancouver','Queen Charlotte Sound','Yes','No'),
	array('Vancouver','Straits of Juan de Fuca','Yes','No'),
	array('Eastern Rupert\\\'s Land','Cote-Nord','No','Yes'),
	array('Eastern Rupert\\\'s Land','Quebec','No','Yes'),
	array('Eastern Rupert\\\'s Land','Montreal','No','Yes'),
	array('Eastern Rupert\\\'s Land','North West Territory Islands','Yes','Yes'),
	array('Eastern Rupert\\\'s Land','Western Rupert\\\'s Land','Yes','Yes'),
	array('Eastern Rupert\\\'s Land','Labrador','Yes','Yes'),
	array('Eastern Rupert\\\'s Land','Hudson Bay','Yes','No'),
	array('Eastern Rupert\\\'s Land','Sea of Labrador','Yes','No'),
	array('Cote-Nord','Quebec','Yes','Yes'),
	array('Cote-Nord','Labrador','Yes','Yes'),
	array('Cote-Nord','Gulf of St-Lawrence','Yes','No'),
	array('Quebec','Montreal','Yes','Yes'),
	array('Quebec','Beauce','Yes','Yes'),
	array('Quebec','Gaspesie','Yes','Yes'),
	array('Quebec','Gulf of St-Lawrence','Yes','No'),
	array('Montreal','Beauce','Yes','Yes'),
	array('Montreal','Western Rupert\\\'s Land','No','Yes'),
	array('Montreal','Ontario','Yes','Yes'),
	array('Beauce','Gaspesie','Yes','Yes'),
	array('Beauce','New York State','Yes','Yes'),
	array('Beauce','Ontario','Yes','Yes'),
	array('Beauce','Maine','No','Yes'),
	array('Beauce','Vermont','No','Yes'),
	array('Gaspesie','Maine','No','Yes'),
	array('Gaspesie','Gulf of St-Lawrence','Yes','No'),
	array('Gaspesie','New Brunswick','No','Yes'),
	array('Gaspesie','New Brunswick (North Coast)','Yes','No'),
	array('San Francisco','Los Angeles','Yes','Yes'),
	array('San Francisco','Oregon','Yes','Yes'),
	array('San Francisco','Nevada Territory','No','Yes'),
	array('San Francisco','West Coast','Yes','No'),
	array('Los Angeles','Arizona Territory','No','Yes'),
	array('Los Angeles','Nevada Territory','No','Yes'),
	array('Los Angeles','Baja California','Yes','Yes'),
	array('Los Angeles','West Coast','Yes','No'),
	array('Los Angeles','Gulf of Santa Catalina','Yes','No'),
	array('Dallas','Houston','No','Yes'),
	array('Dallas','West Texas','No','Yes'),
	array('Dallas','Arizona Territory','No','Yes'),
	array('Dallas','Indian Territory','No','Yes'),
	array('Dallas','Arkansas','No','Yes'),
	array('Dallas','Louisiana','No','Yes'),
	array('Houston','West Texas','Yes','Yes'),
	array('Houston','Louisiana','Yes','Yes'),
	array('Houston','Gulf of Mexico','Yes','No'),
	array('West Texas','Arizona Territory','No','Yes'),
	array('West Texas','Chihuahua','No','Yes'),
	array('West Texas','Coahuila','No','Yes'),
	array('West Texas','Nuevo Leon','Yes','Yes'),
	array('West Texas','Gulf of Mexico','Yes','No'),
	array('Minneapolis','Iowa','No','Yes'),
	array('Minneapolis','Milwaukee','No','Yes'),
	array('Minneapolis','Milwaukee (North Coast)','Yes','No'),
	array('Minneapolis','Manitoba','No','Yes'),
	array('Minneapolis','Western Ontario','Yes','Yes'),
	array('Minneapolis','Dakota Territory','No','Yes'),
	array('Minneapolis','Lake Superior','Yes','No'),
	array('Iowa','Chicago','No','Yes'),
	array('Iowa','Milwaukee','No','Yes'),
	array('Iowa','Nebraska Territory','No','Yes'),
	array('Iowa','Dakota Territory','No','Yes'),
	array('Iowa','Missouri','No','Yes'),
	array('Indiana','Chicago','Yes','Yes'),
	array('Indiana','Michigan','Yes','Yes'),
	array('Indiana','Lake Michigan','Yes','No'),
	array('Indiana','Ohio','No','Yes'),
	array('Indiana','Kentucky','No','Yes'),
	array('Chicago','Milwaukee','No','Yes'),
	array('Chicago','Milwaukee (East Coast)','Yes','No'),
	array('Chicago','Missouri','Yes','Yes'),
	array('Chicago','Lake Michigan','Yes','No'),
	array('Chicago','Kentucky','Yes','Yes'),
	array('Milwaukee','Upper Peninsula','No','Yes'),
	array('Milwaukee (North Coast)','Upper Peninsula','Yes','No'),
	array('Milwaukee (North Coast)','Lake Superior','Yes','No'),
	array('Milwaukee (East Coast)','Upper Peninsula','Yes','No'),
	array('Milwaukee (East Coast)','Lake Michigan','Yes','No'),
	array('West Pennsylvania','New York State','Yes','Yes'),
	array('West Pennsylvania','Philadelphia','No','Yes'),
	array('West Pennsylvania','Lake Erie','Yes','No'),
	array('West Pennsylvania','Ohio','Yes','Yes'),
	array('West Pennsylvania','Washington DC','No','Yes'),
	array('West Pennsylvania','West Virginia','No','Yes'),
	array('New York State','New York City','Yes','Yes'),
	array('New York State','Philadelphia','No','Yes'),
	array('New York State','Ontario','Yes','Yes'),
	array('New York State','Lake Ontario','Yes','No'),
	array('New York State','Lake Erie','Yes','No'),
	array('New York State','Vermont','No','Yes'),
	array('New York State','Massachusetts','No','Yes'),
	array('New York City','New Jersey','Yes','Yes'),
	array('New York City','Philadelphia','No','Yes'),
	array('New York City','Massachusetts','Yes','Yes'),
	array('New York City','Cape May','Yes','No'),
	array('New Jersey','Philadelphia','No','Yes'),
	array('New Jersey','Washington DC','Yes','Yes'),
	array('New Jersey','Cape May','Yes','No'),
	array('Philadelphia','Washington DC','No','Yes'),
	array('Florida','Deep South','Yes','Yes'),
	array('Florida','Georgia','Yes','Yes'),
	array('Florida','East Coast','Yes','No'),
	array('Florida','Straits of Florida','Yes','No'),
	array('Florida','Apalachee Bay','Yes','No'),
	array('Havana','Camaguey','No','Yes'),
	array('Havana','Camaguey (North Coast)','Yes','No'),
	array('Havana','Camaguey (South Coast)','Yes','No'),
	array('Havana','Straits of Florida','Yes','No'),
	array('Havana','Straits of Yucatan','Yes','No'),
	array('Havana','West Caribbean Sea','Yes','No'),
	array('Holguin','Camaguey','No','Yes'),
	array('Holguin','Camaguey (North Coast)','Yes','No'),
	array('Holguin','Camaguey (South Coast)','Yes','No'),
	array('Holguin','Bermuda Triangle','Yes','No'),
	array('Holguin','Cayman Trench','Yes','No'),
	array('Kingston','East Caribbean Sea','Yes','No'),
	array('Kingston','Cayman Trench','Yes','No'),
	array('Kingston','West Caribbean Sea','Yes','No'),
	array('Camaguey (North Coast)','Bermuda Triangle','Yes','No'),
	array('Camaguey (North Coast)','Straits of Florida','Yes','No'),
	array('Camaguey (South Coast)','Cayman Trench','Yes','No'),
	array('Camaguey (South Coast)','West Caribbean Sea','Yes','No'),
	array('Guadalajara','Potosi','No','Yes'),
	array('Guadalajara','Mexico','No','Yes'),
	array('Guadalajara','Guerrero','Yes','Yes'),
	array('Guadalajara','Durango','Yes','Yes'),
	array('Guadalajara','Coast of Mexico','Yes','No'),
	array('Guadalajara','Gulf of California','Yes','No'),
	array('Potosi','Veracruz','Yes','Yes'),
	array('Potosi','Mexico','No','Yes'),
	array('Potosi','Coahuila','No','Yes'),
	array('Potosi','Nuevo Leon','Yes','Yes'),
	array('Potosi','Durango','No','Yes'),
	array('Potosi','Gulf of Campeche','Yes','No'),
	array('Veracruz','Mexico','No','Yes'),
	array('Veracruz','Oaxaca','No','Yes'),
	array('Veracruz','Chiapas','No','Yes'),
	array('Veracruz','Tabasco','Yes','Yes'),
	array('Veracruz','Gulf of Campeche','Yes','No'),
	array('Mexico','Guerrero','No','Yes'),
	array('Mexico','Oaxaca','No','Yes'),
	array('Guerrero','Oaxaca','Yes','Yes'),
	array('Guerrero','Coast of Mexico','Yes','No'),
	array('Oaxaca','Chiapas','Yes','Yes'),
	array('Oaxaca','Coast of Mexico','Yes','No'),
	array('Oaxaca','Gulf of Tehuantepec','Yes','No'),
	array('North West Territory','North West Territory Islands','Yes','Yes'),
	array('North West Territory','Manitoba','No','Yes'),
	array('North West Territory','Western Rupert\\\'s Land','Yes','Yes'),
	array('North West Territory','Beaufort Sea','Yes','No'),
	array('North West Territory Islands','Western Rupert\\\'s Land','Yes','Yes'),
	array('North West Territory Islands','Beaufort Sea','Yes','No'),
	array('North West Territory Islands','Hudson Bay','Yes','No'),
	array('North West Territory Islands','Baffin Bay','Yes','No'),
	array('North West Territory Islands','Sea of Labrador','Yes','No'),
	array('North West Territory Islands','East Arctic Sea','Yes','No'),
	array('Manitoba','Western Rupert\\\'s Land','No','Yes'),
	array('Manitoba','Western Ontario','No','Yes'),
	array('Manitoba','Dakota Territory','No','Yes'),
	array('Western Rupert\\\'s Land','Western Ontario','No','Yes'),
	array('Western Rupert\\\'s Land','Ontario','No','Yes'),
	array('Western Rupert\\\'s Land','Hudson Bay','Yes','No'),
	array('Western Ontario','Ontario','Yes','Yes'),
	array('Western Ontario','Lake Superior','Yes','No'),
	array('Ontario','Lake Ontario','Yes','No'),
	array('Ontario','Upper Peninsula','Yes','Yes'),
	array('Ontario','Michigan','Yes','Yes'),
	array('Ontario','Lake Superior','Yes','No'),
	array('Ontario','Lake Huron','Yes','No'),
	array('Ontario','Lake Erie','Yes','No'),
	array('Labrador','Sea of Labrador','Yes','No'),
	array('Labrador','Gulf of St-Lawrence','Yes','No'),
	array('Nova Scotia','North Atlantic Ocean','Yes','No'),
	array('Nova Scotia','Gulf of St-Lawrence','Yes','No'),
	array('Nova Scotia','Massachusetts Bay','Yes','No'),
	array('Nova Scotia','New Brunswick','No','Yes'),
	array('Nova Scotia','New Brunswick (North Coast)','Yes','No'),
	array('Nova Scotia','New Brunswick (South Coast)','Yes','No'),
	array('Newfoundland','Sea of Labrador','Yes','No'),
	array('Newfoundland','North Atlantic Ocean','Yes','No'),
	array('Newfoundland','Gulf of St-Lawrence','Yes','No'),
	array('Washington Territory','Oregon','Yes','Yes'),
	array('Washington Territory','Utah Territory','No','Yes'),
	array('Washington Territory','Nevada Territory','No','Yes'),
	array('Washington Territory','Nebraska Territory','No','Yes'),
	array('Washington Territory','Dakota Territory','No','Yes'),
	array('Washington Territory','Straits of Juan de Fuca','Yes','No'),
	array('Oregon','Nevada Territory','No','Yes'),
	array('Oregon','Straits of Juan de Fuca','Yes','No'),
	array('Oregon','West Coast','Yes','No'),
	array('Arizona Territory','Utah Territory','No','Yes'),
	array('Arizona Territory','Nevada Territory','No','Yes'),
	array('Arizona Territory','Colorado Territory','No','Yes'),
	array('Arizona Territory','Indian Territory','No','Yes'),
	array('Arizona Territory','Baja California','No','Yes'),
	array('Arizona Territory','Chihuahua','No','Yes'),
	array('Utah Territory','Nevada Territory','No','Yes'),
	array('Utah Territory','Colorado Territory','No','Yes'),
	array('Utah Territory','Nebraska Territory','No','Yes'),
	array('Colorado Territory','Indian Territory','No','Yes'),
	array('Colorado Territory','Kansas','No','Yes'),
	array('Colorado Territory','Nebraska Territory','No','Yes'),
	array('Indian Territory','Kansas','No','Yes'),
	array('Indian Territory','Missouri','No','Yes'),
	array('Indian Territory','Arkansas','No','Yes'),
	array('Kansas','Nebraska Territory','No','Yes'),
	array('Kansas','Missouri','No','Yes'),
	array('Nebraska Territory','Dakota Territory','No','Yes'),
	array('Nebraska Territory','Missouri','No','Yes'),
	array('Missouri','Arkansas','Yes','Yes'),
	array('Missouri','Kentucky','Yes','Yes'),
	array('Missouri','Tennessee','Yes','Yes'),
	array('Arkansas','Louisiana','Yes','Yes'),
	array('Arkansas','Tennessee','Yes','Yes'),
	array('Arkansas','Deep South','Yes','Yes'),
	array('Louisiana','Deep South','Yes','Yes'),
	array('Louisiana','Apalachee Bay','Yes','No'),
	array('Louisiana','Gulf of Mexico','Yes','No'),
	array('Upper Peninsula','Michigan','Yes','Yes'),
	array('Upper Peninsula','Lake Michigan','Yes','No'),
	array('Upper Peninsula','Lake Superior','Yes','No'),
	array('Upper Peninsula','Lake Huron','Yes','No'),
	array('Michigan','Lake Michigan','Yes','No'),
	array('Michigan','Lake Huron','Yes','No'),
	array('Michigan','Lake Erie','Yes','No'),
	array('Michigan','Ohio','Yes','Yes'),
	array('Lake Michigan','Lake Huron','Yes','No'),
	array('Lake Erie','Ohio','Yes','No'),
	array('Ohio','West Virginia','No','Yes'),
	array('Ohio','Kentucky','No','Yes'),
	array('Maine','Vermont','Yes','Yes'),
	array('Maine','Massachusetts Bay','Yes','No'),
	array('Maine','New Brunswick','No','Yes'),
	array('Maine','New Brunswick (South Coast)','Yes','No'),
	array('Vermont','Massachusetts','Yes','Yes'),
	array('Vermont','Massachusetts Bay','Yes','No'),
	array('Massachusetts','Massachusetts Bay','Yes','No'),
	array('Massachusetts','Cape May','Yes','No'),
	array('Washington DC','Richmond','Yes','Yes'),
	array('Washington DC','West Virginia','No','Yes'),
	array('Washington DC','Chesapeake Bay','Yes','No'),
	array('Washington DC','Cape May','Yes','No'),
	array('Richmond','West Virginia','No','Yes'),
	array('Richmond','Kentucky','No','Yes'),
	array('Richmond','Tennessee','No','Yes'),
	array('Richmond','North Carolina','Yes','Yes'),
	array('Richmond','Chesapeake Bay','Yes','No'),
	array('West Virginia','Kentucky','No','Yes'),
	array('Kentucky','Tennessee','Yes','Yes'),
	array('Tennessee','Deep South','Yes','Yes'),
	array('Tennessee','Georgia','No','Yes'),
	array('Tennessee','North Carolina','No','Yes'),
	array('Deep South','Georgia','No','Yes'),
	array('Deep South','Apalachee Bay','Yes','No'),
	array('Georgia','South Carolina','Yes','Yes'),
	array('Georgia','North Carolina','No','Yes'),
	array('Georgia','East Coast','Yes','No'),
	array('South Carolina','North Carolina','Yes','Yes'),
	array('South Carolina','East Coast','Yes','No'),
	array('North Carolina','Chesapeake Bay','Yes','No'),
	array('North Carolina','East Coast','Yes','No'),
	array('Haiti','Dominica','Yes','Yes'),
	array('Haiti','Bermuda Triangle','Yes','No'),
	array('Haiti','East Caribbean Sea','Yes','No'),
	array('Haiti','Cayman Trench','Yes','No'),
	array('Dominica','Mid Atlantic Ocean','Yes','No'),
	array('Dominica','Bermuda Triangle','Yes','No'),
	array('Dominica','East Caribbean Sea','Yes','No'),
	array('Dominica','South Central Atlantic Ocean','Yes','No'),
	array('Baja California','Chihuahua','Yes','Yes'),
	array('Baja California','North Pacific Ocean','Yes','No'),
	array('Baja California','Mid Pacific Ocean','Yes','No'),
	array('Baja California','Gulf of Santa Catalina','Yes','No'),
	array('Baja California','Gulf of California','Yes','No'),
	array('Chihuahua','Coahuila','No','Yes'),
	array('Chihuahua','Durango','Yes','Yes'),
	array('Chihuahua','Gulf of California','Yes','No'),
	array('Coahuila','Nuevo Leon','No','Yes'),
	array('Coahuila','Durango','No','Yes'),
	array('Nuevo Leon','Gulf of Mexico','Yes','No'),
	array('Nuevo Leon','Gulf of Campeche','Yes','No'),
	array('Durango','Gulf of California','Yes','No'),
	array('Chiapas','Tabasco','No','Yes'),
	array('Chiapas','Gulf of Tehuantepec','Yes','No'),
	array('Chiapas','Guatemala','No','Yes'),
	array('Chiapas','Guatemala (South Coast)','Yes','No'),
	array('Tabasco','Yucatan','Yes','Yes'),
	array('Tabasco','Gulf of Campeche','Yes','No'),
	array('Tabasco','Guatemala','No','Yes'),
	array('Yucatan','Gulf of Mexico','Yes','No'),
	array('Yucatan','Gulf of Campeche','Yes','No'),
	array('Yucatan','Straits of Yucatan','Yes','No'),
	array('Yucatan','Gulf of Honduras','Yes','No'),
	array('Yucatan','Guatemala','No','Yes'),
	array('Yucatan','Belize','Yes','Yes'),
	array('El Salvador','Coast of Mexico','Yes','No'),
	array('El Salvador','Gulf of Fonseca','Yes','No'),
	array('El Salvador','Honduras','No','Yes'),
	array('El Salvador','Honduras (South Coast)','Yes','No'),
	array('El Salvador','Guatemala','No','Yes'),
	array('El Salvador','Guatemala (South Coast)','Yes','No'),
	array('Panama','Costa Rica','No','Yes'),
	array('Hawaii','North Pacific Ocean','Yes','No'),
	array('Hawaii','Mid Pacific Ocean','Yes','No'),
	array('Hawaii','Central West Pacific Ocean','Yes','No'),
	array('Hawaii','Central Pacific Ocean','Yes','No'),
	array('Greenland','Baffin Bay','Yes','No'),
	array('Greenland','Sea of Labrador','Yes','No'),
	array('Greenland','North Atlantic Ocean','Yes','No'),
	array('Greenland','East Arctic Sea','Yes','No'),
	array('Bering Sea','West Arctic Sea','Yes','No'),
	array('Bering Sea','Gulf of Alaska','Yes','No'),
	array('Bering Sea','Siberia','Yes','No'),
	array('West Arctic Sea','Beaufort Sea','Yes','No'),
	array('West Arctic Sea','North Atlantic Ocean','Yes','No'),
	array('West Arctic Sea','East Arctic Sea','Yes','No'),
	array('West Arctic Sea','Archangelsk','Yes','No'),
	array('West Arctic Sea','Siberia','Yes','No'),
	array('Beaufort Sea','East Arctic Sea','Yes','No'),
	array('Hudson Bay','Sea of Labrador','Yes','No'),
	array('Baffin Bay','Sea of Labrador','Yes','No'),
	array('Baffin Bay','East Arctic Sea','Yes','No'),
	array('Sea of Labrador','North Atlantic Ocean','Yes','No'),
	array('Sea of Labrador','Gulf of St-Lawrence','Yes','No'),
	array('North Atlantic Ocean','Gulf of St-Lawrence','Yes','No'),
	array('North Atlantic Ocean','Massachusetts Bay','Yes','No'),
	array('North Atlantic Ocean','North Central Atlantic Ocean','Yes','No'),
	array('North Atlantic Ocean','East Arctic Sea','Yes','No'),
	array('North Atlantic Ocean','Portsmouth','Yes','No'),
	array('Gulf of St-Lawrence','New Brunswick (North Coast)','Yes','No'),
	array('Massachusetts Bay','North Central Atlantic Ocean','Yes','No'),
	array('Massachusetts Bay','Cape May','Yes','No'),
	array('Massachusetts Bay','New Brunswick (South Coast)','Yes','No'),
	array('North Central Atlantic Ocean','Cape May','Yes','No'),
	array('North Central Atlantic Ocean','Mid Atlantic Ocean','Yes','No'),
	array('North Central Atlantic Ocean','Bermuda Triangle','Yes','No'),
	array('North Central Atlantic Ocean','La Rochelle','Yes','No'),
	array('North Central Atlantic Ocean','Portsmouth','Yes','No'),
	array('Chesapeake Bay','Cape May','Yes','No'),
	array('Chesapeake Bay','East Coast','Yes','No'),
	array('Cape May','Bermuda Triangle','Yes','No'),
	array('Cape May','East Coast','Yes','No'),
	array('Mid Atlantic Ocean','Bermuda Triangle','Yes','No'),
	array('Mid Atlantic Ocean','South Central Atlantic Ocean','Yes','No'),
	array('Mid Atlantic Ocean','Cadiz','Yes','No'),
	array('Mid Atlantic Ocean','La Rochelle','Yes','No'),
	array('Mid Atlantic Ocean','Puerto Rico','Yes','No'),
	array('Bermuda Triangle','East Coast','Yes','No'),
	array('Bermuda Triangle','Straits of Florida','Yes','No'),
	array('Bermuda Triangle','Cayman Trench','Yes','No'),
	array('East Coast','Straits of Florida','Yes','No'),
	array('Straits of Florida','Apalachee Bay','Yes','No'),
	array('Straits of Florida','Gulf of Mexico','Yes','No'),
	array('Straits of Florida','Straits of Yucatan','Yes','No'),
	array('East Caribbean Sea','South Central Atlantic Ocean','Yes','No'),
	array('East Caribbean Sea','Cayman Trench','Yes','No'),
	array('East Caribbean Sea','West Caribbean Sea','Yes','No'),
	array('East Caribbean Sea','South Caribbean Sea','Yes','No'),
	array('South Central Atlantic Ocean','South Caribbean Sea','Yes','No'),
	array('South Central Atlantic Ocean','South Atlantic Ocean','Yes','No'),
	array('South Central Atlantic Ocean','Cadiz','Yes','No'),
	array('South Central Atlantic Ocean','Puerto Rico','Yes','No'),
	array('Apalachee Bay','Gulf of Mexico','Yes','No'),
	array('Gulf of Mexico','Gulf of Campeche','Yes','No'),
	array('Gulf of Mexico','Straits of Yucatan','Yes','No'),
	array('Straits of Yucatan','Gulf of Honduras','Yes','No'),
	array('Straits of Yucatan','West Caribbean Sea','Yes','No'),
	array('Gulf of Honduras','West Caribbean Sea','Yes','No'),
	array('Gulf of Honduras','Honduras (North Coast)','Yes','No'),
	array('Gulf of Honduras','Guatemala (East Coast)','Yes','No'),
	array('Gulf of Honduras','Belize','Yes','No'),
	array('Cayman Trench','West Caribbean Sea','Yes','No'),
	array('West Caribbean Sea','South Caribbean Sea','Yes','No'),
	array('West Caribbean Sea','Gulf of Mosquitos','Yes','No'),
	array('West Caribbean Sea','Honduras (North Coast)','Yes','No'),
	array('West Caribbean Sea','Nicaragua (East Coast)','Yes','No'),
	array('South Caribbean Sea','Gulf of Mosquitos','Yes','No'),
	array('South Caribbean Sea','South West Atlantic Ocean','Yes','No'),
	array('South Caribbean Sea','South Atlantic Ocean','Yes','No'),
	array('South Caribbean Sea','Panama (North Coast)','Yes','No'),
	array('Gulf of Mosquitos','Nicaragua (East Coast)','Yes','No'),
	array('Gulf of Mosquitos','Costa Rica (North Coast)','Yes','No'),
	array('Gulf of Mosquitos','Panama (North Coast)','Yes','No'),
	array('North Pacific Ocean','Gulf of Alaska','Yes','No'),
	array('North Pacific Ocean','West Coast','Yes','No'),
	array('North Pacific Ocean','Mid Pacific Ocean','Yes','No'),
	array('North Pacific Ocean','Gulf of Santa Catalina','Yes','No'),
	array('North Pacific Ocean','Central West Pacific Ocean','Yes','No'),
	array('North Pacific Ocean','Vladivostok','Yes','No'),
	array('Gulf of Alaska','Queen Charlotte Sound','Yes','No'),
	array('Gulf of Alaska','Straits of Juan de Fuca','Yes','No'),
	array('Gulf of Alaska','West Coast','Yes','No'),
	array('Gulf of Alaska','Vladivostok','Yes','No'),
	array('Queen Charlotte Sound','Straits of Juan de Fuca','Yes','No'),
	array('Straits of Juan de Fuca','West Coast','Yes','No'),
	array('West Coast','Gulf of Santa Catalina','Yes','No'),
	array('Mid Pacific Ocean','Coast of Mexico','Yes','No'),
	array('Mid Pacific Ocean','Gulf of California','Yes','No'),
	array('Mid Pacific Ocean','Central Pacific Ocean','Yes','No'),
	array('Central West Pacific Ocean','Central Pacific Ocean','Yes','No'),
	array('Central West Pacific Ocean','South West Pacific Ocean','Yes','No'),
	array('Coast of Mexico','Gulf of California','Yes','No'),
	array('Coast of Mexico','Gulf of Tehuantepec','Yes','No'),
	array('Coast of Mexico','Central Pacific Ocean','Yes','No'),
	array('Coast of Mexico','Galapagos','Yes','No'),
	array('Coast of Mexico','Gulf of Fonseca','Yes','No'),
	array('Coast of Mexico','Guatemala (South Coast)','Yes','No'),
	array('Gulf of Tehuantepec','Guatemala (South Coast)','Yes','No'),
	array('Central Pacific Ocean','Galapagos','Yes','No'),
	array('Central Pacific Ocean','South West Pacific Ocean','Yes','No'),
	array('Central Pacific Ocean','Southern Pacific Ocean','Yes','No'),
	array('Central Pacific Ocean','South East Pacific Ocean','Yes','No'),
	array('Galapagos','Gulf of Panama','Yes','No'),
	array('Galapagos','Gulf of Fonseca','Yes','No'),
	array('Galapagos','South East Pacific Ocean','Yes','No'),
	array('Gulf of Panama','Coronado Bay','Yes','No'),
	array('Gulf of Panama','Gulf of Fonseca','Yes','No'),
	array('Gulf of Panama','South East Pacific Ocean','Yes','No'),
	array('Gulf of Panama','Panama (South Coast)','Yes','No'),
	array('Coronado Bay','Gulf of Fonseca','Yes','No'),
	array('Coronado Bay','Nicaragua (West Coast)','Yes','No'),
	array('Coronado Bay','Costa Rica (South Coast)','Yes','No'),
	array('Coronado Bay','Panama (South Coast)','Yes','No'),
	array('Gulf of Fonseca','Honduras (South Coast)','Yes','No'),
	array('Gulf of Fonseca','Nicaragua (West Coast)','Yes','No'),
	array('Honduras','Nicaragua','No','Yes'),
	array('Honduras','Guatemala','No','Yes'),
	array('Honduras (North Coast)','Nicaragua (East Coast)','Yes','No'),
	array('Honduras (North Coast)','Guatemala (East Coast)','Yes','No'),
	array('Honduras (South Coast)','Nicaragua (West Coast)','Yes','No'),
	array('Nicaragua','Costa Rica','No','Yes'),
	array('Nicaragua (East Coast)','Costa Rica (North Coast)','Yes','No'),
	array('Nicaragua (West Coast)','Costa Rica (South Coast)','Yes','No'),
	array('Costa Rica (North Coast)','Panama (North Coast)','Yes','No'),
	array('Costa Rica (South Coast)','Panama (South Coast)','Yes','No'),
	array('Guatemala','Belize','No','Yes'),
	array('Guatemala (East Coast)','Belize','Yes','No'),
	array('East Arctic Sea','Archangelsk','Yes','No'),
	array('South West Pacific Ocean','Southern Pacific Ocean','Yes','No'),
	array('Southern Pacific Ocean','South East Pacific Ocean','Yes','No'),
	array('Southern Pacific Ocean','Cape Horn','Yes','No'),
	array('Southern Pacific Ocean','Falklands','Yes','No'),
	array('Southern Pacific Ocean','South Atlantic Ocean','Yes','No'),
	array('South East Pacific Ocean','Cape Horn','Yes','No'),
	array('Cape Horn','Falklands','Yes','No'),
	array('Falklands','South West Atlantic Ocean','Yes','No'),
	array('Falklands','South Atlantic Ocean','Yes','No'),
	array('South West Atlantic Ocean','South Atlantic Ocean','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
