<?php
/*
	Copyright (C) 2010 Carey Jensen / Oliver Auth

	This file is part of the Migraine variant for webDiplomacy

	The Migraine variant for webDiplomacy is free software: you can redistribute
	it and/or modify it under the terms of the GNU Affero General Public License
	as published by the Free Software Foundation, either version 3 of the License,
	or (at your option) any later version.

	The Migraine variant for webDiplomacy is distributed in the hope that it will
	be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of 
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
	Public License for more details.

	You should have received a copy of the GNU Affero General Public License
	along with webDiplomacy. If not, see <http://www.gnu.org/licenses/>.

*/

defined('IN_CODE') or die('This script can not be run by itself.');

require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('North Turgid Ocean'  ,'Sea'  ,'No' ,298,136,194,88 ,'Neutral'),
	array('North Magestic Ocean','Sea'  ,'No' ,689,139,448,90 ,'Neutral'),
	array('East Royal Ocean'    ,'Sea'  ,'No' ,855,296,556,192,'Neutral'),
	array('East Mystic Ocean'   ,'Sea'  ,'No' ,861,695,560,452,'Neutral'),
	array('South Turgid Ocean'  ,'Sea'  ,'No' ,592,911,385,592,'Neutral'),
	array('South Magestic Ocean','Sea'  ,'No' ,390,926,254,602,'Neutral'),
	array('West Royal Ocean'    ,'Sea'  ,'No' ,112,703,73 ,457,'Neutral'),
	array('West Mystic Ocean'   ,'Sea'  ,'No' ,76 ,414,49 ,269,'Neutral'),
	array('Big Guntar Straits'  ,'Sea'  ,'No' ,486,192,316,125,'Neutral'),
	array('Dark Koga Straits'   ,'Sea'  ,'No' ,836,533,543,346,'Neutral'),
	array('San Lasta Straits'   ,'Sea'  ,'No' ,486,820,316,533,'Neutral'),
	array('Thin Zany Straits'   ,'Sea'  ,'No' ,136,524,88 ,341,'Neutral'),
	array('Groach Sea'          ,'Sea'  ,'No' ,536,374,348,243,'Neutral'),
	array('Dog Sea'             ,'Sea'  ,'No' ,620,458,400,295,'Neutral'),
	array('King\\\'s Sea'       ,'Sea'  ,'No' ,622,557,404,362,'Neutral'),
	array('Lucky Sea'           ,'Sea'  ,'No' ,540,635,351,413,'Neutral'),
	array('Saint\\\'s Sea'      ,'Sea'  ,'No' ,422,633,281,411,'Neutral'),
	array('Twine Sea'           ,'Sea'  ,'No' ,347,554,229,363,'Neutral'),
	array('Zwik Sea'            ,'Sea'  ,'No' ,356,458,234,295,'Neutral'),
	array('Blissful Sea'        ,'Sea'  ,'No' ,439,373,285,242,'Neutral'),
	array('Nortia'              ,'Coast','Yes',507,104,330,68 ,'Neutral'),
	array('Easton'              ,'Coast','Yes',907,539,590,350,'Neutral'),
	array('Weston'              ,'Coast','Yes',58 ,538,38 ,350,'Neutral'),
	array('Antoria'             ,'Coast','Yes',450,932,293,606,'Neutral'),
	array('Guteny'              ,'Coast','No' ,561,146,363,89 ,'Neutral'),
	array('Duteny'              ,'Coast','No' ,835,419,543,272,'Neutral'),
	array('Kuteny'              ,'Coast','No' ,835,592,543,385,'Neutral'),
	array('Luteny'              ,'Coast','No' ,560,865,359,568,'Neutral'),
	array('Suteny'              ,'Coast','No' ,410,865,267,567,'Neutral'),
	array('Tuteny'              ,'Coast','No' ,137,585,91 ,385,'Neutral'),
	array('Zuteny'              ,'Coast','No' ,135,425,93 ,271,'Neutral'),
	array('Buteny'              ,'Coast','No' ,413,149,271,90 ,'Neutral'),
	array('Gengor'              ,'Coast','No' ,533,207,346,135,'Neutral'),
	array('Dengor'              ,'Coast','No' ,776,478,504,311,'Neutral'),
	array('Kengor'              ,'Coast','No' ,781,536,503,343,'Neutral'),
	array('Lengor'              ,'Coast','No' ,533,811,346,527,'Neutral'),
	array('Sengor'              ,'Coast','No' ,437,812,284,528,'Neutral'),
	array('Tengor'              ,'Coast','No' ,198,531,116,358,'Neutral'),
	array('Zengor'              ,'Coast','No' ,196,476,127,309,'Neutral'),
	array('Bengor'              ,'Coast','No' ,454,246,295,160,'Neutral'),
	array('Gilington'           ,'Coast','Yes',717,184,472,124,'Gamma'  ),
	array('Dilington'           ,'Coast','Yes',807,304,525,204,'Delta'  ),
	array('Kilington'           ,'Coast','Yes',810,729,527,455,'Kappa'  ),
	array('Lilington'           ,'Coast','Yes',722,826,463,537,'Lambda' ),
	array('Silington'           ,'Coast','Yes',261,825,156,531,'Sigma'  ),
	array('Tilington'           ,'Coast','Yes',163,707,106,454,'Theta'  ),
	array('Zilington'           ,'Coast','Yes',165,302,107,202,'Zeta'   ),
	array('Bilington'           ,'Coast','Yes',253,182,170,118,'Beta'   ),
	array('Garka'               ,'Land' ,'Yes',602,235,391,153,'Gamma'  ),
	array('Darka'               ,'Land' ,'Yes',746,379,485,246,'Delta'  ),
	array('Karka'               ,'Land' ,'Yes',748,646,486,412,'Kappa'  ),
	array('Larka'               ,'Land' ,'Yes',619,736,388,497,'Lambda' ),
	array('Sarka'               ,'Land' ,'Yes',334,774,243,495,'Sigma'  ),
	array('Tarka'               ,'Land' ,'Yes',225,633,146,411,'Theta'  ),
	array('Zarka'               ,'Land' ,'Yes',231,375,150,244,'Zeta'   ),
	array('Barka'               ,'Land' ,'Yes',370,241,241,157,'Beta'   ),
	array('Gocha'               ,'Coast','Yes',556,296,361,192,'Gamma'  ),
	array('Docha'               ,'Coast','Yes',709,453,461,294,'Delta'  ),
	array('Kocha'               ,'Coast','Yes',710,558,462,358,'Kappa'  ),
	array('Locha'               ,'Coast','Yes',557,708,362,460,'Lambda' ),
	array('Socha'               ,'Coast','Yes',416,710,270,462,'Sigma'  ),
	array('Tocha'               ,'Coast','Yes',260,554,169,360,'Theta'  ),
	array('Zocha'               ,'Coast','Yes',267,450,174,293,'Zeta'   ),
	array('Bocha'               ,'Coast','Yes',422,295,274,192,'Beta'   ),
	array('Fidiga'              ,'Coast','Yes',508,415,330,270,'Neutral'),
	array('Harkoom'             ,'Coast','Yes',452,586,294,381,'Neutral'),
	array('Jalta'               ,'Coast','Yes',574,534,373,347,'Neutral'),
	array('Morga'               ,'Coast','Yes',400,473,260,307,'Neutral'),
	array('Nivara'              ,'Coast','No' ,487,510,317,332,'Neutral'),
	array('Diglia'              ,'Coast','Yes',610,408,397,269,'Neutral'),
	array('Liklia'              ,'Coast','Yes',608,605,380,408,'Neutral'),
	array('Sitlia'              ,'Coast','Yes',361,601,235,391,'Neutral'),
	array('Ziblia'              ,'Coast','Yes',359,415,233,270,'Neutral'),
	array('Gadtor'              ,'Land' ,'No' ,739,250,463,180,'Neutral'),
	array('Kaltor'              ,'Land' ,'No' ,744,765,484,497,'Neutral'),
	array('Tastor'              ,'Land' ,'No' ,230,757,150,492,'Neutral'),
	array('Baztor'              ,'Land' ,'No' ,226,245,167,179,'Neutral'),
	array('Dogaru'              ,'Coast','No' ,655,341,426,222,'Neutral'),
	array('Dogaru (A Coast)'    ,'Coast','No' ,573,341,372,222,'Neutral'),
	array('Dogaru (B Coast)'    ,'Coast','No' ,650,414,423,269,'Neutral'),
	array('Lokaru'              ,'Coast','No' ,659,671,428,436,'Neutral'),
	array('Lokaru (A Coast)'    ,'Coast','No' ,573,668,372,434,'Neutral'),
	array('Lokaru (B Coast)'    ,'Coast','No' ,652,595,424,387,'Neutral'),
	array('Sotaru'              ,'Coast','No' ,316,668,205,434,'Neutral'),
	array('Sotaru (A Coast)'    ,'Coast','No' ,399,667,259,434,'Neutral'),
	array('Sotaru (B Coast)'    ,'Coast','No' ,323,593,210,385,'Neutral'),
	array('Zobaru'              ,'Coast','No' ,313,334,203,217,'Neutral'),
	array('Zobaru (A Coast)'    ,'Coast','No' ,397,343,258,223,'Neutral'),
	array('Zobaru (B Coast)'    ,'Coast','No' ,321,416,209,270,'Neutral'),
	array('Chimara'             ,'Coast','Yes',187,829,122,539,'Neutral'),
	array('Chimara (A Coast)'   ,'Coast','No' ,207,839,135,545,'Neutral'),
	array('Chimara (B Coast)'   ,'Coast','No' ,142,790,92 ,514,'Neutral'),
	array('Cantaria'            ,'Coast','Yes',781,823,508,535,'Neutral'),
	array('Cantaria (A Coast)'  ,'Coast','No' ,768,850,499,553,'Neutral'),
	array('Cantaria (B Coast)'  ,'Coast','No' ,832,787,541,512,'Neutral')
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $x, $y, $sx, $sy, $country)=$territoryRawRow;
	if( $country=='Neutral' )
		$countryID=0;
	else
		$countryID=$this->countryID($country);
		
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Antoria'             ,'Nortia'              ,'Yes','Yes'),
	array('Bengor'              ,'Buteny'              ,'Yes','Yes'),
	array('Bengor'              ,'Gengor'              ,'Yes','Yes'),
	array('Bilington'           ,'Buteny'              ,'Yes','Yes'),
	array('Bocha'               ,'Bengor'              ,'Yes','Yes'),
	array('Buteny'              ,'Nortia'              ,'Yes','Yes'),
	array('Dengor'              ,'Duteny'              ,'Yes','Yes'),
	array('Dilington'           ,'Duteny'              ,'Yes','Yes'),
	array('Docha'               ,'Dengor'              ,'Yes','Yes'),
	array('Duteny'              ,'Easton'              ,'Yes','Yes'),
	array('Gengor'              ,'Guteny'              ,'Yes','Yes'),
	array('Gilington'           ,'Guteny'              ,'Yes','Yes'),
	array('Gocha'               ,'Gengor'              ,'Yes','Yes'),
	array('Guteny'              ,'Nortia'              ,'Yes','Yes'),
	array('Jalta'               ,'Fidiga'              ,'Yes','Yes'),
	array('Jalta'               ,'Harkoom'             ,'Yes','Yes'),
	array('Kengor'              ,'Kuteny'              ,'Yes','Yes'),
	array('Kengor'              ,'Dengor'              ,'Yes','Yes'),
	array('Kilington'           ,'Kuteny'              ,'Yes','Yes'),
	array('Kocha'               ,'Kengor'              ,'Yes','Yes'),
	array('Kuteny'              ,'Easton'              ,'Yes','Yes'),
	array('Lengor'              ,'Luteny'              ,'Yes','Yes'),
	array('Lilington'           ,'Luteny'              ,'Yes','Yes'),
	array('Locha'               ,'Lengor'              ,'Yes','Yes'),
	array('Luteny'              ,'Antoria'             ,'Yes','Yes'),
	array('Morga'               ,'Fidiga'              ,'Yes','Yes'),
	array('Morga'               ,'Harkoom'             ,'Yes','Yes'),
	array('Sengor'              ,'Suteny'              ,'Yes','Yes'),
	array('Sengor'              ,'Lengor'              ,'Yes','Yes'),
	array('Silington'           ,'Suteny'              ,'Yes','Yes'),
	array('Socha'               ,'Sengor'              ,'Yes','Yes'),
	array('Suteny'              ,'Antoria'             ,'Yes','Yes'),
	array('Tengor'              ,'Tuteny'              ,'Yes','Yes'),
	array('Tilington'           ,'Tuteny'              ,'Yes','Yes'),
	array('Tocha'               ,'Tengor'              ,'Yes','Yes'),
	array('Tuteny'              ,'Weston'              ,'Yes','Yes'),
	array('Weston'              ,'Easton'              ,'Yes','Yes'),
	array('Zengor'              ,'Zuteny'              ,'Yes','Yes'),
	array('Zengor'              ,'Tengor'              ,'Yes','Yes'),
	array('Zilington'           ,'Zuteny'              ,'Yes','Yes'),
	array('Zocha'               ,'Zengor'              ,'Yes','Yes'),
	array('Zuteny'              ,'Weston'              ,'Yes','Yes'),
	array('Barka'               ,'Bengor'              ,'No' ,'Yes'),
	array('Barka'               ,'Bilington'           ,'No' ,'Yes'),
	array('Baztor'              ,'Bilington'           ,'No' ,'Yes'),
	array('Baztor'              ,'Zilington'           ,'No' ,'Yes'),
	array('Baztor'              ,'Zarka'               ,'No' ,'Yes'),
	array('Baztor'              ,'Barka'               ,'No' ,'Yes'),
	array('Baztor'              ,'Zobaru'              ,'No' ,'Yes'),
	array('Baztor'              ,'Cantaria'            ,'No' ,'Yes'),
	array('Bilington'           ,'Bengor'              ,'No' ,'Yes'),
	array('Bilington'           ,'Cantaria'            ,'No' ,'Yes'),
	array('Bocha'               ,'Barka'               ,'No' ,'Yes'),
	array('Darka'               ,'Dengor'              ,'No' ,'Yes'),
	array('Darka'               ,'Dilington'           ,'No' ,'Yes'),
	array('Dilington'           ,'Dengor'              ,'No' ,'Yes'),
	array('Dilington'           ,'Chimara'             ,'No' ,'Yes'),
	array('Docha'               ,'Darka'               ,'No' ,'Yes'),
	array('Dogaru'              ,'Garka'               ,'No' ,'Yes'),
	array('Dogaru'              ,'Darka'               ,'No' ,'Yes'),
	array('Dogaru'              ,'Gocha'               ,'No' ,'Yes'),
	array('Dogaru'              ,'Docha'               ,'No' ,'Yes'),
	array('Dogaru'              ,'Diglia'              ,'No' ,'Yes'),
	array('Gadtor'              ,'Gilington'           ,'No' ,'Yes'),
	array('Gadtor'              ,'Dilington'           ,'No' ,'Yes'),
	array('Gadtor'              ,'Garka'               ,'No' ,'Yes'),
	array('Gadtor'              ,'Darka'               ,'No' ,'Yes'),
	array('Gadtor'              ,'Dogaru'              ,'No' ,'Yes'),
	array('Gadtor'              ,'Chimara'             ,'No' ,'Yes'),
	array('Garka'               ,'Gengor'              ,'No' ,'Yes'),
	array('Garka'               ,'Gilington'           ,'No' ,'Yes'),
	array('Gilington'           ,'Gengor'              ,'No' ,'Yes'),
	array('Gilington'           ,'Chimara'             ,'No' ,'Yes'),
	array('Gocha'               ,'Garka'               ,'No' ,'Yes'),
	array('Kaltor'              ,'Kilington'           ,'No' ,'Yes'),
	array('Kaltor'              ,'Lilington'           ,'No' ,'Yes'),
	array('Kaltor'              ,'Karka'               ,'No' ,'Yes'),
	array('Kaltor'              ,'Larka'               ,'No' ,'Yes'),
	array('Kaltor'              ,'Lokaru'              ,'No' ,'Yes'),
	array('Kaltor'              ,'Cantaria'            ,'No' ,'Yes'),
	array('Karka'               ,'Kengor'              ,'No' ,'Yes'),
	array('Karka'               ,'Kilington'           ,'No' ,'Yes'),
	array('Kilington'           ,'Kengor'              ,'No' ,'Yes'),
	array('Kilington'           ,'Cantaria'            ,'No' ,'Yes'),
	array('Kocha'               ,'Karka'               ,'No' ,'Yes'),
	array('Larka'               ,'Lengor'              ,'No' ,'Yes'),
	array('Larka'               ,'Lilington'           ,'No' ,'Yes'),
	array('Lilington'           ,'Lengor'              ,'No' ,'Yes'),
	array('Lilington'           ,'Cantaria'            ,'No' ,'Yes'),
	array('Locha'               ,'Larka'               ,'No' ,'Yes'),
	array('Lokaru'              ,'Karka'               ,'No' ,'Yes'),
	array('Lokaru'              ,'Larka'               ,'No' ,'Yes'),
	array('Lokaru'              ,'Kocha'               ,'No' ,'Yes'),
	array('Lokaru'              ,'Locha'               ,'No' ,'Yes'),
	array('Lokaru'              ,'Liklia'              ,'No' ,'Yes'),
	array('Nivara'              ,'Fidiga'              ,'No' ,'Yes'),
	array('Nivara'              ,'Harkoom'             ,'No' ,'Yes'),
	array('Nivara'              ,'Jalta'               ,'No' ,'Yes'),
	array('Nivara'              ,'Morga'               ,'No' ,'Yes'),
	array('Sarka'               ,'Sengor'              ,'No' ,'Yes'),
	array('Sarka'               ,'Silington'           ,'No' ,'Yes'),
	array('Silington'           ,'Sengor'              ,'No' ,'Yes'),
	array('Silington'           ,'Chimara'             ,'No' ,'Yes'),
	array('Socha'               ,'Sarka'               ,'No' ,'Yes'),
	array('Sotaru'              ,'Sarka'               ,'No' ,'Yes'),
	array('Sotaru'              ,'Tarka'               ,'No' ,'Yes'),
	array('Sotaru'              ,'Socha'               ,'No' ,'Yes'),
	array('Sotaru'              ,'Tocha'               ,'No' ,'Yes'),
	array('Sotaru'              ,'Sitlia'              ,'No' ,'Yes'),
	array('Tarka'               ,'Tengor'              ,'No' ,'Yes'),
	array('Tarka'               ,'Tilington'           ,'No' ,'Yes'),
	array('Tastor'              ,'Silington'           ,'No' ,'Yes'),
	array('Tastor'              ,'Tilington'           ,'No' ,'Yes'),
	array('Tastor'              ,'Sarka'               ,'No' ,'Yes'),
	array('Tastor'              ,'Tarka'               ,'No' ,'Yes'),
	array('Tastor'              ,'Sotaru'              ,'No' ,'Yes'),
	array('Tastor'              ,'Chimara'             ,'No' ,'Yes'),
	array('Tilington'           ,'Tengor'              ,'No' ,'Yes'),
	array('Tilington'           ,'Chimara'             ,'No' ,'Yes'),
	array('Tocha'               ,'Tarka'               ,'No' ,'Yes'),
	array('Zarka'               ,'Zengor'              ,'No' ,'Yes'),
	array('Zarka'               ,'Zilington'           ,'No' ,'Yes'),
	array('Zilington'           ,'Zengor'              ,'No' ,'Yes'),
	array('Zilington'           ,'Cantaria'            ,'No' ,'Yes'),
	array('Zobaru'              ,'Zarka'               ,'No' ,'Yes'),
	array('Zobaru'              ,'Barka'               ,'No' ,'Yes'),
	array('Zobaru'              ,'Zocha'               ,'No' ,'Yes'),
	array('Zobaru'              ,'Bocha'               ,'No' ,'Yes'),
	array('Zobaru'              ,'Ziblia'              ,'No' ,'Yes'),
	array('Zocha'               ,'Zarka'               ,'No' ,'Yes'),
	array('Antoria'             ,'South Turgid Ocean'  ,'Yes','No' ),
	array('Antoria'             ,'South Magestic Ocean','Yes','No' ),
	array('Bengor'              ,'Big Guntar Straits'  ,'Yes','No' ),
	array('Big Guntar Straits'  ,'North Turgid Ocean'  ,'Yes','No' ),
	array('Big Guntar Straits'  ,'North Magestic Ocean','Yes','No' ),
	array('Big Guntar Straits'  ,'Nortia'              ,'Yes','No' ),
	array('Bilington'           ,'North Turgid Ocean'  ,'Yes','No' ),
	array('Blissful Sea'        ,'Big Guntar Straits'  ,'Yes','No' ),
	array('Blissful Sea'        ,'Groach Sea'          ,'Yes','No' ),
	array('Blissful Sea'        ,'Zwik Sea'            ,'Yes','No' ),
	array('Bocha'               ,'Big Guntar Straits'  ,'Yes','No' ),
	array('Bocha'               ,'Blissful Sea'        ,'Yes','No' ),
	array('Buteny'              ,'North Turgid Ocean'  ,'Yes','No' ),
	array('Buteny'              ,'Big Guntar Straits'  ,'Yes','No' ),
	array('Dark Koga Straits'   ,'East Royal Ocean'    ,'Yes','No' ),
	array('Dark Koga Straits'   ,'East Mystic Ocean'   ,'Yes','No' ),
	array('Dark Koga Straits'   ,'Easton'              ,'Yes','No' ),
	array('Dengor'              ,'Dark Koga Straits'   ,'Yes','No' ),
	array('Diglia'              ,'Groach Sea'          ,'Yes','No' ),
	array('Diglia'              ,'Dog Sea'             ,'Yes','No' ),
	array('Dilington'           ,'East Royal Ocean'    ,'Yes','No' ),
	array('Docha'               ,'Dark Koga Straits'   ,'Yes','No' ),
	array('Docha'               ,'Dog Sea'             ,'Yes','No' ),
	array('Dog Sea'             ,'Dark Koga Straits'   ,'Yes','No' ),
	array('Dog Sea'             ,'Groach Sea'          ,'Yes','No' ),
	array('Duteny'              ,'East Royal Ocean'    ,'Yes','No' ),
	array('Duteny'              ,'Dark Koga Straits'   ,'Yes','No' ),
	array('Easton'              ,'East Royal Ocean'    ,'Yes','No' ),
	array('Easton'              ,'East Mystic Ocean'   ,'Yes','No' ),
	array('Fidiga'              ,'Groach Sea'          ,'Yes','No' ),
	array('Fidiga'              ,'Blissful Sea'        ,'Yes','No' ),
	array('Gengor'              ,'Big Guntar Straits'  ,'Yes','No' ),
	array('Gilington'           ,'North Magestic Ocean','Yes','No' ),
	array('Gocha'               ,'Big Guntar Straits'  ,'Yes','No' ),
	array('Gocha'               ,'Groach Sea'          ,'Yes','No' ),
	array('Groach Sea'          ,'Big Guntar Straits'  ,'Yes','No' ),
	array('Guteny'              ,'North Magestic Ocean','Yes','No' ),
	array('Guteny'              ,'Big Guntar Straits'  ,'Yes','No' ),
	array('Harkoom'             ,'Lucky Sea'           ,'Yes','No' ),
	array('Harkoom'             ,'Saint\\\'s Sea'      ,'Yes','No' ),
	array('Jalta'               ,'Dog Sea'             ,'Yes','No' ),
	array('Jalta'               ,'King\\\'s Sea'       ,'Yes','No' ),
	array('Kengor'              ,'Dark Koga Straits'   ,'Yes','No' ),
	array('Kilington'           ,'East Mystic Ocean'   ,'Yes','No' ),
	array('King\\\'s Sea'       ,'Dark Koga Straits'   ,'Yes','No' ),
	array('King\\\'s Sea'       ,'Dog Sea'             ,'Yes','No' ),
	array('Kocha'               ,'Dark Koga Straits'   ,'Yes','No' ),
	array('Kocha'               ,'King\\\'s Sea'       ,'Yes','No' ),
	array('Kuteny'              ,'East Mystic Ocean'   ,'Yes','No' ),
	array('Kuteny'              ,'Dark Koga Straits'   ,'Yes','No' ),
	array('Lengor'              ,'San Lasta Straits'   ,'Yes','No' ),
	array('Liklia'              ,'King\\\'s Sea'       ,'Yes','No' ),
	array('Liklia'              ,'Lucky Sea'           ,'Yes','No' ),
	array('Lilington'           ,'South Turgid Ocean'  ,'Yes','No' ),
	array('Locha'               ,'San Lasta Straits'   ,'Yes','No' ),
	array('Locha'               ,'Lucky Sea'           ,'Yes','No' ),
	array('Lucky Sea'           ,'San Lasta Straits'   ,'Yes','No' ),
	array('Lucky Sea'           ,'King\\\'s Sea'       ,'Yes','No' ),
	array('Luteny'              ,'South Turgid Ocean'  ,'Yes','No' ),
	array('Luteny'              ,'San Lasta Straits'   ,'Yes','No' ),
	array('Morga'               ,'Twine Sea'           ,'Yes','No' ),
	array('Morga'               ,'Zwik Sea'            ,'Yes','No' ),
	array('Nortia'              ,'North Turgid Ocean'  ,'Yes','No' ),
	array('Nortia'              ,'North Magestic Ocean','Yes','No' ),
	array('Saint\\\'s Sea'      ,'San Lasta Straits'   ,'Yes','No' ),
	array('Saint\\\'s Sea'      ,'Lucky Sea'           ,'Yes','No' ),
	array('San Lasta Straits'   ,'South Turgid Ocean'  ,'Yes','No' ),
	array('San Lasta Straits'   ,'South Magestic Ocean','Yes','No' ),
	array('San Lasta Straits'   ,'Antoria'             ,'Yes','No' ),
	array('Sengor'              ,'San Lasta Straits'   ,'Yes','No' ),
	array('Silington'           ,'South Magestic Ocean','Yes','No' ),
	array('Sitlia'              ,'Saint\\\'s Sea'      ,'Yes','No' ),
	array('Sitlia'              ,'Twine Sea'           ,'Yes','No' ),
	array('Socha'               ,'San Lasta Straits'   ,'Yes','No' ),
	array('Socha'               ,'Saint\\\'s Sea'      ,'Yes','No' ),
	array('South Magestic Ocean','North Magestic Ocean','Yes','No' ),
	array('South Turgid Ocean'  ,'North Turgid Ocean'  ,'Yes','No' ),
	array('Suteny'              ,'South Magestic Ocean','Yes','No' ),
	array('Suteny'              ,'San Lasta Straits'   ,'Yes','No' ),
	array('Tengor'              ,'Thin Zany Straits'   ,'Yes','No' ),
	array('Thin Zany Straits'   ,'West Royal Ocean'    ,'Yes','No' ),
	array('Thin Zany Straits'   ,'West Mystic Ocean'   ,'Yes','No' ),
	array('Thin Zany Straits'   ,'Weston'              ,'Yes','No' ),
	array('Tilington'           ,'West Royal Ocean'    ,'Yes','No' ),
	array('Tocha'               ,'Thin Zany Straits'   ,'Yes','No' ),
	array('Tocha'               ,'Twine Sea'           ,'Yes','No' ),
	array('Tuteny'              ,'West Royal Ocean'    ,'Yes','No' ),
	array('Tuteny'              ,'Thin Zany Straits'   ,'Yes','No' ),
	array('Twine Sea'           ,'Thin Zany Straits'   ,'Yes','No' ),
	array('Twine Sea'           ,'Saint\\\'s Sea'      ,'Yes','No' ),
	array('West Mystic Ocean'   ,'East Mystic Ocean'   ,'Yes','No' ),
	array('West Royal Ocean'    ,'East Royal Ocean'    ,'Yes','No' ),
	array('Weston'              ,'West Royal Ocean'    ,'Yes','No' ),
	array('Weston'              ,'West Mystic Ocean'   ,'Yes','No' ),
	array('Zengor'              ,'Thin Zany Straits'   ,'Yes','No' ),
	array('Ziblia'              ,'Zwik Sea'            ,'Yes','No' ),
	array('Ziblia'              ,'Blissful Sea'        ,'Yes','No' ),
	array('Zilington'           ,'West Mystic Ocean'   ,'Yes','No' ),
	array('Zocha'               ,'Thin Zany Straits'   ,'Yes','No' ),
	array('Zocha'               ,'Zwik Sea'            ,'Yes','No' ),
	array('Zuteny'              ,'West Mystic Ocean'   ,'Yes','No' ),
	array('Zuteny'              ,'Thin Zany Straits'   ,'Yes','No' ),
	array('Zwik Sea'            ,'Thin Zany Straits'   ,'Yes','No' ),
	array('Zwik Sea'            ,'Twine Sea'           ,'Yes','No' ),
	array('Cantaria (A Coast)'  ,'Bilington'           ,'Yes','No' ),
	array('Cantaria (A Coast)'  ,'Lilington'           ,'Yes','No' ),
	array('Cantaria (A Coast)'  ,'North Turgid Ocean'  ,'Yes','No' ),
	array('Cantaria (A Coast)'  ,'South Turgid Ocean'  ,'Yes','No' ),
	array('Cantaria (B Coast)'  ,'Zilington'           ,'Yes','No' ),
	array('Cantaria (B Coast)'  ,'Kilington'           ,'Yes','No' ),
	array('Cantaria (B Coast)'  ,'East Mystic Ocean'   ,'Yes','No' ),
	array('Cantaria (B Coast)'  ,'West Mystic Ocean'   ,'Yes','No' ),
	array('Chimara (A Coast)'   ,'South Magestic Ocean','Yes','No' ),
	array('Chimara (A Coast)'   ,'North Magestic Ocean','Yes','No' ),
	array('Chimara (A Coast)'   ,'Silington'           ,'Yes','No' ),
	array('Chimara (A Coast)'   ,'Gilington'           ,'Yes','No' ),
	array('Chimara (B Coast)'   ,'West Royal Ocean'    ,'Yes','No' ),
	array('Chimara (B Coast)'   ,'East Royal Ocean'    ,'Yes','No' ),
	array('Chimara (B Coast)'   ,'Tilington'           ,'Yes','No' ),
	array('Chimara (B Coast)'   ,'Dilington'           ,'Yes','No' ),
	array('Dogaru (A Coast)'    ,'Diglia'              ,'Yes','No' ),
	array('Dogaru (A Coast)'    ,'Groach Sea'          ,'Yes','No' ),
	array('Dogaru (A Coast)'    ,'Gocha'               ,'Yes','No' ),
	array('Dogaru (B Coast)'    ,'Diglia'              ,'Yes','No' ),
	array('Dogaru (B Coast)'    ,'Dog Sea'             ,'Yes','No' ),
	array('Dogaru (B Coast)'    ,'Docha'               ,'Yes','No' ),
	array('Lokaru (A Coast)'    ,'Liklia'              ,'Yes','No' ),
	array('Lokaru (A Coast)'    ,'Lucky Sea'           ,'Yes','No' ),
	array('Lokaru (A Coast)'    ,'Locha'               ,'Yes','No' ),
	array('Lokaru (B Coast)'    ,'Liklia'              ,'Yes','No' ),
	array('Lokaru (B Coast)'    ,'King\\\'s Sea'       ,'Yes','No' ),
	array('Lokaru (B Coast)'    ,'Kocha'               ,'Yes','No' ),
	array('Sotaru (A Coast)'    ,'Sitlia'              ,'Yes','No' ),
	array('Sotaru (A Coast)'    ,'Saint\\\'s Sea'      ,'Yes','No' ),
	array('Sotaru (A Coast)'    ,'Socha'               ,'Yes','No' ),
	array('Sotaru (B Coast)'    ,'Sitlia'              ,'Yes','No' ),
	array('Sotaru (B Coast)'    ,'Twine Sea'           ,'Yes','No' ),
	array('Sotaru (B Coast)'    ,'Tocha'               ,'Yes','No' ),
	array('Zobaru (A Coast)'    ,'Ziblia'              ,'Yes','No' ),
	array('Zobaru (A Coast)'    ,'Blissful Sea'        ,'Yes','No' ),
	array('Zobaru (A Coast)'    ,'Bocha'               ,'Yes','No' ),
	array('Zobaru (B Coast)'    ,'Zwik Sea'            ,'Yes','No' ),
	array('Zobaru (B Coast)'    ,'Zocha'               ,'Yes','No' ),
	array('Zobaru (B Coast)'    ,'Ziblia'              ,'Yes','No' ),
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$from]->addBorder(InstallTerritory::$Territories[$to]  ,$fleets,$armies);
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);

?>