<?php
/*
	Copyright (C) 2010 Oliver Auth

	This file is part of the Colonial variant for webDiplomacy

	The Colonial variant for webDiplomacy is free software: you can redistribute
	it and/or modify it under the terms of the GNU Affero General Public License
	as published by the Free Software Foundation, either version 3 of the License,
	or (at your option) any later version.

	The Colonial variant for webDiplomacy is distributed in the hope that it will
	be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of 
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
	See the GNU General Public License for more details.

	You should have received a copy of the GNU Affero General Public License
	along with webDiplomacy. If not, see <http://www.gnu.org/licenses/>.

*/

require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Sakhalin'               , 'Coast' , 'Yes' ,1320, 95,518, 38, 'Neutral' , 'No'     ),
	array('Tashkent'               , 'Land'  , 'Yes' , 540,240,229, 96, 'Neutral' , 'No'     ),
	array('Bengal'                 , 'Coast' , 'Yes' , 850,525,349,212, 'Neutral' , 'No'     ),
	array('Kashmir'                , 'Land'  , 'Yes' , 660,367,263,148, 'Neutral' , 'No'     ),
	array('Ceylon'                 , 'Coast' , 'Yes' , 777,773,301,313, 'Neutral' , 'No'     ),
	array('Mongolia'               , 'Land'  , 'Yes' , 930,200,372, 79, 'Neutral' , 'No'     ),
	array('Kashgar'                , 'Land'  , 'Yes' , 690,315,274,120, 'Neutral' , 'No'     ),
	array('Chungking'              , 'Land'  , 'Yes' ,1020,415,431,190, 'Neutral' , 'No'     ),
	array('Hong Kong'              , 'Coast' , 'Yes' ,1140,570,454,228, 'Britain' , 'No'     ),
	array('Singapore'              , 'Coast' , 'Yes' ,1088,838,435,337, 'Britain' , 'No'     ),
	array('Aden'                   , 'Coast' , 'Yes' , 300,658,120,259, 'Britain' , 'No'     ),
	array('Delhi'                  , 'Land'  , 'Yes' , 705,490,278,190, 'Britain' , 'No'     ),
	array('Bombay'                 , 'Coast' , 'Yes' , 670,585,275,241, 'Britain' , 'No'     ),
	array('Madras'                 , 'Coast' , 'Yes' , 734,715,295,281, 'Britain' , 'No'     ),
	array('Punjab'                 , 'Land'  , 'No'  , 655,426,262,171, 'Britain' , 'No'     ),
	array('Rajputana'              , 'Coast' , 'No'  , 638,517,255,210, 'Britain' , 'No'     ),
	array('Lucknow'                , 'Land'  , 'No'  , 778,510,311,204, 'Britain' , 'No'     ),
	array('Nagpur'                 , 'Land'  , 'No'  , 740,563,300,223, 'Britain' , 'No'     ),
	array('Mysore'                 , 'Coast' , 'No'  , 683,650,273,261, 'Britain' , 'No'     ),
	array('Hyderabad'              , 'Coast' , 'No'  , 755,615,299,255, 'Britain' , 'No'     ),
	array('Constantinople'         , 'Coast' , 'Yes' ,  38,244,  5,105, 'Turkey'  , 'No'     ),
	array('Angora'                 , 'Coast' , 'Yes' , 165,308, 35,132, 'Turkey'  , 'No'     ),
	array('Baghdad'                , 'Coast' , 'Yes' , 260,408,110,160, 'Turkey'  , 'No'     ),
	array('Armenia'                , 'Coast' , 'No'  , 235,318, 91,120, 'Turkey'  , 'No'     ),
	array('Syria'                  , 'Coast' , 'No'  , 190,398, 75,150, 'Turkey'  , 'No'     ),
	array('Mecca'                  , 'Coast' , 'No'  , 205,498, 70,180, 'Turkey'  , 'No'     ),
	array('Odessa'                 , 'Coast' , 'Yes' , 140,158, 55, 75, 'Russia'  , 'No'     ),
	array('Moscow'                 , 'Land'  , 'Yes' , 275,148,110, 40, 'Russia'  , 'No'     ),
	array('Omsk'                   , 'Land'  , 'Yes' , 620, 25,259, 12, 'Russia'  , 'No'     ),
	array('Vladivostok'            , 'Coast' , 'Yes' ,1200,110,515, 65, 'Russia'  , 'No'     ),
	array('Port Arthur'            , 'Coast' , 'Yes' ,1200,255,475,106, 'Russia'  , 'No'     ),
	array('Baku'                   , 'Coast' , 'No'  , 250,247, 90, 90, 'Russia'  , 'No'     ),
	array('Bokhara'                , 'Land'  , 'No'  , 440,297,175,112, 'Russia'  , 'No'     ),
	array('Orenburg'               , 'Land'  , 'No'  , 475,140,190, 60, 'Russia'  , 'No'     ),
	array('Perm'                   , 'Land'  , 'No'  , 440, 27,180, 15, 'Russia'  , 'No'     ),
	array('Akmolinsk'              , 'Land'  , 'No'  , 595,145,245, 53, 'Russia'  , 'No'     ),
	array('Kirghiz'                , 'Land'  , 'No'  , 640,240,255, 85, 'Russia'  , 'No'     ),
	array('Semipalatinsk'          , 'Land'  , 'No'  , 700,155,280, 63, 'Russia'  , 'No'     ),
	array('Krasnoyarsk'            , 'Land'  , 'No'  , 810,107,315, 50, 'Russia'  , 'No'     ),
	array('Irkutsk'                , 'Land'  , 'No'  ,1030, 48,390, 48, 'Russia'  , 'No'     ),
	array('Otaru'                  , 'Coast' , 'Yes' ,1380,197,545, 80, 'Japan'   , 'No'     ),
	array('Akita'                  , 'Coast' , 'No'  ,1407,270,559,115, 'Japan'   , 'No'     ),
	array('Tokyo'                  , 'Coast' , 'Yes' ,1413,315,563,133, 'Japan'   , 'No'     ),
	array('Kyoto'                  , 'Coast' , 'Yes' ,1370,327,540,135, 'Japan'   , 'No'     ),
	array('Kyushu'                 , 'Coast' , 'Yes' ,1329,388,530,155, 'Japan'   , 'No'     ),
	array('Manchuria'              , 'Coast' , 'Yes' ,1180,197,445, 62, 'China'   , 'No'     ),
	array('Peking'                 , 'Land'  , 'Yes' ,1070,245,427, 93, 'China'   , 'No'     ),
	array('Sinkiang'               , 'Land'  , 'Yes' , 860,370,335,137, 'China'   , 'No'     ),
	array('Shanghai'               , 'Coast' , 'Yes' ,1130,348,450,140, 'China'   , 'No'     ),
	array('Canton'                 , 'Coast' , 'Yes' ,1130,534,450,211, 'China'   , 'No'     ),
	array('Urumchi'                , 'Land'  , 'No'  , 740,243,296, 97, 'China'   , 'No'     ),
	array('Langchow'               , 'Land'  , 'No'  , 973,300,389,122, 'China'   , 'No'     ),
	array('Nanchung'               , 'Coast' , 'No'  ,1165,470,466,189, 'China'   , 'No'     ),
	array('Yunnan'                 , 'Land'  , 'No'  , 990,480,396,197, 'China'   , 'No'     ),
	array('Tibet'                  , 'Land'  , 'No'  , 745,395,328,173, 'China'   , 'No'     ),
	array('Tongking'               , 'Coast' , 'Yes' ,1060,555,435,223, 'France'  , 'No'     ),
	array('Cambodia'               , 'Coast' , 'No'  ,1080,653,430,268, 'France'  , 'No'     ),
	array('Annam'                  , 'Coast' , 'Yes' ,1130,638,455,257, 'France'  , 'No'     ),
	array('Cochin'                 , 'Coast' , 'Yes' ,1125,685,445,279, 'France'  , 'No'     ),
	array('Sumatra'                , 'Coast' , 'Yes' ,1055,890,403,330, 'Holland' , 'No'     ),
	array('Java'                   , 'Coast' , 'Yes' ,1155,955,441,379, 'Holland' , 'No'     ),
	array('Borneo'                 , 'Coast' , 'Yes' ,1217,855,490,335, 'Holland' , 'No'     ),
	array('Celebes'                , 'Coast' , 'No'  ,1295,868,518,347, 'Holland' , 'No'     ),
	array('Rumania'                , 'Coast' , 'Yes' ,  40,188, 17, 80, 'Neutral' , 'No'     ),
	array('Tabriz'                 , 'Land'  , 'Yes' , 300,345,117,142, 'Neutral' , 'No'     ),
	array('Egypt'                  , 'Coast' , 'Yes' ,  75,523, 30,205, 'Neutral' , 'No'     ),
	array('Sudan'                  , 'Coast' , 'Yes' ,  75,647, 30,260, 'Neutral' , 'No'     ),
	array('Abysinnia'              , 'Land'  , 'No'  , 190,740, 80,300, 'Neutral' , 'No'     ),
	array('Somalia'                , 'Coast' , 'No'  , 290,807,123,315, 'Neutral' , 'No'     ),
	array('Eritrea'                , 'Coast' , 'No'  , 200,650, 92,275, 'Neutral' , 'No'     ),
	array('Arabia'                 , 'Coast' , 'No'  , 325,550,120,207, 'Neutral' , 'Parent' ),
	array('Arabia (North Coast)'   , 'Coast' , 'No'  , 348,500,128,194, 'Neutral' , 'North'  ),
	array('Arabia (South Coast)'   , 'Coast' , 'No'  , 375,645,150,255, 'Neutral' , 'South'  ),
	array('Oman'                   , 'Coast' , 'No'  , 450,565,180,225, 'Neutral' , 'No'     ),
	array('Shiraz'                 , 'Coast' , 'Yes' , 360,422,135,170, 'Neutral' , 'No'     ),
	array('Persia'                 , 'Coast' , 'Yes' , 450,410,175,160, 'Neutral' , 'No'     ),
	array('Seoul'                  , 'Coast' , 'Yes' ,1233,263,493, 97, 'Neutral' , 'Parent' ),
	array('Seoul (East Coast)'     , 'Coast' , 'Yes' ,1250,250,500,100, 'Neutral' , 'East'   ),
	array('Seoul (West Coast)'     , 'Coast' , 'Yes' ,1217,288,490,115, 'Neutral' , 'West'   ),
	array('Fusan'                  , 'Coast' , 'Yes' ,1265,315,500,130, 'Neutral' , 'No'     ),
	array('Afghanistan'            , 'Land'  , 'No'  , 540,377,218,154, 'Neutral' , 'No'     ),
	array('Karachi'                , 'Coast' , 'Yes' , 525,490,210,200, 'Neutral' , 'No'     ),
	array('Nepal'                  , 'Land'  , 'No'  , 758,466,318,191, 'Neutral' , 'No'     ),
	array('Formosa'                , 'Coast' , 'Yes' ,1297,470,519,188, 'Neutral' , 'No'     ),
	array('Manila'                 , 'Coast' , 'Yes' ,1290,561,512,223, 'Neutral' , 'No'     ),
	array('Cebu'                   , 'Coast' , 'Yes' ,1321,655,539,259, 'Neutral' , 'No'     ),                                  
	array('Davao'                  , 'Coast' , 'Yes' ,1350,710,537,280, 'Neutral' , 'No'     ),
	array('Assam'                  , 'Land'  , 'Yes' , 915,478,356,194, 'Neutral' , 'No'     ),
	array('Upper Burma'            , 'Coast' , 'Yes' , 920,570,367,223, 'Neutral' , 'No'     ),
	array('Mandalay'               , 'Land'  , 'Yes' , 975,557,397,230, 'Neutral' , 'No'     ),
	array('Rangoon'                , 'Coast' , 'Yes' , 945,620,384,250, 'Neutral' , 'No'     ),
	array('North Siam'             , 'Land'  , 'No'  ,1013,610,405,245, 'Neutral' , 'No'     ),
	array('Bangkok'                , 'Coast' , 'Yes' ,1025,660,405,273, 'Neutral' , 'Parent' ),
	array('Bangkok (East Coast)'   , 'Coast' , 'Yes' ,1025,710,410,270, 'Neutral' , 'East'   ),
	array('Bangkok (West Coast)'   , 'Coast' , 'Yes' ,1000,735,400,290, 'Neutral' , 'West'   ),
	array('Malaya'                 , 'Coast' , 'Yes' ,1040,780,415,308, 'Neutral' , 'No'     ),
	array('Sarawak'                , 'Coast' , 'Yes' ,1188,802,474,320, 'Neutral' , 'No'     ),
	array('New Guinea'             , 'Coast' , 'Yes' ,1395,900,554,363, 'Neutral' , 'No'     ),
	array('Red Sea'                , 'Sea'   , 'No'  , 195,580, 79,227, 'Neutral' , 'No'     ),
	array('Black Sea'              , 'Sea'   , 'No'  , 100,250, 40,100, 'Neutral' , 'No'     ),
	array('Mediterranean Sea'      , 'Sea'   , 'No'  ,  65,377, 15,148, 'Neutral' , 'No'     ),
	array('Persian Gulf'           , 'Sea'   , 'No'  , 442,515,179,205, 'Neutral' , 'No'     ),
	array('Okhotsk Sea'            , 'Sea'   , 'No'  ,1400, 70,565, 40, 'Neutral' , 'No'     ),
	array('Sea of Japan'           , 'Sea'   , 'No'  ,1310,258,526, 97, 'Neutral' , 'No'     ),
	array('Yellow Sea'             , 'Sea'   , 'No'  ,1220,350,484,130, 'Neutral' , 'No'     ),
	array('East China Sea'         , 'Sea'   , 'No'  ,1265,418,508,165, 'Neutral' , 'No'     ),
	array('Upper Pacific'          , 'Sea'   , 'No'  ,1413,420,565,162, 'Neutral' , 'No'     ),
	array('South China Sea'        , 'Sea'   , 'No'  ,1200,550,491,205, 'Neutral' , 'No'     ),
	array('Luzon Strait'           , 'Sea'   , 'No'  ,1230,625,491,240, 'Neutral' , 'No'     ),
	array('Middle Pacific'         , 'Sea'   , 'No'  ,1443,600,577,241, 'Neutral' , 'No'     ),
	array('Lower Pacific'          , 'Sea'   , 'No'  ,1448,755,579,304, 'Neutral' , 'No'     ),
	array('Sulu Sea'               , 'Sea'   , 'No'  ,1235,705,489,275, 'Neutral' , 'No'     ),
	array('Celebes Sea'            , 'Sea'   , 'No'  ,1300,782,509,322, 'Neutral' , 'No'     ),
	array('Arabian Sea'            , 'Sea'   , 'No'  , 520,622,220,250, 'Neutral' , 'No'     ),
	array('Gulf of Aden'           , 'Sea'   , 'No'  , 388,860,155,345, 'Neutral' , 'No'     ),
	array('West Indian Ocean'      , 'Sea'   , 'No'  , 618,866,247,347, 'Neutral' , 'No'     ),
	array('Gulf of Manaar'         , 'Sea'   , 'No'  , 805,710,322,284, 'Neutral' , 'No'     ),
	array('Bay of Bengal'          , 'Sea'   , 'No'  , 868,628,347,243, 'Neutral' , 'No'     ),
	array('Southeast Indian Ocean' , 'Sea'   , 'No'  , 913,940,365,377, 'Neutral' , 'No'     ),
	array('East Indian Ocean'      , 'Sea'   , 'No'  , 875,830,350,333, 'Neutral' , 'No'     ),
	array('Andaman Sea'            , 'Sea'   , 'No'  , 948,710,379,277, 'Neutral' , 'No'     ),
	array('Gulf of Siam'           , 'Sea'   , 'No'  ,1060,720,422,289, 'Neutral' , 'No'     ),
	array('Sunda Sea'              , 'Sea'   , 'No'  ,1160,753,464,297, 'Neutral' , 'No'     ),
	array('Java Sea'               , 'Sea'   , 'No'  ,1125,890,459,366, 'Neutral' , 'No'     ),
	array('Timor Sea'              , 'Sea'   , 'No'  ,1330,965,531,383, 'Neutral' , 'No'     )
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $x, $y, $sx, $sy, $country)=$territoryRawRow;
	if( $country=='Neutral' )
		$countryID=0;
	else
		$countryID=$this->countryID($country);
		
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array( 'Constantinople'        , 'Rumania'               , 'Yes', 'Yes' ),
	array( 'Rumania'               , 'Odessa'                , 'Yes', 'Yes' ),
	array( 'Odessa'                , 'Baku'                  , 'Yes', 'Yes' ),
	array( 'Baku'                  , 'Armenia'               , 'Yes', 'Yes' ),
	array( 'Armenia'               , 'Angora'                , 'Yes', 'Yes' ),
	array( 'Angora'                , 'Syria'                 , 'Yes', 'Yes' ),
	array( 'Syria'                 , 'Egypt'                 , 'Yes', 'Yes' ),
	array( 'Egypt'                 , 'Mecca'                 , 'Yes', 'Yes' ),
	array( 'Egypt'                 , 'Sudan'                 , 'Yes', 'Yes' ),
	array( 'Sudan'                 , 'Eritrea'               , 'Yes', 'Yes' ),
	array( 'Eritrea'               , 'Somalia'               , 'Yes', 'Yes' ),
	array( 'Mecca'                 , 'Aden'                  , 'Yes', 'Yes' ),
	array( 'Baghdad'               , 'Shiraz'                , 'Yes', 'Yes' ),
	array( 'Shiraz'                , 'Persia'                , 'Yes', 'Yes' ),
	array( 'Persia'                , 'Karachi'               , 'Yes', 'Yes' ),
	array( 'Karachi'               , 'Rajputana'             , 'Yes', 'Yes' ),
	array( 'Rajputana'             , 'Bombay'                , 'Yes', 'Yes' ),
	array( 'Bombay'                , 'Mysore'                , 'Yes', 'Yes' ),
	array( 'Mysore'                , 'Madras'                , 'Yes', 'Yes' ),
	array( 'Madras'                , 'Hyderabad'             , 'Yes', 'Yes' ),
	array( 'Hyderabad'             , 'Bengal'                , 'Yes', 'Yes' ),
	array( 'Bengal'                , 'Upper Burma'           , 'Yes', 'Yes' ),
	array( 'Upper Burma'           , 'Rangoon'               , 'Yes', 'Yes' ),
	array( 'Cambodia'              , 'Cochin'                , 'Yes', 'Yes' ),
	array( 'Cochin'                , 'Annam'                 , 'Yes', 'Yes' ),
	array( 'Annam'                 , 'Tongking'              , 'Yes', 'Yes' ),
	array( 'Tongking'              , 'Canton'                , 'Yes', 'Yes' ),
	array( 'Canton'                , 'Nanchung'              , 'Yes', 'Yes' ),
	array( 'Nanchung'              , 'Shanghai'              , 'Yes', 'Yes' ),
	array( 'Shanghai'              , 'Manchuria'             , 'Yes', 'Yes' ),
	array( 'Manchuria'             , 'Port Arthur'           , 'Yes', 'Yes' ),
	array( 'Constantinople'        , 'Angora'                , 'Yes', 'Yes' ),
	array( 'Malaya'                , 'Singapore'             , 'Yes', 'Yes' ),
	array( 'Canton'                , 'Hong Kong'             , 'Yes', 'Yes' ),
	array( 'Sakhalin'              , 'Otaru'                 , 'Yes', 'Yes' ),
	array( 'Akita'                 , 'Otaru'                 , 'Yes', 'Yes' ),
	array( 'Kyoto'                 , 'Kyushu'                , 'Yes', 'Yes' ),
	array( 'Kyoto'                 , 'Akita'                 , 'Yes', 'Yes' ),
	array( 'Kyoto'                 , 'Tokyo'                 , 'Yes', 'Yes' ),
	array( 'Manila'                , 'Cebu'                  , 'Yes', 'Yes' ),
	array( 'Cebu'                  , 'Davao'                 , 'Yes', 'Yes' ),
	array( 'Borneo'                , 'Sarawak'               , 'Yes', 'Yes' ),
	array( 'Black Sea'             , 'Rumania'               , 'Yes', 'No'  ),
	array( 'Black Sea'             , 'Odessa'                , 'Yes', 'No'  ),
	array( 'Black Sea'             , 'Baku'                  , 'Yes', 'No'  ),
	array( 'Black Sea'             , 'Armenia'               , 'Yes', 'No'  ),
	array( 'Black Sea'             , 'Angora'                , 'Yes', 'No'  ),
	array( 'Black Sea'             , 'Mediterranean Sea'     , 'Yes', 'No'  ),
	array( 'Mediterranean Sea'     , 'Constantinople'        , 'Yes', 'No'  ),
	array( 'Mediterranean Sea'     , 'Angora'                , 'Yes', 'No'  ),
	array( 'Mediterranean Sea'     , 'Syria'                 , 'Yes', 'No'  ),
	array( 'Mediterranean Sea'     , 'Egypt'                 , 'Yes', 'No'  ),
	array( 'Red Sea'               , 'Mecca'                 , 'Yes', 'No'  ),
	array( 'Red Sea'               , 'Egypt'                 , 'Yes', 'No'  ),
	array( 'Red Sea'               , 'Sudan'                 , 'Yes', 'No'  ),
	array( 'Red Sea'               , 'Eritrea'               , 'Yes', 'No'  ),
	array( 'Red Sea'               , 'Aden'                  , 'Yes', 'No'  ),
	array( 'Red Sea'               , 'Gulf of Aden'          , 'Yes', 'No'  ),
	array( 'Persian Gulf'          , 'Baghdad'               , 'Yes', 'No'  ),
	array( 'Persian Gulf'          , 'Shiraz'                , 'Yes', 'No'  ),
	array( 'Persian Gulf'          , 'Persia'                , 'Yes', 'No'  ),
	array( 'Persian Gulf'          , 'Karachi'               , 'Yes', 'No'  ),
	array( 'Persian Gulf'          , 'Arabian Sea'           , 'Yes', 'No'  ),
	array( 'Persian Gulf'          , 'Oman'                  , 'Yes', 'No'  ),
	array( 'Gulf of Aden'          , 'Aden'                  , 'Yes', 'No'  ),
	array( 'Gulf of Aden'          , 'Arabian Sea'           , 'Yes', 'No'  ),
	array( 'Gulf of Aden'          , 'West Indian Ocean'     , 'Yes', 'No'  ),
	array( 'Gulf of Aden'          , 'Somalia'               , 'Yes', 'No'  ),
	array( 'Gulf of Aden'          , 'Eritrea'               , 'Yes', 'No'  ),
	array( 'Arabian Sea'           , 'Oman'                  , 'Yes', 'No'  ),
	array( 'Arabian Sea'           , 'Karachi'               , 'Yes', 'No'  ),
	array( 'Arabian Sea'           , 'Rajputana'             , 'Yes', 'No'  ),
	array( 'Arabian Sea'           , 'Bombay'                , 'Yes', 'No'  ),
	array( 'Arabian Sea'           , 'Mysore'                , 'Yes', 'No'  ),
	array( 'Arabian Sea'           , 'West Indian Ocean'     , 'Yes', 'No'  ),
	array( 'West Indian Ocean'     , 'Mysore'                , 'Yes', 'No'  ),
	array( 'West Indian Ocean'     , 'Madras'                , 'Yes', 'No'  ),
	array( 'West Indian Ocean'     , 'Gulf of Manaar'        , 'Yes', 'No'  ),
	array( 'West Indian Ocean'     , 'Ceylon'                , 'Yes', 'No'  ),
	array( 'West Indian Ocean'     , 'East Indian Ocean'     , 'Yes', 'No'  ),
	array( 'West Indian Ocean'     , 'Southeast Indian Ocean', 'Yes', 'No'  ),
	array( 'Gulf of Manaar'        , 'Madras'                , 'Yes', 'No'  ),
	array( 'Gulf of Manaar'        , 'Ceylon'                , 'Yes', 'No'  ),
	array( 'Gulf of Manaar'        , 'Hyderabad'             , 'Yes', 'No'  ),
	array( 'Gulf of Manaar'        , 'Bay of Bengal'         , 'Yes', 'No'  ),
	array( 'Gulf of Manaar'        , 'Andaman Sea'           , 'Yes', 'No'  ),
	array( 'Gulf of Manaar'        , 'East Indian Ocean'     , 'Yes', 'No'  ),
	array( 'Bay of Bengal'         , 'Hyderabad'             , 'Yes', 'No'  ),
	array( 'Bay of Bengal'         , 'Bengal'                , 'Yes', 'No'  ),
	array( 'Bay of Bengal'         , 'Upper Burma'           , 'Yes', 'No'  ),
	array( 'Bay of Bengal'         , 'Rangoon'               , 'Yes', 'No'  ),
	array( 'Bay of Bengal'         , 'Andaman Sea'           , 'Yes', 'No'  ),
	array( 'Andaman Sea'           , 'Rangoon'               , 'Yes', 'No'  ),
	array( 'Andaman Sea'           , 'Malaya'                , 'Yes', 'No'  ),
	array( 'Andaman Sea'           , 'Java Sea'              , 'Yes', 'No'  ),
	array( 'Andaman Sea'           , 'Sumatra'               , 'Yes', 'No'  ),
	array( 'Andaman Sea'           , 'East Indian Ocean'     , 'Yes', 'No'  ),
	array( 'East Indian Ocean'     , 'Sumatra'               , 'Yes', 'No'  ),
	array( 'East Indian Ocean'     , 'Southeast Indian Ocean', 'Yes', 'No'  ),
	array( 'East Indian Ocean'     , 'Ceylon'                , 'Yes', 'No'  ),
	array( 'Southeast Indian Ocean', 'Sumatra'               , 'Yes', 'No'  ),
	array( 'Southeast Indian Ocean', 'Java Sea'              , 'Yes', 'No'  ),
	array( 'Southeast Indian Ocean', 'Java'                  , 'Yes', 'No'  ),
	array( 'Southeast Indian Ocean', 'Timor Sea'             , 'Yes', 'No'  ),
	array( 'Java Sea'              , 'Sumatra'               , 'Yes', 'No'  ),
	array( 'Java Sea'              , 'Malaya'                , 'Yes', 'No'  ),
	array( 'Java Sea'              , 'Singapore'             , 'Yes', 'No'  ),
	array( 'Java Sea'              , 'Sunda Sea'             , 'Yes', 'No'  ),
	array( 'Java Sea'              , 'Sarawak'               , 'Yes', 'No'  ),
	array( 'Java Sea'              , 'Borneo'                , 'Yes', 'No'  ),
	array( 'Java Sea'              , 'Celebes Sea'           , 'Yes', 'No'  ),
	array( 'Java Sea'              , 'Celebes'               , 'Yes', 'No'  ),
	array( 'Java Sea'              , 'Timor Sea'             , 'Yes', 'No'  ),
	array( 'Java Sea'              , 'Java'                  , 'Yes', 'No'  ),
	array( 'Gulf of Siam'          , 'Malaya'                , 'Yes', 'No'  ),
	array( 'Gulf of Siam'          , 'Cambodia'              , 'Yes', 'No'  ),
	array( 'Gulf of Siam'          , 'Cochin'                , 'Yes', 'No'  ),
	array( 'Gulf of Siam'          , 'Annam'                 , 'Yes', 'No'  ),
	array( 'Gulf of Siam'          , 'South China Sea'       , 'Yes', 'No'  ),
	array( 'Gulf of Siam'          , 'Sunda Sea'             , 'Yes', 'No'  ),
	array( 'Sunda Sea'             , 'Malaya'                , 'Yes', 'No'  ),
	array( 'Sunda Sea'             , 'South China Sea'       , 'Yes', 'No'  ),
	array( 'Sunda Sea'             , 'Sulu Sea'              , 'Yes', 'No'  ),
	array( 'Sunda Sea'             , 'Sarawak'               , 'Yes', 'No'  ),
	array( 'South China Sea'       , 'Annam'                 , 'Yes', 'No'  ),
	array( 'South China Sea'       , 'Tongking'              , 'Yes', 'No'  ),
	array( 'South China Sea'       , 'Canton'                , 'Yes', 'No'  ),
	array( 'South China Sea'       , 'Nanchung'              , 'Yes', 'No'  ),
	array( 'South China Sea'       , 'East China Sea'        , 'Yes', 'No'  ),
	array( 'South China Sea'       , 'Formosa'               , 'Yes', 'No'  ),
	array( 'South China Sea'       , 'Luzon Strait'          , 'Yes', 'No'  ),
	array( 'South China Sea'       , 'Hong Kong'             , 'Yes', 'No'  ),
	array( 'South China Sea'       , 'Sulu Sea'              , 'Yes', 'No'  ),
	array( 'Luzon Strait'          , 'Formosa'               , 'Yes', 'No'  ),
	array( 'Luzon Strait'          , 'Middle Pacific'        , 'Yes', 'No'  ),
	array( 'Luzon Strait'          , 'Manila'                , 'Yes', 'No'  ),
	array( 'Luzon Strait'          , 'Cebu'                  , 'Yes', 'No'  ),
	array( 'Luzon Strait'          , 'Sulu Sea'              , 'Yes', 'No'  ),
	array( 'Okhotsk Sea'           , 'Vladivostok'           , 'Yes', 'No'  ),
	array( 'Okhotsk Sea'           , 'Sakhalin'              , 'Yes', 'No'  ),
	array( 'Okhotsk Sea'           , 'Sea of Japan'          , 'Yes', 'No'  ),
	array( 'Okhotsk Sea'           , 'Otaru'                 , 'Yes', 'No'  ),
	array( 'Okhotsk Sea'           , 'Akita'                 , 'Yes', 'No'  ),
	array( 'Okhotsk Sea'           , 'Tokyo'                 , 'Yes', 'No'  ),
	array( 'Okhotsk Sea'           , 'Upper Pacific'         , 'Yes', 'No'  ),
	array( 'Sea of Japan'          , 'Vladivostok'           , 'Yes', 'No'  ),
	array( 'Sea of Japan'          , 'Otaru'                 , 'Yes', 'No'  ),
	array( 'Sea of Japan'          , 'Akita'                 , 'Yes', 'No'  ),
	array( 'Sea of Japan'          , 'Kyoto'                 , 'Yes', 'No'  ),
	array( 'Sea of Japan'          , 'Yellow Sea'            , 'Yes', 'No'  ),
	array( 'Sea of Japan'          , 'Fusan'                 , 'Yes', 'No'  ),
	array( 'Yellow Sea'            , 'Fusan'                 , 'Yes', 'No'  ),
	array( 'Yellow Sea'            , 'Kyoto'                 , 'Yes', 'No'  ),
	array( 'Yellow Sea'            , 'Upper Pacific'         , 'Yes', 'No'  ),
	array( 'Yellow Sea'            , 'Kyushu'                , 'Yes', 'No'  ),
	array( 'Yellow Sea'            , 'East China Sea'        , 'Yes', 'No'  ),
	array( 'Yellow Sea'            , 'Shanghai'              , 'Yes', 'No'  ),
	array( 'Yellow Sea'            , 'Manchuria'             , 'Yes', 'No'  ),
	array( 'Yellow Sea'            , 'Port Arthur'           , 'Yes', 'No'  ),
	array( 'Upper Pacific'         , 'Tokyo'                 , 'Yes', 'No'  ),
	array( 'Upper Pacific'         , 'Kyoto'                 , 'Yes', 'No'  ),
	array( 'Upper Pacific'         , 'Kyushu'                , 'Yes', 'No'  ),
	array( 'Upper Pacific'         , 'East China Sea'        , 'Yes', 'No'  ),
	array( 'Upper Pacific'         , 'Formosa'               , 'Yes', 'No'  ),
	array( 'Upper Pacific'         , 'Middle Pacific'        , 'Yes', 'No'  ),
	array( 'East China Sea'        , 'Shanghai'              , 'Yes', 'No'  ),
	array( 'East China Sea'        , 'Nanchung'              , 'Yes', 'No'  ),
	array( 'East China Sea'        , 'Formosa'               , 'Yes', 'No'  ),
	array( 'East China Sea'        , 'Kyushu'                , 'Yes', 'No'  ),
	array( 'Middle Pacific'        , 'Manila'                , 'Yes', 'No'  ),
	array( 'Middle Pacific'        , 'Cebu'                  , 'Yes', 'No'  ),
	array( 'Middle Pacific'        , 'Lower Pacific'         , 'Yes', 'No'  ),
	array( 'Middle Pacific'        , 'Formosa'               , 'Yes', 'No'  ),
	array( 'Middle Pacific'        , 'Davao'                 , 'Yes', 'No'  ),
	array( 'Lower Pacific'         , 'Cebu'                  , 'Yes', 'No'  ),
	array( 'Lower Pacific'         , 'Davao'                 , 'Yes', 'No'  ),
	array( 'Lower Pacific'         , 'Celebes Sea'           , 'Yes', 'No'  ),
	array( 'Lower Pacific'         , 'New Guinea'            , 'Yes', 'No'  ),
	array( 'Sulu Sea'              , 'Cebu'                  , 'Yes', 'No'  ),
	array( 'Sulu Sea'              , 'Davao'                 , 'Yes', 'No'  ),
	array( 'Sulu Sea'              , 'Celebes Sea'           , 'Yes', 'No'  ),
	array( 'Sulu Sea'              , 'Sarawak'               , 'Yes', 'No'  ),
	array( 'Celebes Sea'           , 'Sarawak'               , 'Yes', 'No'  ),
	array( 'Celebes Sea'           , 'Borneo'                , 'Yes', 'No'  ),
	array( 'Celebes Sea'           , 'Celebes'               , 'Yes', 'No'  ),
	array( 'Celebes Sea'           , 'Timor Sea'             , 'Yes', 'No'  ),
	array( 'Celebes Sea'           , 'New Guinea'            , 'Yes', 'No'  ),
	array( 'Celebes Sea'           , 'Davao'                 , 'Yes', 'No'  ),
	array( 'Timor Sea'             , 'Java'                  , 'Yes', 'No'  ),
	array( 'Timor Sea'             , 'Celebes'               , 'Yes', 'No'  ),
	array( 'Timor Sea'             , 'New Guinea'            , 'Yes', 'No'  ),
	array( 'Moscow'                , 'Odessa'                , 'No' , 'Yes' ),
	array( 'Moscow'                , 'Baku'                  , 'No' , 'Yes' ),
	array( 'Moscow'                , 'Bokhara'               , 'No' , 'Yes' ),
	array( 'Moscow'                , 'Orenburg'              , 'No' , 'Yes' ),
	array( 'Moscow'                , 'Perm'                  , 'No' , 'Yes' ),
	array( 'Akmolinsk'             , 'Orenburg'              , 'No' , 'Yes' ),
	array( 'Akmolinsk'             , 'Omsk'                  , 'No' , 'Yes' ),
	array( 'Akmolinsk'             , 'Krasnoyarsk'           , 'No' , 'Yes' ),
	array( 'Akmolinsk'             , 'Semipalatinsk'         , 'No' , 'Yes' ),
	array( 'Akmolinsk'             , 'Kirghiz'               , 'No' , 'Yes' ),
	array( 'Akmolinsk'             , 'Tashkent'              , 'No' , 'Yes' ),
	array( 'Orenburg'              , 'Perm'                  , 'No' , 'Yes' ),
	array( 'Orenburg'              , 'Omsk'                  , 'No' , 'Yes' ),
	array( 'Orenburg'              , 'Tashkent'              , 'No' , 'Yes' ),
	array( 'Orenburg'              , 'Bokhara'               , 'No' , 'Yes' ),
	array( 'Perm'                  , 'Omsk'                  , 'No' , 'Yes' ),
	array( 'Omsk'                  , 'Krasnoyarsk'           , 'No' , 'Yes' ),
	array( 'Krasnoyarsk'           , 'Semipalatinsk'         , 'No' , 'Yes' ),
	array( 'Krasnoyarsk'           , 'Urumchi'               , 'No' , 'Yes' ),
	array( 'Krasnoyarsk'           , 'Mongolia'              , 'No' , 'Yes' ),
	array( 'Krasnoyarsk'           , 'Irkutsk'               , 'No' , 'Yes' ),
	array( 'Mongolia'              , 'Irkutsk'               , 'No' , 'Yes' ),
	array( 'Mongolia'              , 'Manchuria'             , 'No' , 'Yes' ),
	array( 'Mongolia'              , 'Peking'                , 'No' , 'Yes' ),
	array( 'Mongolia'              , 'Langchow'              , 'No' , 'Yes' ),
	array( 'Mongolia'              , 'Sinkiang'              , 'No' , 'Yes' ),
	array( 'Mongolia'              , 'Urumchi'               , 'No' , 'Yes' ),
	array( 'Irkutsk'               , 'Vladivostok'           , 'No' , 'Yes' ),
	array( 'Irkutsk'               , 'Manchuria'             , 'No' , 'Yes' ),
	array( 'Manchuria'             , 'Vladivostok'           , 'No' , 'Yes' ),
	array( 'Manchuria'             , 'Peking'                , 'No' , 'Yes' ),
	array( 'Peking'                , 'Shanghai'              , 'No' , 'Yes' ),
	array( 'Peking'                , 'Langchow'              , 'No' , 'Yes' ),
	array( 'Bokhara'               , 'Tashkent'              , 'No' , 'Yes' ),
	array( 'Bokhara'               , 'Afghanistan'           , 'No' , 'Yes' ),
	array( 'Bokhara'               , 'Persia'                , 'No' , 'Yes' ),
	array( 'Baku'                  , 'Tabriz'                , 'No' , 'Yes' ),
	array( 'Armenia'               , 'Syria'                 , 'No' , 'Yes' ),
	array( 'Armenia'               , 'Baghdad'               , 'No' , 'Yes' ),
	array( 'Armenia'               , 'Tabriz'                , 'No' , 'Yes' ),
	array( 'Syria'                 , 'Baghdad'               , 'No' , 'Yes' ),
	array( 'Syria'                 , 'Mecca'                 , 'No' , 'Yes' ),
	array( 'Abysinnia'             , 'Sudan'                 , 'No' , 'Yes' ),
	array( 'Abysinnia'             , 'Eritrea'               , 'No' , 'Yes' ),
	array( 'Abysinnia'             , 'Somalia'               , 'No' , 'Yes' ),
	array( 'Tabriz'                , 'Baghdad'               , 'No' , 'Yes' ),
	array( 'Tabriz'                , 'Shiraz'                , 'No' , 'Yes' ),
	array( 'Tabriz'                , 'Persia'                , 'No' , 'Yes' ),
	array( 'Persia'                , 'Afghanistan'           , 'No' , 'Yes' ),
	array( 'Afghanistan'           , 'Karachi'               , 'No' , 'Yes' ),
	array( 'Afghanistan'           , 'Punjab'                , 'No' , 'Yes' ),
	array( 'Afghanistan'           , 'Kashmir'               , 'No' , 'Yes' ),
	array( 'Afghanistan'           , 'Kashgar'               , 'No' , 'Yes' ),
	array( 'Afghanistan'           , 'Tashkent'              , 'No' , 'Yes' ),
	array( 'Kirghiz'               , 'Tashkent'              , 'No' , 'Yes' ),
	array( 'Kirghiz'               , 'Kashgar'               , 'No' , 'Yes' ),
	array( 'Kirghiz'               , 'Urumchi'               , 'No' , 'Yes' ),
	array( 'Kirghiz'               , 'Semipalatinsk'         , 'No' , 'Yes' ),
	array( 'Semipalatinsk'         , 'Urumchi'               , 'No' , 'Yes' ),
	array( 'Kashgar'               , 'Tashkent'              , 'No' , 'Yes' ),
	array( 'Kashgar'               , 'Urumchi'               , 'No' , 'Yes' ),
	array( 'Kashgar'               , 'Sinkiang'              , 'No' , 'Yes' ),
	array( 'Kashgar'               , 'Tibet'                 , 'No' , 'Yes' ),
	array( 'Kashgar'               , 'Kashmir'               , 'No' , 'Yes' ),
	array( 'Sinkiang'              , 'Urumchi'               , 'No' , 'Yes' ),
	array( 'Sinkiang'              , 'Langchow'              , 'No' , 'Yes' ),
	array( 'Sinkiang'              , 'Chungking'             , 'No' , 'Yes' ),
	array( 'Sinkiang'              , 'Yunnan'                , 'No' , 'Yes' ),
	array( 'Sinkiang'              , 'Assam'                 , 'No' , 'Yes' ),
	array( 'Sinkiang'              , 'Tibet'                 , 'No' , 'Yes' ),
	array( 'Punjab'                , 'Kashmir'               , 'No' , 'Yes' ),
	array( 'Punjab'                , 'Tibet'                 , 'No' , 'Yes' ),
	array( 'Punjab'                , 'Nepal'                 , 'No' , 'Yes' ),
	array( 'Punjab'                , 'Delhi'                 , 'No' , 'Yes' ),
	array( 'Punjab'                , 'Rajputana'             , 'No' , 'Yes' ),
	array( 'Punjab'                , 'Karachi'               , 'No' , 'Yes' ),
	array( 'Delhi'                 , 'Nepal'                 , 'No' , 'Yes' ),
	array( 'Delhi'                 , 'Lucknow'               , 'No' , 'Yes' ),
	array( 'Delhi'                 , 'Nagpur'                , 'No' , 'Yes' ),
	array( 'Delhi'                 , 'Rajputana'             , 'No' , 'Yes' ),
	array( 'Nagpur'                , 'Rajputana'             , 'No' , 'Yes' ),
	array( 'Nagpur'                , 'Bombay'                , 'No' , 'Yes' ),
	array( 'Nagpur'                , 'Hyderabad'             , 'No' , 'Yes' ),
	array( 'Nagpur'                , 'Lucknow'               , 'No' , 'Yes' ),
	array( 'Hyderabad'             , 'Bombay'                , 'No' , 'Yes' ),
	array( 'Hyderabad'             , 'Mysore'                , 'No' , 'Yes' ),
	array( 'Hyderabad'             , 'Lucknow'               , 'No' , 'Yes' ),
	array( 'Lucknow'               , 'Nepal'                 , 'No' , 'Yes' ),
	array( 'Lucknow'               , 'Bengal'                , 'No' , 'Yes' ),
	array( 'Bengal'                , 'Nepal'                 , 'No' , 'Yes' ),
	array( 'Bengal'                , 'Tibet'                 , 'No' , 'Yes' ),
	array( 'Bengal'                , 'Assam'                 , 'No' , 'Yes' ),
	array( 'Assam'                 , 'Tibet'                 , 'No' , 'Yes' ),
	array( 'Kashmir'               , 'Tibet'                 , 'No' , 'Yes' ),
	array( 'Assam'                 , 'Upper Burma'           , 'No' , 'Yes' ),
	array( 'Assam'                 , 'Yunnan'                , 'No' , 'Yes' ),
	array( 'Yunnan'                , 'Upper Burma'           , 'No' , 'Yes' ),
	array( 'Yunnan'                , 'Mandalay'              , 'No' , 'Yes' ),
	array( 'Yunnan'                , 'Canton'                , 'No' , 'Yes' ),
	array( 'Yunnan'                , 'Chungking'             , 'No' , 'Yes' ),
	array( 'Chungking'             , 'Langchow'              , 'No' , 'Yes' ),
	array( 'Chungking'             , 'Nanchung'              , 'No' , 'Yes' ),
	array( 'Chungking'             , 'Canton'                , 'No' , 'Yes' ),
	array( 'Langchow'              , 'Shanghai'              , 'No' , 'Yes' ),
	array( 'Langchow'              , 'Nanchung'              , 'No' , 'Yes' ),
	array( 'Mandalay'              , 'Upper Burma'           , 'No' , 'Yes' ),
	array( 'Mandalay'              , 'Rangoon'               , 'No' , 'Yes' ),
	array( 'Mandalay'              , 'North Siam'            , 'No' , 'Yes' ),
	array( 'Mandalay'              , 'Tongking'              , 'No' , 'Yes' ),
	array( 'Mandalay'              , 'Canton'                , 'No' , 'Yes' ),
	array( 'North Siam'            , 'Rangoon'               , 'No' , 'Yes' ),
	array( 'North Siam'            , 'Cambodia'              , 'No' , 'Yes' ),
	array( 'North Siam'            , 'Tongking'              , 'No' , 'Yes' ),
	array( 'Cambodia'              , 'Annam'                 , 'No' , 'Yes' ),
	array( 'Cambodia'              , 'Tongking'              , 'No' , 'Yes' ),
	array( 'Arabia'                , 'Syria'                 , 'No' , 'Yes' ),
	array( 'Arabia'                , 'Mecca'                 , 'No' , 'Yes' ),
	array( 'Seoul'                 , 'Manchuria'             , 'No' , 'Yes' ),
	array( 'Bangkok'               , 'North Siam'            , 'No' , 'Yes' ),
	array( 'Arabia'                , 'Baghdad'               , 'No' , 'Yes' ),
	array( 'Arabia'                , 'Oman'                  , 'No' , 'Yes' ),
	array( 'Arabia'                , 'Aden'                  , 'No' , 'Yes' ),
	array( 'Seoul'                 , 'Port Arthur'           , 'No' , 'Yes' ),
	array( 'Seoul'                 , 'Vladivostok'           , 'No' , 'Yes' ),
	array( 'Seoul'                 , 'Fusan'                 , 'No' , 'Yes' ),
	array( 'Bangkok'               , 'Rangoon'               , 'No' , 'Yes' ),
	array( 'Bangkok'               , 'Cambodia'              , 'No' , 'Yes' ),
	array( 'Bangkok'               , 'Malaya'                , 'No' , 'Yes' ),
	array( 'Arabia (North Coast)'  , 'Baghdad'               , 'Yes', 'No'  ),
	array( 'Arabia (North Coast)'  , 'Persian Gulf'          , 'Yes', 'No'  ),
	array( 'Arabia (North Coast)'  , 'Oman'                  , 'Yes', 'No'  ),
	array( 'Arabia (South Coast)'  , 'Aden'                  , 'Yes', 'No'  ),
	array( 'Arabia (South Coast)'  , 'Oman'                  , 'Yes', 'No'  ),
	array( 'Arabia (South Coast)'  , 'Arabian Sea'           , 'Yes', 'No'  ),
	array( 'Arabia (South Coast)'  , 'Gulf of Aden'          , 'Yes', 'No'  ),
	array( 'Seoul (West Coast)'    , 'Port Arthur'           , 'Yes', 'No'  ),
	array( 'Seoul (West Coast)'    , 'Yellow Sea'            , 'Yes', 'No'  ),
	array( 'Seoul (West Coast)'    , 'Fusan'                 , 'Yes', 'No'  ),
	array( 'Seoul (East Coast)'    , 'Vladivostok'           , 'Yes', 'No'  ),
	array( 'Seoul (East Coast)'    , 'Sea of Japan'          , 'Yes', 'No'  ),
	array( 'Seoul (East Coast)'    , 'Fusan'                 , 'Yes', 'No'  ),
	array( 'Bangkok (West Coast)'  , 'Rangoon'               , 'Yes', 'No'  ),
	array( 'Bangkok (West Coast)'  , 'Andaman Sea'           , 'Yes', 'No'  ),
	array( 'Bangkok (West Coast)'  , 'Malaya'                , 'Yes', 'No'  ),
	array( 'Bangkok (East Coast)'  , 'Cambodia'              , 'Yes', 'No'  ),
	array( 'Bangkok (East Coast)'  , 'Gulf of Siam'          , 'Yes', 'No'  ),
	array( 'Bangkok (East Coast)'  , 'Malaya'                , 'Yes', 'No'  )
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
	InstallTerritory::$Territories[$from]->addBorder(InstallTerritory::$Territories[$to]  ,$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);

?>