<?php
// This is file installs the map data for the Colonial variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Sakhalin', 'Coast', 'Yes', 0, 1320, 95, 518, 38),
	array('Tashkent', 'Land', 'Yes', 0, 540, 240, 229, 96),
	array('Bengal', 'Coast', 'Yes', 0, 850, 525, 349, 212),
	array('Kashmir', 'Land', 'Yes', 0, 660, 367, 263, 148),
	array('Ceylon', 'Coast', 'Yes', 0, 777, 773, 301, 313),
	array('Mongolia', 'Land', 'Yes', 0, 930, 200, 372, 79),
	array('Kashgar', 'Land', 'Yes', 0, 690, 315, 274, 120),
	array('Chungking', 'Land', 'Yes', 0, 1020, 415, 431, 190),
	array('Hong Kong', 'Coast', 'Yes', 1, 1140, 570, 454, 228),
	array('Singapore', 'Coast', 'Yes', 1, 1088, 838, 435, 337),
	array('Aden', 'Coast', 'Yes', 1, 300, 658, 120, 259),
	array('Delhi', 'Land', 'Yes', 1, 705, 490, 278, 190),
	array('Bombay', 'Coast', 'Yes', 1, 670, 585, 275, 241),
	array('Madras', 'Coast', 'Yes', 1, 734, 715, 295, 281),
	array('Punjab', 'Land', 'No', 1, 655, 426, 262, 171),
	array('Rajputana', 'Coast', 'No', 1, 638, 517, 255, 210),
	array('Lucknow', 'Land', 'No', 1, 778, 510, 311, 204),
	array('Nagpur', 'Land', 'No', 1, 740, 563, 300, 223),
	array('Mysore', 'Coast', 'No', 1, 683, 650, 273, 261),
	array('Hyderabad', 'Coast', 'No', 1, 755, 615, 299, 255),
	array('Constantinople', 'Coast', 'Yes', 7, 38, 244, 5, 105),
	array('Angora', 'Coast', 'Yes', 7, 165, 308, 35, 132),
	array('Baghdad', 'Coast', 'Yes', 7, 260, 408, 110, 160),
	array('Armenia', 'Coast', 'No', 7, 235, 318, 91, 120),
	array('Syria', 'Coast', 'No', 7, 190, 398, 75, 150),
	array('Mecca', 'Coast', 'No', 7, 205, 498, 70, 180),
	array('Odessa', 'Coast', 'Yes', 6, 140, 158, 55, 75),
	array('Moscow', 'Land', 'Yes', 6, 275, 148, 110, 40),
	array('Omsk', 'Land', 'Yes', 6, 620, 25, 259, 12),
	array('Vladivostok', 'Coast', 'Yes', 6, 1200, 110, 515, 65),
	array('Port Arthur', 'Coast', 'Yes', 6, 1200, 255, 475, 106),
	array('Baku', 'Coast', 'No', 6, 250, 247, 90, 90),
	array('Bokhara', 'Land', 'No', 6, 440, 297, 175, 112),
	array('Orenburg', 'Land', 'No', 6, 475, 140, 190, 60),
	array('Perm', 'Land', 'No', 6, 440, 27, 180, 15),
	array('Akmolinsk', 'Land', 'No', 6, 595, 145, 245, 53),
	array('Kirghiz', 'Land', 'No', 6, 640, 240, 255, 85),
	array('Semipalatinsk', 'Land', 'No', 6, 700, 155, 280, 63),
	array('Krasnoyarsk', 'Land', 'No', 6, 810, 107, 315, 50),
	array('Irkutsk', 'Land', 'No', 6, 1030, 48, 390, 48),
	array('Otaru', 'Coast', 'Yes', 5, 1380, 197, 545, 80),
	array('Akita', 'Coast', 'No', 5, 1407, 270, 559, 115),
	array('Tokyo', 'Coast', 'Yes', 5, 1413, 315, 563, 133),
	array('Kyoto', 'Coast', 'Yes', 5, 1370, 327, 540, 135),
	array('Kyushu', 'Coast', 'Yes', 5, 1329, 388, 530, 155),
	array('Manchuria', 'Coast', 'Yes', 2, 1180, 197, 445, 62),
	array('Peking', 'Land', 'Yes', 2, 1070, 245, 427, 93),
	array('Sinkiang', 'Land', 'Yes', 2, 860, 370, 335, 137),
	array('Shanghai', 'Coast', 'Yes', 2, 1130, 348, 450, 140),
	array('Canton', 'Coast', 'Yes', 2, 1130, 534, 450, 211),
	array('Urumchi', 'Land', 'No', 2, 740, 243, 296, 97),
	array('Langchow', 'Land', 'No', 2, 973, 300, 389, 122),
	array('Nanchung', 'Coast', 'No', 2, 1165, 470, 466, 189),
	array('Yunnan', 'Land', 'No', 2, 990, 480, 396, 197),
	array('Tibet', 'Land', 'No', 2, 745, 395, 328, 173),
	array('Tongking', 'Coast', 'Yes', 3, 1060, 555, 435, 223),
	array('Cambodia', 'Coast', 'No', 3, 1080, 653, 430, 268),
	array('Annam', 'Coast', 'Yes', 3, 1130, 638, 455, 257),
	array('Cochin', 'Coast', 'Yes', 3, 1125, 685, 445, 279),
	array('Sumatra', 'Coast', 'Yes', 4, 1055, 890, 403, 330),
	array('Java', 'Coast', 'Yes', 4, 1155, 955, 441, 379),
	array('Borneo', 'Coast', 'Yes', 4, 1217, 855, 490, 335),
	array('Celebes', 'Coast', 'No', 4, 1295, 868, 518, 347),
	array('Rumania', 'Coast', 'Yes', 0, 40, 188, 17, 80),
	array('Tabriz', 'Land', 'Yes', 0, 300, 345, 117, 142),
	array('Egypt', 'Coast', 'Yes', 0, 75, 523, 30, 205),
	array('Sudan', 'Coast', 'Yes', 0, 75, 647, 30, 260),
	array('Abysinnia', 'Land', 'No', 0, 190, 740, 80, 300),
	array('Somalia', 'Coast', 'No', 0, 290, 807, 123, 315),
	array('Eritrea', 'Coast', 'No', 0, 200, 650, 92, 275),
	array('Arabia', 'Coast', 'No', 0, 325, 550, 120, 207),
	array('Arabia (North Coast)', 'Coast', 'No', 0, 348, 500, 128, 194),
	array('Arabia (South Coast)', 'Coast', 'No', 0, 375, 645, 150, 255),
	array('Oman', 'Coast', 'No', 0, 450, 565, 180, 225),
	array('Shiraz', 'Coast', 'Yes', 0, 360, 422, 135, 170),
	array('Persia', 'Coast', 'Yes', 0, 450, 410, 175, 160),
	array('Seoul', 'Coast', 'Yes', 0, 1233, 263, 493, 97),
	array('Seoul (East Coast)', 'Coast', 'Yes', 0, 1250, 250, 500, 100),
	array('Seoul (West Coast)', 'Coast', 'Yes', 0, 1217, 288, 490, 115),
	array('Fusan', 'Coast', 'Yes', 0, 1265, 315, 500, 130),
	array('Afghanistan', 'Land', 'No', 0, 540, 377, 218, 154),
	array('Karachi', 'Coast', 'Yes', 0, 525, 490, 210, 200),
	array('Nepal', 'Land', 'No', 0, 758, 466, 318, 191),
	array('Formosa', 'Coast', 'Yes', 0, 1297, 470, 519, 188),
	array('Manila', 'Coast', 'Yes', 0, 1290, 561, 512, 223),
	array('Cebu', 'Coast', 'Yes', 0, 1321, 655, 539, 259),
	array('Davao', 'Coast', 'Yes', 0, 1350, 710, 537, 280),
	array('Assam', 'Land', 'Yes', 0, 915, 478, 356, 194),
	array('Upper Burma', 'Coast', 'Yes', 0, 920, 570, 367, 223),
	array('Mandalay', 'Land', 'Yes', 0, 975, 557, 397, 230),
	array('Rangoon', 'Coast', 'Yes', 0, 945, 620, 384, 250),
	array('North Siam', 'Land', 'No', 0, 1013, 610, 405, 245),
	array('Bangkok', 'Coast', 'Yes', 0, 1025, 660, 405, 273),
	array('Bangkok (East Coast)', 'Coast', 'Yes', 0, 1025, 710, 410, 270),
	array('Bangkok (West Coast)', 'Coast', 'Yes', 0, 1000, 735, 400, 290),
	array('Malaya', 'Coast', 'Yes', 0, 1040, 780, 415, 308),
	array('Sarawak', 'Coast', 'Yes', 0, 1188, 802, 474, 320),
	array('New Guinea', 'Coast', 'Yes', 0, 1395, 900, 554, 363),
	array('Red Sea', 'Sea', 'No', 0, 195, 580, 79, 227),
	array('Black Sea', 'Sea', 'No', 0, 100, 250, 40, 100),
	array('Mediterranean Sea', 'Sea', 'No', 0, 65, 377, 15, 148),
	array('Persian Gulf', 'Sea', 'No', 0, 442, 515, 179, 205),
	array('Okhotsk Sea', 'Sea', 'No', 0, 1400, 70, 565, 40),
	array('Sea of Japan', 'Sea', 'No', 0, 1310, 258, 526, 97),
	array('Yellow Sea', 'Sea', 'No', 0, 1220, 350, 484, 130),
	array('East China Sea', 'Sea', 'No', 0, 1265, 418, 508, 165),
	array('Upper Pacific', 'Sea', 'No', 0, 1413, 420, 565, 162),
	array('South China Sea', 'Sea', 'No', 0, 1200, 550, 491, 205),
	array('Luzon Strait', 'Sea', 'No', 0, 1230, 625, 491, 240),
	array('Middle Pacific', 'Sea', 'No', 0, 1443, 600, 577, 241),
	array('Lower Pacific', 'Sea', 'No', 0, 1448, 755, 579, 304),
	array('Sulu Sea', 'Sea', 'No', 0, 1235, 705, 489, 275),
	array('Celebes Sea', 'Sea', 'No', 0, 1300, 782, 509, 322),
	array('Arabian Sea', 'Sea', 'No', 0, 520, 622, 220, 250),
	array('Gulf of Aden', 'Sea', 'No', 0, 388, 860, 155, 345),
	array('West Indian Ocean', 'Sea', 'No', 0, 618, 866, 247, 347),
	array('Gulf of Manaar', 'Sea', 'No', 0, 805, 710, 322, 284),
	array('Bay of Bengal', 'Sea', 'No', 0, 868, 628, 347, 243),
	array('Southeast Indian Ocean', 'Sea', 'No', 0, 913, 940, 365, 377),
	array('East Indian Ocean', 'Sea', 'No', 0, 875, 830, 350, 333),
	array('Andaman Sea', 'Sea', 'No', 0, 948, 710, 379, 277),
	array('Gulf of Siam', 'Sea', 'No', 0, 1060, 720, 422, 289),
	array('Sunda Sea', 'Sea', 'No', 0, 1160, 753, 464, 297),
	array('Java Sea', 'Sea', 'No', 0, 1125, 890, 459, 366),
	array('Timor Sea', 'Sea', 'No', 0, 1330, 965, 531, 383)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Sakhalin','Otaru','Yes','Yes'),
	array('Sakhalin','Okhotsk Sea','Yes','No'),
	array('Tashkent','Kashgar','No','Yes'),
	array('Tashkent','Bokhara','No','Yes'),
	array('Tashkent','Orenburg','No','Yes'),
	array('Tashkent','Akmolinsk','No','Yes'),
	array('Tashkent','Kirghiz','No','Yes'),
	array('Tashkent','Afghanistan','No','Yes'),
	array('Bengal','Lucknow','No','Yes'),
	array('Bengal','Hyderabad','Yes','Yes'),
	array('Bengal','Tibet','No','Yes'),
	array('Bengal','Nepal','No','Yes'),
	array('Bengal','Assam','No','Yes'),
	array('Bengal','Upper Burma','Yes','Yes'),
	array('Bengal','Bay of Bengal','Yes','No'),
	array('Kashmir','Kashgar','No','Yes'),
	array('Kashmir','Punjab','No','Yes'),
	array('Kashmir','Tibet','No','Yes'),
	array('Kashmir','Afghanistan','No','Yes'),
	array('Ceylon','West Indian Ocean','Yes','No'),
	array('Ceylon','Gulf of Manaar','Yes','No'),
	array('Ceylon','East Indian Ocean','Yes','No'),
	array('Mongolia','Krasnoyarsk','No','Yes'),
	array('Mongolia','Irkutsk','No','Yes'),
	array('Mongolia','Manchuria','No','Yes'),
	array('Mongolia','Peking','No','Yes'),
	array('Mongolia','Sinkiang','No','Yes'),
	array('Mongolia','Urumchi','No','Yes'),
	array('Mongolia','Langchow','No','Yes'),
	array('Kashgar','Kirghiz','No','Yes'),
	array('Kashgar','Sinkiang','No','Yes'),
	array('Kashgar','Urumchi','No','Yes'),
	array('Kashgar','Tibet','No','Yes'),
	array('Kashgar','Afghanistan','No','Yes'),
	array('Chungking','Sinkiang','No','Yes'),
	array('Chungking','Canton','No','Yes'),
	array('Chungking','Langchow','No','Yes'),
	array('Chungking','Nanchung','No','Yes'),
	array('Chungking','Yunnan','No','Yes'),
	array('Hong Kong','Canton','Yes','Yes'),
	array('Hong Kong','South China Sea','Yes','No'),
	array('Singapore','Malaya','Yes','Yes'),
	array('Singapore','Java Sea','Yes','No'),
	array('Aden','Mecca','Yes','Yes'),
	array('Aden','Arabia','No','Yes'),
	array('Aden','Arabia (South Coast)','Yes','No'),
	array('Aden','Red Sea','Yes','No'),
	array('Aden','Gulf of Aden','Yes','No'),
	array('Delhi','Punjab','No','Yes'),
	array('Delhi','Rajputana','No','Yes'),
	array('Delhi','Lucknow','No','Yes'),
	array('Delhi','Nagpur','No','Yes'),
	array('Delhi','Nepal','No','Yes'),
	array('Bombay','Rajputana','Yes','Yes'),
	array('Bombay','Nagpur','No','Yes'),
	array('Bombay','Mysore','Yes','Yes'),
	array('Bombay','Hyderabad','No','Yes'),
	array('Bombay','Arabian Sea','Yes','No'),
	array('Madras','Mysore','Yes','Yes'),
	array('Madras','Hyderabad','Yes','Yes'),
	array('Madras','West Indian Ocean','Yes','No'),
	array('Madras','Gulf of Manaar','Yes','No'),
	array('Punjab','Rajputana','No','Yes'),
	array('Punjab','Tibet','No','Yes'),
	array('Punjab','Afghanistan','No','Yes'),
	array('Punjab','Karachi','No','Yes'),
	array('Punjab','Nepal','No','Yes'),
	array('Rajputana','Nagpur','No','Yes'),
	array('Rajputana','Karachi','Yes','Yes'),
	array('Rajputana','Arabian Sea','Yes','No'),
	array('Lucknow','Nagpur','No','Yes'),
	array('Lucknow','Hyderabad','No','Yes'),
	array('Lucknow','Nepal','No','Yes'),
	array('Nagpur','Hyderabad','No','Yes'),
	array('Mysore','Hyderabad','No','Yes'),
	array('Mysore','Arabian Sea','Yes','No'),
	array('Mysore','West Indian Ocean','Yes','No'),
	array('Hyderabad','Gulf of Manaar','Yes','No'),
	array('Hyderabad','Bay of Bengal','Yes','No'),
	array('Constantinople','Angora','Yes','Yes'),
	array('Constantinople','Rumania','Yes','Yes'),
	array('Constantinople','Black Sea','Yes','No'),
	array('Constantinople','Mediterranean Sea','Yes','No'),
	array('Angora','Armenia','Yes','Yes'),
	array('Angora','Syria','Yes','Yes'),
	array('Angora','Black Sea','Yes','No'),
	array('Angora','Mediterranean Sea','Yes','No'),
	array('Baghdad','Armenia','No','Yes'),
	array('Baghdad','Syria','No','Yes'),
	array('Baghdad','Tabriz','No','Yes'),
	array('Baghdad','Arabia','No','Yes'),
	array('Baghdad','Arabia (North Coast)','Yes','No'),
	array('Baghdad','Shiraz','Yes','Yes'),
	array('Baghdad','Persian Gulf','Yes','No'),
	array('Armenia','Syria','No','Yes'),
	array('Armenia','Baku','Yes','Yes'),
	array('Armenia','Tabriz','No','Yes'),
	array('Armenia','Black Sea','Yes','No'),
	array('Syria','Mecca','No','Yes'),
	array('Syria','Egypt','Yes','Yes'),
	array('Syria','Arabia','No','Yes'),
	array('Syria','Mediterranean Sea','Yes','No'),
	array('Mecca','Egypt','Yes','Yes'),
	array('Mecca','Arabia','No','Yes'),
	array('Mecca','Red Sea','Yes','No'),
	array('Odessa','Moscow','No','Yes'),
	array('Odessa','Baku','Yes','Yes'),
	array('Odessa','Rumania','Yes','Yes'),
	array('Odessa','Black Sea','Yes','No'),
	array('Moscow','Baku','No','Yes'),
	array('Moscow','Bokhara','No','Yes'),
	array('Moscow','Orenburg','No','Yes'),
	array('Moscow','Perm','No','Yes'),
	array('Omsk','Orenburg','No','Yes'),
	array('Omsk','Perm','No','Yes'),
	array('Omsk','Akmolinsk','No','Yes'),
	array('Omsk','Krasnoyarsk','No','Yes'),
	array('Vladivostok','Irkutsk','No','Yes'),
	array('Vladivostok','Manchuria','No','Yes'),
	array('Vladivostok','Seoul','No','Yes'),
	array('Vladivostok','Seoul (East Coast)','Yes','No'),
	array('Vladivostok','Okhotsk Sea','Yes','No'),
	array('Vladivostok','Sea of Japan','Yes','No'),
	array('Port Arthur','Manchuria','Yes','Yes'),
	array('Port Arthur','Seoul','No','Yes'),
	array('Port Arthur','Seoul (West Coast)','Yes','No'),
	array('Port Arthur','Yellow Sea','Yes','No'),
	array('Baku','Tabriz','No','Yes'),
	array('Baku','Black Sea','Yes','No'),
	array('Bokhara','Orenburg','No','Yes'),
	array('Bokhara','Persia','No','Yes'),
	array('Bokhara','Afghanistan','No','Yes'),
	array('Orenburg','Perm','No','Yes'),
	array('Orenburg','Akmolinsk','No','Yes'),
	array('Akmolinsk','Kirghiz','No','Yes'),
	array('Akmolinsk','Semipalatinsk','No','Yes'),
	array('Akmolinsk','Krasnoyarsk','No','Yes'),
	array('Kirghiz','Semipalatinsk','No','Yes'),
	array('Kirghiz','Urumchi','No','Yes'),
	array('Semipalatinsk','Krasnoyarsk','No','Yes'),
	array('Semipalatinsk','Urumchi','No','Yes'),
	array('Krasnoyarsk','Irkutsk','No','Yes'),
	array('Krasnoyarsk','Urumchi','No','Yes'),
	array('Irkutsk','Manchuria','No','Yes'),
	array('Otaru','Akita','Yes','Yes'),
	array('Otaru','Okhotsk Sea','Yes','No'),
	array('Otaru','Sea of Japan','Yes','No'),
	array('Akita','Tokyo','Yes','Yes'),
	array('Akita','Kyoto','Yes','Yes'),
	array('Akita','Okhotsk Sea','Yes','No'),
	array('Akita','Sea of Japan','Yes','No'),
	array('Tokyo','Kyoto','Yes','Yes'),
	array('Tokyo','Okhotsk Sea','Yes','No'),
	array('Tokyo','Upper Pacific','Yes','No'),
	array('Kyoto','Kyushu','Yes','Yes'),
	array('Kyoto','Sea of Japan','Yes','No'),
	array('Kyoto','Yellow Sea','Yes','No'),
	array('Kyoto','Upper Pacific','Yes','No'),
	array('Kyushu','Yellow Sea','Yes','No'),
	array('Kyushu','East China Sea','Yes','No'),
	array('Kyushu','Upper Pacific','Yes','No'),
	array('Manchuria','Peking','No','Yes'),
	array('Manchuria','Shanghai','Yes','Yes'),
	array('Manchuria','Seoul','No','Yes'),
	array('Manchuria','Yellow Sea','Yes','No'),
	array('Peking','Shanghai','No','Yes'),
	array('Peking','Langchow','No','Yes'),
	array('Sinkiang','Urumchi','No','Yes'),
	array('Sinkiang','Langchow','No','Yes'),
	array('Sinkiang','Yunnan','No','Yes'),
	array('Sinkiang','Tibet','No','Yes'),
	array('Sinkiang','Assam','No','Yes'),
	array('Shanghai','Langchow','No','Yes'),
	array('Shanghai','Nanchung','Yes','Yes'),
	array('Shanghai','Yellow Sea','Yes','No'),
	array('Shanghai','East China Sea','Yes','No'),
	array('Canton','Nanchung','Yes','Yes'),
	array('Canton','Yunnan','No','Yes'),
	array('Canton','Tongking','Yes','Yes'),
	array('Canton','Mandalay','No','Yes'),
	array('Canton','South China Sea','Yes','No'),
	array('Langchow','Nanchung','No','Yes'),
	array('Nanchung','East China Sea','Yes','No'),
	array('Nanchung','South China Sea','Yes','No'),
	array('Yunnan','Assam','No','Yes'),
	array('Yunnan','Upper Burma','No','Yes'),
	array('Yunnan','Mandalay','No','Yes'),
	array('Tibet','Assam','No','Yes'),
	array('Tongking','Cambodia','No','Yes'),
	array('Tongking','Annam','Yes','Yes'),
	array('Tongking','Mandalay','No','Yes'),
	array('Tongking','North Siam','No','Yes'),
	array('Tongking','South China Sea','Yes','No'),
	array('Cambodia','Annam','No','Yes'),
	array('Cambodia','Cochin','Yes','Yes'),
	array('Cambodia','North Siam','No','Yes'),
	array('Cambodia','Bangkok','No','Yes'),
	array('Cambodia','Bangkok (East Coast)','Yes','No'),
	array('Cambodia','Gulf of Siam','Yes','No'),
	array('Annam','Cochin','Yes','Yes'),
	array('Annam','South China Sea','Yes','No'),
	array('Annam','Gulf of Siam','Yes','No'),
	array('Cochin','Gulf of Siam','Yes','No'),
	array('Sumatra','Southeast Indian Ocean','Yes','No'),
	array('Sumatra','East Indian Ocean','Yes','No'),
	array('Sumatra','Andaman Sea','Yes','No'),
	array('Sumatra','Java Sea','Yes','No'),
	array('Java','Southeast Indian Ocean','Yes','No'),
	array('Java','Java Sea','Yes','No'),
	array('Java','Timor Sea','Yes','No'),
	array('Borneo','Sarawak','Yes','Yes'),
	array('Borneo','Celebes Sea','Yes','No'),
	array('Borneo','Java Sea','Yes','No'),
	array('Celebes','Celebes Sea','Yes','No'),
	array('Celebes','Java Sea','Yes','No'),
	array('Celebes','Timor Sea','Yes','No'),
	array('Rumania','Black Sea','Yes','No'),
	array('Tabriz','Shiraz','No','Yes'),
	array('Tabriz','Persia','No','Yes'),
	array('Egypt','Sudan','Yes','Yes'),
	array('Egypt','Red Sea','Yes','No'),
	array('Egypt','Mediterranean Sea','Yes','No'),
	array('Sudan','Abysinnia','No','Yes'),
	array('Sudan','Eritrea','Yes','Yes'),
	array('Sudan','Red Sea','Yes','No'),
	array('Abysinnia','Somalia','No','Yes'),
	array('Abysinnia','Eritrea','No','Yes'),
	array('Somalia','Eritrea','Yes','Yes'),
	array('Somalia','Gulf of Aden','Yes','No'),
	array('Eritrea','Red Sea','Yes','No'),
	array('Eritrea','Gulf of Aden','Yes','No'),
	array('Arabia','Oman','No','Yes'),
	array('Arabia (North Coast)','Oman','Yes','No'),
	array('Arabia (North Coast)','Persian Gulf','Yes','No'),
	array('Arabia (South Coast)','Oman','Yes','No'),
	array('Arabia (South Coast)','Arabian Sea','Yes','No'),
	array('Arabia (South Coast)','Gulf of Aden','Yes','No'),
	array('Oman','Persian Gulf','Yes','No'),
	array('Oman','Arabian Sea','Yes','No'),
	array('Shiraz','Persia','Yes','Yes'),
	array('Shiraz','Persian Gulf','Yes','No'),
	array('Persia','Afghanistan','No','Yes'),
	array('Persia','Karachi','Yes','Yes'),
	array('Persia','Persian Gulf','Yes','No'),
	array('Seoul','Fusan','No','Yes'),
	array('Seoul (East Coast)','Fusan','Yes','No'),
	array('Seoul (East Coast)','Sea of Japan','Yes','No'),
	array('Seoul (West Coast)','Fusan','Yes','No'),
	array('Seoul (West Coast)','Yellow Sea','Yes','No'),
	array('Fusan','Sea of Japan','Yes','No'),
	array('Fusan','Yellow Sea','Yes','No'),
	array('Afghanistan','Karachi','No','Yes'),
	array('Karachi','Persian Gulf','Yes','No'),
	array('Karachi','Arabian Sea','Yes','No'),
	array('Formosa','East China Sea','Yes','No'),
	array('Formosa','Upper Pacific','Yes','No'),
	array('Formosa','South China Sea','Yes','No'),
	array('Formosa','Luzon Strait','Yes','No'),
	array('Formosa','Middle Pacific','Yes','No'),
	array('Manila','Cebu','Yes','Yes'),
	array('Manila','Luzon Strait','Yes','No'),
	array('Manila','Middle Pacific','Yes','No'),
	array('Cebu','Davao','Yes','Yes'),
	array('Cebu','Luzon Strait','Yes','No'),
	array('Cebu','Middle Pacific','Yes','No'),
	array('Cebu','Lower Pacific','Yes','No'),
	array('Cebu','Sulu Sea','Yes','No'),
	array('Davao','Lower Pacific','Yes','No'),
	array('Davao','Sulu Sea','Yes','No'),
	array('Davao','Celebes Sea','Yes','No'),
	array('Assam','Upper Burma','No','Yes'),
	array('Upper Burma','Mandalay','No','Yes'),
	array('Upper Burma','Rangoon','Yes','Yes'),
	array('Upper Burma','Bay of Bengal','Yes','No'),
	array('Mandalay','Rangoon','No','Yes'),
	array('Mandalay','North Siam','No','Yes'),
	array('Rangoon','North Siam','No','Yes'),
	array('Rangoon','Bangkok','No','Yes'),
	array('Rangoon','Bangkok (West Coast)','Yes','No'),
	array('Rangoon','Bay of Bengal','Yes','No'),
	array('Rangoon','Andaman Sea','Yes','No'),
	array('North Siam','Bangkok','No','Yes'),
	array('Bangkok','Malaya','No','Yes'),
	array('Bangkok (East Coast)','Malaya','Yes','No'),
	array('Bangkok (East Coast)','Gulf of Siam','Yes','No'),
	array('Bangkok (West Coast)','Malaya','Yes','No'),
	array('Bangkok (West Coast)','Andaman Sea','Yes','No'),
	array('Malaya','Andaman Sea','Yes','No'),
	array('Malaya','Gulf of Siam','Yes','No'),
	array('Malaya','Sunda Sea','Yes','No'),
	array('Malaya','Java Sea','Yes','No'),
	array('Sarawak','Sulu Sea','Yes','No'),
	array('Sarawak','Celebes Sea','Yes','No'),
	array('Sarawak','Sunda Sea','Yes','No'),
	array('Sarawak','Java Sea','Yes','No'),
	array('New Guinea','Lower Pacific','Yes','No'),
	array('New Guinea','Celebes Sea','Yes','No'),
	array('New Guinea','Timor Sea','Yes','No'),
	array('Red Sea','Gulf of Aden','Yes','No'),
	array('Black Sea','Mediterranean Sea','Yes','No'),
	array('Persian Gulf','Arabian Sea','Yes','No'),
	array('Okhotsk Sea','Sea of Japan','Yes','No'),
	array('Okhotsk Sea','Upper Pacific','Yes','No'),
	array('Sea of Japan','Yellow Sea','Yes','No'),
	array('Yellow Sea','East China Sea','Yes','No'),
	array('Yellow Sea','Upper Pacific','Yes','No'),
	array('East China Sea','Upper Pacific','Yes','No'),
	array('East China Sea','South China Sea','Yes','No'),
	array('Upper Pacific','Middle Pacific','Yes','No'),
	array('South China Sea','Luzon Strait','Yes','No'),
	array('South China Sea','Sulu Sea','Yes','No'),
	array('South China Sea','Gulf of Siam','Yes','No'),
	array('South China Sea','Sunda Sea','Yes','No'),
	array('Luzon Strait','Middle Pacific','Yes','No'),
	array('Luzon Strait','Sulu Sea','Yes','No'),
	array('Middle Pacific','Lower Pacific','Yes','No'),
	array('Lower Pacific','Celebes Sea','Yes','No'),
	array('Sulu Sea','Celebes Sea','Yes','No'),
	array('Sulu Sea','Sunda Sea','Yes','No'),
	array('Celebes Sea','Java Sea','Yes','No'),
	array('Celebes Sea','Timor Sea','Yes','No'),
	array('Arabian Sea','Gulf of Aden','Yes','No'),
	array('Arabian Sea','West Indian Ocean','Yes','No'),
	array('Gulf of Aden','West Indian Ocean','Yes','No'),
	array('West Indian Ocean','Gulf of Manaar','Yes','No'),
	array('West Indian Ocean','Southeast Indian Ocean','Yes','No'),
	array('West Indian Ocean','East Indian Ocean','Yes','No'),
	array('Gulf of Manaar','Bay of Bengal','Yes','No'),
	array('Gulf of Manaar','East Indian Ocean','Yes','No'),
	array('Gulf of Manaar','Andaman Sea','Yes','No'),
	array('Bay of Bengal','Andaman Sea','Yes','No'),
	array('Southeast Indian Ocean','East Indian Ocean','Yes','No'),
	array('Southeast Indian Ocean','Java Sea','Yes','No'),
	array('Southeast Indian Ocean','Timor Sea','Yes','No'),
	array('East Indian Ocean','Andaman Sea','Yes','No'),
	array('Andaman Sea','Java Sea','Yes','No'),
	array('Gulf of Siam','Sunda Sea','Yes','No'),
	array('Sunda Sea','Java Sea','Yes','No'),
	array('Java Sea','Timor Sea','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
