<?php
// This is file installs the map data for the Colonial1885 variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Kiel', 'Coast', 'Yes', 3, 0, 0, 257, 176),
	array('Iceland', 'Coast', 'No', 0, 0, 0, 88, 70),
	array('Edinburgh', 'Coast', 'Yes', 1, 0, 0, 186, 124),
	array('Liverpool', 'Coast', 'Yes', 1, 0, 0, 180, 150),
	array('Yorkshire', 'Coast', 'No', 1, 0, 0, 203, 159),
	array('Ireland', 'Coast', 'No', 1, 0, 0, 161, 155),
	array('Norway', 'Coast', 'Yes', 0, 0, 0, 268, 93),
	array('Sweden', 'Coast', 'Yes', 0, 0, 0, 300, 100),
	array('Finland', 'Coast', 'No', 7, 0, 0, 365, 84),
	array('St. Petersburg', 'Coast', 'Yes', 7, 0, 0, 429, 108),
	array('St. Petersburg (South Coast)', 'Coast', 'No', 7, 0, 0, 402, 117),
	array('St. Petersburg (North Coast)', 'Coast', 'No', 7, 0, 0, 380, 48),
	array('Brest', 'Coast', 'Yes', 2, 0, 0, 188, 212),
	array('Picardy', 'Coast', 'No', 2, 0, 0, 212, 200),
	array('Paris', 'Land', 'Yes', 2, 0, 0, 218, 227),
	array('London', 'Coast', 'Yes', 1, 0, 0, 212, 173),
	array('Gascony', 'Coast', 'No', 2, 0, 0, 213, 244),
	array('Burgundy', 'Land', 'No', 2, 0, 0, 233, 226),
	array('Spain', 'Coast', 'Yes', 0, 0, 0, 192, 260),
	array('Spain (North Coast)', 'Coast', 'No', 0, 0, 0, 172, 251),
	array('Spain (South Coast)', 'Coast', 'No', 0, 0, 0, 193, 281),
	array('Portugal', 'Coast', 'Yes', 0, 0, 0, 150, 274),
	array('Wales', 'Coast', 'No', 1, 0, 0, 186, 183),
	array('Gibraltar', 'Coast', 'Yes', 1, 0, 0, 166, 295),
	array('Marseilles', 'Coast', 'Yes', 2, 0, 0, 248, 241),
	array('Livonia', 'Coast', 'No', 7, 0, 0, 351, 146),
	array('Denmark', 'Coast', 'Yes', 0, 0, 0, 267, 157),
	array('Berlin', 'Coast', 'Yes', 3, 0, 0, 291, 162),
	array('Saxony', 'Land', 'No', 3, 0, 0, 301, 186),
	array('Cologne', 'Land', 'No', 3, 0, 0, 263, 189),
	array('Holland', 'Coast', 'Yes', 6, 0, 0, 237, 173),
	array('Belgium', 'Coast', 'Yes', 0, 0, 0, 230, 184),
	array('Piedmont', 'Coast', 'No', 4, 0, 0, 274, 245),
	array('Prussia', 'Coast', 'No', 3, 0, 0, 318, 170),
	array('Ruhr', 'Land', 'No', 3, 0, 0, 269, 195),
	array('Moscow', 'Land', 'Yes', 7, 0, 0, 406, 175),
	array('Warsaw', 'Land', 'Yes', 7, 0, 0, 332, 188),
	array('Munich', 'Land', 'Yes', 3, 0, 0, 263, 210),
	array('Bohemia', 'Land', 'No', 5, 0, 0, 310, 206),
	array('Galicia', 'Land', 'No', 5, 0, 0, 338, 200),
	array('Tyrolia', 'Land', 'No', 5, 0, 0, 300, 212),
	array('Venice', 'Coast', 'Yes', 4, 0, 0, 284, 241),
	array('Rome', 'Coast', 'Yes', 4, 0, 0, 297, 266),
	array('Apulia', 'Coast', 'No', 4, 0, 0, 292, 250),
	array('Vienna', 'Land', 'Yes', 5, 0, 0, 315, 217),
	array('Budapest', 'Land', 'Yes', 5, 0, 0, 342, 230),
	array('Ukraine', 'Land', 'No', 7, 0, 0, 388, 210),
	array('Trieste', 'Coast', 'Yes', 5, 0, 0, 300, 222),
	array('Sarajevo', 'Coast', 'Yes', 5, 0, 0, 326, 249),
	array('Sevastopol', 'Coast', 'Yes', 7, 0, 0, 427, 203),
	array('Naples', 'Coast', 'Yes', 4, 0, 0, 313, 279),
	array('Sicily', 'Coast', 'Yes', 4, 0, 0, 303, 301),
	array('Arkhangelsk', 'Coast', 'No', 7, 0, 0, 519, 121),
	array('Omsk', 'Land', 'Yes', 7, 0, 0, 624, 127),
	array('Peking', 'Coast', 'Yes', 9, 0, 0, 950, 283),
	array('Tsaritsyn', 'Coast', 'No', 7, 0, 0, 484, 204),
	array('Rostov', 'Coast', 'Yes', 7, 0, 0, 473, 225),
	array('Rumania', 'Coast', 'Yes', 0, 0, 0, 379, 226),
	array('Serbia', 'Land', 'Yes', 0, 0, 0, 350, 246),
	array('Bulgaria', 'Coast', 'Yes', 0, 0, 0, 367, 250),
	array('Macedonia', 'Coast', 'No', 0, 0, 0, 360, 266),
	array('Albania', 'Coast', 'Yes', 0, 0, 0, 342, 262),
	array('Constantinople', 'Coast', 'Yes', 8, 0, 0, 404, 273),
	array('Greece', 'Coast', 'Yes', 0, 0, 0, 352, 283),
	array('Angora', 'Coast', 'Yes', 8, 0, 0, 464, 275),
	array('Smyrna', 'Coast', 'Yes', 8, 0, 0, 453, 294),
	array('Armenia', 'Coast', 'No', 8, 0, 0, 487, 276),
	array('Orenburg', 'Land', 'Yes', 7, 0, 0, 567, 229),
	array('Akmolinsk', 'Coast', 'No', 7, 0, 0, 637, 231),
	array('Siberia', 'Land', 'No', 7, 0, 0, 770, 94),
	array('Yakutsk', 'Land', 'No', 7, 0, 0, 973, 108),
	array('Irkutsk', 'Land', 'Yes', 7, 0, 0, 829, 155),
	array('Vladivostok', 'Coast', 'Yes', 7, 0, 0, 1093, 216),
	array('Kirghiz', 'Land', 'No', 7, 0, 0, 674, 242),
	array('Kamchatka', 'Coast', 'No', 7, 0, 0, 1081, 100),
	array('Baku', 'Land', 'Yes', 0, 0, 0, 508, 249),
	array('Mongolia', 'Land', 'Yes', 0, 0, 0, 853, 239),
	array('Urumqi', 'Land', 'No', 9, 0, 0, 806, 250),
	array('Kashgar', 'Land', 'Yes', 9, 0, 0, 742, 298),
	array('Sinkiang', 'Land', 'Yes', 9, 0, 0, 926, 325),
	array('Tibet', 'Land', 'No', 9, 0, 0, 839, 349),
	array('Tashkent', 'Land', 'Yes', 0, 0, 0, 638, 275),
	array('Turkmenistan', 'Land', 'No', 0, 0, 0, 599, 269),
	array('Karachi', 'Coast', 'Yes', 0, 0, 0, 700, 354),
	array('Tabriz', 'Land', 'No', 0, 0, 0, 549, 325),
	array('Tehran', 'Land', 'Yes', 0, 0, 0, 593, 313),
	array('Afghanistan', 'Land', 'No', 0, 0, 0, 650, 342),
	array('Qiqihar', 'Land', 'No', 9, 0, 0, 976, 248),
	array('Manchuria', 'Land', 'No', 9, 0, 0, 1059, 251),
	array('Levant', 'Coast', 'No', 8, 0, 0, 460, 328),
	array('Baghdad', 'Coast', 'Yes', 8, 0, 0, 517, 352),
	array('Shiraz', 'Coast', 'Yes', 0, 0, 0, 620, 382),
	array('Arabia', 'Coast', 'No', 0, 0, 0, 545, 435),
	array('Oman', 'Coast', 'Yes', 0, 0, 0, 605, 449),
	array('Mecca', 'Coast', 'No', 8, 0, 0, 473, 396),
	array('Aden', 'Coast', 'Yes', 1, 0, 0, 515, 483),
	array('Kashmir', 'Land', 'No', 0, 0, 0, 728, 352),
	array('Sindh', 'Coast', 'No', 0, 0, 0, 719, 416),
	array('Delhi', 'Land', 'Yes', 1, 0, 0, 759, 373),
	array('Algiers', 'Coast', 'Yes', 2, 0, 0, 205, 327),
	array('Morocco', 'Coast', 'Yes', 0, 0, 0, 152, 367),
	array('Port Arthur', 'Coast', 'Yes', 7, 0, 0, 1045, 277),
	array('Tunis', 'Coast', 'Yes', 0, 0, 0, 266, 333),
	array('Tripoli', 'Coast', 'Yes', 0, 0, 0, 296, 356),
	array('Cyrene', 'Coast', 'No', 0, 0, 0, 367, 370),
	array('Cairo', 'Coast', 'Yes', 8, 0, 0, 424, 410),
	array('Nubia', 'Coast', 'No', 0, 0, 0, 452, 471),
	array('Khartoum', 'Land', 'Yes', 0, 0, 0, 416, 488),
	array('Darfur', 'Land', 'No', 0, 0, 0, 388, 512),
	array('Fezzan', 'Land', 'No', 0, 0, 0, 354, 399),
	array('Deccan', 'Land', 'No', 1, 0, 0, 769, 438),
	array('Tamanrasset', 'Land', 'No', 0, 0, 0, 188, 364),
	array('Nanking', 'Land', 'Yes', 9, 0, 0, 978, 358),
	array('Hebei', 'Coast', 'No', 9, 0, 0, 1008, 304),
	array('Sichuan', 'Land', 'No', 9, 0, 0, 989, 386),
	array('Sakhalin', 'Coast', 'Yes', 0, 0, 0, 1118, 187),
	array('Sapporo', 'Coast', 'Yes', 10, 0, 0, 1163, 252),
	array('Seoul', 'Coast', 'Yes', 0, 0, 0, 1076, 290),
	array('Fusan', 'Coast', 'Yes', 0, 0, 0, 1084, 319),
	array('Shanghai', 'Coast', 'Yes', 9, 0, 0, 1035, 406),
	array('Canton', 'Coast', 'Yes', 9, 0, 0, 1000, 413),
	array('Assam', 'Land', 'No', 0, 0, 0, 841, 391),
	array('Akita', 'Coast', 'No', 10, 0, 0, 1161, 275),
	array('Tokyo', 'Coast', 'Yes', 10, 0, 0, 1177, 301),
	array('Kyoto', 'Coast', 'Yes', 10, 0, 0, 1138, 325),
	array('Kyushu', 'Coast', 'Yes', 10, 0, 0, 1131, 345),
	array('Adrar', 'Coast', 'No', 0, 0, 0, 123, 409),
	array('Timbuktu', 'Land', 'No', 0, 0, 0, 161, 453),
	array('Senegambia', 'Coast', 'Yes', 2, 0, 0, 99, 454),
	array('Wagadugu', 'Land', 'No', 0, 0, 0, 138, 492),
	array('Sierra Leone', 'Coast', 'Yes', 0, 0, 0, 106, 514),
	array('Liberia', 'Coast', 'No', 0, 0, 0, 107, 534),
	array('Ivory Coast', 'Coast', 'Yes', 0, 0, 0, 174, 563),
	array('Ashanti', 'Land', 'No', 0, 0, 0, 208, 520),
	array('Gold Coast', 'Coast', 'Yes', 1, 0, 0, 213, 553),
	array('Formosa', 'Coast', 'Yes', 0, 0, 0, 1072, 425),
	array('Burma', 'Land', 'Yes', 0, 0, 0, 894, 412),
	array('Sokoto', 'Land', 'No', 0, 0, 0, 240, 514),
	array('Benin', 'Coast', 'Yes', 0, 0, 0, 226, 542),
	array('Kamerun', 'Coast', 'Yes', 3, 0, 0, 293, 588),
	array('Bombay', 'Coast', 'Yes', 1, 0, 0, 740, 451),
	array('Madras', 'Coast', 'Yes', 0, 0, 0, 765, 528),
	array('Hyderabad', 'Coast', 'No', 0, 0, 0, 788, 467),
	array('Calcutta', 'Coast', 'Yes', 0, 0, 0, 814, 431),
	array('Eritrea', 'Coast', 'Yes', 4, 0, 0, 485, 493),
	array('Abyssinia', 'Land', 'Yes', 0, 0, 0, 486, 560),
	array('Somaliland', 'Coast', 'Yes', 0, 0, 0, 551, 559),
	array('Mombasa', 'Coast', 'Yes', 0, 0, 0, 468, 636),
	array('Rangoon', 'Coast', 'Yes', 0, 0, 0, 880, 437),
	array('Siam', 'Land', 'No', 0, 0, 0, 910, 438),
	array('Laos', 'Land', 'No', 0, 0, 0, 961, 478),
	array('Yunnan', 'Land', 'No', 9, 0, 0, 930, 427),
	array('Tongking', 'Coast', 'Yes', 2, 0, 0, 971, 438),
	array('Annam', 'Coast', 'No', 2, 0, 0, 976, 473),
	array('Hong Kong', 'Coast', 'Yes', 1, 0, 0, 1023, 428),
	array('Gabon', 'Coast', 'No', 0, 0, 0, 284, 633),
	array('Leopoldville', 'Coast', 'Yes', 0, 0, 0, 295, 651),
	array('Cape Verde', 'Coast', 'Yes', 0, 0, 0, 42, 437),
	array('Dar es Salaam', 'Coast', 'Yes', 3, 0, 0, 475, 691),
	array('West Congo', 'Land', 'No', 0, 0, 0, 361, 660),
	array('East Congo', 'Land', 'No', 0, 0, 0, 395, 661),
	array('Nyasaland', 'Land', 'No', 0, 0, 0, 401, 687),
	array('Cambodia', 'Coast', 'No', 2, 0, 0, 964, 516),
	array('Saigon', 'Coast', 'Yes', 2, 0, 0, 995, 513),
	array('Angola', 'Coast', 'No', 0, 0, 0, 316, 741),
	array('Namibia', 'Coast', 'No', 0, 0, 0, 324, 834),
	array('Ceylon', 'Coast', 'Yes', 0, 0, 0, 801, 552),
	array('Manila', 'Coast', 'Yes', 0, 0, 0, 1096, 491),
	array('Cebu', 'Coast', 'Yes', 0, 0, 0, 1081, 520),
	array('Malaysia', 'Coast', 'Yes', 0, 0, 0, 948, 584),
	array('Davao', 'Coast', 'Yes', 0, 0, 0, 1121, 535),
	array('Sarawak', 'Coast', 'Yes', 0, 0, 0, 1037, 594),
	array('Borneo', 'Coast', 'Yes', 6, 0, 0, 1017, 625),
	array('Sumatra', 'Coast', 'Yes', 6, 0, 0, 946, 622),
	array('Andaman Islands', 'Coast', 'Yes', 0, 0, 0, 875, 511),
	array('Novosibirsk', 'Land', 'No', 7, 0, 0, 740, 152),
	array('Rhodesia', 'Land', 'Yes', 0, 0, 0, 383, 728),
	array('Bechuanaland', 'Land', 'Yes', 0, 0, 0, 369, 785),
	array('Mozambique', 'Coast', 'No', 0, 0, 0, 442, 767),
	array('Madagascar', 'Coast', 'Yes', 2, 0, 0, 528, 796),
	array('Transvaal', 'Coast', 'Yes', 6, 0, 0, 417, 820),
	array('Beaufort', 'Coast', 'No', 0, 0, 0, 377, 883),
	array('Cape Town', 'Coast', 'Yes', 1, 0, 0, 353, 893),
	array('Maldives', 'Coast', 'Yes', 0, 0, 0, 718, 588),
	array('Seychelles', 'Coast', 'Yes', 0, 0, 0, 598, 653),
	array('Mauritius', 'Coast', 'Yes', 0, 0, 0, 619, 774),
	array('Singapore', 'Coast', 'Yes', 1, 0, 0, 976, 617),
	array('Java', 'Coast', 'Yes', 6, 0, 0, 1003, 676),
	array('Celebes', 'Coast', 'No', 6, 0, 0, 1097, 645),
	array('Iriam Java', 'Coast', 'Yes', 0, 0, 0, 1217, 636),
	array('New Guinea', 'Coast', 'No', 0, 0, 0, 1289, 693),
	array('Wilhelmsland', 'Coast', 'Yes', 3, 0, 0, 1281, 666),
	array('Western Australia', 'Coast', 'Yes', 0, 0, 0, 1037, 885),
	array('New South Wales', 'Coast', 'Yes', 1, 0, 0, 1189, 918),
	array('Northern Territory', 'Coast', 'No', 0, 0, 0, 1167, 744),
	array('Queensland', 'Coast', 'Yes', 0, 0, 0, 1243, 781),
	array('South Australia', 'Coast', 'No', 0, 0, 0, 1157, 880),
	array('Barents Sea', 'Sea', 'No', 0, 0, 0, 401, 15),
	array('Norwegian Sea', 'Sea', 'No', 0, 0, 0, 196, 69),
	array('North Passage', 'Sea', 'No', 0, 0, 0, 67, 157),
	array('North Sea', 'Sea', 'No', 0, 0, 0, 225, 159),
	array('Irish Sea', 'Sea', 'No', 0, 0, 0, 173, 165),
	array('English Channel', 'Sea', 'No', 0, 0, 0, 173, 198),
	array('Bay of Biscay', 'Sea', 'No', 0, 0, 0, 146, 224),
	array('North Atlantic', 'Sea', 'No', 0, 0, 0, 27, 355),
	array('Mid Atlantic', 'Sea', 'No', 0, 0, 0, 54, 672),
	array('Canaries', 'Sea', 'No', 0, 0, 0, 58, 516),
	array('Helgoland Bight', 'Sea', 'No', 0, 0, 0, 243, 158),
	array('Skagerrak', 'Sea', 'No', 0, 0, 0, 254, 132),
	array('Baltic Sea', 'Sea', 'No', 0, 0, 0, 322, 135),
	array('Gulf of Bothnia', 'Sea', 'No', 0, 0, 0, 340, 82),
	array('West Mediterranean', 'Sea', 'No', 0, 0, 0, 206, 296),
	array('Gulf of Lyon', 'Sea', 'No', 0, 0, 0, 223, 273),
	array('Tyrrhenian Sea', 'Sea', 'No', 0, 0, 0, 271, 272),
	array('Adriatic Sea', 'Sea', 'No', 0, 0, 0, 300, 244),
	array('Ionian Sea', 'Sea', 'No', 0, 0, 0, 303, 319),
	array('Black Sea', 'Sea', 'No', 0, 0, 0, 457, 255),
	array('Aegean Sea', 'Sea', 'No', 0, 0, 0, 366, 302),
	array('East Mediterranean', 'Sea', 'No', 0, 0, 0, 433, 328),
	array('Red Sea', 'Sea', 'No', 0, 0, 0, 473, 428),
	array('Gulf of Guinea', 'Sea', 'No', 0, 0, 0, 197, 589),
	array('South Atlantic', 'Sea', 'No', 0, 0, 0, 214, 813),
	array('West Southern Ocean', 'Sea', 'No', 0, 0, 0, 64, 880),
	array('East Southern Ocean', 'Sea', 'No', 0, 0, 0, 494, 985),
	array('Cape of Good Hope', 'Sea', 'No', 0, 0, 0, 452, 884),
	array('Horn of Africa', 'Sea', 'No', 0, 0, 0, 578, 589),
	array('Persian Gulf', 'Sea', 'No', 0, 0, 0, 558, 382),
	array('Arabian Sea', 'Sea', 'No', 0, 0, 0, 702, 469),
	array('Gulf of Aden', 'Sea', 'No', 0, 0, 0, 603, 489),
	array('North Indian', 'Sea', 'No', 0, 0, 0, 659, 599),
	array('West Indian', 'Sea', 'No', 0, 0, 0, 701, 681),
	array('Southwest Indian', 'Sea', 'No', 0, 0, 0, 610, 878),
	array('Gulf of Manaar', 'Sea', 'No', 0, 0, 0, 879, 621),
	array('East Indian', 'Sea', 'No', 0, 0, 0, 905, 759),
	array('Southeast Indian', 'Sea', 'No', 0, 0, 0, 918, 948),
	array('New Zealand', 'Coast', 'Yes', 0, 0, 0, 1404, 947),
	array('Sea of Okhotsk', 'Sea', 'No', 0, 0, 0, 1164, 197),
	array('Sea of Japan', 'Sea', 'No', 0, 0, 0, 1122, 253),
	array('North Pacific', 'Sea', 'No', 0, 0, 0, 1325, 289),
	array('Yellow Sea', 'Sea', 'No', 0, 0, 0, 1024, 290),
	array('East China Sea', 'Sea', 'No', 0, 0, 0, 1110, 374),
	array('Philippine Sea', 'Sea', 'No', 0, 0, 0, 1143, 457),
	array('Celebes Sea', 'Sea', 'No', 0, 0, 0, 1223, 591),
	array('Central Pacific', 'Sea', 'No', 0, 0, 0, 1299, 620),
	array('South Pacific', 'Sea', 'No', 0, 0, 0, 1326, 763),
	array('Sulu Sea', 'Sea', 'No', 0, 0, 0, 1020, 563),
	array('Gulf of Siam', 'Sea', 'No', 0, 0, 0, 957, 540),
	array('South China Sea', 'Sea', 'No', 0, 0, 0, 1013, 492),
	array('Tasman Sea', 'Sea', 'No', 0, 0, 0, 1107, 976),
	array('Andaman Sea', 'Sea', 'No', 0, 0, 0, 898, 501),
	array('Bay of Bengal', 'Sea', 'No', 0, 0, 0, 810, 516),
	array('Mozambique Channel', 'Sea', 'No', 0, 0, 0, 509, 729),
	array('Java Sea', 'Sea', 'No', 0, 0, 0, 994, 634),
	array('Timor Sea', 'Sea', 'No', 0, 0, 0, 1122, 681),
	array('Bangkok', 'Coast', 'Yes', 0, 0, 0, 928, 507),
	array('Arabia (North Coast)', 'Coast', 'No', 0, 0, 0, 545, 388),
	array('Arabia (South Coast)', 'Coast', 'No', 0, 0, 0, 572, 475),
	array('Bangkok (East Coast)', 'Coast', 'No', 0, 0, 0, 945, 555),
	array('Bangkok (West Coast)', 'Coast', 'No', 0, 0, 0, 923, 541),
	array('Canton (East Coast)', 'Coast', 'No', 0, 0, 0, 1028, 423),
	array('Canton (West Coast)', 'Coast', 'No', 0, 0, 0, 999, 433),
	array('Seoul (West Coast)', 'Coast', 'No', 0, 0, 0, 1063, 290),
	array('Seoul (East Coast)', 'Coast', 'No', 0, 0, 0, 1077, 265),
	array('Posen', 'Coast', 'Yes', 3, 0, 0, 301, 178),
	array('Silesia', 'Land', 'No', 3, 0, 0, 319, 193),
	array('Tiflis', 'Coast', 'No', 7, 0, 0, 481, 249),
	array('Mukden', 'Coast', 'Yes', 9, 0, 0, 1016, 267),
	array('Tsaritsyn (East Coast)', 'Coast', 'No', 0, 0, 0, 533, 215),
	array('Tsaritsyn (West Coast)', 'Coast', 'No', 0, 0, 0, 458, 209),
	array('Caspian Sea', 'Sea', 'No', 0, 0, 0, 550, 280),
	array('Greenland', 'Coast', 'No', 0, 0, 0, 27, 42)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Kiel','Denmark','Yes','Yes'),
	array('Kiel','Berlin','No','Yes'),
	array('Kiel','Saxony','No','Yes'),
	array('Kiel','Cologne','No','Yes'),
	array('Kiel','Holland','Yes','Yes'),
	array('Kiel','Ruhr','No','Yes'),
	array('Kiel','Helgoland Bight','Yes','No'),
	array('Iceland','Norwegian Sea','Yes','No'),
	array('Iceland','North Passage','Yes','No'),
	array('Edinburgh','Liverpool','Yes','Yes'),
	array('Edinburgh','Yorkshire','Yes','Yes'),
	array('Edinburgh','Norwegian Sea','Yes','No'),
	array('Edinburgh','North Passage','Yes','No'),
	array('Edinburgh','North Sea','Yes','No'),
	array('Liverpool','Yorkshire','No','Yes'),
	array('Liverpool','Ireland','Yes','Yes'),
	array('Liverpool','London','No','Yes'),
	array('Liverpool','Wales','Yes','Yes'),
	array('Liverpool','North Passage','Yes','No'),
	array('Liverpool','Irish Sea','Yes','No'),
	array('Yorkshire','London','Yes','Yes'),
	array('Yorkshire','North Sea','Yes','No'),
	array('Ireland','North Passage','Yes','No'),
	array('Ireland','Irish Sea','Yes','No'),
	array('Norway','Sweden','Yes','Yes'),
	array('Norway','Finland','No','Yes'),
	array('Norway','St. Petersburg','No','Yes'),
	array('Norway','St. Petersburg (North Coast)','Yes','No'),
	array('Norway','Barents Sea','Yes','No'),
	array('Norway','Norwegian Sea','Yes','No'),
	array('Norway','North Sea','Yes','No'),
	array('Norway','Skagerrak','Yes','No'),
	array('Sweden','Finland','Yes','Yes'),
	array('Sweden','Denmark','Yes','Yes'),
	array('Sweden','Skagerrak','Yes','No'),
	array('Sweden','Baltic Sea','Yes','No'),
	array('Sweden','Gulf of Bothnia','Yes','No'),
	array('Finland','St. Petersburg','No','Yes'),
	array('Finland','St. Petersburg (South Coast)','Yes','No'),
	array('Finland','Gulf of Bothnia','Yes','No'),
	array('St. Petersburg','Livonia','No','Yes'),
	array('St. Petersburg','Moscow','No','Yes'),
	array('St. Petersburg','Arkhangelsk','No','Yes'),
	array('St. Petersburg (South Coast)','Livonia','Yes','No'),
	array('St. Petersburg (South Coast)','Gulf of Bothnia','Yes','No'),
	array('St. Petersburg (North Coast)','Arkhangelsk','Yes','No'),
	array('St. Petersburg (North Coast)','Barents Sea','Yes','No'),
	array('Brest','Picardy','Yes','Yes'),
	array('Brest','Paris','No','Yes'),
	array('Brest','Gascony','Yes','Yes'),
	array('Brest','English Channel','Yes','No'),
	array('Brest','Bay of Biscay','Yes','No'),
	array('Picardy','Paris','No','Yes'),
	array('Picardy','Burgundy','No','Yes'),
	array('Picardy','Belgium','Yes','Yes'),
	array('Picardy','English Channel','Yes','No'),
	array('Paris','Gascony','No','Yes'),
	array('Paris','Burgundy','No','Yes'),
	array('London','Wales','Yes','Yes'),
	array('London','North Sea','Yes','No'),
	array('London','English Channel','Yes','No'),
	array('Gascony','Burgundy','No','Yes'),
	array('Gascony','Spain','No','Yes'),
	array('Gascony','Spain (North Coast)','Yes','No'),
	array('Gascony','Marseilles','No','Yes'),
	array('Gascony','Bay of Biscay','Yes','No'),
	array('Burgundy','Marseilles','No','Yes'),
	array('Burgundy','Belgium','No','Yes'),
	array('Burgundy','Ruhr','No','Yes'),
	array('Burgundy','Munich','No','Yes'),
	array('Spain','Portugal','No','Yes'),
	array('Spain','Gibraltar','No','Yes'),
	array('Spain','Marseilles','No','Yes'),
	array('Spain (North Coast)','Portugal','Yes','No'),
	array('Spain (North Coast)','Bay of Biscay','Yes','No'),
	array('Spain (North Coast)','North Atlantic','Yes','No'),
	array('Spain (South Coast)','Gibraltar','Yes','No'),
	array('Spain (South Coast)','Marseilles','Yes','No'),
	array('Spain (South Coast)','West Mediterranean','Yes','No'),
	array('Spain (South Coast)','Gulf of Lyon','Yes','No'),
	array('Portugal','Gibraltar','Yes','Yes'),
	array('Portugal','North Atlantic','Yes','No'),
	array('Wales','Irish Sea','Yes','No'),
	array('Wales','English Channel','Yes','No'),
	array('Gibraltar','Morocco','Yes','Yes'),
	array('Gibraltar','North Atlantic','Yes','No'),
	array('Gibraltar','West Mediterranean','Yes','No'),
	array('Marseilles','Piedmont','Yes','Yes'),
	array('Marseilles','Gulf of Lyon','Yes','No'),
	array('Livonia','Prussia','Yes','Yes'),
	array('Livonia','Moscow','No','Yes'),
	array('Livonia','Warsaw','No','Yes'),
	array('Livonia','Baltic Sea','Yes','No'),
	array('Livonia','Gulf of Bothnia','Yes','No'),
	array('Denmark','Berlin','Yes','Yes'),
	array('Denmark','North Sea','Yes','No'),
	array('Denmark','Helgoland Bight','Yes','No'),
	array('Denmark','Skagerrak','Yes','No'),
	array('Denmark','Baltic Sea','Yes','No'),
	array('Berlin','Saxony','No','Yes'),
	array('Berlin','Baltic Sea','Yes','No'),
	array('Berlin','Posen','Yes','Yes'),
	array('Saxony','Ruhr','No','Yes'),
	array('Saxony','Munich','No','Yes'),
	array('Saxony','Bohemia','No','Yes'),
	array('Saxony','Posen','No','Yes'),
	array('Saxony','Silesia','No','Yes'),
	array('Cologne','Holland','No','Yes'),
	array('Cologne','Belgium','No','Yes'),
	array('Cologne','Ruhr','No','Yes'),
	array('Holland','Belgium','Yes','Yes'),
	array('Holland','North Sea','Yes','No'),
	array('Holland','English Channel','Yes','No'),
	array('Holland','Helgoland Bight','Yes','No'),
	array('Belgium','Ruhr','No','Yes'),
	array('Belgium','English Channel','Yes','No'),
	array('Piedmont','Venice','No','Yes'),
	array('Piedmont','Rome','Yes','Yes'),
	array('Piedmont','Gulf of Lyon','Yes','No'),
	array('Piedmont','Tyrrhenian Sea','Yes','No'),
	array('Prussia','Warsaw','No','Yes'),
	array('Prussia','Baltic Sea','Yes','No'),
	array('Prussia','Posen','Yes','Yes'),
	array('Prussia','Silesia','No','Yes'),
	array('Ruhr','Munich','No','Yes'),
	array('Moscow','Warsaw','No','Yes'),
	array('Moscow','Ukraine','No','Yes'),
	array('Moscow','Sevastopol','No','Yes'),
	array('Moscow','Arkhangelsk','No','Yes'),
	array('Moscow','Tsaritsyn','No','Yes'),
	array('Warsaw','Galicia','No','Yes'),
	array('Warsaw','Ukraine','No','Yes'),
	array('Warsaw','Silesia','No','Yes'),
	array('Munich','Bohemia','No','Yes'),
	array('Munich','Tyrolia','No','Yes'),
	array('Bohemia','Galicia','No','Yes'),
	array('Bohemia','Tyrolia','No','Yes'),
	array('Bohemia','Vienna','No','Yes'),
	array('Bohemia','Silesia','No','Yes'),
	array('Galicia','Vienna','No','Yes'),
	array('Galicia','Budapest','No','Yes'),
	array('Galicia','Ukraine','No','Yes'),
	array('Galicia','Rumania','No','Yes'),
	array('Galicia','Silesia','No','Yes'),
	array('Tyrolia','Venice','No','Yes'),
	array('Tyrolia','Vienna','No','Yes'),
	array('Tyrolia','Trieste','No','Yes'),
	array('Venice','Rome','No','Yes'),
	array('Venice','Apulia','Yes','Yes'),
	array('Venice','Trieste','Yes','Yes'),
	array('Venice','Adriatic Sea','Yes','No'),
	array('Rome','Apulia','No','Yes'),
	array('Rome','Naples','Yes','Yes'),
	array('Rome','Tyrrhenian Sea','Yes','No'),
	array('Apulia','Naples','Yes','Yes'),
	array('Apulia','Adriatic Sea','Yes','No'),
	array('Apulia','Ionian Sea','Yes','No'),
	array('Vienna','Budapest','No','Yes'),
	array('Vienna','Trieste','No','Yes'),
	array('Budapest','Trieste','No','Yes'),
	array('Budapest','Sarajevo','No','Yes'),
	array('Budapest','Rumania','No','Yes'),
	array('Budapest','Serbia','No','Yes'),
	array('Ukraine','Sevastopol','No','Yes'),
	array('Ukraine','Rumania','No','Yes'),
	array('Trieste','Sarajevo','Yes','Yes'),
	array('Trieste','Adriatic Sea','Yes','No'),
	array('Sarajevo','Serbia','No','Yes'),
	array('Sarajevo','Albania','Yes','Yes'),
	array('Sarajevo','Adriatic Sea','Yes','No'),
	array('Sevastopol','Tsaritsyn','No','Yes'),
	array('Sevastopol','Rumania','Yes','Yes'),
	array('Sevastopol','Black Sea','Yes','No'),
	array('Sevastopol','Tsaritsyn (West Coast)','Yes','No'),
	array('Naples','Sicily','Yes','Yes'),
	array('Naples','Tyrrhenian Sea','Yes','No'),
	array('Naples','Ionian Sea','Yes','No'),
	array('Sicily','Tunis','Yes','Yes'),
	array('Sicily','Tyrrhenian Sea','Yes','No'),
	array('Sicily','Ionian Sea','Yes','No'),
	array('Arkhangelsk','Omsk','No','Yes'),
	array('Arkhangelsk','Tsaritsyn','No','Yes'),
	array('Arkhangelsk','Barents Sea','Yes','No'),
	array('Omsk','Tsaritsyn','No','Yes'),
	array('Omsk','Orenburg','No','Yes'),
	array('Omsk','Akmolinsk','No','Yes'),
	array('Omsk','Siberia','No','Yes'),
	array('Omsk','Novosibirsk','No','Yes'),
	array('Peking','Mongolia','No','Yes'),
	array('Peking','Sinkiang','No','Yes'),
	array('Peking','Qiqihar','No','Yes'),
	array('Peking','Hebei','Yes','Yes'),
	array('Peking','Yellow Sea','Yes','No'),
	array('Peking','Mukden','Yes','Yes'),
	array('Tsaritsyn','Rostov','No','Yes'),
	array('Tsaritsyn','Orenburg','No','Yes'),
	array('Tsaritsyn','Baku','No','Yes'),
	array('Rostov','Baku','No','Yes'),
	array('Rostov','Black Sea','Yes','No'),
	array('Rostov','Tiflis','Yes','Yes'),
	array('Rostov','Tsaritsyn (West Coast)','Yes','No'),
	array('Rumania','Serbia','No','Yes'),
	array('Rumania','Bulgaria','Yes','Yes'),
	array('Rumania','Black Sea','Yes','No'),
	array('Serbia','Bulgaria','No','Yes'),
	array('Serbia','Macedonia','No','Yes'),
	array('Serbia','Albania','No','Yes'),
	array('Bulgaria','Macedonia','No','Yes'),
	array('Bulgaria','Constantinople','Yes','Yes'),
	array('Bulgaria','Black Sea','Yes','No'),
	array('Macedonia','Albania','No','Yes'),
	array('Macedonia','Constantinople','Yes','Yes'),
	array('Macedonia','Greece','Yes','Yes'),
	array('Macedonia','Aegean Sea','Yes','No'),
	array('Albania','Greece','Yes','Yes'),
	array('Albania','Adriatic Sea','Yes','No'),
	array('Albania','Ionian Sea','Yes','No'),
	array('Constantinople','Angora','Yes','Yes'),
	array('Constantinople','Smyrna','Yes','Yes'),
	array('Constantinople','Black Sea','Yes','No'),
	array('Constantinople','Aegean Sea','Yes','No'),
	array('Greece','Ionian Sea','Yes','No'),
	array('Greece','Aegean Sea','Yes','No'),
	array('Angora','Smyrna','No','Yes'),
	array('Angora','Armenia','Yes','Yes'),
	array('Angora','Black Sea','Yes','No'),
	array('Smyrna','Armenia','No','Yes'),
	array('Smyrna','Levant','Yes','Yes'),
	array('Smyrna','Aegean Sea','Yes','No'),
	array('Smyrna','East Mediterranean','Yes','No'),
	array('Armenia','Baku','No','Yes'),
	array('Armenia','Tabriz','No','Yes'),
	array('Armenia','Levant','No','Yes'),
	array('Armenia','Baghdad','No','Yes'),
	array('Armenia','Tiflis','Yes','Yes'),
	array('Orenburg','Akmolinsk','No','Yes'),
	array('Orenburg','Tashkent','No','Yes'),
	array('Orenburg','Turkmenistan','No','Yes'),
	array('Orenburg','Tsaritsyn (East Coast)','Yes','No'),
	array('Orenburg','Caspian Sea','Yes','No'),
	array('Akmolinsk','Kirghiz','No','Yes'),
	array('Akmolinsk','Tashkent','No','Yes'),
	array('Akmolinsk','Novosibirsk','No','Yes'),
	array('Siberia','Yakutsk','No','Yes'),
	array('Siberia','Irkutsk','No','Yes'),
	array('Siberia','Novosibirsk','No','Yes'),
	array('Yakutsk','Irkutsk','No','Yes'),
	array('Yakutsk','Vladivostok','No','Yes'),
	array('Yakutsk','Kamchatka','No','Yes'),
	array('Irkutsk','Vladivostok','No','Yes'),
	array('Irkutsk','Mongolia','No','Yes'),
	array('Irkutsk','Qiqihar','No','Yes'),
	array('Irkutsk','Novosibirsk','No','Yes'),
	array('Vladivostok','Kamchatka','Yes','Yes'),
	array('Vladivostok','Qiqihar','No','Yes'),
	array('Vladivostok','Manchuria','No','Yes'),
	array('Vladivostok','Seoul','No','Yes'),
	array('Vladivostok','Sea of Okhotsk','Yes','No'),
	array('Vladivostok','Sea of Japan','Yes','No'),
	array('Vladivostok','Seoul (East Coast)','Yes','No'),
	array('Kirghiz','Urumqi','No','Yes'),
	array('Kirghiz','Kashgar','No','Yes'),
	array('Kirghiz','Tashkent','No','Yes'),
	array('Kirghiz','Novosibirsk','No','Yes'),
	array('Kamchatka','Sea of Okhotsk','Yes','No'),
	array('Kamchatka','North Pacific','Yes','No'),
	array('Baku','Tabriz','No','Yes'),
	array('Baku','Tiflis','No','Yes'),
	array('Baku','Tsaritsyn (East Coast)','Yes','No'),
	array('Baku','Caspian Sea','Yes','No'),
	array('Mongolia','Urumqi','No','Yes'),
	array('Mongolia','Sinkiang','No','Yes'),
	array('Mongolia','Qiqihar','No','Yes'),
	array('Mongolia','Novosibirsk','No','Yes'),
	array('Urumqi','Kashgar','No','Yes'),
	array('Urumqi','Sinkiang','No','Yes'),
	array('Urumqi','Novosibirsk','No','Yes'),
	array('Kashgar','Sinkiang','No','Yes'),
	array('Kashgar','Tibet','No','Yes'),
	array('Kashgar','Tashkent','No','Yes'),
	array('Kashgar','Karachi','No','Yes'),
	array('Kashgar','Kashmir','No','Yes'),
	array('Sinkiang','Tibet','No','Yes'),
	array('Sinkiang','Nanking','No','Yes'),
	array('Sinkiang','Hebei','No','Yes'),
	array('Sinkiang','Sichuan','No','Yes'),
	array('Sinkiang','Burma','No','Yes'),
	array('Tibet','Kashmir','No','Yes'),
	array('Tibet','Assam','No','Yes'),
	array('Tibet','Burma','No','Yes'),
	array('Tashkent','Turkmenistan','No','Yes'),
	array('Tashkent','Karachi','No','Yes'),
	array('Tashkent','Afghanistan','No','Yes'),
	array('Turkmenistan','Tehran','No','Yes'),
	array('Turkmenistan','Afghanistan','No','Yes'),
	array('Turkmenistan','Caspian Sea','Yes','No'),
	array('Karachi','Afghanistan','No','Yes'),
	array('Karachi','Shiraz','Yes','Yes'),
	array('Karachi','Kashmir','No','Yes'),
	array('Karachi','Sindh','Yes','Yes'),
	array('Karachi','Arabian Sea','Yes','No'),
	array('Tabriz','Tehran','No','Yes'),
	array('Tabriz','Baghdad','No','Yes'),
	array('Tabriz','Shiraz','No','Yes'),
	array('Tabriz','Caspian Sea','Yes','No'),
	array('Tehran','Afghanistan','No','Yes'),
	array('Tehran','Shiraz','No','Yes'),
	array('Tehran','Caspian Sea','Yes','No'),
	array('Afghanistan','Shiraz','No','Yes'),
	array('Qiqihar','Manchuria','No','Yes'),
	array('Qiqihar','Mukden','No','Yes'),
	array('Manchuria','Seoul','No','Yes'),
	array('Manchuria','Mukden','No','Yes'),
	array('Levant','Baghdad','No','Yes'),
	array('Levant','Arabia','No','Yes'),
	array('Levant','Mecca','No','Yes'),
	array('Levant','Cairo','Yes','Yes'),
	array('Levant','East Mediterranean','Yes','No'),
	array('Baghdad','Shiraz','Yes','Yes'),
	array('Baghdad','Arabia','No','Yes'),
	array('Baghdad','Persian Gulf','Yes','No'),
	array('Baghdad','Arabia (North Coast)','Yes','No'),
	array('Shiraz','Persian Gulf','Yes','No'),
	array('Shiraz','Arabian Sea','Yes','No'),
	array('Arabia','Oman','No','Yes'),
	array('Arabia','Mecca','No','Yes'),
	array('Arabia','Aden','No','Yes'),
	array('Oman','Persian Gulf','Yes','No'),
	array('Oman','Arabian Sea','Yes','No'),
	array('Oman','Gulf of Aden','Yes','No'),
	array('Oman','Arabia (North Coast)','Yes','No'),
	array('Oman','Arabia (South Coast)','Yes','No'),
	array('Mecca','Aden','Yes','Yes'),
	array('Mecca','Cairo','Yes','Yes'),
	array('Mecca','Red Sea','Yes','No'),
	array('Aden','Red Sea','Yes','No'),
	array('Aden','Gulf of Aden','Yes','No'),
	array('Aden','Arabia (South Coast)','Yes','No'),
	array('Kashmir','Sindh','No','Yes'),
	array('Kashmir','Delhi','No','Yes'),
	array('Sindh','Delhi','No','Yes'),
	array('Sindh','Deccan','No','Yes'),
	array('Sindh','Bombay','Yes','Yes'),
	array('Sindh','Arabian Sea','Yes','No'),
	array('Delhi','Deccan','No','Yes'),
	array('Delhi','Assam','No','Yes'),
	array('Algiers','Morocco','Yes','Yes'),
	array('Algiers','Tunis','Yes','Yes'),
	array('Algiers','Tamanrasset','No','Yes'),
	array('Algiers','West Mediterranean','Yes','No'),
	array('Morocco','Tamanrasset','No','Yes'),
	array('Morocco','Adrar','Yes','Yes'),
	array('Morocco','Timbuktu','No','Yes'),
	array('Morocco','North Atlantic','Yes','No'),
	array('Morocco','Canaries','Yes','No'),
	array('Morocco','West Mediterranean','Yes','No'),
	array('Port Arthur','Seoul','No','Yes'),
	array('Port Arthur','Yellow Sea','Yes','No'),
	array('Port Arthur','Seoul (West Coast)','Yes','No'),
	array('Port Arthur','Mukden','Yes','Yes'),
	array('Tunis','Tripoli','Yes','Yes'),
	array('Tunis','Fezzan','No','Yes'),
	array('Tunis','Tamanrasset','No','Yes'),
	array('Tunis','West Mediterranean','Yes','No'),
	array('Tunis','Tyrrhenian Sea','Yes','No'),
	array('Tunis','Ionian Sea','Yes','No'),
	array('Tripoli','Cyrene','Yes','Yes'),
	array('Tripoli','Fezzan','No','Yes'),
	array('Tripoli','Ionian Sea','Yes','No'),
	array('Cyrene','Cairo','Yes','Yes'),
	array('Cyrene','Fezzan','No','Yes'),
	array('Cyrene','Ionian Sea','Yes','No'),
	array('Cyrene','East Mediterranean','Yes','No'),
	array('Cairo','Nubia','Yes','Yes'),
	array('Cairo','Khartoum','No','Yes'),
	array('Cairo','Fezzan','No','Yes'),
	array('Cairo','East Mediterranean','Yes','No'),
	array('Cairo','Red Sea','Yes','No'),
	array('Nubia','Khartoum','No','Yes'),
	array('Nubia','Eritrea','Yes','Yes'),
	array('Nubia','Abyssinia','No','Yes'),
	array('Nubia','Red Sea','Yes','No'),
	array('Khartoum','Darfur','No','Yes'),
	array('Khartoum','Fezzan','No','Yes'),
	array('Khartoum','Abyssinia','No','Yes'),
	array('Darfur','Abyssinia','No','Yes'),
	array('Darfur','Mombasa','No','Yes'),
	array('Fezzan','Tamanrasset','No','Yes'),
	array('Deccan','Assam','No','Yes'),
	array('Deccan','Bombay','No','Yes'),
	array('Deccan','Madras','No','Yes'),
	array('Deccan','Hyderabad','No','Yes'),
	array('Deccan','Calcutta','No','Yes'),
	array('Tamanrasset','Timbuktu','No','Yes'),
	array('Nanking','Hebei','No','Yes'),
	array('Nanking','Sichuan','No','Yes'),
	array('Nanking','Shanghai','No','Yes'),
	array('Hebei','Shanghai','Yes','Yes'),
	array('Hebei','Yellow Sea','Yes','No'),
	array('Hebei','East China Sea','Yes','No'),
	array('Sichuan','Shanghai','No','Yes'),
	array('Sichuan','Canton','No','Yes'),
	array('Sichuan','Burma','No','Yes'),
	array('Sichuan','Yunnan','No','Yes'),
	array('Sakhalin','Sea of Okhotsk','Yes','No'),
	array('Sakhalin','Sea of Japan','Yes','No'),
	array('Sapporo','Akita','Yes','Yes'),
	array('Sapporo','Sea of Okhotsk','Yes','No'),
	array('Sapporo','Sea of Japan','Yes','No'),
	array('Seoul','Fusan','No','Yes'),
	array('Seoul','Mukden','No','Yes'),
	array('Fusan','Sea of Japan','Yes','No'),
	array('Fusan','Yellow Sea','Yes','No'),
	array('Fusan','East China Sea','Yes','No'),
	array('Fusan','Seoul (West Coast)','Yes','No'),
	array('Fusan','Seoul (East Coast)','Yes','No'),
	array('Shanghai','Canton','No','Yes'),
	array('Shanghai','East China Sea','Yes','No'),
	array('Shanghai','Canton (East Coast)','Yes','No'),
	array('Canton','Yunnan','No','Yes'),
	array('Canton','Tongking','No','Yes'),
	array('Canton','Hong Kong','No','Yes'),
	array('Assam','Burma','No','Yes'),
	array('Assam','Calcutta','No','Yes'),
	array('Akita','Tokyo','Yes','Yes'),
	array('Akita','Kyoto','Yes','Yes'),
	array('Akita','Sea of Okhotsk','Yes','No'),
	array('Akita','Sea of Japan','Yes','No'),
	array('Akita','North Pacific','Yes','No'),
	array('Tokyo','Kyoto','Yes','Yes'),
	array('Tokyo','North Pacific','Yes','No'),
	array('Tokyo','Philippine Sea','Yes','No'),
	array('Kyoto','Kyushu','Yes','Yes'),
	array('Kyoto','Sea of Japan','Yes','No'),
	array('Kyoto','East China Sea','Yes','No'),
	array('Kyoto','Philippine Sea','Yes','No'),
	array('Kyushu','East China Sea','Yes','No'),
	array('Kyushu','Philippine Sea','Yes','No'),
	array('Adrar','Timbuktu','No','Yes'),
	array('Adrar','Senegambia','Yes','Yes'),
	array('Adrar','Wagadugu','No','Yes'),
	array('Adrar','Canaries','Yes','No'),
	array('Timbuktu','Wagadugu','No','Yes'),
	array('Senegambia','Wagadugu','No','Yes'),
	array('Senegambia','Sierra Leone','Yes','Yes'),
	array('Senegambia','Canaries','Yes','No'),
	array('Wagadugu','Sierra Leone','No','Yes'),
	array('Wagadugu','Liberia','No','Yes'),
	array('Wagadugu','Ivory Coast','No','Yes'),
	array('Wagadugu','Ashanti','No','Yes'),
	array('Sierra Leone','Liberia','Yes','Yes'),
	array('Sierra Leone','Canaries','Yes','No'),
	array('Liberia','Ivory Coast','Yes','Yes'),
	array('Liberia','Mid Atlantic','Yes','No'),
	array('Liberia','Canaries','Yes','No'),
	array('Ivory Coast','Ashanti','No','Yes'),
	array('Ivory Coast','Gold Coast','Yes','Yes'),
	array('Ivory Coast','Mid Atlantic','Yes','No'),
	array('Ivory Coast','Gulf of Guinea','Yes','No'),
	array('Ashanti','Gold Coast','No','Yes'),
	array('Ashanti','Sokoto','No','Yes'),
	array('Ashanti','Benin','No','Yes'),
	array('Gold Coast','Benin','Yes','Yes'),
	array('Gold Coast','Gulf of Guinea','Yes','No'),
	array('Formosa','East China Sea','Yes','No'),
	array('Formosa','Philippine Sea','Yes','No'),
	array('Formosa','South China Sea','Yes','No'),
	array('Burma','Calcutta','No','Yes'),
	array('Burma','Rangoon','No','Yes'),
	array('Burma','Siam','No','Yes'),
	array('Burma','Yunnan','No','Yes'),
	array('Sokoto','Benin','No','Yes'),
	array('Sokoto','Kamerun','No','Yes'),
	array('Benin','Kamerun','Yes','Yes'),
	array('Benin','Gulf of Guinea','Yes','No'),
	array('Kamerun','Gabon','Yes','Yes'),
	array('Kamerun','Gulf of Guinea','Yes','No'),
	array('Bombay','Madras','Yes','Yes'),
	array('Bombay','Arabian Sea','Yes','No'),
	array('Bombay','North Indian','Yes','No'),
	array('Madras','Hyderabad','Yes','Yes'),
	array('Madras','Ceylon','Yes','Yes'),
	array('Madras','North Indian','Yes','No'),
	array('Madras','Gulf of Manaar','Yes','No'),
	array('Madras','Bay of Bengal','Yes','No'),
	array('Hyderabad','Calcutta','Yes','Yes'),
	array('Hyderabad','Bay of Bengal','Yes','No'),
	array('Calcutta','Rangoon','Yes','Yes'),
	array('Calcutta','Bay of Bengal','Yes','No'),
	array('Eritrea','Abyssinia','No','Yes'),
	array('Eritrea','Somaliland','Yes','Yes'),
	array('Eritrea','Red Sea','Yes','No'),
	array('Eritrea','Gulf of Aden','Yes','No'),
	array('Abyssinia','Somaliland','No','Yes'),
	array('Abyssinia','Mombasa','No','Yes'),
	array('Somaliland','Mombasa','Yes','Yes'),
	array('Somaliland','Horn of Africa','Yes','No'),
	array('Somaliland','Gulf of Aden','Yes','No'),
	array('Mombasa','Dar es Salaam','Yes','Yes'),
	array('Mombasa','East Congo','No','Yes'),
	array('Mombasa','Horn of Africa','Yes','No'),
	array('Rangoon','Siam','No','Yes'),
	array('Rangoon','Andaman Sea','Yes','No'),
	array('Rangoon','Bay of Bengal','Yes','No'),
	array('Rangoon','Bangkok','No','Yes'),
	array('Rangoon','Bangkok (West Coast)','Yes','No'),
	array('Siam','Laos','No','Yes'),
	array('Siam','Yunnan','No','Yes'),
	array('Siam','Bangkok','No','Yes'),
	array('Laos','Yunnan','No','Yes'),
	array('Laos','Tongking','No','Yes'),
	array('Laos','Annam','No','Yes'),
	array('Laos','Cambodia','No','Yes'),
	array('Laos','Bangkok','No','Yes'),
	array('Yunnan','Tongking','No','Yes'),
	array('Tongking','Annam','Yes','Yes'),
	array('Tongking','South China Sea','Yes','No'),
	array('Tongking','Canton (West Coast)','Yes','No'),
	array('Annam','Cambodia','No','Yes'),
	array('Annam','Saigon','Yes','Yes'),
	array('Annam','South China Sea','Yes','No'),
	array('Hong Kong','East China Sea','Yes','No'),
	array('Hong Kong','South China Sea','Yes','No'),
	array('Hong Kong','Canton (East Coast)','Yes','No'),
	array('Hong Kong','Canton (West Coast)','Yes','No'),
	array('Gabon','Leopoldville','Yes','Yes'),
	array('Gabon','West Congo','No','Yes'),
	array('Gabon','Gulf of Guinea','Yes','No'),
	array('Gabon','South Atlantic','Yes','No'),
	array('Leopoldville','West Congo','No','Yes'),
	array('Leopoldville','Angola','Yes','Yes'),
	array('Leopoldville','South Atlantic','Yes','No'),
	array('Cape Verde','North Atlantic','Yes','No'),
	array('Cape Verde','Mid Atlantic','Yes','No'),
	array('Cape Verde','Canaries','Yes','No'),
	array('Dar es Salaam','East Congo','No','Yes'),
	array('Dar es Salaam','Nyasaland','No','Yes'),
	array('Dar es Salaam','Mozambique','Yes','Yes'),
	array('Dar es Salaam','Horn of Africa','Yes','No'),
	array('Dar es Salaam','Mozambique Channel','Yes','No'),
	array('West Congo','East Congo','No','Yes'),
	array('West Congo','Nyasaland','No','Yes'),
	array('West Congo','Angola','No','Yes'),
	array('West Congo','Rhodesia','No','Yes'),
	array('East Congo','Nyasaland','No','Yes'),
	array('Nyasaland','Rhodesia','No','Yes'),
	array('Nyasaland','Mozambique','No','Yes'),
	array('Cambodia','Saigon','Yes','Yes'),
	array('Cambodia','Gulf of Siam','Yes','No'),
	array('Cambodia','Bangkok','No','Yes'),
	array('Cambodia','Bangkok (East Coast)','Yes','No'),
	array('Saigon','Gulf of Siam','Yes','No'),
	array('Saigon','South China Sea','Yes','No'),
	array('Angola','Namibia','Yes','Yes'),
	array('Angola','Rhodesia','No','Yes'),
	array('Angola','Bechuanaland','No','Yes'),
	array('Angola','South Atlantic','Yes','No'),
	array('Namibia','Bechuanaland','No','Yes'),
	array('Namibia','Beaufort','No','Yes'),
	array('Namibia','Cape Town','Yes','Yes'),
	array('Namibia','South Atlantic','Yes','No'),
	array('Ceylon','Gulf of Manaar','Yes','No'),
	array('Ceylon','Bay of Bengal','Yes','No'),
	array('Manila','Cebu','Yes','Yes'),
	array('Manila','Philippine Sea','Yes','No'),
	array('Manila','South China Sea','Yes','No'),
	array('Cebu','Davao','Yes','Yes'),
	array('Cebu','Philippine Sea','Yes','No'),
	array('Cebu','Celebes Sea','Yes','No'),
	array('Cebu','Sulu Sea','Yes','No'),
	array('Cebu','South China Sea','Yes','No'),
	array('Malaysia','Singapore','Yes','Yes'),
	array('Malaysia','Gulf of Siam','Yes','No'),
	array('Malaysia','Andaman Sea','Yes','No'),
	array('Malaysia','Java Sea','Yes','No'),
	array('Malaysia','Bangkok','No','Yes'),
	array('Malaysia','Bangkok (East Coast)','Yes','No'),
	array('Malaysia','Bangkok (West Coast)','Yes','No'),
	array('Davao','Philippine Sea','Yes','No'),
	array('Davao','Celebes Sea','Yes','No'),
	array('Davao','Sulu Sea','Yes','No'),
	array('Sarawak','Borneo','Yes','Yes'),
	array('Sarawak','Celebes Sea','Yes','No'),
	array('Sarawak','Sulu Sea','Yes','No'),
	array('Sarawak','Java Sea','Yes','No'),
	array('Borneo','Celebes Sea','Yes','No'),
	array('Borneo','Java Sea','Yes','No'),
	array('Sumatra','Java','Yes','Yes'),
	array('Sumatra','Gulf of Manaar','Yes','No'),
	array('Sumatra','East Indian','Yes','No'),
	array('Sumatra','Andaman Sea','Yes','No'),
	array('Sumatra','Java Sea','Yes','No'),
	array('Andaman Islands','Gulf of Manaar','Yes','No'),
	array('Andaman Islands','Andaman Sea','Yes','No'),
	array('Andaman Islands','Bay of Bengal','Yes','No'),
	array('Rhodesia','Bechuanaland','No','Yes'),
	array('Rhodesia','Mozambique','No','Yes'),
	array('Bechuanaland','Mozambique','No','Yes'),
	array('Bechuanaland','Transvaal','No','Yes'),
	array('Bechuanaland','Beaufort','No','Yes'),
	array('Mozambique','Transvaal','Yes','Yes'),
	array('Mozambique','Mozambique Channel','Yes','No'),
	array('Madagascar','Cape of Good Hope','Yes','No'),
	array('Madagascar','Horn of Africa','Yes','No'),
	array('Madagascar','West Indian','Yes','No'),
	array('Madagascar','Southwest Indian','Yes','No'),
	array('Madagascar','Mozambique Channel','Yes','No'),
	array('Transvaal','Beaufort','Yes','Yes'),
	array('Transvaal','Cape of Good Hope','Yes','No'),
	array('Transvaal','Mozambique Channel','Yes','No'),
	array('Beaufort','Cape Town','Yes','Yes'),
	array('Beaufort','Cape of Good Hope','Yes','No'),
	array('Cape Town','South Atlantic','Yes','No'),
	array('Cape Town','Cape of Good Hope','Yes','No'),
	array('Maldives','North Indian','Yes','No'),
	array('Maldives','West Indian','Yes','No'),
	array('Maldives','Gulf of Manaar','Yes','No'),
	array('Seychelles','Horn of Africa','Yes','No'),
	array('Seychelles','North Indian','Yes','No'),
	array('Seychelles','West Indian','Yes','No'),
	array('Mauritius','West Indian','Yes','No'),
	array('Mauritius','Southwest Indian','Yes','No'),
	array('Singapore','Java Sea','Yes','No'),
	array('Java','East Indian','Yes','No'),
	array('Java','Java Sea','Yes','No'),
	array('Java','Timor Sea','Yes','No'),
	array('Celebes','Celebes Sea','Yes','No'),
	array('Celebes','Java Sea','Yes','No'),
	array('Celebes','Timor Sea','Yes','No'),
	array('Iriam Java','New Guinea','Yes','Yes'),
	array('Iriam Java','Wilhelmsland','Yes','Yes'),
	array('Iriam Java','Celebes Sea','Yes','No'),
	array('Iriam Java','Timor Sea','Yes','No'),
	array('New Guinea','Wilhelmsland','Yes','Yes'),
	array('New Guinea','Central Pacific','Yes','No'),
	array('New Guinea','South Pacific','Yes','No'),
	array('New Guinea','Timor Sea','Yes','No'),
	array('Wilhelmsland','Celebes Sea','Yes','No'),
	array('Wilhelmsland','Central Pacific','Yes','No'),
	array('Western Australia','Northern Territory','Yes','Yes'),
	array('Western Australia','South Australia','Yes','Yes'),
	array('Western Australia','East Indian','Yes','No'),
	array('Western Australia','Southeast Indian','Yes','No'),
	array('Western Australia','Tasman Sea','Yes','No'),
	array('New South Wales','Queensland','Yes','Yes'),
	array('New South Wales','South Australia','Yes','Yes'),
	array('New South Wales','Tasman Sea','Yes','No'),
	array('Northern Territory','Queensland','Yes','Yes'),
	array('Northern Territory','South Australia','No','Yes'),
	array('Northern Territory','East Indian','Yes','No'),
	array('Northern Territory','Timor Sea','Yes','No'),
	array('Queensland','South Australia','No','Yes'),
	array('Queensland','South Pacific','Yes','No'),
	array('Queensland','Tasman Sea','Yes','No'),
	array('Queensland','Timor Sea','Yes','No'),
	array('South Australia','Tasman Sea','Yes','No'),
	array('Barents Sea','Norwegian Sea','Yes','No'),
	array('Norwegian Sea','North Passage','Yes','No'),
	array('Norwegian Sea','North Sea','Yes','No'),
	array('Norwegian Sea','Greenland','Yes','No'),
	array('North Passage','Irish Sea','Yes','No'),
	array('North Passage','Bay of Biscay','Yes','No'),
	array('North Passage','North Atlantic','Yes','No'),
	array('North Passage','Greenland','Yes','No'),
	array('North Sea','English Channel','Yes','No'),
	array('North Sea','Helgoland Bight','Yes','No'),
	array('North Sea','Skagerrak','Yes','No'),
	array('Irish Sea','English Channel','Yes','No'),
	array('Irish Sea','Bay of Biscay','Yes','No'),
	array('English Channel','Bay of Biscay','Yes','No'),
	array('Bay of Biscay','North Atlantic','Yes','No'),
	array('North Atlantic','Mid Atlantic','Yes','No'),
	array('North Atlantic','Canaries','Yes','No'),
	array('North Atlantic','West Mediterranean','Yes','No'),
	array('Mid Atlantic','Canaries','Yes','No'),
	array('Mid Atlantic','Gulf of Guinea','Yes','No'),
	array('Mid Atlantic','South Atlantic','Yes','No'),
	array('Mid Atlantic','West Southern Ocean','Yes','No'),
	array('Skagerrak','Baltic Sea','Yes','No'),
	array('Baltic Sea','Gulf of Bothnia','Yes','No'),
	array('Baltic Sea','Posen','Yes','No'),
	array('West Mediterranean','Gulf of Lyon','Yes','No'),
	array('West Mediterranean','Tyrrhenian Sea','Yes','No'),
	array('Gulf of Lyon','Tyrrhenian Sea','Yes','No'),
	array('Tyrrhenian Sea','Ionian Sea','Yes','No'),
	array('Adriatic Sea','Ionian Sea','Yes','No'),
	array('Ionian Sea','Aegean Sea','Yes','No'),
	array('Ionian Sea','East Mediterranean','Yes','No'),
	array('Black Sea','Tiflis','Yes','No'),
	array('Black Sea','Tsaritsyn (West Coast)','Yes','No'),
	array('Aegean Sea','East Mediterranean','Yes','No'),
	array('Red Sea','Gulf of Aden','Yes','No'),
	array('Gulf of Guinea','South Atlantic','Yes','No'),
	array('South Atlantic','West Southern Ocean','Yes','No'),
	array('South Atlantic','Cape of Good Hope','Yes','No'),
	array('West Southern Ocean','East Southern Ocean','Yes','No'),
	array('West Southern Ocean','Cape of Good Hope','Yes','No'),
	array('East Southern Ocean','Cape of Good Hope','Yes','No'),
	array('East Southern Ocean','Southwest Indian','Yes','No'),
	array('East Southern Ocean','Southeast Indian','Yes','No'),
	array('East Southern Ocean','Tasman Sea','Yes','No'),
	array('Cape of Good Hope','Southwest Indian','Yes','No'),
	array('Cape of Good Hope','Mozambique Channel','Yes','No'),
	array('Horn of Africa','Gulf of Aden','Yes','No'),
	array('Horn of Africa','North Indian','Yes','No'),
	array('Horn of Africa','West Indian','Yes','No'),
	array('Horn of Africa','Mozambique Channel','Yes','No'),
	array('Persian Gulf','Arabian Sea','Yes','No'),
	array('Persian Gulf','Arabia (North Coast)','Yes','No'),
	array('Arabian Sea','Gulf of Aden','Yes','No'),
	array('Arabian Sea','North Indian','Yes','No'),
	array('Gulf of Aden','North Indian','Yes','No'),
	array('Gulf of Aden','Arabia (South Coast)','Yes','No'),
	array('North Indian','West Indian','Yes','No'),
	array('North Indian','Gulf of Manaar','Yes','No'),
	array('West Indian','Southwest Indian','Yes','No'),
	array('West Indian','Gulf of Manaar','Yes','No'),
	array('West Indian','East Indian','Yes','No'),
	array('Southwest Indian','East Indian','Yes','No'),
	array('Southwest Indian','Southeast Indian','Yes','No'),
	array('Gulf of Manaar','East Indian','Yes','No'),
	array('Gulf of Manaar','Andaman Sea','Yes','No'),
	array('Gulf of Manaar','Bay of Bengal','Yes','No'),
	array('East Indian','Southeast Indian','Yes','No'),
	array('East Indian','Java Sea','Yes','No'),
	array('East Indian','Timor Sea','Yes','No'),
	array('Southeast Indian','Tasman Sea','Yes','No'),
	array('New Zealand','South Pacific','Yes','No'),
	array('New Zealand','Tasman Sea','Yes','No'),
	array('Sea of Okhotsk','Sea of Japan','Yes','No'),
	array('Sea of Okhotsk','North Pacific','Yes','No'),
	array('Sea of Japan','East China Sea','Yes','No'),
	array('Sea of Japan','Seoul (East Coast)','Yes','No'),
	array('North Pacific','Philippine Sea','Yes','No'),
	array('North Pacific','Central Pacific','Yes','No'),
	array('Yellow Sea','East China Sea','Yes','No'),
	array('Yellow Sea','Seoul (West Coast)','Yes','No'),
	array('Yellow Sea','Mukden','Yes','No'),
	array('East China Sea','Philippine Sea','Yes','No'),
	array('East China Sea','South China Sea','Yes','No'),
	array('East China Sea','Canton (East Coast)','Yes','No'),
	array('Philippine Sea','Celebes Sea','Yes','No'),
	array('Philippine Sea','Central Pacific','Yes','No'),
	array('Philippine Sea','South China Sea','Yes','No'),
	array('Celebes Sea','Central Pacific','Yes','No'),
	array('Celebes Sea','Sulu Sea','Yes','No'),
	array('Celebes Sea','Java Sea','Yes','No'),
	array('Celebes Sea','Timor Sea','Yes','No'),
	array('Central Pacific','South Pacific','Yes','No'),
	array('South Pacific','Tasman Sea','Yes','No'),
	array('South Pacific','Timor Sea','Yes','No'),
	array('Sulu Sea','Gulf of Siam','Yes','No'),
	array('Sulu Sea','South China Sea','Yes','No'),
	array('Sulu Sea','Java Sea','Yes','No'),
	array('Gulf of Siam','South China Sea','Yes','No'),
	array('Gulf of Siam','Java Sea','Yes','No'),
	array('Gulf of Siam','Bangkok (East Coast)','Yes','No'),
	array('South China Sea','Canton (West Coast)','Yes','No'),
	array('Andaman Sea','Bay of Bengal','Yes','No'),
	array('Andaman Sea','Java Sea','Yes','No'),
	array('Andaman Sea','Bangkok (West Coast)','Yes','No'),
	array('Java Sea','Timor Sea','Yes','No'),
	array('Posen','Silesia','No','Yes'),
	array('Tsaritsyn (East Coast)','Caspian Sea','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
