<?php
// This is file installs the map data for the Duo variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Norterend', 'Land', 'Yes', 3, 445, 470, 250, 240),
	array('Westberg', 'Land', 'Yes', 3, 518, 525, 270, 280),
	array('Ostberg', 'Land', 'Yes', 3, 675, 525, 350, 270),
	array('Sund', 'Land', 'Yes', 3, 748, 579, 390, 302),
	array('Helom', 'Coast', 'Yes', 3, 911, 58, 475, 30),
	array('Nordostmeer', 'Sea', 'No', 0, 1041, 81, 543, 42),
	array('Conno', 'Coast', 'Yes', 0, 1150, 58, 600, 30),
	array('Abaun', 'Coast', 'Yes', 3, 288, 972, 150, 507),
	array('Suedwestmeer', 'Sea', 'No', 0, 173, 970, 90, 500),
	array('Corws', 'Coast', 'Yes', 0, 58, 987, 30, 515),
	array('Pirh', 'Coast', 'Yes', 3, 1020, 665, 535, 350),
	array('Gawar', 'Coast', 'Yes', 3, 173, 374, 90, 195),
	array('Jadestadt', 'Coast', 'Yes', 2, 510, 160, 270, 90),
	array('Schloss Gruenburg', 'Coast', 'Yes', 2, 675, 160, 360, 90),
	array('Gruenheim', 'Land', 'Yes', 2, 645, 255, 330, 125),
	array('Elfland', 'Coast', 'No', 0, 824, 58, 430, 30),
	array('Candolti', 'Coast', 'Yes', 0, 297, 259, 155, 135),
	array('Qualinost', 'Coast', 'No', 0, 383, 182, 200, 95),
	array('Eld', 'Coast', 'No', 0, 872, 201, 455, 105),
	array('Kath', 'Coast', 'Yes', 0, 968, 288, 505, 150),
	array('Riesenheim', 'Coast', 'No', 0, 1035, 416, 540, 217),
	array('Bynn', 'Coast', 'No', 0, 1026, 504, 535, 263),
	array('Bynn (East Coast)', 'Coast', 'No', 0, 1072, 485, 559, 253),
	array('Bynn (West Coast)', 'Coast', 'No', 0, 974, 518, 508, 270),
	array('Gwaul', 'Coast', 'No', 0, 1035, 585, 540, 300),
	array('Gwaul (East Coast)', 'Coast', 'No', 0, 1070, 581, 558, 303),
	array('Gwaul (West Coast)', 'Coast', 'No', 0, 985, 567, 514, 296),
	array('Losteria', 'Coast', 'Yes', 0, 910, 775, 470, 407),
	array('Samyria', 'Coast', 'No', 0, 830, 840, 430, 440),
	array('Karminstadt', 'Coast', 'Yes', 1, 690, 870, 365, 460),
	array('Zinnoberburg', 'Coast', 'Yes', 1, 510, 876, 260, 457),
	array('Rotheim', 'Land', 'Yes', 1, 556, 805, 290, 420),
	array('Ailea', 'Coast', 'No', 0, 320, 830, 170, 437),
	array('Kentommenai', 'Coast', 'Yes', 0, 220, 735, 115, 380),
	array('Verlorenes Land', 'Coast', 'No', 0, 173, 633, 90, 330),
	array('Korbia', 'Coast', 'No', 0, 170, 525, 87, 273),
	array('Korbia (East Coast)', 'Coast', 'No', 0, 225, 510, 115, 260),
	array('Korbia (West Coast)', 'Coast', 'No', 0, 127, 542, 66, 283),
	array('Heronn', 'Coast', 'No', 0, 173, 454, 90, 237),
	array('Heronn (East Coast)', 'Coast', 'No', 0, 211, 456, 110, 238),
	array('Heronn (West Coast)', 'Coast', 'No', 0, 130, 445, 68, 232),
	array('Arkoon', 'Coast', 'Yes', 0, 235, 605, 120, 310),
	array('Charaua', 'Coast', 'No', 0, 307, 690, 160, 360),
	array('Barana', 'Coast', 'No', 0, 415, 671, 220, 350),
	array('Nogk', 'Coast', 'No', 0, 400, 605, 215, 320),
	array('Nabai', 'Coast', 'Yes', 0, 355, 555, 185, 295),
	array('Saphirschlucht', 'Coast', 'No', 0, 326, 479, 170, 250),
	array('Gurand', 'Coast', 'No', 0, 307, 374, 160, 195),
	array('Orlon', 'Coast', 'No', 0, 890, 661, 470, 345),
	array('Obstschlucht', 'Coast', 'No', 0, 872, 565, 455, 295),
	array('Mellar', 'Coast', 'Yes', 0, 834, 479, 435, 250),
	array('Esmaladan', 'Coast', 'No', 0, 770, 450, 410, 223),
	array('Amphi', 'Coast', 'No', 0, 785, 370, 407, 197),
	array('Utar', 'Coast', 'No', 0, 882, 355, 460, 185),
	array('Bridon', 'Coast', 'Yes', 0, 970, 460, 510, 240),
	array('Ornheim', 'Coast', 'No', 0, 374, 968, 195, 505),
	array('Jossangia', 'Land', 'No', 0, 479, 230, 250, 120),
	array('Elchen', 'Land', 'No', 0, 498, 297, 260, 155),
	array('Caraveccia', 'Land', 'No', 0, 773, 255, 403, 133),
	array('Tel', 'Land', 'Yes', 0, 435, 364, 220, 190),
	array('Land der Wiesel', 'Land', 'No', 0, 520, 410, 250, 213),
	array('Nari', 'Land', 'No', 0, 613, 307, 320, 160),
	array('Olk', 'Land', 'No', 0, 661, 355, 345, 185),
	array('Yokai', 'Land', 'Yes', 0, 732, 312, 382, 163),
	array('Hugl', 'Land', 'No', 0, 620, 408, 310, 213),
	array('Wildall', 'Land', 'No', 0, 670, 456, 330, 238),
	array('Skr', 'Land', 'No', 0, 560, 470, 292, 245),
	array('Eun', 'Land', 'No', 0, 636, 552, 332, 288),
	array('Hills', 'Land', 'No', 0, 537, 579, 280, 302),
	array('Urur', 'Land', 'No', 0, 575, 629, 300, 328),
	array('Feuerfeld', 'Land', 'No', 0, 690, 629, 360, 328),
	array('Chapablublek', 'Land', 'No', 0, 518, 695, 270, 355),
	array('Nilldall', 'Land', 'No', 0, 575, 725, 300, 385),
	array('Neu Rom', 'Land', 'Yes', 0, 767, 681, 400, 355),
	array('Qwil', 'Land', 'Yes', 0, 490, 750, 253, 393),
	array('Sottovia', 'Land', 'No', 0, 422, 776, 220, 405),
	array('Kaaldewaa', 'Land', 'No', 0, 719, 734, 375, 383),
	array('Mouchimoglou', 'Land', 'No', 0, 742, 805, 387, 420),
	array('Nordwestmeer', 'Sea', 'No', 0, 81, 67, 42, 35),
	array('Polarmeer', 'Sea', 'No', 0, 479, 35, 250, 18),
	array('Fungali-Meer', 'Sea', 'No', 0, 268, 153, 140, 80),
	array('Cobaltmeer', 'Sea', 'No', 0, 652, 102, 340, 53),
	array('Ozean von Doom', 'Sea', 'No', 0, 1030, 200, 540, 110),
	array('Kamalastrasse', 'Sea', 'No', 0, 1120, 350, 590, 175),
	array('Teisee', 'Sea', 'No', 0, 1135, 465, 595, 248),
	array('Kupferkueste', 'Sea', 'No', 0, 1112, 590, 580, 315),
	array('Altes Meer', 'Sea', 'No', 0, 1169, 671, 610, 350),
	array('Golf von Pirh', 'Sea', 'No', 0, 1077, 748, 562, 390),
	array('Suedostmeer', 'Sea', 'No', 0, 1093, 920, 570, 480),
	array('Smaragt Bucht', 'Sea', 'No', 0, 890, 450, 450, 213),
	array('Bucht des Ostens', 'Sea', 'No', 0, 940, 575, 488, 290),
	array('Rodesion Delta', 'Sea', 'No', 0, 968, 678, 505, 340),
	array('Froidevaux-Meer', 'Sea', 'No', 0, 930, 891, 485, 465),
	array('Daxmeer', 'Sea', 'No', 0, 630, 1015, 305, 525),
	array('Lithiumsee', 'Sea', 'No', 0, 518, 935, 270, 492),
	array('Golf von Ailea', 'Sea', 'No', 0, 138, 845, 72, 435),
	array('Doringkanal', 'Sea', 'No', 0, 80, 715, 38, 360),
	array('Borkmeer', 'Sea', 'No', 0, 61, 565, 32, 290),
	array('Kaltes Meer', 'Sea', 'No', 0, 25, 350, 13, 195),
	array('Golf von Gawan', 'Sea', 'No', 0, 115, 278, 60, 145),
	array('Meer von Uuz', 'Sea', 'No', 0, 86, 450, 45, 225),
	array('Gorkion Delta', 'Sea', 'No', 0, 226, 370, 118, 205),
	array('Mitelgorkion', 'Sea', 'No', 0, 263, 498, 137, 260),
	array('Rotbucht', 'Sea', 'No', 0, 315, 604, 160, 315)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Norterend','Westberg','No','Yes'),
	array('Norterend','Saphirschlucht','No','Yes'),
	array('Norterend','Land der Wiesel','No','Yes'),
	array('Norterend','Hugl','No','Yes'),
	array('Norterend','Wildall','No','Yes'),
	array('Norterend','Skr','No','Yes'),
	array('Westberg','Ostberg','No','Yes'),
	array('Westberg','Skr','No','Yes'),
	array('Westberg','Eun','No','Yes'),
	array('Westberg','Hills','No','Yes'),
	array('Ostberg','Sund','No','Yes'),
	array('Ostberg','Wildall','No','Yes'),
	array('Ostberg','Skr','No','Yes'),
	array('Ostberg','Eun','No','Yes'),
	array('Sund','Obstschlucht','No','Yes'),
	array('Sund','Eun','No','Yes'),
	array('Sund','Hills','No','Yes'),
	array('Sund','Urur','No','Yes'),
	array('Sund','Feuerfeld','No','Yes'),
	array('Helom','Nordostmeer','Yes','No'),
	array('Helom','Elfland','Yes','Yes'),
	array('Helom','Polarmeer','Yes','No'),
	array('Helom','Cobaltmeer','Yes','No'),
	array('Nordostmeer','Conno','Yes','No'),
	array('Nordostmeer','Polarmeer','Yes','No'),
	array('Nordostmeer','Cobaltmeer','Yes','No'),
	array('Nordostmeer','Ozean von Doom','Yes','No'),
	array('Abaun','Suedwestmeer','Yes','No'),
	array('Abaun','Ornheim','Yes','Yes'),
	array('Abaun','Daxmeer','Yes','No'),
	array('Abaun','Lithiumsee','Yes','No'),
	array('Suedwestmeer','Corws','Yes','No'),
	array('Suedwestmeer','Daxmeer','Yes','No'),
	array('Suedwestmeer','Lithiumsee','Yes','No'),
	array('Suedwestmeer','Golf von Ailea','Yes','No'),
	array('Pirh','Gwaul','No','Yes'),
	array('Pirh','Gwaul (East Coast)','Yes','No'),
	array('Pirh','Gwaul (West Coast)','Yes','No'),
	array('Pirh','Orlon','No','Yes'),
	array('Pirh','Golf von Pirh','Yes','No'),
	array('Pirh','Bucht des Ostens','Yes','No'),
	array('Pirh','Rodesion Delta','Yes','No'),
	array('Gawar','Heronn','No','Yes'),
	array('Gawar','Heronn (East Coast)','Yes','No'),
	array('Gawar','Heronn (West Coast)','Yes','No'),
	array('Gawar','Gurand','No','Yes'),
	array('Gawar','Golf von Gawan','Yes','No'),
	array('Gawar','Gorkion Delta','Yes','No'),
	array('Gawar','Mitelgorkion','Yes','No'),
	array('Jadestadt','Schloss Gruenburg','Yes','Yes'),
	array('Jadestadt','Qualinost','Yes','Yes'),
	array('Jadestadt','Jossangia','No','Yes'),
	array('Jadestadt','Fungali-Meer','Yes','No'),
	array('Jadestadt','Cobaltmeer','Yes','No'),
	array('Schloss Gruenburg','Gruenheim','No','Yes'),
	array('Schloss Gruenburg','Eld','Yes','Yes'),
	array('Schloss Gruenburg','Jossangia','No','Yes'),
	array('Schloss Gruenburg','Caraveccia','No','Yes'),
	array('Schloss Gruenburg','Cobaltmeer','Yes','No'),
	array('Schloss Gruenburg','Ozean von Doom','Yes','No'),
	array('Gruenheim','Jossangia','No','Yes'),
	array('Gruenheim','Elchen','No','Yes'),
	array('Gruenheim','Caraveccia','No','Yes'),
	array('Gruenheim','Nari','No','Yes'),
	array('Gruenheim','Yokai','No','Yes'),
	array('Elfland','Polarmeer','Yes','No'),
	array('Elfland','Cobaltmeer','Yes','No'),
	array('Candolti','Qualinost','Yes','Yes'),
	array('Candolti','Gurand','Yes','Yes'),
	array('Candolti','Jossangia','No','Yes'),
	array('Candolti','Elchen','No','Yes'),
	array('Candolti','Fungali-Meer','Yes','No'),
	array('Candolti','Gorkion Delta','Yes','No'),
	array('Qualinost','Jossangia','No','Yes'),
	array('Qualinost','Fungali-Meer','Yes','No'),
	array('Eld','Kath','Yes','Yes'),
	array('Eld','Utar','No','Yes'),
	array('Eld','Caraveccia','No','Yes'),
	array('Eld','Ozean von Doom','Yes','No'),
	array('Kath','Riesenheim','Yes','Yes'),
	array('Kath','Utar','No','Yes'),
	array('Kath','Ozean von Doom','Yes','No'),
	array('Kath','Kamalastrasse','Yes','No'),
	array('Riesenheim','Bynn','No','Yes'),
	array('Riesenheim','Bynn (East Coast)','Yes','No'),
	array('Riesenheim','Utar','No','Yes'),
	array('Riesenheim','Bridon','No','Yes'),
	array('Riesenheim','Kamalastrasse','Yes','No'),
	array('Riesenheim','Teisee','Yes','No'),
	array('Bynn','Gwaul','No','Yes'),
	array('Bynn','Bridon','No','Yes'),
	array('Bynn (East Coast)','Gwaul (East Coast)','Yes','No'),
	array('Bynn (East Coast)','Teisee','Yes','No'),
	array('Bynn (East Coast)','Kupferkueste','Yes','No'),
	array('Bynn (West Coast)','Gwaul (West Coast)','Yes','No'),
	array('Bynn (West Coast)','Bridon','Yes','No'),
	array('Bynn (West Coast)','Bucht des Ostens','Yes','No'),
	array('Gwaul (East Coast)','Kupferkueste','Yes','No'),
	array('Gwaul (East Coast)','Golf von Pirh','Yes','No'),
	array('Gwaul (West Coast)','Bucht des Ostens','Yes','No'),
	array('Losteria','Samyria','Yes','Yes'),
	array('Losteria','Orlon','Yes','Yes'),
	array('Losteria','Kaaldewaa','No','Yes'),
	array('Losteria','Mouchimoglou','No','Yes'),
	array('Losteria','Rodesion Delta','Yes','No'),
	array('Losteria','Froidevaux-Meer','Yes','No'),
	array('Samyria','Karminstadt','Yes','Yes'),
	array('Samyria','Mouchimoglou','No','Yes'),
	array('Samyria','Froidevaux-Meer','Yes','No'),
	array('Karminstadt','Zinnoberburg','Yes','Yes'),
	array('Karminstadt','Mouchimoglou','No','Yes'),
	array('Karminstadt','Froidevaux-Meer','Yes','No'),
	array('Karminstadt','Lithiumsee','Yes','No'),
	array('Zinnoberburg','Rotheim','No','Yes'),
	array('Zinnoberburg','Ailea','Yes','Yes'),
	array('Zinnoberburg','Sottovia','No','Yes'),
	array('Zinnoberburg','Mouchimoglou','No','Yes'),
	array('Zinnoberburg','Lithiumsee','Yes','No'),
	array('Zinnoberburg','Golf von Ailea','Yes','No'),
	array('Rotheim','Nilldall','No','Yes'),
	array('Rotheim','Qwil','No','Yes'),
	array('Rotheim','Sottovia','No','Yes'),
	array('Rotheim','Kaaldewaa','No','Yes'),
	array('Rotheim','Mouchimoglou','No','Yes'),
	array('Ailea','Kentommenai','Yes','Yes'),
	array('Ailea','Charaua','No','Yes'),
	array('Ailea','Sottovia','No','Yes'),
	array('Ailea','Golf von Ailea','Yes','No'),
	array('Kentommenai','Verlorenes Land','Yes','Yes'),
	array('Kentommenai','Charaua','No','Yes'),
	array('Kentommenai','Golf von Ailea','Yes','No'),
	array('Kentommenai','Doringkanal','Yes','No'),
	array('Verlorenes Land','Korbia','No','Yes'),
	array('Verlorenes Land','Korbia (West Coast)','Yes','No'),
	array('Verlorenes Land','Arkoon','No','Yes'),
	array('Verlorenes Land','Charaua','No','Yes'),
	array('Verlorenes Land','Doringkanal','Yes','No'),
	array('Verlorenes Land','Borkmeer','Yes','No'),
	array('Korbia','Heronn','No','Yes'),
	array('Korbia','Arkoon','No','Yes'),
	array('Korbia (East Coast)','Heronn (East Coast)','Yes','No'),
	array('Korbia (East Coast)','Arkoon','Yes','No'),
	array('Korbia (East Coast)','Mitelgorkion','Yes','No'),
	array('Korbia (West Coast)','Heronn (West Coast)','Yes','No'),
	array('Korbia (West Coast)','Borkmeer','Yes','No'),
	array('Korbia (West Coast)','Meer von Uuz','Yes','No'),
	array('Heronn (East Coast)','Mitelgorkion','Yes','No'),
	array('Heronn (West Coast)','Golf von Gawan','Yes','No'),
	array('Heronn (West Coast)','Meer von Uuz','Yes','No'),
	array('Arkoon','Charaua','Yes','Yes'),
	array('Arkoon','Nabai','No','Yes'),
	array('Arkoon','Mitelgorkion','Yes','No'),
	array('Arkoon','Rotbucht','Yes','No'),
	array('Charaua','Barana','Yes','Yes'),
	array('Charaua','Nogk','No','Yes'),
	array('Charaua','Sottovia','No','Yes'),
	array('Charaua','Rotbucht','Yes','No'),
	array('Barana','Nogk','Yes','Yes'),
	array('Barana','Urur','No','Yes'),
	array('Barana','Chapablublek','No','Yes'),
	array('Barana','Qwil','No','Yes'),
	array('Barana','Sottovia','No','Yes'),
	array('Barana','Rotbucht','Yes','No'),
	array('Nogk','Nabai','Yes','Yes'),
	array('Nogk','Hills','No','Yes'),
	array('Nogk','Urur','No','Yes'),
	array('Nogk','Rotbucht','Yes','No'),
	array('Nabai','Saphirschlucht','Yes','Yes'),
	array('Nabai','Hills','No','Yes'),
	array('Nabai','Mitelgorkion','Yes','No'),
	array('Nabai','Rotbucht','Yes','No'),
	array('Saphirschlucht','Gurand','Yes','Yes'),
	array('Saphirschlucht','Land der Wiesel','No','Yes'),
	array('Saphirschlucht','Mitelgorkion','Yes','No'),
	array('Gurand','Elchen','No','Yes'),
	array('Gurand','Tel','No','Yes'),
	array('Gurand','Land der Wiesel','No','Yes'),
	array('Gurand','Gorkion Delta','Yes','No'),
	array('Gurand','Mitelgorkion','Yes','No'),
	array('Orlon','Obstschlucht','Yes','Yes'),
	array('Orlon','Feuerfeld','No','Yes'),
	array('Orlon','Neu Rom','No','Yes'),
	array('Orlon','Kaaldewaa','No','Yes'),
	array('Orlon','Bucht des Ostens','Yes','No'),
	array('Orlon','Rodesion Delta','Yes','No'),
	array('Obstschlucht','Mellar','Yes','Yes'),
	array('Obstschlucht','Feuerfeld','No','Yes'),
	array('Obstschlucht','Bucht des Ostens','Yes','No'),
	array('Mellar','Esmaladan','Yes','Yes'),
	array('Mellar','Bridon','No','Yes'),
	array('Mellar','Wildall','No','Yes'),
	array('Mellar','Smaragt Bucht','Yes','No'),
	array('Mellar','Bucht des Ostens','Yes','No'),
	array('Esmaladan','Amphi','Yes','Yes'),
	array('Esmaladan','Utar','No','Yes'),
	array('Esmaladan','Hugl','No','Yes'),
	array('Esmaladan','Wildall','No','Yes'),
	array('Esmaladan','Smaragt Bucht','Yes','No'),
	array('Amphi','Utar','Yes','Yes'),
	array('Amphi','Caraveccia','No','Yes'),
	array('Amphi','Olk','No','Yes'),
	array('Amphi','Yokai','No','Yes'),
	array('Amphi','Hugl','No','Yes'),
	array('Amphi','Smaragt Bucht','Yes','No'),
	array('Utar','Bridon','Yes','Yes'),
	array('Utar','Caraveccia','No','Yes'),
	array('Utar','Smaragt Bucht','Yes','No'),
	array('Bridon','Smaragt Bucht','Yes','No'),
	array('Bridon','Bucht des Ostens','Yes','No'),
	array('Ornheim','Daxmeer','Yes','No'),
	array('Ornheim','Lithiumsee','Yes','No'),
	array('Jossangia','Elchen','No','Yes'),
	array('Elchen','Tel','No','Yes'),
	array('Elchen','Nari','No','Yes'),
	array('Caraveccia','Yokai','No','Yes'),
	array('Tel','Land der Wiesel','No','Yes'),
	array('Tel','Nari','No','Yes'),
	array('Tel','Olk','No','Yes'),
	array('Land der Wiesel','Olk','No','Yes'),
	array('Land der Wiesel','Hugl','No','Yes'),
	array('Nari','Olk','No','Yes'),
	array('Nari','Yokai','No','Yes'),
	array('Olk','Yokai','No','Yes'),
	array('Olk','Hugl','No','Yes'),
	array('Hugl','Wildall','No','Yes'),
	array('Wildall','Skr','No','Yes'),
	array('Eun','Hills','No','Yes'),
	array('Hills','Urur','No','Yes'),
	array('Urur','Feuerfeld','No','Yes'),
	array('Urur','Chapablublek','No','Yes'),
	array('Feuerfeld','Chapablublek','No','Yes'),
	array('Feuerfeld','Neu Rom','No','Yes'),
	array('Chapablublek','Nilldall','No','Yes'),
	array('Chapablublek','Neu Rom','No','Yes'),
	array('Chapablublek','Qwil','No','Yes'),
	array('Nilldall','Neu Rom','No','Yes'),
	array('Nilldall','Qwil','No','Yes'),
	array('Nilldall','Kaaldewaa','No','Yes'),
	array('Neu Rom','Kaaldewaa','No','Yes'),
	array('Qwil','Sottovia','No','Yes'),
	array('Kaaldewaa','Mouchimoglou','No','Yes'),
	array('Nordwestmeer','Polarmeer','Yes','No'),
	array('Nordwestmeer','Fungali-Meer','Yes','No'),
	array('Nordwestmeer','Kaltes Meer','Yes','No'),
	array('Nordwestmeer','Golf von Gawan','Yes','No'),
	array('Polarmeer','Fungali-Meer','Yes','No'),
	array('Polarmeer','Cobaltmeer','Yes','No'),
	array('Fungali-Meer','Cobaltmeer','Yes','No'),
	array('Fungali-Meer','Golf von Gawan','Yes','No'),
	array('Fungali-Meer','Gorkion Delta','Yes','No'),
	array('Cobaltmeer','Ozean von Doom','Yes','No'),
	array('Ozean von Doom','Kamalastrasse','Yes','No'),
	array('Kamalastrasse','Teisee','Yes','No'),
	array('Teisee','Kupferkueste','Yes','No'),
	array('Teisee','Altes Meer','Yes','No'),
	array('Kupferkueste','Altes Meer','Yes','No'),
	array('Kupferkueste','Golf von Pirh','Yes','No'),
	array('Altes Meer','Golf von Pirh','Yes','No'),
	array('Altes Meer','Suedostmeer','Yes','No'),
	array('Golf von Pirh','Suedostmeer','Yes','No'),
	array('Golf von Pirh','Rodesion Delta','Yes','No'),
	array('Golf von Pirh','Froidevaux-Meer','Yes','No'),
	array('Suedostmeer','Froidevaux-Meer','Yes','No'),
	array('Suedostmeer','Daxmeer','Yes','No'),
	array('Smaragt Bucht','Bucht des Ostens','Yes','No'),
	array('Bucht des Ostens','Rodesion Delta','Yes','No'),
	array('Rodesion Delta','Froidevaux-Meer','Yes','No'),
	array('Froidevaux-Meer','Daxmeer','Yes','No'),
	array('Froidevaux-Meer','Lithiumsee','Yes','No'),
	array('Daxmeer','Lithiumsee','Yes','No'),
	array('Lithiumsee','Golf von Ailea','Yes','No'),
	array('Golf von Ailea','Doringkanal','Yes','No'),
	array('Doringkanal','Borkmeer','Yes','No'),
	array('Borkmeer','Kaltes Meer','Yes','No'),
	array('Borkmeer','Meer von Uuz','Yes','No'),
	array('Kaltes Meer','Golf von Gawan','Yes','No'),
	array('Kaltes Meer','Meer von Uuz','Yes','No'),
	array('Golf von Gawan','Meer von Uuz','Yes','No'),
	array('Golf von Gawan','Gorkion Delta','Yes','No'),
	array('Gorkion Delta','Mitelgorkion','Yes','No'),
	array('Mitelgorkion','Rotbucht','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
