<?php

require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Norterend'          , 'Land' , 'Yes', 445, 470,250,240, 'Black'  ),
	array('Westberg'           , 'Land' , 'Yes', 518, 525,270,280, 'Black'  ),
	array('Ostberg'            , 'Land' , 'Yes', 675, 525,350,270, 'Black'  ),
	array('Sund'               , 'Land' , 'Yes', 748, 579,390,302, 'Black'  ),
	array('Helom'              , 'Coast', 'Yes', 911,  58,475, 30, 'Black'  ),
	array('Nordostmeer'        , 'Sea'  , 'No' ,1041,  81,543, 42, 'Neutral'),
	array('Conno'              , 'Coast', 'Yes',1150,  58,600, 30, 'Neutral'),
	array('Abaun'              , 'Coast', 'Yes', 288, 972,150,507, 'Black'  ),
	array('Suedwestmeer'       , 'Sea'  , 'No' , 173, 970, 90,500, 'Neutral'),
	array('Corws'              , 'Coast', 'Yes',  58, 987, 30,515, 'Neutral'),
	array('Pirh'               , 'Coast', 'Yes',1020, 665,535,350, 'Black'  ),
	array('Gawar'              , 'Coast', 'Yes', 173, 374, 90,195, 'Black'  ),
	array('Jadestadt'          , 'Coast', 'Yes', 510, 160,270, 90, 'Green'  ),
	array('Schloss Gruenburg'  , 'Coast', 'Yes', 675, 160,360, 90, 'Green'  ),
	array('Gruenheim'          , 'Land' , 'Yes', 645, 255,330,125, 'Green'  ),
	array('Elfland'            , 'Coast', 'No' , 824,  58,430, 30, 'Neutral'),
	array('Candolti'           , 'Coast', 'Yes', 297, 259,155,135, 'Neutral'),
	array('Qualinost'          , 'Coast', 'No' , 383, 182,200, 95, 'Neutral'),
	array('Eld'                , 'Coast', 'No' , 872, 201,455,105, 'Neutral'),
	array('Kath'               , 'Coast', 'Yes', 968, 288,505,150, 'Neutral'),
	array('Riesenheim'         , 'Coast', 'No' ,1035, 416,540,217, 'Neutral'),
	array('Bynn'               , 'Coast', 'No' ,1026, 504,535,263, 'Neutral'),
	array('Bynn (East Coast)'  , 'Coast', 'No' ,1072, 485,559,253, 'Neutral'),
	array('Bynn (West Coast)'  , 'Coast', 'No' , 974, 518,508,270, 'Neutral'),
	array('Gwaul'              , 'Coast', 'No' ,1035, 585,540,300, 'Neutral'),
	array('Gwaul (East Coast)' , 'Coast', 'No' ,1070, 581,558,303, 'Neutral'),
	array('Gwaul (West Coast)' , 'Coast', 'No' , 985, 567,514,296, 'Neutral'),
	array('Losteria'           , 'Coast', 'Yes', 910, 775,470,407, 'Neutral'),
	array('Samyria'            , 'Coast', 'No' , 830, 840,430,440, 'Neutral'),
	array('Karminstadt'        , 'Coast', 'Yes', 690, 870,365,460, 'Red'    ),
	array('Zinnoberburg'       , 'Coast', 'Yes', 510, 876,260,457, 'Red'    ),
	array('Rotheim'            , 'Land' , 'Yes', 556, 805,290,420, 'Red'    ),
	array('Ailea'              , 'Coast', 'No' , 320, 830,170,437, 'Neutral'),
	array('Kentommenai'        , 'Coast', 'Yes', 220, 735,115,380, 'Neutral'),
	array('Verlorenes Land'    , 'Coast', 'No' , 173, 633, 90,330, 'Neutral'),
	array('Korbia'             , 'Coast', 'No' , 170, 525, 87,273, 'Neutral'),
	array('Korbia (East Coast)', 'Coast', 'No' , 225, 510,115,260, 'Neutral'),
	array('Korbia (West Coast)', 'Coast', 'No' , 127, 542, 66,283, 'Neutral'),
	array('Heronn'             , 'Coast', 'No' , 173, 454, 90,237, 'Neutral'),
	array('Heronn (East Coast)', 'Coast', 'No' , 211, 456,110,238, 'Neutral'),
	array('Heronn (West Coast)', 'Coast', 'No' , 130, 445, 68,232, 'Neutral'),
	array('Arkoon'             , 'Coast', 'Yes', 235, 605,120,310, 'Neutral'),
	array('Charaua'            , 'Coast', 'No' , 307, 690,160,360, 'Neutral'),
	array('Barana'             , 'Coast', 'No' , 415, 671,220,350, 'Neutral'),
	array('Nogk'               , 'Coast', 'No' , 400, 605,215,320, 'Neutral'),
	array('Nabai'              , 'Coast', 'Yes', 355, 555,185,295, 'Neutral'),
	array('Saphirschlucht'     , 'Coast', 'No' , 326, 479,170,250, 'Neutral'),
	array('Gurand'             , 'Coast', 'No' , 307, 374,160,195, 'Neutral'),
	array('Orlon'              , 'Coast', 'No' , 890, 661,470,345, 'Neutral'),
	array('Obstschlucht'       , 'Coast', 'No' , 872, 565,455,295, 'Neutral'),
	array('Mellar'             , 'Coast', 'Yes', 834, 479,435,250, 'Neutral'),
	array('Esmaladan'          , 'Coast', 'No' , 770, 450,410,223, 'Neutral'),
	array('Amphi'              , 'Coast', 'No' , 785, 370,407,197, 'Neutral'),
	array('Utar'               , 'Coast', 'No' , 882, 355,460,185, 'Neutral'),
	array('Bridon'             , 'Coast', 'Yes', 970, 460,510,240, 'Neutral'),
	array('Ornheim'            , 'Coast', 'No' , 374, 968,195,505, 'Neutral'),
	array('Jossangia'          , 'Land' , 'No' , 479, 230,250,120, 'Neutral'),
	array('Elchen'             , 'Land' , 'No' , 498, 297,260,155, 'Neutral'),
	array('Caraveccia'         , 'Land' , 'No' , 773, 255,403,133, 'Neutral'),
	array('Tel'                , 'Land' , 'Yes', 435, 364,220,190, 'Neutral'),
	array('Land der Wiesel'    , 'Land' , 'No' , 520, 410,250,213, 'Neutral'),
	array('Nari'               , 'Land' , 'No' , 613, 307,320,160, 'Neutral'),
	array('Olk'                , 'Land' , 'No' , 661, 355,345,185, 'Neutral'),
	array('Yokai'              , 'Land' , 'Yes', 732, 312,382,163, 'Neutral'),
	array('Hugl'               , 'Land' , 'No' , 620, 408,310,213, 'Neutral'),
	array('Wildall'            , 'Land' , 'No' , 670, 456,330,238, 'Neutral'),
	array('Skr'                , 'Land' , 'No' , 560, 470,292,245, 'Neutral'),
	array('Eun'                , 'Land' , 'No' , 636, 552,332,288, 'Neutral'),
	array('Hills'              , 'Land' , 'No' , 537, 579,280,302, 'Neutral'),
	array('Urur'               , 'Land' , 'No' , 575, 629,300,328, 'Neutral'),
	array('Feuerfeld'          , 'Land' , 'No' , 690, 629,360,328, 'Neutral'),
	array('Chapablublek'       , 'Land' , 'No' , 518, 695,270,355, 'Neutral'),
	array('Nilldall'           , 'Land' , 'No' , 575, 725,300,385, 'Neutral'),
	array('Neu Rom'            , 'Land' , 'Yes', 767, 681,400,355, 'Neutral'),
	array('Qwil'               , 'Land' , 'Yes', 490, 750,253,393, 'Neutral'),
	array('Sottovia'           , 'Land' , 'No' , 422, 776,220,405, 'Neutral'),
	array('Kaaldewaa'          , 'Land' , 'No' , 719, 734,375,383, 'Neutral'),
	array('Mouchimoglou'       , 'Land' , 'No' , 742, 805,387,420, 'Neutral'),
	array('Nordwestmeer'       , 'Sea'  , 'No' ,  81,  67, 42, 35, 'Neutral'),
	array('Polarmeer'          , 'Sea'  , 'No' , 479,  35,250, 18, 'Neutral'),
	array('Fungali-Meer'       , 'Sea'  , 'No' , 268, 153,140, 80, 'Neutral'),
	array('Cobaltmeer'         , 'Sea'  , 'No' , 652, 102,340, 53, 'Neutral'),
	array('Ozean von Doom'     , 'Sea'  , 'No' ,1030, 200,540,110, 'Neutral'),
	array('Kamalastrasse'      , 'Sea'  , 'No' ,1120, 350,590,175, 'Neutral'),
	array('Teisee'             , 'Sea'  , 'No' ,1135, 465,595,248, 'Neutral'),
	array('Kupferkueste'       , 'Sea'  , 'No' ,1112, 590,580,315, 'Neutral'),
	array('Altes Meer'         , 'Sea'  , 'No' ,1169, 671,610,350, 'Neutral'),
	array('Golf von Pirh'      , 'Sea'  , 'No' ,1077, 748,562,390, 'Neutral'),
	array('Suedostmeer'        , 'Sea'  , 'No' ,1093, 920,570,480, 'Neutral'),
	array('Smaragt Bucht'      , 'Sea'  , 'No' , 890, 450,450,213, 'Neutral'),
	array('Bucht des Ostens'   , 'Sea'  , 'No' , 940, 575,488,290, 'Neutral'),
	array('Rodesion Delta'     , 'Sea'  , 'No' , 968, 678,505,340, 'Neutral'),
	array('Froidevaux-Meer'    , 'Sea'  , 'No' , 930, 891,485,465, 'Neutral'),
	array('Daxmeer'            , 'Sea'  , 'No' , 630,1015,305,525, 'Neutral'),
	array('Lithiumsee'         , 'Sea'  , 'No' , 518, 935,270,492, 'Neutral'),
	array('Golf von Ailea'     , 'Sea'  , 'No' , 138, 845, 72,435, 'Neutral'),
	array('Doringkanal'        , 'Sea'  , 'No' ,  80, 715, 38,360, 'Neutral'),
	array('Borkmeer'           , 'Sea'  , 'No' ,  61, 565, 32,290, 'Neutral'),
	array('Kaltes Meer'        , 'Sea'  , 'No' ,  25, 350, 13,195, 'Neutral'),
	array('Golf von Gawan'     , 'Sea'  , 'No' , 115, 278, 60,145, 'Neutral'),
	array('Meer von Uuz'       , 'Sea'  , 'No' ,  86, 450, 45,225, 'Neutral'),
	array('Gorkion Delta'      , 'Sea'  , 'No' , 226, 370,118,205, 'Neutral'),
	array('Mitelgorkion'       , 'Sea'  , 'No' , 263, 498,137,260, 'Neutral'),
	array('Rotbucht'           , 'Sea'  , 'No' , 315, 604,160,315, 'Neutral'),
	array('-=> Transform <=-'  , 'Coast', 'No' ,   0,   0,  0,  0, 'Neutral')
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $x, $y, $sx, $sy, $country)=$territoryRawRow;
	if( $country=='Neutral' )
		$countryID=0;
	else
		$countryID=$this->countryID($country);
		
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Elfland'            , 'Helom'              , 'Yes','Yes'),
	array('Candolti'           , 'Qualinost'          , 'Yes','Yes'),
	array('Qualinost'          , 'Jadestadt'          , 'Yes','Yes'),
	array('Jadestadt'          , 'Schloss Gruenburg'  , 'Yes','Yes'),
	array('Schloss Gruenburg'  , 'Eld'                , 'Yes','Yes'),
	array('Eld'                , 'Kath'               , 'Yes','Yes'),
	array('Kath'               , 'Riesenheim'         , 'Yes','Yes'),
	array('Bridon'             , 'Utar'               , 'Yes','Yes'),
	array('Utar'               , 'Amphi'              , 'Yes','Yes'),
	array('Amphi'              , 'Esmaladan'          , 'Yes','Yes'),
	array('Esmaladan'          , 'Mellar'             , 'Yes','Yes'),
	array('Mellar'             , 'Obstschlucht'       , 'Yes','Yes'),
	array('Obstschlucht'       , 'Orlon'              , 'Yes','Yes'),
	array('Orlon'              , 'Losteria'           , 'Yes','Yes'),
	array('Losteria'           , 'Samyria'            , 'Yes','Yes'),
	array('Samyria'            , 'Karminstadt'        , 'Yes','Yes'),
	array('Karminstadt'        , 'Zinnoberburg'       , 'Yes','Yes'),
	array('Zinnoberburg'       , 'Ailea'              , 'Yes','Yes'),
	array('Ailea'              , 'Kentommenai'        , 'Yes','Yes'),
	array('Kentommenai'        , 'Verlorenes Land'    , 'Yes','Yes'),
	array('Arkoon'             , 'Charaua'            , 'Yes','Yes'),
	array('Charaua'            , 'Barana'             , 'Yes','Yes'),
	array('Barana'             , 'Nogk'               , 'Yes','Yes'),
	array('Nogk'               , 'Nabai'              , 'Yes','Yes'),
	array('Nabai'              , 'Saphirschlucht'     , 'Yes','Yes'),
	array('Saphirschlucht'     , 'Gurand'             , 'Yes','Yes'),
	array('Gurand'             , 'Candolti'           , 'Yes','Yes'),
	array('Abaun'              , 'Ornheim'            , 'Yes','Yes'),
	array('Jossangia'          , 'Candolti'           , 'No' ,'Yes'),
	array('Jossangia'          , 'Qualinost'          , 'No' ,'Yes'),
	array('Jossangia'          , 'Jadestadt'          , 'No' ,'Yes'),
	array('Jossangia'          , 'Schloss Gruenburg'  , 'No' ,'Yes'),
	array('Jossangia'          , 'Gruenheim'          , 'No' ,'Yes'),
	array('Jossangia'          , 'Elchen'             , 'No' ,'Yes'),
	array('Gruenheim'          , 'Schloss Gruenburg'  , 'No' ,'Yes'),
	array('Gruenheim'          , 'Caraveccia'         , 'No' ,'Yes'),
	array('Gruenheim'          , 'Yokai'              , 'No' ,'Yes'),
	array('Gruenheim'          , 'Nari'               , 'No' ,'Yes'),
	array('Gruenheim'          , 'Elchen'             , 'No' ,'Yes'),
	array('Caraveccia'         , 'Schloss Gruenburg'  , 'No' ,'Yes'),
	array('Caraveccia'         , 'Eld'                , 'No' ,'Yes'),
	array('Caraveccia'         , 'Utar'               , 'No' ,'Yes'),
	array('Caraveccia'         , 'Amphi'              , 'No' ,'Yes'),
	array('Caraveccia'         , 'Yokai'              , 'No' ,'Yes'),
	array('Utar'               , 'Eld'                , 'No' ,'Yes'),
	array('Utar'               , 'Kath'               , 'No' ,'Yes'),
	array('Utar'               , 'Riesenheim'         , 'No' ,'Yes'),
	array('Riesenheim'         , 'Bridon'             , 'No' ,'Yes'),
	array('Elchen'             , 'Candolti'           , 'No' ,'Yes'),
	array('Elchen'             , 'Gurand'             , 'No' ,'Yes'),
	array('Elchen'             , 'Tel'                , 'No' ,'Yes'),
	array('Elchen'             , 'Nari'               , 'No' ,'Yes'),
	array('Land der Wiesel'    , 'Gurand'             , 'No' ,'Yes'),
	array('Land der Wiesel'    , 'Tel'                , 'No' ,'Yes'),
	array('Land der Wiesel'    , 'Olk'                , 'No' ,'Yes'),
	array('Land der Wiesel'    , 'Hugl'               , 'No' ,'Yes'),
	array('Land der Wiesel'    , 'Norterend'          , 'No' ,'Yes'),
	array('Land der Wiesel'    , 'Saphirschlucht'     , 'No' ,'Yes'),
	array('Olk'                , 'Tel'                , 'No' ,'Yes'),
	array('Olk'                , 'Nari'               , 'No' ,'Yes'),
	array('Olk'                , 'Yokai'              , 'No' ,'Yes'),
	array('Olk'                , 'Amphi'              , 'No' ,'Yes'),
	array('Olk'                , 'Hugl'               , 'No' ,'Yes'),
	array('Tel'                , 'Gurand'             , 'No' ,'Yes'),
	array('Tel'                , 'Nari'               , 'No' ,'Yes'),
	array('Yokai'              , 'Nari'               , 'No' ,'Yes'),
	array('Yokai'              , 'Amphi'              , 'No' ,'Yes'),
	array('Wildall'            , 'Norterend'          , 'No' ,'Yes'),
	array('Wildall'            , 'Hugl'               , 'No' ,'Yes'),
	array('Wildall'            , 'Esmaladan'          , 'No' ,'Yes'),
	array('Wildall'            , 'Mellar'             , 'No' ,'Yes'),
	array('Wildall'            , 'Ostberg'            , 'No' ,'Yes'),
	array('Wildall'            , 'Skr'                , 'No' ,'Yes'),
	array('Hugl'               , 'Amphi'              , 'No' ,'Yes'),
	array('Hugl'               , 'Esmaladan'          , 'No' ,'Yes'),
	array('Hugl'               , 'Norterend'          , 'No' ,'Yes'),
	array('Norterend'          , 'Saphirschlucht'     , 'No' ,'Yes'),
	array('Norterend'          , 'Westberg'           , 'No' ,'Yes'),
	array('Norterend'          , 'Skr'                , 'No' ,'Yes'),
	array('Hills'              , 'Nabai'              , 'No' ,'Yes'),
	array('Hills'              , 'Westberg'           , 'No' ,'Yes'),
	array('Hills'              , 'Eun'                , 'No' ,'Yes'),
	array('Hills'              , 'Sund'               , 'No' ,'Yes'),
	array('Hills'              , 'Urur'               , 'No' ,'Yes'),
	array('Hills'              , 'Nogk'               , 'No' ,'Yes'),
	array('Sund'               , 'Eun'                , 'No' ,'Yes'),
	array('Sund'               , 'Ostberg'            , 'No' ,'Yes'),
	array('Sund'               , 'Obstschlucht'       , 'No' ,'Yes'),
	array('Sund'               , 'Feuerfeld'          , 'No' ,'Yes'),
	array('Sund'               , 'Urur'               , 'No' ,'Yes'),
	array('Westberg'           , 'Skr'                , 'No' ,'Yes'),
	array('Westberg'           , 'Ostberg'            , 'No' ,'Yes'),
	array('Westberg'           , 'Eun'                , 'No' ,'Yes'),
	array('Ostberg'            , 'Skr'                , 'No' ,'Yes'),
	array('Ostberg'            , 'Eun'                , 'No' ,'Yes'),
	array('Chapablublek'       , 'Barana'             , 'No' ,'Yes'),
	array('Chapablublek'       , 'Urur'               , 'No' ,'Yes'),
	array('Chapablublek'       , 'Feuerfeld'          , 'No' ,'Yes'),
	array('Chapablublek'       , 'Neu Rom'            , 'No' ,'Yes'),
	array('Chapablublek'       , 'Nilldall'           , 'No' ,'Yes'),
	array('Chapablublek'       , 'Qwil'               , 'No' ,'Yes'),
	array('Urur'               , 'Nogk'               , 'No' ,'Yes'),
	array('Urur'               , 'Barana'             , 'No' ,'Yes'),
	array('Urur'               , 'Feuerfeld'          , 'No' ,'Yes'),
	array('Neu Rom'            , 'Feuerfeld'          , 'No' ,'Yes'),
	array('Neu Rom'            , 'Orlon'              , 'No' ,'Yes'),
	array('Neu Rom'            , 'Kaaldewaa'          , 'No' ,'Yes'),
	array('Neu Rom'            , 'Nilldall'           , 'No' ,'Yes'),
	array('Feuerfeld'          , 'Obstschlucht'       , 'No' ,'Yes'),
	array('Feuerfeld'          , 'Orlon'              , 'No' ,'Yes'),
	array('Kaaldewaa'          , 'Nilldall'           , 'No' ,'Yes'),
	array('Kaaldewaa'          , 'Rotheim'            , 'No' ,'Yes'),
	array('Kaaldewaa'          , 'Mouchimoglou'       , 'No' ,'Yes'),
	array('Kaaldewaa'          , 'Losteria'           , 'No' ,'Yes'),
	array('Kaaldewaa'          , 'Orlon'              , 'No' ,'Yes'),
	array('Rotheim'            , 'Nilldall'           , 'No' ,'Yes'),
	array('Rotheim'            , 'Mouchimoglou'       , 'No' ,'Yes'),
	array('Rotheim'            , 'Zinnoberburg'       , 'No' ,'Yes'),
	array('Rotheim'            , 'Sottovia'           , 'No' ,'Yes'),
	array('Rotheim'            , 'Qwil'               , 'No' ,'Yes'),
	array('Barana'             , 'Qwil'               , 'No' ,'Yes'),
	array('Nilldall'           , 'Qwil'               , 'No' ,'Yes'),
	array('Sottovia'           , 'Qwil'               , 'No' ,'Yes'),
	array('Sottovia'           , 'Barana'             , 'No' ,'Yes'),
	array('Sottovia'           , 'Charaua'            , 'No' ,'Yes'),
	array('Sottovia'           , 'Ailea'              , 'No' ,'Yes'),
	array('Sottovia'           , 'Zinnoberburg'       , 'No' ,'Yes'),
	array('Charaua'            , 'Verlorenes Land'    , 'No' ,'Yes'),
	array('Charaua'            , 'Kentommenai'        , 'No' ,'Yes'),
	array('Charaua'            , 'Ailea'              , 'No' ,'Yes'),
	array('Verlorenes Land'    , 'Arkoon'             , 'No' ,'Yes'),
	array('Mouchimoglou'       , 'Zinnoberburg'       , 'No' ,'Yes'),
	array('Mouchimoglou'       , 'Karminstadt'        , 'No' ,'Yes'),
	array('Mouchimoglou'       , 'Samyria'            , 'No' ,'Yes'),
	array('Mouchimoglou'       , 'Losteria'           , 'No' ,'Yes'),
	array('Gawar'              , 'Gurand'             , 'No' ,'Yes'),
	array('Arkoon'             , 'Nabai'              , 'No' ,'Yes'),
	array('Charaua'            , 'Nogk'               , 'No' ,'Yes'),
	array('Esmaladan'          , 'Utar'               , 'No' ,'Yes'), 
	array('Mellar'             , 'Bridon'             , 'No' ,'Yes'),
	array('Orlon'              , 'Pirh'               , 'No' ,'Yes'),
	array('Bynn'               , 'Riesenheim'         , 'No' ,'Yes'),
	array('Bynn'               , 'Bridon'             , 'No' ,'Yes'),
	array('Bynn'               , 'Gwaul'              , 'No' ,'Yes'),
	array('Gwaul'              , 'Pirh'               , 'No' ,'Yes'),
	array('Verlorenes Land'    , 'Korbia'             , 'No' ,'Yes'),
	array('Korbia'             , 'Heronn'             , 'No' ,'Yes'),
	array('Korbia'             , 'Arkoon'             , 'No' ,'Yes'),
	array('Heronn'             , 'Gawar'              , 'No' ,'Yes'),
	array('Nordwestmeer'       , 'Polarmeer'          , 'Yes','No' ),
	array('Nordwestmeer'       , 'Fungali-Meer'       , 'Yes','No' ),
	array('Nordwestmeer'       , 'Golf von Gawan'     , 'Yes','No' ),
	array('Nordwestmeer'       , 'Kaltes Meer'        , 'Yes','No' ),
	array('Fungali-Meer'       , 'Polarmeer'          , 'Yes','No' ),
	array('Fungali-Meer'       , 'Cobaltmeer'         , 'Yes','No' ),
	array('Fungali-Meer'       , 'Jadestadt'          , 'Yes','No' ),
	array('Fungali-Meer'       , 'Qualinost'          , 'Yes','No' ),
	array('Fungali-Meer'       , 'Candolti'           , 'Yes','No' ),
	array('Fungali-Meer'       , 'Gorkion Delta'      , 'Yes','No' ),
	array('Fungali-Meer'       , 'Golf von Gawan'     , 'Yes','No' ),
	array('Cobaltmeer'         , 'Polarmeer'          , 'Yes','No' ),
	array('Cobaltmeer'         , 'Elfland'            , 'Yes','No' ),
	array('Cobaltmeer'         , 'Helom'              , 'Yes','No' ),
	array('Cobaltmeer'         , 'Nordostmeer'        , 'Yes','No' ),
	array('Cobaltmeer'         , 'Ozean von Doom'     , 'Yes','No' ),
	array('Cobaltmeer'         , 'Schloss Gruenburg'  , 'Yes','No' ),
	array('Cobaltmeer'         , 'Jadestadt'          , 'Yes','No' ),
	array('Polarmeer'          , 'Nordostmeer'        , 'Yes','No' ),
	array('Polarmeer'          , 'Elfland'            , 'Yes','No' ),
	array('Polarmeer'          , 'Helom'              , 'Yes','No' ),
	array('Nordostmeer'        , 'Helom'              , 'Yes','No' ),
	array('Nordostmeer'        , 'Conno'              , 'Yes','No' ),
	array('Nordostmeer'        , 'Ozean von Doom'     , 'Yes','No' ),
	array('Ozean von Doom'     , 'Schloss Gruenburg'  , 'Yes','No' ),
	array('Ozean von Doom'     , 'Eld'                , 'Yes','No' ),
	array('Ozean von Doom'     , 'Kath'               , 'Yes','No' ),
	array('Ozean von Doom'     , 'Kamalastrasse'      , 'Yes','No' ),
	array('Kamalastrasse'      , 'Kath'               , 'Yes','No' ),
	array('Kamalastrasse'      , 'Riesenheim'         , 'Yes','No' ),
	array('Kamalastrasse'      , 'Teisee'             , 'Yes','No' ),
	array('Teisee'             , 'Riesenheim'         , 'Yes','No' ),
	array('Teisee'             , 'Kupferkueste'       , 'Yes','No' ),
	array('Teisee'             , 'Altes Meer'         , 'Yes','No' ),
	array('Altes Meer'         , 'Kupferkueste'       , 'Yes','No' ),
	array('Altes Meer'         , 'Golf von Pirh'      , 'Yes','No' ),
	array('Altes Meer'         , 'Suedostmeer'        , 'Yes','No' ),
	array('Golf von Pirh'      , 'Kupferkueste'       , 'Yes','No' ),
	array('Golf von Pirh'      , 'Pirh'               , 'Yes','No' ),
	array('Golf von Pirh'      , 'Rodesion Delta'     , 'Yes','No' ),
	array('Golf von Pirh'      , 'Froidevaux-Meer'    , 'Yes','No' ),
	array('Golf von Pirh'      , 'Suedostmeer'        , 'Yes','No' ),
	array('Froidevaux-Meer'    , 'Losteria'           , 'Yes','No' ),
	array('Froidevaux-Meer'    , 'Rodesion Delta'     , 'Yes','No' ),
	array('Froidevaux-Meer'    , 'Suedostmeer'        , 'Yes','No' ),
	array('Froidevaux-Meer'    , 'Daxmeer'            , 'Yes','No' ),
	array('Froidevaux-Meer'    , 'Lithiumsee'         , 'Yes','No' ),
	array('Froidevaux-Meer'    , 'Karminstadt'        , 'Yes','No' ),
	array('Froidevaux-Meer'    , 'Samyria'            , 'Yes','No' ),
	array('Lithiumsee'         , 'Zinnoberburg'       , 'Yes','No' ),
	array('Lithiumsee'         , 'Karminstadt'        , 'Yes','No' ),
	array('Lithiumsee'         , 'Daxmeer'            , 'Yes','No' ),
	array('Lithiumsee'         , 'Ornheim'            , 'Yes','No' ),
	array('Lithiumsee'         , 'Abaun'              , 'Yes','No' ),
	array('Lithiumsee'         , 'Suedwestmeer'       , 'Yes','No' ),
	array('Lithiumsee'         , 'Golf von Ailea'     , 'Yes','No' ),
	array('Daxmeer'            , 'Suedostmeer'        , 'Yes','No' ),
	array('Daxmeer'            , 'Ornheim'            , 'Yes','No' ),
	array('Daxmeer'            , 'Abaun'              , 'Yes','No' ),
	array('Daxmeer'            , 'Suedwestmeer'       , 'Yes','No' ),
	array('Suedwestmeer'       , 'Corws'              , 'Yes','No' ),
	array('Suedwestmeer'       , 'Abaun'              , 'Yes','No' ),
	array('Suedwestmeer'       , 'Golf von Ailea'     , 'Yes','No' ),
	array('Golf von Ailea'     , 'Doringkanal'        , 'Yes','No' ),
	array('Golf von Ailea'     , 'Kentommenai'        , 'Yes','No' ),
	array('Golf von Ailea'     , 'Ailea'              , 'Yes','No' ),
	array('Golf von Ailea'     , 'Zinnoberburg'       , 'Yes','No' ),
	array('Doringkanal'        , 'Borkmeer'           , 'Yes','No' ),
	array('Doringkanal'        , 'Verlorenes Land'    , 'Yes','No' ),
	array('Doringkanal'        , 'Kentommenai'        , 'Yes','No' ),
	array('Borkmeer'           , 'Verlorenes Land'    , 'Yes','No' ),
	array('Borkmeer'           , 'Kaltes Meer'        , 'Yes','No' ),
	array('Borkmeer'           , 'Meer von Uuz'       , 'Yes','No' ),
	array('Kaltes Meer'        , 'Golf von Gawan'     , 'Yes','No' ),
	array('Kaltes Meer'        , 'Meer von Uuz'       , 'Yes','No' ),
	array('Meer von Uuz'       , 'Golf von Gawan'     , 'Yes','No' ),
	array('Golf von Gawan'     , 'Gawar'              , 'Yes','No' ),
	array('Golf von Gawan'     , 'Gorkion Delta'      , 'Yes','No' ),
	array('Gorkion Delta'      , 'Gawar'              , 'Yes','No' ),
	array('Gorkion Delta'      , 'Candolti'           , 'Yes','No' ),
	array('Gorkion Delta'      , 'Gurand'             , 'Yes','No' ),
	array('Gorkion Delta'      , 'Mitelgorkion'       , 'Yes','No' ),
	array('Mitelgorkion'       , 'Gawar'              , 'Yes','No' ),
	array('Mitelgorkion'       , 'Gurand'             , 'Yes','No' ),
	array('Mitelgorkion'       , 'Saphirschlucht'     , 'Yes','No' ),
	array('Mitelgorkion'       , 'Nabai'              , 'Yes','No' ),
	array('Mitelgorkion'       , 'Rotbucht'           , 'Yes','No' ),
	array('Mitelgorkion'       , 'Arkoon'             , 'Yes','No' ),
	array('Rotbucht'           , 'Nabai'              , 'Yes','No' ),
	array('Rotbucht'           , 'Nogk'               , 'Yes','No' ),
	array('Rotbucht'           , 'Barana'             , 'Yes','No' ),
	array('Rotbucht'           , 'Charaua'            , 'Yes','No' ),
	array('Rotbucht'           , 'Arkoon'             , 'Yes','No' ),
	array('Smaragt Bucht'      , 'Mellar'             , 'Yes','No' ),
	array('Smaragt Bucht'      , 'Esmaladan'          , 'Yes','No' ),
	array('Smaragt Bucht'      , 'Amphi'              , 'Yes','No' ),
	array('Smaragt Bucht'      , 'Utar'               , 'Yes','No' ),
	array('Smaragt Bucht'      , 'Bridon'             , 'Yes','No' ),
	array('Smaragt Bucht'      , 'Bucht des Ostens'   , 'Yes','No' ),
	array('Bucht des Ostens'   , 'Mellar'             , 'Yes','No' ),
	array('Bucht des Ostens'   , 'Obstschlucht'       , 'Yes','No' ),
	array('Bucht des Ostens'   , 'Orlon'              , 'Yes','No' ),
	array('Bucht des Ostens'   , 'Rodesion Delta'     , 'Yes','No' ),
	array('Bucht des Ostens'   , 'Pirh'               , 'Yes','No' ),
	array('Bucht des Ostens'   , 'Bridon'             , 'Yes','No' ),
	array('Rodesion Delta'     , 'Orlon'              , 'Yes','No' ),
	array('Rodesion Delta'     , 'Losteria'           , 'Yes','No' ),
	array('Rodesion Delta'     , 'Pirh'               , 'Yes','No' ),
	array('Bynn (East Coast)'  , 'Teisee'             , 'Yes','No' ),
	array('Bynn (East Coast)'  , 'Riesenheim'         , 'Yes','No' ),
	array('Bynn (East Coast)'  , 'Gwaul (East Coast)' , 'Yes','No' ),
	array('Bynn (East Coast)'  , 'Kupferkueste'       , 'Yes','No' ),
	array('Bynn (West Coast)'  , 'Bucht des Ostens'   , 'Yes','No' ),
	array('Bynn (West Coast)'  , 'Bridon'             , 'Yes','No' ),
	array('Bynn (West Coast)'  , 'Gwaul (West Coast)' , 'Yes','No' ),
	array('Gwaul (East Coast)' , 'Pirh'               , 'Yes','No' ),
	array('Gwaul (East Coast)' , 'Kupferkueste'       , 'Yes','No' ),
	array('Gwaul (East Coast)' , 'Golf von Pirh'      , 'Yes','No' ),
	array('Gwaul (West Coast)' , 'Bucht des Ostens'   , 'Yes','No' ),
	array('Gwaul (West Coast)' , 'Pirh'               , 'Yes','No' ),
	array('Korbia (West Coast)', 'Meer von Uuz'       , 'Yes','No' ),
	array('Korbia (West Coast)', 'Heronn (West Coast)', 'Yes','No' ),
	array('Korbia (West Coast)', 'Verlorenes Land'    , 'Yes','No' ),
	array('Korbia (West Coast)', 'Borkmeer'           , 'Yes','No' ),
	array('Korbia (East Coast)', 'Mitelgorkion'       , 'Yes','No' ),
	array('Korbia (East Coast)', 'Heronn (East Coast)', 'Yes','No' ),
	array('Korbia (East Coast)', 'Arkoon'             , 'Yes','No' ),
	array('Heronn (West Coast)', 'Gawar'              , 'Yes','No' ),
	array('Heronn (West Coast)', 'Meer von Uuz'       , 'Yes','No' ),
	array('Heronn (West Coast)', 'Golf von Gawan'     , 'Yes','No' ),
	array('Heronn (East Coast)', 'Mitelgorkion'       , 'Yes','No' ),
	array('Heronn (East Coast)', 'Gawar'              , 'Yes','No' )
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
	InstallTerritory::$Territories[$from]->addBorder(InstallTerritory::$Territories[$to]  ,$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::$Territories['Helom']->addBorder(InstallTerritory::$Territories['-=> Transform <=-'],'Yes','Yes');
InstallTerritory::$Territories['Conno']->addBorder(InstallTerritory::$Territories['-=> Transform <=-'],'Yes','Yes');
InstallTerritory::$Territories['Abaun']->addBorder(InstallTerritory::$Territories['-=> Transform <=-'],'Yes','Yes');
InstallTerritory::$Territories['Corws']->addBorder(InstallTerritory::$Territories['-=> Transform <=-'],'Yes','Yes');
InstallTerritory::$Territories['Pirh']->addBorder(InstallTerritory::$Territories['-=> Transform <=-'],'Yes','Yes');
InstallTerritory::$Territories['Gawar']->addBorder(InstallTerritory::$Territories['-=> Transform <=-'],'Yes','Yes');
InstallTerritory::$Territories['Jadestadt']->addBorder(InstallTerritory::$Territories['-=> Transform <=-'],'Yes','Yes');
InstallTerritory::$Territories['Schloss Gruenburg']->addBorder(InstallTerritory::$Territories['-=> Transform <=-'],'Yes','Yes');
InstallTerritory::$Territories['Candolti']->addBorder(InstallTerritory::$Territories['-=> Transform <=-'],'Yes','Yes');
InstallTerritory::$Territories['Kath']->addBorder(InstallTerritory::$Territories['-=> Transform <=-'],'Yes','Yes');
InstallTerritory::$Territories['Losteria']->addBorder(InstallTerritory::$Territories['-=> Transform <=-'],'Yes','Yes');
InstallTerritory::$Territories['Karminstadt']->addBorder(InstallTerritory::$Territories['-=> Transform <=-'],'Yes','Yes');
InstallTerritory::$Territories['Zinnoberburg']->addBorder(InstallTerritory::$Territories['-=> Transform <=-'],'Yes','Yes');
InstallTerritory::$Territories['Kentommenai']->addBorder(InstallTerritory::$Territories['-=> Transform <=-'],'Yes','Yes');
InstallTerritory::$Territories['Arkoon']->addBorder(InstallTerritory::$Territories['-=> Transform <=-'],'Yes','Yes');
InstallTerritory::$Territories['Nabai']->addBorder(InstallTerritory::$Territories['-=> Transform <=-'],'Yes','Yes');
InstallTerritory::$Territories['Mellar']->addBorder(InstallTerritory::$Territories['-=> Transform <=-'],'Yes','Yes');
InstallTerritory::$Territories['Bridon']->addBorder(InstallTerritory::$Territories['-=> Transform <=-'],'Yes','Yes');

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);

?>