<?php
// This is file installs the map data for the FreeFlowFantasy variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Glasch', 'Coast', 'Yes', 1, 630, 630, 315, 315),
	array('Delim', 'Land', 'Yes', 2, 1240, 938, 620, 469),
	array('Gi', 'Coast', 'Yes', 3, 1179, 551, 589, 270),
	array('Bagnikki', 'Coast', 'Yes', 4, 1016, 920, 508, 460),
	array('South Holgii', 'Coast', 'Yes', 5, 1057, 463, 534, 234),
	array('Gernavian Colony', 'Coast', 'Yes', 6, 1364, 584, 682, 292),
	array('Nerr', 'Coast', 'Yes', 7, 390, 646, 195, 323),
	array('Elenia', 'Coast', 'Yes', 8, 262, 608, 137, 307),
	array('Braman Strait', 'Sea', 'No', 0, 337, 609, 177, 304),
	array('Great Frozen Wasteland', 'Coast', 'No', 0, 454, 218, 227, 109),
	array('Vindisium', 'Coast', 'No', 0, 674, 110, 337, 55),
	array('Wechtica', 'Land', 'Yes', 0, 854, 56, 423, 26),
	array('Denselands', 'Coast', 'Yes', 0, 282, 384, 141, 192),
	array('Island of Pigs', 'Coast', 'Yes', 0, 342, 576, 171, 288),
	array('Pelain', 'Coast', 'Yes', 0, 781, 618, 398, 283),
	array('Kingdom of Golia', 'Land', 'Yes', 0, 518, 675, 256, 338),
	array('Verdia', 'Coast', 'Yes', 0, 547, 745, 279, 359),
	array('Turridia', 'Coast', 'No', 0, 742, 346, 371, 173),
	array('Oasis', 'Land', 'Yes', 0, 296, 932, 148, 466),
	array('Brim', 'Coast', 'Yes', 0, 527, 603, 257, 298),
	array('Puglia', 'Coast', 'No', 0, 1016, 1106, 508, 553),
	array('Great Haven', 'Coast', 'Yes', 0, 954, 1254, 477, 627),
	array('Empowia', 'Land', 'No', 0, 784, 1078, 392, 539),
	array('Cordianople', 'Coast', 'Yes', 0, 1102, 980, 551, 490),
	array('Erior', 'Coast', 'Yes', 0, 1192, 854, 596, 427),
	array('Delah', 'Land', 'No', 0, 1207, 1028, 591, 510),
	array('Confederation of Dini', 'Coast', 'Yes', 0, 748, 394, 368, 194),
	array('Free World', 'Coast', 'Yes', 0, 1133, 657, 561, 326),
	array('Boon', 'Coast', 'Yes', 0, 1088, 555, 541, 273),
	array('Tripiland', 'Coast', 'Yes', 0, 1216, 384, 601, 189),
	array('Dulgland', 'Coast', 'No', 0, 704, 840, 352, 420),
	array('Mount Pasco', 'Land', 'Yes', 0, 692, 764, 346, 382),
	array('Land of Peace', 'Coast', 'Yes', 0, 776, 718, 388, 359),
	array('Independent Holgia', 'Land', 'No', 0, 1152, 466, 563, 227),
	array('Sunken Holgia', 'Sea', 'No', 0, 826, 284, 413, 142),
	array('Great Ocean', 'Sea', 'No', 0, 422, 422, 211, 211),
	array('Arctic Ocean', 'Sea', 'No', 0, 1086, 180, 543, 90),
	array('Bay of Holgii', 'Sea', 'No', 0, 1082, 268, 542, 127),
	array('Bay of Etvost', 'Sea', 'No', 0, 578, 784, 289, 392),
	array('Ecclian Ocean', 'Sea', 'No', 0, 768, 486, 384, 243),
	array('Holgian Sea', 'Sea', 'No', 0, 984, 572, 492, 286),
	array('Glasc Sea', 'Sea', 'No', 0, 756, 660, 378, 330),
	array('Farther Waters', 'Sea', 'No', 0, 1356, 388, 678, 194),
	array('Elenian Sea', 'Sea', 'No', 0, 266, 504, 133, 252),
	array('Erian Sea', 'Sea', 'No', 0, 1154, 786, 577, 393),
	array('Mouth of Cordia', 'Sea', 'No', 0, 1091, 863, 550, 429),
	array('Eastern Sea', 'Sea', 'No', 0, 1344, 854, 672, 427),
	array('Strait of Hackle', 'Sea', 'No', 0, 1288, 538, 644, 269),
	array('Gernavian Bay', 'Sea', 'No', 0, 871, 842, 418, 356),
	array('Turrid Waters', 'Sea', 'No', 0, 668, 366, 334, 183),
	array('Gernavian Sea', 'Sea', 'No', 0, 1074, 785, 541, 378),
	array('Hackling Bay', 'Sea', 'No', 0, 1226, 590, 613, 295),
	array('North Holgii', 'Coast', 'No', 5, 920, 86, 460, 43),
	array('East Tundra', 'Coast', 'No', 5, 1013, 272, 504, 126),
	array('West Tundra', 'Coast', 'No', 5, 894, 224, 440, 110),
	array('Great Holgii', 'Coast', 'Yes', 5, 1034, 428, 517, 214),
	array('Shire', 'Coast', 'No', 5, 1138, 374, 569, 187),
	array('Dino', 'Coast', 'Yes', 5, 838, 384, 419, 192),
	array('Turri', 'Coast', 'Yes', 8, 669, 312, 332, 151),
	array('Ecce', 'Coast', 'Yes', 8, 547, 537, 273, 269),
	array('Mountains of Elenia', 'Coast', 'No', 8, 116, 705, 55, 343),
	array('Elepio', 'Land', 'No', 8, 214, 729, 98, 366),
	array('Asgrin', 'Land', 'No', 8, 346, 670, 173, 335),
	array('Ports of Elenia', 'Coast', 'No', 8, 277, 662, 140, 333),
	array('Ecclia', 'Coast', 'No', 1, 600, 575, 295, 288),
	array('Bulgi', 'Coast', 'Yes', 1, 639, 773, 319, 381),
	array('Pasci', 'Coast', 'No', 1, 700, 714, 350, 357),
	array('Bram', 'Coast', 'No', 1, 514, 620, 252, 306),
	array('Golni', 'Land', 'Yes', 1, 576, 646, 288, 323),
	array('Olia', 'Coast', 'Yes', 7, 457, 638, 226, 316),
	array('Bramia', 'Land', 'No', 7, 424, 694, 212, 340),
	array('Epio', 'Land', 'No', 7, 362, 710, 181, 355),
	array('Tilia', 'Land', 'No', 7, 416, 800, 208, 400),
	array('Deoveland', 'Land', 'Yes', 7, 442, 745, 224, 370),
	array('Southern Elenia', 'Coast', 'No', 4, 72, 824, 42, 407),
	array('Lost Lands', 'Land', 'No', 4, 336, 816, 168, 408),
	array('Desert of Khelioch', 'Land', 'No', 4, 322, 994, 161, 497),
	array('Kheliocea', 'Land', 'No', 4, 426, 1016, 203, 509),
	array('Ekhveria', 'Land', 'No', 4, 480, 1046, 240, 523),
	array('New Trylia', 'Coast', 'Yes', 4, 531, 846, 262, 418),
	array('Greater Etvost', 'Coast', 'No', 4, 628, 894, 314, 447),
	array('Lesser Etvost', 'Land', 'Yes', 4, 509, 930, 254, 460),
	array('Province of Etvost', 'Coast', 'No', 4, 690, 928, 345, 464),
	array('Blumina', 'Land', 'No', 4, 774, 960, 387, 480),
	array('Tryliost', 'Coast', 'No', 4, 864, 894, 432, 447),
	array('Wasteland', 'Coast', 'No', 4, 992, 990, 496, 495),
	array('Trylia', 'Land', 'Yes', 4, 869, 959, 434, 478),
	array('Great Magnii', 'Coast', 'Yes', 6, 764, 858, 382, 429),
	array('Gernavian Homeworld', 'Coast', 'No', 6, 722, 1280, 361, 640),
	array('Northern Territory', 'Coast', 'No', 6, 878, 660, 439, 330),
	array('Levio', 'Coast', 'Yes', 6, 941, 733, 472, 362),
	array('Pizz', 'Coast', 'No', 6, 992, 770, 493, 380),
	array('Southern Territory', 'Coast', 'No', 6, 1040, 821, 519, 406),
	array('Western Territory', 'Coast', 'Yes', 6, 899, 807, 449, 402),
	array('Tsumi', 'Coast', 'Yes', 3, 1242, 450, 621, 225),
	array('Hackli', 'Coast', 'No', 3, 1186, 496, 592, 244),
	array('Iggle', 'Coast', 'No', 3, 1106, 600, 553, 300),
	array('Hacklia', 'Coast', 'No', 3, 1209, 663, 612, 328),
	array('Grantuck', 'Coast', 'Yes', 3, 1232, 764, 618, 378),
	array('Utuk', 'Coast', 'Yes', 2, 1243, 819, 615, 413),
	array('Groiland', 'Coast', 'No', 2, 1272, 846, 636, 423),
	array('Epimnah', 'Coast', 'No', 2, 1360, 996, 680, 498),
	array('Salitoss', 'Coast', 'Yes', 2, 1314, 908, 657, 454),
	array('Ports of Elenia (West Coast)', 'Coast', 'No', 8, 202, 644, 101, 322),
	array('Ports of Elenia (East Coast)', 'Coast', 'No', 8, 350, 640, 175, 320),
	array('Utuk (West Coast)', 'Coast', 'No', 2, 1204, 798, 602, 399),
	array('Utuk (East Coast)', 'Coast', 'No', 2, 1268, 784, 634, 392),
	array('Levio (West Coast)', 'Coast', 'No', 6, 896, 740, 448, 370),
	array('Levio (East Coast)', 'Coast', 'No', 6, 984, 742, 495, 368),
	array('South Holgii (North Coast)', 'Coast', 'No', 5, 1094, 412, 547, 206),
	array('South Holgii (South Coast)', 'Coast', 'No', 5, 1040, 498, 520, 249),
	array('Great Holgii (West Coast)', 'Coast', 'No', 5, 1022, 465, 507, 226),
	array('Great Holgii (North Coast)', 'Coast', 'No', 5, 1018, 348, 509, 174),
	array('(socialist glock)', 'Coast', 'No', 1, 208, 1228, 103, 610),
	array('(kingdom of saltz)', 'Coast', 'No', 2, 226, 1252, 113, 626),
	array('(the hacklers)', 'Coast', 'No', 3, 222, 1280, 111, 640),
	array('(trylikia)', 'Coast', 'No', 4, 188, 1310, 94, 655),
	array('(ruins of holgii)', 'Coast', 'No', 5, 1422, 1236, 711, 618),
	array('(gernavia)', 'Coast', 'No', 6, 1426, 1260, 713, 630),
	array('(old bramia)', 'Coast', 'No', 7, 1402, 1288, 701, 644),
	array('(elenian empire)', 'Coast', 'No', 8, 1420, 1318, 710, 659)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Glasch','Kingdom of Golia','No','Yes'),
	array('Glasch','Verdia','Yes','Yes'),
	array('Glasch','Bay of Etvost','Yes','No'),
	array('Glasch','Ecclian Ocean','Yes','No'),
	array('Glasch','Glasc Sea','Yes','No'),
	array('Glasch','Ecclia','Yes','Yes'),
	array('Glasch','Bram','No','Yes'),
	array('Glasch','Golni','No','Yes'),
	array('Delim','Cordianople','No','Yes'),
	array('Delim','Erior','No','Yes'),
	array('Delim','Delah','No','Yes'),
	array('Delim','Groiland','No','Yes'),
	array('Delim','Epimnah','No','Yes'),
	array('Delim','Salitoss','No','Yes'),
	array('Gi','Independent Holgia','No','Yes'),
	array('Gi','Hackling Bay','Yes','No'),
	array('Gi','Hackli','Yes','Yes'),
	array('Gi','Iggle','No','Yes'),
	array('Gi','Hacklia','Yes','Yes'),
	array('Bagnikki','Mouth of Cordia','Yes','No'),
	array('Bagnikki','Tryliost','No','Yes'),
	array('Bagnikki','Wasteland','Yes','Yes'),
	array('Bagnikki','Trylia','No','Yes'),
	array('Bagnikki','Southern Territory','Yes','Yes'),
	array('Bagnikki','Western Territory','No','Yes'),
	array('South Holgii','Boon','No','Yes'),
	array('South Holgii','Independent Holgia','No','Yes'),
	array('South Holgii','Great Holgii','No','Yes'),
	array('South Holgii','Shire','No','Yes'),
	array('Gernavian Colony','Farther Waters','Yes','No'),
	array('Gernavian Colony','Eastern Sea','Yes','No'),
	array('Gernavian Colony','Strait of Hackle','Yes','No'),
	array('Nerr','Braman Strait','Yes','No'),
	array('Nerr','Island of Pigs','Yes','Yes'),
	array('Nerr','Asgrin','No','Yes'),
	array('Nerr','Ports of Elenia','No','Yes'),
	array('Nerr','Olia','Yes','Yes'),
	array('Nerr','Bramia','No','Yes'),
	array('Nerr','Epio','No','Yes'),
	array('Nerr','Ports of Elenia (East Coast)','Yes','No'),
	array('Elenia','Braman Strait','Yes','No'),
	array('Elenia','Island of Pigs','Yes','Yes'),
	array('Elenia','Elenian Sea','Yes','No'),
	array('Elenia','Ports of Elenia','No','Yes'),
	array('Elenia','Ports of Elenia (West Coast)','Yes','No'),
	array('Elenia','Ports of Elenia (East Coast)','Yes','No'),
	array('Braman Strait','Island of Pigs','Yes','No'),
	array('Braman Strait','Brim','Yes','No'),
	array('Braman Strait','Great Ocean','Yes','No'),
	array('Braman Strait','Elenian Sea','Yes','No'),
	array('Braman Strait','Bram','Yes','No'),
	array('Braman Strait','Olia','Yes','No'),
	array('Braman Strait','Ports of Elenia (East Coast)','Yes','No'),
	array('Great Frozen Wasteland','Vindisium','Yes','Yes'),
	array('Great Frozen Wasteland','Wechtica','No','Yes'),
	array('Great Frozen Wasteland','Great Ocean','Yes','No'),
	array('Great Frozen Wasteland','Arctic Ocean','Yes','No'),
	array('Great Frozen Wasteland','North Holgii','Yes','Yes'),
	array('Vindisium','Wechtica','No','Yes'),
	array('Vindisium','Sunken Holgia','Yes','No'),
	array('Vindisium','Great Ocean','Yes','No'),
	array('Vindisium','North Holgii','Yes','Yes'),
	array('Wechtica','North Holgii','No','Yes'),
	array('Denselands','Great Ocean','Yes','No'),
	array('Denselands','Farther Waters','Yes','No'),
	array('Denselands','Elenian Sea','Yes','No'),
	array('Island of Pigs','Great Ocean','Yes','No'),
	array('Island of Pigs','Elenian Sea','Yes','No'),
	array('Pelain','Ecclian Ocean','Yes','No'),
	array('Pelain','Holgian Sea','Yes','No'),
	array('Pelain','Glasc Sea','Yes','No'),
	array('Kingdom of Golia','Verdia','No','Yes'),
	array('Kingdom of Golia','Bram','No','Yes'),
	array('Kingdom of Golia','Golni','No','Yes'),
	array('Kingdom of Golia','Olia','No','Yes'),
	array('Kingdom of Golia','Bramia','No','Yes'),
	array('Verdia','Bay of Etvost','Yes','No'),
	array('Verdia','Bramia','No','Yes'),
	array('Verdia','Tilia','No','Yes'),
	array('Verdia','Deoveland','No','Yes'),
	array('Verdia','New Trylia','Yes','Yes'),
	array('Turridia','Confederation of Dini','No','Yes'),
	array('Turridia','Sunken Holgia','Yes','No'),
	array('Turridia','Dino','Yes','Yes'),
	array('Turridia','Turri','Yes','Yes'),
	array('Oasis','Southern Elenia','No','Yes'),
	array('Oasis','Lost Lands','No','Yes'),
	array('Oasis','Desert of Khelioch','No','Yes'),
	array('Brim','Great Ocean','Yes','No'),
	array('Brim','Ecce','Yes','Yes'),
	array('Brim','Ecclia','No','Yes'),
	array('Brim','Bram','Yes','Yes'),
	array('Puglia','Great Haven','Yes','Yes'),
	array('Puglia','Empowia','No','Yes'),
	array('Puglia','Cordianople','Yes','Yes'),
	array('Puglia','Mouth of Cordia','Yes','No'),
	array('Puglia','Wasteland','Yes','Yes'),
	array('Puglia','Gernavian Homeworld','No','Yes'),
	array('Great Haven','Empowia','No','Yes'),
	array('Great Haven','Gernavian Homeworld','No','Yes'),
	array('Empowia','Ekhveria','No','Yes'),
	array('Empowia','Province of Etvost','No','Yes'),
	array('Empowia','Blumina','No','Yes'),
	array('Empowia','Wasteland','No','Yes'),
	array('Empowia','Gernavian Homeworld','No','Yes'),
	array('Cordianople','Erior','Yes','Yes'),
	array('Cordianople','Delah','No','Yes'),
	array('Cordianople','Mouth of Cordia','Yes','No'),
	array('Cordianople','Gernavian Homeworld','No','Yes'),
	array('Erior','Erian Sea','Yes','No'),
	array('Erior','Mouth of Cordia','Yes','No'),
	array('Erior','Utuk','No','Yes'),
	array('Erior','Groiland','No','Yes'),
	array('Erior','Utuk (West Coast)','Yes','No'),
	array('Delah','Gernavian Homeworld','No','Yes'),
	array('Delah','Epimnah','No','Yes'),
	array('Confederation of Dini','Ecclian Ocean','Yes','No'),
	array('Confederation of Dini','Turrid Waters','Yes','No'),
	array('Confederation of Dini','Dino','Yes','Yes'),
	array('Confederation of Dini','Turri','Yes','Yes'),
	array('Free World','Holgian Sea','Yes','No'),
	array('Free World','Gernavian Sea','Yes','No'),
	array('Free World','Iggle','Yes','Yes'),
	array('Free World','Hacklia','No','Yes'),
	array('Free World','Grantuck','Yes','Yes'),
	array('Boon','Independent Holgia','No','Yes'),
	array('Boon','Holgian Sea','Yes','No'),
	array('Boon','Iggle','Yes','Yes'),
	array('Boon','South Holgii (South Coast)','Yes','No'),
	array('Tripiland','Independent Holgia','No','Yes'),
	array('Tripiland','Bay of Holgii','Yes','No'),
	array('Tripiland','Farther Waters','Yes','No'),
	array('Tripiland','Shire','Yes','Yes'),
	array('Tripiland','Tsumi','Yes','Yes'),
	array('Dulgland','Mount Pasco','No','Yes'),
	array('Dulgland','Land of Peace','No','Yes'),
	array('Dulgland','Bay of Etvost','Yes','No'),
	array('Dulgland','Bulgi','Yes','Yes'),
	array('Dulgland','Great Magnii','Yes','Yes'),
	array('Mount Pasco','Land of Peace','No','Yes'),
	array('Mount Pasco','Bulgi','No','Yes'),
	array('Mount Pasco','Pasci','No','Yes'),
	array('Land of Peace','Glasc Sea','Yes','No'),
	array('Land of Peace','Gernavian Bay','Yes','No'),
	array('Land of Peace','Pasci','Yes','Yes'),
	array('Land of Peace','Great Magnii','Yes','Yes'),
	array('Independent Holgia','Shire','No','Yes'),
	array('Independent Holgia','Tsumi','No','Yes'),
	array('Independent Holgia','Hackli','No','Yes'),
	array('Independent Holgia','Iggle','No','Yes'),
	array('Sunken Holgia','Great Ocean','Yes','No'),
	array('Sunken Holgia','Arctic Ocean','Yes','No'),
	array('Sunken Holgia','Holgian Sea','Yes','No'),
	array('Sunken Holgia','Turrid Waters','Yes','No'),
	array('Sunken Holgia','North Holgii','Yes','No'),
	array('Sunken Holgia','West Tundra','Yes','No'),
	array('Sunken Holgia','Dino','Yes','No'),
	array('Sunken Holgia','Turri','Yes','No'),
	array('Sunken Holgia','South Holgii (South Coast)','Yes','No'),
	array('Sunken Holgia','Great Holgii (West Coast)','Yes','No'),
	array('Great Ocean','Arctic Ocean','Yes','No'),
	array('Great Ocean','Ecclian Ocean','Yes','No'),
	array('Great Ocean','Farther Waters','Yes','No'),
	array('Great Ocean','Elenian Sea','Yes','No'),
	array('Great Ocean','Turrid Waters','Yes','No'),
	array('Great Ocean','Ecce','Yes','No'),
	array('Great Ocean','Ecclia','Yes','No'),
	array('Arctic Ocean','Bay of Holgii','Yes','No'),
	array('Arctic Ocean','Farther Waters','Yes','No'),
	array('Arctic Ocean','North Holgii','Yes','No'),
	array('Arctic Ocean','East Tundra','Yes','No'),
	array('Arctic Ocean','West Tundra','Yes','No'),
	array('Bay of Holgii','Farther Waters','Yes','No'),
	array('Bay of Holgii','East Tundra','Yes','No'),
	array('Bay of Holgii','Shire','Yes','No'),
	array('Bay of Holgii','South Holgii (North Coast)','Yes','No'),
	array('Bay of Holgii','Great Holgii (North Coast)','Yes','No'),
	array('Bay of Etvost','Glasc Sea','Yes','No'),
	array('Bay of Etvost','Gernavian Bay','Yes','No'),
	array('Bay of Etvost','Bulgi','Yes','No'),
	array('Bay of Etvost','New Trylia','Yes','No'),
	array('Bay of Etvost','Greater Etvost','Yes','No'),
	array('Bay of Etvost','Province of Etvost','Yes','No'),
	array('Bay of Etvost','Tryliost','Yes','No'),
	array('Bay of Etvost','Great Magnii','Yes','No'),
	array('Ecclian Ocean','Holgian Sea','Yes','No'),
	array('Ecclian Ocean','Glasc Sea','Yes','No'),
	array('Ecclian Ocean','Turrid Waters','Yes','No'),
	array('Ecclian Ocean','Dino','Yes','No'),
	array('Ecclian Ocean','Ecclia','Yes','No'),
	array('Holgian Sea','Glasc Sea','Yes','No'),
	array('Holgian Sea','Gernavian Sea','Yes','No'),
	array('Holgian Sea','Dino','Yes','No'),
	array('Holgian Sea','Northern Territory','Yes','No'),
	array('Holgian Sea','Iggle','Yes','No'),
	array('Holgian Sea','Levio (East Coast)','Yes','No'),
	array('Holgian Sea','South Holgii (South Coast)','Yes','No'),
	array('Glasc Sea','Gernavian Bay','Yes','No'),
	array('Glasc Sea','Bulgi','Yes','No'),
	array('Glasc Sea','Pasci','Yes','No'),
	array('Glasc Sea','Northern Territory','Yes','No'),
	array('Farther Waters','Elenian Sea','Yes','No'),
	array('Farther Waters','Eastern Sea','Yes','No'),
	array('Farther Waters','Strait of Hackle','Yes','No'),
	array('Farther Waters','Mountains of Elenia','Yes','No'),
	array('Farther Waters','Tsumi','Yes','No'),
	array('Elenian Sea','Mountains of Elenia','Yes','No'),
	array('Elenian Sea','Ports of Elenia (West Coast)','Yes','No'),
	array('Erian Sea','Mouth of Cordia','Yes','No'),
	array('Erian Sea','Gernavian Sea','Yes','No'),
	array('Erian Sea','Grantuck','Yes','No'),
	array('Erian Sea','Utuk (West Coast)','Yes','No'),
	array('Mouth of Cordia','Gernavian Sea','Yes','No'),
	array('Mouth of Cordia','Wasteland','Yes','No'),
	array('Mouth of Cordia','Southern Territory','Yes','No'),
	array('Eastern Sea','Strait of Hackle','Yes','No'),
	array('Eastern Sea','Mountains of Elenia','Yes','No'),
	array('Eastern Sea','Southern Elenia','Yes','No'),
	array('Eastern Sea','Gernavian Homeworld','Yes','No'),
	array('Eastern Sea','Groiland','Yes','No'),
	array('Eastern Sea','Epimnah','Yes','No'),
	array('Eastern Sea','Salitoss','Yes','No'),
	array('Eastern Sea','Utuk (East Coast)','Yes','No'),
	array('Strait of Hackle','Hackling Bay','Yes','No'),
	array('Strait of Hackle','Tsumi','Yes','No'),
	array('Strait of Hackle','Hacklia','Yes','No'),
	array('Strait of Hackle','Grantuck','Yes','No'),
	array('Strait of Hackle','Utuk (East Coast)','Yes','No'),
	array('Gernavian Bay','Tryliost','Yes','No'),
	array('Gernavian Bay','Great Magnii','Yes','No'),
	array('Gernavian Bay','Northern Territory','Yes','No'),
	array('Gernavian Bay','Western Territory','Yes','No'),
	array('Gernavian Bay','Levio (West Coast)','Yes','No'),
	array('Turrid Waters','Turri','Yes','No'),
	array('Gernavian Sea','Pizz','Yes','No'),
	array('Gernavian Sea','Southern Territory','Yes','No'),
	array('Gernavian Sea','Grantuck','Yes','No'),
	array('Gernavian Sea','Levio (East Coast)','Yes','No'),
	array('Hackling Bay','Tsumi','Yes','No'),
	array('Hackling Bay','Hackli','Yes','No'),
	array('Hackling Bay','Hacklia','Yes','No'),
	array('East Tundra','West Tundra','Yes','Yes'),
	array('East Tundra','Great Holgii','No','Yes'),
	array('East Tundra','Great Holgii (North Coast)','Yes','No'),
	array('West Tundra','Great Holgii','No','Yes'),
	array('West Tundra','Great Holgii (West Coast)','Yes','No'),
	array('Shire','South Holgii (North Coast)','Yes','No'),
	array('Ecce','Ecclia','Yes','Yes'),
	array('Mountains of Elenia','Elepio','No','Yes'),
	array('Mountains of Elenia','Asgrin','No','Yes'),
	array('Mountains of Elenia','Ports of Elenia','No','Yes'),
	array('Mountains of Elenia','Southern Elenia','Yes','Yes'),
	array('Mountains of Elenia','Ports of Elenia (West Coast)','Yes','No'),
	array('Elepio','Asgrin','No','Yes'),
	array('Elepio','Epio','No','Yes'),
	array('Elepio','Southern Elenia','No','Yes'),
	array('Asgrin','Ports of Elenia','No','Yes'),
	array('Asgrin','Epio','No','Yes'),
	array('Ecclia','Bram','No','Yes'),
	array('Bulgi','Pasci','Yes','Yes'),
	array('Bram','Golni','No','Yes'),
	array('Bram','Olia','Yes','Yes'),
	array('Olia','Bramia','No','Yes'),
	array('Bramia','Epio','No','Yes'),
	array('Bramia','Deoveland','No','Yes'),
	array('Epio','Tilia','No','Yes'),
	array('Epio','Deoveland','No','Yes'),
	array('Epio','Southern Elenia','No','Yes'),
	array('Tilia','Deoveland','No','Yes'),
	array('Tilia','Southern Elenia','No','Yes'),
	array('Tilia','Lost Lands','No','Yes'),
	array('Tilia','Desert of Khelioch','No','Yes'),
	array('Tilia','New Trylia','No','Yes'),
	array('Southern Elenia','Lost Lands','No','Yes'),
	array('Southern Elenia','Desert of Khelioch','No','Yes'),
	array('Southern Elenia','Gernavian Homeworld','Yes','Yes'),
	array('Lost Lands','Desert of Khelioch','No','Yes'),
	array('Desert of Khelioch','Kheliocea','No','Yes'),
	array('Desert of Khelioch','Ekhveria','No','Yes'),
	array('Desert of Khelioch','New Trylia','No','Yes'),
	array('Desert of Khelioch','Gernavian Homeworld','No','Yes'),
	array('Kheliocea','Ekhveria','No','Yes'),
	array('Kheliocea','New Trylia','No','Yes'),
	array('Kheliocea','Lesser Etvost','No','Yes'),
	array('Kheliocea','Province of Etvost','No','Yes'),
	array('Ekhveria','Province of Etvost','No','Yes'),
	array('Ekhveria','Gernavian Homeworld','No','Yes'),
	array('New Trylia','Greater Etvost','Yes','Yes'),
	array('New Trylia','Lesser Etvost','No','Yes'),
	array('Greater Etvost','Lesser Etvost','No','Yes'),
	array('Greater Etvost','Province of Etvost','Yes','Yes'),
	array('Lesser Etvost','Province of Etvost','No','Yes'),
	array('Province of Etvost','Blumina','No','Yes'),
	array('Province of Etvost','Tryliost','Yes','Yes'),
	array('Blumina','Tryliost','No','Yes'),
	array('Blumina','Wasteland','No','Yes'),
	array('Blumina','Trylia','No','Yes'),
	array('Tryliost','Trylia','No','Yes'),
	array('Tryliost','Western Territory','Yes','Yes'),
	array('Wasteland','Trylia','No','Yes'),
	array('Gernavian Homeworld','Epimnah','Yes','Yes'),
	array('Northern Territory','Levio','No','Yes'),
	array('Northern Territory','Levio (West Coast)','Yes','No'),
	array('Northern Territory','Levio (East Coast)','Yes','No'),
	array('Levio','Pizz','No','Yes'),
	array('Levio','Western Territory','No','Yes'),
	array('Pizz','Southern Territory','Yes','Yes'),
	array('Pizz','Western Territory','No','Yes'),
	array('Pizz','Levio (East Coast)','Yes','No'),
	array('Southern Territory','Western Territory','Yes','Yes'),
	array('Western Territory','Levio (West Coast)','Yes','No'),
	array('Tsumi','Hackli','Yes','Yes'),
	array('Iggle','Hacklia','No','Yes'),
	array('Hacklia','Grantuck','Yes','Yes'),
	array('Grantuck','Utuk','No','Yes'),
	array('Grantuck','Utuk (West Coast)','Yes','No'),
	array('Grantuck','Utuk (East Coast)','Yes','No'),
	array('Utuk','Groiland','No','Yes'),
	array('Groiland','Salitoss','Yes','Yes'),
	array('Groiland','Utuk (East Coast)','Yes','No'),
	array('Epimnah','Salitoss','Yes','Yes'),
	array('South Holgii (North Coast)','Great Holgii (North Coast)','Yes','No'),
	array('South Holgii (South Coast)','Great Holgii (West Coast)','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
