<?php
// This is file installs the map data for the Africa variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('North Atlantic Ocean', 'Sea', 'No', 0, 35, 73, 12, 44),
	array('Western Mediterranean Sea', 'Sea', 'No', 0, 422, 20, 187, 10),
	array('Central Mediterranean Sea', 'Sea', 'No', 0, 666, 64, 349, 11),
	array('Aegean Sea', 'Sea', 'No', 0, 873, 42, 423, 10),
	array('Eastern Mediterranean Sea', 'Sea', 'No', 0, 1037, 84, 491, 41),
	array('Suez Canal', 'Sea', 'No', 0, 1040, 134, 485, 59),
	array('Red Sea', 'Sea', 'No', 0, 1172, 393, 533, 148),
	array('Gulf of Aden', 'Sea', 'No', 0, 1453, 458, 639, 227),
	array('North Indian Ocean', 'Sea', 'No', 0, 1327, 761, 674, 285),
	array('Mid Atlantic Ocean', 'Sea', 'No', 0, 30, 618, 36, 236),
	array('Romanche Trench', 'Sea', 'No', 0, 150, 654, 75, 297),
	array('Gulf of Guinea', 'Sea', 'No', 0, 400, 803, 145, 346),
	array('Bight of Benin', 'Sea', 'No', 0, 473, 688, 218, 320),
	array('South-West Atlantic Ocean', 'Sea', 'No', 0, 160, 1139, 54, 536),
	array('South-East Atlantic Ocean', 'Sea', 'No', 0, 567, 1267, 251, 578),
	array('Cape of Good Hope', 'Sea', 'No', 0, 738, 1393, 380, 675),
	array('South Indian Ocean', 'Sea', 'No', 0, 1198, 1325, 556, 636),
	array('Mozambique Channel', 'Sea', 'No', 0, 1143, 1161, 532, 536),
	array('Mascarene Plateau', 'Sea', 'No', 0, 1402, 1041, 631, 552),
	array('Lake Victoria', 'Sea', 'No', 0, 1065, 756, 495, 353),
	array('Strait of Gibraltar', 'Sea', 'No', 0, 303, 23, 140, 8),
	array('Sinai', 'Coast', 'No', 2, 1056, 164, 492, 72),
	array('Cairo', 'Coast', 'Yes', 2, 1025, 225, 474, 77),
	array('Alexandria', 'Coast', 'Yes', 2, 928, 157, 440, 71),
	array('Luxor', 'Coast', 'Yes', 2, 1005, 304, 467, 123),
	array('Benghazi', 'Coast', 'Yes', 0, 881, 157, 392, 59),
	array('Sirte', 'Coast', 'No', 0, 737, 156, 346, 72),
	array('Fezzan', 'Land', 'No', 0, 751, 260, 346, 110),
	array('Tripoli', 'Coast', 'Yes', 9, 706, 142, 322, 62),
	array('North Chad', 'Land', 'Yes', 0, 845, 383, 360, 160),
	array('N\\\'Djamena', 'Land', 'No', 0, 728, 464, 356, 231),
	array('Tamanrasset', 'Land', 'Yes', 0, 550, 232, 254, 103),
	array('Adrar', 'Land', 'Yes', 0, 376, 245, 172, 116),
	array('Western Algeria', 'Land', 'No', 0, 425, 142, 204, 51),
	array('Darfur', 'Land', 'No', 0, 918, 392, 427, 176),
	array('Azawad', 'Land', 'No', 0, 352, 313, 169, 145),
	array('Western Sahara', 'Coast', 'No', 0, 184, 264, 78, 133),
	array('Northern Mauritania', 'Coast', 'Yes', 0, 154, 356, 71, 166),
	array('Nouakchott', 'Coast', 'No', 0, 203, 420, 72, 183),
	array('Casablanca', 'Coast', 'Yes', 6, 319, 62, 127, 42),
	array('Eastern Morocco', 'Coast', 'Yes', 6, 389, 65, 181, 27),
	array('Marrakech', 'Coast', 'Yes', 6, 246, 195, 113, 87),
	array('Timbuktu', 'Coast', 'Yes', 9, 342, 375, 169, 192),
	array('Agadez', 'Land', 'Yes', 0, 578, 380, 296, 158),
	array('Central African Republic', 'Land', 'No', 0, 757, 641, 349, 294),
	array('Orientale', 'Coast', 'No', 1, 882, 712, 428, 339),
	array('South Niger', 'Land', 'No', 0, 545, 445, 252, 196),
	array('Algiers', 'Coast', 'Yes', 0, 564, 28, 233, 11),
	array('Tunisia', 'Coast', 'Yes', 9, 610, 50, 282, 17),
	array('Ascension', 'Sea', 'No', 0, 211, 894, 96, 411),
	array('Kano', 'Land', 'Yes', 7, 652, 535, 306, 249),
	array('North-Western Nigeria', 'Coast', 'No', 7, 539, 498, 248, 233),
	array('Gao', 'Coast', 'Yes', 9, 402, 426, 210, 193),
	array('Burkina Faso', 'Land', 'No', 0, 359, 532, 166, 247),
	array('Cameroon', 'Coast', 'Yes', 0, 617, 658, 288, 302),
	array('Equatorial Guinea', 'Coast', 'No', 0, 623, 707, 291, 328),
	array('Gabon', 'Coast', 'No', 0, 628, 768, 292, 358),
	array('Luanda', 'Coast', 'Yes', 0, 686, 899, 327, 439),
	array('Juba', 'Coast', 'Yes', 0, 1011, 620, 468, 276),
	array('Abuja', 'Coast', 'Yes', 7, 571, 587, 265, 270),
	array('Eastern South Sudan', 'Coast', 'No', 0, 1043, 574, 484, 263),
	array('Omdurman', 'Coast', 'Yes', 0, 1025, 432, 487, 182),
	array('Eritrea', 'Coast', 'No', 0, 1149, 429, 545, 208),
	array('Amhara', 'Coast', 'Yes', 3, 1144, 495, 547, 252),
	array('Djibouti', 'Coast', 'No', 0, 1229, 534, 569, 244),
	array('Somaliland', 'Coast', 'No', 0, 1328, 549, 618, 254),
	array('Mogadishu', 'Coast', 'Yes', 9, 1298, 672, 601, 313),
	array('Nairobi', 'Coast', 'Yes', 0, 1117, 711, 518, 346),
	array('Mombasa', 'Coast', 'No', 0, 1181, 767, 553, 350),
	array('Southern Somalia', 'Coast', 'No', 0, 1220, 726, 584, 310),
	array('Uganda', 'Coast', 'Yes', 0, 1062, 703, 475, 339),
	array('Kivu', 'Land', 'Yes', 9, 972, 819, 448, 358),
	array('Lagos', 'Coast', 'Yes', 7, 543, 619, 252, 290),
	array('Liberia', 'Coast', 'No', 0, 262, 632, 121, 291),
	array('Guinea', 'Coast', 'No', 0, 182, 550, 85, 254),
	array('Guinea-Bissau', 'Coast', 'No', 0, 155, 520, 73, 239),
	array('Dakar', 'Coast', 'Yes', 0, 179, 457, 71, 201),
	array('The Gambia', 'Coast', 'No', 0, 133, 485, 66, 224),
	array('Southern Senegal', 'Coast', 'No', 0, 193, 482, 91, 224),
	array('Kayes', 'Coast', 'Yes', 5, 245, 487, 116, 211),
	array('Ghana', 'Coast', 'Yes', 0, 396, 636, 185, 295),
	array('Cote D\\\'Ivoire', 'Coast', 'Yes', 0, 316, 629, 152, 292),
	array('Sierra Leone', 'Coast', 'Yes', 0, 210, 591, 97, 274),
	array('Niamey', 'Coast', 'Yes', 0, 502, 465, 235, 218),
	array('Rwanda', 'Land', 'Yes', 0, 998, 767, 470, 356),
	array('Western Tanganyika', 'Coast', 'No', 0, 1064, 809, 510, 364),
	array('Dar es Salaam', 'Coast', 'Yes', 0, 1127, 872, 528, 384),
	array('Kasai', 'Coast', 'No', 1, 892, 810, 414, 369),
	array('Burundi', 'Land', 'No', 0, 997, 797, 466, 370),
	array('Lubumbashi', 'Coast', 'Yes', 1, 921, 917, 430, 416),
	array('Dire Dawa', 'Coast', 'Yes', 3, 1263, 613, 569, 297),
	array('Port Harcourt', 'Coast', 'No', 7, 581, 634, 271, 291),
	array('Eastern Zambia', 'Land', 'No', 0, 1000, 926, 473, 458),
	array('Lusaka', 'Land', 'No', 0, 871, 1024, 407, 466),
	array('Sikasso', 'Land', 'Yes', 5, 333, 501, 135, 250),
	array('Cabinda', 'Coast', 'No', 0, 655, 827, 306, 380),
	array('South Angola', 'Coast', 'Yes', 0, 669, 1044, 319, 467),
	array('Namibia', 'Coast', 'Yes', 0, 689, 1117, 319, 507),
	array('Botswana', 'Land', 'No', 0, 875, 1134, 417, 550),
	array('Lesotho', 'Land', 'No', 0, 965, 1313, 449, 608),
	array('Swaziland', 'Coast', 'No', 0, 1025, 1234, 477, 574),
	array('Kinshasa', 'Coast', 'Yes', 1, 689, 834, 321, 387),
	array('Zanzibar', 'Sea', 'No', 0, 1200, 822, 558, 396),
	array('Malawi', 'Land', 'Yes', 0, 1091, 1033, 498, 456),
	array('Mozambique', 'Coast', 'Yes', 0, 1136, 1046, 496, 544),
	array('Antananarivo', 'Coast', 'Yes', 4, 1336, 1045, 624, 489),
	array('Zimbabwe', 'Land', 'Yes', 9, 997, 1117, 458, 500),
	array('Johannesburg', 'Land', 'Yes', 8, 973, 1213, 462, 566),
	array('Orange Free State', 'Land', 'No', 8, 955, 1282, 421, 615),
	array('Port Elizabeth', 'Coast', 'No', 8, 949, 1356, 417, 640),
	array('South Madagascar', 'Coast', 'No', 4, 1306, 1137, 597, 522),
	array('Cape Town', 'Coast', 'Yes', 8, 849, 1383, 373, 651),
	array('Northern Cape', 'Coast', 'No', 8, 771, 1316, 359, 608),
	array('Durban', 'Coast', 'Yes', 8, 1006, 1268, 473, 587),
	array('Southern Nations, Nationalities & People\\\'s Region', 'Land', 'No', 3, 1138, 611, 521, 294),
	array('Mopti & S&eacute;gou', 'Coast', 'No', 5, 357, 470, 168, 214),
	array('&Eacute;quateur', 'Coast', 'Yes', 1, 813, 687, 376, 319),
	array('Cape Verde', 'Sea', 'No', 0, 18, 396, 9, 187),
	array('Hurghada', 'Land', 'No', 2, 1057, 278, 490, 116),
	array('Hurghada (East Coast)', 'Coast', 'No', 2, 1060, 245, 491, 107),
	array('Hurghada (West Coast)', 'Coast', 'No', 2, 1043, 284, 483, 142),
	array('Canary Islands', 'Coast', 'Yes', 0, 144, 200, 66, 92),
	array('Seychelles', 'Coast', 'Yes', 0, 1428, 835, 664, 388),
	array('Comoros', 'Coast', 'Yes', 4, 1280, 978, 595, 454),
	array('Mauritius', 'Coast', 'Yes', 4, 1494, 1121, 696, 521),
	array('St Helena', 'Coast', 'Yes', 0, 342, 1049, 158, 487),
	array('Bamako', 'Land', 'Yes', 5, 298, 509, 142, 218),
	array('Bamako (West Coast)', 'Coast', 'No', 5, 291, 448, 138, 212),
	array('Bamako (East Coast)', 'Coast', 'No', 5, 314, 467, 145, 224),
	array('R&eacute;union', 'Coast', 'Yes', 0, 1461, 1132, 680, 526),
	array('Tristan da Cunha', 'Coast', 'Yes', 0, 79, 1401, 36, 652),
	array('Togo & Benin', 'Land', 'No', 0, 461, 576, 218, 261),
	array('Togo & Benin (North Coast)', 'Coast', 'No', 0, 494, 514, 231, 241),
	array('Togo & Benin (South Coast)', 'Coast', 'No', 0, 482, 610, 219, 284),
	array('S&atilde;o Tom&eacute; and Pr&iacute;ncipe', 'Coast', 'Yes', 0, 556, 722, 258, 336),
	array('Republic of the Congo', 'Land', 'Yes', 0, 746, 707, 350, 328),
	array('Republic of the Congo (East Coast)', 'Coast', 'No', 0, 720, 773, 337, 358),
	array('Republic of the Congo (West Coast)', 'Coast', 'No', 0, 649, 796, 302, 371),
	array('Khartoum', 'Coast', 'Yes', 0, 1097, 405, 510, 192),
	array('Khartoum (East Coast)', 'Coast', 'No', 0, 1103, 325, 515, 155),
	array('Khartoum (West Coast)', 'Coast', 'No', 0, 1041, 480, 489, 222),
	array('Addis Ababa', 'Land', 'Yes', 3, 1168, 587, 542, 271),
	array('Addis Ababa (East Coast)', 'Coast', 'No', 3, 1186, 603, 555, 284),
	array('Addis Ababa (North Coast)', 'Coast', 'No', 3, 1088, 544, 514, 244)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('North Atlantic Ocean','Mid Atlantic Ocean','Yes','No'),
	array('North Atlantic Ocean','Strait of Gibraltar','Yes','No'),
	array('North Atlantic Ocean','Western Sahara','Yes','No'),
	array('North Atlantic Ocean','Northern Mauritania','Yes','No'),
	array('North Atlantic Ocean','Nouakchott','Yes','No'),
	array('North Atlantic Ocean','Casablanca','Yes','No'),
	array('North Atlantic Ocean','Marrakech','Yes','No'),
	array('North Atlantic Ocean','Dakar','Yes','No'),
	array('North Atlantic Ocean','Cape Verde','Yes','No'),
	array('North Atlantic Ocean','Canary Islands','Yes','No'),
	array('Western Mediterranean Sea','Central Mediterranean Sea','Yes','No'),
	array('Western Mediterranean Sea','Strait of Gibraltar','Yes','No'),
	array('Western Mediterranean Sea','Eastern Morocco','Yes','No'),
	array('Western Mediterranean Sea','Algiers','Yes','No'),
	array('Western Mediterranean Sea','Tunisia','Yes','No'),
	array('Central Mediterranean Sea','Aegean Sea','Yes','No'),
	array('Central Mediterranean Sea','Eastern Mediterranean Sea','Yes','No'),
	array('Central Mediterranean Sea','Benghazi','Yes','No'),
	array('Central Mediterranean Sea','Sirte','Yes','No'),
	array('Central Mediterranean Sea','Tripoli','Yes','No'),
	array('Central Mediterranean Sea','Tunisia','Yes','No'),
	array('Aegean Sea','Eastern Mediterranean Sea','Yes','No'),
	array('Eastern Mediterranean Sea','Suez Canal','Yes','No'),
	array('Eastern Mediterranean Sea','Cairo','Yes','No'),
	array('Eastern Mediterranean Sea','Alexandria','Yes','No'),
	array('Eastern Mediterranean Sea','Benghazi','Yes','No'),
	array('Suez Canal','Red Sea','Yes','No'),
	array('Suez Canal','Sinai','Yes','No'),
	array('Suez Canal','Cairo','Yes','No'),
	array('Suez Canal','Hurghada (East Coast)','Yes','No'),
	array('Red Sea','Gulf of Aden','Yes','No'),
	array('Red Sea','Sinai','Yes','No'),
	array('Red Sea','Eritrea','Yes','No'),
	array('Red Sea','Hurghada (East Coast)','Yes','No'),
	array('Red Sea','Khartoum (East Coast)','Yes','No'),
	array('Gulf of Aden','North Indian Ocean','Yes','No'),
	array('Gulf of Aden','Eritrea','Yes','No'),
	array('Gulf of Aden','Djibouti','Yes','No'),
	array('Gulf of Aden','Somaliland','Yes','No'),
	array('Gulf of Aden','Mogadishu','Yes','No'),
	array('North Indian Ocean','Mozambique Channel','Yes','No'),
	array('North Indian Ocean','Mogadishu','Yes','No'),
	array('North Indian Ocean','Southern Somalia','Yes','No'),
	array('North Indian Ocean','Dar es Salaam','Yes','No'),
	array('North Indian Ocean','Zanzibar','Yes','No'),
	array('North Indian Ocean','Mozambique','Yes','No'),
	array('North Indian Ocean','Seychelles','Yes','No'),
	array('North Indian Ocean','Comoros','Yes','No'),
	array('Mid Atlantic Ocean','Romanche Trench','Yes','No'),
	array('Mid Atlantic Ocean','Guinea','Yes','No'),
	array('Mid Atlantic Ocean','Guinea-Bissau','Yes','No'),
	array('Mid Atlantic Ocean','Dakar','Yes','No'),
	array('Mid Atlantic Ocean','The Gambia','Yes','No'),
	array('Mid Atlantic Ocean','Southern Senegal','Yes','No'),
	array('Mid Atlantic Ocean','Sierra Leone','Yes','No'),
	array('Mid Atlantic Ocean','Cape Verde','Yes','No'),
	array('Romanche Trench','Gulf of Guinea','Yes','No'),
	array('Romanche Trench','South-West Atlantic Ocean','Yes','No'),
	array('Romanche Trench','Liberia','Yes','No'),
	array('Romanche Trench','Sierra Leone','Yes','No'),
	array('Gulf of Guinea','Bight of Benin','Yes','No'),
	array('Gulf of Guinea','South-West Atlantic Ocean','Yes','No'),
	array('Gulf of Guinea','South-East Atlantic Ocean','Yes','No'),
	array('Gulf of Guinea','Ascension','Yes','No'),
	array('Gulf of Guinea','Gabon','Yes','No'),
	array('Gulf of Guinea','Luanda','Yes','No'),
	array('Gulf of Guinea','Liberia','Yes','No'),
	array('Gulf of Guinea','Ghana','Yes','No'),
	array('Gulf of Guinea','Cote D\\\'Ivoire','Yes','No'),
	array('Gulf of Guinea','Cabinda','Yes','No'),
	array('Gulf of Guinea','Kinshasa','Yes','No'),
	array('Gulf of Guinea','St Helena','Yes','No'),
	array('Gulf of Guinea','S&atilde;o Tom&eacute; and Pr&iacute;ncipe','Yes','No'),
	array('Gulf of Guinea','Republic of the Congo (West Coast)','Yes','No'),
	array('Bight of Benin','Lagos','Yes','No'),
	array('Bight of Benin','Ghana','Yes','No'),
	array('Bight of Benin','Togo & Benin (South Coast)','Yes','No'),
	array('Bight of Benin','S&atilde;o Tom&eacute; and Pr&iacute;ncipe','Yes','No'),
	array('South-West Atlantic Ocean','South-East Atlantic Ocean','Yes','No'),
	array('South-West Atlantic Ocean','Ascension','Yes','No'),
	array('South-West Atlantic Ocean','St Helena','Yes','No'),
	array('South-West Atlantic Ocean','Tristan da Cunha','Yes','No'),
	array('South-East Atlantic Ocean','Cape of Good Hope','Yes','No'),
	array('South-East Atlantic Ocean','Luanda','Yes','No'),
	array('South-East Atlantic Ocean','South Angola','Yes','No'),
	array('South-East Atlantic Ocean','Namibia','Yes','No'),
	array('South-East Atlantic Ocean','Northern Cape','Yes','No'),
	array('South-East Atlantic Ocean','St Helena','Yes','No'),
	array('South-East Atlantic Ocean','Tristan da Cunha','Yes','No'),
	array('Cape of Good Hope','South Indian Ocean','Yes','No'),
	array('Cape of Good Hope','Cape Town','Yes','No'),
	array('Cape of Good Hope','Northern Cape','Yes','No'),
	array('South Indian Ocean','Mozambique Channel','Yes','No'),
	array('South Indian Ocean','Mascarene Plateau','Yes','No'),
	array('South Indian Ocean','Swaziland','Yes','No'),
	array('South Indian Ocean','Mozambique','Yes','No'),
	array('South Indian Ocean','Port Elizabeth','Yes','No'),
	array('South Indian Ocean','South Madagascar','Yes','No'),
	array('South Indian Ocean','Cape Town','Yes','No'),
	array('South Indian Ocean','Durban','Yes','No'),
	array('South Indian Ocean','R&eacute;union','Yes','No'),
	array('Mozambique Channel','Mozambique','Yes','No'),
	array('Mozambique Channel','Antananarivo','Yes','No'),
	array('Mozambique Channel','South Madagascar','Yes','No'),
	array('Mozambique Channel','Comoros','Yes','No'),
	array('Mascarene Plateau','Antananarivo','Yes','No'),
	array('Mascarene Plateau','South Madagascar','Yes','No'),
	array('Mascarene Plateau','Seychelles','Yes','No'),
	array('Mascarene Plateau','Comoros','Yes','No'),
	array('Mascarene Plateau','Mauritius','Yes','No'),
	array('Mascarene Plateau','R&eacute;union','Yes','No'),
	array('Lake Victoria','Nairobi','Yes','No'),
	array('Lake Victoria','Uganda','Yes','No'),
	array('Lake Victoria','Western Tanganyika','Yes','No'),
	array('Strait of Gibraltar','Casablanca','Yes','No'),
	array('Strait of Gibraltar','Eastern Morocco','Yes','No'),
	array('Sinai','Cairo','Yes','Yes'),
	array('Cairo','Alexandria','Yes','Yes'),
	array('Cairo','Luxor','Yes','Yes'),
	array('Cairo','Hurghada','No','Yes'),
	array('Cairo','Hurghada (East Coast)','Yes','No'),
	array('Cairo','Hurghada (West Coast)','Yes','No'),
	array('Alexandria','Luxor','Yes','Yes'),
	array('Alexandria','Benghazi','Yes','Yes'),
	array('Luxor','Benghazi','No','Yes'),
	array('Luxor','Omdurman','Yes','Yes'),
	array('Luxor','Hurghada','No','Yes'),
	array('Luxor','Hurghada (West Coast)','Yes','No'),
	array('Benghazi','Sirte','Yes','Yes'),
	array('Benghazi','Fezzan','No','Yes'),
	array('Benghazi','North Chad','No','Yes'),
	array('Benghazi','Darfur','No','Yes'),
	array('Benghazi','Omdurman','No','Yes'),
	array('Sirte','Fezzan','No','Yes'),
	array('Sirte','Tripoli','Yes','Yes'),
	array('Fezzan','Tripoli','No','Yes'),
	array('Fezzan','North Chad','No','Yes'),
	array('Fezzan','Tamanrasset','No','Yes'),
	array('Fezzan','Agadez','No','Yes'),
	array('Tripoli','Tamanrasset','No','Yes'),
	array('Tripoli','Tunisia','Yes','Yes'),
	array('North Chad','N\\\'Djamena','No','Yes'),
	array('North Chad','Darfur','No','Yes'),
	array('North Chad','Agadez','No','Yes'),
	array('North Chad','South Niger','No','Yes'),
	array('N\\\'Djamena','Darfur','No','Yes'),
	array('N\\\'Djamena','Central African Republic','No','Yes'),
	array('N\\\'Djamena','South Niger','No','Yes'),
	array('N\\\'Djamena','Kano','No','Yes'),
	array('N\\\'Djamena','Cameroon','No','Yes'),
	array('Tamanrasset','Adrar','No','Yes'),
	array('Tamanrasset','Western Algeria','No','Yes'),
	array('Tamanrasset','Azawad','No','Yes'),
	array('Tamanrasset','Agadez','No','Yes'),
	array('Tamanrasset','Algiers','No','Yes'),
	array('Tamanrasset','Tunisia','No','Yes'),
	array('Adrar','Western Algeria','No','Yes'),
	array('Adrar','Azawad','No','Yes'),
	array('Adrar','Western Sahara','No','Yes'),
	array('Adrar','Northern Mauritania','No','Yes'),
	array('Adrar','Marrakech','No','Yes'),
	array('Western Algeria','Eastern Morocco','No','Yes'),
	array('Western Algeria','Marrakech','No','Yes'),
	array('Western Algeria','Algiers','No','Yes'),
	array('Darfur','Central African Republic','No','Yes'),
	array('Darfur','Juba','No','Yes'),
	array('Darfur','Omdurman','No','Yes'),
	array('Azawad','Northern Mauritania','No','Yes'),
	array('Azawad','Nouakchott','No','Yes'),
	array('Azawad','Timbuktu','No','Yes'),
	array('Azawad','Agadez','No','Yes'),
	array('Azawad','South Niger','No','Yes'),
	array('Azawad','Gao','No','Yes'),
	array('Western Sahara','Northern Mauritania','Yes','Yes'),
	array('Western Sahara','Marrakech','Yes','Yes'),
	array('Western Sahara','Canary Islands','Yes','No'),
	array('Northern Mauritania','Nouakchott','Yes','Yes'),
	array('Nouakchott','Timbuktu','No','Yes'),
	array('Nouakchott','Dakar','Yes','Yes'),
	array('Nouakchott','Kayes','Yes','Yes'),
	array('Nouakchott','Mopti & S&eacute;gou','No','Yes'),
	array('Nouakchott','Bamako','No','Yes'),
	array('Casablanca','Eastern Morocco','Yes','Yes'),
	array('Casablanca','Marrakech','Yes','Yes'),
	array('Eastern Morocco','Marrakech','No','Yes'),
	array('Eastern Morocco','Algiers','Yes','Yes'),
	array('Marrakech','Canary Islands','Yes','No'),
	array('Timbuktu','Gao','Yes','Yes'),
	array('Timbuktu','Mopti & S&eacute;gou','Yes','Yes'),
	array('Agadez','South Niger','No','Yes'),
	array('Central African Republic','Orientale','No','Yes'),
	array('Central African Republic','Cameroon','No','Yes'),
	array('Central African Republic','Juba','No','Yes'),
	array('Central African Republic','&Eacute;quateur','No','Yes'),
	array('Central African Republic','Republic of the Congo','No','Yes'),
	array('Orientale','Juba','No','Yes'),
	array('Orientale','Uganda','No','Yes'),
	array('Orientale','Kivu','No','Yes'),
	array('Orientale','Kasai','Yes','Yes'),
	array('Orientale','&Eacute;quateur','Yes','Yes'),
	array('South Niger','Kano','No','Yes'),
	array('South Niger','North-Western Nigeria','No','Yes'),
	array('South Niger','Gao','No','Yes'),
	array('South Niger','Niamey','No','Yes'),
	array('Algiers','Tunisia','Yes','Yes'),
	array('Ascension','St Helena','Yes','No'),
	array('Kano','North-Western Nigeria','No','Yes'),
	array('Kano','Cameroon','No','Yes'),
	array('Kano','Abuja','No','Yes'),
	array('Kano','Port Harcourt','No','Yes'),
	array('North-Western Nigeria','Abuja','Yes','Yes'),
	array('North-Western Nigeria','Lagos','Yes','Yes'),
	array('North-Western Nigeria','Niamey','Yes','Yes'),
	array('Gao','Burkina Faso','No','Yes'),
	array('Gao','Niamey','Yes','Yes'),
	array('Gao','Mopti & S&eacute;gou','No','Yes'),
	array('Burkina Faso','Ghana','No','Yes'),
	array('Burkina Faso','Cote D\\\'Ivoire','No','Yes'),
	array('Burkina Faso','Niamey','No','Yes'),
	array('Burkina Faso','Sikasso','No','Yes'),
	array('Burkina Faso','Mopti & S&eacute;gou','No','Yes'),
	array('Burkina Faso','Togo & Benin','No','Yes'),
	array('Cameroon','Equatorial Guinea','Yes','Yes'),
	array('Cameroon','Gabon','No','Yes'),
	array('Cameroon','Port Harcourt','Yes','Yes'),
	array('Cameroon','S&atilde;o Tom&eacute; and Pr&iacute;ncipe','Yes','No'),
	array('Cameroon','Republic of the Congo','No','Yes'),
	array('Equatorial Guinea','Gabon','Yes','Yes'),
	array('Equatorial Guinea','S&atilde;o Tom&eacute; and Pr&iacute;ncipe','Yes','No'),
	array('Gabon','S&atilde;o Tom&eacute; and Pr&iacute;ncipe','Yes','No'),
	array('Gabon','Republic of the Congo','No','Yes'),
	array('Gabon','Republic of the Congo (West Coast)','Yes','No'),
	array('Luanda','Kasai','No','Yes'),
	array('Luanda','Lubumbashi','No','Yes'),
	array('Luanda','Lusaka','No','Yes'),
	array('Luanda','South Angola','Yes','Yes'),
	array('Luanda','Kinshasa','Yes','Yes'),
	array('Juba','Eastern South Sudan','Yes','Yes'),
	array('Juba','Omdurman','Yes','Yes'),
	array('Juba','Uganda','Yes','Yes'),
	array('Abuja','Lagos','Yes','Yes'),
	array('Abuja','Port Harcourt','Yes','Yes'),
	array('Eastern South Sudan','Omdurman','Yes','Yes'),
	array('Eastern South Sudan','Nairobi','No','Yes'),
	array('Eastern South Sudan','Uganda','Yes','Yes'),
	array('Eastern South Sudan','Southern Nations, Nationalities & People\\\'s Region','No','Yes'),
	array('Eastern South Sudan','Khartoum','No','Yes'),
	array('Eastern South Sudan','Khartoum (West Coast)','Yes','No'),
	array('Eastern South Sudan','Addis Ababa','No','Yes'),
	array('Omdurman','Khartoum','No','Yes'),
	array('Omdurman','Khartoum (West Coast)','Yes','No'),
	array('Eritrea','Amhara','No','Yes'),
	array('Eritrea','Djibouti','Yes','Yes'),
	array('Eritrea','Khartoum','No','Yes'),
	array('Eritrea','Khartoum (East Coast)','Yes','No'),
	array('Amhara','Djibouti','No','Yes'),
	array('Amhara','Dire Dawa','No','Yes'),
	array('Amhara','Khartoum','No','Yes'),
	array('Amhara','Addis Ababa','No','Yes'),
	array('Amhara','Addis Ababa (North Coast)','Yes','No'),
	array('Djibouti','Somaliland','Yes','Yes'),
	array('Djibouti','Dire Dawa','No','Yes'),
	array('Somaliland','Mogadishu','Yes','Yes'),
	array('Somaliland','Dire Dawa','No','Yes'),
	array('Mogadishu','Southern Somalia','Yes','Yes'),
	array('Mogadishu','Dire Dawa','Yes','Yes'),
	array('Nairobi','Mombasa','No','Yes'),
	array('Nairobi','Uganda','Yes','Yes'),
	array('Nairobi','Western Tanganyika','Yes','Yes'),
	array('Nairobi','Dar es Salaam','No','Yes'),
	array('Nairobi','Southern Nations, Nationalities & People\\\'s Region','No','Yes'),
	array('Nairobi','Addis Ababa','No','Yes'),
	array('Mombasa','Southern Somalia','Yes','Yes'),
	array('Mombasa','Dar es Salaam','Yes','Yes'),
	array('Mombasa','Dire Dawa','No','Yes'),
	array('Mombasa','Zanzibar','Yes','No'),
	array('Mombasa','Addis Ababa','No','Yes'),
	array('Southern Somalia','Dire Dawa','Yes','Yes'),
	array('Southern Somalia','Zanzibar','Yes','No'),
	array('Uganda','Kivu','No','Yes'),
	array('Uganda','Rwanda','No','Yes'),
	array('Uganda','Western Tanganyika','Yes','Yes'),
	array('Kivu','Rwanda','No','Yes'),
	array('Kivu','Western Tanganyika','No','Yes'),
	array('Kivu','Kasai','No','Yes'),
	array('Kivu','Burundi','No','Yes'),
	array('Kivu','Lubumbashi','No','Yes'),
	array('Lagos','Port Harcourt','Yes','Yes'),
	array('Lagos','Togo & Benin','No','Yes'),
	array('Lagos','Togo & Benin (North Coast)','Yes','No'),
	array('Lagos','Togo & Benin (South Coast)','Yes','No'),
	array('Lagos','S&atilde;o Tom&eacute; and Pr&iacute;ncipe','Yes','No'),
	array('Liberia','Guinea','No','Yes'),
	array('Liberia','Cote D\\\'Ivoire','Yes','Yes'),
	array('Liberia','Sierra Leone','Yes','Yes'),
	array('Guinea','Guinea-Bissau','Yes','Yes'),
	array('Guinea','Southern Senegal','No','Yes'),
	array('Guinea','Kayes','No','Yes'),
	array('Guinea','Cote D\\\'Ivoire','No','Yes'),
	array('Guinea','Sierra Leone','Yes','Yes'),
	array('Guinea','Sikasso','No','Yes'),
	array('Guinea','Bamako','No','Yes'),
	array('Guinea-Bissau','Southern Senegal','Yes','Yes'),
	array('Dakar','The Gambia','Yes','Yes'),
	array('Dakar','Southern Senegal','No','Yes'),
	array('Dakar','Kayes','Yes','Yes'),
	array('The Gambia','Southern Senegal','Yes','Yes'),
	array('Southern Senegal','Kayes','No','Yes'),
	array('Kayes','Bamako','No','Yes'),
	array('Kayes','Bamako (West Coast)','Yes','No'),
	array('Ghana','Cote D\\\'Ivoire','Yes','Yes'),
	array('Ghana','Togo & Benin','No','Yes'),
	array('Ghana','Togo & Benin (South Coast)','Yes','No'),
	array('Cote D\\\'Ivoire','Sikasso','No','Yes'),
	array('Niamey','Togo & Benin','No','Yes'),
	array('Niamey','Togo & Benin (North Coast)','Yes','No'),
	array('Rwanda','Western Tanganyika','No','Yes'),
	array('Rwanda','Burundi','No','Yes'),
	array('Western Tanganyika','Dar es Salaam','No','Yes'),
	array('Western Tanganyika','Burundi','No','Yes'),
	array('Western Tanganyika','Lubumbashi','No','Yes'),
	array('Western Tanganyika','Eastern Zambia','No','Yes'),
	array('Dar es Salaam','Eastern Zambia','No','Yes'),
	array('Dar es Salaam','Zanzibar','Yes','No'),
	array('Dar es Salaam','Malawi','No','Yes'),
	array('Dar es Salaam','Mozambique','Yes','Yes'),
	array('Kasai','Lubumbashi','Yes','Yes'),
	array('Kasai','Kinshasa','No','Yes'),
	array('Kasai','&Eacute;quateur','No','Yes'),
	array('Lubumbashi','Eastern Zambia','No','Yes'),
	array('Lubumbashi','Lusaka','No','Yes'),
	array('Dire Dawa','Addis Ababa','No','Yes'),
	array('Dire Dawa','Addis Ababa (East Coast)','Yes','No'),
	array('Port Harcourt','S&atilde;o Tom&eacute; and Pr&iacute;ncipe','Yes','No'),
	array('Eastern Zambia','Lusaka','No','Yes'),
	array('Eastern Zambia','Malawi','No','Yes'),
	array('Eastern Zambia','Mozambique','No','Yes'),
	array('Lusaka','South Angola','No','Yes'),
	array('Lusaka','Botswana','No','Yes'),
	array('Lusaka','Mozambique','No','Yes'),
	array('Lusaka','Zimbabwe','No','Yes'),
	array('Sikasso','Mopti & S&eacute;gou','No','Yes'),
	array('Sikasso','Bamako','No','Yes'),
	array('Cabinda','Kinshasa','Yes','Yes'),
	array('Cabinda','Republic of the Congo','No','Yes'),
	array('Cabinda','Republic of the Congo (East Coast)','Yes','No'),
	array('Cabinda','Republic of the Congo (West Coast)','Yes','No'),
	array('South Angola','Namibia','Yes','Yes'),
	array('South Angola','Botswana','No','Yes'),
	array('Namibia','Botswana','No','Yes'),
	array('Namibia','Northern Cape','Yes','Yes'),
	array('Botswana','Zimbabwe','No','Yes'),
	array('Botswana','Johannesburg','No','Yes'),
	array('Botswana','Northern Cape','No','Yes'),
	array('Lesotho','Orange Free State','No','Yes'),
	array('Lesotho','Port Elizabeth','No','Yes'),
	array('Lesotho','Durban','No','Yes'),
	array('Swaziland','Mozambique','Yes','Yes'),
	array('Swaziland','Johannesburg','No','Yes'),
	array('Swaziland','Durban','Yes','Yes'),
	array('Kinshasa','&Eacute;quateur','Yes','Yes'),
	array('Kinshasa','Republic of the Congo','No','Yes'),
	array('Kinshasa','Republic of the Congo (East Coast)','Yes','No'),
	array('Malawi','Mozambique','No','Yes'),
	array('Mozambique','Zimbabwe','No','Yes'),
	array('Mozambique','Johannesburg','No','Yes'),
	array('Antananarivo','South Madagascar','Yes','Yes'),
	array('Antananarivo','Comoros','Yes','No'),
	array('Zimbabwe','Johannesburg','No','Yes'),
	array('Johannesburg','Orange Free State','No','Yes'),
	array('Johannesburg','Northern Cape','No','Yes'),
	array('Johannesburg','Durban','No','Yes'),
	array('Orange Free State','Port Elizabeth','No','Yes'),
	array('Orange Free State','Northern Cape','No','Yes'),
	array('Orange Free State','Durban','No','Yes'),
	array('Port Elizabeth','Cape Town','Yes','Yes'),
	array('Port Elizabeth','Northern Cape','No','Yes'),
	array('Port Elizabeth','Durban','Yes','Yes'),
	array('Cape Town','Northern Cape','Yes','Yes'),
	array('Southern Nations, Nationalities & People\\\'s Region','Addis Ababa','No','Yes'),
	array('Mopti & S&eacute;gou','Bamako','No','Yes'),
	array('Mopti & S&eacute;gou','Bamako (East Coast)','Yes','No'),
	array('&Eacute;quateur','Republic of the Congo','No','Yes'),
	array('&Eacute;quateur','Republic of the Congo (East Coast)','Yes','No'),
	array('Hurghada','Khartoum','No','Yes'),
	array('Hurghada (East Coast)','Khartoum (East Coast)','Yes','No'),
	array('Hurghada (West Coast)','Khartoum (West Coast)','Yes','No'),
	array('Seychelles','Comoros','Yes','No'),
	array('Seychelles','Mauritius','Yes','No'),
	array('Mauritius','R&eacute;union','Yes','No'),
	array('Khartoum','Addis Ababa','No','Yes'),
	array('Khartoum (West Coast)','Addis Ababa (North Coast)','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
