<?php
/*
	Copyright (C) 2010 Oliver Auth

	This file is part of the Imperium variant for webDiplomacy

	The Imperium variant for webDiplomacy is free software: you can redistribute
	it and/or modify it under the terms of the GNU Affero General Public License
	as published by the Free Software Foundation, either version 3 of the License,
	or (at your option) any later version.

	The Imperium variant for webDiplomacy is distributed in the hope that it will
	be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of 
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
	See the GNU General Public License for more details.

	You should have received a copy of the GNU Affero General Public License
	along with webDiplomacy. If not, see <http://www.gnu.org/licenses/>.

*/

defined('IN_CODE') or die('This script can not be run by itself.');

require_once("variants/install.php");

global $DB;

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Alamanni'              , 'Land' , 'No' , 438 , 245, 217, 121, 'Alamanni'),
	array('Langobardi'            , 'Land' , 'No' , 480 , 104, 246, 53 , 'Alamanni'),
	array('Quadi'                 , 'Land' , 'No' , 650 , 225, 327, 112, 'Alamanni'),
	array('Vandales'              , 'Land' , 'No' , 490 , 205, 244, 102, 'Vandali' ),
	array('Asdingi'               , 'Land' , 'No' , 750 , 235, 365, 121, 'Vandali' ),
	array('Silingi'               , 'Land' , 'No' , 640 , 130, 320, 62 , 'Vandali' ),
	array('Ostrogothi'            , 'Coast', 'No' , 1092, 269, 540, 148, 'Gothi'   ),
	array('Visigothi'             , 'Land' , 'No' , 845 , 230, 423, 118, 'Gothi'   ),
	array('Dacia'                 , 'Coast', 'No' , 725 , 425, 351, 228, 'Gothi'   ),
	array('Franci'                , 'Land' , 'No' , 404 , 120, 202, 62 , 'Franci'  ),
	array('Ripuari'               , 'Land' , 'No' , 530 , 143, 265, 72 , 'Franci'  ),
	array('Suebi'                 , 'Land' , 'No' , 586 , 212, 293, 107, 'Franci'  ),
	array('Hunni Primi'           , 'Land' , 'No' , 690 , 48 , 346, 27 , 'Hunni'   ),
	array('Hunni Secundi'         , 'Land' , 'No' , 720 , 178, 362, 89 , 'Hunni'   ),
	array('Hunni Terti'           , 'Land' , 'No' , 800 , 98 , 395, 58 , 'Hunni'   ),
	array('Hunni Quarti'          , 'Coast', 'No' , 932 , 310, 466, 156, 'Hunni'   ),
	array('Jutii'                 , 'Coast', 'No' , 440 , 67 , 225, 38 , 'Saxones' ),
	array('Iazygi'                , 'Land' , 'No' , 780 , 340, 400, 180, 'Saxones' ),
	array('Teutones'              , 'Land' , 'No' , 444 , 162, 222, 82 , 'Saxones' ),
	array('Mare Adriaticum'       , 'Sea'  , 'No' , 585 , 415, 310, 225, 'Neutral' ),
	array('Aegaeis'               , 'Sea'  , 'No' , 830 , 592, 417, 300, 'Neutral' ),
	array('Aemilia'               , 'Land' , 'No' , 461 , 333, 231, 163, 'Neutral' ),
	array('Alexandria'            , 'Coast', 'Yes', 968 , 772, 487, 388, 'Neutral' ),
	array('Alpes'                 , 'Coast', 'No' , 412 , 375, 205, 175, 'Neutral' ),
	array('Ancona'                , 'Coast', 'Yes', 540 , 426, 268, 216, 'Neutral' ),
	array('Antiochia'             , 'Coast', 'Yes', 1112, 625, 558, 310, 'Neutral' ),
	array('Aquitania'             , 'Coast', 'No' , 250 , 330, 130, 163, 'Neutral' ),
	array('Athenum'               , 'Coast', 'Yes', 765 , 583, 380, 292, 'Neutral' ),
	array('Oceanus Atlanticus'    , 'Sea'  , 'No' , 35  , 330, 16 , 165, 'Neutral' ),
	array('Baetica'               , 'Coast', 'No' , 150 , 570, 75 , 280, 'Neutral' ),
	array('Baleares'              , 'Sea'  , 'No' , 350 , 542, 181, 271, 'Neutral' ),
	array('Belgica'               , 'Coast', 'No' , 294 , 176, 147, 89 , 'Neutral' ),
	array('Oceanus Britannicus'   , 'Sea'  , 'No' , 50  , 178, 20 , 95 , 'Neutral' ),
	array('Brundisium'            , 'Coast', 'Yes', 622 , 505, 311, 247, 'Neutral' ),
	array('Burdigala'             , 'Coast', 'Yes', 214 , 398, 110, 198, 'Neutral' ),
	array('Byzantium'             , 'Coast', 'Yes', 900 , 484, 473, 247, 'Neutral' ),
	array('Mare Cantabricum'      , 'Sea'  , 'No' , 122 , 340, 65 , 168, 'Neutral' ),
	array('Capova'                , 'Coast', 'Yes', 570 , 493, 290, 249, 'Neutral' ),
	array('Carthago'              , 'Coast', 'Yes', 430 , 630, 215, 313, 'Neutral' ),
	array('Chatti'                , 'Land' , 'No' , 577 , 178, 290, 88 , 'Neutral' ),
	array('Chersonesus'           , 'Coast', 'Yes', 1035, 343, 519, 173, 'Neutral' ),
	array('Colonia Agrippa'       , 'Coast', 'Yes', 365 , 180, 185, 95 , 'Neutral' ),
	array('Mare Cypris'           , 'Sea'  , 'No' , 950 , 680, 462, 340, 'Neutral' ),
	array('Dalmatia'              , 'Coast', 'No' , 630 , 375, 305, 195, 'Neutral' ),
	array('Eburacum'              , 'Coast', 'Yes', 170 , 32 , 86 , 10 , 'Neutral' ),
	array('Eburacum (West Coast)' , 'Coast', 'No' , 140 , 30 , 70 , 11 , 'Neutral' ),
	array('Eburacum (East Coast)' , 'Coast', 'No' , 215 , 40 , 108, 20 , 'Neutral' ),
	array('Pontus Euxinus'        , 'Sea'  , 'No' , 1030, 414, 502, 205, 'Neutral' ),
	array('Flavia Caesarensis'    , 'Coast', 'No' , 142 , 88 , 73 , 50 , 'Neutral' ),
	array('Frisii'                , 'Coast', 'No' , 375 , 78 , 189, 42 , 'Neutral' ),
	array('Galatia'               , 'Coast', 'No' , 970 , 538, 490, 269, 'Neutral' ),
	array('Genova'                , 'Coast', 'Yes', 466 , 374, 234, 187, 'Neutral' ),
	array('Mare Germanicum'       , 'Sea'  , 'No' , 330 , 30 , 160, 22 , 'Neutral' ),
	array('Haithabu'              , 'Coast', 'Yes', 532 , 50 , 268, 30 , 'Neutral' ),
	array('Mare Internum'         , 'Sea'  , 'No' , 664 , 668, 335, 340, 'Neutral' ),
	array('Mare Ionium'           , 'Sea'  , 'No' , 668 , 566, 337, 282, 'Neutral' ),
	array('Mare Ligusticum'       , 'Sea'  , 'No' , 412 , 430, 206, 218, 'Neutral' ),
	array('Londinum'              , 'Coast', 'Yes', 170 , 141, 95 , 74 , 'Neutral' ),
	array('Lugdunensis'           , 'Coast', 'No' , 206 , 257, 75 , 128, 'Neutral' ),
	array('Lutetia'               , 'Land' , 'Yes', 300 , 245, 155, 124, 'Neutral' ),
	array('Lybia'                 , 'Coast', 'No' , 765 , 755, 382, 378, 'Neutral' ),
	array('Macedonia'             , 'Coast', 'No' , 742 , 512, 368, 252, 'Neutral' ),
	array('Macedonia (West Coast)', 'Coast', 'No' , 700 , 508, 351, 252, 'Neutral' ),
	array('Macedonia (East Coast)', 'Coast', 'No' , 775 , 525, 397, 257, 'Neutral' ),
	array('Massilia'              , 'Coast', 'Yes', 375 , 400, 187, 196, 'Neutral' ),
	array('Mauretania'            , 'Coast', 'No' , 220 , 694, 110, 347, 'Neutral' ),
	array('Maxima Caesarensis'    , 'Coast', 'No' , 194 , 84 , 97 , 44 , 'Neutral' ),
	array('Miletus'               , 'Coast', 'Yes', 920 , 580, 459, 289, 'Neutral' ),
	array('Narbonensis'           , 'Coast', 'No' , 285 , 420, 152, 203, 'Neutral' ),
	array('Numidia'               , 'Coast', 'No' , 496 , 754, 248, 372, 'Neutral' ),
	array('Olisipo'               , 'Coast', 'Yes', 55  , 528, 20 , 268, 'Neutral' ),
	array('Orientes'              , 'Coast', 'No' , 1110, 730, 555, 358, 'Neutral' ),
	array('Pontica'               , 'Coast', 'No' , 1080, 492, 550, 255, 'Neutral' ),
	array('Ravenna'               , 'Coast', 'Yes', 505 , 382, 259, 191, 'Neutral' ),
	array('Castra Regina'         , 'Land' , 'Yes', 494 , 263, 244, 134, 'Neutral' ),
	array('Rhegium'               , 'Coast', 'Yes', 610 , 535, 310, 273, 'Neutral' ),
	array('Roma'                  , 'Coast', 'Yes', 535 , 463, 270, 232, 'Neutral' ),
	array('Rotomagus'             , 'Coast', 'Yes', 249 , 215, 105, 113, 'Neutral' ),
	array('Saguntum'              , 'Coast', 'Yes', 217 , 500, 120, 241, 'Neutral' ),
	array('Samnium'               , 'Coast', 'No' , 580 , 460, 296, 239, 'Neutral' ),
	array('Litus Saxonicum'       , 'Sea'  , 'No' , 240 , 177, 115, 91 , 'Neutral' ),
	array('Scytia'                , 'Coast', 'No' , 870 , 418, 439, 209, 'Neutral' ),
	array('Sequanorum'            , 'Land' , 'No' , 385 , 285, 192, 142, 'Neutral' ),
	array('Syracusae'             , 'Coast', 'Yes', 560 , 586, 285, 295, 'Neutral' ),
	array('Taraconensis'          , 'Coast', 'No' , 135 , 445, 40 , 220, 'Neutral' ),
	array('Thracia'               , 'Coast', 'No' , 835 , 457, 417, 240, 'Neutral' ),
	array('Tuscia'                , 'Coast', 'No' , 495 , 423, 248, 213, 'Neutral' ),
	array('Mare Tyrrhenicum'      , 'Sea'  , 'No' , 520 , 520, 255, 263, 'Neutral' ),
	array('Verona'                , 'Coast', 'Yes', 525 , 328, 264, 163, 'Neutral' ),
	array('Viennensis'            , 'Land' , 'No' , 336 , 310, 169, 140, 'Neutral' ),
	array('Vindobona'             , 'Land' , 'Yes', 616 , 296, 308, 148, 'Neutral' )	
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $x, $y, $sx, $sy, $country)=$territoryRawRow;
	if( $country=='Neutral' )
		$countryID=0;
	else
		$countryID=$this->countryID($country);
		
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Mare Adriaticum'       , 'Brundisium'            , 'Yes', 'No'  ),
	array('Mare Adriaticum'       , 'Samnium'               , 'Yes', 'No'  ),
	array('Mare Adriaticum'       , 'Ancona'                , 'Yes', 'No'  ),
	array('Mare Adriaticum'       , 'Ravenna'               , 'Yes', 'No'  ),
	array('Mare Adriaticum'       , 'Verona'                , 'Yes', 'No'  ),
	array('Mare Adriaticum'       , 'Dalmatia'              , 'Yes', 'No'  ),
	array('Mare Adriaticum'       , 'Dacia'                 , 'Yes', 'No'  ),
	array('Mare Adriaticum'       , 'Macedonia (West Coast)', 'Yes', 'No'  ),
	array('Mare Adriaticum'       , 'Mare Ionium'           , 'Yes', 'No'  ),
	array('Aegaeis'               , 'Athenum'               , 'Yes', 'No'  ),
	array('Aegaeis'               , 'Macedonia (East Coast)', 'Yes', 'No'  ),
	array('Aegaeis'               , 'Thracia'               , 'Yes', 'No'  ),
	array('Aegaeis'               , 'Byzantium'             , 'Yes', 'No'  ),
	array('Aegaeis'               , 'Galatia'               , 'Yes', 'No'  ),
	array('Aegaeis'               , 'Miletus'               , 'Yes', 'No'  ),
	array('Aegaeis'               , 'Mare Cypris'           , 'Yes', 'No'  ),
	array('Aegaeis'               , 'Mare Internum'         , 'Yes', 'No'  ),
	array('Aemilia'               , 'Castra Regina'         , 'No' , 'Yes' ),
	array('Aemilia'               , 'Verona'                , 'No' , 'Yes' ),
	array('Aemilia'               , 'Ravenna'               , 'No' , 'Yes' ),
	array('Aemilia'               , 'Genova'                , 'No' , 'Yes' ),
	array('Aemilia'               , 'Alpes'                 , 'No' , 'Yes' ),
	array('Alamanni'              , 'Castra Regina'         , 'No' , 'Yes' ),
	array('Alamanni'              , 'Sequanorum'            , 'No' , 'Yes' ),
	array('Alamanni'              , 'Colonia Agrippa'       , 'No' , 'Yes' ),
	array('Alamanni'              , 'Vandales'              , 'No' , 'Yes' ),
	array('Alexandria'            , 'Lybia'                 , 'Yes', 'Yes' ),
	array('Alexandria'            , 'Mare Cypris'           , 'Yes', 'No'  ),
	array('Alexandria'            , 'Orientes'              , 'No' , 'Yes' ),
	array('Alpes'                 , 'Genova'                , 'Yes', 'Yes' ),
	array('Alpes'                 , 'Mare Ligusticum'       , 'Yes', 'No'  ),
	array('Alpes'                 , 'Massilia'              , 'Yes', 'Yes' ),
	array('Alpes'                 , 'Viennensis'            , 'No' , 'Yes' ),
	array('Alpes'                 , 'Sequanorum'            , 'No' , 'Yes' ),
	array('Alpes'                 , 'Castra Regina'         , 'No' , 'Yes' ),
	array('Alpes'                 , 'Aemilia'               , 'No' , 'Yes' ),
	array('Ancona'                , 'Ravenna'               , 'Yes', 'Yes' ),
	array('Ancona'                , 'Mare Adriaticum'       , 'Yes', 'No'  ),
	array('Ancona'                , 'Samnium'               , 'Yes', 'Yes' ),
	array('Ancona'                , 'Tuscia'                , 'No' , 'Yes' ),
	array('Ancona'                , 'Roma'                  , 'No' , 'Yes' ),
	array('Antiochia'             , 'Orientes'              , 'Yes', 'Yes' ),
	array('Antiochia'             , 'Mare Cypris'           , 'Yes', 'No'  ),
	array('Antiochia'             , 'Miletus'               , 'Yes', 'Yes' ),
	array('Antiochia'             , 'Galatia'               , 'No' , 'Yes' ),
	array('Antiochia'             , 'Pontica'               , 'No' , 'Yes' ),
	array('Aquitania'             , 'Burdigala'             , 'Yes', 'Yes' ),
	array('Aquitania'             , 'Mare Cantabricum'      , 'Yes', 'No'  ),
	array('Aquitania'             , 'Lugdunensis'           , 'Yes', 'Yes' ),
	array('Aquitania'             , 'Lutetia'               , 'No' , 'Yes' ),
	array('Aquitania'             , 'Viennensis'            , 'No' , 'Yes' ),
	array('Aquitania'             , 'Massilia'              , 'No' , 'Yes' ),
	array('Aquitania'             , 'Narbonensis'           , 'No' , 'Yes' ),
	array('Asdingi'               , 'Quadi'                 , 'No' , 'Yes' ),
	array('Asdingi'               , 'Hunni Secundi'         , 'No' , 'Yes' ),
	array('Asdingi'               , 'Visigothi'             , 'No' , 'Yes' ),
	array('Asdingi'               , 'Iazygi'                , 'No' , 'Yes' ),
	array('Asdingi'               , 'Vindobona'             , 'No' , 'Yes' ),
	array('Athenum'               , 'Macedonia (West Coast)', 'Yes', 'No'  ),
	array('Athenum'               , 'Macedonia (East Coast)', 'Yes', 'No'  ),
	array('Athenum'               , 'Aegaeis'               , 'Yes', 'No'  ),
	array('Athenum'               , 'Mare Internum'         , 'Yes', 'No'  ),
	array('Athenum'               , 'Mare Ionium'           , 'Yes', 'No'  ),
	array('Athenum'               , 'Macedonia'             , 'No' , 'Yes' ),
	array('Oceanus Atlanticus'    , 'Oceanus Britannicus'   , 'Yes', 'No'  ),
	array('Oceanus Atlanticus'    , 'Mare Cantabricum'      , 'Yes', 'No'  ),
	array('Oceanus Atlanticus'    , 'Taraconensis'          , 'Yes', 'No'  ),
	array('Oceanus Atlanticus'    , 'Olisipo'               , 'Yes', 'No'  ),
	array('Oceanus Atlanticus'    , 'Baetica'               , 'Yes', 'No'  ),
	array('Oceanus Atlanticus'    , 'Baleares'              , 'Yes', 'No'  ),
	array('Oceanus Atlanticus'    , 'Mauretania'            , 'Yes', 'No'  ),
	array('Baetica'               , 'Olisipo'               , 'Yes', 'Yes' ),
	array('Baetica'               , 'Oceanus Atlanticus'    , 'Yes', 'No'  ),
	array('Baetica'               , 'Baleares'              , 'Yes', 'No'  ),
	array('Baetica'               , 'Saguntum'              , 'Yes', 'Yes' ),
	array('Baetica'               , 'Taraconensis'          , 'No' , 'Yes' ),
	array('Baetica'               , 'Mauretania'            , 'Yes', 'Yes' ),
	array('Baleares'              , 'Oceanus Atlanticus'    , 'Yes', 'No'  ),
	array('Baleares'              , 'Baetica'               , 'Yes', 'No'  ),
	array('Baleares'              , 'Saguntum'              , 'Yes', 'No'  ),
	array('Baleares'              , 'Mare Ligusticum'       , 'Yes', 'No'  ),
	array('Baleares'              , 'Mare Tyrrhenicum'      , 'Yes', 'No'  ),
	array('Baleares'              , 'Carthago'              , 'Yes', 'No'  ),
	array('Baleares'              , 'Mauretania'            , 'Yes', 'No'  ),
	array('Belgica'               , 'Rotomagus'             , 'Yes', 'Yes' ),
	array('Belgica'               , 'Litus Saxonicum'       , 'Yes', 'No'  ),
	array('Belgica'               , 'Mare Germanicum'       , 'Yes', 'No'  ),
	array('Belgica'               , 'Colonia Agrippa'       , 'Yes', 'Yes' ),
	array('Belgica'               , 'Lutetia'               , 'No' , 'Yes' ),
	array('Oceanus Britannicus'   , 'Oceanus Atlanticus'    , 'Yes', 'No'  ),
	array('Oceanus Britannicus'   , 'Mare Cantabricum'      , 'Yes', 'No'  ),
	array('Oceanus Britannicus'   , 'Lugdunensis'           , 'Yes', 'No'  ),
	array('Oceanus Britannicus'   , 'Rotomagus'             , 'Yes', 'No'  ),
	array('Oceanus Britannicus'   , 'Litus Saxonicum'       , 'Yes', 'No'  ),
	array('Oceanus Britannicus'   , 'Londinum'              , 'Yes', 'No'  ),
	array('Oceanus Britannicus'   , 'Flavia Caesarensis'    , 'Yes', 'No'  ),
	array('Oceanus Britannicus'   , 'Eburacum (West Coast)' , 'Yes', 'No'  ),
	array('Brundisium'            , 'Samnium'               , 'Yes', 'Yes' ),
	array('Brundisium'            , 'Mare Adriaticum'       , 'Yes', 'No'  ),
	array('Brundisium'            , 'Mare Ionium'           , 'Yes', 'No'  ),
	array('Brundisium'            , 'Rhegium'               , 'Yes', 'Yes' ),
	array('Brundisium'            , 'Capova'                , 'No' , 'Yes' ),
	array('Burdigala'             , 'Taraconensis'          , 'Yes', 'Yes' ),
	array('Burdigala'             , 'Mare Cantabricum'      , 'Yes', 'No'  ),
	array('Burdigala'             , 'Aquitania'             , 'Yes', 'Yes' ),
	array('Burdigala'             , 'Narbonensis'           , 'No' , 'Yes' ),
	array('Byzantium'             , 'Scytia'                , 'Yes', 'Yes' ),
	array('Byzantium'             , 'Pontus Euxinus'        , 'Yes', 'No'  ),
	array('Byzantium'             , 'Pontica'               , 'Yes', 'Yes' ),
	array('Byzantium'             , 'Galatia'               , 'Yes', 'Yes' ),
	array('Byzantium'             , 'Aegaeis'               , 'Yes', 'No'  ),
	array('Byzantium'             , 'Thracia'               , 'Yes', 'Yes' ),
	array('Mare Cantabricum'      , 'Oceanus Atlanticus'    , 'Yes', 'No'  ),
	array('Mare Cantabricum'      , 'Oceanus Britannicus'   , 'Yes', 'No'  ),
	array('Mare Cantabricum'      , 'Lugdunensis'           , 'Yes', 'No'  ),
	array('Mare Cantabricum'      , 'Aquitania'             , 'Yes', 'No'  ),
	array('Mare Cantabricum'      , 'Burdigala'             , 'Yes', 'No'  ),
	array('Mare Cantabricum'      , 'Taraconensis'          , 'Yes', 'No'  ),
	array('Capova'                , 'Roma'                  , 'Yes', 'Yes' ),
	array('Capova'                , 'Mare Tyrrhenicum'      , 'Yes', 'No'  ),
	array('Capova'                , 'Rhegium'               , 'Yes', 'Yes' ),
	array('Capova'                , 'Samnium'               , 'No' , 'Yes' ),
	array('Capova'                , 'Brundisium'            , 'No' , 'Yes' ),
	array('Carthago'              , 'Mauretania'            , 'Yes', 'Yes' ),
	array('Carthago'              , 'Baleares'              , 'Yes', 'No'  ),
	array('Carthago'              , 'Mare Tyrrhenicum'      , 'Yes', 'No'  ),
	array('Carthago'              , 'Mare Internum'         , 'Yes', 'No'  ),
	array('Carthago'              , 'Numidia'               , 'Yes', 'Yes' ),
	array('Chatti'                , 'Ripuari'               , 'No' , 'Yes' ),
	array('Chatti'                , 'Silingi'               , 'No' , 'Yes' ),
	array('Chatti'                , 'Suebi'                 , 'No' , 'Yes' ),
	array('Chatti'                , 'Vandales'              , 'No' , 'Yes' ),
	array('Chersonesus'           , 'Ostrogothi'            , 'Yes', 'Yes' ),
	array('Chersonesus'           , 'Pontus Euxinus'        , 'Yes', 'No'  ),
	array('Chersonesus'           , 'Hunni Quarti'          , 'Yes', 'Yes' ),
	array('Colonia Agrippa'       , 'Belgica'               , 'Yes', 'Yes' ),
	array('Colonia Agrippa'       , 'Mare Germanicum'       , 'Yes', 'No'  ),
	array('Colonia Agrippa'       , 'Frisii'                , 'Yes', 'Yes' ),
	array('Colonia Agrippa'       , 'Lutetia'               , 'No' , 'Yes' ),
	array('Colonia Agrippa'       , 'Viennensis'            , 'No' , 'Yes' ),
	array('Colonia Agrippa'       , 'Sequanorum'            , 'No' , 'Yes' ),
	array('Colonia Agrippa'       , 'Franci'                , 'No' , 'Yes' ),
	array('Colonia Agrippa'       , 'Teutones'              , 'No' , 'Yes' ),
	array('Colonia Agrippa'       , 'Vandales'              , 'No' , 'Yes' ),
	array('Colonia Agrippa'       , 'Alamanni'              , 'No' , 'Yes' ),
	array('Mare Cypris'           , 'Miletus'               , 'Yes', 'No'  ),
	array('Mare Cypris'           , 'Antiochia'             , 'Yes', 'No'  ),
	array('Mare Cypris'           , 'Orientes'              , 'Yes', 'No'  ),
	array('Mare Cypris'           , 'Alexandria'            , 'Yes', 'No'  ),
	array('Mare Cypris'           , 'Lybia'                 , 'Yes', 'No'  ),
	array('Mare Cypris'           , 'Mare Internum'         , 'Yes', 'No'  ),
	array('Mare Cypris'           , 'Aegaeis'               , 'Yes', 'No'  ),
	array('Dacia'                 , 'Dalmatia'              , 'Yes', 'Yes' ),
	array('Dacia'                 , 'Mare Adriaticum'       , 'Yes', 'No'  ),
	array('Dacia'                 , 'Macedonia (West Coast)', 'Yes', 'No'  ),
	array('Dacia'                 , 'Iazygi'                , 'No' , 'Yes' ),
	array('Dacia'                 , 'Thracia'               , 'No' , 'Yes' ),
	array('Dacia'                 , 'Macedonia'             , 'No' , 'Yes' ),
	array('Dalmatia'              , 'Verona'                , 'Yes', 'Yes' ),
	array('Dalmatia'              , 'Mare Adriaticum'       , 'Yes', 'No'  ),
	array('Dalmatia'              , 'Dacia'                 , 'Yes', 'Yes' ),
	array('Dalmatia'              , 'Vindobona'             , 'No' , 'Yes' ),
	array('Dalmatia'              , 'Iazygi'                , 'No' , 'Yes' ),
	array('Eburacum (East Coast)' , 'Mare Germanicum'       , 'Yes', 'No'  ),
	array('Eburacum (East Coast)' , 'Maxima Caesarensis'    , 'Yes', 'No'  ),
	array('Eburacum (West Coast)' , 'Oceanus Britannicus'   , 'Yes', 'No'  ),
	array('Eburacum (West Coast)' , 'Flavia Caesarensis'    , 'Yes', 'No'  ),
	array('Eburacum'              , 'Flavia Caesarensis'    , 'No' , 'Yes' ),
	array('Eburacum'              , 'Maxima Caesarensis'    , 'No' , 'Yes' ),
	array('Pontus Euxinus'        , 'Ostrogothi'            , 'Yes', 'No'  ),
	array('Pontus Euxinus'        , 'Chersonesus'           , 'Yes', 'No'  ),
	array('Pontus Euxinus'        , 'Hunni Quarti'          , 'Yes', 'No'  ),
	array('Pontus Euxinus'        , 'Scytia'                , 'Yes', 'No'  ),
	array('Pontus Euxinus'        , 'Byzantium'             , 'Yes', 'No'  ),
	array('Pontus Euxinus'        , 'Pontica'               , 'Yes', 'No'  ),
	array('Flavia Caesarensis'    , 'Londinum'              , 'Yes', 'Yes' ),
	array('Flavia Caesarensis'    , 'Oceanus Britannicus'   , 'Yes', 'No'  ),
	array('Flavia Caesarensis'    , 'Eburacum (West Coast)' , 'Yes', 'No'  ),
	array('Flavia Caesarensis'    , 'Maxima Caesarensis'    , 'No' , 'Yes' ),
	array('Flavia Caesarensis'    , 'Eburacum'              , 'No' , 'Yes' ),
	array('Franci'                , 'Frisii'                , 'No' , 'Yes' ),
	array('Franci'                , 'Jutii'                 , 'No' , 'Yes' ),
	array('Franci'                , 'Langobardi'            , 'No' , 'Yes' ),
	array('Franci'                , 'Teutones'              , 'No' , 'Yes' ),
	array('Franci'                , 'Colonia Agrippa'       , 'No' , 'Yes' ),
	array('Frisii'                , 'Jutii'                 , 'Yes', 'Yes' ),
	array('Frisii'                , 'Mare Germanicum'       , 'Yes', 'No'  ),
	array('Frisii'                , 'Colonia Agrippa'       , 'Yes', 'Yes' ),
	array('Frisii'                , 'Franci'                , 'No' , 'Yes' ),
	array('Galatia'               , 'Byzantium'             , 'Yes', 'Yes' ),
	array('Galatia'               , 'Thracia'               , 'Yes', 'Yes' ),
	array('Galatia'               , 'Aegaeis'               , 'Yes', 'No'  ),
	array('Galatia'               , 'Miletus'               , 'Yes', 'Yes' ),
	array('Galatia'               , 'Pontica'               , 'No' , 'Yes' ),
	array('Galatia'               , 'Antiochia'             , 'No' , 'Yes' ),
	array('Genova'                , 'Alpes'                 , 'Yes', 'Yes' ),
	array('Genova'                , 'Mare Ligusticum'       , 'Yes', 'No'  ),
	array('Genova'                , 'Tuscia'                , 'Yes', 'Yes' ),
	array('Genova'                , 'Aemilia'               , 'No' , 'Yes' ),
	array('Genova'                , 'Ravenna'               , 'No' , 'Yes' ),
	array('Mare Germanicum'       , 'Haithabu'              , 'Yes', 'No'  ),
	array('Mare Germanicum'       , 'Jutii'                 , 'Yes', 'No'  ),
	array('Mare Germanicum'       , 'Frisii'                , 'Yes', 'No'  ),
	array('Mare Germanicum'       , 'Colonia Agrippa'       , 'Yes', 'No'  ),
	array('Mare Germanicum'       , 'Belgica'               , 'Yes', 'No'  ),
	array('Mare Germanicum'       , 'Litus Saxonicum'       , 'Yes', 'No'  ),
	array('Mare Germanicum'       , 'Londinum'              , 'Yes', 'No'  ),
	array('Mare Germanicum'       , 'Maxima Caesarensis'    , 'Yes', 'No'  ),
	array('Mare Germanicum'       , 'Eburacum (East Coast)' , 'Yes', 'No'  ),
	array('Haithabu'              , 'Mare Germanicum'       , 'Yes', 'No'  ),
	array('Haithabu'              , 'Jutii'                 , 'Yes', 'Yes' ),
	array('Haithabu'              , 'Langobardi'            , 'No' , 'Yes' ),
	array('Haithabu'              , 'Ripuari'               , 'No' , 'Yes' ),
	array('Haithabu'              , 'Silingi'               , 'No' , 'Yes' ),
	array('Haithabu'              , 'Hunni Primi'           , 'No' , 'Yes' ),
	array('Hunni Primi'           , 'Haithabu'              , 'No' , 'Yes' ),
	array('Hunni Primi'           , 'Silingi'               , 'No' , 'Yes' ),
	array('Hunni Primi'           , 'Hunni Terti'           , 'No' , 'Yes' ),
	array('Hunni Secundi'         , 'Silingi'               , 'No' , 'Yes' ),
	array('Hunni Secundi'         , 'Suebi'                 , 'No' , 'Yes' ),
	array('Hunni Secundi'         , 'Quadi'                 , 'No' , 'Yes' ),
	array('Hunni Secundi'         , 'Asdingi'               , 'No' , 'Yes' ),
	array('Hunni Secundi'         , 'Visigothi'             , 'No' , 'Yes' ),
	array('Hunni Secundi'         , 'Hunni Terti'           , 'No' , 'Yes' ),
	array('Hunni Terti'           , 'Hunni Primi'           , 'No' , 'Yes' ),
	array('Hunni Terti'           , 'Silingi'               , 'No' , 'Yes' ),
	array('Hunni Terti'           , 'Hunni Secundi'         , 'No' , 'Yes' ),
	array('Hunni Terti'           , 'Visigothi'             , 'No' , 'Yes' ),
	array('Hunni Terti'           , 'Hunni Quarti'          , 'No' , 'Yes' ),
	array('Hunni Terti'           , 'Ostrogothi'            , 'No' , 'Yes' ),
	array('Hunni Quarti'          , 'Chersonesus'           , 'Yes', 'Yes' ),
	array('Hunni Quarti'          , 'Ostrogothi'            , 'No' , 'Yes' ),
	array('Hunni Quarti'          , 'Hunni Terti'           , 'No' , 'Yes' ),
	array('Hunni Quarti'          , 'Visigothi'             , 'No' , 'Yes' ),
	array('Hunni Quarti'          , 'Iazygi'                , 'No' , 'Yes' ),
	array('Hunni Quarti'          , 'Scytia'                , 'Yes', 'Yes' ),
	array('Hunni Quarti'          , 'Pontus Euxinus'        , 'Yes', 'No'  ),
	array('Iazygi'                , 'Asdingi'               , 'No' , 'Yes' ),
	array('Iazygi'                , 'Visigothi'             , 'No' , 'Yes' ),
	array('Iazygi'                , 'Hunni Quarti'          , 'No' , 'Yes' ),
	array('Iazygi'                , 'Scytia'                , 'No' , 'Yes' ),
	array('Iazygi'                , 'Thracia'               , 'No' , 'Yes' ),
	array('Iazygi'                , 'Dacia'                 , 'No' , 'Yes' ),
	array('Iazygi'                , 'Dalmatia'              , 'No' , 'Yes' ),
	array('Iazygi'                , 'Vindobona'             , 'No' , 'Yes' ),
	array('Mare Internum'         , 'Mare Ionium'           , 'Yes', 'No'  ),
	array('Mare Internum'         , 'Athenum'               , 'Yes', 'No'  ),
	array('Mare Internum'         , 'Aegaeis'               , 'Yes', 'No'  ),
	array('Mare Internum'         , 'Mare Cypris'           , 'Yes', 'No'  ),
	array('Mare Internum'         , 'Lybia'                 , 'Yes', 'No'  ),
	array('Mare Internum'         , 'Numidia'               , 'Yes', 'No'  ),
	array('Mare Internum'         , 'Carthago'              , 'Yes', 'No'  ),
	array('Mare Internum'         , 'Mare Tyrrhenicum'      , 'Yes', 'No'  ),
	array('Mare Internum'         , 'Syracusae'             , 'Yes', 'No'  ),
	array('Mare Ionium'           , 'Athenum'               , 'Yes', 'No'  ),
	array('Mare Ionium'           , 'Mare Internum'         , 'Yes', 'No'  ),
	array('Mare Ionium'           , 'Syracusae'             , 'Yes', 'No'  ),
	array('Mare Ionium'           , 'Mare Tyrrhenicum'      , 'Yes', 'No'  ),
	array('Mare Ionium'           , 'Rhegium'               , 'Yes', 'No'  ),
	array('Mare Ionium'           , 'Brundisium'            , 'Yes', 'No'  ),
	array('Mare Ionium'           , 'Mare Adriaticum'       , 'Yes', 'No'  ),
	array('Mare Ionium'           , 'Macedonia (West Coast)', 'Yes', 'No'  ),
	array('Jutii'                 , 'Haithabu'              , 'Yes', 'Yes' ),
	array('Jutii'                 , 'Mare Germanicum'       , 'Yes', 'No'  ),
	array('Jutii'                 , 'Frisii'                , 'Yes', 'Yes' ),
	array('Jutii'                 , 'Langobardi'            , 'No' , 'Yes' ),
	array('Jutii'                 , 'Franci'                , 'No' , 'Yes' ),
	array('Langobardi'            , 'Jutii'                 , 'No' , 'Yes' ),
	array('Langobardi'            , 'Franci'                , 'No' , 'Yes' ),
	array('Langobardi'            , 'Teutones'              , 'No' , 'Yes' ),
	array('Langobardi'            , 'Ripuari'               , 'No' , 'Yes' ),
	array('Langobardi'            , 'Haithabu'              , 'No' , 'Yes' ),
	array('Mare Ligusticum'       , 'Saguntum'              , 'Yes', 'No'  ),
	array('Mare Ligusticum'       , 'Narbonensis'           , 'Yes', 'No'  ),
	array('Mare Ligusticum'       , 'Massilia'              , 'Yes', 'No'  ),
	array('Mare Ligusticum'       , 'Alpes'                 , 'Yes', 'No'  ),
	array('Mare Ligusticum'       , 'Genova'                , 'Yes', 'No'  ),
	array('Mare Ligusticum'       , 'Tuscia'                , 'Yes', 'No'  ),
	array('Mare Ligusticum'       , 'Roma'                  , 'Yes', 'No'  ),
	array('Mare Ligusticum'       , 'Mare Tyrrhenicum'      , 'Yes', 'No'  ),
	array('Mare Ligusticum'       , 'Baleares'              , 'Yes', 'No'  ),
	array('Londinum'              , 'Maxima Caesarensis'    , 'Yes', 'Yes' ),
	array('Londinum'              , 'Mare Germanicum'       , 'Yes', 'No'  ),
	array('Londinum'              , 'Litus Saxonicum'       , 'Yes', 'No'  ),
	array('Londinum'              , 'Oceanus Britannicus'   , 'Yes', 'No'  ),
	array('Londinum'              , 'Flavia Caesarensis'    , 'Yes', 'Yes' ),
	array('Lugdunensis'           , 'Aquitania'             , 'Yes', 'Yes' ),
	array('Lugdunensis'           , 'Mare Cantabricum'      , 'Yes', 'No'  ),
	array('Lugdunensis'           , 'Oceanus Britannicus'   , 'Yes', 'No'  ),
	array('Lugdunensis'           , 'Rotomagus'             , 'Yes', 'Yes' ),
	array('Lugdunensis'           , 'Lutetia'               , 'No' , 'Yes' ),
	array('Lutetia'               , 'Belgica'               , 'No' , 'Yes' ),
	array('Lutetia'               , 'Colonia Agrippa'       , 'No' , 'Yes' ),
	array('Lutetia'               , 'Viennensis'            , 'No' , 'Yes' ),
	array('Lutetia'               , 'Aquitania'             , 'No' , 'Yes' ),
	array('Lutetia'               , 'Lugdunensis'           , 'No' , 'Yes' ),
	array('Lutetia'               , 'Rotomagus'             , 'No' , 'Yes' ),
	array('Lybia'                 , 'Numidia'               , 'Yes', 'Yes' ),
	array('Lybia'                 , 'Mare Internum'         , 'Yes', 'No'  ),
	array('Lybia'                 , 'Mare Cypris'           , 'Yes', 'No'  ),
	array('Lybia'                 , 'Alexandria'            , 'Yes', 'Yes' ),
	array('Macedonia (East Coast)', 'Thracia'               , 'Yes', 'No'  ),
	array('Macedonia (East Coast)', 'Aegaeis'               , 'Yes', 'No'  ),
	array('Macedonia (East Coast)', 'Athenum'               , 'Yes', 'No'  ),
	array('Macedonia (West Coast)', 'Dacia'                 , 'Yes', 'No'  ),
	array('Macedonia (West Coast)', 'Mare Adriaticum'       , 'Yes', 'No'  ),
	array('Macedonia (West Coast)', 'Mare Ionium'           , 'Yes', 'No'  ),
	array('Macedonia (West Coast)', 'Athenum'               , 'Yes', 'No'  ),
	array('Macedonia'             , 'Dacia'                 , 'No' , 'Yes' ),
	array('Macedonia'             , 'Thracia'               , 'No' , 'Yes' ),
	array('Macedonia'             , 'Athenum'               , 'No' , 'Yes' ),
	array('Massilia'              , 'Narbonensis'           , 'Yes', 'Yes' ),
	array('Massilia'              , 'Mare Ligusticum'       , 'Yes', 'No'  ),
	array('Massilia'              , 'Alpes'                 , 'Yes', 'Yes' ),
	array('Massilia'              , 'Aquitania'             , 'No' , 'Yes' ),
	array('Massilia'              , 'Viennensis'            , 'No' , 'Yes' ),
	array('Mauretania'            , 'Oceanus Atlanticus'    , 'Yes', 'No'  ),
	array('Mauretania'            , 'Baleares'              , 'Yes', 'No'  ),
	array('Mauretania'            , 'Carthago'              , 'Yes', 'Yes' ),
	array('Mauretania'            , 'Numidia'               , 'No' , 'Yes' ),
	array('Mauretania'            , 'Baetica'               , 'No' , 'Yes' ),
	array('Maxima Caesarensis'    , 'Londinum'              , 'Yes', 'Yes' ),
	array('Maxima Caesarensis'    , 'Mare Germanicum'       , 'Yes', 'No'  ),
	array('Maxima Caesarensis'    , 'Eburacum (East Coast)' , 'Yes', 'No'  ),
	array('Maxima Caesarensis'    , 'Eburacum'              , 'No' , 'Yes' ),
	array('Maxima Caesarensis'    , 'Flavia Caesarensis'    , 'No' , 'Yes' ),
	array('Miletus'               , 'Galatia'               , 'Yes', 'Yes' ),
	array('Miletus'               , 'Aegaeis'               , 'Yes', 'No'  ),
	array('Miletus'               , 'Mare Cypris'           , 'Yes', 'No'  ),
	array('Miletus'               , 'Antiochia'             , 'Yes', 'Yes' ),
	array('Narbonensis'           , 'Saguntum'              , 'Yes', 'Yes' ),
	array('Narbonensis'           , 'Mare Ligusticum'       , 'Yes', 'No'  ),
	array('Narbonensis'           , 'Massilia'              , 'Yes', 'Yes' ),
	array('Narbonensis'           , 'Taraconensis'          , 'No' , 'Yes' ),
	array('Narbonensis'           , 'Burdigala'             , 'No' , 'Yes' ),
	array('Narbonensis'           , 'Aquitania'             , 'No' , 'Yes' ),
	array('Numidia'               , 'Carthago'              , 'Yes', 'Yes' ),
	array('Numidia'               , 'Mare Internum'         , 'Yes', 'No'  ),
	array('Numidia'               , 'Lybia'                 , 'Yes', 'Yes' ),
	array('Numidia'               , 'Mauretania'            , 'No' , 'Yes' ),
	array('Olisipo'               , 'Taraconensis'          , 'Yes', 'Yes' ),
	array('Olisipo'               , 'Oceanus Atlanticus'    , 'Yes', 'No'  ),
	array('Olisipo'               , 'Baetica'               , 'Yes', 'Yes' ),
	array('Ostrogothi'            , 'Pontus Euxinus'        , 'Yes', 'No'  ),
	array('Ostrogothi'            , 'Chersonesus'           , 'Yes', 'Yes' ),
	array('Ostrogothi'            , 'Hunni Terti'           , 'No' , 'Yes' ),
	array('Ostrogothi'            , 'Hunni Quarti'          , 'No' , 'Yes' ),
	array('Orientes'              , 'Antiochia'             , 'Yes', 'Yes' ),
	array('Orientes'              , 'Mare Cypris'           , 'Yes', 'No'  ),
	array('Orientes'              , 'Pontica'               , 'No' , 'Yes' ),
	array('Orientes'              , 'Alexandria'            , 'No' , 'Yes' ),
	array('Pontica'               , 'Pontus Euxinus'        , 'Yes', 'No'  ),
	array('Pontica'               , 'Byzantium'             , 'Yes', 'Yes' ),
	array('Pontica'               , 'Galatia'               , 'No' , 'Yes' ),
	array('Pontica'               , 'Antiochia'             , 'No' , 'Yes' ),
	array('Pontica'               , 'Orientes'              , 'No' , 'Yes' ),
	array('Quadi'                 , 'Suebi'                 , 'No' , 'Yes' ),
	array('Quadi'                 , 'Hunni Secundi'         , 'No' , 'Yes' ),
	array('Quadi'                 , 'Asdingi'               , 'No' , 'Yes' ),
	array('Quadi'                 , 'Vindobona'             , 'No' , 'Yes' ),
	array('Ravenna'               , 'Verona'                , 'Yes', 'Yes' ),
	array('Ravenna'               , 'Mare Adriaticum'       , 'Yes', 'No'  ),
	array('Ravenna'               , 'Ancona'                , 'Yes', 'Yes' ),
	array('Ravenna'               , 'Aemilia'               , 'No' , 'Yes' ),
	array('Ravenna'               , 'Genova'                , 'No' , 'Yes' ),
	array('Ravenna'               , 'Tuscia'                , 'No' , 'Yes' ),
	array('Castra Regina'         , 'Vindobona'             , 'No' , 'Yes' ),
	array('Castra Regina'         , 'Verona'                , 'No' , 'Yes' ),
	array('Castra Regina'         , 'Aemilia'               , 'No' , 'Yes' ),
	array('Castra Regina'         , 'Alpes'                 , 'No' , 'Yes' ),
	array('Castra Regina'         , 'Sequanorum'            , 'No' , 'Yes' ),
	array('Castra Regina'         , 'Alamanni'              , 'No' , 'Yes' ),
	array('Castra Regina'         , 'Vandales'              , 'No' , 'Yes' ),
	array('Castra Regina'         , 'Suebi'                 , 'No' , 'Yes' ),
	array('Rhegium'               , 'Brundisium'            , 'Yes', 'Yes' ),
	array('Rhegium'               , 'Mare Ionium'           , 'Yes', 'No'  ),
	array('Rhegium'               , 'Mare Tyrrhenicum'      , 'Yes', 'No'  ),
	array('Rhegium'               , 'Capova'                , 'Yes', 'Yes' ),
	array('Ripuari'               , 'Haithabu'              , 'No' , 'Yes' ),
	array('Ripuari'               , 'Silingi'               , 'No' , 'Yes' ),
	array('Ripuari'               , 'Chatti'                , 'No' , 'Yes' ),
	array('Ripuari'               , 'Vandales'              , 'No' , 'Yes' ),
	array('Ripuari'               , 'Teutones'              , 'No' , 'Yes' ),
	array('Ripuari'               , 'Langobardi'            , 'No' , 'Yes' ),
	array('Roma'                  , 'Tuscia'                , 'Yes', 'Yes' ),
	array('Roma'                  , 'Mare Ligusticum'       , 'Yes', 'No'  ),
	array('Roma'                  , 'Mare Tyrrhenicum'      , 'Yes', 'No'  ),
	array('Roma'                  , 'Capova'                , 'Yes', 'Yes' ),
	array('Roma'                  , 'Ancona'                , 'No' , 'Yes' ),
	array('Roma'                  , 'Samnium'               , 'No' , 'Yes' ),
	array('Rotomagus'             , 'Lugdunensis'           , 'Yes', 'Yes' ),
	array('Rotomagus'             , 'Oceanus Britannicus'   , 'Yes', 'No'  ),
	array('Rotomagus'             , 'Litus Saxonicum'       , 'Yes', 'No'  ),
	array('Rotomagus'             , 'Belgica'               , 'Yes', 'Yes' ),
	array('Rotomagus'             , 'Lutetia'               , 'No' , 'Yes' ),
	array('Saguntum'              , 'Narbonensis'           , 'Yes', 'Yes' ),
	array('Saguntum'              , 'Mare Ligusticum'       , 'Yes', 'No'  ),
	array('Saguntum'              , 'Baleares'              , 'Yes', 'No'  ),
	array('Saguntum'              , 'Baetica'               , 'Yes', 'Yes' ),
	array('Saguntum'              , 'Taraconensis'          , 'No' , 'Yes' ),
	array('Samnium'               , 'Ancona'                , 'Yes', 'Yes' ),
	array('Samnium'               , 'Mare Adriaticum'       , 'Yes', 'No'  ),
	array('Samnium'               , 'Brundisium'            , 'Yes', 'Yes' ),
	array('Samnium'               , 'Roma'                  , 'No' , 'Yes' ),
	array('Samnium'               , 'Capova'                , 'No' , 'Yes' ),
	array('Litus Saxonicum'       , 'Belgica'               , 'Yes', 'No'  ),
	array('Litus Saxonicum'       , 'Rotomagus'             , 'Yes', 'No'  ),
	array('Litus Saxonicum'       , 'Oceanus Britannicus'   , 'Yes', 'No'  ),
	array('Litus Saxonicum'       , 'Londinum'              , 'Yes', 'No'  ),
	array('Litus Saxonicum'       , 'Mare Germanicum'       , 'Yes', 'No'  ),
	array('Scytia'                , 'Byzantium'             , 'Yes', 'Yes' ),
	array('Scytia'                , 'Pontus Euxinus'        , 'Yes', 'No'  ),
	array('Scytia'                , 'Hunni Quarti'          , 'Yes', 'Yes' ),
	array('Scytia'                , 'Thracia'               , 'No' , 'Yes' ),
	array('Scytia'                , 'Iazygi'                , 'No' , 'Yes' ),
	array('Sequanorum'            , 'Colonia Agrippa'       , 'No' , 'Yes' ),
	array('Sequanorum'            , 'Viennensis'            , 'No' , 'Yes' ),
	array('Sequanorum'            , 'Alpes'                 , 'No' , 'Yes' ),
	array('Sequanorum'            , 'Castra Regina'         , 'No' , 'Yes' ),
	array('Sequanorum'            , 'Alamanni'              , 'No' , 'Yes' ),
	array('Silingi'               , 'Haithabu'              , 'No' , 'Yes' ),
	array('Silingi'               , 'Hunni Primi'           , 'No' , 'Yes' ),
	array('Silingi'               , 'Hunni Secundi'         , 'No' , 'Yes' ),
	array('Silingi'               , 'Hunni Terti'           , 'No' , 'Yes' ),
	array('Silingi'               , 'Suebi'                 , 'No' , 'Yes' ),
	array('Silingi'               , 'Chatti'                , 'No' , 'Yes' ),
	array('Silingi'               , 'Ripuari'               , 'No' , 'Yes' ),
	array('Suebi'                 , 'Vandales'              , 'No' , 'Yes' ),
	array('Suebi'                 , 'Chatti'                , 'No' , 'Yes' ),
	array('Suebi'                 , 'Silingi'               , 'No' , 'Yes' ),
	array('Suebi'                 , 'Hunni Secundi'         , 'No' , 'Yes' ),
	array('Suebi'                 , 'Quadi'                 , 'No' , 'Yes' ),
	array('Suebi'                 , 'Vindobona'             , 'No' , 'Yes' ),
	array('Suebi'                 , 'Castra Regina'         , 'No' , 'Yes' ),
	array('Syracusae'             , 'Mare Tyrrhenicum'      , 'Yes', 'No'  ),
	array('Syracusae'             , 'Mare Ionium'           , 'Yes', 'No'  ),
	array('Syracusae'             , 'Mare Internum'         , 'Yes', 'No'  ),
	array('Taraconensis'          , 'Olisipo'               , 'Yes', 'Yes' ),
	array('Taraconensis'          , 'Oceanus Atlanticus'    , 'Yes', 'No'  ),
	array('Taraconensis'          , 'Mare Cantabricum'      , 'Yes', 'No'  ),
	array('Taraconensis'          , 'Burdigala'             , 'Yes', 'Yes' ),
	array('Taraconensis'          , 'Baetica'               , 'No' , 'Yes' ),
	array('Taraconensis'          , 'Saguntum'              , 'No' , 'Yes' ),
	array('Taraconensis'          , 'Narbonensis'           , 'No' , 'Yes' ),
	array('Teutones'              , 'Franci'                , 'No' , 'Yes' ),
	array('Teutones'              , 'Langobardi'            , 'No' , 'Yes' ),
	array('Teutones'              , 'Ripuari'               , 'No' , 'Yes' ),
	array('Teutones'              , 'Vandales'              , 'No' , 'Yes' ),
	array('Teutones'              , 'Colonia Agrippa'       , 'No' , 'Yes' ),
	array('Thracia'               , 'Byzantium'             , 'Yes', 'Yes' ),
	array('Thracia'               , 'Galatia'               , 'Yes', 'Yes' ),
	array('Thracia'               , 'Aegaeis'               , 'Yes', 'No'  ),
	array('Thracia'               , 'Macedonia (East Coast)', 'Yes', 'No'  ),
	array('Thracia'               , 'Scytia'                , 'No' , 'Yes' ),
	array('Thracia'               , 'Iazygi'                , 'No' , 'Yes' ),
	array('Thracia'               , 'Dacia'                 , 'No' , 'Yes' ),
	array('Thracia'               , 'Macedonia'             , 'No' , 'Yes' ),
	array('Tuscia'                , 'Genova'                , 'Yes', 'Yes' ),
	array('Tuscia'                , 'Mare Ligusticum'       , 'Yes', 'No'  ),
	array('Tuscia'                , 'Roma'                  , 'Yes', 'Yes' ),
	array('Tuscia'                , 'Ravenna'               , 'No' , 'Yes' ),
	array('Tuscia'                , 'Ancona'                , 'No' , 'Yes' ),
	array('Mare Tyrrhenicum'      , 'Roma'                  , 'Yes', 'No'  ),
	array('Mare Tyrrhenicum'      , 'Capova'                , 'Yes', 'No'  ),
	array('Mare Tyrrhenicum'      , 'Rhegium'               , 'Yes', 'No'  ),
	array('Mare Tyrrhenicum'      , 'Mare Ionium'           , 'Yes', 'No'  ),
	array('Mare Tyrrhenicum'      , 'Syracusae'             , 'Yes', 'No'  ),
	array('Mare Tyrrhenicum'      , 'Mare Internum'         , 'Yes', 'No'  ),
	array('Mare Tyrrhenicum'      , 'Carthago'              , 'Yes', 'No'  ),
	array('Mare Tyrrhenicum'      , 'Baleares'              , 'Yes', 'No'  ),
	array('Mare Tyrrhenicum'      , 'Mare Ligusticum'       , 'Yes', 'No'  ),
	array('Vandales'              , 'Teutones'              , 'No' , 'Yes' ),
	array('Vandales'              , 'Ripuari'               , 'No' , 'Yes' ),
	array('Vandales'              , 'Chatti'                , 'No' , 'Yes' ),
	array('Vandales'              , 'Suebi'                 , 'No' , 'Yes' ),
	array('Vandales'              , 'Alamanni'              , 'No' , 'Yes' ),
	array('Vandales'              , 'Castra Regina'         , 'No' , 'Yes' ),
	array('Vandales'              , 'Colonia Agrippa'       , 'No' , 'Yes' ),
	array('Verona'                , 'Dalmatia'              , 'Yes', 'Yes' ),
	array('Verona'                , 'Mare Adriaticum'       , 'Yes', 'No'  ),
	array('Verona'                , 'Ravenna'               , 'Yes', 'Yes' ),
	array('Verona'                , 'Vindobona'             , 'No' , 'Yes' ),
	array('Verona'                , 'Castra Regina'         , 'No' , 'Yes' ),
	array('Verona'                , 'Aemilia'               , 'No' , 'Yes' ),
	array('Viennensis'            , 'Lutetia'               , 'No' , 'Yes' ),
	array('Viennensis'            , 'Colonia Agrippa'       , 'No' , 'Yes' ),
	array('Viennensis'            , 'Sequanorum'            , 'No' , 'Yes' ),
	array('Viennensis'            , 'Alpes'                 , 'No' , 'Yes' ),
	array('Viennensis'            , 'Massilia'              , 'No' , 'Yes' ),
	array('Viennensis'            , 'Aquitania'             , 'No' , 'Yes' ),
	array('Vindobona'             , 'Dalmatia'              , 'No' , 'Yes' ),
	array('Vindobona'             , 'Verona'                , 'No' , 'Yes' ),
	array('Vindobona'             , 'Castra Regina'         , 'No' , 'Yes' ),
	array('Vindobona'             , 'Suebi'                 , 'No' , 'Yes' ),
	array('Vindobona'             , 'Quadi'                 , 'No' , 'Yes' ),
	array('Vindobona'             , 'Asdingi'               , 'No' , 'Yes' ),
	array('Vindobona'             , 'Iazygi'                , 'No' , 'Yes' ),
	array('Visigothi'             , 'Hunni Secundi'         , 'No' , 'Yes' ),
	array('Visigothi'             , 'Hunni Terti'           , 'No' , 'Yes' ),
	array('Visigothi'             , 'Hunni Quarti'          , 'No' , 'Yes' ),
	array('Visigothi'             , 'Iazygi'                , 'No' , 'Yes' ),
	array('Visigothi'             , 'Asdingi'               , 'No' , 'Yes' )
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$from]->addBorder(InstallTerritory::$Territories[$to],$fleets,$armies);
}
unset($bordersRawData);

// Custom footer not changed by edit tool

// Make a "fake" SC for every country to fool the Unit-DestroyIndex generation
InstallTerritory::$Territories['Alamanni']->supply='Yes';
InstallTerritory::$Territories['Vandales']->supply='Yes';
InstallTerritory::$Territories['Ostrogothi']->supply='Yes';
InstallTerritory::$Territories['Franci']->supply='Yes';
InstallTerritory::$Territories['Hunni Primi']->supply='Yes';
InstallTerritory::$Territories['Teutones']->supply='Yes';

InstallTerritory::runSQL($this->mapID);

// Remove the fake Home-Supply-Centers created above
$DB->sql_put('UPDATE wD_Territories SET supply="No" WHERE mapID='.$this->mapID.' AND supply="Yes" AND countryID<>0;');

// install Javascript-cache
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);

?>