<?php
// This is file installs the map data for the KnownWorld_901 variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Munster', 'Coast', 'No', 0, 237, 456, 0, 0),
	array('Dublin', 'Coast', 'Yes', 16, 271, 425, 0, 0),
	array('Icelandic Sea', 'Sea', 'No', 0, 270, 185, 0, 0),
	array('Caledonia', 'Coast', 'No', 5, 309, 342, 0, 0),
	array('Jorvik', 'Coast', 'Yes', 5, 344, 419, 0, 0),
	array('Jorvik (East Coast)', 'Coast', 'No', 0, 359, 416, 0, 0),
	array('Jorvik (West Coast)', 'Coast', 'No', 0, 327, 423, 0, 0),
	array('Wales', 'Coast', 'No', 0, 318, 472, 0, 0),
	array('Welsh Sea', 'Sea', 'No', 0, 278, 513, 0, 0),
	array('Wessex', 'Coast', 'Yes', 16, 326, 505, 0, 0),
	array('North German Sea', 'Sea', 'No', 0, 407, 401, 0, 0),
	array('South German Sea', 'Sea', 'No', 0, 434, 461, 0, 0),
	array('Brittish Channel', 'Sea', 'No', 0, 322, 536, 0, 0),
	array('North Ocean Sea', 'Sea', 'No', 0, 175, 551, 0, 0),
	array('Norway', 'Coast', 'No', 5, 507, 283, 0, 0),
	array('Uppland', 'Coast', 'No', 5, 636, 268, 0, 0),
	array('Viken', 'Coast', 'Yes', 5, 574, 334, 0, 0),
	array('Gottland', 'Coast', 'No', 5, 631, 361, 0, 0),
	array('Scania', 'Coast', 'Yes', 5, 594, 394, 0, 0),
	array('Kattegat', 'Sea', 'No', 0, 564, 382, 0, 0),
	array('Abodrite Sea', 'Sea', 'No', 0, 554, 415, 0, 0),
	array('Lettish Sea', 'Sea', 'No', 0, 675, 385, 0, 0),
	array('Finnish Sea', 'Sea', 'No', 0, 746, 304, 0, 0),
	array('White Sea', 'Sea', 'No', 0, 1211, 81, 0, 0),
	array('Karelia', 'Coast', 'No', 10, 832, 253, 0, 0),
	array('Esteland', 'Coast', 'Yes', 16, 787, 335, 0, 0),
	array('Livonia', 'Coast', 'No', 0, 729, 368, 0, 0),
	array('Borussia', 'Coast', 'Yes', 16, 667, 426, 0, 0),
	array('Pomerania', 'Coast', 'No', 0, 614, 437, 0, 0),
	array('Jelling', 'Coast', 'Yes', 5, 530, 367, 0, 0),
	array('Bremen', 'Coast', 'Yes', 8, 505, 473, 0, 0),
	array('Friesland', 'Coast', 'No', 8, 466, 456, 0, 0),
	array('Novgorod', 'Coast', 'Yes', 10, 856, 319, 0, 0),
	array('Lothairingia', 'Coast', 'Yes', 16, 428, 503, 0, 0),
	array('Paris', 'Coast', 'Yes', 7, 379, 547, 0, 0),
	array('Brittany', 'Coast', 'Yes', 16, 324, 558, 0, 0),
	array('Aquitaine', 'Coast', 'Yes', 7, 366, 616, 0, 0),
	array('Bjarmaland', 'Coast', 'Yes', 16, 1055, 213, 0, 0),
	array('Kornia', 'Coast', 'No', 0, 1231, 212, 0, 0),
	array('Yugra', 'Coast', 'No', 0, 1520, 223, 0, 0),
	array('Tunguz', 'Coast', 'No', 0, 1849, 121, 0, 0),
	array('Merkit', 'Land', 'No', 0, 2118, 596, 0, 0),
	array('Saxony', 'Land', 'Yes', 8, 556, 500, 0, 0),
	array('Polania', 'Land', 'No', 0, 640, 477, 0, 0),
	array('Mazovia', 'Land', 'Yes', 16, 734, 488, 0, 0),
	array('Dregovichia', 'Land', 'No', 10, 801, 454, 0, 0),
	array('Smolensk', 'Land', 'Yes', 10, 860, 426, 0, 0),
	array('Cantabric Sea', 'Sea', 'No', 0, 308, 614, 0, 0),
	array('Franconia', 'Land', 'No', 8, 491, 528, 0, 0),
	array('Swabia', 'Land', 'Yes', 8, 527, 540, 0, 0),
	array('Bavaria', 'Land', 'Yes', 8, 566, 578, 0, 0),
	array('Moravia', 'Land', 'Yes', 16, 639, 575, 0, 0),
	array('Rostov', 'Land', 'Yes', 10, 981, 356, 0, 0),
	array('Krivichia', 'Land', 'No', 10, 935, 404, 0, 0),
	array('Kiev', 'Land', 'Yes', 10, 868, 493, 0, 0),
	array('Volhynia', 'Land', 'No', 10, 756, 534, 0, 0),
	array('Vlacha', 'Coast', 'No', 10, 852, 613, 0, 0),
	array('Onoguria', 'Land', 'No', 0, 714, 625, 0, 0),
	array('Slavonia', 'Land', 'No', 0, 646, 605, 0, 0),
	array('Macedonia', 'Land', 'No', 3, 734, 679, 0, 0),
	array('Thrace', 'Coast', 'Yes', 16, 828, 655, 0, 0),
	array('Constantinople', 'Coast', 'Yes', 3, 807, 755, 0, 0),
	array('Dalmatia', 'Coast', 'Yes', 16, 666, 683, 0, 0),
	array('Epirus', 'Coast', 'No', 3, 691, 733, 0, 0),
	array('Aquileia', 'Coast', 'No', 0, 596, 638, 0, 0),
	array('Spoleto', 'Coast', 'No', 0, 606, 706, 0, 0),
	array('Taranto', 'Coast', 'Yes', 3, 643, 771, 0, 0),
	array('Salerno', 'Coast', 'No', 0, 614, 743, 0, 0),
	array('Lombardy', 'Coast', 'No', 8, 544, 660, 0, 0),
	array('Helvetia', 'Land', 'No', 8, 518, 591, 0, 0),
	array('Upper Burgundy', 'Land', 'No', 0, 465, 619, 0, 0),
	array('Autun', 'Land', 'No', 7, 431, 600, 0, 0),
	array('Narbonne', 'Coast', 'Yes', 7, 434, 662, 0, 0),
	array('Lower Burgundy', 'Coast', 'Yes', 16, 460, 680, 0, 0),
	array('Toulouse', 'Land', 'No', 7, 389, 676, 0, 0),
	array('Gascony', 'Coast', 'Yes', 7, 363, 671, 0, 0),
	array('Spanish March', 'Coast', 'No', 0, 400, 726, 0, 0),
	array('Valencia', 'Coast', 'Yes', 11, 378, 748, 0, 0),
	array('Corsica', 'Coast', 'Yes', 16, 517, 698, 0, 0),
	array('Sardinia', 'Coast', 'Yes', 16, 523, 746, 0, 0),
	array('Sicily', 'Coast', 'Yes', 16, 610, 821, 0, 0),
	array('Crete', 'Coast', 'Yes', 16, 755, 870, 0, 0),
	array('Cyprus', 'Coast', 'Yes', 16, 911, 866, 0, 0),
	array('Pamplona', 'Coast', 'Yes', 16, 338, 681, 0, 0),
	array('Asturias', 'Coast', 'No', 0, 291, 678, 0, 0),
	array('Galicia', 'Coast', 'No', 0, 256, 709, 0, 0),
	array('Zaragoza', 'Land', 'No', 11, 338, 736, 0, 0),
	array('Toledo', 'Land', 'No', 11, 323, 753, 0, 0),
	array('Granada', 'Coast', 'No', 11, 351, 815, 0, 0),
	array('Cordova', 'Land', 'Yes', 11, 319, 806, 0, 0),
	array('Salamanca', 'Land', 'Yes', 11, 281, 762, 0, 0),
	array('Cadiz', 'Coast', 'Yes', 11, 252, 772, 0, 0),
	array('Cherson', 'Coast', 'Yes', 3, 903, 639, 0, 0),
	array('Stone Belt', 'Land', 'No', 0, 1313, 393, 0, 0),
	array('Udmurtia', 'Land', 'No', 0, 1185, 444, 0, 0),
	array('Bulgar', 'Land', 'Yes', 16, 1096, 424, 0, 0),
	array('Cheremissia', 'Coast', 'No', 0, 1035, 371, 0, 0),
	array('Mauretania', 'Coast', 'Yes', 16, 320, 899, 0, 0),
	array('Kutamia', 'Coast', 'No', 0, 442, 833, 0, 0),
	array('Vyatichia', 'Land', 'No', 10, 986, 466, 0, 0),
	array('Severyana', 'Land', 'No', 0, 983, 533, 0, 0),
	array('Mordvinia', 'Land', 'No', 0, 1097, 520, 0, 0),
	array('West Euxine Sea', 'Sea', 'No', 0, 873, 655, 0, 0),
	array('East Euxine Sea', 'Sea', 'No', 0, 955, 659, 0, 0),
	array('Aegean Sea', 'Sea', 'No', 0, 778, 789, 0, 0),
	array('Cilician Sea', 'Sea', 'No', 0, 816, 856, 0, 0),
	array('Sea of Tyre', 'Sea', 'No', 0, 907, 926, 0, 0),
	array('Egyptian Sea', 'Sea', 'No', 0, 835, 929, 0, 0),
	array('Ionian Sea', 'Sea', 'No', 0, 695, 845, 0, 0),
	array('Illyrian Sea', 'Sea', 'No', 0, 656, 710, 0, 0),
	array('Tyrrhenian Sea', 'Sea', 'No', 0, 565, 746, 0, 0),
	array('Libyan Sea', 'Sea', 'No', 0, 600, 863, 0, 0),
	array('Straits of Jebel Tarik', 'Sea', 'No', 0, 448, 787, 0, 0),
	array('Balearic Sea', 'Sea', 'No', 0, 416, 760, 0, 0),
	array('Ligurian Sea', 'Sea', 'No', 0, 506, 685, 0, 0),
	array('Sea of Tangiers', 'Sea', 'No', 0, 203, 858, 0, 0),
	array('Sea of Worms', 'Sea', 'No', 0, 49, 740, 0, 0),
	array('Kotoko', 'Coast', 'No', 0, 498, 1392, 0, 0),
	array('Kongo', 'Coast', 'No', 0, 617, 1586, 0, 0),
	array('Namib', 'Coast', 'No', 0, 713, 1842, 0, 0),
	array('Ifriqiya', 'Coast', 'Yes', 16, 528, 860, 0, 0),
	array('Tahert', 'Land', 'No', 0, 463, 996, 0, 0),
	array('Tkanaren', 'Coast', 'Yes', 16, 118, 960, 0, 0),
	array('Takrur Sea', 'Sea', 'No', 0, 107, 1098, 0, 0),
	array('Barghawata', 'Coast', 'No', 0, 260, 963, 0, 0),
	array('Sijilmassa', 'Land', 'No', 0, 362, 1058, 0, 0),
	array('Sanhaja', 'Coast', 'No', 0, 170, 1120, 0, 0),
	array('Tripolitania', 'Coast', 'No', 6, 611, 940, 0, 0),
	array('Barca', 'Coast', 'Yes', 6, 734, 931, 0, 0),
	array('Fazzan', 'Land', 'No', 6, 587, 1021, 0, 0),
	array('Assode', 'Land', 'No', 0, 493, 1183, 0, 0),
	array('Kanem', 'Land', 'Yes', 16, 600, 1218, 0, 0),
	array('Zawila', 'Land', 'Yes', 16, 627, 1094, 0, 0),
	array('Daju', 'Land', 'No', 0, 710, 1191, 0, 0),
	array('Alexandria', 'Coast', 'Yes', 6, 885, 979, 0, 0),
	array('Al-Qatta\\\'i', 'Coast', 'Yes', 6, 888, 1059, 0, 0),
	array('North Red Sea', 'Sea', 'No', 0, 940, 1077, 0, 0),
	array('Berenice', 'Coast', 'No', 0, 920, 1126, 0, 0),
	array('Makuran', 'Land', 'Yes', 16, 834, 1187, 0, 0),
	array('Bashkortostan', 'Land', 'Yes', 16, 1248, 470, 0, 0),
	array('Atil', 'Coast', 'Yes', 9, 1148, 603, 0, 0),
	array('North Khazar Sea', 'Sea', 'No', 0, 1172, 695, 0, 0),
	array('South Khazar Sea', 'Sea', 'No', 0, 1191, 745, 0, 0),
	array('Sarkel', 'Land', 'Yes', 9, 1068, 603, 0, 0),
	array('Tamantarka', 'Coast', 'Yes', 9, 991, 620, 0, 0),
	array('Abkhazia', 'Coast', 'No', 9, 1042, 698, 0, 0),
	array('Balanjar', 'Coast', 'Yes', 9, 1119, 677, 0, 0),
	array('Derbent', 'Coast', 'No', 9, 1147, 730, 0, 0),
	array('Georgia', 'Coast', 'Yes', 16, 1040, 749, 0, 0),
	array('Buccellaria', 'Coast', 'No', 3, 920, 720, 0, 0),
	array('Attalia', 'Coast', 'Yes', 3, 884, 825, 0, 0),
	array('Cappadocia', 'Coast', 'No', 3, 957, 833, 0, 0),
	array('Damascus', 'Coast', 'No', 0, 958, 882, 0, 0),
	array('Kakheti', 'Land', 'No', 0, 1089, 786, 0, 0),
	array('Armenia', 'Land', 'Yes', 16, 1034, 819, 0, 0),
	array('Mosul', 'Land', 'No', 1, 1045, 850, 0, 0),
	array('Baghdad', 'Land', 'Yes', 1, 1069, 924, 0, 0),
	array('Azerbaijan', 'Coast', 'Yes', 16, 1134, 780, 0, 0),
	array('Ghuzz', 'Coast', 'Yes', 16, 1209, 673, 0, 0),
	array('Ardebil', 'Coast', 'Yes', 1, 1184, 836, 0, 0),
	array('Alidistan', 'Coast', 'No', 0, 1235, 821, 0, 0),
	array('Urgench', 'Coast', 'Yes', 12, 1257, 737, 0, 0),
	array('Kipchak', 'Coast', 'No', 0, 1347, 561, 0, 0),
	array('Isfahan', 'Land', 'Yes', 1, 1210, 904, 0, 0),
	array('Khorasan', 'Land', 'No', 0, 1292, 861, 0, 0),
	array('Kyrgyzstan', 'Land', 'No', 0, 1702, 554, 0, 0),
	array('Kyzyl Kum', 'Land', 'No', 12, 1473, 695, 0, 0),
	array('Qarluk', 'Land', 'No', 12, 1744, 710, 0, 0),
	array('Ordu-Balyk', 'Land', 'Yes', 16, 1945, 721, 0, 0),
	array('Khitai', 'Land', 'No', 0, 2169, 731, 0, 0),
	array('Changcheng', 'Land', 'No', 4, 2039, 843, 0, 0),
	array('Yanjing', 'Coast', 'Yes', 4, 2255, 812, 0, 0),
	array('Silla', 'Coast', 'Yes', 16, 2402, 896, 0, 0),
	array('Yellow Sea', 'Sea', 'No', 0, 2331, 901, 0, 0),
	array('Sea of Nihon', 'Sea', 'No', 0, 2466, 866, 0, 0),
	array('Uyghurstan', 'Land', 'Yes', 16, 1794, 835, 0, 0),
	array('Samarkand', 'Land', 'Yes', 12, 1618, 762, 0, 0),
	array('Bukhara', 'Land', 'Yes', 12, 1442, 822, 0, 0),
	array('Sogdia', 'Land', 'No', 0, 1697, 877, 0, 0),
	array('Western Sea', 'Sea', 'No', 0, 31, 1492, 0, 0),
	array('South Ocean Sea', 'Sea', 'No', 0, 365, 1515, 0, 0),
	array('Antipodean Sea', 'Sea', 'No', 0, 711, 1966, 0, 0),
	array('Gokomere Sea', 'Sea', 'No', 0, 718, 1906, 0, 0),
	array('Zimbabwe', 'Coast', 'Yes', 16, 911, 1786, 0, 0),
	array('Awlil', 'Coast', 'Yes', 14, 139, 1253, 0, 0),
	array('Awdagost', 'Land', 'No', 14, 201, 1235, 0, 0),
	array('Kumbi Saleh', 'Land', 'Yes', 14, 291, 1190, 0, 0),
	array('Walata', 'Land', 'Yes', 14, 338, 1237, 0, 0),
	array('Bure', 'Coast', 'No', 14, 199, 1342, 0, 0),
	array('Niore', 'Land', 'Yes', 14, 278, 1284, 0, 0),
	array('Kangaba', 'Coast', 'No', 0, 281, 1398, 0, 0),
	array('Bassikinu', 'Land', 'No', 14, 376, 1248, 0, 0),
	array('Tiraqqa', 'Land', 'No', 14, 445, 1274, 0, 0),
	array('Jenne-Jeno', 'Land', 'Yes', 16, 386, 1290, 0, 0),
	array('Luba', 'Land', 'No', 0, 831, 1465, 0, 0),
	array('Rhapta', 'Coast', 'No', 0, 993, 1585, 0, 0),
	array('Azania', 'Coast', 'No', 2, 1144, 1381, 0, 0),
	array('Malao', 'Coast', 'Yes', 2, 1037, 1364, 0, 0),
	array('Zeila', 'Coast', 'No', 2, 1053, 1326, 0, 0),
	array('Adulis', 'Coast', 'Yes', 2, 1021, 1286, 0, 0),
	array('Meroe', 'Coast', 'No', 2, 948, 1215, 0, 0),
	array('Sudd', 'Land', 'No', 2, 771, 1286, 0, 0),
	array('Luo', 'Land', 'No', 2, 813, 1367, 0, 0),
	array('Roha', 'Land', 'Yes', 2, 918, 1330, 0, 0),
	array('Axum', 'Land', 'Yes', 2, 917, 1272, 0, 0),
	array('Menuthian Sea', 'Sea', 'No', 0, 1085, 1587, 0, 0),
	array('Gulf of Aden', 'Sea', 'No', 0, 1250, 1463, 0, 0),
	array('Phebol', 'Coast', 'No', 0, 1091, 1769, 0, 0),
	array('Mahilaka', 'Coast', 'Yes', 16, 1135, 1770, 0, 0),
	array('Socotra', 'Coast', 'Yes', 16, 1221, 1291, 0, 0),
	array('Yemen', 'Coast', 'Yes', 16, 1138, 1251, 0, 0),
	array('Mecca', 'Coast', 'No', 0, 979, 1068, 0, 0),
	array('Jerusalem', 'Coast', 'Yes', 6, 942, 925, 0, 0),
	array('Nefud', 'Land', 'No', 1, 1068, 1041, 0, 0),
	array('Oman', 'Coast', 'No', 1, 1286, 1160, 0, 0),
	array('Basra', 'Coast', 'Yes', 1, 1203, 1014, 0, 0),
	array('Sijistan', 'Land', 'No', 0, 1350, 1007, 0, 0),
	array('Herat', 'Land', 'Yes', 12, 1425, 932, 0, 0),
	array('Balkh', 'Land', 'No', 0, 1559, 927, 0, 0),
	array('Mansurah', 'Coast', 'Yes', 16, 1436, 1064, 0, 0),
	array('Arabian Sea', 'Sea', 'No', 0, 1370, 1145, 0, 0),
	array('Malabar Sea', 'Sea', 'No', 0, 1475, 1476, 0, 0),
	array('Kashmir', 'Land', 'Yes', 16, 1636, 931, 0, 0),
	array('Shahiya', 'Land', 'No', 15, 1543, 1013, 0, 0),
	array('Indraprastha', 'Land', 'Yes', 15, 1604, 1034, 0, 0),
	array('Kannauj', 'Land', 'Yes', 15, 1627, 1088, 0, 0),
	array('Nepal', 'Land', 'No', 15, 1695, 1011, 0, 0),
	array('Tibet', 'Land', 'Yes', 16, 1810, 996, 0, 0),
	array('Amdo', 'Land', 'No', 0, 1870, 930, 0, 0),
	array('Chang\\\'an', 'Land', 'Yes', 4, 2084, 963, 0, 0),
	array('Henan', 'Coast', 'No', 4, 2248, 896, 0, 0),
	array('Nanjing', 'Coast', 'Yes', 4, 2271, 959, 0, 0),
	array('Eastern Sea', 'Sea', 'No', 0, 2373, 966, 0, 0),
	array('Saikaido', 'Coast', 'Yes', 16, 2449, 962, 0, 0),
	array('Lusong Sea', 'Sea', 'No', 0, 2464, 1199, 0, 0),
	array('Sea of Tepanga', 'Sea', 'No', 0, 2259, 1213, 0, 0),
	array('Sea of Cham', 'Sea', 'No', 0, 2174, 1277, 0, 0),
	array('Java Sea', 'Sea', 'No', 0, 2311, 1659, 0, 0),
	array('Karimata Straits', 'Sea', 'No', 0, 2051, 1418, 0, 0),
	array('Southern Sea', 'Sea', 'No', 0, 1704, 1860, 0, 0),
	array('Minang Sea', 'Sea', 'No', 0, 1733, 1564, 0, 0),
	array('Andaman Sea', 'Sea', 'No', 0, 1780, 1352, 0, 0),
	array('Coromandel Bay', 'Sea', 'No', 0, 1761, 1228, 0, 0),
	array('Serendib', 'Coast', 'Yes', 16, 1654, 1364, 0, 0),
	array('Chola', 'Coast', 'Yes', 16, 1606, 1347, 0, 0),
	array('Rastrakuta', 'Coast', 'No', 0, 1552, 1227, 0, 0),
	array('Ujjain', 'Coast', 'Yes', 15, 1525, 1125, 0, 0),
	array('Chalukya', 'Coast', 'No', 0, 1698, 1197, 0, 0),
	array('Varanasi', 'Coast', 'Yes', 15, 1755, 1126, 0, 0),
	array('Pala', 'Coast', 'No', 15, 1812, 1122, 0, 0),
	array('Pagan', 'Land', 'Yes', 16, 1885, 1129, 0, 0),
	array('Nanzhao', 'Land', 'No', 0, 1946, 1102, 0, 0),
	array('Sichuan', 'Land', 'No', 4, 1996, 1023, 0, 0),
	array('Jiangxi', 'Land', 'No', 4, 2139, 1036, 0, 0),
	array('Guangzhou', 'Coast', 'Yes', 4, 2220, 1103, 0, 0),
	array('Annam', 'Coast', 'No', 0, 2040, 1187, 0, 0),
	array('Champa', 'Coast', 'No', 0, 2077, 1248, 0, 0),
	array('Kambuja', 'Coast', 'Yes', 16, 2051, 1331, 0, 0),
	array('Dvaravati', 'Coast', 'No', 0, 1936, 1234, 0, 0),
	array('Cahaya', 'Coast', 'Yes', 13, 1999, 1441, 0, 0),
	array('Jambi', 'Coast', 'Yes', 13, 1968, 1486, 0, 0),
	array('Palembang', 'Coast', 'Yes', 13, 2043, 1576, 0, 0),
	array('Kalimantan', 'Coast', 'Yes', 13, 2127, 1492, 0, 0),
	array('Sabah', 'Coast', 'No', 13, 2224, 1434, 0, 0),
	array('Butuan', 'Coast', 'Yes', 16, 2350, 1399, 0, 0),
	array('Saamiland', 'Coast', 'No', 0, 762, 139, 0, 0),
	array('Saamiland (North Coast)', 'Coast', 'No', 0, 729, 94, 0, 0),
	array('Saamiland (South Coast)', 'Coast', 'No', 0, 782, 184, 0, 0),
	array('Veletia', 'Coast', 'No', 0, 576, 454, 0, 0),
	array('Veletia (North Coast)', 'Coast', 'No', 0, 570, 432, 0, 0),
	array('Veletia (West Coast)', 'Coast', 'No', 0, 522, 435, 0, 0),
	array('Rome', 'Coast', 'Yes', 16, 583, 716, 0, 0),
	array('Rome (West Coast)', 'Coast', 'No', 0, 578, 714, 0, 0),
	array('Rome (East Coast)', 'Coast', 'No', 0, 573, 655, 0, 0),
	array('Pechenega', 'Coast', 'Yes', 16, 923, 562, 0, 0),
	array('Pechenega (East Coast)', 'Coast', 'No', 0, 952, 600, 0, 0),
	array('Pechenega (West Coast)', 'Coast', 'No', 0, 894, 614, 0, 0),
	array('Balhae', 'Coast', 'No', 0, 2377, 744, 0, 0),
	array('Balhae (East Coast)', 'Coast', 'No', 0, 2442, 749, 0, 0),
	array('Balhae (South Coast)', 'Coast', 'No', 0, 2315, 820, 0, 0),
	array('South Red Sea', 'Sea', 'No', 0, 1036, 1246, 0, 0),
	array('arabia', 'Land', 'No', 1, 2132, 37, 0, 0),
	array('byzantium', 'Coast', 'No', 3, 2132, 54, 0, 0),
	array('china', 'Coast', 'No', 4, 2132, 69, 0, 0),
	array('egypt', 'Coast', 'No', 6, 2133, 103, 0, 0),
	array('france', 'Coast', 'No', 7, 2133, 117, 0, 0),
	array('germany', 'Coast', 'No', 8, 2133, 132, 0, 0),
	array('khazaria', 'Coast', 'No', 9, 2330, 37, 0, 0),
	array('neutral', 'Coast', 'No', 0, 2330, 53, 0, 0),
	array('russia', 'Coast', 'No', 10, 2330, 70, 0, 0),
	array('spanyards', 'Coast', 'No', 11, 2329, 85, 0, 0),
	array('srivijaya', 'Coast', 'No', 13, 2330, 116, 0, 0),
	array('axum', 'Coast', 'No', 2, 2330, 148, 0, 0),
	array('denmark', 'Coast', 'No', 5, 2133, 85, 0, 0),
	array('india', 'Coast', 'No', 15, 2133, 148, 0, 0),
	array('turan', 'Coast', 'No', 12, 2330, 101, 0, 0),
	array('wagadu', 'Coast', 'No', 14, 2330, 132, 0, 0)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $x, $y);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Munster','Dublin','Yes','Yes'),
	array('Munster','Icelandic Sea','Yes','No'),
	array('Munster','North Ocean Sea','Yes','No'),
	array('Dublin','Icelandic Sea','Yes','No'),
	array('Dublin','Welsh Sea','Yes','No'),
	array('Dublin','North Ocean Sea','Yes','No'),
	array('Icelandic Sea','Caledonia','Yes','No'),
	array('Icelandic Sea','Jorvik (East Coast)','Yes','No'),
	array('Icelandic Sea','Welsh Sea','Yes','No'),
	array('Icelandic Sea','North German Sea','Yes','No'),
	array('Icelandic Sea','North Ocean Sea','Yes','No'),
	array('Icelandic Sea','Norway','Yes','No'),
	array('Icelandic Sea','White Sea','Yes','No'),
	array('Icelandic Sea','Bjarmaland','Yes','No'),
	array('Icelandic Sea','Sea of Worms','Yes','No'),
	array('Icelandic Sea','Saamiland (North Coast)','Yes','No'),
	array('Caledonia','Jorvik','No','Yes'),
	array('Caledonia','Jorvik (East Coast)','Yes','No'),
	array('Caledonia','Jorvik (West Coast)','Yes','No'),
	array('Caledonia','Welsh Sea','Yes','No'),
	array('Jorvik','Wales','No','Yes'),
	array('Jorvik','Wessex','No','Yes'),
	array('Jorvik (East Coast)','Wessex','Yes','No'),
	array('Jorvik (East Coast)','North German Sea','Yes','No'),
	array('Jorvik (West Coast)','Wales','Yes','No'),
	array('Jorvik (West Coast)','Welsh Sea','Yes','No'),
	array('Wales','Welsh Sea','Yes','No'),
	array('Wales','Wessex','Yes','Yes'),
	array('Welsh Sea','Wessex','Yes','No'),
	array('Welsh Sea','North Ocean Sea','Yes','No'),
	array('Wessex','North German Sea','Yes','No'),
	array('Wessex','South German Sea','Yes','No'),
	array('Wessex','Brittish Channel','Yes','No'),
	array('Wessex','North Ocean Sea','Yes','No'),
	array('North German Sea','South German Sea','Yes','No'),
	array('North German Sea','Norway','Yes','No'),
	array('North German Sea','Kattegat','Yes','No'),
	array('North German Sea','Jelling','Yes','No'),
	array('South German Sea','Brittish Channel','Yes','No'),
	array('South German Sea','Jelling','Yes','No'),
	array('South German Sea','Bremen','Yes','No'),
	array('South German Sea','Friesland','Yes','No'),
	array('South German Sea','Lothairingia','Yes','No'),
	array('South German Sea','Veletia (West Coast)','Yes','No'),
	array('Brittish Channel','North Ocean Sea','Yes','No'),
	array('Brittish Channel','Lothairingia','Yes','No'),
	array('Brittish Channel','Paris','Yes','No'),
	array('Brittish Channel','Brittany','Yes','No'),
	array('North Ocean Sea','Brittany','Yes','No'),
	array('North Ocean Sea','Cantabric Sea','Yes','No'),
	array('North Ocean Sea','Galicia','Yes','No'),
	array('North Ocean Sea','Cadiz','Yes','No'),
	array('North Ocean Sea','Sea of Tangiers','Yes','No'),
	array('North Ocean Sea','Sea of Worms','Yes','No'),
	array('Norway','Uppland','No','Yes'),
	array('Norway','Viken','Yes','Yes'),
	array('Norway','Kattegat','Yes','No'),
	array('Norway','Saamiland','No','Yes'),
	array('Norway','Saamiland (North Coast)','Yes','No'),
	array('Uppland','Viken','No','Yes'),
	array('Uppland','Gottland','Yes','Yes'),
	array('Uppland','Lettish Sea','Yes','No'),
	array('Uppland','Finnish Sea','Yes','No'),
	array('Uppland','Saamiland','No','Yes'),
	array('Uppland','Saamiland (South Coast)','Yes','No'),
	array('Viken','Gottland','No','Yes'),
	array('Viken','Scania','Yes','Yes'),
	array('Viken','Kattegat','Yes','No'),
	array('Gottland','Scania','Yes','Yes'),
	array('Gottland','Lettish Sea','Yes','No'),
	array('Scania','Kattegat','Yes','No'),
	array('Scania','Abodrite Sea','Yes','No'),
	array('Scania','Lettish Sea','Yes','No'),
	array('Kattegat','Abodrite Sea','Yes','No'),
	array('Kattegat','Jelling','Yes','No'),
	array('Abodrite Sea','Lettish Sea','Yes','No'),
	array('Abodrite Sea','Borussia','Yes','No'),
	array('Abodrite Sea','Pomerania','Yes','No'),
	array('Abodrite Sea','Jelling','Yes','No'),
	array('Abodrite Sea','Veletia (North Coast)','Yes','No'),
	array('Lettish Sea','Finnish Sea','Yes','No'),
	array('Lettish Sea','Livonia','Yes','No'),
	array('Lettish Sea','Borussia','Yes','No'),
	array('Finnish Sea','Karelia','Yes','No'),
	array('Finnish Sea','Esteland','Yes','No'),
	array('Finnish Sea','Livonia','Yes','No'),
	array('Finnish Sea','Novgorod','Yes','No'),
	array('Finnish Sea','Saamiland (South Coast)','Yes','No'),
	array('White Sea','Bjarmaland','Yes','No'),
	array('White Sea','Kornia','Yes','No'),
	array('White Sea','Yugra','Yes','No'),
	array('White Sea','Tunguz','Yes','No'),
	array('Karelia','Novgorod','Yes','Yes'),
	array('Karelia','Bjarmaland','No','Yes'),
	array('Karelia','Rostov','No','Yes'),
	array('Karelia','Cheremissia','No','Yes'),
	array('Karelia','Saamiland','No','Yes'),
	array('Karelia','Saamiland (South Coast)','Yes','No'),
	array('Esteland','Livonia','Yes','Yes'),
	array('Esteland','Novgorod','Yes','Yes'),
	array('Livonia','Borussia','Yes','Yes'),
	array('Livonia','Novgorod','No','Yes'),
	array('Livonia','Dregovichia','No','Yes'),
	array('Livonia','Smolensk','No','Yes'),
	array('Borussia','Pomerania','Yes','Yes'),
	array('Borussia','Polania','No','Yes'),
	array('Borussia','Mazovia','No','Yes'),
	array('Borussia','Dregovichia','No','Yes'),
	array('Pomerania','Saxony','No','Yes'),
	array('Pomerania','Polania','No','Yes'),
	array('Pomerania','Veletia','No','Yes'),
	array('Pomerania','Veletia (North Coast)','Yes','No'),
	array('Jelling','Veletia','No','Yes'),
	array('Jelling','Veletia (North Coast)','Yes','No'),
	array('Jelling','Veletia (West Coast)','Yes','No'),
	array('Bremen','Friesland','Yes','Yes'),
	array('Bremen','Saxony','No','Yes'),
	array('Bremen','Franconia','No','Yes'),
	array('Bremen','Veletia','No','Yes'),
	array('Bremen','Veletia (West Coast)','Yes','No'),
	array('Friesland','Lothairingia','Yes','Yes'),
	array('Friesland','Franconia','No','Yes'),
	array('Novgorod','Smolensk','No','Yes'),
	array('Novgorod','Rostov','No','Yes'),
	array('Novgorod','Krivichia','No','Yes'),
	array('Lothairingia','Paris','Yes','Yes'),
	array('Lothairingia','Franconia','No','Yes'),
	array('Lothairingia','Swabia','No','Yes'),
	array('Lothairingia','Upper Burgundy','No','Yes'),
	array('Lothairingia','Autun','No','Yes'),
	array('Paris','Brittany','Yes','Yes'),
	array('Paris','Aquitaine','No','Yes'),
	array('Paris','Autun','No','Yes'),
	array('Brittany','Aquitaine','Yes','Yes'),
	array('Brittany','Cantabric Sea','Yes','No'),
	array('Aquitaine','Cantabric Sea','Yes','No'),
	array('Aquitaine','Autun','No','Yes'),
	array('Aquitaine','Toulouse','No','Yes'),
	array('Aquitaine','Gascony','Yes','Yes'),
	array('Bjarmaland','Kornia','Yes','Yes'),
	array('Bjarmaland','Cheremissia','No','Yes'),
	array('Bjarmaland','Saamiland','No','Yes'),
	array('Bjarmaland','Saamiland (North Coast)','Yes','No'),
	array('Kornia','Yugra','Yes','Yes'),
	array('Kornia','Stone Belt','No','Yes'),
	array('Kornia','Udmurtia','No','Yes'),
	array('Kornia','Bulgar','No','Yes'),
	array('Kornia','Cheremissia','No','Yes'),
	array('Yugra','Tunguz','Yes','Yes'),
	array('Yugra','Stone Belt','No','Yes'),
	array('Yugra','Bashkortostan','No','Yes'),
	array('Yugra','Kipchak','No','Yes'),
	array('Yugra','Kyrgyzstan','No','Yes'),
	array('Tunguz','Merkit','No','Yes'),
	array('Tunguz','Kyrgyzstan','No','Yes'),
	array('Tunguz','Ordu-Balyk','No','Yes'),
	array('Merkit','Ordu-Balyk','No','Yes'),
	array('Merkit','Khitai','No','Yes'),
	array('Merkit','Balhae','No','Yes'),
	array('Saxony','Polania','No','Yes'),
	array('Saxony','Franconia','No','Yes'),
	array('Saxony','Swabia','No','Yes'),
	array('Saxony','Bavaria','No','Yes'),
	array('Saxony','Veletia','No','Yes'),
	array('Polania','Mazovia','No','Yes'),
	array('Polania','Bavaria','No','Yes'),
	array('Polania','Moravia','No','Yes'),
	array('Polania','Volhynia','No','Yes'),
	array('Mazovia','Dregovichia','No','Yes'),
	array('Mazovia','Volhynia','No','Yes'),
	array('Dregovichia','Smolensk','No','Yes'),
	array('Dregovichia','Kiev','No','Yes'),
	array('Dregovichia','Volhynia','No','Yes'),
	array('Smolensk','Krivichia','No','Yes'),
	array('Smolensk','Kiev','No','Yes'),
	array('Smolensk','Vyatichia','No','Yes'),
	array('Cantabric Sea','Gascony','Yes','No'),
	array('Cantabric Sea','Pamplona','Yes','No'),
	array('Cantabric Sea','Asturias','Yes','No'),
	array('Cantabric Sea','Galicia','Yes','No'),
	array('Franconia','Swabia','No','Yes'),
	array('Swabia','Bavaria','No','Yes'),
	array('Swabia','Helvetia','No','Yes'),
	array('Swabia','Upper Burgundy','No','Yes'),
	array('Bavaria','Moravia','No','Yes'),
	array('Bavaria','Slavonia','No','Yes'),
	array('Bavaria','Aquileia','No','Yes'),
	array('Bavaria','Lombardy','No','Yes'),
	array('Bavaria','Helvetia','No','Yes'),
	array('Moravia','Volhynia','No','Yes'),
	array('Moravia','Onoguria','No','Yes'),
	array('Moravia','Slavonia','No','Yes'),
	array('Rostov','Krivichia','No','Yes'),
	array('Rostov','Cheremissia','No','Yes'),
	array('Krivichia','Cheremissia','No','Yes'),
	array('Krivichia','Vyatichia','No','Yes'),
	array('Kiev','Volhynia','No','Yes'),
	array('Kiev','Vlacha','No','Yes'),
	array('Kiev','Vyatichia','No','Yes'),
	array('Kiev','Severyana','No','Yes'),
	array('Kiev','Pechenega','No','Yes'),
	array('Volhynia','Vlacha','No','Yes'),
	array('Volhynia','Onoguria','No','Yes'),
	array('Vlacha','Onoguria','No','Yes'),
	array('Vlacha','Thrace','Yes','Yes'),
	array('Vlacha','West Euxine Sea','Yes','No'),
	array('Vlacha','Pechenega','No','Yes'),
	array('Vlacha','Pechenega (West Coast)','Yes','No'),
	array('Onoguria','Slavonia','No','Yes'),
	array('Onoguria','Macedonia','No','Yes'),
	array('Onoguria','Thrace','No','Yes'),
	array('Onoguria','Dalmatia','No','Yes'),
	array('Slavonia','Dalmatia','No','Yes'),
	array('Slavonia','Aquileia','No','Yes'),
	array('Macedonia','Thrace','No','Yes'),
	array('Macedonia','Constantinople','No','Yes'),
	array('Macedonia','Dalmatia','No','Yes'),
	array('Macedonia','Epirus','No','Yes'),
	array('Thrace','Constantinople','Yes','Yes'),
	array('Thrace','West Euxine Sea','Yes','No'),
	array('Constantinople','Epirus','Yes','Yes'),
	array('Constantinople','West Euxine Sea','Yes','No'),
	array('Constantinople','Aegean Sea','Yes','No'),
	array('Constantinople','Ionian Sea','Yes','No'),
	array('Constantinople','Buccellaria','Yes','Yes'),
	array('Constantinople','Attalia','Yes','Yes'),
	array('Dalmatia','Epirus','Yes','Yes'),
	array('Dalmatia','Aquileia','Yes','Yes'),
	array('Dalmatia','Illyrian Sea','Yes','No'),
	array('Epirus','Ionian Sea','Yes','No'),
	array('Epirus','Illyrian Sea','Yes','No'),
	array('Aquileia','Lombardy','No','Yes'),
	array('Aquileia','Illyrian Sea','Yes','No'),
	array('Aquileia','Rome','No','Yes'),
	array('Aquileia','Rome (East Coast)','Yes','No'),
	array('Spoleto','Taranto','Yes','Yes'),
	array('Spoleto','Salerno','No','Yes'),
	array('Spoleto','Illyrian Sea','Yes','No'),
	array('Spoleto','Rome','No','Yes'),
	array('Spoleto','Rome (East Coast)','Yes','No'),
	array('Taranto','Salerno','Yes','Yes'),
	array('Taranto','Ionian Sea','Yes','No'),
	array('Taranto','Illyrian Sea','Yes','No'),
	array('Taranto','Tyrrhenian Sea','Yes','No'),
	array('Salerno','Tyrrhenian Sea','Yes','No'),
	array('Salerno','Rome','No','Yes'),
	array('Salerno','Rome (West Coast)','Yes','No'),
	array('Lombardy','Helvetia','No','Yes'),
	array('Lombardy','Lower Burgundy','Yes','Yes'),
	array('Lombardy','Ligurian Sea','Yes','No'),
	array('Lombardy','Rome','No','Yes'),
	array('Lombardy','Rome (West Coast)','Yes','No'),
	array('Helvetia','Upper Burgundy','No','Yes'),
	array('Helvetia','Lower Burgundy','No','Yes'),
	array('Upper Burgundy','Autun','No','Yes'),
	array('Upper Burgundy','Lower Burgundy','No','Yes'),
	array('Autun','Narbonne','No','Yes'),
	array('Autun','Lower Burgundy','No','Yes'),
	array('Autun','Toulouse','No','Yes'),
	array('Narbonne','Lower Burgundy','Yes','Yes'),
	array('Narbonne','Toulouse','No','Yes'),
	array('Narbonne','Spanish March','Yes','Yes'),
	array('Narbonne','Ligurian Sea','Yes','No'),
	array('Lower Burgundy','Ligurian Sea','Yes','No'),
	array('Toulouse','Gascony','No','Yes'),
	array('Toulouse','Spanish March','No','Yes'),
	array('Toulouse','Pamplona','No','Yes'),
	array('Gascony','Pamplona','Yes','Yes'),
	array('Spanish March','Valencia','Yes','Yes'),
	array('Spanish March','Pamplona','No','Yes'),
	array('Spanish March','Zaragoza','No','Yes'),
	array('Spanish March','Balearic Sea','Yes','No'),
	array('Spanish March','Ligurian Sea','Yes','No'),
	array('Valencia','Zaragoza','No','Yes'),
	array('Valencia','Toledo','No','Yes'),
	array('Valencia','Granada','Yes','Yes'),
	array('Valencia','Cordova','No','Yes'),
	array('Valencia','Straits of Jebel Tarik','Yes','No'),
	array('Valencia','Balearic Sea','Yes','No'),
	array('Corsica','Tyrrhenian Sea','Yes','No'),
	array('Corsica','Balearic Sea','Yes','No'),
	array('Corsica','Ligurian Sea','Yes','No'),
	array('Sardinia','Tyrrhenian Sea','Yes','No'),
	array('Sardinia','Straits of Jebel Tarik','Yes','No'),
	array('Sardinia','Balearic Sea','Yes','No'),
	array('Sicily','Ionian Sea','Yes','No'),
	array('Sicily','Tyrrhenian Sea','Yes','No'),
	array('Sicily','Libyan Sea','Yes','No'),
	array('Crete','Aegean Sea','Yes','No'),
	array('Crete','Cilician Sea','Yes','No'),
	array('Crete','Egyptian Sea','Yes','No'),
	array('Crete','Ionian Sea','Yes','No'),
	array('Cyprus','Cilician Sea','Yes','No'),
	array('Cyprus','Sea of Tyre','Yes','No'),
	array('Cyprus','Egyptian Sea','Yes','No'),
	array('Pamplona','Asturias','Yes','Yes'),
	array('Pamplona','Zaragoza','No','Yes'),
	array('Asturias','Galicia','Yes','Yes'),
	array('Asturias','Zaragoza','No','Yes'),
	array('Asturias','Salamanca','No','Yes'),
	array('Galicia','Salamanca','No','Yes'),
	array('Galicia','Cadiz','Yes','Yes'),
	array('Zaragoza','Toledo','No','Yes'),
	array('Zaragoza','Salamanca','No','Yes'),
	array('Toledo','Cordova','No','Yes'),
	array('Toledo','Salamanca','No','Yes'),
	array('Granada','Cordova','No','Yes'),
	array('Granada','Cadiz','Yes','Yes'),
	array('Granada','Straits of Jebel Tarik','Yes','No'),
	array('Cordova','Salamanca','No','Yes'),
	array('Cordova','Cadiz','No','Yes'),
	array('Salamanca','Cadiz','No','Yes'),
	array('Cadiz','Straits of Jebel Tarik','Yes','No'),
	array('Cadiz','Sea of Tangiers','Yes','No'),
	array('Cherson','West Euxine Sea','Yes','No'),
	array('Cherson','East Euxine Sea','Yes','No'),
	array('Cherson','Pechenega','No','Yes'),
	array('Cherson','Pechenega (East Coast)','Yes','No'),
	array('Cherson','Pechenega (West Coast)','Yes','No'),
	array('Stone Belt','Udmurtia','No','Yes'),
	array('Stone Belt','Bashkortostan','No','Yes'),
	array('Udmurtia','Bulgar','No','Yes'),
	array('Udmurtia','Mordvinia','No','Yes'),
	array('Udmurtia','Bashkortostan','No','Yes'),
	array('Udmurtia','Atil','No','Yes'),
	array('Bulgar','Cheremissia','No','Yes'),
	array('Bulgar','Vyatichia','No','Yes'),
	array('Bulgar','Mordvinia','No','Yes'),
	array('Cheremissia','Vyatichia','No','Yes'),
	array('Mauretania','Kutamia','Yes','Yes'),
	array('Mauretania','Straits of Jebel Tarik','Yes','No'),
	array('Mauretania','Sea of Tangiers','Yes','No'),
	array('Mauretania','Tahert','No','Yes'),
	array('Mauretania','Barghawata','Yes','Yes'),
	array('Mauretania','Sijilmassa','No','Yes'),
	array('Kutamia','Straits of Jebel Tarik','Yes','No'),
	array('Kutamia','Ifriqiya','Yes','Yes'),
	array('Kutamia','Tahert','No','Yes'),
	array('Vyatichia','Severyana','No','Yes'),
	array('Vyatichia','Mordvinia','No','Yes'),
	array('Severyana','Mordvinia','No','Yes'),
	array('Severyana','Sarkel','No','Yes'),
	array('Severyana','Tamantarka','No','Yes'),
	array('Severyana','Pechenega','No','Yes'),
	array('Mordvinia','Atil','No','Yes'),
	array('Mordvinia','Sarkel','No','Yes'),
	array('West Euxine Sea','East Euxine Sea','Yes','No'),
	array('West Euxine Sea','Buccellaria','Yes','No'),
	array('West Euxine Sea','Pechenega (West Coast)','Yes','No'),
	array('East Euxine Sea','Tamantarka','Yes','No'),
	array('East Euxine Sea','Abkhazia','Yes','No'),
	array('East Euxine Sea','Georgia','Yes','No'),
	array('East Euxine Sea','Buccellaria','Yes','No'),
	array('East Euxine Sea','Pechenega (East Coast)','Yes','No'),
	array('Aegean Sea','Cilician Sea','Yes','No'),
	array('Aegean Sea','Ionian Sea','Yes','No'),
	array('Aegean Sea','Attalia','Yes','No'),
	array('Cilician Sea','Sea of Tyre','Yes','No'),
	array('Cilician Sea','Egyptian Sea','Yes','No'),
	array('Cilician Sea','Attalia','Yes','No'),
	array('Cilician Sea','Cappadocia','Yes','No'),
	array('Sea of Tyre','Egyptian Sea','Yes','No'),
	array('Sea of Tyre','Cappadocia','Yes','No'),
	array('Sea of Tyre','Damascus','Yes','No'),
	array('Sea of Tyre','Jerusalem','Yes','No'),
	array('Egyptian Sea','Ionian Sea','Yes','No'),
	array('Egyptian Sea','Libyan Sea','Yes','No'),
	array('Egyptian Sea','Barca','Yes','No'),
	array('Egyptian Sea','Alexandria','Yes','No'),
	array('Egyptian Sea','Jerusalem','Yes','No'),
	array('Ionian Sea','Illyrian Sea','Yes','No'),
	array('Ionian Sea','Tyrrhenian Sea','Yes','No'),
	array('Ionian Sea','Libyan Sea','Yes','No'),
	array('Illyrian Sea','Rome (East Coast)','Yes','No'),
	array('Tyrrhenian Sea','Libyan Sea','Yes','No'),
	array('Tyrrhenian Sea','Straits of Jebel Tarik','Yes','No'),
	array('Tyrrhenian Sea','Balearic Sea','Yes','No'),
	array('Tyrrhenian Sea','Ligurian Sea','Yes','No'),
	array('Tyrrhenian Sea','Ifriqiya','Yes','No'),
	array('Tyrrhenian Sea','Rome (West Coast)','Yes','No'),
	array('Libyan Sea','Ifriqiya','Yes','No'),
	array('Libyan Sea','Tripolitania','Yes','No'),
	array('Libyan Sea','Barca','Yes','No'),
	array('Straits of Jebel Tarik','Balearic Sea','Yes','No'),
	array('Straits of Jebel Tarik','Sea of Tangiers','Yes','No'),
	array('Straits of Jebel Tarik','Ifriqiya','Yes','No'),
	array('Balearic Sea','Ligurian Sea','Yes','No'),
	array('Ligurian Sea','Rome (West Coast)','Yes','No'),
	array('Sea of Tangiers','Sea of Worms','Yes','No'),
	array('Sea of Tangiers','Tkanaren','Yes','No'),
	array('Sea of Tangiers','Takrur Sea','Yes','No'),
	array('Sea of Tangiers','Barghawata','Yes','No'),
	array('Sea of Worms','Tkanaren','Yes','No'),
	array('Sea of Worms','Western Sea','Yes','No'),
	array('Kotoko','Kongo','Yes','Yes'),
	array('Kotoko','Assode','No','Yes'),
	array('Kotoko','Kanem','No','Yes'),
	array('Kotoko','South Ocean Sea','Yes','No'),
	array('Kotoko','Niore','No','Yes'),
	array('Kotoko','Kangaba','Yes','Yes'),
	array('Kotoko','Bassikinu','No','Yes'),
	array('Kotoko','Tiraqqa','No','Yes'),
	array('Kotoko','Jenne-Jeno','No','Yes'),
	array('Kotoko','Luba','No','Yes'),
	array('Kotoko','Luo','No','Yes'),
	array('Kongo','Namib','Yes','Yes'),
	array('Kongo','South Ocean Sea','Yes','No'),
	array('Kongo','Zimbabwe','No','Yes'),
	array('Kongo','Luba','No','Yes'),
	array('Namib','South Ocean Sea','Yes','No'),
	array('Namib','Gokomere Sea','Yes','No'),
	array('Namib','Zimbabwe','Yes','Yes'),
	array('Ifriqiya','Tahert','No','Yes'),
	array('Ifriqiya','Tripolitania','Yes','Yes'),
	array('Ifriqiya','Fazzan','No','Yes'),
	array('Tahert','Sijilmassa','No','Yes'),
	array('Tahert','Fazzan','No','Yes'),
	array('Tahert','Assode','No','Yes'),
	array('Tkanaren','Takrur Sea','Yes','No'),
	array('Tkanaren','Western Sea','Yes','No'),
	array('Takrur Sea','Barghawata','Yes','No'),
	array('Takrur Sea','Sanhaja','Yes','No'),
	array('Takrur Sea','Western Sea','Yes','No'),
	array('Takrur Sea','South Ocean Sea','Yes','No'),
	array('Takrur Sea','Awlil','Yes','No'),
	array('Barghawata','Sijilmassa','No','Yes'),
	array('Barghawata','Sanhaja','Yes','Yes'),
	array('Sijilmassa','Sanhaja','No','Yes'),
	array('Sijilmassa','Assode','No','Yes'),
	array('Sijilmassa','Walata','No','Yes'),
	array('Sanhaja','Awlil','Yes','Yes'),
	array('Sanhaja','Awdagost','No','Yes'),
	array('Sanhaja','Kumbi Saleh','No','Yes'),
	array('Sanhaja','Walata','No','Yes'),
	array('Tripolitania','Barca','Yes','Yes'),
	array('Tripolitania','Fazzan','No','Yes'),
	array('Tripolitania','Alexandria','No','Yes'),
	array('Barca','Alexandria','Yes','Yes'),
	array('Fazzan','Assode','No','Yes'),
	array('Fazzan','Zawila','No','Yes'),
	array('Fazzan','Daju','No','Yes'),
	array('Fazzan','Alexandria','No','Yes'),
	array('Fazzan','Al-Qatta\\\'i','No','Yes'),
	array('Assode','Kanem','No','Yes'),
	array('Assode','Zawila','No','Yes'),
	array('Assode','Daju','No','Yes'),
	array('Assode','Walata','No','Yes'),
	array('Assode','Tiraqqa','No','Yes'),
	array('Kanem','Daju','No','Yes'),
	array('Kanem','Sudd','No','Yes'),
	array('Kanem','Luo','No','Yes'),
	array('Zawila','Daju','No','Yes'),
	array('Daju','Al-Qatta\\\'i','No','Yes'),
	array('Daju','Makuran','No','Yes'),
	array('Daju','Sudd','No','Yes'),
	array('Alexandria','Al-Qatta\\\'i','Yes','Yes'),
	array('Alexandria','North Red Sea','Yes','No'),
	array('Alexandria','Mecca','Yes','Yes'),
	array('Alexandria','Jerusalem','Yes','Yes'),
	array('Al-Qatta\\\'i','North Red Sea','Yes','No'),
	array('Al-Qatta\\\'i','Berenice','Yes','Yes'),
	array('Al-Qatta\\\'i','Makuran','No','Yes'),
	array('North Red Sea','Berenice','Yes','No'),
	array('North Red Sea','Mecca','Yes','No'),
	array('North Red Sea','South Red Sea','Yes','No'),
	array('Berenice','Makuran','No','Yes'),
	array('Berenice','Meroe','Yes','Yes'),
	array('Berenice','South Red Sea','Yes','No'),
	array('Makuran','Meroe','No','Yes'),
	array('Makuran','Sudd','No','Yes'),
	array('Bashkortostan','Atil','No','Yes'),
	array('Bashkortostan','Kipchak','No','Yes'),
	array('Atil','North Khazar Sea','Yes','No'),
	array('Atil','Sarkel','No','Yes'),
	array('Atil','Balanjar','Yes','Yes'),
	array('Atil','Kipchak','Yes','Yes'),
	array('North Khazar Sea','South Khazar Sea','Yes','No'),
	array('North Khazar Sea','Balanjar','Yes','No'),
	array('North Khazar Sea','Derbent','Yes','No'),
	array('North Khazar Sea','Ghuzz','Yes','No'),
	array('North Khazar Sea','Urgench','Yes','No'),
	array('North Khazar Sea','Kipchak','Yes','No'),
	array('South Khazar Sea','Derbent','Yes','No'),
	array('South Khazar Sea','Azerbaijan','Yes','No'),
	array('South Khazar Sea','Ardebil','Yes','No'),
	array('South Khazar Sea','Alidistan','Yes','No'),
	array('South Khazar Sea','Urgench','Yes','No'),
	array('Sarkel','Tamantarka','No','Yes'),
	array('Sarkel','Balanjar','No','Yes'),
	array('Tamantarka','Abkhazia','Yes','Yes'),
	array('Tamantarka','Balanjar','No','Yes'),
	array('Tamantarka','Pechenega','No','Yes'),
	array('Tamantarka','Pechenega (East Coast)','Yes','No'),
	array('Abkhazia','Balanjar','No','Yes'),
	array('Abkhazia','Georgia','Yes','Yes'),
	array('Balanjar','Derbent','Yes','Yes'),
	array('Balanjar','Georgia','No','Yes'),
	array('Balanjar','Kakheti','No','Yes'),
	array('Derbent','Kakheti','No','Yes'),
	array('Derbent','Azerbaijan','Yes','Yes'),
	array('Georgia','Buccellaria','Yes','Yes'),
	array('Georgia','Cappadocia','No','Yes'),
	array('Georgia','Kakheti','No','Yes'),
	array('Buccellaria','Attalia','No','Yes'),
	array('Buccellaria','Cappadocia','No','Yes'),
	array('Attalia','Cappadocia','Yes','Yes'),
	array('Cappadocia','Damascus','Yes','Yes'),
	array('Cappadocia','Kakheti','No','Yes'),
	array('Cappadocia','Armenia','No','Yes'),
	array('Damascus','Armenia','No','Yes'),
	array('Damascus','Mosul','No','Yes'),
	array('Damascus','Baghdad','No','Yes'),
	array('Damascus','Mecca','No','Yes'),
	array('Damascus','Jerusalem','Yes','Yes'),
	array('Damascus','Nefud','No','Yes'),
	array('Kakheti','Armenia','No','Yes'),
	array('Kakheti','Mosul','No','Yes'),
	array('Kakheti','Azerbaijan','No','Yes'),
	array('Armenia','Mosul','No','Yes'),
	array('Mosul','Baghdad','No','Yes'),
	array('Mosul','Azerbaijan','No','Yes'),
	array('Mosul','Ardebil','No','Yes'),
	array('Baghdad','Ardebil','No','Yes'),
	array('Baghdad','Isfahan','No','Yes'),
	array('Baghdad','Nefud','No','Yes'),
	array('Baghdad','Basra','No','Yes'),
	array('Azerbaijan','Ardebil','Yes','Yes'),
	array('Ghuzz','Urgench','Yes','Yes'),
	array('Ghuzz','Kipchak','Yes','Yes'),
	array('Ghuzz','Kyzyl Kum','No','Yes'),
	array('Ardebil','Alidistan','Yes','Yes'),
	array('Ardebil','Isfahan','No','Yes'),
	array('Alidistan','Urgench','Yes','Yes'),
	array('Alidistan','Isfahan','No','Yes'),
	array('Alidistan','Khorasan','No','Yes'),
	array('Urgench','Khorasan','No','Yes'),
	array('Urgench','Kyzyl Kum','No','Yes'),
	array('Urgench','Bukhara','No','Yes'),
	array('Urgench','Herat','No','Yes'),
	array('Kipchak','Kyrgyzstan','No','Yes'),
	array('Kipchak','Kyzyl Kum','No','Yes'),
	array('Isfahan','Khorasan','No','Yes'),
	array('Isfahan','Basra','No','Yes'),
	array('Isfahan','Sijistan','No','Yes'),
	array('Khorasan','Sijistan','No','Yes'),
	array('Khorasan','Herat','No','Yes'),
	array('Kyrgyzstan','Kyzyl Kum','No','Yes'),
	array('Kyrgyzstan','Qarluk','No','Yes'),
	array('Kyrgyzstan','Ordu-Balyk','No','Yes'),
	array('Kyzyl Kum','Qarluk','No','Yes'),
	array('Kyzyl Kum','Samarkand','No','Yes'),
	array('Kyzyl Kum','Bukhara','No','Yes'),
	array('Qarluk','Ordu-Balyk','No','Yes'),
	array('Qarluk','Samarkand','No','Yes'),
	array('Ordu-Balyk','Khitai','No','Yes'),
	array('Ordu-Balyk','Changcheng','No','Yes'),
	array('Ordu-Balyk','Uyghurstan','No','Yes'),
	array('Ordu-Balyk','Samarkand','No','Yes'),
	array('Khitai','Changcheng','No','Yes'),
	array('Khitai','Yanjing','No','Yes'),
	array('Khitai','Balhae','No','Yes'),
	array('Changcheng','Yanjing','No','Yes'),
	array('Changcheng','Uyghurstan','No','Yes'),
	array('Changcheng','Chang\\\'an','No','Yes'),
	array('Yanjing','Yellow Sea','Yes','No'),
	array('Yanjing','Chang\\\'an','No','Yes'),
	array('Yanjing','Henan','Yes','Yes'),
	array('Yanjing','Balhae','No','Yes'),
	array('Yanjing','Balhae (South Coast)','Yes','No'),
	array('Silla','Yellow Sea','Yes','No'),
	array('Silla','Sea of Nihon','Yes','No'),
	array('Silla','Eastern Sea','Yes','No'),
	array('Silla','Balhae','No','Yes'),
	array('Silla','Balhae (East Coast)','Yes','No'),
	array('Silla','Balhae (South Coast)','Yes','No'),
	array('Yellow Sea','Henan','Yes','No'),
	array('Yellow Sea','Nanjing','Yes','No'),
	array('Yellow Sea','Eastern Sea','Yes','No'),
	array('Yellow Sea','Balhae (South Coast)','Yes','No'),
	array('Sea of Nihon','Eastern Sea','Yes','No'),
	array('Sea of Nihon','Saikaido','Yes','No'),
	array('Sea of Nihon','Lusong Sea','Yes','No'),
	array('Sea of Nihon','Balhae (East Coast)','Yes','No'),
	array('Uyghurstan','Samarkand','No','Yes'),
	array('Uyghurstan','Sogdia','No','Yes'),
	array('Uyghurstan','Amdo','No','Yes'),
	array('Uyghurstan','Chang\\\'an','No','Yes'),
	array('Samarkand','Bukhara','No','Yes'),
	array('Samarkand','Sogdia','No','Yes'),
	array('Samarkand','Balkh','No','Yes'),
	array('Bukhara','Herat','No','Yes'),
	array('Bukhara','Balkh','No','Yes'),
	array('Sogdia','Balkh','No','Yes'),
	array('Sogdia','Kashmir','No','Yes'),
	array('Sogdia','Tibet','No','Yes'),
	array('Sogdia','Amdo','No','Yes'),
	array('Western Sea','South Ocean Sea','Yes','No'),
	array('Western Sea','Antipodean Sea','Yes','No'),
	array('South Ocean Sea','Antipodean Sea','Yes','No'),
	array('South Ocean Sea','Gokomere Sea','Yes','No'),
	array('South Ocean Sea','Awlil','Yes','No'),
	array('South Ocean Sea','Bure','Yes','No'),
	array('South Ocean Sea','Kangaba','Yes','No'),
	array('Antipodean Sea','Gokomere Sea','Yes','No'),
	array('Antipodean Sea','Menuthian Sea','Yes','No'),
	array('Antipodean Sea','Phebol','Yes','No'),
	array('Antipodean Sea','Mahilaka','Yes','No'),
	array('Antipodean Sea','Southern Sea','Yes','No'),
	array('Gokomere Sea','Zimbabwe','Yes','No'),
	array('Gokomere Sea','Menuthian Sea','Yes','No'),
	array('Zimbabwe','Luba','No','Yes'),
	array('Zimbabwe','Rhapta','Yes','Yes'),
	array('Zimbabwe','Menuthian Sea','Yes','No'),
	array('Awlil','Awdagost','No','Yes'),
	array('Awlil','Bure','Yes','Yes'),
	array('Awdagost','Kumbi Saleh','No','Yes'),
	array('Awdagost','Bure','No','Yes'),
	array('Awdagost','Niore','No','Yes'),
	array('Kumbi Saleh','Walata','No','Yes'),
	array('Kumbi Saleh','Niore','No','Yes'),
	array('Walata','Niore','No','Yes'),
	array('Walata','Bassikinu','No','Yes'),
	array('Walata','Tiraqqa','No','Yes'),
	array('Bure','Niore','No','Yes'),
	array('Bure','Kangaba','Yes','Yes'),
	array('Niore','Kangaba','No','Yes'),
	array('Niore','Bassikinu','No','Yes'),
	array('Bassikinu','Tiraqqa','No','Yes'),
	array('Bassikinu','Jenne-Jeno','No','Yes'),
	array('Tiraqqa','Jenne-Jeno','No','Yes'),
	array('Luba','Rhapta','No','Yes'),
	array('Luba','Malao','No','Yes'),
	array('Luba','Luo','No','Yes'),
	array('Luba','Roha','No','Yes'),
	array('Rhapta','Azania','Yes','Yes'),
	array('Rhapta','Malao','No','Yes'),
	array('Rhapta','Menuthian Sea','Yes','No'),
	array('Azania','Malao','Yes','Yes'),
	array('Azania','Menuthian Sea','Yes','No'),
	array('Azania','Gulf of Aden','Yes','No'),
	array('Malao','Zeila','Yes','Yes'),
	array('Malao','Roha','No','Yes'),
	array('Malao','Gulf of Aden','Yes','No'),
	array('Zeila','Adulis','Yes','Yes'),
	array('Zeila','Roha','No','Yes'),
	array('Zeila','Gulf of Aden','Yes','No'),
	array('Adulis','Meroe','Yes','Yes'),
	array('Adulis','Roha','No','Yes'),
	array('Adulis','Axum','No','Yes'),
	array('Adulis','Gulf of Aden','Yes','No'),
	array('Adulis','South Red Sea','Yes','No'),
	array('Meroe','Sudd','No','Yes'),
	array('Meroe','Axum','No','Yes'),
	array('Meroe','South Red Sea','Yes','No'),
	array('Sudd','Luo','No','Yes'),
	array('Sudd','Roha','No','Yes'),
	array('Sudd','Axum','No','Yes'),
	array('Luo','Roha','No','Yes'),
	array('Roha','Axum','No','Yes'),
	array('Menuthian Sea','Gulf of Aden','Yes','No'),
	array('Menuthian Sea','Phebol','Yes','No'),
	array('Gulf of Aden','Phebol','Yes','No'),
	array('Gulf of Aden','Mahilaka','Yes','No'),
	array('Gulf of Aden','Socotra','Yes','No'),
	array('Gulf of Aden','Yemen','Yes','No'),
	array('Gulf of Aden','Arabian Sea','Yes','No'),
	array('Gulf of Aden','Malabar Sea','Yes','No'),
	array('Gulf of Aden','South Red Sea','Yes','No'),
	array('Phebol','Mahilaka','Yes','Yes'),
	array('Mahilaka','Malabar Sea','Yes','No'),
	array('Mahilaka','Southern Sea','Yes','No'),
	array('Socotra','Arabian Sea','Yes','No'),
	array('Socotra','Malabar Sea','Yes','No'),
	array('Yemen','Mecca','Yes','Yes'),
	array('Yemen','Nefud','No','Yes'),
	array('Yemen','Oman','Yes','Yes'),
	array('Yemen','Arabian Sea','Yes','No'),
	array('Yemen','South Red Sea','Yes','No'),
	array('Mecca','Jerusalem','No','Yes'),
	array('Mecca','Nefud','No','Yes'),
	array('Mecca','South Red Sea','Yes','No'),
	array('Nefud','Oman','No','Yes'),
	array('Nefud','Basra','No','Yes'),
	array('Oman','Basra','Yes','Yes'),
	array('Oman','Arabian Sea','Yes','No'),
	array('Basra','Sijistan','No','Yes'),
	array('Basra','Mansurah','Yes','Yes'),
	array('Basra','Arabian Sea','Yes','No'),
	array('Sijistan','Herat','No','Yes'),
	array('Sijistan','Mansurah','No','Yes'),
	array('Herat','Balkh','No','Yes'),
	array('Herat','Mansurah','No','Yes'),
	array('Balkh','Mansurah','No','Yes'),
	array('Balkh','Kashmir','No','Yes'),
	array('Balkh','Shahiya','No','Yes'),
	array('Mansurah','Arabian Sea','Yes','No'),
	array('Mansurah','Shahiya','No','Yes'),
	array('Mansurah','Ujjain','Yes','Yes'),
	array('Arabian Sea','Malabar Sea','Yes','No'),
	array('Arabian Sea','Ujjain','Yes','No'),
	array('Malabar Sea','Southern Sea','Yes','No'),
	array('Malabar Sea','Minang Sea','Yes','No'),
	array('Malabar Sea','Coromandel Bay','Yes','No'),
	array('Malabar Sea','Serendib','Yes','No'),
	array('Malabar Sea','Chola','Yes','No'),
	array('Malabar Sea','Rastrakuta','Yes','No'),
	array('Malabar Sea','Ujjain','Yes','No'),
	array('Kashmir','Shahiya','No','Yes'),
	array('Kashmir','Indraprastha','No','Yes'),
	array('Kashmir','Nepal','No','Yes'),
	array('Kashmir','Tibet','No','Yes'),
	array('Shahiya','Indraprastha','No','Yes'),
	array('Shahiya','Ujjain','No','Yes'),
	array('Indraprastha','Kannauj','No','Yes'),
	array('Indraprastha','Nepal','No','Yes'),
	array('Indraprastha','Ujjain','No','Yes'),
	array('Kannauj','Nepal','No','Yes'),
	array('Kannauj','Rastrakuta','No','Yes'),
	array('Kannauj','Ujjain','No','Yes'),
	array('Kannauj','Chalukya','No','Yes'),
	array('Kannauj','Varanasi','No','Yes'),
	array('Nepal','Tibet','No','Yes'),
	array('Nepal','Varanasi','No','Yes'),
	array('Nepal','Pala','No','Yes'),
	array('Tibet','Amdo','No','Yes'),
	array('Tibet','Chang\\\'an','No','Yes'),
	array('Tibet','Pala','No','Yes'),
	array('Tibet','Nanzhao','No','Yes'),
	array('Tibet','Sichuan','No','Yes'),
	array('Amdo','Chang\\\'an','No','Yes'),
	array('Chang\\\'an','Henan','No','Yes'),
	array('Chang\\\'an','Nanzhao','No','Yes'),
	array('Chang\\\'an','Sichuan','No','Yes'),
	array('Chang\\\'an','Jiangxi','No','Yes'),
	array('Henan','Nanjing','Yes','Yes'),
	array('Henan','Jiangxi','No','Yes'),
	array('Nanjing','Eastern Sea','Yes','No'),
	array('Nanjing','Jiangxi','No','Yes'),
	array('Nanjing','Guangzhou','Yes','Yes'),
	array('Eastern Sea','Saikaido','Yes','No'),
	array('Eastern Sea','Lusong Sea','Yes','No'),
	array('Eastern Sea','Sea of Tepanga','Yes','No'),
	array('Eastern Sea','Guangzhou','Yes','No'),
	array('Saikaido','Lusong Sea','Yes','No'),
	array('Lusong Sea','Sea of Tepanga','Yes','No'),
	array('Lusong Sea','Java Sea','Yes','No'),
	array('Lusong Sea','Butuan','Yes','No'),
	array('Sea of Tepanga','Sea of Cham','Yes','No'),
	array('Sea of Tepanga','Guangzhou','Yes','No'),
	array('Sea of Tepanga','Butuan','Yes','No'),
	array('Sea of Cham','Java Sea','Yes','No'),
	array('Sea of Cham','Karimata Straits','Yes','No'),
	array('Sea of Cham','Guangzhou','Yes','No'),
	array('Sea of Cham','Annam','Yes','No'),
	array('Sea of Cham','Champa','Yes','No'),
	array('Sea of Cham','Kambuja','Yes','No'),
	array('Sea of Cham','Kalimantan','Yes','No'),
	array('Sea of Cham','Sabah','Yes','No'),
	array('Sea of Cham','Butuan','Yes','No'),
	array('Java Sea','Karimata Straits','Yes','No'),
	array('Java Sea','Southern Sea','Yes','No'),
	array('Java Sea','Palembang','Yes','No'),
	array('Java Sea','Kalimantan','Yes','No'),
	array('Java Sea','Sabah','Yes','No'),
	array('Java Sea','Butuan','Yes','No'),
	array('Karimata Straits','Andaman Sea','Yes','No'),
	array('Karimata Straits','Kambuja','Yes','No'),
	array('Karimata Straits','Cahaya','Yes','No'),
	array('Karimata Straits','Jambi','Yes','No'),
	array('Karimata Straits','Palembang','Yes','No'),
	array('Karimata Straits','Kalimantan','Yes','No'),
	array('Southern Sea','Minang Sea','Yes','No'),
	array('Southern Sea','Jambi','Yes','No'),
	array('Southern Sea','Palembang','Yes','No'),
	array('Minang Sea','Andaman Sea','Yes','No'),
	array('Minang Sea','Serendib','Yes','No'),
	array('Minang Sea','Jambi','Yes','No'),
	array('Andaman Sea','Coromandel Bay','Yes','No'),
	array('Andaman Sea','Serendib','Yes','No'),
	array('Andaman Sea','Dvaravati','Yes','No'),
	array('Andaman Sea','Cahaya','Yes','No'),
	array('Andaman Sea','Jambi','Yes','No'),
	array('Coromandel Bay','Serendib','Yes','No'),
	array('Coromandel Bay','Chola','Yes','No'),
	array('Coromandel Bay','Chalukya','Yes','No'),
	array('Coromandel Bay','Varanasi','Yes','No'),
	array('Coromandel Bay','Pala','Yes','No'),
	array('Coromandel Bay','Dvaravati','Yes','No'),
	array('Chola','Rastrakuta','Yes','Yes'),
	array('Chola','Chalukya','Yes','Yes'),
	array('Rastrakuta','Ujjain','Yes','Yes'),
	array('Rastrakuta','Chalukya','No','Yes'),
	array('Chalukya','Varanasi','Yes','Yes'),
	array('Varanasi','Pala','Yes','Yes'),
	array('Pala','Pagan','No','Yes'),
	array('Pala','Nanzhao','No','Yes'),
	array('Pala','Dvaravati','Yes','Yes'),
	array('Pagan','Nanzhao','No','Yes'),
	array('Pagan','Dvaravati','No','Yes'),
	array('Nanzhao','Sichuan','No','Yes'),
	array('Nanzhao','Jiangxi','No','Yes'),
	array('Nanzhao','Guangzhou','No','Yes'),
	array('Nanzhao','Annam','No','Yes'),
	array('Nanzhao','Dvaravati','No','Yes'),
	array('Jiangxi','Guangzhou','No','Yes'),
	array('Guangzhou','Annam','Yes','Yes'),
	array('Annam','Champa','Yes','Yes'),
	array('Annam','Kambuja','No','Yes'),
	array('Annam','Dvaravati','No','Yes'),
	array('Champa','Kambuja','Yes','Yes'),
	array('Kambuja','Dvaravati','No','Yes'),
	array('Kambuja','Cahaya','Yes','Yes'),
	array('Dvaravati','Cahaya','Yes','Yes'),
	array('Jambi','Palembang','Yes','Yes'),
	array('Kalimantan','Sabah','Yes','Yes')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

// Custom footer not changed by edit tool

// Just create the database as usual:
InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);

// Copy the smallmap-sample to the cache-directory to avoid a screwed variantpage (there is no smallmap available)
copy ('variants/'.$this->name.'/resources/sampleMap.png','variants/'.$this->name.'/cache/sampleMap.png');








