<?php
// This is file installs the map data for the AncMed variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Lusitania', 'Land', 'No', 0, 40, 280, 20, 135),
	array('Tarraconensis', 'Coast', 'No', 0, 165, 280, 80, 130),
	array('Saguntum', 'Coast', 'Yes', 0, 75, 380, 65, 177),
	array('Gaul', 'Land', 'No', 0, 250, 120, 120, 45),
	array('Massilia', 'Coast', 'Yes', 0, 327, 182, 165, 93),
	array('Rhaetia', 'Land', 'No', 0, 440, 80, 205, 45),
	array('Etruria', 'Coast', 'No', 0, 405, 165, 190, 85),
	array('Venetia', 'Coast', 'No', 0, 470, 130, 233, 65),
	array('Roma', 'Coast', 'Yes', 5, 475, 248, 216, 110),
	array('Ravenna', 'Coast', 'Yes', 5, 481, 190, 239, 105),
	array('Neapolis', 'Coast', 'Yes', 5, 566, 322, 280, 172),
	array('Apulia', 'Coast', 'No', 0, 560, 271, 264, 132),
	array('Vindobona', 'Land', 'Yes', 0, 530, 80, 258, 47),
	array('Dalmatia', 'Coast', 'Yes', 0, 594, 200, 280, 95),
	array('Illyria', 'Land', 'No', 0, 710, 227, 323, 98),
	array('Sarmatia', 'Land', 'No', 0, 685, 65, 320, 25),
	array('Dacia', 'Coast', 'No', 0, 800, 187, 385, 90),
	array('Chersonesus', 'Coast', 'Yes', 0, 990, 58, 452, 42),
	array('Epirus', 'Coast', 'No', 0, 695, 335, 330, 165),
	array('Macedonia', 'Coast', 'Yes', 3, 760, 295, 370, 155),
	array('Athens', 'Coast', 'Yes', 3, 750, 373, 355, 174),
	array('Sparta', 'Coast', 'Yes', 3, 757, 423, 365, 202),
	array('Byzantium', 'Coast', 'Yes', 0, 905, 315, 415, 159),
	array('Bithynia', 'Coast', 'No', 0, 990, 257, 457, 129),
	array('Sinope', 'Coast', 'Yes', 0, 1095, 248, 527, 111),
	array('Miletus', 'Coast', 'Yes', 0, 920, 390, 430, 192),
	array('Galatia', 'Land', 'No', 0, 1010, 322, 470, 150),
	array('Isauria', 'Coast', 'No', 0, 1025, 392, 485, 196),
	array('Cappadocia', 'Coast', 'No', 0, 1100, 340, 520, 164),
	array('Armenia', 'Land', 'No', 0, 1240, 270, 580, 135),
	array('Antioch', 'Coast', 'Yes', 4, 1160, 400, 547, 185),
	array('Damascus', 'Land', 'Yes', 4, 1250, 390, 585, 195),
	array('Sidon', 'Coast', 'Yes', 4, 1162, 451, 555, 220),
	array('Tyre', 'Coast', 'Yes', 0, 1163, 503, 550, 235),
	array('Arabia', 'Land', 'No', 0, 1230, 514, 585, 240),
	array('Jerusalem', 'Coast', 'Yes', 0, 1145, 560, 540, 274),
	array('Petra', 'Coast', 'Yes', 0, 1168, 632, 550, 311),
	array('Nabatea', 'Coast', 'No', 0, 1240, 650, 585, 310),
	array('Sinai', 'Coast', 'No', 0, 1105, 600, 520, 282),
	array('Thebes', 'Coast', 'Yes', 2, 1107, 720, 525, 350),
	array('Bayuda', 'Coast', 'No', 0, 860, 780, 420, 365),
	array('Memphis', 'Coast', 'Yes', 2, 960, 715, 460, 328),
	array('Alexandria', 'Coast', 'Yes', 2, 940, 630, 440, 295),
	array('Cyrene', 'Coast', 'Yes', 0, 760, 630, 365, 293),
	array('Marmarica', 'Land', 'No', 0, 730, 730, 355, 335),
	array('Leptis', 'Coast', 'Yes', 0, 530, 638, 270, 310),
	array('Phazania', 'Land', 'No', 0, 480, 680, 245, 330),
	array('Sahara', 'Land', 'No', 0, 260, 650, 135, 298),
	array('Numidia', 'Coast', 'Yes', 0, 428, 590, 205, 274),
	array('Thapsus', 'Coast', 'Yes', 1, 400, 525, 187, 245),
	array('Carthage', 'Coast', 'Yes', 1, 365, 460, 175, 215),
	array('Cirta', 'Land', 'Yes', 1, 312, 532, 148, 255),
	array('Mauretania', 'Coast', 'No', 0, 125, 525, 70, 245),
	array('Baleares', 'Coast', 'Yes', 0, 252, 335, 111, 155),
	array('Sardinia', 'Coast', 'Yes', 0, 398, 340, 188, 155),
	array('Corsica', 'Coast', 'No', 0, 400, 270, 190, 125),
	array('Sicilia', 'Coast', 'Yes', 0, 530, 422, 250, 197),
	array('Crete', 'Coast', 'Yes', 0, 835, 493, 394, 233),
	array('Cyprus', 'Coast', 'Yes', 0, 1045, 481, 492, 229),
	array('Iberian Sea', 'Sea', 'No', 0, 145, 440, 78, 210),
	array('Berber Sea', 'Sea', 'No', 0, 275, 395, 140, 175),
	array('Ligurian Sea', 'Sea', 'No', 0, 340, 255, 170, 120),
	array('Tyrrhenean Sea', 'Sea', 'No', 0, 490, 330, 240, 170),
	array('Punic Sea', 'Sea', 'No', 0, 420, 405, 220, 210),
	array('Gulf of Tacape', 'Sea', 'No', 0, 530, 550, 250, 275),
	array('Ausonian Sea', 'Sea', 'No', 0, 590, 475, 280, 215),
	array('Adriatic Sea', 'Sea', 'No', 0, 575, 249, 260, 110),
	array('Ionian Sea', 'Sea', 'No', 0, 650, 380, 307, 172),
	array('Messenian Sea', 'Sea', 'No', 0, 720, 475, 335, 217),
	array('Libyan Sea', 'Sea', 'No', 0, 750, 550, 330, 260),
	array('Gulf of Syrtis', 'Sea', 'No', 0, 660, 620, 315, 310),
	array('Aegean Sea', 'Sea', 'No', 0, 840, 430, 392, 193),
	array('Pontus Euxinus', 'Sea', 'No', 0, 1000, 190, 445, 90),
	array('Egyptian Sea', 'Sea', 'No', 0, 940, 550, 440, 255),
	array('Minoan Sea', 'Sea', 'No', 0, 920, 465, 425, 226),
	array('Cilician Strait', 'Sea', 'No', 0, 1085, 437, 510, 205),
	array('Syrian Sea', 'Sea', 'No', 0, 1080, 510, 510, 235),
	array('Gulf of Pelusium', 'Sea', 'No', 0, 1060, 560, 512, 268),
	array('Mare Erithraerum', 'Sea', 'No', 0, 1190, 745, 550, 340)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Lusitania','Tarraconensis','No','Yes'),
	array('Lusitania','Saguntum','No','Yes'),
	array('Lusitania','Gaul','No','Yes'),
	array('Tarraconensis','Saguntum','Yes','Yes'),
	array('Tarraconensis','Gaul','No','Yes'),
	array('Tarraconensis','Massilia','Yes','Yes'),
	array('Tarraconensis','Baleares','Yes','No'),
	array('Tarraconensis','Ligurian Sea','Yes','No'),
	array('Saguntum','Mauretania','Yes','Yes'),
	array('Saguntum','Baleares','Yes','No'),
	array('Saguntum','Iberian Sea','Yes','No'),
	array('Saguntum','Berber Sea','Yes','No'),
	array('Gaul','Massilia','No','Yes'),
	array('Gaul','Rhaetia','No','Yes'),
	array('Massilia','Rhaetia','No','Yes'),
	array('Massilia','Etruria','Yes','Yes'),
	array('Massilia','Ligurian Sea','Yes','No'),
	array('Rhaetia','Etruria','No','Yes'),
	array('Rhaetia','Venetia','No','Yes'),
	array('Rhaetia','Vindobona','No','Yes'),
	array('Rhaetia','Sarmatia','No','Yes'),
	array('Etruria','Venetia','No','Yes'),
	array('Etruria','Roma','Yes','Yes'),
	array('Etruria','Ravenna','No','Yes'),
	array('Etruria','Ligurian Sea','Yes','No'),
	array('Venetia','Ravenna','Yes','Yes'),
	array('Venetia','Vindobona','No','Yes'),
	array('Venetia','Dalmatia','Yes','Yes'),
	array('Venetia','Adriatic Sea','Yes','No'),
	array('Roma','Ravenna','No','Yes'),
	array('Roma','Neapolis','Yes','Yes'),
	array('Roma','Apulia','No','Yes'),
	array('Roma','Ligurian Sea','Yes','No'),
	array('Roma','Tyrrhenean Sea','Yes','No'),
	array('Ravenna','Apulia','Yes','Yes'),
	array('Ravenna','Adriatic Sea','Yes','No'),
	array('Neapolis','Apulia','Yes','Yes'),
	array('Neapolis','Sicilia','Yes','Yes'),
	array('Neapolis','Tyrrhenean Sea','Yes','No'),
	array('Neapolis','Ausonian Sea','Yes','No'),
	array('Neapolis','Ionian Sea','Yes','No'),
	array('Apulia','Adriatic Sea','Yes','No'),
	array('Apulia','Ionian Sea','Yes','No'),
	array('Vindobona','Dalmatia','No','Yes'),
	array('Vindobona','Illyria','No','Yes'),
	array('Vindobona','Sarmatia','No','Yes'),
	array('Dalmatia','Illyria','No','Yes'),
	array('Dalmatia','Epirus','Yes','Yes'),
	array('Dalmatia','Adriatic Sea','Yes','No'),
	array('Illyria','Sarmatia','No','Yes'),
	array('Illyria','Dacia','No','Yes'),
	array('Illyria','Epirus','No','Yes'),
	array('Illyria','Macedonia','No','Yes'),
	array('Sarmatia','Dacia','No','Yes'),
	array('Sarmatia','Chersonesus','No','Yes'),
	array('Dacia','Chersonesus','Yes','Yes'),
	array('Dacia','Macedonia','No','Yes'),
	array('Dacia','Byzantium','Yes','Yes'),
	array('Dacia','Pontus Euxinus','Yes','No'),
	array('Chersonesus','Sinope','Yes','Yes'),
	array('Chersonesus','Armenia','No','Yes'),
	array('Chersonesus','Pontus Euxinus','Yes','No'),
	array('Epirus','Macedonia','No','Yes'),
	array('Epirus','Athens','Yes','Yes'),
	array('Epirus','Adriatic Sea','Yes','No'),
	array('Epirus','Ionian Sea','Yes','No'),
	array('Macedonia','Athens','Yes','Yes'),
	array('Macedonia','Byzantium','Yes','Yes'),
	array('Macedonia','Aegean Sea','Yes','No'),
	array('Athens','Sparta','Yes','Yes'),
	array('Athens','Ionian Sea','Yes','No'),
	array('Athens','Aegean Sea','Yes','No'),
	array('Sparta','Ionian Sea','Yes','No'),
	array('Sparta','Messenian Sea','Yes','No'),
	array('Sparta','Aegean Sea','Yes','No'),
	array('Byzantium','Bithynia','Yes','Yes'),
	array('Byzantium','Miletus','Yes','Yes'),
	array('Byzantium','Galatia','No','Yes'),
	array('Byzantium','Aegean Sea','Yes','No'),
	array('Byzantium','Pontus Euxinus','Yes','No'),
	array('Bithynia','Sinope','Yes','Yes'),
	array('Bithynia','Galatia','No','Yes'),
	array('Bithynia','Pontus Euxinus','Yes','No'),
	array('Sinope','Galatia','No','Yes'),
	array('Sinope','Cappadocia','No','Yes'),
	array('Sinope','Armenia','No','Yes'),
	array('Sinope','Pontus Euxinus','Yes','No'),
	array('Miletus','Galatia','No','Yes'),
	array('Miletus','Isauria','Yes','Yes'),
	array('Miletus','Aegean Sea','Yes','No'),
	array('Miletus','Minoan Sea','Yes','No'),
	array('Miletus','Cilician Strait','Yes','No'),
	array('Galatia','Isauria','No','Yes'),
	array('Galatia','Cappadocia','No','Yes'),
	array('Isauria','Cappadocia','Yes','Yes'),
	array('Isauria','Cilician Strait','Yes','No'),
	array('Cappadocia','Armenia','No','Yes'),
	array('Cappadocia','Antioch','Yes','Yes'),
	array('Cappadocia','Damascus','No','Yes'),
	array('Cappadocia','Cilician Strait','Yes','No'),
	array('Armenia','Damascus','No','Yes'),
	array('Antioch','Damascus','No','Yes'),
	array('Antioch','Sidon','Yes','Yes'),
	array('Antioch','Cilician Strait','Yes','No'),
	array('Damascus','Sidon','No','Yes'),
	array('Damascus','Arabia','No','Yes'),
	array('Sidon','Tyre','Yes','Yes'),
	array('Sidon','Arabia','No','Yes'),
	array('Sidon','Cilician Strait','Yes','No'),
	array('Sidon','Syrian Sea','Yes','No'),
	array('Tyre','Arabia','No','Yes'),
	array('Tyre','Jerusalem','Yes','Yes'),
	array('Tyre','Syrian Sea','Yes','No'),
	array('Arabia','Jerusalem','No','Yes'),
	array('Arabia','Nabatea','No','Yes'),
	array('Jerusalem','Petra','No','Yes'),
	array('Jerusalem','Nabatea','No','Yes'),
	array('Jerusalem','Sinai','Yes','Yes'),
	array('Jerusalem','Syrian Sea','Yes','No'),
	array('Jerusalem','Gulf of Pelusium','Yes','No'),
	array('Petra','Nabatea','Yes','Yes'),
	array('Petra','Sinai','Yes','Yes'),
	array('Petra','Mare Erithraerum','Yes','No'),
	array('Nabatea','Mare Erithraerum','Yes','No'),
	array('Sinai','Thebes','Yes','Yes'),
	array('Sinai','Alexandria','Yes','Yes'),
	array('Sinai','Gulf of Pelusium','Yes','No'),
	array('Sinai','Mare Erithraerum','Yes','No'),
	array('Thebes','Bayuda','Yes','Yes'),
	array('Thebes','Memphis','Yes','Yes'),
	array('Thebes','Alexandria','Yes','Yes'),
	array('Thebes','Gulf of Pelusium','Yes','No'),
	array('Thebes','Mare Erithraerum','Yes','No'),
	array('Bayuda','Memphis','Yes','Yes'),
	array('Bayuda','Marmarica','No','Yes'),
	array('Bayuda','Phazania','No','Yes'),
	array('Bayuda','Sahara','No','Yes'),
	array('Memphis','Alexandria','Yes','Yes'),
	array('Memphis','Cyrene','No','Yes'),
	array('Memphis','Marmarica','No','Yes'),
	array('Alexandria','Cyrene','Yes','Yes'),
	array('Alexandria','Libyan Sea','Yes','No'),
	array('Alexandria','Egyptian Sea','Yes','No'),
	array('Alexandria','Gulf of Pelusium','Yes','No'),
	array('Cyrene','Marmarica','No','Yes'),
	array('Cyrene','Leptis','Yes','Yes'),
	array('Cyrene','Libyan Sea','Yes','No'),
	array('Cyrene','Gulf of Syrtis','Yes','No'),
	array('Marmarica','Leptis','No','Yes'),
	array('Marmarica','Phazania','No','Yes'),
	array('Leptis','Phazania','No','Yes'),
	array('Leptis','Numidia','Yes','Yes'),
	array('Leptis','Gulf of Tacape','Yes','No'),
	array('Leptis','Gulf of Syrtis','Yes','No'),
	array('Phazania','Sahara','No','Yes'),
	array('Phazania','Numidia','No','Yes'),
	array('Phazania','Cirta','No','Yes'),
	array('Sahara','Cirta','No','Yes'),
	array('Sahara','Mauretania','No','Yes'),
	array('Numidia','Thapsus','Yes','Yes'),
	array('Numidia','Cirta','No','Yes'),
	array('Numidia','Gulf of Tacape','Yes','No'),
	array('Thapsus','Carthage','Yes','Yes'),
	array('Thapsus','Cirta','No','Yes'),
	array('Thapsus','Punic Sea','Yes','No'),
	array('Thapsus','Gulf of Tacape','Yes','No'),
	array('Carthage','Cirta','No','Yes'),
	array('Carthage','Mauretania','Yes','Yes'),
	array('Carthage','Berber Sea','Yes','No'),
	array('Carthage','Punic Sea','Yes','No'),
	array('Cirta','Mauretania','No','Yes'),
	array('Mauretania','Iberian Sea','Yes','No'),
	array('Mauretania','Berber Sea','Yes','No'),
	array('Baleares','Berber Sea','Yes','No'),
	array('Baleares','Ligurian Sea','Yes','No'),
	array('Sardinia','Corsica','Yes','Yes'),
	array('Sardinia','Berber Sea','Yes','No'),
	array('Sardinia','Ligurian Sea','Yes','No'),
	array('Sardinia','Tyrrhenean Sea','Yes','No'),
	array('Sardinia','Punic Sea','Yes','No'),
	array('Corsica','Ligurian Sea','Yes','No'),
	array('Corsica','Tyrrhenean Sea','Yes','No'),
	array('Sicilia','Tyrrhenean Sea','Yes','No'),
	array('Sicilia','Punic Sea','Yes','No'),
	array('Sicilia','Ausonian Sea','Yes','No'),
	array('Crete','Messenian Sea','Yes','No'),
	array('Crete','Libyan Sea','Yes','No'),
	array('Crete','Aegean Sea','Yes','No'),
	array('Crete','Egyptian Sea','Yes','No'),
	array('Crete','Minoan Sea','Yes','No'),
	array('Cyprus','Egyptian Sea','Yes','No'),
	array('Cyprus','Cilician Strait','Yes','No'),
	array('Cyprus','Syrian Sea','Yes','No'),
	array('Iberian Sea','Berber Sea','Yes','No'),
	array('Berber Sea','Ligurian Sea','Yes','No'),
	array('Berber Sea','Punic Sea','Yes','No'),
	array('Ligurian Sea','Tyrrhenean Sea','Yes','No'),
	array('Tyrrhenean Sea','Punic Sea','Yes','No'),
	array('Tyrrhenean Sea','Ausonian Sea','Yes','No'),
	array('Punic Sea','Gulf of Tacape','Yes','No'),
	array('Punic Sea','Ausonian Sea','Yes','No'),
	array('Gulf of Tacape','Ausonian Sea','Yes','No'),
	array('Gulf of Tacape','Messenian Sea','Yes','No'),
	array('Gulf of Tacape','Libyan Sea','Yes','No'),
	array('Gulf of Tacape','Gulf of Syrtis','Yes','No'),
	array('Ausonian Sea','Ionian Sea','Yes','No'),
	array('Ausonian Sea','Messenian Sea','Yes','No'),
	array('Ausonian Sea','Libyan Sea','Yes','No'),
	array('Adriatic Sea','Ionian Sea','Yes','No'),
	array('Ionian Sea','Messenian Sea','Yes','No'),
	array('Messenian Sea','Libyan Sea','Yes','No'),
	array('Messenian Sea','Aegean Sea','Yes','No'),
	array('Libyan Sea','Gulf of Syrtis','Yes','No'),
	array('Libyan Sea','Egyptian Sea','Yes','No'),
	array('Aegean Sea','Minoan Sea','Yes','No'),
	array('Egyptian Sea','Minoan Sea','Yes','No'),
	array('Egyptian Sea','Cilician Strait','Yes','No'),
	array('Egyptian Sea','Syrian Sea','Yes','No'),
	array('Egyptian Sea','Gulf of Pelusium','Yes','No'),
	array('Minoan Sea','Cilician Strait','Yes','No'),
	array('Cilician Strait','Syrian Sea','Yes','No'),
	array('Syrian Sea','Gulf of Pelusium','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
