<?php
// This is file installs the map data for the AncMed variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Lusitania', 'Land', 'No', 40, 280, 20, 135, 'Neutral'),
	array('Tarraconensis', 'Coast', 'No', 165, 280, 80, 130, 'Neutral'),
	array('Saguntum', 'Coast', 'Yes', 75, 380, 65, 177, 'Neutral'),
	array('Gaul', 'Land', 'No', 250, 120, 120, 45, 'Neutral'),
	array('Massilia', 'Coast', 'Yes', 327, 182, 165, 93, 'Neutral'),
	array('Rhaetia', 'Land', 'No', 440, 80, 205, 45, 'Neutral'),
	array('Etruria', 'Coast', 'No', 405, 165, 190, 85, 'Neutral'),
	array('Venetia', 'Coast', 'No', 470, 130, 233, 65, 'Neutral'),
	array('Roma', 'Coast', 'Yes', 475, 248, 216, 110, 'Rome'),
	array('Ravenna', 'Coast', 'Yes', 481, 190, 239, 105, 'Rome'),
	array('Neapolis', 'Coast', 'Yes', 566, 322, 280, 172, 'Rome'),
	array('Apulia', 'Coast', 'No', 560, 271, 264, 132, 'Neutral'),
	array('Vindobona', 'Land', 'Yes', 530, 80, 259, 47, 'Neutral'),
	array('Dalmatia', 'Coast', 'Yes', 594, 200, 280, 95, 'Neutral'),
	array('Illyria', 'Land', 'No', 710, 227, 323, 98, 'Neutral'),
	array('Sarmatia', 'Land', 'No', 685, 65, 320, 25, 'Neutral'),
	array('Dacia', 'Coast', 'No', 800, 187, 385, 90, 'Neutral'),
	array('Chersonesus', 'Coast', 'Yes', 990, 58, 452, 42, 'Neutral'),
	array('Epirus', 'Coast', 'No', 695, 335, 330, 165, 'Neutral'),
	array('Macedonia', 'Coast', 'Yes', 760, 295, 370, 155, 'Greece'),
	array('Athens', 'Coast', 'Yes', 750, 373, 355, 174, 'Greece'),
	array('Sparta', 'Coast', 'Yes', 757, 423, 365, 202, 'Greece'),
	array('Byzantium', 'Coast', 'Yes', 905, 315, 415, 159, 'Neutral'),
	array('Bithynia', 'Coast', 'No', 990, 257, 457, 129, 'Neutral'),
	array('Sinope', 'Coast', 'Yes', 1095, 248, 527, 111, 'Neutral'),
	array('Miletus', 'Coast', 'Yes', 920, 390, 430, 192, 'Neutral'),
	array('Galatia', 'Land', 'No', 1010, 322, 470, 150, 'Neutral'),
	array('Isauria', 'Coast', 'No', 1025, 392, 485, 196, 'Neutral'),
	array('Cappadocia', 'Coast', 'No', 1100, 340, 520, 164, 'Neutral'),
	array('Armenia', 'Land', 'No', 1240, 270, 580, 135, 'Neutral'),
	array('Antioch', 'Coast', 'Yes', 1160, 400, 547, 185, 'Persia'),
	array('Damascus', 'Land', 'Yes', 1250, 390, 585, 195, 'Persia'),
	array('Sidon', 'Coast', 'Yes', 1162, 451, 555, 220, 'Persia'),
	array('Tyre', 'Coast', 'Yes', 1163, 503, 550, 235, 'Neutral'),
	array('Arabia', 'Land', 'No', 1230, 514, 585, 240, 'Neutral'),
	array('Jerusalem', 'Coast', 'Yes', 1145, 560, 540, 274, 'Neutral'),
	array('Petra', 'Coast', 'Yes', 1168, 632, 550, 311, 'Neutral'),
	array('Nabatea', 'Coast', 'No', 1240, 650, 585, 310, 'Neutral'),
	array('Sinai', 'Coast', 'No', 1105, 600, 520, 282, 'Neutral'),
	array('Thebes', 'Coast', 'Yes', 1107, 720, 525, 350, 'Egypt'),
	array('Bayuda', 'Coast', 'No', 860, 780, 420, 365, 'Neutral'),
	array('Memphis', 'Coast', 'Yes', 960, 715, 460, 328, 'Egypt'),
	array('Alexandria', 'Coast', 'Yes', 940, 630, 440, 295, 'Egypt'),
	array('Cyrene', 'Coast', 'Yes', 760, 630, 365, 293, 'Neutral'),
	array('Marmarica', 'Land', 'No', 730, 730, 355, 335, 'Neutral'),
	array('Leptis', 'Coast', 'Yes', 530, 638, 270, 310, 'Neutral'),
	array('Phazania', 'Land', 'No', 480, 680, 245, 330, 'Neutral'),
	array('Sahara', 'Land', 'No', 260, 650, 135, 298, 'Neutral'),
	array('Numidia', 'Coast', 'Yes', 428, 590, 205, 274, 'Neutral'),
	array('Thapsus', 'Coast', 'Yes', 400, 525, 187, 245, 'Carthage'),
	array('Carthage', 'Coast', 'Yes', 365, 460, 175, 215, 'Carthage'),
	array('Cirta', 'Land', 'Yes', 312, 532, 148, 255, 'Carthage'),
	array('Mauretania', 'Coast', 'No', 125, 525, 70, 245, 'Neutral'),
	array('Baleares', 'Coast', 'Yes', 252, 335, 111, 155, 'Neutral'),
	array('Sardinia', 'Coast', 'Yes', 398, 340, 188, 155, 'Neutral'),
	array('Corsica', 'Coast', 'No', 400, 270, 190, 125, 'Neutral'),
	array('Sicilia', 'Coast', 'Yes', 530, 422, 250, 197, 'Neutral'),
	array('Crete', 'Coast', 'Yes', 835, 493, 394, 233, 'Neutral'),
	array('Cyprus', 'Coast', 'Yes', 1045, 481, 492, 229, 'Neutral'),
	array('Iberian Sea', 'Sea', 'No', 145, 440, 78, 210, 'Neutral'),
	array('Berber Sea', 'Sea', 'No', 275, 395, 140, 175, 'Neutral'),
	array('Ligurian Sea', 'Sea', 'No', 340, 255, 170, 120, 'Neutral'),
	array('Tyrrhenean Sea', 'Sea', 'No', 490, 330, 240, 170, 'Neutral'),
	array('Punic Sea', 'Sea', 'No', 420, 405, 220, 210, 'Neutral'),
	array('Gulf of Tacape', 'Sea', 'No', 530, 550, 250, 275, 'Neutral'),
	array('Ausonian Sea', 'Sea', 'No', 590, 475, 280, 215, 'Neutral'),
	array('Adriatic Sea', 'Sea', 'No', 575, 249, 260, 110, 'Neutral'),
	array('Ionian Sea', 'Sea', 'No', 650, 380, 307, 172, 'Neutral'),
	array('Messenian Sea', 'Sea', 'No', 720, 475, 335, 217, 'Neutral'),
	array('Libyan Sea', 'Sea', 'No', 750, 550, 330, 260, 'Neutral'),
	array('Gulf of Syrtis', 'Sea', 'No', 660, 620, 315, 310, 'Neutral'),
	array('Aegean Sea', 'Sea', 'No', 840, 430, 392, 193, 'Neutral'),
	array('Black Sea', 'Sea', 'No', 1000, 190, 445, 90, 'Neutral'),
	array('Egyptian Sea', 'Sea', 'No', 940, 550, 440, 255, 'Neutral'),
	array('Minoan Sea', 'Sea', 'No', 920, 465, 425, 226, 'Neutral'),
	array('Cilician Strait', 'Sea', 'No', 1085, 437, 510, 205, 'Neutral'),
	array('Syrian Sea', 'Sea', 'No', 1080, 510, 510, 235, 'Neutral'),
	array('Gulf of Pelusium', 'Sea', 'No', 1060, 560, 512, 268, 'Neutral'),
	array('Red Sea', 'Sea', 'No', 1190, 745, 550, 340, 'Neutral')
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $x, $y, $sx, $sy, $country)=$territoryRawRow;
	if( $country=='Neutral' )
		$countryID=0;
	else
		$countryID=$this->countryID($country);
		
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);
$bordersRawData=array(
	array('Lusitania','Tarraconensis','No','Yes'),
	array('Lusitania','Saguntum','No','Yes'),
	array('Lusitania','Gaul','No','Yes'),
	array('Tarraconensis','Lusitania','No','Yes'),
	array('Tarraconensis','Saguntum','Yes','Yes'),
	array('Tarraconensis','Gaul','No','Yes'),
	array('Tarraconensis','Massilia','Yes','Yes'),
	array('Tarraconensis','Baleares','Yes','No'),
	array('Tarraconensis','Ligurian Sea','Yes','No'),
	array('Saguntum','Lusitania','No','Yes'),
	array('Saguntum','Tarraconensis','Yes','Yes'),
	array('Saguntum','Mauretania','Yes','Yes'),
	array('Saguntum','Baleares','Yes','No'),
	array('Saguntum','Iberian Sea','Yes','No'),
	array('Saguntum','Berber Sea','Yes','No'),
	array('Gaul','Lusitania','No','Yes'),
	array('Gaul','Tarraconensis','No','Yes'),
	array('Gaul','Massilia','No','Yes'),
	array('Gaul','Rhaetia','No','Yes'),
	array('Massilia','Tarraconensis','Yes','Yes'),
	array('Massilia','Gaul','No','Yes'),
	array('Massilia','Rhaetia','No','Yes'),
	array('Massilia','Etruria','Yes','Yes'),
	array('Massilia','Ligurian Sea','Yes','No'),
	array('Rhaetia','Gaul','No','Yes'),
	array('Rhaetia','Massilia','No','Yes'),
	array('Rhaetia','Etruria','No','Yes'),
	array('Rhaetia','Venetia','No','Yes'),
	array('Rhaetia','Vindobona','No','Yes'),
	array('Rhaetia','Sarmatia','No','Yes'),
	array('Etruria','Massilia','Yes','Yes'),
	array('Etruria','Rhaetia','No','Yes'),
	array('Etruria','Venetia','No','Yes'),
	array('Etruria','Roma','Yes','Yes'),
	array('Etruria','Ravenna','No','Yes'),
	array('Etruria','Ligurian Sea','Yes','No'),
	array('Venetia','Rhaetia','No','Yes'),
	array('Venetia','Etruria','No','Yes'),
	array('Venetia','Ravenna','Yes','Yes'),
	array('Venetia','Vindobona','No','Yes'),
	array('Venetia','Dalmatia','Yes','Yes'),
	array('Venetia','Adriatic Sea','Yes','No'),
	array('Roma','Etruria','Yes','Yes'),
	array('Roma','Ravenna','No','Yes'),
	array('Roma','Neapolis','Yes','Yes'),
	array('Roma','Apulia','No','Yes'),
	array('Roma','Ligurian Sea','Yes','No'),
	array('Roma','Tyrrhenean Sea','Yes','No'),
	array('Ravenna','Etruria','No','Yes'),
	array('Ravenna','Venetia','Yes','Yes'),
	array('Ravenna','Roma','No','Yes'),
	array('Ravenna','Apulia','Yes','Yes'),
	array('Ravenna','Adriatic Sea','Yes','No'),
	array('Neapolis','Roma','Yes','Yes'),
	array('Neapolis','Apulia','Yes','Yes'),
	array('Neapolis','Sicilia','Yes','Yes'),
	array('Neapolis','Tyrrhenean Sea','Yes','No'),
	array('Neapolis','Ausonian Sea','Yes','No'),
	array('Neapolis','Ionian Sea','Yes','No'),
	array('Apulia','Roma','No','Yes'),
	array('Apulia','Ravenna','Yes','Yes'),
	array('Apulia','Neapolis','Yes','Yes'),
	array('Apulia','Adriatic Sea','Yes','No'),
	array('Apulia','Ionian Sea','Yes','No'),
	array('Vindobona','Rhaetia','No','Yes'),
	array('Vindobona','Venetia','No','Yes'),
	array('Vindobona','Dalmatia','No','Yes'),
	array('Vindobona','Illyria','No','Yes'),
	array('Vindobona','Sarmatia','No','Yes'),
	array('Dalmatia','Venetia','Yes','Yes'),
	array('Dalmatia','Vindobona','No','Yes'),
	array('Dalmatia','Illyria','No','Yes'),
	array('Dalmatia','Epirus','Yes','Yes'),
	array('Dalmatia','Adriatic Sea','Yes','No'),
	array('Illyria','Vindobona','No','Yes'),
	array('Illyria','Dalmatia','No','Yes'),
	array('Illyria','Sarmatia','No','Yes'),
	array('Illyria','Dacia','No','Yes'),
	array('Illyria','Epirus','No','Yes'),
	array('Illyria','Macedonia','No','Yes'),
	array('Sarmatia','Rhaetia','No','Yes'),
	array('Sarmatia','Vindobona','No','Yes'),
	array('Sarmatia','Illyria','No','Yes'),
	array('Sarmatia','Dacia','No','Yes'),
	array('Sarmatia','Chersonesus','No','Yes'),
	array('Dacia','Illyria','No','Yes'),
	array('Dacia','Sarmatia','No','Yes'),
	array('Dacia','Chersonesus','Yes','Yes'),
	array('Dacia','Macedonia','No','Yes'),
	array('Dacia','Byzantium','Yes','Yes'),
	array('Dacia','Black Sea','Yes','No'),
	array('Chersonesus','Sarmatia','No','Yes'),
	array('Chersonesus','Dacia','Yes','Yes'),
	array('Chersonesus','Sinope','Yes','Yes'),
	array('Chersonesus','Armenia','No','Yes'),
	array('Chersonesus','Black Sea','Yes','No'),
	array('Epirus','Dalmatia','Yes','Yes'),
	array('Epirus','Illyria','No','Yes'),
	array('Epirus','Macedonia','No','Yes'),
	array('Epirus','Athens','Yes','Yes'),
	array('Epirus','Adriatic Sea','Yes','No'),
	array('Epirus','Ionian Sea','Yes','No'),
	array('Macedonia','Illyria','No','Yes'),
	array('Macedonia','Dacia','No','Yes'),
	array('Macedonia','Epirus','No','Yes'),
	array('Macedonia','Athens','Yes','Yes'),
	array('Macedonia','Byzantium','Yes','Yes'),
	array('Macedonia','Aegean Sea','Yes','No'),
	array('Athens','Epirus','Yes','Yes'),
	array('Athens','Macedonia','Yes','Yes'),
	array('Athens','Sparta','Yes','Yes'),
	array('Athens','Ionian Sea','Yes','No'),
	array('Athens','Aegean Sea','Yes','No'),
	array('Sparta','Athens','Yes','Yes'),
	array('Sparta','Ionian Sea','Yes','No'),
	array('Sparta','Messenian Sea','Yes','No'),
	array('Sparta','Aegean Sea','Yes','No'),
	array('Byzantium','Dacia','Yes','Yes'),
	array('Byzantium','Macedonia','Yes','Yes'),
	array('Byzantium','Bithynia','Yes','Yes'),
	array('Byzantium','Miletus','Yes','Yes'),
	array('Byzantium','Galatia','No','Yes'),
	array('Byzantium','Aegean Sea','Yes','No'),
	array('Byzantium','Black Sea','Yes','No'),
	array('Bithynia','Byzantium','Yes','Yes'),
	array('Bithynia','Sinope','Yes','Yes'),
	array('Bithynia','Galatia','No','Yes'),
	array('Bithynia','Black Sea','Yes','No'),
	array('Sinope','Chersonesus','Yes','Yes'),
	array('Sinope','Bithynia','Yes','Yes'),
	array('Sinope','Galatia','No','Yes'),
	array('Sinope','Cappadocia','No','Yes'),
	array('Sinope','Armenia','No','Yes'),
	array('Sinope','Black Sea','Yes','No'),
	array('Miletus','Byzantium','Yes','Yes'),
	array('Miletus','Galatia','No','Yes'),
	array('Miletus','Isauria','Yes','Yes'),
	array('Miletus','Aegean Sea','Yes','No'),
	array('Miletus','Minoan Sea','Yes','No'),
	array('Miletus','Cilician Strait','Yes','No'),
	array('Galatia','Byzantium','No','Yes'),
	array('Galatia','Bithynia','No','Yes'),
	array('Galatia','Sinope','No','Yes'),
	array('Galatia','Miletus','No','Yes'),
	array('Galatia','Isauria','No','Yes'),
	array('Galatia','Cappadocia','No','Yes'),
	array('Isauria','Miletus','Yes','Yes'),
	array('Isauria','Galatia','No','Yes'),
	array('Isauria','Cappadocia','Yes','Yes'),
	array('Isauria','Cilician Strait','Yes','No'),
	array('Cappadocia','Sinope','No','Yes'),
	array('Cappadocia','Galatia','No','Yes'),
	array('Cappadocia','Isauria','Yes','Yes'),
	array('Cappadocia','Armenia','No','Yes'),
	array('Cappadocia','Antioch','Yes','Yes'),
	array('Cappadocia','Damascus','No','Yes'),
	array('Cappadocia','Cilician Strait','Yes','No'),
	array('Armenia','Chersonesus','No','Yes'),
	array('Armenia','Sinope','No','Yes'),
	array('Armenia','Cappadocia','No','Yes'),
	array('Armenia','Damascus','No','Yes'),
	array('Antioch','Cappadocia','Yes','Yes'),
	array('Antioch','Damascus','No','Yes'),
	array('Antioch','Sidon','Yes','Yes'),
	array('Antioch','Cilician Strait','Yes','No'),
	array('Damascus','Cappadocia','No','Yes'),
	array('Damascus','Armenia','No','Yes'),
	array('Damascus','Antioch','No','Yes'),
	array('Damascus','Sidon','No','Yes'),
	array('Damascus','Arabia','No','Yes'),
	array('Sidon','Antioch','Yes','Yes'),
	array('Sidon','Damascus','No','Yes'),
	array('Sidon','Tyre','Yes','Yes'),
	array('Sidon','Arabia','No','Yes'),
	array('Sidon','Cilician Strait','Yes','No'),
	array('Sidon','Syrian Sea','Yes','No'),
	array('Tyre','Sidon','Yes','Yes'),
	array('Tyre','Arabia','No','Yes'),
	array('Tyre','Jerusalem','Yes','Yes'),
	array('Tyre','Syrian Sea','Yes','No'),
	array('Arabia','Damascus','No','Yes'),
	array('Arabia','Sidon','No','Yes'),
	array('Arabia','Tyre','No','Yes'),
	array('Arabia','Jerusalem','No','Yes'),
	array('Arabia','Nabatea','No','Yes'),
	array('Jerusalem','Tyre','Yes','Yes'),
	array('Jerusalem','Arabia','No','Yes'),
	array('Jerusalem','Petra','No','Yes'),
	array('Jerusalem','Nabatea','No','Yes'),
	array('Jerusalem','Sinai','Yes','Yes'),
	array('Jerusalem','Syrian Sea','Yes','No'),
	array('Jerusalem','Gulf of Pelusium','Yes','No'),
	array('Petra','Jerusalem','No','Yes'),
	array('Petra','Nabatea','Yes','Yes'),
	array('Petra','Sinai','Yes','Yes'),
	array('Petra','Red Sea','Yes','No'),
	array('Nabatea','Arabia','No','Yes'),
	array('Nabatea','Jerusalem','No','Yes'),
	array('Nabatea','Petra','Yes','Yes'),
	array('Nabatea','Red Sea','Yes','No'),
	array('Sinai','Jerusalem','Yes','Yes'),
	array('Sinai','Petra','Yes','Yes'),
	array('Sinai','Thebes','Yes','Yes'),
	array('Sinai','Alexandria','Yes','Yes'),
	array('Sinai','Gulf of Pelusium','Yes','No'),
	array('Sinai','Red Sea','Yes','No'),
	array('Thebes','Sinai','Yes','Yes'),
	array('Thebes','Bayuda','Yes','Yes'),
	array('Thebes','Memphis','Yes','Yes'),
	array('Thebes','Alexandria','Yes','Yes'),
	array('Thebes','Gulf of Pelusium','Yes','No'),
	array('Thebes','Red Sea','Yes','No'),
	array('Bayuda','Thebes','Yes','Yes'),
	array('Bayuda','Memphis','Yes','Yes'),
	array('Bayuda','Marmarica','No','Yes'),
	array('Bayuda','Phazania','No','Yes'),
	array('Bayuda','Sahara','No','Yes'),
	array('Memphis','Thebes','Yes','Yes'),
	array('Memphis','Bayuda','Yes','Yes'),
	array('Memphis','Alexandria','Yes','Yes'),
	array('Memphis','Cyrene','No','Yes'),
	array('Memphis','Marmarica','No','Yes'),
	array('Alexandria','Sinai','Yes','Yes'),
	array('Alexandria','Thebes','Yes','Yes'),
	array('Alexandria','Memphis','Yes','Yes'),
	array('Alexandria','Cyrene','Yes','Yes'),
	array('Alexandria','Libyan Sea','Yes','No'),
	array('Alexandria','Egyptian Sea','Yes','No'),
	array('Alexandria','Gulf of Pelusium','Yes','No'),
	array('Cyrene','Memphis','No','Yes'),
	array('Cyrene','Alexandria','Yes','Yes'),
	array('Cyrene','Marmarica','No','Yes'),
	array('Cyrene','Leptis','Yes','Yes'),
	array('Cyrene','Libyan Sea','Yes','No'),
	array('Cyrene','Gulf of Syrtis','Yes','No'),
	array('Marmarica','Bayuda','No','Yes'),
	array('Marmarica','Memphis','No','Yes'),
	array('Marmarica','Cyrene','No','Yes'),
	array('Marmarica','Leptis','No','Yes'),
	array('Marmarica','Phazania','No','Yes'),
	array('Leptis','Cyrene','Yes','Yes'),
	array('Leptis','Marmarica','No','Yes'),
	array('Leptis','Phazania','No','Yes'),
	array('Leptis','Numidia','Yes','Yes'),
	array('Leptis','Gulf of Tacape','Yes','No'),
	array('Leptis','Gulf of Syrtis','Yes','No'),
	array('Phazania','Bayuda','No','Yes'),
	array('Phazania','Marmarica','No','Yes'),
	array('Phazania','Leptis','No','Yes'),
	array('Phazania','Sahara','No','Yes'),
	array('Phazania','Numidia','No','Yes'),
	array('Phazania','Cirta','No','Yes'),
	array('Sahara','Bayuda','No','Yes'),
	array('Sahara','Phazania','No','Yes'),
	array('Sahara','Cirta','No','Yes'),
	array('Sahara','Mauretania','No','Yes'),
	array('Numidia','Leptis','Yes','Yes'),
	array('Numidia','Phazania','No','Yes'),
	array('Numidia','Thapsus','Yes','Yes'),
	array('Numidia','Cirta','No','Yes'),
	array('Numidia','Gulf of Tacape','Yes','No'),
	array('Thapsus','Numidia','Yes','Yes'),
	array('Thapsus','Carthage','Yes','Yes'),
	array('Thapsus','Cirta','No','Yes'),
	array('Thapsus','Punic Sea','Yes','No'),
	array('Thapsus','Gulf of Tacape','Yes','No'),
	array('Carthage','Thapsus','Yes','Yes'),
	array('Carthage','Cirta','No','Yes'),
	array('Carthage','Mauretania','Yes','Yes'),
	array('Carthage','Berber Sea','Yes','No'),
	array('Carthage','Punic Sea','Yes','No'),
	array('Cirta','Phazania','No','Yes'),
	array('Cirta','Sahara','No','Yes'),
	array('Cirta','Numidia','No','Yes'),
	array('Cirta','Thapsus','No','Yes'),
	array('Cirta','Carthage','No','Yes'),
	array('Cirta','Mauretania','No','Yes'),
	array('Mauretania','Saguntum','Yes','Yes'),
	array('Mauretania','Sahara','No','Yes'),
	array('Mauretania','Carthage','Yes','Yes'),
	array('Mauretania','Cirta','No','Yes'),
	array('Mauretania','Iberian Sea','Yes','No'),
	array('Mauretania','Berber Sea','Yes','No'),
	array('Baleares','Tarraconensis','Yes','No'),
	array('Baleares','Saguntum','Yes','No'),
	array('Baleares','Berber Sea','Yes','No'),
	array('Baleares','Ligurian Sea','Yes','No'),
	array('Sardinia','Corsica','Yes','Yes'),
	array('Sardinia','Berber Sea','Yes','No'),
	array('Sardinia','Ligurian Sea','Yes','No'),
	array('Sardinia','Tyrrhenean Sea','Yes','No'),
	array('Sardinia','Punic Sea','Yes','No'),
	array('Corsica','Sardinia','Yes','Yes'),
	array('Corsica','Ligurian Sea','Yes','No'),
	array('Corsica','Tyrrhenean Sea','Yes','No'),
	array('Sicilia','Neapolis','Yes','Yes'),
	array('Sicilia','Tyrrhenean Sea','Yes','No'),
	array('Sicilia','Punic Sea','Yes','No'),
	array('Sicilia','Ausonian Sea','Yes','No'),
	array('Crete','Messenian Sea','Yes','No'),
	array('Crete','Libyan Sea','Yes','No'),
	array('Crete','Aegean Sea','Yes','No'),
	array('Crete','Egyptian Sea','Yes','No'),
	array('Crete','Minoan Sea','Yes','No'),
	array('Cyprus','Egyptian Sea','Yes','No'),
	array('Cyprus','Cilician Strait','Yes','No'),
	array('Cyprus','Syrian Sea','Yes','No'),
	array('Iberian Sea','Saguntum','Yes','No'),
	array('Iberian Sea','Mauretania','Yes','No'),
	array('Iberian Sea','Berber Sea','Yes','No'),
	array('Berber Sea','Saguntum','Yes','No'),
	array('Berber Sea','Carthage','Yes','No'),
	array('Berber Sea','Mauretania','Yes','No'),
	array('Berber Sea','Baleares','Yes','No'),
	array('Berber Sea','Sardinia','Yes','No'),
	array('Berber Sea','Iberian Sea','Yes','No'),
	array('Berber Sea','Ligurian Sea','Yes','No'),
	array('Berber Sea','Punic Sea','Yes','No'),
	array('Ligurian Sea','Tarraconensis','Yes','No'),
	array('Ligurian Sea','Massilia','Yes','No'),
	array('Ligurian Sea','Etruria','Yes','No'),
	array('Ligurian Sea','Roma','Yes','No'),
	array('Ligurian Sea','Baleares','Yes','No'),
	array('Ligurian Sea','Sardinia','Yes','No'),
	array('Ligurian Sea','Corsica','Yes','No'),
	array('Ligurian Sea','Berber Sea','Yes','No'),
	array('Ligurian Sea','Tyrrhenean Sea','Yes','No'),
	array('Tyrrhenean Sea','Roma','Yes','No'),
	array('Tyrrhenean Sea','Neapolis','Yes','No'),
	array('Tyrrhenean Sea','Sardinia','Yes','No'),
	array('Tyrrhenean Sea','Corsica','Yes','No'),
	array('Tyrrhenean Sea','Sicilia','Yes','No'),
	array('Tyrrhenean Sea','Ligurian Sea','Yes','No'),
	array('Tyrrhenean Sea','Punic Sea','Yes','No'),
	array('Tyrrhenean Sea','Ausonian Sea','Yes','No'),
	array('Punic Sea','Thapsus','Yes','No'),
	array('Punic Sea','Carthage','Yes','No'),
	array('Punic Sea','Sardinia','Yes','No'),
	array('Punic Sea','Sicilia','Yes','No'),
	array('Punic Sea','Berber Sea','Yes','No'),
	array('Punic Sea','Tyrrhenean Sea','Yes','No'),
	array('Punic Sea','Gulf of Tacape','Yes','No'),
	array('Punic Sea','Ausonian Sea','Yes','No'),
	array('Gulf of Tacape','Leptis','Yes','No'),
	array('Gulf of Tacape','Numidia','Yes','No'),
	array('Gulf of Tacape','Thapsus','Yes','No'),
	array('Gulf of Tacape','Punic Sea','Yes','No'),
	array('Gulf of Tacape','Ausonian Sea','Yes','No'),
	array('Gulf of Tacape','Messenian Sea','Yes','No'),
	array('Gulf of Tacape','Libyan Sea','Yes','No'),
	array('Gulf of Tacape','Gulf of Syrtis','Yes','No'),
	array('Ausonian Sea','Neapolis','Yes','No'),
	array('Ausonian Sea','Sicilia','Yes','No'),
	array('Ausonian Sea','Tyrrhenean Sea','Yes','No'),
	array('Ausonian Sea','Punic Sea','Yes','No'),
	array('Ausonian Sea','Gulf of Tacape','Yes','No'),
	array('Ausonian Sea','Ionian Sea','Yes','No'),
	array('Ausonian Sea','Messenian Sea','Yes','No'),
	array('Ausonian Sea','Libyan Sea','Yes','No'),
	array('Adriatic Sea','Venetia','Yes','No'),
	array('Adriatic Sea','Ravenna','Yes','No'),
	array('Adriatic Sea','Apulia','Yes','No'),
	array('Adriatic Sea','Dalmatia','Yes','No'),
	array('Adriatic Sea','Epirus','Yes','No'),
	array('Adriatic Sea','Ionian Sea','Yes','No'),
	array('Ionian Sea','Neapolis','Yes','No'),
	array('Ionian Sea','Apulia','Yes','No'),
	array('Ionian Sea','Epirus','Yes','No'),
	array('Ionian Sea','Athens','Yes','No'),
	array('Ionian Sea','Sparta','Yes','No'),
	array('Ionian Sea','Ausonian Sea','Yes','No'),
	array('Ionian Sea','Adriatic Sea','Yes','No'),
	array('Ionian Sea','Messenian Sea','Yes','No'),
	array('Messenian Sea','Sparta','Yes','No'),
	array('Messenian Sea','Crete','Yes','No'),
	array('Messenian Sea','Gulf of Tacape','Yes','No'),
	array('Messenian Sea','Ausonian Sea','Yes','No'),
	array('Messenian Sea','Ionian Sea','Yes','No'),
	array('Messenian Sea','Libyan Sea','Yes','No'),
	array('Messenian Sea','Aegean Sea','Yes','No'),
	array('Libyan Sea','Alexandria','Yes','No'),
	array('Libyan Sea','Cyrene','Yes','No'),
	array('Libyan Sea','Crete','Yes','No'),
	array('Libyan Sea','Gulf of Tacape','Yes','No'),
	array('Libyan Sea','Ausonian Sea','Yes','No'),
	array('Libyan Sea','Messenian Sea','Yes','No'),
	array('Libyan Sea','Gulf of Syrtis','Yes','No'),
	array('Libyan Sea','Egyptian Sea','Yes','No'),
	array('Gulf of Syrtis','Cyrene','Yes','No'),
	array('Gulf of Syrtis','Leptis','Yes','No'),
	array('Gulf of Syrtis','Gulf of Tacape','Yes','No'),
	array('Gulf of Syrtis','Libyan Sea','Yes','No'),
	array('Aegean Sea','Macedonia','Yes','No'),
	array('Aegean Sea','Athens','Yes','No'),
	array('Aegean Sea','Sparta','Yes','No'),
	array('Aegean Sea','Byzantium','Yes','No'),
	array('Aegean Sea','Miletus','Yes','No'),
	array('Aegean Sea','Crete','Yes','No'),
	array('Aegean Sea','Messenian Sea','Yes','No'),
	array('Aegean Sea','Minoan Sea','Yes','No'),
	array('Black Sea','Dacia','Yes','No'),
	array('Black Sea','Chersonesus','Yes','No'),
	array('Black Sea','Byzantium','Yes','No'),
	array('Black Sea','Bithynia','Yes','No'),
	array('Black Sea','Sinope','Yes','No'),
	array('Egyptian Sea','Alexandria','Yes','No'),
	array('Egyptian Sea','Crete','Yes','No'),
	array('Egyptian Sea','Cyprus','Yes','No'),
	array('Egyptian Sea','Libyan Sea','Yes','No'),
	array('Egyptian Sea','Minoan Sea','Yes','No'),
	array('Egyptian Sea','Cilician Strait','Yes','No'),
	array('Egyptian Sea','Syrian Sea','Yes','No'),
	array('Egyptian Sea','Gulf of Pelusium','Yes','No'),
	array('Minoan Sea','Miletus','Yes','No'),
	array('Minoan Sea','Crete','Yes','No'),
	array('Minoan Sea','Aegean Sea','Yes','No'),
	array('Minoan Sea','Egyptian Sea','Yes','No'),
	array('Minoan Sea','Cilician Strait','Yes','No'),
	array('Cilician Strait','Miletus','Yes','No'),
	array('Cilician Strait','Isauria','Yes','No'),
	array('Cilician Strait','Cappadocia','Yes','No'),
	array('Cilician Strait','Antioch','Yes','No'),
	array('Cilician Strait','Sidon','Yes','No'),
	array('Cilician Strait','Cyprus','Yes','No'),
	array('Cilician Strait','Egyptian Sea','Yes','No'),
	array('Cilician Strait','Minoan Sea','Yes','No'),
	array('Cilician Strait','Syrian Sea','Yes','No'),
	array('Syrian Sea','Sidon','Yes','No'),
	array('Syrian Sea','Tyre','Yes','No'),
	array('Syrian Sea','Jerusalem','Yes','No'),
	array('Syrian Sea','Cyprus','Yes','No'),
	array('Syrian Sea','Egyptian Sea','Yes','No'),
	array('Syrian Sea','Cilician Strait','Yes','No'),
	array('Syrian Sea','Gulf of Pelusium','Yes','No'),
	array('Gulf of Pelusium','Jerusalem','Yes','No'),
	array('Gulf of Pelusium','Sinai','Yes','No'),
	array('Gulf of Pelusium','Thebes','Yes','No'),
	array('Gulf of Pelusium','Alexandria','Yes','No'),
	array('Gulf of Pelusium','Egyptian Sea','Yes','No'),
	array('Gulf of Pelusium','Syrian Sea','Yes','No'),
	array('Red Sea','Petra','Yes','No'),
	array('Red Sea','Nabatea','Yes','No'),
	array('Red Sea','Sinai','Yes','No'),
	array('Red Sea','Thebes','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
