<?php
/*
	Copyright (C) 2010 Oliver Auth

	This file is part of the Ancient Mediterranean variant for webDiplomacy

	The Ancient Mediterranean variant for webDiplomacy is free software: 
	you can redistribute it and/or modify it under the terms of the GNU Affero
	General Public License as published by the Free Software Foundation, either 
	version 3 of the License, or (at your option) any later version.

	The Ancient Mediterranean variant for webDiplomacy is distributed in the hope
	that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
	warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
	See the GNU General Public License for more details.

	You should have received a copy of the GNU Affero General Public License
	along with webDiplomacy. If not, see <http://www.gnu.org/licenses/>.

*/

require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Lusitania'       , 'Land'  , 'No'  ,  40,280, 20,135, 'Neutral'  , 'No' ),
	array('Tarraconensis'   , 'Coast' , 'No'  , 165,280, 80,130, 'Neutral'  , 'No' ),
	array('Saguntum'        , 'Coast' , 'Yes' ,  75,380, 65,177, 'Neutral'  , 'No' ),
	array('Gaul'            , 'Land'  , 'No'  , 250,120,120, 45, 'Neutral'  , 'No' ),
	array('Massilia'        , 'Coast' , 'Yes' , 327,182,165, 93, 'Neutral'  , 'No' ),
	array('Rhaetia'         , 'Land'  , 'No'  , 440, 80,205, 45, 'Neutral'  , 'No' ),
	array('Etruria'         , 'Coast' , 'No'  , 405,165,190, 85, 'Neutral'  , 'No' ),
	array('Venetia'         , 'Coast' , 'No'  , 470,130,233, 65, 'Neutral'  , 'No' ),
	array('Roma'            , 'Coast' , 'Yes' , 475,248,216,110, 'Rome'     , 'No' ),
	array('Ravenna'         , 'Coast' , 'Yes' , 481,190,239,105, 'Rome'     , 'No' ),
	array('Neapolis'        , 'Coast' , 'Yes' , 566,322,280,172, 'Rome'     , 'No' ),
	array('Apulia'          , 'Coast' , 'No'  , 560,271,264,132, 'Neutral'  , 'No' ),
	array('Vindobona'       , 'Land'  , 'Yes' , 530, 80,258, 47, 'Neutral'  , 'No' ),
	array('Dalmatia'        , 'Coast' , 'Yes' , 594,200,280, 95, 'Neutral'  , 'No' ),
	array('Illyria'         , 'Land'  , 'No'  , 710,227,323, 98, 'Neutral'  , 'No' ),
	array('Sarmatia'        , 'Land'  , 'No'  , 685, 65,320, 25, 'Neutral'  , 'No' ),
	array('Dacia'           , 'Coast' , 'No'  , 800,187,385, 90, 'Neutral'  , 'No' ),
	array('Chersonesus'     , 'Coast' , 'Yes' , 990, 58,452, 42, 'Neutral'  , 'No' ),
	array('Epirus'          , 'Coast' , 'No'  , 695,335,330,165, 'Neutral'  , 'No' ),
	array('Macedonia'       , 'Coast' , 'Yes' , 760,295,370,155, 'Greece'   , 'No' ),
	array('Athens'          , 'Coast' , 'Yes' , 750,373,355,174, 'Greece'   , 'No' ),
	array('Sparta'          , 'Coast' , 'Yes' , 757,423,365,202, 'Greece'   , 'No' ),
	array('Byzantium'       , 'Coast' , 'Yes' , 905,315,415,159, 'Neutral'  , 'No' ),
	array('Bithynia'        , 'Coast' , 'No'  , 990,257,457,129, 'Neutral'  , 'No' ),
	array('Sinope'          , 'Coast' , 'Yes' ,1095,248,527,111, 'Neutral'  , 'No' ),
	array('Miletus'         , 'Coast' , 'Yes' , 920,390,430,192, 'Neutral'  , 'No' ),
	array('Galatia'         , 'Land'  , 'No'  ,1010,322,470,150, 'Neutral'  , 'No' ),
	array('Isauria'         , 'Coast' , 'No'  ,1025,392,485,196, 'Neutral'  , 'No' ),
	array('Cappadocia'      , 'Coast' , 'No'  ,1100,340,520,164, 'Neutral'  , 'No' ),
	array('Armenia'         , 'Land'  , 'No'  ,1240,270,580,135, 'Neutral'  , 'No' ),
	array('Antioch'         , 'Coast' , 'Yes' ,1160,400,547,185, 'Persia'   , 'No' ),
	array('Damascus'        , 'Land'  , 'Yes' ,1250,390,585,195, 'Persia'   , 'No' ),
	array('Sidon'           , 'Coast' , 'Yes' ,1162,451,555,220, 'Persia'   , 'No' ),
	array('Tyre'            , 'Coast' , 'Yes' ,1163,503,550,235, 'Neutral'  , 'No' ),
	array('Arabia'          , 'Land'  , 'No'  ,1230,514,585,240, 'Neutral'  , 'No' ),
	array('Jerusalem'       , 'Coast' , 'Yes' ,1145,560,540,274, 'Neutral'  , 'No' ),
	array('Petra'           , 'Coast' , 'Yes' ,1168,632,550,311, 'Neutral'  , 'No' ),
	array('Nabatea'         , 'Coast' , 'No'  ,1240,650,585,310, 'Neutral'  , 'No' ),
	array('Sinai'           , 'Coast' , 'No'  ,1105,600,520,282, 'Neutral'  , 'No' ),
	array('Thebes'          , 'Coast' , 'Yes' ,1107,720,525,350, 'Egypt'    , 'No' ),
	array('Bayuda'          , 'Coast' , 'No'  , 860,780,420,365, 'Neutral'  , 'No' ),
	array('Memphis'         , 'Coast' , 'Yes' , 960,715,460,328, 'Egypt'    , 'No' ),
	array('Alexandria'      , 'Coast' , 'Yes' , 940,630,440,295, 'Egypt'    , 'No' ),
	array('Cyrene'          , 'Coast' , 'Yes' , 760,630,365,293, 'Neutral'  , 'No' ),
	array('Marmarica'       , 'Land'  , 'No'  , 730,730,355,335, 'Neutral'  , 'No' ),
	array('Leptis'          , 'Coast' , 'Yes' , 530,638,270,310, 'Neutral'  , 'No' ),
	array('Phazania'        , 'Land'  , 'No'  , 480,680,245,330, 'Neutral'  , 'No' ),
	array('Sahara'          , 'Land'  , 'No'  , 260,650,135,298, 'Neutral'  , 'No' ),
	array('Numidia'         , 'Coast' , 'Yes' , 428,590,205,274, 'Neutral'  , 'No' ),
	array('Thapsus'         , 'Coast' , 'Yes' , 400,525,187,245, 'Carthage' , 'No' ),
	array('Carthage'        , 'Coast' , 'Yes' , 365,460,175,215, 'Carthage' , 'No' ),
	array('Cirta'           , 'Land'  , 'Yes' , 312,532,148,255, 'Carthage' , 'No' ),
	array('Mauretania'      , 'Coast' , 'No'  , 125,525, 70,245, 'Neutral'  , 'No' ),
	array('Baleares'        , 'Coast' , 'Yes' , 252,335,111,155, 'Neutral'  , 'No' ),
	array('Sardinia'        , 'Coast' , 'Yes' , 398,340,188,155, 'Neutral'  , 'No' ),
	array('Corsica'         , 'Coast' , 'No'  , 400,270,190,125, 'Neutral'  , 'No' ),
	array('Sicilia'         , 'Coast' , 'Yes' , 530,422,250,197, 'Neutral'  , 'No' ),
	array('Crete'           , 'Coast' , 'Yes' , 835,493,394,233, 'Neutral'  , 'No' ),
	array('Cyprus'          , 'Coast' , 'Yes' ,1045,481,492,229, 'Neutral'  , 'No' ),
	array('Iberian Sea'     , 'Sea'   , 'No'  , 145,440, 78,210, 'Neutral'  , 'No' ),
	array('Berber Sea'      , 'Sea'   , 'No'  , 275,395,140,175, 'Neutral'  , 'No' ),
	array('Ligurian Sea'    , 'Sea'   , 'No'  , 340,255,170,120, 'Neutral'  , 'No' ),
	array('Tyrrhenean Sea'  , 'Sea'   , 'No'  , 490,330,240,170, 'Neutral'  , 'No' ),
	array('Punic Sea'       , 'Sea'   , 'No'  , 420,405,220,210, 'Neutral'  , 'No' ),
	array('Gulf of Tacape'  , 'Sea'   , 'No'  , 530,550,250,275, 'Neutral'  , 'No' ),
	array('Ausonian Sea'    , 'Sea'   , 'No'  , 590,475,280,215, 'Neutral'  , 'No' ),
	array('Adriatic Sea'    , 'Sea'   , 'No'  , 575,249,260,110, 'Neutral'  , 'No' ),
	array('Ionian Sea'      , 'Sea'   , 'No'  , 650,380,307,172, 'Neutral'  , 'No' ),
	array('Messenian Sea'   , 'Sea'   , 'No'  , 720,475,335,217, 'Neutral'  , 'No' ),
	array('Libyan Sea'      , 'Sea'   , 'No'  , 750,550,330,260, 'Neutral'  , 'No' ),
	array('Gulf of Syrtis'  , 'Sea'   , 'No'  , 660,620,315,310, 'Neutral'  , 'No' ),
	array('Aegean Sea'      , 'Sea'   , 'No'  , 840,430,392,193, 'Neutral'  , 'No' ),
	array('Black Sea'       , 'Sea'   , 'No'  ,1000,190,445, 90, 'Neutral'  , 'No' ),
	array('Egyptian Sea'    , 'Sea'   , 'No'  , 940,550,440,255, 'Neutral'  , 'No' ),
	array('Minoan Sea'      , 'Sea'   , 'No'  , 920,465,425,226, 'Neutral'  , 'No' ),
	array('Cilician Strait' , 'Sea'   , 'No'  ,1085,437,510,205, 'Neutral'  , 'No' ),
	array('Syrian Sea'      , 'Sea'   , 'No'  ,1080,510,510,235, 'Neutral'  , 'No' ),
	array('Gulf of Pelusium', 'Sea'   , 'No'  ,1060,560,512,268, 'Neutral'  , 'No' ),
	array('Red Sea'        , 'Sea'   , 'No'  ,1190,745,550,340, 'Neutral'  , 'No' )
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $x, $y, $sx, $sy, $country)=$territoryRawRow;
	if( $country=='Neutral' )
		$countryID=0;
	else
		$countryID=$this->countryID($country);
		
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array( 'Saguntum'        , 'Tarraconensis'   , 'Yes' , 'Yes' ),
	array( 'Tarraconensis'   , 'Massilia'        , 'Yes' , 'Yes' ),
	array( 'Massilia'        , 'Etruria'         , 'Yes' , 'Yes' ),
	array( 'Etruria'         , 'Roma'            , 'Yes' , 'Yes' ),
	array( 'Roma'            , 'Neapolis'        , 'Yes' , 'Yes' ),
	array( 'Neapolis'        , 'Sicilia'         , 'Yes' , 'Yes' ),
	array( 'Neapolis'        , 'Apulia'          , 'Yes' , 'Yes' ),
	array( 'Apulia'          , 'Ravenna'         , 'Yes' , 'Yes' ),
	array( 'Ravenna'         , 'Venetia'         , 'Yes' , 'Yes' ),
	array( 'Venetia'         , 'Dalmatia'        , 'Yes' , 'Yes' ),
	array( 'Dalmatia'        , 'Epirus'          , 'Yes' , 'Yes' ),
	array( 'Epirus'          , 'Athens'          , 'Yes' , 'Yes' ),
	array( 'Athens'          , 'Sparta'          , 'Yes' , 'Yes' ),
	array( 'Athens'          , 'Macedonia'       , 'Yes' , 'Yes' ),
	array( 'Macedonia'       , 'Byzantium'       , 'Yes' , 'Yes' ),
	array( 'Byzantium'       , 'Dacia'           , 'Yes' , 'Yes' ),
	array( 'Byzantium'       , 'Bithynia'        , 'Yes' , 'Yes' ),
	array( 'Byzantium'       , 'Miletus'         , 'Yes' , 'Yes' ),
	array( 'Dacia'           , 'Chersonesus'     , 'Yes' , 'Yes' ),
	array( 'Chersonesus'     , 'Sinope'          , 'Yes' , 'Yes' ),
	array( 'Sinope'          , 'Bithynia'        , 'Yes' , 'Yes' ),
	array( 'Miletus'         , 'Isauria'         , 'Yes' , 'Yes' ),
	array( 'Isauria'         , 'Cappadocia'      , 'Yes' , 'Yes' ),
	array( 'Cappadocia'      , 'Antioch'         , 'Yes' , 'Yes' ),
	array( 'Antioch'         , 'Sidon'           , 'Yes' , 'Yes' ),
	array( 'Sidon'           , 'Tyre'            , 'Yes' , 'Yes' ),
	array( 'Tyre'            , 'Jerusalem'       , 'Yes' , 'Yes' ),
	array( 'Jerusalem'       , 'Sinai'           , 'Yes' , 'Yes' ),
	array( 'Sinai'           , 'Petra'           , 'Yes' , 'Yes' ),
	array( 'Sinai'           , 'Thebes'          , 'Yes' , 'Yes' ),
	array( 'Sinai'           , 'Alexandria'      , 'Yes' , 'Yes' ),
	array( 'Thebes'          , 'Memphis'         , 'Yes' , 'Yes' ),
	array( 'Thebes'          , 'Bayuda'          , 'Yes' , 'Yes' ),
	array( 'Bayuda'          , 'Memphis'         , 'Yes' , 'Yes' ),
	array( 'Memphis'         , 'Alexandria'      , 'Yes' , 'Yes' ),
	array( 'Alexandria'      , 'Cyrene'          , 'Yes' , 'Yes' ),
	array( 'Alexandria'      , 'Thebes'          , 'Yes' , 'Yes' ),
	array( 'Cyrene'          , 'Leptis'          , 'Yes' , 'Yes' ),
	array( 'Leptis'          , 'Numidia'         , 'Yes' , 'Yes' ),
	array( 'Numidia'         , 'Thapsus'         , 'Yes' , 'Yes' ),
	array( 'Thapsus'         , 'Carthage'        , 'Yes' , 'Yes' ),
	array( 'Carthage'        , 'Mauretania'      , 'Yes' , 'Yes' ),
	array( 'Mauretania'      , 'Saguntum'        , 'Yes' , 'Yes' ),
	array( 'Corsica'         , 'Sardinia'        , 'Yes' , 'Yes' ),
	array( 'Lusitania'       , 'Saguntum'        , 'No'  , 'Yes' ),
	array( 'Lusitania'       , 'Tarraconensis'   , 'No'  , 'Yes' ),
	array( 'Lusitania'       , 'Gaul'            , 'No'  , 'Yes' ),
	array( 'Tarraconensis'   , 'Gaul'            , 'No'  , 'Yes' ),
	array( 'Gaul'            , 'Massilia'        , 'No'  , 'Yes' ),
	array( 'Gaul'            , 'Rhaetia'         , 'No'  , 'Yes' ),
	array( 'Massilia'        , 'Rhaetia'         , 'No'  , 'Yes' ),
	array( 'Rhaetia'         , 'Etruria'         , 'No'  , 'Yes' ),
	array( 'Rhaetia'         , 'Venetia'         , 'No'  , 'Yes' ),
	array( 'Rhaetia'         , 'Vindobona'       , 'No'  , 'Yes' ),
	array( 'Rhaetia'         , 'Sarmatia'        , 'No'  , 'Yes' ),
	array( 'Etruria'         , 'Venetia'         , 'No'  , 'Yes' ),
	array( 'Etruria'         , 'Ravenna'         , 'No'  , 'Yes' ),
	array( 'Venetia'         , 'Vindobona'       , 'No'  , 'Yes' ),
	array( 'Roma'            , 'Ravenna'         , 'No'  , 'Yes' ),
	array( 'Roma'            , 'Apulia'          , 'No'  , 'Yes' ),
	array( 'Vindobona'       , 'Dalmatia'        , 'No'  , 'Yes' ),
	array( 'Vindobona'       , 'Illyria'         , 'No'  , 'Yes' ),
	array( 'Vindobona'       , 'Sarmatia'        , 'No'  , 'Yes' ),
	array( 'Dalmatia'        , 'Illyria'         , 'No'  , 'Yes' ),
	array( 'Illyria'         , 'Sarmatia'        , 'No'  , 'Yes' ),
	array( 'Illyria'         , 'Dacia'           , 'No'  , 'Yes' ),
	array( 'Illyria'         , 'Epirus'          , 'No'  , 'Yes' ),
	array( 'Illyria'         , 'Macedonia'       , 'No'  , 'Yes' ),
	array( 'Sarmatia'        , 'Dacia'           , 'No'  , 'Yes' ),
	array( 'Sarmatia'        , 'Chersonesus'     , 'No'  , 'Yes' ),
	array( 'Dacia'           , 'Macedonia'       , 'No'  , 'Yes' ),
	array( 'Chersonesus'     , 'Armenia'         , 'No'  , 'Yes' ),
	array( 'Epirus'          , 'Macedonia'       , 'No'  , 'Yes' ),
	array( 'Byzantium'       , 'Galatia'         , 'No'  , 'Yes' ),
	array( 'Bithynia'        , 'Galatia'         , 'No'  , 'Yes' ),
	array( 'Sinope'          , 'Galatia'         , 'No'  , 'Yes' ),
	array( 'Sinope'          , 'Cappadocia'      , 'No'  , 'Yes' ),
	array( 'Sinope'          , 'Armenia'         , 'No'  , 'Yes' ),
	array( 'Miletus'         , 'Galatia'         , 'No'  , 'Yes' ),
	array( 'Galatia'         , 'Isauria'         , 'No'  , 'Yes' ),
	array( 'Galatia'         , 'Cappadocia'      , 'No'  , 'Yes' ),
	array( 'Cappadocia'      , 'Armenia'         , 'No'  , 'Yes' ),
	array( 'Cappadocia'      , 'Damascus'        , 'No'  , 'Yes' ),
	array( 'Armenia'         , 'Damascus'        , 'No'  , 'Yes' ),
	array( 'Antioch'         , 'Damascus'        , 'No'  , 'Yes' ),
	array( 'Damascus'        , 'Sidon'           , 'No'  , 'Yes' ),
	array( 'Damascus'        , 'Arabia'          , 'No'  , 'Yes' ),
	array( 'Sidon'           , 'Arabia'          , 'No'  , 'Yes' ),
	array( 'Tyre'            , 'Arabia'          , 'No'  , 'Yes' ),
	array( 'Arabia'          , 'Jerusalem'       , 'No'  , 'Yes' ),
	array( 'Arabia'          , 'Nabatea'         , 'No'  , 'Yes' ),
	array( 'Jerusalem'       , 'Petra'           , 'No'  , 'Yes' ),
	array( 'Jerusalem'       , 'Nabatea'         , 'No'  , 'Yes' ),
	array( 'Petra'           , 'Nabatea'         , 'No'  , 'Yes' ),
	array( 'Bayuda'          , 'Marmarica'       , 'No'  , 'Yes' ),
	array( 'Bayuda'          , 'Phazania'        , 'No'  , 'Yes' ),
	array( 'Bayuda'          , 'Sahara'          , 'No'  , 'Yes' ),
	array( 'Memphis'         , 'Cyrene'          , 'No'  , 'Yes' ),
	array( 'Memphis'         , 'Marmarica'       , 'No'  , 'Yes' ),
	array( 'Cyrene'          , 'Marmarica'       , 'No'  , 'Yes' ),
	array( 'Marmarica'       , 'Leptis'          , 'No'  , 'Yes' ),
	array( 'Marmarica'       , 'Phazania'        , 'No'  , 'Yes' ),
	array( 'Leptis'          , 'Phazania'        , 'No'  , 'Yes' ),
	array( 'Phazania'        , 'Sahara'          , 'No'  , 'Yes' ),
	array( 'Phazania'        , 'Numidia'         , 'No'  , 'Yes' ),
	array( 'Phazania'        , 'Cirta'           , 'No'  , 'Yes' ),
	array( 'Sahara'          , 'Cirta'           , 'No'  , 'Yes' ),
	array( 'Sahara'          , 'Mauretania'      , 'No'  , 'Yes' ),
	array( 'Numidia'         , 'Cirta'           , 'No'  , 'Yes' ),
	array( 'Thapsus'         , 'Cirta'           , 'No'  , 'Yes' ),
	array( 'Carthage'        , 'Cirta'           , 'No'  , 'Yes' ),
	array( 'Cirta'           , 'Mauretania'      , 'No'  , 'Yes' ),
	array( 'Tarraconensis'   , 'Baleares'        , 'Yes' , 'No'  ),
	array( 'Tarraconensis'   , 'Ligurian Sea'    , 'Yes' , 'No'  ),
	array( 'Saguntum'        , 'Baleares'        , 'Yes' , 'No'  ),
	array( 'Saguntum'        , 'Iberian Sea'     , 'Yes' , 'No'  ),
	array( 'Saguntum'        , 'Berber Sea'      , 'Yes' , 'No'  ),
	array( 'Massilia'        , 'Ligurian Sea'    , 'Yes' , 'No'  ),
	array( 'Etruria'         , 'Ligurian Sea'    , 'Yes' , 'No'  ),
	array( 'Venetia'         , 'Adriatic Sea'    , 'Yes' , 'No'  ),
	array( 'Roma'            , 'Ligurian Sea'    , 'Yes' , 'No'  ),
	array( 'Roma'            , 'Tyrrhenean Sea'  , 'Yes' , 'No'  ),
	array( 'Ravenna'         , 'Adriatic Sea'    , 'Yes' , 'No'  ),
	array( 'Neapolis'        , 'Tyrrhenean Sea'  , 'Yes' , 'No'  ),
	array( 'Neapolis'        , 'Ausonian Sea'    , 'Yes' , 'No'  ),
	array( 'Neapolis'        , 'Ionian Sea'      , 'Yes' , 'No'  ),
	array( 'Apulia'          , 'Ionian Sea'      , 'Yes' , 'No'  ),
	array( 'Apulia'          , 'Adriatic Sea'    , 'Yes' , 'No'  ),
	array( 'Dalmatia'        , 'Adriatic Sea'    , 'Yes' , 'No'  ),
	array( 'Dacia'           , 'Black Sea'       , 'Yes' , 'No'  ),
	array( 'Chersonesus'     , 'Black Sea'       , 'Yes' , 'No'  ),
	array( 'Epirus'          , 'Adriatic Sea'    , 'Yes' , 'No'  ),
	array( 'Epirus'          , 'Ionian Sea'      , 'Yes' , 'No'  ),
	array( 'Macedonia'       , 'Aegean Sea'      , 'Yes' , 'No'  ),
	array( 'Athens'          , 'Ionian Sea'      , 'Yes' , 'No'  ),
	array( 'Athens'          , 'Aegean Sea'      , 'Yes' , 'No'  ),
	array( 'Sparta'          , 'Ionian Sea'      , 'Yes' , 'No'  ),
	array( 'Sparta'          , 'Messenian Sea'   , 'Yes' , 'No'  ),
	array( 'Sparta'          , 'Aegean Sea'      , 'Yes' , 'No'  ),
	array( 'Byzantium'       , 'Aegean Sea'      , 'Yes' , 'No'  ),
	array( 'Byzantium'       , 'Black Sea'       , 'Yes' , 'No'  ),
	array( 'Bithynia'        , 'Black Sea'       , 'Yes' , 'No'  ),
	array( 'Sinope'          , 'Black Sea'       , 'Yes' , 'No'  ),
	array( 'Miletus'         , 'Aegean Sea'      , 'Yes' , 'No'  ),
	array( 'Miletus'         , 'Minoan Sea'      , 'Yes' , 'No'  ),
	array( 'Miletus'         , 'Cilician Strait' , 'Yes' , 'No'  ),
	array( 'Isauria'         , 'Cilician Strait' , 'Yes' , 'No'  ),
	array( 'Cappadocia'      , 'Cilician Strait' , 'Yes' , 'No'  ),
	array( 'Antioch'         , 'Cilician Strait' , 'Yes' , 'No'  ),
	array( 'Sidon'           , 'Cilician Strait' , 'Yes' , 'No'  ),
	array( 'Sidon'           , 'Syrian Sea'      , 'Yes' , 'No'  ),
	array( 'Tyre'            , 'Syrian Sea'      , 'Yes' , 'No'  ),
	array( 'Jerusalem'       , 'Syrian Sea'      , 'Yes' , 'No'  ),
	array( 'Jerusalem'       , 'Gulf of Pelusium', 'Yes' , 'No'  ),
	array( 'Petra'           , 'Red Sea'        , 'Yes' , 'No'  ),
	array( 'Red Sea'        , 'Nabatea'         , 'Yes' , 'No'  ),
	array( 'Red Sea'        , 'Sinai'           , 'Yes' , 'No'  ),
	array( 'Red Sea'        , 'Thebes'          , 'Yes' , 'No'  ),
	array( 'Baleares'        , 'Ligurian Sea'    , 'Yes' , 'No'  ),
	array( 'Baleares'        , 'Berber Sea'      , 'Yes' , 'No'  ),
	array( 'Ligurian Sea'    , 'Tyrrhenean Sea'  , 'Yes' , 'No'  ),
	array( 'Ligurian Sea'    , 'Corsica'         , 'Yes' , 'No'  ),
	array( 'Ligurian Sea'    , 'Sardinia'        , 'Yes' , 'No'  ),
	array( 'Ligurian Sea'    , 'Berber Sea'      , 'Yes' , 'No'  ),
	array( 'Iberian Sea'     , 'Berber Sea'      , 'Yes' , 'No'  ),
	array( 'Iberian Sea'     , 'Mauretania'      , 'Yes' , 'No'  ),
	array( 'Berber Sea'      , 'Mauretania'      , 'Yes' , 'No'  ),
	array( 'Berber Sea'      , 'Carthage'        , 'Yes' , 'No'  ),
	array( 'Berber Sea'      , 'Punic Sea'       , 'Yes' , 'No'  ),
	array( 'Berber Sea'      , 'Sardinia'        , 'Yes' , 'No'  ),
	array( 'Tyrrhenean Sea'  , 'Corsica'         , 'Yes' , 'No'  ),
	array( 'Tyrrhenean Sea'  , 'Sardinia'        , 'Yes' , 'No'  ),
	array( 'Tyrrhenean Sea'  , 'Punic Sea'       , 'Yes' , 'No'  ),
	array( 'Tyrrhenean Sea'  , 'Sicilia'         , 'Yes' , 'No'  ),
	array( 'Tyrrhenean Sea'  , 'Ausonian Sea'    , 'Yes' , 'No'  ),
	array( 'Adriatic Sea'    , 'Ionian Sea'      , 'Yes' , 'No'  ),
	array( 'Ionian Sea'      , 'Ausonian Sea'    , 'Yes' , 'No'  ),
	array( 'Ionian Sea'      , 'Messenian Sea'   , 'Yes' , 'No'  ),
	array( 'Punic Sea'       , 'Carthage'        , 'Yes' , 'No'  ),
	array( 'Punic Sea'       , 'Thapsus'         , 'Yes' , 'No'  ),
	array( 'Punic Sea'       , 'Sardinia'        , 'Yes' , 'No'  ),
	array( 'Punic Sea'       , 'Gulf of Tacape'  , 'Yes' , 'No'  ),
	array( 'Punic Sea'       , 'Ausonian Sea'    , 'Yes' , 'No'  ),
	array( 'Punic Sea'       , 'Sicilia'         , 'Yes' , 'No'  ),
	array( 'Aegean Sea'      , 'Messenian Sea'   , 'Yes' , 'No'  ),
	array( 'Aegean Sea'      , 'Crete'           , 'Yes' , 'No'  ),
	array( 'Aegean Sea'      , 'Minoan Sea'      , 'Yes' , 'No'  ),
	array( 'Egyptian Sea'    , 'Minoan Sea'      , 'Yes' , 'No'  ),
	array( 'Egyptian Sea'    , 'Cilician Strait' , 'Yes' , 'No'  ),
	array( 'Egyptian Sea'    , 'Cyprus'          , 'Yes' , 'No'  ),
	array( 'Egyptian Sea'    , 'Syrian Sea'      , 'Yes' , 'No'  ),
	array( 'Egyptian Sea'    , 'Gulf of Pelusium', 'Yes' , 'No'  ),
	array( 'Egyptian Sea'    , 'Alexandria'      , 'Yes' , 'No'  ),
	array( 'Egyptian Sea'    , 'Libyan Sea'      , 'Yes' , 'No'  ),
	array( 'Egyptian Sea'    , 'Crete'           , 'Yes' , 'No'  ),
	array( 'Minoan Sea'      , 'Crete'           , 'Yes' , 'No'  ),
	array( 'Minoan Sea'      , 'Cilician Strait' , 'Yes' , 'No'  ),
	array( 'Cilician Strait' , 'Cyprus'          , 'Yes' , 'No'  ),
	array( 'Cilician Strait' , 'Syrian Sea'      , 'Yes' , 'No'  ),
	array( 'Syrian Sea'      , 'Cyprus'          , 'Yes' , 'No'  ),
	array( 'Syrian Sea'      , 'Gulf of Pelusium', 'Yes' , 'No'  ),
	array( 'Gulf of Pelusium', 'Alexandria'      , 'Yes' , 'No'  ),
	array( 'Gulf of Pelusium', 'Sinai'           , 'Yes' , 'No'  ),
	array( 'Gulf of Pelusium', 'Thebes'          , 'Yes' , 'No'  ),
	array( 'Gulf of Syrtis'  , 'Gulf of Tacape'  , 'Yes' , 'No'  ),
	array( 'Gulf of Syrtis'  , 'Libyan Sea'      , 'Yes' , 'No'  ),
	array( 'Gulf of Syrtis'  , 'Cyrene'          , 'Yes' , 'No'  ),
	array( 'Gulf of Syrtis'  , 'Leptis'          , 'Yes' , 'No'  ),
	array( 'Ausonian Sea'    , 'Sicilia'         , 'Yes' , 'No'  ),
	array( 'Ausonian Sea'    , 'Messenian Sea'   , 'Yes' , 'No'  ),
	array( 'Ausonian Sea'    , 'Libyan Sea'      , 'Yes' , 'No'  ),
	array( 'Ausonian Sea'    , 'Gulf of Tacape'  , 'Yes' , 'No'  ),
	array( 'Messenian Sea'   , 'Crete'           , 'Yes' , 'No'  ),
	array( 'Messenian Sea'   , 'Libyan Sea'      , 'Yes' , 'No'  ),
	array( 'Messenian Sea'   , 'Gulf of Tacape'  , 'Yes' , 'No'  ),
	array( 'Gulf of Tacape'  , 'Thapsus'         , 'Yes' , 'No'  ),
	array( 'Gulf of Tacape'  , 'Numidia'         , 'Yes' , 'No'  ),
	array( 'Gulf of Tacape'  , 'Leptis'          , 'Yes' , 'No'  ),
	array( 'Gulf of Tacape'  , 'Libyan Sea'      , 'Yes' , 'No'  ),
	array( 'Libyan Sea'      , 'Cyrene'          , 'Yes' , 'No'  ),
	array( 'Libyan Sea'      , 'Alexandria'      , 'Yes' , 'No'  ),
	array( 'Libyan Sea'      , 'Crete'           , 'Yes' , 'No'  )
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
	InstallTerritory::$Territories[$from]->addBorder(InstallTerritory::$Territories[$to]  ,$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);

?>