<?php
// This is file installs the map data for the Imperial2 variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Abyssinia', 'Coast', 'Yes', 0, 1565, 587, 0, 0),
	array('Aden', 'Coast', 'Yes', 3, 1602, 557, 0, 0),
	array('Adriatic Sea', 'Sea', 'No', 0, 1386, 375, 0, 0),
	array('Aegean Sea', 'Sea', 'No', 0, 1441, 351, 0, 0),
	array('Afganistan', 'Land', 'No', 0, 1729, 415, 0, 0),
	array('Alaska', 'Coast', 'No', 11, 447, 153, 0, 0),
	array('Alaska (North Coast)', 'Coast', 'No', 0, 414, 120, 0, 0),
	array('Alaska (South Coast)', 'Coast', 'No', 0, 456, 205, 0, 0),
	array('Alberta', 'Land', 'Yes', 0, 545, 235, 0, 0),
	array('Algeria', 'Coast', 'No', 0, 1293, 390, 0, 0),
	array('Amazon', 'Land', 'No', 2, 784, 742, 0, 0),
	array('Anchorage', 'Coast', 'Yes', 11, 347, 175, 0, 0),
	array('Andaman Islands', 'Coast', 'Yes', 0, 1932, 582, 0, 0),
	array('Andaman Sea', 'Sea', 'No', 0, 1970, 611, 0, 0),
	array('Angola', 'Coast', 'No', 0, 1397, 810, 0, 0),
	array('Angora', 'Coast', 'Yes', 12, 1520, 356, 0, 0),
	array('Angora (North Coast)', 'Coast', 'No', 12, 1531, 341, 0, 0),
	array('Angora (South Coast)', 'Coast', 'No', 12, 1499, 367, 0, 0),
	array('Annam', 'Coast', 'No', 0, 2077, 555, 0, 0),
	array('Antarctic Atlantic', 'Sea', 'No', 0, 1206, 1172, 0, 0),
	array('Antarctic Indian', 'Sea', 'No', 0, 1682, 1131, 0, 0),
	array('Antarctic Pacific', 'Sea', 'No', 0, 508, 1165, 0, 0),
	array('Arabian', 'Sea', 'No', 0, 1739, 598, 0, 0),
	array('Armenia', 'Land', 'No', 12, 1566, 357, 0, 0),
	array('Ashanti', 'Land', 'No', 0, 1347, 599, 0, 0),
	array('Assam', 'Land', 'No', 0, 1941, 461, 0, 0),
	array('Aswan', 'Coast', 'No', 12, 1503, 480, 0, 0),
	array('Atlanta', 'Coast', 'Yes', 5, 673, 417, 0, 0),
	array('Austin', 'Coast', 'Yes', 5, 579, 424, 0, 0),
	array('Azores', 'Coast', 'Yes', 0, 1140, 371, 0, 0),
	array('Baghdad', 'Coast', 'Yes', 12, 1573, 385, 0, 0),
	array('Bahamas', 'Coast', 'Yes', 0, 737, 484, 0, 0),
	array('Baku', 'Coast', 'Yes', 0, 1583, 344, 0, 0),
	array('Baku (East Coast)', 'Coast', 'No', 0, 1595, 327, 0, 0),
	array('Baku (West Coast)', 'Coast', 'No', 0, 1541, 316, 0, 0),
	array('Baltic Sea', 'Sea', 'No', 0, 1396, 211, 0, 0),
	array('Bangalore', 'Coast', 'Yes', 0, 1672, 426, 0, 0),
	array('Bangkok', 'Coast', 'Yes', 0, 1979, 580, 0, 0),
	array('Bangkok (East Coast)', 'Coast', 'No', 0, 2009, 595, 0, 0),
	array('Bangkok (West Coast)', 'Coast', 'No', 0, 1979, 580, 0, 0),
	array('Barcelone', 'Land', 'Yes', 0, 787, 638, 0, 0),
	array('Barents Sea', 'Sea', 'No', 0, 1336, 90, 0, 0),
	array('Barrier', 'Sea', 'No', 0, 2053, 995, 0, 0),
	array('Bavaria', 'Land', 'Yes', 0, 1350, 265, 0, 0),
	array('Bay of Bengal', 'Sea', 'No', 0, 1926, 530, 0, 0),
	array('Bay of Biscay', 'Sea', 'No', 0, 1189, 313, 0, 0),
	array('Bengal', 'Coast', 'Yes', 0, 1932, 481, 0, 0),
	array('Bering Sea', 'Sea', 'No', 0, 2347, 203, 0, 0),
	array('Berlin', 'Coast', 'Yes', 10, 1356, 243, 0, 0),
	array('Bismark', 'Sea', 'No', 0, 2381, 709, 0, 0),
	array('Black Sea', 'Sea', 'No', 0, 1516, 318, 0, 0),
	array('Bogota', 'Coast', 'Yes', 0, 713, 618, 0, 0),
	array('Bogota (North Coast)', 'Coast', 'No', 0, 715, 594, 0, 0),
	array('Bogota (South Coast)', 'Coast', 'No', 0, 685, 654, 0, 0),
	array('Bokhara', 'Land', 'No', 0, 1733, 351, 0, 0),
	array('Bombay', 'Coast', 'Yes', 3, 1816, 540, 0, 0),
	array('Bordeaux', 'Coast', 'No', 6, 1267, 310, 0, 0),
	array('Borneo', 'Coast', 'Yes', 7, 2121, 679, 0, 0),
	array('Bosnia', 'Coast', 'No', 12, 1415, 337, 0, 0),
	array('Bosnia (East Coast)', 'Coast', 'No', 0, 1422, 342, 0, 0),
	array('Bosnia (West Coast)', 'Coast', 'No', 0, 1405, 339, 0, 0),
	array('Botswana', 'Land', 'Yes', 0, 1438, 889, 0, 0),
	array('Brasilia', 'Land', 'Yes', 2, 855, 802, 0, 0),
	array('Brazil Current', 'Sea', 'No', 0, 1043, 983, 0, 0),
	array('British Columbia', 'Land', 'No', 0, 510, 198, 0, 0),
	array('Budapest', 'Land', 'Yes', 1, 1389, 280, 0, 0),
	array('Burma', 'Land', 'Yes', 0, 1964, 478, 0, 0),
	array('Cairo', 'Coast', 'Yes', 12, 1480, 433, 0, 0),
	array('Cairo (East Coast)', 'Coast', 'No', 12, 1503, 450, 0, 0),
	array('Cairo (North Coast)', 'Coast', 'No', 12, 1479, 424, 0, 0),
	array('Calabozo', 'Coast', 'No', 0, 796, 603, 0, 0),
	array('Caledonia', 'Coast', 'No', 0, 828, 651, 0, 0),
	array('Cambodia', 'Coast', 'Yes', 6, 2034, 573, 0, 0),
	array('Cameroon', 'Coast', 'Yes', 0, 1357, 649, 0, 0),
	array('Canary', 'Sea', 'No', 0, 1148, 432, 0, 0),
	array('Canton', 'Coast', 'Yes', 4, 2064, 495, 0, 0),
	array('Cape Town', 'Coast', 'Yes', 7, 1434, 953, 0, 0),
	array('Cape Verde Islands', 'Coast', 'Yes', 0, 1100, 532, 0, 0),
	array('Caroline Islands', 'Coast', 'Yes', 0, 2362, 635, 0, 0),
	array('Caspian Sea', 'Sea', 'No', 0, 1619, 348, 0, 0),
	array('Cayenne', 'Coast', 'Yes', 6, 888, 629, 0, 0),
	array('Celebes Sea', 'Sea', 'No', 0, 2216, 666, 0, 0),
	array('Celebes', 'Coast', 'No', 7, 2182, 725, 0, 0),
	array('Ceylon', 'Coast', 'Yes', 7, 1880, 606, 0, 0),
	array('Chesapeake', 'Sea', 'No', 0, 859, 334, 0, 0),
	array('Chicago', 'Land', 'Yes', 13, 635, 332, 0, 0),
	array('Chihuahua', 'Land', 'No', 9, 509, 451, 0, 0),
	array('Chilean Basin', 'Sea', 'No', 0, 689, 959, 0, 0),
	array('Chungking', 'Land', 'Yes', 4, 1977, 414, 0, 0),
	array('Coahula', 'Coast', 'No', 9, 548, 470, 0, 0),
	array('Coast of Argentina', 'Sea', 'No', 0, 909, 1043, 0, 0),
	array('Cochabamba', 'Land', 'No', 0, 800, 847, 0, 0),
	array('Cochin', 'Coast', 'Yes', 6, 2056, 582, 0, 0),
	array('Congo', 'Land', 'No', 0, 1466, 761, 0, 0),
	array('Constantinople', 'Coast', 'Yes', 12, 1470, 361, 0, 0),
	array('Coral', 'Sea', 'No', 0, 2420, 842, 0, 0),
	array('Corsica', 'Coast', 'Yes', 6, 1316, 342, 0, 0),
	array('Counter Current', 'Sea', 'No', 0, 307, 456, 0, 0),
	array('Crete', 'Coast', 'Yes', 0, 1449, 396, 0, 0),
	array('Croatia', 'Coast', 'Yes', 1, 1375, 304, 0, 0),
	array('Cuba', 'Coast', 'Yes', 0, 685, 521, 0, 0),
	array('Cyprus', 'Coast', 'Yes', 12, 1483, 393, 0, 0),
	array('Damaraland', 'Coast', 'No', 0, 1388, 852, 0, 0),
	array('Dar Es Sallam', 'Land', 'No', 0, 1474, 601, 0, 0),
	array('Delhi', 'Land', 'Yes', 3, 1839, 450, 0, 0),
	array('Denkyera', 'Coast', 'No', 0, 1308, 629, 0, 0),
	array('Denmark', 'Coast', 'Yes', 0, 1330, 213, 0, 0),
	array('Detroit', 'Land', 'Yes', 13, 702, 312, 0, 0),
	array('Drake', 'Sea', 'No', 0, 863, 1179, 0, 0),
	array('Dublin', 'Coast', 'Yes', 3, 1202, 228, 0, 0),
	array('East China Sea', 'Sea', 'No', 0, 2161, 463, 0, 0),
	array('East Indian', 'Sea', 'No', 0, 1885, 679, 0, 0),
	array('Eastern Carribean', 'Sea', 'No', 0, 767, 567, 0, 0),
	array('Eastern Mediterranean', 'Sea', 'No', 0, 1467, 395, 0, 0),
	array('Eastern Pacific', 'Sea', 'No', 0, 382, 652, 0, 0),
	array('Eastern Seaboard', 'Sea', 'No', 0, 766, 406, 0, 0),
	array('Edinburgh', 'Coast', 'Yes', 3, 1253, 212, 0, 0),
	array('Edo', 'Coast', 'Yes', 8, 2262, 370, 0, 0),
	array('El Jouf', 'Land', 'No', 0, 1252, 538, 0, 0),
	array('Equatorial CounterCurrent', 'Sea', 'No', 0, 2620, 697, 0, 0),
	array('Evenki', 'Land', 'No', 11, 1801, 169, 0, 0),
	array('Falkland Islands', 'Coast', 'Yes', 3, 918, 1112, 0, 0),
	array('Fezz', 'Land', 'No', 0, 1419, 483, 0, 0),
	array('Fiji', 'Coast', 'Yes', 0, 2554, 811, 0, 0),
	array('Finland', 'Coast', 'No', 0, 1437, 144, 0, 0),
	array('Finland (North Coast)', 'Coast', 'No', 0, 1454, 113, 0, 0),
	array('Finland (South Coast)', 'Coast', 'No', 0, 1409, 162, 0, 0),
	array('Formosa', 'Coast', 'Yes', 0, 2154, 502, 0, 0),
	array('Fuchan', 'Coast', 'No', 4, 2108, 470, 0, 0),
	array('Fusan', 'Coast', 'Yes', 0, 2178, 374, 0, 0),
	array('Galapagos', 'Coast', 'Yes', 0, 600, 667, 0, 0),
	array('Galicia', 'Land', 'No', 1, 1429, 270, 0, 0),
	array('Gall Land', 'Land', 'No', 0, 1555, 639, 0, 0),
	array('Georgia', 'Coast', 'Yes', 11, 1558, 274, 0, 0),
	array('Georgia (East Coast)', 'Coast', 'No', 11, 1579, 304, 0, 0),
	array('Georgia (West Coast)', 'Coast', 'No', 11, 1531, 288, 0, 0),
	array('Gibraltar', 'Coast', 'Yes', 3, 1207, 383, 0, 0),
	array('Goodhope', 'Sea', 'No', 0, 1401, 1033, 0, 0),
	array('Goyamas', 'Land', 'No', 0, 802, 943, 0, 0),
	array('Grain Coast', 'Coast', 'Yes', 6, 1209, 620, 0, 0),
	array('Greece', 'Coast', 'Yes', 0, 1419, 387, 0, 0),
	array('Greenland', 'Coast', 'Yes', 0, 1087, 101, 0, 0),
	array('Guatemala', 'Coast', 'No', 0, 604, 538, 0, 0),
	array('Guatemala (East Coast)', 'Coast', 'No', 0, 633, 530, 0, 0),
	array('Guatemala (West Coast)', 'Coast', 'No', 0, 593, 578, 0, 0),
	array('Gujarat', 'Coast', 'No', 0, 1779, 492, 0, 0),
	array('Gulf of Alaska', 'Sea', 'No', 0, 365, 229, 0, 0),
	array('Gulf of Bothnia', 'Sea', 'No', 0, 1396, 172, 0, 0),
	array('Gulf of California', 'Sea', 'No', 0, 500, 549, 0, 0),
	array('Gulf of Guinea', 'Sea', 'No', 0, 1276, 669, 0, 0),
	array('Gulf of Lyon', 'Sea', 'No', 0, 1300, 331, 0, 0),
	array('Gulf of Manaar', 'Sea', 'No', 0, 1883, 565, 0, 0),
	array('Gulf of Mexico', 'Sea', 'No', 0, 605, 462, 0, 0),
	array('Gulf of Panama', 'Sea', 'No', 0, 653, 664, 0, 0),
	array('Gulf of Siam', 'Sea', 'No', 0, 2057, 617, 0, 0),
	array('Hadramaut', 'Coast', 'No', 0, 1631, 521, 0, 0),
	array('Hadramaut (North Coast)', 'Coast', 'No', 0, 1622, 457, 0, 0),
	array('Hadramaut (South Coast)', 'Coast', 'No', 0, 1626, 551, 0, 0),
	array('Haiti', 'Coast', 'Yes', 0, 737, 550, 0, 0),
	array('Hawaii', 'Coast', 'Yes', 0, 92, 516, 0, 0),
	array('Helgoland Bight', 'Sea', 'No', 0, 1303, 223, 0, 0),
	array('Holland', 'Coast', 'Yes', 7, 1303, 246, 0, 0),
	array('Honduras', 'Coast', 'Yes', 0, 629, 561, 0, 0),
	array('Honduras (East Coast)', 'Coast', 'No', 0, 663, 557, 0, 0),
	array('Honduras (West Coast)', 'Coast', 'No', 0, 615, 592, 0, 0),
	array('Hong Kong', 'Coast', 'Yes', 3, 2100, 514, 0, 0),
	array('Horn of Africa', 'Sea', 'No', 0, 1629, 720, 0, 0),
	array('Hudson', 'Sea', 'No', 0, 944, 172, 0, 0),
	array('Hyderabad', 'Coast', 'No', 0, 1863, 526, 0, 0),
	array('Iceland', 'Coast', 'No', 0, 1190, 115, 0, 0),
	array('Inner Mongolia', 'Land', 'No', 4, 2073, 315, 0, 0),
	array('Ionian Sea', 'Sea', 'No', 0, 1393, 406, 0, 0),
	array('Irian Java', 'Coast', 'Yes', 0, 2297, 731, 0, 0),
	array('Irkutsk', 'Land', 'Yes', 11, 1982, 244, 0, 0),
	array('Ivory Coast', 'Coast', 'Yes', 0, 1270, 618, 0, 0),
	array('Izu Trench', 'Sea', 'No', 0, 2366, 449, 0, 0),
	array('Java Sea', 'Sea', 'No', 0, 2076, 721, 0, 0),
	array('Java', 'Coast', 'Yes', 7, 2087, 772, 0, 0),
	array('Kagoshima', 'Coast', 'Yes', 8, 2217, 429, 0, 0),
	array('Kamchatka', 'Coast', 'No', 11, 2248, 162, 0, 0),
	array('Kansas', 'Land', 'Yes', 0, 552, 365, 0, 0),
	array('Karachi', 'Coast', 'Yes', 0, 1768, 423, 0, 0),
	array('Kasala', 'Land', 'No', 0, 1730, 290, 0, 0),
	array('Kashgar', 'Land', 'No', 4, 1845, 383, 0, 0),
	array('Kashmir', 'Land', 'Yes', 0, 1809, 399, 0, 0),
	array('Kenya', 'Coast', 'No', 0, 1527, 698, 0, 0),
	array('Khiva', 'Coast', 'Yes', 0, 1694, 358, 0, 0),
	array('Kiel', 'Coast', 'Yes', 0, 1335, 230, 0, 0),
	array('Kiel (East Coast)', 'Coast', 'No', 0, 1326, 236, 0, 0),
	array('Kiel (West Coast)', 'Coast', 'No', 0, 1345, 230, 0, 0),
	array('Kirbati Sea', 'Sea', 'No', 0, 162, 681, 0, 0),
	array('Kirghiz', 'Land', 'No', 4, 1856, 303, 0, 0),
	array('Krasnoyarsk', 'Land', 'No', 11, 1762, 253, 0, 0),
	array('Kuril', 'Sea', 'No', 0, 2342, 313, 0, 0),
	array('La Paz', 'Land', 'Yes', 0, 768, 792, 0, 0),
	array('Langchow', 'Land', 'No', 4, 1991, 385, 0, 0),
	array('Lima', 'Coast', 'Yes', 0, 705, 708, 0, 0),
	array('Livonia', 'Coast', 'No', 11, 1428, 212, 0, 0),
	array('London', 'Coast', 'Yes', 3, 1270, 242, 0, 0),
	array('Lucknow', 'Land', 'No', 0, 1876, 482, 0, 0),
	array('Luzon Sea', 'Sea', 'No', 0, 2119, 561, 0, 0),
	array('Luzon', 'Coast', 'Yes', 0, 2190, 560, 0, 0),
	array('Madagascar', 'Coast', 'Yes', 0, 1598, 864, 0, 0),
	array('Madras', 'Coast', 'Yes', 0, 1835, 560, 0, 0),
	array('Malagasy Channel', 'Sea', 'No', 0, 1559, 843, 0, 0),
	array('Malaysia', 'Coast', 'Yes', 0, 2041, 654, 0, 0),
	array('Maldives', 'Coast', 'Yes', 0, 1802, 687, 0, 0),
	array('Manchuria', 'Coast', 'Yes', 4, 2131, 316, 0, 0),
	array('Mandalay', 'Land', 'No', 0, 1978, 496, 0, 0),
	array('Mandingoes', 'Land', 'No', 0, 1242, 594, 0, 0),
	array('Mandlah', 'Land', 'No', 3, 1825, 494, 0, 0),
	array('Marseilles', 'Coast', 'Yes', 6, 1297, 312, 0, 0),
	array('Marshal Islands', 'Coast', 'Yes', 0, 2512, 613, 0, 0),
	array('Mazatlan', 'Coast', 'Yes', 9, 505, 499, 0, 0),
	array('Mecca', 'Coast', 'No', 12, 1535, 457, 0, 0),
	array('Merida', 'Coast', 'Yes', 9, 585, 508, 0, 0),
	array('Metz', 'Land', 'No', 6, 1304, 270, 0, 0),
	array('Mexico City', 'Coast', 'Yes', 9, 544, 511, 0, 0),
	array('Middle Atlantic', 'Sea', 'No', 0, 1083, 716, 0, 0),
	array('Mindanao', 'Coast', 'Yes', 0, 2137, 588, 0, 0),
	array('Minnesota', 'Land', 'No', 13, 660, 303, 0, 0),
	array('Mitu', 'Land', 'No', 0, 734, 658, 0, 0),
	array('Mongolia', 'Land', 'No', 4, 1960, 317, 0, 0),
	array('Monrovia', 'Coast', 'Yes', 6, 1189, 596, 0, 0),
	array('Morocco', 'Coast', 'Yes', 0, 1240, 398, 0, 0),
	array('Moscow', 'Land', 'Yes', 11, 1515, 237, 0, 0),
	array('Mozambique', 'Coast', 'No', 0, 1537, 807, 0, 0),
	array('Nantes', 'Coast', 'Yes', 6, 1255, 279, 0, 0),
	array('Nebraska', 'Land', 'Yes', 0, 567, 330, 0, 0),
	array('Nejaaz', 'Land', 'No', 0, 1577, 447, 0, 0),
	array('New Guinea', 'Coast', 'Yes', 0, 2315, 748, 0, 0),
	array('New Mexico', 'Land', 'Yes', 0, 481, 403, 0, 0),
	array('New Orleans', 'Coast', 'Yes', 5, 605, 404, 0, 0),
	array('New South Wales', 'Coast', 'Yes', 0, 2280, 983, 0, 0),
	array('New York', 'Coast', 'Yes', 13, 776, 320, 0, 0),
	array('New Zealand', 'Coast', 'Yes', 0, 2480, 1039, 0, 0),
	array('North Atlantic', 'Sea', 'No', 0, 1039, 332, 0, 0),
	array('North East Monsoon', 'Sea', 'No', 0, 1739, 723, 0, 0),
	array('North East Trades', 'Sea', 'No', 0, 932, 604, 0, 0),
	array('North Pacific', 'Sea', 'No', 0, 254, 374, 0, 0),
	array('North Passage', 'Sea', 'No', 0, 1147, 178, 0, 0),
	array('North Sea', 'Sea', 'No', 0, 1285, 210, 0, 0),
	array('Northern Territories', 'Coast', 'No', 0, 2241, 832, 0, 0),
	array('Northwest Territories', 'Land', 'No', 0, 576, 169, 0, 0),
	array('Norway', 'Coast', 'Yes', 0, 1328, 172, 0, 0),
	array('Norwegian Sea', 'Sea', 'No', 0, 1291, 134, 0, 0),
	array('Nova Scotia', 'Coast', 'Yes', 3, 932, 248, 0, 0),
	array('Oaxaca', 'Coast', 'No', 9, 549, 564, 0, 0),
	array('Ohio', 'Land', 'No', 13, 684, 352, 0, 0),
	array('Okhotsk', 'Sea', 'No', 0, 2214, 223, 0, 0),
	array('Okinawa', 'Coast', 'Yes', 8, 2217, 460, 0, 0),
	array('Oklahoma', 'Land', 'Yes', 0, 586, 386, 0, 0),
	array('Okrana', 'Coast', 'Yes', 0, 1365, 710, 0, 0),
	array('Oliveira', 'Coast', 'Yes', 2, 895, 872, 0, 0),
	array('Oman', 'Coast', 'Yes', 0, 1669, 523, 0, 0),
	array('Omsk', 'Land', 'Yes', 11, 1683, 180, 0, 0),
	array('Ontario', 'Coast', 'No', 3, 732, 267, 0, 0),
	array('Oregon', 'Coast', 'Yes', 13, 461, 313, 0, 0),
	array('Orenburg', 'Coast', 'Yes', 11, 1639, 287, 0, 0),
	array('Pacific Basin', 'Sea', 'No', 0, 532, 797, 0, 0),
	array('Panama', 'Coast', 'Yes', 0, 678, 603, 0, 0),
	array('Panama (North Coast)', 'Coast', 'No', 0, 678, 582, 0, 0),
	array('Panama (South Coast)', 'Coast', 'No', 0, 667, 636, 0, 0),
	array('Paraguay', 'Land', 'Yes', 0, 858, 890, 0, 0),
	array('Paramaribo', 'Coast', 'Yes', 7, 855, 611, 0, 0),
	array('Paris', 'Land', 'Yes', 6, 1289, 286, 0, 0),
	array('Peking', 'Coast', 'Yes', 4, 2074, 374, 0, 0),
	array('Perm', 'Land', 'No', 11, 1602, 149, 0, 0),
	array('Persian Gulf', 'Sea', 'No', 0, 1710, 486, 0, 0),
	array('Perth', 'Coast', 'Yes', 3, 2138, 918, 0, 0),
	array('Philippine', 'Sea', 'No', 0, 2228, 520, 0, 0),
	array('Piedmont', 'Coast', 'Yes', 0, 1323, 301, 0, 0),
	array('Port Arthur', 'Coast', 'Yes', 11, 2126, 379, 0, 0),
	array('Pramaiba', 'Coast', 'No', 2, 871, 694, 0, 0),
	array('Prussia', 'Coast', 'Yes', 10, 1388, 231, 0, 0),
	array('Quebec', 'Coast', 'Yes', 3, 805, 253, 0, 0),
	array('Queensland', 'Coast', 'Yes', 0, 2312, 869, 0, 0),
	array('Quito', 'Coast', 'No', 0, 731, 808, 0, 0),
	array('Rajputana', 'Land', 'No', 0, 1782, 463, 0, 0),
	array('Rangoon', 'Coast', 'Yes', 0, 1949, 498, 0, 0),
	array('Recife', 'Coast', 'Yes', 2, 957, 734, 0, 0),
	array('Red Sea', 'Sea', 'No', 0, 1560, 535, 0, 0),
	array('Rhodesia', 'Land', 'Yes', 0, 1478, 839, 0, 0),
	array('Richmond', 'Coast', 'Yes', 5, 708, 386, 0, 0),
	array('Rio de Janeiro', 'Coast', 'Yes', 2, 945, 816, 0, 0),
	array('Rome', 'Coast', 'Yes', 0, 1354, 321, 0, 0),
	array('Rome (East Coast)', 'Coast', 'No', 0, 1351, 308, 0, 0),
	array('Rome (West Coast)', 'Coast', 'No', 0, 1358, 327, 0, 0),
	array('Rouen', 'Coast', 'No', 6, 1290, 261, 0, 0),
	array('Ruhr', 'Land', 'Yes', 10, 1321, 249, 0, 0),
	array('Rumania', 'Coast', 'Yes', 0, 1475, 317, 0, 0),
	array('Ruperts Land', 'Coast', 'No', 3, 688, 207, 0, 0),
	array('Sakhurlin', 'Coast', 'Yes', 0, 2208, 248, 0, 0),
	array('Salerno', 'Coast', 'Yes', 0, 1398, 361, 0, 0),
	array('San Francisco', 'Coast', 'Yes', 13, 431, 349, 0, 0),
	array('Sapporo', 'Coast', 'Yes', 8, 2256, 310, 0, 0),
	array('Sarawak', 'Coast', 'Yes', 0, 2155, 638, 0, 0),
	array('Sargasso', 'Sea', 'No', 0, 907, 492, 0, 0),
	array('Saskatchewan', 'Land', 'No', 0, 606, 211, 0, 0),
	array('Sea of Japan', 'Sea', 'No', 0, 2193, 351, 0, 0),
	array('Seattle', 'Coast', 'Yes', 0, 505, 291, 0, 0),
	array('Seoul', 'Coast', 'Yes', 0, 2136, 353, 0, 0),
	array('Seoul (East Coast)', 'Coast', 'No', 0, 2160, 340, 0, 0),
	array('Seoul (West Coast)', 'Coast', 'No', 0, 2132, 356, 0, 0),
	array('Serbia', 'Land', 'Yes', 0, 1407, 305, 0, 0),
	array('Sevastopol', 'Coast', 'Yes', 11, 1470, 272, 0, 0),
	array('Seychelles', 'Coast', 'Yes', 0, 1682, 730, 0, 0),
	array('Shanghai', 'Coast', 'Yes', 4, 2107, 436, 0, 0),
	array('Siam', 'Land', 'No', 0, 2020, 536, 0, 0),
	array('Sicily', 'Coast', 'Yes', 0, 1361, 386, 0, 0),
	array('Sierra Leone', 'Coast', 'Yes', 0, 1167, 576, 0, 0),
	array('Silesia', 'Land', 'Yes', 10, 1367, 248, 0, 0),
	array('Singapore', 'Coast', 'Yes', 3, 2058, 674, 0, 0),
	array('Sinkiang', 'Land', 'Yes', 4, 1925, 377, 0, 0),
	array('Skagerrak', 'Sea', 'No', 0, 1302, 198, 0, 0),
	array('Society Islands', 'Coast', 'Yes', 6, 256, 810, 0, 0),
	array('Sofia', 'Coast', 'Yes', 12, 1440, 324, 0, 0),
	array('Sofia (East Coast)', 'Coast', 'No', 12, 1460, 317, 0, 0),
	array('Sofia (South Coast)', 'Coast', 'No', 12, 1438, 337, 0, 0),
	array('Somalia', 'Coast', 'No', 0, 1592, 656, 0, 0),
	array('Sonora', 'Coast', 'No', 9, 478, 445, 0, 0),
	array('South Atlantic', 'Sea', 'No', 0, 1249, 849, 0, 0),
	array('South Australia', 'Coast', 'No', 0, 2234, 948, 0, 0),
	array('South China Sea', 'Sea', 'No', 0, 2088, 537, 0, 0),
	array('South East Trades', 'Sea', 'No', 0, 1940, 860, 0, 0),
	array('South Georgia Islands', 'Coast', 'Yes', 0, 1017, 1123, 0, 0),
	array('South Pacific', 'Sea', 'No', 0, 344, 942, 0, 0),
	array('South West Pacific', 'Sea', 'No', 0, 2541, 965, 0, 0),
	array('St Petersburg', 'Coast', 'Yes', 11, 1471, 165, 0, 0),
	array('St Petersburg (North Coast)', 'Coast', 'No', 11, 1522, 132, 0, 0),
	array('St Petersburg (South Coast)', 'Coast', 'No', 11, 1455, 177, 0, 0),
	array('Straits of Gibraltar', 'Sea', 'No', 0, 1245, 377, 0, 0),
	array('Stuttgart', 'Land', 'Yes', 0, 1332, 253, 0, 0),
	array('Sudan', 'Coast', 'Yes', 0, 1511, 548, 0, 0),
	array('Sumatra', 'Coast', 'Yes', 7, 2024, 695, 0, 0),
	array('Sunda', 'Sea', 'No', 0, 2107, 606, 0, 0),
	array('Sweden', 'Coast', 'Yes', 0, 1369, 169, 0, 0),
	array('Syria', 'Coast', 'No', 12, 1542, 390, 0, 0),
	array('Syria (South Coast)', 'Coast', 'No', 0, 1516, 425, 0, 0),
	array('Syria (West Coast)', 'Coast', 'No', 0, 1523, 386, 0, 0),
	array('Tabrize', 'Coast', 'No', 0, 1612, 393, 0, 0),
	array('Taganet', 'Land', 'No', 0, 1203, 526, 0, 0),
	array('Tampa', 'Sea', 'No', 0, 669, 469, 0, 0),
	array('Tashkent', 'Land', 'Yes', 0, 1799, 280, 0, 0),
	array('Tasman', 'Sea', 'No', 0, 2331, 1035, 0, 0),
	array('Tawarek', 'Land', 'No', 0, 1292, 477, 0, 0),
	array('Tehran', 'Coast', 'Yes', 0, 1645, 396, 0, 0),
	array('Tennessee', 'Land', 'No', 5, 660, 384, 0, 0),
	array('Tibet', 'Land', 'No', 4, 1907, 425, 0, 0),
	array('Timor', 'Sea', 'No', 0, 2207, 773, 0, 0),
	array('Tiris', 'Coast', 'No', 0, 1195, 470, 0, 0),
	array('Toledo', 'Coast', 'No', 0, 1220, 329, 0, 0),
	array('Tonkin', 'Coast', 'Yes', 0, 2029, 508, 0, 0),
	array('Transvaal', 'Coast', 'Yes', 7, 1487, 900, 0, 0),
	array('Tripoli', 'Coast', 'Yes', 0, 1381, 431, 0, 0),
	array('Tubruq', 'Coast', 'No', 0, 1427, 420, 0, 0),
	array('Tunis', 'Coast', 'Yes', 0, 1325, 381, 0, 0),
	array('Tyrrhenian Sea', 'Sea', 'No', 0, 1357, 345, 0, 0),
	array('Unorganized Territories', 'Land', 'No', 0, 599, 303, 0, 0),
	array('Uruguay', 'Coast', 'Yes', 0, 813, 1041, 0, 0),
	array('Utah', 'Land', 'No', 0, 498, 353, 0, 0),
	array('Valencia', 'Coast', 'Yes', 0, 1261, 347, 0, 0),
	array('Vancouver', 'Coast', 'Yes', 3, 495, 240, 0, 0),
	array('Venice', 'Coast', 'Yes', 1, 1363, 289, 0, 0),
	array('Victoria', 'Coast', 'Yes', 0, 438, 255, 0, 0),
	array('Vienna', 'Land', 'Yes', 1, 1378, 267, 0, 0),
	array('Virgin Islands', 'Coast', 'Yes', 0, 814, 541, 0, 0),
	array('Vladivostok', 'Coast', 'Yes', 11, 2141, 263, 0, 0),
	array('Wallacia', 'Land', 'No', 1, 1423, 287, 0, 0),
	array('Warsaw', 'Land', 'Yes', 11, 1434, 237, 0, 0),
	array('Washington DC', 'Coast', 'Yes', 13, 743, 345, 0, 0),
	array('West Bay', 'Sea', 'No', 0, 411, 285, 0, 0),
	array('West Coast', 'Sea', 'No', 0, 411, 450, 0, 0),
	array('West Indian', 'Sea', 'No', 0, 1705, 893, 0, 0),
	array('West Pacific', 'Sea', 'No', 0, 2572, 509, 0, 0),
	array('Westerlies', 'Sea', 'No', 0, 2505, 309, 0, 0),
	array('Western Carribean', 'Sea', 'No', 0, 664, 522, 0, 0),
	array('Western Mediterranean', 'Sea', 'No', 0, 1304, 353, 0, 0),
	array('Wuhan', 'Land', 'Yes', 4, 2046, 416, 0, 0),
	array('Yakutsk', 'Land', 'No', 11, 2049, 163, 0, 0),
	array('Yellow Sea', 'Sea', 'No', 0, 2164, 420, 0, 0),
	array('Yukon', 'Land', 'Yes', 0, 520, 166, 0, 0),
	array('Yunnan', 'Land', 'No', 4, 2009, 478, 0, 0),
	array('Yuthia', 'Land', 'Yes', 0, 1996, 536, 0, 0)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Abyssinia','Dar Es Sallam','No','Yes'),
	array('Abyssinia','Gall Land','No','Yes'),
	array('Abyssinia','Red Sea','Yes','No'),
	array('Abyssinia','Somalia','Yes','Yes'),
	array('Abyssinia','Sudan','Yes','Yes'),
	array('Aden','Hadramaut','No','Yes'),
	array('Aden','Hadramaut (South Coast)','Yes','No'),
	array('Aden','Horn of Africa','Yes','No'),
	array('Aden','Mecca','Yes','Yes'),
	array('Aden','Nejaaz','No','Yes'),
	array('Aden','Red Sea','Yes','No'),
	array('Adriatic Sea','Bosnia (West Coast)','Yes','No'),
	array('Adriatic Sea','Croatia','Yes','No'),
	array('Adriatic Sea','Greece','Yes','No'),
	array('Adriatic Sea','Ionian Sea','Yes','No'),
	array('Adriatic Sea','Rome (East Coast)','Yes','No'),
	array('Adriatic Sea','Salerno','Yes','No'),
	array('Adriatic Sea','Sicily','Yes','No'),
	array('Adriatic Sea','Tyrrhenian Sea','Yes','No'),
	array('Adriatic Sea','Venice','Yes','No'),
	array('Aegean Sea','Black Sea','Yes','No'),
	array('Aegean Sea','Bosnia (East Coast)','Yes','No'),
	array('Aegean Sea','Constantinople','Yes','No'),
	array('Aegean Sea','Crete','Yes','No'),
	array('Aegean Sea','Eastern Mediterranean','Yes','No'),
	array('Aegean Sea','Greece','Yes','No'),
	array('Aegean Sea','Ionian Sea','Yes','No'),
	array('Aegean Sea','Sofia (South Coast)','Yes','No'),
	array('Afganistan','Bangalore','No','Yes'),
	array('Afganistan','Bokhara','No','Yes'),
	array('Afganistan','Karachi','No','Yes'),
	array('Afganistan','Khiva','No','Yes'),
	array('Afganistan','Tehran','No','Yes'),
	array('Alaska','Anchorage','No','Yes'),
	array('Alaska','British Columbia','No','Yes'),
	array('Alaska','Vancouver','No','Yes'),
	array('Alaska','Yukon','No','Yes'),
	array('Alaska (North Coast)','Anchorage','Yes','No'),
	array('Alaska (North Coast)','Bering Sea','Yes','No'),
	array('Alaska (South Coast)','Anchorage','Yes','No'),
	array('Alaska (South Coast)','Gulf of Alaska','Yes','No'),
	array('Alaska (South Coast)','Vancouver','Yes','No'),
	array('Alberta','British Columbia','No','Yes'),
	array('Alberta','Nebraska','No','Yes'),
	array('Alberta','Northwest Territories','No','Yes'),
	array('Alberta','Saskatchewan','No','Yes'),
	array('Alberta','Yukon','No','Yes'),
	array('Algeria','Morocco','Yes','Yes'),
	array('Algeria','Tawarek','No','Yes'),
	array('Algeria','Tripoli','No','Yes'),
	array('Algeria','Tunis','Yes','Yes'),
	array('Algeria','Western Mediterranean','Yes','No'),
	array('Amazon','Barcelone','No','Yes'),
	array('Amazon','Brasilia','No','Yes'),
	array('Amazon','Caledonia','No','Yes'),
	array('Amazon','La Paz','No','Yes'),
	array('Amazon','Lima','No','Yes'),
	array('Amazon','Mitu','No','Yes'),
	array('Amazon','Pramaiba','No','Yes'),
	array('Amazon','Quito','No','Yes'),
	array('Anchorage','Bering Sea','Yes','No'),
	array('Anchorage','Gulf of Alaska','Yes','No'),
	array('Anchorage','North Pacific','Yes','No'),
	array('Andaman Islands','Andaman Sea','Yes','No'),
	array('Andaman Islands','Bay of Bengal','Yes','No'),
	array('Andaman Islands','East Indian','Yes','No'),
	array('Andaman Islands','Gulf of Manaar','Yes','No'),
	array('Andaman Sea','Bangkok (West Coast)','Yes','No'),
	array('Andaman Sea','Bay of Bengal','Yes','No'),
	array('Andaman Sea','East Indian','Yes','No'),
	array('Andaman Sea','Java Sea','Yes','No'),
	array('Andaman Sea','Malaysia','Yes','No'),
	array('Andaman Sea','Rangoon','Yes','No'),
	array('Andaman Sea','Sumatra','Yes','No'),
	array('Angola','Botswana','No','Yes'),
	array('Angola','Congo','No','Yes'),
	array('Angola','Damaraland','Yes','Yes'),
	array('Angola','Okrana','Yes','Yes'),
	array('Angola','Rhodesia','No','Yes'),
	array('Angola','South Atlantic','Yes','No'),
	array('Angora','Armenia','No','Yes'),
	array('Angora','Baku','No','Yes'),
	array('Angora','Constantinople','No','Yes'),
	array('Angora','Cyprus','No','Yes'),
	array('Angora','Syria','No','Yes'),
	array('Angora (North Coast)','Baku (West Coast)','Yes','No'),
	array('Angora (North Coast)','Black Sea','Yes','No'),
	array('Angora (North Coast)','Constantinople','Yes','No'),
	array('Angora (South Coast)','Constantinople','Yes','No'),
	array('Angora (South Coast)','Cyprus','Yes','No'),
	array('Angora (South Coast)','Eastern Mediterranean','Yes','No'),
	array('Angora (South Coast)','Syria (West Coast)','Yes','No'),
	array('Annam','Cambodia','No','Yes'),
	array('Annam','Cochin','Yes','Yes'),
	array('Annam','Siam','No','Yes'),
	array('Annam','South China Sea','Yes','No'),
	array('Annam','Tonkin','Yes','Yes'),
	array('Antarctic Atlantic','Antarctic Indian','Yes','No'),
	array('Antarctic Atlantic','Brazil Current','Yes','No'),
	array('Antarctic Atlantic','Drake','Yes','No'),
	array('Antarctic Atlantic','Goodhope','Yes','No'),
	array('Antarctic Atlantic','South Atlantic','Yes','No'),
	array('Antarctic Atlantic','South Georgia Islands','Yes','No'),
	array('Antarctic Indian','Antarctic Pacific','Yes','No'),
	array('Antarctic Indian','Barrier','Yes','No'),
	array('Antarctic Indian','Goodhope','Yes','No'),
	array('Antarctic Indian','South East Trades','Yes','No'),
	array('Antarctic Indian','West Indian','Yes','No'),
	array('Antarctic Pacific','Barrier','Yes','No'),
	array('Antarctic Pacific','Chilean Basin','Yes','No'),
	array('Antarctic Pacific','Drake','Yes','No'),
	array('Antarctic Pacific','New Zealand','Yes','No'),
	array('Antarctic Pacific','South Pacific','Yes','No'),
	array('Antarctic Pacific','South West Pacific','Yes','No'),
	array('Antarctic Pacific','Tasman','Yes','No'),
	array('Arabian','Bombay','Yes','No'),
	array('Arabian','East Indian','Yes','No'),
	array('Arabian','Gujarat','Yes','No'),
	array('Arabian','Gulf of Manaar','Yes','No'),
	array('Arabian','Hadramaut (South Coast)','Yes','No'),
	array('Arabian','Horn of Africa','Yes','No'),
	array('Arabian','Karachi','Yes','No'),
	array('Arabian','Madras','Yes','No'),
	array('Arabian','Maldives','Yes','No'),
	array('Arabian','North East Monsoon','Yes','No'),
	array('Arabian','Oman','Yes','No'),
	array('Arabian','Persian Gulf','Yes','No'),
	array('Armenia','Baghdad','No','Yes'),
	array('Armenia','Baku','No','Yes'),
	array('Armenia','Syria','No','Yes'),
	array('Armenia','Tabrize','No','Yes'),
	array('Ashanti','Cameroon','No','Yes'),
	array('Ashanti','Denkyera','No','Yes'),
	array('Ashanti','Mandingoes','No','Yes'),
	array('Assam','Bengal','No','Yes'),
	array('Assam','Burma','No','Yes'),
	array('Assam','Rangoon','No','Yes'),
	array('Assam','Tibet','No','Yes'),
	array('Assam','Yunnan','No','Yes'),
	array('Aswan','Cairo','No','Yes'),
	array('Aswan','Cairo (East Coast)','Yes','No'),
	array('Aswan','Dar Es Sallam','No','Yes'),
	array('Aswan','Fezz','No','Yes'),
	array('Aswan','Red Sea','Yes','No'),
	array('Aswan','Sudan','Yes','Yes'),
	array('Atlanta','Bahamas','Yes','Yes'),
	array('Atlanta','Eastern Seaboard','Yes','No'),
	array('Atlanta','New Orleans','Yes','Yes'),
	array('Atlanta','Richmond','Yes','Yes'),
	array('Atlanta','Tampa','Yes','No'),
	array('Atlanta','Tennessee','No','Yes'),
	array('Austin','Chihuahua','No','Yes'),
	array('Austin','Coahula','Yes','Yes'),
	array('Austin','Gulf of Mexico','Yes','No'),
	array('Austin','New Mexico','No','Yes'),
	array('Austin','New Orleans','Yes','Yes'),
	array('Austin','Oklahoma','No','Yes'),
	array('Azores','Bay of Biscay','Yes','No'),
	array('Azores','Canary','Yes','No'),
	array('Azores','North Atlantic','Yes','No'),
	array('Baghdad','Bangalore','Yes','Yes'),
	array('Baghdad','Hadramaut','No','Yes'),
	array('Baghdad','Hadramaut (North Coast)','Yes','No'),
	array('Baghdad','Nejaaz','No','Yes'),
	array('Baghdad','Persian Gulf','Yes','No'),
	array('Baghdad','Syria','No','Yes'),
	array('Baghdad','Tabrize','No','Yes'),
	array('Bahamas','Cuba','Yes','Yes'),
	array('Bahamas','Eastern Seaboard','Yes','No'),
	array('Bahamas','Sargasso','Yes','No'),
	array('Bahamas','Tampa','Yes','No'),
	array('Baku','Georgia','No','Yes'),
	array('Baku','Tabrize','No','Yes'),
	array('Baku (East Coast)','Caspian Sea','Yes','No'),
	array('Baku (East Coast)','Georgia (East Coast)','Yes','No'),
	array('Baku (East Coast)','Tabrize','Yes','No'),
	array('Baku (West Coast)','Black Sea','Yes','No'),
	array('Baku (West Coast)','Georgia (West Coast)','Yes','No'),
	array('Baltic Sea','Berlin','Yes','No'),
	array('Baltic Sea','Denmark','Yes','No'),
	array('Baltic Sea','Gulf of Bothnia','Yes','No'),
	array('Baltic Sea','Kiel (East Coast)','Yes','No'),
	array('Baltic Sea','Livonia','Yes','No'),
	array('Baltic Sea','Prussia','Yes','No'),
	array('Baltic Sea','Skagerrak','Yes','No'),
	array('Baltic Sea','Sweden','Yes','No'),
	array('Bangalore','Karachi','Yes','Yes'),
	array('Bangalore','Persian Gulf','Yes','No'),
	array('Bangalore','Tabrize','No','Yes'),
	array('Bangalore','Tehran','No','Yes'),
	array('Bangkok','Cambodia','No','Yes'),
	array('Bangkok','Malaysia','No','Yes'),
	array('Bangkok','Rangoon','No','Yes'),
	array('Bangkok','Siam','No','Yes'),
	array('Bangkok','Yuthia','No','Yes'),
	array('Bangkok (East Coast)','Cambodia','Yes','No'),
	array('Bangkok (East Coast)','Gulf of Siam','Yes','No'),
	array('Bangkok (East Coast)','Malaysia','Yes','No'),
	array('Bangkok (West Coast)','Malaysia','Yes','No'),
	array('Bangkok (West Coast)','Rangoon','Yes','No'),
	array('Barcelone','Bogota','No','Yes'),
	array('Barcelone','Calabozo','Yes','Yes'),
	array('Barcelone','Caledonia','No','Yes'),
	array('Barcelone','Mitu','No','Yes'),
	array('Barents Sea','Finland (North Coast)','Yes','No'),
	array('Barents Sea','Greenland','Yes','No'),
	array('Barents Sea','Iceland','Yes','No'),
	array('Barents Sea','North Passage','Yes','No'),
	array('Barents Sea','Norway','Yes','No'),
	array('Barents Sea','Norwegian Sea','Yes','No'),
	array('Barents Sea','St Petersburg (North Coast)','Yes','No'),
	array('Barrier','New South Wales','Yes','No'),
	array('Barrier','Perth','Yes','No'),
	array('Barrier','South Australia','Yes','No'),
	array('Barrier','South East Trades','Yes','No'),
	array('Barrier','Tasman','Yes','No'),
	array('Bavaria','Berlin','No','Yes'),
	array('Bavaria','Silesia','No','Yes'),
	array('Bavaria','Stuttgart','No','Yes'),
	array('Bavaria','Venice','No','Yes'),
	array('Bavaria','Vienna','No','Yes'),
	array('Bay of Bengal','Bengal','Yes','No'),
	array('Bay of Bengal','Gulf of Manaar','Yes','No'),
	array('Bay of Bengal','Hyderabad','Yes','No'),
	array('Bay of Bengal','Rangoon','Yes','No'),
	array('Bay of Biscay','Bordeaux','Yes','No'),
	array('Bay of Biscay','Canary','Yes','No'),
	array('Bay of Biscay','Nantes','Yes','No'),
	array('Bay of Biscay','North Atlantic','Yes','No'),
	array('Bay of Biscay','Straits of Gibraltar','Yes','No'),
	array('Bay of Biscay','Toledo','Yes','No'),
	array('Bengal','Hyderabad','Yes','Yes'),
	array('Bengal','Lucknow','No','Yes'),
	array('Bengal','Rangoon','Yes','Yes'),
	array('Bengal','Tibet','No','Yes'),
	array('Bering Sea','Kamchatka','Yes','No'),
	array('Bering Sea','Kuril','Yes','No'),
	array('Bering Sea','North Pacific','Yes','No'),
	array('Bering Sea','Westerlies','Yes','No'),
	array('Berlin','Kiel','No','Yes'),
	array('Berlin','Kiel (East Coast)','Yes','No'),
	array('Berlin','Prussia','Yes','Yes'),
	array('Berlin','Silesia','No','Yes'),
	array('Berlin','Stuttgart','No','Yes'),
	array('Bismark','Caroline Islands','Yes','No'),
	array('Bismark','Celebes Sea','Yes','No'),
	array('Bismark','Coral','Yes','No'),
	array('Bismark','Equatorial CounterCurrent','Yes','No'),
	array('Bismark','Irian Java','Yes','No'),
	array('Bismark','Izu Trench','Yes','No'),
	array('Bismark','Luzon','Yes','No'),
	array('Bismark','Marshal Islands','Yes','No'),
	array('Bismark','Mindanao','Yes','No'),
	array('Bismark','New Guinea','Yes','No'),
	array('Bismark','Philippine','Yes','No'),
	array('Bismark','West Pacific','Yes','No'),
	array('Black Sea','Constantinople','Yes','No'),
	array('Black Sea','Georgia (West Coast)','Yes','No'),
	array('Black Sea','Rumania','Yes','No'),
	array('Black Sea','Sevastopol','Yes','No'),
	array('Black Sea','Sofia (East Coast)','Yes','No'),
	array('Bogota','Calabozo','No','Yes'),
	array('Bogota','Lima','No','Yes'),
	array('Bogota','Mitu','No','Yes'),
	array('Bogota','Panama','No','Yes'),
	array('Bogota (North Coast)','Calabozo','Yes','No'),
	array('Bogota (North Coast)','Eastern Carribean','Yes','No'),
	array('Bogota (North Coast)','Panama (North Coast)','Yes','No'),
	array('Bogota (North Coast)','Western Carribean','Yes','No'),
	array('Bogota (South Coast)','Gulf of Panama','Yes','No'),
	array('Bogota (South Coast)','Lima','Yes','No'),
	array('Bogota (South Coast)','Panama (South Coast)','Yes','No'),
	array('Bokhara','Karachi','No','Yes'),
	array('Bokhara','Kasala','No','Yes'),
	array('Bokhara','Kashgar','No','Yes'),
	array('Bokhara','Khiva','No','Yes'),
	array('Bokhara','Kirghiz','No','Yes'),
	array('Bokhara','Orenburg','No','Yes'),
	array('Bokhara','Tashkent','No','Yes'),
	array('Bombay','Gujarat','Yes','Yes'),
	array('Bombay','Hyderabad','No','Yes'),
	array('Bombay','Madras','Yes','Yes'),
	array('Bombay','Mandlah','No','Yes'),
	array('Bordeaux','Marseilles','No','Yes'),
	array('Bordeaux','Nantes','Yes','Yes'),
	array('Bordeaux','Paris','No','Yes'),
	array('Bordeaux','Toledo','Yes','Yes'),
	array('Bordeaux','Valencia','No','Yes'),
	array('Borneo','Celebes Sea','Yes','No'),
	array('Borneo','Java Sea','Yes','No'),
	array('Borneo','Sarawak','Yes','Yes'),
	array('Bosnia','Croatia','No','Yes'),
	array('Bosnia','Greece','No','Yes'),
	array('Bosnia','Rumania','No','Yes'),
	array('Bosnia','Serbia','No','Yes'),
	array('Bosnia','Sofia','No','Yes'),
	array('Bosnia (East Coast)','Greece','Yes','No'),
	array('Bosnia (East Coast)','Sofia (South Coast)','Yes','No'),
	array('Bosnia (West Coast)','Croatia','Yes','No'),
	array('Bosnia (West Coast)','Greece','Yes','No'),
	array('Botswana','Cape Town','No','Yes'),
	array('Botswana','Damaraland','No','Yes'),
	array('Botswana','Mozambique','No','Yes'),
	array('Botswana','Rhodesia','No','Yes'),
	array('Botswana','Transvaal','No','Yes'),
	array('Brasilia','Cochabamba','No','Yes'),
	array('Brasilia','La Paz','No','Yes'),
	array('Brasilia','Oliveira','No','Yes'),
	array('Brasilia','Pramaiba','No','Yes'),
	array('Brasilia','Recife','No','Yes'),
	array('Brasilia','Rio de Janeiro','No','Yes'),
	array('Brazil Current','Coast of Argentina','Yes','No'),
	array('Brazil Current','Drake','Yes','No'),
	array('Brazil Current','Falkland Islands','Yes','No'),
	array('Brazil Current','Middle Atlantic','Yes','No'),
	array('Brazil Current','Recife','Yes','No'),
	array('Brazil Current','Rio de Janeiro','Yes','No'),
	array('Brazil Current','South Atlantic','Yes','No'),
	array('Brazil Current','South Georgia Islands','Yes','No'),
	array('British Columbia','Vancouver','No','Yes'),
	array('British Columbia','Yukon','No','Yes'),
	array('Budapest','Croatia','No','Yes'),
	array('Budapest','Galicia','No','Yes'),
	array('Budapest','Venice','No','Yes'),
	array('Budapest','Vienna','No','Yes'),
	array('Budapest','Wallacia','No','Yes'),
	array('Burma','Mandalay','No','Yes'),
	array('Burma','Rangoon','No','Yes'),
	array('Burma','Yunnan','No','Yes'),
	array('Cairo','Fezz','No','Yes'),
	array('Cairo','Syria','No','Yes'),
	array('Cairo','Tubruq','No','Yes'),
	array('Cairo (East Coast)','Red Sea','Yes','No'),
	array('Cairo (East Coast)','Syria (South Coast)','Yes','No'),
	array('Cairo (North Coast)','Eastern Mediterranean','Yes','No'),
	array('Cairo (North Coast)','Syria (West Coast)','Yes','No'),
	array('Cairo (North Coast)','Tubruq','Yes','No'),
	array('Calabozo','Caledonia','Yes','Yes'),
	array('Calabozo','Eastern Carribean','Yes','No'),
	array('Caledonia','Eastern Carribean','Yes','No'),
	array('Caledonia','Paramaribo','Yes','Yes'),
	array('Caledonia','Pramaiba','No','Yes'),
	array('Cambodia','Cochin','Yes','Yes'),
	array('Cambodia','Gulf of Siam','Yes','No'),
	array('Cambodia','Siam','No','Yes'),
	array('Cameroon','Denkyera','Yes','Yes'),
	array('Cameroon','Gulf of Guinea','Yes','No'),
	array('Cameroon','Okrana','Yes','Yes'),
	array('Canary','Cape Verde Islands','Yes','No'),
	array('Canary','Middle Atlantic','Yes','No'),
	array('Canary','Morocco','Yes','No'),
	array('Canary','North Atlantic','Yes','No'),
	array('Canary','Sargasso','Yes','No'),
	array('Canary','Straits of Gibraltar','Yes','No'),
	array('Canary','Tiris','Yes','No'),
	array('Canton','Fuchan','No','Yes'),
	array('Canton','Hong Kong','Yes','Yes'),
	array('Canton','South China Sea','Yes','No'),
	array('Canton','Tonkin','Yes','Yes'),
	array('Canton','Wuhan','No','Yes'),
	array('Canton','Yunnan','No','Yes'),
	array('Cape Town','Damaraland','Yes','Yes'),
	array('Cape Town','Goodhope','Yes','No'),
	array('Cape Town','South Atlantic','Yes','No'),
	array('Cape Town','Transvaal','Yes','Yes'),
	array('Cape Verde Islands','Middle Atlantic','Yes','No'),
	array('Cape Verde Islands','Sargasso','Yes','No'),
	array('Caroline Islands','Izu Trench','Yes','No'),
	array('Caroline Islands','Philippine','Yes','No'),
	array('Caspian Sea','Georgia (East Coast)','Yes','No'),
	array('Caspian Sea','Khiva','Yes','No'),
	array('Caspian Sea','Orenburg','Yes','No'),
	array('Caspian Sea','Tabrize','Yes','No'),
	array('Caspian Sea','Tehran','Yes','No'),
	array('Cayenne','North East Trades','Yes','No'),
	array('Cayenne','Paramaribo','Yes','Yes'),
	array('Cayenne','Pramaiba','Yes','Yes'),
	array('Celebes Sea','Celebes','Yes','No'),
	array('Celebes Sea','Irian Java','Yes','No'),
	array('Celebes Sea','Java Sea','Yes','No'),
	array('Celebes Sea','Mindanao','Yes','No'),
	array('Celebes Sea','Sarawak','Yes','No'),
	array('Celebes Sea','Sunda','Yes','No'),
	array('Celebes Sea','Timor','Yes','No'),
	array('Celebes','Java Sea','Yes','No'),
	array('Celebes','Timor','Yes','No'),
	array('Ceylon','East Indian','Yes','No'),
	array('Ceylon','Gulf of Manaar','Yes','No'),
	array('Chesapeake','Eastern Seaboard','Yes','No'),
	array('Chesapeake','Hudson','Yes','No'),
	array('Chesapeake','New York','Yes','No'),
	array('Chesapeake','North Atlantic','Yes','No'),
	array('Chesapeake','Nova Scotia','Yes','No'),
	array('Chesapeake','Quebec','Yes','No'),
	array('Chesapeake','Richmond','Yes','No'),
	array('Chesapeake','Washington DC','Yes','No'),
	array('Chicago','Kansas','No','Yes'),
	array('Chicago','Minnesota','No','Yes'),
	array('Chicago','Nebraska','No','Yes'),
	array('Chicago','New Orleans','No','Yes'),
	array('Chicago','Ohio','No','Yes'),
	array('Chicago','Oklahoma','No','Yes'),
	array('Chicago','Tennessee','No','Yes'),
	array('Chicago','Unorganized Territories','No','Yes'),
	array('Chihuahua','Coahula','No','Yes'),
	array('Chihuahua','Mazatlan','No','Yes'),
	array('Chihuahua','New Mexico','No','Yes'),
	array('Chihuahua','Sonora','No','Yes'),
	array('Chilean Basin','Drake','Yes','No'),
	array('Chilean Basin','Pacific Basin','Yes','No'),
	array('Chilean Basin','Quito','Yes','No'),
	array('Chilean Basin','South Pacific','Yes','No'),
	array('Chungking','Langchow','No','Yes'),
	array('Chungking','Sinkiang','No','Yes'),
	array('Chungking','Wuhan','No','Yes'),
	array('Chungking','Yunnan','No','Yes'),
	array('Coahula','Gulf of Mexico','Yes','No'),
	array('Coahula','Mazatlan','No','Yes'),
	array('Coahula','Mexico City','Yes','Yes'),
	array('Coast of Argentina','Drake','Yes','No'),
	array('Coast of Argentina','Falkland Islands','Yes','No'),
	array('Coast of Argentina','Oliveira','Yes','No'),
	array('Coast of Argentina','Rio de Janeiro','Yes','No'),
	array('Coast of Argentina','Uruguay','Yes','No'),
	array('Cochabamba','Goyamas','No','Yes'),
	array('Cochabamba','La Paz','No','Yes'),
	array('Cochabamba','Oliveira','No','Yes'),
	array('Cochabamba','Paraguay','No','Yes'),
	array('Cochin','Gulf of Siam','Yes','No'),
	array('Cochin','South China Sea','Yes','No'),
	array('Congo','Kenya','No','Yes'),
	array('Congo','Mozambique','No','Yes'),
	array('Congo','Okrana','No','Yes'),
	array('Congo','Rhodesia','No','Yes'),
	array('Constantinople','Eastern Mediterranean','Yes','No'),
	array('Constantinople','Sofia','No','Yes'),
	array('Constantinople','Sofia (East Coast)','Yes','No'),
	array('Constantinople','Sofia (South Coast)','Yes','No'),
	array('Coral','Equatorial CounterCurrent','Yes','No'),
	array('Coral','Fiji','Yes','No'),
	array('Coral','New Guinea','Yes','No'),
	array('Coral','New Zealand','Yes','No'),
	array('Coral','Queensland','Yes','No'),
	array('Coral','South West Pacific','Yes','No'),
	array('Coral','Tasman','Yes','No'),
	array('Coral','Timor','Yes','No'),
	array('Corsica','Gulf of Lyon','Yes','No'),
	array('Corsica','Tyrrhenian Sea','Yes','No'),
	array('Corsica','Western Mediterranean','Yes','No'),
	array('Counter Current','Eastern Pacific','Yes','No'),
	array('Counter Current','Hawaii','Yes','No'),
	array('Counter Current','North Pacific','Yes','No'),
	array('Counter Current','West Coast','Yes','No'),
	array('Crete','Eastern Mediterranean','Yes','No'),
	array('Crete','Ionian Sea','Yes','No'),
	array('Croatia','Serbia','No','Yes'),
	array('Croatia','Venice','Yes','Yes'),
	array('Croatia','Wallacia','No','Yes'),
	array('Cuba','Gulf of Mexico','Yes','No'),
	array('Cuba','Haiti','Yes','Yes'),
	array('Cuba','Sargasso','Yes','No'),
	array('Cuba','Tampa','Yes','No'),
	array('Cuba','Western Carribean','Yes','No'),
	array('Cyprus','Eastern Mediterranean','Yes','No'),
	array('Cyprus','Syria','No','Yes'),
	array('Cyprus','Syria (West Coast)','Yes','No'),
	array('Damaraland','South Atlantic','Yes','No'),
	array('Dar Es Sallam','Fezz','No','Yes'),
	array('Dar Es Sallam','Gall Land','No','Yes'),
	array('Dar Es Sallam','Kenya','No','Yes'),
	array('Dar Es Sallam','Sudan','No','Yes'),
	array('Delhi','Kashmir','No','Yes'),
	array('Delhi','Lucknow','No','Yes'),
	array('Delhi','Mandlah','No','Yes'),
	array('Delhi','Rajputana','No','Yes'),
	array('Denkyera','Gulf of Guinea','Yes','No'),
	array('Denkyera','Ivory Coast','Yes','Yes'),
	array('Denkyera','Mandingoes','No','Yes'),
	array('Denmark','Helgoland Bight','Yes','No'),
	array('Denmark','Kiel','No','Yes'),
	array('Denmark','Kiel (East Coast)','Yes','No'),
	array('Denmark','Kiel (West Coast)','Yes','No'),
	array('Denmark','North Sea','Yes','No'),
	array('Denmark','Norway','Yes','Yes'),
	array('Denmark','Skagerrak','Yes','No'),
	array('Denmark','Sweden','Yes','Yes'),
	array('Detroit','Minnesota','No','Yes'),
	array('Detroit','Ohio','No','Yes'),
	array('Detroit','Ontario','No','Yes'),
	array('Drake','Falkland Islands','Yes','No'),
	array('Drake','Uruguay','Yes','No'),
	array('Dublin','Edinburgh','Yes','Yes'),
	array('Dublin','North Atlantic','Yes','No'),
	array('Dublin','North Passage','Yes','No'),
	array('East China Sea','Formosa','Yes','No'),
	array('East China Sea','Fuchan','Yes','No'),
	array('East China Sea','Hong Kong','Yes','No'),
	array('East China Sea','Okinawa','Yes','No'),
	array('East China Sea','Philippine','Yes','No'),
	array('East China Sea','Shanghai','Yes','No'),
	array('East China Sea','South China Sea','Yes','No'),
	array('East China Sea','Yellow Sea','Yes','No'),
	array('East Indian','Gulf of Manaar','Yes','No'),
	array('East Indian','Maldives','Yes','No'),
	array('East Indian','North East Monsoon','Yes','No'),
	array('East Indian','South East Trades','Yes','No'),
	array('East Indian','Sumatra','Yes','No'),
	array('Eastern Carribean','Haiti','Yes','No'),
	array('Eastern Carribean','North East Trades','Yes','No'),
	array('Eastern Carribean','Paramaribo','Yes','No'),
	array('Eastern Carribean','Sargasso','Yes','No'),
	array('Eastern Carribean','Virgin Islands','Yes','No'),
	array('Eastern Carribean','Western Carribean','Yes','No'),
	array('Eastern Mediterranean','Ionian Sea','Yes','No'),
	array('Eastern Mediterranean','Syria (West Coast)','Yes','No'),
	array('Eastern Mediterranean','Tubruq','Yes','No'),
	array('Eastern Pacific','Galapagos','Yes','No'),
	array('Eastern Pacific','Gulf of California','Yes','No'),
	array('Eastern Pacific','Gulf of Panama','Yes','No'),
	array('Eastern Pacific','Hawaii','Yes','No'),
	array('Eastern Pacific','Kirbati Sea','Yes','No'),
	array('Eastern Pacific','Pacific Basin','Yes','No'),
	array('Eastern Pacific','West Coast','Yes','No'),
	array('Eastern Seaboard','North Atlantic','Yes','No'),
	array('Eastern Seaboard','Richmond','Yes','No'),
	array('Eastern Seaboard','Sargasso','Yes','No'),
	array('Edinburgh','London','Yes','Yes'),
	array('Edinburgh','North Passage','Yes','No'),
	array('Edinburgh','North Sea','Yes','No'),
	array('Edinburgh','Norwegian Sea','Yes','No'),
	array('Edo','Izu Trench','Yes','No'),
	array('Edo','Kagoshima','Yes','Yes'),
	array('Edo','Kuril','Yes','No'),
	array('Edo','Sapporo','Yes','Yes'),
	array('Edo','Sea of Japan','Yes','No'),
	array('El Jouf','Mandingoes','No','Yes'),
	array('El Jouf','Taganet','No','Yes'),
	array('El Jouf','Tawarek','No','Yes'),
	array('El Jouf','Tiris','No','Yes'),
	array('Equatorial CounterCurrent','Fiji','Yes','No'),
	array('Equatorial CounterCurrent','Hawaii','Yes','No'),
	array('Equatorial CounterCurrent','Kirbati Sea','Yes','No'),
	array('Equatorial CounterCurrent','Marshal Islands','Yes','No'),
	array('Equatorial CounterCurrent','South West Pacific','Yes','No'),
	array('Equatorial CounterCurrent','West Pacific','Yes','No'),
	array('Evenki','Irkutsk','No','Yes'),
	array('Evenki','Krasnoyarsk','No','Yes'),
	array('Evenki','Omsk','No','Yes'),
	array('Evenki','Yakutsk','No','Yes'),
	array('Fezz','Tawarek','No','Yes'),
	array('Fezz','Tripoli','No','Yes'),
	array('Fezz','Tubruq','No','Yes'),
	array('Fiji','South West Pacific','Yes','No'),
	array('Finland','Norway','No','Yes'),
	array('Finland','St Petersburg','No','Yes'),
	array('Finland','Sweden','No','Yes'),
	array('Finland (North Coast)','Norway','Yes','No'),
	array('Finland (North Coast)','St Petersburg (North Coast)','Yes','No'),
	array('Finland (South Coast)','Gulf of Bothnia','Yes','No'),
	array('Finland (South Coast)','St Petersburg (South Coast)','Yes','No'),
	array('Finland (South Coast)','Sweden','Yes','No'),
	array('Formosa','Philippine','Yes','No'),
	array('Formosa','South China Sea','Yes','No'),
	array('Fuchan','Hong Kong','Yes','Yes'),
	array('Fuchan','Shanghai','Yes','Yes'),
	array('Fuchan','Wuhan','No','Yes'),
	array('Fusan','Sea of Japan','Yes','No'),
	array('Fusan','Seoul','No','Yes'),
	array('Fusan','Seoul (East Coast)','Yes','No'),
	array('Fusan','Seoul (West Coast)','Yes','No'),
	array('Fusan','Yellow Sea','Yes','No'),
	array('Galapagos','Gulf of Panama','Yes','No'),
	array('Galapagos','Pacific Basin','Yes','No'),
	array('Galicia','Rumania','No','Yes'),
	array('Galicia','Sevastopol','No','Yes'),
	array('Galicia','Silesia','No','Yes'),
	array('Galicia','Vienna','No','Yes'),
	array('Galicia','Wallacia','No','Yes'),
	array('Galicia','Warsaw','No','Yes'),
	array('Gall Land','Kenya','No','Yes'),
	array('Gall Land','Somalia','No','Yes'),
	array('Georgia','Moscow','No','Yes'),
	array('Georgia','Omsk','No','Yes'),
	array('Georgia','Orenburg','No','Yes'),
	array('Georgia','Perm','No','Yes'),
	array('Georgia','Sevastopol','No','Yes'),
	array('Georgia (East Coast)','Orenburg','Yes','No'),
	array('Georgia (West Coast)','Sevastopol','Yes','No'),
	array('Gibraltar','Morocco','Yes','Yes'),
	array('Gibraltar','Straits of Gibraltar','Yes','No'),
	array('Gibraltar','Toledo','Yes','Yes'),
	array('Gibraltar','Valencia','Yes','Yes'),
	array('Goodhope','Madagascar','Yes','No'),
	array('Goodhope','Malagasy Channel','Yes','No'),
	array('Goodhope','South Atlantic','Yes','No'),
	array('Goodhope','Transvaal','Yes','No'),
	array('Goodhope','West Indian','Yes','No'),
	array('Goyamas','La Paz','No','Yes'),
	array('Goyamas','Oliveira','No','Yes'),
	array('Goyamas','Paraguay','No','Yes'),
	array('Goyamas','Uruguay','No','Yes'),
	array('Grain Coast','Gulf of Guinea','Yes','No'),
	array('Grain Coast','Ivory Coast','Yes','Yes'),
	array('Grain Coast','Mandingoes','No','Yes'),
	array('Grain Coast','Middle Atlantic','Yes','No'),
	array('Grain Coast','Monrovia','Yes','Yes'),
	array('Greece','Ionian Sea','Yes','No'),
	array('Greenland','Hudson','Yes','No'),
	array('Greenland','North Passage','Yes','No'),
	array('Guatemala','Honduras','No','Yes'),
	array('Guatemala','Merida','No','Yes'),
	array('Guatemala','Oaxaca','No','Yes'),
	array('Guatemala (East Coast)','Honduras (East Coast)','Yes','No'),
	array('Guatemala (East Coast)','Merida','Yes','No'),
	array('Guatemala (East Coast)','Western Carribean','Yes','No'),
	array('Guatemala (West Coast)','Gulf of California','Yes','No'),
	array('Guatemala (West Coast)','Honduras (West Coast)','Yes','No'),
	array('Guatemala (West Coast)','Oaxaca','Yes','No'),
	array('Gujarat','Karachi','Yes','Yes'),
	array('Gujarat','Mandlah','No','Yes'),
	array('Gujarat','Rajputana','No','Yes'),
	array('Gulf of Alaska','North Pacific','Yes','No'),
	array('Gulf of Alaska','Vancouver','Yes','No'),
	array('Gulf of Alaska','Victoria','Yes','No'),
	array('Gulf of Alaska','West Bay','Yes','No'),
	array('Gulf of Bothnia','Livonia','Yes','No'),
	array('Gulf of Bothnia','St Petersburg (South Coast)','Yes','No'),
	array('Gulf of Bothnia','Sweden','Yes','No'),
	array('Gulf of California','Gulf of Panama','Yes','No'),
	array('Gulf of California','Honduras (West Coast)','Yes','No'),
	array('Gulf of California','Mazatlan','Yes','No'),
	array('Gulf of California','Oaxaca','Yes','No'),
	array('Gulf of California','Sonora','Yes','No'),
	array('Gulf of California','West Coast','Yes','No'),
	array('Gulf of Guinea','Ivory Coast','Yes','No'),
	array('Gulf of Guinea','Middle Atlantic','Yes','No'),
	array('Gulf of Guinea','Okrana','Yes','No'),
	array('Gulf of Guinea','South Atlantic','Yes','No'),
	array('Gulf of Lyon','Marseilles','Yes','No'),
	array('Gulf of Lyon','Piedmont','Yes','No'),
	array('Gulf of Lyon','Rome (West Coast)','Yes','No'),
	array('Gulf of Lyon','Tyrrhenian Sea','Yes','No'),
	array('Gulf of Lyon','Valencia','Yes','No'),
	array('Gulf of Lyon','Western Mediterranean','Yes','No'),
	array('Gulf of Manaar','Hyderabad','Yes','No'),
	array('Gulf of Manaar','Madras','Yes','No'),
	array('Gulf of Mexico','Merida','Yes','No'),
	array('Gulf of Mexico','Mexico City','Yes','No'),
	array('Gulf of Mexico','New Orleans','Yes','No'),
	array('Gulf of Mexico','Tampa','Yes','No'),
	array('Gulf of Mexico','Western Carribean','Yes','No'),
	array('Gulf of Panama','Honduras (West Coast)','Yes','No'),
	array('Gulf of Panama','Lima','Yes','No'),
	array('Gulf of Panama','Pacific Basin','Yes','No'),
	array('Gulf of Panama','Panama (South Coast)','Yes','No'),
	array('Gulf of Siam','Java Sea','Yes','No'),
	array('Gulf of Siam','Malaysia','Yes','No'),
	array('Gulf of Siam','South China Sea','Yes','No'),
	array('Gulf of Siam','Sunda','Yes','No'),
	array('Hadramaut','Nejaaz','No','Yes'),
	array('Hadramaut','Oman','No','Yes'),
	array('Hadramaut (North Coast)','Oman','Yes','No'),
	array('Hadramaut (North Coast)','Persian Gulf','Yes','No'),
	array('Hadramaut (South Coast)','Horn of Africa','Yes','No'),
	array('Hadramaut (South Coast)','Oman','Yes','No'),
	array('Haiti','Sargasso','Yes','No'),
	array('Haiti','Virgin Islands','Yes','Yes'),
	array('Haiti','Western Carribean','Yes','No'),
	array('Hawaii','Kirbati Sea','Yes','No'),
	array('Hawaii','North Pacific','Yes','No'),
	array('Hawaii','West Pacific','Yes','No'),
	array('Hawaii','Westerlies','Yes','No'),
	array('Helgoland Bight','Holland','Yes','No'),
	array('Helgoland Bight','Kiel (West Coast)','Yes','No'),
	array('Helgoland Bight','North Sea','Yes','No'),
	array('Holland','Kiel','No','Yes'),
	array('Holland','Kiel (West Coast)','Yes','No'),
	array('Holland','Metz','No','Yes'),
	array('Holland','North Sea','Yes','No'),
	array('Holland','Rouen','Yes','Yes'),
	array('Holland','Ruhr','No','Yes'),
	array('Honduras','Panama','No','Yes'),
	array('Honduras (East Coast)','Panama (North Coast)','Yes','No'),
	array('Honduras (East Coast)','Western Carribean','Yes','No'),
	array('Honduras (West Coast)','Panama (South Coast)','Yes','No'),
	array('Hong Kong','South China Sea','Yes','No'),
	array('Horn of Africa','Kenya','Yes','No'),
	array('Horn of Africa','Malagasy Channel','Yes','No'),
	array('Horn of Africa','North East Monsoon','Yes','No'),
	array('Horn of Africa','Red Sea','Yes','No'),
	array('Horn of Africa','Seychelles','Yes','No'),
	array('Horn of Africa','Somalia','Yes','No'),
	array('Hudson','North Atlantic','Yes','No'),
	array('Hudson','North Passage','Yes','No'),
	array('Hudson','Nova Scotia','Yes','No'),
	array('Hudson','Ontario','Yes','No'),
	array('Hudson','Quebec','Yes','No'),
	array('Hudson','Ruperts Land','Yes','No'),
	array('Hyderabad','Lucknow','No','Yes'),
	array('Hyderabad','Madras','Yes','Yes'),
	array('Hyderabad','Mandlah','No','Yes'),
	array('Iceland','North Passage','Yes','No'),
	array('Iceland','Norwegian Sea','Yes','No'),
	array('Inner Mongolia','Irkutsk','No','Yes'),
	array('Inner Mongolia','Langchow','No','Yes'),
	array('Inner Mongolia','Manchuria','No','Yes'),
	array('Inner Mongolia','Mongolia','No','Yes'),
	array('Inner Mongolia','Peking','No','Yes'),
	array('Inner Mongolia','Vladivostok','No','Yes'),
	array('Ionian Sea','Sicily','Yes','No'),
	array('Ionian Sea','Tripoli','Yes','No'),
	array('Ionian Sea','Tubruq','Yes','No'),
	array('Ionian Sea','Tunis','Yes','No'),
	array('Ionian Sea','Tyrrhenian Sea','Yes','No'),
	array('Irian Java','New Guinea','Yes','Yes'),
	array('Irian Java','Timor','Yes','No'),
	array('Irkutsk','Krasnoyarsk','No','Yes'),
	array('Irkutsk','Mongolia','No','Yes'),
	array('Irkutsk','Vladivostok','No','Yes'),
	array('Irkutsk','Yakutsk','No','Yes'),
	array('Ivory Coast','Mandingoes','No','Yes'),
	array('Izu Trench','Kagoshima','Yes','No'),
	array('Izu Trench','Kuril','Yes','No'),
	array('Izu Trench','Okinawa','Yes','No'),
	array('Izu Trench','Philippine','Yes','No'),
	array('Izu Trench','Sea of Japan','Yes','No'),
	array('Izu Trench','West Pacific','Yes','No'),
	array('Izu Trench','Yellow Sea','Yes','No'),
	array('Java Sea','Java','Yes','No'),
	array('Java Sea','Malaysia','Yes','No'),
	array('Java Sea','Sarawak','Yes','No'),
	array('Java Sea','Singapore','Yes','No'),
	array('Java Sea','South East Trades','Yes','No'),
	array('Java Sea','Sumatra','Yes','No'),
	array('Java Sea','Sunda','Yes','No'),
	array('Java Sea','Timor','Yes','No'),
	array('Java','South East Trades','Yes','No'),
	array('Java','Timor','Yes','No'),
	array('Kagoshima','Sea of Japan','Yes','No'),
	array('Kagoshima','Yellow Sea','Yes','No'),
	array('Kamchatka','Okhotsk','Yes','No'),
	array('Kamchatka','Vladivostok','Yes','Yes'),
	array('Kamchatka','Yakutsk','No','Yes'),
	array('Kansas','Nebraska','No','Yes'),
	array('Kansas','New Mexico','No','Yes'),
	array('Kansas','Oklahoma','No','Yes'),
	array('Karachi','Kashgar','No','Yes'),
	array('Karachi','Kashmir','No','Yes'),
	array('Karachi','Persian Gulf','Yes','No'),
	array('Karachi','Rajputana','No','Yes'),
	array('Kasala','Krasnoyarsk','No','Yes'),
	array('Kasala','Orenburg','No','Yes'),
	array('Kasala','Tashkent','No','Yes'),
	array('Kashgar','Kashmir','No','Yes'),
	array('Kashgar','Kirghiz','No','Yes'),
	array('Kashgar','Sinkiang','No','Yes'),
	array('Kashgar','Tibet','No','Yes'),
	array('Kashmir','Rajputana','No','Yes'),
	array('Kashmir','Tibet','No','Yes'),
	array('Kenya','Malagasy Channel','Yes','No'),
	array('Kenya','Mozambique','Yes','Yes'),
	array('Kenya','Somalia','Yes','Yes'),
	array('Khiva','Orenburg','Yes','Yes'),
	array('Khiva','Tehran','Yes','Yes'),
	array('Kiel','Ruhr','No','Yes'),
	array('Kiel','Stuttgart','No','Yes'),
	array('Kirbati Sea','Pacific Basin','Yes','No'),
	array('Kirbati Sea','Society Islands','Yes','No'),
	array('Kirbati Sea','South West Pacific','Yes','No'),
	array('Kirghiz','Krasnoyarsk','No','Yes'),
	array('Kirghiz','Langchow','No','Yes'),
	array('Kirghiz','Mongolia','No','Yes'),
	array('Kirghiz','Sinkiang','No','Yes'),
	array('Kirghiz','Tashkent','No','Yes'),
	array('Krasnoyarsk','Mongolia','No','Yes'),
	array('Krasnoyarsk','Omsk','No','Yes'),
	array('Krasnoyarsk','Orenburg','No','Yes'),
	array('Krasnoyarsk','Tashkent','No','Yes'),
	array('Kuril','Okhotsk','Yes','No'),
	array('Kuril','Sapporo','Yes','No'),
	array('Kuril','Sea of Japan','Yes','No'),
	array('Kuril','West Pacific','Yes','No'),
	array('Kuril','Westerlies','Yes','No'),
	array('La Paz','Quito','No','Yes'),
	array('Langchow','Mongolia','No','Yes'),
	array('Langchow','Peking','No','Yes'),
	array('Langchow','Sinkiang','No','Yes'),
	array('Langchow','Wuhan','No','Yes'),
	array('Lima','Mitu','No','Yes'),
	array('Lima','Pacific Basin','Yes','No'),
	array('Lima','Quito','Yes','Yes'),
	array('Livonia','Moscow','No','Yes'),
	array('Livonia','Prussia','Yes','Yes'),
	array('Livonia','St Petersburg','No','Yes'),
	array('Livonia','St Petersburg (South Coast)','Yes','No'),
	array('Livonia','Warsaw','No','Yes'),
	array('London','North Atlantic','Yes','No'),
	array('London','North Passage','Yes','No'),
	array('London','North Sea','Yes','No'),
	array('Lucknow','Mandlah','No','Yes'),
	array('Luzon Sea','Luzon','Yes','No'),
	array('Luzon Sea','Mindanao','Yes','No'),
	array('Luzon Sea','Philippine','Yes','No'),
	array('Luzon Sea','South China Sea','Yes','No'),
	array('Luzon Sea','Sunda','Yes','No'),
	array('Luzon','Mindanao','Yes','Yes'),
	array('Luzon','Philippine','Yes','No'),
	array('Madagascar','Malagasy Channel','Yes','No'),
	array('Madagascar','West Indian','Yes','No'),
	array('Malagasy Channel','Mozambique','Yes','No'),
	array('Malagasy Channel','Seychelles','Yes','No'),
	array('Malagasy Channel','Transvaal','Yes','No'),
	array('Malagasy Channel','West Indian','Yes','No'),
	array('Malaysia','Singapore','Yes','Yes'),
	array('Maldives','North East Monsoon','Yes','No'),
	array('Manchuria','Peking','Yes','Yes'),
	array('Manchuria','Port Arthur','Yes','Yes'),
	array('Manchuria','Seoul','No','Yes'),
	array('Manchuria','Vladivostok','No','Yes'),
	array('Manchuria','Yellow Sea','Yes','No'),
	array('Mandalay','Rangoon','No','Yes'),
	array('Mandalay','Tonkin','No','Yes'),
	array('Mandalay','Yunnan','No','Yes'),
	array('Mandalay','Yuthia','No','Yes'),
	array('Mandingoes','Monrovia','No','Yes'),
	array('Mandingoes','Sierra Leone','No','Yes'),
	array('Mandingoes','Taganet','No','Yes'),
	array('Mandingoes','Tiris','No','Yes'),
	array('Mandlah','Rajputana','No','Yes'),
	array('Marseilles','Metz','No','Yes'),
	array('Marseilles','Paris','No','Yes'),
	array('Marseilles','Piedmont','Yes','Yes'),
	array('Marseilles','Valencia','Yes','Yes'),
	array('Marshal Islands','West Pacific','Yes','No'),
	array('Mazatlan','Mexico City','No','Yes'),
	array('Mazatlan','Oaxaca','Yes','Yes'),
	array('Mazatlan','Sonora','Yes','Yes'),
	array('Mecca','Nejaaz','No','Yes'),
	array('Mecca','Red Sea','Yes','No'),
	array('Mecca','Syria','No','Yes'),
	array('Mecca','Syria (South Coast)','Yes','No'),
	array('Merida','Mexico City','Yes','Yes'),
	array('Merida','Oaxaca','No','Yes'),
	array('Merida','Western Carribean','Yes','No'),
	array('Metz','Paris','No','Yes'),
	array('Metz','Rouen','No','Yes'),
	array('Metz','Ruhr','No','Yes'),
	array('Metz','Stuttgart','No','Yes'),
	array('Mexico City','Oaxaca','No','Yes'),
	array('Middle Atlantic','Monrovia','Yes','No'),
	array('Middle Atlantic','North East Trades','Yes','No'),
	array('Middle Atlantic','Recife','Yes','No'),
	array('Middle Atlantic','Sargasso','Yes','No'),
	array('Middle Atlantic','Sierra Leone','Yes','No'),
	array('Middle Atlantic','South Atlantic','Yes','No'),
	array('Middle Atlantic','Tiris','Yes','No'),
	array('Mindanao','Sunda','Yes','No'),
	array('Minnesota','Ontario','No','Yes'),
	array('Minnesota','Saskatchewan','No','Yes'),
	array('Minnesota','Unorganized Territories','No','Yes'),
	array('Monrovia','Sierra Leone','Yes','Yes'),
	array('Morocco','Straits of Gibraltar','Yes','No'),
	array('Morocco','Tawarek','No','Yes'),
	array('Morocco','Tiris','Yes','Yes'),
	array('Morocco','Western Mediterranean','Yes','No'),
	array('Moscow','Perm','No','Yes'),
	array('Moscow','Sevastopol','No','Yes'),
	array('Moscow','St Petersburg','No','Yes'),
	array('Moscow','Warsaw','No','Yes'),
	array('Mozambique','Rhodesia','No','Yes'),
	array('Mozambique','Transvaal','Yes','Yes'),
	array('Nantes','North Atlantic','Yes','No'),
	array('Nantes','North Sea','Yes','No'),
	array('Nantes','Paris','No','Yes'),
	array('Nantes','Rouen','Yes','Yes'),
	array('Nebraska','Saskatchewan','No','Yes'),
	array('Nebraska','Unorganized Territories','No','Yes'),
	array('Nebraska','Utah','No','Yes'),
	array('Nejaaz','Syria','No','Yes'),
	array('New Guinea','Timor','Yes','No'),
	array('New Mexico','Oklahoma','No','Yes'),
	array('New Mexico','San Francisco','No','Yes'),
	array('New Mexico','Sonora','No','Yes'),
	array('New Mexico','Utah','No','Yes'),
	array('New Orleans','Oklahoma','No','Yes'),
	array('New Orleans','Tampa','Yes','No'),
	array('New Orleans','Tennessee','No','Yes'),
	array('New South Wales','Queensland','Yes','Yes'),
	array('New South Wales','South Australia','Yes','Yes'),
	array('New South Wales','Tasman','Yes','No'),
	array('New York','Ontario','No','Yes'),
	array('New York','Quebec','Yes','Yes'),
	array('New York','Washington DC','Yes','Yes'),
	array('New Zealand','South West Pacific','Yes','No'),
	array('New Zealand','Tasman','Yes','No'),
	array('North Atlantic','North Passage','Yes','No'),
	array('North Atlantic','North Sea','Yes','No'),
	array('North Atlantic','Nova Scotia','Yes','No'),
	array('North Atlantic','Sargasso','Yes','No'),
	array('North East Monsoon','Seychelles','Yes','No'),
	array('North East Monsoon','South East Trades','Yes','No'),
	array('North East Monsoon','West Indian','Yes','No'),
	array('North East Trades','Paramaribo','Yes','No'),
	array('North East Trades','Pramaiba','Yes','No'),
	array('North East Trades','Recife','Yes','No'),
	array('North East Trades','Sargasso','Yes','No'),
	array('North East Trades','Virgin Islands','Yes','No'),
	array('North Pacific','West Bay','Yes','No'),
	array('North Pacific','West Coast','Yes','No'),
	array('North Pacific','Westerlies','Yes','No'),
	array('North Passage','Norwegian Sea','Yes','No'),
	array('North Sea','Norway','Yes','No'),
	array('North Sea','Norwegian Sea','Yes','No'),
	array('North Sea','Rouen','Yes','No'),
	array('North Sea','Skagerrak','Yes','No'),
	array('Northern Territories','Perth','Yes','Yes'),
	array('Northern Territories','Queensland','Yes','Yes'),
	array('Northern Territories','South Australia','No','Yes'),
	array('Northern Territories','Timor','Yes','No'),
	array('Northwest Territories','Ruperts Land','No','Yes'),
	array('Northwest Territories','Saskatchewan','No','Yes'),
	array('Northwest Territories','Yukon','No','Yes'),
	array('Norway','Norwegian Sea','Yes','No'),
	array('Norway','Skagerrak','Yes','No'),
	array('Norway','Sweden','Yes','Yes'),
	array('Nova Scotia','Quebec','Yes','Yes'),
	array('Ohio','Tennessee','No','Yes'),
	array('Ohio','Washington DC','No','Yes'),
	array('Okhotsk','Sakhurlin','Yes','No'),
	array('Okhotsk','Sapporo','Yes','No'),
	array('Okhotsk','Sea of Japan','Yes','No'),
	array('Okhotsk','Vladivostok','Yes','No'),
	array('Okinawa','Philippine','Yes','No'),
	array('Okinawa','Yellow Sea','Yes','No'),
	array('Okrana','South Atlantic','Yes','No'),
	array('Oliveira','Paraguay','No','Yes'),
	array('Oliveira','Rio de Janeiro','Yes','Yes'),
	array('Oliveira','Uruguay','Yes','Yes'),
	array('Oman','Persian Gulf','Yes','No'),
	array('Omsk','Orenburg','No','Yes'),
	array('Omsk','Perm','No','Yes'),
	array('Ontario','Quebec','Yes','Yes'),
	array('Ontario','Ruperts Land','Yes','Yes'),
	array('Ontario','Saskatchewan','No','Yes'),
	array('Oregon','San Francisco','Yes','Yes'),
	array('Oregon','Seattle','Yes','Yes'),
	array('Oregon','Utah','No','Yes'),
	array('Oregon','West Bay','Yes','No'),
	array('Pacific Basin','Quito','Yes','No'),
	array('Pacific Basin','Society Islands','Yes','No'),
	array('Pacific Basin','South Pacific','Yes','No'),
	array('Panama (North Coast)','Western Carribean','Yes','No'),
	array('Paramaribo','Pramaiba','No','Yes'),
	array('Paris','Rouen','No','Yes'),
	array('Peking','Shanghai','Yes','Yes'),
	array('Peking','Wuhan','No','Yes'),
	array('Peking','Yellow Sea','Yes','No'),
	array('Perm','St Petersburg','No','Yes'),
	array('Perth','South Australia','Yes','Yes'),
	array('Perth','South East Trades','Yes','No'),
	array('Perth','Timor','Yes','No'),
	array('Philippine','South China Sea','Yes','No'),
	array('Piedmont','Rome','No','Yes'),
	array('Piedmont','Rome (West Coast)','Yes','No'),
	array('Piedmont','Venice','No','Yes'),
	array('Port Arthur','Seoul','No','Yes'),
	array('Port Arthur','Seoul (West Coast)','Yes','No'),
	array('Port Arthur','Yellow Sea','Yes','No'),
	array('Pramaiba','Recife','Yes','Yes'),
	array('Prussia','Silesia','No','Yes'),
	array('Prussia','Warsaw','No','Yes'),
	array('Queensland','South Australia','No','Yes'),
	array('Queensland','Tasman','Yes','No'),
	array('Queensland','Timor','Yes','No'),
	array('Rangoon','Yuthia','No','Yes'),
	array('Recife','Rio de Janeiro','Yes','Yes'),
	array('Red Sea','Somalia','Yes','No'),
	array('Red Sea','Sudan','Yes','No'),
	array('Red Sea','Syria (South Coast)','Yes','No'),
	array('Richmond','Tennessee','No','Yes'),
	array('Richmond','Washington DC','Yes','Yes'),
	array('Rome','Salerno','No','Yes'),
	array('Rome','Venice','No','Yes'),
	array('Rome (East Coast)','Salerno','Yes','No'),
	array('Rome (East Coast)','Venice','Yes','No'),
	array('Rome (West Coast)','Salerno','Yes','No'),
	array('Rome (West Coast)','Tyrrhenian Sea','Yes','No'),
	array('Ruhr','Stuttgart','No','Yes'),
	array('Rumania','Serbia','No','Yes'),
	array('Rumania','Sevastopol','Yes','Yes'),
	array('Rumania','Sofia','No','Yes'),
	array('Rumania','Sofia (East Coast)','Yes','No'),
	array('Rumania','Wallacia','No','Yes'),
	array('Ruperts Land','Saskatchewan','No','Yes'),
	array('Sakhurlin','Sea of Japan','Yes','No'),
	array('Sakhurlin','Vladivostok','Yes','Yes'),
	array('Salerno','Sicily','Yes','Yes'),
	array('Salerno','Tyrrhenian Sea','Yes','No'),
	array('San Francisco','Sonora','Yes','Yes'),
	array('San Francisco','Utah','No','Yes'),
	array('San Francisco','West Bay','Yes','No'),
	array('San Francisco','West Coast','Yes','No'),
	array('Sapporo','Sea of Japan','Yes','No'),
	array('Sarawak','Sunda','Yes','No'),
	array('Sargasso','Virgin Islands','Yes','No'),
	array('Saskatchewan','Unorganized Territories','No','Yes'),
	array('Sea of Japan','Seoul (East Coast)','Yes','No'),
	array('Sea of Japan','Vladivostok','Yes','No'),
	array('Sea of Japan','Yellow Sea','Yes','No'),
	array('Seattle','Utah','No','Yes'),
	array('Seattle','Vancouver','Yes','Yes'),
	array('Seattle','Victoria','Yes','Yes'),
	array('Seattle','West Bay','Yes','No'),
	array('Seoul','Vladivostok','No','Yes'),
	array('Seoul (East Coast)','Vladivostok','Yes','No'),
	array('Seoul (West Coast)','Yellow Sea','Yes','No'),
	array('Serbia','Wallacia','No','Yes'),
	array('Sevastopol','Warsaw','No','Yes'),
	array('Seychelles','West Indian','Yes','No'),
	array('Shanghai','Wuhan','No','Yes'),
	array('Shanghai','Yellow Sea','Yes','No'),
	array('Siam','Tonkin','No','Yes'),
	array('Siam','Yuthia','No','Yes'),
	array('Sicily','Tyrrhenian Sea','Yes','No'),
	array('Sierra Leone','Tiris','Yes','Yes'),
	array('Silesia','Vienna','No','Yes'),
	array('Silesia','Warsaw','No','Yes'),
	array('Sinkiang','Tibet','No','Yes'),
	array('Sinkiang','Yunnan','No','Yes'),
	array('Skagerrak','Sweden','Yes','No'),
	array('Society Islands','South Pacific','Yes','No'),
	array('Society Islands','South West Pacific','Yes','No'),
	array('Sonora','West Coast','Yes','No'),
	array('South Atlantic','South Georgia Islands','Yes','No'),
	array('South China Sea','Sunda','Yes','No'),
	array('South China Sea','Tonkin','Yes','Yes'),
	array('South East Trades','Sumatra','Yes','No'),
	array('South East Trades','Timor','Yes','No'),
	array('South East Trades','West Indian','Yes','No'),
	array('South Pacific','South West Pacific','Yes','No'),
	array('Straits of Gibraltar','Toledo','Yes','Yes'),
	array('Straits of Gibraltar','Valencia','Yes','No'),
	array('Straits of Gibraltar','Western Mediterranean','Yes','No'),
	array('Tabrize','Tehran','Yes','Yes'),
	array('Taganet','Tiris','No','Yes'),
	array('Tawarek','Tiris','No','Yes'),
	array('Tawarek','Tripoli','No','Yes'),
	array('Tennessee','Washington DC','No','Yes'),
	array('Tibet','Yunnan','No','Yes'),
	array('Toledo','Valencia','No','Yes'),
	array('Tonkin','Yunnan','No','Yes'),
	array('Tonkin','Yuthia','No','Yes'),
	array('Tripoli','Tubruq','Yes','Yes'),
	array('Tripoli','Tunis','Yes','Yes'),
	array('Tunis','Tyrrhenian Sea','Yes','No'),
	array('Tunis','Western Mediterranean','Yes','No'),
	array('Tyrrhenian Sea','Western Mediterranean','Yes','No'),
	array('Valencia','Western Mediterranean','Yes','No'),
	array('Vancouver','Victoria','Yes','Yes'),
	array('Venice','Vienna','No','Yes'),
	array('Victoria','West Bay','Yes','No'),
	array('Vladivostok','Yakutsk','No','Yes'),
	array('West Bay','West Coast','Yes','No'),
	array('West Pacific','Westerlies','Yes','No'),
	array('Wuhan','Yunnan','No','Yes')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

// Custom footer not changed by edit tool

// Just create the database as usual:
InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);

// Copy the smallmap-sample to the cache-directory to avoid a screwed variantpage (there is no smallmap available)
if (!file_exists('variants/'.$this->name.'/cache/sampleMap.png'))
	copy ('variants/'.$this->name.'/resources/sampleMap.png','variants/'.$this->name.'/cache/sampleMap.png');




