<?php
// This is file installs the map data for the Haven variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Abby Normal', 'Coast', 'No', 0, 72, 311, 72, 311),
	array('Acme Acres', 'Land', 'No', 0, 446, 239, 446, 239),
	array('Adder', 'Coast', 'No', 0, 546, 542, 546, 542),
	array('All Saints Bay', 'Sea', 'No', 0, 326, 452, 326, 452),
	array('Allerleirauh', 'Coast', 'No', 0, 200, 724, 200, 724),
	array('Ancient Necropolis', 'Land', 'No', 0, 1007, 677, 1007, 677),
	array('Andarien Plain', 'Coast', 'No', 0, 629, 155, 629, 155),
	array('Anhondon Plain', 'Coast', 'No', 0, 598, 730, 598, 730),
	array('Ansalon', 'Coast', 'Yes', 0, 113, 597, 113, 597),
	array('Anvard', 'Coast', 'Yes', 3, 285, 36, 285, 36),
	array('Arborlon', 'Coast', 'Yes', 9, 394, 44, 394, 44),
	array('Archenland', 'Coast', 'Yes', 0, 336, 90, 336, 90),
	array('Arctic Barrens', 'Coast', 'No', 0, 582, 36, 582, 36),
	array('Ashan', 'Coast', 'Yes', 15, 296, 272, 296, 272),
	array('Aslan', 'Coast', 'No', 0, 320, 51, 320, 51),
	array('Auryn', 'Coast', 'Yes', 12, 556, 730, 556, 730),
	array('Avalon', 'Land', 'Yes', 0, 736, 184, 736, 184),
	array('Babel Beach', 'Sea', 'No', 0, 820, 607, 820, 607),
	array('Baldurs Gate', 'Coast', 'Yes', 19, 669, 470, 669, 470),
	array('Beaversdam', 'Sea', 'No', 0, 318, 239, 318, 239),
	array('Bikini Bottom', 'Sea', 'No', 0, 130, 657, 130, 657),
	array('Brandywine', 'Land', 'No', 0, 737, 622, 737, 622),
	array('Brennin', 'Land', 'Yes', 2, 600, 105, 600, 105),
	array('Caer', 'Coast', 'Yes', 0, 470, 584, 470, 584),
	array('Calormen', 'Coast', 'No', 0, 269, 128, 269, 128),
	array('Camelittle', 'Coast', 'No', 0, 859, 320, 859, 320),
	array('Candlekeep', 'Land', 'Yes', 0, 666, 559, 666, 559),
	array('Carpantha', 'Land', 'Yes', 4, 1117, 601, 1117, 601),
	array('Cathal', 'Coast', 'Yes', 0, 622, 37, 622, 37),
	array('Cave of Ordeals', 'Coast', 'No', 0, 83, 197, 83, 197),
	array('Caverns of the Snow Witch', 'Land', 'No', 0, 1090, 738, 1090, 738),
	array('Celestial Delta', 'Sea', 'No', 0, 354, 191, 354, 191),
	array('Chocolate River', 'Sea', 'No', 0, 541, 279, 541, 279),
	array('Churning Reach', 'Sea', 'No', 0, 454, 431, 454, 431),
	array('City of Splendors', 'Coast', 'Yes', 0, 581, 670, 581, 670),
	array('Cliffs of Insanity', 'Coast', 'No', 0, 619, 334, 619, 334),
	array('Cormyr', 'Coast', 'No', 0, 542, 590, 542, 590),
	array('Corona', 'Land', 'Yes', 0, 285, 373, 285, 373),
	array('Critter Country', 'Land', 'No', 0, 787, 276, 787, 276),
	array('Crystal Lake', 'Sea', 'No', 0, 359, 30, 359, 30),
	array('Cyriss', 'Land', 'Yes', 0, 150, 354, 150, 354),
	array('Daisy Meadows', 'Coast', 'No', 0, 445, 285, 445, 285),
	array('Daisy Meadows (East Coast)', 'Coast', 'No', 0, 462, 304, 462, 304),
	array('Daisy Meadows (West Coast)', 'Coast', 'No', 0, 405, 290, 405, 290),
	array('Dancing Lawn', 'Land', 'No', 0, 263, 73, 263, 73),
	array('Daniloth', 'Coast', 'No', 0, 773, 132, 773, 132),
	array('Dargaard Keep', 'Coast', 'Yes', 0, 242, 372, 242, 372),
	array('Darken Wood', 'Coast', 'No', 0, 199, 377, 199, 377),
	array('Darken Wood (North Coast)', 'Coast', 'No', 0, 208, 334, 208, 334),
	array('Darken Wood (South Coast)', 'Coast', 'No', 0, 208, 389, 208, 389),
	array('Devils Canyon', 'Land', 'Yes', 0, 336, 789, 336, 789),
	array('Dhunia', 'Coast', 'No', 0, 400, 545, 400, 545),
	array('Diamond Mines', 'Land', 'No', 0, 1071, 575, 1071, 575),
	array('Dimmsdale', 'Coast', 'Yes', 0, 439, 336, 439, 336),
	array('Dragon Coast', 'Coast', 'No', 0, 538, 489, 538, 489),
	array('Dragons Teeth Mtns', 'Land', 'No', 0, 513, 166, 513, 166),
	array('Drynwyn', 'Coast', 'No', 0, 682, 174, 682, 174),
	array('Duloc', 'Land', 'Yes', 0, 738, 308, 738, 308),
	array('East Mirianic Ocean', 'Sea', 'No', 0, 516, 380, 516, 380),
	array('East Sea of Shadows', 'Sea', 'No', 0, 205, 433, 205, 433),
	array('Elephant Graveyard', 'Coast', 'No', 0, 751, 243, 751, 243),
	array('Ella', 'Coast', 'Yes', 6, 506, 280, 506, 280),
	array('Eloi', 'Coast', 'No', 0, 781, 470, 781, 470),
	array('Enchanted Isles', 'Coast', 'Yes', 0, 862, 600, 862, 600),
	array('Endor', 'Coast', 'No', 0, 694, 326, 694, 326),
	array('Ergoth', 'Coast', 'Yes', 11, 167, 409, 167, 409),
	array('Eridu', 'Land', 'No', 0, 652, 96, 652, 96),
	array('Everglot', 'Coast', 'Yes', 18, 207, 512, 207, 512),
	array('Faerun', 'Coast', 'Yes', 19, 577, 554, 577, 554),
	array('Fafhrd', 'Coast', 'Yes', 0, 368, 714, 368, 714),
	array('Fantastica', 'Coast', 'Yes', 12, 741, 354, 741, 354),
	array('Far Far Away', 'Coast', 'No', 0, 910, 444, 910, 444),
	array('Fionavar', 'Land', 'No', 0, 486, 139, 486, 139),
	array('Fitzgibbon', 'Coast', 'No', 0, 310, 685, 310, 685),
	array('Fjord', 'Coast', 'Yes', 16, 755, 712, 755, 712),
	array('Florin', 'Coast', 'No', 0, 429, 615, 429, 615),
	array('Forbidden City', 'Land', 'Yes', 0, 536, 776, 536, 776),
	array('France', 'Coast', 'No', 0, 664, 705, 664, 705),
	array('Garthim', 'Coast', 'Yes', 5, 507, 625, 507, 625),
	array('Gelfling', 'Coast', 'Yes', 5, 469, 644, 469, 644),
	array('Golgafrincham', 'Coast', 'No', 0, 771, 656, 771, 656),
	array('Gollerus', 'Coast', 'Yes', 10, 319, 640, 319, 640),
	array('Great Glacier', 'Coast', 'Yes', 0, 534, 446, 534, 446),
	array('Great Steppes', 'Coast', 'No', 0, 351, 656, 351, 656),
	array('Grendel', 'Coast', 'Yes', 0, 116, 366, 116, 366),
	array('Grief Reef', 'Sea', 'No', 0, 896, 304, 896, 304),
	array('Grimheim', 'Coast', 'Yes', 15, 360, 254, 360, 254),
	array('Grimpen Ward', 'Coast', 'Yes', 9, 392, 107, 392, 107),
	array('Grissel', 'Coast', 'Yes', 3, 237, 146, 237, 146),
	array('Groves of Academe', 'Coast', 'No', 0, 853, 245, 853, 245),
	array('Gulf of Luhn', 'Sea', 'No', 0, 732, 489, 732, 489),
	array('Gumdrop Isle', 'Coast', 'Yes', 0, 566, 330, 566, 330),
	array('Gurgi', 'Coast', 'Yes', 0, 418, 197, 418, 197),
	array('GuTanoth', 'Coast', 'Yes', 2, 547, 63, 547, 63),
	array('Gwynir', 'Land', 'Yes', 0, 722, 106, 722, 106),
	array('Hall of Echoes', 'Land', 'No', 0, 972, 731, 972, 731),
	array('Heavens Well', 'Coast', 'No', 0, 492, 53, 492, 53),
	array('Heresh', 'Land', 'No', 0, 394, 779, 394, 779),
	array('Hidden Grotto', 'Land', 'No', 0, 1202, 563, 1202, 563),
	array('High Seas', 'Sea', 'No', 0, 41, 404, 41, 404),
	array('Hoarluk', 'Coast', 'No', 0, 311, 726, 311, 726),
	array('Hollow Earth', 'Land', 'No', 0, 1103, 671, 1103, 671),
	array('Horborixen', 'Coast', 'Yes', 13, 401, 735, 401, 735),
	array('Horned Bay', 'Sea', 'No', 0, 627, 267, 627, 267),
	array('Hundred Acre Wood', 'Coast', 'Yes', 7, 776, 185, 776, 185),
	array('Ice Reach', 'Coast', 'Yes', 0, 505, 13, 505, 13),
	array('Ilthmar', 'Coast', 'No', 0, 504, 730, 504, 730),
	array('Immoren', 'Land', 'No', 0, 148, 124, 148, 124),
	array('Istar', 'Coast', 'No', 0, 234, 476, 234, 476),
	array('Ithin\\\'Carthia', 'Coast', 'No', 0, 74, 544, 74, 544),
	array('Ithin\\\'Carthia (East Coast)', 'Coast', 'No', 0, 114, 552, 114, 552),
	array('Ithin\\\'Carthia (West Coast)', 'Coast', 'No', 0, 59, 535, 59, 535),
	array('Ivory Tower', 'Land', 'Yes', 0, 608, 376, 608, 376),
	array('Kahvi', 'Coast', 'Yes', 17, 82, 339, 82, 339),
	array('Kara-Tur', 'Coast', 'No', 0, 619, 511, 619, 511),
	array('Kender', 'Coast', 'No', 0, 302, 320, 302, 320),
	array('Khaz Modan', 'Land', 'No', 0, 1157, 526, 1157, 526),
	array('Khemri', 'Coast', 'Yes', 7, 813, 162, 813, 162),
	array('Kingdom of Hearts', 'Coast', 'Yes', 0, 606, 182, 606, 182),
	array('Knockshegowna', 'Coast', 'Yes', 10, 195, 661, 195, 661),
	array('Knurremurre', 'Land', 'No', 0, 1081, 522, 1081, 522),
	array('Krikkit', 'Land', 'Yes', 0, 678, 636, 678, 636),
	array('Krynn', 'Coast', 'Yes', 11, 113, 506, 113, 506),
	array('Land Ho', 'Coast', 'Yes', 0, 739, 444, 739, 444),
	array('Land of Sweets', 'Coast', 'Yes', 0, 453, 169, 453, 169),
	array('Lankhmar', 'Coast', 'Yes', 13, 462, 750, 462, 750),
	array('Lindon', 'Coast', 'Yes', 8, 783, 587, 783, 587),
	array('Llyr', 'Coast', 'Yes', 1, 666, 284, 666, 284),
	array('Loxley', 'Coast', 'Yes', 1, 693, 256, 693, 256),
	array('Lubrick', 'Land', 'Yes', 10, 250, 681, 250, 681),
	array('Magrathea', 'Coast', 'Yes', 16, 698, 729, 698, 729),
	array('Marshes of Morva', 'Coast', 'No', 0, 539, 688, 539, 688),
	array('Maze of Regrets', 'Land', 'No', 0, 771, 323, 771, 323),
	array('Mermaids Lagoon', 'Sea', 'No', 0, 899, 410, 899, 410),
	array('Merrow', 'Coast', 'No', 0, 219, 634, 219, 634),
	array('Mist Marsh', 'Sea', 'No', 0, 351, 143, 351, 143),
	array('Moominvalley', 'Coast', 'No', 0, 190, 299, 190, 299),
	array('Mordor', 'Coast', 'Yes', 8, 724, 539, 724, 539),
	array('Mount Nimro', 'Coast', 'Yes', 4, 480, 397, 480, 397),
	array('Myrtle', 'Coast', 'No', 0, 332, 607, 332, 607),
	array('Myth Drannor', 'Coast', 'Yes', 0, 632, 398, 632, 398),
	array('Necronomicon', 'Coast', 'No', 0, 221, 579, 221, 579),
	array('Nehwon', 'Land', 'Yes', 13, 452, 777, 452, 777),
	array('Never Never Land', 'Coast', 'Yes', 0, 883, 517, 883, 517),
	array('Neverpeak Mtn', 'Land', 'Yes', 0, 800, 321, 800, 321),
	array('Newa River', 'Coast', 'Yes', 7, 849, 211, 849, 211),
	array('Niflheim', 'Land', 'Yes', 17, 129, 281, 129, 281),
	array('North Mirianic Ocean', 'Sea', 'No', 0, 490, 328, 490, 328),
	array('North Rainbow Lake', 'Sea', 'No', 0, 393, 577, 393, 577),
	array('Nowwhat', 'Land', 'No', 0, 730, 661, 730, 661),
	array('Ogrun', 'Land', 'No', 0, 500, 776, 500, 776),
	array('Orboros', 'Coast', 'Yes', 0, 223, 194, 223, 194),
	array('Owlwood', 'Coast', 'No', 0, 182, 145, 182, 145),
	array('Oz', 'Coast', 'Yes', 6, 490, 246, 490, 246),
	array('Palmaris', 'Coast', 'No', 0, 242, 417, 242, 417),
	array('Pans Labyrinth', 'Coast', 'Yes', 14, 820, 438, 820, 438),
	array('Paras Derval', 'Coast', 'Yes', 2, 531, 100, 531, 100),
	array('Parce Pass', 'Coast', 'No', 0, 857, 389, 857, 389),
	array('Pendaran Wood', 'Land', 'No', 0, 584, 64, 584, 64),
	array('Pirate Shoals', 'Sea', 'No', 0, 787, 423, 787, 423),
	array('Plains of Dust', 'Land', 'No', 0, 155, 295, 155, 295),
	array('Pool of Radiance', 'Sea', 'No', 0, 232, 311, 232, 311),
	array('Port Ghaast', 'Coast', 'No', 0, 572, 370, 572, 370),
	array('Powry', 'Land', 'No', 0, 238, 718, 238, 718),
	array('Prekkendorran Hts', 'Coast', 'Yes', 5, 422, 659, 422, 659),
	array('Prekkendorran Hts (North Coast)', 'Coast', 'No', 5, 406, 644, 406, 644),
	array('Prekkendorran Hts (South Coast)', 'Coast', 'No', 5, 454, 682, 454, 682),
	array('Prydain', 'Coast', 'Yes', 1, 633, 218, 633, 218),
	array('Pwyll', 'Coast', 'No', 0, 414, 457, 414, 457),
	array('Pygmy', 'Coast', 'No', 0, 166, 242, 166, 242),
	array('Ranaar', 'Coast', 'No', 0, 388, 214, 388, 214),
	array('Razors Edge', 'Sea', 'No', 0, 628, 448, 628, 448),
	array('Restless Waters', 'Sea', 'No', 0, 704, 413, 704, 413),
	array('Rift Canyon', 'Sea', 'No', 0, 683, 377, 683, 377),
	array('Riku', 'Coast', 'Yes', 14, 883, 364, 883, 364),
	array('Rivendell', 'Coast', 'No', 0, 775, 500, 775, 500),
	array('River Of Dawn', 'Sea', 'No', 0, 577, 491, 577, 491),
	array('River Saeren', 'Coast', 'No', 0, 489, 92, 489, 92),
	array('River Styx', 'Sea', 'No', 0, 133, 559, 133, 559),
	array('Roaring Rapids', 'Sea', 'No', 0, 505, 576, 505, 576),
	array('Rohan', 'Coast', 'Yes', 8, 758, 550, 758, 550),
	array('Rugged Roast', 'Sea', 'No', 0, 600, 300, 600, 300),
	array('Sables Swamp', 'Coast', 'No', 0, 136, 428, 136, 428),
	array('Savage Sea', 'Sea', 'No', 0, 318, 498, 318, 498),
	array('Sea Of Fallen Stars', 'Sea', 'No', 0, 839, 552, 839, 552),
	array('Shady Vale', 'Coast', 'No', 0, 423, 132, 423, 132),
	array('Shining Stream', 'Coast', 'No', 0, 677, 682, 677, 682),
	array('Silvanesti', 'Coast', 'No', 0, 440, 556, 440, 556),
	array('Silvanesti (East Coast)', 'Coast', 'No', 0, 485, 540, 485, 540),
	array('Silvanesti (West Coast)', 'Coast', 'No', 0, 436, 581, 436, 581),
	array('Sinking Shore', 'Coast', 'No', 0, 422, 708, 422, 708),
	array('Skellington', 'Coast', 'Yes', 18, 168, 551, 168, 551),
	array('Skullcap', 'Coast', 'Yes', 18, 274, 501, 274, 501),
	array('Sleepy Hollow', 'Land', 'Yes', 0, 703, 65, 703, 65),
	array('Slightly Gulch', 'Coast', 'Yes', 0, 871, 277, 871, 277),
	array('Sorrows End', 'Coast', 'Yes', 17, 100, 236, 100, 236),
	array('South Rainbow Lake', 'Sea', 'No', 0, 379, 626, 379, 626),
	array('Spiral Castle', 'Land', 'Yes', 0, 566, 192, 566, 192),
	array('Spirit Pond', 'Land', 'Yes', 0, 1140, 724, 1140, 724),
	array('Starkadh', 'Coast', 'No', 0, 682, 133, 682, 133),
	array('Strawberry Fields', 'Coast', 'No', 0, 574, 239, 574, 239),
	array('Sunless Sea', 'Sea', 'No', 0, 287, 184, 287, 184),
	array('Tarsis', 'Coast', 'Yes', 11, 78, 409, 78, 409),
	array('Telmar', 'Coast', 'Yes', 0, 319, 122, 319, 122),
	array('Temple of Doom', 'Land', 'No', 0, 1183, 612, 1183, 612),
	array('Terabithia', 'Coast', 'Yes', 0, 347, 540, 347, 540),
	array('The High Way', 'Coast', 'No', 0, 843, 485, 843, 485),
	array('The Julianthes', 'Coast', 'Yes', 0, 392, 412, 392, 412),
	array('The Maw', 'Sea', 'No', 0, 178, 613, 178, 613),
	array('The Neverwood', 'Coast', 'Yes', 14, 793, 387, 793, 387),
	array('The Old Gristmill', 'Coast', 'Yes', 0, 396, 506, 396, 506),
	array('The Silver city', 'Coast', 'Yes', 15, 247, 227, 247, 227),
	array('The Wilderland', 'Coast', 'No', 0, 718, 699, 718, 699),
	array('Thirsty Desert', 'Land', 'No', 0, 638, 615, 638, 615),
	array('Thon Thalas', 'Sea', 'No', 0, 60, 252, 60, 252),
	array('Thra', 'Land', 'No', 0, 449, 502, 449, 502),
	array('Three River Lake', 'Sea', 'No', 0, 478, 712, 478, 712),
	array('Thunderhead', 'Sea', 'No', 0, 265, 594, 265, 594),
	array('Tilva Strait', 'Sea', 'No', 0, 388, 306, 388, 306),
	array('Timberlands', 'Coast', 'No', 0, 290, 463, 290, 463),
	array('To-Gai-Ru', 'Coast', 'Yes', 12, 310, 399, 310, 399),
	array('Traal', 'Land', 'Yes', 16, 652, 745, 652, 745),
	array('Travers Town', 'Coast', 'Yes', 0, 722, 381, 722, 381),
	array('Trog Bog', 'Sea', 'No', 0, 165, 195, 165, 195),
	array('Troldhaugen', 'Coast', 'Yes', 0, 126, 164, 126, 164),
	array('Tuatha', 'Coast', 'Yes', 0, 272, 636, 272, 636),
	array('Tumnus', 'Land', 'Yes', 3, 212, 83, 212, 83),
	array('Twisted Tunnels', 'Land', 'No', 0, 1034, 712, 1034, 712),
	array('Two Towers', 'Land', 'Yes', 0, 700, 613, 700, 613),
	array('Tymwyvenne', 'Land', 'No', 0, 1025, 522, 1025, 522),
	array('Uhl Belk', 'Coast', 'No', 0, 252, 541, 252, 541),
	array('Undermountain', 'Land', 'Yes', 4, 1034, 640, 1034, 640),
	array('Uuno', 'Coast', 'No', 0, 352, 753, 352, 753),
	array('Valley of Lost Honor', 'Land', 'No', 0, 603, 596, 603, 596),
	array('Venatori Umbrarum', 'Land', 'No', 0, 1183, 699, 1183, 699),
	array('Vinyaya', 'Coast', 'Yes', 6, 527, 227, 527, 227),
	array('Walk of Clouds', 'Coast', 'No', 0, 353, 327, 353, 327),
	array('Waterdeep', 'Coast', 'Yes', 19, 619, 548, 619, 548),
	array('Way the Heck', 'Sea', 'No', 0, 34, 535, 34, 535),
	array('West Mirianic Ocean', 'Sea', 'No', 0, 412, 378, 412, 378),
	array('West Sea of Shadows', 'Sea', 'No', 0, 133, 472, 133, 472),
	array('Westmark', 'Land', 'No', 0, 719, 222, 719, 222),
	array('Whoville', 'Land', 'Yes', 0, 295, 769, 295, 769),
	array('Wing Hove', 'Coast', 'Yes', 9, 432, 42, 432, 42),
	array('Yggdrasil', 'Land', 'No', 0, 983, 613, 983, 613),
	array('Yuirwood', 'Coast', 'No', 0, 701, 503, 701, 503),
	array('Zeboims Deep', 'Sea', 'No', 0, 366, 461, 366, 461),
	array('Zhentil Keep', 'Land', 'Yes', 0, 494, 480, 494, 480),
	array('Cave of Ordeals (Underworld)', 'Coast', 'No', 0, 980, 553, 975, 557),
	array('Dragons Teeth Mtns (Underworld)', 'Coast', 'No', 0, 1105, 487, 1105, 487),
	array('Hoarluk (Underworld)', 'Coast', 'No', 0, 1016, 775, 1016, 775),
	array('Mount Nimro (Underworld)', 'Coast', 'No', 0, 1092, 633, 1092, 633),
	array('Nowwhat (Underworld)', 'Coast', 'No', 0, 1167, 767, 1167, 767),
	array('Abby Normal (2)', 'Sea', 'No', 0, 939, 312, 939, 312),
	array('Allerleirauh (2)', 'Coast', 'No', 0, 759, 734, 759, 734),
	array('Ancient Necropolis (2)', 'Coast', 'No', 0, 1209, 677, 16, 677),
	array('Anvard (2)', 'Coast', 'No', 0, 658, 17, 658, 17),
	array('Arctic Barrens (2)', 'Sea', 'No', 0, 310, 4, 310, 4),
	array('Babel Beach (2)', 'Sea', 'No', 0, 15, 626, 15, 626),
	array('Bikini Bottom (2)', 'Sea', 'No', 0, 835, 666, 835, 666),
	array('Cathal (2)', 'Coast', 'No', 0, 285, 18, 285, 18),
	array('Cave of Ordeals (2)', 'Coast', 'No', 0, 881, 194, 881, 194),
	array('Cave of Ordeals (Underworld) (2)', 'Coast', 'No', 0, 1223, 540, 1223, 540),
	array('Crystal Lake (2)', 'Sea', 'No', 0, 582, 11, 582, 11),
	array('Enchanted Isles (2)', 'Sea', 'No', 0, 75, 626, 75, 626),
	array('Far Far Away (2)', 'Coast', 'No', 0, 15, 446, 15, 446),
	array('Fjord (2)', 'Coast', 'No', 0, 179, 737, 179, 737),
	array('Grief Reef (2)', 'Sea', 'No', 0, 18, 311, 18, 311),
	array('Hall of Echoes (2)', 'Sea', 'No', 0, 1245, 731, 1245, 731),
	array('Hidden Grotto (2)', 'Coast', 'No', 0, 935, 569, 935, 569),
	array('High Seas (2)', 'Sea', 'No', 0, 931, 386, 931, 386),
	array('Immoren (2)', 'Coast', 'No', 0, 783, 87, 783, 87),
	array('Magrathea (2)', 'Coast', 'No', 0, 194, 751, 194, 751),
	array('Mermaids Lagoon (2)', 'Sea', 'No', 0, 12, 394, 12, 394),
	array('Never Never Land (2)', 'Coast', 'No', 0, 10, 487, 10, 487),
	array('Newa River (2)', 'Coast', 'No', 0, 56, 203, 56, 203),
	array('Riku (2)', 'Coast', 'No', 0, 5, 368, 5, 368),
	array('Sea Of Fallen Stars (2)', 'Sea', 'No', 0, 32, 570, 32, 570),
	array('Sleepy Hollow (2)', 'Coast', 'No', 0, 156, 90, 156, 90),
	array('Thon Thalas (2)', 'Sea', 'No', 0, 912, 265, 912, 265),
	array('Venatori Umbrarum (2)', 'Coast', 'No', 0, 818, 704, 818, 704),
	array('Way the Heck (2)', 'Sea', 'No', 0, 897, 582, 897, 582),
	array('Yggdrasil (2)', 'Coast', 'No', 0, 1230, 590, 1230, 590)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Abby Normal','Grief Reef','Yes','No'),
	array('Abby Normal','High Seas','Yes','No'),
	array('Abby Normal','Kahvi','Yes','Yes'),
	array('Abby Normal','Niflheim','No','Yes'),
	array('Abby Normal','Sorrows End','Yes','Yes'),
	array('Abby Normal','Thon Thalas','Yes','No'),
	array('Acme Acres','Daisy Meadows','No','Yes'),
	array('Acme Acres','Gurgi','No','Yes'),
	array('Acme Acres','Land of Sweets','No','Yes'),
	array('Acme Acres','Oz','No','Yes'),
	array('Acme Acres','Ranaar','No','Yes'),
	array('Acme Acres','Vinyaya','No','Yes'),
	array('Adder','Cormyr','Yes','Yes'),
	array('Adder','Dragon Coast','Yes','Yes'),
	array('Adder','Faerun','Yes','Yes'),
	array('Adder','River Of Dawn','Yes','No'),
	array('Adder','Roaring Rapids','Yes','No'),
	array('All Saints Bay','Savage Sea','Yes','No'),
	array('All Saints Bay','The Julianthes','Yes','No'),
	array('All Saints Bay','Timberlands','Yes','No'),
	array('All Saints Bay','To-Gai-Ru','Yes','No'),
	array('All Saints Bay','West Mirianic Ocean','Yes','No'),
	array('All Saints Bay','Zeboims Deep','Yes','No'),
	array('Allerleirauh','Bikini Bottom','Yes','No'),
	array('Allerleirauh','Fjord','Yes','Yes'),
	array('Allerleirauh','Knockshegowna','Yes','Yes'),
	array('Allerleirauh','Magrathea','No','Yes'),
	array('Allerleirauh','Powry','No','Yes'),
	array('Ancient Necropolis','Hall of Echoes','No','Yes'),
	array('Ancient Necropolis','Twisted Tunnels','No','Yes'),
	array('Ancient Necropolis','Undermountain','No','Yes'),
	array('Ancient Necropolis','Venatori Umbrarum','No','Yes'),
	array('Ancient Necropolis','Yggdrasil','No','Yes'),
	array('Andarien Plain','Brennin','No','Yes'),
	array('Andarien Plain','Drynwyn','Yes','Yes'),
	array('Andarien Plain','Eridu','No','Yes'),
	array('Andarien Plain','Kingdom of Hearts','Yes','Yes'),
	array('Andarien Plain','Paras Derval','Yes','Yes'),
	array('Andarien Plain','Starkadh','Yes','Yes'),
	array('Anhondon Plain','Auryn','Yes','Yes'),
	array('Anhondon Plain','City of Splendors','Yes','Yes'),
	array('Anhondon Plain','Devils Canyon','No','Yes'),
	array('Anhondon Plain','Forbidden City','No','Yes'),
	array('Anhondon Plain','France','Yes','Yes'),
	array('Anhondon Plain','Traal','No','Yes'),
	array('Ansalon','Bikini Bottom','Yes','No'),
	array('Ansalon','Ithin\\\'Carthia','No','Yes'),
	array('Ansalon','Ithin\\\'Carthia (East Coast)','Yes','No'),
	array('Ansalon','Ithin\\\'Carthia (West Coast)','Yes','No'),
	array('Ansalon','River Styx','Yes','No'),
	array('Ansalon','The Maw','Yes','No'),
	array('Ansalon','Way the Heck','Yes','No'),
	array('Anvard','Aslan','Yes','Yes'),
	array('Anvard','Cathal','Yes','Yes'),
	array('Anvard','Crystal Lake','Yes','No'),
	array('Anvard','Dancing Lawn','No','Yes'),
	array('Anvard','Tumnus','No','Yes'),
	array('Arborlon','Aslan','Yes','Yes'),
	array('Arborlon','Crystal Lake','Yes','No'),
	array('Arborlon','Grimpen Ward','Yes','Yes'),
	array('Arborlon','Wing Hove','Yes','Yes'),
	array('Archenland','Aslan','Yes','Yes'),
	array('Archenland','Calormen','No','Yes'),
	array('Archenland','Dancing Lawn','No','Yes'),
	array('Archenland','Mist Marsh','Yes','No'),
	array('Archenland','Telmar','Yes','Yes'),
	array('Arctic Barrens','Cathal','Yes','Yes'),
	array('Arctic Barrens','Crystal Lake','Yes','No'),
	array('Arctic Barrens','GuTanoth','Yes','Yes'),
	array('Arctic Barrens','Ice Reach','Yes','Yes'),
	array('Arctic Barrens','Pendaran Wood','No','Yes'),
	array('Ashan','Beaversdam','Yes','No'),
	array('Ashan','Grimheim','Yes','Yes'),
	array('Ashan','Kender','Yes','Yes'),
	array('Ashan','Pool of Radiance','Yes','No'),
	array('Ashan','The Silver city','Yes','Yes'),
	array('Ashan','Tilva Strait','Yes','No'),
	array('Ashan','Walk of Clouds','Yes','Yes'),
	array('Aslan','Crystal Lake','Yes','No'),
	array('Aslan','Dancing Lawn','No','Yes'),
	array('Aslan','Grimpen Ward','Yes','Yes'),
	array('Aslan','Mist Marsh','Yes','No'),
	array('Auryn','City of Splendors','Yes','Yes'),
	array('Auryn','Forbidden City','No','Yes'),
	array('Auryn','Ilthmar','Yes','Yes'),
	array('Auryn','Marshes of Morva','Yes','Yes'),
	array('Auryn','Three River Lake','Yes','No'),
	array('Avalon','Drynwyn','No','Yes'),
	array('Avalon','Elephant Graveyard','No','Yes'),
	array('Avalon','Hundred Acre Wood','No','Yes'),
	array('Avalon','Westmark','No','Yes'),
	array('Babel Beach','Bikini Bottom','Yes','No'),
	array('Babel Beach','Enchanted Isles','Yes','No'),
	array('Babel Beach','Fjord','Yes','No'),
	array('Babel Beach','Golgafrincham','Yes','No'),
	array('Babel Beach','Lindon','Yes','No'),
	array('Babel Beach','Sea Of Fallen Stars','Yes','No'),
	array('Babel Beach','Way the Heck','Yes','No'),
	array('Baldurs Gate','Candlekeep','No','Yes'),
	array('Baldurs Gate','Gulf of Luhn','Yes','No'),
	array('Baldurs Gate','Kara-Tur','Yes','Yes'),
	array('Baldurs Gate','Razors Edge','Yes','No'),
	array('Baldurs Gate','Restless Waters','Yes','No'),
	array('Baldurs Gate','Yuirwood','Yes','Yes'),
	array('Beaversdam','Celestial Delta','Yes','No'),
	array('Beaversdam','Grimheim','Yes','No'),
	array('Beaversdam','Orboros','Yes','No'),
	array('Beaversdam','Sunless Sea','Yes','No'),
	array('Beaversdam','The Silver city','Yes','No'),
	array('Beaversdam','Tilva Strait','Yes','No'),
	array('Bikini Bottom','Enchanted Isles','Yes','No'),
	array('Bikini Bottom','Fjord','Yes','No'),
	array('Bikini Bottom','Knockshegowna','Yes','No'),
	array('Bikini Bottom','The Maw','Yes','No'),
	array('Bikini Bottom','Way the Heck','Yes','No'),
	array('Brandywine','Golgafrincham','No','Yes'),
	array('Brandywine','Lindon','No','Yes'),
	array('Brandywine','Nowwhat','No','Yes'),
	array('Brandywine','Rohan','No','Yes'),
	array('Brandywine','Two Towers','No','Yes'),
	array('Brennin','Eridu','No','Yes'),
	array('Brennin','Paras Derval','No','Yes'),
	array('Brennin','Pendaran Wood','No','Yes'),
	array('Caer','North Rainbow Lake','Yes','No'),
	array('Caer','Roaring Rapids','Yes','No'),
	array('Caer','Silvanesti','No','Yes'),
	array('Caer','Silvanesti (East Coast)','Yes','No'),
	array('Caer','Silvanesti (West Coast)','Yes','No'),
	array('Calormen','Dancing Lawn','No','Yes'),
	array('Calormen','Grissel','Yes','Yes'),
	array('Calormen','Sunless Sea','Yes','No'),
	array('Calormen','Telmar','Yes','Yes'),
	array('Calormen','Tumnus','No','Yes'),
	array('Camelittle','Grief Reef','Yes','No'),
	array('Camelittle','Maze of Regrets','No','Yes'),
	array('Camelittle','Neverpeak Mtn','No','Yes'),
	array('Camelittle','Parce Pass','No','Yes'),
	array('Camelittle','Riku','Yes','Yes'),
	array('Camelittle','Slightly Gulch','Yes','Yes'),
	array('Camelittle','The Neverwood','No','Yes'),
	array('Candlekeep','Kara-Tur','No','Yes'),
	array('Candlekeep','Mordor','No','Yes'),
	array('Candlekeep','Thirsty Desert','No','Yes'),
	array('Candlekeep','Two Towers','No','Yes'),
	array('Candlekeep','Waterdeep','No','Yes'),
	array('Candlekeep','Yuirwood','No','Yes'),
	array('Carpantha','Diamond Mines','No','Yes'),
	array('Carpantha','Hollow Earth','No','Yes'),
	array('Carpantha','Khaz Modan','No','Yes'),
	array('Carpantha','Mount Nimro','No','Yes'),
	array('Carpantha','Temple of Doom','No','Yes'),
	array('Cathal','Crystal Lake','Yes','No'),
	array('Cathal','Pendaran Wood','No','Yes'),
	array('Cathal','Sleepy Hollow','No','Yes'),
	array('Cave of Ordeals','Hidden Grotto','No','Yes'),
	array('Cave of Ordeals','Newa River','Yes','Yes'),
	array('Cave of Ordeals','Sorrows End','Yes','Yes'),
	array('Cave of Ordeals','Thon Thalas','Yes','No'),
	array('Cave of Ordeals','Troldhaugen','Yes','Yes'),
	array('Cave of Ordeals','Tymwyvenne','No','Yes'),
	array('Cave of Ordeals','Yggdrasil','No','Yes'),
	array('Caverns of the Snow Witch','Hollow Earth','No','Yes'),
	array('Caverns of the Snow Witch','Nowwhat','No','Yes'),
	array('Caverns of the Snow Witch','Spirit Pond','No','Yes'),
	array('Caverns of the Snow Witch','Twisted Tunnels','No','Yes'),
	array('Celestial Delta','Grimheim','Yes','No'),
	array('Celestial Delta','Grimpen Ward','Yes','No'),
	array('Celestial Delta','Gurgi','Yes','No'),
	array('Celestial Delta','Land of Sweets','Yes','No'),
	array('Celestial Delta','Mist Marsh','Yes','No'),
	array('Celestial Delta','Ranaar','Yes','No'),
	array('Celestial Delta','Shady Vale','Yes','No'),
	array('Celestial Delta','Sunless Sea','Yes','No'),
	array('Chocolate River','Ella','Yes','No'),
	array('Chocolate River','Horned Bay','Yes','No'),
	array('Chocolate River','North Mirianic Ocean','Yes','No'),
	array('Chocolate River','Oz','Yes','No'),
	array('Chocolate River','Rugged Roast','Yes','No'),
	array('Chocolate River','Strawberry Fields','Yes','No'),
	array('Chocolate River','Vinyaya','Yes','No'),
	array('Churning Reach','East Mirianic Ocean','Yes','No'),
	array('Churning Reach','Great Glacier','Yes','No'),
	array('Churning Reach','Mount Nimro','Yes','No'),
	array('Churning Reach','Myth Drannor','Yes','No'),
	array('Churning Reach','Port Ghaast','Yes','No'),
	array('Churning Reach','Pwyll','Yes','No'),
	array('Churning Reach','Razors Edge','Yes','No'),
	array('Churning Reach','The Julianthes','Yes','No'),
	array('Churning Reach','West Mirianic Ocean','Yes','No'),
	array('Churning Reach','Zeboims Deep','Yes','No'),
	array('City of Splendors','Cormyr','No','Yes'),
	array('City of Splendors','France','Yes','Yes'),
	array('City of Splendors','Garthim','No','Yes'),
	array('City of Splendors','Marshes of Morva','Yes','Yes'),
	array('City of Splendors','Shining Stream','Yes','Yes'),
	array('City of Splendors','Thirsty Desert','No','Yes'),
	array('City of Splendors','Valley of Lost Honor','No','Yes'),
	array('Cliffs of Insanity','Endor','Yes','Yes'),
	array('Cliffs of Insanity','Ivory Tower','No','Yes'),
	array('Cliffs of Insanity','Llyr','Yes','Yes'),
	array('Cliffs of Insanity','Myth Drannor','Yes','Yes'),
	array('Cliffs of Insanity','Port Ghaast','Yes','Yes'),
	array('Cliffs of Insanity','Rift Canyon','Yes','No'),
	array('Cliffs of Insanity','Rugged Roast','Yes','No'),
	array('Cormyr','Faerun','No','Yes'),
	array('Cormyr','Garthim','Yes','Yes'),
	array('Cormyr','Roaring Rapids','Yes','No'),
	array('Cormyr','Valley of Lost Honor','No','Yes'),
	array('Corona','Dargaard Keep','No','Yes'),
	array('Corona','Kender','No','Yes'),
	array('Corona','Palmaris','No','Yes'),
	array('Corona','To-Gai-Ru','No','Yes'),
	array('Corona','Walk of Clouds','No','Yes'),
	array('Critter Country','Duloc','No','Yes'),
	array('Critter Country','Elephant Graveyard','No','Yes'),
	array('Critter Country','Groves of Academe','No','Yes'),
	array('Critter Country','Llyr','No','Yes'),
	array('Critter Country','Loxley','No','Yes'),
	array('Critter Country','Maze of Regrets','No','Yes'),
	array('Critter Country','Neverpeak Mtn','No','Yes'),
	array('Critter Country','Slightly Gulch','No','Yes'),
	array('Crystal Lake','Ice Reach','Yes','No'),
	array('Crystal Lake','Wing Hove','Yes','No'),
	array('Cyriss','Darken Wood','No','Yes'),
	array('Cyriss','Ergoth','No','Yes'),
	array('Cyriss','Grendel','No','Yes'),
	array('Cyriss','Moominvalley','No','Yes'),
	array('Cyriss','Plains of Dust','No','Yes'),
	array('Cyriss','Sables Swamp','No','Yes'),
	array('Cyriss','Tarsis','No','Yes'),
	array('Daisy Meadows','Dimmsdale','No','Yes'),
	array('Daisy Meadows','Ella','No','Yes'),
	array('Daisy Meadows','Grimheim','No','Yes'),
	array('Daisy Meadows','Oz','No','Yes'),
	array('Daisy Meadows','Ranaar','No','Yes'),
	array('Daisy Meadows (East Coast)','Dimmsdale','Yes','No'),
	array('Daisy Meadows (East Coast)','Ella','Yes','No'),
	array('Daisy Meadows (East Coast)','North Mirianic Ocean','Yes','No'),
	array('Daisy Meadows (West Coast)','Dimmsdale','Yes','No'),
	array('Daisy Meadows (West Coast)','Grimheim','Yes','No'),
	array('Daisy Meadows (West Coast)','Tilva Strait','Yes','No'),
	array('Dancing Lawn','Tumnus','No','Yes'),
	array('Daniloth','Gwynir','No','Yes'),
	array('Daniloth','Hundred Acre Wood','Yes','Yes'),
	array('Daniloth','Khemri','Yes','Yes'),
	array('Daniloth','Sleepy Hollow','No','Yes'),
	array('Daniloth','Starkadh','Yes','Yes'),
	array('Dargaard Keep','Darken Wood','No','Yes'),
	array('Dargaard Keep','Darken Wood (North Coast)','Yes','No'),
	array('Dargaard Keep','Darken Wood (South Coast)','Yes','No'),
	array('Dargaard Keep','East Sea of Shadows','Yes','No'),
	array('Dargaard Keep','Kender','Yes','Yes'),
	array('Dargaard Keep','Palmaris','Yes','Yes'),
	array('Dargaard Keep','Pool of Radiance','Yes','No'),
	array('Darken Wood','Ergoth','No','Yes'),
	array('Darken Wood','Moominvalley','No','Yes'),
	array('Darken Wood (North Coast)','Moominvalley','Yes','No'),
	array('Darken Wood (North Coast)','Pool of Radiance','Yes','No'),
	array('Darken Wood (South Coast)','East Sea of Shadows','Yes','No'),
	array('Darken Wood (South Coast)','Ergoth','Yes','No'),
	array('Devils Canyon','Heresh','No','Yes'),
	array('Devils Canyon','Hoarluk','No','Yes'),
	array('Devils Canyon','Ogrun','No','Yes'),
	array('Devils Canyon','Powry','No','Yes'),
	array('Devils Canyon','Uuno','No','Yes'),
	array('Devils Canyon','Whoville','No','Yes'),
	array('Dhunia','North Rainbow Lake','Yes','No'),
	array('Dhunia','Silvanesti','No','Yes'),
	array('Dhunia','Silvanesti (West Coast)','Yes','No'),
	array('Dhunia','Terabithia','Yes','Yes'),
	array('Dhunia','The Old Gristmill','Yes','Yes'),
	array('Dhunia','Thra','No','Yes'),
	array('Diamond Mines','Knurremurre','No','Yes'),
	array('Diamond Mines','Tymwyvenne','No','Yes'),
	array('Diamond Mines','Undermountain','No','Yes'),
	array('Diamond Mines','Yggdrasil','No','Yes'),
	array('Dimmsdale','North Mirianic Ocean','Yes','No'),
	array('Dimmsdale','Tilva Strait','Yes','No'),
	array('Dimmsdale','Walk of Clouds','Yes','Yes'),
	array('Dragon Coast','Great Glacier','Yes','Yes'),
	array('Dragon Coast','River Of Dawn','Yes','No'),
	array('Dragon Coast','Roaring Rapids','Yes','No'),
	array('Dragon Coast','Silvanesti','No','Yes'),
	array('Dragon Coast','Silvanesti (East Coast)','Yes','No'),
	array('Dragon Coast','Zhentil Keep','No','Yes'),
	array('Dragons Teeth Mtns','Fionavar','No','Yes'),
	array('Dragons Teeth Mtns','Khaz Modan','No','Yes'),
	array('Dragons Teeth Mtns','Kingdom of Hearts','No','Yes'),
	array('Dragons Teeth Mtns','Knurremurre','No','Yes'),
	array('Dragons Teeth Mtns','Land of Sweets','No','Yes'),
	array('Dragons Teeth Mtns','River Saeren','No','Yes'),
	array('Dragons Teeth Mtns','Spiral Castle','No','Yes'),
	array('Dragons Teeth Mtns','Strawberry Fields','No','Yes'),
	array('Drynwyn','Hundred Acre Wood','Yes','Yes'),
	array('Drynwyn','Kingdom of Hearts','Yes','Yes'),
	array('Drynwyn','Prydain','Yes','Yes'),
	array('Drynwyn','Starkadh','Yes','Yes'),
	array('Drynwyn','Westmark','No','Yes'),
	array('Duloc','Endor','No','Yes'),
	array('Duloc','Fantastica','No','Yes'),
	array('Duloc','Llyr','No','Yes'),
	array('Duloc','Maze of Regrets','No','Yes'),
	array('East Mirianic Ocean','Gumdrop Isle','Yes','No'),
	array('East Mirianic Ocean','Mount Nimro','Yes','No'),
	array('East Mirianic Ocean','North Mirianic Ocean','Yes','No'),
	array('East Mirianic Ocean','Port Ghaast','Yes','No'),
	array('East Mirianic Ocean','Rugged Roast','Yes','No'),
	array('East Mirianic Ocean','West Mirianic Ocean','Yes','No'),
	array('East Sea of Shadows','Ergoth','Yes','No'),
	array('East Sea of Shadows','Everglot','Yes','No'),
	array('East Sea of Shadows','Istar','Yes','No'),
	array('East Sea of Shadows','Palmaris','Yes','No'),
	array('East Sea of Shadows','Timberlands','Yes','No'),
	array('East Sea of Shadows','West Sea of Shadows','Yes','No'),
	array('Elephant Graveyard','Groves of Academe','Yes','Yes'),
	array('Elephant Graveyard','Hundred Acre Wood','Yes','Yes'),
	array('Elephant Graveyard','Loxley','No','Yes'),
	array('Elephant Graveyard','Newa River','Yes','Yes'),
	array('Elephant Graveyard','Westmark','No','Yes'),
	array('Ella','North Mirianic Ocean','Yes','No'),
	array('Ella','Oz','Yes','Yes'),
	array('Eloi','Gulf of Luhn','Yes','No'),
	array('Eloi','Pans Labyrinth','Yes','Yes'),
	array('Eloi','Pirate Shoals','Yes','No'),
	array('Eloi','Rivendell','Yes','Yes'),
	array('Enchanted Isles','Sea Of Fallen Stars','Yes','No'),
	array('Enchanted Isles','Way the Heck','Yes','No'),
	array('Endor','Fantastica','Yes','Yes'),
	array('Endor','Llyr','Yes','Yes'),
	array('Endor','Rift Canyon','Yes','No'),
	array('Endor','Rugged Roast','Yes','No'),
	array('Ergoth','Sables Swamp','Yes','Yes'),
	array('Ergoth','West Sea of Shadows','Yes','No'),
	array('Eridu','Gwynir','No','Yes'),
	array('Eridu','Pendaran Wood','No','Yes'),
	array('Eridu','Starkadh','No','Yes'),
	array('Everglot','Istar','Yes','Yes'),
	array('Everglot','Skellington','Yes','Yes'),
	array('Everglot','Skullcap','No','Yes'),
	array('Everglot','Uhl Belk','No','Yes'),
	array('Everglot','West Sea of Shadows','Yes','No'),
	array('Faerun','River Of Dawn','Yes','No'),
	array('Faerun','Valley of Lost Honor','No','Yes'),
	array('Faerun','Waterdeep','Yes','Yes'),
	array('Fafhrd','Fitzgibbon','Yes','Yes'),
	array('Fafhrd','Great Steppes','Yes','Yes'),
	array('Fafhrd','Hoarluk','Yes','Yes'),
	array('Fafhrd','Horborixen','Yes','Yes'),
	array('Fafhrd','Sinking Shore','Yes','Yes'),
	array('Fafhrd','Uuno','Yes','Yes'),
	array('Fantastica','Maze of Regrets','No','Yes'),
	array('Fantastica','Rift Canyon','Yes','No'),
	array('Fantastica','Travers Town','Yes','Yes'),
	array('Far Far Away','High Seas','Yes','No'),
	array('Far Far Away','Mermaids Lagoon','Yes','No'),
	array('Far Far Away','Never Never Land','Yes','Yes'),
	array('Far Far Away','The High Way','Yes','Yes'),
	array('Fionavar','Land of Sweets','No','Yes'),
	array('Fionavar','River Saeren','No','Yes'),
	array('Fionavar','Shady Vale','No','Yes'),
	array('Fitzgibbon','Gollerus','Yes','Yes'),
	array('Fitzgibbon','Great Steppes','Yes','Yes'),
	array('Fitzgibbon','Hoarluk','Yes','Yes'),
	array('Fitzgibbon','Lubrick','No','Yes'),
	array('Fitzgibbon','Powry','No','Yes'),
	array('Fjord','Golgafrincham','Yes','Yes'),
	array('Fjord','Magrathea','Yes','Yes'),
	array('Fjord','The Wilderland','Yes','Yes'),
	array('Florin','Gelfling','Yes','Yes'),
	array('Florin','North Rainbow Lake','Yes','No'),
	array('Florin','Prekkendorran Hts','No','Yes'),
	array('Florin','Prekkendorran Hts (North Coast)','Yes','No'),
	array('Florin','South Rainbow Lake','Yes','No'),
	array('Forbidden City','Ilthmar','No','Yes'),
	array('Forbidden City','Ogrun','No','Yes'),
	array('France','Magrathea','Yes','Yes'),
	array('France','Shining Stream','Yes','Yes'),
	array('France','The Wilderland','Yes','No'),
	array('France','Traal','No','Yes'),
	array('Garthim','Gelfling','Yes','Yes'),
	array('Garthim','Marshes of Morva','No','Yes'),
	array('Garthim','Roaring Rapids','Yes','No'),
	array('Gelfling','Marshes of Morva','Yes','Yes'),
	array('Gelfling','North Rainbow Lake','Yes','No'),
	array('Gelfling','Prekkendorran Hts','No','Yes'),
	array('Gelfling','Prekkendorran Hts (South Coast)','Yes','No'),
	array('Gelfling','Roaring Rapids','Yes','No'),
	array('Gelfling','Three River Lake','Yes','No'),
	array('Golgafrincham','Lindon','Yes','Yes'),
	array('Golgafrincham','Nowwhat','No','Yes'),
	array('Golgafrincham','The Wilderland','Yes','Yes'),
	array('Gollerus','Great Steppes','Yes','Yes'),
	array('Gollerus','Lubrick','No','Yes'),
	array('Gollerus','Myrtle','Yes','Yes'),
	array('Gollerus','South Rainbow Lake','Yes','No'),
	array('Gollerus','Tuatha','No','Yes'),
	array('Great Glacier','Myth Drannor','Yes','Yes'),
	array('Great Glacier','Pwyll','Yes','Yes'),
	array('Great Glacier','Razors Edge','Yes','No'),
	array('Great Glacier','River Of Dawn','Yes','No'),
	array('Great Glacier','Zhentil Keep','No','Yes'),
	array('Great Steppes','Prekkendorran Hts','No','Yes'),
	array('Great Steppes','Prekkendorran Hts (North Coast)','Yes','No'),
	array('Great Steppes','Sinking Shore','No','Yes'),
	array('Great Steppes','South Rainbow Lake','Yes','No'),
	array('Grendel','High Seas','Yes','No'),
	array('Grendel','Kahvi','Yes','Yes'),
	array('Grendel','Plains of Dust','No','Yes'),
	array('Grendel','Tarsis','Yes','Yes'),
	array('Grief Reef','Groves of Academe','Yes','No'),
	array('Grief Reef','High Seas','Yes','No'),
	array('Grief Reef','Mermaids Lagoon','Yes','No'),
	array('Grief Reef','Newa River','Yes','No'),
	array('Grief Reef','Riku','Yes','No'),
	array('Grief Reef','Slightly Gulch','Yes','No'),
	array('Grief Reef','Thon Thalas','Yes','No'),
	array('Grimheim','Ranaar','Yes','Yes'),
	array('Grimheim','Tilva Strait','Yes','No'),
	array('Grimpen Ward','Heavens Well','Yes','Yes'),
	array('Grimpen Ward','Mist Marsh','Yes','No'),
	array('Grimpen Ward','Shady Vale','Yes','Yes'),
	array('Grimpen Ward','Wing Hove','No','Yes'),
	array('Grissel','Orboros','Yes','Yes'),
	array('Grissel','Owlwood','Yes','Yes'),
	array('Grissel','Sunless Sea','Yes','No'),
	array('Grissel','Trog Bog','Yes','No'),
	array('Grissel','Tumnus','No','Yes'),
	array('Groves of Academe','Newa River','Yes','Yes'),
	array('Groves of Academe','Slightly Gulch','Yes','Yes'),
	array('Gulf of Luhn','Land Ho','Yes','No'),
	array('Gulf of Luhn','Mordor','Yes','No'),
	array('Gulf of Luhn','Pirate Shoals','Yes','No'),
	array('Gulf of Luhn','Restless Waters','Yes','No'),
	array('Gulf of Luhn','Rivendell','Yes','No'),
	array('Gulf of Luhn','Yuirwood','Yes','No'),
	array('Gumdrop Isle','North Mirianic Ocean','Yes','No'),
	array('Gumdrop Isle','Port Ghaast','Yes','Yes'),
	array('Gumdrop Isle','Rugged Roast','Yes','No'),
	array('Gurgi','Land of Sweets','Yes','Yes'),
	array('Gurgi','Ranaar','Yes','Yes'),
	array('GuTanoth','Heavens Well','Yes','Yes'),
	array('GuTanoth','Ice Reach','Yes','Yes'),
	array('GuTanoth','Paras Derval','Yes','Yes'),
	array('GuTanoth','Pendaran Wood','No','Yes'),
	array('Gwynir','Sleepy Hollow','No','Yes'),
	array('Gwynir','Starkadh','No','Yes'),
	array('Hall of Echoes','Hoarluk','No','Yes'),
	array('Hall of Echoes','Twisted Tunnels','No','Yes'),
	array('Hall of Echoes','Venatori Umbrarum','No','Yes'),
	array('Heavens Well','Ice Reach','Yes','Yes'),
	array('Heavens Well','Paras Derval','Yes','Yes'),
	array('Heavens Well','River Saeren','Yes','Yes'),
	array('Heavens Well','Shady Vale','Yes','Yes'),
	array('Heavens Well','Wing Hove','No','Yes'),
	array('Heresh','Horborixen','No','Yes'),
	array('Heresh','Nehwon','No','Yes'),
	array('Heresh','Uuno','No','Yes'),
	array('Hidden Grotto','Khaz Modan','No','Yes'),
	array('Hidden Grotto','Temple of Doom','No','Yes'),
	array('Hidden Grotto','Yggdrasil','No','Yes'),
	array('High Seas','Ithin\\\'Carthia (West Coast)','Yes','No'),
	array('High Seas','Kahvi','Yes','No'),
	array('High Seas','Krynn','Yes','No'),
	array('High Seas','Mermaids Lagoon','Yes','No'),
	array('High Seas','Never Never Land','Yes','No'),
	array('High Seas','Riku','Yes','No'),
	array('High Seas','Sables Swamp','Yes','No'),
	array('High Seas','Tarsis','Yes','No'),
	array('High Seas','Thon Thalas','Yes','No'),
	array('High Seas','Way the Heck','Yes','No'),
	array('High Seas','West Sea of Shadows','Yes','No'),
	array('Hoarluk','Powry','No','Yes'),
	array('Hoarluk','Twisted Tunnels','No','Yes'),
	array('Hoarluk','Uuno','Yes','Yes'),
	array('Hoarluk','Whoville','No','Yes'),
	array('Hollow Earth','Mount Nimro','No','Yes'),
	array('Hollow Earth','Spirit Pond','No','Yes'),
	array('Hollow Earth','Undermountain','No','Yes'),
	array('Horborixen','Lankhmar','Yes','Yes'),
	array('Horborixen','Nehwon','No','Yes'),
	array('Horborixen','Sinking Shore','Yes','Yes'),
	array('Horborixen','Uuno','Yes','Yes'),
	array('Horned Bay','Llyr','Yes','No'),
	array('Horned Bay','Loxley','Yes','No'),
	array('Horned Bay','Prydain','Yes','No'),
	array('Horned Bay','Rugged Roast','Yes','No'),
	array('Horned Bay','Strawberry Fields','Yes','No'),
	array('Hundred Acre Wood','Khemri','Yes','Yes'),
	array('Hundred Acre Wood','Newa River','Yes','Yes'),
	array('Hundred Acre Wood','Starkadh','Yes','Yes'),
	array('Ice Reach','Wing Hove','Yes','Yes'),
	array('Ilthmar','Lankhmar','Yes','Yes'),
	array('Ilthmar','Ogrun','No','Yes'),
	array('Ilthmar','Three River Lake','Yes','No'),
	array('Immoren','Owlwood','No','Yes'),
	array('Immoren','Sleepy Hollow','No','Yes'),
	array('Immoren','Troldhaugen','No','Yes'),
	array('Immoren','Tumnus','No','Yes'),
	array('Istar','Skullcap','No','Yes'),
	array('Istar','Timberlands','Yes','Yes'),
	array('Ithin\\\'Carthia','Krynn','No','Yes'),
	array('Ithin\\\'Carthia (East Coast)','Krynn','Yes','No'),
	array('Ithin\\\'Carthia (East Coast)','River Styx','Yes','No'),
	array('Ithin\\\'Carthia (West Coast)','Krynn','Yes','No'),
	array('Ithin\\\'Carthia (West Coast)','Way the Heck','Yes','No'),
	array('Ivory Tower','Myth Drannor','No','Yes'),
	array('Ivory Tower','Port Ghaast','No','Yes'),
	array('Kahvi','Niflheim','No','Yes'),
	array('Kahvi','Plains of Dust','No','Yes'),
	array('Kara-Tur','Razors Edge','Yes','No'),
	array('Kara-Tur','River Of Dawn','Yes','No'),
	array('Kara-Tur','Waterdeep','Yes','Yes'),
	array('Kender','Pool of Radiance','Yes','No'),
	array('Kender','Walk of Clouds','No','Yes'),
	array('Khaz Modan','Knurremurre','No','Yes'),
	array('Khaz Modan','Temple of Doom','No','Yes'),
	array('Khemri','Newa River','Yes','Yes'),
	array('Kingdom of Hearts','Paras Derval','Yes','Yes'),
	array('Kingdom of Hearts','Prydain','Yes','Yes'),
	array('Kingdom of Hearts','River Saeren','Yes','Yes'),
	array('Kingdom of Hearts','Spiral Castle','No','Yes'),
	array('Kingdom of Hearts','Strawberry Fields','Yes','Yes'),
	array('Knockshegowna','Lubrick','No','Yes'),
	array('Knockshegowna','Merrow','Yes','Yes'),
	array('Knockshegowna','Powry','No','Yes'),
	array('Knockshegowna','The Maw','Yes','No'),
	array('Knurremurre','Tymwyvenne','No','Yes'),
	array('Krikkit','Nowwhat','No','Yes'),
	array('Krikkit','Shining Stream','No','Yes'),
	array('Krikkit','The Wilderland','No','Yes'),
	array('Krikkit','Thirsty Desert','No','Yes'),
	array('Krikkit','Two Towers','No','Yes'),
	array('Krynn','River Styx','Yes','No'),
	array('Krynn','West Sea of Shadows','Yes','No'),
	array('Land Ho','Pirate Shoals','Yes','No'),
	array('Land Ho','Restless Waters','Yes','No'),
	array('Land of Sweets','Shady Vale','Yes','Yes'),
	array('Land of Sweets','Strawberry Fields','No','Yes'),
	array('Land of Sweets','Vinyaya','Yes','Yes'),
	array('Lankhmar','Nehwon','No','Yes'),
	array('Lankhmar','Ogrun','No','Yes'),
	array('Lankhmar','Sinking Shore','Yes','Yes'),
	array('Lankhmar','Three River Lake','Yes','No'),
	array('Lindon','Rohan','Yes','Yes'),
	array('Lindon','Sea Of Fallen Stars','Yes','No'),
	array('Llyr','Loxley','Yes','Yes'),
	array('Llyr','Rugged Roast','Yes','No'),
	array('Loxley','Prydain','Yes','Yes'),
	array('Loxley','Westmark','No','Yes'),
	array('Lubrick','Merrow','No','Yes'),
	array('Lubrick','Powry','No','Yes'),
	array('Lubrick','Tuatha','No','Yes'),
	array('Magrathea','Shining Stream','Yes','Yes'),
	array('Magrathea','The Wilderland','Yes','Yes'),
	array('Magrathea','Traal','No','Yes'),
	array('Marshes of Morva','Three River Lake','Yes','No'),
	array('Maze of Regrets','Neverpeak Mtn','No','Yes'),
	array('Maze of Regrets','The Neverwood','No','Yes'),
	array('Maze of Regrets','Travers Town','No','Yes'),
	array('Mermaids Lagoon','Pans Labyrinth','Yes','No'),
	array('Mermaids Lagoon','Parce Pass','Yes','No'),
	array('Mermaids Lagoon','Riku','Yes','No'),
	array('Mermaids Lagoon','The High Way','Yes','No'),
	array('Merrow','Necronomicon','Yes','Yes'),
	array('Merrow','The Maw','Yes','No'),
	array('Merrow','Thunderhead','Yes','No'),
	array('Merrow','Tuatha','Yes','Yes'),
	array('Mist Marsh','Sunless Sea','Yes','No'),
	array('Mist Marsh','Telmar','Yes','No'),
	array('Moominvalley','Plains of Dust','No','Yes'),
	array('Moominvalley','Pool of Radiance','Yes','No'),
	array('Moominvalley','Pygmy','No','Yes'),
	array('Moominvalley','The Silver city','Yes','Yes'),
	array('Mordor','Rivendell','Yes','Yes'),
	array('Mordor','Rohan','No','Yes'),
	array('Mordor','Two Towers','No','Yes'),
	array('Mordor','Yuirwood','Yes','Yes'),
	array('Mount Nimro','Undermountain','No','Yes'),
	array('Mount Nimro','West Mirianic Ocean','Yes','No'),
	array('Myrtle','South Rainbow Lake','Yes','No'),
	array('Myrtle','Terabithia','Yes','Yes'),
	array('Myrtle','Thunderhead','Yes','No'),
	array('Myrtle','Tuatha','Yes','Yes'),
	array('Myth Drannor','Port Ghaast','Yes','Yes'),
	array('Myth Drannor','Razors Edge','Yes','No'),
	array('Myth Drannor','Rift Canyon','Yes','No'),
	array('Necronomicon','Skellington','Yes','Yes'),
	array('Necronomicon','The Maw','Yes','No'),
	array('Necronomicon','Thunderhead','Yes','No'),
	array('Necronomicon','Uhl Belk','Yes','Yes'),
	array('Nehwon','Ogrun','No','Yes'),
	array('Never Never Land','Sea Of Fallen Stars','Yes','No'),
	array('Never Never Land','The High Way','Yes','Yes'),
	array('Never Never Land','Way the Heck','Yes','No'),
	array('Neverpeak Mtn','Slightly Gulch','No','Yes'),
	array('Newa River','Thon Thalas','Yes','No'),
	array('Niflheim','Plains of Dust','No','Yes'),
	array('Niflheim','Pygmy','No','Yes'),
	array('Niflheim','Sorrows End','No','Yes'),
	array('North Mirianic Ocean','Rugged Roast','Yes','No'),
	array('North Mirianic Ocean','Tilva Strait','Yes','No'),
	array('North Mirianic Ocean','West Mirianic Ocean','Yes','No'),
	array('North Rainbow Lake','Roaring Rapids','Yes','No'),
	array('North Rainbow Lake','Silvanesti (West Coast)','Yes','No'),
	array('North Rainbow Lake','South Rainbow Lake','Yes','No'),
	array('North Rainbow Lake','Terabithia','Yes','No'),
	array('North Rainbow Lake','Thunderhead','Yes','No'),
	array('Nowwhat','Spirit Pond','No','Yes'),
	array('Nowwhat','The Wilderland','No','Yes'),
	array('Nowwhat','Two Towers','No','Yes'),
	array('Nowwhat','Venatori Umbrarum','No','Yes'),
	array('Orboros','Pygmy','Yes','Yes'),
	array('Orboros','Sunless Sea','Yes','No'),
	array('Orboros','The Silver city','Yes','Yes'),
	array('Orboros','Trog Bog','Yes','No'),
	array('Owlwood','Trog Bog','Yes','No'),
	array('Owlwood','Troldhaugen','Yes','Yes'),
	array('Owlwood','Tumnus','No','Yes'),
	array('Oz','Vinyaya','Yes','Yes'),
	array('Palmaris','Timberlands','Yes','Yes'),
	array('Palmaris','To-Gai-Ru','Yes','Yes'),
	array('Pans Labyrinth','Parce Pass','Yes','Yes'),
	array('Pans Labyrinth','Pirate Shoals','Yes','No'),
	array('Pans Labyrinth','Rivendell','No','Yes'),
	array('Pans Labyrinth','The High Way','Yes','Yes'),
	array('Pans Labyrinth','The Neverwood','Yes','Yes'),
	array('Paras Derval','Pendaran Wood','No','Yes'),
	array('Paras Derval','River Saeren','Yes','Yes'),
	array('Parce Pass','Riku','Yes','Yes'),
	array('Parce Pass','The Neverwood','No','Yes'),
	array('Pirate Shoals','Restless Waters','Yes','No'),
	array('Pirate Shoals','The Neverwood','Yes','No'),
	array('Pirate Shoals','Travers Town','Yes','No'),
	array('Plains of Dust','Pygmy','No','Yes'),
	array('Pool of Radiance','The Silver city','Yes','No'),
	array('Port Ghaast','Rugged Roast','Yes','No'),
	array('Prekkendorran Hts','Sinking Shore','No','Yes'),
	array('Prekkendorran Hts (North Coast)','South Rainbow Lake','Yes','No'),
	array('Prekkendorran Hts (South Coast)','Sinking Shore','Yes','No'),
	array('Prekkendorran Hts (South Coast)','Three River Lake','Yes','No'),
	array('Prydain','Strawberry Fields','Yes','Yes'),
	array('Prydain','Westmark','No','Yes'),
	array('Pwyll','The Old Gristmill','Yes','Yes'),
	array('Pwyll','Thra','No','Yes'),
	array('Pwyll','Zeboims Deep','Yes','No'),
	array('Pwyll','Zhentil Keep','No','Yes'),
	array('Pygmy','Sorrows End','Yes','Yes'),
	array('Pygmy','The Silver city','No','Yes'),
	array('Pygmy','Trog Bog','Yes','No'),
	array('Razors Edge','Restless Waters','Yes','No'),
	array('Razors Edge','Rift Canyon','Yes','No'),
	array('Razors Edge','River Of Dawn','Yes','No'),
	array('Restless Waters','Rift Canyon','Yes','No'),
	array('Restless Waters','Travers Town','Yes','No'),
	array('Rift Canyon','Rugged Roast','Yes','No'),
	array('Rift Canyon','Travers Town','Yes','No'),
	array('Rivendell','Rohan','Yes','Yes'),
	array('Rivendell','Sea Of Fallen Stars','Yes','No'),
	array('Rivendell','The High Way','Yes','Yes'),
	array('River Of Dawn','Roaring Rapids','Yes','No'),
	array('River Of Dawn','Waterdeep','Yes','No'),
	array('River Saeren','Shady Vale','Yes','Yes'),
	array('River Styx','Skellington','Yes','No'),
	array('River Styx','The Maw','Yes','No'),
	array('River Styx','West Sea of Shadows','Yes','No'),
	array('Roaring Rapids','Silvanesti (East Coast)','Yes','No'),
	array('Rohan','Sea Of Fallen Stars','Yes','No'),
	array('Rohan','Two Towers','No','Yes'),
	array('Sables Swamp','Tarsis','Yes','Yes'),
	array('Sables Swamp','West Sea of Shadows','Yes','No'),
	array('Savage Sea','Skullcap','Yes','No'),
	array('Savage Sea','Terabithia','Yes','No'),
	array('Savage Sea','Thunderhead','Yes','No'),
	array('Savage Sea','Timberlands','Yes','No'),
	array('Savage Sea','Uhl Belk','Yes','No'),
	array('Savage Sea','Zeboims Deep','Yes','No'),
	array('Sea Of Fallen Stars','The High Way','Yes','No'),
	array('Sea Of Fallen Stars','Way the Heck','Yes','No'),
	array('Shining Stream','The Wilderland','Yes','Yes'),
	array('Shining Stream','Thirsty Desert','No','Yes'),
	array('Silvanesti','Thra','No','Yes'),
	array('Silvanesti','Zhentil Keep','No','Yes'),
	array('Sinking Shore','Three River Lake','Yes','No'),
	array('Skellington','The Maw','Yes','No'),
	array('Skellington','Uhl Belk','No','Yes'),
	array('Skellington','West Sea of Shadows','Yes','No'),
	array('Skullcap','Timberlands','Yes','Yes'),
	array('Skullcap','Uhl Belk','Yes','Yes'),
	array('Sorrows End','Thon Thalas','Yes','No'),
	array('Sorrows End','Trog Bog','Yes','No'),
	array('South Rainbow Lake','Thunderhead','Yes','No'),
	array('Spiral Castle','Strawberry Fields','No','Yes'),
	array('Spirit Pond','Venatori Umbrarum','No','Yes'),
	array('Strawberry Fields','Vinyaya','Yes','Yes'),
	array('Sunless Sea','Telmar','Yes','No'),
	array('Temple of Doom','Venatori Umbrarum','No','Yes'),
	array('Terabithia','The Old Gristmill','Yes','Yes'),
	array('Terabithia','Thunderhead','Yes','No'),
	array('Terabithia','Uhl Belk','Yes','Yes'),
	array('Terabithia','Zeboims Deep','Yes','No'),
	array('The Julianthes','West Mirianic Ocean','Yes','No'),
	array('The Julianthes','Zeboims Deep','Yes','No'),
	array('The Maw','Thunderhead','Yes','No'),
	array('The Neverwood','Travers Town','Yes','Yes'),
	array('The Old Gristmill','Thra','No','Yes'),
	array('The Old Gristmill','Zeboims Deep','Yes','No'),
	array('Thirsty Desert','Two Towers','No','Yes'),
	array('Thirsty Desert','Valley of Lost Honor','No','Yes'),
	array('Thirsty Desert','Waterdeep','No','Yes'),
	array('Thon Thalas','Trog Bog','Yes','No'),
	array('Thon Thalas','Troldhaugen','Yes','No'),
	array('Thra','Zhentil Keep','No','Yes'),
	array('Thunderhead','Tuatha','Yes','No'),
	array('Thunderhead','Uhl Belk','Yes','No'),
	array('Tilva Strait','Walk of Clouds','Yes','No'),
	array('Tilva Strait','West Mirianic Ocean','Yes','No'),
	array('Timberlands','To-Gai-Ru','Yes','Yes'),
	array('To-Gai-Ru','Walk of Clouds','Yes','Yes'),
	array('To-Gai-Ru','West Mirianic Ocean','Yes','No'),
	array('Trog Bog','Troldhaugen','Yes','No'),
	array('Twisted Tunnels','Undermountain','No','Yes'),
	array('Undermountain','Yggdrasil','No','Yes'),
	array('Uuno','Whoville','No','Yes'),
	array('Valley of Lost Honor','Waterdeep','No','Yes'),
	array('Walk of Clouds','West Mirianic Ocean','Yes','No'),
	array('West Mirianic Ocean','Zeboims Deep','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

// Custom footer not changed by edit tool
InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);

// Copy the smallmap-sample to the cache-directory to avoid a screwed variantpage (there is no smallmap available)
if (!file_exists('variants/'.$this->name.'/cache/sampleMap.png'))
	copy ('variants/'.$this->name.'/resources/sampleMap.png','variants/'.$this->name.'/cache/sampleMap.png');

?>





