<?php
/*
    Copyright (C) 2004-2010 Kestas J. Kuliukas

	This file is part of webDiplomacy.

    webDiplomacy is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    webDiplomacy is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with webDiplomacy.  If not, see <http://www.gnu.org/licenses/>.
 */

defined('IN_CODE') or die('This script can not be run by itself.');
//chdir("../.."); define('IN_CODE', true);

/**
 * Installs Classic map data
 */

require_once("variants/install.php");

InstallTerritory::$Territories=array();
new InstallTerritory('Clyde', 'Coast', 'No', 0, 299, 336, 160, 109);
new InstallTerritory('Edinburgh', 'Coast', 'Yes', 1, 346, 347, 175, 112);
new InstallTerritory('Liverpool', 'Coast', 'Yes', 2, 315, 413, 170, 144);
new InstallTerritory('Yorkshire', 'Coast', 'No', 0, 355, 440, 184, 150);
new InstallTerritory('Wales', 'Coast', 'No', 0, 294, 473, 154, 169);
new InstallTerritory('London', 'Coast', 'Yes', 3, 361, 481, 186, 175);
new InstallTerritory('Portugal', 'Coast', 'Yes', 4, 91, 718, 60, 305);
new InstallTerritory('Spain', 'Coast', 'Yes', 5, 177, 794, 100, 324);
new InstallTerritory('North Africa', 'Coast', 'No', 0, 181, 949, 118, 386);
new InstallTerritory('Tunis', 'Coast', 'Yes', 6, 434, 961, 212, 390);
new InstallTerritory('Naples', 'Coast', 'Yes', 7, 570, 864, 298, 362);
new InstallTerritory('Rome', 'Coast', 'Yes', 8, 522, 808, 272, 332);
new InstallTerritory('Tuscany', 'Coast', 'No', 0, 485, 767, 256, 309);
new InstallTerritory('Piedmont', 'Coast', 'No', 0, 441, 694, 228, 279);
new InstallTerritory('Venice', 'Coast', 'Yes', 9, 501, 717, 261, 289);
new InstallTerritory('Apulia', 'Coast', 'No', 0, 591, 825, 305, 343);
new InstallTerritory('Greece', 'Coast', 'Yes', 10, 678, 863, 358, 359);
new InstallTerritory('Albania', 'Coast', 'No', 0, 640, 827, 344, 337);
new InstallTerritory('Serbia', 'Land', 'Yes', 11, 667, 776, 354, 315);
new InstallTerritory('Bulgaria', 'Coast', 'Yes', 12, 740, 776, 396, 311);
new InstallTerritory('Rumania', 'Coast', 'Yes', 13, 717, 724, 422, 289);
new InstallTerritory('Constantinople', 'Coast', 'Yes', 14, 821, 852, 441, 341);
new InstallTerritory('Smyrna', 'Coast', 'Yes', 15, 899, 895, 480, 360);
new InstallTerritory('Ankara', 'Coast', 'Yes', 16, 986, 816, 498, 325);
new InstallTerritory('Armenia', 'Coast', 'No', 0, 1073, 785, 572, 323);
new InstallTerritory('Syria', 'Coast', 'No', 0, 1045, 938, 559, 381);
new InstallTerritory('Sevastopol', 'Coast', 'Yes', 17, 923, 595, 500, 244);
new InstallTerritory('Ukraine', 'Land', 'No', 0, 779, 579, 418, 223);
new InstallTerritory('Warsaw', 'Land', 'Yes', 18, 683, 547, 354, 212);
new InstallTerritory('Livonia', 'Coast', 'No', 0, 719, 430, 374, 168);
new InstallTerritory('Moscow', 'Land', 'Yes', 19, 830, 465, 490, 155);
new InstallTerritory('St. Petersburg', 'Coast', 'Yes', 20, 837, 309, 445, 104);
new InstallTerritory('Finland', 'Coast', 'No', 0, 702, 263, 367, 109);
new InstallTerritory('Sweden', 'Coast', 'Yes', 21, 587, 274, 313, 87);
new InstallTerritory('Norway', 'Coast', 'Yes', 22, 518, 270, 271, 100);
new InstallTerritory('Denmark', 'Coast', 'Yes', 23, 501, 422, 264, 156);
new InstallTerritory('Kiel', 'Coast', 'Yes', 24, 485, 516, 256, 200);
new InstallTerritory('Berlin', 'Coast', 'Yes', 25, 551, 477, 292, 193);
new InstallTerritory('Prussia', 'Coast', 'No', 0, 621, 481, 329, 192);
new InstallTerritory('Silesia', 'Land', 'No', 0, 589, 545, 304, 217);
new InstallTerritory('Munich', 'Land', 'Yes', 26, 489, 581, 248, 232);
new InstallTerritory('Ruhr', 'Land', 'No', 0, 448, 545, 234, 214);
new InstallTerritory('Holland', 'Coast', 'Yes', 27, 440, 488, 234, 186);
new InstallTerritory('Belgium', 'Coast', 'Yes', 28, 410, 551, 215, 205);
new InstallTerritory('Picardy', 'Coast', 'No', 0, 359, 559, 189, 214);
new InstallTerritory('Brest', 'Coast', 'Yes', 29, 291, 583, 146, 223);
new InstallTerritory('Paris', 'Land', 'Yes', 30, 336, 620, 179, 238);
new InstallTerritory('Burgundy', 'Land', 'No', 0, 404, 626, 206, 248);
new InstallTerritory('Marseilles', 'Coast', 'Yes', 31, 390, 689, 183, 286);
new InstallTerritory('Gascony', 'Coast', 'No', 0, 301, 679, 150, 274);
new InstallTerritory('Barents Sea', 'Sea', 'No', 0, 836, 33, 420, 20);
new InstallTerritory('Norwegian Sea', 'Sea', 'No', 0, 452, 109, 268, 35);
new InstallTerritory('North Sea', 'Sea', 'No', 0, 414, 378, 216, 136);
new InstallTerritory('Skagerrack', 'Sea', 'No', 0, 516, 363, 279, 133);
new InstallTerritory('Heligoland Bight', 'Sea', 'No', 0, 460, 447, 250, 167);
new InstallTerritory('Baltic Sea', 'Sea', 'No', 0, 621, 434, 338, 175);
new InstallTerritory('Gulf of Bothnia', 'Sea', 'No', 0, 653, 348, 362, 131);
new InstallTerritory('North Atlantic Ocean', 'Sea', 'No', 0, 153, 237, 78, 87);
new InstallTerritory('Irish Sea', 'Sea', 'No', 0, 218, 478, 110, 178);
new InstallTerritory('English Channel', 'Sea', 'No', 0, 273, 527, 153, 198);
new InstallTerritory('Mid-Atlantic Ocean', 'Sea', 'No', 0, 106, 581, 81, 247);
new InstallTerritory('Western Mediterranean', 'Sea', 'No', 0, 327, 858, 186, 363);
new InstallTerritory('Gulf of Lyons', 'Sea', 'No', 0, 366, 774, 205, 323);
new InstallTerritory('Tyrrhenian Sea', 'Sea', 'No', 0, 488, 849, 250, 348);
new InstallTerritory('Ionian Sea', 'Sea', 'No', 0, 602, 947, 325, 384);
new InstallTerritory('Adriatic Sea', 'Sea', 'No', 0, 564, 773, 311, 319);
new InstallTerritory('Aegean Sea', 'Sea', 'No', 0, 740, 863, 400, 378);
new InstallTerritory('Eastern Mediterranean', 'Sea', 'No', 0, 860, 972, 454, 391);
new InstallTerritory('Black Sea', 'Sea', 'No', 0, 905, 743, 469, 300);
new InstallTerritory('Tyrolia', 'Land', 'No', 0, 538, 641, 273, 260);
new InstallTerritory('Bohemia', 'Land', 'No', 0, 562, 590, 292, 232);
new InstallTerritory('Vienna', 'Land', 'Yes', 32, 602, 627, 319, 246);
new InstallTerritory('Trieste', 'Coast', 'Yes', 33, 593, 730, 311, 291);
new InstallTerritory('Budapest', 'Land', 'Yes', 34, 681, 668, 354, 271);
new InstallTerritory('Galicia', 'Land', 'No', 0, 718, 610, 365, 237);
new InstallTerritory('Spain (North Coast)', 'Coast', 'No', 0, 193, 685, 94, 277);
new InstallTerritory('Spain (South Coast)', 'Coast', 'No', 0, 191, 832, 106, 345);
new InstallTerritory('St. Petersburg (North Coast)', 'Coast', 'No', 0, 828, 111, 448, 59);
new InstallTerritory('St. Petersburg (South Coast)', 'Coast', 'No', 0, 780, 355, 398, 133);
new InstallTerritory('Bulgaria (North Coast)', 'Coast', 'No', 0, 785, 762, 420, 304);
new InstallTerritory('Bulgaria (South Coast)', 'Coast', 'No', 0, 749, 815, 397, 329);
InstallTerritory::$Territories['Edinburgh']->addBorder(InstallTerritory::$Territories['Clyde'], 'Yes', 'Yes');
InstallTerritory::$Territories['Liverpool']->addBorder(InstallTerritory::$Territories['Clyde'], 'Yes', 'Yes');
InstallTerritory::$Territories['Norwegian Sea']->addBorder(InstallTerritory::$Territories['Clyde'], 'Yes', 'No');
InstallTerritory::$Territories['North Atlantic Ocean']->addBorder(InstallTerritory::$Territories['Clyde'], 'Yes', 'No');
InstallTerritory::$Territories['Clyde']->addBorder(InstallTerritory::$Territories['Edinburgh'], 'Yes', 'Yes');
InstallTerritory::$Territories['Liverpool']->addBorder(InstallTerritory::$Territories['Edinburgh'], 'No', 'Yes');
InstallTerritory::$Territories['Yorkshire']->addBorder(InstallTerritory::$Territories['Edinburgh'], 'Yes', 'Yes');
InstallTerritory::$Territories['Norwegian Sea']->addBorder(InstallTerritory::$Territories['Edinburgh'], 'Yes', 'No');
InstallTerritory::$Territories['North Sea']->addBorder(InstallTerritory::$Territories['Edinburgh'], 'Yes', 'No');
InstallTerritory::$Territories['Clyde']->addBorder(InstallTerritory::$Territories['Liverpool'], 'Yes', 'Yes');
InstallTerritory::$Territories['Edinburgh']->addBorder(InstallTerritory::$Territories['Liverpool'], 'No', 'Yes');
InstallTerritory::$Territories['Yorkshire']->addBorder(InstallTerritory::$Territories['Liverpool'], 'No', 'Yes');
InstallTerritory::$Territories['Wales']->addBorder(InstallTerritory::$Territories['Liverpool'], 'Yes', 'Yes');
InstallTerritory::$Territories['North Atlantic Ocean']->addBorder(InstallTerritory::$Territories['Liverpool'], 'Yes', 'No');
InstallTerritory::$Territories['Irish Sea']->addBorder(InstallTerritory::$Territories['Liverpool'], 'Yes', 'No');
InstallTerritory::$Territories['Edinburgh']->addBorder(InstallTerritory::$Territories['Yorkshire'], 'Yes', 'Yes');
InstallTerritory::$Territories['Liverpool']->addBorder(InstallTerritory::$Territories['Yorkshire'], 'No', 'Yes');
InstallTerritory::$Territories['Wales']->addBorder(InstallTerritory::$Territories['Yorkshire'], 'No', 'Yes');
InstallTerritory::$Territories['London']->addBorder(InstallTerritory::$Territories['Yorkshire'], 'Yes', 'Yes');
InstallTerritory::$Territories['North Sea']->addBorder(InstallTerritory::$Territories['Yorkshire'], 'Yes', 'No');
InstallTerritory::$Territories['Liverpool']->addBorder(InstallTerritory::$Territories['Wales'], 'Yes', 'Yes');
InstallTerritory::$Territories['Yorkshire']->addBorder(InstallTerritory::$Territories['Wales'], 'No', 'Yes');
InstallTerritory::$Territories['London']->addBorder(InstallTerritory::$Territories['Wales'], 'Yes', 'Yes');
InstallTerritory::$Territories['Irish Sea']->addBorder(InstallTerritory::$Territories['Wales'], 'Yes', 'No');
InstallTerritory::$Territories['English Channel']->addBorder(InstallTerritory::$Territories['Wales'], 'Yes', 'No');
InstallTerritory::$Territories['Yorkshire']->addBorder(InstallTerritory::$Territories['London'], 'Yes', 'Yes');
InstallTerritory::$Territories['Wales']->addBorder(InstallTerritory::$Territories['London'], 'Yes', 'Yes');
InstallTerritory::$Territories['North Sea']->addBorder(InstallTerritory::$Territories['London'], 'Yes', 'No');
InstallTerritory::$Territories['English Channel']->addBorder(InstallTerritory::$Territories['London'], 'Yes', 'No');
InstallTerritory::$Territories['Spain']->addBorder(InstallTerritory::$Territories['Portugal'], 'No', 'Yes');
InstallTerritory::$Territories['Mid-Atlantic Ocean']->addBorder(InstallTerritory::$Territories['Portugal'], 'Yes', 'No');
InstallTerritory::$Territories['Spain (North Coast)']->addBorder(InstallTerritory::$Territories['Portugal'], 'Yes', 'No');
InstallTerritory::$Territories['Spain (South Coast)']->addBorder(InstallTerritory::$Territories['Portugal'], 'Yes', 'No');
InstallTerritory::$Territories['Portugal']->addBorder(InstallTerritory::$Territories['Spain'], 'No', 'Yes');
InstallTerritory::$Territories['Marseilles']->addBorder(InstallTerritory::$Territories['Spain'], 'No', 'Yes');
InstallTerritory::$Territories['Gascony']->addBorder(InstallTerritory::$Territories['Spain'], 'No', 'Yes');
InstallTerritory::$Territories['Tunis']->addBorder(InstallTerritory::$Territories['North Africa'], 'Yes', 'Yes');
InstallTerritory::$Territories['Mid-Atlantic Ocean']->addBorder(InstallTerritory::$Territories['North Africa'], 'Yes', 'No');
InstallTerritory::$Territories['Western Mediterranean']->addBorder(InstallTerritory::$Territories['North Africa'], 'Yes', 'No');
InstallTerritory::$Territories['North Africa']->addBorder(InstallTerritory::$Territories['Tunis'], 'Yes', 'Yes');
InstallTerritory::$Territories['Western Mediterranean']->addBorder(InstallTerritory::$Territories['Tunis'], 'Yes', 'No');
InstallTerritory::$Territories['Tyrrhenian Sea']->addBorder(InstallTerritory::$Territories['Tunis'], 'Yes', 'No');
InstallTerritory::$Territories['Ionian Sea']->addBorder(InstallTerritory::$Territories['Tunis'], 'Yes', 'No');
InstallTerritory::$Territories['Rome']->addBorder(InstallTerritory::$Territories['Naples'], 'Yes', 'Yes');
InstallTerritory::$Territories['Apulia']->addBorder(InstallTerritory::$Territories['Naples'], 'Yes', 'Yes');
InstallTerritory::$Territories['Tyrrhenian Sea']->addBorder(InstallTerritory::$Territories['Naples'], 'Yes', 'No');
InstallTerritory::$Territories['Ionian Sea']->addBorder(InstallTerritory::$Territories['Naples'], 'Yes', 'No');
InstallTerritory::$Territories['Naples']->addBorder(InstallTerritory::$Territories['Rome'], 'Yes', 'Yes');
InstallTerritory::$Territories['Tuscany']->addBorder(InstallTerritory::$Territories['Rome'], 'Yes', 'Yes');
InstallTerritory::$Territories['Venice']->addBorder(InstallTerritory::$Territories['Rome'], 'No', 'Yes');
InstallTerritory::$Territories['Apulia']->addBorder(InstallTerritory::$Territories['Rome'], 'No', 'Yes');
InstallTerritory::$Territories['Tyrrhenian Sea']->addBorder(InstallTerritory::$Territories['Rome'], 'Yes', 'No');
InstallTerritory::$Territories['Rome']->addBorder(InstallTerritory::$Territories['Tuscany'], 'Yes', 'Yes');
InstallTerritory::$Territories['Piedmont']->addBorder(InstallTerritory::$Territories['Tuscany'], 'Yes', 'Yes');
InstallTerritory::$Territories['Venice']->addBorder(InstallTerritory::$Territories['Tuscany'], 'No', 'Yes');
InstallTerritory::$Territories['Gulf of Lyons']->addBorder(InstallTerritory::$Territories['Tuscany'], 'Yes', 'No');
InstallTerritory::$Territories['Tyrrhenian Sea']->addBorder(InstallTerritory::$Territories['Tuscany'], 'Yes', 'No');
InstallTerritory::$Territories['Tuscany']->addBorder(InstallTerritory::$Territories['Piedmont'], 'Yes', 'Yes');
InstallTerritory::$Territories['Venice']->addBorder(InstallTerritory::$Territories['Piedmont'], 'No', 'Yes');
InstallTerritory::$Territories['Marseilles']->addBorder(InstallTerritory::$Territories['Piedmont'], 'Yes', 'Yes');
InstallTerritory::$Territories['Gulf of Lyons']->addBorder(InstallTerritory::$Territories['Piedmont'], 'Yes', 'No');
InstallTerritory::$Territories['Tyrolia']->addBorder(InstallTerritory::$Territories['Piedmont'], 'No', 'Yes');
InstallTerritory::$Territories['Rome']->addBorder(InstallTerritory::$Territories['Venice'], 'No', 'Yes');
InstallTerritory::$Territories['Tuscany']->addBorder(InstallTerritory::$Territories['Venice'], 'No', 'Yes');
InstallTerritory::$Territories['Piedmont']->addBorder(InstallTerritory::$Territories['Venice'], 'No', 'Yes');
InstallTerritory::$Territories['Apulia']->addBorder(InstallTerritory::$Territories['Venice'], 'Yes', 'Yes');
InstallTerritory::$Territories['Adriatic Sea']->addBorder(InstallTerritory::$Territories['Venice'], 'Yes', 'No');
InstallTerritory::$Territories['Tyrolia']->addBorder(InstallTerritory::$Territories['Venice'], 'No', 'Yes');
InstallTerritory::$Territories['Trieste']->addBorder(InstallTerritory::$Territories['Venice'], 'Yes', 'Yes');
InstallTerritory::$Territories['Naples']->addBorder(InstallTerritory::$Territories['Apulia'], 'Yes', 'Yes');
InstallTerritory::$Territories['Rome']->addBorder(InstallTerritory::$Territories['Apulia'], 'No', 'Yes');
InstallTerritory::$Territories['Venice']->addBorder(InstallTerritory::$Territories['Apulia'], 'Yes', 'Yes');
InstallTerritory::$Territories['Ionian Sea']->addBorder(InstallTerritory::$Territories['Apulia'], 'Yes', 'No');
InstallTerritory::$Territories['Adriatic Sea']->addBorder(InstallTerritory::$Territories['Apulia'], 'Yes', 'No');
InstallTerritory::$Territories['Albania']->addBorder(InstallTerritory::$Territories['Greece'], 'Yes', 'Yes');
InstallTerritory::$Territories['Serbia']->addBorder(InstallTerritory::$Territories['Greece'], 'No', 'Yes');
InstallTerritory::$Territories['Bulgaria']->addBorder(InstallTerritory::$Territories['Greece'], 'No', 'Yes');
InstallTerritory::$Territories['Ionian Sea']->addBorder(InstallTerritory::$Territories['Greece'], 'Yes', 'No');
InstallTerritory::$Territories['Aegean Sea']->addBorder(InstallTerritory::$Territories['Greece'], 'Yes', 'No');
InstallTerritory::$Territories['Bulgaria (South Coast)']->addBorder(InstallTerritory::$Territories['Greece'], 'Yes', 'No');
InstallTerritory::$Territories['Greece']->addBorder(InstallTerritory::$Territories['Albania'], 'Yes', 'Yes');
InstallTerritory::$Territories['Serbia']->addBorder(InstallTerritory::$Territories['Albania'], 'No', 'Yes');
InstallTerritory::$Territories['Ionian Sea']->addBorder(InstallTerritory::$Territories['Albania'], 'Yes', 'No');
InstallTerritory::$Territories['Adriatic Sea']->addBorder(InstallTerritory::$Territories['Albania'], 'Yes', 'No');
InstallTerritory::$Territories['Trieste']->addBorder(InstallTerritory::$Territories['Albania'], 'Yes', 'Yes');
InstallTerritory::$Territories['Greece']->addBorder(InstallTerritory::$Territories['Serbia'], 'No', 'Yes');
InstallTerritory::$Territories['Albania']->addBorder(InstallTerritory::$Territories['Serbia'], 'No', 'Yes');
InstallTerritory::$Territories['Bulgaria']->addBorder(InstallTerritory::$Territories['Serbia'], 'No', 'Yes');
InstallTerritory::$Territories['Rumania']->addBorder(InstallTerritory::$Territories['Serbia'], 'No', 'Yes');
InstallTerritory::$Territories['Trieste']->addBorder(InstallTerritory::$Territories['Serbia'], 'No', 'Yes');
InstallTerritory::$Territories['Budapest']->addBorder(InstallTerritory::$Territories['Serbia'], 'No', 'Yes');
InstallTerritory::$Territories['Greece']->addBorder(InstallTerritory::$Territories['Bulgaria'], 'No', 'Yes');
InstallTerritory::$Territories['Serbia']->addBorder(InstallTerritory::$Territories['Bulgaria'], 'No', 'Yes');
InstallTerritory::$Territories['Rumania']->addBorder(InstallTerritory::$Territories['Bulgaria'], 'No', 'Yes');
InstallTerritory::$Territories['Constantinople']->addBorder(InstallTerritory::$Territories['Bulgaria'], 'No', 'Yes');
InstallTerritory::$Territories['Serbia']->addBorder(InstallTerritory::$Territories['Rumania'], 'No', 'Yes');
InstallTerritory::$Territories['Bulgaria']->addBorder(InstallTerritory::$Territories['Rumania'], 'No', 'Yes');
InstallTerritory::$Territories['Sevastopol']->addBorder(InstallTerritory::$Territories['Rumania'], 'Yes', 'Yes');
InstallTerritory::$Territories['Ukraine']->addBorder(InstallTerritory::$Territories['Rumania'], 'No', 'Yes');
InstallTerritory::$Territories['Black Sea']->addBorder(InstallTerritory::$Territories['Rumania'], 'Yes', 'No');
InstallTerritory::$Territories['Budapest']->addBorder(InstallTerritory::$Territories['Rumania'], 'No', 'Yes');
InstallTerritory::$Territories['Galicia']->addBorder(InstallTerritory::$Territories['Rumania'], 'No', 'Yes');
InstallTerritory::$Territories['Bulgaria (North Coast)']->addBorder(InstallTerritory::$Territories['Rumania'], 'Yes', 'No');
InstallTerritory::$Territories['Bulgaria']->addBorder(InstallTerritory::$Territories['Constantinople'], 'No', 'Yes');
InstallTerritory::$Territories['Smyrna']->addBorder(InstallTerritory::$Territories['Constantinople'], 'Yes', 'Yes');
InstallTerritory::$Territories['Ankara']->addBorder(InstallTerritory::$Territories['Constantinople'], 'Yes', 'Yes');
InstallTerritory::$Territories['Aegean Sea']->addBorder(InstallTerritory::$Territories['Constantinople'], 'Yes', 'No');
InstallTerritory::$Territories['Black Sea']->addBorder(InstallTerritory::$Territories['Constantinople'], 'Yes', 'No');
InstallTerritory::$Territories['Bulgaria (North Coast)']->addBorder(InstallTerritory::$Territories['Constantinople'], 'Yes', 'No');
InstallTerritory::$Territories['Bulgaria (South Coast)']->addBorder(InstallTerritory::$Territories['Constantinople'], 'Yes', 'No');
InstallTerritory::$Territories['Constantinople']->addBorder(InstallTerritory::$Territories['Smyrna'], 'Yes', 'Yes');
InstallTerritory::$Territories['Ankara']->addBorder(InstallTerritory::$Territories['Smyrna'], 'No', 'Yes');
InstallTerritory::$Territories['Armenia']->addBorder(InstallTerritory::$Territories['Smyrna'], 'No', 'Yes');
InstallTerritory::$Territories['Syria']->addBorder(InstallTerritory::$Territories['Smyrna'], 'Yes', 'Yes');
InstallTerritory::$Territories['Aegean Sea']->addBorder(InstallTerritory::$Territories['Smyrna'], 'Yes', 'No');
InstallTerritory::$Territories['Eastern Mediterranean']->addBorder(InstallTerritory::$Territories['Smyrna'], 'Yes', 'No');
InstallTerritory::$Territories['Constantinople']->addBorder(InstallTerritory::$Territories['Ankara'], 'Yes', 'Yes');
InstallTerritory::$Territories['Smyrna']->addBorder(InstallTerritory::$Territories['Ankara'], 'No', 'Yes');
InstallTerritory::$Territories['Armenia']->addBorder(InstallTerritory::$Territories['Ankara'], 'Yes', 'Yes');
InstallTerritory::$Territories['Black Sea']->addBorder(InstallTerritory::$Territories['Ankara'], 'Yes', 'No');
InstallTerritory::$Territories['Smyrna']->addBorder(InstallTerritory::$Territories['Armenia'], 'No', 'Yes');
InstallTerritory::$Territories['Ankara']->addBorder(InstallTerritory::$Territories['Armenia'], 'Yes', 'Yes');
InstallTerritory::$Territories['Syria']->addBorder(InstallTerritory::$Territories['Armenia'], 'No', 'Yes');
InstallTerritory::$Territories['Sevastopol']->addBorder(InstallTerritory::$Territories['Armenia'], 'Yes', 'Yes');
InstallTerritory::$Territories['Black Sea']->addBorder(InstallTerritory::$Territories['Armenia'], 'Yes', 'No');
InstallTerritory::$Territories['Smyrna']->addBorder(InstallTerritory::$Territories['Syria'], 'Yes', 'Yes');
InstallTerritory::$Territories['Armenia']->addBorder(InstallTerritory::$Territories['Syria'], 'No', 'Yes');
InstallTerritory::$Territories['Eastern Mediterranean']->addBorder(InstallTerritory::$Territories['Syria'], 'Yes', 'No');
InstallTerritory::$Territories['Rumania']->addBorder(InstallTerritory::$Territories['Sevastopol'], 'Yes', 'Yes');
InstallTerritory::$Territories['Armenia']->addBorder(InstallTerritory::$Territories['Sevastopol'], 'Yes', 'Yes');
InstallTerritory::$Territories['Ukraine']->addBorder(InstallTerritory::$Territories['Sevastopol'], 'No', 'Yes');
InstallTerritory::$Territories['Moscow']->addBorder(InstallTerritory::$Territories['Sevastopol'], 'No', 'Yes');
InstallTerritory::$Territories['Black Sea']->addBorder(InstallTerritory::$Territories['Sevastopol'], 'Yes', 'No');
InstallTerritory::$Territories['Rumania']->addBorder(InstallTerritory::$Territories['Ukraine'], 'No', 'Yes');
InstallTerritory::$Territories['Sevastopol']->addBorder(InstallTerritory::$Territories['Ukraine'], 'No', 'Yes');
InstallTerritory::$Territories['Warsaw']->addBorder(InstallTerritory::$Territories['Ukraine'], 'No', 'Yes');
InstallTerritory::$Territories['Moscow']->addBorder(InstallTerritory::$Territories['Ukraine'], 'No', 'Yes');
InstallTerritory::$Territories['Galicia']->addBorder(InstallTerritory::$Territories['Ukraine'], 'No', 'Yes');
InstallTerritory::$Territories['Ukraine']->addBorder(InstallTerritory::$Territories['Warsaw'], 'No', 'Yes');
InstallTerritory::$Territories['Livonia']->addBorder(InstallTerritory::$Territories['Warsaw'], 'No', 'Yes');
InstallTerritory::$Territories['Moscow']->addBorder(InstallTerritory::$Territories['Warsaw'], 'No', 'Yes');
InstallTerritory::$Territories['Prussia']->addBorder(InstallTerritory::$Territories['Warsaw'], 'No', 'Yes');
InstallTerritory::$Territories['Silesia']->addBorder(InstallTerritory::$Territories['Warsaw'], 'No', 'Yes');
InstallTerritory::$Territories['Galicia']->addBorder(InstallTerritory::$Territories['Warsaw'], 'No', 'Yes');
InstallTerritory::$Territories['Warsaw']->addBorder(InstallTerritory::$Territories['Livonia'], 'No', 'Yes');
InstallTerritory::$Territories['Moscow']->addBorder(InstallTerritory::$Territories['Livonia'], 'No', 'Yes');
InstallTerritory::$Territories['St. Petersburg']->addBorder(InstallTerritory::$Territories['Livonia'], 'No', 'Yes');
InstallTerritory::$Territories['Prussia']->addBorder(InstallTerritory::$Territories['Livonia'], 'Yes', 'Yes');
InstallTerritory::$Territories['Baltic Sea']->addBorder(InstallTerritory::$Territories['Livonia'], 'Yes', 'No');
InstallTerritory::$Territories['Gulf of Bothnia']->addBorder(InstallTerritory::$Territories['Livonia'], 'Yes', 'No');
InstallTerritory::$Territories['St. Petersburg (South Coast)']->addBorder(InstallTerritory::$Territories['Livonia'], 'Yes', 'No');
InstallTerritory::$Territories['Sevastopol']->addBorder(InstallTerritory::$Territories['Moscow'], 'No', 'Yes');
InstallTerritory::$Territories['Ukraine']->addBorder(InstallTerritory::$Territories['Moscow'], 'No', 'Yes');
InstallTerritory::$Territories['Warsaw']->addBorder(InstallTerritory::$Territories['Moscow'], 'No', 'Yes');
InstallTerritory::$Territories['Livonia']->addBorder(InstallTerritory::$Territories['Moscow'], 'No', 'Yes');
InstallTerritory::$Territories['St. Petersburg']->addBorder(InstallTerritory::$Territories['Moscow'], 'No', 'Yes');
InstallTerritory::$Territories['Livonia']->addBorder(InstallTerritory::$Territories['St. Petersburg'], 'No', 'Yes');
InstallTerritory::$Territories['Moscow']->addBorder(InstallTerritory::$Territories['St. Petersburg'], 'No', 'Yes');
InstallTerritory::$Territories['Finland']->addBorder(InstallTerritory::$Territories['St. Petersburg'], 'No', 'Yes');
InstallTerritory::$Territories['Norway']->addBorder(InstallTerritory::$Territories['St. Petersburg'], 'No', 'Yes');
InstallTerritory::$Territories['St. Petersburg']->addBorder(InstallTerritory::$Territories['Finland'], 'No', 'Yes');
InstallTerritory::$Territories['Sweden']->addBorder(InstallTerritory::$Territories['Finland'], 'Yes', 'Yes');
InstallTerritory::$Territories['Norway']->addBorder(InstallTerritory::$Territories['Finland'], 'No', 'Yes');
InstallTerritory::$Territories['Gulf of Bothnia']->addBorder(InstallTerritory::$Territories['Finland'], 'Yes', 'No');
InstallTerritory::$Territories['St. Petersburg (South Coast)']->addBorder(InstallTerritory::$Territories['Finland'], 'Yes', 'No');
InstallTerritory::$Territories['Finland']->addBorder(InstallTerritory::$Territories['Sweden'], 'Yes', 'Yes');
InstallTerritory::$Territories['Norway']->addBorder(InstallTerritory::$Territories['Sweden'], 'Yes', 'Yes');
InstallTerritory::$Territories['Denmark']->addBorder(InstallTerritory::$Territories['Sweden'], 'Yes', 'Yes');
InstallTerritory::$Territories['Skagerrack']->addBorder(InstallTerritory::$Territories['Sweden'], 'Yes', 'No');
InstallTerritory::$Territories['Baltic Sea']->addBorder(InstallTerritory::$Territories['Sweden'], 'Yes', 'No');
InstallTerritory::$Territories['Gulf of Bothnia']->addBorder(InstallTerritory::$Territories['Sweden'], 'Yes', 'No');
InstallTerritory::$Territories['St. Petersburg']->addBorder(InstallTerritory::$Territories['Norway'], 'No', 'Yes');
InstallTerritory::$Territories['Finland']->addBorder(InstallTerritory::$Territories['Norway'], 'No', 'Yes');
InstallTerritory::$Territories['Sweden']->addBorder(InstallTerritory::$Territories['Norway'], 'Yes', 'Yes');
InstallTerritory::$Territories['Barents Sea']->addBorder(InstallTerritory::$Territories['Norway'], 'Yes', 'No');
InstallTerritory::$Territories['Norwegian Sea']->addBorder(InstallTerritory::$Territories['Norway'], 'Yes', 'No');
InstallTerritory::$Territories['North Sea']->addBorder(InstallTerritory::$Territories['Norway'], 'Yes', 'No');
InstallTerritory::$Territories['Skagerrack']->addBorder(InstallTerritory::$Territories['Norway'], 'Yes', 'No');
InstallTerritory::$Territories['St. Petersburg (North Coast)']->addBorder(InstallTerritory::$Territories['Norway'], 'Yes', 'No');
InstallTerritory::$Territories['Sweden']->addBorder(InstallTerritory::$Territories['Denmark'], 'Yes', 'Yes');
InstallTerritory::$Territories['Kiel']->addBorder(InstallTerritory::$Territories['Denmark'], 'Yes', 'Yes');
InstallTerritory::$Territories['North Sea']->addBorder(InstallTerritory::$Territories['Denmark'], 'Yes', 'No');
InstallTerritory::$Territories['Skagerrack']->addBorder(InstallTerritory::$Territories['Denmark'], 'Yes', 'No');
InstallTerritory::$Territories['Heligoland Bight']->addBorder(InstallTerritory::$Territories['Denmark'], 'Yes', 'No');
InstallTerritory::$Territories['Baltic Sea']->addBorder(InstallTerritory::$Territories['Denmark'], 'Yes', 'No');
InstallTerritory::$Territories['Denmark']->addBorder(InstallTerritory::$Territories['Kiel'], 'Yes', 'Yes');
InstallTerritory::$Territories['Berlin']->addBorder(InstallTerritory::$Territories['Kiel'], 'Yes', 'Yes');
InstallTerritory::$Territories['Munich']->addBorder(InstallTerritory::$Territories['Kiel'], 'No', 'Yes');
InstallTerritory::$Territories['Ruhr']->addBorder(InstallTerritory::$Territories['Kiel'], 'No', 'Yes');
InstallTerritory::$Territories['Holland']->addBorder(InstallTerritory::$Territories['Kiel'], 'Yes', 'Yes');
InstallTerritory::$Territories['Heligoland Bight']->addBorder(InstallTerritory::$Territories['Kiel'], 'Yes', 'No');
InstallTerritory::$Territories['Baltic Sea']->addBorder(InstallTerritory::$Territories['Kiel'], 'Yes', 'No');
InstallTerritory::$Territories['Kiel']->addBorder(InstallTerritory::$Territories['Berlin'], 'Yes', 'Yes');
InstallTerritory::$Territories['Prussia']->addBorder(InstallTerritory::$Territories['Berlin'], 'Yes', 'Yes');
InstallTerritory::$Territories['Silesia']->addBorder(InstallTerritory::$Territories['Berlin'], 'No', 'Yes');
InstallTerritory::$Territories['Munich']->addBorder(InstallTerritory::$Territories['Berlin'], 'No', 'Yes');
InstallTerritory::$Territories['Baltic Sea']->addBorder(InstallTerritory::$Territories['Berlin'], 'Yes', 'No');
InstallTerritory::$Territories['Warsaw']->addBorder(InstallTerritory::$Territories['Prussia'], 'No', 'Yes');
InstallTerritory::$Territories['Livonia']->addBorder(InstallTerritory::$Territories['Prussia'], 'Yes', 'Yes');
InstallTerritory::$Territories['Berlin']->addBorder(InstallTerritory::$Territories['Prussia'], 'Yes', 'Yes');
InstallTerritory::$Territories['Silesia']->addBorder(InstallTerritory::$Territories['Prussia'], 'No', 'Yes');
InstallTerritory::$Territories['Baltic Sea']->addBorder(InstallTerritory::$Territories['Prussia'], 'Yes', 'No');
InstallTerritory::$Territories['Warsaw']->addBorder(InstallTerritory::$Territories['Silesia'], 'No', 'Yes');
InstallTerritory::$Territories['Berlin']->addBorder(InstallTerritory::$Territories['Silesia'], 'No', 'Yes');
InstallTerritory::$Territories['Prussia']->addBorder(InstallTerritory::$Territories['Silesia'], 'No', 'Yes');
InstallTerritory::$Territories['Munich']->addBorder(InstallTerritory::$Territories['Silesia'], 'No', 'Yes');
InstallTerritory::$Territories['Bohemia']->addBorder(InstallTerritory::$Territories['Silesia'], 'No', 'Yes');
InstallTerritory::$Territories['Galicia']->addBorder(InstallTerritory::$Territories['Silesia'], 'No', 'Yes');
InstallTerritory::$Territories['Kiel']->addBorder(InstallTerritory::$Territories['Munich'], 'No', 'Yes');
InstallTerritory::$Territories['Berlin']->addBorder(InstallTerritory::$Territories['Munich'], 'No', 'Yes');
InstallTerritory::$Territories['Silesia']->addBorder(InstallTerritory::$Territories['Munich'], 'No', 'Yes');
InstallTerritory::$Territories['Ruhr']->addBorder(InstallTerritory::$Territories['Munich'], 'No', 'Yes');
InstallTerritory::$Territories['Burgundy']->addBorder(InstallTerritory::$Territories['Munich'], 'No', 'Yes');
InstallTerritory::$Territories['Tyrolia']->addBorder(InstallTerritory::$Territories['Munich'], 'No', 'Yes');
InstallTerritory::$Territories['Bohemia']->addBorder(InstallTerritory::$Territories['Munich'], 'No', 'Yes');
InstallTerritory::$Territories['Kiel']->addBorder(InstallTerritory::$Territories['Ruhr'], 'No', 'Yes');
InstallTerritory::$Territories['Munich']->addBorder(InstallTerritory::$Territories['Ruhr'], 'No', 'Yes');
InstallTerritory::$Territories['Holland']->addBorder(InstallTerritory::$Territories['Ruhr'], 'No', 'Yes');
InstallTerritory::$Territories['Belgium']->addBorder(InstallTerritory::$Territories['Ruhr'], 'No', 'Yes');
InstallTerritory::$Territories['Burgundy']->addBorder(InstallTerritory::$Territories['Ruhr'], 'No', 'Yes');
InstallTerritory::$Territories['Kiel']->addBorder(InstallTerritory::$Territories['Holland'], 'Yes', 'Yes');
InstallTerritory::$Territories['Ruhr']->addBorder(InstallTerritory::$Territories['Holland'], 'No', 'Yes');
InstallTerritory::$Territories['Belgium']->addBorder(InstallTerritory::$Territories['Holland'], 'Yes', 'Yes');
InstallTerritory::$Territories['North Sea']->addBorder(InstallTerritory::$Territories['Holland'], 'Yes', 'No');
InstallTerritory::$Territories['Heligoland Bight']->addBorder(InstallTerritory::$Territories['Holland'], 'Yes', 'No');
InstallTerritory::$Territories['Ruhr']->addBorder(InstallTerritory::$Territories['Belgium'], 'No', 'Yes');
InstallTerritory::$Territories['Holland']->addBorder(InstallTerritory::$Territories['Belgium'], 'Yes', 'Yes');
InstallTerritory::$Territories['Picardy']->addBorder(InstallTerritory::$Territories['Belgium'], 'Yes', 'Yes');
InstallTerritory::$Territories['Burgundy']->addBorder(InstallTerritory::$Territories['Belgium'], 'No', 'Yes');
InstallTerritory::$Territories['North Sea']->addBorder(InstallTerritory::$Territories['Belgium'], 'Yes', 'No');
InstallTerritory::$Territories['English Channel']->addBorder(InstallTerritory::$Territories['Belgium'], 'Yes', 'No');
InstallTerritory::$Territories['Belgium']->addBorder(InstallTerritory::$Territories['Picardy'], 'Yes', 'Yes');
InstallTerritory::$Territories['Brest']->addBorder(InstallTerritory::$Territories['Picardy'], 'Yes', 'Yes');
InstallTerritory::$Territories['Paris']->addBorder(InstallTerritory::$Territories['Picardy'], 'No', 'Yes');
InstallTerritory::$Territories['Burgundy']->addBorder(InstallTerritory::$Territories['Picardy'], 'No', 'Yes');
InstallTerritory::$Territories['English Channel']->addBorder(InstallTerritory::$Territories['Picardy'], 'Yes', 'No');
InstallTerritory::$Territories['Picardy']->addBorder(InstallTerritory::$Territories['Brest'], 'Yes', 'Yes');
InstallTerritory::$Territories['Paris']->addBorder(InstallTerritory::$Territories['Brest'], 'No', 'Yes');
InstallTerritory::$Territories['Gascony']->addBorder(InstallTerritory::$Territories['Brest'], 'Yes', 'Yes');
InstallTerritory::$Territories['English Channel']->addBorder(InstallTerritory::$Territories['Brest'], 'Yes', 'No');
InstallTerritory::$Territories['Mid-Atlantic Ocean']->addBorder(InstallTerritory::$Territories['Brest'], 'Yes', 'No');
InstallTerritory::$Territories['Picardy']->addBorder(InstallTerritory::$Territories['Paris'], 'No', 'Yes');
InstallTerritory::$Territories['Brest']->addBorder(InstallTerritory::$Territories['Paris'], 'No', 'Yes');
InstallTerritory::$Territories['Burgundy']->addBorder(InstallTerritory::$Territories['Paris'], 'No', 'Yes');
InstallTerritory::$Territories['Gascony']->addBorder(InstallTerritory::$Territories['Paris'], 'No', 'Yes');
InstallTerritory::$Territories['Munich']->addBorder(InstallTerritory::$Territories['Burgundy'], 'No', 'Yes');
InstallTerritory::$Territories['Ruhr']->addBorder(InstallTerritory::$Territories['Burgundy'], 'No', 'Yes');
InstallTerritory::$Territories['Belgium']->addBorder(InstallTerritory::$Territories['Burgundy'], 'No', 'Yes');
InstallTerritory::$Territories['Picardy']->addBorder(InstallTerritory::$Territories['Burgundy'], 'No', 'Yes');
InstallTerritory::$Territories['Paris']->addBorder(InstallTerritory::$Territories['Burgundy'], 'No', 'Yes');
InstallTerritory::$Territories['Marseilles']->addBorder(InstallTerritory::$Territories['Burgundy'], 'No', 'Yes');
InstallTerritory::$Territories['Gascony']->addBorder(InstallTerritory::$Territories['Burgundy'], 'No', 'Yes');
InstallTerritory::$Territories['Spain']->addBorder(InstallTerritory::$Territories['Marseilles'], 'No', 'Yes');
InstallTerritory::$Territories['Piedmont']->addBorder(InstallTerritory::$Territories['Marseilles'], 'Yes', 'Yes');
InstallTerritory::$Territories['Burgundy']->addBorder(InstallTerritory::$Territories['Marseilles'], 'No', 'Yes');
InstallTerritory::$Territories['Gascony']->addBorder(InstallTerritory::$Territories['Marseilles'], 'No', 'Yes');
InstallTerritory::$Territories['Gulf of Lyons']->addBorder(InstallTerritory::$Territories['Marseilles'], 'Yes', 'No');
InstallTerritory::$Territories['Spain (South Coast)']->addBorder(InstallTerritory::$Territories['Marseilles'], 'Yes', 'No');
InstallTerritory::$Territories['Spain']->addBorder(InstallTerritory::$Territories['Gascony'], 'No', 'Yes');
InstallTerritory::$Territories['Brest']->addBorder(InstallTerritory::$Territories['Gascony'], 'Yes', 'Yes');
InstallTerritory::$Territories['Paris']->addBorder(InstallTerritory::$Territories['Gascony'], 'No', 'Yes');
InstallTerritory::$Territories['Burgundy']->addBorder(InstallTerritory::$Territories['Gascony'], 'No', 'Yes');
InstallTerritory::$Territories['Marseilles']->addBorder(InstallTerritory::$Territories['Gascony'], 'No', 'Yes');
InstallTerritory::$Territories['Mid-Atlantic Ocean']->addBorder(InstallTerritory::$Territories['Gascony'], 'Yes', 'No');
InstallTerritory::$Territories['Spain (North Coast)']->addBorder(InstallTerritory::$Territories['Gascony'], 'Yes', 'No');
InstallTerritory::$Territories['Norway']->addBorder(InstallTerritory::$Territories['Barents Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Norwegian Sea']->addBorder(InstallTerritory::$Territories['Barents Sea'], 'Yes', 'No');
InstallTerritory::$Territories['St. Petersburg (North Coast)']->addBorder(InstallTerritory::$Territories['Barents Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Clyde']->addBorder(InstallTerritory::$Territories['Norwegian Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Edinburgh']->addBorder(InstallTerritory::$Territories['Norwegian Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Norway']->addBorder(InstallTerritory::$Territories['Norwegian Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Barents Sea']->addBorder(InstallTerritory::$Territories['Norwegian Sea'], 'Yes', 'No');
InstallTerritory::$Territories['North Sea']->addBorder(InstallTerritory::$Territories['Norwegian Sea'], 'Yes', 'No');
InstallTerritory::$Territories['North Atlantic Ocean']->addBorder(InstallTerritory::$Territories['Norwegian Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Edinburgh']->addBorder(InstallTerritory::$Territories['North Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Yorkshire']->addBorder(InstallTerritory::$Territories['North Sea'], 'Yes', 'No');
InstallTerritory::$Territories['London']->addBorder(InstallTerritory::$Territories['North Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Norway']->addBorder(InstallTerritory::$Territories['North Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Denmark']->addBorder(InstallTerritory::$Territories['North Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Holland']->addBorder(InstallTerritory::$Territories['North Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Belgium']->addBorder(InstallTerritory::$Territories['North Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Norwegian Sea']->addBorder(InstallTerritory::$Territories['North Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Skagerrack']->addBorder(InstallTerritory::$Territories['North Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Heligoland Bight']->addBorder(InstallTerritory::$Territories['North Sea'], 'Yes', 'No');
InstallTerritory::$Territories['English Channel']->addBorder(InstallTerritory::$Territories['North Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Sweden']->addBorder(InstallTerritory::$Territories['Skagerrack'], 'Yes', 'No');
InstallTerritory::$Territories['Norway']->addBorder(InstallTerritory::$Territories['Skagerrack'], 'Yes', 'No');
InstallTerritory::$Territories['Denmark']->addBorder(InstallTerritory::$Territories['Skagerrack'], 'Yes', 'No');
InstallTerritory::$Territories['North Sea']->addBorder(InstallTerritory::$Territories['Skagerrack'], 'Yes', 'No');
InstallTerritory::$Territories['Denmark']->addBorder(InstallTerritory::$Territories['Heligoland Bight'], 'Yes', 'No');
InstallTerritory::$Territories['Kiel']->addBorder(InstallTerritory::$Territories['Heligoland Bight'], 'Yes', 'No');
InstallTerritory::$Territories['Holland']->addBorder(InstallTerritory::$Territories['Heligoland Bight'], 'Yes', 'No');
InstallTerritory::$Territories['North Sea']->addBorder(InstallTerritory::$Territories['Heligoland Bight'], 'Yes', 'No');
InstallTerritory::$Territories['Livonia']->addBorder(InstallTerritory::$Territories['Baltic Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Sweden']->addBorder(InstallTerritory::$Territories['Baltic Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Denmark']->addBorder(InstallTerritory::$Territories['Baltic Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Kiel']->addBorder(InstallTerritory::$Territories['Baltic Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Berlin']->addBorder(InstallTerritory::$Territories['Baltic Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Prussia']->addBorder(InstallTerritory::$Territories['Baltic Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Gulf of Bothnia']->addBorder(InstallTerritory::$Territories['Baltic Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Livonia']->addBorder(InstallTerritory::$Territories['Gulf of Bothnia'], 'Yes', 'No');
InstallTerritory::$Territories['Finland']->addBorder(InstallTerritory::$Territories['Gulf of Bothnia'], 'Yes', 'No');
InstallTerritory::$Territories['Sweden']->addBorder(InstallTerritory::$Territories['Gulf of Bothnia'], 'Yes', 'No');
InstallTerritory::$Territories['Baltic Sea']->addBorder(InstallTerritory::$Territories['Gulf of Bothnia'], 'Yes', 'No');
InstallTerritory::$Territories['St. Petersburg (South Coast)']->addBorder(InstallTerritory::$Territories['Gulf of Bothnia'], 'Yes', 'No');
InstallTerritory::$Territories['Clyde']->addBorder(InstallTerritory::$Territories['North Atlantic Ocean'], 'Yes', 'No');
InstallTerritory::$Territories['Liverpool']->addBorder(InstallTerritory::$Territories['North Atlantic Ocean'], 'Yes', 'No');
InstallTerritory::$Territories['Norwegian Sea']->addBorder(InstallTerritory::$Territories['North Atlantic Ocean'], 'Yes', 'No');
InstallTerritory::$Territories['Irish Sea']->addBorder(InstallTerritory::$Territories['North Atlantic Ocean'], 'Yes', 'No');
InstallTerritory::$Territories['Mid-Atlantic Ocean']->addBorder(InstallTerritory::$Territories['North Atlantic Ocean'], 'Yes', 'No');
InstallTerritory::$Territories['Liverpool']->addBorder(InstallTerritory::$Territories['Irish Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Wales']->addBorder(InstallTerritory::$Territories['Irish Sea'], 'Yes', 'No');
InstallTerritory::$Territories['North Atlantic Ocean']->addBorder(InstallTerritory::$Territories['Irish Sea'], 'Yes', 'No');
InstallTerritory::$Territories['English Channel']->addBorder(InstallTerritory::$Territories['Irish Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Mid-Atlantic Ocean']->addBorder(InstallTerritory::$Territories['Irish Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Wales']->addBorder(InstallTerritory::$Territories['English Channel'], 'Yes', 'No');
InstallTerritory::$Territories['London']->addBorder(InstallTerritory::$Territories['English Channel'], 'Yes', 'No');
InstallTerritory::$Territories['Belgium']->addBorder(InstallTerritory::$Territories['English Channel'], 'Yes', 'No');
InstallTerritory::$Territories['Picardy']->addBorder(InstallTerritory::$Territories['English Channel'], 'Yes', 'No');
InstallTerritory::$Territories['Brest']->addBorder(InstallTerritory::$Territories['English Channel'], 'Yes', 'No');
InstallTerritory::$Territories['North Sea']->addBorder(InstallTerritory::$Territories['English Channel'], 'Yes', 'No');
InstallTerritory::$Territories['Irish Sea']->addBorder(InstallTerritory::$Territories['English Channel'], 'Yes', 'No');
InstallTerritory::$Territories['Mid-Atlantic Ocean']->addBorder(InstallTerritory::$Territories['English Channel'], 'Yes', 'No');
InstallTerritory::$Territories['Portugal']->addBorder(InstallTerritory::$Territories['Mid-Atlantic Ocean'], 'Yes', 'No');
InstallTerritory::$Territories['North Africa']->addBorder(InstallTerritory::$Territories['Mid-Atlantic Ocean'], 'Yes', 'No');
InstallTerritory::$Territories['Brest']->addBorder(InstallTerritory::$Territories['Mid-Atlantic Ocean'], 'Yes', 'No');
InstallTerritory::$Territories['Gascony']->addBorder(InstallTerritory::$Territories['Mid-Atlantic Ocean'], 'Yes', 'No');
InstallTerritory::$Territories['North Atlantic Ocean']->addBorder(InstallTerritory::$Territories['Mid-Atlantic Ocean'], 'Yes', 'No');
InstallTerritory::$Territories['Irish Sea']->addBorder(InstallTerritory::$Territories['Mid-Atlantic Ocean'], 'Yes', 'No');
InstallTerritory::$Territories['English Channel']->addBorder(InstallTerritory::$Territories['Mid-Atlantic Ocean'], 'Yes', 'No');
InstallTerritory::$Territories['Western Mediterranean']->addBorder(InstallTerritory::$Territories['Mid-Atlantic Ocean'], 'Yes', 'No');
InstallTerritory::$Territories['Spain (North Coast)']->addBorder(InstallTerritory::$Territories['Mid-Atlantic Ocean'], 'Yes', 'No');
InstallTerritory::$Territories['Spain (South Coast)']->addBorder(InstallTerritory::$Territories['Mid-Atlantic Ocean'], 'Yes', 'No');
InstallTerritory::$Territories['North Africa']->addBorder(InstallTerritory::$Territories['Western Mediterranean'], 'Yes', 'No');
InstallTerritory::$Territories['Tunis']->addBorder(InstallTerritory::$Territories['Western Mediterranean'], 'Yes', 'No');
InstallTerritory::$Territories['Mid-Atlantic Ocean']->addBorder(InstallTerritory::$Territories['Western Mediterranean'], 'Yes', 'No');
InstallTerritory::$Territories['Gulf of Lyons']->addBorder(InstallTerritory::$Territories['Western Mediterranean'], 'Yes', 'No');
InstallTerritory::$Territories['Tyrrhenian Sea']->addBorder(InstallTerritory::$Territories['Western Mediterranean'], 'Yes', 'No');
InstallTerritory::$Territories['Spain (South Coast)']->addBorder(InstallTerritory::$Territories['Western Mediterranean'], 'Yes', 'No');
InstallTerritory::$Territories['Tuscany']->addBorder(InstallTerritory::$Territories['Gulf of Lyons'], 'Yes', 'No');
InstallTerritory::$Territories['Piedmont']->addBorder(InstallTerritory::$Territories['Gulf of Lyons'], 'Yes', 'No');
InstallTerritory::$Territories['Marseilles']->addBorder(InstallTerritory::$Territories['Gulf of Lyons'], 'Yes', 'No');
InstallTerritory::$Territories['Western Mediterranean']->addBorder(InstallTerritory::$Territories['Gulf of Lyons'], 'Yes', 'No');
InstallTerritory::$Territories['Tyrrhenian Sea']->addBorder(InstallTerritory::$Territories['Gulf of Lyons'], 'Yes', 'No');
InstallTerritory::$Territories['Spain (South Coast)']->addBorder(InstallTerritory::$Territories['Gulf of Lyons'], 'Yes', 'No');
InstallTerritory::$Territories['Tunis']->addBorder(InstallTerritory::$Territories['Tyrrhenian Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Naples']->addBorder(InstallTerritory::$Territories['Tyrrhenian Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Rome']->addBorder(InstallTerritory::$Territories['Tyrrhenian Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Tuscany']->addBorder(InstallTerritory::$Territories['Tyrrhenian Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Western Mediterranean']->addBorder(InstallTerritory::$Territories['Tyrrhenian Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Gulf of Lyons']->addBorder(InstallTerritory::$Territories['Tyrrhenian Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Ionian Sea']->addBorder(InstallTerritory::$Territories['Tyrrhenian Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Tunis']->addBorder(InstallTerritory::$Territories['Ionian Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Naples']->addBorder(InstallTerritory::$Territories['Ionian Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Apulia']->addBorder(InstallTerritory::$Territories['Ionian Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Greece']->addBorder(InstallTerritory::$Territories['Ionian Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Albania']->addBorder(InstallTerritory::$Territories['Ionian Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Tyrrhenian Sea']->addBorder(InstallTerritory::$Territories['Ionian Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Adriatic Sea']->addBorder(InstallTerritory::$Territories['Ionian Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Aegean Sea']->addBorder(InstallTerritory::$Territories['Ionian Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Eastern Mediterranean']->addBorder(InstallTerritory::$Territories['Ionian Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Venice']->addBorder(InstallTerritory::$Territories['Adriatic Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Apulia']->addBorder(InstallTerritory::$Territories['Adriatic Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Albania']->addBorder(InstallTerritory::$Territories['Adriatic Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Ionian Sea']->addBorder(InstallTerritory::$Territories['Adriatic Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Trieste']->addBorder(InstallTerritory::$Territories['Adriatic Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Greece']->addBorder(InstallTerritory::$Territories['Aegean Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Constantinople']->addBorder(InstallTerritory::$Territories['Aegean Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Smyrna']->addBorder(InstallTerritory::$Territories['Aegean Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Ionian Sea']->addBorder(InstallTerritory::$Territories['Aegean Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Eastern Mediterranean']->addBorder(InstallTerritory::$Territories['Aegean Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Bulgaria (South Coast)']->addBorder(InstallTerritory::$Territories['Aegean Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Smyrna']->addBorder(InstallTerritory::$Territories['Eastern Mediterranean'], 'Yes', 'No');
InstallTerritory::$Territories['Syria']->addBorder(InstallTerritory::$Territories['Eastern Mediterranean'], 'Yes', 'No');
InstallTerritory::$Territories['Ionian Sea']->addBorder(InstallTerritory::$Territories['Eastern Mediterranean'], 'Yes', 'No');
InstallTerritory::$Territories['Aegean Sea']->addBorder(InstallTerritory::$Territories['Eastern Mediterranean'], 'Yes', 'No');
InstallTerritory::$Territories['Rumania']->addBorder(InstallTerritory::$Territories['Black Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Constantinople']->addBorder(InstallTerritory::$Territories['Black Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Ankara']->addBorder(InstallTerritory::$Territories['Black Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Armenia']->addBorder(InstallTerritory::$Territories['Black Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Sevastopol']->addBorder(InstallTerritory::$Territories['Black Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Bulgaria (North Coast)']->addBorder(InstallTerritory::$Territories['Black Sea'], 'Yes', 'No');
InstallTerritory::$Territories['Piedmont']->addBorder(InstallTerritory::$Territories['Tyrolia'], 'No', 'Yes');
InstallTerritory::$Territories['Venice']->addBorder(InstallTerritory::$Territories['Tyrolia'], 'No', 'Yes');
InstallTerritory::$Territories['Munich']->addBorder(InstallTerritory::$Territories['Tyrolia'], 'No', 'Yes');
InstallTerritory::$Territories['Bohemia']->addBorder(InstallTerritory::$Territories['Tyrolia'], 'No', 'Yes');
InstallTerritory::$Territories['Vienna']->addBorder(InstallTerritory::$Territories['Tyrolia'], 'No', 'Yes');
InstallTerritory::$Territories['Trieste']->addBorder(InstallTerritory::$Territories['Tyrolia'], 'No', 'Yes');
InstallTerritory::$Territories['Silesia']->addBorder(InstallTerritory::$Territories['Bohemia'], 'No', 'Yes');
InstallTerritory::$Territories['Munich']->addBorder(InstallTerritory::$Territories['Bohemia'], 'No', 'Yes');
InstallTerritory::$Territories['Tyrolia']->addBorder(InstallTerritory::$Territories['Bohemia'], 'No', 'Yes');
InstallTerritory::$Territories['Vienna']->addBorder(InstallTerritory::$Territories['Bohemia'], 'No', 'Yes');
InstallTerritory::$Territories['Galicia']->addBorder(InstallTerritory::$Territories['Bohemia'], 'No', 'Yes');
InstallTerritory::$Territories['Tyrolia']->addBorder(InstallTerritory::$Territories['Vienna'], 'No', 'Yes');
InstallTerritory::$Territories['Bohemia']->addBorder(InstallTerritory::$Territories['Vienna'], 'No', 'Yes');
InstallTerritory::$Territories['Trieste']->addBorder(InstallTerritory::$Territories['Vienna'], 'No', 'Yes');
InstallTerritory::$Territories['Budapest']->addBorder(InstallTerritory::$Territories['Vienna'], 'No', 'Yes');
InstallTerritory::$Territories['Galicia']->addBorder(InstallTerritory::$Territories['Vienna'], 'No', 'Yes');
InstallTerritory::$Territories['Venice']->addBorder(InstallTerritory::$Territories['Trieste'], 'Yes', 'Yes');
InstallTerritory::$Territories['Albania']->addBorder(InstallTerritory::$Territories['Trieste'], 'Yes', 'Yes');
InstallTerritory::$Territories['Serbia']->addBorder(InstallTerritory::$Territories['Trieste'], 'No', 'Yes');
InstallTerritory::$Territories['Adriatic Sea']->addBorder(InstallTerritory::$Territories['Trieste'], 'Yes', 'No');
InstallTerritory::$Territories['Tyrolia']->addBorder(InstallTerritory::$Territories['Trieste'], 'No', 'Yes');
InstallTerritory::$Territories['Vienna']->addBorder(InstallTerritory::$Territories['Trieste'], 'No', 'Yes');
InstallTerritory::$Territories['Budapest']->addBorder(InstallTerritory::$Territories['Trieste'], 'No', 'Yes');
InstallTerritory::$Territories['Serbia']->addBorder(InstallTerritory::$Territories['Budapest'], 'No', 'Yes');
InstallTerritory::$Territories['Rumania']->addBorder(InstallTerritory::$Territories['Budapest'], 'No', 'Yes');
InstallTerritory::$Territories['Vienna']->addBorder(InstallTerritory::$Territories['Budapest'], 'No', 'Yes');
InstallTerritory::$Territories['Trieste']->addBorder(InstallTerritory::$Territories['Budapest'], 'No', 'Yes');
InstallTerritory::$Territories['Galicia']->addBorder(InstallTerritory::$Territories['Budapest'], 'No', 'Yes');
InstallTerritory::$Territories['Rumania']->addBorder(InstallTerritory::$Territories['Galicia'], 'No', 'Yes');
InstallTerritory::$Territories['Ukraine']->addBorder(InstallTerritory::$Territories['Galicia'], 'No', 'Yes');
InstallTerritory::$Territories['Warsaw']->addBorder(InstallTerritory::$Territories['Galicia'], 'No', 'Yes');
InstallTerritory::$Territories['Silesia']->addBorder(InstallTerritory::$Territories['Galicia'], 'No', 'Yes');
InstallTerritory::$Territories['Bohemia']->addBorder(InstallTerritory::$Territories['Galicia'], 'No', 'Yes');
InstallTerritory::$Territories['Vienna']->addBorder(InstallTerritory::$Territories['Galicia'], 'No', 'Yes');
InstallTerritory::$Territories['Budapest']->addBorder(InstallTerritory::$Territories['Galicia'], 'No', 'Yes');
InstallTerritory::$Territories['Portugal']->addBorder(InstallTerritory::$Territories['Spain (North Coast)'], 'Yes', 'No');
InstallTerritory::$Territories['Gascony']->addBorder(InstallTerritory::$Territories['Spain (North Coast)'], 'Yes', 'No');
InstallTerritory::$Territories['Mid-Atlantic Ocean']->addBorder(InstallTerritory::$Territories['Spain (North Coast)'], 'Yes', 'No');
InstallTerritory::$Territories['Portugal']->addBorder(InstallTerritory::$Territories['Spain (South Coast)'], 'Yes', 'No');
InstallTerritory::$Territories['Marseilles']->addBorder(InstallTerritory::$Territories['Spain (South Coast)'], 'Yes', 'No');
InstallTerritory::$Territories['Mid-Atlantic Ocean']->addBorder(InstallTerritory::$Territories['Spain (South Coast)'], 'Yes', 'No');
InstallTerritory::$Territories['Western Mediterranean']->addBorder(InstallTerritory::$Territories['Spain (South Coast)'], 'Yes', 'No');
InstallTerritory::$Territories['Gulf of Lyons']->addBorder(InstallTerritory::$Territories['Spain (South Coast)'], 'Yes', 'No');
InstallTerritory::$Territories['Norway']->addBorder(InstallTerritory::$Territories['St. Petersburg (North Coast)'], 'Yes', 'No');
InstallTerritory::$Territories['Barents Sea']->addBorder(InstallTerritory::$Territories['St. Petersburg (North Coast)'], 'Yes', 'No');
InstallTerritory::$Territories['Livonia']->addBorder(InstallTerritory::$Territories['St. Petersburg (South Coast)'], 'Yes', 'No');
InstallTerritory::$Territories['Finland']->addBorder(InstallTerritory::$Territories['St. Petersburg (South Coast)'], 'Yes', 'No');
InstallTerritory::$Territories['Gulf of Bothnia']->addBorder(InstallTerritory::$Territories['St. Petersburg (South Coast)'], 'Yes', 'No');
InstallTerritory::$Territories['Rumania']->addBorder(InstallTerritory::$Territories['Bulgaria (North Coast)'], 'Yes', 'No');
InstallTerritory::$Territories['Constantinople']->addBorder(InstallTerritory::$Territories['Bulgaria (North Coast)'], 'Yes', 'No');
InstallTerritory::$Territories['Black Sea']->addBorder(InstallTerritory::$Territories['Bulgaria (North Coast)'], 'Yes', 'No');
InstallTerritory::$Territories['Greece']->addBorder(InstallTerritory::$Territories['Bulgaria (South Coast)'], 'Yes', 'No');
InstallTerritory::$Territories['Constantinople']->addBorder(InstallTerritory::$Territories['Bulgaria (South Coast)'], 'Yes', 'No');
InstallTerritory::$Territories['Aegean Sea']->addBorder(InstallTerritory::$Territories['Bulgaria (South Coast)'], 'Yes', 'No');

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);

?>