<?php
// This is file installs the map data for the Zeus5 variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Adriatic Sea', 'Sea', 'No', 0, 943, 571, 641, 398),
	array('Alaska', 'Coast', 'No', 2, 396, 620, 271, 436),
	array('Amursk', 'Coast', 'No', 7, 359, 466, 253, 347),
	array('Arctic Ocean', 'Sea', 'No', 0, 511, 660, 343, 459),
	array('Austria', 'Land', 'No', 4, 872, 647, 582, 490),
	array('Baltic Sea', 'Sea', 'No', 0, 696, 574, 475, 407),
	array('Bay of Bengal', 'Sea', 'No', 0, 548, 77, 403, 61),
	array('Bay of Biscay', 'Sea', 'No', 0, 506, 945, 338, 659),
	array('Benghazi', 'Coast', 'No', 3, 1019, 481, 699, 338),
	array('Berlin', 'Coast', 'Yes', 4, 737, 649, 507, 438),
	array('Black Sea', 'Sea', 'No', 0, 727, 324, 488, 225),
	array('Burma', 'Coast', 'No', 0, 542, 119, 371, 81),
	array('California', 'Coast', 'No', 2, 221, 708, 148, 493),
	array('Canada', 'Coast', 'Yes', 1, 349, 667, 238, 473),
	array('Canada (East Coast)', 'Coast', 'No', 1, 359, 739, 265, 482),
	array('Canada (West Coast)', 'Coast', 'No', 1, 348, 639, 226, 438),
	array('Canton', 'Coast', 'Yes', 6, 419, 225, 257, 189),
	array('Caroline Isl.', 'Sea', 'No', 0, 188, 547, 130, 384),
	array('Central Pacific Ocean', 'Sea', 'No', 0, 111, 597, 111, 328),
	array('Chungking', 'Land', 'Yes', 6, 547, 221, 335, 185),
	array('Columbia', 'Coast', 'No', 0, 207, 929, 131, 636),
	array('Columbia (East Coast)', 'Coast', 'No', 0, 229, 950, 159, 672),
	array('Columbia (West Coast)', 'Coast', 'No', 0, 181, 897, 113, 619),
	array('Czech', 'Land', 'No', 0, 829, 592, 560, 425),
	array('Denmark', 'Coast', 'Yes', 0, 677, 657, 441, 471),
	array('East China Sea', 'Sea', 'No', 0, 262, 284, 190, 197),
	array('East Siberian Sea', 'Sea', 'No', 0, 469, 575, 317, 403),
	array('Eastern Mediterranean Sea', 'Sea', 'No', 0, 914, 321, 630, 238),
	array('Edinburgh', 'Coast', 'Yes', 1, 479, 797, 323, 563),
	array('Egypt', 'Coast', 'Yes', 1, 897, 239, 626, 186),
	array('English Channel', 'Sea', 'No', 0, 512, 895, 349, 628),
	array('Finland', 'Coast', 'Yes', 0, 599, 507, 402, 358),
	array('Finland (North Coast)', 'Coast', 'No', 0, 544, 531, 357, 368),
	array('Finland (South Coast)', 'Coast', 'No', 0, 617, 510, 423, 362),
	array('Greece', 'Coast', 'Yes', 0, 923, 451, 595, 293),
	array('Gulf of Bothnia', 'Sea', 'No', 0, 619, 544, 455, 379),
	array('Hamburg', 'Coast', 'Yes', 4, 694, 703, 469, 495),
	array('Hawaii', 'Coast', 'Yes', 2, 153, 720, 100, 504),
	array('Helgoland', 'Sea', 'No', 0, 631, 724, 424, 505),
	array('Hungary', 'Land', 'No', 0, 840, 515, 572, 364),
	array('India', 'Coast', 'Yes', 8, 634, 125, 432, 122),
	array('Indian Ocean', 'Sea', 'No', 0, 645, 60, 477, 81),
	array('IndoChina', 'Coast', 'Yes', 0, 458, 131, 332, 87),
	array('Ionian Sea', 'Sea', 'No', 0, 1002, 532, 695, 421),
	array('Iran', 'Coast', 'No', 0, 683, 211, 466, 149),
	array('Kazakhstan', 'Coast', 'No', 7, 666, 301, 455, 214),
	array('Korea', 'Coast', 'Yes', 0, 332, 383, 219, 270),
	array('Kyushu', 'Coast', 'No', 5, 290, 389, 196, 271),
	array('Leningrad', 'Coast', 'Yes', 7, 582, 468, 399, 320),
	array('Leningrad (North Coast)', 'Coast', 'No', 7, 550, 502, 371, 347),
	array('Leningrad (South Coast)', 'Coast', 'No', 7, 615, 465, 413, 329),
	array('Lithuania', 'Coast', 'No', 0, 674, 510, 455, 358),
	array('London', 'Coast', 'Yes', 1, 542, 857, 366, 594),
	array('Low Countries', 'Coast', 'No', 0, 615, 810, 417, 567),
	array('Magadan', 'Coast', 'Yes', 7, 452, 540, 299, 377),
	array('Mid-Atlantic Ocean', 'Sea', 'No', 0, 320, 880, 233, 641),
	array('Mid-Pacific Ocean', 'Sea', 'No', 0, 243, 553, 166, 373),
	array('Middle East', 'Coast', 'Yes', 1, 758, 243, 514, 171),
	array('Middle East (South Coast)', 'Coast', 'No', 1, 743, 169, 490, 125),
	array('Middle East (West Coast)', 'Coast', 'No', 1, 813, 254, 556, 180),
	array('Midway Isl.', 'Coast', 'Yes', 0, 200, 650, 134, 455),
	array('Moscow', 'Land', 'Yes', 7, 694, 430, 474, 298),
	array('Munich', 'Land', 'Yes', 4, 766, 728, 475, 560),
	array('Nepal', 'Land', 'No', 0, 610, 196, 414, 142),
	array('New York', 'Coast', 'Yes', 2, 312, 774, 217, 543),
	array('North Africa', 'Coast', 'No', 3, 779, 1044, 449, 735),
	array('North Atlantic Ocean', 'Sea', 'No', 0, 405, 788, 283, 538),
	array('North Pacific Ocean', 'Sea', 'No', 0, 344, 579, 193, 417),
	array('North Sea', 'Sea', 'No', 0, 567, 755, 384, 521),
	array('Norway', 'Coast', 'Yes', 0, 588, 677, 403, 447),
	array('Okinawa', 'Coast', 'Yes', 0, 227, 390, 153, 273),
	array('Oregon', 'Coast', 'No', 2, 288, 665, 196, 465),
	array('Panama', 'Coast', 'Yes', 0, 196, 847, 132, 606),
	array('Paris', 'Coast', 'Yes', 0, 557, 914, 374, 643),
	array('Peking', 'Coast', 'Yes', 6, 405, 410, 277, 282),
	array('Piedmont', 'Coast', 'No', 3, 820, 816, 554, 572),
	array('Poland', 'Land', 'Yes', 0, 740, 471, 512, 353),
	array('Prussia', 'Coast', 'No', 4, 710, 519, 483, 385),
	array('Rome', 'Coast', 'Yes', 3, 989, 639, 670, 452),
	array('Rumania', 'Coast', 'Yes', 0, 805, 392, 547, 273),
	array('Sapporo', 'Coast', 'Yes', 5, 321, 507, 217, 357),
	array('Sea of Japan', 'Sea', 'No', 0, 312, 425, 215, 332),
	array('Sea of Okhotsk', 'Sea', 'No', 0, 355, 508, 244, 365),
	array('Sendai', 'Coast', 'Yes', 5, 279, 504, 173, 341),
	array('Siberia', 'Land', 'No', 7, 547, 409, 371, 285),
	array('Sinkiang', 'Land', 'No', 6, 496, 377, 340, 261),
	array('Solomon Isl.', 'Coast', 'Yes', 0, 184, 304, 125, 213),
	array('South Atlantic Ocean', 'Sea', 'No', 0, 300, 978, 227, 713),
	array('South China Sea', 'Sea', 'No', 0, 365, 222, 265, 144),
	array('South Pacific Ocean', 'Sea', 'No', 0, 107, 370, 92, 192),
	array('Spain', 'Coast', 'Yes', 0, 470, 992, 315, 695),
	array('Stalingrad', 'Coast', 'Yes', 7, 664, 374, 443, 259),
	array('Sweden', 'Coast', 'No', 0, 643, 577, 434, 402),
	array('Switzerland', 'Land', 'No', 0, 743, 839, 504, 586),
	array('Tokyo', 'Coast', 'Yes', 5, 264, 434, 179, 301),
	array('Tokyo (East Coast)', 'Coast', 'No', 5, 254, 429, 171, 303),
	array('Tokyo (West Coast)', 'Coast', 'No', 5, 279, 472, 188, 328),
	array('Tripoli', 'Coast', 'Yes', 3, 982, 821, 672, 565),
	array('Turkey', 'Coast', 'Yes', 0, 768, 295, 514, 207),
	array('Venice', 'Coast', 'Yes', 3, 909, 728, 626, 505),
	array('Vichy-France', 'Coast', 'No', 0, 741, 909, 504, 646),
	array('Washington', 'Coast', 'Yes', 2, 263, 793, 168, 560),
	array('Western Britain', 'Coast', 'No', 1, 451, 851, 300, 601),
	array('Western Mediterranean', 'Sea', 'No', 0, 797, 958, 533, 677),
	array('Yellow Sea', 'Sea', 'No', 0, 361, 382, 252, 272),
	array('Yugoslavia', 'Coast', 'Yes', 0, 916, 600, 622, 422),
	array('ch', 'Coast', 'No', 6, 1078, 111, 722, 77),
	array('ger', 'Coast', 'No', 4, 1078, 37, 721, 29),
	array('ita', 'Coast', 'No', 3, 1078, 60, 723, 44),
	array('jap', 'Coast', 'No', 5, 1078, 134, 721, 94),
	array('su', 'Coast', 'No', 7, 1078, 86, 723, 61),
	array('uk', 'Coast', 'No', 1, 1076, 12, 723, 12),
	array('us', 'Coast', 'No', 2, 1076, 160, 721, 111)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Adriatic Sea','Greece','Yes','No'),
	array('Adriatic Sea','Ionian Sea','Yes','No'),
	array('Adriatic Sea','Rome','Yes','No'),
	array('Adriatic Sea','Venice','Yes','No'),
	array('Adriatic Sea','Yugoslavia','Yes','No'),
	array('Alaska','Arctic Ocean','Yes','No'),
	array('Alaska','Canada','No','Yes'),
	array('Alaska','Canada (East Coast)','Yes','No'),
	array('Alaska','Canada (West Coast)','Yes','No'),
	array('Alaska','North Pacific Ocean','Yes','No'),
	array('Amursk','Korea','Yes','Yes'),
	array('Amursk','Magadan','Yes','Yes'),
	array('Amursk','Peking','Yes','Yes'),
	array('Amursk','Sea of Japan','Yes','No'),
	array('Amursk','Sea of Okhotsk','Yes','No'),
	array('Amursk','Siberia','No','Yes'),
	array('Amursk','Sinkiang','No','Yes'),
	array('Arctic Ocean','Canada (East Coast)','Yes','No'),
	array('Arctic Ocean','East Siberian Sea','Yes','No'),
	array('Arctic Ocean','Edinburgh','Yes','No'),
	array('Arctic Ocean','North Atlantic Ocean','Yes','No'),
	array('Arctic Ocean','North Pacific Ocean','Yes','No'),
	array('Arctic Ocean','North Sea','Yes','No'),
	array('Arctic Ocean','Norway','Yes','No'),
	array('Arctic Ocean','Sea of Okhotsk','Yes','No'),
	array('Austria','Czech','No','Yes'),
	array('Austria','Hungary','No','Yes'),
	array('Austria','Munich','No','Yes'),
	array('Austria','Piedmont','No','Yes'),
	array('Austria','Switzerland','No','Yes'),
	array('Austria','Venice','No','Yes'),
	array('Austria','Yugoslavia','No','Yes'),
	array('Baltic Sea','Berlin','Yes','No'),
	array('Baltic Sea','Denmark','Yes','No'),
	array('Baltic Sea','Gulf of Bothnia','Yes','No'),
	array('Baltic Sea','Hamburg','Yes','No'),
	array('Baltic Sea','Prussia','Yes','No'),
	array('Baltic Sea','Sweden','Yes','No'),
	array('Bay of Bengal','Burma','Yes','No'),
	array('Bay of Bengal','India','Yes','No'),
	array('Bay of Bengal','Indian Ocean','Yes','No'),
	array('Bay of Bengal','IndoChina','Yes','No'),
	array('Bay of Biscay','English Channel','Yes','No'),
	array('Bay of Biscay','Mid-Atlantic Ocean','Yes','No'),
	array('Bay of Biscay','Paris','Yes','No'),
	array('Bay of Biscay','Spain','Yes','No'),
	array('Bay of Biscay','Western Britain','Yes','No'),
	array('Benghazi','Eastern Mediterranean Sea','Yes','No'),
	array('Benghazi','Egypt','Yes','Yes'),
	array('Benghazi','Ionian Sea','Yes','No'),
	array('Benghazi','Tripoli','Yes','Yes'),
	array('Berlin','Czech','No','Yes'),
	array('Berlin','Hamburg','Yes','Yes'),
	array('Berlin','Munich','No','Yes'),
	array('Berlin','Poland','No','Yes'),
	array('Berlin','Prussia','Yes','Yes'),
	array('Black Sea','Eastern Mediterranean Sea','Yes','No'),
	array('Black Sea','Greece','Yes','No'),
	array('Black Sea','Kazakhstan','Yes','No'),
	array('Black Sea','Rumania','Yes','No'),
	array('Black Sea','Stalingrad','Yes','No'),
	array('Black Sea','Turkey','Yes','No'),
	array('Burma','Canton','No','Yes'),
	array('Burma','India','Yes','Yes'),
	array('Burma','IndoChina','Yes','Yes'),
	array('Burma','Nepal','No','Yes'),
	array('California','Hawaii','Yes','Yes'),
	array('California','Mid-Pacific Ocean','Yes','No'),
	array('California','Midway Isl.','Yes','Yes'),
	array('California','New York','No','Yes'),
	array('California','Oregon','Yes','Yes'),
	array('California','Panama','Yes','Yes'),
	array('California','Washington','No','Yes'),
	array('Canada','New York','No','Yes'),
	array('Canada','Oregon','No','Yes'),
	array('Canada (East Coast)','New York','Yes','No'),
	array('Canada (East Coast)','North Atlantic Ocean','Yes','No'),
	array('Canada (West Coast)','North Pacific Ocean','Yes','No'),
	array('Canada (West Coast)','Oregon','Yes','No'),
	array('Canton','Chungking','No','Yes'),
	array('Canton','East China Sea','Yes','No'),
	array('Canton','IndoChina','Yes','Yes'),
	array('Canton','Nepal','No','Yes'),
	array('Canton','Peking','Yes','Yes'),
	array('Canton','South China Sea','Yes','No'),
	array('Canton','Yellow Sea','Yes','No'),
	array('Caroline Isl.','Central Pacific Ocean','Yes','No'),
	array('Caroline Isl.','Mid-Pacific Ocean','Yes','No'),
	array('Caroline Isl.','Midway Isl.','Yes','No'),
	array('Caroline Isl.','Okinawa','Yes','No'),
	array('Caroline Isl.','Tokyo (East Coast)','Yes','No'),
	array('Central Pacific Ocean','Hawaii','Yes','No'),
	array('Central Pacific Ocean','Midway Isl.','Yes','No'),
	array('Central Pacific Ocean','Okinawa','Yes','No'),
	array('Central Pacific Ocean','Solomon Isl.','Yes','No'),
	array('Central Pacific Ocean','South Pacific Ocean','Yes','No'),
	array('Chungking','Kazakhstan','No','Yes'),
	array('Chungking','Nepal','No','Yes'),
	array('Chungking','Peking','No','Yes'),
	array('Chungking','Sinkiang','No','Yes'),
	array('Columbia','Panama','No','Yes'),
	array('Columbia (East Coast)','Panama','Yes','No'),
	array('Columbia (East Coast)','South Atlantic Ocean','Yes','No'),
	array('Columbia (West Coast)','Panama','Yes','No'),
	array('Columbia (West Coast)','South Pacific Ocean','Yes','No'),
	array('Czech','Hungary','No','Yes'),
	array('Czech','Munich','No','Yes'),
	array('Czech','Poland','No','Yes'),
	array('Denmark','Hamburg','Yes','Yes'),
	array('Denmark','Helgoland','Yes','No'),
	array('Denmark','North Sea','Yes','No'),
	array('Denmark','Sweden','Yes','Yes'),
	array('East China Sea','Kyushu','Yes','No'),
	array('East China Sea','Okinawa','Yes','No'),
	array('East China Sea','Solomon Isl.','Yes','No'),
	array('East China Sea','South China Sea','Yes','No'),
	array('East China Sea','South Pacific Ocean','Yes','No'),
	array('East China Sea','Yellow Sea','Yes','No'),
	array('East Siberian Sea','Finland (North Coast)','Yes','No'),
	array('East Siberian Sea','Leningrad (North Coast)','Yes','No'),
	array('East Siberian Sea','Magadan','Yes','No'),
	array('East Siberian Sea','Norway','Yes','No'),
	array('East Siberian Sea','Sea of Okhotsk','Yes','No'),
	array('Eastern Mediterranean Sea','Egypt','Yes','No'),
	array('Eastern Mediterranean Sea','Greece','Yes','No'),
	array('Eastern Mediterranean Sea','Ionian Sea','Yes','No'),
	array('Eastern Mediterranean Sea','Middle East (West Coast)','Yes','No'),
	array('Eastern Mediterranean Sea','Turkey','Yes','No'),
	array('Edinburgh','London','Yes','Yes'),
	array('Edinburgh','North Atlantic Ocean','Yes','No'),
	array('Edinburgh','North Sea','Yes','No'),
	array('Edinburgh','Western Britain','Yes','Yes'),
	array('Egypt','Indian Ocean','Yes','No'),
	array('Egypt','Middle East','No','Yes'),
	array('Egypt','Middle East (South Coast)','Yes','No'),
	array('Egypt','Middle East (West Coast)','Yes','No'),
	array('English Channel','London','Yes','No'),
	array('English Channel','Low Countries','Yes','No'),
	array('English Channel','North Sea','Yes','No'),
	array('English Channel','Paris','Yes','No'),
	array('English Channel','Western Britain','Yes','No'),
	array('Finland','Leningrad','No','Yes'),
	array('Finland','Norway','No','Yes'),
	array('Finland','Sweden','No','Yes'),
	array('Finland (North Coast)','Leningrad (North Coast)','Yes','No'),
	array('Finland (North Coast)','Norway','Yes','No'),
	array('Finland (South Coast)','Gulf of Bothnia','Yes','No'),
	array('Finland (South Coast)','Leningrad (South Coast)','Yes','No'),
	array('Finland (South Coast)','Sweden','Yes','No'),
	array('Greece','Ionian Sea','Yes','No'),
	array('Greece','Rumania','Yes','Yes'),
	array('Greece','Yugoslavia','Yes','Yes'),
	array('Gulf of Bothnia','Leningrad (South Coast)','Yes','No'),
	array('Gulf of Bothnia','Lithuania','Yes','No'),
	array('Gulf of Bothnia','Prussia','Yes','No'),
	array('Gulf of Bothnia','Sweden','Yes','No'),
	array('Hamburg','Helgoland','Yes','No'),
	array('Hamburg','Low Countries','Yes','Yes'),
	array('Hamburg','Munich','No','Yes'),
	array('Hawaii','Midway Isl.','Yes','Yes'),
	array('Hawaii','Panama','Yes','Yes'),
	array('Hawaii','South Pacific Ocean','Yes','No'),
	array('Helgoland','Low Countries','Yes','No'),
	array('Helgoland','North Sea','Yes','No'),
	array('Hungary','Poland','No','Yes'),
	array('Hungary','Rumania','No','Yes'),
	array('Hungary','Yugoslavia','No','Yes'),
	array('India','Indian Ocean','Yes','No'),
	array('India','Iran','Yes','Yes'),
	array('India','Kazakhstan','No','Yes'),
	array('India','Nepal','No','Yes'),
	array('Indian Ocean','IndoChina','Yes','No'),
	array('Indian Ocean','Iran','Yes','No'),
	array('Indian Ocean','Middle East (South Coast)','Yes','No'),
	array('Indian Ocean','South Pacific Ocean','Yes','No'),
	array('IndoChina','South China Sea','Yes','No'),
	array('IndoChina','South Pacific Ocean','Yes','No'),
	array('Ionian Sea','Rome','Yes','No'),
	array('Ionian Sea','Tripoli','Yes','No'),
	array('Ionian Sea','Western Mediterranean','Yes','No'),
	array('Iran','Kazakhstan','No','Yes'),
	array('Iran','Middle East','No','Yes'),
	array('Iran','Middle East (South Coast)','Yes','No'),
	array('Iran','Turkey','No','Yes'),
	array('Kazakhstan','Nepal','No','Yes'),
	array('Kazakhstan','Siberia','No','Yes'),
	array('Kazakhstan','Sinkiang','No','Yes'),
	array('Kazakhstan','Stalingrad','Yes','Yes'),
	array('Kazakhstan','Turkey','Yes','Yes'),
	array('Korea','Kyushu','Yes','Yes'),
	array('Korea','Peking','Yes','Yes'),
	array('Korea','Sea of Japan','Yes','No'),
	array('Korea','Yellow Sea','Yes','No'),
	array('Kyushu','Okinawa','Yes','Yes'),
	array('Kyushu','Sea of Japan','Yes','No'),
	array('Kyushu','Tokyo','No','Yes'),
	array('Kyushu','Tokyo (East Coast)','Yes','No'),
	array('Kyushu','Tokyo (West Coast)','Yes','No'),
	array('Kyushu','Yellow Sea','Yes','No'),
	array('Leningrad','Lithuania','No','Yes'),
	array('Leningrad','Magadan','No','Yes'),
	array('Leningrad','Moscow','No','Yes'),
	array('Leningrad','Siberia','No','Yes'),
	array('Leningrad (North Coast)','Magadan','Yes','No'),
	array('Leningrad (South Coast)','Lithuania','Yes','No'),
	array('Lithuania','Moscow','No','Yes'),
	array('Lithuania','Poland','No','Yes'),
	array('Lithuania','Prussia','Yes','Yes'),
	array('London','North Sea','Yes','No'),
	array('London','Western Britain','Yes','Yes'),
	array('Low Countries','Munich','No','Yes'),
	array('Low Countries','North Sea','Yes','No'),
	array('Low Countries','Paris','Yes','Yes'),
	array('Magadan','Sea of Okhotsk','Yes','No'),
	array('Magadan','Siberia','No','Yes'),
	array('Mid-Atlantic Ocean','New York','Yes','No'),
	array('Mid-Atlantic Ocean','North Atlantic Ocean','Yes','No'),
	array('Mid-Atlantic Ocean','Panama','Yes','No'),
	array('Mid-Atlantic Ocean','South Atlantic Ocean','Yes','No'),
	array('Mid-Atlantic Ocean','Spain','Yes','No'),
	array('Mid-Atlantic Ocean','Washington','Yes','No'),
	array('Mid-Atlantic Ocean','Western Britain','Yes','No'),
	array('Mid-Atlantic Ocean','Western Mediterranean','Yes','No'),
	array('Mid-Pacific Ocean','Midway Isl.','Yes','No'),
	array('Mid-Pacific Ocean','North Pacific Ocean','Yes','No'),
	array('Mid-Pacific Ocean','Oregon','Yes','No'),
	array('Mid-Pacific Ocean','Sendai','Yes','No'),
	array('Mid-Pacific Ocean','Tokyo (East Coast)','Yes','No'),
	array('Middle East','Turkey','No','Yes'),
	array('Middle East (West Coast)','Turkey','Yes','No'),
	array('Moscow','Poland','No','Yes'),
	array('Moscow','Rumania','No','Yes'),
	array('Moscow','Siberia','No','Yes'),
	array('Moscow','Stalingrad','No','Yes'),
	array('Munich','Paris','No','Yes'),
	array('Munich','Switzerland','No','Yes'),
	array('New York','North Atlantic Ocean','Yes','No'),
	array('New York','Oregon','No','Yes'),
	array('New York','Washington','Yes','Yes'),
	array('North Africa','South Atlantic Ocean','Yes','No'),
	array('North Africa','Spain','Yes','Yes'),
	array('North Africa','Tripoli','Yes','Yes'),
	array('North Africa','Western Mediterranean','Yes','No'),
	array('North Atlantic Ocean','Western Britain','Yes','No'),
	array('North Pacific Ocean','Oregon','Yes','No'),
	array('North Pacific Ocean','Sapporo','Yes','No'),
	array('North Pacific Ocean','Sea of Okhotsk','Yes','No'),
	array('North Pacific Ocean','Sendai','Yes','No'),
	array('North Sea','Norway','Yes','No'),
	array('North Sea','Sweden','Yes','No'),
	array('Norway','Sweden','Yes','Yes'),
	array('Okinawa','Solomon Isl.','Yes','Yes'),
	array('Okinawa','Tokyo','No','Yes'),
	array('Okinawa','Tokyo (East Coast)','Yes','No'),
	array('Panama','South Atlantic Ocean','Yes','No'),
	array('Panama','South Pacific Ocean','Yes','No'),
	array('Panama','Washington','Yes','Yes'),
	array('Paris','Spain','Yes','Yes'),
	array('Paris','Switzerland','No','Yes'),
	array('Paris','Vichy-France','No','Yes'),
	array('Peking','Sinkiang','No','Yes'),
	array('Peking','Yellow Sea','Yes','No'),
	array('Piedmont','Rome','Yes','Yes'),
	array('Piedmont','Switzerland','No','Yes'),
	array('Piedmont','Venice','No','Yes'),
	array('Piedmont','Vichy-France','Yes','Yes'),
	array('Piedmont','Western Mediterranean','Yes','No'),
	array('Poland','Prussia','No','Yes'),
	array('Poland','Rumania','No','Yes'),
	array('Rome','Venice','Yes','Yes'),
	array('Rome','Western Mediterranean','Yes','No'),
	array('Rumania','Stalingrad','Yes','Yes'),
	array('Rumania','Yugoslavia','No','Yes'),
	array('Sapporo','Sea of Japan','Yes','No'),
	array('Sapporo','Sea of Okhotsk','Yes','No'),
	array('Sapporo','Sendai','Yes','Yes'),
	array('Sapporo','Tokyo','No','Yes'),
	array('Sapporo','Tokyo (West Coast)','Yes','No'),
	array('Sea of Japan','Sea of Okhotsk','Yes','No'),
	array('Sea of Japan','Tokyo (West Coast)','Yes','No'),
	array('Sendai','Tokyo','No','Yes'),
	array('Sendai','Tokyo (East Coast)','Yes','No'),
	array('Siberia','Sinkiang','No','Yes'),
	array('Siberia','Stalingrad','No','Yes'),
	array('Solomon Isl.','South Pacific Ocean','Yes','No'),
	array('South Atlantic Ocean','Western Mediterranean','Yes','No'),
	array('South China Sea','South Pacific Ocean','Yes','No'),
	array('Spain','Vichy-France','Yes','Yes'),
	array('Spain','Western Mediterranean','Yes','No'),
	array('Switzerland','Vichy-France','No','Yes'),
	array('Tripoli','Western Mediterranean','Yes','No'),
	array('Venice','Yugoslavia','Yes','Yes'),
	array('Vichy-France','Western Mediterranean','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
