<?php
// This is file installs the map data for the BalkanWarsVI variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Apulia', 'Coast', 'No', 0, 290, 454, 145, 227),
	array('Arda', 'Land', 'No', 2, 974, 404, 487, 202),
	array('Athens', 'Coast', 'Yes', 3, 794, 642, 397, 321),
	array('Belgrade', 'Land', 'Yes', 5, 564, 298, 282, 149),
	array('Bessarabia', 'Coast', 'No', 4, 1106, 174, 553, 87),
	array('Bithynia', 'Coast', 'No', 6, 1428, 454, 714, 227),
	array('Bosnia', 'Coast', 'No', 0, 306, 252, 153, 126),
	array('Bucharest', 'Land', 'Yes', 4, 892, 228, 446, 114),
	array('Cilicia', 'Coast', 'No', 6, 1408, 624, 704, 312),
	array('Cluj', 'Land', 'Yes', 0, 634, 108, 317, 54),
	array('Constantinople', 'Coast', 'Yes', 6, 1044, 438, 522, 219),
	array('Constanta', 'Coast', 'Yes', 4, 1096, 234, 548, 117),
	array('Creta', 'Coast', 'Yes', 0, 840, 830, 420, 415),
	array('Croatia', 'Coast', 'No', 0, 269, 181, 136, 92),
	array('Cypres', 'Coast', 'Yes', 0, 1258, 880, 629, 440),
	array('Dubruja', 'Coast', 'Yes', 0, 1076, 290, 538, 145),
	array('Epirus', 'Coast', 'No', 3, 626, 606, 313, 303),
	array('Galati', 'Coast', 'Yes', 4, 986, 180, 495, 85),
	array('Hercegovina', 'Coast', 'No', 0, 426, 338, 213, 169),
	array('Izmit', 'Coast', 'Yes', 6, 1206, 510, 603, 255),
	array('Kols', 'Land', 'No', 2, 1002, 314, 501, 157),
	array('Macedonia', 'Land', 'No', 0, 746, 426, 373, 213),
	array('Malta', 'Coast', 'Yes', 0, 250, 858, 125, 429),
	array('Montenegro', 'Coast', 'Yes', 1, 488, 384, 244, 192),
	array('Mt. Jara', 'Land', 'No', 0, 566, 390, 283, 195),
	array('Nish', 'Land', 'Yes', 5, 638, 334, 319, 167),
	array('Oltenia', 'Land', 'No', 4, 782, 294, 391, 147),
	array('Plovdiv', 'Land', 'Yes', 2, 920, 404, 460, 202),
	array('Rhodes', 'Coast', 'Yes', 0, 1088, 778, 544, 389),
	array('Solonika', 'Coast', 'Yes', 3, 700, 530, 350, 265),
	array('Skopje', 'Land', 'Yes', 5, 634, 436, 317, 218),
	array('Smyrna', 'Coast', 'Yes', 6, 1050, 592, 525, 296),
	array('Sofia', 'Land', 'Yes', 2, 802, 384, 401, 192),
	array('Sparta', 'Coast', 'Yes', 3, 680, 688, 340, 344),
	array('Thrace', 'Coast', 'Yes', 2, 938, 470, 469, 235),
	array('Tirana', 'Coast', 'Yes', 1, 544, 430, 272, 215),
	array('Transylvania', 'Land', 'No', 0, 848, 108, 424, 54),
	array('Trieste', 'Coast', 'Yes', 0, 91, 260, 34, 82),
	array('Valona', 'Coast', 'Yes', 1, 528, 514, 264, 257),
	array('Varna', 'Coast', 'Yes', 2, 1030, 392, 515, 196),
	array('Aegaean Sea', 'Sea', 'No', 0, 884, 570, 442, 285),
	array('Central Mediterranean Sea', 'Sea', 'No', 0, 124, 728, 62, 364),
	array('Corinthian Sea', 'Sea', 'No', 0, 538, 728, 269, 364),
	array('Cyclades', 'Sea', 'No', 0, 940, 732, 470, 366),
	array('East Mediterranean Sea', 'Sea', 'No', 0, 1224, 820, 612, 410),
	array('Ionian Sea', 'Sea', 'No', 0, 366, 656, 183, 328),
	array('Mamera Sea', 'Sea', 'No', 0, 1122, 478, 561, 239),
	array('North Adriatic Sea', 'Sea', 'No', 0, 198, 256, 99, 128),
	array('North Black Sea', 'Sea', 'No', 0, 1284, 248, 642, 124),
	array('South Adriatic Sea', 'Sea', 'No', 0, 452, 476, 226, 238),
	array('South Black Sea', 'Sea', 'No', 0, 1148, 378, 574, 189),
	array('South Mediterranean Sea', 'Sea', 'No', 0, 768, 886, 384, 443)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Apulia','Trieste','Yes','Yes'),
	array('Apulia','Central Mediterranean Sea','Yes','No'),
	array('Apulia','Ionian Sea','Yes','No'),
	array('Apulia','South Adriatic Sea','Yes','No'),
	array('Arda','Constantinople','No','Yes'),
	array('Arda','Plovdiv','No','Yes'),
	array('Arda','Thrace','No','Yes'),
	array('Arda','Varna','No','Yes'),
	array('Athens','Epirus','Yes','Yes'),
	array('Athens','Solonika','Yes','Yes'),
	array('Athens','Sparta','Yes','Yes'),
	array('Athens','Aegaean Sea','Yes','No'),
	array('Athens','Corinthian Sea','Yes','No'),
	array('Athens','Cyclades','Yes','No'),
	array('Belgrade','Bucharest','No','Yes'),
	array('Belgrade','Croatia','No','Yes'),
	array('Belgrade','Hercegovina','No','Yes'),
	array('Belgrade','Montenegro','No','Yes'),
	array('Belgrade','Nish','No','Yes'),
	array('Belgrade','Transylvania','No','Yes'),
	array('Bessarabia','Cluj','No','Yes'),
	array('Bessarabia','Constanta','Yes','Yes'),
	array('Bessarabia','Galati','Yes','Yes'),
	array('Bessarabia','Transylvania','No','Yes'),
	array('Bessarabia','North Black Sea','Yes','No'),
	array('Bithynia','Cilicia','No','Yes'),
	array('Bithynia','Izmit','Yes','Yes'),
	array('Bithynia','North Black Sea','Yes','No'),
	array('Bosnia','Croatia','Yes','Yes'),
	array('Bosnia','Hercegovina','Yes','Yes'),
	array('Bosnia','North Adriatic Sea','Yes','No'),
	array('Bucharest','Constanta','No','Yes'),
	array('Bucharest','Dubruja','No','Yes'),
	array('Bucharest','Galati','No','Yes'),
	array('Bucharest','Nish','No','Yes'),
	array('Bucharest','Oltenia','No','Yes'),
	array('Bucharest','Sofia','No','Yes'),
	array('Bucharest','Transylvania','No','Yes'),
	array('Cilicia','Izmit','No','Yes'),
	array('Cilicia','Smyrna','Yes','Yes'),
	array('Cilicia','East Mediterranean Sea','Yes','No'),
	array('Cluj','Croatia','No','Yes'),
	array('Cluj','Transylvania','No','Yes'),
	array('Constantinople','Izmit','Yes','Yes'),
	array('Constantinople','Smyrna','Yes','Yes'),
	array('Constantinople','Thrace','Yes','Yes'),
	array('Constantinople','Varna','Yes','Yes'),
	array('Constantinople','Aegaean Sea','Yes','No'),
	array('Constantinople','Mamera Sea','Yes','No'),
	array('Constantinople','South Black Sea','Yes','No'),
	array('Constanta','Dubruja','Yes','Yes'),
	array('Constanta','Galati','Yes','Yes'),
	array('Constanta','North Black Sea','Yes','No'),
	array('Creta','Corinthian Sea','Yes','No'),
	array('Creta','Cyclades','Yes','No'),
	array('Creta','South Mediterranean Sea','Yes','No'),
	array('Croatia','Hercegovina','Yes','Yes'),
	array('Croatia','Transylvania','No','Yes'),
	array('Croatia','Trieste','Yes','Yes'),
	array('Croatia','North Adriatic Sea','Yes','No'),
	array('Cypres','East Mediterranean Sea','Yes','No'),
	array('Cypres','South Mediterranean Sea','Yes','No'),
	array('Dubruja','Kols','No','Yes'),
	array('Dubruja','Sofia','No','Yes'),
	array('Dubruja','Varna','Yes','Yes'),
	array('Dubruja','North Black Sea','Yes','No'),
	array('Dubruja','South Black Sea','Yes','No'),
	array('Epirus','Solonika','No','Yes'),
	array('Epirus','Sparta','Yes','Yes'),
	array('Epirus','Valona','Yes','Yes'),
	array('Epirus','Corinthian Sea','Yes','No'),
	array('Galati','Transylvania','No','Yes'),
	array('Hercegovina','Montenegro','Yes','Yes'),
	array('Hercegovina','North Adriatic Sea','Yes','No'),
	array('Izmit','Smyrna','Yes','Yes'),
	array('Izmit','Mamera Sea','Yes','No'),
	array('Izmit','North Black Sea','Yes','No'),
	array('Izmit','South Black Sea','Yes','No'),
	array('Kols','Sofia','No','Yes'),
	array('Kols','Varna','No','Yes'),
	array('Macedonia','Plovdiv','No','Yes'),
	array('Macedonia','Solonika','No','Yes'),
	array('Macedonia','Skopje','No','Yes'),
	array('Macedonia','Sofia','No','Yes'),
	array('Macedonia','Thrace','No','Yes'),
	array('Malta','Central Mediterranean Sea','Yes','No'),
	array('Malta','Corinthian Sea','Yes','No'),
	array('Malta','Ionian Sea','Yes','No'),
	array('Malta','South Mediterranean Sea','Yes','No'),
	array('Montenegro','Mt. Jara','No','Yes'),
	array('Montenegro','Nish','No','Yes'),
	array('Montenegro','Tirana','Yes','Yes'),
	array('Montenegro','North Adriatic Sea','Yes','No'),
	array('Montenegro','South Adriatic Sea','Yes','No'),
	array('Mt. Jara','Nish','No','Yes'),
	array('Mt. Jara','Tirana','No','Yes'),
	array('Nish','Oltenia','No','Yes'),
	array('Nish','Skopje','No','Yes'),
	array('Nish','Sofia','No','Yes'),
	array('Nish','Tirana','No','Yes'),
	array('Oltenia','Sofia','No','Yes'),
	array('Plovdiv','Sofia','No','Yes'),
	array('Plovdiv','Thrace','No','Yes'),
	array('Plovdiv','Varna','No','Yes'),
	array('Rhodes','Cyclades','Yes','No'),
	array('Rhodes','East Mediterranean Sea','Yes','No'),
	array('Rhodes','South Mediterranean Sea','Yes','No'),
	array('Solonika','Skopje','No','Yes'),
	array('Solonika','Thrace','Yes','Yes'),
	array('Solonika','Valona','No','Yes'),
	array('Solonika','Aegaean Sea','Yes','No'),
	array('Skopje','Sofia','No','Yes'),
	array('Skopje','Tirana','No','Yes'),
	array('Skopje','Valona','No','Yes'),
	array('Smyrna','Aegaean Sea','Yes','No'),
	array('Smyrna','Cyclades','Yes','No'),
	array('Smyrna','East Mediterranean Sea','Yes','No'),
	array('Smyrna','Mamera Sea','Yes','No'),
	array('Sofia','Varna','No','Yes'),
	array('Sparta','Corinthian Sea','Yes','No'),
	array('Sparta','Cyclades','Yes','No'),
	array('Thrace','Aegaean Sea','Yes','No'),
	array('Tirana','Valona','Yes','Yes'),
	array('Tirana','South Adriatic Sea','Yes','No'),
	array('Trieste','North Adriatic Sea','Yes','No'),
	array('Trieste','South Adriatic Sea','Yes','No'),
	array('Valona','Corinthian Sea','Yes','No'),
	array('Valona','South Adriatic Sea','Yes','No'),
	array('Varna','South Black Sea','Yes','No'),
	array('Aegaean Sea','Cyclades','Yes','No'),
	array('Aegaean Sea','Mamera Sea','Yes','No'),
	array('Central Mediterranean Sea','Ionian Sea','Yes','No'),
	array('Corinthian Sea','Cyclades','Yes','No'),
	array('Corinthian Sea','Ionian Sea','Yes','No'),
	array('Corinthian Sea','South Adriatic Sea','Yes','No'),
	array('Corinthian Sea','South Mediterranean Sea','Yes','No'),
	array('Cyclades','East Mediterranean Sea','Yes','No'),
	array('Cyclades','South Mediterranean Sea','Yes','No'),
	array('East Mediterranean Sea','South Mediterranean Sea','Yes','No'),
	array('Ionian Sea','South Adriatic Sea','Yes','No'),
	array('Mamera Sea','South Black Sea','Yes','No'),
	array('North Adriatic Sea','South Adriatic Sea','Yes','No'),
	array('North Black Sea','South Black Sea','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
