<?php
// This is file installs the map data for the Empire4 variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Anchorage', 'Coast', 'Yes', 290, 270, 140, 125, 'British-Columbia'),
	array('Yukon', 'Coast', 'No', 384, 380, 192, 185, 'British-Columbia'),
	array('Calgary', 'Land', 'Yes', 530, 616, 265, 309, 'British-Columbia'),
	array('Northern BC', 'Land', 'No', 422, 510, 211, 272, 'British-Columbia'),
	array('Vancouver', 'Coast', 'Yes', 426, 638, 220, 332, 'British-Columbia'),
	array('Abitibi', 'Coast', 'No', 982, 675, 491, 336, 'Quebec'),
	array('Ungava', 'Coast', 'Yes', 985, 540, 495, 270, 'Quebec'),
	array('Cote-Nord', 'Coast', 'No', 1065, 595, 536, 295, 'Quebec'),
	array('Quebec', 'Coast', 'Yes', 1040, 675, 518, 339, 'Quebec'),
	array('Montreal', 'Coast', 'Yes', 1030, 710, 509, 357, 'Quebec'),
	array('Beauce', 'Coast', 'No', 1073, 708, 538, 355, 'Quebec'),
	array('Gaspesie', 'Coast', 'No', 1105, 630, 553, 315, 'Quebec'),
	array('San Francisco', 'Coast', 'Yes', 360, 880, 180, 442, 'California'),
	array('Los Angeles', 'Coast', 'Yes', 360, 952, 185, 476, 'California'),
	array('San Diego', 'Coast', 'Yes', 411, 1009, 210, 500, 'California'),
	array('Dallas', 'Land', 'Yes', 770, 1040, 385, 520, 'Texas'),
	array('Houston', 'Coast', 'Yes', 780, 1090, 397, 546, 'Texas'),
	array('San Antonio', 'Coast', 'Yes', 745, 1125, 368, 560, 'Texas'),
	array('West Texas', 'Land', 'No', 675, 1065, 337, 533, 'Texas'),
	array('Minneapolis', 'Coast', 'Yes', 768, 770, 387, 408, 'Heartland'),
	array('Iowa', 'Land', 'No', 790, 855, 395, 436, 'Heartland'),
	array('Indiana', 'Coast', 'No', 910, 875, 455, 435, 'Heartland'),
	array('Chicago', 'Coast', 'Yes', 868, 899, 436, 452, 'Heartland'),
	array('Milwaukee', 'Coast', 'Yes', 837, 815, 418, 410, 'Heartland'),
	array('Milwaukee (North Coast)', 'Coast', 'No', 818, 765, 409, 388, 'Heartland'),
	array('Milwaukee (East Coast)', 'Coast', 'No', 863, 824, 434, 412, 'Heartland'),
	array('West Pennsylvania', 'Coast', 'No', 1020, 830, 509, 415, 'New-York'),
	array('New York State', 'Coast', 'No', 1045, 782, 520, 392, 'New-York'),
	array('New York City', 'Coast', 'Yes', 1090, 788, 544, 393, 'New-York'),
	array('New Jersey', 'Coast', 'Yes', 1088, 818, 544, 409, 'New-York'),
	array('Philadelphia', 'Land', 'Yes', 1048, 810, 522, 414, 'New-York'),
	array('Florida Panhandle', 'Coast', 'No', 978, 1049, 493, 524, 'Florida'),
	array('Jacksonville', 'Coast', 'Yes', 1048, 1048, 524, 524, 'Florida'),
	array('Miami', 'Coast', 'Yes', 1058, 1088, 528, 545, 'Florida'),
	array('Tampa', 'Coast', 'Yes', 1023, 1058, 512, 531, 'Florida'),
	array('Havana', 'Coast', 'Yes', 1060, 1165, 538, 580, 'Cuba'),
	array('Holguin', 'Coast', 'Yes', 1184, 1155, 592, 579, 'Cuba'),
	array('Kingston', 'Coast', 'Yes', 1194, 1204, 597, 602, 'Cuba'),
	array('Camaguey', 'Coast', 'No', 1135, 1156, 565, 579, 'Cuba'),
	array('Camaguey (North Coast)', 'Coast', 'No', 1142, 1144, 571, 572, 'Cuba'),
	array('Camaguey (South Coast)', 'Coast', 'No', 1142, 1164, 569, 584, 'Cuba'),
	array('Guadalajara', 'Coast', 'Yes', 625, 1260, 310, 631, 'Mexico'),
	array('Potosi', 'Coast', 'No', 700, 1220, 344, 608, 'Mexico'),
	array('Veracruz', 'Coast', 'Yes', 780, 1280, 394, 639, 'Mexico'),
	array('Mexico', 'Land', 'Yes', 722, 1280, 363, 640, 'Mexico'),
	array('Guerrero', 'Coast', 'No', 680, 1298, 340, 649, 'Mexico'),
	array('Oaxaca', 'Coast', 'No', 748, 1320, 375, 660, 'Mexico'),
	array('Antioquia', 'Coast', 'No', 1280, 1350, 642, 672, 'Peru'),
	array('Guajira', 'Coast', 'No', 1306, 1294, 653, 647, 'Peru'),
	array('Vichada', 'Land', 'No', 1378, 1360, 689, 682, 'Peru'),
	array('Bogota', 'Land', 'Yes', 1364, 1410, 684, 703, 'Peru'),
	array('Lima', 'Coast', 'Yes', 1352, 1525, 674, 765, 'Peru'),
	array('Ecuador', 'Coast', 'No', 1245, 1520, 628, 760, 'Peru'),
	array('Cali', 'Coast', 'Yes', 1280, 1420, 640, 710, 'Peru'),
	array('Cali (North Coast)', 'Coast', 'No', 1256, 1358, 628, 679, 'Peru'),
	array('Cali (South Coast)', 'Coast', 'No', 1270, 1420, 635, 710, 'Peru'),
	array('North West Territories', 'Coast', 'No', 470, 390, 235, 195, 'Neutral'),
	array('Nunavut', 'Coast', 'No', 712, 385, 356, 190, 'Neutral'),
	array('Manitoba', 'Coast', 'Yes', 724, 615, 362, 295, 'Neutral'),
	array('Saskatchewan', 'Land', 'No', 624, 665, 312, 315, 'Neutral'),
	array('Northern Ontario', 'Coast', 'No', 866, 600, 445, 330, 'Neutral'),
	array('Western Ontario', 'Coast', 'No', 805, 685, 403, 362, 'Neutral'),
	array('Ontario', 'Coast', 'Yes', 980, 745, 465, 366, 'Neutral'),
	array('Labrador', 'Coast', 'No', 1125, 478, 559, 255, 'Neutral'),
	array('Nova Scotia', 'Coast', 'Yes', 1175, 663, 587, 330, 'Neutral'),
	array('Newfoundland', 'Coast', 'No', 1222, 532, 611, 278, 'Neutral'),
	array('Washington', 'Coast', 'Yes', 410, 742, 211, 360, 'Neutral'),
	array('Oregon', 'Coast', 'Yes', 410, 785, 205, 394, 'Neutral'),
	array('Idaho', 'Land', 'No', 485, 815, 240, 407, 'Neutral'),
	array('Arizona', 'Land', 'Yes', 508, 1005, 254, 505, 'Neutral'),
	array('Utah', 'Land', 'No', 518, 920, 259, 460, 'Neutral'),
	array('Nevada', 'Land', 'No', 438, 900, 219, 450, 'Neutral'),
	array('New Mexico', 'Land', 'No', 604, 1000, 302, 518, 'Neutral'),
	array('Colorado', 'Land', 'Yes', 610, 920, 300, 458, 'Neutral'),
	array('Wyoming', 'Land', 'No', 590, 855, 295, 420, 'Neutral'),
	array('Montana', 'Land', 'No', 560, 775, 280, 388, 'Neutral'),
	array('Oklahoma', 'Land', 'No', 750, 1000, 375, 500, 'Neutral'),
	array('Kansas', 'Land', 'Yes', 750, 925, 380, 462, 'Neutral'),
	array('Nebraska', 'Land', 'No', 725, 885, 352, 447, 'Neutral'),
	array('Dakotas', 'Land', 'No', 696, 805, 348, 405, 'Neutral'),
	array('Missouri', 'Coast', 'Yes', 818, 916, 408, 458, 'Neutral'),
	array('Arkansas', 'Coast', 'No', 830, 1000, 415, 491, 'Neutral'),
	array('Louisiana', 'Coast', 'Yes', 836, 1055, 419, 525, 'Neutral'),
	array('Lake Ontario', 'Sea', 'No', 1014, 776, 509, 388, 'Neutral'),
	array('Upper Peninsula', 'Coast', 'No', 875, 765, 437, 382, 'Neutral'),
	array('Michigan', 'Coast', 'Yes', 924, 802, 460, 398, 'Neutral'),
	array('Lake Michigan', 'Sea', 'No', 885, 810, 443, 406, 'Neutral'),
	array('Lake Superior', 'Sea', 'No', 868, 740, 437, 370, 'Neutral'),
	array('Lake Huron', 'Sea', 'No', 938, 768, 469, 384, 'Neutral'),
	array('Lake Erie', 'Sea', 'No', 968, 822, 492, 405, 'Neutral'),
	array('Ohio', 'Coast', 'Yes', 962, 855, 482, 436, 'Neutral'),
	array('Maine', 'Coast', 'No', 1118, 692, 560, 348, 'Neutral'),
	array('Vermont', 'Coast', 'No', 1080, 730, 540, 366, 'Neutral'),
	array('Massachusetts', 'Coast', 'Yes', 1100, 768, 555, 384, 'Neutral'),
	array('Washington DC', 'Coast', 'Yes', 1070, 850, 540, 429, 'Neutral'),
	array('Virginia', 'Coast', 'No', 1048, 880, 524, 440, 'Neutral'),
	array('West Virginia', 'Land', 'No', 997, 888, 498, 447, 'Neutral'),
	array('Kentucky', 'Coast', 'No', 950, 905, 472, 462, 'Neutral'),
	array('Tennessee', 'Coast', 'Yes', 950, 950, 473, 477, 'Neutral'),
	array('Deep South', 'Coast', 'No', 912, 1005, 467, 505, 'Neutral'),
	array('Georgia', 'Coast', 'Yes', 1002, 998, 499, 498, 'Neutral'),
	array('South Carolina', 'Coast', 'No', 1036, 972, 517, 489, 'Neutral'),
	array('North Carolina', 'Coast', 'Yes', 1065, 928, 535, 464, 'Neutral'),
	array('Haiti', 'Coast', 'No', 1270, 1142, 635, 571, 'Neutral'),
	array('Dominican Republic', 'Coast', 'Yes', 1330, 1126, 665, 563, 'Neutral'),
	array('Baja California', 'Coast', 'No', 449, 1116, 227, 558, 'Neutral'),
	array('Chihuahua', 'Coast', 'Yes', 560, 1100, 276, 565, 'Neutral'),
	array('Coahuila', 'Land', 'No', 668, 1145, 334, 578, 'Neutral'),
	array('Nuevo Leon', 'Coast', 'Yes', 745, 1185, 374, 591, 'Neutral'),
	array('Durango', 'Coast', 'Yes', 590, 1175, 300, 585, 'Neutral'),
	array('Chiapas', 'Coast', 'No', 847, 1320, 419, 661, 'Neutral'),
	array('Tabasco', 'Coast', 'No', 882, 1290, 439, 643, 'Neutral'),
	array('Yucatan', 'Coast', 'Yes', 944, 1242, 462, 632, 'Neutral'),
	array('El Salvador', 'Coast', 'No', 968, 1348, 484, 674, 'Neutral'),
	array('Panama', 'Coast', 'Yes', 1164, 1386, 582, 693, 'Neutral'),
	array('Venezuela', 'Coast', 'Yes', 1373, 1278, 687, 640, 'Neutral'),
	array('Hawaii', 'Coast', 'Yes', 186, 1308, 93, 654, 'Neutral'),
	array('Greenland', 'Coast', 'Yes', 1000, 100, 531, 75, 'Neutral'),
	array('Bering Sea', 'Sea', 'No', 78, 160, 39, 100, 'Neutral'),
	array('Arctic Ocean', 'Sea', 'No', 412, 118, 206, 59, 'Neutral'),
	array('Beaufort Sea', 'Sea', 'No', 472, 220, 236, 105, 'Neutral'),
	array('Hudson Bay', 'Sea', 'No', 834, 510, 417, 245, 'Neutral'),
	array('Baffin Bay', 'Sea', 'No', 905, 194, 440, 95, 'Neutral'),
	array('Sea of Labrador', 'Sea', 'No', 1108, 374, 554, 175, 'Neutral'),
	array('North Atlantic Ocean', 'Sea', 'No', 1310, 400, 650, 200, 'Neutral'),
	array('Gulf of St-Lawrence', 'Sea', 'No', 1165, 610, 595, 291, 'Neutral'),
	array('Massachusetts Bay', 'Sea', 'No', 1220, 715, 610, 363, 'Neutral'),
	array('Mid Atlantic Ocean', 'Sea', 'No', 1350, 770, 670, 380, 'Neutral'),
	array('Chesapeake Bay', 'Sea', 'No', 1180, 905, 590, 453, 'Neutral'),
	array('Cape May', 'Sea', 'No', 1180, 820, 597, 410, 'Neutral'),
	array('Sea of Sargasso', 'Sea', 'No', 1350, 945, 680, 475, 'Neutral'),
	array('Bermuda Triangle', 'Sea', 'No', 1260, 1048, 630, 515, 'Neutral'),
	array('East Coast', 'Sea', 'No', 1130, 985, 571, 485, 'Neutral'),
	array('Straits of Florida', 'Sea', 'No', 1105, 1115, 555, 558, 'Neutral'),
	array('East Caribbean Sea', 'Sea', 'No', 1280, 1190, 635, 597, 'Neutral'),
	array('Lesser Antilles', 'Sea', 'No', 1364, 1150, 685, 573, 'Neutral'),
	array('Apalachee Bay', 'Sea', 'No', 950, 1085, 488, 555, 'Neutral'),
	array('Gulf of Mexico', 'Sea', 'No', 864, 1155, 430, 573, 'Neutral'),
	array('Gulf of Campeche', 'Sea', 'No', 800, 1235, 400, 618, 'Neutral'),
	array('Straits of Yucatan', 'Sea', 'No', 1009, 1175, 505, 584, 'Neutral'),
	array('Gulf of Honduras', 'Sea', 'No', 1008, 1250, 500, 641, 'Neutral'),
	array('Cayman Trench', 'Sea', 'No', 1220, 1178, 611, 590, 'Neutral'),
	array('West Caribbean Sea', 'Sea', 'No', 1118, 1245, 563, 640, 'Neutral'),
	array('South Caribbean Sea', 'Sea', 'No', 1250, 1275, 625, 637, 'Neutral'),
	array('Gulf of Mosquitos', 'Sea', 'No', 1144, 1330, 572, 665, 'Neutral'),
	array('North Pacific Ocean', 'Sea', 'No', 130, 940, 65, 460, 'Neutral'),
	array('Gulf of Alaska', 'Sea', 'No', 130, 490, 78, 241, 'Neutral'),
	array('Queen Charlotte Sound', 'Sea', 'No', 270, 580, 135, 300, 'Neutral'),
	array('Straits of Juan de Fuca', 'Sea', 'No', 314, 702, 157, 330, 'Neutral'),
	array('West Coast', 'Sea', 'No', 280, 855, 140, 435, 'Neutral'),
	array('Mid Pacific Ocean', 'Sea', 'No', 410, 1280, 200, 625, 'Neutral'),
	array('Gulf of Santa Catalina', 'Sea', 'No', 354, 1010, 179, 499, 'Neutral'),
	array('South West Pacific Ocean', 'Sea', 'No', 140, 1440, 50, 710, 'Neutral'),
	array('Coast of Mexico', 'Sea', 'No', 680, 1370, 340, 680, 'Neutral'),
	array('Gulf of California', 'Sea', 'No', 540, 1225, 270, 603, 'Neutral'),
	array('Gulf of Tehuantepec', 'Sea', 'No', 825, 1363, 425, 686, 'Neutral'),
	array('South Pacific Ocean', 'Sea', 'No', 550, 1490, 280, 740, 'Neutral'),
	array('Galapagos', 'Sea', 'No', 1020, 1520, 505, 760, 'Neutral'),
	array('Gulf of Guayaquil', 'Sea', 'No', 1130, 1470, 580, 755, 'Neutral'),
	array('Gulf of Panama', 'Sea', 'No', 1210, 1405, 607, 697, 'Neutral'),
	array('Coronado Bay', 'Sea', 'No', 1075, 1433, 536, 717, 'Neutral'),
	array('Gulf of Fonseca', 'Sea', 'No', 978, 1390, 489, 690, 'Neutral'),
	array('New Brunswick', 'Coast', 'No', 1130, 650, 565, 324, 'Neutral'),
	array('New Brunswick (North Coast)', 'Coast', 'No', 1142, 636, 571, 318, 'Neutral'),
	array('New Brunswick (South Coast)', 'Coast', 'No', 1140, 676, 574, 338, 'Neutral'),
	array('Honduras', 'Coast', 'No', 1022, 1312, 511, 656, 'Neutral'),
	array('Honduras (North Coast)', 'Coast', 'No', 1000, 1305, 520, 645, 'Neutral'),
	array('Honduras (South Coast)', 'Coast', 'No', 995, 1345, 498, 674, 'Neutral'),
	array('Nicaragua', 'Coast', 'Yes', 1060, 1330, 530, 662, 'Neutral'),
	array('Nicaragua (East Coast)', 'Coast', 'No', 1078, 1322, 540, 661, 'Neutral'),
	array('Nicaragua (West Coast)', 'Coast', 'No', 1020, 1360, 510, 681, 'Neutral'),
	array('Costa Rica', 'Coast', 'No', 1097, 1382, 545, 691, 'Neutral'),
	array('Costa Rica (North Coast)', 'Coast', 'No', 1100, 1368, 549, 682, 'Neutral'),
	array('Costa Rica (South Coast)', 'Coast', 'No', 1100, 1395, 531, 697, 'Neutral'),
	array('Guatemala', 'Coast', 'Yes', 945, 1298, 470, 650, 'Neutral'),
	array('Guatemala (South Coast)', 'Coast', 'No', 926, 1350, 463, 675, 'Neutral'),
	array('Guatemala (East Coast)', 'Coast', 'No', 965, 1298, 484, 645, 'Neutral')
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $x, $y, $sx, $sy, $country)=$territoryRawRow;
	if( $country=='Neutral' )
		$countryID=0;
	else
		$countryID=$this->countryID($country);
		
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);
$bordersRawData=array(
	array('Anchorage','Yukon','Yes','Yes'),
	array('Anchorage','Northern BC','No','Yes'),
	array('Anchorage','Vancouver','Yes','Yes'),
	array('Anchorage','Bering Sea','Yes','No'),
	array('Anchorage','Arctic Ocean','Yes','No'),
	array('Anchorage','Beaufort Sea','Yes','No'),
	array('Anchorage','Gulf of Alaska','Yes','No'),
	array('Anchorage','Queen Charlotte Sound','Yes','No'),
	array('Yukon','Anchorage','Yes','Yes'),
	array('Yukon','Northern BC','No','Yes'),
	array('Yukon','North West Territories','Yes','Yes'),
	array('Yukon','Beaufort Sea','Yes','No'),
	array('Calgary','Northern BC','No','Yes'),
	array('Calgary','Vancouver','No','Yes'),
	array('Calgary','North West Territories','No','Yes'),
	array('Calgary','Saskatchewan','No','Yes'),
	array('Calgary','Montana','No','Yes'),
	array('Northern BC','Anchorage','No','Yes'),
	array('Northern BC','Yukon','No','Yes'),
	array('Northern BC','Calgary','No','Yes'),
	array('Northern BC','Vancouver','No','Yes'),
	array('Northern BC','North West Territories','No','Yes'),
	array('Vancouver','Anchorage','Yes','Yes'),
	array('Vancouver','Calgary','No','Yes'),
	array('Vancouver','Northern BC','No','Yes'),
	array('Vancouver','Washington','Yes','Yes'),
	array('Vancouver','Idaho','No','Yes'),
	array('Vancouver','Montana','No','Yes'),
	array('Vancouver','Queen Charlotte Sound','Yes','No'),
	array('Vancouver','Straits of Juan de Fuca','Yes','No'),
	array('Abitibi','Ungava','Yes','Yes'),
	array('Abitibi','Quebec','No','Yes'),
	array('Abitibi','Montreal','No','Yes'),
	array('Abitibi','Northern Ontario','Yes','Yes'),
	array('Abitibi','Hudson Bay','Yes','No'),
	array('Ungava','Abitibi','Yes','Yes'),
	array('Ungava','Cote-Nord','No','Yes'),
	array('Ungava','Quebec','No','Yes'),
	array('Ungava','Nunavut','Yes','Yes'),
	array('Ungava','Labrador','Yes','Yes'),
	array('Ungava','Hudson Bay','Yes','No'),
	array('Ungava','Sea of Labrador','Yes','No'),
	array('Cote-Nord','Ungava','No','Yes'),
	array('Cote-Nord','Quebec','Yes','Yes'),
	array('Cote-Nord','Labrador','Yes','Yes'),
	array('Cote-Nord','Gulf of St-Lawrence','Yes','No'),
	array('Quebec','Abitibi','No','Yes'),
	array('Quebec','Ungava','No','Yes'),
	array('Quebec','Cote-Nord','Yes','Yes'),
	array('Quebec','Montreal','Yes','Yes'),
	array('Quebec','Beauce','Yes','Yes'),
	array('Quebec','Gaspesie','Yes','Yes'),
	array('Quebec','Gulf of St-Lawrence','Yes','No'),
	array('Montreal','Abitibi','No','Yes'),
	array('Montreal','Quebec','Yes','Yes'),
	array('Montreal','Beauce','Yes','Yes'),
	array('Montreal','Northern Ontario','No','Yes'),
	array('Montreal','Ontario','Yes','Yes'),
	array('Beauce','Quebec','Yes','Yes'),
	array('Beauce','Montreal','Yes','Yes'),
	array('Beauce','Gaspesie','Yes','Yes'),
	array('Beauce','New York State','Yes','Yes'),
	array('Beauce','Ontario','Yes','Yes'),
	array('Beauce','Maine','No','Yes'),
	array('Beauce','Vermont','No','Yes'),
	array('Gaspesie','Quebec','Yes','Yes'),
	array('Gaspesie','Beauce','Yes','Yes'),
	array('Gaspesie','Maine','No','Yes'),
	array('Gaspesie','Gulf of St-Lawrence','Yes','No'),
	array('Gaspesie','New Brunswick','No','Yes'),
	array('Gaspesie','New Brunswick (North Coast)','Yes','No'),
	array('San Francisco','Los Angeles','Yes','Yes'),
	array('San Francisco','Oregon','Yes','Yes'),
	array('San Francisco','Nevada','No','Yes'),
	array('San Francisco','West Coast','Yes','No'),
	array('Los Angeles','San Francisco','Yes','Yes'),
	array('Los Angeles','San Diego','Yes','Yes'),
	array('Los Angeles','Nevada','No','Yes'),
	array('Los Angeles','West Coast','Yes','No'),
	array('Los Angeles','Gulf of Santa Catalina','Yes','No'),
	array('San Diego','Los Angeles','Yes','Yes'),
	array('San Diego','Arizona','No','Yes'),
	array('San Diego','Nevada','No','Yes'),
	array('San Diego','Baja California','Yes','Yes'),
	array('San Diego','Gulf of Santa Catalina','Yes','No'),
	array('Dallas','Houston','No','Yes'),
	array('Dallas','San Antonio','No','Yes'),
	array('Dallas','West Texas','No','Yes'),
	array('Dallas','New Mexico','No','Yes'),
	array('Dallas','Oklahoma','No','Yes'),
	array('Dallas','Arkansas','No','Yes'),
	array('Dallas','Louisiana','No','Yes'),
	array('Houston','Dallas','No','Yes'),
	array('Houston','San Antonio','Yes','Yes'),
	array('Houston','Louisiana','Yes','Yes'),
	array('Houston','Gulf of Mexico','Yes','No'),
	array('San Antonio','Dallas','No','Yes'),
	array('San Antonio','Houston','Yes','Yes'),
	array('San Antonio','West Texas','No','Yes'),
	array('San Antonio','Coahuila','No','Yes'),
	array('San Antonio','Nuevo Leon','Yes','Yes'),
	array('San Antonio','Gulf of Mexico','Yes','No'),
	array('West Texas','Dallas','No','Yes'),
	array('West Texas','San Antonio','No','Yes'),
	array('West Texas','New Mexico','No','Yes'),
	array('West Texas','Chihuahua','No','Yes'),
	array('West Texas','Coahuila','No','Yes'),
	array('Minneapolis','Iowa','No','Yes'),
	array('Minneapolis','Milwaukee','No','Yes'),
	array('Minneapolis','Milwaukee (North Coast)','Yes','No'),
	array('Minneapolis','Manitoba','No','Yes'),
	array('Minneapolis','Western Ontario','Yes','Yes'),
	array('Minneapolis','Dakotas','No','Yes'),
	array('Minneapolis','Lake Superior','Yes','No'),
	array('Iowa','Minneapolis','No','Yes'),
	array('Iowa','Chicago','No','Yes'),
	array('Iowa','Milwaukee','No','Yes'),
	array('Iowa','Nebraska','No','Yes'),
	array('Iowa','Dakotas','No','Yes'),
	array('Iowa','Missouri','No','Yes'),
	array('Indiana','Chicago','Yes','Yes'),
	array('Indiana','Michigan','Yes','Yes'),
	array('Indiana','Lake Michigan','Yes','No'),
	array('Indiana','Ohio','No','Yes'),
	array('Indiana','Kentucky','No','Yes'),
	array('Chicago','Iowa','No','Yes'),
	array('Chicago','Indiana','Yes','Yes'),
	array('Chicago','Milwaukee','No','Yes'),
	array('Chicago','Milwaukee (East Coast)','Yes','No'),
	array('Chicago','Missouri','Yes','Yes'),
	array('Chicago','Lake Michigan','Yes','No'),
	array('Chicago','Kentucky','Yes','Yes'),
	array('Milwaukee','Minneapolis','No','Yes'),
	array('Milwaukee','Iowa','No','Yes'),
	array('Milwaukee','Chicago','No','Yes'),
	array('Milwaukee','Upper Peninsula','No','Yes'),
	array('Milwaukee (North Coast)','Minneapolis','Yes','No'),
	array('Milwaukee (North Coast)','Upper Peninsula','Yes','No'),
	array('Milwaukee (North Coast)','Lake Superior','Yes','No'),
	array('Milwaukee (East Coast)','Chicago','Yes','No'),
	array('Milwaukee (East Coast)','Upper Peninsula','Yes','No'),
	array('Milwaukee (East Coast)','Lake Michigan','Yes','No'),
	array('West Pennsylvania','New York State','Yes','Yes'),
	array('West Pennsylvania','Philadelphia','No','Yes'),
	array('West Pennsylvania','Lake Erie','Yes','No'),
	array('West Pennsylvania','Ohio','Yes','Yes'),
	array('West Pennsylvania','Washington DC','No','Yes'),
	array('West Pennsylvania','West Virginia','No','Yes'),
	array('New York State','Beauce','Yes','Yes'),
	array('New York State','West Pennsylvania','Yes','Yes'),
	array('New York State','New York City','No','Yes'),
	array('New York State','Philadelphia','No','Yes'),
	array('New York State','Ontario','Yes','Yes'),
	array('New York State','Lake Ontario','Yes','No'),
	array('New York State','Lake Erie','Yes','No'),
	array('New York State','Vermont','No','Yes'),
	array('New York State','Massachusetts','No','Yes'),
	array('New York City','New York State','No','Yes'),
	array('New York City','New Jersey','Yes','Yes'),
	array('New York City','Philadelphia','No','Yes'),
	array('New York City','Massachusetts','Yes','Yes'),
	array('New York City','Cape May','Yes','No'),
	array('New Jersey','New York City','Yes','Yes'),
	array('New Jersey','Philadelphia','No','Yes'),
	array('New Jersey','Washington DC','Yes','Yes'),
	array('New Jersey','Cape May','Yes','No'),
	array('Philadelphia','West Pennsylvania','No','Yes'),
	array('Philadelphia','New York State','No','Yes'),
	array('Philadelphia','New York City','No','Yes'),
	array('Philadelphia','New Jersey','No','Yes'),
	array('Philadelphia','Washington DC','No','Yes'),
	array('Florida Panhandle','Jacksonville','No','Yes'),
	array('Florida Panhandle','Tampa','Yes','Yes'),
	array('Florida Panhandle','Deep South','Yes','Yes'),
	array('Florida Panhandle','Georgia','No','Yes'),
	array('Florida Panhandle','Apalachee Bay','Yes','No'),
	array('Jacksonville','Florida Panhandle','No','Yes'),
	array('Jacksonville','Miami','Yes','Yes'),
	array('Jacksonville','Tampa','No','Yes'),
	array('Jacksonville','Georgia','Yes','Yes'),
	array('Jacksonville','East Coast','Yes','No'),
	array('Miami','Jacksonville','Yes','Yes'),
	array('Miami','Tampa','Yes','Yes'),
	array('Miami','East Coast','Yes','No'),
	array('Miami','Straits of Florida','Yes','No'),
	array('Miami','Apalachee Bay','Yes','No'),
	array('Tampa','Florida Panhandle','Yes','Yes'),
	array('Tampa','Jacksonville','No','Yes'),
	array('Tampa','Miami','Yes','Yes'),
	array('Tampa','Apalachee Bay','Yes','No'),
	array('Havana','Camaguey','No','Yes'),
	array('Havana','Camaguey (North Coast)','Yes','No'),
	array('Havana','Camaguey (South Coast)','Yes','No'),
	array('Havana','Straits of Florida','Yes','No'),
	array('Havana','Straits of Yucatan','Yes','No'),
	array('Havana','West Caribbean Sea','Yes','No'),
	array('Holguin','Camaguey','No','Yes'),
	array('Holguin','Camaguey (North Coast)','Yes','No'),
	array('Holguin','Camaguey (South Coast)','Yes','No'),
	array('Holguin','Bermuda Triangle','Yes','No'),
	array('Holguin','Cayman Trench','Yes','No'),
	array('Kingston','East Caribbean Sea','Yes','No'),
	array('Kingston','Cayman Trench','Yes','No'),
	array('Kingston','West Caribbean Sea','Yes','No'),
	array('Camaguey','Havana','No','Yes'),
	array('Camaguey','Holguin','No','Yes'),
	array('Camaguey (North Coast)','Havana','Yes','No'),
	array('Camaguey (North Coast)','Holguin','Yes','No'),
	array('Camaguey (North Coast)','Bermuda Triangle','Yes','No'),
	array('Camaguey (North Coast)','Straits of Florida','Yes','No'),
	array('Camaguey (South Coast)','Havana','Yes','No'),
	array('Camaguey (South Coast)','Holguin','Yes','No'),
	array('Camaguey (South Coast)','Cayman Trench','Yes','No'),
	array('Camaguey (South Coast)','West Caribbean Sea','Yes','No'),
	array('Guadalajara','Potosi','No','Yes'),
	array('Guadalajara','Mexico','No','Yes'),
	array('Guadalajara','Guerrero','Yes','Yes'),
	array('Guadalajara','Durango','Yes','Yes'),
	array('Guadalajara','Coast of Mexico','Yes','No'),
	array('Guadalajara','Gulf of California','Yes','No'),
	array('Potosi','Guadalajara','No','Yes'),
	array('Potosi','Veracruz','Yes','Yes'),
	array('Potosi','Mexico','No','Yes'),
	array('Potosi','Coahuila','No','Yes'),
	array('Potosi','Nuevo Leon','Yes','Yes'),
	array('Potosi','Durango','No','Yes'),
	array('Potosi','Gulf of Campeche','Yes','No'),
	array('Veracruz','Potosi','Yes','Yes'),
	array('Veracruz','Mexico','No','Yes'),
	array('Veracruz','Oaxaca','No','Yes'),
	array('Veracruz','Chiapas','No','Yes'),
	array('Veracruz','Tabasco','Yes','Yes'),
	array('Veracruz','Gulf of Campeche','Yes','No'),
	array('Mexico','Guadalajara','No','Yes'),
	array('Mexico','Potosi','No','Yes'),
	array('Mexico','Veracruz','No','Yes'),
	array('Mexico','Guerrero','No','Yes'),
	array('Mexico','Oaxaca','No','Yes'),
	array('Guerrero','Guadalajara','Yes','Yes'),
	array('Guerrero','Mexico','No','Yes'),
	array('Guerrero','Oaxaca','Yes','Yes'),
	array('Guerrero','Coast of Mexico','Yes','No'),
	array('Oaxaca','Veracruz','No','Yes'),
	array('Oaxaca','Mexico','No','Yes'),
	array('Oaxaca','Guerrero','Yes','Yes'),
	array('Oaxaca','Chiapas','Yes','Yes'),
	array('Oaxaca','Coast of Mexico','Yes','No'),
	array('Oaxaca','Gulf of Tehuantepec','Yes','No'),
	array('Antioquia','Guajira','Yes','Yes'),
	array('Antioquia','Vichada','No','Yes'),
	array('Antioquia','Bogota','No','Yes'),
	array('Antioquia','Cali','No','Yes'),
	array('Antioquia','Cali (North Coast)','Yes','No'),
	array('Antioquia','South Caribbean Sea','Yes','No'),
	array('Guajira','Antioquia','Yes','Yes'),
	array('Guajira','Vichada','No','Yes'),
	array('Guajira','Venezuela','Yes','Yes'),
	array('Guajira','South Caribbean Sea','Yes','No'),
	array('Vichada','Antioquia','No','Yes'),
	array('Vichada','Guajira','No','Yes'),
	array('Vichada','Bogota','No','Yes'),
	array('Vichada','Venezuela','No','Yes'),
	array('Bogota','Antioquia','No','Yes'),
	array('Bogota','Vichada','No','Yes'),
	array('Bogota','Lima','No','Yes'),
	array('Bogota','Ecuador','No','Yes'),
	array('Bogota','Cali','No','Yes'),
	array('Lima','Bogota','No','Yes'),
	array('Lima','Ecuador','Yes','Yes'),
	array('Lima','Galapagos','Yes','No'),
	array('Lima','Gulf of Guayaquil','Yes','No'),
	array('Ecuador','Bogota','No','Yes'),
	array('Ecuador','Lima','Yes','Yes'),
	array('Ecuador','Cali','No','Yes'),
	array('Ecuador','Cali (South Coast)','Yes','No'),
	array('Ecuador','Gulf of Guayaquil','Yes','No'),
	array('Cali','Antioquia','No','Yes'),
	array('Cali','Bogota','No','Yes'),
	array('Cali','Ecuador','No','Yes'),
	array('Cali','Panama','No','Yes'),
	array('Cali (North Coast)','Antioquia','Yes','No'),
	array('Cali (North Coast)','Panama','Yes','No'),
	array('Cali (North Coast)','South Caribbean Sea','Yes','No'),
	array('Cali (South Coast)','Ecuador','Yes','No'),
	array('Cali (South Coast)','Panama','Yes','No'),
	array('Cali (South Coast)','Gulf of Guayaquil','Yes','No'),
	array('Cali (South Coast)','Gulf of Panama','Yes','No'),
	array('North West Territories','Yukon','Yes','Yes'),
	array('North West Territories','Calgary','No','Yes'),
	array('North West Territories','Northern BC','No','Yes'),
	array('North West Territories','Nunavut','Yes','Yes'),
	array('North West Territories','Saskatchewan','No','Yes'),
	array('North West Territories','Arctic Ocean','Yes','No'),
	array('North West Territories','Beaufort Sea','Yes','No'),
	array('Nunavut','Ungava','Yes','Yes'),
	array('Nunavut','North West Territories','Yes','Yes'),
	array('Nunavut','Manitoba','Yes','Yes'),
	array('Nunavut','Saskatchewan','No','Yes'),
	array('Nunavut','Arctic Ocean','Yes','No'),
	array('Nunavut','Beaufort Sea','Yes','No'),
	array('Nunavut','Hudson Bay','Yes','No'),
	array('Nunavut','Baffin Bay','Yes','No'),
	array('Nunavut','Sea of Labrador','Yes','No'),
	array('Manitoba','Minneapolis','No','Yes'),
	array('Manitoba','Nunavut','Yes','Yes'),
	array('Manitoba','Saskatchewan','No','Yes'),
	array('Manitoba','Northern Ontario','Yes','Yes'),
	array('Manitoba','Western Ontario','No','Yes'),
	array('Manitoba','Dakotas','No','Yes'),
	array('Manitoba','Hudson Bay','Yes','No'),
	array('Saskatchewan','Calgary','No','Yes'),
	array('Saskatchewan','North West Territories','No','Yes'),
	array('Saskatchewan','Nunavut','No','Yes'),
	array('Saskatchewan','Manitoba','No','Yes'),
	array('Saskatchewan','Montana','No','Yes'),
	array('Saskatchewan','Dakotas','No','Yes'),
	array('Northern Ontario','Abitibi','Yes','Yes'),
	array('Northern Ontario','Montreal','No','Yes'),
	array('Northern Ontario','Manitoba','Yes','Yes'),
	array('Northern Ontario','Western Ontario','No','Yes'),
	array('Northern Ontario','Ontario','No','Yes'),
	array('Northern Ontario','Hudson Bay','Yes','No'),
	array('Western Ontario','Minneapolis','Yes','Yes'),
	array('Western Ontario','Manitoba','No','Yes'),
	array('Western Ontario','Northern Ontario','No','Yes'),
	array('Western Ontario','Ontario','Yes','Yes'),
	array('Western Ontario','Lake Superior','Yes','No'),
	array('Ontario','Montreal','Yes','Yes'),
	array('Ontario','Beauce','Yes','Yes'),
	array('Ontario','New York State','Yes','Yes'),
	array('Ontario','Northern Ontario','No','Yes'),
	array('Ontario','Western Ontario','Yes','Yes'),
	array('Ontario','Lake Ontario','Yes','No'),
	array('Ontario','Upper Peninsula','Yes','Yes'),
	array('Ontario','Michigan','Yes','Yes'),
	array('Ontario','Lake Superior','Yes','No'),
	array('Ontario','Lake Huron','Yes','No'),
	array('Ontario','Lake Erie','Yes','No'),
	array('Labrador','Ungava','Yes','Yes'),
	array('Labrador','Cote-Nord','Yes','Yes'),
	array('Labrador','Sea of Labrador','Yes','No'),
	array('Labrador','Gulf of St-Lawrence','Yes','No'),
	array('Nova Scotia','North Atlantic Ocean','Yes','No'),
	array('Nova Scotia','Gulf of St-Lawrence','Yes','No'),
	array('Nova Scotia','Massachusetts Bay','Yes','No'),
	array('Nova Scotia','New Brunswick','No','Yes'),
	array('Nova Scotia','New Brunswick (North Coast)','Yes','No'),
	array('Nova Scotia','New Brunswick (South Coast)','Yes','No'),
	array('Newfoundland','Sea of Labrador','Yes','No'),
	array('Newfoundland','North Atlantic Ocean','Yes','No'),
	array('Newfoundland','Gulf of St-Lawrence','Yes','No'),
	array('Washington','Vancouver','Yes','Yes'),
	array('Washington','Oregon','Yes','Yes'),
	array('Washington','Idaho','No','Yes'),
	array('Washington','Straits of Juan de Fuca','Yes','No'),
	array('Oregon','San Francisco','Yes','Yes'),
	array('Oregon','Washington','Yes','Yes'),
	array('Oregon','Idaho','No','Yes'),
	array('Oregon','Nevada','No','Yes'),
	array('Oregon','Straits of Juan de Fuca','Yes','No'),
	array('Oregon','West Coast','Yes','No'),
	array('Idaho','Vancouver','No','Yes'),
	array('Idaho','Washington','No','Yes'),
	array('Idaho','Oregon','No','Yes'),
	array('Idaho','Utah','No','Yes'),
	array('Idaho','Nevada','No','Yes'),
	array('Idaho','Wyoming','No','Yes'),
	array('Idaho','Montana','No','Yes'),
	array('Arizona','San Diego','No','Yes'),
	array('Arizona','Utah','No','Yes'),
	array('Arizona','Nevada','No','Yes'),
	array('Arizona','New Mexico','No','Yes'),
	array('Arizona','Colorado','No','Yes'),
	array('Arizona','Baja California','No','Yes'),
	array('Arizona','Chihuahua','No','Yes'),
	array('Utah','Idaho','No','Yes'),
	array('Utah','Arizona','No','Yes'),
	array('Utah','Nevada','No','Yes'),
	array('Utah','Colorado','No','Yes'),
	array('Utah','Wyoming','No','Yes'),
	array('Nevada','San Francisco','No','Yes'),
	array('Nevada','Los Angeles','No','Yes'),
	array('Nevada','San Diego','No','Yes'),
	array('Nevada','Oregon','No','Yes'),
	array('Nevada','Idaho','No','Yes'),
	array('Nevada','Arizona','No','Yes'),
	array('Nevada','Utah','No','Yes'),
	array('New Mexico','Dallas','No','Yes'),
	array('New Mexico','West Texas','No','Yes'),
	array('New Mexico','Arizona','No','Yes'),
	array('New Mexico','Colorado','No','Yes'),
	array('New Mexico','Oklahoma','No','Yes'),
	array('New Mexico','Chihuahua','No','Yes'),
	array('Colorado','Arizona','No','Yes'),
	array('Colorado','Utah','No','Yes'),
	array('Colorado','New Mexico','No','Yes'),
	array('Colorado','Wyoming','No','Yes'),
	array('Colorado','Oklahoma','No','Yes'),
	array('Colorado','Kansas','No','Yes'),
	array('Colorado','Nebraska','No','Yes'),
	array('Wyoming','Idaho','No','Yes'),
	array('Wyoming','Utah','No','Yes'),
	array('Wyoming','Colorado','No','Yes'),
	array('Wyoming','Montana','No','Yes'),
	array('Wyoming','Nebraska','No','Yes'),
	array('Wyoming','Dakotas','No','Yes'),
	array('Montana','Calgary','No','Yes'),
	array('Montana','Vancouver','No','Yes'),
	array('Montana','Saskatchewan','No','Yes'),
	array('Montana','Idaho','No','Yes'),
	array('Montana','Wyoming','No','Yes'),
	array('Montana','Dakotas','No','Yes'),
	array('Oklahoma','Dallas','No','Yes'),
	array('Oklahoma','New Mexico','No','Yes'),
	array('Oklahoma','Colorado','No','Yes'),
	array('Oklahoma','Kansas','No','Yes'),
	array('Oklahoma','Missouri','No','Yes'),
	array('Oklahoma','Arkansas','No','Yes'),
	array('Kansas','Colorado','No','Yes'),
	array('Kansas','Oklahoma','No','Yes'),
	array('Kansas','Nebraska','No','Yes'),
	array('Kansas','Missouri','No','Yes'),
	array('Nebraska','Iowa','No','Yes'),
	array('Nebraska','Colorado','No','Yes'),
	array('Nebraska','Wyoming','No','Yes'),
	array('Nebraska','Kansas','No','Yes'),
	array('Nebraska','Dakotas','No','Yes'),
	array('Nebraska','Missouri','No','Yes'),
	array('Dakotas','Minneapolis','No','Yes'),
	array('Dakotas','Iowa','No','Yes'),
	array('Dakotas','Manitoba','No','Yes'),
	array('Dakotas','Saskatchewan','No','Yes'),
	array('Dakotas','Wyoming','No','Yes'),
	array('Dakotas','Montana','No','Yes'),
	array('Dakotas','Nebraska','No','Yes'),
	array('Missouri','Iowa','No','Yes'),
	array('Missouri','Chicago','Yes','Yes'),
	array('Missouri','Oklahoma','No','Yes'),
	array('Missouri','Kansas','No','Yes'),
	array('Missouri','Nebraska','No','Yes'),
	array('Missouri','Arkansas','Yes','Yes'),
	array('Missouri','Kentucky','Yes','Yes'),
	array('Missouri','Tennessee','Yes','Yes'),
	array('Arkansas','Dallas','No','Yes'),
	array('Arkansas','Oklahoma','No','Yes'),
	array('Arkansas','Missouri','Yes','Yes'),
	array('Arkansas','Louisiana','Yes','Yes'),
	array('Arkansas','Tennessee','Yes','Yes'),
	array('Arkansas','Deep South','Yes','Yes'),
	array('Louisiana','Dallas','No','Yes'),
	array('Louisiana','Houston','Yes','Yes'),
	array('Louisiana','Arkansas','Yes','Yes'),
	array('Louisiana','Deep South','Yes','Yes'),
	array('Louisiana','Apalachee Bay','Yes','No'),
	array('Louisiana','Gulf of Mexico','Yes','No'),
	array('Lake Ontario','New York State','Yes','No'),
	array('Lake Ontario','Ontario','Yes','No'),
	array('Upper Peninsula','Milwaukee','No','Yes'),
	array('Upper Peninsula','Milwaukee (North Coast)','Yes','No'),
	array('Upper Peninsula','Milwaukee (East Coast)','Yes','No'),
	array('Upper Peninsula','Ontario','Yes','Yes'),
	array('Upper Peninsula','Michigan','Yes','Yes'),
	array('Upper Peninsula','Lake Michigan','Yes','No'),
	array('Upper Peninsula','Lake Superior','Yes','No'),
	array('Upper Peninsula','Lake Huron','Yes','No'),
	array('Michigan','Indiana','Yes','Yes'),
	array('Michigan','Ontario','Yes','Yes'),
	array('Michigan','Upper Peninsula','Yes','Yes'),
	array('Michigan','Lake Michigan','Yes','No'),
	array('Michigan','Lake Huron','Yes','No'),
	array('Michigan','Lake Erie','Yes','No'),
	array('Michigan','Ohio','Yes','Yes'),
	array('Lake Michigan','Indiana','Yes','No'),
	array('Lake Michigan','Chicago','Yes','No'),
	array('Lake Michigan','Milwaukee (East Coast)','Yes','No'),
	array('Lake Michigan','Upper Peninsula','Yes','No'),
	array('Lake Michigan','Michigan','Yes','No'),
	array('Lake Michigan','Lake Huron','Yes','No'),
	array('Lake Superior','Minneapolis','Yes','No'),
	array('Lake Superior','Milwaukee (North Coast)','Yes','No'),
	array('Lake Superior','Western Ontario','Yes','No'),
	array('Lake Superior','Ontario','Yes','No'),
	array('Lake Superior','Upper Peninsula','Yes','No'),
	array('Lake Huron','Ontario','Yes','No'),
	array('Lake Huron','Upper Peninsula','Yes','No'),
	array('Lake Huron','Michigan','Yes','No'),
	array('Lake Huron','Lake Michigan','Yes','No'),
	array('Lake Erie','West Pennsylvania','Yes','No'),
	array('Lake Erie','New York State','Yes','No'),
	array('Lake Erie','Ontario','Yes','No'),
	array('Lake Erie','Michigan','Yes','No'),
	array('Lake Erie','Ohio','Yes','No'),
	array('Ohio','Indiana','No','Yes'),
	array('Ohio','West Pennsylvania','Yes','Yes'),
	array('Ohio','Michigan','Yes','Yes'),
	array('Ohio','Lake Erie','Yes','No'),
	array('Ohio','West Virginia','No','Yes'),
	array('Ohio','Kentucky','No','Yes'),
	array('Maine','Beauce','No','Yes'),
	array('Maine','Gaspesie','No','Yes'),
	array('Maine','Vermont','Yes','Yes'),
	array('Maine','Massachusetts Bay','Yes','No'),
	array('Maine','New Brunswick','No','Yes'),
	array('Maine','New Brunswick (South Coast)','Yes','No'),
	array('Vermont','Beauce','No','Yes'),
	array('Vermont','New York State','No','Yes'),
	array('Vermont','Maine','Yes','Yes'),
	array('Vermont','Massachusetts','Yes','Yes'),
	array('Vermont','Massachusetts Bay','Yes','No'),
	array('Massachusetts','New York State','No','Yes'),
	array('Massachusetts','New York City','Yes','Yes'),
	array('Massachusetts','Vermont','Yes','Yes'),
	array('Massachusetts','Massachusetts Bay','Yes','No'),
	array('Massachusetts','Cape May','Yes','No'),
	array('Washington DC','West Pennsylvania','No','Yes'),
	array('Washington DC','New Jersey','Yes','Yes'),
	array('Washington DC','Philadelphia','No','Yes'),
	array('Washington DC','Virginia','Yes','Yes'),
	array('Washington DC','West Virginia','No','Yes'),
	array('Washington DC','Chesapeake Bay','Yes','No'),
	array('Washington DC','Cape May','Yes','No'),
	array('Virginia','Washington DC','Yes','Yes'),
	array('Virginia','West Virginia','No','Yes'),
	array('Virginia','Kentucky','No','Yes'),
	array('Virginia','Tennessee','No','Yes'),
	array('Virginia','North Carolina','Yes','Yes'),
	array('Virginia','Chesapeake Bay','Yes','No'),
	array('West Virginia','West Pennsylvania','No','Yes'),
	array('West Virginia','Ohio','No','Yes'),
	array('West Virginia','Washington DC','No','Yes'),
	array('West Virginia','Virginia','No','Yes'),
	array('West Virginia','Kentucky','No','Yes'),
	array('Kentucky','Indiana','No','Yes'),
	array('Kentucky','Chicago','Yes','Yes'),
	array('Kentucky','Missouri','Yes','Yes'),
	array('Kentucky','Ohio','No','Yes'),
	array('Kentucky','Virginia','No','Yes'),
	array('Kentucky','West Virginia','No','Yes'),
	array('Kentucky','Tennessee','Yes','Yes'),
	array('Tennessee','Missouri','Yes','Yes'),
	array('Tennessee','Arkansas','Yes','Yes'),
	array('Tennessee','Virginia','No','Yes'),
	array('Tennessee','Kentucky','Yes','Yes'),
	array('Tennessee','Deep South','Yes','Yes'),
	array('Tennessee','Georgia','No','Yes'),
	array('Tennessee','North Carolina','No','Yes'),
	array('Deep South','Florida Panhandle','Yes','Yes'),
	array('Deep South','Arkansas','Yes','Yes'),
	array('Deep South','Louisiana','Yes','Yes'),
	array('Deep South','Tennessee','Yes','Yes'),
	array('Deep South','Georgia','No','Yes'),
	array('Deep South','Apalachee Bay','Yes','No'),
	array('Georgia','Florida Panhandle','No','Yes'),
	array('Georgia','Jacksonville','Yes','Yes'),
	array('Georgia','Tennessee','No','Yes'),
	array('Georgia','Deep South','No','Yes'),
	array('Georgia','South Carolina','Yes','Yes'),
	array('Georgia','North Carolina','No','Yes'),
	array('Georgia','East Coast','Yes','No'),
	array('South Carolina','Georgia','Yes','Yes'),
	array('South Carolina','North Carolina','Yes','Yes'),
	array('South Carolina','East Coast','Yes','No'),
	array('North Carolina','Virginia','Yes','Yes'),
	array('North Carolina','Tennessee','No','Yes'),
	array('North Carolina','Georgia','No','Yes'),
	array('North Carolina','South Carolina','Yes','Yes'),
	array('North Carolina','Chesapeake Bay','Yes','No'),
	array('North Carolina','East Coast','Yes','No'),
	array('Haiti','Dominican Republic','Yes','Yes'),
	array('Haiti','Bermuda Triangle','Yes','No'),
	array('Haiti','East Caribbean Sea','Yes','No'),
	array('Haiti','Cayman Trench','Yes','No'),
	array('Dominican Republic','Haiti','Yes','Yes'),
	array('Dominican Republic','Sea of Sargasso','Yes','No'),
	array('Dominican Republic','Bermuda Triangle','Yes','No'),
	array('Dominican Republic','East Caribbean Sea','Yes','No'),
	array('Dominican Republic','Lesser Antilles','Yes','No'),
	array('Baja California','San Diego','Yes','Yes'),
	array('Baja California','Arizona','No','Yes'),
	array('Baja California','Chihuahua','Yes','Yes'),
	array('Baja California','North Pacific Ocean','Yes','No'),
	array('Baja California','Mid Pacific Ocean','Yes','No'),
	array('Baja California','Gulf of Santa Catalina','Yes','No'),
	array('Baja California','Gulf of California','Yes','No'),
	array('Chihuahua','West Texas','No','Yes'),
	array('Chihuahua','Arizona','No','Yes'),
	array('Chihuahua','New Mexico','No','Yes'),
	array('Chihuahua','Baja California','Yes','Yes'),
	array('Chihuahua','Coahuila','No','Yes'),
	array('Chihuahua','Durango','Yes','Yes'),
	array('Chihuahua','Gulf of California','Yes','No'),
	array('Coahuila','San Antonio','No','Yes'),
	array('Coahuila','West Texas','No','Yes'),
	array('Coahuila','Potosi','No','Yes'),
	array('Coahuila','Chihuahua','No','Yes'),
	array('Coahuila','Nuevo Leon','No','Yes'),
	array('Coahuila','Durango','No','Yes'),
	array('Nuevo Leon','San Antonio','Yes','Yes'),
	array('Nuevo Leon','Potosi','Yes','Yes'),
	array('Nuevo Leon','Coahuila','No','Yes'),
	array('Nuevo Leon','Gulf of Mexico','Yes','No'),
	array('Nuevo Leon','Gulf of Campeche','Yes','No'),
	array('Durango','Guadalajara','Yes','Yes'),
	array('Durango','Potosi','No','Yes'),
	array('Durango','Chihuahua','Yes','Yes'),
	array('Durango','Coahuila','No','Yes'),
	array('Durango','Gulf of California','Yes','No'),
	array('Chiapas','Veracruz','No','Yes'),
	array('Chiapas','Oaxaca','Yes','Yes'),
	array('Chiapas','Tabasco','No','Yes'),
	array('Chiapas','Gulf of Tehuantepec','Yes','No'),
	array('Chiapas','Guatemala','No','Yes'),
	array('Chiapas','Guatemala (South Coast)','Yes','No'),
	array('Tabasco','Veracruz','Yes','Yes'),
	array('Tabasco','Chiapas','No','Yes'),
	array('Tabasco','Yucatan','Yes','Yes'),
	array('Tabasco','Gulf of Campeche','Yes','No'),
	array('Tabasco','Guatemala','No','Yes'),
	array('Yucatan','Tabasco','Yes','Yes'),
	array('Yucatan','Gulf of Mexico','Yes','No'),
	array('Yucatan','Gulf of Campeche','Yes','No'),
	array('Yucatan','Straits of Yucatan','Yes','No'),
	array('Yucatan','Gulf of Honduras','Yes','No'),
	array('Yucatan','Guatemala','No','Yes'),
	array('Yucatan','Guatemala (East Coast)','Yes','No'),
	array('El Salvador','Coast of Mexico','Yes','No'),
	array('El Salvador','Gulf of Fonseca','Yes','No'),
	array('El Salvador','Honduras','No','Yes'),
	array('El Salvador','Honduras (South Coast)','Yes','No'),
	array('El Salvador','Guatemala','No','Yes'),
	array('El Salvador','Guatemala (South Coast)','Yes','No'),
	array('Panama','Cali','No','Yes'),
	array('Panama','Cali (North Coast)','Yes','No'),
	array('Panama','Cali (South Coast)','Yes','No'),
	array('Panama','South Caribbean Sea','Yes','No'),
	array('Panama','Gulf of Mosquitos','Yes','No'),
	array('Panama','Gulf of Panama','Yes','No'),
	array('Panama','Coronado Bay','Yes','No'),
	array('Panama','Costa Rica','No','Yes'),
	array('Panama','Costa Rica (North Coast)','Yes','No'),
	array('Panama','Costa Rica (South Coast)','Yes','No'),
	array('Venezuela','Guajira','Yes','Yes'),
	array('Venezuela','Vichada','No','Yes'),
	array('Venezuela','East Caribbean Sea','Yes','No'),
	array('Venezuela','Lesser Antilles','Yes','No'),
	array('Venezuela','South Caribbean Sea','Yes','No'),
	array('Hawaii','North Pacific Ocean','Yes','No'),
	array('Hawaii','Mid Pacific Ocean','Yes','No'),
	array('Hawaii','South West Pacific Ocean','Yes','No'),
	array('Hawaii','South Pacific Ocean','Yes','No'),
	array('Greenland','Arctic Ocean','Yes','No'),
	array('Greenland','Baffin Bay','Yes','No'),
	array('Greenland','Sea of Labrador','Yes','No'),
	array('Greenland','North Atlantic Ocean','Yes','No'),
	array('Bering Sea','Anchorage','Yes','No'),
	array('Bering Sea','Arctic Ocean','Yes','No'),
	array('Bering Sea','Gulf of Alaska','Yes','No'),
	array('Arctic Ocean','Anchorage','Yes','No'),
	array('Arctic Ocean','North West Territories','Yes','No'),
	array('Arctic Ocean','Nunavut','Yes','No'),
	array('Arctic Ocean','Greenland','Yes','No'),
	array('Arctic Ocean','Bering Sea','Yes','No'),
	array('Arctic Ocean','Beaufort Sea','Yes','No'),
	array('Arctic Ocean','Baffin Bay','Yes','No'),
	array('Beaufort Sea','Anchorage','Yes','No'),
	array('Beaufort Sea','Yukon','Yes','No'),
	array('Beaufort Sea','North West Territories','Yes','No'),
	array('Beaufort Sea','Nunavut','Yes','No'),
	array('Beaufort Sea','Arctic Ocean','Yes','No'),
	array('Hudson Bay','Abitibi','Yes','No'),
	array('Hudson Bay','Ungava','Yes','No'),
	array('Hudson Bay','Nunavut','Yes','No'),
	array('Hudson Bay','Manitoba','Yes','No'),
	array('Hudson Bay','Northern Ontario','Yes','No'),
	array('Hudson Bay','Sea of Labrador','Yes','No'),
	array('Baffin Bay','Nunavut','Yes','No'),
	array('Baffin Bay','Greenland','Yes','No'),
	array('Baffin Bay','Arctic Ocean','Yes','No'),
	array('Baffin Bay','Sea of Labrador','Yes','No'),
	array('Sea of Labrador','Ungava','Yes','No'),
	array('Sea of Labrador','Nunavut','Yes','No'),
	array('Sea of Labrador','Labrador','Yes','No'),
	array('Sea of Labrador','Newfoundland','Yes','No'),
	array('Sea of Labrador','Greenland','Yes','No'),
	array('Sea of Labrador','Hudson Bay','Yes','No'),
	array('Sea of Labrador','Baffin Bay','Yes','No'),
	array('Sea of Labrador','North Atlantic Ocean','Yes','No'),
	array('Sea of Labrador','Gulf of St-Lawrence','Yes','No'),
	array('North Atlantic Ocean','Nova Scotia','Yes','No'),
	array('North Atlantic Ocean','Newfoundland','Yes','No'),
	array('North Atlantic Ocean','Greenland','Yes','No'),
	array('North Atlantic Ocean','Sea of Labrador','Yes','No'),
	array('North Atlantic Ocean','Gulf of St-Lawrence','Yes','No'),
	array('North Atlantic Ocean','Massachusetts Bay','Yes','No'),
	array('North Atlantic Ocean','Mid Atlantic Ocean','Yes','No'),
	array('Gulf of St-Lawrence','Cote-Nord','Yes','No'),
	array('Gulf of St-Lawrence','Quebec','Yes','No'),
	array('Gulf of St-Lawrence','Gaspesie','Yes','No'),
	array('Gulf of St-Lawrence','Labrador','Yes','No'),
	array('Gulf of St-Lawrence','Nova Scotia','Yes','No'),
	array('Gulf of St-Lawrence','Newfoundland','Yes','No'),
	array('Gulf of St-Lawrence','Sea of Labrador','Yes','No'),
	array('Gulf of St-Lawrence','North Atlantic Ocean','Yes','No'),
	array('Gulf of St-Lawrence','New Brunswick (North Coast)','Yes','No'),
	array('Massachusetts Bay','Nova Scotia','Yes','No'),
	array('Massachusetts Bay','Maine','Yes','No'),
	array('Massachusetts Bay','Vermont','Yes','No'),
	array('Massachusetts Bay','Massachusetts','Yes','No'),
	array('Massachusetts Bay','North Atlantic Ocean','Yes','No'),
	array('Massachusetts Bay','Mid Atlantic Ocean','Yes','No'),
	array('Massachusetts Bay','Cape May','Yes','No'),
	array('Massachusetts Bay','New Brunswick (South Coast)','Yes','No'),
	array('Mid Atlantic Ocean','North Atlantic Ocean','Yes','No'),
	array('Mid Atlantic Ocean','Massachusetts Bay','Yes','No'),
	array('Mid Atlantic Ocean','Cape May','Yes','No'),
	array('Mid Atlantic Ocean','Sea of Sargasso','Yes','No'),
	array('Mid Atlantic Ocean','Bermuda Triangle','Yes','No'),
	array('Chesapeake Bay','Washington DC','Yes','No'),
	array('Chesapeake Bay','Virginia','Yes','No'),
	array('Chesapeake Bay','North Carolina','Yes','No'),
	array('Chesapeake Bay','Cape May','Yes','No'),
	array('Chesapeake Bay','East Coast','Yes','No'),
	array('Cape May','New York City','Yes','No'),
	array('Cape May','New Jersey','Yes','No'),
	array('Cape May','Massachusetts','Yes','No'),
	array('Cape May','Washington DC','Yes','No'),
	array('Cape May','Massachusetts Bay','Yes','No'),
	array('Cape May','Mid Atlantic Ocean','Yes','No'),
	array('Cape May','Chesapeake Bay','Yes','No'),
	array('Cape May','Bermuda Triangle','Yes','No'),
	array('Cape May','East Coast','Yes','No'),
	array('Sea of Sargasso','Dominican Republic','Yes','No'),
	array('Sea of Sargasso','Mid Atlantic Ocean','Yes','No'),
	array('Sea of Sargasso','Bermuda Triangle','Yes','No'),
	array('Sea of Sargasso','Lesser Antilles','Yes','No'),
	array('Bermuda Triangle','Holguin','Yes','No'),
	array('Bermuda Triangle','Camaguey (North Coast)','Yes','No'),
	array('Bermuda Triangle','Haiti','Yes','No'),
	array('Bermuda Triangle','Dominican Republic','Yes','No'),
	array('Bermuda Triangle','Mid Atlantic Ocean','Yes','No'),
	array('Bermuda Triangle','Cape May','Yes','No'),
	array('Bermuda Triangle','Sea of Sargasso','Yes','No'),
	array('Bermuda Triangle','East Coast','Yes','No'),
	array('Bermuda Triangle','Straits of Florida','Yes','No'),
	array('Bermuda Triangle','Cayman Trench','Yes','No'),
	array('East Coast','Jacksonville','Yes','No'),
	array('East Coast','Miami','Yes','No'),
	array('East Coast','Georgia','Yes','No'),
	array('East Coast','South Carolina','Yes','No'),
	array('East Coast','North Carolina','Yes','No'),
	array('East Coast','Chesapeake Bay','Yes','No'),
	array('East Coast','Cape May','Yes','No'),
	array('East Coast','Bermuda Triangle','Yes','No'),
	array('East Coast','Straits of Florida','Yes','No'),
	array('Straits of Florida','Miami','Yes','No'),
	array('Straits of Florida','Havana','Yes','No'),
	array('Straits of Florida','Camaguey (North Coast)','Yes','No'),
	array('Straits of Florida','Bermuda Triangle','Yes','No'),
	array('Straits of Florida','East Coast','Yes','No'),
	array('Straits of Florida','Apalachee Bay','Yes','No'),
	array('Straits of Florida','Gulf of Mexico','Yes','No'),
	array('Straits of Florida','Straits of Yucatan','Yes','No'),
	array('East Caribbean Sea','Kingston','Yes','No'),
	array('East Caribbean Sea','Haiti','Yes','No'),
	array('East Caribbean Sea','Dominican Republic','Yes','No'),
	array('East Caribbean Sea','Venezuela','Yes','No'),
	array('East Caribbean Sea','Lesser Antilles','Yes','No'),
	array('East Caribbean Sea','Cayman Trench','Yes','No'),
	array('East Caribbean Sea','West Caribbean Sea','Yes','No'),
	array('East Caribbean Sea','South Caribbean Sea','Yes','No'),
	array('Lesser Antilles','Dominican Republic','Yes','No'),
	array('Lesser Antilles','Venezuela','Yes','No'),
	array('Lesser Antilles','Sea of Sargasso','Yes','No'),
	array('Lesser Antilles','East Caribbean Sea','Yes','No'),
	array('Apalachee Bay','Florida Panhandle','Yes','No'),
	array('Apalachee Bay','Miami','Yes','No'),
	array('Apalachee Bay','Tampa','Yes','No'),
	array('Apalachee Bay','Louisiana','Yes','No'),
	array('Apalachee Bay','Deep South','Yes','No'),
	array('Apalachee Bay','Straits of Florida','Yes','No'),
	array('Apalachee Bay','Gulf of Mexico','Yes','No'),
	array('Gulf of Mexico','Houston','Yes','No'),
	array('Gulf of Mexico','San Antonio','Yes','No'),
	array('Gulf of Mexico','Louisiana','Yes','No'),
	array('Gulf of Mexico','Nuevo Leon','Yes','No'),
	array('Gulf of Mexico','Yucatan','Yes','No'),
	array('Gulf of Mexico','Straits of Florida','Yes','No'),
	array('Gulf of Mexico','Apalachee Bay','Yes','No'),
	array('Gulf of Mexico','Gulf of Campeche','Yes','No'),
	array('Gulf of Mexico','Straits of Yucatan','Yes','No'),
	array('Gulf of Campeche','Potosi','Yes','No'),
	array('Gulf of Campeche','Veracruz','Yes','No'),
	array('Gulf of Campeche','Nuevo Leon','Yes','No'),
	array('Gulf of Campeche','Tabasco','Yes','No'),
	array('Gulf of Campeche','Yucatan','Yes','No'),
	array('Gulf of Campeche','Gulf of Mexico','Yes','No'),
	array('Straits of Yucatan','Havana','Yes','No'),
	array('Straits of Yucatan','Yucatan','Yes','No'),
	array('Straits of Yucatan','Straits of Florida','Yes','No'),
	array('Straits of Yucatan','Gulf of Mexico','Yes','No'),
	array('Straits of Yucatan','Gulf of Honduras','Yes','No'),
	array('Straits of Yucatan','West Caribbean Sea','Yes','No'),
	array('Gulf of Honduras','Yucatan','Yes','No'),
	array('Gulf of Honduras','Straits of Yucatan','Yes','No'),
	array('Gulf of Honduras','West Caribbean Sea','Yes','No'),
	array('Gulf of Honduras','Honduras (North Coast)','Yes','No'),
	array('Gulf of Honduras','Guatemala (East Coast)','Yes','No'),
	array('Cayman Trench','Holguin','Yes','No'),
	array('Cayman Trench','Kingston','Yes','No'),
	array('Cayman Trench','Camaguey (South Coast)','Yes','No'),
	array('Cayman Trench','Haiti','Yes','No'),
	array('Cayman Trench','Bermuda Triangle','Yes','No'),
	array('Cayman Trench','East Caribbean Sea','Yes','No'),
	array('Cayman Trench','West Caribbean Sea','Yes','No'),
	array('West Caribbean Sea','Havana','Yes','No'),
	array('West Caribbean Sea','Kingston','Yes','No'),
	array('West Caribbean Sea','Camaguey (South Coast)','Yes','No'),
	array('West Caribbean Sea','East Caribbean Sea','Yes','No'),
	array('West Caribbean Sea','Straits of Yucatan','Yes','No'),
	array('West Caribbean Sea','Gulf of Honduras','Yes','No'),
	array('West Caribbean Sea','Cayman Trench','Yes','No'),
	array('West Caribbean Sea','South Caribbean Sea','Yes','No'),
	array('West Caribbean Sea','Gulf of Mosquitos','Yes','No'),
	array('West Caribbean Sea','Honduras (North Coast)','Yes','No'),
	array('West Caribbean Sea','Nicaragua (East Coast)','Yes','No'),
	array('South Caribbean Sea','Antioquia','Yes','No'),
	array('South Caribbean Sea','Guajira','Yes','No'),
	array('South Caribbean Sea','Cali (North Coast)','Yes','No'),
	array('South Caribbean Sea','Panama','Yes','No'),
	array('South Caribbean Sea','Venezuela','Yes','No'),
	array('South Caribbean Sea','East Caribbean Sea','Yes','No'),
	array('South Caribbean Sea','West Caribbean Sea','Yes','No'),
	array('South Caribbean Sea','Gulf of Mosquitos','Yes','No'),
	array('Gulf of Mosquitos','Panama','Yes','No'),
	array('Gulf of Mosquitos','West Caribbean Sea','Yes','No'),
	array('Gulf of Mosquitos','South Caribbean Sea','Yes','No'),
	array('Gulf of Mosquitos','Nicaragua (East Coast)','Yes','No'),
	array('Gulf of Mosquitos','Costa Rica (North Coast)','Yes','No'),
	array('North Pacific Ocean','Baja California','Yes','No'),
	array('North Pacific Ocean','Hawaii','Yes','No'),
	array('North Pacific Ocean','Gulf of Alaska','Yes','No'),
	array('North Pacific Ocean','West Coast','Yes','No'),
	array('North Pacific Ocean','Mid Pacific Ocean','Yes','No'),
	array('North Pacific Ocean','Gulf of Santa Catalina','Yes','No'),
	array('North Pacific Ocean','South West Pacific Ocean','Yes','No'),
	array('Gulf of Alaska','Anchorage','Yes','No'),
	array('Gulf of Alaska','Bering Sea','Yes','No'),
	array('Gulf of Alaska','North Pacific Ocean','Yes','No'),
	array('Gulf of Alaska','Queen Charlotte Sound','Yes','No'),
	array('Gulf of Alaska','Straits of Juan de Fuca','Yes','No'),
	array('Gulf of Alaska','West Coast','Yes','No'),
	array('Queen Charlotte Sound','Anchorage','Yes','No'),
	array('Queen Charlotte Sound','Vancouver','Yes','No'),
	array('Queen Charlotte Sound','Gulf of Alaska','Yes','No'),
	array('Queen Charlotte Sound','Straits of Juan de Fuca','Yes','No'),
	array('Straits of Juan de Fuca','Vancouver','Yes','No'),
	array('Straits of Juan de Fuca','Washington','Yes','No'),
	array('Straits of Juan de Fuca','Oregon','Yes','No'),
	array('Straits of Juan de Fuca','Gulf of Alaska','Yes','No'),
	array('Straits of Juan de Fuca','Queen Charlotte Sound','Yes','No'),
	array('Straits of Juan de Fuca','West Coast','Yes','No'),
	array('West Coast','San Francisco','Yes','No'),
	array('West Coast','Los Angeles','Yes','No'),
	array('West Coast','Oregon','Yes','No'),
	array('West Coast','North Pacific Ocean','Yes','No'),
	array('West Coast','Gulf of Alaska','Yes','No'),
	array('West Coast','Straits of Juan de Fuca','Yes','No'),
	array('West Coast','Gulf of Santa Catalina','Yes','No'),
	array('Mid Pacific Ocean','Baja California','Yes','No'),
	array('Mid Pacific Ocean','Hawaii','Yes','No'),
	array('Mid Pacific Ocean','North Pacific Ocean','Yes','No'),
	array('Mid Pacific Ocean','Coast of Mexico','Yes','No'),
	array('Mid Pacific Ocean','Gulf of California','Yes','No'),
	array('Mid Pacific Ocean','South Pacific Ocean','Yes','No'),
	array('Gulf of Santa Catalina','Los Angeles','Yes','No'),
	array('Gulf of Santa Catalina','San Diego','Yes','No'),
	array('Gulf of Santa Catalina','Baja California','Yes','No'),
	array('Gulf of Santa Catalina','North Pacific Ocean','Yes','No'),
	array('Gulf of Santa Catalina','West Coast','Yes','No'),
	array('South West Pacific Ocean','Hawaii','Yes','No'),
	array('South West Pacific Ocean','North Pacific Ocean','Yes','No'),
	array('South West Pacific Ocean','South Pacific Ocean','Yes','No'),
	array('Coast of Mexico','Guadalajara','Yes','No'),
	array('Coast of Mexico','Guerrero','Yes','No'),
	array('Coast of Mexico','Oaxaca','Yes','No'),
	array('Coast of Mexico','El Salvador','Yes','No'),
	array('Coast of Mexico','Mid Pacific Ocean','Yes','No'),
	array('Coast of Mexico','Gulf of California','Yes','No'),
	array('Coast of Mexico','Gulf of Tehuantepec','Yes','No'),
	array('Coast of Mexico','South Pacific Ocean','Yes','No'),
	array('Coast of Mexico','Galapagos','Yes','No'),
	array('Coast of Mexico','Gulf of Fonseca','Yes','No'),
	array('Coast of Mexico','Guatemala (South Coast)','Yes','No'),
	array('Gulf of California','Guadalajara','Yes','No'),
	array('Gulf of California','Baja California','Yes','No'),
	array('Gulf of California','Chihuahua','Yes','No'),
	array('Gulf of California','Durango','Yes','No'),
	array('Gulf of California','Mid Pacific Ocean','Yes','No'),
	array('Gulf of California','Coast of Mexico','Yes','No'),
	array('Gulf of Tehuantepec','Oaxaca','Yes','No'),
	array('Gulf of Tehuantepec','Chiapas','Yes','No'),
	array('Gulf of Tehuantepec','Coast of Mexico','Yes','No'),
	array('Gulf of Tehuantepec','Guatemala (South Coast)','Yes','No'),
	array('South Pacific Ocean','Hawaii','Yes','No'),
	array('South Pacific Ocean','Mid Pacific Ocean','Yes','No'),
	array('South Pacific Ocean','South West Pacific Ocean','Yes','No'),
	array('South Pacific Ocean','Coast of Mexico','Yes','No'),
	array('South Pacific Ocean','Galapagos','Yes','No'),
	array('Galapagos','Lima','Yes','No'),
	array('Galapagos','Coast of Mexico','Yes','No'),
	array('Galapagos','South Pacific Ocean','Yes','No'),
	array('Galapagos','Gulf of Guayaquil','Yes','No'),
	array('Galapagos','Gulf of Fonseca','Yes','No'),
	array('Gulf of Guayaquil','Lima','Yes','No'),
	array('Gulf of Guayaquil','Ecuador','Yes','No'),
	array('Gulf of Guayaquil','Cali (South Coast)','Yes','No'),
	array('Gulf of Guayaquil','Galapagos','Yes','No'),
	array('Gulf of Guayaquil','Gulf of Panama','Yes','No'),
	array('Gulf of Guayaquil','Coronado Bay','Yes','No'),
	array('Gulf of Guayaquil','Gulf of Fonseca','Yes','No'),
	array('Gulf of Panama','Cali (South Coast)','Yes','No'),
	array('Gulf of Panama','Panama','Yes','No'),
	array('Gulf of Panama','Gulf of Guayaquil','Yes','No'),
	array('Gulf of Panama','Coronado Bay','Yes','No'),
	array('Coronado Bay','Panama','Yes','No'),
	array('Coronado Bay','Gulf of Guayaquil','Yes','No'),
	array('Coronado Bay','Gulf of Panama','Yes','No'),
	array('Coronado Bay','Gulf of Fonseca','Yes','No'),
	array('Coronado Bay','Nicaragua (West Coast)','Yes','No'),
	array('Coronado Bay','Costa Rica (South Coast)','Yes','No'),
	array('Gulf of Fonseca','El Salvador','Yes','No'),
	array('Gulf of Fonseca','Coast of Mexico','Yes','No'),
	array('Gulf of Fonseca','Galapagos','Yes','No'),
	array('Gulf of Fonseca','Gulf of Guayaquil','Yes','No'),
	array('Gulf of Fonseca','Coronado Bay','Yes','No'),
	array('Gulf of Fonseca','Honduras (South Coast)','Yes','No'),
	array('Gulf of Fonseca','Nicaragua (West Coast)','Yes','No'),
	array('New Brunswick','Gaspesie','No','Yes'),
	array('New Brunswick','Nova Scotia','No','Yes'),
	array('New Brunswick','Maine','No','Yes'),
	array('New Brunswick (North Coast)','Gaspesie','Yes','No'),
	array('New Brunswick (North Coast)','Nova Scotia','Yes','No'),
	array('New Brunswick (North Coast)','Gulf of St-Lawrence','Yes','No'),
	array('New Brunswick (South Coast)','Nova Scotia','Yes','No'),
	array('New Brunswick (South Coast)','Maine','Yes','No'),
	array('New Brunswick (South Coast)','Massachusetts Bay','Yes','No'),
	array('Honduras','El Salvador','No','Yes'),
	array('Honduras','Nicaragua','No','Yes'),
	array('Honduras','Guatemala','No','Yes'),
	array('Honduras (North Coast)','Gulf of Honduras','Yes','No'),
	array('Honduras (North Coast)','West Caribbean Sea','Yes','No'),
	array('Honduras (North Coast)','Nicaragua (East Coast)','Yes','No'),
	array('Honduras (North Coast)','Guatemala (East Coast)','Yes','No'),
	array('Honduras (South Coast)','El Salvador','Yes','No'),
	array('Honduras (South Coast)','Gulf of Fonseca','Yes','No'),
	array('Honduras (South Coast)','Nicaragua (West Coast)','Yes','No'),
	array('Nicaragua','Honduras','No','Yes'),
	array('Nicaragua','Costa Rica','No','Yes'),
	array('Nicaragua (East Coast)','West Caribbean Sea','Yes','No'),
	array('Nicaragua (East Coast)','Gulf of Mosquitos','Yes','No'),
	array('Nicaragua (East Coast)','Honduras (North Coast)','Yes','No'),
	array('Nicaragua (East Coast)','Costa Rica (North Coast)','Yes','No'),
	array('Nicaragua (West Coast)','Coronado Bay','Yes','No'),
	array('Nicaragua (West Coast)','Gulf of Fonseca','Yes','No'),
	array('Nicaragua (West Coast)','Honduras (South Coast)','Yes','No'),
	array('Nicaragua (West Coast)','Costa Rica (South Coast)','Yes','No'),
	array('Costa Rica','Panama','No','Yes'),
	array('Costa Rica','Nicaragua','No','Yes'),
	array('Costa Rica (North Coast)','Panama','Yes','No'),
	array('Costa Rica (North Coast)','Gulf of Mosquitos','Yes','No'),
	array('Costa Rica (North Coast)','Nicaragua (East Coast)','Yes','No'),
	array('Costa Rica (South Coast)','Panama','Yes','No'),
	array('Costa Rica (South Coast)','Coronado Bay','Yes','No'),
	array('Costa Rica (South Coast)','Nicaragua (West Coast)','Yes','No'),
	array('Guatemala','Chiapas','No','Yes'),
	array('Guatemala','Tabasco','No','Yes'),
	array('Guatemala','Yucatan','No','Yes'),
	array('Guatemala','El Salvador','No','Yes'),
	array('Guatemala','Honduras','No','Yes'),
	array('Guatemala (South Coast)','Chiapas','Yes','No'),
	array('Guatemala (South Coast)','El Salvador','Yes','No'),
	array('Guatemala (South Coast)','Coast of Mexico','Yes','No'),
	array('Guatemala (South Coast)','Gulf of Tehuantepec','Yes','No'),
	array('Guatemala (East Coast)','Yucatan','Yes','No'),
	array('Guatemala (East Coast)','Gulf of Honduras','Yes','No'),
	array('Guatemala (East Coast)','Honduras (North Coast)','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
