<?php
// This is file installs the map data for the Rinascimento variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Geneve', 'Land', 'Yes', 87, 90, 47, 48, 'Neutral units'),
	array('Annecy', 'Land', 'No', 25, 142, 13, 71, 'French'),
	array('Domodossola', 'Land', 'No', 204, 66, 103, 32, 'French'),
	array('Sion', 'Land', 'No', 145, 153, 71, 77, 'Neutral'),
	array('Aosta', 'Land', 'Yes', 89, 218, 43, 110, 'Neutral'),
	array('Chambery', 'Land', 'Yes', 57, 260, 28, 130, 'Savoia'),
	array('Torino', 'Land', 'Yes', 112, 312, 56, 157, 'Savoia'),
	array('Briancon', 'Land', 'No', 29, 440, 15, 220, 'Neutral'),
	array('Nizza', 'Coast', 'Yes', 24, 566, 15, 282, 'Neutral'),
	array('Ventimiglia', 'Coast', 'Yes', 126, 502, 66, 249, 'Neutral'),
	array('Saluzzo', 'Land', 'No', 132, 399, 65, 200, 'Savoia'),
	array('Savona', 'Coast', 'No', 220, 424, 111, 212, 'Genova'),
	array('Asti', 'Land', 'No', 211, 358, 106, 179, 'Savoia'),
	array('Alessandria', 'Land', 'No', 267, 347, 135, 173, 'Milano'),
	array('Casale', 'Land', 'No', 237, 299, 120, 150, 'Savoia'),
	array('Vercelli', 'Land', 'No', 205, 225, 104, 112, 'Savoia'),
	array('Novara', 'Land', 'No', 187, 186, 94, 93, 'Milano'),
	array('Como', 'Land', 'Yes', 252, 210, 127, 107, 'Neutral'),
	array('Milano', 'Land', 'Yes', 308, 247, 154, 126, 'Milano'),
	array('Pavia', 'Land', 'Yes', 305, 289, 153, 144, 'Milano'),
	array('Bobbio', 'Land', 'No', 363, 322, 183, 160, 'Milano'),
	array('Genova', 'Coast', 'Yes', 318, 406, 160, 203, 'Genova'),
	array('La Spezia', 'Coast', 'Yes', 376, 439, 187, 221, 'Neutral'),
	array('Sarzana', 'Coast', 'No', 420, 461, 210, 231, 'Neutral'),
	array('Piacenza', 'Land', 'Yes', 403, 366, 200, 181, 'Milano'),
	array('Cremona', 'Land', 'No', 417, 288, 209, 145, 'Milano'),
	array('Lodi', 'Land', 'No', 363, 277, 183, 139, 'Milano'),
	array('Bergamo', 'Land', 'Yes', 362, 182, 181, 93, 'Neutral'),
	array('Sondrio', 'Land', 'No', 389, 136, 216, 55, 'Neutral'),
	array('Brescia', 'Land', 'Yes', 417, 245, 210, 124, 'Venezia'),
	array('Verona', 'Land', 'Yes', 532, 271, 252, 104, 'Venezia'),
	array('Arco', 'Land', 'No', 560, 144, 250, 63, 'Neutral'),
	array('Trento', 'Land', 'Yes', 489, 80, 242, 40, 'Neutral units'),
	array('Vicenza', 'Land', 'No', 558, 226, 278, 111, 'Venezia'),
	array('Treviso', 'Land', 'No', 637, 195, 319, 97, 'Venezia'),
	array('Udine', 'Land', 'Yes', 722, 96, 362, 48, 'Neutral'),
	array('Aquileia', 'Coast', 'No', 752, 199, 377, 100, 'Venezia'),
	array('Trieste', 'Coast', 'Yes', 796, 206, 396, 100, 'Neutral units'),
	array('Pola', 'Coast', 'Yes', 823, 297, 412, 148, 'Neutral'),
	array('Fiume', 'Coast', 'No', 955, 335, 477, 164, 'Venezia'),
	array('Zara', 'Coast', 'Yes', 1020, 466, 503, 229, 'Neutral'),
	array('Spalato', 'Coast', 'Yes', 1188, 548, 599, 277, 'Venezia'),
	array('Ragusa', 'Coast', 'No', 1306, 636, 654, 318, 'Neutral'),
	array('Chioggia', 'Coast', 'No', 729, 219, 366, 110, 'Venezia'),
	array('Venezia', 'Coast', 'Yes', 698, 237, 349, 117, 'Venezia'),
	array('Padova', 'Land', 'Yes', 604, 249, 302, 122, 'Neutral'),
	array('Adria', 'Coast', 'No', 667, 312, 334, 154, 'Ferrara'),
	array('Comacchio', 'Coast', 'Yes', 648, 352, 325, 178, 'Neutral'),
	array('Ferrara', 'Land', 'Yes', 591, 344, 296, 175, 'Ferrara'),
	array('Mantova', 'Land', 'Yes', 479, 326, 241, 164, 'Neutral'),
	array('Parma', 'Land', 'Yes', 452, 379, 225, 189, 'Neutral'),
	array('Modena', 'Land', 'Yes', 492, 389, 247, 195, 'Neutral'),
	array('Bologna', 'Land', 'Yes', 527, 410, 263, 206, 'Stato della Chiesa'),
	array('Ravenna', 'Coast', 'Yes', 656, 399, 334, 209, 'Neutral'),
	array('Forli', 'Land', 'No', 618, 455, 309, 226, 'Stato della Chiesa'),
	array('Castel del Rio', 'Land', 'No', 570, 453, 285, 229, 'Neutral'),
	array('Prato', 'Land', 'No', 500, 451, 249, 225, 'Firenze'),
	array('Lucca', 'Land', 'Yes', 455, 467, 228, 236, 'Neutral'),
	array('Pisa', 'Coast', 'Yes', 432, 519, 218, 264, 'Pisa'),
	array('Livorno', 'Coast', 'No', 460, 580, 230, 289, 'Firenze'),
	array('Firenze', 'Land', 'Yes', 523, 517, 260, 260, 'Firenze'),
	array('Arezzo', 'Land', 'Yes', 590, 524, 295, 263, 'Firenze'),
	array('Urbino', 'Land', 'Yes', 700, 503, 352, 255, 'Neutral'),
	array('Rimini', 'Coast', 'No', 779, 502, 385, 249, 'Stato della Chiesa'),
	array('Fabriano', 'Land', 'No', 744, 567, 371, 284, 'Stato della Chiesa'),
	array('Chiusi', 'Land', 'No', 664, 547, 331, 273, 'Stato della Chiesa'),
	array('Siena', 'Land', 'Yes', 592, 593, 296, 297, 'Siena'),
	array('Piombino', 'Coast', 'Yes', 491, 619, 245, 312, 'Neutral'),
	array('Grosseto', 'Coast', 'Yes', 532, 676, 261, 334, 'Neutral'),
	array('Viterbo', 'Coast', 'No', 578, 693, 289, 347, 'Stato della Chiesa'),
	array('Spoleto', 'Land', 'No', 728, 691, 363, 346, 'Stato della Chiesa'),
	array('Perugia', 'Land', 'Yes', 701, 630, 350, 317, 'Stato della Chiesa'),
	array('L\\\'Aquila', 'Land', 'Yes', 812, 736, 403, 368, 'Neutral'),
	array('Ancona', 'Coast', 'Yes', 824, 590, 415, 302, 'Neutral'),
	array('Pescara', 'Coast', 'No', 911, 703, 450, 347, 'Napoli'),
	array('Sulmona', 'Land', 'No', 851, 816, 426, 409, 'Napoli'),
	array('ROMA', 'Coast', 'Yes', 642, 756, 322, 379, 'Stato della Chiesa'),
	array('Ostia', 'Coast', 'Yes', 682, 802, 342, 400, 'Neutral'),
	array('Frosinone', 'Coast', 'No', 738, 836, 362, 413, 'Stato della Chiesa'),
	array('Napoli', 'Coast', 'Yes', 834, 873, 413, 437, 'Napoli'),
	array('Amalfi', 'Coast', 'Yes', 969, 1002, 477, 494, 'Napoli'),
	array('Potenza', 'Land', 'No', 960, 883, 479, 442, 'Napoli'),
	array('Benevento', 'Land', 'Yes', 916, 808, 457, 403, 'Stato della Chiesa'),
	array('Foggia', 'Coast', 'No', 1010, 788, 503, 393, 'Napoli'),
	array('Foggia (West Coast)', 'Coast', 'No', 1057, 726, 502, 370, 'Napoli'),
	array('Foggia (East Coast)', 'Coast', 'No', 1210, 879, 605, 440, 'Napoli'),
	array('Bari', 'Coast', 'Yes', 1165, 858, 582, 429, 'Neutral'),
	array('Brindisi', 'Coast', 'Yes', 1315, 960, 662, 516, 'Napoli'),
	array('Taranto', 'Coast', 'Yes', 1143, 979, 572, 491, 'Neutral'),
	array('Catanzaro', 'Coast', 'No', 1074, 1030, 537, 516, 'Napoli'),
	array('Catanzaro (East Coast)', 'Coast', 'No', 1187, 1156, 593, 555, 'Napoli'),
	array('Catanzaro (West Coast)', 'Coast', 'No', 1043, 1073, 533, 564, 'Napoli'),
	array('Reggio Calabria', 'Coast', 'Yes', 1068, 1305, 531, 655, 'Neutral'),
	array('Messina', 'Coast', 'No', 999, 1262, 467, 637, 'Napoli'),
	array('Catania', 'Coast', 'Yes', 964, 1370, 481, 684, 'Neutral'),
	array('Siracusa', 'Coast', 'Yes', 959, 1479, 467, 741, 'Neutral'),
	array('Agrigento', 'Coast', 'No', 821, 1420, 400, 706, 'Napoli'),
	array('Caltanissetta', 'Land', 'No', 886, 1348, 444, 672, 'Napoli'),
	array('Palermo', 'Coast', 'Yes', 684, 1292, 337, 673, 'Napoli'),
	array('Pantelleria', 'Coast', 'Yes', 624, 1470, 316, 736, 'Neutral'),
	array('Malta', 'Coast', 'Yes', 885, 1566, 448, 785, 'Neutral'),
	array('Cagliari', 'Coast', 'Yes', 241, 1174, 123, 585, 'Neutral'),
	array('Oristano', 'Coast', 'No', 257, 1031, 145, 520, 'Napoli'),
	array('Oristano (East Coast)', 'Coast', 'No', 326, 1033, 162, 501, 'Napoli'),
	array('Oristano (West Coast)', 'Coast', 'No', 192, 1033, 94, 499, 'Napoli'),
	array('Sassari', 'Coast', 'Yes', 238, 877, 117, 438, 'Neutral'),
	array('Ajaccio', 'Coast', 'Yes', 273, 812, 137, 406, 'Genova'),
	array('Aleria', 'Coast', 'No', 268, 734, 119, 341, 'Genova'),
	array('Aleria (East Coast)', 'Coast', 'No', 291, 736, 147, 367, 'Genova'),
	array('Aleria (West Coast)', 'Coast', 'No', 217, 659, 111, 323, 'Genova'),
	array('Bastia', 'Coast', 'Yes', 289, 598, 146, 301, 'Neutral'),
	array('Elba', 'Coast', 'Yes', 427, 611, 210, 310, 'Neutral'),
	array('Africa', 'Coast', 'No', 354, 1367, 177, 685, 'Turkish'),
	array('Laguna di Venezia', 'Sea', 'No', 720, 264, 356, 139, 'Neutral'),
	array('Litorale Adriatico', 'Sea', 'No', 759, 465, 370, 224, 'Neutral'),
	array('Central Adriatic Sea', 'Sea', 'No', 983, 585, 476, 278, 'Neutral'),
	array('Dalmatian Sea', 'Sea', 'No', 902, 403, 452, 202, 'Neutral'),
	array('Arcipelago di Spalato', 'Sea', 'No', 1221, 736, 615, 360, 'Turkish'),
	array('Terrazzo delle Tremiti', 'Sea', 'No', 1048, 682, 524, 346, 'Neutral'),
	array('Coast of Bari', 'Sea', 'No', 1332, 846, 657, 424, 'Neutral'),
	array('Channel of Otranto', 'Sea', 'No', 1366, 1034, 679, 474, 'Neutral'),
	array('Gulf of Taranto', 'Sea', 'No', 1234, 1124, 613, 562, 'Neutral'),
	array('East Gateway', 'Sea', 'No', 1354, 1209, 679, 612, 'Turkish'),
	array('Outer Ionian Sea', 'Sea', 'No', 1258, 1269, 630, 638, 'Turkish'),
	array('Inner Ionian Sea', 'Sea', 'No', 1165, 1216, 582, 611, 'Neutral'),
	array('Eastern Mediterranean Sea', 'Sea', 'No', 1158, 1447, 577, 733, 'Turkish'),
	array('Channel of Sicilia', 'Sea', 'No', 696, 1419, 349, 710, 'Neutral'),
	array('Fossa di Pantelleria', 'Sea', 'No', 740, 1536, 270, 764, 'Neutral'),
	array('Western Mediterranean Sea', 'Sea', 'No', 433, 1345, 215, 678, 'Neutral'),
	array('Bacino Avventura', 'Sea', 'No', 598, 1252, 315, 629, 'Neutral'),
	array('Strait of Messina', 'Sea', 'No', 1011, 1235, 505, 618, 'Neutral'),
	array('Terrazzo delle Lipari', 'Sea', 'No', 939, 1156, 471, 580, 'Neutral'),
	array('Coast of Amalfi', 'Sea', 'No', 1018, 1123, 511, 567, 'Neutral'),
	array('Eastern Thyrrenean Sea', 'Sea', 'No', 713, 988, 352, 492, 'Neutral'),
	array('Western Thyrrenean Sea', 'Sea', 'No', 406, 1201, 210, 605, 'Neutral'),
	array('Southern Sardinian Sea', 'Sea', 'No', 70, 1106, 40, 552, 'Neutral'),
	array('Northern Sardinian Sea', 'Sea', 'No', 70, 929, 51, 372, 'Neutral'),
	array('Western Ligurian Sea', 'Sea', 'No', 124, 592, 69, 298, 'Neutral'),
	array('Gulf of Genova', 'Sea', 'No', 274, 519, 129, 265, 'Neutral'),
	array('Eastern Ligurian Sea', 'Sea', 'No', 386, 548, 191, 275, 'Neutral'),
	array('Channel of Corsica', 'Sea', 'No', 362, 837, 183, 430, 'Neutral'),
	array('Bacino del Giglio', 'Sea', 'No', 538, 783, 267, 393, 'Neutral')
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $x, $y, $sx, $sy, $country)=$territoryRawRow;
	if( $country=='Neutral' )
		$countryID=0;
	else
		$countryID=$this->countryID($country);
		
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);
$bordersRawData=array(
	array('Geneve','Annecy','No','Yes'),
	array('Geneve','Domodossola','No','Yes'),
	array('Geneve','Sion','No','Yes'),
	array('Geneve','Aosta','No','Yes'),
	array('Annecy','Geneve','No','Yes'),
	array('Annecy','Aosta','No','Yes'),
	array('Annecy','Chambery','No','Yes'),
	array('Annecy','Briancon','No','Yes'),
	array('Domodossola','Geneve','No','Yes'),
	array('Domodossola','Sion','No','Yes'),
	array('Domodossola','Novara','No','Yes'),
	array('Sion','Geneve','No','Yes'),
	array('Sion','Domodossola','No','Yes'),
	array('Sion','Aosta','No','Yes'),
	array('Sion','Novara','No','Yes'),
	array('Aosta','Geneve','No','Yes'),
	array('Aosta','Annecy','No','Yes'),
	array('Aosta','Sion','No','Yes'),
	array('Aosta','Chambery','No','Yes'),
	array('Aosta','Torino','No','Yes'),
	array('Aosta','Vercelli','No','Yes'),
	array('Aosta','Novara','No','Yes'),
	array('Chambery','Annecy','No','Yes'),
	array('Chambery','Aosta','No','Yes'),
	array('Chambery','Torino','No','Yes'),
	array('Chambery','Briancon','No','Yes'),
	array('Torino','Aosta','No','Yes'),
	array('Torino','Chambery','No','Yes'),
	array('Torino','Briancon','No','Yes'),
	array('Torino','Saluzzo','No','Yes'),
	array('Torino','Asti','No','Yes'),
	array('Torino','Casale','No','Yes'),
	array('Torino','Vercelli','No','Yes'),
	array('Briancon','Annecy','No','Yes'),
	array('Briancon','Chambery','No','Yes'),
	array('Briancon','Torino','No','Yes'),
	array('Briancon','Nizza','No','Yes'),
	array('Briancon','Saluzzo','No','Yes'),
	array('Nizza','Briancon','No','Yes'),
	array('Nizza','Ventimiglia','Yes','Yes'),
	array('Nizza','Saluzzo','No','Yes'),
	array('Nizza','Western Ligurian Sea','Yes','No'),
	array('Ventimiglia','Nizza','Yes','Yes'),
	array('Ventimiglia','Saluzzo','No','Yes'),
	array('Ventimiglia','Savona','Yes','Yes'),
	array('Ventimiglia','Western Ligurian Sea','Yes','No'),
	array('Ventimiglia','Gulf of Genova','Yes','No'),
	array('Saluzzo','Torino','No','Yes'),
	array('Saluzzo','Briancon','No','Yes'),
	array('Saluzzo','Nizza','No','Yes'),
	array('Saluzzo','Ventimiglia','No','Yes'),
	array('Saluzzo','Savona','No','Yes'),
	array('Saluzzo','Asti','No','Yes'),
	array('Savona','Ventimiglia','Yes','Yes'),
	array('Savona','Saluzzo','No','Yes'),
	array('Savona','Asti','No','Yes'),
	array('Savona','Genova','Yes','Yes'),
	array('Savona','Gulf of Genova','Yes','No'),
	array('Asti','Torino','No','Yes'),
	array('Asti','Saluzzo','No','Yes'),
	array('Asti','Savona','No','Yes'),
	array('Asti','Alessandria','No','Yes'),
	array('Asti','Casale','No','Yes'),
	array('Asti','Genova','No','Yes'),
	array('Alessandria','Asti','No','Yes'),
	array('Alessandria','Casale','No','Yes'),
	array('Alessandria','Pavia','No','Yes'),
	array('Alessandria','Bobbio','No','Yes'),
	array('Alessandria','Genova','No','Yes'),
	array('Casale','Torino','No','Yes'),
	array('Casale','Asti','No','Yes'),
	array('Casale','Alessandria','No','Yes'),
	array('Casale','Vercelli','No','Yes'),
	array('Casale','Milano','No','Yes'),
	array('Casale','Pavia','No','Yes'),
	array('Vercelli','Aosta','No','Yes'),
	array('Vercelli','Torino','No','Yes'),
	array('Vercelli','Casale','No','Yes'),
	array('Vercelli','Novara','No','Yes'),
	array('Vercelli','Como','No','Yes'),
	array('Vercelli','Milano','No','Yes'),
	array('Novara','Domodossola','No','Yes'),
	array('Novara','Sion','No','Yes'),
	array('Novara','Aosta','No','Yes'),
	array('Novara','Vercelli','No','Yes'),
	array('Novara','Como','No','Yes'),
	array('Como','Vercelli','No','Yes'),
	array('Como','Novara','No','Yes'),
	array('Como','Milano','No','Yes'),
	array('Como','Sondrio','No','Yes'),
	array('Milano','Casale','No','Yes'),
	array('Milano','Vercelli','No','Yes'),
	array('Milano','Como','No','Yes'),
	array('Milano','Pavia','No','Yes'),
	array('Milano','Lodi','No','Yes'),
	array('Milano','Bergamo','No','Yes'),
	array('Milano','Sondrio','No','Yes'),
	array('Pavia','Alessandria','No','Yes'),
	array('Pavia','Casale','No','Yes'),
	array('Pavia','Milano','No','Yes'),
	array('Pavia','Bobbio','No','Yes'),
	array('Pavia','Lodi','No','Yes'),
	array('Bobbio','Alessandria','No','Yes'),
	array('Bobbio','Pavia','No','Yes'),
	array('Bobbio','Genova','No','Yes'),
	array('Bobbio','Piacenza','No','Yes'),
	array('Bobbio','Cremona','No','Yes'),
	array('Bobbio','Lodi','No','Yes'),
	array('Genova','Savona','Yes','Yes'),
	array('Genova','Asti','No','Yes'),
	array('Genova','Alessandria','No','Yes'),
	array('Genova','Bobbio','No','Yes'),
	array('Genova','La Spezia','Yes','Yes'),
	array('Genova','Gulf of Genova','Yes','No'),
	array('La Spezia','Genova','Yes','Yes'),
	array('La Spezia','Sarzana','Yes','Yes'),
	array('La Spezia','Gulf of Genova','Yes','No'),
	array('La Spezia','Eastern Ligurian Sea','Yes','No'),
	array('Sarzana','La Spezia','Yes','Yes'),
	array('Sarzana','Piacenza','No','Yes'),
	array('Sarzana','Parma','No','Yes'),
	array('Sarzana','Lucca','No','Yes'),
	array('Sarzana','Pisa','Yes','Yes'),
	array('Sarzana','Eastern Ligurian Sea','Yes','No'),
	array('Piacenza','Bobbio','No','Yes'),
	array('Piacenza','Sarzana','No','Yes'),
	array('Piacenza','Cremona','No','Yes'),
	array('Piacenza','Mantova','No','Yes'),
	array('Piacenza','Parma','No','Yes'),
	array('Cremona','Bobbio','No','Yes'),
	array('Cremona','Piacenza','No','Yes'),
	array('Cremona','Lodi','No','Yes'),
	array('Cremona','Brescia','No','Yes'),
	array('Cremona','Verona','No','Yes'),
	array('Cremona','Adria','No','Yes'),
	array('Cremona','Mantova','No','Yes'),
	array('Lodi','Milano','No','Yes'),
	array('Lodi','Pavia','No','Yes'),
	array('Lodi','Bobbio','No','Yes'),
	array('Lodi','Cremona','No','Yes'),
	array('Lodi','Bergamo','No','Yes'),
	array('Lodi','Brescia','No','Yes'),
	array('Bergamo','Milano','No','Yes'),
	array('Bergamo','Lodi','No','Yes'),
	array('Bergamo','Sondrio','No','Yes'),
	array('Bergamo','Brescia','No','Yes'),
	array('Sondrio','Como','No','Yes'),
	array('Sondrio','Milano','No','Yes'),
	array('Sondrio','Bergamo','No','Yes'),
	array('Sondrio','Brescia','No','Yes'),
	array('Sondrio','Arco','No','Yes'),
	array('Sondrio','Trento','No','Yes'),
	array('Brescia','Cremona','No','Yes'),
	array('Brescia','Lodi','No','Yes'),
	array('Brescia','Bergamo','No','Yes'),
	array('Brescia','Sondrio','No','Yes'),
	array('Brescia','Verona','No','Yes'),
	array('Brescia','Arco','No','Yes'),
	array('Verona','Cremona','No','Yes'),
	array('Verona','Brescia','No','Yes'),
	array('Verona','Arco','No','Yes'),
	array('Verona','Vicenza','No','Yes'),
	array('Verona','Padova','No','Yes'),
	array('Verona','Adria','No','Yes'),
	array('Arco','Sondrio','No','Yes'),
	array('Arco','Brescia','No','Yes'),
	array('Arco','Verona','No','Yes'),
	array('Arco','Trento','No','Yes'),
	array('Arco','Vicenza','No','Yes'),
	array('Trento','Sondrio','No','Yes'),
	array('Trento','Arco','No','Yes'),
	array('Trento','Vicenza','No','Yes'),
	array('Vicenza','Verona','No','Yes'),
	array('Vicenza','Arco','No','Yes'),
	array('Vicenza','Trento','No','Yes'),
	array('Vicenza','Treviso','No','Yes'),
	array('Vicenza','Udine','No','Yes'),
	array('Vicenza','Padova','No','Yes'),
	array('Treviso','Vicenza','No','Yes'),
	array('Treviso','Udine','No','Yes'),
	array('Treviso','Aquileia','No','Yes'),
	array('Treviso','Chioggia','No','Yes'),
	array('Treviso','Padova','No','Yes'),
	array('Udine','Vicenza','No','Yes'),
	array('Udine','Treviso','No','Yes'),
	array('Udine','Aquileia','No','Yes'),
	array('Aquileia','Treviso','No','Yes'),
	array('Aquileia','Udine','No','Yes'),
	array('Aquileia','Trieste','Yes','Yes'),
	array('Aquileia','Chioggia','Yes','Yes'),
	array('Aquileia','Laguna di Venezia','Yes','No'),
	array('Trieste','Aquileia','Yes','Yes'),
	array('Trieste','Pola','Yes','Yes'),
	array('Trieste','Fiume','No','Yes'),
	array('Trieste','Laguna di Venezia','Yes','No'),
	array('Trieste','Dalmatian Sea','Yes','No'),
	array('Pola','Trieste','Yes','Yes'),
	array('Pola','Fiume','Yes','Yes'),
	array('Pola','Dalmatian Sea','Yes','No'),
	array('Fiume','Trieste','No','Yes'),
	array('Fiume','Pola','Yes','Yes'),
	array('Fiume','Zara','Yes','Yes'),
	array('Fiume','Spalato','No','Yes'),
	array('Fiume','Ragusa','No','Yes'),
	array('Fiume','Dalmatian Sea','Yes','No'),
	array('Zara','Fiume','Yes','Yes'),
	array('Zara','Spalato','Yes','Yes'),
	array('Zara','Dalmatian Sea','Yes','No'),
	array('Zara','Arcipelago di Spalato','Yes','No'),
	array('Spalato','Fiume','No','Yes'),
	array('Spalato','Zara','Yes','Yes'),
	array('Spalato','Ragusa','Yes','Yes'),
	array('Spalato','Arcipelago di Spalato','Yes','No'),
	array('Ragusa','Fiume','No','Yes'),
	array('Ragusa','Spalato','Yes','Yes'),
	array('Ragusa','Arcipelago di Spalato','Yes','No'),
	array('Chioggia','Treviso','No','Yes'),
	array('Chioggia','Aquileia','Yes','Yes'),
	array('Chioggia','Venezia','Yes','Yes'),
	array('Chioggia','Padova','No','Yes'),
	array('Chioggia','Adria','Yes','Yes'),
	array('Chioggia','Laguna di Venezia','Yes','No'),
	array('Venezia','Chioggia','Yes','Yes'),
	array('Venezia','Laguna di Venezia','Yes','No'),
	array('Padova','Verona','No','Yes'),
	array('Padova','Vicenza','No','Yes'),
	array('Padova','Treviso','No','Yes'),
	array('Padova','Chioggia','No','Yes'),
	array('Padova','Adria','No','Yes'),
	array('Adria','Cremona','No','Yes'),
	array('Adria','Verona','No','Yes'),
	array('Adria','Chioggia','Yes','Yes'),
	array('Adria','Padova','No','Yes'),
	array('Adria','Comacchio','Yes','Yes'),
	array('Adria','Ferrara','No','Yes'),
	array('Adria','Mantova','No','Yes'),
	array('Adria','Laguna di Venezia','Yes','No'),
	array('Comacchio','Adria','Yes','Yes'),
	array('Comacchio','Ferrara','No','Yes'),
	array('Comacchio','Ravenna','Yes','Yes'),
	array('Comacchio','Laguna di Venezia','Yes','No'),
	array('Comacchio','Litorale Adriatico','Yes','No'),
	array('Ferrara','Adria','No','Yes'),
	array('Ferrara','Comacchio','No','Yes'),
	array('Ferrara','Mantova','No','Yes'),
	array('Ferrara','Modena','No','Yes'),
	array('Ferrara','Bologna','No','Yes'),
	array('Mantova','Piacenza','No','Yes'),
	array('Mantova','Cremona','No','Yes'),
	array('Mantova','Adria','No','Yes'),
	array('Mantova','Ferrara','No','Yes'),
	array('Mantova','Parma','No','Yes'),
	array('Mantova','Modena','No','Yes'),
	array('Parma','Sarzana','No','Yes'),
	array('Parma','Piacenza','No','Yes'),
	array('Parma','Mantova','No','Yes'),
	array('Parma','Modena','No','Yes'),
	array('Modena','Ferrara','No','Yes'),
	array('Modena','Mantova','No','Yes'),
	array('Modena','Parma','No','Yes'),
	array('Modena','Bologna','No','Yes'),
	array('Bologna','Ferrara','No','Yes'),
	array('Bologna','Modena','No','Yes'),
	array('Bologna','Ravenna','No','Yes'),
	array('Bologna','Castel del Rio','No','Yes'),
	array('Ravenna','Comacchio','Yes','Yes'),
	array('Ravenna','Bologna','No','Yes'),
	array('Ravenna','Forli','No','Yes'),
	array('Ravenna','Castel del Rio','No','Yes'),
	array('Ravenna','Rimini','Yes','Yes'),
	array('Ravenna','Litorale Adriatico','Yes','No'),
	array('Forli','Ravenna','No','Yes'),
	array('Forli','Castel del Rio','No','Yes'),
	array('Forli','Arezzo','No','Yes'),
	array('Forli','Urbino','No','Yes'),
	array('Forli','Rimini','No','Yes'),
	array('Castel del Rio','Bologna','No','Yes'),
	array('Castel del Rio','Ravenna','No','Yes'),
	array('Castel del Rio','Forli','No','Yes'),
	array('Castel del Rio','Prato','No','Yes'),
	array('Castel del Rio','Firenze','No','Yes'),
	array('Prato','Castel del Rio','No','Yes'),
	array('Prato','Lucca','No','Yes'),
	array('Prato','Pisa','No','Yes'),
	array('Prato','Firenze','No','Yes'),
	array('Lucca','Sarzana','No','Yes'),
	array('Lucca','Prato','No','Yes'),
	array('Lucca','Pisa','No','Yes'),
	array('Pisa','Sarzana','Yes','Yes'),
	array('Pisa','Prato','No','Yes'),
	array('Pisa','Lucca','No','Yes'),
	array('Pisa','Livorno','Yes','Yes'),
	array('Pisa','Eastern Ligurian Sea','Yes','No'),
	array('Pisa','Bacino del Giglio','Yes','No'),
	array('Livorno','Pisa','Yes','Yes'),
	array('Livorno','Firenze','No','Yes'),
	array('Livorno','Piombino','Yes','Yes'),
	array('Livorno','Bacino del Giglio','Yes','No'),
	array('Firenze','Castel del Rio','No','Yes'),
	array('Firenze','Prato','No','Yes'),
	array('Firenze','Livorno','No','Yes'),
	array('Firenze','Arezzo','No','Yes'),
	array('Firenze','Piombino','No','Yes'),
	array('Arezzo','Forli','No','Yes'),
	array('Arezzo','Firenze','No','Yes'),
	array('Arezzo','Chiusi','No','Yes'),
	array('Arezzo','Siena','No','Yes'),
	array('Urbino','Forli','No','Yes'),
	array('Urbino','Rimini','No','Yes'),
	array('Urbino','Fabriano','No','Yes'),
	array('Urbino','Chiusi','No','Yes'),
	array('Rimini','Ravenna','Yes','Yes'),
	array('Rimini','Forli','No','Yes'),
	array('Rimini','Urbino','No','Yes'),
	array('Rimini','Fabriano','No','Yes'),
	array('Rimini','Ancona','Yes','Yes'),
	array('Rimini','Litorale Adriatico','Yes','No'),
	array('Fabriano','Urbino','No','Yes'),
	array('Fabriano','Rimini','No','Yes'),
	array('Fabriano','Chiusi','No','Yes'),
	array('Fabriano','Ancona','No','Yes'),
	array('Chiusi','Arezzo','No','Yes'),
	array('Chiusi','Urbino','No','Yes'),
	array('Chiusi','Fabriano','No','Yes'),
	array('Chiusi','Siena','No','Yes'),
	array('Chiusi','Viterbo','No','Yes'),
	array('Chiusi','Spoleto','No','Yes'),
	array('Chiusi','Perugia','No','Yes'),
	array('Siena','Arezzo','No','Yes'),
	array('Siena','Chiusi','No','Yes'),
	array('Siena','Piombino','No','Yes'),
	array('Siena','Grosseto','No','Yes'),
	array('Siena','Viterbo','No','Yes'),
	array('Piombino','Livorno','Yes','Yes'),
	array('Piombino','Firenze','No','Yes'),
	array('Piombino','Siena','No','Yes'),
	array('Piombino','Grosseto','Yes','Yes'),
	array('Piombino','Bacino del Giglio','Yes','No'),
	array('Grosseto','Siena','No','Yes'),
	array('Grosseto','Piombino','Yes','Yes'),
	array('Grosseto','Viterbo','Yes','Yes'),
	array('Grosseto','Bacino del Giglio','Yes','No'),
	array('Viterbo','Chiusi','No','Yes'),
	array('Viterbo','Siena','No','Yes'),
	array('Viterbo','Grosseto','Yes','Yes'),
	array('Viterbo','Spoleto','No','Yes'),
	array('Viterbo','ROMA','Yes','Yes'),
	array('Viterbo','Bacino del Giglio','Yes','No'),
	array('Spoleto','Chiusi','No','Yes'),
	array('Spoleto','Viterbo','No','Yes'),
	array('Spoleto','Perugia','No','Yes'),
	array('Spoleto','L\\\'Aquila','No','Yes'),
	array('Spoleto','Ancona','No','Yes'),
	array('Spoleto','Sulmona','No','Yes'),
	array('Spoleto','ROMA','No','Yes'),
	array('Perugia','Chiusi','No','Yes'),
	array('Perugia','Spoleto','No','Yes'),
	array('L\\\'Aquila','Spoleto','No','Yes'),
	array('L\\\'Aquila','Sulmona','No','Yes'),
	array('Ancona','Rimini','Yes','Yes'),
	array('Ancona','Fabriano','No','Yes'),
	array('Ancona','Spoleto','No','Yes'),
	array('Ancona','Pescara','Yes','Yes'),
	array('Ancona','Litorale Adriatico','Yes','No'),
	array('Ancona','Terrazzo delle Tremiti','Yes','No'),
	array('Pescara','Ancona','Yes','Yes'),
	array('Pescara','Benevento','No','Yes'),
	array('Pescara','Foggia','No','Yes'),
	array('Pescara','Foggia (West Coast)','Yes','No'),
	array('Pescara','Terrazzo delle Tremiti','Yes','No'),
	array('Sulmona','Spoleto','No','Yes'),
	array('Sulmona','L\\\'Aquila','No','Yes'),
	array('Sulmona','ROMA','No','Yes'),
	array('Sulmona','Frosinone','No','Yes'),
	array('Sulmona','Napoli','No','Yes'),
	array('Sulmona','Potenza','No','Yes'),
	array('Sulmona','Benevento','No','Yes'),
	array('ROMA','Viterbo','Yes','Yes'),
	array('ROMA','Spoleto','No','Yes'),
	array('ROMA','Sulmona','No','Yes'),
	array('ROMA','Ostia','Yes','Yes'),
	array('ROMA','Frosinone','No','Yes'),
	array('ROMA','Bacino del Giglio','Yes','No'),
	array('Ostia','ROMA','Yes','Yes'),
	array('Ostia','Frosinone','Yes','Yes'),
	array('Ostia','Eastern Thyrrenean Sea','Yes','No'),
	array('Ostia','Bacino del Giglio','Yes','No'),
	array('Frosinone','Sulmona','No','Yes'),
	array('Frosinone','ROMA','No','Yes'),
	array('Frosinone','Ostia','Yes','Yes'),
	array('Frosinone','Napoli','Yes','Yes'),
	array('Frosinone','Eastern Thyrrenean Sea','Yes','No'),
	array('Napoli','Sulmona','No','Yes'),
	array('Napoli','Frosinone','Yes','Yes'),
	array('Napoli','Amalfi','Yes','Yes'),
	array('Napoli','Potenza','No','Yes'),
	array('Napoli','Eastern Thyrrenean Sea','Yes','No'),
	array('Amalfi','Napoli','Yes','Yes'),
	array('Amalfi','Potenza','No','Yes'),
	array('Amalfi','Catanzaro','No','Yes'),
	array('Amalfi','Catanzaro (West Coast)','Yes','No'),
	array('Amalfi','Coast of Amalfi','Yes','No'),
	array('Amalfi','Eastern Thyrrenean Sea','Yes','No'),
	array('Potenza','Sulmona','No','Yes'),
	array('Potenza','Napoli','No','Yes'),
	array('Potenza','Amalfi','No','Yes'),
	array('Potenza','Benevento','No','Yes'),
	array('Potenza','Foggia','No','Yes'),
	array('Potenza','Catanzaro','No','Yes'),
	array('Benevento','Pescara','No','Yes'),
	array('Benevento','Sulmona','No','Yes'),
	array('Benevento','Potenza','No','Yes'),
	array('Benevento','Foggia','No','Yes'),
	array('Foggia','Pescara','No','Yes'),
	array('Foggia','Potenza','No','Yes'),
	array('Foggia','Benevento','No','Yes'),
	array('Foggia','Bari','No','Yes'),
	array('Foggia','Brindisi','No','Yes'),
	array('Foggia','Taranto','No','Yes'),
	array('Foggia','Catanzaro','No','Yes'),
	array('Foggia (West Coast)','Pescara','Yes','No'),
	array('Foggia (West Coast)','Bari','Yes','No'),
	array('Foggia (West Coast)','Terrazzo delle Tremiti','Yes','No'),
	array('Foggia (East Coast)','Bari','Yes','No'),
	array('Foggia (East Coast)','Brindisi','Yes','No'),
	array('Foggia (East Coast)','Coast of Bari','Yes','No'),
	array('Bari','Foggia','No','Yes'),
	array('Bari','Foggia (West Coast)','Yes','No'),
	array('Bari','Foggia (East Coast)','Yes','No'),
	array('Bari','Terrazzo delle Tremiti','Yes','No'),
	array('Bari','Coast of Bari','Yes','No'),
	array('Brindisi','Foggia','No','Yes'),
	array('Brindisi','Foggia (East Coast)','Yes','No'),
	array('Brindisi','Taranto','Yes','Yes'),
	array('Brindisi','Coast of Bari','Yes','No'),
	array('Brindisi','Channel of Otranto','Yes','No'),
	array('Taranto','Foggia','No','Yes'),
	array('Taranto','Brindisi','Yes','Yes'),
	array('Taranto','Catanzaro','No','Yes'),
	array('Taranto','Catanzaro (East Coast)','Yes','No'),
	array('Taranto','Channel of Otranto','Yes','No'),
	array('Taranto','Gulf of Taranto','Yes','No'),
	array('Catanzaro','Amalfi','No','Yes'),
	array('Catanzaro','Potenza','No','Yes'),
	array('Catanzaro','Foggia','No','Yes'),
	array('Catanzaro','Taranto','No','Yes'),
	array('Catanzaro','Reggio Calabria','No','Yes'),
	array('Catanzaro (East Coast)','Taranto','Yes','No'),
	array('Catanzaro (East Coast)','Reggio Calabria','Yes','No'),
	array('Catanzaro (East Coast)','Gulf of Taranto','Yes','No'),
	array('Catanzaro (East Coast)','Inner Ionian Sea','Yes','No'),
	array('Catanzaro (West Coast)','Amalfi','Yes','No'),
	array('Catanzaro (West Coast)','Reggio Calabria','Yes','No'),
	array('Catanzaro (West Coast)','Coast of Amalfi','Yes','No'),
	array('Reggio Calabria','Catanzaro','No','Yes'),
	array('Reggio Calabria','Catanzaro (East Coast)','Yes','No'),
	array('Reggio Calabria','Catanzaro (West Coast)','Yes','No'),
	array('Reggio Calabria','Inner Ionian Sea','Yes','No'),
	array('Reggio Calabria','Strait of Messina','Yes','No'),
	array('Reggio Calabria','Terrazzo delle Lipari','Yes','No'),
	array('Reggio Calabria','Coast of Amalfi','Yes','No'),
	array('Messina','Catania','Yes','Yes'),
	array('Messina','Caltanissetta','No','Yes'),
	array('Messina','Palermo','Yes','Yes'),
	array('Messina','Bacino Avventura','Yes','No'),
	array('Messina','Strait of Messina','Yes','No'),
	array('Messina','Terrazzo delle Lipari','Yes','No'),
	array('Catania','Messina','Yes','Yes'),
	array('Catania','Siracusa','Yes','Yes'),
	array('Catania','Agrigento','No','Yes'),
	array('Catania','Caltanissetta','No','Yes'),
	array('Catania','Inner Ionian Sea','Yes','No'),
	array('Catania','Strait of Messina','Yes','No'),
	array('Siracusa','Catania','Yes','Yes'),
	array('Siracusa','Agrigento','Yes','Yes'),
	array('Siracusa','Inner Ionian Sea','Yes','No'),
	array('Siracusa','Channel of Sicilia','Yes','No'),
	array('Agrigento','Catania','No','Yes'),
	array('Agrigento','Siracusa','Yes','Yes'),
	array('Agrigento','Caltanissetta','No','Yes'),
	array('Agrigento','Palermo','Yes','Yes'),
	array('Agrigento','Channel of Sicilia','Yes','No'),
	array('Caltanissetta','Messina','No','Yes'),
	array('Caltanissetta','Catania','No','Yes'),
	array('Caltanissetta','Agrigento','No','Yes'),
	array('Caltanissetta','Palermo','No','Yes'),
	array('Palermo','Messina','Yes','Yes'),
	array('Palermo','Agrigento','Yes','Yes'),
	array('Palermo','Caltanissetta','No','Yes'),
	array('Palermo','Channel of Sicilia','Yes','No'),
	array('Palermo','Bacino Avventura','Yes','No'),
	array('Pantelleria','Channel of Sicilia','Yes','No'),
	array('Pantelleria','Fossa di Pantelleria','Yes','No'),
	array('Pantelleria','Western Mediterranean Sea','Yes','No'),
	array('Pantelleria','Bacino Avventura','Yes','No'),
	array('Malta','Eastern Mediterranean Sea','Yes','No'),
	array('Malta','Channel of Sicilia','Yes','No'),
	array('Malta','Fossa di Pantelleria','Yes','No'),
	array('Cagliari','Oristano','No','Yes'),
	array('Cagliari','Oristano (East Coast)','Yes','No'),
	array('Cagliari','Oristano (West Coast)','Yes','No'),
	array('Cagliari','Western Thyrrenean Sea','Yes','No'),
	array('Cagliari','Southern Sardinian Sea','Yes','No'),
	array('Oristano','Cagliari','No','Yes'),
	array('Oristano','Sassari','No','Yes'),
	array('Oristano (East Coast)','Cagliari','Yes','No'),
	array('Oristano (East Coast)','Sassari','Yes','No'),
	array('Oristano (East Coast)','Western Thyrrenean Sea','Yes','No'),
	array('Oristano (East Coast)','Channel of Corsica','Yes','No'),
	array('Oristano (West Coast)','Cagliari','Yes','No'),
	array('Oristano (West Coast)','Sassari','Yes','No'),
	array('Oristano (West Coast)','Southern Sardinian Sea','Yes','No'),
	array('Oristano (West Coast)','Northern Sardinian Sea','Yes','No'),
	array('Sassari','Oristano','No','Yes'),
	array('Sassari','Oristano (East Coast)','Yes','No'),
	array('Sassari','Oristano (West Coast)','Yes','No'),
	array('Sassari','Northern Sardinian Sea','Yes','No'),
	array('Sassari','Channel of Corsica','Yes','No'),
	array('Ajaccio','Aleria','No','Yes'),
	array('Ajaccio','Aleria (East Coast)','Yes','No'),
	array('Ajaccio','Aleria (West Coast)','Yes','No'),
	array('Ajaccio','Northern Sardinian Sea','Yes','No'),
	array('Ajaccio','Channel of Corsica','Yes','No'),
	array('Aleria','Ajaccio','No','Yes'),
	array('Aleria','Bastia','No','Yes'),
	array('Aleria (East Coast)','Ajaccio','Yes','No'),
	array('Aleria (East Coast)','Bastia','Yes','No'),
	array('Aleria (East Coast)','Channel of Corsica','Yes','No'),
	array('Aleria (West Coast)','Ajaccio','Yes','No'),
	array('Aleria (West Coast)','Bastia','Yes','No'),
	array('Aleria (West Coast)','Northern Sardinian Sea','Yes','No'),
	array('Aleria (West Coast)','Western Ligurian Sea','Yes','No'),
	array('Bastia','Aleria','No','Yes'),
	array('Bastia','Aleria (East Coast)','Yes','No'),
	array('Bastia','Aleria (West Coast)','Yes','No'),
	array('Bastia','Western Ligurian Sea','Yes','No'),
	array('Bastia','Gulf of Genova','Yes','No'),
	array('Bastia','Channel of Corsica','Yes','No'),
	array('Elba','Eastern Ligurian Sea','Yes','No'),
	array('Elba','Channel of Corsica','Yes','No'),
	array('Elba','Bacino del Giglio','Yes','No'),
	array('Africa','Fossa di Pantelleria','Yes','No'),
	array('Africa','Western Mediterranean Sea','Yes','No'),
	array('Laguna di Venezia','Aquileia','Yes','No'),
	array('Laguna di Venezia','Trieste','Yes','No'),
	array('Laguna di Venezia','Chioggia','Yes','No'),
	array('Laguna di Venezia','Venezia','Yes','No'),
	array('Laguna di Venezia','Adria','Yes','No'),
	array('Laguna di Venezia','Comacchio','Yes','No'),
	array('Laguna di Venezia','Litorale Adriatico','Yes','No'),
	array('Laguna di Venezia','Central Adriatic Sea','Yes','No'),
	array('Laguna di Venezia','Dalmatian Sea','Yes','No'),
	array('Litorale Adriatico','Comacchio','Yes','No'),
	array('Litorale Adriatico','Ravenna','Yes','No'),
	array('Litorale Adriatico','Rimini','Yes','No'),
	array('Litorale Adriatico','Ancona','Yes','No'),
	array('Litorale Adriatico','Laguna di Venezia','Yes','No'),
	array('Litorale Adriatico','Central Adriatic Sea','Yes','No'),
	array('Litorale Adriatico','Terrazzo delle Tremiti','Yes','No'),
	array('Central Adriatic Sea','Laguna di Venezia','Yes','No'),
	array('Central Adriatic Sea','Litorale Adriatico','Yes','No'),
	array('Central Adriatic Sea','Dalmatian Sea','Yes','No'),
	array('Central Adriatic Sea','Arcipelago di Spalato','Yes','No'),
	array('Central Adriatic Sea','Terrazzo delle Tremiti','Yes','No'),
	array('Dalmatian Sea','Trieste','Yes','No'),
	array('Dalmatian Sea','Pola','Yes','No'),
	array('Dalmatian Sea','Fiume','Yes','No'),
	array('Dalmatian Sea','Zara','Yes','No'),
	array('Dalmatian Sea','Laguna di Venezia','Yes','No'),
	array('Dalmatian Sea','Central Adriatic Sea','Yes','No'),
	array('Dalmatian Sea','Arcipelago di Spalato','Yes','No'),
	array('Arcipelago di Spalato','Zara','Yes','No'),
	array('Arcipelago di Spalato','Spalato','Yes','No'),
	array('Arcipelago di Spalato','Ragusa','Yes','No'),
	array('Arcipelago di Spalato','Central Adriatic Sea','Yes','No'),
	array('Arcipelago di Spalato','Dalmatian Sea','Yes','No'),
	array('Arcipelago di Spalato','Terrazzo delle Tremiti','Yes','No'),
	array('Arcipelago di Spalato','Coast of Bari','Yes','No'),
	array('Terrazzo delle Tremiti','Ancona','Yes','No'),
	array('Terrazzo delle Tremiti','Pescara','Yes','No'),
	array('Terrazzo delle Tremiti','Foggia (West Coast)','Yes','No'),
	array('Terrazzo delle Tremiti','Bari','Yes','No'),
	array('Terrazzo delle Tremiti','Litorale Adriatico','Yes','No'),
	array('Terrazzo delle Tremiti','Central Adriatic Sea','Yes','No'),
	array('Terrazzo delle Tremiti','Arcipelago di Spalato','Yes','No'),
	array('Terrazzo delle Tremiti','Coast of Bari','Yes','No'),
	array('Coast of Bari','Foggia (East Coast)','Yes','No'),
	array('Coast of Bari','Bari','Yes','No'),
	array('Coast of Bari','Brindisi','Yes','No'),
	array('Coast of Bari','Arcipelago di Spalato','Yes','No'),
	array('Coast of Bari','Terrazzo delle Tremiti','Yes','No'),
	array('Coast of Bari','Channel of Otranto','Yes','No'),
	array('Channel of Otranto','Brindisi','Yes','No'),
	array('Channel of Otranto','Taranto','Yes','No'),
	array('Channel of Otranto','Coast of Bari','Yes','No'),
	array('Channel of Otranto','Gulf of Taranto','Yes','No'),
	array('Channel of Otranto','East Gateway','Yes','No'),
	array('Gulf of Taranto','Taranto','Yes','No'),
	array('Gulf of Taranto','Catanzaro (East Coast)','Yes','No'),
	array('Gulf of Taranto','Channel of Otranto','Yes','No'),
	array('Gulf of Taranto','East Gateway','Yes','No'),
	array('Gulf of Taranto','Outer Ionian Sea','Yes','No'),
	array('Gulf of Taranto','Inner Ionian Sea','Yes','No'),
	array('East Gateway','Channel of Otranto','Yes','No'),
	array('East Gateway','Gulf of Taranto','Yes','No'),
	array('East Gateway','Outer Ionian Sea','Yes','No'),
	array('Outer Ionian Sea','Gulf of Taranto','Yes','No'),
	array('Outer Ionian Sea','East Gateway','Yes','No'),
	array('Outer Ionian Sea','Inner Ionian Sea','Yes','No'),
	array('Outer Ionian Sea','Eastern Mediterranean Sea','Yes','No'),
	array('Inner Ionian Sea','Catanzaro (East Coast)','Yes','No'),
	array('Inner Ionian Sea','Reggio Calabria','Yes','No'),
	array('Inner Ionian Sea','Catania','Yes','No'),
	array('Inner Ionian Sea','Siracusa','Yes','No'),
	array('Inner Ionian Sea','Gulf of Taranto','Yes','No'),
	array('Inner Ionian Sea','Outer Ionian Sea','Yes','No'),
	array('Inner Ionian Sea','Eastern Mediterranean Sea','Yes','No'),
	array('Inner Ionian Sea','Channel of Sicilia','Yes','No'),
	array('Inner Ionian Sea','Strait of Messina','Yes','No'),
	array('Eastern Mediterranean Sea','Malta','Yes','No'),
	array('Eastern Mediterranean Sea','Outer Ionian Sea','Yes','No'),
	array('Eastern Mediterranean Sea','Inner Ionian Sea','Yes','No'),
	array('Eastern Mediterranean Sea','Channel of Sicilia','Yes','No'),
	array('Channel of Sicilia','Siracusa','Yes','No'),
	array('Channel of Sicilia','Agrigento','Yes','No'),
	array('Channel of Sicilia','Palermo','Yes','No'),
	array('Channel of Sicilia','Pantelleria','Yes','No'),
	array('Channel of Sicilia','Malta','Yes','No'),
	array('Channel of Sicilia','Inner Ionian Sea','Yes','No'),
	array('Channel of Sicilia','Eastern Mediterranean Sea','Yes','No'),
	array('Channel of Sicilia','Fossa di Pantelleria','Yes','No'),
	array('Channel of Sicilia','Bacino Avventura','Yes','No'),
	array('Fossa di Pantelleria','Pantelleria','Yes','No'),
	array('Fossa di Pantelleria','Malta','Yes','No'),
	array('Fossa di Pantelleria','Africa','Yes','No'),
	array('Fossa di Pantelleria','Channel of Sicilia','Yes','No'),
	array('Fossa di Pantelleria','Western Mediterranean Sea','Yes','No'),
	array('Western Mediterranean Sea','Pantelleria','Yes','No'),
	array('Western Mediterranean Sea','Africa','Yes','No'),
	array('Western Mediterranean Sea','Fossa di Pantelleria','Yes','No'),
	array('Western Mediterranean Sea','Bacino Avventura','Yes','No'),
	array('Western Mediterranean Sea','Western Thyrrenean Sea','Yes','No'),
	array('Western Mediterranean Sea','Southern Sardinian Sea','Yes','No'),
	array('Bacino Avventura','Messina','Yes','No'),
	array('Bacino Avventura','Palermo','Yes','No'),
	array('Bacino Avventura','Pantelleria','Yes','No'),
	array('Bacino Avventura','Channel of Sicilia','Yes','No'),
	array('Bacino Avventura','Western Mediterranean Sea','Yes','No'),
	array('Bacino Avventura','Terrazzo delle Lipari','Yes','No'),
	array('Bacino Avventura','Eastern Thyrrenean Sea','Yes','No'),
	array('Bacino Avventura','Western Thyrrenean Sea','Yes','No'),
	array('Strait of Messina','Reggio Calabria','Yes','No'),
	array('Strait of Messina','Messina','Yes','No'),
	array('Strait of Messina','Catania','Yes','No'),
	array('Strait of Messina','Inner Ionian Sea','Yes','No'),
	array('Strait of Messina','Terrazzo delle Lipari','Yes','No'),
	array('Terrazzo delle Lipari','Reggio Calabria','Yes','No'),
	array('Terrazzo delle Lipari','Messina','Yes','No'),
	array('Terrazzo delle Lipari','Bacino Avventura','Yes','No'),
	array('Terrazzo delle Lipari','Strait of Messina','Yes','No'),
	array('Terrazzo delle Lipari','Coast of Amalfi','Yes','No'),
	array('Terrazzo delle Lipari','Eastern Thyrrenean Sea','Yes','No'),
	array('Coast of Amalfi','Amalfi','Yes','No'),
	array('Coast of Amalfi','Catanzaro (West Coast)','Yes','No'),
	array('Coast of Amalfi','Reggio Calabria','Yes','No'),
	array('Coast of Amalfi','Terrazzo delle Lipari','Yes','No'),
	array('Coast of Amalfi','Eastern Thyrrenean Sea','Yes','No'),
	array('Eastern Thyrrenean Sea','Ostia','Yes','No'),
	array('Eastern Thyrrenean Sea','Frosinone','Yes','No'),
	array('Eastern Thyrrenean Sea','Napoli','Yes','No'),
	array('Eastern Thyrrenean Sea','Amalfi','Yes','No'),
	array('Eastern Thyrrenean Sea','Bacino Avventura','Yes','No'),
	array('Eastern Thyrrenean Sea','Terrazzo delle Lipari','Yes','No'),
	array('Eastern Thyrrenean Sea','Coast of Amalfi','Yes','No'),
	array('Eastern Thyrrenean Sea','Western Thyrrenean Sea','Yes','No'),
	array('Eastern Thyrrenean Sea','Bacino del Giglio','Yes','No'),
	array('Western Thyrrenean Sea','Cagliari','Yes','No'),
	array('Western Thyrrenean Sea','Oristano (East Coast)','Yes','No'),
	array('Western Thyrrenean Sea','Western Mediterranean Sea','Yes','No'),
	array('Western Thyrrenean Sea','Bacino Avventura','Yes','No'),
	array('Western Thyrrenean Sea','Eastern Thyrrenean Sea','Yes','No'),
	array('Western Thyrrenean Sea','Southern Sardinian Sea','Yes','No'),
	array('Western Thyrrenean Sea','Channel of Corsica','Yes','No'),
	array('Western Thyrrenean Sea','Bacino del Giglio','Yes','No'),
	array('Southern Sardinian Sea','Cagliari','Yes','No'),
	array('Southern Sardinian Sea','Oristano (West Coast)','Yes','No'),
	array('Southern Sardinian Sea','Western Mediterranean Sea','Yes','No'),
	array('Southern Sardinian Sea','Western Thyrrenean Sea','Yes','No'),
	array('Southern Sardinian Sea','Northern Sardinian Sea','Yes','No'),
	array('Northern Sardinian Sea','Oristano (West Coast)','Yes','No'),
	array('Northern Sardinian Sea','Sassari','Yes','No'),
	array('Northern Sardinian Sea','Ajaccio','Yes','No'),
	array('Northern Sardinian Sea','Aleria (West Coast)','Yes','No'),
	array('Northern Sardinian Sea','Southern Sardinian Sea','Yes','No'),
	array('Northern Sardinian Sea','Western Ligurian Sea','Yes','No'),
	array('Northern Sardinian Sea','Channel of Corsica','Yes','No'),
	array('Western Ligurian Sea','Nizza','Yes','No'),
	array('Western Ligurian Sea','Ventimiglia','Yes','No'),
	array('Western Ligurian Sea','Aleria (West Coast)','Yes','No'),
	array('Western Ligurian Sea','Bastia','Yes','No'),
	array('Western Ligurian Sea','Northern Sardinian Sea','Yes','No'),
	array('Western Ligurian Sea','Gulf of Genova','Yes','No'),
	array('Gulf of Genova','Ventimiglia','Yes','No'),
	array('Gulf of Genova','Savona','Yes','No'),
	array('Gulf of Genova','Genova','Yes','No'),
	array('Gulf of Genova','La Spezia','Yes','No'),
	array('Gulf of Genova','Bastia','Yes','No'),
	array('Gulf of Genova','Western Ligurian Sea','Yes','No'),
	array('Gulf of Genova','Eastern Ligurian Sea','Yes','No'),
	array('Gulf of Genova','Channel of Corsica','Yes','No'),
	array('Eastern Ligurian Sea','La Spezia','Yes','No'),
	array('Eastern Ligurian Sea','Sarzana','Yes','No'),
	array('Eastern Ligurian Sea','Pisa','Yes','No'),
	array('Eastern Ligurian Sea','Elba','Yes','No'),
	array('Eastern Ligurian Sea','Gulf of Genova','Yes','No'),
	array('Eastern Ligurian Sea','Channel of Corsica','Yes','No'),
	array('Eastern Ligurian Sea','Bacino del Giglio','Yes','No'),
	array('Channel of Corsica','Oristano (East Coast)','Yes','No'),
	array('Channel of Corsica','Sassari','Yes','No'),
	array('Channel of Corsica','Ajaccio','Yes','No'),
	array('Channel of Corsica','Aleria (East Coast)','Yes','No'),
	array('Channel of Corsica','Bastia','Yes','No'),
	array('Channel of Corsica','Elba','Yes','No'),
	array('Channel of Corsica','Western Thyrrenean Sea','Yes','No'),
	array('Channel of Corsica','Northern Sardinian Sea','Yes','No'),
	array('Channel of Corsica','Gulf of Genova','Yes','No'),
	array('Channel of Corsica','Eastern Ligurian Sea','Yes','No'),
	array('Channel of Corsica','Bacino del Giglio','Yes','No'),
	array('Bacino del Giglio','Pisa','Yes','No'),
	array('Bacino del Giglio','Livorno','Yes','No'),
	array('Bacino del Giglio','Piombino','Yes','No'),
	array('Bacino del Giglio','Grosseto','Yes','No'),
	array('Bacino del Giglio','Viterbo','Yes','No'),
	array('Bacino del Giglio','ROMA','Yes','No'),
	array('Bacino del Giglio','Ostia','Yes','No'),
	array('Bacino del Giglio','Elba','Yes','No'),
	array('Bacino del Giglio','Eastern Thyrrenean Sea','Yes','No'),
	array('Bacino del Giglio','Western Thyrrenean Sea','Yes','No'),
	array('Bacino del Giglio','Eastern Ligurian Sea','Yes','No'),
	array('Bacino del Giglio','Channel of Corsica','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

// Custom footer not changed by edit tool

// Make 2 "fake" SC's to fool the Unit-DestroyIndex generation
InstallTerritory::$Territories['Annecy']->supply='Yes';
InstallTerritory::$Territories['Eastern Mediterranean Sea']->supply='Yes';

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);

// Remove the fake Home-Supply-Centers created above
$DB->sql_put('UPDATE wD_Territories SET supply="No" WHERE mapID='.$this->mapID.' AND (name="Annecy" OR name="Eastern Mediterranean Sea")');

?>






