ALTER TABLE `wD_Games` ADD `specialCDcount` SMALLINT( 5 ) UNSIGNED NOT NULL DEFAULT '1';
ALTER TABLE `wD_Games` ADD `specialCDturn` SMALLINT( 5 ) UNSIGNED NOT NULL DEFAULT '1';
ALTER TABLE `wD_Backup_Games` ADD `specialCDcount` SMALLINT( 5 ) UNSIGNED NOT NULL DEFAULT '1';
ALTER TABLE `wD_Backup_Games` ADD `specialCDturn` SMALLINT( 5 ) UNSIGNED NOT NULL DEFAULT '1';
