<?php
// This file will install the map data for the Alacavre variant

require_once("variants/install.php");
InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Albert', 'Coast', 'No', 299, 336, 352, 126, 'Oz'),
	array('Southern Oz', 'Coast', 'Yes', 346, 347, 334, 97, 'Oz'),
	array('Old North Wales', 'Coast', 'Yes', 315, 413, 365, 109, 'Oz'),
	array('Western Oz', 'Coast', 'No', 355, 440, 319, 85, 'Oz'),
	array('Kingsland', 'Coast', 'No', 294, 473, 373, 91, 'Oz'),
	array('Northern Terror', 'Coast', 'Yes', 361, 481, 349, 71, 'Oz'),
	array('The point', 'Coast', 'Yes', 91, 718, 506, 195, 'Neutral'),
	array('Isthmus', 'Coast', 'Yes', 177, 794, 511, 250, 'Neutral'),
	array('North Walang', 'Coast', 'No', 181, 949, 412, 165, 'Neutral'),
	array('South Walang', 'Coast', 'Yes', 434, 961, 410, 191, 'Neutral'),
	array('Arenos Desert', 'Coast', 'No', 441, 694, 508, 338, 'Neutral'),
	array('Lik', 'Coast', 'Yes', 570, 864, 422, 297, 'Quiom'),
	array('Quok', 'Coast', 'Yes', 522, 808, 422, 318, 'Quiom'),
	array('Rint', 'Coast', 'No', 485, 767, 417, 348, 'Quiom'),
	array('Kreiasth', 'Coast', 'Yes', 501, 717, 369, 351, 'Quiom'),
	array('Mealak', 'Coast', 'No', 591, 825, 397, 304, 'Quiom'),
	array('Bdail', 'Coast', 'Yes', 678, 863, 341, 290, 'Neutral'),
	array('Hixalop', 'Coast', 'No', 640, 827, 324, 310, 'Neutral'),
	array('Artok', 'Land', 'Yes', 667, 776, 310, 291, 'Neutral'),
	array('Acabat', 'Coast', 'Yes', 740, 776, 316, 262, 'Neutral'),
	array('Lanbuo', 'Coast', 'Yes', 717, 724, 241, 265, 'Neutral'),
	array('Metpri', 'Coast', 'Yes', 821, 852, 332, 236, 'Maroe'),
	array('Orkali', 'Coast', 'Yes', 899, 895, 337, 214, 'Maroe'),
	array('Lireo', 'Coast', 'Yes', 986, 816, 297, 230, 'Maroe'),
	array('Porinta', 'Coast', 'No', 1045, 938, 341, 196, 'Maroe'),
	array('Alternative States United', 'Coast', 'No', 1073, 785, 279, 229, 'Neutral'),
	array('Ayetok', 'Coast', 'Yes', 923, 595, 253, 230, 'Shinto'),
	array('Riah', 'Land', 'No', 779, 579, 208, 231, 'Shinto'),
	array('Hawyo', 'Land', 'Yes', 683, 547, 164, 200, 'Shinto'),
	array('Eot', 'Coast', 'No', 719, 430, 181, 174, 'Shinto'),
	array('Heashoult', 'Land', 'Yes', 830, 465, 217, 202, 'Shinto'),
	array('Knie', 'Coast', 'Yes', 837, 309, 225, 162, 'Shinto'),
	array('mraerof', 'Land', 'No', 718, 610, 164, 225, 'Shinto'),
	array('Au', 'Coast', 'No', 702, 263, 208, 134, 'Neutral'),
	array('Igma', 'Coast', 'Yes', 587, 274, 189, 121, 'Neutral'),
	array('Ota', 'Coast', 'Yes', 518, 270, 233, 122, 'Neutral'),
	array('Appa', 'Coast', 'Yes', 501, 422, 192, 96, 'Neutral'),
	array('Prithski', 'Coast', 'Yes', 485, 516, 156, 75, 'Payashk'),
	array('Vorulov', 'Coast', 'Yes', 551, 477, 124, 108, 'Payashk'),
	array('Kerop', 'Coast', 'No', 621, 481, 135, 144, 'Payashk'),
	array('Montuk', 'Land', 'No', 589, 545, 93, 143, 'Payashk'),
	array('Kelpuct', 'Land', 'Yes', 489, 581, 65, 56, 'Payashk'),
	array('Taorip', 'Land', 'No', 448, 545, 241, 37, 'Neutral'),
	array('Litov', 'Coast', 'Yes', 440, 488, 226, 63, 'Neutral'),
	array('Yria', 'Coast', 'Yes', 410, 551, 324, 35, 'Neutral'),
	array('Ghion', 'Coast', 'No', 359, 559, 415, 60, 'Namaq'),
	array('Lehas', 'Coast', 'Yes', 291, 583, 485, 120, 'Namaq'),
	array('Olbucfor', 'Land', 'Yes', 336, 620, 521, 107, 'Namaq'),
	array('Mianey', 'Coast', 'Yes', 390, 689, 563, 291, 'Namaq'),
	array('Cope Dive', 'Coast', 'No', 301, 679, 569, 224, 'Namaq'),
	array('Furbina Kosa', 'Land', 'No', 404, 626, 537, 39, 'Neutral'),
	array('Square Patch of Water', 'Sea', 'No', 836, 33, 251, 138, 'Neutral'),
	array('Tamsin Sea', 'Sea', 'No', 452, 109, 318, 133, 'Neutral'),
	array('Nota Ocean', 'Sea', 'No', 414, 378, 266, 89, 'Neutral'),
	array('Cove', 'Sea', 'No', 516, 363, 214, 96, 'Neutral'),
	array('Passage', 'Sea', 'No', 460, 447, 189, 73, 'Neutral'),
	array('The Lagoon', 'Sea', 'No', 621, 434, 156, 126, 'Neutral'),
	array('Old Creek', 'Sea', 'No', 653, 348, 188, 158, 'Neutral'),
	array('The Wet', 'Sea', 'No', 153, 237, 373, 141, 'Neutral'),
	array('Triak', 'Sea', 'No', 218, 478, 399, 123, 'Neutral'),
	array('Ghion Sea', 'Sea', 'No', 273, 527, 396, 92, 'Neutral'),
	array('Big Sea', 'Sea', 'No', 106, 581, 474, 170, 'Neutral'),
	array('New Stretch', 'Sea', 'No', 327, 858, 463, 263, 'Neutral'),
	array('Buo Bay', 'Sea', 'No', 366, 774, 489, 314, 'Neutral'),
	array('Forth of toria', 'Sea', 'No', 488, 849, 435, 278, 'Neutral'),
	array('Fonty Sea', 'Sea', 'No', 602, 947, 397, 246, 'Neutral'),
	array('New Bay', 'Sea', 'No', 564, 773, 363, 308, 'Neutral'),
	array('Orina Sea', 'Sea', 'No', 740, 863, 356, 245, 'Neutral'),
	array('Trago Sea', 'Sea', 'No', 860, 972, 369, 208, 'Neutral'),
	array('Lake', 'Sea', 'No', 905, 743, 281, 257, 'Neutral'),
	array('Seca Desert', 'Land', 'No', 538, 641, 83, 339, 'Neutral'),
	array('Thuimp', 'Land', 'No', 562, 590, 76, 194, 'Ithsomn'),
	array('Vaarle', 'Land', 'Yes', 602, 627, 121, 271, 'Ithsomn'),
	array('Nuit', 'Coast', 'Yes', 593, 730, 253, 348, 'Ithsomn'),
	array('Uark', 'Land', 'Yes', 681, 668, 211, 280, 'Ithsomn'),
	array('Isthmus (East Coast)', 'Coast', 'No', 193, 685, 531, 242, 'Neutral'),
	array('Isthmus (West Coast)', 'Coast', 'No', 191, 832, 499, 276, 'Neutral'),
	array('Knie (East Coast)', 'Coast', 'No', 828, 111, 245, 145, 'Shinto'),
	array('Knie (West Coast)', 'Coast', 'No', 780, 355, 204, 157, 'Shinto'),
	array('Acabat (West Coast)', 'Coast', 'No', 785, 762, 295, 261, 'Neutral'),
	array('Acabat (East Coast)', 'Coast', 'No', 749, 815, 331, 256, 'Neutral')
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $x, $y, $sx, $sy, $country)=$territoryRawRow;
	if( $country=='Neutral' )
		 $countryID=0;
	else
		 $countryID=$this->countryID($country);
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);		

$bordersRawData=array(
	array('Albert','Southern Oz','Yes','Yes'),
	array('Albert','Old North Wales','Yes','Yes'),
	array('Albert','Tamsin Sea','Yes','No'),
	array('Albert','The Wet','Yes','No'),
	array('Southern Oz','Albert','Yes','Yes'),
	array('Southern Oz','Old North Wales','No','Yes'),
	array('Southern Oz','Western Oz','Yes','Yes'),
	array('Southern Oz','Tamsin Sea','Yes','No'),
	array('Southern Oz','Nota Ocean','Yes','No'),
	array('Old North Wales','Albert','Yes','Yes'),
	array('Old North Wales','Southern Oz','No','Yes'),
	array('Old North Wales','Western Oz','No','Yes'),
	array('Old North Wales','Kingsland','Yes','Yes'),
	array('Old North Wales','The Wet','Yes','No'),
	array('Old North Wales','Triak','Yes','No'),
	array('Western Oz','Southern Oz','Yes','Yes'),
	array('Western Oz','Old North Wales','No','Yes'),
	array('Western Oz','Kingsland','No','Yes'),
	array('Western Oz','Northern Terror','Yes','Yes'),
	array('Western Oz','Nota Ocean','Yes','No'),
	array('Kingsland','Old North Wales','Yes','Yes'),
	array('Kingsland','Western Oz','No','Yes'),
	array('Kingsland','Northern Terror','Yes','Yes'),
	array('Kingsland','Triak','Yes','No'),
	array('Kingsland','Ghion Sea','Yes','No'),
	array('Northern Terror','Western Oz','Yes','Yes'),
	array('Northern Terror','Kingsland','Yes','Yes'),
	array('Northern Terror','Nota Ocean','Yes','No'),
	array('Northern Terror','Ghion Sea','Yes','No'),
	array('The point','Isthmus','No','Yes'),
	array('The point','Big Sea','Yes','No'),
	array('The point','Isthmus (East Coast)','Yes','No'),
	array('The point','Isthmus (West Coast)','Yes','No'),
	array('Isthmus','The point','No','Yes'),
	array('Isthmus','Mianey','No','Yes'),
	array('Isthmus','Cope Dive','No','Yes'),
	array('North Walang','South Walang','Yes','Yes'),
	array('North Walang','Big Sea','Yes','No'),
	array('North Walang','New Stretch','Yes','No'),
	array('South Walang','North Walang','Yes','Yes'),
	array('South Walang','New Stretch','Yes','No'),
	array('South Walang','Forth of toria','Yes','No'),
	array('South Walang','Fonty Sea','Yes','No'),
	array('Arenos Desert','Rint','Yes','Yes'),
	array('Arenos Desert','Kreiasth','No','Yes'),
	array('Arenos Desert','Mianey','Yes','Yes'),
	array('Arenos Desert','Buo Bay','Yes','No'),
	array('Arenos Desert','Seca Desert','No','Yes'),
	array('Lik','Quok','Yes','Yes'),
	array('Lik','Mealak','Yes','Yes'),
	array('Lik','Forth of toria','Yes','No'),
	array('Lik','Fonty Sea','Yes','No'),
	array('Quok','Lik','Yes','Yes'),
	array('Quok','Rint','Yes','Yes'),
	array('Quok','Kreiasth','No','Yes'),
	array('Quok','Mealak','No','Yes'),
	array('Quok','Forth of toria','Yes','No'),
	array('Rint','Arenos Desert','Yes','Yes'),
	array('Rint','Quok','Yes','Yes'),
	array('Rint','Kreiasth','No','Yes'),
	array('Rint','Buo Bay','Yes','No'),
	array('Rint','Forth of toria','Yes','No'),
	array('Kreiasth','Arenos Desert','No','Yes'),
	array('Kreiasth','Quok','No','Yes'),
	array('Kreiasth','Rint','No','Yes'),
	array('Kreiasth','Mealak','Yes','Yes'),
	array('Kreiasth','New Bay','Yes','No'),
	array('Kreiasth','Seca Desert','No','Yes'),
	array('Kreiasth','Nuit','Yes','Yes'),
	array('Mealak','Lik','Yes','Yes'),
	array('Mealak','Quok','No','Yes'),
	array('Mealak','Kreiasth','Yes','Yes'),
	array('Mealak','Fonty Sea','Yes','No'),
	array('Mealak','New Bay','Yes','No'),
	array('Bdail','Hixalop','Yes','Yes'),
	array('Bdail','Artok','No','Yes'),
	array('Bdail','Acabat','No','Yes'),
	array('Bdail','Fonty Sea','Yes','No'),
	array('Bdail','Orina Sea','Yes','No'),
	array('Bdail','Acabat (East Coast)','Yes','No'),
	array('Hixalop','Bdail','Yes','Yes'),
	array('Hixalop','Artok','No','Yes'),
	array('Hixalop','Fonty Sea','Yes','No'),
	array('Hixalop','New Bay','Yes','No'),
	array('Hixalop','Nuit','Yes','Yes'),
	array('Artok','Bdail','No','Yes'),
	array('Artok','Hixalop','No','Yes'),
	array('Artok','Acabat','No','Yes'),
	array('Artok','Lanbuo','No','Yes'),
	array('Artok','Nuit','No','Yes'),
	array('Artok','Uark','No','Yes'),
	array('Acabat','Bdail','No','Yes'),
	array('Acabat','Artok','No','Yes'),
	array('Acabat','Lanbuo','No','Yes'),
	array('Acabat','Metpri','No','Yes'),
	array('Lanbuo','Artok','No','Yes'),
	array('Lanbuo','Acabat','No','Yes'),
	array('Lanbuo','Ayetok','Yes','Yes'),
	array('Lanbuo','Riah','No','Yes'),
	array('Lanbuo','mraerof','No','Yes'),
	array('Lanbuo','Lake','Yes','No'),
	array('Lanbuo','Uark','No','Yes'),
	array('Lanbuo','Acabat (West Coast)','Yes','No'),
	array('Metpri','Acabat','No','Yes'),
	array('Metpri','Orkali','Yes','Yes'),
	array('Metpri','Lireo','Yes','Yes'),
	array('Metpri','Orina Sea','Yes','No'),
	array('Metpri','Lake','Yes','No'),
	array('Metpri','Acabat (West Coast)','Yes','No'),
	array('Metpri','Acabat (East Coast)','Yes','No'),
	array('Orkali','Metpri','Yes','Yes'),
	array('Orkali','Lireo','No','Yes'),
	array('Orkali','Porinta','Yes','Yes'),
	array('Orkali','Alternative States United','No','Yes'),
	array('Orkali','Orina Sea','Yes','No'),
	array('Orkali','Trago Sea','Yes','No'),
	array('Lireo','Metpri','Yes','Yes'),
	array('Lireo','Orkali','No','Yes'),
	array('Lireo','Alternative States United','Yes','Yes'),
	array('Lireo','Lake','Yes','No'),
	array('Porinta','Orkali','Yes','Yes'),
	array('Porinta','Alternative States United','No','Yes'),
	array('Porinta','Trago Sea','Yes','No'),
	array('Alternative States United','Orkali','No','Yes'),
	array('Alternative States United','Lireo','Yes','Yes'),
	array('Alternative States United','Porinta','No','Yes'),
	array('Alternative States United','Ayetok','Yes','Yes'),
	array('Alternative States United','Lake','Yes','No'),
	array('Ayetok','Lanbuo','Yes','Yes'),
	array('Ayetok','Alternative States United','Yes','Yes'),
	array('Ayetok','Riah','No','Yes'),
	array('Ayetok','Heashoult','No','Yes'),
	array('Ayetok','Lake','Yes','No'),
	array('Riah','Lanbuo','No','Yes'),
	array('Riah','Ayetok','No','Yes'),
	array('Riah','Hawyo','No','Yes'),
	array('Riah','Heashoult','No','Yes'),
	array('Riah','mraerof','No','Yes'),
	array('Hawyo','Riah','No','Yes'),
	array('Hawyo','Eot','No','Yes'),
	array('Hawyo','Heashoult','No','Yes'),
	array('Hawyo','mraerof','No','Yes'),
	array('Hawyo','Kerop','No','Yes'),
	array('Hawyo','Montuk','No','Yes'),
	array('Eot','Hawyo','No','Yes'),
	array('Eot','Heashoult','No','Yes'),
	array('Eot','Knie','No','Yes'),
	array('Eot','Kerop','Yes','Yes'),
	array('Eot','The Lagoon','Yes','No'),
	array('Eot','Old Creek','Yes','No'),
	array('Eot','Knie (West Coast)','Yes','No'),
	array('Heashoult','Ayetok','No','Yes'),
	array('Heashoult','Riah','No','Yes'),
	array('Heashoult','Hawyo','No','Yes'),
	array('Heashoult','Eot','No','Yes'),
	array('Heashoult','Knie','No','Yes'),
	array('Knie','Eot','No','Yes'),
	array('Knie','Heashoult','No','Yes'),
	array('Knie','Au','No','Yes'),
	array('Knie','Ota','No','Yes'),
	array('mraerof','Lanbuo','No','Yes'),
	array('mraerof','Riah','No','Yes'),
	array('mraerof','Hawyo','No','Yes'),
	array('mraerof','Montuk','No','Yes'),
	array('mraerof','Thuimp','No','Yes'),
	array('mraerof','Vaarle','No','Yes'),
	array('mraerof','Uark','No','Yes'),
	array('Au','Knie','No','Yes'),
	array('Au','Igma','Yes','Yes'),
	array('Au','Ota','No','Yes'),
	array('Au','Old Creek','Yes','No'),
	array('Au','Knie (West Coast)','Yes','No'),
	array('Igma','Au','Yes','Yes'),
	array('Igma','Ota','Yes','Yes'),
	array('Igma','Appa','Yes','Yes'),
	array('Igma','Cove','Yes','No'),
	array('Igma','The Lagoon','Yes','No'),
	array('Igma','Old Creek','Yes','No'),
	array('Ota','Knie','No','Yes'),
	array('Ota','Au','No','Yes'),
	array('Ota','Igma','Yes','Yes'),
	array('Ota','Square Patch of Water','Yes','No'),
	array('Ota','Tamsin Sea','Yes','No'),
	array('Ota','Nota Ocean','Yes','No'),
	array('Ota','Cove','Yes','No'),
	array('Ota','Knie (East Coast)','Yes','No'),
	array('Appa','Igma','Yes','Yes'),
	array('Appa','Prithski','Yes','Yes'),
	array('Appa','Nota Ocean','Yes','No'),
	array('Appa','Cove','Yes','No'),
	array('Appa','Passage','Yes','No'),
	array('Appa','The Lagoon','Yes','No'),
	array('Prithski','Appa','Yes','Yes'),
	array('Prithski','Vorulov','Yes','Yes'),
	array('Prithski','Kelpuct','No','Yes'),
	array('Prithski','Taorip','No','Yes'),
	array('Prithski','Litov','Yes','Yes'),
	array('Prithski','Passage','Yes','No'),
	array('Prithski','The Lagoon','Yes','No'),
	array('Vorulov','Prithski','Yes','Yes'),
	array('Vorulov','Kerop','Yes','Yes'),
	array('Vorulov','Montuk','No','Yes'),
	array('Vorulov','Kelpuct','No','Yes'),
	array('Vorulov','The Lagoon','Yes','No'),
	array('Kerop','Hawyo','No','Yes'),
	array('Kerop','Eot','Yes','Yes'),
	array('Kerop','Vorulov','Yes','Yes'),
	array('Kerop','Montuk','No','Yes'),
	array('Kerop','The Lagoon','Yes','No'),
	array('Montuk','Hawyo','No','Yes'),
	array('Montuk','mraerof','No','Yes'),
	array('Montuk','Vorulov','No','Yes'),
	array('Montuk','Kerop','No','Yes'),
	array('Montuk','Kelpuct','No','Yes'),
	array('Montuk','Thuimp','No','Yes'),
	array('Kelpuct','Prithski','No','Yes'),
	array('Kelpuct','Vorulov','No','Yes'),
	array('Kelpuct','Montuk','No','Yes'),
	array('Kelpuct','Taorip','No','Yes'),
	array('Kelpuct','Furbina Kosa','No','Yes'),
	array('Kelpuct','Seca Desert','No','Yes'),
	array('Kelpuct','Thuimp','No','Yes'),
	array('Taorip','Prithski','No','Yes'),
	array('Taorip','Kelpuct','No','Yes'),
	array('Taorip','Litov','No','Yes'),
	array('Taorip','Yria','No','Yes'),
	array('Taorip','Furbina Kosa','No','Yes'),
	array('Litov','Prithski','Yes','Yes'),
	array('Litov','Taorip','No','Yes'),
	array('Litov','Yria','Yes','Yes'),
	array('Litov','Nota Ocean','Yes','No'),
	array('Litov','Passage','Yes','No'),
	array('Yria','Taorip','No','Yes'),
	array('Yria','Litov','Yes','Yes'),
	array('Yria','Ghion','Yes','Yes'),
	array('Yria','Furbina Kosa','No','Yes'),
	array('Yria','Nota Ocean','Yes','No'),
	array('Yria','Ghion Sea','Yes','No'),
	array('Ghion','Yria','Yes','Yes'),
	array('Ghion','Lehas','Yes','Yes'),
	array('Ghion','Olbucfor','No','Yes'),
	array('Ghion','Furbina Kosa','No','Yes'),
	array('Ghion','Ghion Sea','Yes','No'),
	array('Lehas','Ghion','Yes','Yes'),
	array('Lehas','Olbucfor','No','Yes'),
	array('Lehas','Cope Dive','Yes','Yes'),
	array('Lehas','Ghion Sea','Yes','No'),
	array('Lehas','Big Sea','Yes','No'),
	array('Olbucfor','Ghion','No','Yes'),
	array('Olbucfor','Lehas','No','Yes'),
	array('Olbucfor','Cope Dive','No','Yes'),
	array('Olbucfor','Furbina Kosa','No','Yes'),
	array('Mianey','Isthmus','No','Yes'),
	array('Mianey','Arenos Desert','Yes','Yes'),
	array('Mianey','Cope Dive','No','Yes'),
	array('Mianey','Furbina Kosa','No','Yes'),
	array('Mianey','Buo Bay','Yes','No'),
	array('Mianey','Isthmus (West Coast)','Yes','No'),
	array('Cope Dive','Isthmus','No','Yes'),
	array('Cope Dive','Lehas','Yes','Yes'),
	array('Cope Dive','Olbucfor','No','Yes'),
	array('Cope Dive','Mianey','No','Yes'),
	array('Cope Dive','Furbina Kosa','No','Yes'),
	array('Cope Dive','Big Sea','Yes','No'),
	array('Cope Dive','Isthmus (East Coast)','Yes','No'),
	array('Furbina Kosa','Kelpuct','No','Yes'),
	array('Furbina Kosa','Taorip','No','Yes'),
	array('Furbina Kosa','Yria','No','Yes'),
	array('Furbina Kosa','Ghion','No','Yes'),
	array('Furbina Kosa','Olbucfor','No','Yes'),
	array('Furbina Kosa','Mianey','No','Yes'),
	array('Furbina Kosa','Cope Dive','No','Yes'),
	array('Square Patch of Water','Ota','Yes','No'),
	array('Square Patch of Water','Tamsin Sea','Yes','No'),
	array('Square Patch of Water','Knie (East Coast)','Yes','No'),
	array('Tamsin Sea','Albert','Yes','No'),
	array('Tamsin Sea','Southern Oz','Yes','No'),
	array('Tamsin Sea','Ota','Yes','No'),
	array('Tamsin Sea','Square Patch of Water','Yes','No'),
	array('Tamsin Sea','Nota Ocean','Yes','No'),
	array('Tamsin Sea','The Wet','Yes','No'),
	array('Nota Ocean','Southern Oz','Yes','No'),
	array('Nota Ocean','Western Oz','Yes','No'),
	array('Nota Ocean','Northern Terror','Yes','No'),
	array('Nota Ocean','Ota','Yes','No'),
	array('Nota Ocean','Appa','Yes','No'),
	array('Nota Ocean','Litov','Yes','No'),
	array('Nota Ocean','Yria','Yes','No'),
	array('Nota Ocean','Tamsin Sea','Yes','No'),
	array('Nota Ocean','Cove','Yes','No'),
	array('Nota Ocean','Passage','Yes','No'),
	array('Nota Ocean','Ghion Sea','Yes','No'),
	array('Cove','Igma','Yes','No'),
	array('Cove','Ota','Yes','No'),
	array('Cove','Appa','Yes','No'),
	array('Cove','Nota Ocean','Yes','No'),
	array('Passage','Appa','Yes','No'),
	array('Passage','Prithski','Yes','No'),
	array('Passage','Litov','Yes','No'),
	array('Passage','Nota Ocean','Yes','No'),
	array('The Lagoon','Eot','Yes','No'),
	array('The Lagoon','Igma','Yes','No'),
	array('The Lagoon','Appa','Yes','No'),
	array('The Lagoon','Prithski','Yes','No'),
	array('The Lagoon','Vorulov','Yes','No'),
	array('The Lagoon','Kerop','Yes','No'),
	array('The Lagoon','Old Creek','Yes','No'),
	array('Old Creek','Eot','Yes','No'),
	array('Old Creek','Au','Yes','No'),
	array('Old Creek','Igma','Yes','No'),
	array('Old Creek','The Lagoon','Yes','No'),
	array('Old Creek','Knie (West Coast)','Yes','No'),
	array('The Wet','Albert','Yes','No'),
	array('The Wet','Old North Wales','Yes','No'),
	array('The Wet','Tamsin Sea','Yes','No'),
	array('The Wet','Triak','Yes','No'),
	array('The Wet','Big Sea','Yes','No'),
	array('Triak','Old North Wales','Yes','No'),
	array('Triak','Kingsland','Yes','No'),
	array('Triak','The Wet','Yes','No'),
	array('Triak','Ghion Sea','Yes','No'),
	array('Triak','Big Sea','Yes','No'),
	array('Ghion Sea','Kingsland','Yes','No'),
	array('Ghion Sea','Northern Terror','Yes','No'),
	array('Ghion Sea','Yria','Yes','No'),
	array('Ghion Sea','Ghion','Yes','No'),
	array('Ghion Sea','Lehas','Yes','No'),
	array('Ghion Sea','Nota Ocean','Yes','No'),
	array('Ghion Sea','Triak','Yes','No'),
	array('Ghion Sea','Big Sea','Yes','No'),
	array('Big Sea','The point','Yes','No'),
	array('Big Sea','North Walang','Yes','No'),
	array('Big Sea','Lehas','Yes','No'),
	array('Big Sea','Cope Dive','Yes','No'),
	array('Big Sea','The Wet','Yes','No'),
	array('Big Sea','Triak','Yes','No'),
	array('Big Sea','Ghion Sea','Yes','No'),
	array('Big Sea','New Stretch','Yes','No'),
	array('Big Sea','Isthmus (East Coast)','Yes','No'),
	array('Big Sea','Isthmus (West Coast)','Yes','No'),
	array('New Stretch','North Walang','Yes','No'),
	array('New Stretch','South Walang','Yes','No'),
	array('New Stretch','Big Sea','Yes','No'),
	array('New Stretch','Buo Bay','Yes','No'),
	array('New Stretch','Forth of toria','Yes','No'),
	array('New Stretch','Isthmus (West Coast)','Yes','No'),
	array('Buo Bay','Arenos Desert','Yes','No'),
	array('Buo Bay','Rint','Yes','No'),
	array('Buo Bay','Mianey','Yes','No'),
	array('Buo Bay','New Stretch','Yes','No'),
	array('Buo Bay','Forth of toria','Yes','No'),
	array('Buo Bay','Isthmus (West Coast)','Yes','No'),
	array('Forth of toria','South Walang','Yes','No'),
	array('Forth of toria','Lik','Yes','No'),
	array('Forth of toria','Quok','Yes','No'),
	array('Forth of toria','Rint','Yes','No'),
	array('Forth of toria','New Stretch','Yes','No'),
	array('Forth of toria','Buo Bay','Yes','No'),
	array('Forth of toria','Fonty Sea','Yes','No'),
	array('Fonty Sea','South Walang','Yes','No'),
	array('Fonty Sea','Lik','Yes','No'),
	array('Fonty Sea','Mealak','Yes','No'),
	array('Fonty Sea','Bdail','Yes','No'),
	array('Fonty Sea','Hixalop','Yes','No'),
	array('Fonty Sea','Forth of toria','Yes','No'),
	array('Fonty Sea','New Bay','Yes','No'),
	array('Fonty Sea','Orina Sea','Yes','No'),
	array('Fonty Sea','Trago Sea','Yes','No'),
	array('New Bay','Kreiasth','Yes','No'),
	array('New Bay','Mealak','Yes','No'),
	array('New Bay','Hixalop','Yes','No'),
	array('New Bay','Fonty Sea','Yes','No'),
	array('New Bay','Nuit','Yes','No'),
	array('Orina Sea','Bdail','Yes','No'),
	array('Orina Sea','Metpri','Yes','No'),
	array('Orina Sea','Orkali','Yes','No'),
	array('Orina Sea','Fonty Sea','Yes','No'),
	array('Orina Sea','Trago Sea','Yes','No'),
	array('Orina Sea','Acabat (East Coast)','Yes','No'),
	array('Trago Sea','Orkali','Yes','No'),
	array('Trago Sea','Porinta','Yes','No'),
	array('Trago Sea','Fonty Sea','Yes','No'),
	array('Trago Sea','Orina Sea','Yes','No'),
	array('Lake','Lanbuo','Yes','No'),
	array('Lake','Metpri','Yes','No'),
	array('Lake','Lireo','Yes','No'),
	array('Lake','Alternative States United','Yes','No'),
	array('Lake','Ayetok','Yes','No'),
	array('Lake','Acabat (West Coast)','Yes','No'),
	array('Seca Desert','Arenos Desert','No','Yes'),
	array('Seca Desert','Kreiasth','No','Yes'),
	array('Seca Desert','Kelpuct','No','Yes'),
	array('Seca Desert','Thuimp','No','Yes'),
	array('Seca Desert','Vaarle','No','Yes'),
	array('Seca Desert','Nuit','No','Yes'),
	array('Thuimp','mraerof','No','Yes'),
	array('Thuimp','Montuk','No','Yes'),
	array('Thuimp','Kelpuct','No','Yes'),
	array('Thuimp','Seca Desert','No','Yes'),
	array('Thuimp','Vaarle','No','Yes'),
	array('Vaarle','mraerof','No','Yes'),
	array('Vaarle','Seca Desert','No','Yes'),
	array('Vaarle','Thuimp','No','Yes'),
	array('Vaarle','Nuit','No','Yes'),
	array('Vaarle','Uark','No','Yes'),
	array('Nuit','Kreiasth','Yes','Yes'),
	array('Nuit','Hixalop','Yes','Yes'),
	array('Nuit','Artok','No','Yes'),
	array('Nuit','New Bay','Yes','No'),
	array('Nuit','Seca Desert','No','Yes'),
	array('Nuit','Vaarle','No','Yes'),
	array('Nuit','Uark','No','Yes'),
	array('Uark','Artok','No','Yes'),
	array('Uark','Lanbuo','No','Yes'),
	array('Uark','mraerof','No','Yes'),
	array('Uark','Vaarle','No','Yes'),
	array('Uark','Nuit','No','Yes'),
	array('Isthmus (East Coast)','The point','Yes','No'),
	array('Isthmus (East Coast)','Cope Dive','Yes','No'),
	array('Isthmus (East Coast)','Big Sea','Yes','No'),
	array('Isthmus (West Coast)','The point','Yes','No'),
	array('Isthmus (West Coast)','Mianey','Yes','No'),
	array('Isthmus (West Coast)','Big Sea','Yes','No'),
	array('Isthmus (West Coast)','New Stretch','Yes','No'),
	array('Isthmus (West Coast)','Buo Bay','Yes','No'),
	array('Knie (East Coast)','Ota','Yes','No'),
	array('Knie (East Coast)','Square Patch of Water','Yes','No'),
	array('Knie (West Coast)','Eot','Yes','No'),
	array('Knie (West Coast)','Au','Yes','No'),
	array('Knie (West Coast)','Old Creek','Yes','No'),
	array('Acabat (West Coast)','Lanbuo','Yes','No'),
	array('Acabat (West Coast)','Metpri','Yes','No'),
	array('Acabat (West Coast)','Lake','Yes','No'),
	array('Acabat (East Coast)','Bdail','Yes','No'),
	array('Acabat (East Coast)','Metpri','Yes','No'),
	array('Acabat (East Coast)','Orina Sea','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	 list($from, $to, $fleets, $armies)=$borderRawRow;
	 InstallTerritory::$Territories[$from]->addBorder(InstallTerritory::$Territories[$to]  ,$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
