<?php
// This is file installs the map data for the ColdWar variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('West Pacific', 'Sea', 'No', 0, 804, 30, 423, 19),
	array('East Pacific', 'Sea', 'No', 0, 240, 79, 75, 68),
	array('Bering Sea', 'Sea', 'No', 0, 653, 116, 380, 79),
	array('Japan', 'Coast', 'Yes', 0, 811, 114, 514, 81),
	array('Philippines', 'Coast', 'No', 2, 1040, 90, 648, 57),
	array('Indonesia', 'Coast', 'Yes', 0, 1152, 140, 705, 93),
	array('Alaska', 'Coast', 'Yes', 0, 513, 202, 323, 139),
	array('Kamchatka', 'Coast', 'No', 1, 655, 207, 422, 162),
	array('West Canada', 'Coast', 'No', 2, 402, 248, 235, 182),
	array('Vladivostok', 'Coast', 'Yes', 1, 776, 206, 486, 121),
	array('Manchuria', 'Coast', 'No', 1, 839, 191, 514, 133),
	array('Seoul', 'Coast', 'Yes', 0, 885, 154, 547, 110),
	array('Shanghai', 'Coast', 'Yes', 1, 976, 209, 604, 143),
	array('North Vietnam', 'Coast', 'No', 1, 1062, 245, 649, 170),
	array('South East Asia', 'Coast', 'No', 0, 1096, 284, 670, 183),
	array('Bangladesh', 'Coast', 'No', 0, 1039, 339, 638, 217),
	array('India', 'Coast', 'Yes', 0, 1049, 426, 662, 274),
	array('Siberia', 'Coast', 'No', 1, 766, 299, 491, 231),
	array('Urals', 'Coast', 'No', 1, 809, 437, 481, 279),
	array('Mongolia', 'Land', 'No', 1, 883, 311, 544, 183),
	array('Yellow Sea', 'Sea', 'No', 0, 944, 101, 590, 80),
	array('South China Sea', 'Sea', 'No', 0, 1090, 179, 677, 127),
	array('Bay of Bengal', 'Sea', 'No', 0, 1134, 345, 677, 227),
	array('Indian Ocean', 'Sea', 'No', 0, 1167, 554, 736, 388),
	array('Arctic Ocean', 'Sea', 'No', 0, 588, 300, 393, 200),
	array('Greenland', 'Coast', 'No', 2, 520, 422, 332, 269),
	array('Norwegian Sea', 'Sea', 'No', 0, 584, 459, 361, 315),
	array('West China', 'Land', 'No', 1, 947, 344, 596, 205),
	array('Los Angeles', 'Coast', 'Yes', 2, 291, 205, 197, 137),
	array('Midwest', 'Land', 'No', 2, 268, 316, 174, 228),
	array('Southwest', 'Coast', 'No', 2, 218, 258, 140, 185),
	array('Florida', 'Coast', 'No', 2, 193, 375, 146, 256),
	array('Toronto', 'Coast', 'Yes', 0, 313, 387, 208, 244),
	array('New York', 'Coast', 'Yes', 2, 256, 420, 181, 289),
	array('Quebec', 'Coast', 'No', 2, 339, 415, 201, 276),
	array('Mexico', 'Coast', 'No', 0, 150, 259, 113, 167),
	array('West Atlantic', 'Sea', 'No', 0, 248, 594, 162, 355),
	array('East Atlantic', 'Sea', 'No', 0, 439, 630, 275, 381),
	array('Panama', 'Coast', 'Yes', 0, 25, 445, 36, 280),
	array('Brazil', 'Coast', 'Yes', 0, 28, 649, 24, 415),
	array('Spain', 'Coast', 'No', 2, 560, 652, 350, 407),
	array('East Africa', 'Coast', 'No', 0, 995, 715, 531, 451),
	array('Egypt', 'Coast', 'Yes', 0, 797, 689, 486, 432),
	array('Paris', 'Coast', 'Yes', 2, 606, 625, 368, 387),
	array('London', 'Coast', 'Yes', 2, 582, 581, 361, 370),
	array('North Africa', 'Coast', 'No', 0, 614, 701, 342, 450),
	array('Colombia', 'Coast', 'No', 0, 18, 521, 27, 333),
	array('Libya', 'Coast', 'No', 0, 743, 712, 467, 443),
	array('Tunis', 'Coast', 'Yes', 0, 654, 706, 409, 431),
	array('Italy', 'Coast', 'No', 2, 664, 641, 405, 396),
	array('Arabia', 'Coast', 'No', 0, 922, 630, 548, 409),
	array('Pakistan', 'Coast', 'No', 2, 983, 485, 608, 316),
	array('Afghanistan', 'Land', 'No', 0, 944, 483, 583, 321),
	array('Iran', 'Coast', 'Yes', 0, 920, 551, 545, 362),
	array('Caucasus', 'Coast', 'No', 1, 802, 537, 497, 337),
	array('Moscow', 'Land', 'Yes', 1, 753, 539, 472, 339),
	array('Leningrad', 'Coast', 'Yes', 1, 708, 515, 443, 333),
	array('Sweden', 'Coast', 'Yes', 0, 642, 506, 400, 328),
	array('Norway', 'Coast', 'No', 2, 620, 538, 392, 330),
	array('Ukraine', 'Coast', 'No', 1, 727, 591, 446, 372),
	array('Yugoslavia', 'Coast', 'No', 0, 677, 624, 421, 389),
	array('Greece', 'Coast', 'No', 2, 727, 655, 452, 408),
	array('Albania', 'Coast', 'Yes', 1, 707, 644, 434, 395),
	array('Iraq', 'Coast', 'No', 2, 855, 601, 527, 376),
	array('Istanbul', 'Coast', 'Yes', 2, 786, 609, 470, 396),
	array('Armenia', 'Coast', 'No', 2, 820, 590, 507, 374),
	array('Levant', 'Coast', 'No', 0, 826, 623, 512, 384),
	array('East Germany', 'Coast', 'Yes', 0, 663, 582, 412, 363),
	array('West Germany', 'Coast', 'Yes', 0, 626, 592, 385, 373),
	array('Denmark', 'Coast', 'No', 2, 629, 569, 394, 352),
	array('Venezuela', 'Coast', 'No', 0, 66, 558, 58, 350),
	array('Central America', 'Coast', 'No', 0, 65, 376, 55, 240),
	array('Havana', 'Coast', 'Yes', 1, 126, 440, 92, 273),
	array('Saigon', 'Coast', 'Yes', 0, 1095, 204, 672, 143),
	array('Gulf of Mexico', 'Sea', 'No', 0, 142, 383, 88, 218),
	array('Caribbean Sea', 'Sea', 'No', 0, 70, 466, 67, 304),
	array('Arabian Sea', 'Sea', 'No', 0, 1043, 527, 637, 372),
	array('Red Sea', 'Sea', 'No', 0, 993, 667, 540, 426),
	array('Black Sea', 'Sea', 'No', 0, 760, 601, 488, 367),
	array('East Mediterranean', 'Sea', 'No', 0, 776, 665, 472, 417),
	array('Baltic Sea', 'Sea', 'No', 0, 663, 552, 416, 340),
	array('North Sea', 'Sea', 'No', 0, 594, 547, 372, 339),
	array('Ionian Sea', 'Sea', 'No', 0, 703, 683, 428, 427),
	array('West Mediterranean', 'Sea', 'No', 0, 650, 667, 377, 418),
	array('Finland', 'Coast', 'No', 0, 671, 513, 420, 324),
	array('Central America (West Coast)', 'Coast', 'No', 0, 63, 364, 40, 255),
	array('Central America (East Coast)', 'Coast', 'No', 0, 70, 377, 64, 254),
	array('Mexico (West Coast)', 'Coast', 'No', 0, 135, 257, 89, 166),
	array('Mexico (East Coast)', 'Coast', 'No', 0, 101, 304, 84, 197),
	array('West Canada (West Coast)', 'Coast', 'No', 0, 383, 227, 251, 148),
	array('West Canada (North Coast)', 'Coast', 'No', 0, 471, 267, 297, 181),
	array('Paris (North Coast)', 'Coast', 'No', 0, 589, 614, 361, 385),
	array('Paris (South Coast)', 'Coast', 'No', 0, 621, 642, 380, 401),
	array('Leningrad (North Coast)', 'Coast', 'No', 0, 679, 469, 424, 296),
	array('Leningrad (South Coast)', 'Coast', 'No', 0, 679, 553, 423, 343),
	array('North Korea', 'Coast', 'No', 0, 866, 172, 535, 116),
	array('North Korea (East Coast)', 'Coast', 'No', 0, 863, 168, 532, 115),
	array('North Korea (West Coast)', 'Coast', 'No', 0, 877, 175, 544, 120),
	array('Colombia (North Coast)', 'Coast', 'No', 0, 37, 509, 51, 309),
	array('Colombia (West Coast)', 'Coast', 'No', 0, 7, 479, 10, 300),
	array('Hudson Bay', 'Sea', 'No', 0, 381, 356, 236, 248),
	array('Sea of Japan', 'Sea', 'No', 0, 824, 145, 508, 103),
	array('Gulf of Alaska', 'Sea', 'No', 0, 413, 142, 286, 111),
	array('Australia', 'Coast', 'Yes', 2, 1196, 13, 744, 11)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('West Pacific','East Pacific','Yes','No'),
	array('West Pacific','Bering Sea','Yes','No'),
	array('West Pacific','Japan','Yes','No'),
	array('West Pacific','Philippines','Yes','No'),
	array('West Pacific','Indonesia','Yes','No'),
	array('West Pacific','Yellow Sea','Yes','No'),
	array('West Pacific','Australia','Yes','No'),
	array('East Pacific','Bering Sea','Yes','No'),
	array('East Pacific','Los Angeles','Yes','No'),
	array('East Pacific','Panama','Yes','No'),
	array('East Pacific','Central America (West Coast)','Yes','No'),
	array('East Pacific','Mexico (West Coast)','Yes','No'),
	array('East Pacific','Colombia (West Coast)','Yes','No'),
	array('East Pacific','Gulf of Alaska','Yes','No'),
	array('Bering Sea','Japan','Yes','No'),
	array('Bering Sea','Alaska','Yes','No'),
	array('Bering Sea','Kamchatka','Yes','No'),
	array('Bering Sea','Vladivostok','Yes','No'),
	array('Bering Sea','Arctic Ocean','Yes','No'),
	array('Bering Sea','Sea of Japan','Yes','No'),
	array('Bering Sea','Gulf of Alaska','Yes','No'),
	array('Japan','Yellow Sea','Yes','No'),
	array('Japan','Sea of Japan','Yes','No'),
	array('Philippines','Indonesia','Yes','Yes'),
	array('Philippines','Yellow Sea','Yes','No'),
	array('Philippines','South China Sea','Yes','No'),
	array('Indonesia','South China Sea','Yes','No'),
	array('Indonesia','Bay of Bengal','Yes','No'),
	array('Indonesia','Indian Ocean','Yes','No'),
	array('Indonesia','Australia','Yes','Yes'),
	array('Alaska','West Canada','No','Yes'),
	array('Alaska','Arctic Ocean','Yes','No'),
	array('Alaska','West Canada (West Coast)','Yes','No'),
	array('Alaska','West Canada (North Coast)','Yes','No'),
	array('Alaska','Gulf of Alaska','Yes','No'),
	array('Kamchatka','Vladivostok','Yes','Yes'),
	array('Kamchatka','Siberia','Yes','Yes'),
	array('Kamchatka','Arctic Ocean','Yes','No'),
	array('West Canada','Los Angeles','No','Yes'),
	array('West Canada','Midwest','No','Yes'),
	array('West Canada','Toronto','No','Yes'),
	array('Vladivostok','Manchuria','No','Yes'),
	array('Vladivostok','Siberia','No','Yes'),
	array('Vladivostok','North Korea','No','Yes'),
	array('Vladivostok','North Korea (East Coast)','Yes','No'),
	array('Vladivostok','Sea of Japan','Yes','No'),
	array('Manchuria','Shanghai','Yes','Yes'),
	array('Manchuria','Siberia','No','Yes'),
	array('Manchuria','Mongolia','No','Yes'),
	array('Manchuria','Yellow Sea','Yes','No'),
	array('Manchuria','North Korea','No','Yes'),
	array('Manchuria','North Korea (West Coast)','Yes','No'),
	array('Seoul','Yellow Sea','Yes','No'),
	array('Seoul','North Korea','No','Yes'),
	array('Seoul','North Korea (East Coast)','Yes','No'),
	array('Seoul','North Korea (West Coast)','Yes','No'),
	array('Seoul','Sea of Japan','Yes','No'),
	array('Shanghai','North Vietnam','Yes','Yes'),
	array('Shanghai','South East Asia','No','Yes'),
	array('Shanghai','Bangladesh','No','Yes'),
	array('Shanghai','Mongolia','No','Yes'),
	array('Shanghai','Yellow Sea','Yes','No'),
	array('Shanghai','South China Sea','Yes','No'),
	array('Shanghai','West China','No','Yes'),
	array('North Vietnam','South East Asia','No','Yes'),
	array('North Vietnam','South China Sea','Yes','No'),
	array('North Vietnam','Saigon','Yes','Yes'),
	array('South East Asia','Bangladesh','Yes','Yes'),
	array('South East Asia','South China Sea','Yes','No'),
	array('South East Asia','Bay of Bengal','Yes','No'),
	array('South East Asia','Saigon','Yes','Yes'),
	array('Bangladesh','India','Yes','Yes'),
	array('Bangladesh','Bay of Bengal','Yes','No'),
	array('Bangladesh','West China','No','Yes'),
	array('India','Bay of Bengal','Yes','No'),
	array('India','Indian Ocean','Yes','No'),
	array('India','Pakistan','Yes','Yes'),
	array('India','Arabian Sea','Yes','No'),
	array('Siberia','Urals','Yes','Yes'),
	array('Siberia','Mongolia','No','Yes'),
	array('Siberia','Arctic Ocean','Yes','No'),
	array('Siberia','West China','No','Yes'),
	array('Urals','Arctic Ocean','Yes','No'),
	array('Urals','Norwegian Sea','Yes','No'),
	array('Urals','West China','No','Yes'),
	array('Urals','Pakistan','No','Yes'),
	array('Urals','Afghanistan','No','Yes'),
	array('Urals','Iran','No','Yes'),
	array('Urals','Caucasus','No','Yes'),
	array('Urals','Moscow','No','Yes'),
	array('Urals','Leningrad','No','Yes'),
	array('Urals','Leningrad (North Coast)','Yes','No'),
	array('Mongolia','West China','No','Yes'),
	array('Yellow Sea','South China Sea','Yes','No'),
	array('Yellow Sea','North Korea (West Coast)','Yes','No'),
	array('Yellow Sea','Sea of Japan','Yes','No'),
	array('South China Sea','Bay of Bengal','Yes','No'),
	array('South China Sea','Saigon','Yes','No'),
	array('Bay of Bengal','Indian Ocean','Yes','No'),
	array('Indian Ocean','East Africa','Yes','No'),
	array('Indian Ocean','Arabian Sea','Yes','No'),
	array('Indian Ocean','Red Sea','Yes','No'),
	array('Indian Ocean','Australia','Yes','No'),
	array('Arctic Ocean','Greenland','Yes','No'),
	array('Arctic Ocean','Norwegian Sea','Yes','No'),
	array('Arctic Ocean','West Atlantic','Yes','No'),
	array('Arctic Ocean','West Canada (North Coast)','Yes','No'),
	array('Arctic Ocean','Hudson Bay','Yes','No'),
	array('Greenland','Norwegian Sea','Yes','No'),
	array('Greenland','West Atlantic','Yes','No'),
	array('Norwegian Sea','West Atlantic','Yes','No'),
	array('Norwegian Sea','East Atlantic','Yes','No'),
	array('Norwegian Sea','London','Yes','No'),
	array('Norwegian Sea','Norway','Yes','No'),
	array('Norwegian Sea','North Sea','Yes','No'),
	array('Norwegian Sea','Leningrad (North Coast)','Yes','No'),
	array('West China','Pakistan','No','Yes'),
	array('Los Angeles','Midwest','No','Yes'),
	array('Los Angeles','Southwest','No','Yes'),
	array('Los Angeles','Mexico','No','Yes'),
	array('Los Angeles','Mexico (West Coast)','Yes','No'),
	array('Los Angeles','West Canada (West Coast)','Yes','No'),
	array('Los Angeles','Gulf of Alaska','Yes','No'),
	array('Midwest','Southwest','No','Yes'),
	array('Midwest','Florida','No','Yes'),
	array('Midwest','Toronto','No','Yes'),
	array('Midwest','New York','No','Yes'),
	array('Southwest','Florida','Yes','Yes'),
	array('Southwest','Mexico','No','Yes'),
	array('Southwest','Gulf of Mexico','Yes','No'),
	array('Southwest','Mexico (East Coast)','Yes','No'),
	array('Florida','New York','Yes','Yes'),
	array('Florida','West Atlantic','Yes','No'),
	array('Florida','Gulf of Mexico','Yes','No'),
	array('Florida','Caribbean Sea','Yes','No'),
	array('Toronto','Quebec','Yes','Yes'),
	array('Toronto','West Canada (North Coast)','Yes','No'),
	array('Toronto','Hudson Bay','Yes','No'),
	array('New York','Quebec','Yes','Yes'),
	array('New York','West Atlantic','Yes','No'),
	array('Quebec','West Atlantic','Yes','No'),
	array('Quebec','Hudson Bay','Yes','No'),
	array('Mexico','Central America','No','Yes'),
	array('West Atlantic','East Atlantic','Yes','No'),
	array('West Atlantic','Brazil','Yes','No'),
	array('West Atlantic','Venezuela','Yes','No'),
	array('West Atlantic','Caribbean Sea','Yes','No'),
	array('West Atlantic','Hudson Bay','Yes','No'),
	array('East Atlantic','Spain','Yes','No'),
	array('East Atlantic','London','Yes','No'),
	array('East Atlantic','North Africa','Yes','No'),
	array('East Atlantic','North Sea','Yes','No'),
	array('East Atlantic','West Mediterranean','Yes','No'),
	array('East Atlantic','Paris (North Coast)','Yes','No'),
	array('Panama','Colombia','No','Yes'),
	array('Panama','Central America','No','Yes'),
	array('Panama','Caribbean Sea','Yes','No'),
	array('Panama','Central America (West Coast)','Yes','No'),
	array('Panama','Central America (East Coast)','Yes','No'),
	array('Panama','Colombia (North Coast)','Yes','No'),
	array('Panama','Colombia (West Coast)','Yes','No'),
	array('Brazil','Colombia','No','Yes'),
	array('Brazil','Venezuela','Yes','Yes'),
	array('Spain','Paris','No','Yes'),
	array('Spain','West Mediterranean','Yes','No'),
	array('Spain','Paris (North Coast)','Yes','No'),
	array('Spain','Paris (South Coast)','Yes','No'),
	array('East Africa','Egypt','Yes','Yes'),
	array('East Africa','Libya','No','Yes'),
	array('East Africa','Red Sea','Yes','No'),
	array('Egypt','Libya','Yes','Yes'),
	array('Egypt','Arabia','Yes','Yes'),
	array('Egypt','Levant','Yes','Yes'),
	array('Egypt','Red Sea','Yes','No'),
	array('Egypt','East Mediterranean','Yes','No'),
	array('Paris','Italy','No','Yes'),
	array('Paris','West Germany','No','Yes'),
	array('London','North Sea','Yes','No'),
	array('North Africa','Libya','No','Yes'),
	array('North Africa','Tunis','Yes','Yes'),
	array('North Africa','West Mediterranean','Yes','No'),
	array('Colombia','Venezuela','No','Yes'),
	array('Libya','Tunis','Yes','Yes'),
	array('Libya','East Mediterranean','Yes','No'),
	array('Libya','Ionian Sea','Yes','No'),
	array('Tunis','Ionian Sea','Yes','No'),
	array('Tunis','West Mediterranean','Yes','No'),
	array('Italy','Yugoslavia','Yes','Yes'),
	array('Italy','Ionian Sea','Yes','No'),
	array('Italy','West Mediterranean','Yes','No'),
	array('Italy','Paris (South Coast)','Yes','No'),
	array('Arabia','Iraq','Yes','Yes'),
	array('Arabia','Levant','No','Yes'),
	array('Arabia','Arabian Sea','Yes','No'),
	array('Arabia','Red Sea','Yes','No'),
	array('Pakistan','Afghanistan','No','Yes'),
	array('Pakistan','Iran','Yes','Yes'),
	array('Pakistan','Arabian Sea','Yes','No'),
	array('Afghanistan','Iran','No','Yes'),
	array('Iran','Caucasus','No','Yes'),
	array('Iran','Iraq','Yes','Yes'),
	array('Iran','Armenia','No','Yes'),
	array('Iran','Arabian Sea','Yes','No'),
	array('Caucasus','Moscow','No','Yes'),
	array('Caucasus','Ukraine','Yes','Yes'),
	array('Caucasus','Armenia','Yes','Yes'),
	array('Caucasus','Black Sea','Yes','No'),
	array('Moscow','Leningrad','No','Yes'),
	array('Moscow','Ukraine','No','Yes'),
	array('Moscow','East Germany','No','Yes'),
	array('Leningrad','Norway','No','Yes'),
	array('Leningrad','East Germany','No','Yes'),
	array('Leningrad','Finland','No','Yes'),
	array('Sweden','Norway','Yes','Yes'),
	array('Sweden','Denmark','Yes','Yes'),
	array('Sweden','Baltic Sea','Yes','No'),
	array('Sweden','North Sea','Yes','No'),
	array('Sweden','Finland','Yes','Yes'),
	array('Norway','North Sea','Yes','No'),
	array('Norway','Finland','No','Yes'),
	array('Norway','Leningrad (North Coast)','Yes','No'),
	array('Ukraine','Yugoslavia','No','Yes'),
	array('Ukraine','Greece','No','Yes'),
	array('Ukraine','Istanbul','Yes','Yes'),
	array('Ukraine','East Germany','No','Yes'),
	array('Ukraine','Black Sea','Yes','No'),
	array('Yugoslavia','Greece','No','Yes'),
	array('Yugoslavia','Albania','Yes','Yes'),
	array('Yugoslavia','East Germany','No','Yes'),
	array('Yugoslavia','West Germany','No','Yes'),
	array('Yugoslavia','Ionian Sea','Yes','No'),
	array('Greece','Albania','Yes','Yes'),
	array('Greece','Istanbul','Yes','Yes'),
	array('Greece','East Mediterranean','Yes','No'),
	array('Greece','Ionian Sea','Yes','No'),
	array('Albania','Ionian Sea','Yes','No'),
	array('Iraq','Armenia','No','Yes'),
	array('Iraq','Levant','No','Yes'),
	array('Iraq','Arabian Sea','Yes','No'),
	array('Istanbul','Armenia','Yes','Yes'),
	array('Istanbul','Levant','Yes','Yes'),
	array('Istanbul','Black Sea','Yes','No'),
	array('Istanbul','East Mediterranean','Yes','No'),
	array('Armenia','Levant','No','Yes'),
	array('Armenia','Black Sea','Yes','No'),
	array('Levant','East Mediterranean','Yes','No'),
	array('East Germany','West Germany','No','Yes'),
	array('East Germany','Denmark','Yes','Yes'),
	array('East Germany','Baltic Sea','Yes','No'),
	array('East Germany','Leningrad (South Coast)','Yes','No'),
	array('West Germany','Denmark','Yes','Yes'),
	array('West Germany','North Sea','Yes','No'),
	array('West Germany','Paris (North Coast)','Yes','No'),
	array('Denmark','Baltic Sea','Yes','No'),
	array('Denmark','North Sea','Yes','No'),
	array('Venezuela','Caribbean Sea','Yes','No'),
	array('Venezuela','Colombia (North Coast)','Yes','No'),
	array('Havana','Gulf of Mexico','Yes','No'),
	array('Havana','Caribbean Sea','Yes','No'),
	array('Gulf of Mexico','Caribbean Sea','Yes','No'),
	array('Gulf of Mexico','Mexico (East Coast)','Yes','No'),
	array('Caribbean Sea','Central America (East Coast)','Yes','No'),
	array('Caribbean Sea','Mexico (East Coast)','Yes','No'),
	array('Caribbean Sea','Colombia (North Coast)','Yes','No'),
	array('Arabian Sea','Red Sea','Yes','No'),
	array('East Mediterranean','Ionian Sea','Yes','No'),
	array('Baltic Sea','Finland','Yes','No'),
	array('Baltic Sea','Leningrad (South Coast)','Yes','No'),
	array('North Sea','Paris (North Coast)','Yes','No'),
	array('Ionian Sea','West Mediterranean','Yes','No'),
	array('West Mediterranean','Paris (South Coast)','Yes','No'),
	array('Finland','Leningrad (South Coast)','Yes','No'),
	array('Central America (West Coast)','Mexico (West Coast)','Yes','No'),
	array('Central America (East Coast)','Mexico (East Coast)','Yes','No'),
	array('West Canada (West Coast)','Gulf of Alaska','Yes','No'),
	array('West Canada (North Coast)','Hudson Bay','Yes','No'),
	array('North Korea (East Coast)','Sea of Japan','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
