<?php
// This is file installs the map data for the World variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Baltic Sea', 'Sea', 'No', 0, 744, 131, 372, 65),
	array('Skandanavia', 'Coast', 'Yes', 0, 748, 102, 374, 51),
	array('Great Britain', 'Coast', 'Yes', 0, 668, 149, 334, 76),
	array('Arctic Circle', 'Sea', 'No', 0, 670, 36, 300, 18),
	array('Beaufort Sea', 'Sea', 'No', 0, 315, 80, 164, 33),
	array('Thule', 'Coast', 'No', 0, 588, 66, 294, 34),
	array('Godthab', 'Coast', 'Yes', 0, 585, 90, 289, 49),
	array('Barents Sea', 'Sea', 'No', 0, 686, 66, 343, 33),
	array('East Siberian Sea', 'Sea', 'No', 0, 940, 58, 491, 29),
	array('Norwegian Sea', 'Sea', 'No', 0, 610, 136, 306, 69),
	array('Labrador Sea', 'Sea', 'No', 0, 525, 145, 270, 77),
	array('Hudson Bay', 'Sea', 'No', 0, 414, 127, 207, 67),
	array('Baffin Island', 'Coast', 'No', 0, 476, 93, 238, 49),
	array('Newfoundland', 'Coast', 'Yes', 12, 472, 150, 236, 79),
	array('Quebec', 'Coast', 'Yes', 12, 434, 178, 217, 84),
	array('Ontario', 'Coast', 'Yes', 12, 383, 165, 193, 84),
	array('Manitoba', 'Coast', 'Yes', 0, 355, 150, 179, 75),
	array('Saskatchewan', 'Land', 'No', 0, 320, 158, 160, 79),
	array('Alberta', 'Land', 'No', 0, 289, 165, 146, 77),
	array('British Columbia', 'Coast', 'Yes', 16, 264, 152, 132, 76),
	array('Northwest Territories', 'Coast', 'Yes', 16, 305, 115, 169, 59),
	array('Yukon Territory', 'Coast', 'Yes', 16, 260, 124, 130, 62),
	array('Alaska', 'Coast', 'Yes', 0, 205, 124, 100, 62),
	array('Bering Strait', 'Sea', 'No', 0, 152, 140, 76, 70),
	array('Northwest Pacific', 'Sea', 'No', 0, 1252, 224, 626, 112),
	array('North Pacific Ocean', 'Sea', 'No', 0, 180, 190, 103, 86),
	array('Indian Territory', 'Coast', 'Yes', 0, 266, 208, 133, 100),
	array('Midwest', 'Land', 'No', 0, 320, 200, 160, 104),
	array('Union', 'Coast', 'Yes', 0, 380, 220, 179, 111),
	array('Florida', 'Coast', 'Yes', 15, 360, 257, 180, 124),
	array('Deep South', 'Coast', 'No', 0, 318, 240, 165, 125),
	array('Texas', 'Coast', 'Yes', 15, 294, 252, 146, 129),
	array('Nevada', 'Land', 'No', 0, 265, 230, 135, 118),
	array('California', 'Coast', 'Yes', 15, 234, 222, 117, 111),
	array('Northwest Atlantic', 'Sea', 'No', 0, 450, 290, 229, 158),
	array('Northeast Atlantic', 'Sea', 'No', 0, 575, 260, 285, 142),
	array('Gulf of Mexico', 'Sea', 'No', 0, 340, 282, 162, 143),
	array('Carribean Sea', 'Sea', 'No', 0, 355, 320, 182, 166),
	array('Monterrey', 'Coast', 'No', 0, 266, 272, 134, 141),
	array('Mexico', 'Coast', 'Yes', 0, 285, 308, 149, 160),
	array('Central America', 'Coast', 'No', 0, 334, 347, 165, 169),
	array('Colombia', 'Coast', 'Yes', 0, 383, 394, 190, 191),
	array('Venezuela', 'Coast', 'Yes', 0, 415, 370, 204, 187),
	array('Carribean Islands', 'Coast', 'No', 0, 395, 314, 197, 157),
	array('Central Pacific Ocean', 'Sea', 'No', 0, 1340, 350, 682, 191),
	array('Northeast Pacific', 'Sea', 'No', 0, 220, 360, 139, 197),
	array('South Pacific Ocean', 'Sea', 'No', 0, 200, 650, 109, 338),
	array('East Pacific', 'Sea', 'No', 0, 240, 486, 153, 243),
	array('Pacific Islands', 'Sea', 'No', 0, 1335, 500, 672, 255),
	array('Southeast Pacific', 'Sea', 'No', 0, 350, 630, 193, 328),
	array('Ross Ice Shelf', 'Coast', 'No', 0, 1080, 742, 537, 374),
	array('Peru', 'Coast', 'Yes', 0, 370, 435, 182, 211),
	array('Chile', 'Coast', 'Yes', 1, 410, 586, 205, 293),
	array('Guyana', 'Coast', 'No', 0, 446, 374, 223, 189),
	array('Recife', 'Coast', 'Yes', 2, 486, 414, 243, 207),
	array('Brasillia', 'Land', 'Yes', 2, 446, 445, 223, 208),
	array('Amazon', 'Land', 'No', 0, 412, 410, 206, 205),
	array('Bolivia', 'Land', 'No', 0, 420, 470, 210, 237),
	array('Salvador', 'Coast', 'No', 0, 514, 448, 258, 224),
	array('Belo Horizonte', 'Land', 'No', 0, 486, 444, 243, 223),
	array('Rio de Janeiro', 'Coast', 'Yes', 2, 503, 468, 253, 235),
	array('Sao Paulo', 'Coast', 'No', 0, 465, 490, 240, 249),
	array('Uruguay', 'Coast', 'Yes', 0, 468, 534, 234, 266),
	array('Buenos Aires', 'Coast', 'Yes', 1, 443, 566, 224, 283),
	array('Mendoza', 'Land', 'No', 0, 426, 534, 213, 261),
	array('Santa Cruz', 'Coast', 'Yes', 1, 432, 605, 216, 300),
	array('West Atlantic Ocean', 'Sea', 'No', 0, 554, 480, 277, 235),
	array('East Atlantic Ocean', 'Sea', 'No', 0, 655, 470, 338, 267),
	array('Southwest Atlantic', 'Sea', 'No', 0, 560, 640, 285, 316),
	array('Southeast Atlantic', 'Sea', 'No', 0, 730, 615, 380, 302),
	array('Marie Byrd Land', 'Coast', 'No', 0, 400, 730, 222, 375),
	array('South Pole', 'Land', 'Yes', 0, 735, 751, 351, 374),
	array('Norwegian Dependency', 'Land', 'No', 0, 840, 734, 400, 364),
	array('British Antarctic Territory', 'Coast', 'Yes', 0, 520, 734, 260, 364),
	array('Antarctic Penninsula', 'Coast', 'No', 0, 502, 716, 251, 348),
	array('Sanae IV', 'Coast', 'Yes', 14, 665, 716, 336, 354),
	array('Novolazarevskaya', 'Coast', 'No', 0, 724, 714, 362, 352),
	array('Syowa', 'Coast', 'Yes', 0, 810, 700, 405, 350),
	array('Mawson', 'Coast', 'Yes', 5, 908, 702, 454, 351),
	array('Vostok', 'Coast', 'No', 0, 952, 712, 476, 356),
	array('Casey', 'Coast', 'Yes', 5, 1004, 696, 502, 348),
	array('Dumont dUrville', 'Coast', 'No', 0, 1042, 702, 521, 351),
	array('Leningradskaya', 'Coast', 'Yes', 5, 1080, 714, 540, 357),
	array('North Sea', 'Sea', 'No', 0, 682, 135, 346, 75),
	array('Mediterranean', 'Sea', 'No', 0, 745, 238, 373, 122),
	array('Southwest Indian', 'Sea', 'No', 0, 850, 590, 430, 317),
	array('Southeast Indian', 'Sea', 'No', 0, 1090, 600, 526, 324),
	array('Southern Indian Ocean', 'Sea', 'No', 0, 957, 598, 480, 301),
	array('Northwest Indian', 'Sea', 'No', 0, 925, 445, 460, 252),
	array('Northeast Indian', 'Sea', 'No', 0, 1045, 450, 517, 263),
	array('Arabian Sea', 'Sea', 'No', 0, 922, 335, 461, 164),
	array('Red Sea', 'Sea', 'No', 0, 860, 342, 436, 171),
	array('Southwest Pacific', 'Sea', 'No', 0, 1205, 625, 608, 307),
	array('Tasman Sea', 'Sea', 'No', 0, 1272, 550, 636, 275),
	array('Java Sea', 'Sea', 'No', 0, 1138, 465, 569, 230),
	array('Bay of Bengal', 'Sea', 'No', 0, 1024, 326, 508, 164),
	array('South China Sea', 'Sea', 'No', 0, 1116, 358, 558, 179),
	array('West Pacific Ocean', 'Sea', 'No', 0, 1228, 360, 616, 189),
	array('Yellow Sea', 'Sea', 'No', 0, 1157, 278, 580, 139),
	array('Sea of Japan', 'Sea', 'No', 0, 1166, 216, 583, 108),
	array('Sea of Othoksk', 'Sea', 'No', 0, 1171, 150, 584, 74),
	array('Japan', 'Coast', 'Yes', 0, 1190, 226, 595, 113),
	array('Spain', 'Coast', 'No', 0, 664, 215, 332, 111),
	array('France', 'Coast', 'Yes', 4, 694, 189, 343, 94),
	array('Germany', 'Coast', 'Yes', 4, 705, 170, 356, 84),
	array('Italy', 'Coast', 'Yes', 4, 720, 205, 357, 101),
	array('Austria-Hungary', 'Coast', 'No', 0, 737, 189, 369, 95),
	array('Poland', 'Coast', 'No', 0, 744, 164, 372, 85),
	array('Baltic States', 'Coast', 'No', 0, 760, 145, 382, 73),
	array('Saint Petersburg', 'Coast', 'Yes', 13, 796, 128, 398, 64),
	array('Belorussia', 'Land', 'Yes', 13, 780, 155, 390, 81),
	array('Ukraine', 'Coast', 'Yes', 0, 788, 175, 395, 90),
	array('Black Sea', 'Sea', 'No', 0, 803, 208, 399, 105),
	array('Balkans', 'Coast', 'No', 0, 760, 208, 380, 104),
	array('Moscow', 'Coast', 'Yes', 13, 827, 157, 416, 80),
	array('West Siberia', 'Coast', 'Yes', 0, 890, 136, 445, 67),
	array('East Siberia', 'Coast', 'Yes', 11, 998, 106, 499, 53),
	array('Yakutsk', 'Coast', 'Yes', 11, 1090, 114, 540, 57),
	array('Kamchatka', 'Coast', 'No', 0, 1182, 116, 591, 58),
	array('Kazakhstan', 'Land', 'No', 0, 905, 172, 456, 87),
	array('Omsk', 'Land', 'No', 0, 994, 158, 497, 79),
	array('Irkutsk', 'Land', 'No', 0, 1052, 154, 526, 77),
	array('Mongolia', 'Land', 'No', 0, 1045, 193, 517, 98),
	array('Inner Mongolia', 'Land', 'No', 0, 1078, 214, 539, 107),
	array('Western China', 'Land', 'No', 0, 988, 218, 494, 114),
	array('Beijing', 'Coast', 'Yes', 3, 1101, 238, 551, 116),
	array('Vladivostok', 'Coast', 'Yes', 11, 1128, 168, 564, 84),
	array('Heilongjiang', 'Land', 'No', 0, 1128, 196, 565, 100),
	array('Korea', 'Coast', 'Yes', 0, 1148, 236, 574, 118),
	array('Shanghai', 'Coast', 'Yes', 3, 1106, 255, 553, 131),
	array('Guangzhou', 'Coast', 'Yes', 3, 1098, 282, 549, 141),
	array('Vietnam', 'Coast', 'No', 0, 1090, 338, 546, 172),
	array('Thailand', 'Coast', 'Yes', 0, 1061, 350, 535, 185),
	array('Burma', 'Coast', 'No', 0, 1043, 297, 525, 152),
	array('Bangladesh', 'Coast', 'Yes', 0, 1022, 291, 512, 143),
	array('Lanzhou', 'Land', 'Yes', 0, 1042, 250, 521, 129),
	array('Tibet', 'Land', 'No', 0, 990, 261, 496, 131),
	array('Calcutta', 'Coast', 'Yes', 7, 992, 289, 496, 143),
	array('Bombay', 'Coast', 'Yes', 7, 974, 330, 487, 165),
	array('Delhi', 'Land', 'Yes', 7, 965, 267, 484, 137),
	array('Pakistan', 'Coast', 'No', 0, 938, 265, 468, 136),
	array('Afghanistan', 'Land', 'Yes', 0, 919, 246, 461, 123),
	array('Tajikistan', 'Land', 'No', 0, 947, 230, 469, 114),
	array('Kyrgyzstan', 'Land', 'No', 0, 933, 214, 472, 103),
	array('Iran', 'Coast', 'No', 0, 878, 258, 439, 126),
	array('Turkmenistan', 'Land', 'No', 0, 880, 224, 442, 111),
	array('Uzbekistan', 'Land', 'No', 0, 908, 217, 451, 103),
	array('Armenia', 'Coast', 'Yes', 0, 828, 207, 414, 103),
	array('Turkey', 'Coast', 'Yes', 0, 785, 228, 395, 114),
	array('Syria', 'Coast', 'Yes', 10, 818, 244, 409, 122),
	array('Iraq', 'Coast', 'Yes', 10, 848, 260, 421, 123),
	array('Saudi Arabia', 'Coast', 'Yes', 10, 840, 300, 440, 156),
	array('Western Australia', 'Coast', 'Yes', 17, 1136, 516, 568, 258),
	array('Northern Territory', 'Coast', 'No', 0, 1186, 473, 593, 243),
	array('Queensland', 'Coast', 'No', 0, 1230, 496, 615, 248),
	array('New South Wales', 'Coast', 'Yes', 17, 1224, 536, 614, 268),
	array('Victoria', 'Coast', 'Yes', 17, 1210, 550, 600, 275),
	array('South Australia', 'Coast', 'No', 0, 1197, 517, 591, 261),
	array('New Zealand', 'Coast', 'Yes', 0, 1285, 593, 640, 299),
	array('Indonesia', 'Coast', 'Yes', 0, 1126, 412, 563, 206),
	array('Phillipines', 'Coast', 'No', 0, 1143, 330, 578, 176),
	array('Morocco', 'Coast', 'Yes', 0, 644, 268, 321, 134),
	array('Algeria', 'Coast', 'Yes', 0, 684, 270, 342, 135),
	array('Libya', 'Coast', 'Yes', 9, 736, 270, 368, 141),
	array('Egypt', 'Coast', 'Yes', 9, 782, 273, 391, 144),
	array('North Sudan', 'Coast', 'Yes', 9, 788, 315, 394, 161),
	array('Ethiopia', 'Coast', 'Yes', 0, 835, 360, 413, 184),
	array('Somalia', 'Coast', 'No', 0, 859, 370, 429, 187),
	array('Mauritania', 'Coast', 'No', 0, 624, 304, 312, 154),
	array('Mali', 'Land', 'Yes', 6, 666, 316, 333, 158),
	array('Niger', 'Land', 'No', 0, 714, 312, 351, 161),
	array('Chad', 'Land', 'Yes', 0, 744, 326, 372, 163),
	array('South Sudan', 'Land', 'No', 0, 788, 355, 394, 180),
	array('Guinea', 'Coast', 'Yes', 6, 636, 358, 318, 183),
	array('Ghana', 'Coast', 'Yes', 6, 670, 359, 335, 173),
	array('Nigeria', 'Coast', 'No', 0, 706, 350, 353, 179),
	array('Cameroon', 'Coast', 'No', 0, 720, 375, 359, 189),
	array('Central African Republic', 'Land', 'No', 0, 760, 368, 375, 187),
	array('Congo', 'Coast', 'Yes', 0, 726, 410, 363, 201),
	array('Zaire', 'Land', 'Yes', 0, 762, 406, 379, 203),
	array('Uganda', 'Land', 'Yes', 8, 797, 404, 395, 202),
	array('Kenya', 'Coast', 'Yes', 8, 820, 390, 410, 195),
	array('Tanzania', 'Coast', 'Yes', 8, 804, 426, 402, 213),
	array('Madagascar', 'Coast', 'No', 0, 852, 492, 429, 240),
	array('Mozambique', 'Coast', 'Yes', 0, 814, 461, 405, 234),
	array('South Africa', 'Coast', 'Yes', 14, 777, 530, 383, 271),
	array('Zimbabwe', 'Land', 'No', 0, 786, 484, 393, 243),
	array('Botswana', 'Land', 'No', 0, 763, 496, 383, 250),
	array('Namibia', 'Coast', 'Yes', 14, 739, 510, 368, 257),
	array('Angola', 'Coast', 'No', 0, 740, 454, 370, 228),
	array('Zambia', 'Land', 'Yes', 0, 792, 455, 387, 232),
	array('Mozambique Channel', 'Sea', 'No', 0, 820, 512, 413, 256),
	array('Yukon Territory (North Coast)', 'Coast', 'No', 0, 282, 100, 141, 50),
	array('Yukon Territory (South Coast)', 'Coast', 'No', 0, 244, 132, 122, 66),
	array('Quebec (North Coast)', 'Coast', 'No', 0, 432, 144, 216, 72),
	array('Quebec (South Coast)', 'Coast', 'No', 0, 458, 192, 224, 96),
	array('Monterrey (West Coast)', 'Coast', 'No', 0, 236, 275, 118, 136),
	array('Monterrey (East Coast)', 'Coast', 'No', 0, 293, 292, 143, 144),
	array('Mexico (West Coast)', 'Coast', 'No', 0, 280, 326, 143, 162),
	array('Mexico (East Coast)', 'Coast', 'No', 0, 315, 308, 162, 154),
	array('Colombia (West Coast)', 'Coast', 'No', 0, 358, 383, 183, 193),
	array('Colombia (North Coast)', 'Coast', 'No', 0, 376, 353, 188, 179),
	array('British Antarctic Territory (West Coast)', 'Coast', 'No', 0, 458, 714, 229, 357),
	array('British Antarctic Territory (East Coast)', 'Coast', 'No', 0, 574, 728, 287, 364),
	array('France (North Coast)', 'Coast', 'No', 0, 668, 184, 338, 92),
	array('France (South Coast)', 'Coast', 'No', 0, 692, 208, 346, 104),
	array('Saint Petersburg (North Coast)', 'Coast', 'No', 0, 786, 100, 393, 50),
	array('Saint Petersburg (South Coast)', 'Coast', 'No', 0, 770, 132, 387, 65),
	array('Balkans (South Coast)', 'Coast', 'No', 0, 752, 218, 376, 109),
	array('Balkans (East Coast)', 'Coast', 'No', 0, 774, 202, 387, 101),
	array('Saudi Arabia (North Coast)', 'Coast', 'No', 0, 810, 258, 407, 130),
	array('Saudi Arabia (South Coast)', 'Coast', 'No', 0, 890, 320, 440, 156),
	array('Yakutsk (North Coast)', 'Coast', 'No', 0, 1092, 92, 546, 46),
	array('Yakutsk (South Coast)', 'Coast', 'No', 0, 1128, 140, 564, 70)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Baltic Sea','Skandanavia','Yes','No'),
	array('Baltic Sea','North Sea','Yes','No'),
	array('Baltic Sea','Germany','Yes','No'),
	array('Baltic Sea','Poland','Yes','No'),
	array('Baltic Sea','Baltic States','Yes','No'),
	array('Baltic Sea','Saint Petersburg (South Coast)','Yes','No'),
	array('Skandanavia','Barents Sea','Yes','No'),
	array('Skandanavia','Norwegian Sea','Yes','No'),
	array('Skandanavia','North Sea','Yes','No'),
	array('Skandanavia','Saint Petersburg','No','Yes'),
	array('Skandanavia','Saint Petersburg (North Coast)','Yes','No'),
	array('Skandanavia','Saint Petersburg (South Coast)','Yes','No'),
	array('Great Britain','Norwegian Sea','Yes','No'),
	array('Great Britain','Northeast Atlantic','Yes','No'),
	array('Great Britain','North Sea','Yes','No'),
	array('Arctic Circle','Beaufort Sea','Yes','No'),
	array('Arctic Circle','Barents Sea','Yes','No'),
	array('Arctic Circle','East Siberian Sea','Yes','No'),
	array('Arctic Circle','Alaska','Yes','No'),
	array('Arctic Circle','Bering Strait','Yes','No'),
	array('Arctic Circle','Kamchatka','Yes','No'),
	array('Arctic Circle','Yakutsk (North Coast)','Yes','No'),
	array('Beaufort Sea','Thule','Yes','No'),
	array('Beaufort Sea','Barents Sea','Yes','No'),
	array('Beaufort Sea','Labrador Sea','Yes','No'),
	array('Beaufort Sea','Hudson Bay','Yes','No'),
	array('Beaufort Sea','Baffin Island','Yes','No'),
	array('Beaufort Sea','Northwest Territories','Yes','No'),
	array('Beaufort Sea','Alaska','Yes','No'),
	array('Beaufort Sea','Yukon Territory (North Coast)','Yes','No'),
	array('Thule','Godthab','Yes','Yes'),
	array('Thule','Barents Sea','Yes','No'),
	array('Thule','Labrador Sea','Yes','No'),
	array('Godthab','Barents Sea','Yes','No'),
	array('Godthab','Norwegian Sea','Yes','No'),
	array('Godthab','Labrador Sea','Yes','No'),
	array('Barents Sea','East Siberian Sea','Yes','No'),
	array('Barents Sea','Norwegian Sea','Yes','No'),
	array('Barents Sea','West Siberia','Yes','No'),
	array('Barents Sea','Saint Petersburg (North Coast)','Yes','No'),
	array('East Siberian Sea','West Siberia','Yes','No'),
	array('East Siberian Sea','East Siberia','Yes','No'),
	array('East Siberian Sea','Yakutsk (North Coast)','Yes','No'),
	array('Norwegian Sea','Labrador Sea','Yes','No'),
	array('Norwegian Sea','Northeast Atlantic','Yes','No'),
	array('Norwegian Sea','North Sea','Yes','No'),
	array('Labrador Sea','Hudson Bay','Yes','No'),
	array('Labrador Sea','Baffin Island','Yes','No'),
	array('Labrador Sea','Newfoundland','Yes','No'),
	array('Labrador Sea','Northwest Atlantic','Yes','No'),
	array('Labrador Sea','Northeast Atlantic','Yes','No'),
	array('Hudson Bay','Baffin Island','Yes','No'),
	array('Hudson Bay','Newfoundland','Yes','No'),
	array('Hudson Bay','Ontario','Yes','No'),
	array('Hudson Bay','Manitoba','Yes','No'),
	array('Hudson Bay','Northwest Territories','Yes','No'),
	array('Hudson Bay','Quebec (North Coast)','Yes','No'),
	array('Newfoundland','Quebec','No','Yes'),
	array('Newfoundland','Northwest Atlantic','Yes','No'),
	array('Newfoundland','Quebec (North Coast)','Yes','No'),
	array('Newfoundland','Quebec (South Coast)','Yes','No'),
	array('Quebec','Ontario','No','Yes'),
	array('Quebec','Union','No','Yes'),
	array('Ontario','Manitoba','Yes','Yes'),
	array('Ontario','Midwest','No','Yes'),
	array('Ontario','Union','No','Yes'),
	array('Ontario','Quebec (North Coast)','Yes','No'),
	array('Manitoba','Saskatchewan','No','Yes'),
	array('Manitoba','Northwest Territories','Yes','Yes'),
	array('Manitoba','Midwest','No','Yes'),
	array('Saskatchewan','Alberta','No','Yes'),
	array('Saskatchewan','Northwest Territories','No','Yes'),
	array('Saskatchewan','Indian Territory','No','Yes'),
	array('Saskatchewan','Midwest','No','Yes'),
	array('Alberta','British Columbia','No','Yes'),
	array('Alberta','Northwest Territories','No','Yes'),
	array('Alberta','Indian Territory','No','Yes'),
	array('British Columbia','Northwest Territories','No','Yes'),
	array('British Columbia','Yukon Territory','No','Yes'),
	array('British Columbia','North Pacific Ocean','Yes','No'),
	array('British Columbia','Indian Territory','Yes','Yes'),
	array('British Columbia','Yukon Territory (South Coast)','Yes','No'),
	array('Northwest Territories','Yukon Territory','No','Yes'),
	array('Northwest Territories','Yukon Territory (North Coast)','Yes','No'),
	array('Yukon Territory','Alaska','No','Yes'),
	array('Alaska','Bering Strait','Yes','No'),
	array('Alaska','North Pacific Ocean','Yes','No'),
	array('Alaska','Yukon Territory (North Coast)','Yes','No'),
	array('Alaska','Yukon Territory (South Coast)','Yes','No'),
	array('Bering Strait','Northwest Pacific','Yes','No'),
	array('Bering Strait','North Pacific Ocean','Yes','No'),
	array('Bering Strait','Kamchatka','Yes','No'),
	array('Northwest Pacific','North Pacific Ocean','Yes','No'),
	array('Northwest Pacific','Central Pacific Ocean','Yes','No'),
	array('Northwest Pacific','West Pacific Ocean','Yes','No'),
	array('Northwest Pacific','Sea of Othoksk','Yes','No'),
	array('Northwest Pacific','Japan','Yes','No'),
	array('Northwest Pacific','Kamchatka','Yes','No'),
	array('North Pacific Ocean','Indian Territory','Yes','No'),
	array('North Pacific Ocean','California','Yes','No'),
	array('North Pacific Ocean','Central Pacific Ocean','Yes','No'),
	array('North Pacific Ocean','Northeast Pacific','Yes','No'),
	array('North Pacific Ocean','Yukon Territory (South Coast)','Yes','No'),
	array('North Pacific Ocean','Monterrey (West Coast)','Yes','No'),
	array('Indian Territory','Midwest','No','Yes'),
	array('Indian Territory','Nevada','No','Yes'),
	array('Indian Territory','California','Yes','Yes'),
	array('Midwest','Union','No','Yes'),
	array('Midwest','Deep South','No','Yes'),
	array('Midwest','Nevada','No','Yes'),
	array('Union','Florida','Yes','Yes'),
	array('Union','Deep South','No','Yes'),
	array('Union','Northwest Atlantic','Yes','No'),
	array('Union','Quebec (South Coast)','Yes','No'),
	array('Florida','Deep South','Yes','Yes'),
	array('Florida','Northwest Atlantic','Yes','No'),
	array('Florida','Gulf of Mexico','Yes','No'),
	array('Deep South','Texas','Yes','Yes'),
	array('Deep South','Nevada','No','Yes'),
	array('Deep South','Gulf of Mexico','Yes','No'),
	array('Texas','Nevada','No','Yes'),
	array('Texas','Gulf of Mexico','Yes','No'),
	array('Texas','Monterrey','No','Yes'),
	array('Texas','Monterrey (East Coast)','Yes','No'),
	array('Nevada','California','No','Yes'),
	array('Nevada','Monterrey','No','Yes'),
	array('California','Monterrey','No','Yes'),
	array('California','Monterrey (West Coast)','Yes','No'),
	array('Northwest Atlantic','Northeast Atlantic','Yes','No'),
	array('Northwest Atlantic','Gulf of Mexico','Yes','No'),
	array('Northwest Atlantic','Carribean Sea','Yes','No'),
	array('Northwest Atlantic','Venezuela','Yes','No'),
	array('Northwest Atlantic','Carribean Islands','Yes','No'),
	array('Northwest Atlantic','Guyana','Yes','No'),
	array('Northwest Atlantic','Recife','Yes','No'),
	array('Northwest Atlantic','West Atlantic Ocean','Yes','No'),
	array('Northwest Atlantic','Quebec (South Coast)','Yes','No'),
	array('Northeast Atlantic','West Atlantic Ocean','Yes','No'),
	array('Northeast Atlantic','East Atlantic Ocean','Yes','No'),
	array('Northeast Atlantic','North Sea','Yes','No'),
	array('Northeast Atlantic','Mediterranean','Yes','No'),
	array('Northeast Atlantic','Spain','Yes','No'),
	array('Northeast Atlantic','Morocco','Yes','No'),
	array('Northeast Atlantic','Algeria','Yes','No'),
	array('Northeast Atlantic','Mauritania','Yes','No'),
	array('Northeast Atlantic','France (North Coast)','Yes','No'),
	array('Gulf of Mexico','Carribean Sea','Yes','No'),
	array('Gulf of Mexico','Carribean Islands','Yes','No'),
	array('Gulf of Mexico','Monterrey (East Coast)','Yes','No'),
	array('Gulf of Mexico','Mexico (East Coast)','Yes','No'),
	array('Carribean Sea','Central America','Yes','No'),
	array('Carribean Sea','Venezuela','Yes','No'),
	array('Carribean Sea','Carribean Islands','Yes','No'),
	array('Carribean Sea','Mexico (East Coast)','Yes','No'),
	array('Carribean Sea','Colombia (North Coast)','Yes','No'),
	array('Monterrey','Mexico','No','Yes'),
	array('Mexico','Central America','No','Yes'),
	array('Central America','Colombia','No','Yes'),
	array('Central America','Northeast Pacific','Yes','No'),
	array('Central America','Mexico (West Coast)','Yes','No'),
	array('Central America','Mexico (East Coast)','Yes','No'),
	array('Central America','Colombia (West Coast)','Yes','No'),
	array('Central America','Colombia (North Coast)','Yes','No'),
	array('Colombia','Venezuela','No','Yes'),
	array('Colombia','Peru','No','Yes'),
	array('Colombia','Amazon','No','Yes'),
	array('Venezuela','Guyana','Yes','Yes'),
	array('Venezuela','Brasillia','No','Yes'),
	array('Venezuela','Amazon','No','Yes'),
	array('Venezuela','Colombia (North Coast)','Yes','No'),
	array('Central Pacific Ocean','Northeast Pacific','Yes','No'),
	array('Central Pacific Ocean','Pacific Islands','Yes','No'),
	array('Central Pacific Ocean','West Pacific Ocean','Yes','No'),
	array('Northeast Pacific','East Pacific','Yes','No'),
	array('Northeast Pacific','Pacific Islands','Yes','No'),
	array('Northeast Pacific','Peru','Yes','No'),
	array('Northeast Pacific','Monterrey (West Coast)','Yes','No'),
	array('Northeast Pacific','Mexico (West Coast)','Yes','No'),
	array('Northeast Pacific','Colombia (West Coast)','Yes','No'),
	array('South Pacific Ocean','East Pacific','Yes','No'),
	array('South Pacific Ocean','Pacific Islands','Yes','No'),
	array('South Pacific Ocean','Southeast Pacific','Yes','No'),
	array('South Pacific Ocean','Ross Ice Shelf','Yes','No'),
	array('South Pacific Ocean','Marie Byrd Land','Yes','No'),
	array('South Pacific Ocean','Southwest Pacific','Yes','No'),
	array('East Pacific','Pacific Islands','Yes','No'),
	array('East Pacific','Southeast Pacific','Yes','No'),
	array('East Pacific','Peru','Yes','No'),
	array('East Pacific','Chile','Yes','No'),
	array('Pacific Islands','Southwest Pacific','Yes','No'),
	array('Pacific Islands','Tasman Sea','Yes','No'),
	array('Pacific Islands','Java Sea','Yes','No'),
	array('Pacific Islands','West Pacific Ocean','Yes','No'),
	array('Pacific Islands','Queensland','Yes','No'),
	array('Pacific Islands','New Zealand','Yes','No'),
	array('Pacific Islands','Indonesia','Yes','No'),
	array('Southeast Pacific','Chile','Yes','No'),
	array('Southeast Pacific','Southwest Atlantic','Yes','No'),
	array('Southeast Pacific','Marie Byrd Land','Yes','No'),
	array('Southeast Pacific','Antarctic Penninsula','Yes','No'),
	array('Southeast Pacific','British Antarctic Territory (West Coast)','Yes','No'),
	array('Ross Ice Shelf','Marie Byrd Land','Yes','No'),
	array('Ross Ice Shelf','South Pole','No','Yes'),
	array('Ross Ice Shelf','Leningradskaya','Yes','Yes'),
	array('Ross Ice Shelf','Southwest Pacific','Yes','No'),
	array('Peru','Chile','Yes','Yes'),
	array('Peru','Amazon','No','Yes'),
	array('Peru','Bolivia','No','Yes'),
	array('Peru','Colombia (West Coast)','Yes','No'),
	array('Chile','Bolivia','No','Yes'),
	array('Chile','Mendoza','No','Yes'),
	array('Chile','Santa Cruz','Yes','Yes'),
	array('Chile','Southwest Atlantic','Yes','No'),
	array('Guyana','Recife','Yes','Yes'),
	array('Guyana','Brasillia','No','Yes'),
	array('Recife','Brasillia','No','Yes'),
	array('Recife','Salvador','Yes','Yes'),
	array('Recife','West Atlantic Ocean','Yes','No'),
	array('Brasillia','Amazon','No','Yes'),
	array('Brasillia','Bolivia','No','Yes'),
	array('Brasillia','Salvador','No','Yes'),
	array('Brasillia','Belo Horizonte','No','Yes'),
	array('Brasillia','Rio de Janeiro','No','Yes'),
	array('Brasillia','Sao Paulo','No','Yes'),
	array('Amazon','Bolivia','No','Yes'),
	array('Bolivia','Sao Paulo','No','Yes'),
	array('Bolivia','Mendoza','No','Yes'),
	array('Salvador','Belo Horizonte','No','Yes'),
	array('Salvador','Rio de Janeiro','Yes','Yes'),
	array('Salvador','West Atlantic Ocean','Yes','No'),
	array('Belo Horizonte','Rio de Janeiro','No','Yes'),
	array('Rio de Janeiro','Sao Paulo','Yes','Yes'),
	array('Rio de Janeiro','West Atlantic Ocean','Yes','No'),
	array('Sao Paulo','Uruguay','Yes','Yes'),
	array('Sao Paulo','Mendoza','No','Yes'),
	array('Sao Paulo','West Atlantic Ocean','Yes','No'),
	array('Uruguay','Buenos Aires','Yes','Yes'),
	array('Uruguay','Mendoza','No','Yes'),
	array('Uruguay','West Atlantic Ocean','Yes','No'),
	array('Buenos Aires','Mendoza','No','Yes'),
	array('Buenos Aires','Santa Cruz','Yes','Yes'),
	array('Buenos Aires','West Atlantic Ocean','Yes','No'),
	array('Buenos Aires','Southwest Atlantic','Yes','No'),
	array('Mendoza','Santa Cruz','No','Yes'),
	array('Santa Cruz','Southwest Atlantic','Yes','No'),
	array('West Atlantic Ocean','East Atlantic Ocean','Yes','No'),
	array('West Atlantic Ocean','Southwest Atlantic','Yes','No'),
	array('East Atlantic Ocean','Southwest Atlantic','Yes','No'),
	array('East Atlantic Ocean','Southeast Atlantic','Yes','No'),
	array('East Atlantic Ocean','Mauritania','Yes','No'),
	array('East Atlantic Ocean','Guinea','Yes','No'),
	array('East Atlantic Ocean','Ghana','Yes','No'),
	array('East Atlantic Ocean','Nigeria','Yes','No'),
	array('East Atlantic Ocean','Cameroon','Yes','No'),
	array('East Atlantic Ocean','Congo','Yes','No'),
	array('East Atlantic Ocean','South Africa','Yes','No'),
	array('East Atlantic Ocean','Namibia','Yes','No'),
	array('East Atlantic Ocean','Angola','Yes','No'),
	array('Southwest Atlantic','Southeast Atlantic','Yes','No'),
	array('Southwest Atlantic','Antarctic Penninsula','Yes','No'),
	array('Southwest Atlantic','Sanae IV','Yes','No'),
	array('Southwest Atlantic','British Antarctic Territory (East Coast)','Yes','No'),
	array('Southeast Atlantic','Sanae IV','Yes','No'),
	array('Southeast Atlantic','Novolazarevskaya','Yes','No'),
	array('Southeast Atlantic','Syowa','Yes','No'),
	array('Southeast Atlantic','Southwest Indian','Yes','No'),
	array('Southeast Atlantic','South Africa','Yes','No'),
	array('Marie Byrd Land','South Pole','No','Yes'),
	array('Marie Byrd Land','British Antarctic Territory','No','Yes'),
	array('Marie Byrd Land','British Antarctic Territory (West Coast)','Yes','No'),
	array('South Pole','Norwegian Dependency','No','Yes'),
	array('South Pole','British Antarctic Territory','No','Yes'),
	array('South Pole','Leningradskaya','No','Yes'),
	array('Norwegian Dependency','British Antarctic Territory','No','Yes'),
	array('Norwegian Dependency','Sanae IV','No','Yes'),
	array('Norwegian Dependency','Novolazarevskaya','No','Yes'),
	array('Norwegian Dependency','Syowa','No','Yes'),
	array('Norwegian Dependency','Mawson','No','Yes'),
	array('Norwegian Dependency','Vostok','No','Yes'),
	array('Norwegian Dependency','Dumont dUrville','No','Yes'),
	array('Norwegian Dependency','Leningradskaya','No','Yes'),
	array('British Antarctic Territory','Antarctic Penninsula','No','Yes'),
	array('British Antarctic Territory','Sanae IV','No','Yes'),
	array('Antarctic Penninsula','British Antarctic Territory (West Coast)','Yes','No'),
	array('Antarctic Penninsula','British Antarctic Territory (East Coast)','Yes','No'),
	array('Sanae IV','Novolazarevskaya','Yes','Yes'),
	array('Sanae IV','British Antarctic Territory (East Coast)','Yes','No'),
	array('Novolazarevskaya','Syowa','Yes','Yes'),
	array('Syowa','Mawson','Yes','Yes'),
	array('Syowa','Southwest Indian','Yes','No'),
	array('Mawson','Vostok','Yes','Yes'),
	array('Mawson','Southwest Indian','Yes','No'),
	array('Mawson','Southern Indian Ocean','Yes','No'),
	array('Vostok','Casey','Yes','Yes'),
	array('Vostok','Dumont dUrville','No','Yes'),
	array('Vostok','Southeast Indian','Yes','No'),
	array('Vostok','Southern Indian Ocean','Yes','No'),
	array('Casey','Dumont dUrville','Yes','Yes'),
	array('Casey','Southeast Indian','Yes','No'),
	array('Dumont dUrville','Leningradskaya','Yes','Yes'),
	array('Dumont dUrville','Southeast Indian','Yes','No'),
	array('Leningradskaya','Southeast Indian','Yes','No'),
	array('Leningradskaya','Southwest Pacific','Yes','No'),
	array('North Sea','Germany','Yes','No'),
	array('North Sea','France (North Coast)','Yes','No'),
	array('Mediterranean','Spain','Yes','No'),
	array('Mediterranean','Italy','Yes','No'),
	array('Mediterranean','Austria-Hungary','Yes','No'),
	array('Mediterranean','Turkey','Yes','No'),
	array('Mediterranean','Syria','Yes','No'),
	array('Mediterranean','Algeria','Yes','No'),
	array('Mediterranean','Libya','Yes','No'),
	array('Mediterranean','Egypt','Yes','No'),
	array('Mediterranean','France (South Coast)','Yes','No'),
	array('Mediterranean','Balkans (South Coast)','Yes','No'),
	array('Mediterranean','Saudi Arabia (North Coast)','Yes','No'),
	array('Southwest Indian','Southern Indian Ocean','Yes','No'),
	array('Southwest Indian','Northwest Indian','Yes','No'),
	array('Southwest Indian','Madagascar','Yes','No'),
	array('Southwest Indian','South Africa','Yes','No'),
	array('Southwest Indian','Mozambique Channel','Yes','No'),
	array('Southeast Indian','Southern Indian Ocean','Yes','No'),
	array('Southeast Indian','Northeast Indian','Yes','No'),
	array('Southeast Indian','Southwest Pacific','Yes','No'),
	array('Southeast Indian','Western Australia','Yes','No'),
	array('Southeast Indian','Victoria','Yes','No'),
	array('Southeast Indian','South Australia','Yes','No'),
	array('Southern Indian Ocean','Northwest Indian','Yes','No'),
	array('Southern Indian Ocean','Northeast Indian','Yes','No'),
	array('Northwest Indian','Northeast Indian','Yes','No'),
	array('Northwest Indian','Arabian Sea','Yes','No'),
	array('Northwest Indian','Bombay','Yes','No'),
	array('Northwest Indian','Somalia','Yes','No'),
	array('Northwest Indian','Kenya','Yes','No'),
	array('Northwest Indian','Tanzania','Yes','No'),
	array('Northwest Indian','Madagascar','Yes','No'),
	array('Northwest Indian','Mozambique Channel','Yes','No'),
	array('Northeast Indian','Java Sea','Yes','No'),
	array('Northeast Indian','Bay of Bengal','Yes','No'),
	array('Northeast Indian','South China Sea','Yes','No'),
	array('Northeast Indian','Thailand','Yes','No'),
	array('Northeast Indian','Bombay','Yes','No'),
	array('Northeast Indian','Western Australia','Yes','No'),
	array('Northeast Indian','Indonesia','Yes','No'),
	array('Arabian Sea','Red Sea','Yes','No'),
	array('Arabian Sea','Bombay','Yes','No'),
	array('Arabian Sea','Pakistan','Yes','No'),
	array('Arabian Sea','Iran','Yes','No'),
	array('Arabian Sea','Iraq','Yes','No'),
	array('Arabian Sea','Somalia','Yes','No'),
	array('Arabian Sea','Saudi Arabia (South Coast)','Yes','No'),
	array('Red Sea','Egypt','Yes','No'),
	array('Red Sea','North Sudan','Yes','No'),
	array('Red Sea','Ethiopia','Yes','No'),
	array('Red Sea','Somalia','Yes','No'),
	array('Red Sea','Saudi Arabia (South Coast)','Yes','No'),
	array('Southwest Pacific','Tasman Sea','Yes','No'),
	array('Southwest Pacific','Victoria','Yes','No'),
	array('Southwest Pacific','New Zealand','Yes','No'),
	array('Tasman Sea','Queensland','Yes','No'),
	array('Tasman Sea','New South Wales','Yes','No'),
	array('Tasman Sea','Victoria','Yes','No'),
	array('Tasman Sea','New Zealand','Yes','No'),
	array('Java Sea','Western Australia','Yes','No'),
	array('Java Sea','Northern Territory','Yes','No'),
	array('Java Sea','Queensland','Yes','No'),
	array('Java Sea','Indonesia','Yes','No'),
	array('Bay of Bengal','Thailand','Yes','No'),
	array('Bay of Bengal','Burma','Yes','No'),
	array('Bay of Bengal','Bangladesh','Yes','No'),
	array('Bay of Bengal','Calcutta','Yes','No'),
	array('Bay of Bengal','Bombay','Yes','No'),
	array('South China Sea','West Pacific Ocean','Yes','No'),
	array('South China Sea','Yellow Sea','Yes','No'),
	array('South China Sea','Guangzhou','Yes','No'),
	array('South China Sea','Vietnam','Yes','No'),
	array('South China Sea','Thailand','Yes','No'),
	array('South China Sea','Indonesia','Yes','No'),
	array('South China Sea','Phillipines','Yes','No'),
	array('West Pacific Ocean','Yellow Sea','Yes','No'),
	array('West Pacific Ocean','Japan','Yes','No'),
	array('West Pacific Ocean','Indonesia','Yes','No'),
	array('West Pacific Ocean','Phillipines','Yes','No'),
	array('Yellow Sea','Sea of Japan','Yes','No'),
	array('Yellow Sea','Japan','Yes','No'),
	array('Yellow Sea','Beijing','Yes','No'),
	array('Yellow Sea','Korea','Yes','No'),
	array('Yellow Sea','Shanghai','Yes','No'),
	array('Yellow Sea','Guangzhou','Yes','No'),
	array('Yellow Sea','Phillipines','Yes','No'),
	array('Sea of Japan','Sea of Othoksk','Yes','No'),
	array('Sea of Japan','Japan','Yes','No'),
	array('Sea of Japan','Vladivostok','Yes','No'),
	array('Sea of Japan','Korea','Yes','No'),
	array('Sea of Othoksk','Japan','Yes','No'),
	array('Sea of Othoksk','Kamchatka','Yes','No'),
	array('Sea of Othoksk','Vladivostok','Yes','No'),
	array('Sea of Othoksk','Yakutsk (South Coast)','Yes','No'),
	array('Spain','France','No','Yes'),
	array('Spain','France (North Coast)','Yes','No'),
	array('Spain','France (South Coast)','Yes','No'),
	array('France','Germany','No','Yes'),
	array('France','Italy','No','Yes'),
	array('Germany','Italy','No','Yes'),
	array('Germany','Austria-Hungary','No','Yes'),
	array('Germany','Poland','Yes','Yes'),
	array('Germany','France (North Coast)','Yes','No'),
	array('Italy','Austria-Hungary','Yes','Yes'),
	array('Italy','France (South Coast)','Yes','No'),
	array('Austria-Hungary','Poland','No','Yes'),
	array('Austria-Hungary','Ukraine','No','Yes'),
	array('Austria-Hungary','Balkans','No','Yes'),
	array('Austria-Hungary','Balkans (South Coast)','Yes','No'),
	array('Poland','Baltic States','Yes','Yes'),
	array('Poland','Belorussia','No','Yes'),
	array('Poland','Ukraine','No','Yes'),
	array('Baltic States','Saint Petersburg','No','Yes'),
	array('Baltic States','Belorussia','No','Yes'),
	array('Baltic States','Saint Petersburg (South Coast)','Yes','No'),
	array('Saint Petersburg','Belorussia','No','Yes'),
	array('Saint Petersburg','Moscow','No','Yes'),
	array('Saint Petersburg','West Siberia','No','Yes'),
	array('Belorussia','Ukraine','No','Yes'),
	array('Belorussia','Moscow','No','Yes'),
	array('Ukraine','Black Sea','Yes','No'),
	array('Ukraine','Balkans','No','Yes'),
	array('Ukraine','Moscow','Yes','Yes'),
	array('Ukraine','Balkans (East Coast)','Yes','No'),
	array('Black Sea','Moscow','Yes','No'),
	array('Black Sea','Armenia','Yes','No'),
	array('Black Sea','Turkey','Yes','No'),
	array('Black Sea','Balkans (East Coast)','Yes','No'),
	array('Balkans','Turkey','No','Yes'),
	array('Moscow','West Siberia','No','Yes'),
	array('Moscow','Kazakhstan','No','Yes'),
	array('Moscow','Armenia','Yes','Yes'),
	array('West Siberia','East Siberia','Yes','Yes'),
	array('West Siberia','Kazakhstan','No','Yes'),
	array('West Siberia','Omsk','No','Yes'),
	array('West Siberia','Saint Petersburg (North Coast)','Yes','No'),
	array('East Siberia','Yakutsk','No','Yes'),
	array('East Siberia','Omsk','No','Yes'),
	array('East Siberia','Irkutsk','No','Yes'),
	array('East Siberia','Yakutsk (North Coast)','Yes','No'),
	array('Yakutsk','Kamchatka','No','Yes'),
	array('Yakutsk','Irkutsk','No','Yes'),
	array('Yakutsk','Vladivostok','No','Yes'),
	array('Kamchatka','Yakutsk (North Coast)','Yes','No'),
	array('Kamchatka','Yakutsk (South Coast)','Yes','No'),
	array('Kazakhstan','Omsk','No','Yes'),
	array('Kazakhstan','Mongolia','No','Yes'),
	array('Kazakhstan','Western China','No','Yes'),
	array('Kazakhstan','Kyrgyzstan','No','Yes'),
	array('Kazakhstan','Turkmenistan','No','Yes'),
	array('Kazakhstan','Uzbekistan','No','Yes'),
	array('Omsk','Irkutsk','No','Yes'),
	array('Omsk','Mongolia','No','Yes'),
	array('Irkutsk','Mongolia','No','Yes'),
	array('Irkutsk','Inner Mongolia','No','Yes'),
	array('Irkutsk','Vladivostok','No','Yes'),
	array('Mongolia','Inner Mongolia','No','Yes'),
	array('Mongolia','Western China','No','Yes'),
	array('Inner Mongolia','Western China','No','Yes'),
	array('Inner Mongolia','Beijing','No','Yes'),
	array('Inner Mongolia','Vladivostok','No','Yes'),
	array('Inner Mongolia','Heilongjiang','No','Yes'),
	array('Inner Mongolia','Lanzhou','No','Yes'),
	array('Western China','Lanzhou','No','Yes'),
	array('Western China','Tibet','No','Yes'),
	array('Western China','Delhi','No','Yes'),
	array('Western China','Pakistan','No','Yes'),
	array('Western China','Afghanistan','No','Yes'),
	array('Western China','Tajikistan','No','Yes'),
	array('Western China','Kyrgyzstan','No','Yes'),
	array('Beijing','Heilongjiang','No','Yes'),
	array('Beijing','Korea','Yes','Yes'),
	array('Beijing','Shanghai','Yes','Yes'),
	array('Beijing','Lanzhou','No','Yes'),
	array('Vladivostok','Heilongjiang','No','Yes'),
	array('Vladivostok','Korea','Yes','Yes'),
	array('Vladivostok','Yakutsk (South Coast)','Yes','No'),
	array('Heilongjiang','Korea','No','Yes'),
	array('Shanghai','Guangzhou','Yes','Yes'),
	array('Shanghai','Lanzhou','No','Yes'),
	array('Guangzhou','Vietnam','Yes','Yes'),
	array('Guangzhou','Lanzhou','No','Yes'),
	array('Vietnam','Thailand','Yes','Yes'),
	array('Vietnam','Burma','No','Yes'),
	array('Vietnam','Lanzhou','No','Yes'),
	array('Thailand','Burma','Yes','Yes'),
	array('Burma','Bangladesh','Yes','Yes'),
	array('Burma','Lanzhou','No','Yes'),
	array('Bangladesh','Lanzhou','No','Yes'),
	array('Bangladesh','Calcutta','Yes','Yes'),
	array('Lanzhou','Tibet','No','Yes'),
	array('Lanzhou','Calcutta','No','Yes'),
	array('Tibet','Calcutta','No','Yes'),
	array('Tibet','Delhi','No','Yes'),
	array('Calcutta','Bombay','Yes','Yes'),
	array('Calcutta','Delhi','No','Yes'),
	array('Bombay','Delhi','No','Yes'),
	array('Bombay','Pakistan','Yes','Yes'),
	array('Delhi','Pakistan','No','Yes'),
	array('Pakistan','Afghanistan','No','Yes'),
	array('Pakistan','Iran','Yes','Yes'),
	array('Afghanistan','Tajikistan','No','Yes'),
	array('Afghanistan','Iran','No','Yes'),
	array('Afghanistan','Turkmenistan','No','Yes'),
	array('Afghanistan','Uzbekistan','No','Yes'),
	array('Tajikistan','Kyrgyzstan','No','Yes'),
	array('Tajikistan','Uzbekistan','No','Yes'),
	array('Kyrgyzstan','Uzbekistan','No','Yes'),
	array('Iran','Turkmenistan','No','Yes'),
	array('Iran','Armenia','No','Yes'),
	array('Iran','Turkey','No','Yes'),
	array('Iran','Iraq','Yes','Yes'),
	array('Turkmenistan','Uzbekistan','No','Yes'),
	array('Armenia','Turkey','Yes','Yes'),
	array('Turkey','Syria','Yes','Yes'),
	array('Turkey','Iraq','No','Yes'),
	array('Turkey','Balkans (South Coast)','Yes','No'),
	array('Turkey','Balkans (East Coast)','Yes','No'),
	array('Syria','Iraq','No','Yes'),
	array('Syria','Saudi Arabia','No','Yes'),
	array('Syria','Saudi Arabia (North Coast)','Yes','No'),
	array('Iraq','Saudi Arabia','No','Yes'),
	array('Iraq','Saudi Arabia (South Coast)','Yes','No'),
	array('Saudi Arabia','Egypt','No','Yes'),
	array('Western Australia','Northern Territory','Yes','Yes'),
	array('Western Australia','South Australia','Yes','Yes'),
	array('Northern Territory','Queensland','Yes','Yes'),
	array('Northern Territory','South Australia','No','Yes'),
	array('Queensland','New South Wales','Yes','Yes'),
	array('Queensland','South Australia','No','Yes'),
	array('New South Wales','Victoria','Yes','Yes'),
	array('New South Wales','South Australia','No','Yes'),
	array('Victoria','South Australia','Yes','Yes'),
	array('Morocco','Algeria','Yes','Yes'),
	array('Morocco','Mauritania','Yes','Yes'),
	array('Algeria','Libya','Yes','Yes'),
	array('Algeria','Mauritania','No','Yes'),
	array('Algeria','Mali','No','Yes'),
	array('Algeria','Niger','No','Yes'),
	array('Libya','Egypt','Yes','Yes'),
	array('Libya','North Sudan','No','Yes'),
	array('Libya','Niger','No','Yes'),
	array('Libya','Chad','No','Yes'),
	array('Egypt','North Sudan','Yes','Yes'),
	array('Egypt','Saudi Arabia (North Coast)','Yes','No'),
	array('Egypt','Saudi Arabia (South Coast)','Yes','No'),
	array('North Sudan','Ethiopia','Yes','Yes'),
	array('North Sudan','Chad','No','Yes'),
	array('North Sudan','South Sudan','No','Yes'),
	array('Ethiopia','Somalia','Yes','Yes'),
	array('Ethiopia','South Sudan','No','Yes'),
	array('Ethiopia','Kenya','No','Yes'),
	array('Somalia','Kenya','Yes','Yes'),
	array('Mauritania','Mali','No','Yes'),
	array('Mauritania','Guinea','Yes','Yes'),
	array('Mali','Niger','No','Yes'),
	array('Mali','Guinea','No','Yes'),
	array('Mali','Ghana','No','Yes'),
	array('Niger','Chad','No','Yes'),
	array('Niger','Ghana','No','Yes'),
	array('Niger','Nigeria','No','Yes'),
	array('Chad','South Sudan','No','Yes'),
	array('Chad','Nigeria','No','Yes'),
	array('Chad','Cameroon','No','Yes'),
	array('Chad','Central African Republic','No','Yes'),
	array('South Sudan','Central African Republic','No','Yes'),
	array('South Sudan','Zaire','No','Yes'),
	array('South Sudan','Uganda','No','Yes'),
	array('South Sudan','Kenya','No','Yes'),
	array('Guinea','Ghana','Yes','Yes'),
	array('Ghana','Nigeria','Yes','Yes'),
	array('Nigeria','Cameroon','Yes','Yes'),
	array('Cameroon','Central African Republic','No','Yes'),
	array('Cameroon','Congo','Yes','Yes'),
	array('Central African Republic','Congo','No','Yes'),
	array('Central African Republic','Zaire','No','Yes'),
	array('Congo','Zaire','No','Yes'),
	array('Congo','Angola','Yes','Yes'),
	array('Zaire','Uganda','No','Yes'),
	array('Zaire','Tanzania','No','Yes'),
	array('Zaire','Angola','No','Yes'),
	array('Zaire','Zambia','No','Yes'),
	array('Uganda','Kenya','No','Yes'),
	array('Uganda','Tanzania','No','Yes'),
	array('Kenya','Tanzania','Yes','Yes'),
	array('Tanzania','Mozambique','Yes','Yes'),
	array('Tanzania','Zambia','No','Yes'),
	array('Tanzania','Mozambique Channel','Yes','No'),
	array('Madagascar','Mozambique Channel','Yes','No'),
	array('Mozambique','South Africa','Yes','Yes'),
	array('Mozambique','Zimbabwe','No','Yes'),
	array('Mozambique','Zambia','No','Yes'),
	array('Mozambique','Mozambique Channel','Yes','No'),
	array('South Africa','Zimbabwe','No','Yes'),
	array('South Africa','Botswana','No','Yes'),
	array('South Africa','Namibia','Yes','Yes'),
	array('South Africa','Mozambique Channel','Yes','No'),
	array('Zimbabwe','Botswana','No','Yes'),
	array('Zimbabwe','Namibia','No','Yes'),
	array('Zimbabwe','Zambia','No','Yes'),
	array('Botswana','Namibia','No','Yes'),
	array('Namibia','Angola','Yes','Yes'),
	array('Namibia','Zambia','No','Yes'),
	array('Angola','Zambia','No','Yes'),
	array('Monterrey (West Coast)','Mexico (West Coast)','Yes','No'),
	array('Monterrey (East Coast)','Mexico (East Coast)','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
