<?php
// This is file installs the map data for the Modern2 variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Adana', 'Coast', 'Yes', 940, 626, 494, 389, 'Turkey'),
	array('Adriatic Sea', 'Sea', 'No', 572, 594, 280, 329, 'Neutral'),
	array('Aegean Sea', 'Sea', 'No', 726, 684, 383, 401, 'Neutral'),
	array('Albania', 'Coast', 'No', 616, 602, 322, 361, 'Neutral'),
	array('Alexandria', 'Coast', 'Yes', 792, 816, 438, 485, 'Egypt'),
	array('Algeria', 'Coast', 'No', 272, 700, 138, 423, 'Neutral'),
	array('Alsace', 'Land', 'No', 384, 434, 205, 258, 'France'),
	array('Anatolia', 'Coast', 'No', 872, 666, 461, 409, 'Turkey'),
	array('Andalucia', 'Coast', 'No', 204, 622, 87, 380, 'Spain'),
	array('Ankara', 'Coast', 'Yes', 962, 570, 471, 348, 'Turkey'),
	array('Apulia', 'Coast', 'No', 528, 598, 284, 354, 'Italy'),
	array('Arabian Sea', 'Sea', 'No', 1242, 1034, 692, 532, 'Neutral'),
	array('Arctic Ocean', 'Sea', 'No', 138, 18, 157, 12, 'Neutral'),
	array('Armenia', 'Land', 'No', 1044, 554, 567, 333, 'Neutral'),
	array('Aswan', 'Coast', 'Yes', 922, 942, 501, 542, 'Egypt'),
	array('Austria', 'Land', 'Yes', 522, 446, 280, 275, 'Neutral'),
	array('Auvergne', 'Coast', 'No', 302, 528, 159, 314, 'France'),
	array('Azerbaijan', 'Coast', 'No', 1114, 562, 612, 322, 'Neutral'),
	array('Baltic Sea', 'Sea', 'No', 614, 314, 319, 168, 'Neutral'),
	array('Barcelona', 'Coast', 'Yes', 218, 588, 116, 349, 'Spain'),
	array('Barents Sea', 'Sea', 'No', 720, 18, 310, 11, 'Neutral'),
	array('Bay of Biscay', 'Sea', 'No', 204, 476, 105, 277, 'Neutral'),
	array('Belgium', 'Coast', 'Yes', 356, 352, 198, 227, 'Neutral'),
	array('Berlin', 'Coast', 'Yes', 512, 348, 268, 197, 'Germany'),
	array('Bhm. Sea', 'Sea', 'No', 552, 305, 291, 178, 'Neutral'),
	array('Bielorussia', 'Land', 'Yes', 726, 372, 397, 186, 'Neutral'),
	array('Bordeaux', 'Coast', 'Yes', 244, 504, 140, 285, 'France'),
	array('Bosnia', 'Land', 'No', 584, 546, 309, 317, 'Neutral'),
	array('Brittany', 'Coast', 'No', 268, 424, 142, 260, 'France'),
	array('Bulgaria', 'Coast', 'Yes', 752, 546, 381, 347, 'Neutral'),
	array('Cairo', 'Coast', 'Yes', 864, 836, 475, 488, 'Egypt'),
	array('Caspian Sea', 'Sea', 'No', 1154, 524, 591, 266, 'Neutral'),
	array('Caucasus', 'Coast', 'No', 1052, 484, 589, 300, 'Russia'),
	array('Central Russian Plateau', 'Land', 'No', 798, 353, 441, 189, 'Russia'),
	array('Clyde', 'Coast', 'No', 288, 216, 145, 121, 'Britain'),
	array('Croatia', 'Coast', 'Yes', 538, 530, 279, 304, 'Neutral'),
	array('Czech Republic', 'Land', 'Yes', 522, 424, 276, 244, 'Neutral'),
	array('Denmark', 'Coast', 'Yes', 488, 268, 256, 146, 'Neutral'),
	array('Donetsk', 'Coast', 'No', 888, 452, 489, 256, 'Ukraine'),
	array('Eastern Black Sea', 'Sea', 'No', 902, 530, 483, 305, 'Neutral'),
	array('Eastern Mediterranean', 'Sea', 'No', 832, 752, 420, 434, 'Neutral'),
	array('Eastern Sahara', 'Coast', 'No', 730, 804, 359, 471, 'Egypt'),
	array('Edinburgh', 'Coast', 'Yes', 326, 204, 159, 134, 'Britain'),
	array('English Channel', 'Sea', 'No', 264, 366, 93, 226, 'Neutral'),
	array('Estonia', 'Coast', 'No', 680, 246, 358, 127, 'Neutral'),
	array('Finland', 'Coast', 'No', 662, 198, 365, 76, 'Neutral'),
	array('Frankfurt', 'Land', 'Yes', 458, 386, 247, 221, 'Germany'),
	array('Gdansk', 'Coast', 'Yes', 614, 346, 329, 181, 'Poland'),
	array('Georgia', 'Coast', 'Yes', 992, 534, 540, 314, 'Neutral'),
	array('Gibraltar', 'Coast', 'Yes', 134, 622, 55, 385, 'Britain'),
	array('Gorky', 'Land', 'Yes', 920, 224, 493, 123, 'Russia'),
	array('Greece', 'Coast', 'Yes', 658, 662, 350, 397, 'Neutral'),
	array('Gulf of Bothnia', 'Sea', 'No', 622, 236, 339, 131, 'Neutral'),
	array('Gulf of Lyon', 'Sea', 'No', 330, 558, 166, 344, 'Neutral'),
	array('Hamburg', 'Coast', 'Yes', 456, 332, 247, 187, 'Germany'),
	array('Heligoland Bight', 'Sea', 'No', 427, 307, 226, 170, 'Neutral'),
	array('Holland', 'Coast', 'Yes', 424, 334, 202, 208, 'Neutral'),
	array('Hungary', 'Land', 'Yes', 618, 468, 322, 277, 'Neutral'),
	array('Iceland', 'Coast', 'No', 278, 52, 125, 33, 'Neutral'),
	array('Ionian Sea', 'Sea', 'No', 600, 670, 319, 407, 'Neutral'),
	array('Iran', 'Coast', 'Yes', 1166, 702, 636, 393, 'Neutral'),
	array('Iran (North Coast)', 'Coast', 'No', 1148, 600, 651, 354, 'Neutral'),
	array('Iran (South Coast)', 'Coast', 'No', 1200, 808, 677, 452, 'Neutral'),
	array('Iraq', 'Coast', 'No', 1088, 772, 583, 407, 'Neutral'),
	array('Ireland', 'Coast', 'Yes', 222, 274, 96, 165, 'Neutral'),
	array('Irish Sea', 'Sea', 'No', 228, 310, 111, 187, 'Neutral'),
	array('Israel', 'Coast', 'Yes', 930, 764, 506, 432, 'Neutral'),
	array('Istanbul', 'Coast', 'Yes', 770, 598, 432, 365, 'Turkey'),
	array('Izmir', 'Coast', 'Yes', 808, 674, 425, 416, 'Turkey'),
	array('Jordan', 'Coast', 'No', 952, 792, 523, 452, 'Neutral'),
	array('Kazakhstan', 'Land', 'No', 1192, 456, 655, 212, 'Neutral'),
	array('Kharkov', 'Land', 'Yes', 868, 400, 471, 240, 'Ukraine'),
	array('Kiev', 'Land', 'Yes', 832, 418, 447, 243, 'Ukraine'),
	array('Krakow', 'Land', 'Yes', 642, 414, 349, 231, 'Poland'),
	array('Lapland', 'Coast', 'No', 574, 68, 321, 24, 'Neutral'),
	array('Latvia', 'Coast', 'No', 648, 294, 345, 150, 'Neutral'),
	array('Libya', 'Coast', 'Yes', 504, 822, 285, 488, 'Neutral'),
	array('Libyan Sea', 'Sea', 'No', 690, 754, 396, 457, 'Neutral'),
	array('Ligurian Sea', 'Sea', 'No', 428, 573, 216, 331, 'Neutral'),
	array('Lithuania', 'Coast', 'Yes', 648, 326, 349, 167, 'Neutral'),
	array('Liverpool', 'Coast', 'Yes', 300, 244, 149, 152, 'Britain'),
	array('London', 'Coast', 'Yes', 344, 312, 169, 204, 'Britain'),
	array('Lyon', 'Land', 'Yes', 340, 476, 175, 280, 'France'),
	array('Macedonia', 'Land', 'No', 652, 594, 345, 350, 'Neutral'),
	array('Madrid', 'Land', 'Yes', 160, 568, 86, 345, 'Spain'),
	array('Maltese Sea', 'Sea', 'No', 524, 722, 249, 428, 'Neutral'),
	array('Marseilles', 'Coast', 'Yes', 364, 496, 181, 306, 'France'),
	array('Mid-Atlantic Ocean', 'Sea', 'No', 76, 436, 27, 253, 'Neutral'),
	array('Milan', 'Land', 'Yes', 452, 512, 237, 304, 'Italy'),
	array('Moldavia', 'Land', 'No', 767, 460, 407, 277, 'Neutral'),
	array('Monaco', 'Coast', 'Yes', 371, 533, 200, 319, 'Neutral'),
	array('Morocco', 'Coast', 'Yes', 134, 676, 47, 412, 'Neutral'),
	array('Moscow', 'Land', 'Yes', 796, 304, 413, 147, 'Russia'),
	array('Munich', 'Land', 'Yes', 448, 412, 224, 257, 'Germany'),
	array('Murmansk', 'Coast', 'Yes', 806, 128, 395, 63, 'Russia'),
	array('Naples', 'Coast', 'Yes', 526, 676, 291, 386, 'Italy'),
	array('Navarra', 'Coast', 'No', 152, 502, 70, 293, 'Spain'),
	array('North Atlantic Ocean', 'Sea', 'No', 148, 186, 67, 115, 'Neutral'),
	array('North Sea', 'Sea', 'No', 388, 264, 198, 165, 'Neutral'),
	array('Norway', 'Coast', 'Yes', 476, 186, 245, 109, 'Neutral'),
	array('Norwegian Sea', 'Sea', 'No', 366, 112, 209, 64, 'Neutral'),
	array('Odessa', 'Coast', 'Yes', 820, 456, 426, 267, 'Ukraine'),
	array('Paris', 'Land', 'Yes', 314, 442, 160, 262, 'France'),
	array('Persian Gulf', 'Sea', 'No', 1162, 816, 629, 452, 'Neutral'),
	array('Picardy', 'Coast', 'No', 336, 372, 165, 230, 'France'),
	array('Piedmont', 'Coast', 'No', 402, 512, 219, 309, 'Italy'),
	array('Podolia', 'Land', 'No', 698, 408, 381, 235, 'Ukraine'),
	array('Portugal', 'Coast', 'Yes', 94, 582, 40, 336, 'Neutral'),
	array('Prussia', 'Coast', 'No', 570, 346, 309, 191, 'Poland'),
	array('Red Sea', 'Sea', 'No', 958, 916, 519, 507, 'Neutral'),
	array('Rome', 'Coast', 'Yes', 470, 570, 260, 352, 'Italy'),
	array('Rostov', 'Coast', 'Yes', 962, 458, 511, 274, 'Russia'),
	array('Ruhr', 'Land', 'No', 414, 386, 217, 232, 'Germany'),
	array('Rumania', 'Coast', 'Yes', 750, 506, 376, 299, 'Neutral'),
	array('Saudi Arabia', 'Coast', 'Yes', 1168, 986, 587, 491, 'Neutral'),
	array('Saxony', 'Land', 'No', 476, 406, 251, 245, 'Germany'),
	array('Sea of Gibraltar', 'Sea', 'No', 206, 652, 87, 397, 'Neutral'),
	array('Serbia', 'Coast', 'Yes', 612, 566, 335, 322, 'Neutral'),
	array('Sevastopol', 'Coast', 'Yes', 882, 490, 458, 282, 'Ukraine'),
	array('Seville', 'Coast', 'Yes', 142, 600, 62, 347, 'Spain'),
	array('Siberia', 'Land', 'No', 1160, 190, 656, 61, 'Russia'),
	array('Silecia', 'Land', 'No', 562, 393, 301, 221, 'Poland'),
	array('Sinai Peninsula', 'Coast', 'No', 914, 838, 499, 470, 'Egypt'),
	array('Skagerrak', 'Sea', 'No', 512, 260, 239, 138, 'Neutral'),
	array('Slovakia', 'Land', 'No', 576, 436, 329, 260, 'Neutral'),
	array('South Atlantic Ocean', 'Sea', 'No', 36, 594, 15, 361, 'Neutral'),
	array('St. Petersburg', 'Coast', 'Yes', 734, 240, 412, 106, 'Russia'),
	array('Sweden', 'Coast', 'Yes', 558, 190, 300, 125, 'Neutral'),
	array('Switzerland', 'Land', 'Yes', 414, 454, 223, 272, 'Neutral'),
	array('Syria', 'Coast', 'No', 952, 698, 507, 411, 'Neutral'),
	array('Tunisia', 'Coast', 'Yes', 394, 710, 209, 430, 'Neutral'),
	array('Tuscany', 'Coast', 'No', 449, 545, 241, 326, 'Italy'),
	array('Tyrrhenian Sea', 'Sea', 'No', 446, 618, 239, 368, 'Neutral'),
	array('Urals', 'Coast', 'No', 932, 64, 516, 39, 'Russia'),
	array('Venice', 'Coast', 'Yes', 488, 550, 263, 326, 'Italy'),
	array('Volga', 'Coast', 'No', 1024, 390, 535, 219, 'Russia'),
	array('Wales', 'Coast', 'No', 282, 328, 142, 201, 'Britain'),
	array('Warsaw', 'Land', 'Yes', 604, 392, 324, 210, 'Poland'),
	array('Western Black Sea', 'Sea', 'No', 820, 554, 429, 336, 'Neutral'),
	array('Western Mediterranean', 'Sea', 'No', 332, 620, 120, 387, 'Neutral'),
	array('Western Sahara', 'Land', 'No', 176, 844, 75, 517, 'Neutral'),
	array('White Sea', 'Sea', 'No', 830, 68, 427, 53, 'Neutral'),
	array('Yorkshire', 'Coast', 'No', 336, 270, 166, 177, 'Britain')
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $x, $y, $sx, $sy, $country)=$territoryRawRow;
	if( $country=='Neutral' )
		$countryID=0;
	else
		$countryID=$this->countryID($country);
		
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);
$bordersRawData=array(
	array('Adana','Anatolia','Yes','Yes'),
	array('Adana','Ankara','No','Yes'),
	array('Adana','Armenia','No','Yes'),
	array('Adana','Eastern Mediterranean','Yes','No'),
	array('Adana','Iran','No','Yes'),
	array('Adana','Iraq','No','Yes'),
	array('Adana','Syria','Yes','Yes'),
	array('Adriatic Sea','Albania','Yes','No'),
	array('Adriatic Sea','Apulia','Yes','No'),
	array('Adriatic Sea','Croatia','Yes','No'),
	array('Adriatic Sea','Ionian Sea','Yes','No'),
	array('Adriatic Sea','Serbia','Yes','No'),
	array('Adriatic Sea','Venice','Yes','No'),
	array('Aegean Sea','Eastern Mediterranean','Yes','No'),
	array('Aegean Sea','Greece','Yes','No'),
	array('Aegean Sea','Ionian Sea','Yes','No'),
	array('Aegean Sea','Istanbul','Yes','No'),
	array('Aegean Sea','Izmir','Yes','No'),
	array('Albania','Adriatic Sea','Yes','No'),
	array('Albania','Greece','Yes','Yes'),
	array('Albania','Ionian Sea','Yes','No'),
	array('Albania','Macedonia','No','Yes'),
	array('Albania','Serbia','Yes','Yes'),
	array('Alexandria','Aswan','No','Yes'),
	array('Alexandria','Cairo','Yes','Yes'),
	array('Alexandria','Eastern Mediterranean','Yes','No'),
	array('Alexandria','Eastern Sahara','Yes','Yes'),
	array('Alexandria','Libyan Sea','Yes','No'),
	array('Algeria','Libya','No','Yes'),
	array('Algeria','Morocco','Yes','Yes'),
	array('Algeria','Sea of Gibraltar','Yes','No'),
	array('Algeria','Tunisia','Yes','Yes'),
	array('Algeria','Western Mediterranean','Yes','No'),
	array('Algeria','Western Sahara','No','Yes'),
	array('Alsace','Belgium','No','Yes'),
	array('Alsace','Lyon','No','Yes'),
	array('Alsace','Munich','No','Yes'),
	array('Alsace','Paris','No','Yes'),
	array('Alsace','Picardy','No','Yes'),
	array('Alsace','Ruhr','No','Yes'),
	array('Alsace','Switzerland','No','Yes'),
	array('Anatolia','Adana','Yes','Yes'),
	array('Anatolia','Ankara','No','Yes'),
	array('Anatolia','Eastern Mediterranean','Yes','No'),
	array('Anatolia','Izmir','Yes','Yes'),
	array('Andalucia','Barcelona','Yes','Yes'),
	array('Andalucia','Gibraltar','Yes','Yes'),
	array('Andalucia','Madrid','No','Yes'),
	array('Andalucia','Sea of Gibraltar','Yes','No'),
	array('Andalucia','Seville','No','Yes'),
	array('Andalucia','Western Mediterranean','Yes','No'),
	array('Ankara','Adana','No','Yes'),
	array('Ankara','Anatolia','No','Yes'),
	array('Ankara','Armenia','No','Yes'),
	array('Ankara','Eastern Black Sea','Yes','No'),
	array('Ankara','Georgia','Yes','Yes'),
	array('Ankara','Istanbul','Yes','Yes'),
	array('Ankara','Izmir','No','Yes'),
	array('Ankara','Western Black Sea','Yes','No'),
	array('Apulia','Adriatic Sea','Yes','No'),
	array('Apulia','Ionian Sea','Yes','No'),
	array('Apulia','Naples','Yes','Yes'),
	array('Apulia','Rome','No','Yes'),
	array('Apulia','Venice','Yes','Yes'),
	array('Arabian Sea','Iran (South Coast)','Yes','No'),
	array('Arabian Sea','Persian Gulf','Yes','No'),
	array('Arabian Sea','Red Sea','Yes','No'),
	array('Arabian Sea','Saudi Arabia','Yes','No'),
	array('Arctic Ocean','Barents Sea','Yes','No'),
	array('Arctic Ocean','Iceland','Yes','No'),
	array('Arctic Ocean','North Atlantic Ocean','Yes','No'),
	array('Arctic Ocean','Norwegian Sea','Yes','No'),
	array('Armenia','Adana','No','Yes'),
	array('Armenia','Ankara','No','Yes'),
	array('Armenia','Azerbaijan','No','Yes'),
	array('Armenia','Georgia','No','Yes'),
	array('Armenia','Iran','No','Yes'),
	array('Aswan','Alexandria','No','Yes'),
	array('Aswan','Cairo','Yes','Yes'),
	array('Aswan','Eastern Sahara','No','Yes'),
	array('Aswan','Red Sea','Yes','No'),
	array('Austria','Croatia','No','Yes'),
	array('Austria','Czech Republic','No','Yes'),
	array('Austria','Hungary','No','Yes'),
	array('Austria','Milan','No','Yes'),
	array('Austria','Munich','No','Yes'),
	array('Austria','Saxony','No','Yes'),
	array('Austria','Slovakia','No','Yes'),
	array('Austria','Switzerland','No','Yes'),
	array('Austria','Venice','No','Yes'),
	array('Auvergne','Barcelona','Yes','Yes'),
	array('Auvergne','Bordeaux','No','Yes'),
	array('Auvergne','Gulf of Lyon','Yes','No'),
	array('Auvergne','Lyon','No','Yes'),
	array('Auvergne','Marseilles','Yes','Yes'),
	array('Auvergne','Navarra','No','Yes'),
	array('Auvergne','Paris','No','Yes'),
	array('Azerbaijan','Armenia','No','Yes'),
	array('Azerbaijan','Caspian Sea','Yes','No'),
	array('Azerbaijan','Caucasus','Yes','Yes'),
	array('Azerbaijan','Georgia','No','Yes'),
	array('Azerbaijan','Iran','No','Yes'),
	array('Azerbaijan','Iran (North Coast)','Yes','No'),
	array('Baltic Sea','Bhm. Sea','Yes','No'),
	array('Baltic Sea','Gdansk','Yes','No'),
	array('Baltic Sea','Gulf of Bothnia','Yes','No'),
	array('Baltic Sea','Latvia','Yes','No'),
	array('Baltic Sea','Lithuania','Yes','No'),
	array('Baltic Sea','Prussia','Yes','No'),
	array('Baltic Sea','Sweden','Yes','No'),
	array('Barcelona','Andalucia','Yes','Yes'),
	array('Barcelona','Auvergne','Yes','Yes'),
	array('Barcelona','Gulf of Lyon','Yes','No'),
	array('Barcelona','Madrid','No','Yes'),
	array('Barcelona','Navarra','No','Yes'),
	array('Barcelona','Western Mediterranean','Yes','No'),
	array('Barents Sea','Arctic Ocean','Yes','No'),
	array('Barents Sea','Lapland','Yes','No'),
	array('Barents Sea','Murmansk','Yes','No'),
	array('Barents Sea','Norwegian Sea','Yes','No'),
	array('Barents Sea','Urals','Yes','No'),
	array('Barents Sea','White Sea','Yes','No'),
	array('Bay of Biscay','Bordeaux','Yes','No'),
	array('Bay of Biscay','Brittany','Yes','No'),
	array('Bay of Biscay','English Channel','Yes','No'),
	array('Bay of Biscay','Mid-Atlantic Ocean','Yes','No'),
	array('Bay of Biscay','Navarra','Yes','No'),
	array('Belgium','Alsace','No','Yes'),
	array('Belgium','English Channel','Yes','No'),
	array('Belgium','Holland','Yes','Yes'),
	array('Belgium','North Sea','Yes','No'),
	array('Belgium','Picardy','Yes','Yes'),
	array('Belgium','Ruhr','No','Yes'),
	array('Berlin','Bhm. Sea','Yes','No'),
	array('Berlin','Frankfurt','No','Yes'),
	array('Berlin','Hamburg','Yes','Yes'),
	array('Berlin','Prussia','Yes','Yes'),
	array('Berlin','Saxony','No','Yes'),
	array('Berlin','Silecia','No','Yes'),
	array('Bhm. Sea','Baltic Sea','Yes','No'),
	array('Bhm. Sea','Berlin','Yes','No'),
	array('Bhm. Sea','Denmark','Yes','No'),
	array('Bhm. Sea','Hamburg','Yes','No'),
	array('Bhm. Sea','Prussia','Yes','No'),
	array('Bhm. Sea','Sweden','Yes','No'),
	array('Bielorussia','Central Russian Plateau','No','Yes'),
	array('Bielorussia','Kiev','No','Yes'),
	array('Bielorussia','Krakow','No','Yes'),
	array('Bielorussia','Latvia','No','Yes'),
	array('Bielorussia','Lithuania','No','Yes'),
	array('Bielorussia','Moscow','No','Yes'),
	array('Bielorussia','Podolia','No','Yes'),
	array('Bielorussia','Warsaw','No','Yes'),
	array('Bordeaux','Auvergne','No','Yes'),
	array('Bordeaux','Bay of Biscay','Yes','No'),
	array('Bordeaux','Brittany','Yes','Yes'),
	array('Bordeaux','Navarra','Yes','Yes'),
	array('Bordeaux','Paris','No','Yes'),
	array('Bosnia','Croatia','No','Yes'),
	array('Bosnia','Serbia','No','Yes'),
	array('Brittany','Bay of Biscay','Yes','No'),
	array('Brittany','Bordeaux','Yes','Yes'),
	array('Brittany','English Channel','Yes','No'),
	array('Brittany','Paris','No','Yes'),
	array('Brittany','Picardy','Yes','Yes'),
	array('Bulgaria','Greece','No','Yes'),
	array('Bulgaria','Istanbul','Yes','Yes'),
	array('Bulgaria','Macedonia','No','Yes'),
	array('Bulgaria','Rumania','Yes','Yes'),
	array('Bulgaria','Serbia','No','Yes'),
	array('Bulgaria','Western Black Sea','Yes','No'),
	array('Cairo','Alexandria','Yes','Yes'),
	array('Cairo','Aswan','Yes','Yes'),
	array('Cairo','Eastern Mediterranean','Yes','No'),
	array('Cairo','Israel','Yes','Yes'),
	array('Cairo','Red Sea','Yes','No'),
	array('Cairo','Sinai Peninsula','Yes','Yes'),
	array('Caspian Sea','Azerbaijan','Yes','No'),
	array('Caspian Sea','Caucasus','Yes','No'),
	array('Caspian Sea','Iran (North Coast)','Yes','No'),
	array('Caspian Sea','Kazakhstan','Yes','No'),
	array('Caspian Sea','Volga','Yes','No'),
	array('Caucasus','Azerbaijan','Yes','Yes'),
	array('Caucasus','Caspian Sea','Yes','No'),
	array('Caucasus','Georgia','No','Yes'),
	array('Caucasus','Rostov','No','Yes'),
	array('Caucasus','Volga','Yes','Yes'),
	array('Central Russian Plateau','Bielorussia','No','Yes'),
	array('Central Russian Plateau','Kharkov','No','Yes'),
	array('Central Russian Plateau','Kiev','No','Yes'),
	array('Central Russian Plateau','Moscow','No','Yes'),
	array('Central Russian Plateau','Volga','No','Yes'),
	array('Clyde','Edinburgh','Yes','Yes'),
	array('Clyde','Liverpool','Yes','Yes'),
	array('Clyde','North Atlantic Ocean','Yes','No'),
	array('Clyde','Norwegian Sea','Yes','No'),
	array('Croatia','Adriatic Sea','Yes','No'),
	array('Croatia','Austria','No','Yes'),
	array('Croatia','Bosnia','No','Yes'),
	array('Croatia','Hungary','No','Yes'),
	array('Croatia','Serbia','Yes','Yes'),
	array('Croatia','Venice','Yes','Yes'),
	array('Czech Republic','Austria','No','Yes'),
	array('Czech Republic','Krakow','No','Yes'),
	array('Czech Republic','Saxony','No','Yes'),
	array('Czech Republic','Silecia','No','Yes'),
	array('Czech Republic','Slovakia','No','Yes'),
	array('Denmark','Bhm. Sea','Yes','No'),
	array('Denmark','Hamburg','Yes','Yes'),
	array('Denmark','Heligoland Bight','Yes','No'),
	array('Denmark','North Sea','Yes','No'),
	array('Denmark','Skagerrak','Yes','No'),
	array('Denmark','Sweden','Yes','Yes'),
	array('Donetsk','Eastern Black Sea','Yes','No'),
	array('Donetsk','Kharkov','No','Yes'),
	array('Donetsk','Kiev','No','Yes'),
	array('Donetsk','Rostov','Yes','Yes'),
	array('Donetsk','Sevastopol','Yes','Yes'),
	array('Donetsk','Volga','No','Yes'),
	array('Eastern Black Sea','Ankara','Yes','No'),
	array('Eastern Black Sea','Donetsk','Yes','No'),
	array('Eastern Black Sea','Georgia','Yes','No'),
	array('Eastern Black Sea','Rostov','Yes','No'),
	array('Eastern Black Sea','Sevastopol','Yes','No'),
	array('Eastern Black Sea','Western Black Sea','Yes','No'),
	array('Eastern Mediterranean','Adana','Yes','No'),
	array('Eastern Mediterranean','Aegean Sea','Yes','No'),
	array('Eastern Mediterranean','Alexandria','Yes','No'),
	array('Eastern Mediterranean','Anatolia','Yes','No'),
	array('Eastern Mediterranean','Cairo','Yes','No'),
	array('Eastern Mediterranean','Ionian Sea','Yes','No'),
	array('Eastern Mediterranean','Israel','Yes','No'),
	array('Eastern Mediterranean','Izmir','Yes','No'),
	array('Eastern Mediterranean','Libyan Sea','Yes','No'),
	array('Eastern Mediterranean','Syria','Yes','No'),
	array('Eastern Sahara','Alexandria','Yes','Yes'),
	array('Eastern Sahara','Aswan','No','Yes'),
	array('Eastern Sahara','Libya','Yes','Yes'),
	array('Eastern Sahara','Libyan Sea','Yes','No'),
	array('Edinburgh','Clyde','Yes','Yes'),
	array('Edinburgh','Liverpool','No','Yes'),
	array('Edinburgh','North Sea','Yes','No'),
	array('Edinburgh','Norwegian Sea','Yes','No'),
	array('Edinburgh','Yorkshire','Yes','Yes'),
	array('English Channel','Bay of Biscay','Yes','No'),
	array('English Channel','Belgium','Yes','No'),
	array('English Channel','Brittany','Yes','No'),
	array('English Channel','Irish Sea','Yes','No'),
	array('English Channel','London','Yes','No'),
	array('English Channel','Mid-Atlantic Ocean','Yes','No'),
	array('English Channel','North Sea','Yes','No'),
	array('English Channel','Picardy','Yes','No'),
	array('English Channel','Wales','Yes','No'),
	array('Estonia','Gulf of Bothnia','Yes','No'),
	array('Estonia','Latvia','Yes','Yes'),
	array('Estonia','St. Petersburg','Yes','Yes'),
	array('Finland','Gulf of Bothnia','Yes','No'),
	array('Finland','Lapland','No','Yes'),
	array('Finland','Murmansk','No','Yes'),
	array('Finland','St. Petersburg','Yes','Yes'),
	array('Finland','Sweden','Yes','Yes'),
	array('Frankfurt','Berlin','No','Yes'),
	array('Frankfurt','Hamburg','No','Yes'),
	array('Frankfurt','Munich','No','Yes'),
	array('Frankfurt','Ruhr','No','Yes'),
	array('Frankfurt','Saxony','No','Yes'),
	array('Gdansk','Baltic Sea','Yes','No'),
	array('Gdansk','Lithuania','Yes','Yes'),
	array('Gdansk','Prussia','Yes','Yes'),
	array('Gdansk','Warsaw','No','Yes'),
	array('Georgia','Ankara','Yes','Yes'),
	array('Georgia','Armenia','No','Yes'),
	array('Georgia','Azerbaijan','No','Yes'),
	array('Georgia','Caucasus','No','Yes'),
	array('Georgia','Eastern Black Sea','Yes','No'),
	array('Georgia','Rostov','Yes','Yes'),
	array('Gibraltar','Andalucia','Yes','Yes'),
	array('Gibraltar','Sea of Gibraltar','Yes','No'),
	array('Gibraltar','Seville','Yes','Yes'),
	array('Gibraltar','South Atlantic Ocean','Yes','No'),
	array('Gorky','Moscow','No','Yes'),
	array('Gorky','Murmansk','No','Yes'),
	array('Gorky','St. Petersburg','No','Yes'),
	array('Gorky','Urals','No','Yes'),
	array('Gorky','Volga','No','Yes'),
	array('Greece','Aegean Sea','Yes','No'),
	array('Greece','Albania','Yes','Yes'),
	array('Greece','Bulgaria','No','Yes'),
	array('Greece','Ionian Sea','Yes','No'),
	array('Greece','Istanbul','Yes','Yes'),
	array('Greece','Macedonia','No','Yes'),
	array('Gulf of Bothnia','Baltic Sea','Yes','No'),
	array('Gulf of Bothnia','Estonia','Yes','No'),
	array('Gulf of Bothnia','Finland','Yes','No'),
	array('Gulf of Bothnia','Latvia','Yes','No'),
	array('Gulf of Bothnia','St. Petersburg','Yes','No'),
	array('Gulf of Bothnia','Sweden','Yes','No'),
	array('Gulf of Lyon','Auvergne','Yes','No'),
	array('Gulf of Lyon','Barcelona','Yes','No'),
	array('Gulf of Lyon','Ligurian Sea','Yes','No'),
	array('Gulf of Lyon','Marseilles','Yes','No'),
	array('Gulf of Lyon','Tyrrhenian Sea','Yes','No'),
	array('Gulf of Lyon','Western Mediterranean','Yes','No'),
	array('Hamburg','Berlin','Yes','Yes'),
	array('Hamburg','Bhm. Sea','Yes','No'),
	array('Hamburg','Denmark','Yes','Yes'),
	array('Hamburg','Frankfurt','No','Yes'),
	array('Hamburg','Heligoland Bight','Yes','No'),
	array('Hamburg','Holland','Yes','Yes'),
	array('Hamburg','Ruhr','No','Yes'),
	array('Heligoland Bight','Denmark','Yes','No'),
	array('Heligoland Bight','Hamburg','Yes','No'),
	array('Heligoland Bight','Holland','Yes','No'),
	array('Heligoland Bight','North Sea','Yes','No'),
	array('Holland','Belgium','Yes','Yes'),
	array('Holland','Hamburg','Yes','Yes'),
	array('Holland','Heligoland Bight','Yes','No'),
	array('Holland','North Sea','Yes','No'),
	array('Holland','Ruhr','No','Yes'),
	array('Hungary','Austria','No','Yes'),
	array('Hungary','Croatia','No','Yes'),
	array('Hungary','Podolia','No','Yes'),
	array('Hungary','Rumania','No','Yes'),
	array('Hungary','Serbia','No','Yes'),
	array('Hungary','Slovakia','No','Yes'),
	array('Iceland','Arctic Ocean','Yes','No'),
	array('Iceland','North Atlantic Ocean','Yes','No'),
	array('Iceland','Norwegian Sea','Yes','No'),
	array('Ionian Sea','Adriatic Sea','Yes','No'),
	array('Ionian Sea','Aegean Sea','Yes','No'),
	array('Ionian Sea','Albania','Yes','No'),
	array('Ionian Sea','Apulia','Yes','No'),
	array('Ionian Sea','Eastern Mediterranean','Yes','No'),
	array('Ionian Sea','Greece','Yes','No'),
	array('Ionian Sea','Libyan Sea','Yes','No'),
	array('Ionian Sea','Maltese Sea','Yes','No'),
	array('Ionian Sea','Naples','Yes','No'),
	array('Iran','Adana','No','Yes'),
	array('Iran','Armenia','No','Yes'),
	array('Iran','Azerbaijan','No','Yes'),
	array('Iran','Iraq','No','Yes'),
	array('Iran','Kazakhstan','No','Yes'),
	array('Iran (North Coast)','Azerbaijan','Yes','No'),
	array('Iran (North Coast)','Caspian Sea','Yes','No'),
	array('Iran (North Coast)','Kazakhstan','Yes','No'),
	array('Iran (South Coast)','Arabian Sea','Yes','No'),
	array('Iran (South Coast)','Iraq','Yes','No'),
	array('Iran (South Coast)','Persian Gulf','Yes','No'),
	array('Iraq','Adana','No','Yes'),
	array('Iraq','Iran','No','Yes'),
	array('Iraq','Iran (South Coast)','Yes','No'),
	array('Iraq','Jordan','No','Yes'),
	array('Iraq','Persian Gulf','Yes','No'),
	array('Iraq','Saudi Arabia','Yes','Yes'),
	array('Iraq','Syria','No','Yes'),
	array('Ireland','Irish Sea','Yes','No'),
	array('Ireland','North Atlantic Ocean','Yes','No'),
	array('Irish Sea','English Channel','Yes','No'),
	array('Irish Sea','Ireland','Yes','No'),
	array('Irish Sea','Liverpool','Yes','No'),
	array('Irish Sea','Mid-Atlantic Ocean','Yes','No'),
	array('Irish Sea','North Atlantic Ocean','Yes','No'),
	array('Irish Sea','Wales','Yes','No'),
	array('Israel','Cairo','Yes','Yes'),
	array('Israel','Eastern Mediterranean','Yes','No'),
	array('Israel','Jordan','Yes','Yes'),
	array('Israel','Sinai Peninsula','No','Yes'),
	array('Israel','Syria','Yes','Yes'),
	array('Istanbul','Aegean Sea','Yes','No'),
	array('Istanbul','Ankara','Yes','Yes'),
	array('Istanbul','Bulgaria','Yes','Yes'),
	array('Istanbul','Greece','Yes','Yes'),
	array('Istanbul','Izmir','Yes','Yes'),
	array('Istanbul','Western Black Sea','Yes','No'),
	array('Izmir','Aegean Sea','Yes','No'),
	array('Izmir','Anatolia','Yes','Yes'),
	array('Izmir','Ankara','No','Yes'),
	array('Izmir','Eastern Mediterranean','Yes','No'),
	array('Izmir','Istanbul','Yes','Yes'),
	array('Jordan','Iraq','No','Yes'),
	array('Jordan','Israel','Yes','Yes'),
	array('Jordan','Red Sea','Yes','No'),
	array('Jordan','Saudi Arabia','Yes','Yes'),
	array('Jordan','Sinai Peninsula','Yes','Yes'),
	array('Jordan','Syria','No','Yes'),
	array('Kazakhstan','Caspian Sea','Yes','No'),
	array('Kazakhstan','Iran','No','Yes'),
	array('Kazakhstan','Iran (North Coast)','Yes','No'),
	array('Kazakhstan','Siberia','No','Yes'),
	array('Kazakhstan','Volga','Yes','Yes'),
	array('Kharkov','Central Russian Plateau','No','Yes'),
	array('Kharkov','Donetsk','No','Yes'),
	array('Kharkov','Kiev','No','Yes'),
	array('Kharkov','Volga','No','Yes'),
	array('Kiev','Bielorussia','No','Yes'),
	array('Kiev','Central Russian Plateau','No','Yes'),
	array('Kiev','Donetsk','No','Yes'),
	array('Kiev','Kharkov','No','Yes'),
	array('Kiev','Odessa','No','Yes'),
	array('Kiev','Podolia','No','Yes'),
	array('Kiev','Sevastopol','No','Yes'),
	array('Krakow','Bielorussia','No','Yes'),
	array('Krakow','Czech Republic','No','Yes'),
	array('Krakow','Podolia','No','Yes'),
	array('Krakow','Silecia','No','Yes'),
	array('Krakow','Slovakia','No','Yes'),
	array('Krakow','Warsaw','No','Yes'),
	array('Lapland','Barents Sea','Yes','No'),
	array('Lapland','Finland','No','Yes'),
	array('Lapland','Murmansk','Yes','Yes'),
	array('Lapland','Norway','Yes','Yes'),
	array('Lapland','Norwegian Sea','Yes','No'),
	array('Lapland','Sweden','No','Yes'),
	array('Latvia','Baltic Sea','Yes','No'),
	array('Latvia','Bielorussia','No','Yes'),
	array('Latvia','Estonia','Yes','Yes'),
	array('Latvia','Gulf of Bothnia','Yes','No'),
	array('Latvia','Lithuania','Yes','Yes'),
	array('Latvia','Moscow','No','Yes'),
	array('Latvia','St. Petersburg','No','Yes'),
	array('Libya','Algeria','No','Yes'),
	array('Libya','Eastern Sahara','Yes','Yes'),
	array('Libya','Libyan Sea','Yes','No'),
	array('Libya','Maltese Sea','Yes','No'),
	array('Libya','Tunisia','Yes','Yes'),
	array('Libya','Western Sahara','No','Yes'),
	array('Libyan Sea','Alexandria','Yes','No'),
	array('Libyan Sea','Eastern Mediterranean','Yes','No'),
	array('Libyan Sea','Eastern Sahara','Yes','No'),
	array('Libyan Sea','Ionian Sea','Yes','No'),
	array('Libyan Sea','Libya','Yes','No'),
	array('Libyan Sea','Maltese Sea','Yes','No'),
	array('Ligurian Sea','Gulf of Lyon','Yes','No'),
	array('Ligurian Sea','Marseilles','Yes','No'),
	array('Ligurian Sea','Monaco','Yes','No'),
	array('Ligurian Sea','Piedmont','Yes','No'),
	array('Ligurian Sea','Rome','Yes','No'),
	array('Ligurian Sea','Tuscany','Yes','No'),
	array('Ligurian Sea','Tyrrhenian Sea','Yes','No'),
	array('Lithuania','Baltic Sea','Yes','No'),
	array('Lithuania','Bielorussia','No','Yes'),
	array('Lithuania','Gdansk','Yes','Yes'),
	array('Lithuania','Latvia','Yes','Yes'),
	array('Lithuania','Warsaw','No','Yes'),
	array('Liverpool','Clyde','Yes','Yes'),
	array('Liverpool','Edinburgh','No','Yes'),
	array('Liverpool','Irish Sea','Yes','No'),
	array('Liverpool','North Atlantic Ocean','Yes','No'),
	array('Liverpool','Wales','Yes','Yes'),
	array('Liverpool','Yorkshire','No','Yes'),
	array('London','English Channel','Yes','No'),
	array('London','North Sea','Yes','No'),
	array('London','Wales','Yes','Yes'),
	array('London','Yorkshire','Yes','Yes'),
	array('Lyon','Alsace','No','Yes'),
	array('Lyon','Auvergne','No','Yes'),
	array('Lyon','Marseilles','No','Yes'),
	array('Lyon','Paris','No','Yes'),
	array('Lyon','Switzerland','No','Yes'),
	array('Macedonia','Albania','No','Yes'),
	array('Macedonia','Bulgaria','No','Yes'),
	array('Macedonia','Greece','No','Yes'),
	array('Macedonia','Serbia','No','Yes'),
	array('Madrid','Andalucia','No','Yes'),
	array('Madrid','Barcelona','No','Yes'),
	array('Madrid','Navarra','No','Yes'),
	array('Madrid','Portugal','No','Yes'),
	array('Madrid','Seville','No','Yes'),
	array('Maltese Sea','Ionian Sea','Yes','No'),
	array('Maltese Sea','Libya','Yes','No'),
	array('Maltese Sea','Libyan Sea','Yes','No'),
	array('Maltese Sea','Naples','Yes','No'),
	array('Maltese Sea','Tunisia','Yes','No'),
	array('Maltese Sea','Tyrrhenian Sea','Yes','No'),
	array('Marseilles','Auvergne','Yes','Yes'),
	array('Marseilles','Gulf of Lyon','Yes','No'),
	array('Marseilles','Ligurian Sea','Yes','No'),
	array('Marseilles','Lyon','No','Yes'),
	array('Marseilles','Monaco','Yes','Yes'),
	array('Marseilles','Piedmont','No','Yes'),
	array('Marseilles','Switzerland','No','Yes'),
	array('Mid-Atlantic Ocean','Bay of Biscay','Yes','No'),
	array('Mid-Atlantic Ocean','English Channel','Yes','No'),
	array('Mid-Atlantic Ocean','Irish Sea','Yes','No'),
	array('Mid-Atlantic Ocean','Navarra','Yes','No'),
	array('Mid-Atlantic Ocean','North Atlantic Ocean','Yes','No'),
	array('Mid-Atlantic Ocean','Portugal','Yes','No'),
	array('Mid-Atlantic Ocean','South Atlantic Ocean','Yes','No'),
	array('Milan','Austria','No','Yes'),
	array('Milan','Piedmont','No','Yes'),
	array('Milan','Switzerland','No','Yes'),
	array('Milan','Tuscany','No','Yes'),
	array('Milan','Venice','No','Yes'),
	array('Moldavia','Odessa','No','Yes'),
	array('Moldavia','Podolia','No','Yes'),
	array('Moldavia','Rumania','No','Yes'),
	array('Monaco','Ligurian Sea','Yes','No'),
	array('Monaco','Marseilles','Yes','Yes'),
	array('Monaco','Piedmont','Yes','Yes'),
	array('Morocco','Algeria','Yes','Yes'),
	array('Morocco','Sea of Gibraltar','Yes','No'),
	array('Morocco','South Atlantic Ocean','Yes','No'),
	array('Morocco','Western Sahara','No','Yes'),
	array('Moscow','Bielorussia','No','Yes'),
	array('Moscow','Central Russian Plateau','No','Yes'),
	array('Moscow','Gorky','No','Yes'),
	array('Moscow','Latvia','No','Yes'),
	array('Moscow','St. Petersburg','No','Yes'),
	array('Moscow','Volga','No','Yes'),
	array('Munich','Alsace','No','Yes'),
	array('Munich','Austria','No','Yes'),
	array('Munich','Frankfurt','No','Yes'),
	array('Munich','Ruhr','No','Yes'),
	array('Munich','Saxony','No','Yes'),
	array('Munich','Switzerland','No','Yes'),
	array('Murmansk','Barents Sea','Yes','No'),
	array('Murmansk','Finland','No','Yes'),
	array('Murmansk','Gorky','No','Yes'),
	array('Murmansk','Lapland','Yes','Yes'),
	array('Murmansk','St. Petersburg','No','Yes'),
	array('Murmansk','Urals','Yes','Yes'),
	array('Murmansk','White Sea','Yes','No'),
	array('Naples','Apulia','Yes','Yes'),
	array('Naples','Ionian Sea','Yes','No'),
	array('Naples','Maltese Sea','Yes','No'),
	array('Naples','Rome','Yes','Yes'),
	array('Naples','Tyrrhenian Sea','Yes','No'),
	array('Navarra','Auvergne','No','Yes'),
	array('Navarra','Barcelona','No','Yes'),
	array('Navarra','Bay of Biscay','Yes','No'),
	array('Navarra','Bordeaux','Yes','Yes'),
	array('Navarra','Madrid','No','Yes'),
	array('Navarra','Mid-Atlantic Ocean','Yes','No'),
	array('Navarra','Portugal','Yes','Yes'),
	array('North Atlantic Ocean','Arctic Ocean','Yes','No'),
	array('North Atlantic Ocean','Clyde','Yes','No'),
	array('North Atlantic Ocean','Iceland','Yes','No'),
	array('North Atlantic Ocean','Ireland','Yes','No'),
	array('North Atlantic Ocean','Irish Sea','Yes','No'),
	array('North Atlantic Ocean','Liverpool','Yes','No'),
	array('North Atlantic Ocean','Mid-Atlantic Ocean','Yes','No'),
	array('North Atlantic Ocean','Norwegian Sea','Yes','No'),
	array('North Sea','Belgium','Yes','No'),
	array('North Sea','Denmark','Yes','No'),
	array('North Sea','Edinburgh','Yes','No'),
	array('North Sea','English Channel','Yes','No'),
	array('North Sea','Heligoland Bight','Yes','No'),
	array('North Sea','Holland','Yes','No'),
	array('North Sea','London','Yes','No'),
	array('North Sea','Norway','Yes','No'),
	array('North Sea','Norwegian Sea','Yes','No'),
	array('North Sea','Skagerrak','Yes','No'),
	array('North Sea','Yorkshire','Yes','No'),
	array('Norway','Lapland','Yes','Yes'),
	array('Norway','North Sea','Yes','No'),
	array('Norway','Norwegian Sea','Yes','No'),
	array('Norway','Skagerrak','Yes','No'),
	array('Norway','Sweden','Yes','Yes'),
	array('Norwegian Sea','Arctic Ocean','Yes','No'),
	array('Norwegian Sea','Barents Sea','Yes','No'),
	array('Norwegian Sea','Clyde','Yes','No'),
	array('Norwegian Sea','Edinburgh','Yes','No'),
	array('Norwegian Sea','Iceland','Yes','No'),
	array('Norwegian Sea','Lapland','Yes','No'),
	array('Norwegian Sea','North Atlantic Ocean','Yes','No'),
	array('Norwegian Sea','North Sea','Yes','No'),
	array('Norwegian Sea','Norway','Yes','No'),
	array('Odessa','Kiev','No','Yes'),
	array('Odessa','Moldavia','No','Yes'),
	array('Odessa','Podolia','No','Yes'),
	array('Odessa','Rumania','Yes','Yes'),
	array('Odessa','Sevastopol','Yes','Yes'),
	array('Odessa','Western Black Sea','Yes','No'),
	array('Paris','Alsace','No','Yes'),
	array('Paris','Auvergne','No','Yes'),
	array('Paris','Bordeaux','No','Yes'),
	array('Paris','Brittany','No','Yes'),
	array('Paris','Lyon','No','Yes'),
	array('Paris','Picardy','No','Yes'),
	array('Persian Gulf','Arabian Sea','Yes','No'),
	array('Persian Gulf','Iran (South Coast)','Yes','No'),
	array('Persian Gulf','Iraq','Yes','No'),
	array('Persian Gulf','Saudi Arabia','Yes','No'),
	array('Picardy','Alsace','No','Yes'),
	array('Picardy','Belgium','Yes','Yes'),
	array('Picardy','Brittany','Yes','Yes'),
	array('Picardy','English Channel','Yes','No'),
	array('Picardy','Paris','No','Yes'),
	array('Piedmont','Ligurian Sea','Yes','No'),
	array('Piedmont','Marseilles','No','Yes'),
	array('Piedmont','Milan','No','Yes'),
	array('Piedmont','Monaco','Yes','Yes'),
	array('Piedmont','Switzerland','No','Yes'),
	array('Piedmont','Tuscany','Yes','Yes'),
	array('Podolia','Bielorussia','No','Yes'),
	array('Podolia','Hungary','No','Yes'),
	array('Podolia','Kiev','No','Yes'),
	array('Podolia','Krakow','No','Yes'),
	array('Podolia','Moldavia','No','Yes'),
	array('Podolia','Odessa','No','Yes'),
	array('Podolia','Rumania','No','Yes'),
	array('Podolia','Slovakia','No','Yes'),
	array('Portugal','Madrid','No','Yes'),
	array('Portugal','Mid-Atlantic Ocean','Yes','No'),
	array('Portugal','Navarra','Yes','Yes'),
	array('Portugal','Seville','Yes','Yes'),
	array('Portugal','South Atlantic Ocean','Yes','No'),
	array('Prussia','Baltic Sea','Yes','No'),
	array('Prussia','Berlin','Yes','Yes'),
	array('Prussia','Bhm. Sea','Yes','No'),
	array('Prussia','Gdansk','Yes','Yes'),
	array('Prussia','Silecia','No','Yes'),
	array('Prussia','Warsaw','No','Yes'),
	array('Red Sea','Arabian Sea','Yes','No'),
	array('Red Sea','Aswan','Yes','No'),
	array('Red Sea','Cairo','Yes','No'),
	array('Red Sea','Jordan','Yes','No'),
	array('Red Sea','Saudi Arabia','Yes','No'),
	array('Red Sea','Sinai Peninsula','Yes','No'),
	array('Rome','Apulia','No','Yes'),
	array('Rome','Ligurian Sea','Yes','No'),
	array('Rome','Naples','Yes','Yes'),
	array('Rome','Tuscany','Yes','Yes'),
	array('Rome','Tyrrhenian Sea','Yes','No'),
	array('Rome','Venice','No','Yes'),
	array('Rostov','Caucasus','No','Yes'),
	array('Rostov','Donetsk','Yes','Yes'),
	array('Rostov','Eastern Black Sea','Yes','No'),
	array('Rostov','Georgia','Yes','Yes'),
	array('Rostov','Volga','Yes','Yes'),
	array('Ruhr','Alsace','No','Yes'),
	array('Ruhr','Belgium','No','Yes'),
	array('Ruhr','Frankfurt','No','Yes'),
	array('Ruhr','Hamburg','No','Yes'),
	array('Ruhr','Holland','No','Yes'),
	array('Ruhr','Munich','No','Yes'),
	array('Rumania','Bulgaria','Yes','Yes'),
	array('Rumania','Hungary','No','Yes'),
	array('Rumania','Moldavia','No','Yes'),
	array('Rumania','Odessa','Yes','Yes'),
	array('Rumania','Podolia','No','Yes'),
	array('Rumania','Serbia','No','Yes'),
	array('Rumania','Western Black Sea','Yes','No'),
	array('Saudi Arabia','Arabian Sea','Yes','No'),
	array('Saudi Arabia','Iraq','Yes','Yes'),
	array('Saudi Arabia','Jordan','Yes','Yes'),
	array('Saudi Arabia','Persian Gulf','Yes','No'),
	array('Saudi Arabia','Red Sea','Yes','No'),
	array('Saxony','Austria','No','Yes'),
	array('Saxony','Berlin','No','Yes'),
	array('Saxony','Czech Republic','No','Yes'),
	array('Saxony','Frankfurt','No','Yes'),
	array('Saxony','Munich','No','Yes'),
	array('Saxony','Silecia','No','Yes'),
	array('Sea of Gibraltar','Algeria','Yes','No'),
	array('Sea of Gibraltar','Andalucia','Yes','No'),
	array('Sea of Gibraltar','Gibraltar','Yes','No'),
	array('Sea of Gibraltar','Morocco','Yes','No'),
	array('Sea of Gibraltar','South Atlantic Ocean','Yes','No'),
	array('Sea of Gibraltar','Western Mediterranean','Yes','No'),
	array('Serbia','Adriatic Sea','Yes','No'),
	array('Serbia','Albania','Yes','Yes'),
	array('Serbia','Bosnia','No','Yes'),
	array('Serbia','Bulgaria','No','Yes'),
	array('Serbia','Croatia','Yes','Yes'),
	array('Serbia','Hungary','No','Yes'),
	array('Serbia','Macedonia','No','Yes'),
	array('Serbia','Rumania','No','Yes'),
	array('Sevastopol','Donetsk','Yes','Yes'),
	array('Sevastopol','Eastern Black Sea','Yes','No'),
	array('Sevastopol','Kiev','No','Yes'),
	array('Sevastopol','Odessa','Yes','Yes'),
	array('Sevastopol','Western Black Sea','Yes','No'),
	array('Seville','Andalucia','No','Yes'),
	array('Seville','Gibraltar','Yes','Yes'),
	array('Seville','Madrid','No','Yes'),
	array('Seville','Portugal','Yes','Yes'),
	array('Seville','South Atlantic Ocean','Yes','No'),
	array('Siberia','Kazakhstan','No','Yes'),
	array('Siberia','Urals','No','Yes'),
	array('Siberia','Volga','No','Yes'),
	array('Silecia','Berlin','No','Yes'),
	array('Silecia','Czech Republic','No','Yes'),
	array('Silecia','Krakow','No','Yes'),
	array('Silecia','Prussia','No','Yes'),
	array('Silecia','Saxony','No','Yes'),
	array('Silecia','Warsaw','No','Yes'),
	array('Sinai Peninsula','Cairo','Yes','Yes'),
	array('Sinai Peninsula','Israel','No','Yes'),
	array('Sinai Peninsula','Jordan','Yes','Yes'),
	array('Sinai Peninsula','Red Sea','Yes','No'),
	array('Skagerrak','Denmark','Yes','No'),
	array('Skagerrak','North Sea','Yes','No'),
	array('Skagerrak','Norway','Yes','No'),
	array('Skagerrak','Sweden','Yes','No'),
	array('Slovakia','Austria','No','Yes'),
	array('Slovakia','Czech Republic','No','Yes'),
	array('Slovakia','Hungary','No','Yes'),
	array('Slovakia','Krakow','No','Yes'),
	array('Slovakia','Podolia','No','Yes'),
	array('South Atlantic Ocean','Gibraltar','Yes','No'),
	array('South Atlantic Ocean','Mid-Atlantic Ocean','Yes','No'),
	array('South Atlantic Ocean','Morocco','Yes','No'),
	array('South Atlantic Ocean','Portugal','Yes','No'),
	array('South Atlantic Ocean','Sea of Gibraltar','Yes','No'),
	array('South Atlantic Ocean','Seville','Yes','No'),
	array('St. Petersburg','Estonia','Yes','Yes'),
	array('St. Petersburg','Finland','Yes','Yes'),
	array('St. Petersburg','Gorky','No','Yes'),
	array('St. Petersburg','Gulf of Bothnia','Yes','No'),
	array('St. Petersburg','Latvia','No','Yes'),
	array('St. Petersburg','Moscow','No','Yes'),
	array('St. Petersburg','Murmansk','No','Yes'),
	array('Sweden','Baltic Sea','Yes','No'),
	array('Sweden','Bhm. Sea','Yes','No'),
	array('Sweden','Denmark','Yes','Yes'),
	array('Sweden','Finland','Yes','Yes'),
	array('Sweden','Gulf of Bothnia','Yes','No'),
	array('Sweden','Lapland','No','Yes'),
	array('Sweden','Norway','Yes','Yes'),
	array('Sweden','Skagerrak','Yes','No'),
	array('Switzerland','Alsace','No','Yes'),
	array('Switzerland','Austria','No','Yes'),
	array('Switzerland','Lyon','No','Yes'),
	array('Switzerland','Marseilles','No','Yes'),
	array('Switzerland','Milan','No','Yes'),
	array('Switzerland','Munich','No','Yes'),
	array('Switzerland','Piedmont','No','Yes'),
	array('Syria','Adana','Yes','Yes'),
	array('Syria','Eastern Mediterranean','Yes','No'),
	array('Syria','Iraq','No','Yes'),
	array('Syria','Israel','Yes','Yes'),
	array('Syria','Jordan','No','Yes'),
	array('Tunisia','Algeria','Yes','Yes'),
	array('Tunisia','Libya','Yes','Yes'),
	array('Tunisia','Maltese Sea','Yes','No'),
	array('Tunisia','Tyrrhenian Sea','Yes','No'),
	array('Tunisia','Western Mediterranean','Yes','No'),
	array('Tuscany','Ligurian Sea','Yes','No'),
	array('Tuscany','Milan','No','Yes'),
	array('Tuscany','Piedmont','Yes','Yes'),
	array('Tuscany','Rome','Yes','Yes'),
	array('Tuscany','Venice','No','Yes'),
	array('Tyrrhenian Sea','Gulf of Lyon','Yes','No'),
	array('Tyrrhenian Sea','Ligurian Sea','Yes','No'),
	array('Tyrrhenian Sea','Maltese Sea','Yes','No'),
	array('Tyrrhenian Sea','Naples','Yes','No'),
	array('Tyrrhenian Sea','Rome','Yes','No'),
	array('Tyrrhenian Sea','Tunisia','Yes','No'),
	array('Tyrrhenian Sea','Western Mediterranean','Yes','No'),
	array('Urals','Barents Sea','Yes','No'),
	array('Urals','Gorky','No','Yes'),
	array('Urals','Murmansk','Yes','Yes'),
	array('Urals','Siberia','No','Yes'),
	array('Urals','Volga','No','Yes'),
	array('Urals','White Sea','Yes','No'),
	array('Venice','Adriatic Sea','Yes','No'),
	array('Venice','Apulia','Yes','Yes'),
	array('Venice','Austria','No','Yes'),
	array('Venice','Croatia','Yes','Yes'),
	array('Venice','Milan','No','Yes'),
	array('Venice','Rome','No','Yes'),
	array('Venice','Tuscany','No','Yes'),
	array('Volga','Caspian Sea','Yes','No'),
	array('Volga','Caucasus','Yes','Yes'),
	array('Volga','Central Russian Plateau','No','Yes'),
	array('Volga','Donetsk','No','Yes'),
	array('Volga','Gorky','No','Yes'),
	array('Volga','Kazakhstan','Yes','Yes'),
	array('Volga','Kharkov','No','Yes'),
	array('Volga','Moscow','No','Yes'),
	array('Volga','Rostov','Yes','Yes'),
	array('Volga','Siberia','No','Yes'),
	array('Volga','Urals','No','Yes'),
	array('Wales','English Channel','Yes','No'),
	array('Wales','Irish Sea','Yes','No'),
	array('Wales','Liverpool','Yes','Yes'),
	array('Wales','London','Yes','Yes'),
	array('Wales','Yorkshire','No','Yes'),
	array('Warsaw','Bielorussia','No','Yes'),
	array('Warsaw','Gdansk','No','Yes'),
	array('Warsaw','Krakow','No','Yes'),
	array('Warsaw','Lithuania','No','Yes'),
	array('Warsaw','Prussia','No','Yes'),
	array('Warsaw','Silecia','No','Yes'),
	array('Western Black Sea','Ankara','Yes','No'),
	array('Western Black Sea','Bulgaria','Yes','No'),
	array('Western Black Sea','Eastern Black Sea','Yes','No'),
	array('Western Black Sea','Istanbul','Yes','No'),
	array('Western Black Sea','Odessa','Yes','No'),
	array('Western Black Sea','Rumania','Yes','No'),
	array('Western Black Sea','Sevastopol','Yes','No'),
	array('Western Mediterranean','Algeria','Yes','No'),
	array('Western Mediterranean','Andalucia','Yes','No'),
	array('Western Mediterranean','Barcelona','Yes','No'),
	array('Western Mediterranean','Gulf of Lyon','Yes','No'),
	array('Western Mediterranean','Sea of Gibraltar','Yes','No'),
	array('Western Mediterranean','Tunisia','Yes','No'),
	array('Western Mediterranean','Tyrrhenian Sea','Yes','No'),
	array('Western Sahara','Algeria','No','Yes'),
	array('Western Sahara','Libya','No','Yes'),
	array('Western Sahara','Morocco','No','Yes'),
	array('White Sea','Barents Sea','Yes','No'),
	array('White Sea','Murmansk','Yes','No'),
	array('White Sea','Urals','Yes','No'),
	array('Yorkshire','Edinburgh','Yes','Yes'),
	array('Yorkshire','Liverpool','No','Yes'),
	array('Yorkshire','London','Yes','Yes'),
	array('Yorkshire','North Sea','Yes','No'),
	array('Yorkshire','Wales','No','Yes')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
