<?php
// This is file installs the map data for the CelticBritain variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Atrebates', 'Land', 'Yes', 0, 1128, 1286, 564, 645),
	array('Auteini', 'Coast', 'Yes', 6, 289, 1111, 139, 559),
	array('Belgae', 'Coast', 'Yes', 8, 1031, 1359, 518, 684),
	array('Blanii', 'Coast', 'No', 0, 531, 954, 262, 478),
	array('Caledonii', 'Coast', 'Yes', 3, 711, 379, 356, 182),
	array('Caledonii (North Coast)', 'Coast', 'No', 3, 645, 460, 312, 229),
	array('Caledonii (South Coast)', 'Coast', 'No', 3, 666, 523, 332, 269),
	array('Cantiaci', 'Coast', 'Yes', 2, 1277, 1303, 636, 646),
	array('Carini', 'Coast', 'Yes', 4, 471, 288, 234, 145),
	array('Cauci', 'Coast', 'No', 0, 531, 1010, 269, 505),
	array('Cerones', 'Coast', 'No', 0, 644, 344, 321, 169),
	array('Cerones (East Coast)', 'Coast', 'No', 0, 733, 284, 372, 136),
	array('Cerones (West Coast)', 'Coast', 'No', 0, 623, 364, 313, 190),
	array('Coriondi', 'Coast', 'No', 0, 513, 1125, 262, 561),
	array('Cornavii', 'Coast', 'Yes', 0, 860, 34, 412, 27),
	array('Damnonii', 'Coast', 'Yes', 0, 764, 583, 378, 290),
	array('Damnonii (East Coast)', 'Coast', 'No', 0, 838, 557, 415, 280),
	array('Damnonii (West Coast)', 'Coast', 'No', 0, 726, 601, 365, 302),
	array('Darini', 'Coast', 'Yes', 7, 538, 826, 272, 413),
	array('Decantae', 'Coast', 'Yes', 0, 677, 260, 330, 109),
	array('Decantae (East Coast)', 'Coast', 'No', 0, 759, 232, 367, 109),
	array('Decantae (West Coast)', 'Coast', 'No', 0, 626, 256, 311, 122),
	array('Deceangli', 'Coast', 'Yes', 5, 772, 1012, 415, 491),
	array('Demetae', 'Coast', 'Yes', 0, 721, 1204, 391, 584),
	array('Dobunni', 'Coast', 'No', 0, 965, 1250, 477, 629),
	array('Dumnonii', 'Coast', 'Yes', 8, 788, 1433, 390, 676),
	array('Durotriges', 'Coast', 'Yes', 8, 870, 1359, 477, 672),
	array('Durotriges (North Coast)', 'Coast', 'No', 8, 843, 1328, 426, 666),
	array('Durotriges (South Coast)', 'Coast', 'No', 8, 942, 1391, 491, 685),
	array('E.Coritani', 'Coast', 'No', 0, 1108, 1007, 561, 475),
	array('East Oceanus Caledonia', 'Sea', 'No', 0, 623, 90, 342, 22),
	array('East Oceanus Germanicus', 'Sea', 'No', 0, 1341, 482, 674, 199),
	array('East Oceanus Vercivius', 'Sea', 'No', 0, 590, 1317, 321, 657),
	array('Epidii', 'Coast', 'No', 0, 633, 539, 314, 267),
	array('Erdin', 'Coast', 'Yes', 7, 238, 911, 138, 451),
	array('Iceni', 'Coast', 'Yes', 2, 1288, 1059, 591, 541),
	array('Ituna Aest.', 'Sea', 'No', 0, 781, 768, 397, 406),
	array('Iverni', 'Coast', 'Yes', 6, 266, 1216, 129, 613),
	array('Limnu', 'Coast', 'Yes', 4, 525, 206, 280, 69),
	array('Litus', 'Sea', 'No', 0, 1360, 1344, 674, 674),
	array('Lugi', 'Coast', 'Yes', 0, 782, 138, 394, 73),
	array('Menapii', 'Coast', 'Yes', 6, 535, 1073, 272, 536),
	array('Metaris Aest.', 'Sea', 'No', 0, 1310, 940, 658, 477),
	array('Mid Oceanus Hibernicus', 'Sea', 'No', 0, 643, 944, 335, 393),
	array('Mona', 'Coast', 'Yes', 0, 739, 989, 379, 485),
	array('Monapia', 'Coast', 'Yes', 0, 734, 808, 364, 398),
	array('Moricambe Aest.', 'Sea', 'No', 0, 799, 876, 399, 472),
	array('N.Brigantes', 'Coast', 'Yes', 1, 870, 794, 446, 364),
	array('N.Catuvellauni', 'Land', 'Yes', 0, 1037, 1141, 520, 573),
	array('N.Cornovii', 'Coast', 'Yes', 5, 925, 1061, 454, 502),
	array('Nagnate', 'Coast', 'Yes', 0, 278, 1024, 135, 513),
	array('North Oceanus Atlantic', 'Sea', 'No', 0, 147, 649, 81, 332),
	array('North Oceanus Germanicus', 'Sea', 'No', 0, 1198, 290, 600, 147),
	array('North Oceanus Hibernicus', 'Sea', 'No', 0, 498, 540, 258, 213),
	array('Novantae', 'Coast', 'No', 0, 816, 652, 405, 324),
	array('Oceanus Atlantic', 'Sea', 'No', 0, 71, 924, 39, 465),
	array('Oceanus Britanicus', 'Sea', 'No', 0, 978, 1539, 505, 770),
	array('Ordovices', 'Coast', 'Yes', 5, 829, 1103, 435, 568),
	array('Parisi', 'Coast', 'Yes', 0, 1085, 852, 542, 429),
	array('Portus Magnus', 'Sea', 'No', 0, 744, 1501, 372, 751),
	array('Regninses', 'Coast', 'No', 0, 1111, 1364, 581, 663),
	array('Robogdii', 'Coast', 'No', 0, 544, 671, 285, 361),
	array('S.Brigantes', 'Coast', 'Yes', 0, 923, 917, 476, 422),
	array('S.Catuvellauni', 'Land', 'Yes', 0, 1139, 1220, 568, 611),
	array('S.Cornovii', 'Land', 'Yes', 5, 945, 1163, 463, 583),
	array('Sabrina Aest.', 'Sea', 'No', 0, 759, 1292, 393, 637),
	array('Saxonicum', 'Sea', 'No', 0, 1374, 1120, 686, 564),
	array('Selgovae', 'Land', 'Yes', 1, 928, 665, 464, 335),
	array('Silures', 'Coast', 'No', 0, 837, 1251, 428, 605),
	array('Skitis', 'Coast', 'Yes', 4, 563, 250, 284, 127),
	array('South Oceanus Germanicus', 'Sea', 'No', 0, 1223, 702, 614, 300),
	array('South Oceanus Hibernicus', 'Sea', 'No', 0, 703, 1103, 348, 555),
	array('Taexali', 'Coast', 'Yes', 3, 797, 313, 397, 156),
	array('Taexali (East Coast)', 'Coast', 'No', 3, 909, 367, 458, 181),
	array('Taexali (North Coast)', 'Coast', 'No', 3, 789, 273, 392, 144),
	array('Trinovantes', 'Coast', 'Yes', 2, 1230, 1207, 614, 601),
	array('Vacomagi', 'Coast', 'Yes', 3, 927, 282, 438, 133),
	array('Vectis', 'Coast', 'Yes', 0, 1064, 1383, 538, 695),
	array('Velabri', 'Coast', 'Yes', 6, 158, 1184, 107, 562),
	array('Venicones', 'Coast', 'Yes', 3, 795, 442, 398, 227),
	array('Vennicnii', 'Coast', 'Yes', 7, 404, 684, 208, 374),
	array('Vodiae', 'Coast', 'Yes', 0, 365, 1182, 199, 563),
	array('Voluntii', 'Coast', 'Yes', 7, 531, 906, 224, 442),
	array('Votadini', 'Coast', 'Yes', 1, 983, 663, 502, 356),
	array('W.Coritani', 'Land', 'No', 0, 1020, 1025, 509, 512),
	array('West Oceanus Caledonia', 'Sea', 'No', 0, 192, 223, 97, 111),
	array('West Oceanus Germanicus', 'Sea', 'No', 0, 1057, 498, 524, 206),
	array('West Oceanus Vercivius', 'Sea', 'No', 0, 223, 1423, 158, 721)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Atrebates','Belgae','No','Yes'),
	array('Atrebates','Cantiaci','No','Yes'),
	array('Atrebates','Dobunni','No','Yes'),
	array('Atrebates','Regninses','No','Yes'),
	array('Atrebates','S.Catuvellauni','No','Yes'),
	array('Auteini','Cauci','No','Yes'),
	array('Auteini','Iverni','No','Yes'),
	array('Auteini','Menapii','No','Yes'),
	array('Auteini','Nagnate','Yes','Yes'),
	array('Auteini','Oceanus Atlantic','Yes','No'),
	array('Auteini','Velabri','Yes','Yes'),
	array('Auteini','Vodiae','No','Yes'),
	array('Belgae','Dobunni','No','Yes'),
	array('Belgae','Durotriges','No','Yes'),
	array('Belgae','Durotriges (South Coast)','Yes','No'),
	array('Belgae','Litus','Yes','No'),
	array('Belgae','Portus Magnus','Yes','No'),
	array('Belgae','Regninses','Yes','Yes'),
	array('Belgae','Vectis','Yes','No'),
	array('Blanii','Cauci','Yes','Yes'),
	array('Blanii','Mid Oceanus Hibernicus','Yes','No'),
	array('Blanii','Nagnate','No','Yes'),
	array('Blanii','South Oceanus Hibernicus','Yes','No'),
	array('Blanii','Voluntii','Yes','Yes'),
	array('Caledonii','Cerones','No','Yes'),
	array('Caledonii','Damnonii','No','Yes'),
	array('Caledonii','Epidii','No','Yes'),
	array('Caledonii','Venicones','No','Yes'),
	array('Caledonii (North Coast)','Cerones (West Coast)','Yes','No'),
	array('Caledonii (North Coast)','Epidii','Yes','No'),
	array('Caledonii (North Coast)','North Oceanus Hibernicus','Yes','No'),
	array('Caledonii (South Coast)','Damnonii (West Coast)','Yes','No'),
	array('Caledonii (South Coast)','Epidii','Yes','No'),
	array('Caledonii (South Coast)','North Oceanus Hibernicus','Yes','No'),
	array('Cantiaci','Litus','Yes','No'),
	array('Cantiaci','Regninses','Yes','Yes'),
	array('Cantiaci','S.Catuvellauni','No','Yes'),
	array('Cantiaci','Saxonicum','Yes','No'),
	array('Cantiaci','Trinovantes','Yes','Yes'),
	array('Carini','East Oceanus Caledonia','Yes','No'),
	array('Carini','Limnu','Yes','No'),
	array('Carini','North Oceanus Atlantic','Yes','No'),
	array('Carini','North Oceanus Hibernicus','Yes','No'),
	array('Carini','Skitis','Yes','No'),
	array('Carini','West Oceanus Caledonia','Yes','No'),
	array('Cauci','Menapii','Yes','Yes'),
	array('Cauci','Nagnate','No','Yes'),
	array('Cauci','South Oceanus Hibernicus','Yes','No'),
	array('Cerones','Decantae','No','Yes'),
	array('Cerones','Taexali','No','Yes'),
	array('Cerones','Venicones','No','Yes'),
	array('Cerones (East Coast)','Decantae (East Coast)','Yes','No'),
	array('Cerones (East Coast)','North Oceanus Germanicus','Yes','No'),
	array('Cerones (East Coast)','Taexali (North Coast)','Yes','No'),
	array('Cerones (West Coast)','Decantae (West Coast)','Yes','No'),
	array('Cerones (West Coast)','North Oceanus Hibernicus','Yes','No'),
	array('Cerones (West Coast)','Skitis','Yes','No'),
	array('Coriondi','East Oceanus Vercivius','Yes','No'),
	array('Coriondi','Menapii','Yes','Yes'),
	array('Coriondi','Vodiae','Yes','Yes'),
	array('Cornavii','East Oceanus Caledonia','Yes','No'),
	array('Cornavii','Lugi','Yes','No'),
	array('Cornavii','North Oceanus Germanicus','Yes','No'),
	array('Damnonii','Novantae','No','Yes'),
	array('Damnonii','Selgovae','No','Yes'),
	array('Damnonii','Venicones','No','Yes'),
	array('Damnonii','Votadini','No','Yes'),
	array('Damnonii (East Coast)','Venicones','Yes','No'),
	array('Damnonii (East Coast)','Votadini','Yes','No'),
	array('Damnonii (East Coast)','West Oceanus Germanicus','Yes','No'),
	array('Damnonii (West Coast)','North Oceanus Hibernicus','Yes','No'),
	array('Damnonii (West Coast)','Novantae','Yes','No'),
	array('Darini','Mid Oceanus Hibernicus','Yes','No'),
	array('Darini','Robogdii','Yes','Yes'),
	array('Darini','Vennicnii','No','Yes'),
	array('Darini','Voluntii','Yes','Yes'),
	array('Decantae','Lugi','No','Yes'),
	array('Decantae (East Coast)','Lugi','Yes','No'),
	array('Decantae (East Coast)','North Oceanus Germanicus','Yes','No'),
	array('Decantae (West Coast)','East Oceanus Caledonia','Yes','No'),
	array('Decantae (West Coast)','Lugi','Yes','No'),
	array('Decantae (West Coast)','Skitis','Yes','No'),
	array('Deceangli','Mona','Yes','Yes'),
	array('Deceangli','Moricambe Aest.','Yes','No'),
	array('Deceangli','N.Cornovii','Yes','Yes'),
	array('Deceangli','Ordovices','Yes','Yes'),
	array('Deceangli','South Oceanus Hibernicus','Yes','No'),
	array('Demetae','East Oceanus Vercivius','Yes','No'),
	array('Demetae','Ordovices','Yes','Yes'),
	array('Demetae','Silures','Yes','Yes'),
	array('Demetae','South Oceanus Hibernicus','Yes','No'),
	array('Dobunni','Durotriges','No','Yes'),
	array('Dobunni','Durotriges (North Coast)','Yes','No'),
	array('Dobunni','N.Catuvellauni','No','Yes'),
	array('Dobunni','S.Catuvellauni','No','Yes'),
	array('Dobunni','S.Cornovii','No','Yes'),
	array('Dobunni','Sabrina Aest.','Yes','No'),
	array('Dobunni','Silures','Yes','Yes'),
	array('Dumnonii','Durotriges','No','Yes'),
	array('Dumnonii','Durotriges (North Coast)','Yes','No'),
	array('Dumnonii','Durotriges (South Coast)','Yes','No'),
	array('Dumnonii','East Oceanus Vercivius','Yes','No'),
	array('Dumnonii','Portus Magnus','Yes','No'),
	array('Dumnonii','Sabrina Aest.','Yes','No'),
	array('Durotriges (North Coast)','Sabrina Aest.','Yes','No'),
	array('Durotriges (South Coast)','Portus Magnus','Yes','No'),
	array('E.Coritani','Iceni','Yes','Yes'),
	array('E.Coritani','Metaris Aest.','Yes','No'),
	array('E.Coritani','N.Catuvellauni','No','Yes'),
	array('E.Coritani','Parisi','Yes','Yes'),
	array('E.Coritani','S.Brigantes','No','Yes'),
	array('E.Coritani','W.Coritani','No','Yes'),
	array('East Oceanus Caledonia','Limnu','Yes','No'),
	array('East Oceanus Caledonia','Lugi','Yes','No'),
	array('East Oceanus Caledonia','Skitis','Yes','No'),
	array('East Oceanus Caledonia','West Oceanus Caledonia','Yes','No'),
	array('East Oceanus Germanicus','North Oceanus Germanicus','Yes','No'),
	array('East Oceanus Germanicus','South Oceanus Germanicus','Yes','No'),
	array('East Oceanus Germanicus','West Oceanus Germanicus','Yes','No'),
	array('East Oceanus Vercivius','Menapii','Yes','No'),
	array('East Oceanus Vercivius','Portus Magnus','Yes','No'),
	array('East Oceanus Vercivius','Sabrina Aest.','Yes','No'),
	array('East Oceanus Vercivius','Silures','Yes','No'),
	array('East Oceanus Vercivius','South Oceanus Hibernicus','Yes','No'),
	array('East Oceanus Vercivius','Vodiae','Yes','No'),
	array('East Oceanus Vercivius','West Oceanus Vercivius','Yes','No'),
	array('Epidii','North Oceanus Hibernicus','Yes','No'),
	array('Erdin','Nagnate','Yes','Yes'),
	array('Erdin','North Oceanus Atlantic','Yes','No'),
	array('Erdin','Oceanus Atlantic','Yes','No'),
	array('Erdin','Vennicnii','Yes','Yes'),
	array('Erdin','Voluntii','No','Yes'),
	array('Iceni','Metaris Aest.','Yes','No'),
	array('Iceni','N.Catuvellauni','No','Yes'),
	array('Iceni','S.Catuvellauni','No','Yes'),
	array('Iceni','Saxonicum','Yes','No'),
	array('Iceni','Trinovantes','Yes','Yes'),
	array('Ituna Aest.','Mid Oceanus Hibernicus','Yes','No'),
	array('Ituna Aest.','Monapia','Yes','No'),
	array('Ituna Aest.','Moricambe Aest.','Yes','No'),
	array('Ituna Aest.','N.Brigantes','Yes','No'),
	array('Ituna Aest.','Novantae','Yes','No'),
	array('Iverni','Velabri','Yes','Yes'),
	array('Iverni','Vodiae','Yes','Yes'),
	array('Iverni','West Oceanus Vercivius','Yes','No'),
	array('Limnu','West Oceanus Caledonia','Yes','No'),
	array('Litus','Oceanus Britanicus','Yes','No'),
	array('Litus','Portus Magnus','Yes','No'),
	array('Litus','Regninses','Yes','No'),
	array('Litus','Saxonicum','Yes','No'),
	array('Litus','Vectis','Yes','No'),
	array('Lugi','North Oceanus Germanicus','Yes','No'),
	array('Menapii','South Oceanus Hibernicus','Yes','No'),
	array('Menapii','Vodiae','No','Yes'),
	array('Metaris Aest.','Parisi','Yes','No'),
	array('Metaris Aest.','Saxonicum','Yes','No'),
	array('Metaris Aest.','South Oceanus Germanicus','Yes','No'),
	array('Mid Oceanus Hibernicus','Mona','Yes','No'),
	array('Mid Oceanus Hibernicus','Monapia','Yes','No'),
	array('Mid Oceanus Hibernicus','Moricambe Aest.','Yes','No'),
	array('Mid Oceanus Hibernicus','North Oceanus Hibernicus','Yes','No'),
	array('Mid Oceanus Hibernicus','Novantae','Yes','No'),
	array('Mid Oceanus Hibernicus','Robogdii','Yes','No'),
	array('Mid Oceanus Hibernicus','South Oceanus Hibernicus','Yes','No'),
	array('Mid Oceanus Hibernicus','Voluntii','Yes','No'),
	array('Mona','Moricambe Aest.','Yes','No'),
	array('Mona','South Oceanus Hibernicus','Yes','No'),
	array('Monapia','Moricambe Aest.','Yes','No'),
	array('Moricambe Aest.','N.Brigantes','Yes','No'),
	array('Moricambe Aest.','N.Cornovii','Yes','No'),
	array('Moricambe Aest.','S.Brigantes','Yes','No'),
	array('Moricambe Aest.','South Oceanus Hibernicus','Yes','No'),
	array('N.Brigantes','Novantae','Yes','Yes'),
	array('N.Brigantes','Parisi','No','Yes'),
	array('N.Brigantes','S.Brigantes','Yes','Yes'),
	array('N.Brigantes','Selgovae','No','Yes'),
	array('N.Brigantes','Votadini','No','Yes'),
	array('N.Catuvellauni','S.Catuvellauni','No','Yes'),
	array('N.Catuvellauni','S.Cornovii','No','Yes'),
	array('N.Catuvellauni','W.Coritani','No','Yes'),
	array('N.Cornovii','Ordovices','No','Yes'),
	array('N.Cornovii','S.Brigantes','Yes','Yes'),
	array('N.Cornovii','S.Cornovii','No','Yes'),
	array('N.Cornovii','W.Coritani','No','Yes'),
	array('Nagnate','Oceanus Atlantic','Yes','No'),
	array('Nagnate','Voluntii','No','Yes'),
	array('North Oceanus Atlantic','North Oceanus Hibernicus','Yes','No'),
	array('North Oceanus Atlantic','Oceanus Atlantic','Yes','No'),
	array('North Oceanus Atlantic','Vennicnii','Yes','No'),
	array('North Oceanus Atlantic','West Oceanus Caledonia','Yes','No'),
	array('North Oceanus Germanicus','Taexali (North Coast)','Yes','No'),
	array('North Oceanus Germanicus','Vacomagi','Yes','No'),
	array('North Oceanus Germanicus','West Oceanus Germanicus','Yes','No'),
	array('North Oceanus Hibernicus','Novantae','Yes','No'),
	array('North Oceanus Hibernicus','Robogdii','Yes','No'),
	array('North Oceanus Hibernicus','Skitis','Yes','No'),
	array('North Oceanus Hibernicus','Vennicnii','Yes','No'),
	array('North Oceanus Hibernicus','West Oceanus Caledonia','Yes','No'),
	array('Novantae','Selgovae','No','Yes'),
	array('Oceanus Atlantic','West Oceanus Vercivius','Yes','No'),
	array('Oceanus Britanicus','Portus Magnus','Yes','No'),
	array('Oceanus Britanicus','West Oceanus Vercivius','Yes','No'),
	array('Ordovices','S.Cornovii','No','Yes'),
	array('Ordovices','Silures','No','Yes'),
	array('Ordovices','South Oceanus Hibernicus','Yes','No'),
	array('Parisi','S.Brigantes','No','Yes'),
	array('Parisi','South Oceanus Germanicus','Yes','No'),
	array('Parisi','Votadini','Yes','Yes'),
	array('Portus Magnus','Vectis','Yes','No'),
	array('Portus Magnus','West Oceanus Vercivius','Yes','No'),
	array('Robogdii','Vennicnii','Yes','Yes'),
	array('S.Brigantes','W.Coritani','No','Yes'),
	array('S.Catuvellauni','Trinovantes','No','Yes'),
	array('S.Cornovii','Silures','No','Yes'),
	array('S.Cornovii','W.Coritani','No','Yes'),
	array('Sabrina Aest.','Silures','Yes','No'),
	array('Saxonicum','Trinovantes','Yes','No'),
	array('Selgovae','Votadini','No','Yes'),
	array('South Oceanus Germanicus','Votadini','Yes','No'),
	array('South Oceanus Germanicus','West Oceanus Germanicus','Yes','No'),
	array('Taexali','Vacomagi','No','Yes'),
	array('Taexali','Venicones','No','Yes'),
	array('Taexali (East Coast)','Vacomagi','Yes','No'),
	array('Taexali (East Coast)','Venicones','Yes','No'),
	array('Taexali (East Coast)','West Oceanus Germanicus','Yes','No'),
	array('Taexali (North Coast)','Vacomagi','Yes','No'),
	array('Vacomagi','West Oceanus Germanicus','Yes','No'),
	array('Velabri','West Oceanus Vercivius','Yes','No'),
	array('Venicones','West Oceanus Germanicus','Yes','No'),
	array('Vennicnii','Voluntii','No','Yes'),
	array('Vodiae','West Oceanus Vercivius','Yes','No'),
	array('Votadini','West Oceanus Germanicus','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
