<?php
// This is file installs the map data for the ClassicTouchy variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Edinburgh', 'Coast', 'Yes', 1, 330, 343, 168, 109),
	array('Liverpool', 'Coast', 'Yes', 1, 306, 464, 155, 169),
	array('London', 'Coast', 'Yes', 1, 343, 472, 180, 174),
	array('Irish Sea', 'Sea', 'No', 0, 224, 521, 143, 203),
	array('Atlantic Ocean', 'Sea', 'No', 0, 96, 440, 39, 149),
	array('Norwegian Sea', 'Sea', 'No', 0, 452, 126, 263, 18),
	array('North Sea', 'Sea', 'No', 0, 417, 373, 213, 124),
	array('Sweden', 'Coast', 'Yes', 0, 568, 274, 287, 103),
	array('St. Petersburg', 'Coast', 'Yes', 7, 830, 313, 473, 87),
	array('St. Petersburg (South Coast)', 'Coast', 'No', 7, 727, 300, 380, 111),
	array('St. Petersburg (North Coast)', 'Coast', 'No', 7, 894, 154, 453, 58),
	array('Moscow', 'Land', 'Yes', 7, 955, 448, 446, 175),
	array('Warsaw', 'Coast', 'Yes', 7, 722, 459, 373, 175),
	array('Sevastopol', 'Coast', 'Yes', 7, 887, 591, 470, 240),
	array('Baltic Sea', 'Sea', 'No', 0, 634, 421, 338, 137),
	array('Berlin', 'Coast', 'Yes', 4, 584, 490, 309, 200),
	array('Kiel', 'Coast', 'Yes', 4, 482, 497, 255, 191),
	array('Munich', 'Coast', 'Yes', 4, 493, 589, 250, 234),
	array('Ankara', 'Coast', 'Yes', 6, 1012, 811, 544, 320),
	array('Constantinople', 'Coast', 'Yes', 6, 830, 843, 436, 339),
	array('Smyrna', 'Coast', 'Yes', 6, 847, 900, 501, 351),
	array('Bulgaria', 'Coast', 'Yes', 0, 731, 759, 390, 298),
	array('Bulgaria (South Coast)', 'Coast', 'No', 0, 755, 804, 398, 326),
	array('Bulgaria (North Coast)', 'Coast', 'No', 0, 790, 739, 420, 285),
	array('Serbia', 'Coast', 'Yes', 0, 665, 807, 353, 334),
	array('Vienna', 'Land', 'Yes', 5, 572, 610, 284, 252),
	array('Budapest', 'Land', 'Yes', 5, 673, 663, 358, 256),
	array('Trieste', 'Coast', 'Yes', 5, 583, 705, 312, 289),
	array('Venice', 'Coast', 'Yes', 3, 492, 702, 259, 293),
	array('Rome', 'Coast', 'Yes', 3, 497, 766, 255, 307),
	array('Naples', 'Coast', 'Yes', 3, 578, 832, 295, 342),
	array('Marseilles', 'Coast', 'Yes', 2, 378, 686, 194, 269),
	array('Paris', 'Coast', 'Yes', 2, 341, 598, 176, 229),
	array('Spain', 'Coast', 'Yes', 0, 152, 764, 90, 327),
	array('North Africa', 'Coast', 'Yes', 0, 340, 936, 155, 388),
	array('Western Medierranean', 'Sea', 'No', 0, 369, 825, 193, 335),
	array('Eastern Mediterranean', 'Sea', 'No', 0, 841, 957, 405, 380),
	array('Ionian Sea', 'Sea', 'No', 0, 600, 934, 335, 383),
	array('Black Sea', 'Sea', 'No', 0, 870, 744, 450, 294),
	array('Brest', 'Coast', 'Yes', 2, 301, 577, 150, 262),
	array('Holland', 'Coast', 'Yes', 0, 401, 532, 215, 198)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Edinburgh','Liverpool','Yes','Yes'),
	array('Edinburgh','London','Yes','Yes'),
	array('Edinburgh','Atlantic Ocean','Yes','No'),
	array('Edinburgh','Norwegian Sea','Yes','No'),
	array('Edinburgh','North Sea','Yes','No'),
	array('Liverpool','London','Yes','Yes'),
	array('Liverpool','Irish Sea','Yes','No'),
	array('Liverpool','Atlantic Ocean','Yes','No'),
	array('London','Irish Sea','Yes','No'),
	array('London','North Sea','Yes','No'),
	array('London','Paris','Yes','Yes'),
	array('London','Holland','Yes','Yes'),
	array('Irish Sea','Atlantic Ocean','Yes','No'),
	array('Irish Sea','North Sea','Yes','No'),
	array('Irish Sea','Paris','Yes','No'),
	array('Irish Sea','Brest','Yes','No'),
	array('Irish Sea','Holland','Yes','No'),
	array('Atlantic Ocean','Norwegian Sea','Yes','No'),
	array('Atlantic Ocean','Spain','Yes','No'),
	array('Atlantic Ocean','North Africa','Yes','No'),
	array('Atlantic Ocean','Western Medierranean','Yes','No'),
	array('Atlantic Ocean','Brest','Yes','No'),
	array('Norwegian Sea','North Sea','Yes','No'),
	array('Norwegian Sea','Sweden','Yes','No'),
	array('Norwegian Sea','St. Petersburg (North Coast)','Yes','No'),
	array('North Sea','Sweden','Yes','No'),
	array('North Sea','Kiel','Yes','No'),
	array('North Sea','Holland','Yes','No'),
	array('Sweden','St. Petersburg','No','Yes'),
	array('Sweden','St. Petersburg (South Coast)','Yes','No'),
	array('Sweden','St. Petersburg (North Coast)','Yes','No'),
	array('Sweden','Baltic Sea','Yes','No'),
	array('Sweden','Kiel','Yes','Yes'),
	array('St. Petersburg','Moscow','No','Yes'),
	array('St. Petersburg','Warsaw','No','Yes'),
	array('St. Petersburg (South Coast)','Warsaw','Yes','No'),
	array('St. Petersburg (South Coast)','Baltic Sea','Yes','No'),
	array('Moscow','Warsaw','No','Yes'),
	array('Moscow','Sevastopol','No','Yes'),
	array('Warsaw','Sevastopol','No','Yes'),
	array('Warsaw','Baltic Sea','Yes','No'),
	array('Warsaw','Berlin','Yes','Yes'),
	array('Warsaw','Munich','No','Yes'),
	array('Warsaw','Budapest','No','Yes'),
	array('Sevastopol','Ankara','Yes','Yes'),
	array('Sevastopol','Bulgaria','No','Yes'),
	array('Sevastopol','Bulgaria (North Coast)','Yes','No'),
	array('Sevastopol','Budapest','No','Yes'),
	array('Sevastopol','Black Sea','Yes','No'),
	array('Baltic Sea','Berlin','Yes','No'),
	array('Baltic Sea','Kiel','Yes','No'),
	array('Berlin','Kiel','Yes','Yes'),
	array('Berlin','Munich','No','Yes'),
	array('Kiel','Munich','No','Yes'),
	array('Kiel','Marseilles','No','Yes'),
	array('Kiel','Holland','Yes','Yes'),
	array('Munich','Vienna','No','Yes'),
	array('Munich','Budapest','No','Yes'),
	array('Munich','Marseilles','No','Yes'),
	array('Ankara','Constantinople','Yes','Yes'),
	array('Ankara','Smyrna','No','Yes'),
	array('Ankara','Black Sea','Yes','No'),
	array('Constantinople','Smyrna','Yes','Yes'),
	array('Constantinople','Bulgaria','No','Yes'),
	array('Constantinople','Bulgaria (South Coast)','Yes','No'),
	array('Constantinople','Bulgaria (North Coast)','Yes','No'),
	array('Constantinople','Eastern Mediterranean','Yes','No'),
	array('Constantinople','Black Sea','Yes','No'),
	array('Smyrna','Eastern Mediterranean','Yes','No'),
	array('Bulgaria','Serbia','No','Yes'),
	array('Bulgaria','Budapest','No','Yes'),
	array('Bulgaria (South Coast)','Serbia','Yes','No'),
	array('Bulgaria (South Coast)','Eastern Mediterranean','Yes','No'),
	array('Bulgaria (North Coast)','Black Sea','Yes','No'),
	array('Serbia','Budapest','No','Yes'),
	array('Serbia','Trieste','Yes','Yes'),
	array('Serbia','Naples','Yes','Yes'),
	array('Serbia','Eastern Mediterranean','Yes','No'),
	array('Serbia','Ionian Sea','Yes','No'),
	array('Vienna','Budapest','No','Yes'),
	array('Vienna','Trieste','No','Yes'),
	array('Vienna','Venice','No','Yes'),
	array('Vienna','Rome','No','Yes'),
	array('Budapest','Trieste','No','Yes'),
	array('Trieste','Venice','Yes','Yes'),
	array('Trieste','Ionian Sea','Yes','No'),
	array('Venice','Rome','No','Yes'),
	array('Venice','Naples','Yes','Yes'),
	array('Venice','Ionian Sea','Yes','No'),
	array('Rome','Naples','Yes','Yes'),
	array('Rome','Marseilles','Yes','Yes'),
	array('Rome','Western Medierranean','Yes','No'),
	array('Naples','Western Medierranean','Yes','No'),
	array('Naples','Ionian Sea','Yes','No'),
	array('Marseilles','Paris','No','Yes'),
	array('Marseilles','Spain','Yes','Yes'),
	array('Marseilles','Western Medierranean','Yes','No'),
	array('Marseilles','Brest','No','Yes'),
	array('Marseilles','Holland','No','Yes'),
	array('Paris','Brest','Yes','Yes'),
	array('Paris','Holland','Yes','Yes'),
	array('Spain','North Africa','Yes','Yes'),
	array('Spain','Western Medierranean','Yes','No'),
	array('Spain','Brest','Yes','Yes'),
	array('North Africa','Western Medierranean','Yes','No'),
	array('North Africa','Ionian Sea','Yes','No'),
	array('Western Medierranean','Ionian Sea','Yes','No'),
	array('Eastern Mediterranean','Ionian Sea','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
