<?php
// This is file installs the map data for the Maharajah variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Hormuz', 'Coast', 'Yes', 5, 207, 535, 140, 268),
	array('persia', 'Coast', 'No', 5, 1155, 141, 533, 92),
	array('rajputana', 'Coast', 'No', 6, 1153, 170, 534, 107),
	array('vijayanagar', 'Coast', 'No', 7, 1154, 199, 533, 120),
	array('bahmana', 'Coast', 'No', 1, 1152, 29, 444, 93),
	array('delhi', 'Coast', 'No', 2, 1151, 52, 445, 107),
	array('gondwana', 'Coast', 'No', 3, 1153, 86, 445, 120),
	array('mughalistan', 'Coast', 'No', 4, 1155, 112, 444, 135),
	array('Kashgar', 'Land', 'No', 0, 836, 99, 419, 46),
	array('Kashmir', 'Land', 'Yes', 0, 750, 232, 372, 91),
	array('Lahore', 'Coast', 'No', 0, 671, 245, 335, 122),
	array('Jaipur', 'Land', 'No', 0, 678, 363, 340, 202),
	array('Malwa', 'Land', 'Yes', 0, 700, 555, 346, 281),
	array('Bidar', 'Land', 'Yes', 0, 713, 633, 363, 338),
	array('Warangal', 'Land', 'No', 0, 785, 713, 392, 355),
	array('Benares', 'Coast', 'No', 0, 813, 483, 388, 245),
	array('Orissa', 'Coast', 'Yes', 0, 936, 684, 430, 365),
	array('Bengal', 'Coast', 'No', 0, 971, 613, 497, 314),
	array('Assam', 'Coast', 'No', 0, 1072, 546, 540, 258),
	array('Ava', 'Coast', 'No', 0, 1168, 515, 595, 245),
	array('Pegu', 'Coast', 'Yes', 0, 1110, 688, 552, 343),
	array('Ayutthaya', 'Coast', 'Yes', 0, 1260, 866, 620, 402),
	array('Kra', 'Coast', 'No', 0, 1270, 972, 638, 495),
	array('Aceh', 'Coast', 'Yes', 0, 1207, 1121, 604, 554),
	array('Kandy', 'Coast', 'Yes', 0, 793, 1061, 392, 535),
	array('Honavar', 'Coast', 'No', 0, 660, 818, 328, 408),
	array('Khandesh', 'Land', 'Yes', 0, 599, 642, 305, 318),
	array('Ahmadabad', 'Coast', 'No', 0, 562, 623, 281, 307),
	array('Gujarat', 'Coast', 'Yes', 0, 523, 621, 259, 321),
	array('Sind', 'Coast', 'Yes', 0, 469, 566, 237, 276),
	array('Kandahar', 'Land', 'No', 0, 394, 335, 199, 163),
	array('Herat', 'Land', 'Yes', 0, 354, 248, 177, 124),
	array('Bukhara', 'Land', 'No', 0, 331, 93, 169, 43),
	array('Samarkand', 'Land', 'Yes', 0, 476, 64, 246, 25),
	array('Oman', 'Coast', 'Yes', 0, 235, 724, 120, 349),
	array('Rub Al Khali', 'Land', 'No', 0, 145, 709, 70, 357),
	array('Hadramaut', 'Coast', 'No', 0, 156, 807, 68, 404),
	array('Yemen', 'Coast', 'Yes', 0, 42, 882, 25, 443),
	array('Arabia', 'Coast', 'No', 0, 40, 628, 34, 317),
	array('Seylac', 'Coast', 'Yes', 0, 30, 1051, 27, 498),
	array('Isfahan', 'Coast', 'Yes', 5, 111, 463, 40, 205),
	array('Shiraz', 'Land', 'No', 5, 321, 424, 139, 211),
	array('Yezd', 'Land', 'No', 5, 272, 313, 120, 158),
	array('Dasht-I-Kavir', 'Land', 'No', 5, 133, 208, 68, 117),
	array('Meshed', 'Land', 'Yes', 5, 219, 156, 107, 85),
	array('Qom', 'Coast', 'No', 5, 19, 308, 11, 154),
	array('Elburz', 'Land', 'No', 5, 85, 153, 44, 68),
	array('Kara Kum', 'Land', 'No', 5, 230, 59, 99, 19),
	array('Balkh', 'Land', 'Yes', 4, 440, 182, 220, 82),
	array('Badakhshan', 'Land', 'Yes', 4, 629, 102, 296, 67),
	array('Ferghana', 'Land', 'No', 4, 717, 73, 357, 28),
	array('Kabul', 'Coast', 'Yes', 4, 588, 216, 306, 107),
	array('Peshawar', 'Coast', 'No', 4, 483, 355, 247, 168),
	array('Multan', 'Coast', 'Yes', 6, 619, 314, 286, 171),
	array('Bikaner', 'Coast', 'No', 6, 559, 413, 291, 204),
	array('Jaisalmer', 'Coast', 'Yes', 6, 513, 484, 257, 223),
	array('Jodhpur', 'Land', 'Yes', 6, 588, 525, 293, 263),
	array('Mewar', 'Land', 'No', 6, 649, 500, 322, 258),
	array('Ahmadnagar', 'Coast', 'Yes', 1, 582, 687, 307, 354),
	array('Bijapur', 'Land', 'Yes', 1, 672, 699, 335, 377),
	array('Goa', 'Coast', 'Yes', 1, 591, 760, 292, 385),
	array('Calicut', 'Coast', 'Yes', 7, 668, 869, 337, 435),
	array('Tinnevelly', 'Coast', 'No', 7, 694, 982, 345, 489),
	array('Pulicat', 'Coast', 'Yes', 7, 737, 909, 366, 451),
	array('Bangalore', 'Coast', 'Yes', 7, 793, 798, 392, 397),
	array('Jaffna', 'Coast', 'No', 7, 771, 988, 384, 491),
	array('Berar', 'Land', 'No', 3, 750, 590, 371, 289),
	array('Jabalpur', 'Land', 'Yes', 3, 853, 562, 409, 274),
	array('Raipur', 'Land', 'Yes', 3, 821, 633, 393, 324),
	array('Sambalpur', 'Coast', 'Yes', 3, 913, 629, 449, 300),
	array('Agra', 'Coast', 'Yes', 2, 743, 377, 367, 182),
	array('Awadh', 'Coast', 'Yes', 2, 803, 363, 408, 192),
	array('Muzaffarpur', 'Coast', 'Yes', 2, 965, 509, 474, 252),
	array('Nepal', 'Land', 'No', 2, 906, 374, 466, 189),
	array('Gartok', 'Land', 'No', 2, 850, 277, 419, 117),
	array('Persian Gulf', 'Sea', 'No', 0, 70, 543, 47, 275),
	array('Arabian Sea', 'Sea', 'No', 0, 370, 765, 189, 375),
	array('Laccadive Sea', 'Sea', 'No', 0, 539, 982, 217, 478),
	array('Gulf of Aden', 'Sea', 'No', 0, 111, 917, 53, 458),
	array('Maldive Sea', 'Sea', 'No', 0, 361, 1104, 204, 549),
	array('Sea of Ceylon', 'Sea', 'No', 0, 856, 1115, 469, 560),
	array('Nicobar Sea', 'Sea', 'No', 0, 949, 986, 476, 495),
	array('Bay of Bengal', 'Sea', 'No', 0, 991, 813, 485, 404),
	array('Andaman Sea', 'Sea', 'No', 0, 1201, 1029, 595, 499)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Hormuz','Sind','Yes','Yes'),
	array('Hormuz','Isfahan','Yes','Yes'),
	array('Hormuz','Shiraz','No','Yes'),
	array('Hormuz','Persian Gulf','Yes','No'),
	array('Hormuz','Arabian Sea','Yes','No'),
	array('Kashgar','Kashmir','No','Yes'),
	array('Kashgar','Ferghana','No','Yes'),
	array('Kashgar','Gartok','No','Yes'),
	array('Kashmir','Lahore','No','Yes'),
	array('Kashmir','Badakhshan','No','Yes'),
	array('Kashmir','Ferghana','No','Yes'),
	array('Kashmir','Kabul','No','Yes'),
	array('Kashmir','Agra','No','Yes'),
	array('Kashmir','Awadh','No','Yes'),
	array('Kashmir','Gartok','No','Yes'),
	array('Lahore','Jaipur','No','Yes'),
	array('Lahore','Kabul','Yes','Yes'),
	array('Lahore','Peshawar','Yes','Yes'),
	array('Lahore','Multan','Yes','Yes'),
	array('Lahore','Agra','No','Yes'),
	array('Jaipur','Malwa','No','Yes'),
	array('Jaipur','Benares','No','Yes'),
	array('Jaipur','Multan','No','Yes'),
	array('Jaipur','Bikaner','No','Yes'),
	array('Jaipur','Mewar','No','Yes'),
	array('Jaipur','Agra','No','Yes'),
	array('Malwa','Bidar','No','Yes'),
	array('Malwa','Benares','No','Yes'),
	array('Malwa','Ahmadabad','No','Yes'),
	array('Malwa','Mewar','No','Yes'),
	array('Malwa','Berar','No','Yes'),
	array('Bidar','Warangal','No','Yes'),
	array('Bidar','Honavar','No','Yes'),
	array('Bidar','Khandesh','No','Yes'),
	array('Bidar','Ahmadabad','No','Yes'),
	array('Bidar','Bijapur','No','Yes'),
	array('Bidar','Bangalore','No','Yes'),
	array('Bidar','Berar','No','Yes'),
	array('Bidar','Raipur','No','Yes'),
	array('Warangal','Orissa','No','Yes'),
	array('Warangal','Bangalore','No','Yes'),
	array('Warangal','Raipur','No','Yes'),
	array('Warangal','Sambalpur','No','Yes'),
	array('Benares','Bengal','Yes','Yes'),
	array('Benares','Berar','No','Yes'),
	array('Benares','Jabalpur','No','Yes'),
	array('Benares','Sambalpur','Yes','Yes'),
	array('Benares','Agra','Yes','Yes'),
	array('Benares','Muzaffarpur','Yes','Yes'),
	array('Orissa','Bengal','Yes','Yes'),
	array('Orissa','Bangalore','Yes','Yes'),
	array('Orissa','Sambalpur','Yes','Yes'),
	array('Orissa','Bay of Bengal','Yes','No'),
	array('Bengal','Assam','Yes','Yes'),
	array('Bengal','Pegu','Yes','Yes'),
	array('Bengal','Sambalpur','Yes','Yes'),
	array('Bengal','Muzaffarpur','Yes','Yes'),
	array('Bengal','Bay of Bengal','Yes','No'),
	array('Assam','Ava','No','Yes'),
	array('Assam','Pegu','No','Yes'),
	array('Assam','Muzaffarpur','Yes','Yes'),
	array('Ava','Pegu','Yes','Yes'),
	array('Ava','Ayutthaya','No','Yes'),
	array('Ava','Muzaffarpur','No','Yes'),
	array('Ava','Nepal','No','Yes'),
	array('Pegu','Ayutthaya','Yes','Yes'),
	array('Pegu','Bay of Bengal','Yes','No'),
	array('Ayutthaya','Kra','Yes','Yes'),
	array('Ayutthaya','Bay of Bengal','Yes','No'),
	array('Ayutthaya','Andaman Sea','Yes','No'),
	array('Kra','Andaman Sea','Yes','No'),
	array('Aceh','Sea of Ceylon','Yes','No'),
	array('Aceh','Nicobar Sea','Yes','No'),
	array('Aceh','Andaman Sea','Yes','No'),
	array('Kandy','Jaffna','Yes','Yes'),
	array('Kandy','Laccadive Sea','Yes','No'),
	array('Kandy','Maldive Sea','Yes','No'),
	array('Kandy','Sea of Ceylon','Yes','No'),
	array('Kandy','Nicobar Sea','Yes','No'),
	array('Honavar','Bijapur','No','Yes'),
	array('Honavar','Goa','Yes','Yes'),
	array('Honavar','Calicut','Yes','Yes'),
	array('Honavar','Bangalore','No','Yes'),
	array('Honavar','Laccadive Sea','Yes','No'),
	array('Khandesh','Ahmadabad','No','Yes'),
	array('Khandesh','Ahmadnagar','No','Yes'),
	array('Khandesh','Bijapur','No','Yes'),
	array('Ahmadabad','Gujarat','Yes','Yes'),
	array('Ahmadabad','Jodhpur','No','Yes'),
	array('Ahmadabad','Mewar','No','Yes'),
	array('Ahmadabad','Ahmadnagar','Yes','Yes'),
	array('Ahmadabad','Arabian Sea','Yes','No'),
	array('Gujarat','Sind','Yes','Yes'),
	array('Gujarat','Jaisalmer','No','Yes'),
	array('Gujarat','Jodhpur','No','Yes'),
	array('Gujarat','Arabian Sea','Yes','No'),
	array('Sind','Shiraz','No','Yes'),
	array('Sind','Peshawar','Yes','Yes'),
	array('Sind','Jaisalmer','Yes','Yes'),
	array('Sind','Arabian Sea','Yes','No'),
	array('Kandahar','Herat','No','Yes'),
	array('Kandahar','Shiraz','No','Yes'),
	array('Kandahar','Yezd','No','Yes'),
	array('Kandahar','Balkh','No','Yes'),
	array('Kandahar','Kabul','No','Yes'),
	array('Kandahar','Peshawar','No','Yes'),
	array('Herat','Bukhara','No','Yes'),
	array('Herat','Yezd','No','Yes'),
	array('Herat','Meshed','No','Yes'),
	array('Herat','Balkh','No','Yes'),
	array('Bukhara','Samarkand','No','Yes'),
	array('Bukhara','Meshed','No','Yes'),
	array('Bukhara','Kara Kum','No','Yes'),
	array('Bukhara','Balkh','No','Yes'),
	array('Samarkand','Balkh','No','Yes'),
	array('Samarkand','Badakhshan','No','Yes'),
	array('Samarkand','Ferghana','No','Yes'),
	array('Oman','Rub Al Khali','No','Yes'),
	array('Oman','Hadramaut','Yes','Yes'),
	array('Oman','Arabia','Yes','Yes'),
	array('Oman','Persian Gulf','Yes','No'),
	array('Oman','Arabian Sea','Yes','No'),
	array('Rub Al Khali','Hadramaut','No','Yes'),
	array('Rub Al Khali','Yemen','No','Yes'),
	array('Rub Al Khali','Arabia','No','Yes'),
	array('Hadramaut','Yemen','Yes','Yes'),
	array('Hadramaut','Arabian Sea','Yes','No'),
	array('Hadramaut','Gulf of Aden','Yes','No'),
	array('Yemen','Arabia','No','Yes'),
	array('Yemen','Gulf of Aden','Yes','No'),
	array('Arabia','Persian Gulf','Yes','No'),
	array('Seylac','Laccadive Sea','Yes','No'),
	array('Seylac','Gulf of Aden','Yes','No'),
	array('Seylac','Maldive Sea','Yes','No'),
	array('Isfahan','Shiraz','No','Yes'),
	array('Isfahan','Yezd','No','Yes'),
	array('Isfahan','Dasht-I-Kavir','No','Yes'),
	array('Isfahan','Qom','Yes','Yes'),
	array('Isfahan','Persian Gulf','Yes','No'),
	array('Shiraz','Yezd','No','Yes'),
	array('Shiraz','Peshawar','No','Yes'),
	array('Yezd','Dasht-I-Kavir','No','Yes'),
	array('Yezd','Meshed','No','Yes'),
	array('Dasht-I-Kavir','Meshed','No','Yes'),
	array('Dasht-I-Kavir','Qom','No','Yes'),
	array('Dasht-I-Kavir','Elburz','No','Yes'),
	array('Meshed','Elburz','No','Yes'),
	array('Meshed','Kara Kum','No','Yes'),
	array('Qom','Elburz','No','Yes'),
	array('Qom','Persian Gulf','Yes','No'),
	array('Elburz','Kara Kum','No','Yes'),
	array('Balkh','Badakhshan','No','Yes'),
	array('Balkh','Kabul','No','Yes'),
	array('Badakhshan','Ferghana','No','Yes'),
	array('Badakhshan','Kabul','No','Yes'),
	array('Kabul','Peshawar','Yes','Yes'),
	array('Peshawar','Multan','Yes','Yes'),
	array('Peshawar','Bikaner','Yes','Yes'),
	array('Peshawar','Jaisalmer','Yes','Yes'),
	array('Multan','Bikaner','Yes','Yes'),
	array('Bikaner','Jaisalmer','Yes','Yes'),
	array('Bikaner','Jodhpur','No','Yes'),
	array('Bikaner','Mewar','No','Yes'),
	array('Jaisalmer','Jodhpur','No','Yes'),
	array('Jodhpur','Mewar','No','Yes'),
	array('Ahmadnagar','Bijapur','No','Yes'),
	array('Ahmadnagar','Goa','Yes','Yes'),
	array('Ahmadnagar','Arabian Sea','Yes','No'),
	array('Bijapur','Goa','No','Yes'),
	array('Goa','Arabian Sea','Yes','No'),
	array('Goa','Laccadive Sea','Yes','No'),
	array('Calicut','Tinnevelly','Yes','Yes'),
	array('Calicut','Pulicat','No','Yes'),
	array('Calicut','Bangalore','No','Yes'),
	array('Calicut','Laccadive Sea','Yes','No'),
	array('Tinnevelly','Pulicat','Yes','Yes'),
	array('Tinnevelly','Laccadive Sea','Yes','No'),
	array('Tinnevelly','Nicobar Sea','Yes','No'),
	array('Pulicat','Bangalore','Yes','Yes'),
	array('Pulicat','Nicobar Sea','Yes','No'),
	array('Pulicat','Bay of Bengal','Yes','No'),
	array('Bangalore','Bay of Bengal','Yes','No'),
	array('Jaffna','Laccadive Sea','Yes','No'),
	array('Jaffna','Nicobar Sea','Yes','No'),
	array('Berar','Jabalpur','No','Yes'),
	array('Berar','Raipur','No','Yes'),
	array('Jabalpur','Raipur','No','Yes'),
	array('Jabalpur','Sambalpur','No','Yes'),
	array('Raipur','Sambalpur','No','Yes'),
	array('Agra','Awadh','Yes','Yes'),
	array('Agra','Muzaffarpur','Yes','Yes'),
	array('Awadh','Muzaffarpur','Yes','Yes'),
	array('Awadh','Nepal','No','Yes'),
	array('Awadh','Gartok','No','Yes'),
	array('Muzaffarpur','Nepal','No','Yes'),
	array('Nepal','Gartok','No','Yes'),
	array('Persian Gulf','Arabian Sea','Yes','No'),
	array('Arabian Sea','Laccadive Sea','Yes','No'),
	array('Arabian Sea','Gulf of Aden','Yes','No'),
	array('Laccadive Sea','Gulf of Aden','Yes','No'),
	array('Laccadive Sea','Maldive Sea','Yes','No'),
	array('Laccadive Sea','Nicobar Sea','Yes','No'),
	array('Maldive Sea','Sea of Ceylon','Yes','No'),
	array('Sea of Ceylon','Nicobar Sea','Yes','No'),
	array('Nicobar Sea','Bay of Bengal','Yes','No'),
	array('Nicobar Sea','Andaman Sea','Yes','No'),
	array('Bay of Bengal','Andaman Sea','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
