<?php
// This is file installs the map data for the Germany1648 variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Franche-Comte', 'Coast', 'Yes', 2, 291, 995, 146, 493),
	array('Western Spanish Netherlands', 'Coast', 'No', 2, 37, 474, 24, 244),
	array('Eastern Spanish Netherlands', 'Coast', 'Yes', 0, 212, 496, 100, 251),
	array('Bishopric of Luttich', 'Coast', 'No', 7, 281, 501, 141, 252),
	array('Duchy of Luxemburg', 'Coast', 'Yes', 2, 330, 619, 170, 315),
	array('Duchy of Bar', 'Coast', 'No', 0, 308, 675, 155, 338),
	array('Duchy of Lorraine', 'Coast', 'Yes', 0, 333, 787, 167, 395),
	array('Saarland', 'Coast', 'No', 0, 402, 723, 202, 358),
	array('Enheim', 'Coast', 'No', 5, 432, 779, 217, 391),
	array('Weissenburg', 'Coast', 'No', 0, 459, 718, 230, 357),
	array('Archbishopric of Trier', 'Coast', 'Yes', 7, 383, 635, 192, 319),
	array('Duchy of Julich', 'Coast', 'Yes', 5, 384, 516, 188, 259),
	array('Archbishopric of Cologne', 'Coast', 'Yes', 0, 382, 426, 192, 215),
	array('Far Spanish Netherlands', 'Coast', 'No', 2, 338, 430, 170, 215),
	array('Duchy of Cleves', 'Coast', 'No', 6, 394, 375, 197, 187),
	array('County of Mark', 'Coast', 'Yes', 6, 465, 432, 233, 216),
	array('Bishopric of Munster', 'Coast', 'Yes', 7, 445, 311, 224, 158),
	array('County of Lingen', 'Coast', 'No', 0, 485, 270, 241, 133),
	array('County of East Frisia', 'Coast', 'No', 0, 470, 162, 236, 80),
	array('County of Oldenburg', 'Coast', 'No', 0, 527, 194, 264, 96),
	array('Archbishopric of Bremen', 'Coast', 'Yes', 0, 603, 193, 303, 98),
	array('Holstein Gluckstadt', 'Coast', 'Yes', 0, 675, 104, 338, 53),
	array('Holstein Gottorp', 'Coast', 'No', 0, 675, 55, 336, 29),
	array('Duchy of Lauenburg', 'Coast', 'No', 0, 782, 148, 383, 60),
	array('Duchy of Meklenburg', 'Coast', 'No', 0, 890, 145, 445, 74),
	array('West Pomerania', 'Coast', 'No', 6, 888, 94, 448, 45),
	array('Duchy of Brunswick Luneburg', 'Coast', 'Yes', 0, 571, 250, 287, 126),
	array('Duchy of Kalenberg', 'Coast', 'No', 0, 670, 301, 335, 151),
	array('Electorate of Brandenburg', 'Coast', 'Yes', 6, 872, 235, 432, 117),
	array('Pomerania', 'Coast', 'No', 6, 1030, 161, 521, 55),
	array('Lisatia', 'Coast', 'No', 3, 1005, 424, 503, 212),
	array('Archbishopric of Magdeburg', 'Coast', 'Yes', 0, 767, 317, 383, 158),
	array('Bishopric of Hildeshein', 'Coast', 'No', 7, 716, 328, 359, 163),
	array('Principality of Anhalt', 'Coast', 'Yes', 0, 760, 362, 381, 182),
	array('County of Ravensberg', 'Coast', 'No', 6, 535, 330, 268, 165),
	array('County of Lippe', 'Coast', 'No', 0, 575, 339, 289, 168),
	array('Bishopric of Paderborn', 'Land', 'No', 7, 581, 397, 279, 192),
	array('Duchy of Westphalia', 'Coast', 'No', 7, 503, 435, 260, 215),
	array('Duchy of Berg', 'Coast', 'No', 5, 415, 420, 209, 210),
	array('County of Sayn', 'Coast', 'No', 0, 476, 499, 239, 248),
	array('Principality of Nassau', 'Coast', 'Yes', 0, 537, 545, 269, 273),
	array('Landgraviate of Hesse-Darmstadt', 'Coast', 'Yes', 0, 583, 502, 293, 252),
	array('Landgraviate of Hesse-Cassel', 'Coast', 'Yes', 0, 610, 440, 306, 222),
	array('Duchy of Brunswick Wolfenburger', 'Coast', 'Yes', 0, 688, 367, 345, 184),
	array('Eichsfeld', 'Coast', 'No', 7, 665, 433, 333, 220),
	array('Grafschaft Mansfeld', 'Coast', 'No', 0, 747, 398, 374, 199),
	array('Duchy of Saxony', 'Coast', 'Yes', 3, 726, 547, 365, 275),
	array('County of Schwarzburg', 'Coast', 'No', 5, 748, 481, 375, 243),
	array('Bishopric of Fulda', 'Coast', 'No', 7, 622, 527, 312, 263),
	array('Bishopric of Wurzburg', 'Coast', 'Yes', 0, 658, 607, 329, 306),
	array('Bishopric of Bamberg', 'Coast', 'No', 7, 738, 624, 370, 309),
	array('Margraviate of Bayreuth', 'Coast', 'No', 6, 788, 592, 392, 298),
	array('Principality of Pfalz-Sulzbach', 'Coast', 'No', 5, 807, 707, 405, 354),
	array('Electorate of Saxony', 'Coast', 'Yes', 3, 877, 369, 440, 184),
	array('County of Reuss', 'Coast', 'No', 5, 792, 526, 397, 263),
	array('Kingdom of Bohemia', 'Coast', 'Yes', 1, 998, 678, 499, 342),
	array('Duchy of Silesia', 'Coast', 'Yes', 0, 1280, 528, 641, 265),
	array('Margraviate of Moravia', 'Coast', 'No', 1, 1129, 695, 567, 347),
	array('Archduchy of Austria', 'Coast', 'Yes', 1, 1064, 843, 533, 424),
	array('Duchy of Styria', 'Coast', 'Yes', 0, 1117, 991, 560, 497),
	array('Duchy of Carinthia', 'Coast', 'No', 1, 977, 1044, 489, 523),
	array('Duchy of Carniola', 'Coast', 'No', 1, 1031, 1081, 518, 541),
	array('Archbishopric of Salzburg', 'Coast', 'Yes', 7, 908, 921, 456, 460),
	array('Ob Der Enns', 'Coast', 'No', 1, 985, 803, 492, 405),
	array('County of Tyrol', 'Coast', 'No', 1, 758, 1009, 380, 507),
	array('Bishopric of Trient', 'Coast', 'Yes', 0, 780, 1102, 375, 564),
	array('Electorate of Bavaria', 'Coast', 'Yes', 4, 766, 876, 386, 439),
	array('Bishopric of Regensburg', 'Coast', 'Yes', 4, 824, 626, 414, 315),
	array('Principality of Neuburg', 'Coast', 'Yes', 5, 756, 739, 378, 371),
	array('Margraviate of Ansbach', 'Coast', 'Yes', 6, 720, 712, 361, 357),
	array('County of Isenberg', 'Coast', 'No', 0, 599, 575, 300, 287),
	array('Hesse-Cassel Dependancy', 'Coast', 'No', 0, 481, 570, 242, 285),
	array('County of Sponheim', 'Coast', 'No', 7, 431, 600, 216, 300),
	array('Principality of Zweibrucken', 'Coast', 'Yes', 0, 443, 678, 222, 343),
	array('Western Electoral Palatinate', 'Coast', 'No', 5, 486, 651, 244, 327),
	array('Lower Electoral Palatinate', 'Coast', 'Yes', 0, 544, 615, 270, 307),
	array('Upper Electoral Palatinate', 'Coast', 'Yes', 5, 571, 675, 286, 339),
	array('Archbishopric of Mainz', 'Coast', 'Yes', 7, 601, 616, 299, 309),
	array('County of Hohenlohe', 'Coast', 'No', 0, 631, 712, 316, 355),
	array('Probstei Ellwangen', 'Coast', 'No', 7, 658, 758, 333, 378),
	array('Duchy of Wurttemberg', 'Coast', 'Yes', 0, 598, 779, 299, 387),
	array('Bishopric of Speyer', 'Coast', 'No', 7, 555, 705, 278, 352),
	array('Margraviate of Baden', 'Coast', 'No', 0, 507, 759, 254, 379),
	array('Bishopric of Strassburg', 'Coast', 'No', 7, 485, 812, 243, 406),
	array('Breisgau', 'Coast', 'No', 1, 477, 894, 238, 446),
	array('Memmingen', 'Coast', 'No', 7, 703, 840, 351, 420),
	array('Bishopric of Augsburg', 'Coast', 'Yes', 0, 706, 895, 353, 448),
	array('Lindau', 'Coast', 'No', 0, 668, 924, 335, 462),
	array('Duchy of Furstenberg', 'Coast', 'No', 0, 525, 863, 261, 433),
	array('Hohenzollern', 'Coast', 'No', 6, 579, 857, 290, 429),
	array('Biberach', 'Coast', 'No', 7, 650, 839, 328, 416),
	array('Lubeck #1', 'Land', 'Yes', 8, 713, 103, 358, 52),
	array('Hamburg #2', 'Land', 'Yes', 8, 669, 151, 336, 77),
	array('Bremen #3', 'Land', 'Yes', 8, 557, 199, 280, 100),
	array('Muhlhausen #4', 'Land', 'Yes', 8, 695, 439, 349, 220),
	array('Cologne #5', 'Land', 'Yes', 8, 415, 465, 209, 233),
	array('Aachen #6', 'Land', 'Yes', 8, 343, 491, 173, 246),
	array('Frankfurt am Main #7', 'Land', 'Yes', 8, 541, 591, 272, 296),
	array('Worms #8', 'Land', 'Yes', 8, 511, 653, 257, 327),
	array('Speyer #9', 'Land', 'Yes', 8, 487, 717, 245, 359),
	array('Strassburg #10', 'Land', 'Yes', 8, 461, 785, 232, 392),
	array('Ravensburg #11', 'Land', 'Yes', 8, 615, 881, 309, 441),
	array('Ulm #12', 'Land', 'Yes', 8, 649, 801, 326, 401),
	array('Augsburg #13', 'Land', 'Yes', 8, 737, 807, 370, 404),
	array('Nuremberg #14', 'Land', 'Yes', 8, 763, 669, 383, 335),
	array('Regensburg #15', 'Land', 'Yes', 8, 833, 727, 418, 363)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Franche-Comte','Duchy of Bar','Yes','No'),
	array('Franche-Comte','Duchy of Lorraine','Yes','Yes'),
	array('Franche-Comte','Saarland','Yes','No'),
	array('Franche-Comte','Enheim','Yes','No'),
	array('Franche-Comte','Duchy of Wurttemberg','Yes','No'),
	array('Franche-Comte','Margraviate of Baden','Yes','No'),
	array('Franche-Comte','Bishopric of Strassburg','Yes','Yes'),
	array('Franche-Comte','Breisgau','Yes','No'),
	array('Franche-Comte','Duchy of Furstenberg','Yes','No'),
	array('Western Spanish Netherlands','Eastern Spanish Netherlands','Yes','Yes'),
	array('Western Spanish Netherlands','Bishopric of Luttich','Yes','Yes'),
	array('Western Spanish Netherlands','Duchy of Luxemburg','Yes','No'),
	array('Western Spanish Netherlands','Duchy of Julich','Yes','No'),
	array('Western Spanish Netherlands','Far Spanish Netherlands','Yes','No'),
	array('Eastern Spanish Netherlands','Bishopric of Luttich','Yes','Yes'),
	array('Eastern Spanish Netherlands','Duchy of Luxemburg','Yes','No'),
	array('Eastern Spanish Netherlands','Duchy of Julich','Yes','No'),
	array('Eastern Spanish Netherlands','Far Spanish Netherlands','Yes','No'),
	array('Bishopric of Luttich','Duchy of Luxemburg','Yes','Yes'),
	array('Bishopric of Luttich','Duchy of Bar','Yes','No'),
	array('Bishopric of Luttich','Archbishopric of Trier','Yes','No'),
	array('Bishopric of Luttich','Duchy of Julich','Yes','Yes'),
	array('Bishopric of Luttich','Archbishopric of Cologne','Yes','No'),
	array('Bishopric of Luttich','Far Spanish Netherlands','Yes','Yes'),
	array('Bishopric of Luttich','Duchy of Cleves','Yes','No'),
	array('Bishopric of Luttich','Duchy of Berg','Yes','No'),
	array('Bishopric of Luttich','County of Sayn','Yes','No'),
	array('Duchy of Luxemburg','Duchy of Bar','Yes','Yes'),
	array('Duchy of Luxemburg','Duchy of Lorraine','Yes','No'),
	array('Duchy of Luxemburg','Saarland','Yes','No'),
	array('Duchy of Luxemburg','Archbishopric of Trier','Yes','Yes'),
	array('Duchy of Luxemburg','Duchy of Julich','Yes','Yes'),
	array('Duchy of Luxemburg','Archbishopric of Cologne','Yes','No'),
	array('Duchy of Luxemburg','Far Spanish Netherlands','Yes','No'),
	array('Duchy of Luxemburg','Duchy of Berg','Yes','No'),
	array('Duchy of Luxemburg','County of Sayn','Yes','No'),
	array('Duchy of Luxemburg','Principality of Nassau','Yes','No'),
	array('Duchy of Luxemburg','Hesse-Cassel Dependancy','Yes','No'),
	array('Duchy of Luxemburg','County of Sponheim','Yes','No'),
	array('Duchy of Luxemburg','Principality of Zweibrucken','Yes','No'),
	array('Duchy of Luxemburg','Aachen #6','No','Yes'),
	array('Duchy of Bar','Duchy of Lorraine','Yes','Yes'),
	array('Duchy of Bar','Saarland','Yes','No'),
	array('Duchy of Bar','Enheim','Yes','No'),
	array('Duchy of Bar','Archbishopric of Trier','Yes','No'),
	array('Duchy of Bar','Duchy of Julich','Yes','No'),
	array('Duchy of Bar','Bishopric of Strassburg','Yes','No'),
	array('Duchy of Lorraine','Saarland','Yes','Yes'),
	array('Duchy of Lorraine','Enheim','Yes','Yes'),
	array('Duchy of Lorraine','Weissenburg','Yes','No'),
	array('Duchy of Lorraine','Archbishopric of Trier','Yes','No'),
	array('Duchy of Lorraine','Principality of Zweibrucken','Yes','No'),
	array('Duchy of Lorraine','Duchy of Wurttemberg','Yes','No'),
	array('Duchy of Lorraine','Margraviate of Baden','Yes','No'),
	array('Duchy of Lorraine','Bishopric of Strassburg','Yes','Yes'),
	array('Duchy of Lorraine','Breisgau','Yes','No'),
	array('Duchy of Lorraine','Duchy of Furstenberg','Yes','No'),
	array('Saarland','Enheim','Yes','Yes'),
	array('Saarland','Weissenburg','Yes','Yes'),
	array('Saarland','Archbishopric of Trier','Yes','Yes'),
	array('Saarland','Duchy of Julich','Yes','No'),
	array('Saarland','County of Sayn','Yes','No'),
	array('Saarland','Principality of Nassau','Yes','No'),
	array('Saarland','Hesse-Cassel Dependancy','Yes','No'),
	array('Saarland','County of Sponheim','Yes','No'),
	array('Saarland','Principality of Zweibrucken','Yes','Yes'),
	array('Saarland','Western Electoral Palatinate','Yes','No'),
	array('Saarland','Upper Electoral Palatinate','Yes','No'),
	array('Saarland','Margraviate of Baden','Yes','No'),
	array('Saarland','Bishopric of Strassburg','Yes','No'),
	array('Enheim','Weissenburg','Yes','Yes'),
	array('Enheim','Archbishopric of Trier','Yes','No'),
	array('Enheim','Principality of Zweibrucken','Yes','No'),
	array('Enheim','Duchy of Wurttemberg','Yes','No'),
	array('Enheim','Margraviate of Baden','Yes','No'),
	array('Enheim','Bishopric of Strassburg','Yes','Yes'),
	array('Enheim','Breisgau','Yes','No'),
	array('Enheim','Duchy of Furstenberg','Yes','No'),
	array('Enheim','Strassburg #10','No','Yes'),
	array('Weissenburg','Archbishopric of Trier','Yes','No'),
	array('Weissenburg','County of Sponheim','Yes','No'),
	array('Weissenburg','Principality of Zweibrucken','Yes','Yes'),
	array('Weissenburg','Western Electoral Palatinate','Yes','No'),
	array('Weissenburg','Upper Electoral Palatinate','Yes','No'),
	array('Weissenburg','Duchy of Wurttemberg','Yes','No'),
	array('Weissenburg','Bishopric of Speyer','Yes','No'),
	array('Weissenburg','Margraviate of Baden','Yes','Yes'),
	array('Weissenburg','Bishopric of Strassburg','Yes','No'),
	array('Weissenburg','Speyer #9','No','Yes'),
	array('Archbishopric of Trier','Duchy of Julich','Yes','Yes'),
	array('Archbishopric of Trier','Archbishopric of Cologne','Yes','No'),
	array('Archbishopric of Trier','Far Spanish Netherlands','Yes','No'),
	array('Archbishopric of Trier','Duchy of Westphalia','Yes','No'),
	array('Archbishopric of Trier','Duchy of Berg','Yes','No'),
	array('Archbishopric of Trier','County of Sayn','Yes','Yes'),
	array('Archbishopric of Trier','Principality of Nassau','Yes','Yes'),
	array('Archbishopric of Trier','Landgraviate of Hesse-Darmstadt','Yes','No'),
	array('Archbishopric of Trier','County of Isenberg','Yes','No'),
	array('Archbishopric of Trier','Hesse-Cassel Dependancy','Yes','Yes'),
	array('Archbishopric of Trier','County of Sponheim','Yes','Yes'),
	array('Archbishopric of Trier','Principality of Zweibrucken','Yes','Yes'),
	array('Archbishopric of Trier','Western Electoral Palatinate','Yes','No'),
	array('Archbishopric of Trier','Lower Electoral Palatinate','Yes','No'),
	array('Archbishopric of Trier','Upper Electoral Palatinate','Yes','No'),
	array('Duchy of Julich','Archbishopric of Cologne','Yes','Yes'),
	array('Duchy of Julich','Far Spanish Netherlands','Yes','Yes'),
	array('Duchy of Julich','Duchy of Cleves','Yes','No'),
	array('Duchy of Julich','County of Mark','Yes','No'),
	array('Duchy of Julich','Bishopric of Munster','Yes','No'),
	array('Duchy of Julich','Duchy of Westphalia','Yes','No'),
	array('Duchy of Julich','Duchy of Berg','Yes','Yes'),
	array('Duchy of Julich','County of Sayn','Yes','Yes'),
	array('Duchy of Julich','Principality of Nassau','Yes','No'),
	array('Duchy of Julich','Hesse-Cassel Dependancy','Yes','No'),
	array('Duchy of Julich','County of Sponheim','Yes','No'),
	array('Duchy of Julich','Principality of Zweibrucken','Yes','No'),
	array('Duchy of Julich','Aachen #6','No','Yes'),
	array('Archbishopric of Cologne','Far Spanish Netherlands','Yes','Yes'),
	array('Archbishopric of Cologne','County of Mark','Yes','No'),
	array('Archbishopric of Cologne','Bishopric of Munster','Yes','No'),
	array('Archbishopric of Cologne','Duchy of Westphalia','Yes','No'),
	array('Archbishopric of Cologne','Duchy of Berg','Yes','Yes'),
	array('Archbishopric of Cologne','County of Sayn','Yes','No'),
	array('Archbishopric of Cologne','Principality of Nassau','Yes','No'),
	array('Archbishopric of Cologne','Cologne #5','No','Yes'),
	array('Far Spanish Netherlands','Duchy of Cleves','Yes','Yes'),
	array('Far Spanish Netherlands','County of Mark','Yes','No'),
	array('Far Spanish Netherlands','Bishopric of Munster','Yes','No'),
	array('Far Spanish Netherlands','Duchy of Westphalia','Yes','No'),
	array('Far Spanish Netherlands','Duchy of Berg','Yes','Yes'),
	array('Far Spanish Netherlands','County of Sayn','Yes','No'),
	array('Duchy of Cleves','County of Mark','Yes','No'),
	array('Duchy of Cleves','Bishopric of Munster','Yes','Yes'),
	array('Duchy of Cleves','County of Lingen','Yes','No'),
	array('Duchy of Cleves','County of East Frisia','Yes','No'),
	array('Duchy of Cleves','County of Oldenburg','Yes','No'),
	array('Duchy of Cleves','Duchy of Brunswick Luneburg','Yes','No'),
	array('Duchy of Cleves','County of Ravensberg','Yes','No'),
	array('Duchy of Cleves','Bishopric of Paderborn','Yes','No'),
	array('Duchy of Cleves','Duchy of Westphalia','Yes','No'),
	array('Duchy of Cleves','Duchy of Berg','Yes','Yes'),
	array('Duchy of Cleves','County of Sayn','Yes','No'),
	array('County of Mark','Bishopric of Munster','Yes','Yes'),
	array('County of Mark','County of Lingen','Yes','No'),
	array('County of Mark','County of East Frisia','Yes','No'),
	array('County of Mark','County of Oldenburg','Yes','No'),
	array('County of Mark','Duchy of Brunswick Luneburg','Yes','No'),
	array('County of Mark','County of Ravensberg','Yes','No'),
	array('County of Mark','Bishopric of Paderborn','Yes','No'),
	array('County of Mark','Duchy of Westphalia','Yes','Yes'),
	array('County of Mark','Duchy of Berg','Yes','Yes'),
	array('County of Mark','County of Sayn','Yes','No'),
	array('County of Mark','Principality of Nassau','Yes','No'),
	array('County of Mark','Landgraviate of Hesse-Darmstadt','Yes','No'),
	array('County of Mark','Landgraviate of Hesse-Cassel','Yes','No'),
	array('Bishopric of Munster','County of Lingen','Yes','Yes'),
	array('Bishopric of Munster','County of East Frisia','Yes','Yes'),
	array('Bishopric of Munster','County of Oldenburg','Yes','Yes'),
	array('Bishopric of Munster','Archbishopric of Bremen','Yes','No'),
	array('Bishopric of Munster','Holstein Gluckstadt','Yes','No'),
	array('Bishopric of Munster','Duchy of Lauenburg','Yes','No'),
	array('Bishopric of Munster','Duchy of Brunswick Luneburg','Yes','Yes'),
	array('Bishopric of Munster','Duchy of Kalenberg','Yes','No'),
	array('Bishopric of Munster','Electorate of Brandenburg','Yes','No'),
	array('Bishopric of Munster','Bishopric of Hildeshein','Yes','No'),
	array('Bishopric of Munster','County of Ravensberg','Yes','Yes'),
	array('Bishopric of Munster','County of Lippe','Yes','No'),
	array('Bishopric of Munster','Bishopric of Paderborn','Yes','Yes'),
	array('Bishopric of Munster','Duchy of Westphalia','Yes','Yes'),
	array('Bishopric of Munster','Duchy of Berg','Yes','Yes'),
	array('Bishopric of Munster','County of Sayn','Yes','No'),
	array('Bishopric of Munster','Principality of Nassau','Yes','No'),
	array('Bishopric of Munster','Landgraviate of Hesse-Darmstadt','Yes','No'),
	array('Bishopric of Munster','Landgraviate of Hesse-Cassel','Yes','No'),
	array('Bishopric of Munster','Duchy of Brunswick Wolfenburger','Yes','No'),
	array('County of Lingen','County of East Frisia','Yes','No'),
	array('County of Lingen','County of Oldenburg','Yes','No'),
	array('County of Lingen','Duchy of Brunswick Luneburg','Yes','No'),
	array('County of Lingen','County of Ravensberg','Yes','Yes'),
	array('County of Lingen','County of Lippe','Yes','No'),
	array('County of Lingen','Bishopric of Paderborn','Yes','No'),
	array('County of Lingen','Duchy of Westphalia','Yes','No'),
	array('County of Lingen','Duchy of Berg','Yes','No'),
	array('County of East Frisia','County of Oldenburg','Yes','Yes'),
	array('County of East Frisia','Archbishopric of Bremen','Yes','No'),
	array('County of East Frisia','Duchy of Brunswick Luneburg','Yes','No'),
	array('County of East Frisia','County of Ravensberg','Yes','No'),
	array('County of East Frisia','Bishopric of Paderborn','Yes','No'),
	array('County of East Frisia','Duchy of Westphalia','Yes','No'),
	array('County of East Frisia','Duchy of Berg','Yes','No'),
	array('County of Oldenburg','Archbishopric of Bremen','Yes','Yes'),
	array('County of Oldenburg','Holstein Gluckstadt','Yes','No'),
	array('County of Oldenburg','Duchy of Lauenburg','Yes','No'),
	array('County of Oldenburg','Duchy of Brunswick Luneburg','Yes','Yes'),
	array('County of Oldenburg','Duchy of Kalenberg','Yes','No'),
	array('County of Oldenburg','Electorate of Brandenburg','Yes','No'),
	array('County of Oldenburg','Bishopric of Hildeshein','Yes','No'),
	array('County of Oldenburg','County of Ravensberg','Yes','No'),
	array('County of Oldenburg','County of Lippe','Yes','No'),
	array('County of Oldenburg','Bishopric of Paderborn','Yes','No'),
	array('County of Oldenburg','Duchy of Westphalia','Yes','No'),
	array('County of Oldenburg','Duchy of Berg','Yes','No'),
	array('County of Oldenburg','Bremen #3','No','Yes'),
	array('Archbishopric of Bremen','Holstein Gluckstadt','Yes','Yes'),
	array('Archbishopric of Bremen','Holstein Gottorp','Yes','No'),
	array('Archbishopric of Bremen','Duchy of Lauenburg','Yes','No'),
	array('Archbishopric of Bremen','Duchy of Meklenburg','Yes','No'),
	array('Archbishopric of Bremen','Duchy of Brunswick Luneburg','Yes','Yes'),
	array('Archbishopric of Bremen','Duchy of Kalenberg','Yes','No'),
	array('Archbishopric of Bremen','Electorate of Brandenburg','Yes','No'),
	array('Archbishopric of Bremen','Bishopric of Hildeshein','Yes','No'),
	array('Archbishopric of Bremen','County of Ravensberg','Yes','No'),
	array('Archbishopric of Bremen','County of Lippe','Yes','No'),
	array('Archbishopric of Bremen','Bremen #3','No','Yes'),
	array('Holstein Gluckstadt','Holstein Gottorp','Yes','Yes'),
	array('Holstein Gluckstadt','Duchy of Lauenburg','Yes','Yes'),
	array('Holstein Gluckstadt','Duchy of Meklenburg','Yes','No'),
	array('Holstein Gluckstadt','Duchy of Brunswick Luneburg','Yes','Yes'),
	array('Holstein Gluckstadt','Duchy of Kalenberg','Yes','No'),
	array('Holstein Gluckstadt','Electorate of Brandenburg','Yes','No'),
	array('Holstein Gluckstadt','Bishopric of Hildeshein','Yes','No'),
	array('Holstein Gluckstadt','County of Ravensberg','Yes','No'),
	array('Holstein Gluckstadt','County of Lippe','Yes','No'),
	array('Holstein Gluckstadt','Lubeck #1','No','Yes'),
	array('Holstein Gluckstadt','Hamburg #2','No','Yes'),
	array('Holstein Gottorp','Duchy of Lauenburg','Yes','No'),
	array('Holstein Gottorp','Duchy of Brunswick Luneburg','Yes','No'),
	array('Holstein Gottorp','Lubeck #1','No','Yes'),
	array('Duchy of Lauenburg','Duchy of Meklenburg','Yes','Yes'),
	array('Duchy of Lauenburg','West Pomerania','Yes','No'),
	array('Duchy of Lauenburg','Duchy of Brunswick Luneburg','Yes','Yes'),
	array('Duchy of Lauenburg','Duchy of Kalenberg','Yes','No'),
	array('Duchy of Lauenburg','Electorate of Brandenburg','Yes','Yes'),
	array('Duchy of Lauenburg','Pomerania','Yes','No'),
	array('Duchy of Lauenburg','Lisatia','Yes','No'),
	array('Duchy of Lauenburg','Archbishopric of Magdeburg','Yes','No'),
	array('Duchy of Lauenburg','Bishopric of Hildeshein','Yes','No'),
	array('Duchy of Lauenburg','County of Ravensberg','Yes','No'),
	array('Duchy of Lauenburg','County of Lippe','Yes','No'),
	array('Duchy of Lauenburg','Electorate of Saxony','Yes','No'),
	array('Duchy of Lauenburg','Duchy of Silesia','Yes','No'),
	array('Duchy of Lauenburg','Lubeck #1','No','Yes'),
	array('Duchy of Lauenburg','Hamburg #2','No','Yes'),
	array('Duchy of Meklenburg','West Pomerania','Yes','Yes'),
	array('Duchy of Meklenburg','Duchy of Brunswick Luneburg','Yes','No'),
	array('Duchy of Meklenburg','Electorate of Brandenburg','Yes','Yes'),
	array('Duchy of Meklenburg','Pomerania','Yes','No'),
	array('Duchy of Meklenburg','Lisatia','Yes','No'),
	array('Duchy of Meklenburg','Archbishopric of Magdeburg','Yes','No'),
	array('Duchy of Meklenburg','Electorate of Saxony','Yes','No'),
	array('Duchy of Meklenburg','Duchy of Silesia','Yes','No'),
	array('West Pomerania','Duchy of Brunswick Luneburg','Yes','No'),
	array('West Pomerania','Electorate of Brandenburg','Yes','Yes'),
	array('West Pomerania','Pomerania','Yes','Yes'),
	array('West Pomerania','Lisatia','Yes','No'),
	array('West Pomerania','Archbishopric of Magdeburg','Yes','No'),
	array('West Pomerania','Bishopric of Hildeshein','Yes','No'),
	array('West Pomerania','Electorate of Saxony','Yes','No'),
	array('West Pomerania','Duchy of Silesia','Yes','No'),
	array('Duchy of Brunswick Luneburg','Duchy of Kalenberg','Yes','Yes'),
	array('Duchy of Brunswick Luneburg','Electorate of Brandenburg','Yes','Yes'),
	array('Duchy of Brunswick Luneburg','Pomerania','Yes','No'),
	array('Duchy of Brunswick Luneburg','Lisatia','Yes','No'),
	array('Duchy of Brunswick Luneburg','Archbishopric of Magdeburg','Yes','No'),
	array('Duchy of Brunswick Luneburg','Bishopric of Hildeshein','Yes','Yes'),
	array('Duchy of Brunswick Luneburg','Principality of Anhalt','Yes','No'),
	array('Duchy of Brunswick Luneburg','County of Ravensberg','Yes','Yes'),
	array('Duchy of Brunswick Luneburg','County of Lippe','Yes','Yes'),
	array('Duchy of Brunswick Luneburg','Bishopric of Paderborn','Yes','No'),
	array('Duchy of Brunswick Luneburg','Duchy of Westphalia','Yes','No'),
	array('Duchy of Brunswick Luneburg','Duchy of Berg','Yes','No'),
	array('Duchy of Brunswick Luneburg','Duchy of Brunswick Wolfenburger','Yes','No'),
	array('Duchy of Brunswick Luneburg','Grafschaft Mansfeld','Yes','No'),
	array('Duchy of Brunswick Luneburg','Electorate of Saxony','Yes','No'),
	array('Duchy of Brunswick Luneburg','Duchy of Silesia','Yes','No'),
	array('Duchy of Brunswick Luneburg','Hamburg #2','No','Yes'),
	array('Duchy of Brunswick Luneburg','Bremen #3','No','Yes'),
	array('Duchy of Kalenberg','Electorate of Brandenburg','Yes','No'),
	array('Duchy of Kalenberg','Archbishopric of Magdeburg','Yes','No'),
	array('Duchy of Kalenberg','Bishopric of Hildeshein','Yes','Yes'),
	array('Duchy of Kalenberg','Principality of Anhalt','Yes','No'),
	array('Duchy of Kalenberg','County of Ravensberg','Yes','No'),
	array('Duchy of Kalenberg','County of Lippe','Yes','Yes'),
	array('Duchy of Kalenberg','Bishopric of Paderborn','Yes','No'),
	array('Duchy of Kalenberg','Landgraviate of Hesse-Cassel','Yes','No'),
	array('Duchy of Kalenberg','Duchy of Brunswick Wolfenburger','Yes','Yes'),
	array('Duchy of Kalenberg','Eichsfeld','Yes','No'),
	array('Duchy of Kalenberg','Grafschaft Mansfeld','Yes','No'),
	array('Electorate of Brandenburg','Pomerania','Yes','Yes'),
	array('Electorate of Brandenburg','Lisatia','Yes','Yes'),
	array('Electorate of Brandenburg','Archbishopric of Magdeburg','Yes','Yes'),
	array('Electorate of Brandenburg','Bishopric of Hildeshein','Yes','Yes'),
	array('Electorate of Brandenburg','Principality of Anhalt','Yes','No'),
	array('Electorate of Brandenburg','County of Ravensberg','Yes','No'),
	array('Electorate of Brandenburg','County of Lippe','Yes','No'),
	array('Electorate of Brandenburg','Duchy of Brunswick Wolfenburger','Yes','No'),
	array('Electorate of Brandenburg','Eichsfeld','Yes','No'),
	array('Electorate of Brandenburg','Grafschaft Mansfeld','Yes','No'),
	array('Electorate of Brandenburg','Duchy of Saxony','Yes','No'),
	array('Electorate of Brandenburg','County of Schwarzburg','Yes','No'),
	array('Electorate of Brandenburg','Margraviate of Bayreuth','Yes','No'),
	array('Electorate of Brandenburg','Electorate of Saxony','Yes','Yes'),
	array('Electorate of Brandenburg','County of Reuss','Yes','No'),
	array('Electorate of Brandenburg','Kingdom of Bohemia','Yes','No'),
	array('Electorate of Brandenburg','Duchy of Silesia','Yes','Yes'),
	array('Electorate of Brandenburg','Margraviate of Moravia','Yes','No'),
	array('Pomerania','Lisatia','Yes','No'),
	array('Pomerania','Archbishopric of Magdeburg','Yes','No'),
	array('Pomerania','Bishopric of Hildeshein','Yes','No'),
	array('Pomerania','Electorate of Saxony','Yes','No'),
	array('Pomerania','Duchy of Silesia','Yes','No'),
	array('Lisatia','Archbishopric of Magdeburg','Yes','No'),
	array('Lisatia','Bishopric of Hildeshein','Yes','No'),
	array('Lisatia','Principality of Anhalt','Yes','No'),
	array('Lisatia','Eichsfeld','Yes','No'),
	array('Lisatia','Grafschaft Mansfeld','Yes','No'),
	array('Lisatia','Duchy of Saxony','Yes','No'),
	array('Lisatia','County of Schwarzburg','Yes','No'),
	array('Lisatia','Margraviate of Bayreuth','Yes','No'),
	array('Lisatia','Electorate of Saxony','Yes','Yes'),
	array('Lisatia','County of Reuss','Yes','No'),
	array('Lisatia','Kingdom of Bohemia','Yes','Yes'),
	array('Lisatia','Duchy of Silesia','Yes','Yes'),
	array('Lisatia','Margraviate of Moravia','Yes','No'),
	array('Lisatia','Archduchy of Austria','Yes','No'),
	array('Lisatia','Ob Der Enns','Yes','No'),
	array('Lisatia','Bishopric of Regensburg','Yes','No'),
	array('Archbishopric of Magdeburg','Bishopric of Hildeshein','Yes','Yes'),
	array('Archbishopric of Magdeburg','Principality of Anhalt','Yes','Yes'),
	array('Archbishopric of Magdeburg','Duchy of Brunswick Wolfenburger','Yes','No'),
	array('Archbishopric of Magdeburg','Eichsfeld','Yes','No'),
	array('Archbishopric of Magdeburg','Grafschaft Mansfeld','Yes','No'),
	array('Archbishopric of Magdeburg','Duchy of Saxony','Yes','No'),
	array('Archbishopric of Magdeburg','County of Schwarzburg','Yes','No'),
	array('Archbishopric of Magdeburg','Margraviate of Bayreuth','Yes','No'),
	array('Archbishopric of Magdeburg','Electorate of Saxony','Yes','Yes'),
	array('Archbishopric of Magdeburg','County of Reuss','Yes','No'),
	array('Archbishopric of Magdeburg','Kingdom of Bohemia','Yes','No'),
	array('Archbishopric of Magdeburg','Duchy of Silesia','Yes','No'),
	array('Bishopric of Hildeshein','Principality of Anhalt','Yes','Yes'),
	array('Bishopric of Hildeshein','County of Ravensberg','Yes','No'),
	array('Bishopric of Hildeshein','County of Lippe','Yes','No'),
	array('Bishopric of Hildeshein','Bishopric of Paderborn','Yes','No'),
	array('Bishopric of Hildeshein','Landgraviate of Hesse-Cassel','Yes','No'),
	array('Bishopric of Hildeshein','Duchy of Brunswick Wolfenburger','Yes','Yes'),
	array('Bishopric of Hildeshein','Eichsfeld','Yes','No'),
	array('Bishopric of Hildeshein','Grafschaft Mansfeld','Yes','Yes'),
	array('Bishopric of Hildeshein','Electorate of Saxony','Yes','No'),
	array('Bishopric of Hildeshein','Duchy of Silesia','Yes','No'),
	array('Principality of Anhalt','Duchy of Brunswick Wolfenburger','Yes','No'),
	array('Principality of Anhalt','Eichsfeld','Yes','No'),
	array('Principality of Anhalt','Grafschaft Mansfeld','Yes','Yes'),
	array('Principality of Anhalt','Duchy of Saxony','Yes','No'),
	array('Principality of Anhalt','County of Schwarzburg','Yes','No'),
	array('Principality of Anhalt','Margraviate of Bayreuth','Yes','No'),
	array('Principality of Anhalt','Electorate of Saxony','Yes','Yes'),
	array('Principality of Anhalt','County of Reuss','Yes','No'),
	array('Principality of Anhalt','Kingdom of Bohemia','Yes','No'),
	array('County of Ravensberg','County of Lippe','Yes','Yes'),
	array('County of Ravensberg','Bishopric of Paderborn','Yes','No'),
	array('County of Ravensberg','Duchy of Westphalia','Yes','No'),
	array('County of Ravensberg','Duchy of Berg','Yes','No'),
	array('County of Ravensberg','Duchy of Brunswick Wolfenburger','Yes','No'),
	array('County of Lippe','Bishopric of Paderborn','Yes','Yes'),
	array('County of Lippe','Duchy of Westphalia','Yes','No'),
	array('County of Lippe','Landgraviate of Hesse-Cassel','Yes','No'),
	array('County of Lippe','Duchy of Brunswick Wolfenburger','Yes','Yes'),
	array('County of Lippe','Eichsfeld','Yes','No'),
	array('County of Lippe','Grafschaft Mansfeld','Yes','No'),
	array('Bishopric of Paderborn','Duchy of Westphalia','Yes','Yes'),
	array('Bishopric of Paderborn','Duchy of Berg','Yes','No'),
	array('Bishopric of Paderborn','County of Sayn','Yes','No'),
	array('Bishopric of Paderborn','Principality of Nassau','Yes','No'),
	array('Bishopric of Paderborn','Landgraviate of Hesse-Darmstadt','Yes','No'),
	array('Bishopric of Paderborn','Landgraviate of Hesse-Cassel','Yes','Yes'),
	array('Bishopric of Paderborn','Duchy of Brunswick Wolfenburger','Yes','Yes'),
	array('Bishopric of Paderborn','Eichsfeld','Yes','No'),
	array('Bishopric of Paderborn','Grafschaft Mansfeld','Yes','No'),
	array('Bishopric of Paderborn','Duchy of Saxony','Yes','No'),
	array('Bishopric of Paderborn','Bishopric of Fulda','Yes','No'),
	array('Duchy of Westphalia','Duchy of Berg','Yes','Yes'),
	array('Duchy of Westphalia','County of Sayn','Yes','Yes'),
	array('Duchy of Westphalia','Principality of Nassau','Yes','Yes'),
	array('Duchy of Westphalia','Landgraviate of Hesse-Darmstadt','Yes','Yes'),
	array('Duchy of Westphalia','Landgraviate of Hesse-Cassel','Yes','Yes'),
	array('Duchy of Westphalia','Duchy of Brunswick Wolfenburger','Yes','No'),
	array('Duchy of Westphalia','Eichsfeld','Yes','No'),
	array('Duchy of Westphalia','Duchy of Saxony','Yes','No'),
	array('Duchy of Westphalia','Bishopric of Fulda','Yes','No'),
	array('Duchy of Westphalia','County of Isenberg','Yes','No'),
	array('Duchy of Westphalia','Hesse-Cassel Dependancy','Yes','No'),
	array('Duchy of Berg','County of Sayn','Yes','Yes'),
	array('Duchy of Berg','Principality of Nassau','Yes','No'),
	array('Duchy of Berg','Landgraviate of Hesse-Darmstadt','Yes','No'),
	array('Duchy of Berg','Landgraviate of Hesse-Cassel','Yes','No'),
	array('Duchy of Berg','Cologne #5','No','Yes'),
	array('County of Sayn','Principality of Nassau','Yes','Yes'),
	array('County of Sayn','Landgraviate of Hesse-Darmstadt','Yes','No'),
	array('County of Sayn','Landgraviate of Hesse-Cassel','Yes','No'),
	array('County of Sayn','County of Isenberg','Yes','No'),
	array('County of Sayn','Hesse-Cassel Dependancy','Yes','No'),
	array('County of Sayn','County of Sponheim','Yes','No'),
	array('County of Sayn','Principality of Zweibrucken','Yes','No'),
	array('Principality of Nassau','Landgraviate of Hesse-Darmstadt','Yes','Yes'),
	array('Principality of Nassau','Landgraviate of Hesse-Cassel','Yes','No'),
	array('Principality of Nassau','Bishopric of Fulda','Yes','No'),
	array('Principality of Nassau','Bishopric of Wurzburg','Yes','No'),
	array('Principality of Nassau','County of Isenberg','Yes','Yes'),
	array('Principality of Nassau','Hesse-Cassel Dependancy','Yes','Yes'),
	array('Principality of Nassau','County of Sponheim','Yes','No'),
	array('Principality of Nassau','Principality of Zweibrucken','Yes','No'),
	array('Principality of Nassau','Lower Electoral Palatinate','Yes','No'),
	array('Principality of Nassau','Archbishopric of Mainz','Yes','No'),
	array('Principality of Nassau','Frankfurt am Main #7','No','Yes'),
	array('Landgraviate of Hesse-Darmstadt','Landgraviate of Hesse-Cassel','Yes','Yes'),
	array('Landgraviate of Hesse-Darmstadt','Duchy of Brunswick Wolfenburger','Yes','No'),
	array('Landgraviate of Hesse-Darmstadt','Eichsfeld','Yes','No'),
	array('Landgraviate of Hesse-Darmstadt','Duchy of Saxony','Yes','No'),
	array('Landgraviate of Hesse-Darmstadt','Bishopric of Fulda','Yes','Yes'),
	array('Landgraviate of Hesse-Darmstadt','Bishopric of Wurzburg','Yes','No'),
	array('Landgraviate of Hesse-Darmstadt','County of Isenberg','Yes','Yes'),
	array('Landgraviate of Hesse-Darmstadt','Hesse-Cassel Dependancy','Yes','No'),
	array('Landgraviate of Hesse-Darmstadt','Archbishopric of Mainz','Yes','No'),
	array('Landgraviate of Hesse-Cassel','Duchy of Brunswick Wolfenburger','Yes','Yes'),
	array('Landgraviate of Hesse-Cassel','Eichsfeld','Yes','Yes'),
	array('Landgraviate of Hesse-Cassel','Grafschaft Mansfeld','Yes','No'),
	array('Landgraviate of Hesse-Cassel','Duchy of Saxony','Yes','Yes'),
	array('Landgraviate of Hesse-Cassel','County of Schwarzburg','Yes','No'),
	array('Landgraviate of Hesse-Cassel','Bishopric of Fulda','Yes','Yes'),
	array('Landgraviate of Hesse-Cassel','Bishopric of Wurzburg','Yes','No'),
	array('Landgraviate of Hesse-Cassel','Bishopric of Bamberg','Yes','No'),
	array('Landgraviate of Hesse-Cassel','Electorate of Saxony','Yes','No'),
	array('Landgraviate of Hesse-Cassel','County of Reuss','Yes','No'),
	array('Landgraviate of Hesse-Cassel','County of Isenberg','Yes','No'),
	array('Duchy of Brunswick Wolfenburger','Eichsfeld','Yes','Yes'),
	array('Duchy of Brunswick Wolfenburger','Grafschaft Mansfeld','Yes','Yes'),
	array('Duchy of Brunswick Wolfenburger','Duchy of Saxony','Yes','No'),
	array('Duchy of Brunswick Wolfenburger','Bishopric of Fulda','Yes','No'),
	array('Duchy of Brunswick Wolfenburger','Electorate of Saxony','Yes','No'),
	array('Duchy of Brunswick Wolfenburger','Muhlhausen #4','No','Yes'),
	array('Eichsfeld','Grafschaft Mansfeld','Yes','No'),
	array('Eichsfeld','Duchy of Saxony','Yes','Yes'),
	array('Eichsfeld','County of Schwarzburg','Yes','No'),
	array('Eichsfeld','Bishopric of Fulda','Yes','No'),
	array('Eichsfeld','Bishopric of Wurzburg','Yes','No'),
	array('Eichsfeld','Bishopric of Bamberg','Yes','No'),
	array('Eichsfeld','Margraviate of Bayreuth','Yes','No'),
	array('Eichsfeld','Electorate of Saxony','Yes','Yes'),
	array('Eichsfeld','County of Reuss','Yes','No'),
	array('Eichsfeld','Kingdom of Bohemia','Yes','No'),
	array('Eichsfeld','Muhlhausen #4','No','Yes'),
	array('Grafschaft Mansfeld','Duchy of Saxony','Yes','No'),
	array('Grafschaft Mansfeld','County of Schwarzburg','Yes','No'),
	array('Grafschaft Mansfeld','Margraviate of Bayreuth','Yes','No'),
	array('Grafschaft Mansfeld','Electorate of Saxony','Yes','Yes'),
	array('Grafschaft Mansfeld','County of Reuss','Yes','No'),
	array('Grafschaft Mansfeld','Kingdom of Bohemia','Yes','No'),
	array('Grafschaft Mansfeld','Muhlhausen #4','No','Yes'),
	array('Duchy of Saxony','County of Schwarzburg','Yes','Yes'),
	array('Duchy of Saxony','Bishopric of Fulda','Yes','Yes'),
	array('Duchy of Saxony','Bishopric of Wurzburg','Yes','Yes'),
	array('Duchy of Saxony','Bishopric of Bamberg','Yes','Yes'),
	array('Duchy of Saxony','Margraviate of Bayreuth','Yes','No'),
	array('Duchy of Saxony','Principality of Pfalz-Sulzbach','Yes','No'),
	array('Duchy of Saxony','Electorate of Saxony','Yes','Yes'),
	array('Duchy of Saxony','County of Reuss','Yes','Yes'),
	array('Duchy of Saxony','Kingdom of Bohemia','Yes','No'),
	array('Duchy of Saxony','Margraviate of Ansbach','Yes','No'),
	array('Duchy of Saxony','County of Isenberg','Yes','No'),
	array('Duchy of Saxony','Archbishopric of Mainz','Yes','No'),
	array('Duchy of Saxony','County of Hohenlohe','Yes','No'),
	array('County of Schwarzburg','Bishopric of Fulda','Yes','No'),
	array('County of Schwarzburg','Bishopric of Wurzburg','Yes','No'),
	array('County of Schwarzburg','Bishopric of Bamberg','Yes','No'),
	array('County of Schwarzburg','Margraviate of Bayreuth','Yes','No'),
	array('County of Schwarzburg','Electorate of Saxony','Yes','Yes'),
	array('County of Schwarzburg','County of Reuss','Yes','No'),
	array('County of Schwarzburg','Kingdom of Bohemia','Yes','No'),
	array('Bishopric of Fulda','Bishopric of Wurzburg','Yes','Yes'),
	array('Bishopric of Fulda','Bishopric of Bamberg','Yes','No'),
	array('Bishopric of Fulda','Electorate of Saxony','Yes','No'),
	array('Bishopric of Fulda','County of Reuss','Yes','No'),
	array('Bishopric of Fulda','Margraviate of Ansbach','Yes','No'),
	array('Bishopric of Fulda','County of Isenberg','Yes','Yes'),
	array('Bishopric of Fulda','Archbishopric of Mainz','Yes','No'),
	array('Bishopric of Fulda','County of Hohenlohe','Yes','No'),
	array('Bishopric of Wurzburg','Bishopric of Bamberg','Yes','Yes'),
	array('Bishopric of Wurzburg','Margraviate of Bayreuth','Yes','No'),
	array('Bishopric of Wurzburg','Principality of Pfalz-Sulzbach','Yes','No'),
	array('Bishopric of Wurzburg','Electorate of Saxony','Yes','No'),
	array('Bishopric of Wurzburg','County of Reuss','Yes','No'),
	array('Bishopric of Wurzburg','Electorate of Bavaria','Yes','No'),
	array('Bishopric of Wurzburg','Principality of Neuburg','Yes','No'),
	array('Bishopric of Wurzburg','Margraviate of Ansbach','Yes','Yes'),
	array('Bishopric of Wurzburg','County of Isenberg','Yes','Yes'),
	array('Bishopric of Wurzburg','Lower Electoral Palatinate','Yes','No'),
	array('Bishopric of Wurzburg','Upper Electoral Palatinate','Yes','No'),
	array('Bishopric of Wurzburg','Archbishopric of Mainz','Yes','Yes'),
	array('Bishopric of Wurzburg','County of Hohenlohe','Yes','Yes'),
	array('Bishopric of Wurzburg','Probstei Ellwangen','Yes','No'),
	array('Bishopric of Wurzburg','Duchy of Wurttemberg','Yes','No'),
	array('Bishopric of Bamberg','Margraviate of Bayreuth','Yes','Yes'),
	array('Bishopric of Bamberg','Principality of Pfalz-Sulzbach','Yes','Yes'),
	array('Bishopric of Bamberg','Electorate of Saxony','Yes','No'),
	array('Bishopric of Bamberg','County of Reuss','Yes','Yes'),
	array('Bishopric of Bamberg','Kingdom of Bohemia','Yes','No'),
	array('Bishopric of Bamberg','Electorate of Bavaria','Yes','No'),
	array('Bishopric of Bamberg','Bishopric of Regensburg','Yes','No'),
	array('Bishopric of Bamberg','Principality of Neuburg','Yes','No'),
	array('Bishopric of Bamberg','Margraviate of Ansbach','Yes','Yes'),
	array('Bishopric of Bamberg','County of Isenberg','Yes','No'),
	array('Bishopric of Bamberg','Archbishopric of Mainz','Yes','No'),
	array('Bishopric of Bamberg','County of Hohenlohe','Yes','No'),
	array('Bishopric of Bamberg','Probstei Ellwangen','Yes','No'),
	array('Bishopric of Bamberg','Nuremberg #14','No','Yes'),
	array('Margraviate of Bayreuth','Principality of Pfalz-Sulzbach','Yes','Yes'),
	array('Margraviate of Bayreuth','Electorate of Saxony','Yes','Yes'),
	array('Margraviate of Bayreuth','County of Reuss','Yes','Yes'),
	array('Margraviate of Bayreuth','Kingdom of Bohemia','Yes','Yes'),
	array('Margraviate of Bayreuth','Duchy of Silesia','Yes','No'),
	array('Margraviate of Bayreuth','Margraviate of Moravia','Yes','No'),
	array('Margraviate of Bayreuth','Archduchy of Austria','Yes','No'),
	array('Margraviate of Bayreuth','Ob Der Enns','Yes','No'),
	array('Margraviate of Bayreuth','Electorate of Bavaria','Yes','No'),
	array('Margraviate of Bayreuth','Bishopric of Regensburg','Yes','Yes'),
	array('Margraviate of Bayreuth','Margraviate of Ansbach','Yes','No'),
	array('Principality of Pfalz-Sulzbach','Electorate of Saxony','Yes','No'),
	array('Principality of Pfalz-Sulzbach','County of Reuss','Yes','No'),
	array('Principality of Pfalz-Sulzbach','Kingdom of Bohemia','Yes','No'),
	array('Principality of Pfalz-Sulzbach','Archbishopric of Salzburg','Yes','No'),
	array('Principality of Pfalz-Sulzbach','Ob Der Enns','Yes','No'),
	array('Principality of Pfalz-Sulzbach','County of Tyrol','Yes','No'),
	array('Principality of Pfalz-Sulzbach','Electorate of Bavaria','Yes','Yes'),
	array('Principality of Pfalz-Sulzbach','Bishopric of Regensburg','Yes','Yes'),
	array('Principality of Pfalz-Sulzbach','Principality of Neuburg','Yes','No'),
	array('Principality of Pfalz-Sulzbach','Margraviate of Ansbach','Yes','No'),
	array('Principality of Pfalz-Sulzbach','Memmingen','Yes','No'),
	array('Principality of Pfalz-Sulzbach','Bishopric of Augsburg','Yes','No'),
	array('Principality of Pfalz-Sulzbach','Nuremberg #14','No','Yes'),
	array('Principality of Pfalz-Sulzbach','Regensburg #15','No','Yes'),
	array('Electorate of Saxony','County of Reuss','Yes','Yes'),
	array('Electorate of Saxony','Kingdom of Bohemia','Yes','Yes'),
	array('Electorate of Saxony','Duchy of Silesia','Yes','No'),
	array('Electorate of Saxony','Margraviate of Moravia','Yes','No'),
	array('Electorate of Saxony','Archduchy of Austria','Yes','No'),
	array('Electorate of Saxony','Ob Der Enns','Yes','No'),
	array('Electorate of Saxony','Bishopric of Regensburg','Yes','No'),
	array('Electorate of Saxony','Muhlhausen #4','No','Yes'),
	array('County of Reuss','Kingdom of Bohemia','Yes','No'),
	array('County of Reuss','Bishopric of Regensburg','Yes','No'),
	array('County of Reuss','Margraviate of Ansbach','Yes','No'),
	array('Kingdom of Bohemia','Duchy of Silesia','Yes','Yes'),
	array('Kingdom of Bohemia','Margraviate of Moravia','Yes','Yes'),
	array('Kingdom of Bohemia','Archduchy of Austria','Yes','Yes'),
	array('Kingdom of Bohemia','Duchy of Styria','Yes','No'),
	array('Kingdom of Bohemia','Archbishopric of Salzburg','Yes','No'),
	array('Kingdom of Bohemia','Ob Der Enns','Yes','Yes'),
	array('Kingdom of Bohemia','Electorate of Bavaria','Yes','No'),
	array('Kingdom of Bohemia','Bishopric of Regensburg','Yes','Yes'),
	array('Duchy of Silesia','Margraviate of Moravia','Yes','Yes'),
	array('Duchy of Silesia','Archduchy of Austria','Yes','No'),
	array('Duchy of Silesia','Ob Der Enns','Yes','No'),
	array('Duchy of Silesia','Bishopric of Regensburg','Yes','No'),
	array('Margraviate of Moravia','Archduchy of Austria','Yes','Yes'),
	array('Margraviate of Moravia','Duchy of Styria','Yes','No'),
	array('Margraviate of Moravia','Ob Der Enns','Yes','No'),
	array('Margraviate of Moravia','Bishopric of Regensburg','Yes','No'),
	array('Archduchy of Austria','Duchy of Styria','Yes','Yes'),
	array('Archduchy of Austria','Duchy of Carinthia','Yes','No'),
	array('Archduchy of Austria','Duchy of Carniola','Yes','No'),
	array('Archduchy of Austria','Archbishopric of Salzburg','Yes','No'),
	array('Archduchy of Austria','Ob Der Enns','Yes','Yes'),
	array('Archduchy of Austria','Electorate of Bavaria','Yes','No'),
	array('Archduchy of Austria','Bishopric of Regensburg','Yes','No'),
	array('Duchy of Styria','Duchy of Carinthia','Yes','Yes'),
	array('Duchy of Styria','Duchy of Carniola','Yes','Yes'),
	array('Duchy of Styria','Archbishopric of Salzburg','Yes','Yes'),
	array('Duchy of Styria','Ob Der Enns','Yes','Yes'),
	array('Duchy of Styria','County of Tyrol','Yes','No'),
	array('Duchy of Styria','Electorate of Bavaria','Yes','No'),
	array('Duchy of Styria','Bishopric of Regensburg','Yes','No'),
	array('Duchy of Carinthia','Duchy of Carniola','Yes','Yes'),
	array('Duchy of Carinthia','Archbishopric of Salzburg','Yes','Yes'),
	array('Duchy of Carinthia','Ob Der Enns','Yes','No'),
	array('Duchy of Carinthia','County of Tyrol','Yes','Yes'),
	array('Duchy of Carinthia','Bishopric of Trient','Yes','No'),
	array('Duchy of Carinthia','Electorate of Bavaria','Yes','No'),
	array('Duchy of Carinthia','Bishopric of Augsburg','Yes','No'),
	array('Duchy of Carinthia','Lindau','Yes','No'),
	array('Duchy of Carniola','Archbishopric of Salzburg','Yes','No'),
	array('Duchy of Carniola','Ob Der Enns','Yes','No'),
	array('Duchy of Carniola','County of Tyrol','Yes','No'),
	array('Archbishopric of Salzburg','Ob Der Enns','Yes','Yes'),
	array('Archbishopric of Salzburg','County of Tyrol','Yes','Yes'),
	array('Archbishopric of Salzburg','Bishopric of Trient','Yes','No'),
	array('Archbishopric of Salzburg','Electorate of Bavaria','Yes','Yes'),
	array('Archbishopric of Salzburg','Bishopric of Regensburg','Yes','No'),
	array('Archbishopric of Salzburg','Principality of Neuburg','Yes','No'),
	array('Archbishopric of Salzburg','Margraviate of Ansbach','Yes','No'),
	array('Archbishopric of Salzburg','Memmingen','Yes','No'),
	array('Archbishopric of Salzburg','Bishopric of Augsburg','Yes','No'),
	array('Archbishopric of Salzburg','Lindau','Yes','No'),
	array('Ob Der Enns','County of Tyrol','Yes','No'),
	array('Ob Der Enns','Electorate of Bavaria','Yes','Yes'),
	array('Ob Der Enns','Bishopric of Regensburg','Yes','Yes'),
	array('Ob Der Enns','Principality of Neuburg','Yes','No'),
	array('Ob Der Enns','Margraviate of Ansbach','Yes','No'),
	array('Ob Der Enns','Memmingen','Yes','No'),
	array('Ob Der Enns','Bishopric of Augsburg','Yes','No'),
	array('County of Tyrol','Bishopric of Trient','Yes','Yes'),
	array('County of Tyrol','Electorate of Bavaria','Yes','Yes'),
	array('County of Tyrol','Bishopric of Regensburg','Yes','No'),
	array('County of Tyrol','Principality of Neuburg','Yes','No'),
	array('County of Tyrol','Margraviate of Ansbach','Yes','No'),
	array('County of Tyrol','Memmingen','Yes','No'),
	array('County of Tyrol','Bishopric of Augsburg','Yes','Yes'),
	array('County of Tyrol','Lindau','Yes','Yes'),
	array('County of Tyrol','Hohenzollern','Yes','No'),
	array('County of Tyrol','Biberach','Yes','No'),
	array('Bishopric of Trient','Electorate of Bavaria','Yes','No'),
	array('Bishopric of Trient','Bishopric of Augsburg','Yes','No'),
	array('Bishopric of Trient','Lindau','Yes','No'),
	array('Electorate of Bavaria','Bishopric of Regensburg','Yes','Yes'),
	array('Electorate of Bavaria','Principality of Neuburg','Yes','Yes'),
	array('Electorate of Bavaria','Margraviate of Ansbach','Yes','Yes'),
	array('Electorate of Bavaria','County of Hohenlohe','Yes','No'),
	array('Electorate of Bavaria','Probstei Ellwangen','Yes','No'),
	array('Electorate of Bavaria','Memmingen','Yes','Yes'),
	array('Electorate of Bavaria','Bishopric of Augsburg','Yes','Yes'),
	array('Electorate of Bavaria','Lindau','Yes','No'),
	array('Electorate of Bavaria','Biberach','Yes','No'),
	array('Electorate of Bavaria','Augsburg #13','No','Yes'),
	array('Electorate of Bavaria','Nuremberg #14','No','Yes'),
	array('Electorate of Bavaria','Regensburg #15','No','Yes'),
	array('Bishopric of Regensburg','Principality of Neuburg','Yes','No'),
	array('Bishopric of Regensburg','Margraviate of Ansbach','Yes','No'),
	array('Bishopric of Regensburg','Memmingen','Yes','No'),
	array('Bishopric of Regensburg','Bishopric of Augsburg','Yes','No'),
	array('Bishopric of Regensburg','Regensburg #15','No','Yes'),
	array('Principality of Neuburg','Margraviate of Ansbach','Yes','Yes'),
	array('Principality of Neuburg','County of Hohenlohe','Yes','No'),
	array('Principality of Neuburg','Probstei Ellwangen','Yes','Yes'),
	array('Principality of Neuburg','Duchy of Wurttemberg','Yes','No'),
	array('Principality of Neuburg','Memmingen','Yes','Yes'),
	array('Principality of Neuburg','Bishopric of Augsburg','Yes','No'),
	array('Principality of Neuburg','Lindau','Yes','No'),
	array('Principality of Neuburg','Hohenzollern','Yes','No'),
	array('Principality of Neuburg','Biberach','Yes','Yes'),
	array('Principality of Neuburg','Ulm #12','No','Yes'),
	array('Principality of Neuburg','Augsburg #13','No','Yes'),
	array('Margraviate of Ansbach','County of Isenberg','Yes','No'),
	array('Margraviate of Ansbach','Archbishopric of Mainz','Yes','No'),
	array('Margraviate of Ansbach','County of Hohenlohe','Yes','Yes'),
	array('Margraviate of Ansbach','Probstei Ellwangen','Yes','Yes'),
	array('Margraviate of Ansbach','Duchy of Wurttemberg','Yes','No'),
	array('Margraviate of Ansbach','Memmingen','Yes','No'),
	array('Margraviate of Ansbach','Bishopric of Augsburg','Yes','No'),
	array('Margraviate of Ansbach','Biberach','Yes','No'),
	array('Margraviate of Ansbach','Nuremberg #14','No','Yes'),
	array('County of Isenberg','Hesse-Cassel Dependancy','Yes','No'),
	array('County of Isenberg','Lower Electoral Palatinate','Yes','No'),
	array('County of Isenberg','Upper Electoral Palatinate','Yes','No'),
	array('County of Isenberg','Archbishopric of Mainz','Yes','Yes'),
	array('County of Isenberg','County of Hohenlohe','Yes','No'),
	array('County of Isenberg','Duchy of Wurttemberg','Yes','No'),
	array('County of Isenberg','Frankfurt am Main #7','No','Yes'),
	array('Hesse-Cassel Dependancy','County of Sponheim','Yes','Yes'),
	array('Hesse-Cassel Dependancy','Principality of Zweibrucken','Yes','No'),
	array('Hesse-Cassel Dependancy','Western Electoral Palatinate','Yes','No'),
	array('Hesse-Cassel Dependancy','Lower Electoral Palatinate','Yes','Yes'),
	array('Hesse-Cassel Dependancy','Upper Electoral Palatinate','Yes','No'),
	array('Hesse-Cassel Dependancy','Archbishopric of Mainz','Yes','No'),
	array('Hesse-Cassel Dependancy','Frankfurt am Main #7','No','Yes'),
	array('County of Sponheim','Principality of Zweibrucken','Yes','Yes'),
	array('County of Sponheim','Western Electoral Palatinate','Yes','Yes'),
	array('County of Sponheim','Lower Electoral Palatinate','Yes','Yes'),
	array('County of Sponheim','Upper Electoral Palatinate','Yes','No'),
	array('County of Sponheim','Archbishopric of Mainz','Yes','No'),
	array('Principality of Zweibrucken','Western Electoral Palatinate','Yes','Yes'),
	array('Principality of Zweibrucken','Lower Electoral Palatinate','Yes','No'),
	array('Principality of Zweibrucken','Upper Electoral Palatinate','Yes','Yes'),
	array('Principality of Zweibrucken','Archbishopric of Mainz','Yes','No'),
	array('Principality of Zweibrucken','Duchy of Wurttemberg','Yes','No'),
	array('Principality of Zweibrucken','Bishopric of Speyer','Yes','No'),
	array('Principality of Zweibrucken','Margraviate of Baden','Yes','No'),
	array('Principality of Zweibrucken','Speyer #9','No','Yes'),
	array('Western Electoral Palatinate','Lower Electoral Palatinate','Yes','Yes'),
	array('Western Electoral Palatinate','Upper Electoral Palatinate','Yes','Yes'),
	array('Western Electoral Palatinate','Archbishopric of Mainz','Yes','No'),
	array('Western Electoral Palatinate','Duchy of Wurttemberg','Yes','No'),
	array('Western Electoral Palatinate','Bishopric of Speyer','Yes','No'),
	array('Western Electoral Palatinate','Worms #8','No','Yes'),
	array('Lower Electoral Palatinate','Upper Electoral Palatinate','Yes','Yes'),
	array('Lower Electoral Palatinate','Archbishopric of Mainz','Yes','Yes'),
	array('Lower Electoral Palatinate','County of Hohenlohe','Yes','No'),
	array('Lower Electoral Palatinate','Duchy of Wurttemberg','Yes','No'),
	array('Lower Electoral Palatinate','Bishopric of Speyer','Yes','No'),
	array('Lower Electoral Palatinate','Frankfurt am Main #7','No','Yes'),
	array('Lower Electoral Palatinate','Worms #8','No','Yes'),
	array('Upper Electoral Palatinate','Archbishopric of Mainz','Yes','Yes'),
	array('Upper Electoral Palatinate','County of Hohenlohe','Yes','No'),
	array('Upper Electoral Palatinate','Probstei Ellwangen','Yes','No'),
	array('Upper Electoral Palatinate','Duchy of Wurttemberg','Yes','Yes'),
	array('Upper Electoral Palatinate','Bishopric of Speyer','Yes','Yes'),
	array('Upper Electoral Palatinate','Margraviate of Baden','Yes','No'),
	array('Upper Electoral Palatinate','Bishopric of Strassburg','Yes','No'),
	array('Upper Electoral Palatinate','Duchy of Furstenberg','Yes','No'),
	array('Upper Electoral Palatinate','Hohenzollern','Yes','No'),
	array('Upper Electoral Palatinate','Biberach','Yes','No'),
	array('Upper Electoral Palatinate','Worms #8','No','Yes'),
	array('Upper Electoral Palatinate','Speyer #9','No','Yes'),
	array('Archbishopric of Mainz','County of Hohenlohe','Yes','Yes'),
	array('Archbishopric of Mainz','Probstei Ellwangen','Yes','No'),
	array('Archbishopric of Mainz','Duchy of Wurttemberg','Yes','Yes'),
	array('Archbishopric of Mainz','Bishopric of Speyer','Yes','No'),
	array('Archbishopric of Mainz','Margraviate of Baden','Yes','No'),
	array('Archbishopric of Mainz','Bishopric of Strassburg','Yes','No'),
	array('Archbishopric of Mainz','Duchy of Furstenberg','Yes','No'),
	array('Archbishopric of Mainz','Hohenzollern','Yes','No'),
	array('Archbishopric of Mainz','Biberach','Yes','No'),
	array('Archbishopric of Mainz','Frankfurt am Main #7','No','Yes'),
	array('County of Hohenlohe','Probstei Ellwangen','Yes','Yes'),
	array('County of Hohenlohe','Duchy of Wurttemberg','Yes','Yes'),
	array('County of Hohenlohe','Bishopric of Speyer','Yes','No'),
	array('County of Hohenlohe','Margraviate of Baden','Yes','No'),
	array('County of Hohenlohe','Bishopric of Strassburg','Yes','No'),
	array('County of Hohenlohe','Duchy of Furstenberg','Yes','No'),
	array('County of Hohenlohe','Hohenzollern','Yes','No'),
	array('County of Hohenlohe','Biberach','Yes','No'),
	array('Probstei Ellwangen','Duchy of Wurttemberg','Yes','Yes'),
	array('Probstei Ellwangen','Bishopric of Speyer','Yes','No'),
	array('Probstei Ellwangen','Margraviate of Baden','Yes','No'),
	array('Probstei Ellwangen','Bishopric of Strassburg','Yes','No'),
	array('Probstei Ellwangen','Memmingen','Yes','No'),
	array('Probstei Ellwangen','Duchy of Furstenberg','Yes','No'),
	array('Probstei Ellwangen','Hohenzollern','Yes','No'),
	array('Probstei Ellwangen','Biberach','Yes','No'),
	array('Probstei Ellwangen','Ulm #12','No','Yes'),
	array('Duchy of Wurttemberg','Bishopric of Speyer','Yes','Yes'),
	array('Duchy of Wurttemberg','Margraviate of Baden','Yes','Yes'),
	array('Duchy of Wurttemberg','Bishopric of Strassburg','Yes','Yes'),
	array('Duchy of Wurttemberg','Breisgau','Yes','No'),
	array('Duchy of Wurttemberg','Memmingen','Yes','No'),
	array('Duchy of Wurttemberg','Bishopric of Augsburg','Yes','No'),
	array('Duchy of Wurttemberg','Lindau','Yes','No'),
	array('Duchy of Wurttemberg','Duchy of Furstenberg','Yes','Yes'),
	array('Duchy of Wurttemberg','Hohenzollern','Yes','Yes'),
	array('Duchy of Wurttemberg','Biberach','Yes','Yes'),
	array('Duchy of Wurttemberg','Ulm #12','No','Yes'),
	array('Bishopric of Speyer','Margraviate of Baden','Yes','Yes'),
	array('Bishopric of Speyer','Bishopric of Strassburg','Yes','No'),
	array('Bishopric of Speyer','Duchy of Furstenberg','Yes','No'),
	array('Bishopric of Speyer','Hohenzollern','Yes','No'),
	array('Bishopric of Speyer','Biberach','Yes','No'),
	array('Bishopric of Speyer','Speyer #9','No','Yes'),
	array('Margraviate of Baden','Bishopric of Strassburg','Yes','Yes'),
	array('Margraviate of Baden','Breisgau','Yes','No'),
	array('Margraviate of Baden','Duchy of Furstenberg','Yes','No'),
	array('Margraviate of Baden','Hohenzollern','Yes','No'),
	array('Margraviate of Baden','Biberach','Yes','No'),
	array('Margraviate of Baden','Speyer #9','No','Yes'),
	array('Margraviate of Baden','Strassburg #10','No','Yes'),
	array('Bishopric of Strassburg','Breisgau','Yes','Yes'),
	array('Bishopric of Strassburg','Duchy of Furstenberg','Yes','Yes'),
	array('Bishopric of Strassburg','Hohenzollern','Yes','No'),
	array('Bishopric of Strassburg','Biberach','Yes','No'),
	array('Bishopric of Strassburg','Strassburg #10','No','Yes'),
	array('Breisgau','Duchy of Furstenberg','Yes','Yes'),
	array('Breisgau','Hohenzollern','Yes','No'),
	array('Memmingen','Bishopric of Augsburg','Yes','Yes'),
	array('Memmingen','Lindau','Yes','No'),
	array('Memmingen','Hohenzollern','Yes','No'),
	array('Memmingen','Biberach','Yes','Yes'),
	array('Memmingen','Ulm #12','No','Yes'),
	array('Memmingen','Augsburg #13','No','Yes'),
	array('Bishopric of Augsburg','Lindau','Yes','Yes'),
	array('Bishopric of Augsburg','Hohenzollern','Yes','No'),
	array('Bishopric of Augsburg','Biberach','Yes','Yes'),
	array('Lindau','Duchy of Furstenberg','Yes','No'),
	array('Lindau','Hohenzollern','Yes','Yes'),
	array('Lindau','Biberach','Yes','Yes'),
	array('Lindau','Ravensburg #11','No','Yes'),
	array('Duchy of Furstenberg','Hohenzollern','Yes','Yes'),
	array('Duchy of Furstenberg','Biberach','Yes','No'),
	array('Hohenzollern','Biberach','Yes','Yes'),
	array('Hohenzollern','Ravensburg #11','No','Yes'),
	array('Biberach','Ravensburg #11','No','Yes'),
	array('Biberach','Ulm #12','No','Yes')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
