<?php
// This is file installs the map data for the Viking variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Lapland', 'Coast', 'No', 0, 652, 73, 429, 48),
	array('White Sea', 'Sea', 'No', 0, 860, 78, 566, 51),
	array('Arkhangelsk', 'Coast', 'Yes', 6, 888, 152, 584, 100),
	array('Bjarmaland', 'Coast', 'No', 0, 804, 87, 529, 57),
	array('Vardoeyhus', 'Coast', 'Yes', 0, 710, 52, 467, 34),
	array('Abruzzi', 'Coast', 'No', 2, 565, 651, 372, 428),
	array('Aegean Sea', 'Sea', 'No', 0, 787, 721, 518, 474),
	array('Aldeigjuborg', 'Coast', 'Yes', 8, 809, 231, 532, 152),
	array('Alexandria', 'Coast', 'Yes', 9, 898, 882, 591, 580),
	array('Alsace', 'Land', 'No', 2, 435, 471, 286, 310),
	array('Ancona', 'Coast', 'Yes', 0, 545, 611, 362, 406),
	array('Ankara', 'Coast', 'Yes', 4, 939, 642, 618, 422),
	array('Antakya', 'Coast', 'Yes', 1, 1035, 740, 681, 487),
	array('Asturias', 'Coast', 'No', 0, 155, 541, 102, 356),
	array('Athinai', 'Coast', 'Yes', 4, 731, 756, 481, 497),
	array('Auvergne', 'Land', 'No', 2, 377, 518, 248, 341),
	array('Avignon', 'Coast', 'Yes', 2, 330, 587, 217, 386),
	array('Baltic Sea', 'Sea', 'No', 0, 648, 336, 426, 221),
	array('Barca', 'Coast', 'No', 1, 711, 835, 468, 549),
	array('Barents Sea', 'Sea', 'No', 0, 611, 32, 402, 21),
	array('Bavaria', 'Land', 'No', 5, 527, 464, 347, 305),
	array('Bay of Biscay', 'Sea', 'No', 0, 230, 535, 151, 352),
	array('Beograd', 'Land', 'Yes', 6, 711, 620, 468, 408),
	array('Berber Coast', 'Sea', 'No', 0, 264, 704, 174, 463),
	array('Birka', 'Coast', 'Yes', 8, 629, 281, 414, 185),
	array('Bornholmer Sea', 'Sea', 'No', 0, 582, 348, 383, 229),
	array('Brandenburg', 'Land', 'Yes', 0, 546, 417, 359, 274),
	array('Breslau', 'Land', 'Yes', 6, 631, 409, 415, 269),
	array('Bretagne', 'Coast', 'No', 5, 245, 418, 161, 275),
	array('Bruges', 'Coast', 'Yes', 0, 410, 382, 270, 251),
	array('Buda', 'Land', 'Yes', 9, 638, 556, 420, 366),
	array('Burgos', 'Coast', 'Yes', 0, 213, 564, 140, 371),
	array('Burta', 'Land', 'No', 6, 945, 410, 622, 270),
	array('Cagliari', 'Coast', 'Yes', 0, 439, 666, 289, 438),
	array('Catalonia', 'Coast', 'No', 0, 252, 634, 166, 417),
	array('Champagne', 'Land', 'No', 5, 366, 503, 241, 331),
	array('Charsiana', 'Land', 'No', 4, 941, 695, 619, 457),
	array('Cherson Bight', 'Sea', 'No', 0, 906, 541, 596, 356),
	array('Cordoba', 'Coast', 'Yes', 1, 220, 680, 145, 447),
	array('Cornwall', 'Coast', 'No', 0, 301, 366, 198, 241),
	array('Cumaniya', 'Coast', 'No', 6, 907, 491, 597, 323),
	array('Cypriot Sea', 'Sea', 'No', 0, 997, 788, 656, 518),
	array('Dogger Bank', 'Sea', 'No', 0, 486, 315, 320, 207),
	array('Dorestad', 'Coast', 'Yes', 3, 436, 360, 287, 237),
	array('Dyvlin', 'Coast', 'Yes', 7, 245, 298, 161, 196),
	array('Eastern Adriatic Sea', 'Sea', 'No', 0, 576, 610, 379, 401),
	array('Eastern Mediterranean Sea', 'Sea', 'No', 0, 815, 819, 536, 539),
	array('English Channel', 'Sea', 'No', 0, 319, 391, 210, 257),
	array('Essex', 'Coast', 'No', 0, 375, 347, 247, 228),
	array('Flanders', 'Land', 'No', 2, 438, 407, 288, 268),
	array('Frankfurt', 'Land', 'Yes', 5, 503, 461, 331, 303),
	array('Zurich', 'Land', 'Yes', 0, 435, 496, 286, 326),
	array('Westmorland', 'Land', 'No', 3, 344, 313, 226, 206),
	array('Western Mediterranean Sea', 'Sea', 'No', 0, 383, 693, 252, 456),
	array('Western Adriatic Sea', 'Sea', 'No', 0, 617, 667, 406, 439),
	array('Wales', 'Coast', 'No', 0, 306, 325, 201, 214),
	array('Vladimir', 'Coast', 'Yes', 6, 1040, 345, 684, 227),
	array('Vitebsk', 'Land', 'Yes', 6, 766, 345, 504, 227),
	array('Visby', 'Coast', 'Yes', 8, 661, 290, 435, 191),
	array('Viatka', 'Land', 'No', 6, 1047, 225, 689, 148),
	array('Verdun', 'Land', 'Yes', 2, 407, 473, 268, 311),
	array('Venezia', 'Coast', 'Yes', 4, 530, 564, 349, 371),
	array('Valakia', 'Land', 'No', 6, 815, 549, 536, 361),
	array('Uppsala', 'Coast', 'Yes', 8, 637, 195, 419, 128),
	array('Tyrrhenian Sea', 'Sea', 'No', 0, 552, 721, 363, 474),
	array('Tunis', 'Coast', 'Yes', 1, 404, 765, 280, 547),
	array('Trebizond', 'Coast', 'Yes', 1, 1088, 596, 716, 392),
	array('Transylvania', 'Land', 'No', 0, 731, 547, 481, 360),
	array('Tours', 'Land', 'Yes', 5, 334, 500, 220, 329),
	array('Toulouse', 'Coast', 'Yes', 5, 274, 547, 180, 360),
	array('Tiundaland', 'Land', 'No', 8, 610, 207, 401, 136),
	array('Tirol', 'Land', 'No', 5, 529, 506, 348, 333),
	array('Thessaly', 'Coast', 'No', 4, 763, 663, 502, 436),
	array('Tarsus', 'Coast', 'Yes', 0, 973, 718, 640, 472),
	array('Taron', 'Land', 'No', 1, 1070, 672, 704, 442),
	array('Syracuse', 'Coast', 'Yes', 4, 532, 762, 348, 510),
	array('Strathclyde', 'Coast', 'No', 0, 321, 252, 211, 166),
	array('Strait of Sicily', 'Sea', 'No', 0, 468, 737, 308, 485),
	array('St. Gallen', 'Land', 'Yes', 5, 477, 499, 314, 328),
	array('Spalato', 'Coast', 'Yes', 4, 593, 582, 390, 383),
	array('South Black Sea', 'Sea', 'No', 0, 938, 607, 617, 399),
	array('Smyrna', 'Coast', 'Yes', 4, 844, 730, 555, 480),
	array('Smolensk', 'Land', 'Yes', 0, 819, 360, 539, 237),
	array('Skiringssal', 'Coast', 'Yes', 7, 547, 225, 360, 148),
	array('Skegness', 'Coast', 'Yes', 3, 366, 321, 241, 211),
	array('Skagerrak', 'Sea', 'No', 0, 530, 266, 349, 175),
	array('Skaalholt', 'Coast', 'Yes', 7, 292, 74, 189, 47),
	array('Sevilla', 'Coast', 'Yes', 1, 141, 687, 93, 452),
	array('Serkland', 'Coast', 'No', 1, 196, 757, 129, 498),
	array('Segovia', 'Land', 'No', 1, 176, 605, 116, 398),
	array('Sea of England', 'Sea', 'No', 0, 421, 336, 277, 221),
	array('Scotland', 'Coast', 'No', 0, 356, 225, 234, 148),
	array('Savoie', 'Land', 'No', 2, 406, 517, 267, 340),
	array('Ruthenia', 'Land', 'No', 6, 768, 468, 505, 308),
	array('Rouen', 'Coast', 'Yes', 3, 369, 409, 243, 269),
	array('Rostov', 'Coast', 'Yes', 8, 900, 275, 592, 181),
	array('Roma', 'Coast', 'Yes', 2, 541, 669, 356, 440),
	array('Reval', 'Coast', 'Yes', 3, 739, 271, 486, 178),
	array('Ranrike', 'Coast', 'No', 7, 578, 234, 380, 154),
	array('Ragusa', 'Coast', 'Yes', 0, 648, 625, 426, 411),
	array('Przemysl', 'Land', 'Yes', 6, 769, 400, 506, 263),
	array('Prussia', 'Land', 'No', 6, 717, 383, 472, 252),
	array('Praha', 'Land', 'Yes', 6, 626, 476, 412, 313),
	array('Pommern', 'Coast', 'No', 3, 635, 365, 418, 240),
	array('Pisa', 'Coast', 'Yes', 2, 489, 604, 322, 397),
	array('Pest', 'Land', 'Yes', 9, 693, 511, 456, 336),
	array('Paristria', 'Coast', 'No', 4, 830, 593, 546, 390),
	array('Paris', 'Land', 'Yes', 5, 369, 468, 243, 308),
	array('Palmyra', 'Coast', 'Yes', 1, 1052, 784, 692, 516),
	array('Palma', 'Coast', 'Yes', 0, 325, 657, 214, 432),
	array('Palestine', 'Land', 'No', 1, 1099, 830, 723, 546),
	array('Palermo', 'Coast', 'Yes', 1, 503, 746, 331, 491),
	array('Osterbotten', 'Coast', 'No', 8, 711, 234, 468, 154),
	array('Oldenburg', 'Land', 'No', 0, 499, 407, 328, 268),
	array('Oerne', 'Coast', 'No', 3, 567, 321, 373, 211),
	array('Norwegian Sea', 'Sea', 'No', 0, 448, 105, 295, 69),
	array('North Sea', 'Sea', 'No', 0, 424, 246, 279, 162),
	array('North Black Sea', 'Sea', 'No', 0, 1002, 555, 659, 365),
	array('Noirmoutier', 'Coast', 'Yes', 7, 278, 468, 196, 312),
	array('Nidaros', 'Coast', 'Yes', 7, 578, 135, 380, 89),
	array('Napoli', 'Coast', 'Yes', 4, 600, 730, 395, 480),
	array('Nantes', 'Coast', 'Yes', 5, 289, 505, 190, 332),
	array('Muscovy', 'Land', 'No', 6, 906, 213, 596, 140),
	array('Mordvin', 'Land', 'No', 6, 885, 334, 582, 220),
	array('Miklagard', 'Coast', 'Yes', 4, 860, 646, 566, 425),
	array('Mid Atlantic Ocean', 'Sea', 'No', 0, 143, 433, 94, 285),
	array('Memel', 'Coast', 'Yes', 0, 717, 322, 472, 212),
	array('Mecklenburg', 'Coast', 'No', 0, 553, 368, 364, 242),
	array('Marseilles', 'Coast', 'Yes', 2, 377, 584, 248, 384),
	array('Mainz', 'Land', 'Yes', 0, 456, 483, 300, 318),
	array('Maine', 'Land', 'No', 5, 322, 464, 212, 305),
	array('Macedonia', 'Coast', 'No', 0, 690, 687, 454, 452),
	array('London', 'Land', 'Yes', 9, 351, 344, 231, 226),
	array('Lombardy', 'Land', 'No', 2, 496, 555, 326, 365),
	array('Lisboa', 'Coast', 'Yes', 1, 122, 597, 80, 393),
	array('Ligurian Sea', 'Sea', 'No', 0, 471, 634, 310, 417),
	array('Libyan Sea', 'Sea', 'No', 0, 538, 801, 354, 527),
	array('Kvenland', 'Coast', 'No', 0, 724, 128, 476, 84),
	array('Koln', 'Land', 'Yes', 2, 458, 414, 301, 272),
	array('Kjonugard', 'Coast', 'Yes', 8, 853, 418, 561, 275),
	array('Kirkby', 'Coast', 'Yes', 7, 321, 289, 211, 190),
	array('Khazar Empire', 'Coast', 'No', 0, 1050, 491, 691, 323),
	array('Kattegat', 'Sea', 'No', 0, 562, 283, 370, 186),
	array('Katanes', 'Coast', 'Yes', 7, 331, 198, 218, 130),
	array('Karelia', 'Land', 'No', 6, 838, 219, 551, 144),
	array('Kalmar', 'Coast', 'Yes', 3, 599, 303, 394, 199),
	array('Kaffa', 'Coast', 'Yes', 6, 974, 499, 641, 328),
	array('Jylland', 'Coast', 'No', 3, 515, 290, 339, 191),
	array('Jorvik', 'Coast', 'Yes', 3, 365, 290, 240, 191),
	array('Jorsal', 'Coast', 'Yes', 9, 1017, 848, 669, 558),
	array('Jomsborg', 'Coast', 'Yes', 3, 582, 389, 383, 256),
	array('Jemtland', 'Land', 'No', 7, 605, 149, 398, 98),
	array('Irish Sea', 'Sea', 'No', 0, 261, 330, 172, 217),
	array('Ionian Sea', 'Sea', 'No', 0, 660, 733, 402, 518),
	array('Ingermannland', 'Coast', 'No', 8, 790, 272, 520, 179),
	array('Hordaland', 'Coast', 'No', 7, 508, 184, 334, 121),
	array('Holmgard', 'Coast', 'Yes', 8, 845, 287, 556, 189),
	array('Hibernian Sea', 'Sea', 'No', 0, 327, 161, 215, 106),
	array('Hessen', 'Land', 'No', 5, 518, 412, 341, 271),
	array('Helsingjaland', 'Coast', 'No', 8, 664, 144, 437, 95),
	array('Hedeby', 'Coast', 'Yes', 3, 514, 327, 338, 215),
	array('Hastings', 'Coast', 'Yes', 0, 327, 366, 215, 241),
	array('Hamburg', 'Coast', 'Yes', 5, 502, 365, 330, 240),
	array('Hafrsfjord', 'Coast', 'Yes', 7, 497, 233, 327, 153),
	array('Gulf of Lyons', 'Sea', 'No', 0, 339, 628, 223, 413),
	array('Gulf of Finland', 'Sea', 'No', 0, 710, 255, 467, 168),
	array('Gulf of Cadiz', 'Sea', 'No', 0, 46, 660, 30, 434),
	array('Gulf of Bothnia', 'Sea', 'No', 0, 676, 236, 445, 155),
	array('Groningen', 'Coast', 'Yes', 2, 471, 357, 310, 235),
	array('Graz', 'Land', 'Yes', 5, 576, 496, 379, 326),
	array('Goteborg', 'Coast', 'Yes', 0, 582, 275, 383, 181),
	array('Genova', 'Coast', 'Yes', 2, 442, 558, 291, 367),
	array('Gdansk', 'Coast', 'Yes', 8, 666, 362, 438, 238),
	array('Gardarike', 'Coast', 'No', 8, 862, 354, 567, 233),
	array('Lindisfarne', 'Coast', 'Yes', 0, 340, 263, 224, 173),
	array('norge', 'Coast', 'No', 7, 78, 816, 51, 537),
	array('demark', 'Coast', 'No', 3, 68, 833, 51, 551),
	array('sverige', 'Coast', 'No', 8, 167, 846, 51, 564),
	array('france', 'Coast', 'No', 5, 132, 858, 52, 577),
	array('burgandy', 'Coast', 'No', 2, 287, 815, 189, 536),
	array('est rom emp', 'Coast', 'No', 4, 280, 836, 184, 550),
	array('ar cal', 'Coast', 'No', 1, 271, 847, 196, 563),
	array('sl nat', 'Coast', 'No', 6, 263, 861, 197, 577),
	array('North Atlantic Ocean', 'Sea', 'No', 0, 242, 231, 159, 152)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Lapland','Bjarmaland','No','Yes'),
	array('Lapland','Vardoeyhus','Yes','Yes'),
	array('Lapland','Barents Sea','Yes','No'),
	array('Lapland','Nidaros','Yes','Yes'),
	array('Lapland','Kvenland','No','Yes'),
	array('Lapland','Jemtland','No','Yes'),
	array('Lapland','Helsingjaland','No','Yes'),
	array('White Sea','Arkhangelsk','Yes','No'),
	array('White Sea','Bjarmaland','Yes','No'),
	array('White Sea','Barents Sea','Yes','No'),
	array('Arkhangelsk','Bjarmaland','Yes','Yes'),
	array('Arkhangelsk','Viatka','No','Yes'),
	array('Arkhangelsk','Muscovy','No','Yes'),
	array('Arkhangelsk','Karelia','No','Yes'),
	array('Bjarmaland','Vardoeyhus','Yes','Yes'),
	array('Bjarmaland','Barents Sea','Yes','No'),
	array('Bjarmaland','Kvenland','No','Yes'),
	array('Bjarmaland','Karelia','No','Yes'),
	array('Vardoeyhus','Barents Sea','Yes','No'),
	array('Abruzzi','Ancona','Yes','Yes'),
	array('Abruzzi','Western Adriatic Sea','Yes','No'),
	array('Abruzzi','Roma','No','Yes'),
	array('Abruzzi','Pisa','No','Yes'),
	array('Abruzzi','Napoli','Yes','Yes'),
	array('Aegean Sea','Athinai','Yes','No'),
	array('Aegean Sea','Eastern Mediterranean Sea','Yes','No'),
	array('Aegean Sea','Thessaly','Yes','No'),
	array('Aegean Sea','Smyrna','Yes','No'),
	array('Aegean Sea','Miklagard','Yes','No'),
	array('Aegean Sea','Ionian Sea','Yes','No'),
	array('Aldeigjuborg','Osterbotten','Yes','Yes'),
	array('Aldeigjuborg','Kvenland','No','Yes'),
	array('Aldeigjuborg','Karelia','No','Yes'),
	array('Aldeigjuborg','Ingermannland','Yes','Yes'),
	array('Aldeigjuborg','Holmgard','Yes','Yes'),
	array('Aldeigjuborg','Gulf of Finland','Yes','No'),
	array('Alexandria','Barca','Yes','Yes'),
	array('Alexandria','Eastern Mediterranean Sea','Yes','No'),
	array('Alexandria','Jorsal','Yes','Yes'),
	array('Alsace','Frankfurt','No','Yes'),
	array('Alsace','Zurich','No','Yes'),
	array('Alsace','Verdun','No','Yes'),
	array('Alsace','Mainz','No','Yes'),
	array('Alsace','Koln','No','Yes'),
	array('Ancona','Western Adriatic Sea','Yes','No'),
	array('Ancona','Venezia','Yes','Yes'),
	array('Ancona','Pisa','No','Yes'),
	array('Ankara','Charsiana','No','Yes'),
	array('Ankara','Trebizond','Yes','Yes'),
	array('Ankara','South Black Sea','Yes','No'),
	array('Ankara','Miklagard','Yes','Yes'),
	array('Antakya','Cypriot Sea','Yes','No'),
	array('Antakya','Tarsus','Yes','Yes'),
	array('Antakya','Taron','No','Yes'),
	array('Antakya','Palmyra','Yes','Yes'),
	array('Antakya','Palestine','No','Yes'),
	array('Asturias','Bay of Biscay','Yes','No'),
	array('Asturias','Burgos','Yes','Yes'),
	array('Asturias','Segovia','No','Yes'),
	array('Asturias','Mid Atlantic Ocean','Yes','No'),
	array('Asturias','Lisboa','Yes','Yes'),
	array('Athinai','Thessaly','Yes','Yes'),
	array('Athinai','Macedonia','Yes','Yes'),
	array('Athinai','Ionian Sea','Yes','No'),
	array('Auvergne','Avignon','No','Yes'),
	array('Auvergne','Champagne','No','Yes'),
	array('Auvergne','Verdun','No','Yes'),
	array('Auvergne','Tours','No','Yes'),
	array('Auvergne','Toulouse','No','Yes'),
	array('Auvergne','Savoie','No','Yes'),
	array('Auvergne','Nantes','No','Yes'),
	array('Avignon','Catalonia','Yes','Yes'),
	array('Avignon','Toulouse','No','Yes'),
	array('Avignon','Savoie','No','Yes'),
	array('Avignon','Marseilles','Yes','Yes'),
	array('Avignon','Gulf of Lyons','Yes','No'),
	array('Baltic Sea','Birka','Yes','No'),
	array('Baltic Sea','Bornholmer Sea','Yes','No'),
	array('Baltic Sea','Visby','Yes','No'),
	array('Baltic Sea','Reval','Yes','No'),
	array('Baltic Sea','Pommern','Yes','No'),
	array('Baltic Sea','Memel','Yes','No'),
	array('Baltic Sea','Kalmar','Yes','No'),
	array('Baltic Sea','Jomsborg','Yes','No'),
	array('Baltic Sea','Gulf of Finland','Yes','No'),
	array('Baltic Sea','Gulf of Bothnia','Yes','No'),
	array('Baltic Sea','Gdansk','Yes','No'),
	array('Barca','Eastern Mediterranean Sea','Yes','No'),
	array('Barca','Tunis','Yes','Yes'),
	array('Barca','Libyan Sea','Yes','No'),
	array('Barents Sea','Norwegian Sea','Yes','No'),
	array('Barents Sea','Nidaros','Yes','No'),
	array('Bavaria','Brandenburg','No','Yes'),
	array('Bavaria','Frankfurt','No','Yes'),
	array('Bavaria','Zurich','No','Yes'),
	array('Bavaria','Tirol','No','Yes'),
	array('Bavaria','St. Gallen','No','Yes'),
	array('Bavaria','Praha','No','Yes'),
	array('Bavaria','Mainz','No','Yes'),
	array('Bavaria','Hessen','No','Yes'),
	array('Bavaria','Graz','No','Yes'),
	array('Bay of Biscay','Burgos','Yes','No'),
	array('Bay of Biscay','Toulouse','Yes','No'),
	array('Bay of Biscay','Noirmoutier','Yes','No'),
	array('Bay of Biscay','Nantes','Yes','No'),
	array('Bay of Biscay','Mid Atlantic Ocean','Yes','No'),
	array('Beograd','Buda','No','Yes'),
	array('Beograd','Valakia','No','Yes'),
	array('Beograd','Transylvania','No','Yes'),
	array('Beograd','Spalato','No','Yes'),
	array('Beograd','Ragusa','No','Yes'),
	array('Beograd','Pest','No','Yes'),
	array('Beograd','Paristria','No','Yes'),
	array('Beograd','Macedonia','No','Yes'),
	array('Berber Coast','Cordoba','Yes','No'),
	array('Berber Coast','Western Mediterranean Sea','Yes','No'),
	array('Berber Coast','Tunis','Yes','No'),
	array('Berber Coast','Strait of Sicily','Yes','No'),
	array('Berber Coast','Serkland','Yes','No'),
	array('Berber Coast','Palma','Yes','No'),
	array('Berber Coast','Gulf of Lyons','Yes','No'),
	array('Berber Coast','Gulf of Cadiz','Yes','No'),
	array('Birka','Uppsala','Yes','Yes'),
	array('Birka','Tiundaland','No','Yes'),
	array('Birka','Kalmar','Yes','Yes'),
	array('Birka','Gulf of Bothnia','Yes','No'),
	array('Birka','Goteborg','No','Yes'),
	array('Bornholmer Sea','Oerne','Yes','No'),
	array('Bornholmer Sea','Mecklenburg','Yes','No'),
	array('Bornholmer Sea','Kalmar','Yes','No'),
	array('Bornholmer Sea','Jomsborg','Yes','No'),
	array('Bornholmer Sea','Hedeby','Yes','No'),
	array('Brandenburg','Breslau','No','Yes'),
	array('Brandenburg','Praha','No','Yes'),
	array('Brandenburg','Mecklenburg','No','Yes'),
	array('Brandenburg','Jomsborg','No','Yes'),
	array('Brandenburg','Hessen','No','Yes'),
	array('Brandenburg','Hamburg','No','Yes'),
	array('Breslau','Ruthenia','No','Yes'),
	array('Breslau','Przemysl','No','Yes'),
	array('Breslau','Prussia','No','Yes'),
	array('Breslau','Praha','No','Yes'),
	array('Breslau','Pommern','No','Yes'),
	array('Breslau','Jomsborg','No','Yes'),
	array('Breslau','Gdansk','No','Yes'),
	array('Bretagne','English Channel','Yes','No'),
	array('Bretagne','Rouen','Yes','Yes'),
	array('Bretagne','Noirmoutier','Yes','Yes'),
	array('Bretagne','Mid Atlantic Ocean','Yes','No'),
	array('Bretagne','Maine','No','Yes'),
	array('Bretagne','Irish Sea','Yes','No'),
	array('Bruges','Dorestad','Yes','Yes'),
	array('Bruges','English Channel','Yes','No'),
	array('Bruges','Flanders','No','Yes'),
	array('Bruges','Sea of England','Yes','No'),
	array('Bruges','Rouen','Yes','Yes'),
	array('Buda','Venezia','No','Yes'),
	array('Buda','Spalato','No','Yes'),
	array('Buda','Praha','No','Yes'),
	array('Buda','Pest','No','Yes'),
	array('Buda','Graz','No','Yes'),
	array('Burgos','Catalonia','No','Yes'),
	array('Burgos','Toulouse','Yes','Yes'),
	array('Burgos','Segovia','No','Yes'),
	array('Burta','Cumaniya','No','Yes'),
	array('Burta','Vladimir','No','Yes'),
	array('Burta','Mordvin','No','Yes'),
	array('Burta','Kjonugard','No','Yes'),
	array('Burta','Khazar Empire','No','Yes'),
	array('Burta','Kaffa','No','Yes'),
	array('Burta','Gardarike','No','Yes'),
	array('Cagliari','Western Mediterranean Sea','Yes','No'),
	array('Cagliari','Tyrrhenian Sea','Yes','No'),
	array('Cagliari','Strait of Sicily','Yes','No'),
	array('Cagliari','Ligurian Sea','Yes','No'),
	array('Catalonia','Cordoba','Yes','Yes'),
	array('Catalonia','Toulouse','No','Yes'),
	array('Catalonia','Segovia','No','Yes'),
	array('Catalonia','Gulf of Lyons','Yes','No'),
	array('Champagne','Verdun','No','Yes'),
	array('Champagne','Tours','No','Yes'),
	array('Champagne','Paris','No','Yes'),
	array('Charsiana','Trebizond','No','Yes'),
	array('Charsiana','Tarsus','No','Yes'),
	array('Charsiana','Taron','No','Yes'),
	array('Charsiana','Smyrna','No','Yes'),
	array('Charsiana','Miklagard','No','Yes'),
	array('Cherson Bight','Cumaniya','Yes','No'),
	array('Cherson Bight','South Black Sea','Yes','No'),
	array('Cherson Bight','Paristria','Yes','No'),
	array('Cherson Bight','North Black Sea','Yes','No'),
	array('Cherson Bight','Kaffa','Yes','No'),
	array('Cordoba','Sevilla','Yes','Yes'),
	array('Cordoba','Segovia','No','Yes'),
	array('Cordoba','Lisboa','No','Yes'),
	array('Cordoba','Gulf of Lyons','Yes','No'),
	array('Cordoba','Gulf of Cadiz','Yes','No'),
	array('Cornwall','English Channel','Yes','No'),
	array('Cornwall','Wales','Yes','Yes'),
	array('Cornwall','Irish Sea','Yes','No'),
	array('Cornwall','Hastings','Yes','Yes'),
	array('Cumaniya','Valakia','No','Yes'),
	array('Cumaniya','Transylvania','No','Yes'),
	array('Cumaniya','Ruthenia','No','Yes'),
	array('Cumaniya','Paristria','Yes','Yes'),
	array('Cumaniya','Kjonugard','Yes','Yes'),
	array('Cumaniya','Kaffa','Yes','Yes'),
	array('Cypriot Sea','Eastern Mediterranean Sea','Yes','No'),
	array('Cypriot Sea','Tarsus','Yes','No'),
	array('Cypriot Sea','Smyrna','Yes','No'),
	array('Cypriot Sea','Palmyra','Yes','No'),
	array('Cypriot Sea','Jorsal','Yes','No'),
	array('Dogger Bank','Dorestad','Yes','No'),
	array('Dogger Bank','Sea of England','Yes','No'),
	array('Dogger Bank','North Sea','Yes','No'),
	array('Dogger Bank','Jylland','Yes','No'),
	array('Dogger Bank','Hedeby','Yes','No'),
	array('Dogger Bank','Hamburg','Yes','No'),
	array('Dogger Bank','Groningen','Yes','No'),
	array('Dorestad','Flanders','No','Yes'),
	array('Dorestad','Sea of England','Yes','No'),
	array('Dorestad','Groningen','Yes','Yes'),
	array('Dyvlin','Mid Atlantic Ocean','Yes','No'),
	array('Dyvlin','Irish Sea','Yes','No'),
	array('Dyvlin','Hibernian Sea','Yes','No'),
	array('Dyvlin','North Atlantic Ocean','Yes','No'),
	array('Eastern Adriatic Sea','Western Adriatic Sea','Yes','No'),
	array('Eastern Adriatic Sea','Venezia','Yes','No'),
	array('Eastern Adriatic Sea','Spalato','Yes','No'),
	array('Eastern Adriatic Sea','Ragusa','Yes','No'),
	array('Eastern Adriatic Sea','Ionian Sea','Yes','No'),
	array('Eastern Mediterranean Sea','Smyrna','Yes','No'),
	array('Eastern Mediterranean Sea','Libyan Sea','Yes','No'),
	array('Eastern Mediterranean Sea','Jorsal','Yes','No'),
	array('Eastern Mediterranean Sea','Ionian Sea','Yes','No'),
	array('English Channel','Sea of England','Yes','No'),
	array('English Channel','Rouen','Yes','No'),
	array('English Channel','Irish Sea','Yes','No'),
	array('English Channel','Hastings','Yes','No'),
	array('Essex','Skegness','Yes','Yes'),
	array('Essex','Sea of England','Yes','No'),
	array('Essex','London','No','Yes'),
	array('Essex','Hastings','Yes','Yes'),
	array('Flanders','Verdun','No','Yes'),
	array('Flanders','Rouen','No','Yes'),
	array('Flanders','Koln','No','Yes'),
	array('Flanders','Groningen','No','Yes'),
	array('Frankfurt','Mainz','No','Yes'),
	array('Frankfurt','Koln','No','Yes'),
	array('Frankfurt','Hessen','No','Yes'),
	array('Zurich','Verdun','No','Yes'),
	array('Zurich','St. Gallen','No','Yes'),
	array('Zurich','Savoie','No','Yes'),
	array('Zurich','Mainz','No','Yes'),
	array('Zurich','Lombardy','No','Yes'),
	array('Westmorland','Wales','No','Yes'),
	array('Westmorland','Skegness','No','Yes'),
	array('Westmorland','London','No','Yes'),
	array('Westmorland','Kirkby','No','Yes'),
	array('Westmorland','Jorvik','No','Yes'),
	array('Westmorland','Lindisfarne','No','Yes'),
	array('Western Mediterranean Sea','Strait of Sicily','Yes','No'),
	array('Western Mediterranean Sea','Palma','Yes','No'),
	array('Western Mediterranean Sea','Ligurian Sea','Yes','No'),
	array('Western Mediterranean Sea','Gulf of Lyons','Yes','No'),
	array('Western Adriatic Sea','Venezia','Yes','No'),
	array('Western Adriatic Sea','Napoli','Yes','No'),
	array('Western Adriatic Sea','Ionian Sea','Yes','No'),
	array('Wales','London','No','Yes'),
	array('Wales','Kirkby','Yes','Yes'),
	array('Wales','Irish Sea','Yes','No'),
	array('Wales','Hastings','No','Yes'),
	array('Vladimir','Viatka','No','Yes'),
	array('Vladimir','Rostov','Yes','Yes'),
	array('Vladimir','Mordvin','No','Yes'),
	array('Vladimir','Khazar Empire','Yes','Yes'),
	array('Vitebsk','Smolensk','No','Yes'),
	array('Vitebsk','Przemysl','No','Yes'),
	array('Vitebsk','Memel','No','Yes'),
	array('Vitebsk','Holmgard','No','Yes'),
	array('Vitebsk','Gardarike','No','Yes'),
	array('Visby','Gulf of Finland','Yes','No'),
	array('Visby','Gulf of Bothnia','Yes','No'),
	array('Viatka','Rostov','No','Yes'),
	array('Viatka','Muscovy','No','Yes'),
	array('Verdun','Savoie','No','Yes'),
	array('Verdun','Rouen','No','Yes'),
	array('Verdun','Paris','No','Yes'),
	array('Verdun','Koln','No','Yes'),
	array('Venezia','Tirol','No','Yes'),
	array('Venezia','Spalato','Yes','Yes'),
	array('Venezia','Pisa','No','Yes'),
	array('Venezia','Lombardy','No','Yes'),
	array('Venezia','Graz','No','Yes'),
	array('Valakia','Transylvania','No','Yes'),
	array('Valakia','Paristria','No','Yes'),
	array('Uppsala','Tiundaland','No','Yes'),
	array('Uppsala','Jemtland','No','Yes'),
	array('Uppsala','Helsingjaland','Yes','Yes'),
	array('Uppsala','Gulf of Bothnia','Yes','No'),
	array('Tyrrhenian Sea','Syracuse','Yes','No'),
	array('Tyrrhenian Sea','Strait of Sicily','Yes','No'),
	array('Tyrrhenian Sea','Roma','Yes','No'),
	array('Tyrrhenian Sea','Palermo','Yes','No'),
	array('Tyrrhenian Sea','Napoli','Yes','No'),
	array('Tyrrhenian Sea','Ligurian Sea','Yes','No'),
	array('Tyrrhenian Sea','Ionian Sea','Yes','No'),
	array('Tunis','Strait of Sicily','Yes','No'),
	array('Tunis','Serkland','Yes','Yes'),
	array('Tunis','Libyan Sea','Yes','No'),
	array('Trebizond','Taron','No','Yes'),
	array('Trebizond','South Black Sea','Yes','No'),
	array('Trebizond','North Black Sea','Yes','No'),
	array('Trebizond','Khazar Empire','Yes','Yes'),
	array('Transylvania','Ruthenia','No','Yes'),
	array('Transylvania','Pest','No','Yes'),
	array('Tours','Paris','No','Yes'),
	array('Tours','Nantes','No','Yes'),
	array('Tours','Maine','No','Yes'),
	array('Toulouse','Nantes','Yes','Yes'),
	array('Tiundaland','Skiringssal','No','Yes'),
	array('Tiundaland','Ranrike','No','Yes'),
	array('Tiundaland','Jemtland','No','Yes'),
	array('Tiundaland','Goteborg','No','Yes'),
	array('Tirol','St. Gallen','No','Yes'),
	array('Tirol','Lombardy','No','Yes'),
	array('Tirol','Graz','No','Yes'),
	array('Thessaly','Paristria','No','Yes'),
	array('Thessaly','Miklagard','Yes','Yes'),
	array('Thessaly','Macedonia','No','Yes'),
	array('Tarsus','Taron','No','Yes'),
	array('Tarsus','Smyrna','Yes','Yes'),
	array('Syracuse','Palermo','Yes','Yes'),
	array('Syracuse','Libyan Sea','Yes','No'),
	array('Syracuse','Ionian Sea','Yes','No'),
	array('Strathclyde','Scotland','No','Yes'),
	array('Strathclyde','Kirkby','Yes','Yes'),
	array('Strathclyde','Katanes','Yes','Yes'),
	array('Strathclyde','Hibernian Sea','Yes','No'),
	array('Strathclyde','Lindisfarne','No','Yes'),
	array('Strait of Sicily','Palermo','Yes','No'),
	array('Strait of Sicily','Libyan Sea','Yes','No'),
	array('St. Gallen','Lombardy','No','Yes'),
	array('Spalato','Ragusa','Yes','Yes'),
	array('South Black Sea','Paristria','Yes','No'),
	array('South Black Sea','North Black Sea','Yes','No'),
	array('South Black Sea','Miklagard','Yes','No'),
	array('Smyrna','Miklagard','Yes','Yes'),
	array('Smolensk','Przemysl','No','Yes'),
	array('Smolensk','Kjonugard','No','Yes'),
	array('Smolensk','Gardarike','No','Yes'),
	array('Skiringssal','Skagerrak','Yes','No'),
	array('Skiringssal','Ranrike','Yes','Yes'),
	array('Skiringssal','Nidaros','No','Yes'),
	array('Skiringssal','Jemtland','No','Yes'),
	array('Skiringssal','Hordaland','No','Yes'),
	array('Skiringssal','Hafrsfjord','Yes','Yes'),
	array('Skegness','Sea of England','Yes','No'),
	array('Skegness','London','No','Yes'),
	array('Skegness','Jorvik','Yes','Yes'),
	array('Skagerrak','Ranrike','Yes','No'),
	array('Skagerrak','North Sea','Yes','No'),
	array('Skagerrak','Kattegat','Yes','No'),
	array('Skagerrak','Jylland','Yes','No'),
	array('Skagerrak','Hafrsfjord','Yes','No'),
	array('Skagerrak','Goteborg','Yes','No'),
	array('Skaalholt','Norwegian Sea','Yes','No'),
	array('Skaalholt','Hibernian Sea','Yes','No'),
	array('Skaalholt','North Atlantic Ocean','Yes','No'),
	array('Sevilla','Lisboa','Yes','Yes'),
	array('Sevilla','Gulf of Cadiz','Yes','No'),
	array('Serkland','Gulf of Cadiz','Yes','No'),
	array('Segovia','Lisboa','No','Yes'),
	array('Sea of England','North Sea','Yes','No'),
	array('Sea of England','Jorvik','Yes','No'),
	array('Sea of England','Hastings','Yes','No'),
	array('Sea of England','Lindisfarne','Yes','No'),
	array('Scotland','North Sea','Yes','No'),
	array('Scotland','Katanes','Yes','Yes'),
	array('Scotland','Lindisfarne','Yes','Yes'),
	array('Savoie','Marseilles','No','Yes'),
	array('Savoie','Lombardy','No','Yes'),
	array('Savoie','Genova','No','Yes'),
	array('Ruthenia','Przemysl','No','Yes'),
	array('Ruthenia','Praha','No','Yes'),
	array('Ruthenia','Pest','No','Yes'),
	array('Ruthenia','Kjonugard','No','Yes'),
	array('Rouen','Paris','No','Yes'),
	array('Rouen','Maine','No','Yes'),
	array('Rostov','Muscovy','No','Yes'),
	array('Rostov','Mordvin','No','Yes'),
	array('Rostov','Karelia','No','Yes'),
	array('Rostov','Holmgard','Yes','Yes'),
	array('Roma','Pisa','Yes','Yes'),
	array('Roma','Napoli','Yes','Yes'),
	array('Roma','Ligurian Sea','Yes','No'),
	array('Reval','Memel','Yes','Yes'),
	array('Reval','Ingermannland','Yes','Yes'),
	array('Reval','Gulf of Finland','Yes','No'),
	array('Ranrike','Goteborg','Yes','Yes'),
	array('Ragusa','Macedonia','Yes','Yes'),
	array('Ragusa','Ionian Sea','Yes','No'),
	array('Przemysl','Prussia','No','Yes'),
	array('Przemysl','Memel','No','Yes'),
	array('Przemysl','Kjonugard','No','Yes'),
	array('Prussia','Memel','No','Yes'),
	array('Prussia','Gdansk','No','Yes'),
	array('Praha','Pest','No','Yes'),
	array('Praha','Graz','No','Yes'),
	array('Pommern','Jomsborg','Yes','Yes'),
	array('Pommern','Gdansk','Yes','Yes'),
	array('Pisa','Lombardy','No','Yes'),
	array('Pisa','Ligurian Sea','Yes','No'),
	array('Pisa','Genova','Yes','Yes'),
	array('Paristria','Miklagard','Yes','Yes'),
	array('Paristria','Macedonia','No','Yes'),
	array('Paris','Maine','No','Yes'),
	array('Palmyra','Palestine','No','Yes'),
	array('Palmyra','Jorsal','Yes','Yes'),
	array('Palma','Gulf of Lyons','Yes','No'),
	array('Palestine','Jorsal','No','Yes'),
	array('Palermo','Libyan Sea','Yes','No'),
	array('Osterbotten','Kvenland','Yes','Yes'),
	array('Osterbotten','Gulf of Finland','Yes','No'),
	array('Osterbotten','Gulf of Bothnia','Yes','No'),
	array('Oldenburg','Koln','No','Yes'),
	array('Oldenburg','Hessen','No','Yes'),
	array('Oldenburg','Hamburg','No','Yes'),
	array('Oldenburg','Groningen','No','Yes'),
	array('Oerne','Kattegat','Yes','No'),
	array('Oerne','Kalmar','Yes','Yes'),
	array('Oerne','Jylland','Yes','Yes'),
	array('Oerne','Hedeby','Yes','Yes'),
	array('Norwegian Sea','North Sea','Yes','No'),
	array('Norwegian Sea','Nidaros','Yes','No'),
	array('Norwegian Sea','Hordaland','Yes','No'),
	array('Norwegian Sea','Hibernian Sea','Yes','No'),
	array('Norwegian Sea','North Atlantic Ocean','Yes','No'),
	array('North Sea','Katanes','Yes','No'),
	array('North Sea','Jylland','Yes','No'),
	array('North Sea','Hordaland','Yes','No'),
	array('North Sea','Hibernian Sea','Yes','No'),
	array('North Sea','Hafrsfjord','Yes','No'),
	array('North Sea','Lindisfarne','Yes','No'),
	array('North Black Sea','Khazar Empire','Yes','No'),
	array('North Black Sea','Kaffa','Yes','No'),
	array('Noirmoutier','Nantes','Yes','Yes'),
	array('Noirmoutier','Mid Atlantic Ocean','Yes','No'),
	array('Noirmoutier','Maine','No','Yes'),
	array('Nidaros','Jemtland','No','Yes'),
	array('Nidaros','Hordaland','Yes','Yes'),
	array('Napoli','Ionian Sea','Yes','No'),
	array('Nantes','Maine','No','Yes'),
	array('Muscovy','Karelia','No','Yes'),
	array('Mordvin','Holmgard','No','Yes'),
	array('Mordvin','Gardarike','No','Yes'),
	array('Mid Atlantic Ocean','Lisboa','Yes','No'),
	array('Mid Atlantic Ocean','Irish Sea','Yes','No'),
	array('Mid Atlantic Ocean','Gulf of Cadiz','Yes','No'),
	array('Mid Atlantic Ocean','North Atlantic Ocean','Yes','No'),
	array('Memel','Ingermannland','No','Yes'),
	array('Memel','Holmgard','No','Yes'),
	array('Memel','Gdansk','Yes','Yes'),
	array('Mecklenburg','Jomsborg','Yes','Yes'),
	array('Mecklenburg','Hedeby','Yes','Yes'),
	array('Mecklenburg','Hamburg','No','Yes'),
	array('Marseilles','Ligurian Sea','Yes','No'),
	array('Marseilles','Gulf of Lyons','Yes','No'),
	array('Marseilles','Genova','Yes','Yes'),
	array('Macedonia','Ionian Sea','Yes','No'),
	array('London','Hastings','No','Yes'),
	array('Lombardy','Genova','No','Yes'),
	array('Lisboa','Gulf of Cadiz','Yes','No'),
	array('Ligurian Sea','Gulf of Lyons','Yes','No'),
	array('Ligurian Sea','Genova','Yes','No'),
	array('Libyan Sea','Ionian Sea','Yes','No'),
	array('Kvenland','Karelia','No','Yes'),
	array('Kvenland','Helsingjaland','Yes','Yes'),
	array('Kvenland','Gulf of Bothnia','Yes','No'),
	array('Koln','Hessen','No','Yes'),
	array('Koln','Groningen','No','Yes'),
	array('Kjonugard','Gardarike','Yes','Yes'),
	array('Kirkby','Irish Sea','Yes','No'),
	array('Kirkby','Hibernian Sea','Yes','No'),
	array('Kirkby','Lindisfarne','No','Yes'),
	array('Khazar Empire','Kaffa','Yes','Yes'),
	array('Kattegat','Kalmar','Yes','No'),
	array('Kattegat','Jylland','Yes','No'),
	array('Kattegat','Goteborg','Yes','No'),
	array('Katanes','Hibernian Sea','Yes','No'),
	array('Karelia','Holmgard','No','Yes'),
	array('Kalmar','Goteborg','Yes','Yes'),
	array('Jylland','Hedeby','Yes','Yes'),
	array('Jorvik','Lindisfarne','Yes','Yes'),
	array('Jemtland','Helsingjaland','No','Yes'),
	array('Irish Sea','Hibernian Sea','Yes','No'),
	array('Ingermannland','Holmgard','No','Yes'),
	array('Ingermannland','Gulf of Finland','Yes','No'),
	array('Hordaland','Hafrsfjord','Yes','Yes'),
	array('Holmgard','Gardarike','Yes','Yes'),
	array('Hibernian Sea','North Atlantic Ocean','Yes','No'),
	array('Hessen','Hamburg','No','Yes'),
	array('Helsingjaland','Gulf of Bothnia','Yes','No'),
	array('Hedeby','Hamburg','Yes','Yes'),
	array('Hamburg','Groningen','Yes','Yes'),
	array('Gulf of Finland','Gulf of Bothnia','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
