<?php
// This is file installs the map data for the Hussite variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Magdeburg', 'Coast', 'Yes', 0, 47, 126, 25, 67),
	array('Potsdam', 'Coast', 'Yes', 5, 208, 92, 111, 49),
	array('Berlin', 'Coast', 'Yes', 5, 319, 98, 170, 52),
	array('Frankfurt', 'Coast', 'Yes', 5, 486, 77, 259, 41),
	array('Landsberg', 'Land', 'No', 4, 615, 137, 328, 73),
	array('Posen', 'Coast', 'Yes', 4, 861, 128, 459, 68),
	array('Warschau', 'Coast', 'Yes', 4, 1313, 113, 688, 84),
	array('Wittenberg', 'Land', 'No', 5, 201, 242, 107, 129),
	array('Fürstenwalde', 'Land', 'No', 5, 338, 204, 180, 109),
	array('Cottbus', 'Coast', 'Yes', 0, 478, 291, 255, 155),
	array('Grünberg', 'Land', 'Yes', 0, 697, 244, 362, 137),
	array('Kalisch', 'Land', 'No', 4, 919, 281, 490, 150),
	array('Lodz', 'Land', 'No', 4, 1170, 294, 624, 157),
	array('Leipzig', 'Coast', 'Yes', 8, 92, 343, 49, 183),
	array('Meissen', 'Land', 'No', 8, 216, 379, 115, 202),
	array('Dresden', 'Coast', 'Yes', 8, 326, 411, 174, 219),
	array('Senftenberg', 'Land', 'No', 8, 362, 328, 193, 175),
	array('Görlitz', 'Coast', 'Yes', 0, 512, 413, 273, 220),
	array('Glogau', 'Land', 'No', 2, 643, 371, 343, 198),
	array('Liegnitz', 'Land', 'No', 2, 774, 366, 413, 195),
	array('Breslau', 'Coast', 'Yes', 0, 908, 452, 484, 241),
	array('Katowitz', 'Coast', 'Yes', 0, 1114, 561, 594, 299),
	array('Radom', 'Land', 'No', 4, 1363, 488, 727, 260),
	array('Jena', 'Land', 'No', 8, 62, 510, 33, 272),
	array('Chemnitz', 'Land', 'Yes', 8, 208, 469, 109, 269),
	array('Zwickau', 'Land', 'No', 8, 188, 585, 100, 312),
	array('Teplitz', 'Land', 'No', 2, 351, 559, 186, 319),
	array('Tetschen', 'Land', 'No', 2, 458, 508, 235, 296),
	array('Aussig', 'Coast', 'Yes', 0, 473, 540, 248, 309),
	array('Reichenberg', 'Coast', 'Yes', 0, 594, 542, 317, 289),
	array('Hirschberg', 'Land', 'Yes', 0, 683, 467, 343, 264),
	array('Waldenburg', 'Land', 'No', 2, 759, 536, 405, 286),
	array('Oppeln', 'Land', 'No', 2, 896, 585, 478, 312),
	array('Ostrau', 'Coast', 'Yes', 0, 1018, 788, 543, 420),
	array('Bielitz-Biala', 'Land', 'No', 4, 1224, 806, 652, 446),
	array('Krakau', 'Coast', 'Yes', 4, 1356, 729, 723, 389),
	array('Bayreuth', 'Land', 'No', 1, 45, 653, 24, 348),
	array('Eger', 'Coast', 'Yes', 0, 214, 630, 104, 366),
	array('Saaz', 'Coast', 'Yes', 0, 268, 606, 153, 344),
	array('Schlan', 'Land', 'Yes', 7, 369, 624, 195, 349),
	array('Leitmeritz', 'Land', 'No', 7, 426, 604, 230, 349),
	array('Altstadt', 'Coast', 'Yes', 7, 473, 602, 252, 321),
	array('Bunzlau', 'Land', 'No', 7, 534, 585, 290, 336),
	array('Königgratz', 'Coast', 'Yes', 6, 604, 626, 329, 358),
	array('Oreb', 'Land', 'Yes', 6, 679, 589, 362, 337),
	array('Leitomischl', 'Land', 'Yes', 6, 731, 681, 390, 363),
	array('Schönberg', 'Land', 'No', 2, 836, 716, 446, 382),
	array('Olmütz', 'Coast', 'Yes', 2, 771, 804, 409, 451),
	array('Prerau', 'Land', 'No', 2, 954, 803, 494, 441),
	array('Settein', 'Land', 'No', 2, 926, 906, 494, 483),
	array('Sillein', 'Coast', 'Yes', 3, 1151, 864, 620, 482),
	array('Kaschau', 'Land', 'No', 3, 1288, 1001, 687, 534),
	array('Regensburg', 'Coast', 'Yes', 1, 56, 851, 30, 454),
	array('Fürth', 'Land', 'No', 1, 139, 801, 74, 427),
	array('Tachau', 'Coast', 'Yes', 0, 188, 752, 100, 401),
	array('Rakonitz', 'Land', 'No', 7, 274, 699, 146, 373),
	array('Kladno', 'Land', 'No', 7, 360, 722, 192, 385),
	array('Beneschau', 'Land', 'No', 7, 474, 754, 257, 423),
	array('Neustadt', 'Coast', 'Yes', 7, 506, 668, 262, 380),
	array('Kuttenberg', 'Land', 'Yes', 0, 593, 739, 316, 394),
	array('Pardubitz', 'Land', 'No', 6, 668, 733, 357, 410),
	array('Brünn', 'Coast', 'Yes', 2, 844, 855, 450, 482),
	array('Landshut', 'Land', 'No', 1, 75, 984, 40, 525),
	array('Straubing', 'Land', 'No', 1, 197, 891, 97, 499),
	array('Pilsen', 'Coast', 'Yes', 2, 225, 789, 125, 444),
	array('Klattau', 'Land', 'No', 9, 338, 898, 180, 479),
	array('Rokitzan', 'Coast', 'Yes', 0, 362, 793, 191, 450),
	array('Pibrams', 'Land', 'No', 9, 441, 788, 232, 442),
	array('Pisek', 'Coast', 'Yes', 9, 414, 898, 221, 479),
	array('Tabor', 'Coast', 'Yes', 9, 506, 786, 267, 445),
	array('Pilgrams', 'Land', 'No', 9, 546, 831, 291, 443),
	array('Iglau', 'Coast', 'Yes', 2, 688, 816, 366, 465),
	array('München', 'Coast', 'Yes', 1, 188, 1052, 100, 561),
	array('Passau', 'Coast', 'Yes', 1, 272, 936, 152, 531),
	array('Krumlau', 'Land', 'No', 9, 403, 954, 219, 541),
	array('Budweis', 'Coast', 'Yes', 9, 514, 881, 272, 491),
	array('Znoim', 'Land', 'No', 2, 671, 911, 349, 508),
	array('Lundenburg', 'Coast', 'Yes', 0, 825, 930, 443, 518),
	array('Salzburg', 'Land', 'No', 0, 354, 1196, 189, 638),
	array('Linz', 'Coast', 'Yes', 0, 497, 1046, 265, 558),
	array('Hollabrunn', 'Land', 'No', 0, 587, 999, 313, 533),
	array('Wien', 'Coast', 'Yes', 0, 774, 1048, 413, 559),
	array('Sankt Pölten', 'Land', 'No', 0, 593, 1163, 316, 620),
	array('Pressburg', 'Coast', 'Yes', 3, 879, 1035, 480, 578),
	array('Trentschin', 'Land', 'No', 3, 1043, 1013, 536, 570),
	array('Ofen', 'Coast', 'Yes', 3, 1221, 1178, 651, 628)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Magdeburg','Potsdam','Yes','Yes'),
	array('Magdeburg','Berlin','Yes','No'),
	array('Magdeburg','Frankfurt','Yes','No'),
	array('Magdeburg','Wittenberg','No','Yes'),
	array('Magdeburg','Leipzig','Yes','Yes'),
	array('Magdeburg','Dresden','Yes','No'),
	array('Potsdam','Berlin','Yes','Yes'),
	array('Potsdam','Wittenberg','No','Yes'),
	array('Potsdam','Cottbus','Yes','No'),
	array('Berlin','Frankfurt','No','Yes'),
	array('Berlin','Fürstenwalde','No','Yes'),
	array('Berlin','Cottbus','Yes','No'),
	array('Frankfurt','Landsberg','No','Yes'),
	array('Frankfurt','Posen','Yes','No'),
	array('Frankfurt','Warschau','Yes','No'),
	array('Frankfurt','Cottbus','Yes','Yes'),
	array('Frankfurt','Görlitz','Yes','No'),
	array('Frankfurt','Breslau','Yes','No'),
	array('Landsberg','Posen','No','Yes'),
	array('Landsberg','Grünberg','No','Yes'),
	array('Landsberg','Kalisch','No','Yes'),
	array('Posen','Warschau','No','Yes'),
	array('Posen','Kalisch','No','Yes'),
	array('Warschau','Kalisch','No','Yes'),
	array('Warschau','Lodz','No','Yes'),
	array('Warschau','Radom','No','Yes'),
	array('Warschau','Krakau','Yes','No'),
	array('Wittenberg','Fürstenwalde','No','Yes'),
	array('Wittenberg','Leipzig','No','Yes'),
	array('Wittenberg','Meissen','No','Yes'),
	array('Wittenberg','Dresden','No','Yes'),
	array('Wittenberg','Senftenberg','No','Yes'),
	array('Fürstenwalde','Cottbus','No','Yes'),
	array('Fürstenwalde','Senftenberg','No','Yes'),
	array('Cottbus','Grünberg','No','Yes'),
	array('Cottbus','Senftenberg','No','Yes'),
	array('Cottbus','Görlitz','Yes','Yes'),
	array('Cottbus','Glogau','No','Yes'),
	array('Grünberg','Kalisch','No','Yes'),
	array('Grünberg','Glogau','No','Yes'),
	array('Grünberg','Liegnitz','No','Yes'),
	array('Kalisch','Lodz','No','Yes'),
	array('Kalisch','Liegnitz','No','Yes'),
	array('Kalisch','Breslau','No','Yes'),
	array('Lodz','Breslau','No','Yes'),
	array('Lodz','Katowitz','No','Yes'),
	array('Lodz','Radom','No','Yes'),
	array('Leipzig','Meissen','No','Yes'),
	array('Leipzig','Dresden','Yes','No'),
	array('Leipzig','Jena','No','Yes'),
	array('Leipzig','Chemnitz','No','Yes'),
	array('Meissen','Dresden','No','Yes'),
	array('Meissen','Chemnitz','No','Yes'),
	array('Meissen','Zwickau','No','Yes'),
	array('Meissen','Teplitz','No','Yes'),
	array('Meissen','Tetschen','No','Yes'),
	array('Dresden','Senftenberg','No','Yes'),
	array('Dresden','Görlitz','No','Yes'),
	array('Dresden','Tetschen','No','Yes'),
	array('Dresden','Aussig','Yes','No'),
	array('Senftenberg','Görlitz','No','Yes'),
	array('Görlitz','Glogau','No','Yes'),
	array('Görlitz','Tetschen','No','Yes'),
	array('Görlitz','Aussig','No','Yes'),
	array('Görlitz','Reichenberg','Yes','Yes'),
	array('Görlitz','Hirschberg','No','Yes'),
	array('Glogau','Liegnitz','No','Yes'),
	array('Glogau','Hirschberg','No','Yes'),
	array('Liegnitz','Breslau','No','Yes'),
	array('Liegnitz','Hirschberg','No','Yes'),
	array('Liegnitz','Waldenburg','No','Yes'),
	array('Breslau','Katowitz','No','Yes'),
	array('Breslau','Waldenburg','No','Yes'),
	array('Breslau','Oppeln','No','Yes'),
	array('Breslau','Ostrau','Yes','No'),
	array('Katowitz','Radom','No','Yes'),
	array('Katowitz','Oppeln','No','Yes'),
	array('Katowitz','Ostrau','No','Yes'),
	array('Katowitz','Bielitz-Biala','No','Yes'),
	array('Katowitz','Krakau','Yes','Yes'),
	array('Radom','Krakau','No','Yes'),
	array('Jena','Chemnitz','No','Yes'),
	array('Jena','Zwickau','No','Yes'),
	array('Jena','Bayreuth','No','Yes'),
	array('Jena','Eger','No','Yes'),
	array('Chemnitz','Zwickau','No','Yes'),
	array('Zwickau','Teplitz','No','Yes'),
	array('Zwickau','Eger','No','Yes'),
	array('Zwickau','Saaz','No','Yes'),
	array('Teplitz','Tetschen','No','Yes'),
	array('Teplitz','Aussig','No','Yes'),
	array('Teplitz','Saaz','No','Yes'),
	array('Teplitz','Schlan','No','Yes'),
	array('Teplitz','Leitmeritz','No','Yes'),
	array('Tetschen','Aussig','No','Yes'),
	array('Aussig','Reichenberg','No','Yes'),
	array('Aussig','Saaz','Yes','No'),
	array('Aussig','Leitmeritz','No','Yes'),
	array('Aussig','Altstadt','Yes','Yes'),
	array('Aussig','Bunzlau','No','Yes'),
	array('Aussig','Königgratz','Yes','No'),
	array('Aussig','Neustadt','Yes','No'),
	array('Reichenberg','Hirschberg','No','Yes'),
	array('Reichenberg','Bunzlau','No','Yes'),
	array('Reichenberg','Oreb','No','Yes'),
	array('Hirschberg','Waldenburg','No','Yes'),
	array('Hirschberg','Oreb','No','Yes'),
	array('Waldenburg','Oppeln','No','Yes'),
	array('Waldenburg','Oreb','No','Yes'),
	array('Waldenburg','Leitomischl','No','Yes'),
	array('Oppeln','Ostrau','No','Yes'),
	array('Oppeln','Leitomischl','No','Yes'),
	array('Oppeln','Schönberg','No','Yes'),
	array('Oppeln','Olmütz','No','Yes'),
	array('Oppeln','Prerau','No','Yes'),
	array('Ostrau','Bielitz-Biala','No','Yes'),
	array('Ostrau','Prerau','No','Yes'),
	array('Ostrau','Settein','No','Yes'),
	array('Ostrau','Sillein','No','Yes'),
	array('Bielitz-Biala','Krakau','No','Yes'),
	array('Bielitz-Biala','Sillein','No','Yes'),
	array('Bielitz-Biala','Kaschau','No','Yes'),
	array('Krakau','Kaschau','No','Yes'),
	array('Bayreuth','Eger','No','Yes'),
	array('Bayreuth','Regensburg','No','Yes'),
	array('Bayreuth','Fürth','No','Yes'),
	array('Bayreuth','Tachau','No','Yes'),
	array('Eger','Saaz','Yes','Yes'),
	array('Eger','Tachau','No','Yes'),
	array('Eger','Rakonitz','No','Yes'),
	array('Saaz','Schlan','No','Yes'),
	array('Saaz','Altstadt','Yes','No'),
	array('Saaz','Königgratz','Yes','No'),
	array('Saaz','Rakonitz','No','Yes'),
	array('Schlan','Leitmeritz','No','Yes'),
	array('Schlan','Rakonitz','No','Yes'),
	array('Schlan','Kladno','No','Yes'),
	array('Leitmeritz','Altstadt','No','Yes'),
	array('Leitmeritz','Kladno','No','Yes'),
	array('Altstadt','Bunzlau','No','Yes'),
	array('Altstadt','Beneschau','No','Yes'),
	array('Altstadt','Neustadt','Yes','Yes'),
	array('Altstadt','Pilsen','Yes','No'),
	array('Altstadt','Rokitzan','Yes','No'),
	array('Bunzlau','Königgratz','No','Yes'),
	array('Bunzlau','Neustadt','No','Yes'),
	array('Bunzlau','Kuttenberg','No','Yes'),
	array('Königgratz','Oreb','No','Yes'),
	array('Königgratz','Leitomischl','No','Yes'),
	array('Königgratz','Kuttenberg','No','Yes'),
	array('Königgratz','Pardubitz','No','Yes'),
	array('Oreb','Leitomischl','No','Yes'),
	array('Leitomischl','Schönberg','No','Yes'),
	array('Leitomischl','Pardubitz','No','Yes'),
	array('Schönberg','Olmütz','No','Yes'),
	array('Schönberg','Pardubitz','No','Yes'),
	array('Schönberg','Iglau','No','Yes'),
	array('Olmütz','Prerau','No','Yes'),
	array('Olmütz','Brünn','No','Yes'),
	array('Olmütz','Iglau','No','Yes'),
	array('Olmütz','Znoim','No','Yes'),
	array('Olmütz','Lundenburg','Yes','No'),
	array('Olmütz','Wien','Yes','No'),
	array('Olmütz','Pressburg','Yes','No'),
	array('Prerau','Settein','No','Yes'),
	array('Prerau','Brünn','No','Yes'),
	array('Settein','Sillein','No','Yes'),
	array('Settein','Kaschau','No','Yes'),
	array('Settein','Brünn','No','Yes'),
	array('Settein','Lundenburg','No','Yes'),
	array('Settein','Pressburg','No','Yes'),
	array('Settein','Trentschin','No','Yes'),
	array('Sillein','Kaschau','No','Yes'),
	array('Sillein','Pressburg','Yes','No'),
	array('Sillein','Ofen','Yes','No'),
	array('Kaschau','Trentschin','No','Yes'),
	array('Kaschau','Ofen','No','Yes'),
	array('Regensburg','Fürth','No','Yes'),
	array('Regensburg','Landshut','No','Yes'),
	array('Regensburg','Straubing','No','Yes'),
	array('Regensburg','München','Yes','No'),
	array('Regensburg','Passau','Yes','No'),
	array('Fürth','Tachau','No','Yes'),
	array('Fürth','Straubing','No','Yes'),
	array('Fürth','Pilsen','No','Yes'),
	array('Tachau','Rakonitz','No','Yes'),
	array('Tachau','Pilsen','Yes','Yes'),
	array('Rakonitz','Kladno','No','Yes'),
	array('Rakonitz','Pilsen','No','Yes'),
	array('Rakonitz','Rokitzan','No','Yes'),
	array('Kladno','Beneschau','No','Yes'),
	array('Kladno','Rokitzan','No','Yes'),
	array('Kladno','Pibrams','No','Yes'),
	array('Beneschau','Neustadt','No','Yes'),
	array('Beneschau','Kuttenberg','No','Yes'),
	array('Beneschau','Pibrams','No','Yes'),
	array('Beneschau','Tabor','No','Yes'),
	array('Neustadt','Kuttenberg','No','Yes'),
	array('Neustadt','Pisek','Yes','No'),
	array('Neustadt','Tabor','Yes','No'),
	array('Neustadt','Budweis','Yes','No'),
	array('Kuttenberg','Pardubitz','No','Yes'),
	array('Kuttenberg','Tabor','No','Yes'),
	array('Kuttenberg','Pilgrams','No','Yes'),
	array('Kuttenberg','Iglau','No','Yes'),
	array('Pardubitz','Iglau','No','Yes'),
	array('Brünn','Iglau','Yes','No'),
	array('Brünn','Znoim','No','Yes'),
	array('Brünn','Lundenburg','Yes','Yes'),
	array('Landshut','Straubing','No','Yes'),
	array('Landshut','München','No','Yes'),
	array('Landshut','Passau','No','Yes'),
	array('Straubing','Klattau','No','Yes'),
	array('Straubing','Passau','No','Yes'),
	array('Pilsen','Klattau','No','Yes'),
	array('Pilsen','Rokitzan','Yes','Yes'),
	array('Klattau','Rokitzan','No','Yes'),
	array('Klattau','Pisek','No','Yes'),
	array('Klattau','Passau','No','Yes'),
	array('Klattau','Krumlau','No','Yes'),
	array('Rokitzan','Pibrams','No','Yes'),
	array('Rokitzan','Pisek','No','Yes'),
	array('Pibrams','Pisek','No','Yes'),
	array('Pibrams','Tabor','No','Yes'),
	array('Pisek','Tabor','Yes','Yes'),
	array('Pisek','Krumlau','No','Yes'),
	array('Pisek','Budweis','Yes','Yes'),
	array('Tabor','Pilgrams','No','Yes'),
	array('Tabor','Budweis','Yes','Yes'),
	array('Pilgrams','Iglau','No','Yes'),
	array('Pilgrams','Budweis','No','Yes'),
	array('Pilgrams','Znoim','No','Yes'),
	array('Iglau','Znoim','No','Yes'),
	array('Iglau','Lundenburg','Yes','No'),
	array('München','Passau','Yes','Yes'),
	array('München','Salzburg','No','Yes'),
	array('Passau','Krumlau','No','Yes'),
	array('Passau','Salzburg','No','Yes'),
	array('Passau','Linz','Yes','No'),
	array('Krumlau','Budweis','No','Yes'),
	array('Krumlau','Salzburg','No','Yes'),
	array('Krumlau','Linz','No','Yes'),
	array('Krumlau','Hollabrunn','No','Yes'),
	array('Budweis','Znoim','No','Yes'),
	array('Budweis','Hollabrunn','No','Yes'),
	array('Znoim','Lundenburg','No','Yes'),
	array('Znoim','Hollabrunn','No','Yes'),
	array('Lundenburg','Hollabrunn','No','Yes'),
	array('Lundenburg','Wien','Yes','Yes'),
	array('Lundenburg','Pressburg','Yes','Yes'),
	array('Salzburg','Linz','No','Yes'),
	array('Salzburg','Sankt Pölten','No','Yes'),
	array('Linz','Hollabrunn','No','Yes'),
	array('Linz','Wien','Yes','No'),
	array('Linz','Sankt Pölten','No','Yes'),
	array('Hollabrunn','Wien','No','Yes'),
	array('Hollabrunn','Sankt Pölten','No','Yes'),
	array('Wien','Sankt Pölten','No','Yes'),
	array('Wien','Pressburg','Yes','Yes'),
	array('Sankt Pölten','Pressburg','No','Yes'),
	array('Pressburg','Trentschin','No','Yes'),
	array('Pressburg','Ofen','Yes','Yes'),
	array('Trentschin','Ofen','No','Yes')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
