<?php
// This is file installs the map data for the Pirates variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Antigua', 'Coast', 'Yes', 0, 1096, 471, 692, 283),
	array('Barbados', 'Coast', 'Yes', 2, 1140, 625, 712, 390),
	array('Bay of Honduras', 'Coast', 'No', 0, 341, 418, 213, 261),
	array('Baymen Ports', 'Coast', 'Yes', 0, 285, 464, 178, 290),
	array('Bermuda Triangle', 'Coast', 'No', 10, 868, 168, 542, 105),
	array('Bermuda', 'Coast', 'Yes', 0, 951, 72, 588, 41),
	array('Buried Treasure', 'Coast', 'Yes', 0, 577, 775, 358, 483),
	array('Caicos and Turks Islands', 'Coast', 'No', 0, 780, 325, 487, 203),
	array('Campeche', 'Coast', 'Yes', 5, 211, 407, 132, 254),
	array('Cannonball Coast', 'Coast', 'No', 0, 609, 75, 380, 47),
	array('Cantina el Borracho', 'Coast', 'No', 1, 38, 399, 24, 249),
	array('Caracus', 'Coast', 'Yes', 5, 952, 722, 594, 453),
	array('Cartagena', 'Coast', 'Yes', 0, 636, 713, 402, 441),
	array('Cayman Islands', 'Coast', 'No', 1, 495, 404, 309, 252),
	array('Central Caribbean Sea', 'Coast', 'No', 12, 745, 546, 465, 341),
	array('Coro', 'Coast', 'Yes', 0, 815, 681, 505, 423),
	array('Crooked Island Passage', 'Coast', 'No', 10, 740, 258, 463, 175),
	array('Cunana', 'Coast', 'Yes', 0, 998, 711, 622, 442),
	array('Curacao', 'Coast', 'Yes', 4, 862, 658, 538, 411),
	array('Deadman\\\'s Trench', 'Coast', 'No', 0, 1131, 508, 706, 317),
	array('East Cuba', 'Coast', 'No', 1, 645, 338, 403, 211),
	array('Eastern Bay of Campeche', 'Coast', 'No', 0, 181, 371, 104, 222),
	array('Eastern Gulf of Darien', 'Coast', 'No', 0, 602, 729, 376, 455),
	array('Eastern Gulf of Mexico', 'Coast', 'No', 0, 389, 135, 243, 84),
	array('Eastern New Grenada', 'Coast', 'No', 1, 741, 762, 455, 470),
	array('Eleuthera', 'Coast', 'Yes', 0, 708, 227, 448, 149),
	array('Florida Channel', 'Coast', 'No', 13, 513, 244, 368, 152),
	array('Florida Keys', 'Coast', 'Yes', 7, 482, 226, 301, 141),
	array('Florida', 'Coast', 'No', 1, 508, 93, 311, 28),
	array('Gibraltar', 'Coast', 'Yes', 0, 777, 721, 482, 448),
	array('Gran Granada', 'Coast', 'Yes', 0, 372, 666, 236, 424),
	array('Grand Bahama', 'Coast', 'Yes', 0, 649, 117, 405, 73),
	array('Grenada', 'Coast', 'Yes', 0, 1105, 584, 688, 367),
	array('Guadeloupe', 'Coast', 'Yes', 3, 1097, 511, 685, 319),
	array('Gulf of Venezuela', 'Coast', 'No', 12, 783, 655, 490, 412),
	array('Gulf Stream', 'Coast', 'No', 0, 1127, 295, 704, 184),
	array('Havana', 'Coast', 'Yes', 1, 424, 293, 284, 174),
	array('Hispaniola', 'Coast', 'No', 3, 790, 427, 492, 277),
	array('Honduras', 'Coast', 'No', 1, 309, 533, 193, 333),
	array('Isla Blanquilla', 'Coast', 'No', 1, 1060, 649, 662, 405),
	array('Isla de los Pinos', 'Coast', 'No', 9, 471, 308, 292, 202),
	array('Jamaica Channel', 'Coast', 'No', 0, 679, 452, 424, 282),
	array('Jamaica', 'Coast', 'No', 2, 604, 432, 384, 272),
	array('Keelhaul Key', 'Coast', 'No', 0, 1004, 523, 650, 323),
	array('La Vega', 'Coast', 'Yes', 0, 804, 383, 520, 247),
	array('Louisiana', 'Coast', 'No', 1, 279, 40, 174, 25),
	array('Maracaibo Lagoon', 'Coast', 'No', 0, 756, 745, 471, 464),
	array('Maracaibo', 'Coast', 'Yes', 0, 742, 706, 457, 449),
	array('Margarita', 'Coast', 'Yes', 0, 1033, 663, 651, 421),
	array('Martinique', 'Coast', 'Yes', 3, 1097, 545, 677, 333),
	array('Mayaguana Passage', 'Coast', 'No', 13, 733, 324, 458, 202),
	array('Mayan Gold', 'Coast', 'Yes', 0, 313, 390, 192, 252),
	array('Mermaid Peaks', 'Coast', 'No', 0, 1111, 394, 694, 246),
	array('Mid Atlantic', 'Coast', 'No', 8, 1084, 136, 677, 85),
	array('Mona Passage', 'Coast', 'No', 8, 890, 437, 556, 273),
	array('Montserrat', 'Coast', 'Yes', 0, 1010, 495, 632, 308),
	array('Mosquito Coast', 'Coast', 'No', 1, 390, 611, 250, 365),
	array('Nassau', 'Coast', 'Yes', 0, 623, 201, 384, 130),
	array('New Andalucia', 'Coast', 'No', 1, 1038, 731, 644, 455),
	array('New Grenada', 'Coast', 'No', 0, 674, 758, 421, 473),
	array('Nombre de Dior', 'Coast', 'Yes', 0, 548, 767, 346, 472),
	array('North Caribbean Sea', 'Coast', 'No', 0, 849, 476, 530, 297),
	array('North Riff', 'Coast', 'No', 13, 843, 349, 539, 227),
	array('Northeast Caribbean Sea', 'Coast', 'No', 11, 897, 513, 560, 320),
	array('Northern Gulf of Mexico', 'Coast', 'No', 9, 136, 144, 85, 90),
	array('Northwest Caribbean Sea', 'Coast', 'No', 11, 498, 520, 298, 322),
	array('Northwest Channel', 'Coast', 'No', 10, 581, 175, 363, 109),
	array('Old Bahama Strait', 'Coast', 'No', 1, 613, 290, 383, 181),
	array('Old Spanish Armory', 'Coast', 'Yes', 0, 564, 346, 355, 220),
	array('Orinico', 'Coast', 'No', 0, 1137, 750, 710, 468),
	array('Panama', 'Coast', 'Yes', 1, 508, 745, 317, 465),
	array('Petit Goave', 'Coast', 'Yes', 0, 729, 432, 468, 271),
	array('Pirate Coast', 'Coast', 'No', 1, 391, 711, 244, 444),
	array('Port Royal', 'Coast', 'Yes', 6, 634, 448, 396, 280),
	array('Port-de-Paix', 'Coast', 'Yes', 0, 756, 386, 474, 244),
	array('Providence', 'Coast', 'Yes', 6, 424, 636, 265, 397),
	array('Puerto Bello', 'Coast', 'Yes', 0, 423, 751, 265, 471),
	array('Puerto Cabello', 'Coast', 'Yes', 0, 913, 710, 568, 444),
	array('Rio de la Hacha', 'Coast', 'Yes', 0, 748, 648, 473, 407),
	array('Rum Distillery', 'Coast', 'Yes', 0, 803, 296, 501, 188),
	array('San Juan', 'Coast', 'Yes', 0, 954, 436, 597, 272),
	array('Santa Maria', 'Coast', 'Yes', 0, 661, 690, 411, 432),
	array('Santiago', 'Coast', 'Yes', 0, 626, 376, 387, 234),
	array('Santo Poco', 'Coast', 'Yes', 0, 10, 310, 6, 196),
	array('Shipwreck Bay', 'Coast', 'No', 0, 458, 703, 286, 439),
	array('Singing Bush', 'Coast', 'No', 1, 43, 120, 37, 74),
	array('Skeleton Bluff', 'Coast', 'No', 12, 996, 578, 632, 344),
	array('South Caribbean Sea', 'Coast', 'No', 11, 607, 629, 379, 393),
	array('Southeast Caribbean Sea', 'Coast', 'No', 8, 880, 610, 532, 385),
	array('Southwest Caribbean Sea', 'Coast', 'No', 11, 524, 578, 327, 361),
	array('Spanish Town', 'Coast', 'Yes', 2, 588, 442, 367, 276),
	array('St Augustine', 'Coast', 'Yes', 0, 551, 53, 346, 38),
	array('St Domingue', 'Coast', 'Yes', 3, 860, 428, 541, 273),
	array('St Eustatius', 'Coast', 'Yes', 4, 1021, 452, 642, 286),
	array('St Kitts', 'Coast', 'Yes', 2, 1049, 474, 655, 296),
	array('St Lucia', 'Coast', 'Yes', 0, 1067, 567, 667, 354),
	array('St Martin', 'Coast', 'Yes', 4, 1034, 418, 646, 261),
	array('Terra Firma', 'Coast', 'No', 1, 855, 711, 534, 444),
	array('Tobago', 'Coast', 'No', 1, 1118, 690, 698, 431),
	array('Tongue of the Ocean', 'Coast', 'No', 13, 651, 223, 406, 161),
	array('Tortuga', 'Coast', 'Yes', 7, 765, 362, 486, 230),
	array('Treasure Island', 'Coast', 'Yes', 0, 783, 456, 487, 293),
	array('Trinadad', 'Coast', 'Yes', 0, 1068, 697, 668, 437),
	array('Veracruz', 'Coast', 'Yes', 0, 153, 428, 98, 270),
	array('Virgin Islands', 'Coast', 'No', 10, 987, 460, 609, 281),
	array('Voodoo Witch Hut', 'Coast', 'Yes', 1, 592, 335, 336, 178),
	array('Waters of the Spanish Main', 'Coast', 'No', 12, 996, 679, 622, 424),
	array('West Atlantic', 'Coast', 'No', 6, 772, 99, 482, 62),
	array('West Cuba', 'Coast', 'No', 1, 535, 309, 334, 193),
	array('Western Bay of Campeche', 'Coast', 'No', 0, 96, 415, 60, 259),
	array('Western Gulf of Darien', 'Coast', 'No', 0, 570, 684, 356, 427),
	array('Western Gulf of Mexico', 'Coast', 'No', 9, 258, 255, 161, 159),
	array('Western New Grenada', 'Coast', 'No', 1, 601, 767, 386, 470),
	array('Windward Passage', 'Coast', 'No', 0, 724, 373, 452, 233),
	array('Yaguano', 'Coast', 'Yes', 0, 765, 423, 471, 253),
	array('Yuchatan Channel', 'Coast', 'No', 9, 373, 338, 233, 211),
	array('Yuchatan', 'Coast', 'No', 1, 293, 328, 183, 205)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Antigua','Deadman\\\'s Trench','Yes','No'),
	array('Antigua','Guadeloupe','Yes','Yes'),
	array('Antigua','Gulf Stream','Yes','No'),
	array('Antigua','Keelhaul Key','Yes','No'),
	array('Antigua','Martinique','Yes','No'),
	array('Antigua','Mermaid Peaks','Yes','Yes'),
	array('Antigua','Mid Atlantic','Yes','No'),
	array('Antigua','Montserrat','Yes','No'),
	array('Antigua','Northeast Caribbean Sea','Yes','No'),
	array('Antigua','St Eustatius','Yes','Yes'),
	array('Antigua','St Kitts','Yes','Yes'),
	array('Antigua','St Martin','Yes','No'),
	array('Antigua','Virgin Islands','Yes','No'),
	array('Barbados','Deadman\\\'s Trench','Yes','Yes'),
	array('Barbados','Grenada','Yes','Yes'),
	array('Barbados','Guadeloupe','Yes','No'),
	array('Barbados','Gulf Stream','Yes','Yes'),
	array('Barbados','Isla Blanquilla','Yes','No'),
	array('Barbados','Keelhaul Key','Yes','No'),
	array('Barbados','Martinique','Yes','Yes'),
	array('Barbados','Mermaid Peaks','Yes','No'),
	array('Barbados','Mid Atlantic','Yes','No'),
	array('Barbados','New Andalucia','Yes','No'),
	array('Barbados','Orinico','Yes','No'),
	array('Barbados','Skeleton Bluff','Yes','No'),
	array('Barbados','St Lucia','Yes','Yes'),
	array('Barbados','Tobago','Yes','Yes'),
	array('Barbados','Trinadad','Yes','No'),
	array('Barbados','Waters of the Spanish Main','Yes','No'),
	array('Bay of Honduras','Baymen Ports','Yes','Yes'),
	array('Bay of Honduras','Campeche','Yes','No'),
	array('Bay of Honduras','Cayman Islands','Yes','No'),
	array('Bay of Honduras','Central Caribbean Sea','Yes','No'),
	array('Bay of Honduras','Eastern Bay of Campeche','Yes','No'),
	array('Bay of Honduras','Eastern Gulf of Mexico','Yes','No'),
	array('Bay of Honduras','Gran Granada','Yes','No'),
	array('Bay of Honduras','Havana','Yes','No'),
	array('Bay of Honduras','Honduras','Yes','Yes'),
	array('Bay of Honduras','Isla de los Pinos','Yes','No'),
	array('Bay of Honduras','Jamaica Channel','Yes','No'),
	array('Bay of Honduras','Mayan Gold','Yes','Yes'),
	array('Bay of Honduras','Mosquito Coast','Yes','Yes'),
	array('Bay of Honduras','North Caribbean Sea','Yes','No'),
	array('Bay of Honduras','Northwest Caribbean Sea','Yes','Yes'),
	array('Bay of Honduras','Port Royal','Yes','No'),
	array('Bay of Honduras','Providence','Yes','No'),
	array('Bay of Honduras','Southwest Caribbean Sea','Yes','No'),
	array('Bay of Honduras','Spanish Town','Yes','No'),
	array('Bay of Honduras','Western Gulf of Mexico','Yes','No'),
	array('Bay of Honduras','Yuchatan Channel','Yes','Yes'),
	array('Bay of Honduras','Yuchatan','Yes','Yes'),
	array('Baymen Ports','Honduras','Yes','Yes'),
	array('Baymen Ports','Mayan Gold','Yes','Yes'),
	array('Baymen Ports','Mosquito Coast','Yes','No'),
	array('Baymen Ports','Northwest Caribbean Sea','Yes','No'),
	array('Baymen Ports','Yuchatan Channel','Yes','No'),
	array('Baymen Ports','Yuchatan','Yes','No'),
	array('Bermuda Triangle','Bermuda','Yes','Yes'),
	array('Bermuda Triangle','Caicos and Turks Islands','Yes','Yes'),
	array('Bermuda Triangle','Cannonball Coast','Yes','No'),
	array('Bermuda Triangle','Crooked Island Passage','Yes','Yes'),
	array('Bermuda Triangle','East Cuba','Yes','No'),
	array('Bermuda Triangle','Eleuthera','Yes','Yes'),
	array('Bermuda Triangle','Florida','Yes','No'),
	array('Bermuda Triangle','Grand Bahama','Yes','Yes'),
	array('Bermuda Triangle','Gulf Stream','Yes','No'),
	array('Bermuda Triangle','La Vega','Yes','No'),
	array('Bermuda Triangle','Mayaguana Passage','Yes','Yes'),
	array('Bermuda Triangle','Mermaid Peaks','Yes','No'),
	array('Bermuda Triangle','Mid Atlantic','Yes','Yes'),
	array('Bermuda Triangle','Mona Passage','Yes','Yes'),
	array('Bermuda Triangle','Nassau','Yes','No'),
	array('Bermuda Triangle','North Caribbean Sea','Yes','No'),
	array('Bermuda Triangle','North Riff','Yes','Yes'),
	array('Bermuda Triangle','Northeast Caribbean Sea','Yes','No'),
	array('Bermuda Triangle','Northwest Channel','Yes','No'),
	array('Bermuda Triangle','Old Bahama Strait','Yes','No'),
	array('Bermuda Triangle','Port-de-Paix','Yes','No'),
	array('Bermuda Triangle','Rum Distillery','Yes','Yes'),
	array('Bermuda Triangle','San Juan','Yes','Yes'),
	array('Bermuda Triangle','Santiago','Yes','No'),
	array('Bermuda Triangle','St Domingue','Yes','No'),
	array('Bermuda Triangle','St Eustatius','Yes','No'),
	array('Bermuda Triangle','St Kitts','Yes','No'),
	array('Bermuda Triangle','St Martin','Yes','No'),
	array('Bermuda Triangle','Tongue of the Ocean','Yes','No'),
	array('Bermuda Triangle','Tortuga','Yes','No'),
	array('Bermuda Triangle','Virgin Islands','Yes','Yes'),
	array('Bermuda Triangle','West Atlantic','Yes','Yes'),
	array('Bermuda Triangle','Windward Passage','Yes','No'),
	array('Bermuda','Caicos and Turks Islands','Yes','No'),
	array('Bermuda','Cannonball Coast','Yes','No'),
	array('Bermuda','Crooked Island Passage','Yes','No'),
	array('Bermuda','Eleuthera','Yes','No'),
	array('Bermuda','Grand Bahama','Yes','No'),
	array('Bermuda','Gulf Stream','Yes','No'),
	array('Bermuda','Mayaguana Passage','Yes','No'),
	array('Bermuda','Mermaid Peaks','Yes','No'),
	array('Bermuda','Mid Atlantic','Yes','Yes'),
	array('Bermuda','Mona Passage','Yes','No'),
	array('Bermuda','North Riff','Yes','No'),
	array('Bermuda','Rum Distillery','Yes','No'),
	array('Bermuda','San Juan','Yes','No'),
	array('Bermuda','St Eustatius','Yes','No'),
	array('Bermuda','St Martin','Yes','No'),
	array('Bermuda','Virgin Islands','Yes','No'),
	array('Bermuda','West Atlantic','Yes','Yes'),
	array('Buried Treasure','Cartagena','Yes','No'),
	array('Buried Treasure','Eastern Gulf of Darien','Yes','Yes'),
	array('Buried Treasure','Nombre de Dior','Yes','Yes'),
	array('Buried Treasure','Panama','Yes','No'),
	array('Buried Treasure','Santa Maria','Yes','No'),
	array('Buried Treasure','South Caribbean Sea','Yes','No'),
	array('Buried Treasure','Southwest Caribbean Sea','Yes','No'),
	array('Buried Treasure','Western Gulf of Darien','Yes','Yes'),
	array('Buried Treasure','Western New Grenada','Yes','Yes'),
	array('Caicos and Turks Islands','Crooked Island Passage','Yes','No'),
	array('Caicos and Turks Islands','Eleuthera','Yes','No'),
	array('Caicos and Turks Islands','Grand Bahama','Yes','No'),
	array('Caicos and Turks Islands','La Vega','Yes','No'),
	array('Caicos and Turks Islands','Mayaguana Passage','Yes','Yes'),
	array('Caicos and Turks Islands','Mid Atlantic','Yes','No'),
	array('Caicos and Turks Islands','Mona Passage','Yes','No'),
	array('Caicos and Turks Islands','North Riff','Yes','Yes'),
	array('Caicos and Turks Islands','Port-de-Paix','Yes','No'),
	array('Caicos and Turks Islands','Rum Distillery','Yes','Yes'),
	array('Caicos and Turks Islands','San Juan','Yes','No'),
	array('Caicos and Turks Islands','Tortuga','Yes','Yes'),
	array('Caicos and Turks Islands','Virgin Islands','Yes','No'),
	array('Caicos and Turks Islands','West Atlantic','Yes','No'),
	array('Caicos and Turks Islands','Windward Passage','Yes','No'),
	array('Campeche','Cantina el Borracho','Yes','No'),
	array('Campeche','Eastern Bay of Campeche','Yes','Yes'),
	array('Campeche','Mayan Gold','Yes','No'),
	array('Campeche','Veracruz','Yes','Yes'),
	array('Campeche','Western Bay of Campeche','Yes','No'),
	array('Campeche','Western Gulf of Mexico','Yes','No'),
	array('Campeche','Yuchatan Channel','Yes','No'),
	array('Campeche','Yuchatan','Yes','Yes'),
	array('Cannonball Coast','Eastern Gulf of Mexico','Yes','No'),
	array('Cannonball Coast','Eleuthera','Yes','No'),
	array('Cannonball Coast','Florida Channel','Yes','No'),
	array('Cannonball Coast','Florida Keys','Yes','No'),
	array('Cannonball Coast','Florida','Yes','Yes'),
	array('Cannonball Coast','Grand Bahama','Yes','Yes'),
	array('Cannonball Coast','Louisiana','Yes','No'),
	array('Cannonball Coast','Nassau','Yes','No'),
	array('Cannonball Coast','Northern Gulf of Mexico','Yes','No'),
	array('Cannonball Coast','Northwest Channel','Yes','No'),
	array('Cannonball Coast','St Augustine','Yes','Yes'),
	array('Cannonball Coast','West Atlantic','Yes','Yes'),
	array('Cantina el Borracho','Eastern Bay of Campeche','Yes','No'),
	array('Cantina el Borracho','Santo Poco','Yes','Yes'),
	array('Cantina el Borracho','Singing Bush','Yes','No'),
	array('Cantina el Borracho','Veracruz','Yes','Yes'),
	array('Cantina el Borracho','Western Bay of Campeche','Yes','Yes'),
	array('Cantina el Borracho','Western Gulf of Mexico','Yes','No'),
	array('Caracus','Coro','Yes','No'),
	array('Caracus','Cunana','Yes','Yes'),
	array('Caracus','Curacao','Yes','No'),
	array('Caracus','Gulf of Venezuela','Yes','No'),
	array('Caracus','Isla Blanquilla','Yes','No'),
	array('Caracus','Margarita','Yes','No'),
	array('Caracus','New Andalucia','Yes','No'),
	array('Caracus','Puerto Cabello','Yes','Yes'),
	array('Caracus','South Caribbean Sea','Yes','No'),
	array('Caracus','Southeast Caribbean Sea','Yes','No'),
	array('Caracus','Terra Firma','Yes','No'),
	array('Caracus','Tobago','Yes','No'),
	array('Caracus','Trinadad','Yes','No'),
	array('Caracus','Waters of the Spanish Main','Yes','Yes'),
	array('Cartagena','Eastern Gulf of Darien','Yes','Yes'),
	array('Cartagena','Rio de la Hacha','Yes','No'),
	array('Cartagena','Santa Maria','Yes','Yes'),
	array('Cartagena','South Caribbean Sea','Yes','No'),
	array('Cartagena','Western Gulf of Darien','Yes','No'),
	array('Cartagena','Western New Grenada','Yes','Yes'),
	array('Cayman Islands','Central Caribbean Sea','Yes','No'),
	array('Cayman Islands','Crooked Island Passage','Yes','No'),
	array('Cayman Islands','East Cuba','Yes','No'),
	array('Cayman Islands','Eastern Bay of Campeche','Yes','No'),
	array('Cayman Islands','Eastern Gulf of Mexico','Yes','No'),
	array('Cayman Islands','Havana','Yes','No'),
	array('Cayman Islands','Isla de los Pinos','Yes','Yes'),
	array('Cayman Islands','Jamaica Channel','Yes','Yes'),
	array('Cayman Islands','Jamaica','Yes','Yes'),
	array('Cayman Islands','Mosquito Coast','Yes','No'),
	array('Cayman Islands','North Caribbean Sea','Yes','No'),
	array('Cayman Islands','Northwest Caribbean Sea','Yes','Yes'),
	array('Cayman Islands','Old Spanish Armory','Yes','Yes'),
	array('Cayman Islands','Petit Goave','Yes','No'),
	array('Cayman Islands','Port Royal','Yes','No'),
	array('Cayman Islands','Providence','Yes','No'),
	array('Cayman Islands','Santiago','Yes','Yes'),
	array('Cayman Islands','Southwest Caribbean Sea','Yes','No'),
	array('Cayman Islands','Spanish Town','Yes','Yes'),
	array('Cayman Islands','Voodoo Witch Hut','Yes','Yes'),
	array('Cayman Islands','West Cuba','Yes','No'),
	array('Cayman Islands','Western Gulf of Mexico','Yes','No'),
	array('Cayman Islands','Windward Passage','Yes','No'),
	array('Cayman Islands','Yuchatan Channel','Yes','Yes'),
	array('Cayman Islands','Yuchatan','Yes','No'),
	array('Central Caribbean Sea','Curacao','Yes','No'),
	array('Central Caribbean Sea','Eastern Gulf of Darien','Yes','No'),
	array('Central Caribbean Sea','Gulf of Venezuela','Yes','No'),
	array('Central Caribbean Sea','Hispaniola','Yes','No'),
	array('Central Caribbean Sea','Isla Blanquilla','Yes','No'),
	array('Central Caribbean Sea','Jamaica Channel','Yes','No'),
	array('Central Caribbean Sea','Keelhaul Key','Yes','No'),
	array('Central Caribbean Sea','Margarita','Yes','No'),
	array('Central Caribbean Sea','Mona Passage','Yes','No'),
	array('Central Caribbean Sea','Montserrat','Yes','No'),
	array('Central Caribbean Sea','Mosquito Coast','Yes','No'),
	array('Central Caribbean Sea','North Caribbean Sea','Yes','Yes'),
	array('Central Caribbean Sea','Northeast Caribbean Sea','Yes','Yes'),
	array('Central Caribbean Sea','Northwest Caribbean Sea','Yes','Yes'),
	array('Central Caribbean Sea','Panama','Yes','No'),
	array('Central Caribbean Sea','Petit Goave','Yes','No'),
	array('Central Caribbean Sea','Port Royal','Yes','No'),
	array('Central Caribbean Sea','Providence','Yes','No'),
	array('Central Caribbean Sea','Rio de la Hacha','Yes','No'),
	array('Central Caribbean Sea','San Juan','Yes','No'),
	array('Central Caribbean Sea','Santa Maria','Yes','No'),
	array('Central Caribbean Sea','Shipwreck Bay','Yes','No'),
	array('Central Caribbean Sea','Skeleton Bluff','Yes','No'),
	array('Central Caribbean Sea','South Caribbean Sea','Yes','Yes'),
	array('Central Caribbean Sea','Southeast Caribbean Sea','Yes','Yes'),
	array('Central Caribbean Sea','Southwest Caribbean Sea','Yes','Yes'),
	array('Central Caribbean Sea','Spanish Town','Yes','No'),
	array('Central Caribbean Sea','St Domingue','Yes','No'),
	array('Central Caribbean Sea','St Kitts','Yes','No'),
	array('Central Caribbean Sea','Treasure Island','Yes','No'),
	array('Central Caribbean Sea','Virgin Islands','Yes','No'),
	array('Central Caribbean Sea','Waters of the Spanish Main','Yes','No'),
	array('Central Caribbean Sea','Western Gulf of Darien','Yes','No'),
	array('Central Caribbean Sea','Yuchatan Channel','Yes','No'),
	array('Coro','Cunana','Yes','No'),
	array('Coro','Curacao','Yes','No'),
	array('Coro','Eastern New Grenada','Yes','No'),
	array('Coro','Gibraltar','Yes','Yes'),
	array('Coro','Gulf of Venezuela','Yes','Yes'),
	array('Coro','Isla Blanquilla','Yes','No'),
	array('Coro','Maracaibo Lagoon','Yes','Yes'),
	array('Coro','Maracaibo','Yes','No'),
	array('Coro','Margarita','Yes','No'),
	array('Coro','New Andalucia','Yes','No'),
	array('Coro','Puerto Cabello','Yes','No'),
	array('Coro','Rio de la Hacha','Yes','No'),
	array('Coro','South Caribbean Sea','Yes','No'),
	array('Coro','Southeast Caribbean Sea','Yes','No'),
	array('Coro','Terra Firma','Yes','Yes'),
	array('Coro','Tobago','Yes','No'),
	array('Coro','Trinadad','Yes','No'),
	array('Coro','Waters of the Spanish Main','Yes','Yes'),
	array('Crooked Island Passage','East Cuba','Yes','Yes'),
	array('Crooked Island Passage','Eleuthera','Yes','Yes'),
	array('Crooked Island Passage','Florida Channel','Yes','No'),
	array('Crooked Island Passage','Grand Bahama','Yes','No'),
	array('Crooked Island Passage','Jamaica Channel','Yes','No'),
	array('Crooked Island Passage','Mayaguana Passage','Yes','Yes'),
	array('Crooked Island Passage','Mid Atlantic','Yes','No'),
	array('Crooked Island Passage','Mona Passage','Yes','No'),
	array('Crooked Island Passage','Nassau','Yes','No'),
	array('Crooked Island Passage','North Riff','Yes','No'),
	array('Crooked Island Passage','Old Bahama Strait','Yes','Yes'),
	array('Crooked Island Passage','Petit Goave','Yes','No'),
	array('Crooked Island Passage','Port-de-Paix','Yes','No'),
	array('Crooked Island Passage','Rum Distillery','Yes','No'),
	array('Crooked Island Passage','San Juan','Yes','No'),
	array('Crooked Island Passage','Santiago','Yes','Yes'),
	array('Crooked Island Passage','Tongue of the Ocean','Yes','Yes'),
	array('Crooked Island Passage','Tortuga','Yes','No'),
	array('Crooked Island Passage','Virgin Islands','Yes','No'),
	array('Crooked Island Passage','Voodoo Witch Hut','Yes','No'),
	array('Crooked Island Passage','West Atlantic','Yes','No'),
	array('Crooked Island Passage','Windward Passage','Yes','Yes'),
	array('Crooked Island Passage','Yaguano','Yes','No'),
	array('Cunana','Curacao','Yes','No'),
	array('Cunana','Gulf of Venezuela','Yes','No'),
	array('Cunana','Isla Blanquilla','Yes','No'),
	array('Cunana','Margarita','Yes','No'),
	array('Cunana','New Andalucia','Yes','Yes'),
	array('Cunana','Orinico','Yes','No'),
	array('Cunana','Puerto Cabello','Yes','No'),
	array('Cunana','South Caribbean Sea','Yes','No'),
	array('Cunana','Southeast Caribbean Sea','Yes','No'),
	array('Cunana','Terra Firma','Yes','No'),
	array('Cunana','Tobago','Yes','No'),
	array('Cunana','Trinadad','Yes','No'),
	array('Cunana','Waters of the Spanish Main','Yes','Yes'),
	array('Curacao','Eastern Gulf of Darien','Yes','No'),
	array('Curacao','Gulf of Venezuela','Yes','No'),
	array('Curacao','Isla Blanquilla','Yes','No'),
	array('Curacao','Keelhaul Key','Yes','No'),
	array('Curacao','Maracaibo Lagoon','Yes','No'),
	array('Curacao','Maracaibo','Yes','No'),
	array('Curacao','Margarita','Yes','No'),
	array('Curacao','Montserrat','Yes','No'),
	array('Curacao','New Andalucia','Yes','No'),
	array('Curacao','Northeast Caribbean Sea','Yes','No'),
	array('Curacao','Puerto Cabello','Yes','No'),
	array('Curacao','Rio de la Hacha','Yes','No'),
	array('Curacao','Santa Maria','Yes','No'),
	array('Curacao','Skeleton Bluff','Yes','No'),
	array('Curacao','South Caribbean Sea','Yes','Yes'),
	array('Curacao','Southeast Caribbean Sea','Yes','Yes'),
	array('Curacao','Southwest Caribbean Sea','Yes','No'),
	array('Curacao','Terra Firma','Yes','No'),
	array('Curacao','Tobago','Yes','No'),
	array('Curacao','Trinadad','Yes','No'),
	array('Curacao','Waters of the Spanish Main','Yes','Yes'),
	array('Deadman\\\'s Trench','Grenada','Yes','No'),
	array('Deadman\\\'s Trench','Guadeloupe','Yes','Yes'),
	array('Deadman\\\'s Trench','Gulf Stream','Yes','Yes'),
	array('Deadman\\\'s Trench','Keelhaul Key','Yes','No'),
	array('Deadman\\\'s Trench','Martinique','Yes','Yes'),
	array('Deadman\\\'s Trench','Mermaid Peaks','Yes','Yes'),
	array('Deadman\\\'s Trench','Mid Atlantic','Yes','No'),
	array('Deadman\\\'s Trench','Montserrat','Yes','No'),
	array('Deadman\\\'s Trench','Skeleton Bluff','Yes','No'),
	array('Deadman\\\'s Trench','St Eustatius','Yes','No'),
	array('Deadman\\\'s Trench','St Kitts','Yes','No'),
	array('Deadman\\\'s Trench','St Lucia','Yes','No'),
	array('Deadman\\\'s Trench','Tobago','Yes','No'),
	array('East Cuba','Eleuthera','Yes','No'),
	array('East Cuba','Florida Channel','Yes','No'),
	array('East Cuba','Havana','Yes','No'),
	array('East Cuba','Jamaica Channel','Yes','No'),
	array('East Cuba','Mayaguana Passage','Yes','No'),
	array('East Cuba','Old Bahama Strait','Yes','Yes'),
	array('East Cuba','Santiago','Yes','Yes'),
	array('East Cuba','Tongue of the Ocean','Yes','No'),
	array('East Cuba','Voodoo Witch Hut','Yes','Yes'),
	array('East Cuba','Windward Passage','Yes','No'),
	array('Eastern Bay of Campeche','Eastern Gulf of Mexico','Yes','No'),
	array('Eastern Bay of Campeche','Havana','Yes','No'),
	array('Eastern Bay of Campeche','Isla de los Pinos','Yes','No'),
	array('Eastern Bay of Campeche','Mayan Gold','Yes','No'),
	array('Eastern Bay of Campeche','Northern Gulf of Mexico','Yes','No'),
	array('Eastern Bay of Campeche','Northwest Caribbean Sea','Yes','No'),
	array('Eastern Bay of Campeche','Santo Poco','Yes','No'),
	array('Eastern Bay of Campeche','Singing Bush','Yes','No'),
	array('Eastern Bay of Campeche','Veracruz','Yes','Yes'),
	array('Eastern Bay of Campeche','Western Bay of Campeche','Yes','Yes'),
	array('Eastern Bay of Campeche','Western Gulf of Mexico','Yes','Yes'),
	array('Eastern Bay of Campeche','Yuchatan Channel','Yes','Yes'),
	array('Eastern Bay of Campeche','Yuchatan','Yes','Yes'),
	array('Eastern Gulf of Darien','Gulf of Venezuela','Yes','No'),
	array('Eastern Gulf of Darien','Nombre de Dior','Yes','No'),
	array('Eastern Gulf of Darien','Panama','Yes','No'),
	array('Eastern Gulf of Darien','Rio de la Hacha','Yes','No'),
	array('Eastern Gulf of Darien','Santa Maria','Yes','Yes'),
	array('Eastern Gulf of Darien','South Caribbean Sea','Yes','Yes'),
	array('Eastern Gulf of Darien','Southeast Caribbean Sea','Yes','No'),
	array('Eastern Gulf of Darien','Southwest Caribbean Sea','Yes','No'),
	array('Eastern Gulf of Darien','Waters of the Spanish Main','Yes','No'),
	array('Eastern Gulf of Darien','Western Gulf of Darien','Yes','Yes'),
	array('Eastern Gulf of Darien','Western New Grenada','Yes','Yes'),
	array('Eastern Gulf of Mexico','Florida Channel','Yes','Yes'),
	array('Eastern Gulf of Mexico','Florida Keys','Yes','Yes'),
	array('Eastern Gulf of Mexico','Florida','Yes','Yes'),
	array('Eastern Gulf of Mexico','Grand Bahama','Yes','No'),
	array('Eastern Gulf of Mexico','Havana','Yes','Yes'),
	array('Eastern Gulf of Mexico','Isla de los Pinos','Yes','No'),
	array('Eastern Gulf of Mexico','Louisiana','Yes','No'),
	array('Eastern Gulf of Mexico','Nassau','Yes','No'),
	array('Eastern Gulf of Mexico','Northern Gulf of Mexico','Yes','Yes'),
	array('Eastern Gulf of Mexico','Northwest Caribbean Sea','Yes','No'),
	array('Eastern Gulf of Mexico','Northwest Channel','Yes','No'),
	array('Eastern Gulf of Mexico','Old Bahama Strait','Yes','No'),
	array('Eastern Gulf of Mexico','Santo Poco','Yes','No'),
	array('Eastern Gulf of Mexico','Singing Bush','Yes','No'),
	array('Eastern Gulf of Mexico','St Augustine','Yes','No'),
	array('Eastern Gulf of Mexico','Tongue of the Ocean','Yes','No'),
	array('Eastern Gulf of Mexico','Voodoo Witch Hut','Yes','No'),
	array('Eastern Gulf of Mexico','West Cuba','Yes','No'),
	array('Eastern Gulf of Mexico','Western Bay of Campeche','Yes','No'),
	array('Eastern Gulf of Mexico','Western Gulf of Mexico','Yes','Yes'),
	array('Eastern Gulf of Mexico','Yuchatan Channel','Yes','Yes'),
	array('Eastern Gulf of Mexico','Yuchatan','Yes','No'),
	array('Eastern New Grenada','Gibraltar','Yes','Yes'),
	array('Eastern New Grenada','Gulf of Venezuela','Yes','No'),
	array('Eastern New Grenada','Maracaibo Lagoon','Yes','Yes'),
	array('Eastern New Grenada','Maracaibo','Yes','Yes'),
	array('Eastern New Grenada','Rio de la Hacha','Yes','No'),
	array('Eleuthera','Florida Channel','Yes','No'),
	array('Eleuthera','Florida','Yes','No'),
	array('Eleuthera','Grand Bahama','Yes','Yes'),
	array('Eleuthera','Mayaguana Passage','Yes','No'),
	array('Eleuthera','Mid Atlantic','Yes','No'),
	array('Eleuthera','Mona Passage','Yes','No'),
	array('Eleuthera','Nassau','Yes','Yes'),
	array('Eleuthera','North Riff','Yes','No'),
	array('Eleuthera','Northwest Channel','Yes','No'),
	array('Eleuthera','Old Bahama Strait','Yes','No'),
	array('Eleuthera','Rum Distillery','Yes','No'),
	array('Eleuthera','San Juan','Yes','No'),
	array('Eleuthera','Santiago','Yes','No'),
	array('Eleuthera','Tongue of the Ocean','Yes','Yes'),
	array('Eleuthera','Virgin Islands','Yes','No'),
	array('Eleuthera','West Atlantic','Yes','No'),
	array('Eleuthera','Windward Passage','Yes','No'),
	array('Florida Channel','Florida Keys','Yes','Yes'),
	array('Florida Channel','Grand Bahama','Yes','No'),
	array('Florida Channel','Havana','Yes','Yes'),
	array('Florida Channel','Isla de los Pinos','Yes','No'),
	array('Florida Channel','Louisiana','Yes','No'),
	array('Florida Channel','Nassau','Yes','Yes'),
	array('Florida Channel','Northern Gulf of Mexico','Yes','No'),
	array('Florida Channel','Northwest Channel','Yes','Yes'),
	array('Florida Channel','Old Bahama Strait','Yes','Yes'),
	array('Florida Channel','St Augustine','Yes','No'),
	array('Florida Channel','Tongue of the Ocean','Yes','Yes'),
	array('Florida Channel','Voodoo Witch Hut','Yes','Yes'),
	array('Florida Channel','West Cuba','Yes','No'),
	array('Florida Channel','Western Gulf of Mexico','Yes','No'),
	array('Florida Channel','Yuchatan Channel','Yes','No'),
	array('Florida Keys','Florida','Yes','Yes'),
	array('Florida Keys','Grand Bahama','Yes','No'),
	array('Florida Keys','Havana','Yes','No'),
	array('Florida Keys','Louisiana','Yes','No'),
	array('Florida Keys','Nassau','Yes','No'),
	array('Florida Keys','Northern Gulf of Mexico','Yes','No'),
	array('Florida Keys','Northwest Channel','Yes','No'),
	array('Florida Keys','Old Bahama Strait','Yes','No'),
	array('Florida Keys','St Augustine','Yes','No'),
	array('Florida Keys','Tongue of the Ocean','Yes','No'),
	array('Florida Keys','Voodoo Witch Hut','Yes','No'),
	array('Florida Keys','Western Gulf of Mexico','Yes','No'),
	array('Florida Keys','Yuchatan Channel','Yes','No'),
	array('Florida','Grand Bahama','Yes','Yes'),
	array('Florida','Havana','Yes','No'),
	array('Florida','Louisiana','Yes','Yes'),
	array('Florida','Nassau','Yes','No'),
	array('Florida','Northern Gulf of Mexico','Yes','Yes'),
	array('Florida','Northwest Channel','Yes','Yes'),
	array('Florida','Old Bahama Strait','Yes','No'),
	array('Florida','Singing Bush','Yes','No'),
	array('Florida','St Augustine','Yes','Yes'),
	array('Florida','Tongue of the Ocean','Yes','No'),
	array('Florida','Voodoo Witch Hut','Yes','No'),
	array('Florida','West Atlantic','Yes','No'),
	array('Florida','Western Gulf of Mexico','Yes','No'),
	array('Florida','Yuchatan Channel','Yes','No'),
	array('Gibraltar','Gulf of Venezuela','Yes','No'),
	array('Gibraltar','Maracaibo Lagoon','Yes','Yes'),
	array('Gibraltar','Maracaibo','Yes','No'),
	array('Gibraltar','Terra Firma','Yes','No'),
	array('Gibraltar','Waters of the Spanish Main','Yes','No'),
	array('Gran Granada','Honduras','Yes','No'),
	array('Gran Granada','Mosquito Coast','Yes','Yes'),
	array('Gran Granada','Northwest Caribbean Sea','Yes','No'),
	array('Gran Granada','Pirate Coast','Yes','Yes'),
	array('Gran Granada','Providence','Yes','Yes'),
	array('Gran Granada','Puerto Bello','Yes','No'),
	array('Gran Granada','Shipwreck Bay','Yes','No'),
	array('Gran Granada','Southwest Caribbean Sea','Yes','No'),
	array('Grand Bahama','Louisiana','Yes','No'),
	array('Grand Bahama','Mayaguana Passage','Yes','No'),
	array('Grand Bahama','Mid Atlantic','Yes','No'),
	array('Grand Bahama','Mona Passage','Yes','No'),
	array('Grand Bahama','Nassau','Yes','Yes'),
	array('Grand Bahama','North Riff','Yes','No'),
	array('Grand Bahama','Northern Gulf of Mexico','Yes','No'),
	array('Grand Bahama','Northwest Channel','Yes','Yes'),
	array('Grand Bahama','Rum Distillery','Yes','No'),
	array('Grand Bahama','San Juan','Yes','No'),
	array('Grand Bahama','St Augustine','Yes','No'),
	array('Grand Bahama','Tongue of the Ocean','Yes','No'),
	array('Grand Bahama','Virgin Islands','Yes','No'),
	array('Grand Bahama','West Atlantic','Yes','Yes'),
	array('Grenada','Gulf Stream','Yes','No'),
	array('Grenada','Isla Blanquilla','Yes','Yes'),
	array('Grenada','Keelhaul Key','Yes','No'),
	array('Grenada','Margarita','Yes','No'),
	array('Grenada','Martinique','Yes','No'),
	array('Grenada','New Andalucia','Yes','No'),
	array('Grenada','Orinico','Yes','No'),
	array('Grenada','Skeleton Bluff','Yes','Yes'),
	array('Grenada','Southeast Caribbean Sea','Yes','No'),
	array('Grenada','St Lucia','Yes','Yes'),
	array('Grenada','Tobago','Yes','Yes'),
	array('Grenada','Trinadad','Yes','No'),
	array('Grenada','Waters of the Spanish Main','Yes','No'),
	array('Guadeloupe','Gulf Stream','Yes','No'),
	array('Guadeloupe','Keelhaul Key','Yes','Yes'),
	array('Guadeloupe','Martinique','Yes','Yes'),
	array('Guadeloupe','Mermaid Peaks','Yes','Yes'),
	array('Guadeloupe','Mid Atlantic','Yes','No'),
	array('Guadeloupe','Montserrat','Yes','Yes'),
	array('Guadeloupe','Northeast Caribbean Sea','Yes','No'),
	array('Guadeloupe','Skeleton Bluff','Yes','No'),
	array('Guadeloupe','Southeast Caribbean Sea','Yes','No'),
	array('Guadeloupe','St Eustatius','Yes','No'),
	array('Guadeloupe','St Kitts','Yes','Yes'),
	array('Guadeloupe','St Lucia','Yes','No'),
	array('Guadeloupe','Virgin Islands','Yes','No'),
	array('Gulf of Venezuela','Isla Blanquilla','Yes','No'),
	array('Gulf of Venezuela','Maracaibo Lagoon','Yes','Yes'),
	array('Gulf of Venezuela','Maracaibo','Yes','Yes'),
	array('Gulf of Venezuela','Margarita','Yes','No'),
	array('Gulf of Venezuela','New Andalucia','Yes','No'),
	array('Gulf of Venezuela','Puerto Cabello','Yes','No'),
	array('Gulf of Venezuela','Rio de la Hacha','Yes','Yes'),
	array('Gulf of Venezuela','Santa Maria','Yes','No'),
	array('Gulf of Venezuela','South Caribbean Sea','Yes','Yes'),
	array('Gulf of Venezuela','Southeast Caribbean Sea','Yes','No'),
	array('Gulf of Venezuela','Southwest Caribbean Sea','Yes','No'),
	array('Gulf of Venezuela','Terra Firma','Yes','No'),
	array('Gulf of Venezuela','Tobago','Yes','No'),
	array('Gulf of Venezuela','Trinadad','Yes','No'),
	array('Gulf of Venezuela','Waters of the Spanish Main','Yes','Yes'),
	array('Gulf Stream','Martinique','Yes','No'),
	array('Gulf Stream','Mermaid Peaks','Yes','Yes'),
	array('Gulf Stream','Mid Atlantic','Yes','Yes'),
	array('Gulf Stream','St Eustatius','Yes','No'),
	array('Gulf Stream','St Lucia','Yes','No'),
	array('Gulf Stream','St Martin','Yes','No'),
	array('Gulf Stream','Tobago','Yes','No'),
	array('Gulf Stream','Virgin Islands','Yes','No'),
	array('Havana','Isla de los Pinos','Yes','Yes'),
	array('Havana','Nassau','Yes','No'),
	array('Havana','Northern Gulf of Mexico','Yes','No'),
	array('Havana','Northwest Caribbean Sea','Yes','No'),
	array('Havana','Northwest Channel','Yes','No'),
	array('Havana','Old Bahama Strait','Yes','No'),
	array('Havana','Old Spanish Armory','Yes','No'),
	array('Havana','Tongue of the Ocean','Yes','No'),
	array('Havana','Voodoo Witch Hut','Yes','Yes'),
	array('Havana','West Cuba','Yes','Yes'),
	array('Havana','Western Gulf of Mexico','Yes','No'),
	array('Havana','Yuchatan Channel','Yes','Yes'),
	array('Havana','Yuchatan','Yes','No'),
	array('Hispaniola','Jamaica Channel','Yes','No'),
	array('Hispaniola','La Vega','Yes','No'),
	array('Hispaniola','Mona Passage','Yes','No'),
	array('Hispaniola','North Caribbean Sea','Yes','Yes'),
	array('Hispaniola','Northeast Caribbean Sea','Yes','No'),
	array('Hispaniola','Northwest Caribbean Sea','Yes','No'),
	array('Hispaniola','Petit Goave','Yes','Yes'),
	array('Hispaniola','St Domingue','Yes','Yes'),
	array('Hispaniola','Treasure Island','Yes','Yes'),
	array('Hispaniola','Windward Passage','Yes','No'),
	array('Hispaniola','Yaguano','Yes','No'),
	array('Honduras','Mayan Gold','Yes','No'),
	array('Honduras','Mosquito Coast','Yes','Yes'),
	array('Honduras','Northwest Caribbean Sea','Yes','No'),
	array('Honduras','Providence','Yes','No'),
	array('Honduras','Yuchatan Channel','Yes','No'),
	array('Honduras','Yuchatan','Yes','No'),
	array('Isla Blanquilla','Keelhaul Key','Yes','No'),
	array('Isla Blanquilla','Margarita','Yes','Yes'),
	array('Isla Blanquilla','Martinique','Yes','No'),
	array('Isla Blanquilla','Montserrat','Yes','No'),
	array('Isla Blanquilla','New Andalucia','Yes','No'),
	array('Isla Blanquilla','Northeast Caribbean Sea','Yes','No'),
	array('Isla Blanquilla','Orinico','Yes','No'),
	array('Isla Blanquilla','Puerto Cabello','Yes','No'),
	array('Isla Blanquilla','Skeleton Bluff','Yes','Yes'),
	array('Isla Blanquilla','South Caribbean Sea','Yes','No'),
	array('Isla Blanquilla','Southeast Caribbean Sea','Yes','Yes'),
	array('Isla Blanquilla','St Lucia','Yes','No'),
	array('Isla Blanquilla','Terra Firma','Yes','No'),
	array('Isla Blanquilla','Tobago','Yes','Yes'),
	array('Isla Blanquilla','Trinadad','Yes','Yes'),
	array('Isla Blanquilla','Waters of the Spanish Main','Yes','Yes'),
	array('Isla de los Pinos','Jamaica Channel','Yes','No'),
	array('Isla de los Pinos','Jamaica','Yes','No'),
	array('Isla de los Pinos','Northwest Caribbean Sea','Yes','No'),
	array('Isla de los Pinos','Old Spanish Armory','Yes','Yes'),
	array('Isla de los Pinos','Santiago','Yes','No'),
	array('Isla de los Pinos','Spanish Town','Yes','No'),
	array('Isla de los Pinos','Voodoo Witch Hut','Yes','No'),
	array('Isla de los Pinos','West Cuba','Yes','Yes'),
	array('Isla de los Pinos','Western Gulf of Mexico','Yes','No'),
	array('Isla de los Pinos','Yuchatan Channel','Yes','Yes'),
	array('Isla de los Pinos','Yuchatan','Yes','No'),
	array('Jamaica Channel','Jamaica','Yes','Yes'),
	array('Jamaica Channel','Mayaguana Passage','Yes','No'),
	array('Jamaica Channel','Mona Passage','Yes','No'),
	array('Jamaica Channel','Mosquito Coast','Yes','No'),
	array('Jamaica Channel','North Caribbean Sea','Yes','Yes'),
	array('Jamaica Channel','North Riff','Yes','No'),
	array('Jamaica Channel','Northeast Caribbean Sea','Yes','No'),
	array('Jamaica Channel','Northwest Caribbean Sea','Yes','Yes'),
	array('Jamaica Channel','Old Spanish Armory','Yes','No'),
	array('Jamaica Channel','Petit Goave','Yes','Yes'),
	array('Jamaica Channel','Port Royal','Yes','Yes'),
	array('Jamaica Channel','Port-de-Paix','Yes','No'),
	array('Jamaica Channel','Providence','Yes','No'),
	array('Jamaica Channel','Santiago','Yes','Yes'),
	array('Jamaica Channel','Southwest Caribbean Sea','Yes','No'),
	array('Jamaica Channel','Spanish Town','Yes','No'),
	array('Jamaica Channel','St Domingue','Yes','No'),
	array('Jamaica Channel','Tortuga','Yes','No'),
	array('Jamaica Channel','Treasure Island','Yes','No'),
	array('Jamaica Channel','Voodoo Witch Hut','Yes','No'),
	array('Jamaica Channel','Windward Passage','Yes','Yes'),
	array('Jamaica Channel','Yaguano','Yes','No'),
	array('Jamaica Channel','Yuchatan Channel','Yes','No'),
	array('Jamaica','North Caribbean Sea','Yes','No'),
	array('Jamaica','Northwest Caribbean Sea','Yes','No'),
	array('Jamaica','Old Spanish Armory','Yes','No'),
	array('Jamaica','Petit Goave','Yes','No'),
	array('Jamaica','Port Royal','Yes','Yes'),
	array('Jamaica','Santiago','Yes','No'),
	array('Jamaica','Spanish Town','Yes','Yes'),
	array('Jamaica','Voodoo Witch Hut','Yes','No'),
	array('Jamaica','Windward Passage','Yes','No'),
	array('Jamaica','Yuchatan Channel','Yes','No'),
	array('Keelhaul Key','Margarita','Yes','No'),
	array('Keelhaul Key','Martinique','Yes','Yes'),
	array('Keelhaul Key','Mermaid Peaks','Yes','No'),
	array('Keelhaul Key','Montserrat','Yes','Yes'),
	array('Keelhaul Key','Northeast Caribbean Sea','Yes','No'),
	array('Keelhaul Key','Skeleton Bluff','Yes','Yes'),
	array('Keelhaul Key','South Caribbean Sea','Yes','No'),
	array('Keelhaul Key','Southeast Caribbean Sea','Yes','Yes'),
	array('Keelhaul Key','St Kitts','Yes','No'),
	array('Keelhaul Key','St Lucia','Yes','No'),
	array('Keelhaul Key','Waters of the Spanish Main','Yes','No'),
	array('La Vega','Mona Passage','Yes','Yes'),
	array('La Vega','North Caribbean Sea','Yes','No'),
	array('La Vega','North Riff','Yes','Yes'),
	array('La Vega','Northeast Caribbean Sea','Yes','No'),
	array('La Vega','Port-de-Paix','Yes','Yes'),
	array('La Vega','San Juan','Yes','No'),
	array('La Vega','St Domingue','Yes','Yes'),
	array('La Vega','Tortuga','Yes','No'),
	array('La Vega','Windward Passage','Yes','No'),
	array('La Vega','Yaguano','Yes','No'),
	array('Louisiana','Northern Gulf of Mexico','Yes','Yes'),
	array('Louisiana','Northwest Channel','Yes','No'),
	array('Louisiana','Santo Poco','Yes','No'),
	array('Louisiana','Singing Bush','Yes','Yes'),
	array('Louisiana','St Augustine','Yes','No'),
	array('Louisiana','Western Gulf of Mexico','Yes','No'),
	array('Maracaibo Lagoon','Maracaibo','Yes','Yes'),
	array('Maracaibo Lagoon','Rio de la Hacha','Yes','No'),
	array('Maracaibo Lagoon','South Caribbean Sea','Yes','No'),
	array('Maracaibo Lagoon','Terra Firma','Yes','No'),
	array('Maracaibo Lagoon','Waters of the Spanish Main','Yes','No'),
	array('Maracaibo','Rio de la Hacha','Yes','Yes'),
	array('Maracaibo','Santa Maria','Yes','No'),
	array('Maracaibo','South Caribbean Sea','Yes','No'),
	array('Maracaibo','Waters of the Spanish Main','Yes','No'),
	array('Margarita','Montserrat','Yes','No'),
	array('Margarita','New Andalucia','Yes','No'),
	array('Margarita','Northeast Caribbean Sea','Yes','No'),
	array('Margarita','Puerto Cabello','Yes','No'),
	array('Margarita','Skeleton Bluff','Yes','No'),
	array('Margarita','South Caribbean Sea','Yes','No'),
	array('Margarita','Southeast Caribbean Sea','Yes','Yes'),
	array('Margarita','Terra Firma','Yes','No'),
	array('Margarita','Tobago','Yes','No'),
	array('Margarita','Trinadad','Yes','No'),
	array('Margarita','Waters of the Spanish Main','Yes','Yes'),
	array('Martinique','Mermaid Peaks','Yes','No'),
	array('Martinique','Montserrat','Yes','No'),
	array('Martinique','Skeleton Bluff','Yes','Yes'),
	array('Martinique','Southeast Caribbean Sea','Yes','No'),
	array('Martinique','St Kitts','Yes','No'),
	array('Martinique','St Lucia','Yes','Yes'),
	array('Martinique','Tobago','Yes','No'),
	array('Mayaguana Passage','Mid Atlantic','Yes','No'),
	array('Mayaguana Passage','Mona Passage','Yes','No'),
	array('Mayaguana Passage','North Riff','Yes','No'),
	array('Mayaguana Passage','Old Bahama Strait','Yes','No'),
	array('Mayaguana Passage','Petit Goave','Yes','No'),
	array('Mayaguana Passage','Port-de-Paix','Yes','No'),
	array('Mayaguana Passage','Rum Distillery','Yes','Yes'),
	array('Mayaguana Passage','San Juan','Yes','No'),
	array('Mayaguana Passage','Santiago','Yes','No'),
	array('Mayaguana Passage','Tongue of the Ocean','Yes','No'),
	array('Mayaguana Passage','Tortuga','Yes','Yes'),
	array('Mayaguana Passage','Virgin Islands','Yes','No'),
	array('Mayaguana Passage','West Atlantic','Yes','No'),
	array('Mayaguana Passage','Windward Passage','Yes','Yes'),
	array('Mayaguana Passage','Yaguano','Yes','No'),
	array('Mayan Gold','Mosquito Coast','Yes','No'),
	array('Mayan Gold','Northwest Caribbean Sea','Yes','No'),
	array('Mayan Gold','Yuchatan Channel','Yes','No'),
	array('Mayan Gold','Yuchatan','Yes','Yes'),
	array('Mermaid Peaks','Mid Atlantic','Yes','Yes'),
	array('Mermaid Peaks','Montserrat','Yes','No'),
	array('Mermaid Peaks','St Eustatius','Yes','Yes'),
	array('Mermaid Peaks','St Kitts','Yes','No'),
	array('Mermaid Peaks','St Martin','Yes','No'),
	array('Mermaid Peaks','Virgin Islands','Yes','No'),
	array('Mid Atlantic','Mona Passage','Yes','No'),
	array('Mid Atlantic','North Riff','Yes','No'),
	array('Mid Atlantic','Northeast Caribbean Sea','Yes','No'),
	array('Mid Atlantic','Rum Distillery','Yes','No'),
	array('Mid Atlantic','San Juan','Yes','No'),
	array('Mid Atlantic','St Eustatius','Yes','Yes'),
	array('Mid Atlantic','St Kitts','Yes','No'),
	array('Mid Atlantic','St Martin','Yes','Yes'),
	array('Mid Atlantic','Virgin Islands','Yes','Yes'),
	array('Mid Atlantic','West Atlantic','Yes','No'),
	array('Mona Passage','Montserrat','Yes','No'),
	array('Mona Passage','North Caribbean Sea','Yes','Yes'),
	array('Mona Passage','North Riff','Yes','Yes'),
	array('Mona Passage','Northeast Caribbean Sea','Yes','Yes'),
	array('Mona Passage','Northwest Caribbean Sea','Yes','No'),
	array('Mona Passage','Petit Goave','Yes','No'),
	array('Mona Passage','Port-de-Paix','Yes','No'),
	array('Mona Passage','Rum Distillery','Yes','No'),
	array('Mona Passage','San Juan','Yes','Yes'),
	array('Mona Passage','Southeast Caribbean Sea','Yes','No'),
	array('Mona Passage','St Domingue','Yes','Yes'),
	array('Mona Passage','St Kitts','Yes','No'),
	array('Mona Passage','Tortuga','Yes','No'),
	array('Mona Passage','Treasure Island','Yes','No'),
	array('Mona Passage','Virgin Islands','Yes','No'),
	array('Mona Passage','West Atlantic','Yes','No'),
	array('Mona Passage','Windward Passage','Yes','No'),
	array('Montserrat','North Caribbean Sea','Yes','No'),
	array('Montserrat','Northeast Caribbean Sea','Yes','Yes'),
	array('Montserrat','San Juan','Yes','No'),
	array('Montserrat','Skeleton Bluff','Yes','No'),
	array('Montserrat','South Caribbean Sea','Yes','No'),
	array('Montserrat','Southeast Caribbean Sea','Yes','Yes'),
	array('Montserrat','St Eustatius','Yes','No'),
	array('Montserrat','St Kitts','Yes','Yes'),
	array('Montserrat','Virgin Islands','Yes','No'),
	array('Montserrat','Waters of the Spanish Main','Yes','No'),
	array('Mosquito Coast','North Caribbean Sea','Yes','No'),
	array('Mosquito Coast','Northwest Caribbean Sea','Yes','Yes'),
	array('Mosquito Coast','Pirate Coast','Yes','No'),
	array('Mosquito Coast','Port Royal','Yes','No'),
	array('Mosquito Coast','Providence','Yes','Yes'),
	array('Mosquito Coast','Shipwreck Bay','Yes','No'),
	array('Mosquito Coast','Southwest Caribbean Sea','Yes','No'),
	array('Mosquito Coast','Spanish Town','Yes','No'),
	array('Mosquito Coast','Yuchatan Channel','Yes','No'),
	array('Mosquito Coast','Yuchatan','Yes','No'),
	array('Nassau','Northwest Channel','Yes','Yes'),
	array('Nassau','Old Bahama Strait','Yes','No'),
	array('Nassau','Tongue of the Ocean','Yes','Yes'),
	array('Nassau','Voodoo Witch Hut','Yes','No'),
	array('Nassau','West Atlantic','Yes','No'),
	array('New Andalucia','Orinico','Yes','Yes'),
	array('New Andalucia','Puerto Cabello','Yes','Yes'),
	array('New Andalucia','South Caribbean Sea','Yes','No'),
	array('New Andalucia','Southeast Caribbean Sea','Yes','No'),
	array('New Andalucia','Terra Firma','Yes','No'),
	array('New Andalucia','Tobago','Yes','Yes'),
	array('New Andalucia','Trinadad','Yes','Yes'),
	array('New Andalucia','Waters of the Spanish Main','Yes','Yes'),
	array('Nombre de Dior','Panama','Yes','Yes'),
	array('Nombre de Dior','Puerto Bello','Yes','No'),
	array('Nombre de Dior','Shipwreck Bay','Yes','No'),
	array('Nombre de Dior','Southwest Caribbean Sea','Yes','No'),
	array('Nombre de Dior','Western Gulf of Darien','Yes','Yes'),
	array('Nombre de Dior','Western New Grenada','Yes','No'),
	array('North Caribbean Sea','North Riff','Yes','No'),
	array('North Caribbean Sea','Northeast Caribbean Sea','Yes','Yes'),
	array('North Caribbean Sea','Northwest Caribbean Sea','Yes','Yes'),
	array('North Caribbean Sea','Petit Goave','Yes','Yes'),
	array('North Caribbean Sea','Port Royal','Yes','No'),
	array('North Caribbean Sea','Providence','Yes','No'),
	array('North Caribbean Sea','San Juan','Yes','No'),
	array('North Caribbean Sea','Santiago','Yes','No'),
	array('North Caribbean Sea','South Caribbean Sea','Yes','No'),
	array('North Caribbean Sea','Southeast Caribbean Sea','Yes','No'),
	array('North Caribbean Sea','Southwest Caribbean Sea','Yes','No'),
	array('North Caribbean Sea','Spanish Town','Yes','No'),
	array('North Caribbean Sea','St Domingue','Yes','Yes'),
	array('North Caribbean Sea','St Kitts','Yes','No'),
	array('North Caribbean Sea','Treasure Island','Yes','Yes'),
	array('North Caribbean Sea','Virgin Islands','Yes','No'),
	array('North Caribbean Sea','Windward Passage','Yes','No'),
	array('North Caribbean Sea','Yaguano','Yes','No'),
	array('North Caribbean Sea','Yuchatan Channel','Yes','No'),
	array('North Riff','Northeast Caribbean Sea','Yes','No'),
	array('North Riff','Petit Goave','Yes','No'),
	array('North Riff','Port-de-Paix','Yes','Yes'),
	array('North Riff','Rum Distillery','Yes','No'),
	array('North Riff','San Juan','Yes','No'),
	array('North Riff','Santiago','Yes','No'),
	array('North Riff','St Domingue','Yes','No'),
	array('North Riff','Tortuga','Yes','Yes'),
	array('North Riff','Virgin Islands','Yes','No'),
	array('North Riff','West Atlantic','Yes','No'),
	array('North Riff','Windward Passage','Yes','Yes'),
	array('North Riff','Yaguano','Yes','No'),
	array('Northeast Caribbean Sea','Northwest Caribbean Sea','Yes','No'),
	array('Northeast Caribbean Sea','Petit Goave','Yes','No'),
	array('Northeast Caribbean Sea','San Juan','Yes','Yes'),
	array('Northeast Caribbean Sea','Skeleton Bluff','Yes','No'),
	array('Northeast Caribbean Sea','South Caribbean Sea','Yes','No'),
	array('Northeast Caribbean Sea','Southeast Caribbean Sea','Yes','Yes'),
	array('Northeast Caribbean Sea','Southwest Caribbean Sea','Yes','No'),
	array('Northeast Caribbean Sea','St Domingue','Yes','No'),
	array('Northeast Caribbean Sea','St Eustatius','Yes','No'),
	array('Northeast Caribbean Sea','St Kitts','Yes','Yes'),
	array('Northeast Caribbean Sea','St Martin','Yes','No'),
	array('Northeast Caribbean Sea','Treasure Island','Yes','No'),
	array('Northeast Caribbean Sea','Virgin Islands','Yes','Yes'),
	array('Northeast Caribbean Sea','Waters of the Spanish Main','Yes','No'),
	array('Northern Gulf of Mexico','Northwest Channel','Yes','No'),
	array('Northern Gulf of Mexico','Santo Poco','Yes','No'),
	array('Northern Gulf of Mexico','Singing Bush','Yes','Yes'),
	array('Northern Gulf of Mexico','St Augustine','Yes','No'),
	array('Northern Gulf of Mexico','Western Bay of Campeche','Yes','No'),
	array('Northern Gulf of Mexico','Western Gulf of Mexico','Yes','Yes'),
	array('Northern Gulf of Mexico','Yuchatan Channel','Yes','No'),
	array('Northwest Caribbean Sea','Old Spanish Armory','Yes','No'),
	array('Northwest Caribbean Sea','Panama','Yes','No'),
	array('Northwest Caribbean Sea','Petit Goave','Yes','No'),
	array('Northwest Caribbean Sea','Pirate Coast','Yes','No'),
	array('Northwest Caribbean Sea','Port Royal','Yes','Yes'),
	array('Northwest Caribbean Sea','Providence','Yes','Yes'),
	array('Northwest Caribbean Sea','Santiago','Yes','No'),
	array('Northwest Caribbean Sea','Shipwreck Bay','Yes','No'),
	array('Northwest Caribbean Sea','South Caribbean Sea','Yes','No'),
	array('Northwest Caribbean Sea','Southeast Caribbean Sea','Yes','No'),
	array('Northwest Caribbean Sea','Southwest Caribbean Sea','Yes','Yes'),
	array('Northwest Caribbean Sea','Spanish Town','Yes','Yes'),
	array('Northwest Caribbean Sea','St Domingue','Yes','No'),
	array('Northwest Caribbean Sea','Treasure Island','Yes','No'),
	array('Northwest Caribbean Sea','Voodoo Witch Hut','Yes','No'),
	array('Northwest Caribbean Sea','Western Gulf of Darien','Yes','No'),
	array('Northwest Caribbean Sea','Western Gulf of Mexico','Yes','No'),
	array('Northwest Caribbean Sea','Windward Passage','Yes','No'),
	array('Northwest Caribbean Sea','Yuchatan Channel','Yes','Yes'),
	array('Northwest Caribbean Sea','Yuchatan','Yes','No'),
	array('Northwest Channel','Old Bahama Strait','Yes','No'),
	array('Northwest Channel','St Augustine','Yes','No'),
	array('Northwest Channel','Tongue of the Ocean','Yes','No'),
	array('Northwest Channel','Voodoo Witch Hut','Yes','No'),
	array('Northwest Channel','West Atlantic','Yes','No'),
	array('Old Bahama Strait','Santiago','Yes','No'),
	array('Old Bahama Strait','Tongue of the Ocean','Yes','Yes'),
	array('Old Bahama Strait','Voodoo Witch Hut','Yes','Yes'),
	array('Old Bahama Strait','Windward Passage','Yes','No'),
	array('Old Spanish Armory','Santiago','Yes','No'),
	array('Old Spanish Armory','Spanish Town','Yes','No'),
	array('Old Spanish Armory','Voodoo Witch Hut','Yes','Yes'),
	array('Old Spanish Armory','West Cuba','Yes','Yes'),
	array('Old Spanish Armory','Yuchatan Channel','Yes','No'),
	array('Orinico','Tobago','Yes','Yes'),
	array('Orinico','Trinadad','Yes','No'),
	array('Orinico','Waters of the Spanish Main','Yes','No'),
	array('Panama','Pirate Coast','Yes','No'),
	array('Panama','Providence','Yes','No'),
	array('Panama','Puerto Bello','Yes','Yes'),
	array('Panama','Shipwreck Bay','Yes','Yes'),
	array('Panama','South Caribbean Sea','Yes','No'),
	array('Panama','Southwest Caribbean Sea','Yes','Yes'),
	array('Panama','Western Gulf of Darien','Yes','Yes'),
	array('Petit Goave','Port Royal','Yes','No'),
	array('Petit Goave','Port-de-Paix','Yes','No'),
	array('Petit Goave','Santiago','Yes','No'),
	array('Petit Goave','St Domingue','Yes','No'),
	array('Petit Goave','Tortuga','Yes','No'),
	array('Petit Goave','Treasure Island','Yes','Yes'),
	array('Petit Goave','Windward Passage','Yes','Yes'),
	array('Petit Goave','Yaguano','Yes','Yes'),
	array('Pirate Coast','Providence','Yes','Yes'),
	array('Pirate Coast','Puerto Bello','Yes','Yes'),
	array('Pirate Coast','Shipwreck Bay','Yes','Yes'),
	array('Pirate Coast','Southwest Caribbean Sea','Yes','No'),
	array('Port Royal','Providence','Yes','No'),
	array('Port Royal','Santiago','Yes','No'),
	array('Port Royal','Southwest Caribbean Sea','Yes','No'),
	array('Port Royal','Spanish Town','Yes','Yes'),
	array('Port Royal','Windward Passage','Yes','No'),
	array('Port Royal','Yuchatan Channel','Yes','No'),
	array('Port-de-Paix','Santiago','Yes','No'),
	array('Port-de-Paix','St Domingue','Yes','No'),
	array('Port-de-Paix','Tortuga','Yes','Yes'),
	array('Port-de-Paix','Windward Passage','Yes','Yes'),
	array('Port-de-Paix','Yaguano','Yes','Yes'),
	array('Providence','Puerto Bello','Yes','No'),
	array('Providence','Shipwreck Bay','Yes','Yes'),
	array('Providence','South Caribbean Sea','Yes','No'),
	array('Providence','Southwest Caribbean Sea','Yes','Yes'),
	array('Providence','Spanish Town','Yes','No'),
	array('Providence','Western Gulf of Darien','Yes','No'),
	array('Providence','Yuchatan Channel','Yes','No'),
	array('Puerto Bello','Shipwreck Bay','Yes','Yes'),
	array('Puerto Bello','Southwest Caribbean Sea','Yes','No'),
	array('Puerto Bello','Western Gulf of Darien','Yes','No'),
	array('Puerto Cabello','South Caribbean Sea','Yes','No'),
	array('Puerto Cabello','Southeast Caribbean Sea','Yes','No'),
	array('Puerto Cabello','Terra Firma','Yes','Yes'),
	array('Puerto Cabello','Tobago','Yes','No'),
	array('Puerto Cabello','Trinadad','Yes','No'),
	array('Puerto Cabello','Waters of the Spanish Main','Yes','Yes'),
	array('Rio de la Hacha','Santa Maria','Yes','Yes'),
	array('Rio de la Hacha','South Caribbean Sea','Yes','Yes'),
	array('Rio de la Hacha','Southeast Caribbean Sea','Yes','No'),
	array('Rio de la Hacha','Southwest Caribbean Sea','Yes','No'),
	array('Rio de la Hacha','Waters of the Spanish Main','Yes','No'),
	array('Rum Distillery','San Juan','Yes','No'),
	array('Rum Distillery','Tortuga','Yes','No'),
	array('Rum Distillery','Virgin Islands','Yes','No'),
	array('Rum Distillery','West Atlantic','Yes','No'),
	array('Rum Distillery','Windward Passage','Yes','No'),
	array('San Juan','Southeast Caribbean Sea','Yes','No'),
	array('San Juan','St Domingue','Yes','No'),
	array('San Juan','St Eustatius','Yes','No'),
	array('San Juan','St Kitts','Yes','No'),
	array('San Juan','St Martin','Yes','No'),
	array('San Juan','Virgin Islands','Yes','Yes'),
	array('San Juan','West Atlantic','Yes','No'),
	array('Santa Maria','South Caribbean Sea','Yes','Yes'),
	array('Santa Maria','Southeast Caribbean Sea','Yes','No'),
	array('Santa Maria','Southwest Caribbean Sea','Yes','No'),
	array('Santa Maria','Waters of the Spanish Main','Yes','No'),
	array('Santa Maria','Western Gulf of Darien','Yes','No'),
	array('Santa Maria','Western New Grenada','Yes','No'),
	array('Santiago','Spanish Town','Yes','No'),
	array('Santiago','Tongue of the Ocean','Yes','No'),
	array('Santiago','Tortuga','Yes','No'),
	array('Santiago','Voodoo Witch Hut','Yes','Yes'),
	array('Santiago','West Cuba','Yes','No'),
	array('Santiago','Windward Passage','Yes','Yes'),
	array('Santiago','Yaguano','Yes','No'),
	array('Santiago','Yuchatan Channel','Yes','No'),
	array('Santo Poco','Singing Bush','Yes','Yes'),
	array('Santo Poco','Veracruz','Yes','No'),
	array('Santo Poco','Western Bay of Campeche','Yes','Yes'),
	array('Santo Poco','Western Gulf of Mexico','Yes','Yes'),
	array('Santo Poco','Yuchatan Channel','Yes','No'),
	array('Shipwreck Bay','South Caribbean Sea','Yes','No'),
	array('Shipwreck Bay','Southwest Caribbean Sea','Yes','Yes'),
	array('Shipwreck Bay','Western Gulf of Darien','Yes','No'),
	array('Singing Bush','Western Bay of Campeche','Yes','No'),
	array('Singing Bush','Western Gulf of Mexico','Yes','Yes'),
	array('Singing Bush','Yuchatan Channel','Yes','No'),
	array('Skeleton Bluff','South Caribbean Sea','Yes','No'),
	array('Skeleton Bluff','Southeast Caribbean Sea','Yes','Yes'),
	array('Skeleton Bluff','St Lucia','Yes','Yes'),
	array('Skeleton Bluff','Tobago','Yes','No'),
	array('Skeleton Bluff','Trinadad','Yes','No'),
	array('Skeleton Bluff','Waters of the Spanish Main','Yes','No'),
	array('South Caribbean Sea','Southeast Caribbean Sea','Yes','Yes'),
	array('South Caribbean Sea','Southwest Caribbean Sea','Yes','Yes'),
	array('South Caribbean Sea','Terra Firma','Yes','No'),
	array('South Caribbean Sea','Tobago','Yes','No'),
	array('South Caribbean Sea','Trinadad','Yes','No'),
	array('South Caribbean Sea','Waters of the Spanish Main','Yes','Yes'),
	array('South Caribbean Sea','Western Gulf of Darien','Yes','No'),
	array('South Caribbean Sea','Western New Grenada','Yes','No'),
	array('Southeast Caribbean Sea','Southwest Caribbean Sea','Yes','No'),
	array('Southeast Caribbean Sea','St Kitts','Yes','No'),
	array('Southeast Caribbean Sea','St Lucia','Yes','No'),
	array('Southeast Caribbean Sea','Terra Firma','Yes','No'),
	array('Southeast Caribbean Sea','Tobago','Yes','No'),
	array('Southeast Caribbean Sea','Trinadad','Yes','No'),
	array('Southeast Caribbean Sea','Virgin Islands','Yes','No'),
	array('Southeast Caribbean Sea','Waters of the Spanish Main','Yes','Yes'),
	array('Southwest Caribbean Sea','Spanish Town','Yes','No'),
	array('Southwest Caribbean Sea','Waters of the Spanish Main','Yes','No'),
	array('Southwest Caribbean Sea','Western Gulf of Darien','Yes','Yes'),
	array('Southwest Caribbean Sea','Yuchatan Channel','Yes','No'),
	array('Spanish Town','Voodoo Witch Hut','Yes','No'),
	array('Spanish Town','Yuchatan Channel','Yes','No'),
	array('St Augustine','West Atlantic','Yes','No'),
	array('St Domingue','Treasure Island','Yes','No'),
	array('St Eustatius','St Kitts','Yes','Yes'),
	array('St Eustatius','St Martin','Yes','Yes'),
	array('St Eustatius','Virgin Islands','Yes','Yes'),
	array('St Kitts','St Martin','Yes','No'),
	array('St Kitts','Virgin Islands','Yes','Yes'),
	array('St Lucia','Tobago','Yes','No'),
	array('St Martin','Virgin Islands','Yes','Yes'),
	array('Terra Firma','Tobago','Yes','No'),
	array('Terra Firma','Trinadad','Yes','No'),
	array('Terra Firma','Waters of the Spanish Main','Yes','Yes'),
	array('Tobago','Trinadad','Yes','Yes'),
	array('Tobago','Waters of the Spanish Main','Yes','Yes'),
	array('Tongue of the Ocean','Voodoo Witch Hut','Yes','No'),
	array('Tongue of the Ocean','Windward Passage','Yes','No'),
	array('Tortuga','Windward Passage','Yes','Yes'),
	array('Tortuga','Yaguano','Yes','No'),
	array('Treasure Island','Windward Passage','Yes','No'),
	array('Treasure Island','Yaguano','Yes','No'),
	array('Trinadad','Waters of the Spanish Main','Yes','Yes'),
	array('Veracruz','Western Bay of Campeche','Yes','Yes'),
	array('Veracruz','Western Gulf of Mexico','Yes','No'),
	array('Veracruz','Yuchatan Channel','Yes','No'),
	array('Veracruz','Yuchatan','Yes','No'),
	array('Virgin Islands','West Atlantic','Yes','No'),
	array('Voodoo Witch Hut','West Cuba','Yes','Yes'),
	array('Voodoo Witch Hut','Windward Passage','Yes','No'),
	array('Voodoo Witch Hut','Yuchatan Channel','Yes','No'),
	array('West Cuba','Yuchatan Channel','Yes','No'),
	array('Western Bay of Campeche','Western Gulf of Mexico','Yes','Yes'),
	array('Western Bay of Campeche','Yuchatan Channel','Yes','No'),
	array('Western Bay of Campeche','Yuchatan','Yes','No'),
	array('Western Gulf of Darien','Western New Grenada','Yes','No'),
	array('Western Gulf of Mexico','Yuchatan Channel','Yes','Yes'),
	array('Western Gulf of Mexico','Yuchatan','Yes','No'),
	array('Windward Passage','Yaguano','Yes','Yes'),
	array('Yuchatan Channel','Yuchatan','Yes','Yes')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

// Custom footer not changed by edit tool

// Make a "fake" SC for every pirate to fool the Unit-DestroyIndex generation (they have no home SC)
InstallTerritory::$Territories['Mid Atlantic']->supply='Yes';           // Isaac Rochussen
InstallTerritory::$Territories['Western Gulf of Mexico']->supply='Yes'; // The Infamous El Guapo
InstallTerritory::$Territories['Mayaguana Passage']->supply='Yes';      // Daniel "The Terror" Johnson
InstallTerritory::$Territories['Virgin Islands']->supply='Yes';         // Daniel "The Exterminator" Montbars
InstallTerritory::$Territories['Skeleton Bluff']->supply='Yes';         // Bartolomeu "The Portuguese" de la Cueva
InstallTerritory::$Territories['Southwest Caribbean Sea']->supply='Yes';// Roche "The Rock" Braziliano

InstallTerritory::runSQL($this->mapID);

// Remove the fake Home-Supply-Centers created above
$DB->sql_put('UPDATE wD_Territories SET supply="No" WHERE mapID='.$this->mapID.' AND supply="Yes" AND countryID > 7;');

// install Javascript-cache
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);

?>



