<?php
// This is file installs the map data for the Fubar variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Big Wide Ocean', 'Sea', 'No', 158, 28, 88, 22, 'Neutral'),
	array('North-East quadrant', 'Coast', 'Yes', 161, 105, 103, 74, 'Neutral'),
	array('North-West quadrant', 'Coast', 'No', 110, 105, 64, 73, 'Neutral'),
	array('Owl', 'Coast', 'Yes', 521, 159, 311, 96, 'Neutral'),
	array('South-West quadrant', 'Coast', 'Yes', 130, 236, 75, 137, 'Neutral'),
	array('South-East quadrant', 'Coast', 'No', 156, 210, 96, 113, 'Neutral'),
	array('Sickness Reef', 'Sea', 'No', 276, 177, 178, 85, 'Neutral'),
	array('Health Passage', 'Sea', 'No', 215, 260, 131, 151, 'Neutral'),
	array('Boring Island Sea', 'Sea', 'No', 56, 381, 37, 218, 'Neutral'),
	array('Ocean of Despair', 'Sea', 'No', 898, 34, 536, 15, 'Neutral'),
	array('More Rectangular', 'Sea', 'No', 525, 118, 312, 67, 'Neutral'),
	array('Gulf of Confusion', 'Sea', 'No', 794, 191, 476, 105, 'Neutral'),
	array('Haha Sea', 'Sea', 'No', 967, 472, 580, 288, 'Neutral'),
	array('Laughter Lagune', 'Sea', 'No', 854, 271, 511, 157, 'Neutral'),
	array('WTF', 'Coast', 'Yes', 854, 72, 511, 46, 'Neutral'),
	array('LMAO', 'Coast', 'No', 938, 173, 563, 105, 'Neutral'),
	array('LOL', 'Coast', 'No', 887, 164, 543, 134, 'Neutral'),
	array('ROFL', 'Coast', 'Yes', 947, 363, 568, 220, 'Neutral'),
	array('Guffaw Coast', 'Sea', 'No', 887, 505, 527, 303, 'Neutral'),
	array('Sea of Rights', 'Sea', 'No', 962, 661, 578, 373, 'Neutral'),
	array('Sea of Wrongs', 'Sea', 'No', 650, 929, 338, 571, 'Neutral'),
	array('Dissapointing Straits', 'Sea', 'No', 868, 657, 521, 393, 'Neutral'),
	array('Abandonment Alley', 'Sea', 'No', 746, 815, 446, 485, 'Neutral'),
	array('Right', 'Coast', 'No', 922, 901, 555, 538, 'Neutral'),
	array('Left', 'Coast', 'No', 791, 871, 476, 521, 'Neutral'),
	array('Inland', 'Land', 'Yes', 878, 892, 523, 535, 'Neutral'),
	array('Glorious Gateway', 'Sea', 'No', 478, 816, 287, 486, 'Neutral'),
	array('The Pool', 'Sea', 'No', 407, 946, 251, 572, 'Neutral'),
	array('Footprint Sea', 'Sea', 'No', 50, 520, 26, 475, 'Neutral'),
	array('Enlightenment Bay', 'Sea', 'No', 257, 779, 156, 468, 'Neutral'),
	array('Epiphany Straits', 'Sea', 'No', 174, 659, 107, 381, 'Neutral'),
	array('Sort of Square', 'Sea', 'No', 187, 436, 97, 271, 'Neutral'),
	array('Heel', 'Coast', 'Yes', 102, 670, 64, 410, 'Neutral'),
	array('Lateral', 'Coast', 'No', 165, 787, 97, 468, 'Neutral'),
	array('Medial', 'Coast', 'No', 115, 789, 68, 469, 'Neutral'),
	array('Hallux', 'Coast', 'Yes', 165, 900, 92, 538, 'Neutral'),
	array('Toes', 'Coast', 'No', 212, 916, 139, 543, 'Neutral'),
	array('Arch Deep', 'Sea', 'No', 175, 859, 106, 513, 'Neutral'),
	array('River', 'Sea', 'No', 479, 711, 287, 425, 'Neutral'),
	array('Eeny', 'Sea', 'No', 461, 520, 276, 309, 'Neutral'),
	array('Meeny', 'Sea', 'No', 619, 474, 373, 279, 'Neutral'),
	array('Miny', 'Sea', 'No', 486, 600, 291, 365, 'Neutral'),
	array('Moe', 'Sea', 'No', 681, 551, 406, 335, 'Neutral'),
	array('Pupil', 'Coast', 'Yes', 597, 533, 351, 316, 'Neutral'),
	array('Table', 'Coast', 'No', 451, 163, 271, 98, 'multi_152'),
	array('Meerkat', 'Coast', 'Yes', 334, 201, 214, 115, 'multi_152'),
	array('Spoon', 'Coast', 'No', 278, 279, 168, 172, 'Fatflap'),
	array('Book', 'Coast', 'No', 257, 370, 150, 222, 'Fatflap'),
	array('Televison', 'Coast', 'No', 239, 462, 144, 278, 'Sh1tn00b'),
	array('Pig', 'Coast', 'Yes', 242, 575, 146, 346, 'Sh1tn00b'),
	array('Frog', 'Coast', 'Yes', 294, 686, 177, 404, 'Neutral'),
	array('Trashcan', 'Coast', 'No', 323, 720, 199, 429, 'Fatflap'),
	array('Knife', 'Coast', 'No', 386, 757, 236, 456, 'Fatflap'),
	array('Phone', 'Coast', 'No', 444, 725, 266, 434, 'Fatflap'),
	array('Sink', 'Coast', 'No', 448, 658, 270, 399, 'Fatflap'),
	array('Desk', 'Coast', 'No', 399, 571, 240, 341, 'Fatflap'),
	array('Blanket', 'Coast', 'No', 418, 465, 247, 283, 'Fatflap'),
	array('Chair', 'Coast', 'No', 610, 407, 362, 244, 'Fatflap'),
	array('Squirrel', 'Coast', 'Yes', 699, 441, 423, 256, 'Fatflap'),
	array('Broom', 'Coast', 'No', 735, 477, 439, 285, 'Howdoileavethisgame'),
	array('Sheep', 'Coast', 'Yes', 747, 572, 456, 321, 'Howdoileavethisgame'),
	array('Bottle', 'Coast', 'No', 672, 631, 401, 381, 'Fatflap'),
	array('Shelf', 'Coast', 'No', 541, 651, 310, 400, 'Fatflap'),
	array('Pen', 'Coast', 'No', 510, 704, 306, 424, 'Fatflap'),
	array('Car', 'Coast', 'No', 529, 777, 315, 463, 'timmy1999'),
	array('Kangaroo', 'Coast', 'Yes', 582, 790, 355, 478, 'timmy1999'),
	array('Swallow', 'Coast', 'Yes', 701, 761, 423, 453, 'Neutral'),
	array('Bag', 'Coast', 'No', 774, 697, 465, 421, 'Fatflap'),
	array('Carpet', 'Coast', 'No', 809, 620, 481, 379, 'Fatflap'),
	array('Bat', 'Coast', 'Yes', 823, 483, 487, 311, 'Howdoileavethisgame'),
	array('Fence', 'Coast', 'No', 821, 405, 485, 229, 'Fatflap'),
	array('Vulture', 'Coast', 'Yes', 764, 295, 455, 180, 'Neutral'),
	array('Ostrich', 'Coast', 'Yes', 694, 190, 404, 121, 'oMgYoUrAsLuT'),
	array('Door', 'Coast', 'No', 595, 160, 359, 98, 'oMgYoUrAsLuT'),
	array('Snake', 'Land', 'Yes', 622, 728, 375, 438, 'timmy1999'),
	array('Cow', 'Land', 'Yes', 554, 716, 335, 426, 'Fatflap'),
	array('Couch', 'Land', 'No', 635, 690, 383, 412, 'Fatflap'),
	array('Lion', 'Land', 'Yes', 750, 653, 444, 391, 'Fatflap'),
	array('Fish', 'Land', 'Yes', 773, 618, 461, 371, 'Fatflap'),
	array('Bear', 'Land', 'Yes', 766, 442, 464, 275, 'Neutral'),
	array('Lamp', 'Land', 'No', 668, 262, 400, 160, 'oMgYoUrAsLuT'),
	array('Fork', 'Land', 'No', 639, 327, 381, 197, 'Fatflap'),
	array('Zebra', 'Land', 'Yes', 584, 357, 343, 217, 'Fatflap'),
	array('Lizard', 'Land', 'Yes', 436, 364, 298, 222, 'Fatflap'),
	array('Airconditioner', 'Land', 'No', 533, 310, 326, 187, 'Fatflap'),
	array('Platypus', 'Land', 'Yes', 538, 244, 348, 147, 'oMgYoUrAsLuT'),
	array('Elephant', 'Land', 'Yes', 426, 250, 290, 148, 'multi_152'),
	array('Shark', 'Land', 'Yes', 329, 267, 200, 162, 'Neutral'),
	array('Turtle', 'Land', 'Yes', 332, 334, 199, 212, 'Fatflap'),
	array('Rat', 'Land', 'Yes', 341, 457, 214, 278, 'Fatflap'),
	array('Bike', 'Land', 'No', 313, 476, 177, 268, 'Fatflap'),
	array('Window', 'Land', 'No', 316, 517, 181, 306, 'Fatflap'),
	array('Eagle', 'Land', 'Yes', 297, 574, 179, 340, 'Sh1tn00b'),
	array('Chicken', 'Land', 'Yes', 366, 606, 217, 364, 'Fatflap'),
	array('Monkey', 'Land', 'Yes', 384, 709, 243, 425, 'Fatflap')
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $x, $y, $sx, $sy, $country)=$territoryRawRow;
	if( $country=='Neutral' )
		$countryID=0;
	else
		$countryID=$this->countryID($country);
		
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);
$bordersRawData=array(
	array('Big Wide Ocean','North-East quadrant','Yes','No'),
	array('Big Wide Ocean','North-West quadrant','Yes','No'),
	array('Big Wide Ocean','Sickness Reef','Yes','No'),
	array('Big Wide Ocean','Boring Island Sea','Yes','No'),
	array('Big Wide Ocean','Ocean of Despair','Yes','No'),
	array('Big Wide Ocean','More Rectangular','Yes','No'),
	array('North-East quadrant','Big Wide Ocean','Yes','No'),
	array('North-East quadrant','North-West quadrant','Yes','Yes'),
	array('North-East quadrant','South-West quadrant','No','Yes'),
	array('North-East quadrant','South-East quadrant','Yes','Yes'),
	array('North-East quadrant','Sickness Reef','Yes','No'),
	array('North-West quadrant','Big Wide Ocean','Yes','No'),
	array('North-West quadrant','North-East quadrant','Yes','Yes'),
	array('North-West quadrant','South-West quadrant','Yes','Yes'),
	array('North-West quadrant','South-East quadrant','No','Yes'),
	array('North-West quadrant','Boring Island Sea','Yes','No'),
	array('Owl','More Rectangular','Yes','No'),
	array('Owl','Table','Yes','Yes'),
	array('Owl','Door','Yes','Yes'),
	array('Owl','Platypus','No','Yes'),
	array('Owl','Elephant','No','Yes'),
	array('South-West quadrant','North-East quadrant','No','Yes'),
	array('South-West quadrant','North-West quadrant','Yes','Yes'),
	array('South-West quadrant','South-East quadrant','Yes','Yes'),
	array('South-West quadrant','Health Passage','Yes','No'),
	array('South-West quadrant','Boring Island Sea','Yes','No'),
	array('South-East quadrant','North-East quadrant','Yes','Yes'),
	array('South-East quadrant','North-West quadrant','No','Yes'),
	array('South-East quadrant','South-West quadrant','Yes','Yes'),
	array('South-East quadrant','Sickness Reef','Yes','No'),
	array('South-East quadrant','Health Passage','Yes','No'),
	array('Sickness Reef','Big Wide Ocean','Yes','No'),
	array('Sickness Reef','North-East quadrant','Yes','No'),
	array('Sickness Reef','South-East quadrant','Yes','No'),
	array('Sickness Reef','Health Passage','Yes','No'),
	array('Sickness Reef','More Rectangular','Yes','No'),
	array('Sickness Reef','Table','Yes','No'),
	array('Sickness Reef','Meerkat','Yes','No'),
	array('Sickness Reef','Spoon','Yes','No'),
	array('Health Passage','South-West quadrant','Yes','No'),
	array('Health Passage','South-East quadrant','Yes','No'),
	array('Health Passage','Sickness Reef','Yes','No'),
	array('Health Passage','Boring Island Sea','Yes','No'),
	array('Health Passage','Sort of Square','Yes','No'),
	array('Health Passage','Spoon','Yes','No'),
	array('Health Passage','Book','Yes','No'),
	array('Boring Island Sea','Big Wide Ocean','Yes','No'),
	array('Boring Island Sea','North-West quadrant','Yes','No'),
	array('Boring Island Sea','South-West quadrant','Yes','No'),
	array('Boring Island Sea','Health Passage','Yes','No'),
	array('Boring Island Sea','Footprint Sea','Yes','No'),
	array('Boring Island Sea','Sort of Square','Yes','No'),
	array('Ocean of Despair','Big Wide Ocean','Yes','No'),
	array('Ocean of Despair','More Rectangular','Yes','No'),
	array('Ocean of Despair','Gulf of Confusion','Yes','No'),
	array('Ocean of Despair','Haha Sea','Yes','No'),
	array('Ocean of Despair','WTF','Yes','No'),
	array('Ocean of Despair','LMAO','Yes','No'),
	array('Ocean of Despair','LOL','Yes','No'),
	array('More Rectangular','Big Wide Ocean','Yes','No'),
	array('More Rectangular','Owl','Yes','No'),
	array('More Rectangular','Sickness Reef','Yes','No'),
	array('More Rectangular','Ocean of Despair','Yes','No'),
	array('More Rectangular','Gulf of Confusion','Yes','No'),
	array('More Rectangular','Table','Yes','No'),
	array('More Rectangular','Door','Yes','No'),
	array('Gulf of Confusion','Ocean of Despair','Yes','No'),
	array('Gulf of Confusion','More Rectangular','Yes','No'),
	array('Gulf of Confusion','Laughter Lagune','Yes','No'),
	array('Gulf of Confusion','WTF','Yes','No'),
	array('Gulf of Confusion','LOL','Yes','No'),
	array('Gulf of Confusion','Vulture','Yes','No'),
	array('Gulf of Confusion','Ostrich','Yes','No'),
	array('Gulf of Confusion','Door','Yes','No'),
	array('Haha Sea','Ocean of Despair','Yes','No'),
	array('Haha Sea','LMAO','Yes','No'),
	array('Haha Sea','ROFL','Yes','No'),
	array('Haha Sea','Guffaw Coast','Yes','No'),
	array('Haha Sea','Sea of Rights','Yes','No'),
	array('Laughter Lagune','Gulf of Confusion','Yes','No'),
	array('Laughter Lagune','LOL','Yes','No'),
	array('Laughter Lagune','ROFL','Yes','No'),
	array('Laughter Lagune','Guffaw Coast','Yes','No'),
	array('Laughter Lagune','Fence','Yes','No'),
	array('Laughter Lagune','Vulture','Yes','No'),
	array('WTF','Ocean of Despair','Yes','No'),
	array('WTF','Gulf of Confusion','Yes','No'),
	array('WTF','LMAO','Yes','Yes'),
	array('WTF','LOL','Yes','Yes'),
	array('LMAO','Ocean of Despair','Yes','No'),
	array('LMAO','Haha Sea','Yes','No'),
	array('LMAO','WTF','Yes','Yes'),
	array('LMAO','LOL','No','Yes'),
	array('LMAO','ROFL','Yes','Yes'),
	array('LOL','Ocean of Despair','Yes','No'),
	array('LOL','Gulf of Confusion','Yes','No'),
	array('LOL','Laughter Lagune','Yes','No'),
	array('LOL','WTF','Yes','Yes'),
	array('LOL','LMAO','No','Yes'),
	array('LOL','ROFL','Yes','Yes'),
	array('ROFL','Haha Sea','Yes','No'),
	array('ROFL','Laughter Lagune','Yes','No'),
	array('ROFL','LMAO','Yes','Yes'),
	array('ROFL','LOL','Yes','Yes'),
	array('ROFL','Guffaw Coast','Yes','No'),
	array('Guffaw Coast','Haha Sea','Yes','No'),
	array('Guffaw Coast','Laughter Lagune','Yes','No'),
	array('Guffaw Coast','ROFL','Yes','No'),
	array('Guffaw Coast','Sea of Rights','Yes','No'),
	array('Guffaw Coast','Dissapointing Straits','Yes','No'),
	array('Guffaw Coast','Carpet','Yes','No'),
	array('Guffaw Coast','Bat','Yes','No'),
	array('Guffaw Coast','Fence','Yes','No'),
	array('Sea of Rights','Haha Sea','Yes','No'),
	array('Sea of Rights','Guffaw Coast','Yes','No'),
	array('Sea of Rights','Sea of Wrongs','Yes','No'),
	array('Sea of Rights','Dissapointing Straits','Yes','No'),
	array('Sea of Rights','Right','Yes','No'),
	array('Sea of Wrongs','Sea of Rights','Yes','No'),
	array('Sea of Wrongs','Abandonment Alley','Yes','No'),
	array('Sea of Wrongs','Right','Yes','No'),
	array('Sea of Wrongs','Left','Yes','No'),
	array('Sea of Wrongs','Glorious Gateway','Yes','No'),
	array('Sea of Wrongs','The Pool','Yes','No'),
	array('Dissapointing Straits','Guffaw Coast','Yes','No'),
	array('Dissapointing Straits','Sea of Rights','Yes','No'),
	array('Dissapointing Straits','Abandonment Alley','Yes','No'),
	array('Dissapointing Straits','Right','Yes','No'),
	array('Dissapointing Straits','Left','Yes','No'),
	array('Dissapointing Straits','Swallow','Yes','No'),
	array('Dissapointing Straits','Bag','Yes','No'),
	array('Dissapointing Straits','Carpet','Yes','No'),
	array('Abandonment Alley','Sea of Wrongs','Yes','No'),
	array('Abandonment Alley','Dissapointing Straits','Yes','No'),
	array('Abandonment Alley','Left','Yes','No'),
	array('Abandonment Alley','Glorious Gateway','Yes','No'),
	array('Abandonment Alley','Kangaroo','Yes','No'),
	array('Abandonment Alley','Swallow','Yes','No'),
	array('Right','Sea of Rights','Yes','No'),
	array('Right','Sea of Wrongs','Yes','No'),
	array('Right','Dissapointing Straits','Yes','No'),
	array('Right','Left','Yes','Yes'),
	array('Right','Inland','No','Yes'),
	array('Left','Sea of Wrongs','Yes','No'),
	array('Left','Dissapointing Straits','Yes','No'),
	array('Left','Abandonment Alley','Yes','No'),
	array('Left','Right','Yes','Yes'),
	array('Left','Inland','No','Yes'),
	array('Inland','Right','No','Yes'),
	array('Inland','Left','No','Yes'),
	array('Glorious Gateway','Sea of Wrongs','Yes','No'),
	array('Glorious Gateway','Abandonment Alley','Yes','No'),
	array('Glorious Gateway','The Pool','Yes','No'),
	array('Glorious Gateway','Enlightenment Bay','Yes','No'),
	array('Glorious Gateway','River','Yes','No'),
	array('Glorious Gateway','Knife','Yes','No'),
	array('Glorious Gateway','Phone','Yes','No'),
	array('Glorious Gateway','Car','Yes','No'),
	array('Glorious Gateway','Kangaroo','Yes','No'),
	array('The Pool','Sea of Wrongs','Yes','No'),
	array('The Pool','Glorious Gateway','Yes','No'),
	array('The Pool','Footprint Sea','Yes','No'),
	array('The Pool','Enlightenment Bay','Yes','No'),
	array('The Pool','Hallux','Yes','No'),
	array('The Pool','Toes','Yes','No'),
	array('The Pool','Arch Deep','Yes','No'),
	array('Footprint Sea','Boring Island Sea','Yes','No'),
	array('Footprint Sea','The Pool','Yes','No'),
	array('Footprint Sea','Epiphany Straits','Yes','No'),
	array('Footprint Sea','Sort of Square','Yes','No'),
	array('Footprint Sea','Heel','Yes','No'),
	array('Footprint Sea','Medial','Yes','No'),
	array('Footprint Sea','Arch Deep','Yes','No'),
	array('Enlightenment Bay','Glorious Gateway','Yes','No'),
	array('Enlightenment Bay','The Pool','Yes','No'),
	array('Enlightenment Bay','Epiphany Straits','Yes','No'),
	array('Enlightenment Bay','Lateral','Yes','No'),
	array('Enlightenment Bay','Toes','Yes','No'),
	array('Enlightenment Bay','Arch Deep','Yes','No'),
	array('Enlightenment Bay','Frog','Yes','No'),
	array('Enlightenment Bay','Trashcan','Yes','No'),
	array('Enlightenment Bay','Knife','Yes','No'),
	array('Epiphany Straits','Footprint Sea','Yes','No'),
	array('Epiphany Straits','Enlightenment Bay','Yes','No'),
	array('Epiphany Straits','Sort of Square','Yes','No'),
	array('Epiphany Straits','Heel','Yes','No'),
	array('Epiphany Straits','Lateral','Yes','No'),
	array('Epiphany Straits','Televison','Yes','No'),
	array('Epiphany Straits','Pig','Yes','No'),
	array('Epiphany Straits','Frog','Yes','No'),
	array('Sort of Square','Health Passage','Yes','No'),
	array('Sort of Square','Boring Island Sea','Yes','No'),
	array('Sort of Square','Footprint Sea','Yes','No'),
	array('Sort of Square','Epiphany Straits','Yes','No'),
	array('Sort of Square','Book','Yes','No'),
	array('Sort of Square','Televison','Yes','No'),
	array('Heel','Footprint Sea','Yes','No'),
	array('Heel','Epiphany Straits','Yes','No'),
	array('Heel','Lateral','Yes','Yes'),
	array('Heel','Medial','Yes','Yes'),
	array('Lateral','Enlightenment Bay','Yes','No'),
	array('Lateral','Epiphany Straits','Yes','No'),
	array('Lateral','Heel','Yes','Yes'),
	array('Lateral','Medial','Yes','Yes'),
	array('Lateral','Arch Deep','Yes','No'),
	array('Medial','Footprint Sea','Yes','No'),
	array('Medial','Heel','Yes','Yes'),
	array('Medial','Lateral','Yes','Yes'),
	array('Medial','Arch Deep','Yes','No'),
	array('Hallux','The Pool','Yes','No'),
	array('Hallux','Toes','Yes','Yes'),
	array('Hallux','Arch Deep','Yes','No'),
	array('Toes','The Pool','Yes','No'),
	array('Toes','Enlightenment Bay','Yes','No'),
	array('Toes','Hallux','Yes','Yes'),
	array('Toes','Arch Deep','Yes','No'),
	array('Arch Deep','The Pool','Yes','No'),
	array('Arch Deep','Footprint Sea','Yes','No'),
	array('Arch Deep','Enlightenment Bay','Yes','No'),
	array('Arch Deep','Lateral','Yes','No'),
	array('Arch Deep','Medial','Yes','No'),
	array('Arch Deep','Hallux','Yes','No'),
	array('Arch Deep','Toes','Yes','No'),
	array('River','Glorious Gateway','Yes','No'),
	array('River','Miny','Yes','No'),
	array('River','Phone','Yes','No'),
	array('River','Sink','Yes','No'),
	array('River','Shelf','Yes','No'),
	array('River','Pen','Yes','No'),
	array('River','Car','Yes','No'),
	array('Eeny','Meeny','Yes','No'),
	array('Eeny','Miny','Yes','No'),
	array('Eeny','Pupil','Yes','No'),
	array('Eeny','Desk','Yes','No'),
	array('Eeny','Blanket','Yes','No'),
	array('Eeny','Chair','Yes','No'),
	array('Meeny','Eeny','Yes','No'),
	array('Meeny','Moe','Yes','No'),
	array('Meeny','Pupil','Yes','No'),
	array('Meeny','Chair','Yes','No'),
	array('Meeny','Squirrel','Yes','No'),
	array('Meeny','Broom','Yes','No'),
	array('Miny','River','Yes','No'),
	array('Miny','Eeny','Yes','No'),
	array('Miny','Moe','Yes','No'),
	array('Miny','Pupil','Yes','No'),
	array('Miny','Sink','Yes','No'),
	array('Miny','Desk','Yes','No'),
	array('Miny','Bottle','Yes','No'),
	array('Miny','Shelf','Yes','No'),
	array('Moe','Meeny','Yes','No'),
	array('Moe','Miny','Yes','No'),
	array('Moe','Pupil','Yes','No'),
	array('Moe','Broom','Yes','No'),
	array('Moe','Sheep','Yes','No'),
	array('Moe','Bottle','Yes','No'),
	array('Pupil','Eeny','Yes','No'),
	array('Pupil','Meeny','Yes','No'),
	array('Pupil','Miny','Yes','No'),
	array('Pupil','Moe','Yes','No'),
	array('Table','Owl','Yes','Yes'),
	array('Table','Sickness Reef','Yes','No'),
	array('Table','More Rectangular','Yes','No'),
	array('Table','Meerkat','Yes','Yes'),
	array('Table','Elephant','No','Yes'),
	array('Meerkat','Sickness Reef','Yes','No'),
	array('Meerkat','Table','Yes','Yes'),
	array('Meerkat','Spoon','Yes','Yes'),
	array('Meerkat','Elephant','No','Yes'),
	array('Meerkat','Shark','No','Yes'),
	array('Spoon','Sickness Reef','Yes','No'),
	array('Spoon','Health Passage','Yes','No'),
	array('Spoon','Meerkat','Yes','Yes'),
	array('Spoon','Book','Yes','Yes'),
	array('Spoon','Shark','No','Yes'),
	array('Spoon','Turtle','No','Yes'),
	array('Book','Health Passage','Yes','No'),
	array('Book','Sort of Square','Yes','No'),
	array('Book','Spoon','Yes','Yes'),
	array('Book','Televison','Yes','Yes'),
	array('Book','Turtle','No','Yes'),
	array('Book','Bike','No','Yes'),
	array('Televison','Epiphany Straits','Yes','No'),
	array('Televison','Sort of Square','Yes','No'),
	array('Televison','Book','Yes','Yes'),
	array('Televison','Pig','Yes','Yes'),
	array('Televison','Bike','No','Yes'),
	array('Televison','Window','No','Yes'),
	array('Televison','Eagle','No','Yes'),
	array('Pig','Epiphany Straits','Yes','No'),
	array('Pig','Televison','Yes','Yes'),
	array('Pig','Frog','Yes','Yes'),
	array('Pig','Eagle','No','Yes'),
	array('Frog','Enlightenment Bay','Yes','No'),
	array('Frog','Epiphany Straits','Yes','No'),
	array('Frog','Pig','Yes','Yes'),
	array('Frog','Trashcan','Yes','Yes'),
	array('Frog','Eagle','No','Yes'),
	array('Frog','Chicken','No','Yes'),
	array('Trashcan','Enlightenment Bay','Yes','No'),
	array('Trashcan','Frog','Yes','Yes'),
	array('Trashcan','Knife','Yes','Yes'),
	array('Trashcan','Chicken','No','Yes'),
	array('Trashcan','Monkey','No','Yes'),
	array('Knife','Glorious Gateway','Yes','No'),
	array('Knife','Enlightenment Bay','Yes','No'),
	array('Knife','Trashcan','Yes','Yes'),
	array('Knife','Phone','Yes','Yes'),
	array('Knife','Monkey','No','Yes'),
	array('Phone','Glorious Gateway','Yes','No'),
	array('Phone','River','Yes','No'),
	array('Phone','Knife','Yes','Yes'),
	array('Phone','Sink','Yes','Yes'),
	array('Phone','Pen','No','Yes'),
	array('Phone','Car','No','Yes'),
	array('Phone','Monkey','No','Yes'),
	array('Sink','River','Yes','No'),
	array('Sink','Miny','Yes','No'),
	array('Sink','Phone','Yes','Yes'),
	array('Sink','Desk','Yes','Yes'),
	array('Sink','Shelf','No','Yes'),
	array('Sink','Pen','No','Yes'),
	array('Sink','Chicken','No','Yes'),
	array('Sink','Monkey','No','Yes'),
	array('Desk','Eeny','Yes','No'),
	array('Desk','Miny','Yes','No'),
	array('Desk','Sink','Yes','Yes'),
	array('Desk','Blanket','Yes','Yes'),
	array('Desk','Window','No','Yes'),
	array('Desk','Chicken','No','Yes'),
	array('Blanket','Eeny','Yes','No'),
	array('Blanket','Desk','Yes','Yes'),
	array('Blanket','Chair','Yes','Yes'),
	array('Blanket','Lizard','No','Yes'),
	array('Blanket','Turtle','No','Yes'),
	array('Blanket','Rat','No','Yes'),
	array('Blanket','Bike','No','Yes'),
	array('Blanket','Window','No','Yes'),
	array('Chair','Eeny','Yes','No'),
	array('Chair','Meeny','Yes','No'),
	array('Chair','Blanket','Yes','Yes'),
	array('Chair','Squirrel','Yes','Yes'),
	array('Chair','Fork','No','Yes'),
	array('Chair','Zebra','No','Yes'),
	array('Chair','Lizard','No','Yes'),
	array('Squirrel','Meeny','Yes','No'),
	array('Squirrel','Chair','Yes','Yes'),
	array('Squirrel','Broom','Yes','Yes'),
	array('Squirrel','Fence','No','Yes'),
	array('Squirrel','Vulture','No','Yes'),
	array('Squirrel','Bear','No','Yes'),
	array('Squirrel','Fork','No','Yes'),
	array('Broom','Meeny','Yes','No'),
	array('Broom','Moe','Yes','No'),
	array('Broom','Squirrel','Yes','Yes'),
	array('Broom','Sheep','Yes','Yes'),
	array('Broom','Bat','No','Yes'),
	array('Broom','Bear','No','Yes'),
	array('Sheep','Moe','Yes','No'),
	array('Sheep','Broom','Yes','Yes'),
	array('Sheep','Bottle','Yes','Yes'),
	array('Sheep','Carpet','No','Yes'),
	array('Sheep','Bat','No','Yes'),
	array('Sheep','Fish','No','Yes'),
	array('Bottle','Miny','Yes','No'),
	array('Bottle','Moe','Yes','No'),
	array('Bottle','Sheep','Yes','Yes'),
	array('Bottle','Shelf','Yes','Yes'),
	array('Bottle','Cow','No','Yes'),
	array('Bottle','Couch','No','Yes'),
	array('Bottle','Lion','No','Yes'),
	array('Bottle','Fish','No','Yes'),
	array('Shelf','River','Yes','No'),
	array('Shelf','Miny','Yes','No'),
	array('Shelf','Sink','No','Yes'),
	array('Shelf','Bottle','Yes','Yes'),
	array('Shelf','Pen','Yes','Yes'),
	array('Shelf','Cow','No','Yes'),
	array('Pen','River','Yes','No'),
	array('Pen','Phone','No','Yes'),
	array('Pen','Sink','No','Yes'),
	array('Pen','Shelf','Yes','Yes'),
	array('Pen','Car','Yes','Yes'),
	array('Pen','Cow','No','Yes'),
	array('Car','Glorious Gateway','Yes','No'),
	array('Car','River','Yes','No'),
	array('Car','Phone','No','Yes'),
	array('Car','Pen','Yes','Yes'),
	array('Car','Kangaroo','Yes','Yes'),
	array('Car','Snake','No','Yes'),
	array('Car','Cow','No','Yes'),
	array('Kangaroo','Abandonment Alley','Yes','No'),
	array('Kangaroo','Glorious Gateway','Yes','No'),
	array('Kangaroo','Car','Yes','Yes'),
	array('Kangaroo','Swallow','Yes','Yes'),
	array('Kangaroo','Snake','No','Yes'),
	array('Swallow','Dissapointing Straits','Yes','No'),
	array('Swallow','Abandonment Alley','Yes','No'),
	array('Swallow','Kangaroo','Yes','Yes'),
	array('Swallow','Bag','Yes','Yes'),
	array('Swallow','Snake','No','Yes'),
	array('Swallow','Couch','No','Yes'),
	array('Swallow','Lion','No','Yes'),
	array('Bag','Dissapointing Straits','Yes','No'),
	array('Bag','Swallow','Yes','Yes'),
	array('Bag','Carpet','Yes','Yes'),
	array('Bag','Lion','No','Yes'),
	array('Carpet','Guffaw Coast','Yes','No'),
	array('Carpet','Dissapointing Straits','Yes','No'),
	array('Carpet','Sheep','No','Yes'),
	array('Carpet','Bag','Yes','Yes'),
	array('Carpet','Bat','Yes','Yes'),
	array('Carpet','Lion','No','Yes'),
	array('Carpet','Fish','No','Yes'),
	array('Bat','Guffaw Coast','Yes','No'),
	array('Bat','Broom','No','Yes'),
	array('Bat','Sheep','No','Yes'),
	array('Bat','Carpet','Yes','Yes'),
	array('Bat','Fence','Yes','Yes'),
	array('Bat','Bear','No','Yes'),
	array('Fence','Laughter Lagune','Yes','No'),
	array('Fence','Guffaw Coast','Yes','No'),
	array('Fence','Squirrel','No','Yes'),
	array('Fence','Bat','Yes','Yes'),
	array('Fence','Vulture','Yes','Yes'),
	array('Fence','Bear','No','Yes'),
	array('Vulture','Gulf of Confusion','Yes','No'),
	array('Vulture','Laughter Lagune','Yes','No'),
	array('Vulture','Squirrel','No','Yes'),
	array('Vulture','Fence','Yes','Yes'),
	array('Vulture','Ostrich','Yes','Yes'),
	array('Vulture','Lamp','No','Yes'),
	array('Vulture','Fork','No','Yes'),
	array('Ostrich','Gulf of Confusion','Yes','No'),
	array('Ostrich','Vulture','Yes','Yes'),
	array('Ostrich','Door','Yes','Yes'),
	array('Ostrich','Lamp','No','Yes'),
	array('Ostrich','Platypus','No','Yes'),
	array('Door','Owl','Yes','Yes'),
	array('Door','More Rectangular','Yes','No'),
	array('Door','Gulf of Confusion','Yes','No'),
	array('Door','Ostrich','Yes','Yes'),
	array('Door','Platypus','No','Yes'),
	array('Snake','Car','No','Yes'),
	array('Snake','Kangaroo','No','Yes'),
	array('Snake','Swallow','No','Yes'),
	array('Snake','Cow','No','Yes'),
	array('Snake','Couch','No','Yes'),
	array('Cow','Bottle','No','Yes'),
	array('Cow','Shelf','No','Yes'),
	array('Cow','Pen','No','Yes'),
	array('Cow','Car','No','Yes'),
	array('Cow','Snake','No','Yes'),
	array('Cow','Couch','No','Yes'),
	array('Couch','Bottle','No','Yes'),
	array('Couch','Swallow','No','Yes'),
	array('Couch','Snake','No','Yes'),
	array('Couch','Cow','No','Yes'),
	array('Couch','Lion','No','Yes'),
	array('Lion','Bottle','No','Yes'),
	array('Lion','Swallow','No','Yes'),
	array('Lion','Bag','No','Yes'),
	array('Lion','Carpet','No','Yes'),
	array('Lion','Couch','No','Yes'),
	array('Lion','Fish','No','Yes'),
	array('Fish','Sheep','No','Yes'),
	array('Fish','Bottle','No','Yes'),
	array('Fish','Carpet','No','Yes'),
	array('Fish','Lion','No','Yes'),
	array('Bear','Squirrel','No','Yes'),
	array('Bear','Broom','No','Yes'),
	array('Bear','Bat','No','Yes'),
	array('Bear','Fence','No','Yes'),
	array('Lamp','Vulture','No','Yes'),
	array('Lamp','Ostrich','No','Yes'),
	array('Lamp','Fork','No','Yes'),
	array('Lamp','Platypus','No','Yes'),
	array('Fork','Chair','No','Yes'),
	array('Fork','Squirrel','No','Yes'),
	array('Fork','Vulture','No','Yes'),
	array('Fork','Lamp','No','Yes'),
	array('Fork','Zebra','No','Yes'),
	array('Fork','Airconditioner','No','Yes'),
	array('Fork','Platypus','No','Yes'),
	array('Zebra','Chair','No','Yes'),
	array('Zebra','Fork','No','Yes'),
	array('Zebra','Lizard','No','Yes'),
	array('Zebra','Airconditioner','No','Yes'),
	array('Lizard','Blanket','No','Yes'),
	array('Lizard','Chair','No','Yes'),
	array('Lizard','Zebra','No','Yes'),
	array('Lizard','Airconditioner','No','Yes'),
	array('Lizard','Turtle','No','Yes'),
	array('Airconditioner','Fork','No','Yes'),
	array('Airconditioner','Zebra','No','Yes'),
	array('Airconditioner','Lizard','No','Yes'),
	array('Airconditioner','Platypus','No','Yes'),
	array('Airconditioner','Elephant','No','Yes'),
	array('Airconditioner','Shark','No','Yes'),
	array('Airconditioner','Turtle','No','Yes'),
	array('Platypus','Owl','No','Yes'),
	array('Platypus','Ostrich','No','Yes'),
	array('Platypus','Door','No','Yes'),
	array('Platypus','Lamp','No','Yes'),
	array('Platypus','Fork','No','Yes'),
	array('Platypus','Airconditioner','No','Yes'),
	array('Platypus','Elephant','No','Yes'),
	array('Elephant','Owl','No','Yes'),
	array('Elephant','Table','No','Yes'),
	array('Elephant','Meerkat','No','Yes'),
	array('Elephant','Airconditioner','No','Yes'),
	array('Elephant','Platypus','No','Yes'),
	array('Elephant','Shark','No','Yes'),
	array('Shark','Meerkat','No','Yes'),
	array('Shark','Spoon','No','Yes'),
	array('Shark','Airconditioner','No','Yes'),
	array('Shark','Elephant','No','Yes'),
	array('Shark','Turtle','No','Yes'),
	array('Turtle','Spoon','No','Yes'),
	array('Turtle','Book','No','Yes'),
	array('Turtle','Blanket','No','Yes'),
	array('Turtle','Lizard','No','Yes'),
	array('Turtle','Airconditioner','No','Yes'),
	array('Turtle','Shark','No','Yes'),
	array('Turtle','Rat','No','Yes'),
	array('Turtle','Bike','No','Yes'),
	array('Rat','Blanket','No','Yes'),
	array('Rat','Turtle','No','Yes'),
	array('Rat','Bike','No','Yes'),
	array('Bike','Book','No','Yes'),
	array('Bike','Televison','No','Yes'),
	array('Bike','Blanket','No','Yes'),
	array('Bike','Turtle','No','Yes'),
	array('Bike','Rat','No','Yes'),
	array('Bike','Window','No','Yes'),
	array('Window','Televison','No','Yes'),
	array('Window','Desk','No','Yes'),
	array('Window','Blanket','No','Yes'),
	array('Window','Bike','No','Yes'),
	array('Window','Eagle','No','Yes'),
	array('Window','Chicken','No','Yes'),
	array('Eagle','Televison','No','Yes'),
	array('Eagle','Pig','No','Yes'),
	array('Eagle','Frog','No','Yes'),
	array('Eagle','Window','No','Yes'),
	array('Eagle','Chicken','No','Yes'),
	array('Chicken','Frog','No','Yes'),
	array('Chicken','Trashcan','No','Yes'),
	array('Chicken','Sink','No','Yes'),
	array('Chicken','Desk','No','Yes'),
	array('Chicken','Window','No','Yes'),
	array('Chicken','Eagle','No','Yes'),
	array('Chicken','Monkey','No','Yes'),
	array('Monkey','Trashcan','No','Yes'),
	array('Monkey','Knife','No','Yes'),
	array('Monkey','Phone','No','Yes'),
	array('Monkey','Sink','No','Yes'),
	array('Monkey','Chicken','No','Yes')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
