<?php
// This is file installs the map data for the GreatLakes variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Atikoken', 'Coast', 'No', 7, 335, 183, 163, 89),
	array('Whyte', 'Coast', 'Yes', 7, 232, 297, 110, 151),
	array('Savanna', 'Land', 'Yes', 7, 93, 310, 25, 193),
	array('Croix', 'Coast', 'Yes', 7, 220, 412, 103, 208),
	array('Eau Galle', 'Land', 'No', 7, 157, 549, 78, 270),
	array('Nemadji', 'Land', 'No', 7, 46, 587, 30, 313),
	array('Klondyke', 'Coast', 'No', 1, 890, 323, 430, 134),
	array('Mattawa', 'Land', 'No', 1, 980, 244, 483, 119),
	array('Kioshkokwi', 'Land', 'Yes', 1, 1030, 319, 510, 156),
	array('Shawanaga', 'Coast', 'Yes', 1, 961, 366, 475, 181),
	array('Wahwashkesh', 'Land', 'Yes', 1, 1063, 395, 523, 189),
	array('Simcoe', 'Coast', 'No', 1, 1007, 449, 501, 219),
	array('Madawaska', 'Land', 'No', 9, 1217, 195, 605, 94),
	array('Matawin', 'Land', 'Yes', 9, 1355, 248, 670, 122),
	array('Manotick', 'Land', 'Yes', 9, 1277, 222, 633, 111),
	array('Jasper', 'Land', 'No', 9, 1325, 308, 656, 151),
	array('Vars', 'Coast', 'Yes', 9, 1353, 354, 670, 172),
	array('Windmill', 'Land', 'No', 9, 1249, 373, 618, 174),
	array('Niagara', 'Coast', 'No', 4, 1132, 573, 559, 285),
	array('Rochester', 'Coast', 'Yes', 4, 1172, 559, 582, 276),
	array('Chenango', 'Land', 'No', 4, 1314, 636, 645, 315),
	array('Ithaca', 'Land', 'No', 4, 1215, 692, 595, 336),
	array('Oswego', 'Coast', 'Yes', 4, 1145, 624, 565, 313),
	array('Tuscarora', 'Coast', 'Yes', 4, 1253, 537, 620, 278),
	array('Wyalusing', 'Land', 'No', 4, 1178, 769, 577, 379),
	array('Buckhorn', 'Land', 'No', 6, 1057, 447, 524, 222),
	array('Klemburg', 'Land', 'Yes', 6, 1052, 480, 516, 240),
	array('Nottawasaga', 'Land', 'No', 6, 999, 529, 494, 262),
	array('Oshawa', 'Coast', 'Yes', 6, 1125, 476, 552, 234),
	array('Selkirk', 'Coast', 'No', 6, 1040, 617, 514, 304),
	array('Toronto', 'Coast', 'Yes', 6, 1051, 559, 533, 257),
	array('Cheptow', 'Coast', 'Yes', 3, 966, 471, 475, 234),
	array('Appin', 'Land', 'No', 3, 952, 616, 468, 305),
	array('Nile', 'Coast', 'Yes', 3, 927, 561, 456, 278),
	array('Sanilac', 'Coast', 'Yes', 3, 805, 583, 400, 288),
	array('Sarnia', 'Coast', 'No', 3, 898, 649, 439, 322),
	array('Aetna', 'Coast', 'Yes', 8, 602, 551, 304, 273),
	array('Alcona', 'Coast', 'Yes', 8, 739, 441, 364, 217),
	array('Arenac', 'Coast', 'No', 8, 751, 536, 366, 265),
	array('Boyee', 'Coast', 'Yes', 8, 653, 429, 322, 214),
	array('North Channel', 'Coast', 'No', 8, 678, 357, 337, 177),
	array('Oshkosh', 'Coast', 'No', 8, 572, 376, 290, 178),
	array('Cass', 'Coast', 'No', 2, 629, 777, 319, 382),
	array('Essex', 'Coast', 'Yes', 2, 872, 743, 427, 364),
	array('Imlay', 'Land', 'Yes', 2, 787, 718, 388, 350),
	array('Lenawee', 'Land', 'No', 2, 731, 775, 364, 382),
	array('Toledo', 'Coast', 'Yes', 2, 850, 808, 417, 397),
	array('Kankakee', 'Coast', 'Yes', 5, 503, 783, 242, 391),
	array('Kegonsa', 'Land', 'No', 5, 371, 725, 183, 354),
	array('Sussex', 'Coast', 'Yes', 5, 488, 646, 237, 320),
	array('Waukesha', 'Coast', 'Yes', 5, 503, 739, 238, 348),
	array('Winamac', 'Coast', 'No', 5, 541, 820, 266, 410),
	array('Pukaskwa', 'Coast', 'No', 0, 618, 226, 309, 102),
	array('Kapuskasing', 'Land', 'Yes', 0, 678, 150, 330, 72),
	array('Manitoulin', 'Coast', 'Yes', 0, 838, 326, 411, 161),
	array('Ontonagon', 'Coast', 'No', 0, 437, 412, 214, 202),
	array('Chequamegon', 'Coast', 'Yes', 0, 321, 403, 161, 206),
	array('Oconto', 'Coast', 'Yes', 0, 461, 509, 226, 251),
	array('Weyauwega', 'Land', 'Yes', 0, 342, 498, 170, 248),
	array('La Crosse', 'Land', 'Yes', 0, 223, 660, 118, 302),
	array('Waunakee', 'Land', 'No', 0, 357, 617, 174, 309),
	array('Muscoda', 'Land', 'No', 0, 140, 756, 77, 373),
	array('Pecatonica', 'Land', 'Yes', 0, 272, 758, 130, 347),
	array('Kewanne', 'Land', 'Yes', 0, 330, 859, 141, 416),
	array('Wawasee', 'Coast', 'Yes', 0, 593, 830, 294, 416),
	array('Saranac', 'Coast', 'Yes', 0, 625, 651, 310, 320),
	array('Saginaw', 'Land', 'Yes', 0, 677, 533, 335, 265),
	array('Shiawassee', 'Land', 'Yes', 0, 739, 634, 365, 314),
	array('Seneca', 'Coast', 'Yes', 0, 942, 788, 466, 394),
	array('Cussewago', 'Coast', 'Yes', 0, 1055, 716, 528, 352),
	array('Oneida', 'Coast', 'Yes', 0, 1290, 457, 634, 233),
	array('Massena', 'Coast', 'Yes', 0, 1349, 405, 665, 202),
	array('Crowe', 'Coast', 'Yes', 0, 1188, 455, 587, 225),
	array('Mazinaw', 'Coast', 'No', 0, 1152, 463, 568, 228),
	array('Matawatchan', 'Land', 'No', 0, 1147, 319, 566, 161),
	array('Petawawa', 'Land', 'Yes', 0, 1116, 244, 552, 117),
	array('Perth', 'Land', 'Yes', 0, 1215, 278, 601, 141),
	array('Ethana', 'Land', 'Yes', 0, 964, 549, 475, 271),
	array('Calina', 'Land', 'Yes', 0, 990, 570, 489, 280),
	array('Waten', 'Land', 'Yes', 0, 1005, 595, 496, 293),
	array('Naningo', 'Coast', 'Yes', 0, 982, 641, 483, 317),
	array('Lynanee', 'Coast', 'No', 0, 1269, 414, 622, 206),
	array('Adinanara', 'Land', 'Yes', 0, 1358, 505, 672, 247),
	array('Almina', 'Coast', 'Yes', 0, 908, 704, 449, 346),
	array('West Lake Superior', 'Sea', 'No', 0, 304, 350, 149, 172),
	array('Central Lake Superior', 'Sea', 'No', 0, 446, 264, 221, 130),
	array('East Lake Superior', 'Sea', 'No', 0, 582, 283, 286, 144),
	array('North Lake Michigan', 'Sea', 'No', 0, 567, 485, 284, 239),
	array('Central Lake Michigan', 'Sea', 'No', 0, 550, 634, 271, 314),
	array('South Lake Michigan', 'Sea', 'No', 0, 572, 769, 285, 379),
	array('North Lake Huron', 'Sea', 'No', 0, 810, 461, 401, 222),
	array('South Lake Huron', 'Sea', 'No', 0, 867, 508, 425, 256),
	array('Georgian Bay', 'Sea', 'No', 0, 912, 390, 448, 195),
	array('Lake St. Clair', 'Sea', 'No', 0, 869, 703, 428, 348),
	array('West Lake Erie', 'Sea', 'No', 0, 912, 752, 450, 372),
	array('East Lake Erie', 'Sea', 'No', 0, 1060, 653, 522, 324),
	array('West Lake Ontario', 'Sea', 'No', 0, 1122, 533, 555, 263),
	array('Central Lake Ontario', 'Sea', 'No', 0, 1173, 494, 579, 247),
	array('East Lake Ontario', 'Sea', 'No', 0, 1219, 510, 602, 251),
	array('West St. Lawrence River', 'Sea', 'No', 0, 1288, 426, 635, 209),
	array('East St. Lawrence River', 'Sea', 'No', 0, 1366, 377, 677, 185),
	array('Algonquin', 'Land', 'No', 1, 771, 31, 380, 15),
	array('Erie', 'Land', 'No', 2, 770, 71, 380, 35),
	array('Huron', 'Land', 'No', 3, 770, 109, 380, 54),
	array('Iroquois', 'Land', 'No', 4, 952, 32, 469, 16),
	array('Kaskasia', 'Land', 'No', 5, 953, 70, 470, 35),
	array('Mississauga', 'Land', 'No', 6, 953, 109, 470, 54),
	array('Ojibwe', 'Land', 'No', 7, 1134, 31, 559, 16),
	array('Otawatomi', 'Land', 'No', 8, 1134, 71, 559, 35),
	array('Ottawa', 'Land', 'No', 9, 1134, 109, 559, 54),
	array('Ontonagon (North Coast)', 'Coast', 'No', 0, 439, 364, 215, 180),
	array('Ontonagon (East Coast)', 'Coast', 'No', 0, 540, 414, 265, 203),
	array('Oshkosh (North Coast)', 'Coast', 'No', 8, 567, 348, 278, 171),
	array('Oshkosh (South Coast)', 'Coast', 'No', 8, 599, 384, 284, 193),
	array('Almina (West Coast)', 'Coast', 'No', 0, 894, 697, 442, 345),
	array('Almina (South Coast)', 'Coast', 'No', 0, 910, 709, 451, 347)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Atikoken','Whyte','Yes','Yes'),
	array('Atikoken','Savanna','No','Yes'),
	array('Atikoken','Pukaskwa','Yes','Yes'),
	array('Atikoken','Kapuskasing','No','Yes'),
	array('Atikoken','West Lake Superior','Yes','No'),
	array('Atikoken','Central Lake Superior','Yes','No'),
	array('Whyte','Savanna','No','Yes'),
	array('Whyte','Croix','Yes','Yes'),
	array('Whyte','West Lake Superior','Yes','No'),
	array('Savanna','Croix','No','Yes'),
	array('Savanna','Eau Galle','No','Yes'),
	array('Savanna','Nemadji','No','Yes'),
	array('Croix','Eau Galle','No','Yes'),
	array('Croix','Chequamegon','Yes','Yes'),
	array('Croix','West Lake Superior','Yes','No'),
	array('Eau Galle','Nemadji','No','Yes'),
	array('Eau Galle','Chequamegon','No','Yes'),
	array('Eau Galle','Weyauwega','No','Yes'),
	array('Eau Galle','La Crosse','No','Yes'),
	array('Nemadji','La Crosse','No','Yes'),
	array('Nemadji','Muscoda','No','Yes'),
	array('Klondyke','Mattawa','No','Yes'),
	array('Klondyke','Shawanaga','Yes','Yes'),
	array('Klondyke','North Channel','No','Yes'),
	array('Klondyke','Pukaskwa','No','Yes'),
	array('Klondyke','Kapuskasing','No','Yes'),
	array('Klondyke','Manitoulin','Yes','Yes'),
	array('Klondyke','Georgian Bay','Yes','No'),
	array('Mattawa','Kioshkokwi','No','Yes'),
	array('Mattawa','Shawanaga','No','Yes'),
	array('Mattawa','Kapuskasing','No','Yes'),
	array('Mattawa','Petawawa','No','Yes'),
	array('Kioshkokwi','Shawanaga','No','Yes'),
	array('Kioshkokwi','Wahwashkesh','No','Yes'),
	array('Kioshkokwi','Matawatchan','No','Yes'),
	array('Kioshkokwi','Petawawa','No','Yes'),
	array('Shawanaga','Wahwashkesh','No','Yes'),
	array('Shawanaga','Simcoe','Yes','Yes'),
	array('Shawanaga','Georgian Bay','Yes','No'),
	array('Wahwashkesh','Simcoe','No','Yes'),
	array('Wahwashkesh','Buckhorn','No','Yes'),
	array('Wahwashkesh','Mazinaw','No','Yes'),
	array('Wahwashkesh','Matawatchan','No','Yes'),
	array('Simcoe','Buckhorn','No','Yes'),
	array('Simcoe','Nottawasaga','No','Yes'),
	array('Simcoe','Cheptow','Yes','Yes'),
	array('Simcoe','Georgian Bay','Yes','No'),
	array('Madawaska','Matawin','No','Yes'),
	array('Madawaska','Manotick','No','Yes'),
	array('Madawaska','Petawawa','No','Yes'),
	array('Madawaska','Perth','No','Yes'),
	array('Matawin','Manotick','No','Yes'),
	array('Matawin','Jasper','No','Yes'),
	array('Matawin','Vars','No','Yes'),
	array('Manotick','Jasper','No','Yes'),
	array('Manotick','Perth','No','Yes'),
	array('Jasper','Vars','No','Yes'),
	array('Jasper','Windmill','No','Yes'),
	array('Jasper','Perth','No','Yes'),
	array('Vars','Windmill','No','Yes'),
	array('Vars','Lynanee','Yes','Yes'),
	array('Vars','East St. Lawrence River','Yes','No'),
	array('Windmill','Crowe','No','Yes'),
	array('Windmill','Matawatchan','No','Yes'),
	array('Windmill','Perth','No','Yes'),
	array('Windmill','Lynanee','No','Yes'),
	array('Niagara','Rochester','Yes','Yes'),
	array('Niagara','Oswego','Yes','Yes'),
	array('Niagara','Selkirk','Yes','Yes'),
	array('Niagara','Toronto','Yes','Yes'),
	array('Niagara','East Lake Erie','Yes','No'),
	array('Niagara','West Lake Ontario','Yes','No'),
	array('Rochester','Oswego','No','Yes'),
	array('Rochester','Tuscarora','Yes','Yes'),
	array('Rochester','West Lake Ontario','Yes','No'),
	array('Rochester','Central Lake Ontario','Yes','No'),
	array('Rochester','East Lake Ontario','Yes','No'),
	array('Chenango','Ithaca','No','Yes'),
	array('Chenango','Tuscarora','No','Yes'),
	array('Chenango','Wyalusing','No','Yes'),
	array('Chenango','Oneida','No','Yes'),
	array('Chenango','Adinanara','No','Yes'),
	array('Ithaca','Oswego','No','Yes'),
	array('Ithaca','Tuscarora','No','Yes'),
	array('Ithaca','Wyalusing','No','Yes'),
	array('Ithaca','Cussewago','No','Yes'),
	array('Oswego','Tuscarora','No','Yes'),
	array('Oswego','Cussewago','Yes','Yes'),
	array('Oswego','East Lake Erie','Yes','No'),
	array('Tuscarora','Oneida','Yes','Yes'),
	array('Tuscarora','East Lake Ontario','Yes','No'),
	array('Wyalusing','Seneca','No','Yes'),
	array('Wyalusing','Cussewago','No','Yes'),
	array('Buckhorn','Klemburg','No','Yes'),
	array('Buckhorn','Nottawasaga','No','Yes'),
	array('Buckhorn','Oshawa','No','Yes'),
	array('Buckhorn','Mazinaw','No','Yes'),
	array('Klemburg','Nottawasaga','No','Yes'),
	array('Klemburg','Oshawa','No','Yes'),
	array('Klemburg','Toronto','No','Yes'),
	array('Klemburg','Waten','No','Yes'),
	array('Nottawasaga','Cheptow','No','Yes'),
	array('Nottawasaga','Ethana','No','Yes'),
	array('Nottawasaga','Calina','No','Yes'),
	array('Nottawasaga','Waten','No','Yes'),
	array('Oshawa','Toronto','Yes','Yes'),
	array('Oshawa','Mazinaw','Yes','Yes'),
	array('Oshawa','West Lake Ontario','Yes','No'),
	array('Oshawa','Central Lake Ontario','Yes','No'),
	array('Selkirk','Toronto','No','Yes'),
	array('Selkirk','Waten','No','Yes'),
	array('Selkirk','Naningo','Yes','Yes'),
	array('Selkirk','East Lake Erie','Yes','No'),
	array('Toronto','Waten','No','Yes'),
	array('Toronto','West Lake Ontario','Yes','No'),
	array('Cheptow','Nile','Yes','Yes'),
	array('Cheptow','Ethana','No','Yes'),
	array('Cheptow','South Lake Huron','Yes','No'),
	array('Cheptow','Georgian Bay','Yes','No'),
	array('Appin','Nile','No','Yes'),
	array('Appin','Sarnia','No','Yes'),
	array('Appin','Ethana','No','Yes'),
	array('Appin','Calina','No','Yes'),
	array('Appin','Waten','No','Yes'),
	array('Appin','Naningo','No','Yes'),
	array('Appin','Almina','No','Yes'),
	array('Nile','Sarnia','Yes','Yes'),
	array('Nile','Ethana','No','Yes'),
	array('Nile','South Lake Huron','Yes','No'),
	array('Sanilac','Sarnia','Yes','Yes'),
	array('Sanilac','Arenac','Yes','Yes'),
	array('Sanilac','Shiawassee','No','Yes'),
	array('Sanilac','South Lake Huron','Yes','No'),
	array('Sarnia','Essex','Yes','Yes'),
	array('Sarnia','Imlay','No','Yes'),
	array('Sarnia','Shiawassee','No','Yes'),
	array('Sarnia','Almina','No','Yes'),
	array('Sarnia','South Lake Huron','Yes','No'),
	array('Sarnia','Lake St. Clair','Yes','No'),
	array('Sarnia','Almina (West Coast)','Yes','No'),
	array('Aetna','Boyee','Yes','Yes'),
	array('Aetna','Saranac','Yes','Yes'),
	array('Aetna','Saginaw','No','Yes'),
	array('Aetna','North Lake Michigan','Yes','No'),
	array('Aetna','Central Lake Michigan','Yes','No'),
	array('Alcona','Arenac','Yes','Yes'),
	array('Alcona','Boyee','Yes','Yes'),
	array('Alcona','North Channel','Yes','Yes'),
	array('Alcona','North Lake Huron','Yes','No'),
	array('Arenac','Boyee','No','Yes'),
	array('Arenac','Saginaw','No','Yes'),
	array('Arenac','Shiawassee','No','Yes'),
	array('Arenac','North Lake Huron','Yes','No'),
	array('Arenac','South Lake Huron','Yes','No'),
	array('Boyee','North Channel','Yes','Yes'),
	array('Boyee','Saginaw','No','Yes'),
	array('Boyee','North Lake Michigan','Yes','No'),
	array('North Channel','Oshkosh','No','Yes'),
	array('North Channel','Pukaskwa','Yes','Yes'),
	array('North Channel','Manitoulin','Yes','Yes'),
	array('North Channel','East Lake Superior','Yes','No'),
	array('North Channel','North Lake Michigan','Yes','No'),
	array('North Channel','North Lake Huron','Yes','No'),
	array('North Channel','Oshkosh (North Coast)','Yes','No'),
	array('North Channel','Oshkosh (South Coast)','Yes','No'),
	array('Oshkosh','Ontonagon','No','Yes'),
	array('Cass','Lenawee','No','Yes'),
	array('Cass','Wawasee','Yes','Yes'),
	array('Cass','Saranac','Yes','Yes'),
	array('Cass','Shiawassee','No','Yes'),
	array('Cass','South Lake Michigan','Yes','No'),
	array('Essex','Imlay','No','Yes'),
	array('Essex','Toledo','Yes','Yes'),
	array('Essex','Almina','No','Yes'),
	array('Essex','Lake St. Clair','Yes','No'),
	array('Essex','West Lake Erie','Yes','No'),
	array('Essex','Almina (West Coast)','Yes','No'),
	array('Essex','Almina (South Coast)','Yes','No'),
	array('Imlay','Lenawee','No','Yes'),
	array('Imlay','Toledo','No','Yes'),
	array('Imlay','Shiawassee','No','Yes'),
	array('Lenawee','Toledo','No','Yes'),
	array('Lenawee','Wawasee','No','Yes'),
	array('Lenawee','Shiawassee','No','Yes'),
	array('Toledo','Wawasee','No','Yes'),
	array('Toledo','Seneca','Yes','Yes'),
	array('Toledo','West Lake Erie','Yes','No'),
	array('Kankakee','Kegonsa','No','Yes'),
	array('Kankakee','Waukesha','Yes','Yes'),
	array('Kankakee','Winamac','Yes','Yes'),
	array('Kankakee','Kewanne','No','Yes'),
	array('Kankakee','South Lake Michigan','Yes','No'),
	array('Kegonsa','Sussex','No','Yes'),
	array('Kegonsa','Waukesha','No','Yes'),
	array('Kegonsa','Waunakee','No','Yes'),
	array('Kegonsa','Pecatonica','No','Yes'),
	array('Kegonsa','Kewanne','No','Yes'),
	array('Sussex','Waukesha','Yes','Yes'),
	array('Sussex','Oconto','Yes','Yes'),
	array('Sussex','Waunakee','No','Yes'),
	array('Sussex','North Lake Michigan','Yes','No'),
	array('Sussex','Central Lake Michigan','Yes','No'),
	array('Waukesha','Central Lake Michigan','Yes','No'),
	array('Waukesha','South Lake Michigan','Yes','No'),
	array('Winamac','Wawasee','Yes','Yes'),
	array('Winamac','South Lake Michigan','Yes','No'),
	array('Pukaskwa','Kapuskasing','No','Yes'),
	array('Pukaskwa','Central Lake Superior','Yes','No'),
	array('Pukaskwa','East Lake Superior','Yes','No'),
	array('Manitoulin','North Lake Huron','Yes','No'),
	array('Manitoulin','Georgian Bay','Yes','No'),
	array('Ontonagon','Chequamegon','No','Yes'),
	array('Ontonagon','Oconto','No','Yes'),
	array('Chequamegon','Oconto','No','Yes'),
	array('Chequamegon','Weyauwega','No','Yes'),
	array('Chequamegon','West Lake Superior','Yes','No'),
	array('Chequamegon','Ontonagon (North Coast)','Yes','No'),
	array('Oconto','Weyauwega','No','Yes'),
	array('Oconto','Waunakee','No','Yes'),
	array('Oconto','North Lake Michigan','Yes','No'),
	array('Oconto','Ontonagon (East Coast)','Yes','No'),
	array('Weyauwega','La Crosse','No','Yes'),
	array('Weyauwega','Waunakee','No','Yes'),
	array('La Crosse','Waunakee','No','Yes'),
	array('La Crosse','Muscoda','No','Yes'),
	array('La Crosse','Pecatonica','No','Yes'),
	array('Waunakee','Pecatonica','No','Yes'),
	array('Muscoda','Pecatonica','No','Yes'),
	array('Muscoda','Kewanne','No','Yes'),
	array('Pecatonica','Kewanne','No','Yes'),
	array('Wawasee','South Lake Michigan','Yes','No'),
	array('Saranac','Saginaw','No','Yes'),
	array('Saranac','Shiawassee','No','Yes'),
	array('Saranac','Central Lake Michigan','Yes','No'),
	array('Saranac','South Lake Michigan','Yes','No'),
	array('Saginaw','Shiawassee','No','Yes'),
	array('Seneca','Cussewago','Yes','Yes'),
	array('Seneca','West Lake Erie','Yes','No'),
	array('Cussewago','West Lake Erie','Yes','No'),
	array('Cussewago','East Lake Erie','Yes','No'),
	array('Oneida','Massena','Yes','Yes'),
	array('Oneida','Adinanara','No','Yes'),
	array('Oneida','East Lake Ontario','Yes','No'),
	array('Oneida','West St. Lawrence River','Yes','No'),
	array('Massena','Adinanara','No','Yes'),
	array('Massena','West St. Lawrence River','Yes','No'),
	array('Massena','East St. Lawrence River','Yes','No'),
	array('Crowe','Mazinaw','Yes','Yes'),
	array('Crowe','Matawatchan','No','Yes'),
	array('Crowe','Lynanee','Yes','Yes'),
	array('Crowe','Central Lake Ontario','Yes','No'),
	array('Crowe','East Lake Ontario','Yes','No'),
	array('Mazinaw','Matawatchan','No','Yes'),
	array('Mazinaw','Central Lake Ontario','Yes','No'),
	array('Matawatchan','Petawawa','No','Yes'),
	array('Matawatchan','Perth','No','Yes'),
	array('Petawawa','Perth','No','Yes'),
	array('Ethana','Calina','No','Yes'),
	array('Calina','Waten','No','Yes'),
	array('Waten','Naningo','No','Yes'),
	array('Naningo','Almina','No','Yes'),
	array('Naningo','East Lake Erie','Yes','No'),
	array('Naningo','Almina (South Coast)','Yes','No'),
	array('Lynanee','East Lake Ontario','Yes','No'),
	array('Lynanee','West St. Lawrence River','Yes','No'),
	array('Lynanee','East St. Lawrence River','Yes','No'),
	array('West Lake Superior','Central Lake Superior','Yes','No'),
	array('West Lake Superior','Ontonagon (North Coast)','Yes','No'),
	array('Central Lake Superior','East Lake Superior','Yes','No'),
	array('Central Lake Superior','Ontonagon (North Coast)','Yes','No'),
	array('East Lake Superior','Ontonagon (North Coast)','Yes','No'),
	array('East Lake Superior','Oshkosh (North Coast)','Yes','No'),
	array('North Lake Michigan','Central Lake Michigan','Yes','No'),
	array('North Lake Michigan','Ontonagon (East Coast)','Yes','No'),
	array('North Lake Michigan','Oshkosh (South Coast)','Yes','No'),
	array('Central Lake Michigan','South Lake Michigan','Yes','No'),
	array('North Lake Huron','South Lake Huron','Yes','No'),
	array('North Lake Huron','Georgian Bay','Yes','No'),
	array('South Lake Huron','Georgian Bay','Yes','No'),
	array('Lake St. Clair','Almina (West Coast)','Yes','No'),
	array('West Lake Erie','East Lake Erie','Yes','No'),
	array('West Lake Erie','Almina (South Coast)','Yes','No'),
	array('East Lake Erie','Almina (South Coast)','Yes','No'),
	array('West Lake Ontario','Central Lake Ontario','Yes','No'),
	array('Central Lake Ontario','East Lake Ontario','Yes','No'),
	array('East Lake Ontario','West St. Lawrence River','Yes','No'),
	array('West St. Lawrence River','East St. Lawrence River','Yes','No'),
	array('Ontonagon (North Coast)','Oshkosh (North Coast)','Yes','No'),
	array('Ontonagon (East Coast)','Oshkosh (South Coast)','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
