<?php
// This file will install the map data for the SouthAmerica8 variant

require_once("variants/install.php");
InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Buenos Aires', 'Coast', 'Yes', 425, 699, 253, 411, 'Argentina'),
	array('Salta', 'Land', 'Yes', 312, 552, 183, 319, 'Argentina'),
	array('Cordoba', 'Land', 'Yes', 315, 685, 188, 402, 'Argentina'),
	array('Patagonia', 'Coast', 'Yes', 342, 871, 208, 507, 'Neutral'),
	array('San Miguel de Tucuman', 'Land', 'Yes', 345, 605, 184, 358, 'Neutral'),
	array('Corrientes', 'Coast', 'Yes', 402, 616, 244, 363, 'Neutral'),
	array('Bahia Blanca', 'Coast', 'No', 386, 765, 239, 436, 'Argentina'),
	array('Rosario', 'Land', 'No', 366, 690, 218, 406, 'Argentina'),
	array('Mendoza', 'Land', 'No', 315, 722, 187, 421, 'Argentina'),
	array('Santa Fe', 'Coast', 'No', 380, 640, 242, 384, 'Argentina'),
	array('Antofagasta', 'Coast', 'Yes', 252, 541, 147, 305, 'Bolivia'),
	array('La Paz', 'Land', 'Yes', 274, 460, 164, 254, 'Bolivia'),
	array('Santa Cruz', 'Land', 'Yes', 350, 457, 203, 248, 'Neutral'),
	array('Potosi', 'Land', 'Yes', 315, 485, 185, 284, 'Neutral'),
	array('Atacama', 'Coast', 'No', 243, 475, 145, 275, 'Bolivia'),
	array('Riberalta', 'Land', 'No', 280, 375, 167, 219, 'Bolivia'),
	array('Slv', 'Coast', 'Yes', 620, 406, 382, 247, 'Brazil'),
	array('Rio de Janeiro', 'Coast', 'Yes', 638, 484, 373, 291, 'Brazil'),
	array('Sao Paulo', 'Coast', 'Yes', 555, 550, 325, 325, 'Brazil'),
	array('Manaus', 'Coast', 'Yes', 383, 270, 227, 147, 'Brazil'),
	array('Maranhao', 'Coast', 'Yes', 552, 226, 326, 137, 'Neutral'),
	array('Rio Grande do Sul', 'Coast', 'Yes', 523, 619, 308, 366, 'Neutral'),
	array('Parana', 'Coast', 'Yes', 504, 570, 298, 332, 'Neutral'),
	array('Aquiris Ingenous Territory', 'Land', 'Yes', 270, 328, 157, 196, 'Neutral'),
	array('Para', 'Coast', 'No', 466, 200, 278, 118, 'Brazil'),
	array('Pernambuco', 'Coast', 'No', 641, 281, 383, 167, 'Brazil'),
	array('Mato Grosso', 'Coast', 'No', 423, 335, 256, 210, 'Brazil'),
	array('Amazonas', 'Coast', 'No', 281, 260, 168, 138, 'Brazil'),
	array('Guapore', 'Coast', 'No', 317, 335, 189, 199, 'Brazil'),
	array('Pantanal', 'Coast', 'No', 450, 490, 265, 282, 'Brazil'),
	array('Rio Branco', 'Land', 'No', 344, 155, 204, 93, 'Brazil'),
	array('Goias', 'Land', 'No', 515, 430, 302, 254, 'Brazil'),
	array('Minas Gerais', 'Land', 'No', 572, 485, 342, 271, 'Brazil'),
	array('Santiago', 'Coast', 'Yes', 266, 724, 157, 423, 'Chile'),
	array('Valparaiso', 'Coast', 'Yes', 265, 681, 153, 391, 'Chile'),
	array('Punta Arenas', 'Coast', 'Yes', 330, 940, 221, 558, 'Neutral'),
	array('Copiapo', 'Coast', 'No', 263, 576, 152, 345, 'Chile'),
	array('Arauncanian Indigenous Territory', 'Coast', 'No', 298, 883, 170, 483, 'Chile'),
	array('Cartagena', 'Coast', 'Yes', 147, 68, 92, 38, 'Colombia'),
	array('Cali', 'Coast', 'Yes', 125, 163, 70, 97, 'Colombia'),
	array('Bogota', 'Land', 'Yes', 195, 120, 110, 68, 'Colombia'),
	array('Panama', 'Coast', 'Yes', 80, 78, 43, 46, 'Neutral'),
	array('Panama (North Coast)', 'Coast', 'No', 82, 64, 63, 33, 'Neutral'),
	array('Panama (South Coast)', 'Coast', 'No', 94, 83, 51, 53, 'Neutral'),
	array('Medellin', 'Coast', 'No', 147, 128, 85, 65, 'Colombia'),
	array('Santa Marta', 'Coast', 'No', 182, 52, 107, 23, 'Colombia'),
	array('Popayan', 'Land', 'No', 199, 185, 116, 102, 'Colombia'),
	array('Llanos', 'Land', 'No', 233, 130, 140, 77, 'Colombia'),
	array('Concepcion', 'Land', 'Yes', 435, 530, 259, 313, 'Paraguay'),
	array('Formosa', 'Land', 'No', 375, 550, 238, 332, 'Paraguay'),
	array('Chaco', 'Land', 'No', 380, 500, 224, 294, 'Paraguay'),
	array('Asuncion', 'Coast', 'Yes', 454, 569, 271, 336, 'Paraguay'),
	array('Misiones', 'Coast', 'No', 455, 624, 277, 356, 'Paraguay'),
	array('Lima', 'Coast', 'Yes', 140, 348, 82, 206, 'Peru'),
	array('Trujillo', 'Coast', 'Yes', 113, 305, 67, 178, 'Peru'),
	array('Iquitos', 'Land', 'Yes', 165, 243, 98, 142, 'Neutral'),
	array('Arica', 'Coast', 'Yes', 222, 435, 134, 262, 'Neutral'),
	array('Arequipa', 'Coast', 'No', 178, 416, 115, 247, 'Peru'),
	array('Piura', 'Coast', 'No', 85, 270, 48, 165, 'Peru'),
	array('Cusco', 'Land', 'No', 208, 359, 123, 211, 'Peru'),
	array('Maracaibo', 'Coast', 'Yes', 224, 63, 134, 40, 'Venezuela'),
	array('Caracas', 'Coast', 'Yes', 279, 52, 165, 29, 'Venezuela'),
	array('Cumana', 'Coast', 'Yes', 342, 56, 202, 33, 'Neutral'),
	array('Angostura', 'Coast', 'Yes', 337, 105, 199, 62, 'Neutral'),
	array('Barinas', 'Land', 'No', 254, 85, 166, 54, 'Venezuela'),
	array('Orinoco', 'Land', 'No', 283, 138, 169, 81, 'Venezuela'),
	array('Veragua', 'Coast', 'No', 30, 43, 17, 25, 'Neutral'),
	array('Veragua (North Coast)', 'Coast', 'No', 58, 56, 27, 18, 'Neutral'),
	array('Veragua (South Coast)', 'Coast', 'No', 19, 52, 12, 30, 'Neutral'),
	array('Quito', 'Coast', 'Yes', 98, 190, 58, 110, 'Neutral'),
	array('Canelos', 'Land', 'No', 138, 207, 79, 131, 'Neutral'),
	array('Guayaquil', 'Coast', 'No', 100, 232, 57, 144, 'Neutral'),
	array('Montevideo', 'Coast', 'Yes', 461, 665, 280, 404, 'Neutral'),
	array('Islas Galapagos', 'Coast', 'Yes', 4, 189, 3, 112, 'Neutral'),
	array('Islas Juan Fernandez', 'Coast', 'Yes', 82, 755, 54, 437, 'Neutral'),
	array('Islas Malvinas', 'Coast', 'Yes', 484, 940, 287, 552, 'Neutral'),
	array('Golfo de Darien', 'Sea', 'No', 140, 30, 100, 13, 'Neutral'),
	array('Golfo de Paria', 'Sea', 'No', 372, 49, 178, 15, 'Neutral'),
	array('Atlantic Ocean', 'Sea', 'No', 625, 115, 363, 59, 'Neutral'),
	array('Boca de Navios', 'Sea', 'No', 522, 134, 309, 85, 'Neutral'),
	array('Bahia Sao Marcos', 'Sea', 'No', 602, 191, 365, 106, 'Neutral'),
	array('Bahia de Todos os Santos', 'Sea', 'No', 716, 463, 414, 296, 'Neutral'),
	array('Bahia de Sao Sebastao', 'Sea', 'No', 600, 565, 358, 326, 'Neutral'),
	array('Bahia de Paranagua', 'Sea', 'No', 600, 660, 379, 378, 'Neutral'),
	array('Rio de la Plata', 'Sea', 'No', 510, 722, 294, 435, 'Neutral'),
	array('South Atlantic Ocean', 'Sea', 'No', 596, 792, 376, 452, 'Neutral'),
	array('Golfo de San Jorge', 'Sea', 'No', 448, 852, 264, 503, 'Neutral'),
	array('Scotia Sea', 'Sea', 'No', 623, 931, 392, 559, 'Neutral'),
	array('Strait of Magellan', 'Sea', 'No', 324, 988, 190, 579, 'Neutral'),
	array('Drake Passage', 'Sea', 'No', 138, 841, 115, 519, 'Neutral'),
	array('Golfo de Guafo', 'Sea', 'No', 136, 645, 105, 380, 'Neutral'),
	array('South Pacific Ocean', 'Sea', 'No', 67, 506, 34, 304, 'Neutral'),
	array('Bahia de Arica', 'Sea', 'No', 153, 471, 82, 262, 'Neutral'),
	array('Nazca Sea', 'Sea', 'No', 47, 300, 27, 191, 'Neutral'),
	array('Bahia Sechura', 'Sea', 'No', 62, 200, 35, 116, 'Neutral'),
	array('Golfo de Panama', 'Sea', 'No', 96, 133, 51, 71, 'Neutral')
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $x, $y, $sx, $sy, $country)=$territoryRawRow;
	if( $country=='Neutral' )
		 $countryID=0;
	else
		 $countryID=$this->countryID($country);
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);		

$bordersRawData=array(
	array('Buenos Aires','Bahia Blanca','Yes','Yes'),
	array('Buenos Aires','Rosario','No','Yes'),
	array('Buenos Aires','Santa Fe','Yes','Yes'),
	array('Buenos Aires','Montevideo','Yes','Yes'),
	array('Buenos Aires','Rio de la Plata','Yes','No'),
	array('Salta','San Miguel de Tucuman','No','Yes'),
	array('Salta','Potosi','No','Yes'),
	array('Salta','Formosa','No','Yes'),
	array('Salta','Chaco','No','Yes'),
	array('Cordoba','San Miguel de Tucuman','No','Yes'),
	array('Cordoba','Rosario','No','Yes'),
	array('Cordoba','Mendoza','No','Yes'),
	array('Cordoba','Santa Fe','No','Yes'),
	array('Patagonia','Bahia Blanca','Yes','Yes'),
	array('Patagonia','Mendoza','No','Yes'),
	array('Patagonia','Punta Arenas','Yes','Yes'),
	array('Patagonia','Arauncanian Indigenous Territory','No','Yes'),
	array('Patagonia','Golfo de San Jorge','Yes','No'),
	array('San Miguel de Tucuman','Salta','No','Yes'),
	array('San Miguel de Tucuman','Cordoba','No','Yes'),
	array('San Miguel de Tucuman','Corrientes','No','Yes'),
	array('San Miguel de Tucuman','Santa Fe','No','Yes'),
	array('San Miguel de Tucuman','Formosa','No','Yes'),
	array('Corrientes','San Miguel de Tucuman','No','Yes'),
	array('Corrientes','Santa Fe','Yes','Yes'),
	array('Corrientes','Formosa','No','Yes'),
	array('Corrientes','Asuncion','Yes','Yes'),
	array('Corrientes','Misiones','Yes','Yes'),
	array('Bahia Blanca','Buenos Aires','Yes','Yes'),
	array('Bahia Blanca','Patagonia','Yes','Yes'),
	array('Bahia Blanca','Rosario','No','Yes'),
	array('Bahia Blanca','Mendoza','No','Yes'),
	array('Bahia Blanca','Rio de la Plata','Yes','No'),
	array('Bahia Blanca','Golfo de San Jorge','Yes','No'),
	array('Rosario','Buenos Aires','No','Yes'),
	array('Rosario','Cordoba','No','Yes'),
	array('Rosario','Bahia Blanca','No','Yes'),
	array('Rosario','Mendoza','No','Yes'),
	array('Rosario','Santa Fe','No','Yes'),
	array('Mendoza','Cordoba','No','Yes'),
	array('Mendoza','Patagonia','No','Yes'),
	array('Mendoza','Bahia Blanca','No','Yes'),
	array('Mendoza','Rosario','No','Yes'),
	array('Mendoza','Santiago','No','Yes'),
	array('Santa Fe','Buenos Aires','Yes','Yes'),
	array('Santa Fe','Cordoba','No','Yes'),
	array('Santa Fe','San Miguel de Tucuman','No','Yes'),
	array('Santa Fe','Corrientes','Yes','Yes'),
	array('Santa Fe','Rosario','No','Yes'),
	array('Santa Fe','Misiones','Yes','Yes'),
	array('Santa Fe','Montevideo','Yes','Yes'),
	array('Antofagasta','Potosi','No','Yes'),
	array('Antofagasta','Atacama','Yes','Yes'),
	array('Antofagasta','Copiapo','Yes','Yes'),
	array('Antofagasta','Golfo de Guafo','Yes','No'),
	array('Antofagasta','Bahia de Arica','Yes','No'),
	array('La Paz','Santa Cruz','No','Yes'),
	array('La Paz','Potosi','No','Yes'),
	array('La Paz','Riberalta','No','Yes'),
	array('La Paz','Cusco','No','Yes'),
	array('Santa Cruz','La Paz','No','Yes'),
	array('Santa Cruz','Potosi','No','Yes'),
	array('Santa Cruz','Riberalta','No','Yes'),
	array('Santa Cruz','Mato Grosso','No','Yes'),
	array('Santa Cruz','Guapore','No','Yes'),
	array('Santa Cruz','Pantanal','No','Yes'),
	array('Santa Cruz','Chaco','No','Yes'),
	array('Potosi','Salta','No','Yes'),
	array('Potosi','Antofagasta','No','Yes'),
	array('Potosi','La Paz','No','Yes'),
	array('Potosi','Santa Cruz','No','Yes'),
	array('Potosi','Chaco','No','Yes'),
	array('Atacama','Antofagasta','Yes','Yes'),
	array('Atacama','Arica','Yes','Yes'),
	array('Atacama','Bahia de Arica','Yes','No'),
	array('Riberalta','La Paz','No','Yes'),
	array('Riberalta','Santa Cruz','No','Yes'),
	array('Riberalta','Aquiris Ingenous Territory','No','Yes'),
	array('Riberalta','Guapore','No','Yes'),
	array('Riberalta','Cusco','No','Yes'),
	array('Slv','Rio de Janeiro','Yes','Yes'),
	array('Slv','Pernambuco','Yes','Yes'),
	array('Slv','Goias','No','Yes'),
	array('Slv','Minas Gerais','No','Yes'),
	array('Slv','Bahia Sao Marcos','Yes','No'),
	array('Slv','Bahia de Todos os Santos','Yes','No'),
	array('Rio de Janeiro','Slv','Yes','Yes'),
	array('Rio de Janeiro','Sao Paulo','Yes','Yes'),
	array('Rio de Janeiro','Minas Gerais','No','Yes'),
	array('Rio de Janeiro','Bahia de Todos os Santos','Yes','No'),
	array('Rio de Janeiro','Bahia de Sao Sebastao','Yes','No'),
	array('Sao Paulo','Rio de Janeiro','Yes','Yes'),
	array('Sao Paulo','Rio Grande do Sul','Yes','Yes'),
	array('Sao Paulo','Parana','No','Yes'),
	array('Sao Paulo','Pantanal','No','Yes'),
	array('Sao Paulo','Goias','No','Yes'),
	array('Sao Paulo','Minas Gerais','No','Yes'),
	array('Sao Paulo','Bahia de Sao Sebastao','Yes','No'),
	array('Manaus','Para','Yes','Yes'),
	array('Manaus','Mato Grosso','Yes','Yes'),
	array('Manaus','Amazonas','Yes','Yes'),
	array('Manaus','Rio Branco','No','Yes'),
	array('Maranhao','Para','Yes','Yes'),
	array('Maranhao','Pernambuco','Yes','Yes'),
	array('Maranhao','Mato Grosso','Yes','Yes'),
	array('Maranhao','Goias','No','Yes'),
	array('Maranhao','Boca de Navios','Yes','No'),
	array('Maranhao','Bahia Sao Marcos','Yes','No'),
	array('Rio Grande do Sul','Sao Paulo','Yes','Yes'),
	array('Rio Grande do Sul','Parana','No','Yes'),
	array('Rio Grande do Sul','Misiones','No','Yes'),
	array('Rio Grande do Sul','Montevideo','Yes','Yes'),
	array('Rio Grande do Sul','Bahia de Sao Sebastao','Yes','No'),
	array('Rio Grande do Sul','Bahia de Paranagua','Yes','No'),
	array('Rio Grande do Sul','Rio de la Plata','Yes','No'),
	array('Parana','Sao Paulo','No','Yes'),
	array('Parana','Rio Grande do Sul','No','Yes'),
	array('Parana','Pantanal','Yes','Yes'),
	array('Parana','Asuncion','Yes','Yes'),
	array('Parana','Misiones','Yes','Yes'),
	array('Aquiris Ingenous Territory','Riberalta','No','Yes'),
	array('Aquiris Ingenous Territory','Amazonas','No','Yes'),
	array('Aquiris Ingenous Territory','Guapore','No','Yes'),
	array('Aquiris Ingenous Territory','Iquitos','No','Yes'),
	array('Aquiris Ingenous Territory','Cusco','No','Yes'),
	array('Para','Manaus','Yes','Yes'),
	array('Para','Maranhao','Yes','Yes'),
	array('Para','Mato Grosso','Yes','Yes'),
	array('Para','Rio Branco','No','Yes'),
	array('Para','Boca de Navios','Yes','No'),
	array('Pernambuco','Slv','Yes','Yes'),
	array('Pernambuco','Maranhao','Yes','Yes'),
	array('Pernambuco','Goias','No','Yes'),
	array('Pernambuco','Bahia Sao Marcos','Yes','No'),
	array('Mato Grosso','Santa Cruz','No','Yes'),
	array('Mato Grosso','Manaus','Yes','Yes'),
	array('Mato Grosso','Maranhao','Yes','Yes'),
	array('Mato Grosso','Para','Yes','Yes'),
	array('Mato Grosso','Amazonas','Yes','Yes'),
	array('Mato Grosso','Guapore','Yes','Yes'),
	array('Mato Grosso','Pantanal','No','Yes'),
	array('Mato Grosso','Goias','No','Yes'),
	array('Amazonas','Manaus','Yes','Yes'),
	array('Amazonas','Aquiris Ingenous Territory','No','Yes'),
	array('Amazonas','Mato Grosso','Yes','Yes'),
	array('Amazonas','Guapore','Yes','Yes'),
	array('Amazonas','Rio Branco','No','Yes'),
	array('Amazonas','Popayan','No','Yes'),
	array('Amazonas','Llanos','No','Yes'),
	array('Amazonas','Iquitos','No','Yes'),
	array('Amazonas','Orinoco','No','Yes'),
	array('Guapore','Santa Cruz','No','Yes'),
	array('Guapore','Riberalta','No','Yes'),
	array('Guapore','Aquiris Ingenous Territory','No','Yes'),
	array('Guapore','Mato Grosso','Yes','Yes'),
	array('Guapore','Amazonas','Yes','Yes'),
	array('Pantanal','Santa Cruz','No','Yes'),
	array('Pantanal','Sao Paulo','No','Yes'),
	array('Pantanal','Parana','Yes','Yes'),
	array('Pantanal','Mato Grosso','No','Yes'),
	array('Pantanal','Goias','No','Yes'),
	array('Pantanal','Concepcion','No','Yes'),
	array('Pantanal','Chaco','No','Yes'),
	array('Pantanal','Asuncion','Yes','Yes'),
	array('Rio Branco','Manaus','No','Yes'),
	array('Rio Branco','Para','No','Yes'),
	array('Rio Branco','Amazonas','No','Yes'),
	array('Rio Branco','Angostura','No','Yes'),
	array('Rio Branco','Orinoco','No','Yes'),
	array('Goias','Slv','No','Yes'),
	array('Goias','Sao Paulo','No','Yes'),
	array('Goias','Maranhao','No','Yes'),
	array('Goias','Pernambuco','No','Yes'),
	array('Goias','Mato Grosso','No','Yes'),
	array('Goias','Pantanal','No','Yes'),
	array('Goias','Minas Gerais','No','Yes'),
	array('Minas Gerais','Slv','No','Yes'),
	array('Minas Gerais','Rio de Janeiro','No','Yes'),
	array('Minas Gerais','Sao Paulo','No','Yes'),
	array('Minas Gerais','Goias','No','Yes'),
	array('Santiago','Mendoza','No','Yes'),
	array('Santiago','Valparaiso','Yes','Yes'),
	array('Santiago','Arauncanian Indigenous Territory','Yes','Yes'),
	array('Santiago','Drake Passage','Yes','No'),
	array('Valparaiso','Santiago','Yes','Yes'),
	array('Valparaiso','Copiapo','Yes','Yes'),
	array('Valparaiso','Drake Passage','Yes','No'),
	array('Valparaiso','Golfo de Guafo','Yes','No'),
	array('Punta Arenas','Patagonia','Yes','Yes'),
	array('Punta Arenas','Arauncanian Indigenous Territory','Yes','Yes'),
	array('Punta Arenas','Golfo de San Jorge','Yes','No'),
	array('Punta Arenas','Strait of Magellan','Yes','No'),
	array('Punta Arenas','Drake Passage','Yes','No'),
	array('Copiapo','Antofagasta','Yes','Yes'),
	array('Copiapo','Valparaiso','Yes','Yes'),
	array('Copiapo','Golfo de Guafo','Yes','No'),
	array('Arauncanian Indigenous Territory','Patagonia','No','Yes'),
	array('Arauncanian Indigenous Territory','Santiago','Yes','Yes'),
	array('Arauncanian Indigenous Territory','Punta Arenas','Yes','Yes'),
	array('Arauncanian Indigenous Territory','Drake Passage','Yes','No'),
	array('Cartagena','Bogota','No','Yes'),
	array('Cartagena','Panama','No','Yes'),
	array('Cartagena','Panama (North Coast)','Yes','No'),
	array('Cartagena','Medellin','No','Yes'),
	array('Cartagena','Santa Marta','Yes','Yes'),
	array('Cartagena','Golfo de Darien','Yes','No'),
	array('Cali','Bogota','No','Yes'),
	array('Cali','Medellin','Yes','Yes'),
	array('Cali','Quito','Yes','Yes'),
	array('Cali','Canelos','No','Yes'),
	array('Cali','Bahia Sechura','Yes','No'),
	array('Cali','Golfo de Panama','Yes','No'),
	array('Bogota','Cartagena','No','Yes'),
	array('Bogota','Cali','No','Yes'),
	array('Bogota','Medellin','No','Yes'),
	array('Bogota','Santa Marta','No','Yes'),
	array('Bogota','Popayan','No','Yes'),
	array('Bogota','Llanos','No','Yes'),
	array('Panama','Cartagena','No','Yes'),
	array('Panama','Medellin','No','Yes'),
	array('Panama','Veragua','No','Yes'),
	array('Panama (North Coast)','Cartagena','Yes','No'),
	array('Panama (North Coast)','Veragua (North Coast)','Yes','No'),
	array('Panama (North Coast)','Golfo de Darien','Yes','No'),
	array('Panama (South Coast)','Medellin','Yes','No'),
	array('Panama (South Coast)','Veragua (South Coast)','Yes','No'),
	array('Panama (South Coast)','Golfo de Panama','Yes','No'),
	array('Medellin','Cartagena','No','Yes'),
	array('Medellin','Cali','Yes','Yes'),
	array('Medellin','Bogota','No','Yes'),
	array('Medellin','Panama','No','Yes'),
	array('Medellin','Panama (South Coast)','Yes','No'),
	array('Medellin','Golfo de Panama','Yes','No'),
	array('Santa Marta','Cartagena','Yes','Yes'),
	array('Santa Marta','Bogota','No','Yes'),
	array('Santa Marta','Llanos','No','Yes'),
	array('Santa Marta','Maracaibo','Yes','Yes'),
	array('Santa Marta','Golfo de Darien','Yes','No'),
	array('Popayan','Amazonas','No','Yes'),
	array('Popayan','Bogota','No','Yes'),
	array('Popayan','Llanos','No','Yes'),
	array('Popayan','Iquitos','No','Yes'),
	array('Popayan','Canelos','No','Yes'),
	array('Llanos','Amazonas','No','Yes'),
	array('Llanos','Bogota','No','Yes'),
	array('Llanos','Santa Marta','No','Yes'),
	array('Llanos','Popayan','No','Yes'),
	array('Llanos','Maracaibo','No','Yes'),
	array('Llanos','Barinas','No','Yes'),
	array('Llanos','Orinoco','No','Yes'),
	array('Concepcion','Pantanal','No','Yes'),
	array('Concepcion','Formosa','No','Yes'),
	array('Concepcion','Chaco','No','Yes'),
	array('Concepcion','Asuncion','No','Yes'),
	array('Formosa','Salta','No','Yes'),
	array('Formosa','San Miguel de Tucuman','No','Yes'),
	array('Formosa','Corrientes','No','Yes'),
	array('Formosa','Concepcion','No','Yes'),
	array('Formosa','Chaco','No','Yes'),
	array('Formosa','Asuncion','No','Yes'),
	array('Chaco','Salta','No','Yes'),
	array('Chaco','Santa Cruz','No','Yes'),
	array('Chaco','Potosi','No','Yes'),
	array('Chaco','Pantanal','No','Yes'),
	array('Chaco','Concepcion','No','Yes'),
	array('Chaco','Formosa','No','Yes'),
	array('Asuncion','Corrientes','Yes','Yes'),
	array('Asuncion','Parana','Yes','Yes'),
	array('Asuncion','Pantanal','Yes','Yes'),
	array('Asuncion','Concepcion','No','Yes'),
	array('Asuncion','Formosa','No','Yes'),
	array('Asuncion','Misiones','Yes','Yes'),
	array('Misiones','Corrientes','Yes','Yes'),
	array('Misiones','Santa Fe','Yes','Yes'),
	array('Misiones','Rio Grande do Sul','No','Yes'),
	array('Misiones','Parana','Yes','Yes'),
	array('Misiones','Asuncion','Yes','Yes'),
	array('Misiones','Montevideo','Yes','Yes'),
	array('Lima','Trujillo','Yes','Yes'),
	array('Lima','Arequipa','Yes','Yes'),
	array('Lima','Cusco','No','Yes'),
	array('Lima','Bahia de Arica','Yes','No'),
	array('Lima','Nazca Sea','Yes','No'),
	array('Trujillo','Lima','Yes','Yes'),
	array('Trujillo','Iquitos','No','Yes'),
	array('Trujillo','Piura','Yes','Yes'),
	array('Trujillo','Nazca Sea','Yes','No'),
	array('Iquitos','Aquiris Ingenous Territory','No','Yes'),
	array('Iquitos','Amazonas','No','Yes'),
	array('Iquitos','Popayan','No','Yes'),
	array('Iquitos','Trujillo','No','Yes'),
	array('Iquitos','Cusco','No','Yes'),
	array('Iquitos','Canelos','No','Yes'),
	array('Arica','Atacama','Yes','Yes'),
	array('Arica','Arequipa','Yes','Yes'),
	array('Arica','Bahia de Arica','Yes','No'),
	array('Arequipa','Lima','Yes','Yes'),
	array('Arequipa','Arica','Yes','Yes'),
	array('Arequipa','Bahia de Arica','Yes','No'),
	array('Piura','Trujillo','Yes','Yes'),
	array('Piura','Guayaquil','Yes','Yes'),
	array('Piura','Nazca Sea','Yes','No'),
	array('Piura','Bahia Sechura','Yes','No'),
	array('Cusco','La Paz','No','Yes'),
	array('Cusco','Riberalta','No','Yes'),
	array('Cusco','Aquiris Ingenous Territory','No','Yes'),
	array('Cusco','Lima','No','Yes'),
	array('Cusco','Iquitos','No','Yes'),
	array('Maracaibo','Santa Marta','Yes','Yes'),
	array('Maracaibo','Llanos','No','Yes'),
	array('Maracaibo','Caracas','Yes','Yes'),
	array('Maracaibo','Barinas','No','Yes'),
	array('Maracaibo','Golfo de Darien','Yes','No'),
	array('Caracas','Maracaibo','Yes','Yes'),
	array('Caracas','Cumana','Yes','Yes'),
	array('Caracas','Angostura','No','Yes'),
	array('Caracas','Barinas','No','Yes'),
	array('Caracas','Golfo de Darien','Yes','No'),
	array('Caracas','Golfo de Paria','Yes','No'),
	array('Cumana','Caracas','Yes','Yes'),
	array('Cumana','Angostura','Yes','Yes'),
	array('Cumana','Golfo de Paria','Yes','No'),
	array('Angostura','Rio Branco','No','Yes'),
	array('Angostura','Caracas','No','Yes'),
	array('Angostura','Cumana','Yes','Yes'),
	array('Angostura','Barinas','No','Yes'),
	array('Angostura','Orinoco','No','Yes'),
	array('Angostura','Golfo de Paria','Yes','No'),
	array('Angostura','Boca de Navios','Yes','No'),
	array('Barinas','Llanos','No','Yes'),
	array('Barinas','Maracaibo','No','Yes'),
	array('Barinas','Caracas','No','Yes'),
	array('Barinas','Angostura','No','Yes'),
	array('Barinas','Orinoco','No','Yes'),
	array('Orinoco','Amazonas','No','Yes'),
	array('Orinoco','Rio Branco','No','Yes'),
	array('Orinoco','Llanos','No','Yes'),
	array('Orinoco','Angostura','No','Yes'),
	array('Orinoco','Barinas','No','Yes'),
	array('Veragua','Panama','No','Yes'),
	array('Veragua (North Coast)','Panama (North Coast)','Yes','No'),
	array('Veragua (North Coast)','Golfo de Darien','Yes','No'),
	array('Veragua (South Coast)','Panama (South Coast)','Yes','No'),
	array('Veragua (South Coast)','Golfo de Panama','Yes','No'),
	array('Quito','Cali','Yes','Yes'),
	array('Quito','Guayaquil','Yes','Yes'),
	array('Quito','Bahia Sechura','Yes','No'),
	array('Canelos','Cali','No','Yes'),
	array('Canelos','Popayan','No','Yes'),
	array('Canelos','Iquitos','No','Yes'),
	array('Canelos','Guayaquil','No','Yes'),
	array('Guayaquil','Piura','Yes','Yes'),
	array('Guayaquil','Quito','Yes','Yes'),
	array('Guayaquil','Canelos','No','Yes'),
	array('Guayaquil','Bahia Sechura','Yes','No'),
	array('Montevideo','Buenos Aires','Yes','Yes'),
	array('Montevideo','Santa Fe','Yes','Yes'),
	array('Montevideo','Rio Grande do Sul','Yes','Yes'),
	array('Montevideo','Misiones','Yes','Yes'),
	array('Montevideo','Rio de la Plata','Yes','No'),
	array('Islas Galapagos','Nazca Sea','Yes','No'),
	array('Islas Galapagos','Bahia Sechura','Yes','No'),
	array('Islas Galapagos','Golfo de Panama','Yes','No'),
	array('Islas Juan Fernandez','Drake Passage','Yes','No'),
	array('Islas Juan Fernandez','Golfo de Guafo','Yes','No'),
	array('Islas Malvinas','Golfo de San Jorge','Yes','No'),
	array('Islas Malvinas','Scotia Sea','Yes','No'),
	array('Golfo de Darien','Cartagena','Yes','No'),
	array('Golfo de Darien','Panama (North Coast)','Yes','No'),
	array('Golfo de Darien','Santa Marta','Yes','No'),
	array('Golfo de Darien','Maracaibo','Yes','No'),
	array('Golfo de Darien','Caracas','Yes','No'),
	array('Golfo de Darien','Veragua (North Coast)','Yes','No'),
	array('Golfo de Darien','Golfo de Paria','Yes','No'),
	array('Golfo de Paria','Caracas','Yes','No'),
	array('Golfo de Paria','Cumana','Yes','No'),
	array('Golfo de Paria','Angostura','Yes','No'),
	array('Golfo de Paria','Golfo de Darien','Yes','No'),
	array('Golfo de Paria','Atlantic Ocean','Yes','No'),
	array('Golfo de Paria','Boca de Navios','Yes','No'),
	array('Atlantic Ocean','Golfo de Paria','Yes','No'),
	array('Atlantic Ocean','Boca de Navios','Yes','No'),
	array('Atlantic Ocean','Bahia Sao Marcos','Yes','No'),
	array('Boca de Navios','Maranhao','Yes','No'),
	array('Boca de Navios','Para','Yes','No'),
	array('Boca de Navios','Angostura','Yes','No'),
	array('Boca de Navios','Golfo de Paria','Yes','No'),
	array('Boca de Navios','Atlantic Ocean','Yes','No'),
	array('Boca de Navios','Bahia Sao Marcos','Yes','No'),
	array('Bahia Sao Marcos','Slv','Yes','No'),
	array('Bahia Sao Marcos','Maranhao','Yes','No'),
	array('Bahia Sao Marcos','Pernambuco','Yes','No'),
	array('Bahia Sao Marcos','Atlantic Ocean','Yes','No'),
	array('Bahia Sao Marcos','Boca de Navios','Yes','No'),
	array('Bahia Sao Marcos','Bahia de Todos os Santos','Yes','No'),
	array('Bahia de Todos os Santos','Slv','Yes','No'),
	array('Bahia de Todos os Santos','Rio de Janeiro','Yes','No'),
	array('Bahia de Todos os Santos','Bahia Sao Marcos','Yes','No'),
	array('Bahia de Todos os Santos','Bahia de Sao Sebastao','Yes','No'),
	array('Bahia de Todos os Santos','Bahia de Paranagua','Yes','No'),
	array('Bahia de Sao Sebastao','Rio de Janeiro','Yes','No'),
	array('Bahia de Sao Sebastao','Sao Paulo','Yes','No'),
	array('Bahia de Sao Sebastao','Rio Grande do Sul','Yes','No'),
	array('Bahia de Sao Sebastao','Bahia de Todos os Santos','Yes','No'),
	array('Bahia de Sao Sebastao','Bahia de Paranagua','Yes','No'),
	array('Bahia de Paranagua','Rio Grande do Sul','Yes','No'),
	array('Bahia de Paranagua','Bahia de Todos os Santos','Yes','No'),
	array('Bahia de Paranagua','Bahia de Sao Sebastao','Yes','No'),
	array('Bahia de Paranagua','Rio de la Plata','Yes','No'),
	array('Bahia de Paranagua','South Atlantic Ocean','Yes','No'),
	array('Rio de la Plata','Buenos Aires','Yes','No'),
	array('Rio de la Plata','Bahia Blanca','Yes','No'),
	array('Rio de la Plata','Rio Grande do Sul','Yes','No'),
	array('Rio de la Plata','Montevideo','Yes','No'),
	array('Rio de la Plata','Bahia de Paranagua','Yes','No'),
	array('Rio de la Plata','South Atlantic Ocean','Yes','No'),
	array('Rio de la Plata','Golfo de San Jorge','Yes','No'),
	array('South Atlantic Ocean','Bahia de Paranagua','Yes','No'),
	array('South Atlantic Ocean','Rio de la Plata','Yes','No'),
	array('South Atlantic Ocean','Golfo de San Jorge','Yes','No'),
	array('South Atlantic Ocean','Scotia Sea','Yes','No'),
	array('Golfo de San Jorge','Patagonia','Yes','No'),
	array('Golfo de San Jorge','Bahia Blanca','Yes','No'),
	array('Golfo de San Jorge','Punta Arenas','Yes','No'),
	array('Golfo de San Jorge','Islas Malvinas','Yes','No'),
	array('Golfo de San Jorge','Rio de la Plata','Yes','No'),
	array('Golfo de San Jorge','South Atlantic Ocean','Yes','No'),
	array('Golfo de San Jorge','Scotia Sea','Yes','No'),
	array('Golfo de San Jorge','Strait of Magellan','Yes','No'),
	array('Scotia Sea','Islas Malvinas','Yes','No'),
	array('Scotia Sea','South Atlantic Ocean','Yes','No'),
	array('Scotia Sea','Golfo de San Jorge','Yes','No'),
	array('Scotia Sea','Strait of Magellan','Yes','No'),
	array('Strait of Magellan','Punta Arenas','Yes','No'),
	array('Strait of Magellan','Golfo de San Jorge','Yes','No'),
	array('Strait of Magellan','Scotia Sea','Yes','No'),
	array('Strait of Magellan','Drake Passage','Yes','No'),
	array('Drake Passage','Santiago','Yes','No'),
	array('Drake Passage','Valparaiso','Yes','No'),
	array('Drake Passage','Punta Arenas','Yes','No'),
	array('Drake Passage','Arauncanian Indigenous Territory','Yes','No'),
	array('Drake Passage','Islas Juan Fernandez','Yes','No'),
	array('Drake Passage','Strait of Magellan','Yes','No'),
	array('Drake Passage','Golfo de Guafo','Yes','No'),
	array('Golfo de Guafo','Antofagasta','Yes','No'),
	array('Golfo de Guafo','Valparaiso','Yes','No'),
	array('Golfo de Guafo','Copiapo','Yes','No'),
	array('Golfo de Guafo','Islas Juan Fernandez','Yes','No'),
	array('Golfo de Guafo','Drake Passage','Yes','No'),
	array('Golfo de Guafo','South Pacific Ocean','Yes','No'),
	array('Golfo de Guafo','Bahia de Arica','Yes','No'),
	array('South Pacific Ocean','Golfo de Guafo','Yes','No'),
	array('South Pacific Ocean','Bahia de Arica','Yes','No'),
	array('South Pacific Ocean','Nazca Sea','Yes','No'),
	array('Bahia de Arica','Antofagasta','Yes','No'),
	array('Bahia de Arica','Atacama','Yes','No'),
	array('Bahia de Arica','Lima','Yes','No'),
	array('Bahia de Arica','Arica','Yes','No'),
	array('Bahia de Arica','Arequipa','Yes','No'),
	array('Bahia de Arica','Golfo de Guafo','Yes','No'),
	array('Bahia de Arica','South Pacific Ocean','Yes','No'),
	array('Bahia de Arica','Nazca Sea','Yes','No'),
	array('Nazca Sea','Lima','Yes','No'),
	array('Nazca Sea','Trujillo','Yes','No'),
	array('Nazca Sea','Piura','Yes','No'),
	array('Nazca Sea','Islas Galapagos','Yes','No'),
	array('Nazca Sea','South Pacific Ocean','Yes','No'),
	array('Nazca Sea','Bahia de Arica','Yes','No'),
	array('Nazca Sea','Bahia Sechura','Yes','No'),
	array('Bahia Sechura','Cali','Yes','No'),
	array('Bahia Sechura','Piura','Yes','No'),
	array('Bahia Sechura','Quito','Yes','No'),
	array('Bahia Sechura','Guayaquil','Yes','No'),
	array('Bahia Sechura','Islas Galapagos','Yes','No'),
	array('Bahia Sechura','Nazca Sea','Yes','No'),
	array('Bahia Sechura','Golfo de Panama','Yes','No'),
	array('Golfo de Panama','Cali','Yes','No'),
	array('Golfo de Panama','Panama (South Coast)','Yes','No'),
	array('Golfo de Panama','Medellin','Yes','No'),
	array('Golfo de Panama','Veragua (South Coast)','Yes','No'),
	array('Golfo de Panama','Islas Galapagos','Yes','No'),
	array('Golfo de Panama','Bahia Sechura','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	 list($from, $to, $fleets, $armies)=$borderRawRow;
	 InstallTerritory::$Territories[$from]->addBorder(InstallTerritory::$Territories[$to]  ,$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
